### ISSUE TITLE
Integration mode: import filters to desktop AG user filter

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#10]
Steps to reproduce:
1. Install AG for Windows and AG browser add-on
2. Go to https://youtube.adblockplus.me/en/
3. Press "Add filter"
4. Rule will be added to add-on's user filter

In integration mode rules should be added to desktop AG user filter

**Comment by atropnikov** [comment]
Unfortunately, we cannot do it now, because every added rule triggers notification from the desktop application. We should provide the method for adding the list of rules in new integration API.
#190
