### ISSUE TITLE
Acceptable ads not being blocked in Palemoon 26

### ISSUE THREAD

**Issue by gshumihin** [AdguardTeam/AdguardBrowserExtension#100]
Tested with 2.0.21 beta build

**Comment by Mizzick** [comment]
I can see this issue with the latest FF 46 also.

**Comment by Mizzick** [comment]
@Alex-302 Please take a look

**Comment by Alex-302** [comment]
@Mizzick 
it is clean with FF 46.0 and extension 2.2.3
http://imagizer.imageshack.com/img922/1012/74PCh9.png
but I can't check it on Palemoon, because can't install extension(legacy version).

**Comment by Mizzick** [comment]
https://www.dropbox.com/s/7t4fmpipj32gq42/Screenshot%202016-05-04%2022.42.17.png?dl=0

**Comment by Mizzick** [comment]
Works fine with FF 46.0.1
