### ISSUE TITLE
JS rules don't work on xda-developers.com in Firefox

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/AdguardBrowserExtension#1004]
### Steps to reproduce

1. Add this rule to user filter - `xda-developers.com#%#console.log("Test");`
2. Go here - https://www.xda-developers.com/

### Expected behavior

JS rules should work
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/38927121-0e6ca314-4305-11e8-8bc9-4f1f990d4902.png)

</details>

### Actual behavior

JS rules don't work

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29142494/38927139-1ebfe582-4305-11e8-9fe7-f84e22780d33.png)

</details>
<br>

It's probably due to rules like these:
`$webrtc,domain=xda-developers.com`
`$websocket,domain=xda-developers.com`

### Your environment

* AdGuard AdBlocker extension version: 2.9.2
* Environment name and version: Firefox 59.0.2
* Filters you use in AdGuard: English
* Any other browser extensions you have installed: -

**Comment by BlazDT** [comment]
Site seems to override something and sets some cookies with "_conv_". When those cookies are present, javascript rules seem to non-working anymore. On clean visit the following rule works fine, when waiting a bit and then changing to another article, it reads those cookies and is messing with our javascript rules:

xda-developers.com#%#window.alert("Hello");
