### ISSUE TITLE
Filters settings

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#1007]
Filters must be divided into 7 groups (just like it's done here):
https://github.com/AdguardTeam/FiltersRegistry/pull/43

* Ad Blocking
* Privacy
* Social Widgets
* Annoyances
* Security
* Other
* Language-specific

Criteria:
1. **Filter cannot be in two groups at the same moment**. If a filter is placed in one group, it cannot be placed to another.
2. First of all, filters marked with `lang:` go to `Language-specific`
3. Then take all filters left with `purpose:ads` and place them to "Ad Blocking"
4. etc, etc.

Also, there is a "Custom" group, there will be subscriptions added by URL.

**Comment by Mizzick** [comment]
@ameshkov regarding criteria, do you mean to pick filters by tags to new groups? 
Why don't we just use groupId from metadata?

**Comment by ameshkov** [comment]
> Why don't we just use groupId from metadata?

they are not yet ready so stick to picking by tags but mark it as temporary

**Comment by ameshkov** [comment]
One more UI improvement is required:
https://uploads.adguard.com/up04_crlz0_filters.sketch.png

https://www.dropbox.com/s/t7mu6h6j94aovg7/filters.sketch?dl=0
