### ISSUE TITLE
Chrome Extension - ext-CSS not always applied

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/AdguardBrowserExtension#1009]
When opening this amazon page, ext-CSS is applied as it should:

https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.amazon.de%2Fs%2Fref%3Dsr_pg_2%3Frh%3Dn%253A12950651%252Cn%253A359480031%252Ck%253Agummiball%26page%3D2%26keywords%3Dgummiball%26ie%3DUTF8%26qid%3D1524679180

When changing to the next page of results, it is not applied anymore:

amazon.de,amazon.com,amazon.co.uk,amazon.fr,amazon.it,amazon.es##.s-result-list > .s-result-item[-ext-has='span[data-a-popover*="sponsored-header"]']

The same rule works fine in AdGuard for Windows which both are using ext-CSS 1.10.

https://github.com/AdguardTeam/AdguardFilters/issues/15294

**Comment by BlazDT** [comment]
@vozersky and @maximtop 
Could you please check if Extension is applying the ext-CSS rule (without redefining inisStick on that site):

https://github.com/AdguardTeam/AdguardFilters/issues/17436#issuecomment-397898003

**Comment by ameshkov** [comment]
@BlazDT talking about this rule?
`3movs.com###side_col_video_view > div.section:has(> div.block_header_side > h4:contains(Advertisement))`

**Comment by BlazDT** [comment]
Yes, any ext-css rule which targets that div.section.

**Comment by maximtop** [comment]
@BlazDT 
```3movs.com###side_col_video_view > div.section:has(> div.block_header_side > h4:contains(Advertisement))```
this rule is applying correctly in the new version of extension

**Comment by BlazDT** [comment]
Good :)
Please close the issue when new version is public beta.
