### ISSUE TITLE
[request] Add EasyList without element hiding

### ISSUE THREAD

**Issue by nhantrn** [AdguardTeam/AdguardBrowserExtension#101]
Hi,
I notice there is no **EasyList without element hiding** in adguard. Please add it.
The source is on EasyList site. Direct link here:

https://easylist-downloads.adblockplus.org/easylist_noelemhide.txt

**Comment by ameshkov** [comment]
We'll add it, thank you!

**Comment by ameshkov** [comment]
Let's wait until we add an option to add custom filter subscriptions by URL.
So you'll be able to add this subscription manually.

**Comment by ameshkov** [comment]
@ankushg now it is:)
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/212

**Comment by ameshkov** [comment]
Dup
