### ISSUE TITLE
How do I subscribe to a custom url?

### ISSUE THREAD

**Issue by T-baby** [AdguardTeam/AdguardBrowserExtension#1013]
How do I subscribe to a custom url? How should I configure it? Thank you!

**Comment by vozersky** [comment]
@T-baby hi! Custom subscriptions are going to be available in the coming v.3.0. Currently, you can only import custom rules to User Filter, so you will have to save all the rules from the custom filter you want to use into .txt file and import it.

**Comment by T-baby** [comment]
When will version 3.0 be released?
