### ISSUE TITLE
WebSocket requests are not visible in Edge extension

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1014]
### Steps to reproduce

1. Disable English filter end enable Esylist or add `$websocket,domain=lib.rus.ec,badfilter`
2. Open filtering log
3. Go to http://lib.rus.ec/new
4. Try to find websockets in the log.

### Actual behavior
WS requests are not displayed.

<details><summary>Screenshot:</summary>

![image](http://ipic.su/img/img7/fs/kiss_350kb.1525677454.jpg)

</details>

### Your environment

* AdGuard AdBlocker extension version: from MS Store
* Environment name and version: Edge 41.16299.248.0
* Filters you use in AdGuard: Rus, Eng
* Any other browser extensions you have installed: none.

**Comment by maximtop** [comment]
To check if this issue was resolved. 
1. Install Adguard Extension for Edge
2. go to https://www.websocket.org/echo.html
3. open filtering log, refresh
4. view if there are WebSocket requests in the log
