### ISSUE TITLE
Compatibility issue with Disconnect

### ISSUE THREAD

**Issue by kwstas86** [AdguardTeam/AdguardBrowserExtension#1020]
![adguard error](https://user-images.githubusercontent.com/12601176/40277168-7bc6ba1c-5c23-11e8-9f0e-4c58c55b1378.png)

### Steps to reproduce

1. Can't remember my exact actions to reproduce it, happened 3 - 4 times.

### Your environment

* AdGuard AdBlocker extension version:

![adguard version](https://user-images.githubusercontent.com/12601176/40277279-cab88550-5c24-11e8-85ec-c1cf4f89f1ad.png)
 
* Environment name and version: (e.g. Chrome 59.0.3071.115)

![chrome version](https://user-images.githubusercontent.com/12601176/40277192-aaabe136-5c23-11e8-90b5-3ea3a1cefb00.png)

* Filters you use in AdGuard:

![adguard settings](https://user-images.githubusercontent.com/12601176/40277194-b6842edc-5c23-11e8-9695-fe46b343317f.png)

![adguard user filter](https://user-images.githubusercontent.com/12601176/40277196-bd138b76-5c23-11e8-8293-6a9d8bb9e9aa.png)

* Any other browser extensions you have installed:

![other extensions](https://user-images.githubusercontent.com/12601176/40277240-418c84ca-5c24-11e8-8942-09ab95e1ccae.png)

**Comment by ameshkov** [comment]
Not that we can do anything with this.

You see, the first extension that does the redirection wins, and this time it was "Disconnect" :)
However, redirecting to about:blank or to a stub resource does not happen too often so it shouldn't cause any serious issues.
