### ISSUE TITLE
[Enhancement] Temporarily activate the most appropriate filters automatically

### ISSUE THREAD

**Issue by kwstas86** [AdguardTeam/AdguardBrowserExtension#1021]
If you visit https://potplayerclub.pl 
The following filters activate automatically:

Adblock & uBlock polish filter Version 2.0.1.56. Updated 3 april 2018 at 12:03.
Adblock & uBlock polish cookies filter Version 2.0.0.38. Updated 3 april 2018 at 00:02.
EasyList Polish Version 2.0.0.68. Updated 3 april 2018 at 18:04.

But when you close the tab, the filters are still active. 
Closing the tab of https://potplayerclub.pl should deactivate those filters.

**Comment by vozersky** [comment]
Hi! Moved your request here https://github.com/AdguardTeam/AdguardBrowserExtension/issues/472
