### ISSUE TITLE
Netflix main page extremely laggy/freezes

### ISSUE THREAD

**Issue by Shnub** [AdguardTeam/AdguardBrowserExtension#1026]
For about a week now (no problems before), the Netflix main page becomes extremely laggy upon loading (page intermittently freezes, beachballing, no scrolling possible, no response from page elements). This continues for about 5 to 20 seconds (varies), after which the page finally becomes responsive and behaves normally. It happens on every load or reload (i. e. also after Cmd + R).

No similar issues on other websites.

### Steps to reproduce

1. Log in to Netflix
2. Open https://www.netflix.com/browse
3. Choose profile (if applicable)

The main page then loads, with the behavior described above.

### Excluding other possible causes

- Hard reload (Cmd + Alt + R) has no effect.
- Clearing Safari caches has no effect.
- Disabling other (any or all) Safari extensions has no effect.
- Restarting Safari has no effect.
- Rebooting the system has no effect.

### Identifying AdGuard extension as cause

- Disabling AdGuard extension from Safari preferences resolves the issue (page is responsive immediately, no lags/freezes).
- _Pausing_ the extension (from the popover) resolves the issue as well.

### Troubleshooting within AdGuard

- Disabling "Protection on this website" does **not** (!) resolve the issue.
- Updating filters doesn't help.
- Clearing user filters doesn't help.

### Your environment

AdGuard Browser extension 2.9.2
Safari 11.1
macOS 10.13.4

Active filters:
Safari, Annoyances, English, Spyware, Social Media, German

Settings:
Allow search ads:				off
Activate filters automatically:	off
Phishing/malware protection:	off
Use optimized filters:			on

Other extensions present: JS Blocker, 1Password, PopSearch

**Comment by ameshkov** [comment]
@Alex-302 could you please also check it? This kind of behavior is often caused by the ExtCss rules, enable debugging to see if there're any.

**Comment by Alex-302** [comment]
I can visit only the main page(don't have paid account). We have no ExtCss rules for this domain.

**Comment by Alex-302** [comment]
It seems this is not caused by filters. `@@||netflix.com^$document` does not help.

**Comment by superlex** [comment]
Hi,
I can confirm the issue.
Using old API instead of "Content Blocking API" fixes the issue for me.

**Comment by ameshkov** [comment]
Needs to be re-tested when we introduce a new Safari extension

**Comment by karina-archazh** [comment]
The issue doesn't repeated on 2.10. version
