### ISSUE TITLE
Find a way to inject scripts faster than we do it at the moment

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#1029]
We need to find a way to improve the current situation and reliably inject our scripts BEFORE the in-page scripts are executed.

There's no 100% reliable way (relevant feature request: https://bugs.chromium.org/p/chromium/issues/detail?id=471801), but we can try some hacks in order to achieve a better result than we have at the moment.

First of all, try figure what Tampermonkey does (as I recall they're using `onCommitted` just like we do, but I may be wrong).

Here's what I suggest:
1. Split the injection function into a couple of parts;
2. Use the async `onBeforeRequest` listener to prepare scripts to be injected (and save it to some temp cache with -- use tabId and frameId pair as a cache key);
3. Use both `onResponseStarted` (unreliable but fast) and `onCommitted` (reliable but not fast enough) listeners to inject scripts;
4. Use `onCompleted` and `onErrorOccurred` to clean up the cache;
5. Handle the possibility of duplicate injection in the script;
5. CSS must be injected in the `onCommitted` handler only;

**Comment by maximtop** [comment]
This feature is not reliable, but for some sites, it should inject scripts faster than inline scripts of the site itself.
In order to check this issue, you should
1. add user rule ```maximtop.github.io#%#console.log('hi')```
2. open site https://maximtop.github.io/test-script-order/
3. open developer tools
4. word `hi` should fire early than other logs

Also in 2.10 JavaScript rules correctly work for iframes in Firefox

**Comment by Alex-302** [comment]
The real example, when it is required:
https://kurs.com.ru/
add the rule
`kurs.com.ru#%#AG_abortInlineScript(/!function/, 'String.fromCharCode');`
Expected result - ad script, located in `<head>`, is aborted:
![image](https://user-images.githubusercontent.com/8361299/42763218-0e1730e4-891b-11e8-8ec9-f17fd6c1c394.png)
Add `.js|$third-party,domain=kurs.com.ru,important` to see ads(dev tools must be closed)
Screenshot:

<details>

![image](https://user-images.githubusercontent.com/8361299/42763395-968c6dea-891b-11e8-82bf-e334f4878ba6.png)
</details>
