### ISSUE TITLE
[Feature, Enhancement] Specific Url Whitelisting

### ISSUE THREAD

**Issue by kwstas86** [AdguardTeam/AdguardBrowserExtension#1030]
When you add a website to white list like https://github.com/AdguardTeam/AdguardBrowserExtension/issues/new

The whole github.com gets whitelisted... not sure if its a bug.

**Comment by ameshkov** [comment]
That's actually expected, the whitelist is for domains, not for specific pages.

You can make a more precise exception by adding a rule like this to the user filter:
```
@@||github.com/AdguardTeam/AdguardBrowserExtension/issues/new$document
```
