### ISSUE TITLE
AdGuard not detecting mining scripts on Edge

### ISSUE THREAD

**Issue by MarDarkXT** [AdguardTeam/AdguardBrowserExtension#1031]
### Steps to reproduce
1. Go to www.edu.ro on Edge (has mining script for the moment)
2. No warning message is shown
3. Go to the same site on Firefox and Chrome
4. Warning message is shown and script is blocked

### Expected behavior
Show warning about mining and block script

### Actual behavior
No warning is shown

![ff](https://user-images.githubusercontent.com/25929539/40785255-b33bff9a-64f0-11e8-8400-be4cc5fa625d.PNG)

![chrome](https://user-images.githubusercontent.com/25929539/40785259-b4a9cbd2-64f0-11e8-8b06-935859935825.PNG)

### Your environment
* AdGuard AdBlocker extension version: 2.9.2
* Environment name and version: (e.g. Chrome  69.0.3445.2, Firefox 61.0b9, Edge 17.17134)
* Filters you use in AdGuard: English, Spyware and ROList
* Any other browser extensions you have installed: Pocket and Personal Shopping Assistant

**Comment by zebrum** [comment]
@MarDarkXT are you sure a miner is still there? Can't access the site.

**Comment by ameshkov** [comment]
@MarDarkXT let's check a simple example, is AG able to detect the miner on coinhive.com ?

**Comment by MarDarkXT** [comment]
@ameshkov For coinhive.com it is a bit different:
1. For Chrome everything is OK
![chrome](https://user-images.githubusercontent.com/25929539/41231515-ef9457b4-6d8b-11e8-88df-1efad0ff7816.PNG)
2. For Firefox the page is broken and no message
![firefox](https://user-images.githubusercontent.com/25929539/41231528-fc054724-6d8b-11e8-93bc-936ce64737a3.PNG)
3. For Edge the page is also broken and no message
![edge](https://user-images.githubusercontent.com/25929539/41231543-0a2a4cc8-6d8c-11e8-8564-ae1dc3bb4057.PNG)

**Comment by ameshkov** [comment]
Ah, I remember, the rule was misbehaving in Edge so we decided to simply block known crypto-mining domains instead.

**Comment by ameshkov** [comment]
We'll re-test it and see what can be done about it.
