### ISSUE TITLE
[Firefox for Android] If you click on "AdGuard settings", nothing happens

### ISSUE THREAD

**Issue by superlex** [AdguardTeam/AdguardBrowserExtension#1034]
Hi,
I don't know if it happens only for me, however when I click on "AdGuard settings", nothing happens.

### Steps to reproduce

1. click on menu
2. click on AdGuard AdBlocker
3. click on AdGuard settings

### Expected behavior

settings window should open

### Actual behavior
nothing happens

<details><summary>Screenshot:</summary>

![screenshot](https://user-images.githubusercontent.com/1375223/41119171-6aec81e0-6a92-11e8-8679-cecca3e3b21a.png)

</details>

### Your environment

* AdGuard AdBlocker extension version: 2.9.2
* Environment name and version: Android 7.1 , Firefox for Android 60.0.2
* Filters you use in AdGuard: default
* Any other browser extensions you have installed: nothing

**Comment by zebrum** [comment]
reproduced. 
@superlex you can access AdGuard settings in FF menu: Add-ons - AdGuard AdBlocker - Options

**Comment by superlex** [comment]
Ok, thanks :)

**Comment by superlex** [comment]
Hi,
I don't know if it's the same bug, however this window doesn't work for me:
![screen](https://user-images.githubusercontent.com/1375223/41478920-c22c4d40-70c9-11e8-854f-63aa7e6a6e27.png)
When it appears, buttons don't work. 
Could you check, please?
Thanks.

**Comment by zebrum** [comment]
@superlex are you in beta test group? there is a v4.2.8 Assistant in beta build.

**Comment by superlex** [comment]
Nope, where can I find beta versions?

**Comment by ameshkov** [comment]
@zebrum the add-on is not yet in beta, we're waiting for the last v2.10 major feature to be done before pushing it.

**Comment by maximtop** [comment]
In order to check if the issue is resolved: 
Install beta extension in Firefox for Android.
Check if AdGuard Assitant is working.

**Comment by zebrum** [comment]
@maximtop still need to fix `AdGuard settings` :)
