### ISSUE TITLE
Get rid of Safari and Firefox Legacy builds

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#1035]
Due to the latest changes, we no more need to maintain Safari (this will be a separate app now) and Firefox Legacy.

**Comment by XX-J** [comment]
Т.е. все версии Firefox до 51-ой останутся без Adguard? А почему под Safari прекращаете выпуск?

**Comment by ameshkov** [comment]
> Т.е. все версии Firefox до 51-ой останутся без Adguard?

Просто 2.X только останется.

> А почему под Safari прекращаете выпуск?

Эппл там решил все экстеншны запретить и заставить использовать их новое API (по сути придется отдельное мак-приложение делать). Мы это сделаем, но это займет время, и это будет уже в другом репозитории.

**Comment by XX-J** [comment]
> ...это будет уже в другом репозитории.

 Тоже переезжаете с GitHub'a ? Если да, то куда, на GitLab ?

**Comment by ameshkov** [comment]
Не, в другом репозитории на гитхабе, не вот в этом - тут только код расширений для хрома и фф останется.

**Comment by markmanching** [comment]
this is "worse" on affecting "legacy" version on this addon such as Waterfox, Pale Moon, SeaMonkey, TenFourFox, Basilisk, etc.. any reactions for now?

**Comment by ameshkov** [comment]
> this is "worse" on affecting "legacy" version on this addon such as Waterfox, Pale Moon, SeaMonkey, TenFourFox, Basilisk, etc.. any reactions for now?

As long as we're on v2 branch they will still be supported.

The problem is that maintaining support for them slows down development a lot, and that's why in the new v3 branch we're planning to stop supporting them and concentrate on modern browsers only.

Please note, that AG v2.X will continue to work there.

**Comment by jostyee** [comment]
So where is the Safari app now?

**Comment by ameshkov** [comment]
@jostyee in development, and it will take quite some time -- we cannot reuse most of the existing code there as we have to use an entirely different programming language.

Meanwhile, you'll be able to use old extensions till December: https://safari-extensions.apple.com/

**Comment by ameshkov** [comment]
@Mizzick don't forget to move the Safari converter to a separate repo.

Merge it with https://github.com/AdguardTeam/SafariContentBlockerTester and https://github.com/AdguardTeam/SafariContentBlockerConverterCompiler
