### ISSUE TITLE
Make "White list" and "User filters" a extensible list.

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardBrowserExtension#1037]
Сделайте, пожалуйста, списки - "Белый список" и "Пользовательский фильтр", которые находятся в настройках AdGuard'a - **расширяемыми списками с запоминанием размеров**.

 Чтобы, например, если не пользуешься "Белым списком", то можно его сузить до минимума, а "Пользовательский фильтр", наоборот, развернуть побольше, чтобы было поудобнее (нагляднее).

<details><summary>Screenshot:</summary>

![2018 06 12-3](https://user-images.githubusercontent.com/17948007/41278830-8a55f026-6e33-11e8-8383-6b7e74070d5d.png)
</details>
<br/>

 Заметил небольшую ошибку: Ссылка на справку по составлению собственных правил, находящаяся в кратком описании "Пользовательского фильтра" в настройках, ведёт к [англоязычной версии](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters?utm_source=extension&aid=16593), хотя интерфейс AdGuard'a - русский.

___________________________________________________
Mozilla Firefox v50.0.2 (Win7SP1) - Adguard v2.9.2 (legacy)

**Comment by ameshkov** [comment]
Мы сделаем, но уже в редизайне, там все сильно по другому выглядит:
https://uploads.adguard.com/up04_xtozr_AdGuard_Settings.png

**Comment by XX-J** [comment]
Спасибо за редизайн, но в версии 3.0.3 обе проблемы актуальны.

**Comment by XX-J** [comment]
Они остались такими же маленькими, относительно рабочей области монитора. А когда переключаешься на "Пользовательский фильтр", то хочется его видеть максимально полно и наглядно, для более быстрой и лёгкой ориентации в нём.

<details><summary>Screenshot:</summary>

![2019 01 28-1](https://user-images.githubusercontent.com/17948007/51836458-85ef9d00-2311-11e9-9459-457fae497c03.png)
</details><br/>

 Например я бы растянул его так, чтобы в нём не остались полосы прокрутки, а полоса прокрутки появилась в основном окне, для того, чтобы можно было прокручивать как шапку, так и футер, - бесполезную, с точки зрения работы с собственными правилами.
 Так, что, - буду Благодарен, если сделаете их расширяемыми (с запоминанием размеров).

**Comment by XX-J** [comment]
**1**. Сделайте, пожалуйста, возможным **неограниченное расширение** этих списков **по горизонтали**.
 **2**. Вторая проблема до сих пор актуальна:
>  Заметил небольшую ошибку: Ссылка на справку по составлению собственных правил, находящаяся в кратком описании "Пользовательского фильтра" в настройках, ведёт к [англоязычной версии](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters?utm_source=extension&aid=16593), хотя интерфейс AdGuard'a - русский.

___________________________________________________
Mozilla Firefox v53.0.3 (Win7SP1) - Adguard v3.0.13

**Comment by ameshkov** [comment]
> Заметил небольшую ошибку: Ссылка на справку по составлению собственных правил, находящаяся в кратком описании "Пользовательского фильтра" в настройках, ведёт к англоязычной версии, хотя интерфейс AdGuard'a - русский.

Точно у вас браузер с русским языком? Там по ссылке KB должен сам определять язык

**Comment by XX-J** [comment]
Русский язык - отдельным .xpi , а так - да, полностью на русском.

**Comment by ameshkov** [comment]
http://www.xhaus.com/headers

Вот тут какие заголовки?

**Comment by XX-J** [comment]
```

HTTP Header* | Value
-- | --
Accept | text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding | gzip, deflate
Accept-Language | ru,en-US;q=0.7,en;q=0.3
Connection | keep-alive
Dnt | 1
Host | www.xhaus.com
Upgrade-Insecure-Requests | 1
User-Agent | Mozilla/5.0 (Windows NT 6.1; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0
```

**Comment by ameshkov** [comment]
@XX-J а если вот так по прямой ссылке перейти?
https://kb.adguard.com/general/how-to-create-your-own-ad-filters

**Comment by XX-J** [comment]
Перенаправляет на русскоязычную страницу.

**Comment by ameshkov** [comment]
Угу, ну я нашел кажется в чем косяк, там лишний редирект забрался. Поправим на след неделе

**Comment by XX-J** [comment]
А что на счёт горизонтального расширения?

**Comment by ameshkov** [comment]
Очень сложно с текущей версткой.

Вообще если надо сложные и длинные правила редактировать, то текстовый редактор гораздо лучше подходит чем пользовательский фильтр.

Возьмите VS Code и вот этот плагин например:
https://marketplace.visualstudio.com/items?itemName=adguard.adblock

**Comment by XX-J** [comment]
Спасибо, я понял.
