### ISSUE TITLE
[FF] $replace rule not applied

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/AdguardBrowserExtension#1038]
https://s3.amazonaws.com/homad-global-configs.schneevonmorgen.com/global_config.json   

This rule is in German filter and gets applied by AdGuard for Windows, but not by FireFox Extension:

||s3.amazonaws.com/homad-global-configs.schneevonmorgen.com/global_config.json$replace=/"enabled":[\s\S]*true\,/"enabled": false\,/i,important

Andrey mentioned an issue in Slack in February, but it should have been fixed in the next version according to him. Meanwhile we got a new version. Sadly I couldn't find the issue link at github.

**Comment by ameshkov** [comment]
@maximtop please check it with the version from the master branch. Most likely the issue is resolved already, we need to confirm it.

**Comment by maximtop** [comment]
@ameshkov in 2.10 replace modifier is not working

**Comment by maximtop** [comment]
This rule is not correct for the extension. Commas should be escaped. Also, there is no `important` modifier for the extension.
Here is right version of the rule:
`||s3.amazonaws.com/homad-global-configs.schneevonmorgen.com/global_config.json$replace=/"enabled":[\s\S]*true\,/"enabled": false\,/i`
But unfortunately, this rule won't work till the next version, there are some issues with charset defining for json files in current version.

**Comment by BlazDT** [comment]
Why does it require an additional escape while it works fine for AdGuard for Windows?

**Comment by maximtop** [comment]
I don't know why it works in windows, but here 
https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#replace-modifier
is stated
`In replace value, two characters must be escaped: comma (,) and ($). Use (\) for it. For example, escaped comma looks like this: \,.`

**Comment by BlazDT** [comment]
That article seems to be wrong - normal regex is without escaping ,    - but ( and ) must be escpaed.

https://regex101.com/

<img width="320" alt="regex" src="https://user-images.githubusercontent.com/34266271/41986542-bfec1530-7a36-11e8-8c3b-bb9cb0515b92.png">

**Comment by ameshkov** [comment]
@BlazDT the problem is that `,` is a special character for AdGuard rules, not regular expressions. We use it to divide modifiers and that's why you need to escape it so that AdGuard could understand that this comma is not for separating modifiers.

**Comment by BlazDT** [comment]
@ameshkov 
Then AdGuard for Windows shouldn't accept that rule.

**Comment by ameshkov** [comment]
Yep, it must be a coincidence that it does (different language, different parsing algorithm). It'll be easier to sync this behavior between Mac-Android-Win-Extension once we start using CL.

**Comment by maximtop** [comment]
To check if this issue is fixed you should in Firefox:
1. Add user rule `||s3.amazonaws.com/homad-global-configs.schneevonmorgen.com/global_config.json$replace=/"enabled":[\s\S]*true\,/"enabled": false\,/i`
2. Open `s3.amazonaws.com/homad-global-configs.schneevonmorgen.com/global_config.json`
3. It should correctly replace `enabled: true` to `enabled: false`

**Comment by BlazDT** [comment]
When beta/final is posted here https://github.com/AdguardTeam/AdguardBrowserExtension/releases then the user can test.
