### ISSUE TITLE
[Bug/FeatureRequest] When you import user filter list, it should accept only text files

### ISSUE THREAD

**Issue by superlex** [AdguardTeam/AdguardBrowserExtension#1039]
Hi, 
it's only a little bug (or a little feature request), however it could be important.

### Steps to reproduce

1. Go to AdGuard settings;
2. click on import to import your filter list.

### Expected behavior
It should accept only text files.

### Actual behavior
It accepts image files too, and other file types.

### Your environment

* AdGuard AdBlocker extension version: 2.9.2
* Environment name and version: macOS 10.13.5, Safari 11.1.1
* Filters you use in AdGuard: default

**Comment by aspasskaya** [comment]
.jpeg file still can be imported in Edge.
Maybe there should be a warning or an error message when a user trying to import non txt file.
# 
https://uploads.adguard.com/assa_9uk0i.png
https://uploads.adguard.com/assa_3ita6.png
