### ISSUE TITLE
Chrome Extension ICON Need Update for "Material Design Toolbar"

### ISSUE THREAD

**Issue by LenKiMo** [AdguardTeam/AdguardBrowserExtension#104]
Chrome 49.0.2587.3 dev-m (64-bit), Open `#top-chrome-md` in `Chrome://flags`. 
If the extension does not provide the appropriate size, Chrome will be reduced the icon according to algorithm. Shrinking effect is not satisfactory. I think Adguard should provide an suitible icon.
I think it is possible that MD-Design and icon algorthm in this new version is not friendly with low DPI screen.:(

http://i.imgur.com/H4Y2jML.png

**Comment by ameshkov** [comment]
Outdated, new icon covers this feature request
