### ISSUE TITLE
Adguard stop blocking everything in Windows-Chrome 64bits

### ISSUE THREAD

**Issue by linoramone** [AdguardTeam/AdguardBrowserExtension#1041]
Hi

I'm not a stupid user. I check the settings.
Chrome 67.0.3396.87 64bits @Windows 7 x64
Adguard 2.9.2
Allow search ads and the self-promotion of websites == OFF
English filter= ON
EasyList == ON
No other extension is active.
Incognito mode == OFF
Protection on this website == ON
Blicked=0
Total=51

I see all ads on every page. Ex: Youtube.com

**Comment by ameshkov** [comment]
Hm, just in case, could you please try reinstalling the extension?

Maybe the extensions settings are corrupted (that's the only explanation I see for now).
