### ISSUE TITLE
AdGuard fails to block ads in the Sidebar in Firefox 60.x

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardBrowserExtension#1043]
Ads are not blocked, while everything works fine in regular tabs

### Steps to reproduce

1. Open a website in a regular tab
2. Add a website to the Bookmarks 
3. Right-click on the bookmark, choose Preferences 
4. Put a checkmark here: https://uploads.adguard.com/Monosnap_07-04-13-43.png
5. Open a website in the sidebar

### Expected behavior

A website loads in the sidebar, ads are blocked

### Actual behavior

A website loads in the sidebar, but ads are not blocked

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/42273008-8e5edd54-7f90-11e8-9a34-d900b49df4be.png)

</details>

### Your environment

* AdGuard AdBlocker extension version: 2.9.2
* Environment name and version: 60.0.1
* Filters you use in AdGuard: Russian, English 
* Any other browser extensions you have installed: n/a

**Comment by maximtop** [comment]
Firefox sidebar has tabId = -1 that's why extension can block bad requests (you can see them in filtering log if you choose background tab), and can't apply cosmetic rules.

**Comment by ameshkov** [comment]
Closed as we can't do anything with this
