### ISSUE TITLE
Add ability to block network requests, which are excluded by the rule in the custom filter

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1044]
At the moment this is impossible to create blocking rule for requests, exclused by custom filter
![image](https://user-images.githubusercontent.com/8361299/42569995-1026eea0-851b-11e8-8eab-c14aa1c7e7a3.png)
It will be useful for debugging some rules.

**Comment by Alex-302** [comment]
the same issue with requests, excluded by the filters
![image](https://user-images.githubusercontent.com/8361299/43659142-c127975e-9763-11e8-8dda-e72eb39be915.png)

**Comment by ameshkov** [comment]
That's possible if we add a rule with the `$important` modifier.
