### ISSUE TITLE
User filter doesnt block URL if it is whitelisted in standard filter

### ISSUE THREAD

**Issue by oleksiy2015ua** [AdguardTeam/AdguardBrowserExtension#1045]
### Steps to reproduce

1. English filter has "@@||seekingalpha.com^$script" rule
2. I created such user rule "||seekingalpha.com/assets/pages/article_page-*.js"
3. In logs I see that URL "https://static2.seekingalpha.com/assets/pages/article_page-93caf3eb3bce54967b6fd3229280136b57657b746dc9fee201da45c18a3ea46d.js" is allowed because of whitelisted rule

Here is live URL to test
https://seekingalpha.com/article/4174631-svxy-short-volatility-ready-fly?page=2

### Expected behavior

It would be great if user filter rules block URLs whitelisted in standard filter.

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

<details><summary>Screenshot of the browser console:</summary>

</details>

### Your environment

* AdGuard AdBlocker extension version: 2.9.2
* Environment name and version: (e.g. Chrome 67.0.3396)
* Filters you use in AdGuard: English, 
* Any other browser extensions you have installed:

**Comment by ameshkov** [comment]
Hi, you need to use the `$important` modifier:
```
||seekingalpha.com/assets/pages/article_page-*.js$important
```
