### ISSUE TITLE
Element hiding rules don't work in frame from playbuzz

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/AdguardBrowserExtension#1046]
Issue - https://github.com/AdguardTeam/AdguardFilters/issues/19612

### Steps to reproduce

1. Go here - https://www.sporx.com/milli-atletler-belarusta-kosacak-SXHBQ689247SXQ
2. Try to hide social widget, for example use one of these rules:
`##.share-bar`
`playbuzz.com##.share-bar`

### Expected behavior

Social widget should be hidden.

### Actual behavior

Social widget is not hidden.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29142494/42755717-a24c5568-88f9-11e8-8eb9-2e8ebb03c93d.png)

</details>

### Your environment

* AdGuard AdBlocker extension version:  2.9.2
* Environment name and version: Chrome 67.0.3396.99
* Filters you use in AdGuard: English, Spyware, Social, Annoyances

**Comment by ameshkov** [comment]
Needs to be re-tested with v2.10 beta

**Comment by maximtop** [comment]
Reproduced. I'll check why the rule doesn't affect elements in the iframe on this site.
