### ISSUE TITLE
Blocks ad video, but sound remains

### ISSUE THREAD

**Issue by t-zander** [AdguardTeam/AdguardBrowserExtension#1052]
### Steps to reproduce

1. Open Google Chrome
2. Go to http://hdrezka.ag/series/fiction/1738-ostatsya-v-zhivyh-2004.html#t:56-s:3-e:4
3. Launch video

### Expected behavior

I should hear film sound
### Actual behavior

You will hear some strange ad sound together with the movie sound

<details><summary>Screenshot:</summary>

Scrren shot can't demonstrate the issue
</details>

<details><summary>Screenshot of the browser console:</summary>

</details>

### Your environment

* AdGuard AdBlocker extension version: 
last version
* Environment name and version: (e.g. Chrome 59.0.3071.115)
last version
* Filters you use in AdGuard:

* Any other browser extensions you have installed:

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdguardFilters #20410](https://github.com/AdguardTeam/AdguardFilters/issues/20410) via [**ZenHub**](https://www.zenhub.com/)
