### ISSUE TITLE
[Filtering log] Remove Pattern and Options, when creating exclusions for element hiding rules

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1057]
Remove Pattern and Options, when creating exclusions for element hiding rules(`##`, `#$#`, `#?#`). They are make no sense in this case.
![image](https://user-images.githubusercontent.com/8361299/43528973-db3fea4a-95b2-11e8-8d4a-cc3c1427cfec.png)
`#?#` - ABP Extended CSS syntax.

**Comment by maximtop** [comment]
> in order to check, install the extension
> open site where CSS rules are applied
> open filtering log
> try to unblock this rule
> see if there are no redundant options
