### ISSUE TITLE
[Filtering log] Search is not working for hidden elements and works only in URL column

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1058]
For example:
![image](https://user-images.githubusercontent.com/8361299/43575419-767bc2a8-964f-11e8-8da9-79f7a26caf01.png)
* trying to find DIV
![image](https://user-images.githubusercontent.com/8361299/43575524-aec2a7e4-964f-11e8-8d3e-0fcab7eb02cc.png)
* trying to find the rule
![image](https://user-images.githubusercontent.com/8361299/43575550-c56fb13a-964f-11e8-848d-3e8182a5325f.png)

**Comment by maximtop** [comment]
> in order to check, open filtering log
> try to filter rows by URL, element, filter name and rule name
