### ISSUE TITLE
Tests doesn't  run successfully on http://testcases.adguard.com for Chrome/Safari

### ISSUE THREAD

**Issue by karina-archazh** [AdguardTeam/AdguardBrowserExtension#1060]
* AdGuard AdBlocker extension version: 2.10.1
* Environment name and version: Chrome Version 68.0.3440.75 (Official Build) (64-bit) and Safar 11.1.2 (13605.3.8)

Testing rule  on page http://testcases.adguard.com/Filters/simple-rules/generichide/test.html doesn't  run successfully for both browsers:
![image](https://user-images.githubusercontent.com/41899455/43590538-e0a27d28-9679-11e8-8b39-22167d06199a.png)

 And for Safari:
![image](https://user-images.githubusercontent.com/41899455/43590648-2ba1c14e-967a-11e8-9d2c-7c88aee18148.png)
http://testcases.adguard.com/Filters/extended-css-rules/test-extended-css-rules.html

**Comment by maximtop** [comment]
> in order to test:
> open page http://testcases.adguard.com/Filters/simple-rules/generichide/test.html
> import rules for this tests
> check if all tests run successfully

**Comment by karina-archazh** [comment]
Automatical test cases work as usual and as expected in 3.0
