### ISSUE TITLE
Unable to use functionality of AdGuard extension when pCloud is enabled.

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardBrowserExtension#1062]
When pCloud extension is enabled unable to block ads on a website.

### Steps to reproduce

1. Install and enable AdGuard extension
2. Install and enable pCloud extension
3. Open any page and try to block any element.

### Expected behavior

Any selectable element can be blocked.
### Actual behavior
See the screenshot

<details><summary>Screenshot:</summary>

</details>

<details><summary>Screenshot of the browser console:</summary>

</details>

**Comment by TheHasagi** [comment]
[Image](https://user-images.githubusercontent.com/37797229/43690686-0f9f93d2-9917-11e8-8a7d-c927d74988d6.png))

**Comment by TheHasagi** [comment]
[Image](https://files.slack.com/files-pri/T0B41S97U-FC2H44AL9/pcloud.png)

**Comment by zebrum** [comment]
https://uploads.adguard.com/Windows_10_2018-08-13_17-59-17.png
