### ISSUE TITLE
Allow to save filtering log when reloading the page

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1074]
Some sites refresh the page, when ad blocker is detected, and you can't check blocked elements(without dev tools)
Sample site:
http://fb.ru/
Clear cookies and add `fb.ru##.adsbygoogle` to reproduce it.

**Comment by ameshkov** [comment]
We need to add a "Preserve log" checkbox. We need an advise from the designer before doing it.

**Comment by Alex-302** [comment]
also suggest to add separator(the line with URL only) when refreshing the tab. Something like that
![image](https://user-images.githubusercontent.com/8361299/44260351-c86a6500-a21c-11e8-8bb2-40606142249c.png)

**Comment by Alex-302** [comment]
Many sites which reload tab after adblock detection(with Yandex Direct. For example http://fb.ru/)

**Comment by ameshkov** [comment]
1. Add the `Preserve log` checkbox: https://uploads.adguard.com/up04_m1b96_DevTools_-_chrome-extensiongfggjaccafhcbfogfkogggoepomehbjlpageslog.html.png
2. Do not clear the filtering log when the page reloads if this box is checked

**Comment by karina-archazh** [comment]
Checked.
