### ISSUE TITLE
Please update the Ukrainian translations

### ISSUE THREAD

**Issue by aalpatkina** [AdguardTeam/AdguardBrowserExtension#1076]

**Comment by ameshkov** [comment]
Hm, I am not sure if Chrome/FF supports Ukrainian language

**Comment by maximtop** [comment]
chrome and firefox supports ukrainian language, and extension works with them also. But I couldn't download any new translations for `uk` locale code. I think that ukrainian translations were updated already

**Comment by karina-archazh** [comment]
Checked
