### ISSUE TITLE
Phantom integration mode

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1077]
@adguard-bot commented on [Fri Aug 17 2018](https://github.com/AdguardTeam/AdguardFilters/issues/21199)

### Issue URL (Incorrect Blocking)
[https://www.drive2.ru/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.drive2.ru%2F)
### Comment
Username: @CaesarRulezzz
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/UgRVmXp.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | Ext
AdGuard version: | 2.9.2
Browser: | Chrome
Filters: | Russian,<br>Mobile Ads,<br>RU AdList,<br>Annoyances,<br>Simplified domain names,<br>English,<br>Adblock Warning Removal List,<br>Anti-Adblock Killer | Reek,<br>RU AdList: Counters,<br>RU AdList: BitBlock,<br>Spyware
Other extensions used: | AdGuard показывает, что включен Adguard для Windows, хотя у меня операционная система Linux (Mint 19)

---

@Alex-302 commented on [Fri Aug 17 2018](https://github.com/AdguardTeam/AdguardFilters/issues/21199#issuecomment-413839307)

@CaesarRulezzz а можно удалённо глянуть? Есть подобные жалобы, но никак повторить не удаётся.

**Comment by CaesarRulezzz** [comment]
@Alex-302 Да, конечно

**Comment by Alex-302** [comment]
ещё вопрос - это эпизодически или всегда?(сайты с Директом, похоже)

**Comment by CaesarRulezzz** [comment]
@Alex-302 на Drive2.ru стабильно. Причем сразу с главной.

**Comment by Alex-302** [comment]
А можете контакты дать чтоб договориться об удалённом сеансе?
Или в телеграм можете написать https://t.me/Alex302

**Comment by Alex-302** [comment]
Fixed
