### ISSUE TITLE
Не срабатывает автообновление фильтров.

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardBrowserExtension#1082]
@Light-on commented on [Tue Aug 28 2018](https://github.com/AdguardTeam/AdguardForWindows/issues/2315)

Здравствуйте.  Недавно перестали обновляться фильтры расширения при запуске браузера. Никогда раньше такой проблемы не было. С обновлением вручную всё в порядке.
Браузер Chrome 68.0.3440.106
Adguard расширение 2.9.2
P.S.: первый раз создаю тему для обсуждения. Не ориентируюсь, что к чему на сайте. Ищу решение проблемы здесь, так как никто не отвечает на форуме. Если тема не соответствует правилам оформления и подлежит закрытию, пожалуйста, скажите мне, где прочитать о правилах создания тем.

**Comment by zebrum** [comment]
@Light-on вообще период проверки обновлений для фильтров 48 часов. У вас вручную фильтры обновляются?

**Comment by Light-on** [comment]
@zebrum окно у меня всегда показывается только при обновлении фильтров вручную. После вашего комментария проверила настройки и вижу, что фильтры обновлены вчера и позавчера! Дело в том, что я привыкла смотреть по трафику, каждый раз с запуском браузера стабильно был скачок загрузки данных, я всегда следила за этим и понимала, что обновился Adguard. А недавно эта загрузка прекратилась. Открывается стартовая страница Google и никакого трафика. Но если обновить фильтры вручную, видна та самая загрузка данных, которая раньше наблюдалась сразу при запуске браузера. По-видимому, расширение работает исправно, но что-то изменилось.

**Comment by Light-on** [comment]
@zebrum сейчас вижу, что стоит версия 2.10.8, расширение обновилось до новой версии само. А фильтры, как я поняла, теперь обновляются не моментально при запуске браузера, как было всегда, а между делом, не отследить, когда именно.

**Comment by zebrum** [comment]
@Light-on в версии 3.0 будет реализована возможно выбрать период обновления фильтров.

**Comment by Light-on** [comment]
@zebrum я ещё думаю, что могли измениться свойства браузера. Фильтры всегда обновлялись при запуске Хрома, сколько бы ни прошло времени с момента предыдущего обновления. Например, открываю браузер, жду минуту, закрываю, сразу открываю снова и тут же вижу загрузку данных Adguard.
