### ISSUE TITLE
Assistant preview doesn't close

### ISSUE THREAD

**Issue by Mizzick** [AdguardTeam/AdguardBrowserExtension#1083]
### Steps to reproduce
1. Open assistant
2. Preview - select some element
3. Click Block
4. ?

### Expected behavior
Assistant popup should be closed.

### Actual behavior
Nothing happens

<details><summary>Screenshot:</summary>
<img width="1263" alt="screenshot 2018-08-29 12 55 16" src="https://user-images.githubusercontent.com/13855288/44780647-18d1b300-ab8b-11e8-9546-713f18cbc81e.png">
</details>

### Your environment

* AdGuard AdBlocker extension version: 
* 2.10.8

**Comment by karina-archazh** [comment]
Checked

**Comment by planet0** [comment]
Also occurring whilst Integration mode is active.

Trying to click 'Block' whilst in preview mode does not work. You must exit preview mode first in order to successfully block something.
