### ISSUE TITLE
The Norwegian translation implementation is broken

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdguardBrowserExtension#1085]
I take note that [the Norwegian translation of the AdGuard browser extension](http://translate.adguard.com/collaboration/translate/project/project/13698/language/180) is at 100%, but that [the corresponding JSON file](https://github.com/AdguardTeam/AdguardBrowserExtension/blob/master/Extension/_locales/nb/messages.json) in this repo hasn't been updated with any of those translated strings, and therefore the extension's settings are shown in English on my end. Would that be possible to fix, presumably by connecting the translation project and the JSON file properly, or by downloading the JSON file from OneSkyApp's servers (which I don't seem to be able to do) and pasting it into GitHub?

**Comment by ameshkov** [comment]
@maximtop let's update the translations in the 2.10 hotfix release which we're going to publish soon.
