### ISSUE TITLE
When using Edge dev console, JS error occurs in extended-css.js

### ISSUE THREAD

**Issue by tallman5** [AdguardTeam/AdguardBrowserExtension#1086]
### Steps to reproduce
1. Launch Edge
2. Navigate to https://www.google.com
3. Launch dev console (F12)
4. Refresh page (Ctrl+F5)

### Expected behavior
Dev Console should not show any JS errors

### Actual behavior
JS debugger pauses on an unhandled exception in extended-css.js, line 407
Error: Object doesn't support property or method 'bind'

<details><summary>Screenshot:</summary>

<!
![agerror](https://user-images.githubusercontent.com/11196425/44957849-19c55600-aea5-11e8-8324-256c62df03a8.png)
--- drag and drop, upload or paste your screenshot to this area-->

</details>

<details><summary>Screenshot of the browser console:</summary>

</details>

### Your environment

* AdGuard AdBlocker extension version: 2.10.8
* Environment name and version: Edge 42.17134.1.0
* Filters you use in AdGuard: defaults
* Any other browser extensions you have installed: none

**Comment by ameshkov** [comment]
@maximtop I thought we've fixed it?

**Comment by maximtop** [comment]
As I remember we've decided to postpone this. 
We found that this error happens only while edge developer tool is open, because edge uses strange implementation of console.log

**Comment by karina-archazh** [comment]
Checked
