### ISSUE TITLE
Сosmetic filters stop working after refresh of a page cached by a ServiceWorker

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/AdguardBrowserExtension#1087]
### Steps to reproduce

1. Go to https://outlook.live.com/ and then log in.
2. Add this rule to user filter `outlook.live.com##body`
3. Refresh website once or few times.

### Expected behavior

Website should be blank.

### Actual behavior

Cosmetic filter doesn't work.

### Your environment

* AdGuard AdBlocker extension version: 2.10.8
* Environment name and version: Chrome 68.0.3440.106
* Filters you use in AdGuard: -
* Any other browser extensions you have installed: -

https://github.com/AdguardTeam/AdguardFilters/issues/2686#issuecomment-417745416

**Comment by AdamWr** [comment]
Similar issue happens on https://mail.google.com/ - https://github.com/AdguardTeam/AdguardFilters/issues/21629#issuecomment-418361630

Steps to reproduce
1. Go to https://mail.google.com/ and then log in.
2. For example add this rule to user filter `mail.google.com##body`
3. Refresh website few(many?) times, I'm not sure how many and what is a culprit, because it happens randomly, but when it happened then cosmetic filters doesn't work.

**Comment by Alex-302** [comment]
For Gmail - temporary added `mail.google.com##.aeF > .nH > .nH[role="main"] > .aKB:has(> div)`
Should be tested with exclusion rule: `mail.google.com#@#.aeF > .nH > .nH[role="main"] > .aKB:has(> div)`

**Comment by karina-archazh** [comment]
Checked
