### ISSUE TITLE
groups.google.com

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1089]
@adguard-bot commented on [Mon Sep 03 2018](https://github.com/AdguardTeam/AdguardFilters/issues/21917)

### Issue URL (Incorrect Blocking)
[https://groups.google.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fgroups.google.com%2F)
### Comment
> После последнего обновления (до версии 2.10.8) наблюдаются проблемы при ответе в гугл группах. Ответы не работают, вылезает много ошибок по JavaScript в консоли браузера.
>  
> Браузер Chrome Версия 68.0.3440.106 (Официальная сборка), (64 бит)
> 
> Отключение фильтрации на сайте не помогает, помогает только полностью отключение расширения со вкладки "Управление расширениями" браузера (chrome://extensions/?id=bgnkhhnnamicmpeenaelnjfhikgbkllg)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](http://res.cloudinary.com/adguard/image/private/s--CLWGrF1L--/v1535976120/p3sdf5v9zgcbu1e7xqfc.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | Ext
AdGuard version: | 2.10.8
Browser: | Chrome
Filters: | AdGuard Russian,<br>RU AdList,<br>AdGuard Base,<br>Malware Domains,<br>Spam404,<br>NoCoin Filter List,<br>AdGuard Spyware,<br>AdGuard Social Media
Other extensions used: | Антивирус DrWeb, другие расширения отключены

**Comment by zebrum** [comment]
can't repro
@maximtop @ameshkov any thoughts?

**Comment by maximtop** [comment]
I couldn't reproduce too

**Comment by ameshkov** [comment]
Guys, have you enabled the same filters lists?

**Comment by zebrum** [comment]
yep
