### ISSUE TITLE
AdGuard 2.10.8 extension for Edge blocks Spotify web player song play

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardBrowserExtension#1090]
### Steps to reproduce

1. Go to https://open.spotify.com/
2. Try to play any album.
3. "Play" button is blocked. 
4. The album icon in the left-down corner is missing.

Whitelisting the website doesn't work. If I disabled AdGuard, the album icon is back, songs can be played, no problem at all.

### Actual behavior

<details><summary>Screenshot:</summary>

![inkedscreenshot_1_li](https://user-images.githubusercontent.com/27292111/45000731-22667b00-afd0-11e8-85ca-2b041bd4b81e.jpg)

</details>

<details><summary>Screenshot of the browser console:</summary>

![inkedscreenshot_2_li](https://user-images.githubusercontent.com/27292111/45000741-36aa7800-afd0-11e8-98e4-38ffa2ab2513.jpg)

</details>

### Your environment

* AdGuard AdBlocker extension version: AdGuard 2.10.8 extension for Edge
* Environment name and version: Microsoft Edge 42.17134.1.0
* Filters you use in AdGuard: AdGuard base filter
* Any other browser extensions you have installed: none

**Comment by karina-archazh** [comment]
Checked

**Comment by viniciusvillas** [comment]
AdGuard is also blocking the XProtect Web Client (Milestone) video feed via WebSockets on MS Edge. I believe it's the exact same issue. Whitelisting the site doesn't work. Disabling the extension works. The fixing of issue #1014 is probably the culprit.

**Comment by ameshkov** [comment]
@viniciusvillas yep, that must be it, thank you for chiming in!

**Comment by ameshkov** [comment]
It seems that the only viable way is to simply rollback #1014 :(

Edge behaves unpredictably when we override WebSocket.
