### ISSUE TITLE
Assitant advanced settings button doesn't respond

### ISSUE THREAD

**Issue by Mizzick** [AdguardTeam/AdguardBrowserExtension#1091]
### Steps to reproduce

1. Open assistant from toolbar popup
2. Select element
3. Click on "Advanced settings"
4. ?

### Expected behavior
Advanced settings should open.

<details><summary>Screenshot:</summary>

<img width="1033" alt="screenshot 2018-09-07 16 09 08" src="https://user-images.githubusercontent.com/13855288/45220960-a06c9f80-b2b8-11e8-81c6-2af884b19a90.png">

</details>

**Comment by ameshkov** [comment]
Happens with Polish filter enabled due to this rule: `##[id^="adv-"]`

Let's rename the element `adv-settings` -> `advanced-settings`
