### ISSUE TITLE
Allow applying multiple $replace rules to a single web request

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#1092]
Check the spec:
https://github.com/AdguardTeam/CoreLibs/issues/45

**Comment by maximtop** [comment]
Instructions how to test if this feature works in the Extension for Firefox
Install extension for Firefox
Add rules:
`||example.org^$replace=/Example/Hello/`
`||example.org^$replace=/Domain/Tester/`

Open example.org
On the page, you should see that `Example Domain` replaced with `Hello Tester`

Add rule
`@@||example.org^$replace=/Domain/Tester/`
On the page, you should notice `Hello Domain`
Rule `||example.org^$replace=/Domain/Tester/` was whitelisted

Remove `@@||example.org^$replace=/Domain/Tester/`
Add rule `@@||example.org^$replace`. It whitelists both rules
On the page, you should see `Example Domain`
