### ISSUE TITLE
Integration mode not always active - Chrome/Windows

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardBrowserExtension#1094]
### Steps to reproduce

1. Install AdGuard for Windows
2. Also install AdGuard Browser Extension
3. Browse some websites
4. Check status of icon

### Expected behavior
Integration mode always active if AdGuard for Windows is installed and enabled

<details><summary>Screenshot:</summary>

![expected](https://user-images.githubusercontent.com/42660125/45262174-1c9bea00-b455-11e8-8833-4b62761b8acf.PNG)

</details>

### Actual behavior
Extension falls back and blocks elements, like AdGuard for Windows doesn't exist; integration mode isn't active

<details><summary>Screenshot:</summary>

![actual](https://user-images.githubusercontent.com/42660125/45262176-1e65ad80-b455-11e8-9884-929326d615ee.PNG)

</details>

### Your environment

* AdGuard AdBlocker extension version: 2.10.8 Beta 
* Environment name and version: Chrome Version 69.0.3497.81 (Official Build) (64-bit)
* Filters you use in AdGuard: AdGuard Base filter, AdGuard Spyware filter, AdGuard Social Media filter, AdGuard Annoyances filter
* Any other browser extensions you have installed: Authy Chrome Extension, Checker Plus for Gmail™
Checker Plus for Google Calendar™, Google Analytics Opt-out Add-on (by Google), Google Docs Offline, IBA Opt-out (by Google), LastPass: Free Password Manager, Windows Defender Browser Protection

**Comment by planet0** [comment]
Previous screenshot was on github.com, this time it occured with Gmail. Was able to screenshot the Console for you.

![console-error](https://user-images.githubusercontent.com/42660125/45277072-3c8ce580-b509-11e8-9fec-5c8e40f7b0a7.PNG)

**Comment by ameshkov** [comment]
That's all due to ServiceWorker's caching mechanism, it messes with the way the integration works.

Can't be resolved unless we change the integration mechanism.

**Comment by planet0** [comment]
Thanks for explaining that @ameshkov -- is it okay to continue as is and let both the extension and windows program filter at the same time for those sites?

**Comment by ameshkov** [comment]
Yeah, it is okay, on those websites it's not too problematic to have both AGs filter it.
