### ISSUE TITLE
AdGuard "send statistics" crashes google sheets when option turned on

### ISSUE THREAD

**Issue by berwynhoyt** [AdguardTeam/AdguardBrowserExtension#1096]
### Steps to reproduce
In short: log in to google and load a sheet. If "send statistics" is enabled, sheets will crash.

<details>
1. Make sure AdGuard for windows is running Open any google sheet
2. Ensure the default browser extension option "Send statistics for ad filters usage" is enabled.
3. Open any google sheet. Make sure you are logged in to google docs.
4. When the sheet has fully loaded (within 30 seconds) it will fail.

### Expected behavior
The sheet should be editable.

### Actual behavior
When the sheet has fully loaded (within 30 seconds) it will crash with the message "Unable to load file. Try to load it again or send error report" and the single button option "Reload".

![image](https://user-images.githubusercontent.com/8123425/45269108-4b10d800-b4dc-11e8-9460-cef6d89eb81b.png)

There are no browser errors. Just a warning shown here:
![image](https://user-images.githubusercontent.com/8123425/45269078-8363e680-b4db-11e8-9c49-57be2c91818e.png)

</details>

### Your environment
* AdGuard AdBlocker extension version: 2.10.8
* Chrome version 69.0.3497.81 (Official Build) (64-bit)
* Filters you use in AdGuard:
![image](https://user-images.githubusercontent.com/8123425/45269099-19980c80-b4dc-11e8-9c46-74ebe1900534.png)

* No other browser extensions are installed (I turned them all off for this test).

**Comment by berwynhoyt** [comment]
PS: The crash happens even if docs.google.com is in the whitelist.

**Comment by planet0** [comment]
Also experienced the same issue with the extension and the statistics setting enabled.

Sheets file would 'crash' after a few seconds every single time.

Workaround was to not use the Sheets app in Chrome (go directly to sheets.google.com) and disable Offline Mode.

**Comment by ameshkov** [comment]
> 2. Ensure the default browser extension option "Send statistics for ad filters usage" is enabled.

Guys, please note that this option will do nothing in the integration mode (as the extension won't be used for blocking anything).

**Comment by berwynhoyt** [comment]
Disabling offline mode didn't work for me. The only thing that worked was disabling "Send statistics" in AdGuard

**Comment by karina-archazh** [comment]
The issue with google sheets still occur in Google Chrome.
