### ISSUE TITLE
Ncloud CSP doesn't allow to execute scripts in Firefox 

### ISSUE THREAD

**Issue by maximtop** [AdguardTeam/AdguardBrowserExtension#1104]
### Steps to reproduce
1. Install AdGuard 2.10.8
2. Open https://ncloud.adguard.com/login

### Expected behavior
No CSP errors in console

### Actual behavior
errors in developer tools
`Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”)`

![image](https://user-images.githubusercontent.com/17272769/45409450-d96d9100-b677-11e8-9efe-0a4f9eae5b88.png)

### Environment
* AdGuard AdBlocker extension version: 2.10.8
* Firefox 61.0.2 (64-bit)

**Comment by ameshkov** [comment]
Closing as we can no more reproduce it :)
