### ISSUE TITLE
[FF extension] soft98.ir $replace rule speed up

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/AdguardBrowserExtension#1107]
Sometimes on soft98.ir the $replace rule is getting applied a few seconds too late and user is getting adblock detection.

Any way to speed that up in FF extension?

You have to add the following rules to your user filter to test:

soft98.ir#@$#[class^="adz"] { max-height:0px!important; } 
soft98.ir#$#[class^="adz"] { display:none!important; }
`soft98.ir/templates/soft98_default/js/jquery$replace=/\|antibot\|[\s\S]*\|main\|download/\|antibot\|body\|main\|download/`

**Comment by Alex-302** [comment]
Try to escape `|`

**Comment by BlazDT** [comment]
I posted the wrong rule, this one is the current one:

soft98.ir/templates/soft98_default/js/jquery$replace=/\|antibot\|[\s\S]*\|main\|download/\|antibot\|body\|main\|download/

**Comment by ameshkov** [comment]
I don't really understand how does the replace speed can influence the detection on that website.

As I understand, what we do is removing the detection code, right?

**Comment by BlazDT** [comment]
We are changing it to body. In AdGuard for Windows the replace works everytimewith no detection, in Firefox not always. Especially when you freshly start the browser and open the site directly. Then when you refresh the site after getting detection, it works as it should.

**Comment by ameshkov** [comment]
> Especially when you freshly start the browser and open the site directly.

Maybe, it is caused by the extension being in process of initialization at that moment.

What if the browser was started for some time, is it possible to reproduce it?

**Comment by BlazDT** [comment]
Then it happen very rarely.
