### ISSUE TITLE
For the statistics dimensions, use the very same filters groups as in the ad blocker settings

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#1108]
Note, that if the stats are empty for a given group, you should not list that group at all.

**Comment by zzebrum** [comment]
@ameshkov question is should there appear statistics for custom filters?

**Comment by maximtop** [comment]
I'll make them to appear in the statistics too

**Comment by maximtop** [comment]
![image](https://user-images.githubusercontent.com/17272769/50448462-7f48c100-0932-11e9-9c2e-09aca581003e.png)
Custom filters statistics is already shown
