### ISSUE TITLE
CSS/JS is still injected even when domain is in exclusions list

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#111]

**Comment by Mizzick** [comment]
Cannot reproduce

**Comment by einfallstoll** [comment]
I use Safari and have whitelisted "localhost". However, the extension still injects the script, which throws an CSP exception causing the debugger to run:

<img width="763" alt="image" src="https://user-images.githubusercontent.com/619048/82729509-5fb8f200-9cf8-11ea-9450-231a581aa936.png">

I would expect AdGuard to *not* inject any scripts into whitelisted pages.
