### ISSUE TITLE
Safari 12.0 blocks AdGuard browser extension 2.10.8

### ISSUE THREAD

**Issue by sergerosenthaler** [AdguardTeam/AdguardBrowserExtension#1110]
### Steps to reproduce

1. Install Safari 12.0 from macOS AppStore
2. Launch Safari 12.0
3. A dialog pops up with a message that AdGuard browser extension slows down the browser and will get disabled.

### Expected behavior
AdGuard browser extension should be compatible with Safari 12.0

### Actual behavior
Safari 12.0 blocks AdGuard browser extension. Enable it again in settings is possible, but the slow down warning persists. 

<details><summary>Screenshot:</summary>
![2018-09-18_14-41-43](https://user-images.githubusercontent.com/25068100/45688395-8c932a00-bb51-11e8-9ead-cec4302319a9.png)

</details>

<details><summary>Screenshot of the browser console:</summary>

</details>

### Your environment

* AdGuard AdBlocker extension version: 
* Environment name and version: Safari 12.0, AdGuard browser extension for Safari 2.10.8
* Filters you use in AdGuard:
* Any other browser extensions you have installed:

**Comment by ameshkov** [comment]
@sergerosenthaler hi! 

It's all there: https://adguard.com/en/blog/safari-adblock-extensions/
The new extension code will be published here: https://github.com/AdguardTeam/AdguardForSafari
