### ISSUE TITLE
Add Disconnect tracking protection list (as used by Firefox)

### ISSUE THREAD

**Issue by RobynScore** [AdguardTeam/AdguardBrowserExtension#1111]
Would it be a possibility to add [Disconnect's tracking protection](https://github.com/disconnectme/disconnect-tracking-protection/blob/master/services.json) list in the list of privacy filters? 

This might an option for users who want _third-party_ tracking protection without using ten-thousands of rules (incl. all those element hiding rules), for instance on mobile. It also might just complement existing filter lists (e.g. it includes Adobe Tag Manager, whereas Adguard's Spyware filter does not).

The link above does not point to the utterly incomplete lists that are associated with Disconnect (which used to be an option in uBlock) floating around the internet. This filter is the basis for Firefox's tracking protection. 

Only thing is that it is not a list in standard format, yet a JSON list with a fairly simple syntax.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/FiltersRegistry #106](https://github.com/AdguardTeam/FiltersRegistry/issues/106) via [**ZenHub**](https://www.zenhub.com/)
