### ISSUE TITLE
Add Better's tracking filter list

### ISSUE THREAD

**Issue by RobynScore** [AdguardTeam/AdguardBrowserExtension#1115]
Also in reference to [this forum post](https://forum.adguard.com/index.php?threads/better’s-list-of-trackers.28339/), would [this list](https://better.fyi/blockerList.txt) from [Better](https://better.fyi) not also suit Adguard users?

It is small in size, yet blocks many of the main trackers (incl. a few Adguard's Spyware filter misses), so this might be interesting as a lighter list for mobile users, or those concerned with performance.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/FiltersRegistry #105](https://github.com/AdguardTeam/FiltersRegistry/issues/105) via [**ZenHub**](https://www.zenhub.com/)
