### ISSUE TITLE
Update text on the settings page

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#1116]
1. Add "Learn more about it" link to the "self-promo" item: https://kb.adguard.com/en/general/search-ads-and-self-promotion

2. Add "Learn more about it" link to the browsing security item: https://kb.adguard.com/en/general/how-malware-protection-works

3. Add "Learn more about it" to the "Enable integration mode" item: https://kb.adguard.com/en/browser-extensions/integration-mode

4. Add "Learn more about it" to the "Send statistics for ad filters usage" item: https://kb.adguard.com/en/general/filter-rules-statistics

5. Unnecessary button: https://uploads.adguard.com/up04_r73jz_AdGuard_Settings.png

**Comment by ameshkov** [comment]
@maximtop check that it's done

**Comment by maximtop** [comment]
@ameshkov everything is done
