### ISSUE TITLE
Adguard description in Firefox contains non-utf characters

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#112]
http://forum.adguard.com/attachment.php?attachmentid=3951&d=1450954091

![extension](https://cloud.githubusercontent.com/assets/5947035/11994254/4ea7d164-aa4c-11e5-92dc-56b029e1533c.png)

**Comment by Mizzick** [comment]
So it's ok now?

**Comment by ameshkov** [comment]
@Mizzick yes, it's ok in 2.1.1
