### ISSUE TITLE
$extension modifier prevents first-party URL blocking

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1122]
### Steps to reproduce

1. Open http://example.org/
2. Add:
```
@@||example.org^$extension
||example.org/favicon.ico
```
### Actual behavior
`example.org/favicon.ico` is not blocked.

### Expected behavior
`example.org/favicon.ico` must be blocked.

### Your environment

* AdGuard AdBlocker extension version: 2.10.11
* Environment name and version: (e.g. Chrome 59.0.3071.115)

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/FiltersCompiler #22](https://github.com/AdguardTeam/FiltersCompiler/issues/22) via [**ZenHub**](https://www.zenhub.com/)

**Comment by ameshkov** [comment]
`$extension` must be unknown modifier to browser extensions...
