### ISSUE TITLE
Persist size, position, state (fullscreen/not-fullscreen) of the filtering log window

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardBrowserExtension#1125]
Если есть возможность, то сделайте, пожалуйста, сохранение с последующим восстановлением размера и положения окна журнала.

**Comment by XX-J** [comment]
Восстанавливается только положение окна. Размер окна не восстанавливается, а кнопка разворачивания окна во весь экран и вовсе не активна. Это как-то относится к багу в FireFox'e или ...?
<br>

----------
 AdGuard v4.0.181  |  FireFox v78.13 ESR  |  Win7SP1

**Comment by gork7777** [comment]
When you open the filtering log in Chrome and bring it well to the edges, there will be a space at the edges. This happens when you turn on the filtering log again.

<details><summary>Video</summary>

https://user-images.githubusercontent.com/35523759/182257441-a91dd9b8-705a-46a7-b35f-e407cf95dffa.mp4
</details>

**Comment by stanislav-atr** [comment]
@XX-J добрый день! Не получилось повторить, в консоли фильтрлога и расширения появляются ошибки?
Для фильтрлога `F12 > Console`
Для расширения, в поисковой строке фф: `about:debugging#/runtime/this-firefox`,` AdGuard AdBlocker > Inspect > Console`
https://user-images.githubusercontent.com/68852737/182336236-3641607d-274c-4230-9bfc-0cbfbbfdcac9.mp4

**Comment by stanislav-atr** [comment]
@gork7777 i've been able to reproduce this on Windows, 
it seems that thats how it's rendered when `screenLeft` is `0`.
do you experience this with other browsers?

**Comment by gork7777** [comment]
@stanislav-atr Yes. I'm experienced this with Edge, Opera and Chrome browsers. No problem in Firefox.

**Comment by stanislav-atr** [comment]
> When you open the filtering log in Chrome and bring it well to the edges, there will be a space at the edges. This happens when you turn on the filtering log again.

@gork7777, hi, thank you for report!
Do you experience this on some particular setup? Chrom or Windows only?

**Comment by gork7777** [comment]
> Do you experience this on some particular setup? Chrom or Windows only?

@stanislav-atr No I guess. I'm using stable channel update for Chrome (v104.0.5112.81). Just experienced this on Windows 10 - 21H2. Don't know other platforms. Let me know if you need any other settings or info.

**Comment by stanislav-atr** [comment]
@gork7777, this issue is only reproducible on Windows devices and i wasn't able to find anything from our side to cause this. This might be the way Windows renders tabs, but i might be wrong. Feel free to add more cases if such occur.
