### ISSUE TITLE
Replace obfuscated code with minified

### ISSUE THREAD

**Issue by maximtop** [AdguardTeam/AdguardBrowserExtension#1129]
Obfuscated code has to be replaced to minified code
For example, files bellow are obfuscated:
- d3.min.js
- deferred.min.js
- Dropbox-sdk.min.js
- moment-with-locales.min.js

Otherwise, chrome won't publish the extension to the store
https://blog.chromium.org/2018/10/trustworthy-chrome-extensions-by-default.html

**Comment by ameshkov** [comment]
@maximtop let's even use unminified.
