### ISSUE TITLE
Change manifest to indicate properly what's the latest Chrome version supported

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardBrowserExtension#1134]
Не обновляются (подгружаются) фильтры, не работает журнал, не (полностью) блокируется реклама.
Последняя нормально работающая версия Adguard'a - 2.9.2 .

 Вывод: допилить или повысить версию в манифесте.

___________________________________________________
Google Chrome v44.0.2403.157 (Win7SP1) - Adguard v2.10.11

**Comment by XX-J** [comment]
Версии 3.0.x (до 3.0.9 включительно) не работают вовсе.
Думал в #1315 и #1318 исправили это и относительно Chrome v44, но нет.

<details><summary>Показывает такие же меню:</summary>

Всплывающее меню значка на панели
![2019 03 16-2](https://user-images.githubusercontent.com/17948007/54476411-0f015b80-480e-11e9-859e-4450339d81d9.png)
----------
## **Страница настроек**
![2019 03 16-1](https://user-images.githubusercontent.com/17948007/54476414-188ac380-480e-11e9-96a5-5c4b80ce04bc.png)
</details>

**Comment by ameshkov** [comment]
@XX-J бета-версию попробовали?

**Comment by ameshkov** [comment]
> до 3.0.9 включительно

А, вижу. Ну самое новое что мы пробовали - версия 49. Версии еще старше мы уже поддерживать не будем.

**Comment by ameshkov** [comment]
> Вывод: допилить или повысить версию в манифесте.

@maximtop это вот верное замечение, что в манифесте нужно подправить

**Comment by maximtop** [comment]
> это вот верное замечение, что в манифесте нужно подправить
ага, добавь milestone

**Comment by XX-J** [comment]
А Вы манифест только у новых версий подправите или во всех после 2.9.2 ?
 Просто сейчас приходится использовать версию 2.9.2 распакованной (в режиме разработчика), чтобы она не обновлялась.

**Comment by ameshkov** [comment]
@XX-J только у новых, остальные нельзя менять - они уже опубликованы
