### ISSUE TITLE
Add "About" screen to the options page

### ISSUE THREAD

**Issue by floam** [AdguardTeam/AdguardBrowserExtension#1135]
In Adguard Settings, I was surprised that I was unable to quickly figure out what version of the adguard browser extension I had installed on Safari, after checking the changelog on github from the link at the bottom of the settings page. I had to go to the preferences panel.

The version number should be shown somewhere on the settings page, and next to the Changelog link makes sense to me.

**Comment by ameshkov** [comment]
Good idea, thank you!
