### ISSUE TITLE
Add desktop app version to abuse site report in integration mode 

### ISSUE THREAD

**Issue by moraks** [AdguardTeam/AdguardBrowserExtension#1139]
У меня установлена программа для windows, и расширение для управления Adguard в режиме интеграции. 
Если отправлять жалобу на пропущенную рекламу через "Пожаловаться на этот сайт" в контекстном меню расширения (работающего в режиме интеграции) в репорте указывается, что у меня установлено только расширение, а версию win программы проходится отдельно прописывать.

### Ожидание 
В репорте будет указана версия win программы (+ версия расширения), также будут перечислены фильтры из неё.

<details><summary>Скрин:</summary>

![123444](https://user-images.githubusercontent.com/20518047/47256130-d484d400-d4a4-11e8-8b31-57bb6f7a61db.jpg)

</details>

### Система
* Win 10 x64 - 1809 - latest update
* AdGuard desktop: beta ch 6.4.1739.4753
* AdGuard ext: 2.10.11
* Browser: Chrome latest beta, FF - latest stable release 

// не высокий приоритет 
// Могу на английском написать, если это важно

**Comment by zebrum** [comment]
@moraks включите в настройках десктопной версии AdGuard в разделе `Расширения` - `Помощник AdGuard`. Если отправлять жалобы через помощник, то он данные из приложения подтянет в форму. А через расширение невозможно передать настройки программы в форму репорта.
