### ISSUE TITLE
https://vk.com/feed

### ISSUE THREAD

**Issue by Light-on** [AdguardTeam/AdguardBrowserExtension#1140]
Здравствуйте. Перестала блокироваться вставка между новостями "Возможные друзья". Всегда скрывалось вручную как нежелательный элемент, а сейчас не срабатывает. Найдётся ли у вас какое-нибудь решение?

Браузер Google Chrome
Adguard extension 2.10.11

**Comment by ameshkov** [comment]
Здравствуйте!

Жалобы на такие вещи нужно вот сюда отправлять:
https://agrd.io/report

Либо в самом расширении нажмите на "пожаловаться на сайт".
