### ISSUE TITLE
Update Spam404 filter URL

### ISSUE THREAD

**Issue by MS-PC** [AdguardTeam/AdguardBrowserExtension#1143]
Updated:
`https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt`

Reference: [collinbarrett/FilterLists/Issue#595](https://github.com/collinbarrett/FilterLists/issues/595) & [gorhill/uBlock/Pull#3740](https://github.com/gorhill/uBlock/pull/3740)

**Comment by Alex-302** [comment]
Fixed
https://github.com/AdguardTeam/FiltersRegistry/pull/110
