### ISSUE TITLE
An issue with `#?#***:style()` rules

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1146]
### Steps to reproduce
Add `radikal.ru#?#.render_body_main:style(margin-top: 0 !important)` and open https://radikal.ru/lfp/c.radikal.ru/c27/1810/ac/e2cc7c7bc164.jpg/htm

### Actual behavior
~`display: none;` is applied to `.render_body_main`~
UPD:
`display: none;` is added by site script, and should be removed while page loading. AdGuard prevents to do it.

### Your environment

* AdGuard AdBlocker extension version: 2.10.13
* Environment name and version: (e.g. Chrome 59.0.3071.115)
* Filters you use in AdGuard:
* Any other browser extensions you have installed:

**Comment by maximtop** [comment]
@Alex-302 What did you expect from this rule?

**Comment by Alex-302** [comment]
This rule must apply `margin-top: 0 !important` to `.render_body_main`, not `display: none;`.
The same with desktop app. But in both cases not all these rules works wrong.
`#?#.base-page_left-side:style(overflow: auto !important)` - correct result;
`#?#.render_body_main:style(margin-top: 0 !important)` - incorrect result(`display: none;` applied).
Is not it ExtCSS bug?

**Comment by maximtop** [comment]
`#?#.base-page_left-side:style(overflow: auto !important)`
`#?#.render_body_main:style(margin-top: 0 !important)`
These rules are not supported in extension. Correct work of the first rule is coincidence
You should use extended CSS injection mask `#$?#` in order to apply cosmetic rules

@ameshkov maybe we should support such rules
If not then maybe we should warn users that they are incorrect?

**Comment by maximtop** [comment]
@Alex-302 if everything is clear with this issue, I close it

**Comment by Alex-302** [comment]
Definitely this is an issue. 
`radikal.ru#?#.render_body_main:style(margin-top: 0 !important)` works as it should in uBO.

**Comment by ameshkov** [comment]
Re-assigned to v3.3_patch1

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/ExtendedCss #92](https://github.com/AdguardTeam/ExtendedCss/issues/92) via [**ZenHub**](https://www.zenhub.com/)
