### ISSUE TITLE
Typo Polish translation

### ISSUE THREAD

**Issue by krystian3w** [AdguardTeam/AdguardBrowserExtension#1147]
[AdguardBrowserExtension/search?q=Widźety&unscoped_q=Widźety](https://github.com/AdguardTeam/AdguardBrowserExtension/search?q=Wid%C5%BAety&unscoped_q=Wid%C5%BAety)

<ul>

https://github.com/AdguardTeam/AdguardBrowserExtension/blob/e11014fc2f15a6775f91b910616145f7d26a31ea/Extension/filters/chromium/filters_i18n.json#L261

https://github.com/AdguardTeam/AdguardBrowserExtension/blob/e11014fc2f15a6775f91b910616145f7d26a31ea/Extension/filters/edge/filters_i18n.json#L261

https://github.com/AdguardTeam/AdguardBrowserExtension/blob/e11014fc2f15a6775f91b910616145f7d26a31ea/Extension/filters/firefox/filters_i18n.json#L261

https://github.com/AdguardTeam/AdguardBrowserExtension/blob/e11014fc2f15a6775f91b910616145f7d26a31ea/Extension/filters/opera/filters_i18n.json#L261

https://github.com/AdguardTeam/AdguardBrowserExtension/blob/e11014fc2f15a6775f91b910616145f7d26a31ea/Extension/filters/safari/filters_i18n.json#L261

</ul>

Correct: `Widżety` - exchange of `ź` to `ż`.

**Comment by ameshkov** [comment]
@aalpatkina please fix this on https://adguard.oneskyapp.com/

**Comment by aalpatkina** [comment]
fixed

**Comment by ameshkov** [comment]
@Mizzick we need to update translations in Filters registry now
