### ISSUE TITLE
Show applied rules with `::before` and `::after` in filtering log

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1148]
Example:
https://hotline.ua/computer-videokarty/evga-geforce-gtx-1080-sc-gaming-acx-30-08g-p4-6183-kr/
Gray overlay
![image](https://user-images.githubusercontent.com/8361299/48785837-39268f00-ecee-11e8-9694-629d669ccfdf.png)
the rules
```
hotline.ua#$#body.reset-scroll:before { z-index: -9999!important; display: none!important; }
hotline.ua##body.reset-scroll::before
```
These rules are working.
Check without annoyances filter in private tabs.

https://github.com/AdguardTeam/FiltersCompiler/issues/33

**Comment by maximtop** [comment]
Currently, we don't count rules applied to the pseudo elements
