### ISSUE TITLE
Change context menu

### ISSUE THREAD

**Issue by maximtop** [AdguardTeam/AdguardBrowserExtension#1150]
Remove nested links to settings and use only one link to the settings 
https://uploads.adguard.com/mtopciu_7lzm5.png

**Comment by ameshkov** [comment]
Too many menu items now:
https://uploads.adguard.com/up04_c00po_Monosnap.png

Here's how they should be sorted to get "check filters updates" back to the menu:
https://uploads.adguard.com/up04_a63l0_Example_Domain.png

**Comment by maximtop** [comment]
In Chrome <72 separators don't work
https://bugs.chromium.org/p/chromium/issues/detail?id=904220

Also, separators don't work in Chrome 73 if select some text or image before the context menu called
