### ISSUE TITLE
UI issues

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#1154]
Here is the list of UI issues that we should resolve

* `General Settings` --> `General` (https://uploads.adguard.com/up04_t0gbh_AdGuard_Settings.png)
* See the filters layout changes: https://share.goabstract.com/8f0486ed-53d2-43e5-a42c-319d2f19b145 (@maximtop you can start doing it already)
* "delete" filter position: https://uploads.adguard.com/up04_jkdo6_AdGuard_Settings.png
* Fix the notification layout: https://uploads.adguard.com/up04_5jyjv_AdGuard_Settings.png (do not forget to check how it looks in firefox and edge https://uploads.adguard.com/mtopciu_tsugt.png) 
* Sort out the browser action footer. Let's get rid of the "Other AdGuard versions" footer and replace it with a simple Adguard website link.

**Comment by AlikhanAliev** [comment]
https://share.goabstract.com/13794ce2-05f3-4b77-bff7-d4f63be8e86f

https://share.goabstract.com/63a85cc0-8aea-412e-a7d7-437e92dae830
