### ISSUE TITLE
[FireFox Extension] forum.golem.de - $$ rules are not applied

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/AdguardBrowserExtension#1156]
https://github.com/AdguardTeam/AdguardFilters/issues/26500

`golem.de$$script[max-length="0"]` should normally remove all scripts, but they aren't. Please check and `golem.de$$script[tag-content=".UABPd"][min-length="20000"][max-length="150000"]`

**Comment by ameshkov** [comment]
Needs to be re-tested with v3.0

**Comment by Mizzick** [comment]
Cannot reproduce in 3.0

**Comment by BlazDT** [comment]
Please reopen, currently still reproducable with latest beta.

**Comment by maximtop** [comment]
> Please reopen, currently still reproducable with latest beta.
> Also reproducable on example.org with example.com$$div[max-length="0"]

@BlazDT 
rule should be not for example.**com**, but for example.**org** -> `example.org$$div[max-length="0"]`

and it seems to work in my firefox.

**Comment by BlazDT** [comment]
Yes, you are correct. Working fine. Thought I typed example.com into address bar.

**Comment by XX-J** [comment]
А у меня не работает.

Вставил оба правила: `example.org$$div[max-length="0"]` и `example.com$$div[max-length="0"]`, перешёл на соответствующие сайты и... ничего. Правила эти, как я понимаю, должны вырезать из страницы div'ы, но у меня всё на месте.

 И вообще, давно заметил, что правила вырезания элементов из страницы у меня вообще никогда не работали, хоть и написано в инструкции по составлению собственных правил фильтрации что поддерживается расширение для Firefox. Я понимаю безперспективность их использования в отсутствии унификации, но всё же...
___________________________________________________
Mozilla Firefox v53.0.3 (Win7SP1) - Adguard v3.0.13

**Comment by ameshkov** [comment]
`max-length=0` лишний

**Comment by XX-J** [comment]
Проверил на обоих доменах: `example.org$$div` и `example.com$$div` - НЕ вырезает ни там, ни там.

**Comment by ameshkov** [comment]
Может быть из-за того что FF старый?
