### ISSUE TITLE
Ignore scriptlets and snippets properly

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#1159]
@ameshkov commented on [Wed Dec 05 2018](https://github.com/AdguardTeam/CoreLibs/issues/646)

There are some ABP- and uBO- specific rules that we should process gracefully:

* snippets: `#$#snippet_name(param, param)`
* uBO HTML filters: https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#html-filters
* uBO scriptlet injections: https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#scriptlet-injection

**Comment by Mizzick** [comment]
About the snippets,
we actually have css inject rules with the very same mask:
https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#cosmetic-css-rules-syntax-1

**Comment by Mizzick** [comment]
Test instructions:
- add rules mentioned in subject to user filter
- check the rules has no effect in filtering
- check logs in background page, rules count should be the same as without these rules.
