### ISSUE TITLE
Third-party rules do not block 4-th level subdomains

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#116]
The source:
https://github.com/AdguardTeam/ExperimentalFilter/issues/1192

The problem:
1. We have a rule ```||innity.net^$third-party```
2. For some reason this rule is not applied to ```https://ssl-cdn.media.innity.net/lib/global.js```

**Comment by Mizzick** [comment]
```Content blocker prevented frame displaying http://cn.cari.com.my/portal.php from loading a resource from https://ssl-cdn.media.innity.net/lib/global.js
Content blocker prevented frame displaying http://cn.cari.com.my/portal.php from loading a resource from http://partner.googleadservices.com/gpt/pubads_impl_78.js```
As I can see in console, global.js is blocked and on the next line an other 4-th level domain is blocked. So everything is fine?

**Comment by ameshkov** [comment]
No, it's not fine.

partner.googleadservices.com - is 3rd level subdomain.
And ```ssl-cdn.media.innity.net``` currently is blocked due to the ```||media.innity.net^$third-party``` I've added in https://github.com/AdguardTeam/ExperimentalFilter/issues/1192

Just disable "Safari filter" and it won't be blocked again.

**Comment by ameshkov** [comment]
The same issue with exception rules:
```
Content blocker prevented frame displaying http://www.pornhub.com/ from loading a resource from http://cdn1b.static.pornhub.phncdn.com/images/categories/118x88/7.jpg
```

While here is the rule that should unblock it:
```
@@||pornhub.phncdn.com^$image,object-subrequest,domain=pornhub.com|redtube.com|tube8.com|tube8.es|tube8.fr|youporn.com|youporngay.com
```

**Comment by Mizzick** [comment]
Fixed, the issue was in incorrect regexp:
"url-filter": "^https?://[^.]*\\.?test-elemhide\\.com"
changed to:
"url-filter": "^https?://[^.]*\\.*?test-elemhide\\.com"

**Comment by ameshkov** [comment]
Hm, seems that the incorrect regexp has became even more incorrect...

**Comment by Mizzick** [comment]
What?
The previous matches only one domain level up, cause it allows only one dot character before the domain name.

**Comment by ameshkov** [comment]
Right. The same as your new version.

**Comment by Mizzick** [comment]
```https?:\/\/[^.][^/]*\.?domain\.com```

**Comment by ameshkov** [comment]
verygooddomain.com is matched by this regexp:
http://www.regexr.com/3cg43

**Comment by ameshkov** [comment]
Huh, I think we had the same issue with a previous regexp too

**Comment by Mizzick** [comment]
I don't think it's a bug.

**Comment by ameshkov** [comment]
I am pretty sure this is wrong.
```||domain.com``` should match domain.com and it's subdomains and SHOULD NOT match other domains.

**Comment by Mizzick** [comment]
This regexp preffix is used not only for || rules

**Comment by ameshkov** [comment]
In fact it is used for ```||``` prefixes only.

url-filter-rule:
```
    if (StringUtils.startWith(regex, UrlFilterRule.MASK_START_URL)) {
        regex = UrlFilterRule.REGEXP_START_URL + regex.substring(UrlFilterRule.MASK_START_URL.length);
```

converter:
```
urlFilter = StringUtils.replaceAll(urlFilter, UrlFilterRule.REGEXP_START_URL, URL_FILTER_REGEXP_START_URL);
```

**Comment by ameshkov** [comment]
We may ignore this for now and use even simpler regexp:
```
https?:\/\/[^/]*\.?domain.com
```

Or we can try a bit more complex version that works properly:
```
https?:\/\/([^/]*\.)?domain.com
```

The question is: what's the difference in terms of performance if we use the second regexp?

**Comment by Mizzick** [comment]
Okay changed to https?:\/\/([^/]*\.)?domain.com

**Comment by ameshkov** [comment]
What with performance test? What's the difference?

**Comment by Mizzick** [comment]
var regExp3 = new RegExp('^https?://([^/]*\\.)?some-domain.com\\.com[/:&?]?', 'i');
base-test.js:52 2015-12-29T15:41:05.270Z DEBUG Elapsed: 127ms
base-test.js:52 2015-12-29T15:41:05.377Z DEBUG Elapsed: 107ms
base-test.js:52 2015-12-29T15:41:05.377Z DEBUG Performance gain: 16%

var regExp4 = new RegExp('^https?://[^/]*\\.?some-domain.com\\.com[/:&?]?', 'i');
base-test.js:52 2015-12-29T15:41:05.509Z DEBUG Elapsed: 131ms
base-test.js:52 2015-12-29T15:41:05.608Z DEBUG Elapsed: 98ms
base-test.js:52 2015-12-29T15:41:05.609Z DEBUG Performance gain: 26%

**Comment by ameshkov** [comment]
Ok then. You'd better increase converter version
