### ISSUE TITLE
[Filtering log] If element is hidden by few rules, print all applied rules

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1160]
For example, FuckAdblock script check visibility of element with classes
`.pub_300x250.pub_300x250m.pub_728x90.text-ad.textAd.text_ad.text_ads.text-ads.text-ad-links`
At the moment, AdGuard prints only one applied rule.
It can be checked on this site:
https://www.gs.by/2018/11/08/vnimanie-novyj-fotokonkurs-zveryo-moyo/

**Comment by Alex-302** [comment]
ping

**Comment by ameshkov** [comment]
This one is quite complicated actually
