### ISSUE TITLE
Contradicting UI text on failed filter update

### ISSUE THREAD

**Issue by leonschmidlin** [AdguardTeam/AdguardBrowserExtension#1166]
When trying to update filters e.g. without internet connection, the Adguard UI Popup says "Filters updated successfully. Failed to get updates. Please try again later." in a black-green color scheme.

Expected behavior
Change "Filters updated successfully" in case of failed update. Maybe change the green UI strip to red.

<details><summary>Screenshot:</summary>

<img width="460" alt="screenshot 2018-12-07 at 10 41 31" src="https://user-images.githubusercontent.com/27723630/49642467-6aec6500-fa13-11e8-9d37-02038301be84.png">

</details>

AdGuard AdBlocker extension version: 2.10.13
Browser: Firefox 63.0.3, Safari 12.0.1, Chrome 70.0.3538.110 and 71.0.3578.80

**Comment by ameshkov** [comment]
@zzebrum please check if this is fixed in v3.0 branch

**Comment by zzebrum** [comment]
no contradiction message in v3.0, but there is a related error: #1173
