### ISSUE TITLE
'Hide referer third-parties' doesn't work (Privacy section)

### ISSUE THREAD

**Issue by aspasskaya** [AdguardTeam/AdguardBrowserExtension#1168]
### Steps to reproduce
1. Go to 'Privacy' and enable 'Hide referer third-parties'
2. Open google.com
3. Tap on https://browserleaks.com/ip and http://www.xhaus.com/headers so you will be redirected to the website, it'll open in new tab
4. Check for referer

### Expected behavior
https://browserleaks.com/ip and http://www.xhaus.com/headers

### Actual behavior
https://google.com

#
https://monosnap.com/file/K1wkCXAqKDDkKQ1COBv0Rv3Qt01ET8
https://monosnap.com/file/VPyY9uy3xFyIBOMRwmAt03QjwDZR8T
https://monosnap.com/file/ziiU7SvURfzls32XO0znRfwXrhAu6y

### Your environment
* Chrome Extension 3.0
* Chrome 71.0.3578.80
* Win 10 64 bit

**Comment by karina-archazh** [comment]
Same for MS Edge and FireFox.
there is no any particular changes with on and off privacy options.
