### ISSUE TITLE
Select another Element should be relabled select a different Element

### ISSUE THREAD

**Issue by Samuel12321** [AdguardTeam/AdguardBrowserExtension#1169]
### Steps to reproduce

1. Click on the adguard icon 
2. Select Block ads on this website
3. Select an ad
4. Click select another element 

### Expected behavior
Adguard should allow the user to select an additional ad as well, as "select another element" suggests an additional element as well as the one already selected.
### Actual behavior
Previous selected elements are discarded and the user is allowed to select an add to block

If this is intentional the button should be relabled "select a different element", if not there is a bug.

### Your environment

* AdGuard AdBlocker extension version: 2.10.14
* Environment name and version: Chrome 70.0.3538.110
* Filters you use in AdGuard: AdGuard Base filter, AdGuard Spyware filter, AdGuard Social Media filter, AdGuard Annoyances filter, Adblock Warning Removal List
* Any other browser extensions you have installed:

**Comment by ameshkov** [comment]
That's intended behavior so I guess we should rename the button:
`Select another element` --> `Select a different element`
