### ISSUE TITLE
JS rules load order is wrong (in any extension)

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#117]
**Steps to reproduce:**
1. Add this rule to the user filter:
```
lenta.ru#%#AG_onLoad(function() { alert('1'); });
```

2. Go to lenta.ru, you'll see alert there
3. Restart the browser and go to lenta.ru again

**Result:**
Instead of alert you'll see error in the browser console:
```
Error executing AG js: ReferenceError: AG_onLoad is not defined
```

**Solution:**
Rules from the user filter MUST BE loaded after all other filters are loaded.

**Comment by Mizzick** [comment]
Fixed

**Comment by atropnikov** [comment]
https://github.com/AdguardTeam/AdguardBrowserExtension/pull/119
See last comment from ameshkov

**Comment by ameshkov** [comment]
Fixed:
https://github.com/AdguardTeam/AdguardBrowserExtension/commit/1d57490fe81a7c7c46c82cbedbf02d0dde7c6637
https://github.com/AdguardTeam/AdguardBrowserExtension/commit/365052d39eebfa3e54d6ad2e4c99dcbdcc8cef87
