### ISSUE TITLE
Transparent pop-up description in filter section for disabled filters

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardBrowserExtension#1171]
It should be the same as for enabled filters: https://uploads.adguard.com/AdGuard_Settings_2018-12-10_13-50-08.png

What else needs to be done for filters section: https://app.goabstract.com/projects/e98440d0-c706-11e8-a44d-f7faae7452b5/branches/c6c3a020-ebd9-11e8-8287-9d6a4e6dbc23/commits/7308c78f4a24b369c8be50c13a68491dec21b443/files/CF7DF434-049D-4CD4-9297-877FF7F4763F/layers/D5B98C8B-7666-4C77-B873-8A694A196E20?mode=design

**Comment by maximtop** [comment]
fixed while doing #1154
