### ISSUE TITLE
The rules, pasted from the clipboard, are not saved [Filter editor]

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1172]
### Steps to reproduce

1. Paste any text;
2. Close the window after saving;
3. Open filter editor.

### Actual behavior
Filter editor is empty(or recent changes are not saved).

* AdGuard for Safari 1.1.0

**Comment by ameshkov** [comment]
Should be backported to AG for Safari as well

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdGuardForSafari #96](https://github.com/AdguardTeam/AdGuardForSafari/issues/96) via [**ZenHub**](https://www.zenhub.com/)

**Comment by maximtop** [comment]
This is already done in extension
