### ISSUE TITLE
Error when updating filters if a network is unavailable

### ISSUE THREAD

**Issue by aspasskaya** [AdguardTeam/AdguardBrowserExtension#1173]
### Preconditions
Filters - base, spyware, social, annoynces, useful ads, rus + custom - rules for websocket rules tests
Enable in Extension settings - collect error data
### Steps to reproduce
1. Disable network
2. Update the filters

### Expected behavior
Filters updated correctly.

### Actual behavior
Error - 2018-12-07T12:00:04.068Z: Error retrieved response from server for filters [10,14,1,2,3,4], cause:

#
https://uploads.adguard.com/2.jpeg
https://uploads.adguard.com/5.jpeg

### Your environment
* Chrome Extension 3.0
* Chrome 71.0.3578.80
* Win 10 64 bit

**Comment by maximtop** [comment]
This behavior is deliberate.
There is correct update notification popup that it is impossible to update filters
https://uploads.adguard.com/mtopciu_vitvg.png
Also, extension writes the error to the console.
