### ISSUE TITLE
Extension main page doesn't fully loading in private mode

### ISSUE THREAD

**Issue by karina-archazh** [AdguardTeam/AdguardBrowserExtension#1175]
### Steps to reproduce

1. Open MS EDGE settings
2. Allow AG extension work in Private Mode
3. Open new tab in Private Mode

### Expected behavior
Extension menu should be available by clicking on it

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/41899455/49785277-16a5f580-fd31-11e8-81bb-afa6079178e9.png)

</details>

### Your environment

* AdGuard AdBlocker extension version: 3.0
* Environment name and version: Ms Edge 17.17

**Comment by zzebrum** [comment]
@maximtop can't repro the issue, neither do I. 
If the issue is still reproducible, please provide with a screenshot of browser console.
