### ISSUE TITLE
MS Edge: User Filter tests doesnt work on AdGuard test page

### ISSUE THREAD

**Issue by karina-archazh** [AdguardTeam/AdguardBrowserExtension#1176]
### Steps to reproduce

1. Go to http://testcases.adguard.com/
2. Add rules from simple rules test to user filter
3. Return to test page

### Expected behavior
All test should be passed

### Actual behavior
For this browser following test doesn't work:
simple rules
generic hide rules
extended css

### Your environment

* AdGuard AdBlocker extension version: 3.0
* Environment name and version:Edge 17.17

**Comment by zzebrum** [comment]
Seems to be working. It takes some time to apply added rules. @karina-archazh please recheck on your device.
