### ISSUE TITLE
Block WebRTC doesnt work in Edge and FF

### ISSUE THREAD

**Issue by karina-archazh** [AdguardTeam/AdguardBrowserExtension#1179]
### Steps to reproduce

1. Run AG extension
2. Open for check webrtc https://browserleaks.com/webrtc

### Expected behavior
![image](https://user-images.githubusercontent.com/41899455/49855243-9b5e4580-fdfd-11e8-9b40-3ce46cd0ab1e.png)

### Actual behavior
With Adguard privacy on and off there no any changes on webrtc page

<details><summary>Screenshot:</summary>

FF

![image](https://user-images.githubusercontent.com/41899455/49855167-6a7e1080-fdfd-11e8-80a6-4cc4115d09b1.png)

edge
![image](https://user-images.githubusercontent.com/41899455/49855187-7a95f000-fdfd-11e8-8315-37fe0aa57cab.png)

</details>

**Comment by aspasskaya** [comment]
In Chrome extension is also a problem.
https://uploads.adguard.com/Untitled.jpeg

**Comment by maximtop** [comment]
This feature is not working for the EDGE browser.
@ameshkov do I correctly understand that testers should check only that IP address is not detectable?

**Comment by ameshkov** [comment]
> This feature is not working for the EDGE browser.
> @ameshkov do I correctly understand that testers should check only that IP address is not detectable?

We should also hide this option in Edge
