### ISSUE TITLE
Mac and Android symbols on footer of main window doesn't located right

### ISSUE THREAD

**Issue by karina-archazh** [AdguardTeam/AdguardBrowserExtension#1199]
### Steps to reproduce

1. Add AG extension to broweser
2. Tap on AG Icon
3. Close "Premium ad@ on footer 

### Expected behavior
Mac and Android symbols should be in line

### Actual behavior

![image](https://user-images.githubusercontent.com/41899455/50354875-f01c6180-055d-11e9-9943-e073800e62f1.png)

### Your environment
For all tested devices

**Comment by AlikhanAliev** [comment]
AdGuard для Мобильных

**Comment by ameshkov** [comment]
@AlikhanAliev the HTML layout must be ready for a string of **any length**
