### ISSUE TITLE
Applied element hiding rules are not visible in filtering log in some cases

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1200]
### Steps to reproduce

1. Log in to e.mail.ru

### Actual behavior
Applied rule is not shown in filtering log `e.mail.ru##div[class^="b-letter"] div.b-rb:has(> div)`
After applying the ryle, anti-adblock script obfuscate html tags.

### Expected behavior
The rule is visible in the log.

### Your environment

* AdGuard AdBlocker extension version: 2.10.14 / 3.0
* Environment name and version: Chrome 70
* Filters you use in AdGuard: Eng(Base), Rus

**Comment by maximtop** [comment]
`Memo for myself`
The extension should check all mutation records if the filtering log is open despite the performance

**Comment by maximtop** [comment]
In order to test you can repeat steps described by the topic starter

**Comment by Alex-302** [comment]
That rule is removed. Add it to user filter.
