### ISSUE TITLE
Long URL in Custom filters causes horizontal scroll

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardBrowserExtension#1202]
Go to AG settings - Filters - Custom, try to add a custom filter 
https://uploads.adguard.com/AdGuard_Settings_2018-12-25_17-05-24.png

**Comment by karina-archazh** [comment]
Still persist in Chrome 71. for Mac
<details> 

![image](https://user-images.githubusercontent.com/41899455/50449697-fa61a580-0939-11e9-97ff-8b98680c78ab.png)
</details>

**Comment by zzebrum** [comment]
@karina-archazh are you sure you have the latest build? :)
anyway, now a link is cut short. but no horizontal scroll for me )

**Comment by zzebrum** [comment]
https://uploads.adguard.com/Windows_10_64_bit_Inside_preview_2019-07-03_12-47-38.png
Edge v44.18922.1000.0
AdGuard v3.2.1
