### ISSUE TITLE
Editor is marked "editing" and "saved" when switching between Inverted whitelist and regular Whitelist

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardBrowserExtension#1208]
Similar to https://github.com/AdguardTeam/AdGuardForSafari/issues/95
but in Whitelist section. Reproduced with empty and filled lists.

**Comment by maximtop** [comment]
I think that it is right that it indicates about saving when there are some rules in the white rules list
With the empty list, I couldn't reproduce in the firefox and chrome 

Also, there is no saving indicator in the user list rules at all if rules are already saved

Maybe you can provide more specific instructions?
