### ISSUE TITLE
Let users specify a custom filter title

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#1209]
Besides the URL, we should let people specify the filter name when adding a new custom filter.

**Comment by aspasskaya** [comment]
There is no possibility to give a new name if there is a header for the filter.

![image](https://user-images.githubusercontent.com/43952607/52945870-ca57e100-3383-11e9-99a1-d7e336d02c5c.png)
![image](https://user-images.githubusercontent.com/43952607/52945946-f4a99e80-3383-11e9-8097-8abb57532821.png)
