### ISSUE TITLE
Please update translations of the extension and Stealth Extension.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardBrowserExtension#1218]
@ameshkov 
@aalpatkina

Today, I just finished all Traditional Chinese translations (**zh-TW**) in the projects of **Extension** and **Stealth Extension**.

1. Please don't forget to add a placeholder in the back of "Powered by" on onesky.
https://github.com/AdguardTeam/StealthMode/issues/21
https://github.com/AdguardTeam/Recovery/issues/9

2. May you update translations of the Extension and Stealth Extension in the next version?

3. I want to translate the descriptions on Chrome WebStore, Addons Mozilla Org and Windows Store (Edge) to Traditional Chinese.
But they're tooooooo much!
May you simplify them?
I don't think users will patiently read the long descriptions.
We should just give succinct but clear introductions on app/extension store.
I suggest the length of descriptions for AG for Safari (AppStore Desc) or AdGuard content blocker on Google Play is suitable.

Thanks.

**Comment by ameshkov** [comment]
Thank you:)

Regarding the stealth extension, we're going to take it down as the main extension now has the same functionality.

Regarding web store description, @aalpatkina could you please check what do we have there? We can supply a short version for translators and use longer versions in English for instance.

**Comment by lancelot-moon** [comment]
After checking v3.0.1 beta, I found some issue of translations.

1. It will lead to an English Configuration page.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/Vcs2VdK.png)
</details><br/>

2. I early updated the translations of security and language-specific in Miscellaneous / Miscellaneous.
But why do they show outmoded translations?
I think that filters' translations on your server were updated before.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/GpwmpHv.png)
</details><br/>

In AG for Android, I also have the similar problem.
The translations of filters categories' names and their tags' descriptions are outmoded.
I must ever enable and update the filters, and then they will become the latest translations.

**Comment by ameshkov** [comment]
Uh, there's a lot to do:)

@maximtop 

> You wrongly use Simplified Chinese for AG Assistant.
> There is already Traditional Chinese (zh_TW) for AG Assistant, but you often wrongly use Simplified Chinese (zh or zh_CN) in Traditional Chinese interface...

This one is obviously a bug, we should deal with it.

**Comment by lancelot-moon** [comment]
About date format in Chinese:
https://www.ibm.com/support/knowledgecenter/en/SSS28S_3.0.0/com.ibm.help.forms.doc/locale_spec/i_xfdl_r_formats_zh_Hant_TW.html

**Comment by lancelot-moon** [comment]
@maximtop

**Comment by ameshkov** [comment]
3. Ops, my bad. We don't plan to translate these

**Comment by lancelot-moon** [comment]
@maximtop 
3. At least, Third party, Blocked, Whitelisted are translated in the filtering log of AG for Windows.
7. Just localize AdGuard's company name with formal translations.
Ltd. = 株式会社 (Japanese) = 有限公司 (Chinese Traditional)
It's a formal local translation when a company applies for enrollment in Japan or Taiwan.
10. Wait until v3 release version.

Well, it's only my suggestions.

**Comment by ameshkov** [comment]
3. We don't want to translate developer-related strings (and tbh, we shouldn't have translated them in AG for Win).
7. Company names are "proper names", and generally, they shouldn't be translated.

**Comment by lancelot-moon** [comment]
So Google, Microsoft, Intel and so on have "Traditional Chinese proper names" in Taiwan, not only use Ltd.
Well, just different thought.
