### ISSUE TITLE
[Filtering log] Filter column is empty for cookie

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1219]
![image](https://user-images.githubusercontent.com/8361299/50511338-f3e84080-0a95-11e9-91ec-ba207be7cfed.png)

**Comment by maximtop** [comment]
To test if the issue is resolved
1. Turn on `Self-destructing third-party cookies` and/or `Self-destructing first-party cookies`
2. Open some site
3. Check if cookies are blocked and filter name is `Stealth mode`
