### ISSUE TITLE
Invalid rule is constructed by "Block ad on this website" feature

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#122]
**Source:**
http://forum.adguard.com/showthread.php?8445-%D0%9E%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B0-%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D0%B0-%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F

**Steps to reproduce:**
1. Open http://demo.phpbb3styles.net/viewtopic.php?style=10&f=13&t=2185
2. Adguard - Block ad on this website
3. Select an avatar image
4. Open "Advanced settings" and choose "Block element by URL" there
5. The rule will be:
```
./download/file.php?avatar=4561_1261193879.png$domain=demo.phpbb3styles.net
```

This rule won't work. The proper rule is:
```
/download/file.php?avatar=4561_1261193879.png$domain=demo.phpbb3styles.net
```

**Comment by Mizzick** [comment]
The rule with the dot works fine!

**Comment by ameshkov** [comment]
The problem is specific to Firefox:)

**Comment by Mizzick** [comment]
Ok, fixed
