### ISSUE TITLE
Make new permissions optional

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#1220]
https://stackoverflow.com/questions/13652969/upgrading-permissions-of-a-chrome-extensions

We need `privacy` permission for blocking web RTC.

So the idea is to request this permission when user enables this feature or when the user enables stealth mode when blocking webRTC is enabled. 

Additionally, we should check that FF extension is not disabled after update.

**Comment by ameshkov** [comment]
Another issue is Firefox: https://uploads.adguard.com/up04_erpif_Monosnap.png

It does not allow adding `privacy` to the list of optional permissions so we should test how automatic update looks like.

**Comment by maximtop** [comment]
Privacy permissions can be optional only in the chrome.
In order to check if the issue is resolved:
1. install the extension from the scratch
2. enable stealth mode
3. enable Block WebRTC setting
4. the extension should ask you to grant privacy permissions
