### ISSUE TITLE
Some ads are not blocked adter update from 2.10 to 3.0

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1228]
or the filters are old even after update. Afler clean install I can't reproduce it.

### Steps to reproduce
1. Update 2.10 to 3.0;
2. Enable annoyances filter; 
3. Check for filters update;
4. Visit https://wm.exchanger.ru/asp/wmlist.asp;

### Actual behavior

<details>

![image](https://user-images.githubusercontent.com/8361299/50523238-aa204a00-0ad7-11e9-803b-846857bcfe2d.png)

</details>

### Expected behavior

<details>

![image](https://user-images.githubusercontent.com/8361299/50523253-be644700-0ad7-11e9-8dc0-2410c144453b.png)

</details>

Another example:
https://4pda.ru/forum/index.php?act=idx

<details>

![image](https://user-images.githubusercontent.com/8361299/50523306-0daa7780-0ad8-11e9-9e32-eaab8d2ceed7.png)

</details>

### Your environment

* AdGuard AdBlocker extension version: 3.01
* Environment name and version: Chrome

**Comment by ameshkov** [comment]
@Alex-302 the bug is caused by https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1227

You need to disable and then enable back filters groups
