### ISSUE TITLE
Cookie rues are applied in integration mode

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1231]
### Steps to reproduce
1. Run AdGuard for Windows
2. Add `google.com$cookie=SAPISID` to extension
3. Open https://www.google.com/

### Actual behavior

![image](https://user-images.githubusercontent.com/8361299/50537937-a3451600-0b6f-11e9-9f76-a117d3a388b7.png)

### Your environment

* AdGuard AdBlocker extension version:  3.0.2
* Environment name and version: Chrome

**Comment by maximtop** [comment]
To test if the issue resolved
1. Launch AdGuard for desktop
2. Open google.com
3. Find some cookie present in the developer tools
4. Block the cookie with user filter rule `||google.com^$cookie={cookie_name}`
5. Check in the filtering log that the cookie wasn't blocked
6. Turn off integration mode
7. Check that the cookie is removed or modified

**Comment by maximtop** [comment]
Actually, this issue cannot be reproduced in the new beta version, but there are other stealth mode options applied to the page.
I've created a new issue #1269
