### ISSUE TITLE
Import settings doesn't importing filters group settings

### ISSUE THREAD

**Issue by karina-archazh** [AdguardTeam/AdguardBrowserExtension#1232]
https://monosnap.com/file/IZKgrTHg1frnTokpgXbcaJHgU1sbCd
1. Disable all of groups switches
2. Export settings
3. Enable all of groups switches
3. Import this settings
4. Check groups switches

### Expected behavior
Switches should be disable as exported.
### Actual behavior
Nothing changes.

**Comment by maximtop** [comment]
fixed in the pull request #340
