### ISSUE TITLE
Filtering log is not working as it should in Opera

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1234]
### Steps to reproduce
1. Open `yandex weather`
2. Look to the filtering log.

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/50548917-360fae80-0c5d-11e9-87b6-6a82f2e35c7a.png)

</details>

### Your environment

* AdGuard AdBlocker extension version: 3.0.3
* Environment name and version: Opera 57.0.3098.106

**Comment by maximtop** [comment]
In Opera you should allow access to search page results 
https://uploads.adguard.com/mtopciu_3ai78.png
