### ISSUE TITLE
`badfilter` modifier is not working with `stealth` exclusions

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1236]
### Steps to reproduce

1. Open https://trade.aliexpress.com/
2. Add `@@||trade.aliexpress.com$stealth,badfilter`

### Expected behavior
Stealth mode exclusion `@@||trade.aliexpress.com$stealth`  ***is*** disabled

### Actual behavior
Stealth mode exclusion `@@||trade.aliexpress.com$stealth`  ***is not*** disabled.

* AdGuard AdBlocker extension version: 3.0.3
* Environment name and version: Chrome
* Filters you use in AdGuard: Base filter

**Comment by ameshkov** [comment]
@Alex-302 can you also check if it works on CoreLibs versions of AG?
