### ISSUE TITLE
Ads are not blocked in Safari when the browser is just started

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#124]
Content blocker is initialized after the homepage is loaded.

In old extension we've been doing a page cleanup (and CSS injection) after extension initialization. But in the new one we don't do it.

@Mizzick can we reuse the same way in new version?

**Comment by Mizzick** [comment]
Fixed

**Comment by ameshkov** [comment]
Pull request?

**Comment by Mizzick** [comment]
https://github.com/AdguardTeam/AdguardBrowserExtension/pull/126
