### ISSUE TITLE
The custom filter is always updated

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#1240]
We should either check if filter content was changed OR if the version was changed.

Otherwise, we shoudn't consider the custom filter updated.

**Comment by maximtop** [comment]
In order to test if this issue is resolved please use this instruction
https://github.com/maximtop/ag-test-custom-filter-update

**Comment by BooBerry** [comment]
This issue still exists in 3.0.5.

If I add my custom filter (and then make sure all other filters are up-to-date by manually checking for filter updates), then increasing the version of my custom filter and pushing an update then checking for filter updates again doesn't actually update the filter. If you close the browser (both Chrome and Firefox) and reopen it and check the custom filters, a) the filter version is still the old/previous one that was first added and b) checking for manual filter updates again "updates" the filter, but it's not actually updating it.

The only workaround is to remove the custom filters and re-add them. But if I make anymore changes to the filter and push an update, again, it won't update correctly once again.

**Comment by maximtop** [comment]
@BooBerry could you please send me the link to your custom filter?

**Comment by BooBerry** [comment]
Sure, here it is. Just download it and upload it somewhere else where the browser extension can update it from.

https://dl.dropboxusercontent.com/s/69t5su7669zfsrl/adguard_user_filter.txt

Easiest way to get this to happen...

1) Add the filter as a custom filter (I use Trusted if that makes any difference).
2) Do a manual check for filters update, to make sure all the filters are up-to-date.
3) Make a change to the custom filter, e.g. increase version and date then upload the updated filter.
4) Manual check for filter updates again, the browser extension will say the filter has been updated. Click on Custom and you'll note the version listed is still the previous version. You can manually check for filter updates again, but it *should* say there's no updates.
5) Close the web browser and reopen it.
6) Back in the filters section, manually check for filter updates again... and the custom filter is "updated" again... but it's not actually updating.

**Comment by maximtop** [comment]
Yes, I can confirm that filter information is not displayed correctly if the browser is reloaded. I'll fix it.

But actually, custom filter content updates correctly when you update its version. You can check it adding some console.log statements in the filter, e.g. `#%#console.log('updated version to 235');` and after update open console on `example.org`

**Comment by BooBerry** [comment]
Ah, I see now. So even though it'd try to "update" after closing/reopening the browser, it was already updated. Makes sense, thanks. :+1:

**Comment by maximtop** [comment]
Instructions for testers
1. Add a custom filter with specified fields:
```
! Version: 1.0.0.107
! TimeUpdated: 2019-02-22
```
_Version and TimeUpdated can be other_
2. Add some rule to the filter, update version
3. Check that filter updated and filter information updated correspondingly
4. Check that old rules were removed and new ones were added
5. Reload browser or extension
6. Check that filter info and rules info remained actual
