### ISSUE TITLE
YouTube "iCards" don't display properly on Safari when using AdGuard

### ISSUE THREAD

**Issue by AppleAuthority** [AdguardTeam/AdguardBrowserExtension#1244]
### Steps to reproduce

1.Open a YouTube video with an iCard in it ([example](https://youtu.be/-Sex3r_CNWU?t=74))
2. Fullscreen the video
3.
4.

### Expected behavior

Entire iCard displays properly
### Actual behavior

Only the ⓘ displays and the rest of the card is blocked by AdGuard

<details><summary>Screenshot:</summary>

</details>

<details><summary>Screenshot of the browser console:</summary>

</details>

### Your environment

* AdGuard AdBlocker extension version: AdGuard for Safari 1.2.1
* Environment name and version: Safari 12.0.2 (14606.3.4)
* Filters you use in AdGuard: None
* Any other browser extensions you have installed: Ghostery Lite for Safari 1.0.0

**Comment by karina-archazh** [comment]
Issue moved to [AdguardTeam/AdGuardForSafari #122](https://github.com/AdguardTeam/AdGuardForSafari/issues/122) via [**ZenHub**](https://www.zenhub.com/)
