### ISSUE TITLE
Self-destructing third-party cookies leads to logout from Google account

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#1245]
I don't see how it happens as I don't see `google.com` used in a third-party context.

I suppose that the mistake might be in how we process `main_frame` requests. For instance, when I click on a link leading to `google.com` and we consider it a third-party request -> self-destruct cookies.

**Comment by maximtop** [comment]
in order to repeat:

1. turn off all stealth mode options
2. turn on `Self-destructing third-party cookies` option
3. decrease time to 10 minutes
4. log out from the gmail.com
5. try to log in back to the gmail.com  

There shouldn't appear cookies mismatch notification

**Comment by BooBerry** [comment]
This is still happening in 3.0.5. In fact if you try log back in, the browser/Google gives a warning about cookies. The only way to fix it is to delete the cookies and log in again.
