### ISSUE TITLE
Hide Referrer from third-parties breaks VKpay

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardBrowserExtension#1246]
AG v3.0.3Beta

details: https://yadi.sk/i/yd8xa0OnxanpjQ

console: https://uploads.adguard.com/VK_Pay_2019-01-10_19-21-38.png

**Comment by ameshkov** [comment]
@zzebrum this should be fixed in the filters (add a $stealth exception)

**Comment by Alex-302** [comment]
@zzebrum I don't see that request.
![image](https://user-images.githubusercontent.com/8361299/51478903-6dbdd200-1d95-11e9-9b04-807f157bfe77.png)
please send to user
`@@||vk.payservice.io^$stealth`

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdguardFilters #28586](https://github.com/AdguardTeam/AdguardFilters/issues/28586) via [**ZenHub**](https://www.zenhub.com/)
