### ISSUE TITLE
Feature Request: Option to Hide Assistant Icon

### ISSUE THREAD

**Issue by alpyn** [AdguardTeam/AdguardBrowserExtension#1247]
Hello,

is it possible to hide AdGuard Assistant icon in the browser?

If not, I would like to have this option enabled.

I guess this icon is being used rarely; therefore we don't need to have it visible all the time.

Thanks.

**Comment by zzebrum** [comment]
@alpyn you can disable assistant in app's settings. Assistant is an extension in AG full version and it is not the same as a browser extension.
