### ISSUE TITLE
Element Blocking assistant does not work in mobile version of websites

### ISSUE THREAD

**Issue by pedrogarcia** [AdguardTeam/AdguardBrowserExtension#1250]
### Steps to reproduce

1. Open a webpage, such as [duckduckgo.com](https://duckduckgo.com/?q=remove+header&t=h_&ia=web)
2. Open DevTools, and toggle device toolbar to view mobile version of website
3. Iniate the Element Blocking assistant from the Adguard extension 
4. Tap any element - it does not work or do anything

<details><summary>Screenshot:</summary>

![snipaste_2019-01-15_15-42-31](https://user-images.githubusercontent.com/2473545/51198772-53d74780-18dc-11e9-97b7-b185e4739437.png)

</details>

</details>

### Your environment
* AdGuard AdBlocker extension version: 2.10.14
* Environment name and version: Chrome 71.0.3578.98  (64-bit)

**Comment by zzebrum** [comment]
@pedrogarcia what does console show?
