### ISSUE TITLE
Feature request: make website resize to fill gaps created by blocked ads

### ISSUE THREAD

**Issue by Samuel12321** [AdguardTeam/AdguardBrowserExtension#1252]
Not sure if this is possible:
if a list of ads are blocked on one side of the page the page does not resize to fill it creating a rather lopsided uneven look. it would be nice if the page could be recenterd to fill the gap

**Comment by zzebrum** [comment]
@Samuel12321 Hi there! I think it is possible only in some cases.

Please, provide an example and what is the extension config you have?

**Comment by Samuel12321** [comment]
resized nicely: 
[Microsoft is preparing for foldable Windows devices - The Verge.pdf](https://github.com/AdguardTeam/AdguardBrowserExtension/files/2799480/Microsoft.is.preparing.for.foldable.Windows.devices.-.The.Verge.pdf)

Not resized nicely:
![annotation 2019-01-27 095910](https://user-images.githubusercontent.com/35312698/51792720-3f6b4700-221a-11e9-8379-5fcce9164fa0.jpg)

**Comment by zzebrum** [comment]
well, in this case, it's not possible to fill the gap. I mean if it's some small space, then yes, sometimes it can be fixed. Anyway, such questions will be better create in other [repo](https://github.com/AdguardTeam/AdguardFilters/issues).
