### ISSUE TITLE
Update third-party libraries sources

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#1253]
From the Mozilla addon reviewer:

> Please take a look at the 3rd party libraries in libs folder and make sure that *all* links point to the specific tag/release instead of a branch (e.g. "master"). Also note that only stable releases are acceptable (not beta, pre, RC, dev or in your case patched) and that third party CDNs are not considered official source. For more information, refer to https://developer.mozilla.org/en-US/Add-ons/Third_Party_Library_Usage .

Here's what needs to be done:

1. Get rid of minified libraries completely
2. Ensure that we use stable releases when it's possible and update `sources.txt` with the proper links. There are some links to `master` branches there, this is not acceptable.
3. Patched libraries and edge cases must be indicated in the `sources.txt`:
    * `nprogress` - the same approach, let's fork it, apply our patch, tag the commit and use it.
    * `https://github.com/AndersLindman/SHA256` - the same, fork/patch/tag/use
    * `https://github.com/inexorabletash/text-encoding`

4. I might be wrong about these, but haven't we moved them all to Assistant?
    * `diff_match_patch` - it was finally moved to Github so we can try updating it. However, there are no releases there. Let's fork the repo, beautify the JS file, apply our patch, and use it instead of what we use now: https://github.com/google/diff-match-patch
    * `https://github.com/cantino/selectorgadget` - the same
    * `https://github.com/mathiasbynens/CSS.escape`

**Comment by ameshkov** [comment]
Ok, more than that, you will need to migrate these changes:
https://github.com/AdguardTeam/AdguardBrowserExtension/commit/a1f8f8e4d24e2cd49dc0effe53edfce8bd3db346

**Comment by ameshkov** [comment]
Aand now we need to get rid of balalaika too (or write something like that from scratch and make it understandable)
https://github.com/AdguardTeam/AdguardBrowserExtension/commit/5bc3eac21bd95630c7f0b846068a271a48b0addb

**Comment by maximtop** [comment]
Here is nothing to test
