### ISSUE TITLE
Parameter ‘Filters update interval’ duplicate after import settings

### ISSUE THREAD

**Issue by aspasskaya** [AdguardTeam/AdguardBrowserExtension#1254]
### Steps to reproduce
1. General Settings
2. Import settings -> Upload file .json
https://uploads.adguard.com/assa_vcwkp.json

### Expected behavior
![image](https://user-images.githubusercontent.com/43952607/51397673-c0f41280-1b52-11e9-9b8d-2cc180996cb8.png)

### Your environment
* Chrome Extension 3.0
* Chrome 71.0.3578.98 
* Win 10 64 bit

**Comment by maximtop** [comment]
fixed in the pr 344

**Comment by aspasskaya** [comment]
Error in MS Edge after import .json file.
![image](https://user-images.githubusercontent.com/43952607/52278186-7dc5dc00-2967-11e9-8b3c-918fb9d89742.png)
