### ISSUE TITLE
Parameter 'Filters update interval’ doesn’t save in settings file after export

### ISSUE THREAD

**Issue by aspasskaya** [AdguardTeam/AdguardBrowserExtension#1255]
### Steps to reproduce
1. General settings
2. Change the parameter 'Filters update interval' -> 12 hours
3. Export settings
4. Change the parameter 'Filters update interval' -> 1 hour
5. Import settings -> Upload the file .json
https://uploads.adguard.com/assa_ohokj.json

### Expected behavior
Parameter 'Filters update interval’ -> 12 hours

### Actual behavior
Parameter 'Filters update interval’ -> 1 hour

### Your environment
* Chrome Extension 3.0
* Chrome 71.0.3578.98
* Win 10 64 bit

**Comment by aspasskaya** [comment]
Error in MS Edge after import .json file.
![image](https://user-images.githubusercontent.com/43952607/52278186-7dc5dc00-2967-11e9-8b3c-918fb9d89742.png)

**Comment by maximtop** [comment]
Export in the edge is not working due to this bug
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8178877/
