### ISSUE TITLE
Return Save button for User rules and Whitelist

### ISSUE THREAD

**Issue by oleedd** [AdguardTeam/AdguardBrowserExtension#1257]

**Comment by oleedd** [comment]
It means ability to use "save" button. It is important because the file (on hard drive) with the user filter will become too big if to auto save every second during editing custom rules.

**Comment by oleedd** [comment]
мм

**Comment by oleedd** [comment]
@ameshkov 
It annoys very much when you type a rule and it saves 10 times during this. Can you please make a save button which was in the previous design?

**Comment by maximtop** [comment]
We have returned the save button in the v4.0

**Comment by oleedd** [comment]
No pollyfill for `Object.fromEntries()` in beta.

**Comment by maximtop** [comment]
> No pollyfill for `Object.fromEntries()` in beta.

Hi! In which browser did this error happen? What is its version?

**Comment by oleedd** [comment]
Hi. Chrome 65.

**Comment by maximtop** [comment]
We are going to support chrome starting from the 79 version

**Comment by oleedd** [comment]
>support chrome starting from the 79 version

Why? Just interesting.
