### ISSUE TITLE
$$ rules

### ISSUE THREAD

**Issue by oleedd** [AdguardTeam/AdguardBrowserExtension#1258]
Is it possible to support $$ removing rules for next versions?

**Comment by ameshkov** [comment]
They are supported in FF but not in Chrome, it simply does not provide technical means for implementing these rules.

**Comment by oleedd** [comment]
OK. I understood. But there are Node.remove() and Node.removeChild() in Chrome and they work.
It is interesting what methods exist in FF but are not in Chrome for implementing $$ rules?

**Comment by ameshkov** [comment]
The difference is that `$$` rules work **before** the page is processed by the browser while `Node` is executed after. For instance, removing a script would make no sense as the browser has already parsed and executed it by the time of calling remove()
