### ISSUE TITLE
Add an option to resize "user filter" and "whitelist" textareas

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#1263]
It seems easy to do so assigning to v3.0 right away. The default size == the minimum size.

**Comment by XX-J** [comment]
Разрешите, пожалуйста, ширину без ограничений.

<details><summary>Screenshot:</summary>

![2019 03 03-1](https://user-images.githubusercontent.com/17948007/53687857-21c65b80-3d4b-11e9-9fd3-2cbd4ac27bd7.png)
</details>

**Comment by zzebrum** [comment]
@XX-J  какой у вас браузер?

**Comment by XX-J** [comment]
Mozilla Firefox v53.0.3 (Win7SP1) - Adguard v3.0.6
