### ISSUE TITLE
Adguard assistant icon won't go away (YouTube only)

### ISSUE THREAD

**Issue by d0x360** [AdguardTeam/AdguardBrowserExtension#1266]
The assistant icon is suddenly on every YouTube video I watch but only video pages.

I have uninstalled assistant (again), I also installed agduard and checked remove settings which removed the icon but then I installed adguard beta and the icon appeared again but only on YouTube video pages.

So again I disabled assistant which didn't work then I uninstalled assistant which also didn't work.

I don't understand what's going on here.

Windows 10 PRO latest public build and latest public build of Chrome.

Adguard Beta version 6.4.1814.4903

Any help would be appreciated.

**Comment by ameshkov** [comment]
Could you please try clearing the browser cache?

**Comment by d0x360** [comment]
Clearing the cache didn't work so I uninstalled chrome, then installed it
again and disabled sync and that seems to have fixed it.

I would guess that when I cleared the cache (and everything else) it was
resyncing all of it even though it's not supposed to.

Either way the icon is finally gone although i am curious how it appeared
again all by itself after months of being gone.

Thanks for the help.

**Comment by d0x360** [comment]
The explanation about switching from a release build to beta makes sense
but I haven't changed my install (or any settings) for months.

Today I booted my PC, loaded a YouTube video and it was just there so I
loaded adguard and Assistant was still disabled.  The icon would also only
show up on YouTube videos and nothing else which was kinda odd.

**Comment by ameshkov** [comment]
> The icon would also only
> show up on YouTube videos and nothing else which was kinda odd.

This really sounds like some kind of a cache, but I guess it's not a simple browser cache.

I just checked -- YouTube registers a ServiceWorker, maybe they used its caching capabilities. It is different from the regular browser cache and generally, it fits. 

To clean all website data including service workers: open Chrome developer tools, go to "Application" tab, select "Clear storage" in the left sidebar menu.

**Comment by d0x360** [comment]
Interesting, thank you for the explanation.

I ended up clearing lifetime data for everything in chrome anyways.  I
figured I might as well they had a very detailed history for long enough
and provided they follow their own rules they get to start over now.

Thanks again and take care.

**Comment by vampireinfinite** [comment]
> The assistant icon is suddenly on every YouTube video I watch but only video pages.
> 
> I have uninstalled assistant (again), I also installed agduard and checked remove settings which removed the icon but then I installed adguard beta and the icon appeared again but only on YouTube video pages.
> 
> So again I disabled assistant which didn't work then I uninstalled assistant which also didn't work.
> 
> I don't understand what's going on here.
> 
> Windows 10 PRO latest public build and latest public build of Chrome.
> 
> Adguard Beta version 6.4.1814.4903
> 
> Any help would be appreciated.





Ok, here you go do one thing if you facing such an issue with Adguard. Do not uninstall the application neither you need to Clear the cache or Cookies of your browser.

Just type in the search box of chrome. chrome://flags/.
New windows open just find the caption Experimental QUIC Protocol. It should be default you need to Disabled it.
Then relaunch your browser and open the www.youtube.com you saw your issue is being resolved. I personally do this just now and I saw the assistant icon of Adguard on YouTube official website.
Rather you using other methods, it's better you can go ahead with it.
