### ISSUE TITLE
3.0.4 beta doesn't block yandex direct in Opera

### ISSUE THREAD

**Issue by skipik** [AdguardTeam/AdguardBrowserExtension#1271]
### Steps to reproduce

1. Install Opera browser
2. Install AdGuard 3.0.4 beta
3. Visit https://yandex.ru/pogoda/moscow?from=home
4.

### Expected behavior
AdGuard extension should block yandex direct (using the cookies method)

### Actual behavior
AdGuard extension doesn't block yandex direct. It works in Google Chrome correctly though. So the problem is only with Opera browser.

<details><summary>Screenshot:</summary>

</details>

<details><summary>Screenshot of the browser console:</summary>

</details>

### Your environment

* AdGuard AdBlocker extension version: 3.0.4 beta, the same behavior was on 3.0.3 beta also.
* Environment name and version: Current Opera Stable & Opera Developer
* Filters you use in AdGuard: I tried both modes - all the basic filter enabled plus only my custom rule for yandex direct (got it from @Alex-302 ), no difference.
* Any other browser extensions you have installed: No extensions.

**Comment by maximtop** [comment]
Hi, can you look please response in this issue
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1234

**Comment by skipik** [comment]
Looks like it helped. Thank you @maximtop !

**Comment by maximtop** [comment]
You're welcome!
