### ISSUE TITLE
[GUI:TEXT] Block WebRTC description doesn't follow up

### ISSUE THREAD

**Issue by AjvarXX** [AdguardTeam/AdguardBrowserExtension#1274]
Descrition of previous and next options describe what they do. While WebRTC description describes what WebRTC is which might confuse.
How it should be: **Prevent a possible disclosure of your real IP address even with proxy or VPN through WebRTC.**

<details><summary>Screenshot:</summary>

![rtc](https://user-images.githubusercontent.com/9568793/52454642-2d13d600-2b55-11e9-8cd3-a9614504c68a.PNG)

</details>
### Your environment

* AdGuard AdBlocker extension version: 3.0.3
* Environment name and version: Waterfox 56.2.7.1

P.S. Would you suggest leaving Disable WebRTC addon or enabling this option in your? Will WebRTC blocking stops if I choose "Pause Adguard on this site" or "Disable protection"? Maybe leave it always enabled if user chose to use it?

**Comment by ameshkov** [comment]
You are right, thank you!

> P.S. Would you suggest leaving Disable WebRTC addon or enabling this option in your? 

I don't really know what "Disable WebRTC" addon does. AG does not fully disable WebRTC, just prevents the IP leak. If that's what it does, then one extension is enough. 

> Will WebRTC blocking stops if I choose "Pause Adguard on this site" or "Disable protection"? Maybe leave it always enabled if user chose to use it?

No, it works by changing a global setting.
