### ISSUE TITLE
adding 2 banking websites to the https exclusion list....

### ISSUE THREAD

**Issue by Dan2mg** [AdguardTeam/AdguardBrowserExtension#1277]
I wish to add 2 banking websites to the https exclusion list in AdGuard..
https://my.sjpbank.co.uk
https://portal.newdaycards.com

is this what I need to do?

**Comment by zzebrum** [comment]
Issue moved to [AdguardTeam/HttpsExclusions #137](https://github.com/AdguardTeam/HttpsExclusions/issues/137) via [**ZenHub**](https://www.zenhub.com/)
