### ISSUE TITLE
Let user filter itself support AG_defineProperty by default.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardBrowserExtension#1279]
@maximtop
@AdamWr

1. How does the integration mode of AG for PC and AG Browser Extension work?
   Ex: Under integration mode, if Base filter in AG for PC is disabled but Base filter is enabled in AG Browser Extension, the rules in Base filter won't work because AG for PC is active, right?
**Is there any benefits for integration mode in the aspect of filters' complementary?
Seems no.**

2. Before, I didn't know that user filter itself doesn't support `AG_defineProperty` rules.
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1276#issuecomment-461923800

Please fix it.
It's because users may disable all AG filters but try `AG_defineProperty` rules in the user filter for testing.

**Comment by ameshkov** [comment]
Well, AG_definePropery must be reworked as a scriptlet:
https://github.com/AdguardTeam/CoreLibs/issues/664

Once it's done, it will be possible to use it from the user filter.

**Comment by ameshkov** [comment]
Regarding the first question, you're right, integration mode does not improve filtering.

**Comment by lancelot-moon** [comment]
@ameshkov

1. Your AG for PC and Android may have CoreLibs.
But is it available for **AG browser extension** and **AG content blocker for Android** if you only fix it in CoreLibs?

2. May you tell me about the advantage of integration mode in other aspects?
Thanks.

**Comment by ameshkov** [comment]
> But is it available for **AG browser extension** and **AG content blocker for Android** if you only fix it in CoreLibs?

1. Content blocker relies on third-party filtering provided by the browsers so it's not really relevant.
2. As I've said, there are two independent filtering engines maintained by us. One is CoreLibs, another is the AG browser extension.

> 2. May you tell me about the advantage of integration mode in other aspects?

Mainly cosmetics, you can use it to enable/disable filtering or block an element, and it works outside of a webpage (some people don't like having the assistant icon).

**Comment by lancelot-moon** [comment]
Without integration mode, cosmetics rules in AG for PC still work system-wide.
The AG Assistant still can't be hidden now.
I don't know there is any association to integration mode.
