### ISSUE TITLE
Statistics graph only working for current day

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardBrowserExtension#1280]
Well I already have to open a new issue regarding #1241.
The statistics of today are working fine, but everything else not. No statistics are saved for the last week etc. although I used it everyday (see screenshots)

<details><summary>Screenshot:</summary>

Today:
![screenshot 2019-02-11 at 14 15 45](https://user-images.githubusercontent.com/10995998/52565747-04673700-2e08-11e9-8db7-185375ef3f93.png)

Week:
![screenshot 2019-02-11 at 14 15 32](https://user-images.githubusercontent.com/10995998/52565748-04ffcd80-2e08-11e9-857b-be3e9cd76f7a.png)

</details>

### Your environment

* AdGuard AdBlocker extension version: 3.0.5
* Environment name and version: 72.0.3626.97

**Comment by maximtop** [comment]
@danidoedel how did you update extension?

**Comment by danidoedel** [comment]
It updated automatically to 3.0.5. I‘m on the beta channel for quite some time now.

**Comment by danidoedel** [comment]
Ok no not really. Data from yesterday and the day before is reset again. Didn't reinstall the extension or anything like that.

**Comment by ameshkov** [comment]
Yeah, something is really off with the charts data at the moment, I can confirm it

**Comment by TheHasagi** [comment]
I checked the result from last week, everything looks good. 

@danidoedel 

Do you still face the issue?

**Comment by danidoedel** [comment]
@TheHasagi Did you already fix this? I still don't have any statistics other than from today.

**Comment by maximtop** [comment]
@danidoedel maybe I can contact with you via telegram or skype?

**Comment by danidoedel** [comment]
@maximtop Sure, telegram ist fine, same username
