### ISSUE TITLE
Minor improvements

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardBrowserExtension#1281]
@maximtop

1. It seems that it has unnecessary space or lack a comma in the number for "Total:".
#2377995
Total: $1

ex: 1128 or 1,128?

2. Please add "Check for updates" in the main screen.
It'll check for updates of **both browser extension version and filters**.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/oFNsNeo.png)
</details><br/>

3. Please upload the new phrases to onesky.
Need to translate them.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/JC0XpbM.png)
</details><br/>

Thanks.

**Comment by ameshkov** [comment]
> Please add "Check for updates" in the main screen.
>   It'll check for updates of **both browser extension version and filters**.

This needs to be filed as a feature request, it's not as simple

**Comment by lancelot-moon** [comment]
If checking for updates of browser extension version is difficult, only checking for updates of filters in home screen is ok.

Thanks.
