### ISSUE TITLE
Remove the "settings" button when browser extension is in integration mode

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#1282]
https://uploads.adguard.com/up04_xt5io_Monosnap.png

**Comment by lancelot-moon** [comment]
Why?
How can I disable integration mode if no entrance to settings.

**Comment by lancelot-moon** [comment]
Some people will set different filters between AG for PC and AG browser extension.
You know AG for PC will show a warning if enabling too many filters.
**Some users wish filters AG for PC and AG browser extension can be complementary.**
I think integration mode isn't useful...

**Comment by ameshkov** [comment]
> How can I disable integration mode if no entrance to settings.

You still can go to settings via the right click and disable the integration mode. But when the integration mode is active, extension settings are redundant.

**Comment by lancelot-moon** [comment]
Actually, I knew that I can go to settings via browser's context menu.
I just think it can be in the **obvious place**, ex: settings icon in home screen.

And how can users find entrance to settings if already disabling "Add AdGuard item to browser's context menu"?
