### ISSUE TITLE
Improvement of integration mode.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardBrowserExtension#1283]
@ameshkov
@maximtop 

Under integration mode:
1. After enabling integration mode, AG browser extension will detect that which filters in AG for PC are enabled.

**Those enabled filters in AG for PC can't be selective and enabled in AG browser extension.**

2. In AG browser extension, there are marks for those enabled filters in AG for PC.

AG for PC will show a warning if enabling too many filters.
I wish filters in AG for PC and AG browser extension can be **complementary**.

**Comment by lancelot-moon** [comment]
We might have different definitions of integration mode.

In your definition of integration mode, AG for PC is ONLY active.

Then why do I need to install AG Browser Extension if having AG for PC installed?

You ignored **complementary** between AG for PC and AG Browser Extension before.

In my definition of integration mode, AG for PC is active, so **user filter, whitelist, stealth mode and AG Assistant in AG Browser Extension** should be **invalid** and **can't be operated**.
**Need an obvious mark or notification in home screen for users.**

Only filters section, general settings and miscellaneous can be configured.
But if some filters in AG for PC are already enabled, the same filters in AG Browser Extension should be invalid and can't be operated.

Merely the filters which is disabled in AG for PC can be configured in AG Browser Extension, and they will be also active if being enabled in AG Browser Extension.

**Comment by lancelot-moon** [comment]
@ameshkov

Or give the icon/option of Settings, but the configuration of user filter, whitelist, stealth mode and AG Assistant in AG Browser Extension should **disappear** (hidden) in settings under integration mode.

This method should be easier.
How do you think?

**Comment by ameshkov** [comment]
> Then why do I need to install AG Browser Extension if having AG for PC installed?

Just to replace the AG Assistant and to manage AG for PC. That's the only reason for having a browser extension alongside the desktop AG.

**Comment by lancelot-moon** [comment]
Well, if wishing AG for PC and browser extension can be complementary, use uBO since the integration mode of AG Browser Extension doesn't run with a better way...

**Comment by ameshkov** [comment]
Using different ad blockers at the same time is recommended neither by us nor by uBO. Ad blockers **do not complement** each other.

**Comment by lancelot-moon** [comment]
If enabling too many filters in AG for PC, it will show the warning.

That's why I think to enable some other filters in Browser Extension.

That's the complementarity which I mean.

**Comment by ameshkov** [comment]
Well, it's just warning and nothing more. We're trying to protect people from themselves -- those who like to enable all available filter lists.

**Comment by ameshkov** [comment]
Integration mode will be deprecated in favor of the new assistant extension
