### ISSUE TITLE
Sort the filters in the search result

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1285]
... instead of random order)

**Comment by ameshkov** [comment]
It's not random, we should use `displayNumber` that we have in the filters registry

**Comment by ameshkov** [comment]
Reopening this.

Sort order:
groupId, displayNumber, name

**Comment by maximtop** [comment]
@Alex-302 what's wrong with the filters sort?

**Comment by Alex-302** [comment]
@maximtop 
according to 
```
Sort order:
groupId, displayNumber, name
```
the sort order is correct.
