### ISSUE TITLE
Firefox extension 2.1.1 (Beta) causes memory leak

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardBrowserExtension#129]
Версия антибаннера 2.1.1 (Beta), которая была доступна на нашем сайте.
Опция отправки статистики использования фильтров отключена. Версия Firefox
43.0.4.
В плагине присутствует утечка памяти в браузере Firefox. При долгом серфинге по большому количеству страниц, общая потребляемая память Firefox возрастает до 1,5-2 гигабайтов. При отключении аддона Adguard проблема решается.
BMO-994-48752

**Comment by ameshkov** [comment]
@gshumihin please test it

**Comment by gshumihin** [comment]
Протестил на макоси, ситуация такая: Firefox разжирается до 1 Гб что с адгардом, что без него. Пойду проверю еще на windows.

**Comment by gshumihin** [comment]
Same situation on windows. Need more information about installed extensions (others) from user @evgeniy-ADG 
Maybe that's incompatibility between extensions

**Comment by evgeniy-ADG** [comment]
Ok, will do.

**Comment by evgeniy-ADG** [comment]
We have the list
![image](https://cloud.githubusercontent.com/assets/15856304/12415300/acccfc18-bea3-11e5-8eb8-afe9f096772d.png)
![image](https://cloud.githubusercontent.com/assets/15856304/12415313/bddced92-bea3-11e5-80e0-d4783cfd02ca.png)

**Comment by atropnikov** [comment]
Next time when firefox have high memory consumption please open new tab and type "about:memory" in address bar, then click "Measure and save..." and attach generated file to this issue.

**Comment by evgeniy-ADG** [comment]
Done.

**Comment by atropnikov** [comment]
@evgeniy-ADG I don't see any attachments. Can you drag&drop generated file to comment block and send it again?

**Comment by evgeniy-ADG** [comment]
I mean I asked him to send it to us and will update as soon as I receive it. Srry. )

**Comment by atropnikov** [comment]
Ok, thank you.

**Comment by evgeniy-ADG** [comment]
We have an answer.

"Сделал сегодня 2 снимка памяти Firefox на работе. Первый сразу после запуск
файрфокса, второй через 8 часов работы. После 8ми часов работы, файрфокс с
теми же вкладками использовал примерно на 200 мегабайт больше."

[memory-report_1_work.json.zip](https://github.com/AdguardTeam/AdguardBrowserExtension/files/96314/memory-report_1_work.json.zip)

**Comment by gshumihin** [comment]
Here's one more memory dump from myself:
[memory-report.json.gz](https://github.com/AdguardTeam/AdguardBrowserExtension/files/99262/memory-report.json.gz)
