### ISSUE TITLE
Stealth Mode working in pause mode

### ISSUE THREAD

**Issue by aspasskaya** [AdguardTeam/AdguardBrowserExtension#1290]
### Steps to reproduce
1. Enable pause Adguard protection button
2. Go to ok.ru
2. Go to Filtering log

### Actual behavior
Stealth Mode working.
![image.png](https://images.zenhubusercontent.com/5bbf23f1307bc60241e3ae0e/654f653b-742d-46db-9eab-3635ae5859c5)

**Comment by TheHasagi** [comment]
Plus this one:

![img](https://uploads.adguard.com/TheHasagi3buud.png)
