### ISSUE TITLE
Enabled filters in disabled filters group in report link

### ISSUE THREAD

**Issue by aspasskaya** [AdguardTeam/AdguardBrowserExtension#1293]
### Steps to reproduce
1. Disable all filters group 
2. Disable all filters inside groups
3. Enable Base filter in disabled filters group 'Ad blocking'
4. Tap on 'Submit a complaint about this website'
5. Go to step 4 'App configuration'

### Actual behavior
![image](https://user-images.githubusercontent.com/43952607/53109550-2d937000-354a-11e9-8a24-e88b3c7bb26b.png)
# 
#### !Also, change filter name in report link: Spyware filter -> Tracking Protection filter

![image](https://user-images.githubusercontent.com/43952607/53109814-b90d0100-354a-11e9-9fb6-998ea300ad76.png)

**Comment by maximtop** [comment]
Filter name will be updated when this issue be resolved
https://github.com/AdguardTeam/ReportsWebApp/issues/190
