### ISSUE TITLE
Stealth Mode working in inverted whitelist

### ISSUE THREAD

**Issue by aspasskaya** [AdguardTeam/AdguardBrowserExtension#1298]
### Steps to reproduce
1. Go to Adguard settings - Whitelist Add website 
2. Enable "Invert whitelist".
3. Add website lenta.ru + adguard.com
4. Go to dni.ru

### Your environment
* Adguard 3.0.6
* Edge
* Win 10 64 bit

### Expected behavior
Ads are unblocked everywhere except the whitelisted websites.

### Actual behavior
![image.png](https://images.zenhubusercontent.com/5bbf23f1307bc60241e3ae0e/ed8c193d-52b2-40d6-91e5-af541d7c7d8e)

![image.png](https://images.zenhubusercontent.com/5bbf23f1307bc60241e3ae0e/53d15053-2bbe-46c0-b679-20948c22c69c)

![image.png](https://images.zenhubusercontent.com/5bbf23f1307bc60241e3ae0e/328dadeb-cdf7-4de0-9d03-c4e0aa640869)

![image.png](https://images.zenhubusercontent.com/5bbf23f1307bc60241e3ae0e/d0c964a2-2147-4ccd-ab44-ffb8faa4896a)

**Comment by ameshkov** [comment]
Well, I am not sure if this should be a bug actually

**Comment by zzebrum** [comment]
@ameshkov  why not?
