### ISSUE TITLE
The tag "#lang:fo" has no description in Dandelion Sprout's Nordic Filters.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardBrowserExtension#1303]
@ameshkov
@maximtop
@aalpatkina

In Dandelion Sprout's Nordic Filters, the tag "#lang:fo" has no description.
On onesky, there is also no phrase for "#lang:fo (Faroese language)".
Need to upload the new phrase.

@Mizzick
**Wait some time for translators.**
You need to again update filters locales after this is done.

**Comment by ameshkov** [comment]
That's not an issue for this repo. There will be a translation in due course, but we can't stall the release till we get it.
