### ISSUE TITLE
Add the buttons to the pages of AG for Windows/macOS in the home screen below.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardBrowserExtension#1305]
@maximtop
@aalpatkina

Why did you not advertise for AG for PC in AG Browser Extension? = =

1. Modify the phrase in #47997576 on onesky.
Get AdGuard for your mobile
-> Get AdGuard for your devices

2. Add the buttons (links) to the pages of AG for Windows/macOS in the home screen below, such as the screenshot.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/s9d9tlk.png)
</details><br/>

**Comment by ameshkov** [comment]
Tbh, I don't want to bloat extension's UI with more links. Users can learn about desktop versions in various places (thank you page, settings page), I just don't want to stuff it everywhere.
