### ISSUE TITLE
Simplified descriptions for Chrome WebStore, Addons Mozilla Org and Windows Store (Edge).

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardBrowserExtension#1306]
@ameshkov 
@aalpatkina

The modified version of descriptions is still too much.
Users won't want to read them!
Please use the same simplified descriptions for Chrome WebStore, Addons Mozilla Org and Windows Store (Edge).
You also knew that Spyware Filter was renamed to Tracking Protection Filter.
Microsoft Edge will be a Chromium-based browser.

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/oKdLY8n.png)
</details><br/>

Delete some and add the new phrases below.
Others are kept.

★ Blocks all ads and solves adblock circumvention scripts with AdGuard Base Filter: video ads (includes YouTube adblock), rich media advertising, unwanted pop-ups, banners and text ads (includes Facebook adblock);

★ Protects your privacy with AdGuard Tracking Protection Filter, whose database is even larger than what Ghostery® and Disconnect have;

★ Protects you from online threats, malware and phishing with AdGuard Browsing Security;

★ Blocks Crypto-jacking and CoinHive with AdGuard Base Filter and some open source filters like NoCoin;

★ Removes social media widgets with AdGuard Social Media Filter;

★ Blocks irritating elements on web pages such as cookie notices, third-party widgets & in-page pop-ups, and even solves adblock circumvention scripts with AdGuard Annoyances Filter;

★ Provides more than 20 language-specific and general filters, which is helpful to regional ad blocking and includes some rules for solving adblock circumvention scripts;

★ Additionally, AdGuard Mobile Ads Filter and the option of "Use optimized filters" will be automatically enabled for mobile ad networks by default if your mobile browsers can support browser extension, ex: Firefox, Kiwi or Yandex Browser for Android;

★ If enabling the option of "Use optimized filters", the optimized filters by compressing original filters and removing rarely used rules will work, which is especially lightweight for mobile browsers;

★ Stealth Mode protects your identity and sensitive personal information from thousands of online trackers.

**Comment by ameshkov** [comment]
Well, we can split the description into two parts.

A short part that is absolutely necessary, and a longer part that I want to have in the English version of the description.

@aalpatkina, thoughts?

**Comment by aalpatkina** [comment]
Yes, we can do that. I just think it's difficult to remove some parts from the descriptions as all of them are important enough to be listed in them. But if you want, I'll do it.

I personally don't see any problems here. We don't force anybody to read it. @lancelot-moon, users are different. Some people always read just the first strings, others look through the text and emphasize the most important points for themselves, etc. But if somebody wants to get more information about AdGuard features before installing an extension, than it's a good thing that we have comprehensive descriptions in Stores. Moreover, they are already translated into most of the languages. 

@ameshkov maybe it would be better just to let @lancelot-moon shorten the description in Chinese Traditional if he wants?

P.S. @lancelot-moon in my opinion, a semicolon is more appropriate when listing features here. If you know another rule, please send me a link. Thanks.

**Comment by lancelot-moon** [comment]
Actually, the new phrases in that screenshot includes the deleted parts.

Only describe in succinct words.
It's ok if you don't want apply them for other languages' descriptions.

But can I write the Traditional Chinese descriptions according to the above contents?

**Comment by ameshkov** [comment]
@lancelot-moon you can if you think it works better that way.

@aalpatkina well, I think when we change it seriously next time, we'd better divide it into two parts just to make translators life a little bit easier. It's not necessary right now.

**Comment by aalpatkina** [comment]
@ameshkov ok
