### ISSUE TITLE
Enable "Mobile ads filter" by default on the Firefox for Android

### ISSUE THREAD

**Issue by maximtop** [AdguardTeam/AdguardBrowserExtension#1307]

**Comment by lancelot-moon** [comment]
This is really a very good idea!

But you already give the below option in the "miscellaneous" of "settings".
`Use optimized filters`
`(List of filters optimized for mobile devices)`

1. If using desktop browsers, users don't need to enable `Use optimized filters`, right?
2. What's the difference `Use optimized filters` and `Mobile Ads filter`?
I don't understand.
Do users need to enable `Use optimized filters` if `Mobile Ads filter` is enabled by default for Firefox for Android?

In the past, I supposed it would go to enable `Mobile Ads filter` if first enabling `Use optimized filters` in the "miscellaneous" of "settings"...
Thanks.

**Comment by lancelot-moon** [comment]
@ameshkov 

I don't know the difference.
May you answer me?
Thanks.

**Comment by ameshkov** [comment]
Mobile ads filter is a separate filter with mobile-specific ad networks and trackers.
"Optimized" filters compresses original filters and removes rarely used rules

**Comment by lancelot-moon** [comment]
> "Optimized" filters compresses original filters and removes rarely used rules

Well, why does `Use optimized filters` mark `Lists of filters optimized for mobile devices`?
It's very strange since Browser Extension is mainly for desktop browsers.
I don't understand.

**Comment by ameshkov** [comment]
Because the number of rules is important for mobile devices (especially, iOS)

**Comment by lancelot-moon** [comment]
On iOS, it seems that there is no browser which support Browser Extension.

**Comment by lancelot-moon** [comment]
Hi,
It seems that Yandex.Browser also supports Browser Extension.
https://www.guidingtech.com/install-google-chrome-extensions-android-yandex-firefox/
https://yandex.com/support/browser-mobile-android-phone/personal-settings/extensions.html

You can enable "Mobile Ads filter" by default in the Yandex.Browser for Android.

**Comment by ameshkov** [comment]
They have a limited support in order to prevent ad blockers do its work

**Comment by lancelot-moon** [comment]
Except for Mobile Ads filter, should we enable `Use optimized filters` by default for mobile browsers?
