### ISSUE TITLE
Language-specific filters will be automatically activated even if the group of Language-specific is disabled.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardBrowserExtension#1308]
@maximtop

Language-specific filters will be automatically activated if the option of "Activate the most appropriate filters automatically" is enabled, but the group of Language-specific is disabled.
Ex: When I visit VK, AG Russian Filter is automatically activated even if the group of Language-specific is disabled.

I'm not sure if this is a bug...

**Comment by maximtop** [comment]
Yeah, it is a bug. I'll fix it. Thank you.

**Comment by ameshkov** [comment]
The group should be enabled as well

**Comment by lancelot-moon** [comment]
I manually disabled the group of Language-specific in AG Browser Extension since I have language-specific filters enabled in AG for Windows.

**Comment by ameshkov** [comment]
Well, again, I don't think that using browser extension alongside the desktop version makes much sense, but that's up to you.

**Comment by lancelot-moon** [comment]
I install AG Browser Extension because I know that you would confuse Traditional Chinese with Simplified Chinese.
I need to help your developer to check translations and date format.

In the past, I **never used** AG Browser Extension since I have AG for Windows.

After test, I might remove it...

But many users use other Browser Extension such like uBO or Nano Adblocker with AG for PC.

That's why I emphasize the complementarity of filters between AG for PC and Browser Extension.

**Comment by maximtop** [comment]
Instructions for testers
1. Install extension
2. Check that `Activate the most appropriate filters automatically` is enabled
3. Turn on `Language-specific` category
4. Turn off all filters inside it
5. Turn off `Language-specific` category
6. Go to russian languages sites, visit view pages
7. You should see popup that `AdGuard Russian filter` was activated
8. Go to options, `Language-specific` category should be activated as well
