### ISSUE TITLE
Please update descriptions for Chrome WebStore, Addons Mozilla Org and Windows Store (Edge).

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardBrowserExtension#1309]
@aalpatkina 

Specific Traditional Chinese descriptions are done.
Please update descriptions for Chrome WebStore, Addons Mozilla Org and Windows Store (Edge) when AG Browser Extension v3 is released.

You also need to modify Spyware filter -> Tracking Protection filter in English descriptions.

I introduce Stealth Mode in my descriptions.
You maybe need to add the descriptions of Stealth Mode in English.

Thanks.

**Comment by lancelot-moon** [comment]
@maximtop

The now overview for Chrome WebStore, Addons Mozilla Org and Windows Store (Edge) are all outmoded.
(The overview was made 1 year ago.)

May you update not only browser extensions but also their overview?
Thanks.

**Comment by maximtop** [comment]
@lancelot-moon 
we will update description later

**Comment by a-ladanov** [comment]
В браузере, наверно, тоже стоит обновить описание. Описание не входит. На мой взгляд, первого предложения вполне достаточно.
![adguard](https://user-images.githubusercontent.com/18179397/59156619-78b09f00-8ab7-11e9-8e8f-9e38ebef8b6a.png)
