### ISSUE TITLE
Do not print desktop app injection requests in the filtering log

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1311]
![image](https://user-images.githubusercontent.com/8361299/53796002-df17a580-3f3b-11e9-871d-ae92e2630d5c.png)

https://github.com/AdguardTeam/AdguardForWindows/issues/2469

**Comment by ameshkov** [comment]
On the other hand, we weren't doing it before, why would we do it now?

**Comment by Alex-302** [comment]
> On the other hand, we weren't doing it before, why would we do it now?

If they should be hidden in the app, why not to do the same in extension?
