### ISSUE TITLE
Filtering log is empty if "Blocked" and "Whitelisted" checkboxes are checked

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/AdguardBrowserExtension#1314]
### Steps to reproduce

1. Open filtering log
2. Check "Blocked" and "Whitelisted" checkboxes
3. Open any website, for example https://www.google.com/ 

### Expected behavior

Filtering log should show blocked and whitelisted requests.

### Actual behavior

Filtering log is empty.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29142494/53904465-71a46b80-4046-11e9-9f8a-84590a2ec2e2.png)

![image](https://user-images.githubusercontent.com/29142494/53904473-7701b600-4046-11e9-999f-afd4e53b33ac.png)

</details>

### Your environment

* AdGuard AdBlocker extension version: 3.0.7
* Environment name and version: Chrome 72.0.3626.121
* Filters you use in AdGuard: -
* Any other browser extensions you have installed: -

**Comment by Alex-302** [comment]
What about to make these options like in Android version?

**Comment by AdamWr** [comment]
I think it's good idea.
I also would like to have these options in filtering log in AG for Windows.

**Comment by lancelot-moon** [comment]
For your reference:
https://github.com/AdguardTeam/AdguardForAndroid/issues/2607

**Comment by maximtop** [comment]
@AlikhanAliev Could you please provide us with layout regarding how it should look in the extension?

**Comment by lancelot-moon** [comment]
@maximtop
This?
Well, check with your partner.
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1358

**Comment by maximtop** [comment]
This issue was resolved in v4.0
