### ISSUE TITLE
AdGuard extension does not properly show on Chrome 56 (winXP)

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardBrowserExtension#1315]
AdGuard extension (3.0.7) does not properly show on Chrome 56 (winXP), see the screenshot:

<details><summary>Screenshot:</summary>

![img](https://uploads.adguard.com/TheHasagijqrvs.png)
![img](https://uploads.adguard.com/up22_i5grd.png)

<details><summary>Screenshot of the browser console:</summary>

**Comment by maximtop** [comment]
Same issue with the Opera 36

**Comment by Alexander033018** [comment]
Internet browser Mozilla Firefox 52.9.0 ESR.
I was installed Adguard AdBlocker Standalone 2.10.17.
After renew to Adguard AdBlocker to version 3.0.8 that all settings disappeared.
How to configure this version? 
![Adguard1](https://user-images.githubusercontent.com/37940091/54195043-228f8800-44d7-11e9-8046-f51344b9c2de.png)
![Adguard2](https://user-images.githubusercontent.com/37940091/54195051-26230f00-44d7-11e9-85ba-a696874d4113.png)

**Comment by maximtop** [comment]
@Alexander033018 could you check please if this build works properly in your browser 
https://github.com/AdguardTeam/AdguardBrowserExtension/releases/tag/v3.0.9

**Comment by Alexander033018** [comment]
Now everything works well. Thanks to the developer for the prompt solution of the problem. We are waiting for updates.

**Comment by Alexander033018** [comment]
Updated and working fine
