### ISSUE TITLE
AdGuard extension doesn't work in UC browser

### ISSUE THREAD

**Issue by aspasskaya** [AdguardTeam/AdguardBrowserExtension#1318]
### Steps to reproduce
1. Go to extension settings
2. Go to any website
### Actual behavior

![image](https://user-images.githubusercontent.com/43952607/53970903-cb6f6900-410c-11e9-9888-758b444aae85.png)
![image](https://user-images.githubusercontent.com/43952607/53970915-d0ccb380-410c-11e9-87a4-d39c59b9641b.png)

**Comment by maximtop** [comment]
Fixed via #1315
