### ISSUE TITLE
A group should be enabled if a filter is enabled from search a filters

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1319]
#### Steps to reproduce

1. Go to Search filters
2. Enable a filter

#### Expected behavior
Filter group should be enbaled

#### Actual behavior
Filter group is disabled

#### Your environment
Adguard version: 3.0.8

**Comment by maximtop** [comment]
Actually it works as described above till user didn't enabled or disabled group himself.

**Comment by Alex-302** [comment]
not required
