### ISSUE TITLE
Suggest to use Chinese date format for filters' update time in Chinese interface.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardBrowserExtension#1322]
Suggest to use Chinese date format for filters' update time in Chinese interface.

ex: Is it 6th March or 3rd June?
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/SmKt6On.png)
</details><br/>

Use 24-hour clock.
Don't need AM or PM.
ex: March 08, 2019 19:23:56
Chinese date format: 2019年3月8日 19:23:56

**Comment by lancelot-moon** [comment]
Can you modify it as the below at least if using Chinese date format is difficult.
ex: March 08, 2019 19:23:56
2019/3/8 19:23:56

8/03/2019 is not Eastern date format.
We're not used to Western date format.

**Comment by maximtop** [comment]
@lancelot-moon ok, I'll take a look.
