### ISSUE TITLE
[Edge] Opening a new tab via right-click + "Open in new tab" leads to ads not being filtered on new tab

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardBrowserExtension#1323]
### Steps to reproduce
1. Open any site on MS Edge
2. Attempt to open any link via mousewheel click or rightclick+"Open in new tab"
3. Sometimes, ads won't be filtered at all

### Expected behavior
Extension should filter ads on new tab

### Actual behavior
Sometimes AdGuard ignores the tab completely

### Your environment

* AdGuard AdBlocker extension version:  3.0.7
* Environment name and version: Microsoft Edge 44.18353.1.0 / EdgeHTML 18.18353
* Filters you use in AdGuard: Base, Mobile Ads, Russian, Annoyances
* Any other browser extensions you have installed: None

**Comment by TheHasagi** [comment]
Unable to reproduce.

Please, reinstall or update the extension to the latest version and check again.

**Comment by akmLaVx** [comment]
User reports that the issue no longer manifests itself. Closing.
