### ISSUE TITLE
Cannot block some URLs using regex rules

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1325]
### Steps to reproduce

1. Add these rules:
```
/:\/\/[^\s]+(.club\/|.com\/|.online\/|.ru\/)[^\s]{50}/$xmlhttprequest,other,domain=hdgo.cc|vio.to,badfilter
/:\/\/[^\s]+(.club|.com|.online|.ru)\//$xmlhttprequest,other,domain=hdgo.cc|vio.to,badfilter
! UPD: also add this
||ldkdierujjfmcn.club^$third-party,badfilter
```
and one of these
```
/:\/\/[^\s]+(.club|.com|.online|.ru)\/[^\s]+/$xmlhttprequest,other,domain=hdgo.cc|vio.to
```
```
/:\/\/[^\s]+(.club|.com|.online|.ru)\//$xmlhttprequest,other,domain=hdgo.cc|vio.to
```
URL which must be blocked:
`https://ldkdierujjfmcn.club/zO0KK320rTlxNA23zPvnuujMiwk-il4hW7Rvn0z1ARvsEtKofyD2rAzSuLAlrO_3E4a7HlAsH6hZKsBuiA_aQhvGuluW48yo`
The first rule disables an old rule it Russian filter.
2. Open filtering log
3. Go to http://hdserial.cc/330-doktor-kto-11-sezon-2018-smotret-onlajn-serial-besplatno-hd-720.html and press Play button

### Actual behavior

<details>

![image](https://user-images.githubusercontent.com/8361299/54146575-f1f91100-4438-11e9-9079-56cb039d0b92.png)

</details>

### Expected behavior

Requests must be blocked, like with AG for Windows

<details>

![image](https://user-images.githubusercontent.com/8361299/54146645-1b19a180-4439-11e9-8a79-0a2b92a3e1cb.png)

</details>

* AdGuard AdBlocker extension version: 3.0.8
* Environment name and version: Chrome

**Comment by maximtop** [comment]
Couldn't reproduce.
Also I do not understand, why should to work rule
`/:\/\/[^\s]+(.club|.com|.online|.ru)\//$xmlhttprequest,other,domain=hdgo.cc|vio.to`
along with
`/:\/\/[^\s]+(.club|.com|.online|.ru)\//$xmlhttprequest,other,domain=hdgo.cc|vio.to,badfilter`

This rule
`/:\/\/[^\s]+(.club|.com|.online|.ru)\/[^\s]+/$xmlhttprequest,other,domain=hdgo.cc|vio.to`
blocks requests properly
https://uploads.adguard.com/maximtop_dicno.png
https://uploads.adguard.com/maximtop_s0cxr.png

**Comment by maximtop** [comment]
Regex rules are working properly, but there is a bug described here #1328
