### ISSUE TITLE
Missing previous statistics information

### ISSUE THREAD

**Issue by NguyenPhucAn** [AdguardTeam/AdguardBrowserExtension#1326]
It only show the current statistic information

### Actual behavior

<details><summary>Screenshot:</summary>

![Screenshot from 2019-03-12 09-13-15](https://user-images.githubusercontent.com/27940316/54169875-2c999280-44a7-11e9-9f36-d3703a381b77.png)

</details>

### Your environment

* AdGuard AdBlocker extension version: 3.0.8
* Environment name and version: Chrome 72.0.3626.121
* OS: Ubuntu 18.10

**Comment by ameshkov** [comment]
Do you mean the stats you had before the upgrade?

**Comment by NguyenPhucAn** [comment]
No, I mean the statistics of previous days. 
I installed Adguard last Friday and used it until now. But the statistics tab only show the stats of the current day.

**Comment by aspasskaya** [comment]
Hi!
I cant repro this particular issue.
@NguyenPhucAn  are problems still reproducible?

**Comment by NguyenPhucAn** [comment]
Hi @aspasskaya ,
I'm not sure this issue is still reproducible. After I updated to Adguard 3.0.13, it didn't happen.  I don't know root cause but it may be the problem from OS. 
I use dual boot Windows 10 and Ubuntu , it's only happened when I switch Windows to Ubuntu.
