### ISSUE TITLE
Selector lib creates an invalid rule

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#133]
Steps to reproduce:

1. Open "bild.de"
2. Scroll down and try to block "Tweets aus der Redaktion" element:
http://screencast.com/t/3DA2hmOuufZ

3. You'll see that selector created by us is invalid:
```bild.de###innerWrapper > DIV.faux.clearfix:nth-child(10) > DIV.content.s15 > SECTION > DIV > DIV.pagination:last-child > DIV.module.tlx > DIV.tlw-15.clearfix > DIV.misc..posLast > DIV.pm-hot-bei-bild:last-child > UL > LI:last-child```

The problem is in two dots: DIV.misc**..**posLast

**Comment by Mizzick** [comment]
Fixed
