### ISSUE TITLE
CSS rules with `url` are ignored in user filter and in trusted custom filter

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1332]
Related to https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1196
These rules are working in user filter in AdGuard 7.0

### Steps to reproduce

1. Add `#$#body { background: url(https://avatars3.githubusercontent.com/u/41899455); }`
2. Open exapmle.org

### Actual behavior

<details>

![image](https://user-images.githubusercontent.com/8361299/54354211-b9d31780-465e-11e9-9d43-f03c469dd1c2.png)

</details>

### Expected behavior

<details>

![image](https://user-images.githubusercontent.com/8361299/54354257-d4a58c00-465e-11e9-8954-25880d13639e.png)

</details>

**Comment by ameshkov** [comment]
CSS rules with URL are forbidden regardless of if it's a trusted filter or not.
