### ISSUE TITLE
Hidden elements/CSS rules are not counted in AdGuard's icon

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1333]
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/54393566-2aa41f00-46b3-11e9-8035-2104cc3caa74.png)

</details>

* AdGuard AdBlocker extension version: 3.0.8
* Environment name and version: Chrome

**Comment by ameshkov** [comment]
That's intended, icon counter is for blocked requests only

**Comment by ameshkov** [comment]
Hidden elements are reported to the log only when filtering log is open, we can't count them every time

**Comment by Alex-302** [comment]
Ok, got it.
