### ISSUE TITLE
Incorrect Blocked Count?

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardBrowserExtension#1336]
The count of blocked elements on the extension icons and the count of 'actual' blocked elements as seen in the 'Filtering Log' are possibly not right.

Screenshot: http://prntscr.com/myowav

URL to check: http://dafabet.pl

Issue seen in the latest version (3.0.8).

**Comment by maximtop** [comment]
On the specified page occures redirect `http://dafabet.pl` -> `http://dafabet.pl/?z`
Filtering log page displays blocked requests after this redirect, while extension icon displays all blocked requests till page reloaded or opened in the tab. 
If you'll check preserve log checkbox, then you'll be able to see all requests on the page.
@ameshkov i'm not sure if it is a bug)

**Comment by ameshkov** [comment]
Well, this is too complicated to fix

**Comment by Nzzyme** [comment]
Not sure why is it so complicated. AG already shows the stats - it's just that some changes need to be made to now show correct stats on the page. I am not referring to the redirect example mentioned above but the stat counts on the same page.

Ex: Visit the following webpage "https://www.wilderssecurity.com" when the AG Chrome extension is turned off. You will see the cookie notice on this page.

Now turn on AG on this page and you will see the page reloaded and the cookie notice now disappears. However, the count of blocked elements is still 0 which is clearly incorrect.

**Comment by ameshkov** [comment]
> Now turn on AG on this page and you will see the page reloaded and the cookie notice now disappears. However, the count of blocked elements is still 0 which is clearly incorrect.

This is because we do not indicate cosmetic rules in the badge.

The thing is that collecting cosmetic rules hits is a little bit expensive so it is done only when the filtering log is opened.
