### ISSUE TITLE
"Send statistics..." causes the tab to hang on gosuslugi.ru

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardBrowserExtension#1337]
1. Включить "Отправлять статистику использования фильтров"
 2. Зайти на [https://www.gosuslugi.ru/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.gosuslugi.ru/)
 3. Залогиниться на Госуслугах.
 4. Страница прокручивается, но на нажатия не реагирует. При этом сильно загружен процессор и начинается жор памяти. Сайты в новых вкладках не загружаются.

 Помогает только перезапуск браузера.

 Похоже на #1096.

 Проверил на следующих конфигурациях:
   Mozilla Firefox v53.0.3 (Win7SP1) - Adguard v3.0.9
   Mozilla Firefox v52.9 (WinVistaSP1) - Adguard v3.0.9
___________________________________________________
Базовый фильтр AdGuard | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и систем аналитики

**Comment by maximtop** [comment]
Мы повторили описанные вами шаги, но у нас проблема не повторилась. Можете прислать адрес страницы, на которой вы столкнулись с данной проблемой?

**Comment by ameshkov** [comment]
Список фильтров нам нужен

**Comment by XX-J** [comment]
Проверил ещё раз, с другой последовательностью:

 1. Удалил все свои правила (список стандартных фильтров - в первом сообщении).
 2. Зашёл на главную страницу [https://www.gosuslugi.ru/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.gosuslugi.ru/) (как по ссылке).
 3. Залогинился (Это ВАЖНО) (После этого остаёшся на главной странице (как по ссылке выше)).
 4. Включил "Отправлять статистику использования фильтров".
(до сих пор курсор реагирует на ссылки на странице, меняя свой вид со стрелки на руку)
 5. Перезагружаю страницу Госуслуг.
 6. Она перезагружается, но курсор перестаёт реагировать на ссылки на странице.
     Причём перестаёт реагировать и кнопка перезагрузки этой вкладки.
     Диспетчер задач, после 5-го пункта, показывает большую (60-80%) загрузку процессора, загрузка памяти прыгает на 100 МБ вверх и продолжает неспешно расти (до полного зависания браузера я не дожидался но, думаю, минут через 15 он бы повис, с 2-мя ГБ оперативки).
 7. Перехожу на вкладку с настройками AdGuard'a и выключаю "Отправлять статистику использования фильтров".
 8. Перезапускаю браузер.
 9. Опять захожу на страницу Госуслуг -> Логинюсь -> Всё работает.

 Проверял и на чистом профиле второй конфигурации (которая с Vist'ой) - тоже самое.

**Comment by XX-J** [comment]
С v3.0.10 ошибка повторяется...

     Дополню наблюдения:
 1. Во второй конфигурации (FF 52.9) при зависании вкладки вверху страницы появляется всплывающее сообщение, что-то типа: "Эта страница замедляет работу браузера..." и кнопки "Остановить" и, вроде, "Продолжить". При нажатии "Остановить" работа браузера продолжается как ни в чём не бывало.
 2. Скорость потребления памяти, при зависании, ~ 5-10 МБ/сек.

**Comment by ameshkov** [comment]
@XX-J мы пока еще не правили (хотя примерно понимаем в чем косяк), в следующем релизе подправим

**Comment by maximtop** [comment]
In order to test you have to install firefox with a version lower than 55 and test that error there is not reproducible and counting of cosmetic rules hits is not working.

Also, you have to test extension in the FF with the version higher than 55 and cosmetic rules hit should be visible in the filtering log.

**Comment by XX-J** [comment]
Теперь, с Firefox v53.0.3 (Win7SP1), всё работает без зависания.
 Большое Спасибо!

**Comment by XX-J** [comment]
Вы, оказывается, НА ВСЕХ САЙТАХ отключили отображение косметических правил в журнале?
Если так, то, пожалуйста, - ВЕРНИТЕ! А то это похоже на лечение, путём омпутации.
Я лучше отключу "Отправку статистики...", чем лишаться столь ВАЖНОГО контроля.

**Comment by maximtop** [comment]
Только для FF версии ниже 55

**Comment by XX-J** [comment]
> Только для FF версии ниже 55

 Я понимаю, НО я пользуюсь ещё и Windows XP (и я такой не один), на котором максимально поддерживаемая версия FireFox - 52.9 .
 А подсветка косметических правил в ЖУРНАЛЕ - **КРАЙНЕ** НЕОБХОДИМА!

 Поэтому прошу Вас - Пожалуйста верните подсветку косметических правил в журнале.

 А вышеозначенную проблему лучше решить другим способом, например отключать сбор статистики на этом сайте или отключать сбор статистики для версий < 55.
 В конце-концов я лучше отключу сбор статистики, чем потеряю столь **ВАЖНЫЙ** функционал!

**Comment by ameshkov** [comment]
А дело не в сборе статистики же, там просто один и тот же механизм используется для косметических правил в журнале.

По идее, есть альтернативное решение, для которого не нужно будет отключать подссчет косметики:
1. Если для сайта имеется `$elemhide`-исключение, то нужно отключить сбор хитов
2. Для госуслуг добавить правило `@@||gosuslugi.ru^$elemhide` в пользовательский фильтр

**Comment by XX-J** [comment]
> По идее, есть альтернативное решение, для которого не нужно будет отключать подссчет косметики:

>   1. Если для сайта имеется $elemhide-исключение, то нужно отключить сбор хитов
>   2. Для госуслуг добавить правило @@||gosuslugi.ru^$elemhide в пользовательский фильтр

 Полностью поддерживаю такой вариант. Ведь негоже отключать столь важный функционал для всех сайтов из-за одного.

 Кстати, а Вы случайно не выяснили, какой **именно** (из-за чего) конфликт возникает между сайтом ГосУслуг, подсчётом косметических правил AdGuard'ом и FireFox'ом < 55 версии?

**Comment by ameshkov** [comment]
Из-за того что в FF 55 MutationObserver себя неадекватно ведет, но так как в более новых все ок, мы решили особо не концентрироваться на этом.

**Comment by XX-J** [comment]
Версии 3.1.1 и 3.1.3 теперь работают с сайтом ГосУслуг как и оговаривалось, т.е. при добавлении в список правил `@@||gosuslugi.ru^$elemhide` и включённой статистики - сайт не зависает после входа в учётную запись. За это - Спасибо, **НО!**

 Я провёл тестирование и пришёл к следующим результатам:

 Потребление Оперативной Памяти браузером FireFox v53.0.3 **при старте**, с AdGuard'ом версий 3.1.1 или 3.1.3 с Выключеной статистикой и с Включённой статистикой - Возросло.

 Причём с Включённой статистикой возросло настолько, что браузер начал загружаться на порядок дольше, - 20-30 минут вместо 2-3.

 У меня обычный ноутбук, с характеристиками: "2 ядра, 2 гига, а посередине Windows". И обычно его более-менее хватает. Но новые версии AdGuard'a ставят крест на моей скромной экосистеме, если использовать их с включённой статистикой. С выключенной они, кстати, тоже начали потреблять больше памяти.

__________

 Вопреки версиям 3.1.1 и 3.1.3 версии 3.1.0 и 3.0.13 столько памяти  **при старте** браузера и Включённой статистики  **НЕ потребляют** и браузер стартует нормально - за 2-3 минуты.

 Привожу видео Диспетчера Задач (Process Hacker) полного старта браузера с версиями AdGuard'a 3.1.3 и 3.0.13, с Включённой и Выключенной статистикой. Все **расширения**, кроме AdGuard'a, **выключены**. Браузер стартует на странице [Релизов расширения AdGuard](https://github.com/AdguardTeam/AdguardBrowserExtension/releases). В конце старта я переключаюсь ещё по двум вкладкам, для проверки, и останавливаю видео.

 Потребление памяти **после старта, в покое**: браузером без AdGuard'a ~ 400-450 МБ; с AdGuard'ом v3.0.13 ~ 600 МБ; с AdGuard'ом v3.1.3 ~ 650 МБ .

 Прошу обратить внимание на потребление памяти браузером и занятую и свободную память системы в строке состояния.

 **1**. Версия 3.1.3 с ВКЛючённой статистикой: [Посмотреть](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://radikal.ru/video/cwVi04yCXx2) или [Скачать](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http://ge.tt/2kFGwQw2)

 Стартует ~ 12 мин. На видео видно три явно выраженных пика потребления памяти, при которых система уходит в своп и скорость загрузки сокращается в разы: ~ 1,5 ГБ на 2-4 мин., ~ 1,9 ГБ на 5-6 мин. и ~ 2 ГБ на 8-9 мин.

 Но это со **Всеми выключенными сторонними расширениями**. Если же их включить (а это необходимый мне комплект), то потребление памяти браузером **при старте** доходит до немыслимых **2,5 ГБ**, а время загрузки, до момента **начала работы** в нём, доходит до **40-60 минут**.

 **2**. Версия 3.1.3 с ВЫКЛюченной статистикой: [Посмотреть](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://radikal.ru/video/S92JN73zklc) или [Скачать](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http://ge.tt/3BgTBRw2)

 Стартует ~ 3 мин. Во время старта есть один пик ~ 1 ГБ.

 **3**. Версия 3.0.13 с ВКЛючённой статистикой: [Посмотреть](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://radikal.ru/video/vA4AsxSN47z) или [Скачать](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http://ge.tt/1Z2EHRw2)

 Стартует ~ 2 мин. Во время старта есть один пик ~ 1,2 ГБ.

 **4**. Версия 3.0.13 с ВЫКЛюченной статистикой: [Посмотреть](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://radikal.ru/video/fv8b3ctipV9) или [Скачать](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http://ge.tt/6PfYHRw2)

 Стартует ~ 2,5 мин. Во время старта есть один пик ~ 1,05 ГБ. (Стартовал чуть дольше, чем с включённой статистикой - может AdGuard фильтры обновлял?)

__________

 Я понимаю, что по современным меркам 2 ГБ ОЗУ - это маловато, но на одновременную работу с несколькими вкладками - хватает. И я думаю, что AdGuard не должен потреблять памяти столько, чтобы не хватало на работу в системе с 2 ГБ ОЗУ.
