### ISSUE TITLE
Block WebRTC is not working

### ISSUE THREAD

**Issue by adrianh-za** [AdguardTeam/AdguardBrowserExtension#1339]
Enabling "Block WebRTC" leaks local IP.

Test ran on this site

https://ip8.com/webrtc-test

* AdGuard AdBlocker extension version: 3.0.9
* Environment name and version: Chrome 72.0.3626.121 (Official Build) (64-bit)
* Filters you use in AdGuard: N/A
* Any other browser extensions you have installed: None

**Comment by ameshkov** [comment]
@adrianh-za I cannot reproduce this. Could you please show how does the issue look like on your side?

**Comment by Eugene-Savenko** [comment]
It leaks on my end in Yandex browser but does not leak in Chrome:

<details> <summary> Yandex </summary>

![image](https://user-images.githubusercontent.com/15856304/54524221-0d54a680-497a-11e9-80c4-e402d768ec43.png)

</details>


<details> <summary> Chrome </summary>

![image](https://user-images.githubusercontent.com/15856304/54524276-3c6b1800-497a-11e9-94b2-05bea7cad659.png)

</details>

It's also been reported here: ID 2141209

**Comment by adrianh-za** [comment]
> @adrianh-za I cannot reproduce this. Could you please show how does the issue look like on your side?

I rechecked.  Adguard does indeed block WebRTC.  The issue was due to the fact I had another extension name **WebRTC Leak Shield** running in Chrome which seemed to mess around with Adguard's blocking mechanism.  I also checked through a VPN and it also working there now.

Sorry for wasting your time.

**Comment by XX-J** [comment]
У меня тоже не работает:

 На https://ip8.com/webrtc-test

<details><summary>Screenshot:</summary>

![2019 03 22-2](https://user-images.githubusercontent.com/17948007/54849095-4e3f1900-4cf4-11e9-9c04-e88b353aeb13.png)
</details>

 ----------
На https://whoer.net/ru

<details><summary>Screenshot:</summary>

![2019 03 22-1](https://user-images.githubusercontent.com/17948007/54849143-7595e600-4cf4-11e9-88e1-38087719283d.png)
</details>

___________________________________________________
Mozilla Firefox v53.0.3 (Win7SP1) - Adguard v3.0.10
Базовый фильтр AdGuard | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и систем аналитики
