### ISSUE TITLE
[chrome] "Block ads on this site" button doesn't work if few windows are opened

### ISSUE THREAD

**Issue by gshumihin** [AdguardTeam/AdguardBrowserExtension#134]
Steps to reproduce:
1. Open at least two chrome windows
2. Install in one of them adguard extension
3. Tab to second one
4. Try to block something with button "Block ads on this site"

**Comment by Mizzick** [comment]
https://code.google.com/p/chromium/issues/detail?id=546696&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified&start=100

There is a possible bug in chrome in chrome with 
```chrome.windows.getLastFocused()```

**Comment by ameshkov** [comment]
Nice, so it's all good now?

**Comment by Mizzick** [comment]
Yeap, check the https://github.com/AdguardTeam/AdguardBrowserExtension/pull/167
