### ISSUE TITLE
$stealth modifier does not work in some cases

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/AdguardBrowserExtension#1342]
### Steps to reproduce

1. Enable Stealth mode
2. Go to this website - https://www.bilibili.com/video/av2075941?from=search&seid=12447341876205298842

### Expected behavior

Video player should works.

### Actual behavior

Video player not works due to Stealth mode. In AdGuard Base filter are these rules which should fix that issue (works with AG for Windows):
`@@||hdslb.com^$domain=bilibili.com,stealth`
`@@||acgvideo.com^$domain=bilibili.com,stealth`

In extension this rule works:
`@@||bilibili.com^$stealth`

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29142494/54601730-1445ec80-4a40-11e9-8f18-7d5215940939.png)

</details>

### Your environment

* AdGuard AdBlocker extension version: 3.0.8
* Environment name and version: Chrome 73.0.3683.75
* Filters you use in AdGuard:
* Any other browser extensions you have installed:

**Comment by maximtop** [comment]
After fixing issue described above we found that information in the filtering log about whitelist rule appears in the filtering log after almost one minute.
