### ISSUE TITLE
Syntax highlighting issues

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#1344]
* `$csp=script-src 'none',domain=example.org` -- $domain modifier is not highlighted
* Make `scriptlet` keyword highlighted by Ace

To be continued

**Comment by maximtop** [comment]
In order to test:
1. add the rule to the user filter
`example.org#%#//scriptlet("abort-on-property-read", "alert")`
`scriptlet` word should be highlighted
2. add the rule
`$csp=script-src 'none',domain=example.org`
domain modifier should be highlighted
