### ISSUE TITLE
Chrome Extension does not handle all requests

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/AdguardBrowserExtension#1348]
Visit this site while Chrome Extension is showing filter protocol:
https://static.crunchyroll.com/vilos/player.html

No requests are shown. When doing the same with FireFox it works fine.
This issue results in ads getting played on crunchyroll.com with US IP.

https://github.com/AdguardTeam/AdguardFilters/issues/29942

**Comment by maximtop** [comment]
Somehow requests do not trigger event listeners in the browser.webRequest api after the site is cached.
After clearing cache, request events appear for 1-2 page reloads and then disappear again.
Seems like this is an chrome bug.

**Comment by BlazDT** [comment]
Is there a ticket number at Google yet?

**Comment by ameshkov** [comment]
Guys, could it be that this request is cached by a service worker?

**Comment by maximtop** [comment]
I didn't find there any service workers
It is application cache
https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache

**Comment by BlazDT** [comment]
So we are waiting for Google to fix it?

**Comment by ameshkov** [comment]
Yes, and we need to file a bug report to them.

**Comment by maximtop** [comment]
I have filled the issue here
https://bugs.chromium.org/p/chromium/issues/detail?id=952882

**Comment by maximtop** [comment]
I'm closing this issue because chrome developers won't fix this bug.
https://bugs.chromium.org/p/chromium/issues/detail?id=952882#c5

**Comment by BlazDT** [comment]
Great google :(

**Comment by ameshkov** [comment]
As usual
