### ISSUE TITLE
[Request] Enable/disable user filter switcher

### ISSUE THREAD

**Issue by oleedd** [AdguardTeam/AdguardBrowserExtension#1352]

**Comment by XX-J** [comment]
Добавьте, пожалуйста, выключатель пользовательского фильтра на отдельную страницу редактирования этого самого пользовательского фильтра.

![2022 06 24-2](https://user-images.githubusercontent.com/17948007/175457752-769f0576-5d5f-4ae8-8709-8cadface6c87.png)

 А то неудобно - редактируешь на одной странице, а лезть за полным отключением надо в настройки - на другую страницу. Я всегда держу страницу редактирования пользовательских правил открытой, а держать открытой страницу настроек из-за одной из них - это перебор.

**Comment by maximtop** [comment]
@XX-J заведите новую задачку с фиче реквестом
