### ISSUE TITLE
logger

### ISSUE THREAD

**Issue by bogachenko** [AdguardTeam/AdguardBrowserExtension#1353]
Я не знаю куда писать, чтобы спросить? Этот вопрос вы скорее всего закроете, так как тут о проблемах расширения пишут, а не о вопросах. Возможно мне стоило написать сюда https://github.com/AdguardTeam/deep-override, а не вам... короче...

~Какого черта~ Почему в логгере не отображаются скриптлеты?
типа таких 
```
AG_removeCookie
AG_abortOnPropertyWrite(property, debug)
AG_abortOnPropertyRead(property, debug)
AG_abortInlineScript(regex, property, debug)
```
Каким таким образом я должен догадаться какой именно скриптлет работает на сайте, если об этом логгер не сообщает? Лезть непосредственно в RAW лист и как неандерталец проверять сайт на котором я нахожусь в RAW листе.

@ameshkov как на счет запилить такую опцию, например флажок в настройках для "Продвинутых пользователей"? Или если я опростоволосился и такая функция уже есть (ее нет), как мне ее включить (никак)?

**Comment by ameshkov** [comment]
@bogachenko а ведь блин хороший вопрос.

1. Изначально, мы хотели делать относительно сложную схему, при которой скриптлеты в логе будут отображаться только если они свою работу выполняют (вот именно ее мы внедрим в 3.1). Типа если abortOnPropertyRead действительно абортнул выполнение.
2. А с другой стороны, почему бы нам сразу не выводить список всех заинжекченных скриптов в логе, и как-то среди них помечать те, которые отработали как задумывалось?

Чего думаете?

**Comment by bogachenko** [comment]
ну для меня было бы радостью хотя бы до 1 варианта до жить @ameshkov

**Comment by ameshkov** [comment]
@bogachenko в программах пока что сделаем "вариант 0" -- просто выводить список заинжекченных скриптов без дополнительной индикации.

Вариант 2 вроде прикольнее звучит, надо подумать как визуально отобразить.

Мы репозиторий скриптлетов еще не выложили, но как выложим - там можно будет увидеть, как этот механизм реализован.

**Comment by Alex-302** [comment]
> просто выводить список заинжекченных скриптов без дополнительной индикации.

поскорее бы) https://github.com/AdguardTeam/AdguardForWindows/issues/1796

**Comment by bogachenko** [comment]
@ameshkov и кстати, такое дело, у вас в логгере нет возможности вывести список заблокированных + разрешенных запросов. Хочу вывести все на что триггерится на сайте. Список заблокированных запросов и список разрешенных, все вместе, но логгер мне не дает, смотри
![1](https://user-images.githubusercontent.com/8535285/55274695-f182c600-52d2-11e9-8b2d-47c7d3a78bf0.gif)

**Comment by ameshkov** [comment]
Ага, не очень удобно, вот так мы сейчас сделаем на винде и маке:
https://uploads.adguard.com/slbdzd8llhm6e.png

В расширении тоже так нужно будет сделать.

**Comment by bogachenko** [comment]
> Ага, не очень удобно, вот так мы сейчас сделаем на винде и маке:
https://uploads.adguard.com/slbdzd8llhm6e.png

круто, круто, круто

> В расширении тоже так нужно будет сделать.

Этого я так понимаю не будет в версии 3.1? Не давлю. Просто спрашиваю.

**Comment by ameshkov** [comment]
Пока что выставил 3.1, но у нас там уже много накопилось на этом майлстоуне, можем передвинуть что-то.

**Comment by bogachenko** [comment]
@ameshkov 
Впадлу создавать новую тему, писать буду здесь.
Можешь сделать [это вот меню](https://user-images.githubusercontent.com/8535285/70374178-1a6c5800-1944-11ea-9e76-7088df80c132.png) подвижным? Я бы хотел его закрепить 
снизу окна.

**Comment by ameshkov** [comment]
Типа как в хроме?

**Comment by bogachenko** [comment]
Ага. И еще, пока я окончательно не обнаглел, еще бы в логгере прикольно было видеть - не желательные типы запросов, чекни, как сделали твои конкуренты 
![Безымянный](https://user-images.githubusercontent.com/8535285/70439119-630e4780-1ae3-11ea-8d6a-db5a3ae913d3.png)
