### ISSUE TITLE
Wrong domain detection (Auto-activation of the filters)

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardBrowserExtension#1354]
yadi.sk has been detected incorrectly.

### Steps to reproduce

1. Open Opera with the latest extension installed
2. Open this (link)[https://yadi.sk/d/a73IuXnHAgW9JA]

<details><summary>Screenshot:</summary>

![img](https://uploads.adguard.com/TheHasagib5pis.jpg)

### Your environment

* AdGuard AdBlocker extension version: 3.0.10
* Environment name and version: (e.g. Chrome 59.0.3071.115): Opera

**Comment by ameshkov** [comment]
Ignore hostnames which length is less or equal to 8.
