### ISSUE TITLE
Filtering Log: add "filter" settings 

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#1358]
Just like what we have in the new Mac and Win versions:
https://uploads.adguard.com/slbdzd8llhm6e.png

**Comment by XX-J** [comment]
Удобнее было бы иметь кнопки фильтрации сразу на панели, без меню. Можно сократить полосу поиска, для освобождения места под кнопки. Можно кнопки сделать квадратиками, которые подсвечиваются при нажатии, а для их обозначения помещать первую заглавную букву внутрь квадратика и, при наведении, показывать полное название опции во всплывающей подсказке.

**Comment by XX-J** [comment]
Как я понимаю, это уже реализовано в новом интерфейсе 4-й версии и можно закрывать. Или ..?
