### ISSUE TITLE
Blocked iframe flickering 

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1359]
### Steps to reproduce

1. Add `forum.watch.ru#@#iframe[src*="clientscript/a_"]`
2. Open http://forum.watch.ru/

### Actual behavior
You will see blocked iframes very short time. Collapsing is slow on this site. 

### Your environment

* AdGuard AdBlocker extension version: 3.0.11

**Comment by ameshkov** [comment]
@Alex-302 this is not something that can be easily fixed, unfortunately.

**Comment by Alex-302** [comment]
got it
