### ISSUE TITLE
"Remove X-Client-Data header" should be specific to Google Chrome only

### ISSUE THREAD

**Issue by Big-U-Boss** [AdguardTeam/AdguardBrowserExtension#1362]
### Steps to reproduce

1. Не выставляется настройка убирать x-клиент у запросов! Включил и при переходе  и обратно сбрасывается!
2.
3.
4.

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

<details><summary>Screenshot of the browser console:</summary>

</details>

### Your environment

* AdGuard AdBlocker extension version: 3.11
* Environment name and version: (e.g. Chrome 59.0.3071.115) Chrome/71.0.3578.98 Safari/537.36 OPR/58.0.3135.127
* Filters you use in AdGuard :раздражители, кнопки соц. сетей, русский,английский, аналитика
* Any other browser extensions you have installed: нет

**Comment by maximtop** [comment]
Здравствуйте, у меня не получилось повторить.
Опишите, пожалуйста подробно действия, которые воспроизводят проблему.

**Comment by Big-U-Boss** [comment]
Как и было написано, сбрасывается в режиме антитреканга опция скрывать x-клиент! Галку поставил, а она снимается при повторном заходе.

**Comment by maximtop** [comment]
"при повторном заходе" - это вы имеете в виду, что вы выключаете браузер?

**Comment by Big-U-Boss** [comment]
Достаточно просто перейти на другую вкладку к примеру!

**Comment by maximtop** [comment]
А какие-то ошибки в консоли есть при этом?

**Comment by Big-U-Boss** [comment]
В инспекторе?

**Comment by maximtop** [comment]
в инструментах разработчика

**Comment by Big-U-Boss** [comment]
Это ж не страница!😏

**Comment by maximtop** [comment]
> Это ж не страница!😏
опции экстеншена это страница
у вас есть скайп, телеграмм? может там будет удобнее пообщаться?

**Comment by Big-U-Boss** [comment]
я не знаю,как в консоли разработчика определить ошибку, там только показывает ошибки запросов URL

**Comment by Big-U-Boss** [comment]
Я не знаю как в консоли разработчика определить ошибку, там только показывает ошибки запросов URL насколько мне известно!

**Comment by Big-U-Boss** [comment]
> у вас есть скайп, телеграмм? может там будет удобнее пообщаться?

whatsup есть!

**Comment by Big-U-Boss** [comment]
> у вас есть скайп, телеграмм? может там будет удобнее пообщаться?

whatsapp есть!

**Comment by maximtop** [comment]
можете мне на почту `maximtop@gmail.com` прислать ваш номер телефона, чтобы тут не его не показывать всем

**Comment by maximtop** [comment]
This issue is relative to Opera
There is no need to use show `Remove X-Client-Data header` option for Opera, so we should remove it from options page

**Comment by ameshkov** [comment]
@maximtop actually, it must be shown in Google Chrome only, and not in other chromium-based browsers.
