### ISSUE TITLE
Adguard extension sometimes manages wrong Chrome tab in private mode

### ISSUE THREAD

**Issue by Dmitriusan** [AdguardTeam/AdguardBrowserExtension#1363]
### Steps to reproduce
Not sure about exact steps since it's intermittent, but looks like that
1. Enable 'Allow in incognito' Chrome setting for Adguard extension 
2. Open few tabs at Chrome non-private mode, and one or few tabs at a private mode
3. Switch to non-private tab, and then to a private tab
4. Click on Adguard extension and check site URL for a private tab. If bug reproduces, Adguard extension menu will show a wrong url (from a non-private tab) at a private tab. Attempt to disable protection will disable protection for a wrong Chrome tab.
5. If I close and open Adguard extension menu at this point, that often solves an issue. But if I switch to a non-private tab, and then back to a private tab, the bug reproduces again.

### Expected behavior
Adguard should show current site name, and manage current tab when the extension menu is opened at a private Chrome tab

### Actual behavior
Looks like Adguard sometimes can not track current open tab when running in Chrome private mode. 

<details><summary>Screenshot:</summary>

![scr1](https://user-images.githubusercontent.com/1825803/55687636-f2bd8e00-5977-11e9-9313-9d3910371a4b.png)

</details>

<details><summary>Screenshot of the browser console:</summary>
</details>

### Your environment

* AdGuard AdBlocker extension version: 3.0.11
* Environment name and version: Version 73.0.3683.86 (Official Build) (64-bit)
* Filters you use in AdGuard:
* Any other browser extensions you have installed:
```
Enabled
Add-ons for Evernote Web App
AdGuard AdBlocker
Celestial Lights
Crypto-Plugin
ePN CashBack Plugin
Export links of all extensions
Google Analytics Opt-out Add-on (by Google)
Google Docs Offline
Google Drive
Google Play Music
Grammarly for Chrome
JSONView
Mercury Reader
MindMeister
Protect My Choices
Save to Pocket
Take Webpage Screenshots Entirely - FireShot
The Great Suspender

Disabled:
Evernote Web Clipper
Honey
uMatrix
```
Note: Maybe the bug is related to the fact that I use 2 monitors

**Comment by ameshkov** [comment]
Sounds like a very interesting bug, thank you!

**Comment by maximtop** [comment]
Can't reproduce.
@Dmitriusan can you write me in the telegram? My id there is @maximtop too.

**Comment by maximtop** [comment]
User uses linux mint xfce + xmonad
`browser.tabs.query({ currentWindow: true, active: true }` call seems is not working properly
after user created new incognito window, browser continue to return tabs for previous window.
