### ISSUE TITLE
Please add a placeholder to #49280753 of welcome page.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardBrowserExtension#1365]
@aalpatkina
@maximtop 

http://adguard.oneskyapp.com/collaboration/translate/project/project/155819/language/2#/?keyword=%2349280753

Compatible with
-> Compatible with [placeholder]
or -> Compatible with these OSs

What's it after "with"?
Icons or words?

If they're icons after "with", maybe modify it as:
Compatible with these OSs (Windows icon) (macOS icon) ...

I remember the phrase is from website.
Before, I used the translation of "Compatible with these OSs" as its translation

**Comment by aalpatkina** [comment]
@lancelot-moon 
Yes, there are icons after this phrase. Your translation into Chinese as "Compatible with these OSs" is appropriate in this case. For other languages, we will leave this phrase as it is. Thank you.
