### ISSUE TITLE
Add $redirect and $rewrite support

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#1367]
See the `$redirect` and `$rewrite` definitions in uBO and ABP.

**Comment by jeffreymcclain** [comment]
Potential vulnerability: https://adblockplus.org/blog/potential-vulnerability-through-the-url-rewrite-filter-option

**Comment by ameshkov** [comment]
Yeah, I saw the news. It seems they're going to completely remove the $rewrite base functionality and just keep the `abp-resource:` part of it.

It basically means that `$rewrite` will now do virtually the same as `$redirect`. Well, it's actually good news.

My comment on the issue in general:
> 1. AdGuard does not let using powerful modifiers in third-party filter lists.
> 2. All the filters which are offered in AdGuard products are served from AdGuard server, and the purpose is to strip them of unsupported or too powerful modifiers and be able to react if a filter list author decides to do anything abnormal. For instance, in the case with politically motivated attack mentioned in the article, we quickly reacted and updated the filter list on our server.

**Comment by superlex** [comment]
Thanks for your comment @ameshkov :)
