### ISSUE TITLE
Extended CSS logging 

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/AdguardBrowserExtension#1370]
On http://lordfilms.tv/ rule `lordfilms.tv,lordfilm.tv#$#.wrap:has(> div) { margin-top: 0!important; }` logging as

![slbdzd8lazii2](https://user-images.githubusercontent.com/45171506/56222393-98f24d80-6074-11e9-870c-6747f93a76d4.png)

* AdGuard 3.0.13 beta
* Chrome 73

**Comment by maximtop** [comment]
In order to test open `http://lordfilms.tv/` with the Russian filter enabled. 
Applied Extended CSS rule should be displayed in the filtering log as a cosmetic rule with yellow color.
All rule details should be displayed correctly.
