### ISSUE TITLE
Change the default configuration on welcome page.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardBrowserExtension#1371]
After the installation, `Allow search ads and the self-promotion of websites.` is enabled by default on welcome page.
Why?
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/oYlIz9L.png)
</details><br/>

Is it possible to change the default configuration on welcome page as the below?
At least, `Allow search ads and the self-promotion of websites.` should be **disabled** by default on welcome page.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/qoOoUGT.png)
</details><br/>

Thanks.

**Comment by lancelot-moon** [comment]
@ameshkov 
@maximtop 

https://malwaretips.com/threads/updated-29-12-2018-browser-extension-comparison-malwares-and-phishings.80915/

After checking, browsing security, tracking protection filter, social media filter and annoyances filter are disabled in your original configuration on welcome page by default.

That's why I think it's better to change the default configuration.

**Comment by TheHasagi** [comment]
@lancelot-moon 

It is not related to AdGuard, for some people, self-promo & search ads might be helpful.

**Comment by lancelot-moon** [comment]
Filter unblocking search ads and self-promotion is disabled in paid AdGuard products by default.
AG Browser Extension is free, which is the difference.
Just beginners don't know how to do better configuration.
