### ISSUE TITLE
Request Info Popup doesn't disappear if Filtering Log is opened for another tab

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/AdguardBrowserExtension#1372]
<b>Expected behaviour</b>
When filtering log is opening for another tab Request Info Popup for previous one shouldn't be opened.

[▶️ <b>Actual behaviour</b> (start at 0:20)](https://uploads.adguard.com/slbdzd8laer1z.mp4)

* AdGuard 3.0.13
* Chrome 73

**Comment by slavaleleka** [comment]
Also Search field isn't empty after Filtering Log is opened for another tab if user searched something earlier (just noticed that and actually I don't know is that correct or not)

**Comment by maximtop** [comment]
> Also Search field isn't empty after Filtering Log is opened for another tab if user searched something earlier (just noticed that and actually I don't know is that correct or not)

I do not think that it would be an appropriate behavior to clear search on tab switch.

**Comment by maximtop** [comment]
In order to test repeat actions from the above video. 
Detailed popup should close if a user opens a new site.
