### ISSUE TITLE
Persist original rule text in the rule converter and reuse it in the filtering log

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#1381]
The only purpose is to print it in the filtering log:
https://uploads.adguard.com/up04_xk1a2_Filtering_log.png

**Comment by maximtop** [comment]
in order to test add a rule in the user filter
`yandex.ru##body:style(background:inherit;)`
go to yandex.ru
open filtering log
in the filtering log, you should find cosmetic hit by user rule
in the details of the rule, you will find original rule and result of conversion

**Comment by XX-J** [comment]
> in order to test add a rule in the user filter
> `yandex.ru##body:style(background:inherit;)`

 Правило применяется, но в журнале его не видно.
Пробовал то же правило и на example.org , с тем же результатом:
`example.org##body:style(background:inherit;)`

**Comment by maximtop** [comment]
> Правило применяется, но в журнале его не видно.

В FF ниже 55 версии статистика по косметическим правилам отключена.

**Comment by XX-J** [comment]
Теперь - работает.
