### ISSUE TITLE
Strona google.com się dłużej ładuje z AdGuardem.

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardBrowserExtension#1384]
Kółko ładowania na głównej stronie w chrome jak mamy adguarda to się kręci o wiele dłużej, co się przekłada na dłuższe ładowanie strony, bez adguarda nie ma takich problemów,

**Comment by ameshkov** [comment]
Hi! I cannot reproduce this with AdGuard so I suggest this might be a compatibility issue with some other browser extension.

Which extensions besides AG do you have?
Could you please try disabling all of them and see if it changes anything?

**Comment by en57001** [comment]
Mam tylko jedne rozszerzenie i jest nim AdGuard, usunąłem nawet domyślne rozszerzenia.

**Comment by zzebrum** [comment]
@en57001 hello!
does the problem still happen with the latest AdGuard version? What filters are enabled?

**Comment by zzebrum** [comment]
reopen if needed
