### ISSUE TITLE
Extension Won't Translated to PT-BR

### ISSUE THREAD

**Issue by ialexsilva** [AdguardTeam/AdguardBrowserExtension#1387]
My name's is Alex, and I'm the moderator of PT-BR translation

### Steps to reproduce

1. Change Windows Language to Portuguese Brazilian
2. Open Browser and AdGuard

### Expected behavior

The extesion display in Portuguese Brazilian

### Actual behavior

The extesion display in English

<details><summary>Screenshot:</summary>

![photo_2019-04-26_09-27-33](https://user-images.githubusercontent.com/6363160/56809209-b7d9a800-6809-11e9-80cb-f080ef7b21f4.jpg)
![photo_2019-04-26_09-24-37](https://user-images.githubusercontent.com/6363160/56809216-ba3c0200-6809-11e9-8d92-9b7852a246b9.jpg)
![photo_2019-04-26_07-49-36](https://user-images.githubusercontent.com/6363160/56809222-bf00b600-6809-11e9-815d-e0bb3d61b189.jpg)
![photo_2019-04-26_07-46-08](https://user-images.githubusercontent.com/6363160/56809227-c2943d00-6809-11e9-80f2-bafd47457516.jpg)

</details>

<details><summary>Screenshot of the browser console:</summary>

![image](https://user-images.githubusercontent.com/6363160/56809968-81049180-680b-11e9-9984-67ab5c86be82.png)

</details>

### Your environment

* AdGuard AdBlocker extension version: 3.0.13
* Environment name and version: Microsoft Edge 44.17763.1.0
* Filters you use in AdGuard: Default Filters (AdGuard Base +  Specific for langague Portuguese
* Any other browser extensions you have installed: No

<details><summary>Config Export:</summary>

`{"protocol-version":"1.0","general-settings":{"app-language":"pt-BR","allow-acceptable-ads":false,"show-blocked-ads-count":true,"autodetect-filters":true,"safebrowsing-enabled":false,"safebrowsing-help":false,"filters-update-period":172800000},"extension-specific-settings":{"use-optimized-filters":false,"collect-hits-count":false,"show-context-menu":true,"show-info-about-adguard":false,"show-app-updated-info":true},"filters":{"enabled-groups":[1,6,7],"enabled-filters":[2,9],"custom-filters":[],"user-filter":{"rules":"","disabled-rules":""},"whitelist":{"inverted":false,"domains":[],"inverted-domains":[]}}}`

**Comment by maximtop** [comment]
Thank you, Alex. I'll take care of this issue)

**Comment by maximtop** [comment]
@aalpatkina 
Seems that translations were not applied because Chrome can't apply translations from the folders named as `'pt-BR', 'pt-PT'`. It applies translations only from folders which are named as `'pt_BR', 'pt_PT'`.
I had changed these folders and codes in November of last year.
Maybe do you remember why we could have decided to change these codes?

**Comment by ialexsilva** [comment]
@maximtop I tested the new version that @aalpatkina sent me and its working now
