### ISSUE TITLE
JS rules not work in Edge

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/AdguardBrowserExtension#1389]
### Steps to reproduce

1. Add this rule to user filter:
`#%#alert("test");`
2. Go to any website, for example https://adguard.com/

### Expected behavior

JS rule should works and there should be an alert.

### Actual behavior

JS rule not work.

### Your environment

* AdGuard AdBlocker extension version: 3.0.13
* Environment name and version: Microsoft Edge 44.17763.1.0
* Filters you use in AdGuard: Base
* Any other browser extensions you have installed: -

**Comment by maximtop** [comment]
This issue was fixed in #1366 
Check please when the new release will be out.

**Comment by AdamWr** [comment]
Works fine with the latest version (3.1.1) 👍
