### ISSUE TITLE
Adguard extention stops being in assistant mode on some sites

### ISSUE THREAD

**Issue by gurgun-dayioglu** [AdguardTeam/AdguardBrowserExtension#1392]
### Steps to reproduce
1. Go to a new tab where no filtering is done (IMPORTANT)
2. Visit directly using the address bar on Chrome (with both extension and Adguard for Windows installed): "https://www.rottentomatoes.com/"

### Expected behavior
Adguard Extension should let the desktop app do its job.

### Actual behavior
The extension doesn't go into assistant mode but it starts blocking ads.

Screenshot: http://prntscr.com/nj7mld

Note: When Google is visited first, after you search for Rotten Tomatoes and go to it's website. Adguard Extension works as intended.

Screenshot 1: http://prntscr.com/nj7njn
2: http://prntscr.com/nj7nrf
3: http://prntscr.com/nj7o51

I don't know if it is a display glitch or actually a bug where it just starts blocking on itself

* AdGuard AdBlocker extension version: Latest stable
* Environment name and version: Latest stable
* Filters you use in AdGuard: Base, Spyware, Turkish, Annoyances
* Any other browser extensions you have installed: Enpass, Office Online

**Comment by gurgun-dayioglu** [comment]
Some other site I found where the same can be produced:
1: Visit https://www.gittigidiyor.com/ using the adress bar on Chrome
Using google search first instead again solves the problem.

**Comment by gurgun-dayioglu** [comment]
I think once it goes into assistant mode its fine but going to a link from a new tab causes the issue.

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/CoreLibs/issues/597
