### ISSUE TITLE
Impossible install firefox extension

### ISSUE THREAD

**Issue by parkito** [AdguardTeam/AdguardBrowserExtension#1393]
I use firefox 66.0.3 MacOs. I try to download extension from https://addons.mozilla.org/en-GB/firefox/addon/adguard-adblocker/. But after clicking  + Add to Firefox i got **Download failed. Please check your connection.** Other extensions from this website i can install.

**Comment by vitalkanev** [comment]
Probably a browser bug. See https://bugzilla.mozilla.org/show_bug.cgi?id=1548973

**Comment by parkito** [comment]
Yeah. Seems so https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/
