### ISSUE TITLE
The title and overview of AG BE on Taiwan/China chrome web store became English last week.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardBrowserExtension#1394]
@aalpatkina 
@maximtop 

1. The title and overview of AG BE on Taiwan/China chrome web store became English last week.

Traditional Chinese (zh-TW, Taiwan):
https://tinyurl.com/y8pbv48a

Simplified Chinese (zh-CN, China):
https://tinyurl.com/y6ttolaz

It's normally localized in other languages interface.
Japanese:
https://tinyurl.com/y9hmhf3x

Korean:
https://tinyurl.com/y656k3gh

Russian:
https://tinyurl.com/y62fdupe

Why?
Or is it Google's error?
May you tell Google to solve?
Thanks.

2. Well, please update translations for chrome web store.

B/R

**Comment by maximtop** [comment]
I've submitted the issue to the chrome store developer support.
I'll notify if there will be news from them.

**Comment by maximtop** [comment]
Chrome has fixed this issue.
