### ISSUE TITLE
Adguard Extension old Microsoft Edge problem with hiding cookies/RODO.

### ISSUE THREAD

**Issue by seba2282** [AdguardTeam/AdguardBrowserExtension#1395]
Browser : Microsoft Edge on old EdgeHTML
Extension : Adguard Adblocker
Windows : Windows 10 1903 

Hello, I have not typical problem. Adguard doesn't work for hiding/accept cookies/RODO. I don't know, how is in other browser but on old Edge doesn't work. 
Example site : www.dobreprogramy.pl or www.forum.dobreprogramy.pl
Screenshoot, how look this : 
![bugonlyadguard](https://user-images.githubusercontent.com/16944478/57284671-f39a2a80-70b1-11e9-9eab-e707d2d3121f.png)

I tested first only with polish filters and doesn't work, after with my settings turned filters and doesn't work too. In normal Polish Annoyances should block that but on Edge I see is bug in Adguard extension.

**Comment by seba2282** [comment]
Update filters fixed problem.

P.S. @AdamWr, please can you give new rule aka script, which remove anty-adblock on player.pl for Adguard extension for Edge/Firefox, because old rule doesn't work now.

**Comment by ameshkov** [comment]
Awesome, thank you for checking:)

I'll let Adam know about your player.pl question

**Comment by seba2282** [comment]
Thank you :)
