### ISSUE TITLE
Remove tracking parameters isn't working

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardBrowserExtension#1397]
Remove tracking parameters isn't working via this [link](https://myaccount.google.com/activitycontrols?utm_campaign&continue=https%3A%2F%2Fmyactivity.google.com%2Fmyactivity%3Futm_campaign%3Dcontinue)

**Comment by maximtop** [comment]
The URL you have provided doesn't contain any data related to the UTM parameter that's why they are not removed.
Here is an example with correct UTM parameters
`https://myaccount.google.com/activitycontrols?utm_source=google-account&utm_medium=web`
