### ISSUE TITLE
Rules with a slash (/) in the beginning do not work.

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardBrowserExtension#1399]
Пример:

 Для блокировки баннера на обфусцированной главной странице [Яндекса](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://yandex.ru/) я использую следующие правила:
`yandex.*##.main [class=""] > :matches-css(margin-bottom: 0px)`
`yandex.*#$#.main [class=""] :matches-css(background-repeat: no-repeat) { background-image: none!important; }`

<details><summary>Screenshot:</summary>

![2019 05 15-3](https://user-images.githubusercontent.com/17948007/57784118-09ee5900-7738-11e9-87d1-4bc132028f0c.png)
</details><br/>

 Но я не хочу чтобы они затрагивали поддомены, поэтому добавляю слэш (`/`) в начало:
`/yandex.*##.main [class=""] > :matches-css(margin-bottom: 0px)`
`/yandex.*#$#.main [class=""] :matches-css(background-repeat: no-repeat) { background-image: none!important; }`

 И такие правила перестают работать...

<details><summary>Screenshot:</summary>

![2019 05 15-2](https://user-images.githubusercontent.com/17948007/57784248-4621b980-7738-11e9-9c27-afafeaf729e5.png)
</details><br/>

 Это касается и других доменов и более простых правил.

 P.S.: Раньше, помню, такие правила работали (не именно такие, а со слэшем в начале). Точно не помню, но работали они толи в последних версиях 2.х линейки, толи в первых версиях 3.х линейки...

___________________________________________________
Mozilla Firefox v53.0.3 (Win7SP1) - Adguard v3.0.13
Базовый фильтр AdGuard | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и систем аналитики

**Comment by ameshkov** [comment]
Если они работали, то это была ошибка (скорее всего они наоборот на всех доменах применялись).

**Comment by ameshkov** [comment]
Ну то есть функционала который вы описываете вообще не было никогда

**Comment by XX-J** [comment]
Эти правила 100% работали, и не один раз:
```
/yandex.ru##.container__banner
/yandex.ru#$#.main div:nth-child(4) > div { background-image: none!important; }
/yandex.ru#$#.main div:nth-child(5) > div { background-image: none!important; }
/yandex.ru#$#.main div:nth-child(6) > div { background-image: none!important; }
/yandex.ru##.main div:nth-child(7)
/yandex.ru##.main div:nth-child(8)
/yandex.ru##.main div:nth-child(9)
```

 Они делают тоже самое, что и правила из первого сообщения, только не со 100% точностью :) 
 И, если бы они не работали, я бы их не применял.

 А слэш в начале я подсмотрел в правилах Alex'a.

 Да и как правило привязать к коренному домену, не затрагивая поддомены?

**Comment by Alex-302** [comment]
> А слэш в начале я подсмотрел в правилах Alex'a.

не мог я такого написать) Может опечатка была?

**Comment by XX-J** [comment]
@Alex-302 
 Факт(1) в том, что я это не сам придумал, а учусь я составлять правила на Ваших примерах. Может, конечно, и не у Вас подсмотрел, но вероятность этого крайне мала.

 Факт(2) - это работало.

 Ну и основной вопрос (раз функционала со слэшем больше не будет):

> Да и как правило привязать к коренному домену, не затрагивая поддомены?

P.S.: А может ввести такой функционал (с использованием слэша)?

**Comment by ameshkov** [comment]
Эти правила работали потому что ошибка в коде была -- кривой домен игнорировался и получалось, что они на всех доменах применялись.

> P.S.: А может ввести такой функционал (с использованием слэша)?

Да в идеале вообще что-то такое:
`||example.org/path$cosmetic=##banner`

**Comment by XX-J** [comment]
> Эти правила работали потому что ошибка в коде была -- кривой домен игнорировался и получалось, что они на всех доменах применялись.

 Теперь понятна непонятка.

> Да в идеале вообще что-то такое:
> `||example.org/path$cosmetic=##banner`

 Это было бы супер, что-то похожее ввести. Т.к. этого функционала мне тоже не доставало.

 Но основной вопрос касался слэша именно в начале доменного имени, дабы отделить сиё правило от поддоменов проклятущих... :)

**Comment by XX-J** [comment]
Нашёл примеры со слешем в начале. Случайно один попался на глаза:
`@@//yandex.*/yandsearch?clid=$generichide` в Русском фильтре.

<details><summary>Screenshot:</summary>

![2019 08 24-1](https://user-images.githubusercontent.com/17948007/66433044-185f4900-ea28-11e9-9d23-f945705f9d4f.png)
</details>

 Решил посмотреть, где конкретно:
https://github.com/AdguardTeam/AdguardFilters/blob/master/RussianFilter/sections/antiadblock.txt
 А там он оказывается не один: ищется по маске `/yandex` .
