### ISSUE TITLE
Assistant and element hiding works partially because of the CSP

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#140]
Example:
http://gidonline.club/

Seems to be caused by their CSP:
```
Content-Security-Policy:default-src 'self' gidonline.club; script-src 'self' 'unsafe-inline' 'unsafe-eval' gidonline.club *.marketgid.com cdn.hgdat.com hghit.com https://apis.google.com counter.yadro.ru; frame-src 'self' gidonline.club cdn.hgdat.com counter.yadro.ru moonwalk.cc serpens.nl 37.220.36.15 *.ivi.ru vk.com https://vk.com *.youtube.com https://www.youtube.com https://apis.google.com https://accounts.google.com; connect-src 'self' gidonline.club *.ivi.ru; style-src 'self' 'unsafe-inline' gidonline.club counter.yadro.ru; font-src 'self' gidonline.club counter.yadro.ru; img-src 'self' gidonline.club *.marketgid.com https://ft.imgsniper.com counter.tovarro.com front.facetz.net cdn.hgdat.com hghit.com hhit.xyz counter.yadro.ru *.gstatic.com; object-src 'self' gidonline.club cdn.hgdat.com counter.yadro.ru *.ivi.ru https://*.ivi.ru;
```

Read more about is here:
https://developer.mozilla.org/en-US/docs/Web/Security/CSP/CSP_policy_directives
https://developer.mozilla.org/en-US/docs/Web/Security/CSP/Using_Content_Security_Policy

**Comment by Mizzick** [comment]
`Refused to load the font 'data:application/font-woff;base64,d09GRgABAAAAAII8ABMAAAABAyQAAQAAAAAAAAAAA…D2jIyQYWUZI6OTZYKM15YpMqktM2S6ssyR2dKyQOYLyzGyUH9qKNUHk8lN/QAAAVKzC2QAAA==' because it violates the following Content Security Policy directive: "font-src 'self' gidonline.club counter.yadro.ru".`

**Comment by ameshkov** [comment]
Hm, frankly i am not sure if we should do anything here.
