### ISSUE TITLE
 Android BrowserExtension is broken

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardBrowserExtension#1401]
### Steps to reproduce

1. Open FireFox Extension
2. Try to download AdGuard

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/49645813/58097044-20386100-7bdf-11e9-95e3-373980092676.png)

</details>

### Your environment

* Environment name and version: Firefox 66.0.2

**Comment by ameshkov** [comment]
Firefox is broken, not the extension.
