### ISSUE TITLE
Add Lithuanian language in AdguardBrowserExtension

### ISSUE THREAD

**Issue by Tolimas** [AdguardTeam/AdguardBrowserExtension#1403]
Adguard Browser Extension does not support user interface in Lithuanian language. The translation exists on OneSky (http://adguard.oneskyapp.com/collaboration/translate/project/project/13698/language/44#/). Please, add.

**Comment by ameshkov** [comment]
@maximtop can we somehow add it before v3.1 release?

**Comment by maximtop** [comment]
Yes, we can. 
Unfortunately, there are no translations to Lithuanian language for thank you page and uninstall page.
@Tolimas It would be kind of you if you add these translations too. 
Here is the link to the project http://adguard.oneskyapp.com/admin/project/dashboard/project/123764
