### ISSUE TITLE
After disabling "Allow search ads and the self-promotion of websites" in the welcome page, it's still enabled in the general settings of AG BE for Firefox.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardBrowserExtension#1406]
After disabling "Allow search ads and the self-promotion of websites" in the welcome page, the option of "Allow search ads and the self-promotion of websites" is still enabled in the general settings of AG Browser Extension for Firefox v3.1.3.

**Comment by zzebrum** [comment]
can't reproduce, reopen if needed.
