### ISSUE TITLE
115.бел is broken

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1407]
@adguard-bot commented on [Tue Jun 04 2019](https://github.com/AdguardTeam/AdguardFilters/issues/34747)

### Issue URL (Incorrect Blocking)
[http://115.бел/map](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2F115.%D0%B1%D0%B5%D0%BB%2Fmap)
### Comment
Username: @tank666
> На скриншотах №1 и №2 видно, что AdGuard блокирует отображение карты openstreetmap.org на ресурсе http://115.бел/map.
> 
> В консоли Google Chrome отображаются эти и подобные им строки:
> Access to image at 'http://a.tile.openstreetmap.org/13/4802/2690.png' from origin 'http://115.xn--90ais' has been blocked by CORS policy: The response is invalid (map:1)
> Failed to load resource: net::ERR_FAILED (2690.png:1)
> 
> Если приостановить защиту AdGuard, то карта по прежнему не отображается (Скриншот 2). А как только выключить расширение на странице расширений Chrome (chrome://extensions/?id=bgnkhhnnamicmpeenaelnjfhikgbkllg), тогда тайлы карты начинают отображаться (Скриншот 3).

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/IIsLCiq.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/THAk3bs.png)
</details>
<details>
  <summary>Screenshot 3</summary>

  ![Screenshot 3](https://reports-img.adguard.com/CitUrNP.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | Ext
AdGuard version: | 3.1.3
Browser: | Chrome
Filters: | AdGuard Russian,<br>AdGuard Base,<br>Filter unblocking search ads and self-promotion

**Comment by Alex-302** [comment]
@tank666 спасибо. Это баг расширения. 
Ход решения будет здесь
https://github.com/AdguardTeam/AdguardFilters/issues/34747

**Comment by maximtop** [comment]
@alex302 seems like this is a chrome bug, which occurs if add in this listeners

```
onHeadersReceived
onBeforeSendHeaders
```

option `extraHeaders`

I'll google if such issue is already described in the crome bug tracker, if no, I'll create a new one.

**Comment by maximtop** [comment]
Link to the issue
https://bugs.chromium.org/p/chromium/issues/detail?id=971206

**Comment by AdamWr** [comment]
I guess the same happens here - http://poedb.tw/us/ (https://github.com/AdguardTeam/AdguardFilters/issues/33148) or is it a different issue?

**Comment by maximtop** [comment]
@AdamWr Yes, seems that it is the same issue. I think it happens when http request is redirected to https

**Comment by AdamWr** [comment]
Ok, thank you for your answer.
