### ISSUE TITLE
No header formatting was used in the description of the extension

### ISSUE THREAD

**Issue by Rakleed** [AdguardTeam/AdguardBrowserExtension#1409]
В описании расширения в [Chrome Web Store](https://chrome.google.com/webstore/detail/adguard-adblocker/bgnkhhnnamicmpeenaelnjfhikgbkllg), [Microsoft Store](https://www.microsoft.com/ru-ru/p/adguard-adblocker/9mz607gwkbs7), [Opera Add-ons](https://addons.opera.com/en/extensions/details/adguard/) не применилось форматирование для заголовков.
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/19418601/58924069-fc325f00-874a-11e9-9053-fe7a5750a2fb.png)

</details>

**Comment by zzebrum** [comment]
там не маркдаун вроде, просто такое оформление текста.

**Comment by Rakleed** [comment]
@zzebrum в Chrome Web Store вообще отсутствует форматирование описания? И зачем тогда вообще оставлять `##`, они же рассчитаны для Markdown, а просто так они не карсиво выглядят.

**Comment by ameshkov** [comment]
Да, в CWS нет форматирования, а заголовки хочется как-то выделять.
