### ISSUE TITLE
Can't downlaod deviantart files

### ISSUE THREAD

**Issue by thegamerx05** [AdguardTeam/AdguardBrowserExtension#1415]
### Steps to reproduce
try to download file

### Expected behavior
Download file

### Actual behavior
Not downloading file unless right clicking and opening in new tab
It also doesn't allow to enter user profiles clicking user profile or user name unless right clicking and opening in new tab

<details><summary>Screenshot of the browser console:</summary>
https://imgur.com/a/spUhLLH
</details>

### Your environment
* AdGuard AdBlocker extension version: Version 3.1.3
* Environment name and version: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
* Filters you use in AdGuard: All Filters
* Any other browser extensions you have installed: Not important links work after disabling adguard

**Comment by ameshkov** [comment]
Fixed by https://github.com/AdguardTeam/AdguardFilters/commit/a8e2f57bc09f7692e068b74940de9eaa9964c88f
