### ISSUE TITLE
Ошибка фильтрации или конвертирования (?)

### ISSUE THREAD

**Issue by a-ladanov** [AdguardTeam/AdguardBrowserExtension#1416]
### Steps to reproduce

1. Установить связку фильтров Easylist + RUAdList для uBlock Origin (его можно установить по ссылке 
`https://easylist-downloads.adblockplus.org/advblock+cssfixes.txt `)
2. Зайти на https://www.sports.ru/

### Expected behavior
Страница отфильтрована, без пустых участков.

### Actual behavior
Существует большой отступ от шапки сайта.

<details><summary>Screenshot:</summary>
![123](https://user-images.githubusercontent.com/18179397/59151240-1c169b00-8a49-11e9-9fb9-ed5a5d05f8d4.png)

</details>

### Your environment

* AdGuard AdBlocker extension version: 3.1.3
* Environment name and version: Chrome 75.0.3770.80
* Filters you use in AdGuard: Easylist + RUAdList для uBlock Origin
* Any other browser extensions you have installed: Нет

Судя по последним релизам расширения, появилась поддержка правил вида `#?#`, которых много в Ruadlist и особенно много в версии для uBlock Origin.
Однако на примере выше, не все правила конвертируются или возникают какие-то конфликты правил. В Ruadlist отступ убирает правило  `sports.ru,tribuna.com#?##branding-layout:not(#id):style(margin-top: 96px !important)`
Если добавить это правило в пользовательский фильтр, оно конвертируется и работает. Однако, в сочетании Easylist+Ruadlist для uBlock Origin, куда оно входит - правило не работает и вообще не появляется в журнале фильтрации.

**Comment by ameshkov** [comment]
Интересная проблема.

В общем, в руадлисте есть два правила, которые применяются как `#?##` к одному и тому же элементу. А у нас в ExtCSS есть похоже проблема -- к одному элементу может быть применено только одно правило. Я пожалуй перетащу в нужный репозиторий этот баг.

А исправляется он кстати элементарно, нужно `#?#` заменить на обычное правило `##` (я вообще не понимаю такую особую любовь к `#?#` - они медленнее)

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/ExtendedCss #85](https://github.com/AdguardTeam/ExtendedCss/issues/85) via [**ZenHub**](https://www.zenhub.com/)
