### ISSUE TITLE
Increase the minimum browser versions in the manifest

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#1419]
We should check which versions support async/await and set it as a minimum version in every manifest file: Opera, Chrome, Edge, Firefox

**Comment by maximtop** [comment]
According to the https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function
and https://caniuse.com/#feat=async-functions
async functions were introduced in browsers starting from the next versions
```
Chrome: 55
Firefox: 52
Opera: 42
Edge: 15
```
