### ISSUE TITLE
Electromaps not loading

### ISSUE THREAD

**Issue by thegamerx05** [AdguardTeam/AdguardBrowserExtension#1420]
### Steps to reproduce
1.Enter website
### Expected behavior
map to show up

### Actual behavior
map not showing up

<details><summary>Screenshot:</summary>
https://imgur.com/a/k7N3Kfx

</details>

<details><summary>Screenshot of the browser console:</summary>
https://imgur.com/a/b5bZYit

</details>

### Your environment

* AdGuard AdBlocker extension version: Version 3.1.3
* Environment name and version: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
* Filters you use in AdGuard: ALL
* Any other browser extensions you have installed: Not important map works after disabling adguard

**Comment by ameshkov** [comment]
Hi, I'll ask @Alex-302 to take a look, but next time please file the report here: https://agrd.io/report

**Comment by Alex-302** [comment]
It does not work on my end with disabled extension
![image](https://user-images.githubusercontent.com/8361299/59227061-15b92800-8bdd-11e9-829c-42fbf9ee855e.png)

**Comment by Alex-302** [comment]
But in VM it works with AdGuard:
![image](https://user-images.githubusercontent.com/8361299/59227222-7b0d1900-8bdd-11e9-9922-b1467171c476.png)

**Comment by BlazDT** [comment]
Reproduced with FF extension, fixed for Stealth Module [Referrer].
