### ISSUE TITLE
белый список для 3p Referrer

### ISSUE THREAD

**Issue by bogachenko** [AdguardTeam/AdguardBrowserExtension#1421]
Антитрекер от вас это круто, хорошая штука, с 1 но. Некоторые сайты блокируются. Есть 1 польский сайт `https://www.tvokazje.pl/325-ogladaj-na-zywo` там антиаблок его можно пофиксить 
```
@@||gemius.pl^$important,domain=tvokazje.pl
@@||imasdk.googleapis.com^$important,domain=tvokazje.pl
```
, однако я не хочу разрешать сервисы гугло ~говна~ не на сервисах гугла ~говна~.
Собственно, я по поэтому поводу запилил вот такие фильтры
```
@@||gemius.pl^$important,domain=tvokazje.pl
||imasdk.googleapis.com^$important,empty,domain=tvokazje.pl
```
и по идеи они должны были работать, но нет. **Антиадблока больше не было**, но я получаю ошибку -- **У вас проблемы с интернетом.**
 https://user-images.githubusercontent.com/8535285/59264582-23c78100-8c8f-11e9-90c3-6bf7fc2de383.png
Проблема была в 3p Referrerе, сайт тригирится на функцию Скрыть `Referrer от сторонних ресурсов`, собственно вопрос такой, как на счет запилить белый списк для Referrer и (sic! Cookie, трекер-куки нельзя никак добавить в белый список, даже с флагом `$important`)
![Безымянный](https://user-images.githubusercontent.com/8535285/59266511-7efb7280-8c93-11e9-8226-6031467e2083.png)
![1](https://user-images.githubusercontent.com/8535285/59266514-80c53600-8c93-11e9-94cc-bb73159bab02.png)

**Comment by ameshkov** [comment]
@bogachenko вообще есть модификатор `$stealth` который отключает только антитрекинг

**Comment by bogachenko** [comment]
да, но это не то

**Comment by bogachenko** [comment]
белый список именно, не?

**Comment by ameshkov** [comment]
А почему не то? Как раз же отключит модификацию кук и реферера для урлов которые правило матчит.

**Comment by bogachenko** [comment]
а раздельно нельзя?

**Comment by ameshkov** [comment]
Пока что не, но вообще мысль расширить его есть.
Что-то типа: `@@||example.org^$stealth=referrer|1p-cookies|3p-cookies`

**Comment by bogachenko** [comment]
например для этого сайта мне не нужно только рефф, а на куки все равно, пусть будут

**Comment by bogachenko** [comment]
блин, ну ладно

**Comment by ameshkov** [comment]
> например для этого сайта мне не нужно только рефф, а на куки все равно, пусть будут

Да не, нормальная идея, просто еще не запилено:)
