### ISSUE TITLE
 Integration issues on chrome web store

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardBrowserExtension#1422]
### Steps to reproduce

1. Go to https://chrome.google.com/webstore/category/extensions?h1=en
2. Sometimes the helper icon in the integration mode is selected correctly. 
3. But more often it is displayed in green (integration does not work)

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/49645813/59451406-138cde80-8e14-11e9-9494-1319fc383b41.png)

</details>

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/49645813/59451549-5c449780-8e14-11e9-9827-863f9f2ba88a.png)

</details>

### Your environment

* AdGuard AdBlocker extension version: 3.1.3
* Environment name and version: Chrome 74.0.3729.169

**Comment by ameshkov** [comment]
Will be resolved after we change how the integration mode works
