### ISSUE TITLE
Wrong blocking rules created for generic element hiding or JS exclusions

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1424]
### Steps to reproduce
1. Add document level exclusion - `@@||example.org^$generichide` or `@@||example.org^$elemhide`
2. Try to create blocking rule for it using filtering log

### Actual behavior
`||example.org^$domain=example.org,important`

### Expected behavior
`@@||example.org^$generichide,badfilter`

The same issue with `$jsinject`.

**Comment by maximtop** [comment]
For document-level rules, we should add badfilter modifier
