### ISSUE TITLE
CSS exclusions are not working

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1425]
### Steps to reproduce

1. Open https://reevown.com/mega
2. Add these rules:
`reevown.com#$#body > div { height: 21px!important; }`
`reevown.com#@$#body > div { height: 21px!important; }`

### Actual behavior

Style is applied to `body > div`
![image](https://user-images.githubusercontent.com/8361299/59614977-70490b80-912a-11e9-9a69-5d8c792a82d7.png)

### Expected behavior

The rule is not applied to the site.

AdGuard 3.1.3, Chrome

**Comment by AdamWr** [comment]
I guess that it's the same issue as here - https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1412 :)

**Comment by Alex-302** [comment]
Sure)
