### ISSUE TITLE
Edge, upload format changes if AdGuard is on

### ISSUE THREAD

**Issue by dhoko** [AdguardTeam/AdguardBrowserExtension#1427]
Hey, 

I have an issue only on Edge with AdGuard. 
On protonmail when we create a draft, if we try to upload an attachment with AdGuard, it fails.
(_btw same issue with IE11_).

Which is weird is, if I add protonmail inside the exclusion list, now it works.
The code on protonmail doesn't change, the only diff is AdGuard.

I looked into the network, and find something unexpected: the payload is not the same if AdGuard is turned on.

### Steps to reproduce
1. Open https://mail.protonmail.com
2. Create a draft (_Button Composer_)
3. Add an attachment ex: a zip
4. You get an error Invalid Input

### Expected behavior
It should upload the attachment.

### Actual behavior
AdGuard: on -> it doesn't work
AdGuard: off -> it works
AdGuard: on + protonmail inside exclusion list -> it works

<details><summary>Screenshot:</summary>

**With AdGuard**

```

-----------------------------7e3bf16801d4
Content-Disposition: form-data; name="Filename"

Imgur Album  Watt.zip
-----------------------------7e3bf16801d4
Content-Disposition: form-data; name="MessageID"

<ID>
-----------------------------7e3bf16801d4
Content-Disposition: form-data; name="ContentID"


-----------------------------7e3bf16801d4
Content-Disposition: form-data; name="MIMEType"

application/x-zip-compressed
-----------------------------7e3bf16801d4
Content-Disposition: form-data; name="KeyPackets"

[object Blob]
-----------------------------7e3bf16801d4
Content-Disposition: form-data; name="DataPacket"

[object Blob]
-----------------------------7e3bf16801d4
Content-Disposition: form-data; name="Signature"

[object Blob]
-----------------------------7e3bf16801d4--
```

**Without AdGuard**

```
-----------------------------7e31a62e907ceqatest123
Content-Disposition: form-data; name="Filename"

Imgur Album  Watt.zip
-----------------------------7e31a62e907ce
Content-Disposition: form-data; name="MessageID"

<ID>
-----------------------------7e31a62e907ce
Content-Disposition: form-data; name="ContentID"


-----------------------------7e31a62e907ce
Content-Disposition: form-data; name="MIMEType"

application/x-zip-compressed
-----------------------------7e31a62e907ce
Content-Disposition: form-data; name="KeyPackets"; filename="blob"
Content-Type: application/octet-stream

Á^0Ù"órÑº­QÜmï_03&ygæÃvJ åCßv7¾ôÀCàYí|ü
-----------------------------7e31a62e907ce
Content-Disposition: form-data; name="DataPacket"; filename="blob"
Content-Type: application/octet-stream

Òÿ
``` 

As you can see AdGuard changes the `Content-Type`.

</details>

### Your environment
* AdGuard AdBlocker extension version: v7.0.2693.6661 RELEASE CL 1.3.351
* Environment name and version: Edge (latest) IE11
* Filters you use in AdGuard: Default, post install
* Any other browser extensions you have installed: None

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/CoreLibs #973](https://github.com/AdguardTeam/CoreLibs/issues/973) via [**ZenHub**](https://www.zenhub.com/)
