### ISSUE TITLE
Can we create a setting switching Safari extension from Content Blocker to old API and back?

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#143]
At least we could create a separate build based on old API.

**Comment by Eitot** [comment]
The old blocking mechanism is deprecated in Safari 9 and will probably be dropped in the near future.

**Comment by ameshkov** [comment]
> The old blocking mechanism is deprecated in Safari 9 and will probably be dropped in the near future.

That's what they say. But no one has answered when exactly it will be dropped.
Yet the old API still provides some very useful features we don't have with content blocking api.

**Comment by Mizzick** [comment]
Actually I think it's possible, but it's possible to simply use the old versions of our extension to achieve this.
Our old blocking mechanism still works with new safaries, but no one knows for how long.

**Comment by ameshkov** [comment]
@Mizzick let's add a switch to AG settings then?

Settings section: Miscellaneous

How it looks like:
**Use an old Safari API** _Learn more_

_Learn more_ leads to https://github.com/AdguardTeam/AdguardBrowserExtension/wiki/Safari:-difference-between-new-and-old-API

Disabled by default.

**Comment by ameshkov** [comment]
Change of plans. This setting is for power users, so let's simply place it to extension settings:
https://developer.apple.com/library/safari/documentation/Tools/Conceptual/SafariExtensionGuide/ExtensionSettings/ExtensionSettings.html

**Comment by ameshkov** [comment]
Done. Now we have a setting that allows to enable old API.

<img width="552" alt="2016-01-27_1820" src="https://cloud.githubusercontent.com/assets/5947035/12617922/bef17d9e-c522-11e5-9d9e-5fd103c6d53d.png">
