### ISSUE TITLE
slader.com - filtering log does not work as it should in Edge browser

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1430]
### Steps to reproduce

1. Go to https://www.slader.com/textbook/9780618394807-larson-precalculus-with-limits-a-graphing-approach-4th-edition/
2. Open filtering log
2. Refresh the tab

### Actual behavior
Filtering log is empty.

If you will add a scriptlet rule, it will be visible, but if you refresh a tab using browser's buttons or hot key, new string will be added, instead of clearing the log and adding only new string.

### Expected behavior
Filtering log is not empty:)

### Your environment

* AdGuard AdBlocker extension version: 3.1.3
* Environment name and version: MS Edge 44.18362.1.0
* Filters you use in AdGuard: Base, Rus, Social, tracking protection, Annoyances.

**Comment by Alex-302** [comment]
Strange. It works after few restarts.

**Comment by Alex-302** [comment]
Again:
![image](https://user-images.githubusercontent.com/8361299/59764605-cfcb2680-92a4-11e9-9bc0-f1ddd4b45d89.png)

**Comment by zzebrum** [comment]
can't confirm on my device

**Comment by zzebrum** [comment]
@Alex-302 is it still reproducible?

**Comment by slavaleleka** [comment]
it's non-reproducible at my end now

**Comment by zzebrum** [comment]
reopen if needed
