### ISSUE TITLE
JavaScript error in "AdGuard Extra.user.js": Uncaught TypeError: Object.values is not a function

### ISSUE THREAD

**Issue by victor-homyakov** [AdguardTeam/AdguardBrowserExtension#1431]
### Steps to reproduce
1. Install older version of Chrome (53 and older) or Opera (40 and older)
2. Install AdGuard with AdGuard Extra script
3. Open yandex.ru

### Expected behavior
No errors should happen

### Actual behavior
Older browsers (Opera 40 and older, Chrome 53 and older) will throw JavaScript error

```
TypeError: Object.values is not a function
    at findAds (AdGuard%20Extra.user.js:71:7335)
    at hideYaDirectAds (AdGuard%20Extra.user.js:71:7938)
    at MutationObserver.eval (AdGuard%20Extra.user.js:71:8766)
```

because JavaScript in `AdGuard Extra.user.js` uses `Object.values()`, which isn't supported in older browser versions https://caniuse.com/#search=Object.values.

### Your environment
* AdGuard AdBlocker extension version: 
* Environment name and version: Chrome/53.0.2785.21
* Filters you use in AdGuard:
* Any other browser extensions you have installed: none

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardExtra #4](https://github.com/AdguardTeam/AdGuardExtra/issues/4) via [**ZenHub**](https://www.zenhub.com/)
