### ISSUE TITLE
Adguard Assistant Icon not appear on youtube.com

### ISSUE THREAD

**Issue by vampireinfinite** [AdguardTeam/AdguardBrowserExtension#1432]
Ok, here you go do one thing if you facing such an issue with Adguard. Do not uninstall the application neither you need to Clear the cache or Cookies of your browser.

Just type in the search box of chrome. chrome://flags/.
New windows open just find the caption Experimental QUIC Protocol. It should be default you need to Disabled it.
Then relaunch your browser and open the www.youtube.com you saw your issue is being resolved. I personally do this just now and I saw the assistant icon of Adguard on YouTube official website.
Rather you using other methods, it's better you can go ahead with it.

**Comment by ameshkov** [comment]
@vampireinfinite what exact version of AdGuard do you use?

**Comment by ameshkov** [comment]
@vampireinfinite what exact version of AdGuard do you use?

**Comment by vampireinfinite** [comment]
I am using Adguard with 6.3.1399.4073 Stable version with a Premium license but the method will be the same for each and every one.
It's a free version you can also get online from various websites.

**Comment by ameshkov** [comment]
This is quite an old version, have you tried using v7.0?

**Comment by vampireinfinite** [comment]
> This is quite an old version, have you tried using v7.0?

Who cares about the version the matter is just to block the adds rather than version just download it use it or if you need to update it go to updates and update it freely. It will automatically be updated and do not ask you to enter the key again and again.

**Comment by ameshkov** [comment]
I cannot reproduce your issue with AdGuard 7.0

**Comment by vampireinfinite** [comment]
> I cannot reproduce your issue with AdGuard 7.0

I have no obligations with it. That's all up to you.

Thanks.
