### ISSUE TITLE
Change the browser action UI on internal browser pages

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#1433]
Currently, this is how it looks like on the internal pages:
https://uploads.adguard.com/up04_bl8l3_Monosnap.png

We should change it and explain what's going on: 
https://uploads.adguard.com/up04_7t92c_Monosnap.png

Also, change the way the popup looks on pages where protection is disabled by some filter list's $document rule. "Unavailable" status line should be removed.

**Comment by maximtop** [comment]
Final view
![Artboard Copy 17@1x](https://user-images.githubusercontent.com/17272769/60344499-5aa3d380-99bf-11e9-8946-daf17e3a66fa.png)
