### ISSUE TITLE
The translations for AG Assistant are outmoded.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardBrowserExtension#1434]
In AG for Windows/Mac, the translations for AG Assistant are newer.
But the translations for AG Assistant are very outmoded in AG Browser Extension, AG for Safari and AG for iOS v3.
I suggest to again update AG Assistant's translations for supported languages and then use the latest translations in apps.

**Comment by lancelot-moon** [comment]
@maximtop
The translations for AG Assistant in AG BE v3.2.1 are still very outmoded.
May you update it?
Thanks.

**Comment by maximtop** [comment]
@lancelot-moon I'll do it in the next release
