### ISSUE TITLE
Windows Error Reporting (Event Log)

### ISSUE THREAD

**Issue by deadlyshadow79** [AdguardTeam/AdguardBrowserExtension#1436]
**There are too many logs in Event Log about Adguard Edge Extention**
**It's the Log Details**

Fault bucket , type 0
Event Name: WWAJSE
Response: Not available
Cab Id: 0

Problem signature:
P1: Adguard.AdguardAdBlocker_3.1.3.0_neutral__m055xr0c82818
P2: App
P3: 4e6f
P4: 5
P5: ms-browser-extension://EdgeExtension_AdguardAdguardAdBlocker_m055xr0c82818/lib/utils/element-collapser.js
P6: 67_9
P7: 
P8: 
P9: 
P10: 

Attached files:
ErrorInfo.2540.8548.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: d9a302e7-dd57-4d94-8816-19f8dda94a65
Report Status: 268697600
Hashed bucket: 
Cab Guid: 0

**Comment by maximtop** [comment]
Directions for testers

To check if the issue is resolved:
1. Install the extension in Edge
2. Go to mail.ru 
3. check that there are no errors in the console related to `/element-collapser.js`

**Comment by deadlyshadow79** [comment]
> Directions for testers
> To check if the issue is resolved:
> 
> Install the extension in Edge
> Go to mail.ru
> check that there are no errors in the console related to /element-collapser.js
It seems the last Version has fixed this issue, there is no Log for this issue in Windows Event Log
