### ISSUE TITLE
Error adding anti pop ads list to custom filters

### ISSUE THREAD

**Issue by superlex** [AdguardTeam/AdguardBrowserExtension#1437]
See
https://github.com/Yhonay/antipopads/issues/29

It looks like an English (Base) filter (specifically, EasyList part) issue, it's possible to add it by disabling English filter.

### Your environment

* AdGuard AdBlocker extension version:  3.2.1
* Environment name and version: Firefox

**Comment by maximtop** [comment]
@superlex could you please send a link to the filter you want to add?

**Comment by superlex** [comment]
@maximtop 
Sure, the list is
https://raw.githubusercontent.com/Yhonay/antipopads/master/popads.txt
Homepage:
https://github.com/Yhonay/antipopads
Try with and without English filter enabled.
Thanks!

**Comment by maximtop** [comment]
There is a rule in the AdGuard base filter which blocks provided link on the background page

![image](https://user-images.githubusercontent.com/17272769/60707717-08aa0300-9f15-11e9-848e-a8a358f8740d.png)

Temporarily you can add the unblocking rule for this request

```
@@||raw.githubusercontent.com/Yhonay/antipopads/master/popads.txt
```

I think extension shouldn't filter request generated while a user adds a custom filter.

**Comment by superlex** [comment]
Ok, thank you!
