### ISSUE TITLE
"Processing requests..." issue when Custom filter enabled

### ISSUE THREAD

**Issue by SaberAkiyama** [AdguardTeam/AdguardBrowserExtension#1439]
I was open Gmail, and it frozen while loading. I've saw on the bottom left corner, and word "Processing requests..."

I just disabled Custom filter, and loading is normal with no problem.

### Your environment

* AdGuard AdBlocker extension version: v3.2.1
* Environment name and version: Chrome v75.0.3770.100 (Official Build)
* Filters you use in AdGuard: Custom filter only
* Any other browser extensions you have installed: None

**Comment by maximtop** [comment]
Seems like your custom filter is not working correctly.
Could you share please the link to your custom filters?

**Comment by SaberAkiyama** [comment]
[Nano Defender Integration](https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoMirror/NanoDefender.txt)

[Steven Black's Unified Hosts](https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-social/hosts)

**Comment by maximtop** [comment]
@Alex-302 could you take a look, please?

**Comment by maximtop** [comment]
@SaberAkiyama we do not support hosts files

https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-social/hosts

**Comment by SaberAkiyama** [comment]
I just removed Steven Black host, thanks.
