### ISSUE TITLE
Add ability to batch import filters by list using text field

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1441]
Reports contains the list of filters. For example 
https://github.com/AdguardTeam/AdguardFilters/issues/36616
<details>

```
AdGuard Russian,
EasyList,
EasyList Czech and Slovak,
EasyList Italy,
AdGuard Mobile Ads,
Fanboy's Annoyances,
Fanboy's Social Blocking List,
AdGuard Annoyances,
AdGuard Base,
Peter Lowe's list,
Adblock Warning Removal List,
Malware Domains,
Official Polish filters for AdBlock, uBlock Origin & AdGuard,
I don't care about cookies,
Adblock List for Finland,
AdGuard Tracking Protection,
AdGuard Social Media
```

</details>

It is not fast process, when you change filters list for each report. It would be great to import the filters lists(disable current filters and enable imported)

Something like that 
<details>

![image](https://user-images.githubusercontent.com/8361299/61052323-d35d5380-a3f3-11e9-89ff-53e8781b6460.png)

</details>

or add advanced option to show new tab.

**Comment by XX-J** [comment]
Можно сделать опцию "Расширенный режим" на странице Фильтров > переключаешь, и можно списками херачить...

**Comment by Alex-302** [comment]
Please implement it in earlier versions, useful option for filter maintainers(the most of [reports](https://github.com/AdguardTeam/AdguardFilters/issues) have different filters lists)

**Comment by ameshkov** [comment]
This task should be reworked.

Some of AdGuard have the ability to import settings using a special `adguard://` links.
We should do the same for the browser extension and extend the reporting tool so that it created an import settings link.
