### ISSUE TITLE
Please change time format for simplified Chinese (zh-CN)

### ISSUE THREAD

**Issue by byyxx128** [AdguardTeam/AdguardBrowserExtension#1442]
This issue exists in all platforms (all browser extensions, mobile apps and desktop applications), so I am not sure if it is correct to report here. But I will report here first, and managers can move it if necessary.

- **The time format in English is like this:**
![image](https://user-images.githubusercontent.com/20079289/61058654-abef9200-a3c5-11e9-9ebc-8f5b825ca0cc.png)

- **But in simplified Chinese it is like this:**
![image](https://user-images.githubusercontent.com/20079289/61059042-5962a580-a3c6-11e9-9122-9c34a0fb3717.png)

The date format is completely correct, however, the time format is super uncanny. `上午9点30分`  sounds like `9 o'clock past 30 minutes in the morning`. **Why not display in general number format directly?**

Well, 24-hour time is more acceptable in Chinese, so the time can be converted to `9:30` in simplified Chinese. And same, `9:30 pm` in English can be converted to `21:30` in simplified Chinese. But do not use `9 o'clock past 30 minutes in the evening`, that is so stupid.

I did not find any matched strings in https://adguard.oneskyapp.com, so I do not know if I can improve the translation directly over there. If so, please tell me where the strings are and close this issue. Otherwise, please consider my report and improve it.

**Comment by maximtop** [comment]
@byyxx128 hi
can you send which version do you use?
as I see there is no am/pm format for English in the current version (v.3.2.1)

**Comment by lancelot-moon** [comment]
上午9点30分 = 9:30 AM
He asked to change 2019年7月11日上午9点30分 -> 2019年7月11日 9:30 in **zh-CN** locale.
Such what you did in **zh-TW** locale.
He doesn't wish Chinese time format.

**Comment by byyxx128** [comment]
@lancelot-moon Thanks for your interpretation.
@maximtop Just as he said.
