### ISSUE TITLE
Google Analytics!

### ISSUE THREAD

**Issue by Spok1** [AdguardTeam/AdguardBrowserExtension#1446]
Сделайте так,чтобы utm-метка с юрл http://feedproxy.google.com/~r/itc-ua/~3/dzA3BTfAPaQ/  не срабатывала, а сразу преобразовывалась в  юрл домена itc-ua и пр. Аналитика гугла достала уже меня!
-------------------------------------------------------------------------------------------------------------
Make UTM-label with URL  http://feedproxy.google.com/~r/itc-ua/~3/dzA3BTfAPaQ/ did not work, and immediately transformed into a URL domain itc-ua, etc. Google . Google Analytics is already tired me!

**Comment by zzebrum** [comment]
в url нет utm-метки
