### ISSUE TITLE
Safari add-on blocks whole websites because of $subdocument modifier

### ISSUE THREAD

**Issue by Freida-Moo-Goo-Gai-Pan** [AdguardTeam/AdguardBrowserExtension#145]
With the easy list enabled, it blocks redtube, youporn, youjizz, etc.  Any of those types of sites show ":blank" in the address bar and do not load.  This only happens using the easy list in Adguard and not in other blockers.

**Comment by ameshkov** [comment]
Problematic rules are:
```
||devicemag.com^$subdocument,~third-party
||eporner.com^$subdocument,~third-party
||pornvideoxo.com^$subdocument,~third-party
||tube8.com^$subdocument,~third-party
||youjizz.com^$subdocument,~third-party
||youporn.com^$subdocument,~third-party
```

Content Blocker does not provide a special type for matching iframes, so in our case $subdocument matches any document.

**Comment by ameshkov** [comment]
Temporary solution - do not convert $subdocument rules without $third-party modifier

**Comment by ameshkov** [comment]
I've filed a feature request to webkit:
https://bugs.webkit.org/show_bug.cgi?id=153559

For now we'll use the suggested workaround, but I hope the "subdocument" resource type will be added to webkit.

Fix will be included into the next beta version.
