### ISSUE TITLE
Internal filters conversion

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#1452]
@ameshkov commented on [Tue Apr 23 2019](https://github.com/AdguardTeam/CoreLibs/issues/880)

* Scriptlets/snippets conversion (don't forget about converting `#@#+js`).
* Convert `:style` uBO rules to `#$#`.
* Convert `##^script:has-text` to `$$script[tag-containts]`
* `inline-script` -- the same as `csp=script-src 'self' 'unsafe-eval' http: https: data: blob: mediastream: filesystem:`
* `inline-font`  -- the same as `csp=font-src 'self' 'unsafe-eval' http: https: data: blob: mediastream: filesystem:`

* Also, assume text content for $empty: https://github.com/gorhill/uBlock/commit/3e5c9e00ab3603ae0c02e08b007b084404bbb71d
* Add `media` for `mp4`: https://github.com/gorhill/uBlock/commit/68ae847ba385c09c5efa511d18a18a4753af47be

* [all](https://github.com/gorhill/ublock/wiki/Static-filter-syntax#all) -> multiple rules ($document,popup and $csp)

**Comment by Mizzick** [comment]
- [ x] Scriptlets/snippets conversion (don't forget about converting #@#+js).

- [x ] Convert :style uBO rules to #$#.

- [ ]  Convert ##^script:has-text to $$script[tag-containts]

- [ ] Also, assume text content for $empty: gorhill/uBlock@3e5c9e0

- [ ] Add media for mp4: gorhill/uBlock@68ae847

- [ ] all -> multiple rules ($document,popup and $csp)

**Comment by ameshkov** [comment]
One more thing:
https://github.com/AdguardTeam/CoreLibs/issues/1154#issuecomment-538144831

**Comment by maximtop** [comment]
> One more thing:
> [AdguardTeam/CoreLibs#1154 (comment)](https://github.com/AdguardTeam/CoreLibs/issues/1154#issuecomment-538144831)

already done
```
    actual = adguard.rules.ruleConverter.convertRule('||fastmap33.com^$empty');
    expected = '||fastmap33.com^$redirect=nooptext';
    assert.equal(actual, expected);

    actual = adguard.rules.ruleConverter.convertRule('||anyporn.com/xml^$media,mp4');
    expected = adguard.rules.ruleConverter.convertRule('||anyporn.com/xml^$media,redirect=noopmp4-1s');
    assert.equal(actual, expected);
```

**Comment by ameshkov** [comment]
@maximtop it should be:
```
    actual = adguard.rules.ruleConverter.convertRule('||anyporn.com/xml^$mp4');
    expected = adguard.rules.ruleConverter.convertRule('||anyporn.com/xml^$media,redirect=noopmp4-1s');
    assert.equal(actual, expected);
```

**Comment by maximtop** [comment]
This is ready too

```
QUnit.test('$mp4 modifier should always go with $media modifier together', (assert) => {
    let rule = '||video.example.org^$mp4';
    let actual = adguard.rules.ruleConverter.convertRule(rule);
    let expected = '||video.example.org^$redirect=noopmp4-1s,media';
    assert.equal(actual, expected);

    rule = '||video.example.org^$media,mp4';
    actual = adguard.rules.ruleConverter.convertRule(rule);
    expected = '||video.example.org^$media,redirect=noopmp4-1s';
    assert.equal(actual, expected);

    rule = '||video.example.org^$media,mp4,domain=example.org';
    actual = adguard.rules.ruleConverter.convertRule(rule);
    expected = '||video.example.org^$media,redirect=noopmp4-1s,domain=example.org';
    assert.equal(actual, expected);

    rule = '||video.example.org^$mp4,domain=example.org,media';
    actual = adguard.rules.ruleConverter.convertRule(rule);
    expected = '||video.example.org^$redirect=noopmp4-1s,domain=example.org,media';
    assert.equal(actual, expected);
});
```
