### ISSUE TITLE
Browse button when adding custom filter by path

### ISSUE THREAD

**Issue by SoLenny** [AdguardTeam/AdguardBrowserExtension#1454]
When you want to add a custom filter in the "Custom" tab (AdGuard extension menu -> Filters -> Custom -> Add custom filter), under the input field there is a hint: "Enter valid URL or file path of the filter into the field above. You will be subscribed to that filter". But if you try to enter the file path, it will give an error.  This can be avoided if you enable "Allow access to file URLs" in the settings of the browser (settings ->  extension -> AdGuard extension)
However, for many users, this will not be obvious.  Also, there is no hint of the correct input format of the local path.

So it would be great if the user can just click on the "Browse" button (right side of the input field).

**Comment by maximtop** [comment]
It is impossible to add the "Browse" button because browsers do not allow to get file full path for the next updates due to security reasons.
