### ISSUE TITLE
Inability to scroll the settings page left or right

### ISSUE THREAD

**Issue by SoLenny** [AdguardTeam/AdguardBrowserExtension#1457]
When you open the settings in one window and open something else in an adjacent window (or reduce the window with open settings), it is impossible to scroll the page to the right or left, so it is not possible to turn on or off any functions.

https://uploads.adguard.com/solennyioj53.png

**Comment by maximtop** [comment]
The issue is not actual anymore in version 4.x as the extension's options tab adapts to the screen size.
