### ISSUE TITLE
Handle service workers cache properly

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardBrowserExtension#1459]
### Шаги для воспроизведения:
1. Установить расширение AdGuard версии 3.2.1.
2. Зайти на сайт www.twitter.com.
3. Нажать на кнопку AdGuard в браузере и на основной ползунок который отключит защиту на этом сайте.
4. Закрываем вкладку и открываем новую и опять переходим на www.twitter.com.

### Ожидаемое поведение:
Сайт должен добавится и сохраниться в исключениях.

### Фактическое поведение:
Ползунок остается в позиции включено и сайт не добавился в список исключений.

<details><summary>Описание:</summary>
Пользователь Андрей33 поднимал данный вопрос на форуме:

https://forum.adguard.com/index.php?threads/Не-запоминает-веб-сайт-twitter-в-качестве-исключения.34265/

Мною так же было проведено тестирование и я подтверждаю наличие проблемы.

</details>

### Среда:
Windows 10 Pro, версия 1903, билд 18362.239.
Яндекс Браузер или любой другой на Chromium.
Расширение AdGuard версии 3.2.1.

**Comment by decagon82** [comment]
Сейчас обратил внимание, что у него, когда я захожу на страницы Твиттера, всегда написано "Заблокировано: 0". Может, если никакой рекламы нет на странице, он сам решает быть "зелёным" даже если сайт в исключениях стоит? Хотя, всё равно как-то бессмысленно.

Написал Андрей33 на форуме.

**Comment by maximtop** [comment]
Похоже, что хром начал использовать service worker'ы для загрузки.
А в хроме существует баг https://bugs.chromium.org/p/chromium/issues/detail?id=766433, из-за которого запросы из service worker'ов не попадают в запросы таба, в котором открыт сайт. Поэтому и экстеншн не может правильно определить добавлен сайт в вайтлист или нет.
Твиттер сайт популярный, нужно будет глянуть как решить эту проблему.

**Comment by ngvirus** [comment]
Same happens in tinder(dot)com. Even the site is whitelisted the extension still works and have to be turned off manually every time.
