### ISSUE TITLE
Блокировка

### ISSUE THREAD

**Issue by slavserver** [AdguardTeam/AdguardBrowserExtension#1460]
ПОСЛЕДНЕЕ ОБНОВЛЕНИЕ версии 2019-08-12 23:28

Здравствуйте, блокирует информационные виджеты курса валют, что крайне не удобно..
пример кода:

<script type="text/javascript" src="https://files.coinmarketcap.com/static/widget/currency.js"></script>
<div class="coinmarketcap-currency-widget" data-currency="expanse" data-base="USD" data-secondary="BTC" data-ticker="true" data-rank="true" data-marketcap="true" data-volume="true" data-stats="USD" data-statsticker="true"></div>

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdguardFilters #38595](https://github.com/AdguardTeam/AdguardFilters/issues/38595) via [**ZenHub**](https://www.zenhub.com/)
