### ISSUE TITLE
[Integration mode] Not able to turn off on view-source:

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/AdguardBrowserExtension#1462]
view-source:https://torrentgalaxy.to/

Slider to turn off is not doing anything (missing left part too) when viewing the source of a website, so rules are still active.

<img width="241" alt="integration-mode" src="https://user-images.githubusercontent.com/34266271/63072914-7e4abb00-bf26-11e9-8080-6c77e4143c85.png">

**Comment by SoLenny** [comment]
@BlazDT 
By design.

**Comment by BlazDT** [comment]
Then another message should be displayed.
