### ISSUE TITLE
Remove tracking parameter issue

### ISSUE THREAD

**Issue by PentagramTr** [AdguardTeam/AdguardBrowserExtension#1463]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

Remove tracking parameters feature does not work on some links on this site.

https://forum.donanimhaber.com/

- **AdGuard version:** 3.2.1
  
- **Browser and version:** 68.0.2 (64 bit) Firefox Quantum
  
- **Operating system and version:** Windows 10
  
- **Filters you use in AdGuard:** Base-Social-Tracking Protection-Annoyance-Turkish-NoCoin
  
- **Stealth Mode settings:** Enabled

- **Other browser extensions:** Nimbus-Pushbullet-Simple Translate-View Image-Search by Image 
  

### Actual Behavior

Links still have tracking parameters.

### Additional Information

Click for links with tracking parameters.

https://forum.donanimhaber.com//mesaj/yonlen/139587433

<details><summary>Screenshot:</summary>

![forum donanimhaber com(5)](https://user-images.githubusercontent.com/34379403/63181305-5a879200-c058-11e9-825d-2e6747271173.png)

</details>

After clicking

`https://urun.gittigidiyor.com/cep-telefonu-ve-aksesuar/xiaomi-redmi-note-6-pro-32-gb-siyah-cift-sim-cep-telefonu-466480899?ga_prodid=466480899&amp;scxid=14489-145823-2357-0&amp;utm_source=DonanimHaber&amp;utm_medium=referral&amp;utm_campaign=DonanimHaber&amp;utm_content=standard&amp;v=0.66.8`

---

https://forum.donanimhaber.com//mesaj/yonlen/139559635

<details><summary>Screenshot:</summary>

![forum donanimhaber com](https://user-images.githubusercontent.com/34379403/63181564-f2857b80-c058-11e9-98d5-6656a5c3424b.png)

</details>

After clicking the link still has the parameter.

`https://www.istanbulbilisim.com/nikon-d3500-18-55mm-vr-fotograf-makinesi-fiyati-288257.html?refid=cimri&amp;utm_source=Cimri.com&amp;utm_medium=Cimri.com%20&amp;utm_campaign=Cimri.com`

---

https://forum.donanimhaber.com//mesaj/yonlen/138909201

<details><summary>Screenshot:</summary>

![forum donanimhaber com(3)](https://user-images.githubusercontent.com/34379403/63183673-3f1f8580-c05e-11e9-86d0-8d4d98281756.png)

</details>

`https://teklif.sbm.org.tr/trm-teklif/public/trafikTeklifYenileme/sorgu.sbm?amp;utm_medium=referral&amp;utm_source=DonanimHaber`

**Comment by ameshkov** [comment]
Thank you!

**Comment by ameshkov** [comment]
Closing for now:
https://github.com/AdguardTeam/CoreLibs/issues/1090#issuecomment-529410411
