### ISSUE TITLE
QUESTION - Are there news about Manifest V3 ( Google Chrome ) ?

### ISSUE THREAD

**Issue by LucasDiTomase** [AdguardTeam/AdguardBrowserExtension#1465]
Hi. Chrome (and possibly Firefox) are planning on implementing Manifest V3 for browser extensions. Do you guys have a timeline on when AdGuard will be affected? I read that the first version of M. V3 will come in Chrome Canary soon. Can you elaborate on when you guys will release the first AdGuard browser version that supports V3? Thanks

**Comment by ameshkov** [comment]
Hi! It's too early to say anything as the current state of Manifest V3 draft is not stable. It seems that we have quite some time to adapt so expect some news next year.
