### ISSUE TITLE
"Self-destructing third-party cookies" not working on Firefox 

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardBrowserExtension#1470]
### Issue Details

"Self-destructing third-party cookies" is not working. The kill value is set to 1 minute.

- **AdGuard version:**
  - 3.2.1
- **Browser and version:**
  - 68.0.2 stable
- **Operating system and version:**
  - Linux Pop!_OS (Ubuntu fork)
- **Filters you use in AdGuard:**
  - Base, Tracking, Social, Annoyances
- **Stealth Mode settings:**
  - Default, **Self-destructing third-party cookies (1)**
- **Other browser extensions:**
  - Bitwarden Password Manager

### Expected Behavior

"Self-destructing third-party cookies" should delete 3rd-party cookies after a delay set user

### Actual Behavior

"Self-destructing third-party cookies" does not work for some reason

### Screenshots

<details><summary>Screenshot:</summary>

![2019-08-28 21-31-26 ekran görüntüsü](https://user-images.githubusercontent.com/33634917/64011619-be17c200-cb24-11e9-8dad-13986b32fd9a.png)
![2019-08-28 21-31-42 ekran görüntüsü](https://user-images.githubusercontent.com/33634917/64011620-be17c200-cb24-11e9-8a72-1b6a101594d0.png)

</details>

### Additional Information

Support desk ID: 2298504

**Comment by zzebrum** [comment]
@TheHasagi did you manage to reproduce the issue?

**Comment by TheHasagi** [comment]
Does not happen with the latest extension update.

@akmLaVx 

Please, ask a customer to update the extension version and check again.

**Comment by ameshkov** [comment]
AdGuard does not simply delete all cookies, it should first see this cookie being set or used before kicking off the timer
