### ISSUE TITLE
Extension periodically fails to launch on Firefox

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardBrowserExtension#1472]
### Issue Details

- **AdGuard version:**
  - Ext 3.2.1
- **Browser and version:**
  - Firefox 52.9.0 ESR
- **Operating system and version:**
  - presumably Windows XP
- **Filters you use in AdGuard:**
  - Base, Russian
- **Stealth Mode settings:**
  - Unspecified
- **Other browser extensions:**
  - Irrelevant - extension fails to launch in clear, addon-less browser as well

### Expected Behavior

Extension should launch every time when a user opens Firefox

### Actual Behavior

It doesn't launch sometimes. User is required to go to extension manager [Ctrl+Shift+A] and enable the extension manually.

### Screenshots

None provided.

### Additional Information

Reproduction:

1) Launch browser;
2) AdGuard WON'T start;
3) Go to Tools > Extensions;
4) Disable and then re-enable the extension;
5) Go to AdGuard settings and turn off any mode (ad blocker, stealth mode, etc.);
6) Turn it on back again;
7) Relaunch the browser;
8) AdGuard will then launch.

**Comment by ameshkov** [comment]
I don't see what we can do about this - it sounds clearly like a browser bug (or maybe a compatibility issue with some other addon/browser setting)
