### ISSUE TITLE
Is it possible to somehow use regex/wildcards for CSS attributes?

### ISSUE THREAD

**Issue by levonder** [AdguardTeam/AdguardBrowserExtension#1473]
The use-case is the following:

I used to filter google results based on URL regex which was quite simple using CSS rules with `:contains`, as the URL was printed in plain text in the result feed.

Now google invented super-smart arrow based URL encoding so that e.g.
`https://twitter.com/<username>/status/<post_id>` becomes `https://twitter.com › mxcl › status`.

Initially I was able to filter-out all the status messages via `/twitter\.com.*\/status\//` in a `:contains` block.

Currently I can do it with e.g. this `/twitter\.com.*› status/`, but generally those arrow abbreviations don't map 1:1 to URLs, so I guess I should be able to filter by `href` attribute of a link now.

As I know, usual CSS doesn't allow regex or wildcard rules for attributes.
Is it possible with Adguard with e.g. ExtCss magic or something like that?..

I'm kind of stuck on how to work around this
Would be really glad to hear any suggestions

**Comment by levonder** [comment]
Well, as I see, in most (probably all) of my cases chained selectors (`.a.b`) with some CSS attribute filtering would work

But it would still be really interesting to know if there are any built-in means of working with attributes at a more general level

**Comment by ameshkov** [comment]
> Is it possible with Adguard with e.g. ExtCss magic or something like that?..

Yeah, we even have a feature request about this:
https://github.com/AdguardTeam/ExtendedCss/issues/90
