### ISSUE TITLE
Some $csp rules are not applied to iframes

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#1475]
@AdamWr commented on [Mon Jun 10 2019](https://github.com/AdguardTeam/CoreLibs/issues/963)

It seems that there is a difference how `$csp` rules work in app and extension.
For example, in app a rule like this `$csp=img-src 'none',domain=example.com` is also applied to iframes, but in extension it isn't.

### Steps to reproduce

First case.
1. Add this rule:
`$csp=worker-src 'none',domain=powvideo.net`
2. Go to this website - https://powvideo.net/n2ijzy8kb2st

Second case.
1. Add this rule:
`$csp=img-src 'none',domain=cdaction.pl`
2. Go to this website - https://www.cdaction.pl/news-56870/doom-eternal-mamy-gameplay-i-date-premiery-wideo.html

### Expected behavior

In first case reCAPTCHA shouldn't be broken.
In second case images from YouTube shouldn't be blocked.
### Actual behavior

reCAPTCHA is broken.
Images from YouTube are blocked.

<details><summary>First case:</summary>

![image](https://user-images.githubusercontent.com/29142494/59184799-2fbc2180-8b6f-11e9-96aa-65c63684b124.png)

</details>

### Your environment

* Adguard version: AdGuard for Windows 7.0.2708.6691 NIGHTLY (CL 1.4.13)

---

@AdamWr commented on [Mon Jun 10 2019](https://github.com/AdguardTeam/CoreLibs/issues/963#issuecomment-500363310)

Regarding first case - it was reported here - https://github.com/AdguardTeam/AdguardFilters/issues/34925 and I added `@@||google.com/recaptcha/$csp` as a temporary solution, so please disable it before checking.

---

@bogachenko commented on [Mon Jun 10 2019](https://github.com/AdguardTeam/CoreLibs/issues/963#issuecomment-500369321)

> $csp=worker-src 'none',domain=powvideo.net

`powvldeo.net`

add also and this domain

---

@ameshkov commented on [Mon Sep 09 2019](https://github.com/AdguardTeam/CoreLibs/issues/963#issuecomment-529471789)

Well, it occurs to me that it works properly in the program.

This should be moved to the extension's repo.

**Comment by maximtop** [comment]
expected and actual behaviors are inverted because the issue was copied from corelibs repository

**Comment by ameshkov** [comment]
closed as a duplicate of https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1494

Please check that it works properly in our case.
