### ISSUE TITLE
$badfilter modifier does not work, if a rule converted by AdGuard

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1476]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - AdGuard v3.2.1/3.2.2
- **Browser and version:**
  - Chrome 76
- **Operating system and version:**
  - Windows 10
- **Filters you use in AdGuard:**
  - Base filter, Social filter, Russian
- **Stealth Mode settings:**
  - 
- **Other browser extensions:**
  - 

### Expected Behavior

`||v.adfox.ru/*/getCode?pp=$domain=1tv.ru,empty,important` is disabled by `||v.adfox.ru/*/getCode?pp=$domain=1tv.ru,empty,important,badfilter`

### Actual Behavior

The rule is not disabled even with `||v.adfox.ru/*/getCode?pp=$domain=1tv.ru,redirect=noopjs,important,badfilter`

### Additional Information

`||v.adfox.ru/*/getCode?pp=$domain=1tv.ru,empty,important` is removed from Russian filter, so import it in custom filter.

**Comment by ameshkov** [comment]
@maximtop I suggest handling this on the "rules converter" level
