### ISSUE TITLE
Does the AdGuard AdBlocker Whitelist allow wildcards?

### ISSUE THREAD

**Issue by gaveitatry02** [AdguardTeam/AdguardBrowserExtension#1479]
There is a website that I have on my Whitelist that keeps changing.  Examples:
ww1.something.com
www6.something.com
www9.something.com
www11.something.com

I don't want to keep adding an exception to my Whitelist each and every time the domain changes slightly.  One, because it is inconvenient.  But two, also because I forget.  So I go to this website and videos won't work and I won't have any idea why.  It will take me a few days or weeks before I realize that it is because the domain changed slightly and now I have to create a new entry in my Whitelist.

So I am wondering if there is a way to use wildcards.  Like www*.something.com.  Please let me know.  Thanks.

EDIT:  I want to add that using i.e. something.com didn't work for that particular website.  So I had to be specific and use ww11, or whatever it was at the time.

**Comment by gaveitatry02** [comment]
UPDATE:  I tested out ww*.something.com and it seems to be working.  Am I doing it right?  Am I mistaken, or is this really working?  You should provide some wildcard information on the add-on page on the Whitelist tab so people will know that they can use it.

**Comment by TheHasagi** [comment]
@gaveitatry02 

Extension support wildcards partially, for example - `google.*`
