### ISSUE TITLE
The paths for all devtools JS modules have changed

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#148]
I am not sure about Pale Moon though.

https://bugzilla.mozilla.org/show_bug.cgi?id=1203159

Warning: The paths for all devtools JS modules have changed from resource://gre/modules/devtools/* to resource://devtools/*.See https://bugzil.la/1203159 for more information.

```
var console = Cu.import('resource://gre/modules/devtools/Console.jsm', {}).console;
```

**Comment by Mizzick** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1203159#c79

Console.jsm path was not changed. So no need to do anything here

**Comment by Mizzick** [comment]
Changed
