### ISSUE TITLE
web.whatsapp not working

### ISSUE THREAD

**Issue by Zahar661** [AdguardTeam/AdguardBrowserExtension#1480]
- **AdGuard version:3.2.1
- **Browser and version: Yandex 19.9.1.237
- **Operating system and version: Windows 10
- **Filters you use in AdGuard: Base filter
- **Stealth Mode settings: if it's enabled
- **Other browser extensions: no

### Expected Behavior

What site will work

### Actual Behavior

The site says that the PC is not connected to the Internet, the site works but not on all ports or services

### Screenshots
![image](https://user-images.githubusercontent.com/26430136/64935863-5ec7ea80-d864-11e9-9903-66c3cd98e4dc.png)

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/26430136/64935911-7b642280-d864-11e9-88cc-eae869e666a5.png)
With off Adguard works
![image](https://user-images.githubusercontent.com/26430136/64935940-a2225900-d864-11e9-93b8-cb1c89c15748.png)

</details>

**Comment by TheHasagi** [comment]
That's strange. Cannot reproduce the issue, WhatsApp web connecting as usual without any problem. By the way, if you disable protection for that domain it can not be filtered or affected by AdGuard. Also, can you send the exported settings to devteam@adguard.com to me for check?

**Comment by Zahar661** [comment]
settings rest to default.
Of the features, the Internet through a proxy. 
I understand that if the site is in exceptions, it should not affect, but in fact something like this.
![image](https://user-images.githubusercontent.com/26430136/66108870-8cd35b80-e5d4-11e9-9f24-431e72755f05.png)
![image](https://user-images.githubusercontent.com/26430136/66108891-98bf1d80-e5d4-11e9-83e6-079336cc5b51.png)
![image](https://user-images.githubusercontent.com/26430136/66109038-dcb22280-e5d4-11e9-90d8-db34189916cb.png)

**Comment by zzebrum** [comment]
@Zahar661 does WhatsApp working with AdGuard if you disable proxy?

**Comment by Zahar661** [comment]
@zzebrum there is no way to check, without a proxy there is no internet.

**Comment by Alex-302** [comment]
Is stealth mode enabled?

**Comment by Zahar661** [comment]
@Alex-302  no

**Comment by Alex-302** [comment]
Does it work when all filters, stealth mode and safebrowsing are disabled?

**Comment by ameshkov** [comment]
@zebrum have you tried reproducing this in YaBro specifically? It sometimes behaves differently to Chrome, and if we're able to reproduce this, we'd better report the bug to them.

**Comment by zzebrum** [comment]
well, no problems on my side, but I don't use proxy though
@Zahar661 if you disable AdGuard extensions in browser settings, whatsapp is working correctly?

**Comment by TheHasagi** [comment]
Seems like this issue is not actual. What's app web is working properly with any filters recommended in extension. 

@Zahar661 

If you still facing this problem, let me know by a mention.
