### ISSUE TITLE
Adguard Keeps Hanging/freezing Safari

### ISSUE THREAD

**Issue by JasonFrovich** [AdguardTeam/AdguardBrowserExtension#1487]
I have never had safari hang/beachball so often, and then I have to force quit it. It been close to 10 times since installing this plugin last night.

- [ ] I am running Version 1.5.4
- [ ] No one else is complaining of hanging.

### Issue Details

AdGuard Version 1.5.4
Safari 13
MacOs 10.14.6
Only enabled Base fillers, turned all other off to try and fix the issue
Don't see any settings on stealth mode.
No other extensions enabled.

It happened several times when I tried to edit a picture in Shopify website.
It also happened when I was watching a YouTube video and just now composing an email in gmail.
Most time I'm just surfing, typical usage. Please tell me what else I can do, this isn't usable at this time.

I am unable to find log files for the app, in either library folder.
I an able to find 2 safari.hang files. I will zip them and upload them.

[Safari Hang.zip](https://github.com/AdguardTeam/AdguardBrowserExtension/files/3644108/Safari.Hang.zip)

**Comment by zzebrum** [comment]
Issue moved to [AdguardTeam/AdGuardForSafari #257](https://github.com/AdguardTeam/AdGuardForSafari/issues/257) via [**ZenHub**](https://www.zenhub.com/)
