### ISSUE TITLE
Change display of a rule in `Filtering rule` column in filtering log

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1496]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

Element hiding, JS, CSS rules with few domains are not visible.

![image](https://user-images.githubusercontent.com/8361299/66126260-c070ae80-e5f1-11e9-88a6-48556832637c.png)

It is a problem, when filter contains a list of the rules with the same domains list. User need to cliсk on every string to check which rule was applied.

### Proposed Solution

Strip domains and show `…` instead of domains in `Filtering rule` column(full rule is visible in details).

![image](https://user-images.githubusercontent.com/8361299/66126633-966bbc00-e5f2-11e9-9b04-ef09f2225a4f.png)

**Comment by XX-J** [comment]
Это до сих пор актуально, @Alex-302 может стоит переоткрыть?
