### ISSUE TITLE
Please add Estonian (et) and Hindi (hi) localizations

### ISSUE THREAD

**Issue by aalpatkina** [AdguardTeam/AdguardBrowserExtension#1497]

**Comment by Laurisade** [comment]
Beta 3.3.2 still does not include Estonian translation.

Could you add it? So I could fix potential context based smaller mistakes before the final :)

**Comment by maximtop** [comment]
> Beta 3.3.2 still does not include Estonian translation.
> 
> Could you add it? So I could fix potential context based smaller mistakes before the final :)

Sorry, but we already released 3.3.2 without the Estonian language.
I'll reopen this issue, and in the next release, i'll add it for sure.
