### ISSUE TITLE
Is it possible to apply CSS rules inside iframes?

### ISSUE THREAD

**Issue by levonder** [AdguardTeam/AdguardBrowserExtension#1498]
Usecase: suppose I have the following rule
```
amazon.com#?##productDescription
```
It's ExtCss-style rule (the same behavior with a usual rule - `###` instead of `#?##`)

It works on usual Amazon pages but doesn't work on eBook ones - those ones are wrapping productDescription sections in iframes
E.g. it doesn't work here: https://www.amazon.co.uk/Art-War-Sun-Tzu-ebook/dp/B009MFTGBS

Is it possible for the rule to work on the latter page?
I googled a bit and it seems AG should support blocking inside iframes (especially on the desktop (Chrome)), but I can't get it to work

Thank you.

**Comment by Alex-302** [comment]
Hi
This rule works in my case
`amazon.co.uk##div#productDescription`

![image](https://user-images.githubusercontent.com/8361299/66239968-da021b00-e703-11e9-8115-ad4a755f59f8.png)

**Comment by levonder** [comment]
Hm... apparently my usecase is somewhat more subtle that I thought.. Does iframe blocking play well with CSS 4 `has`/`contains` (pseudo-)rules?
Your rule does work for me indeed (in the form `amazon.co.uk###productDescription`, as well as in the form you pasted), but this one doesn't: `amazon.co.uk###productDescription:has(.content)` (while there is a `content` element inside a `productDescription` one).

`#?#` doesn't seem to help (on the contrary, it breaks even the rule without `has`). (Maybe it's expected, I don't know.)

**Comment by Alex-302** [comment]
Sure. Extended CSS rule does not work in this case.

**Comment by ameshkov** [comment]
Hmm, wait, ExtCSS rules should also work okay, and if they're not -- this is a bug.
