### ISSUE TITLE
Add Thunderbird compatibility to add-on manifest

### ISSUE THREAD

**Issue by CHEF-KOCH** [AdguardTeam/AdguardBrowserExtension#150]
Hey, is it possible to add the Thunderbird addon in the store so that I can directly download it from the official addon store and install it?

[I don't know if that is necessary if I use AdGuard](https://github.com/AdguardTeam/AdguardForWindows/issues/785) but not everyone want to install the client and just want the addon. 

I also tried to download the .xpi and install it directly via Thunderbird but seems it isn't compatible, so that's why I'm open this.

Many thanks guys. :+1:

**Comment by ameshkov** [comment]
I suppose it is possible, currently thunderbird is simply not listed in add-on manifest. We'll try it after #138

**Comment by CHEF-KOCH** [comment]
THX ! :+1:

**Comment by ameshkov** [comment]
Again, not so easy:) Thunderbird does not support Firefox Add-on SDK which we use now.

But anyway, we want to drop it. So we'll add Thunderbird as soon as #151 is resolved.

**Comment by Mizzick** [comment]
Seems like it's too late for easy way with adding few lines in `install.rdf`.
Thunderburd is moving towards WebExtensions support, but it's not yet enough implemented.

We should keep a look at uBlock simular issue:
https://github.com/gorhill/uBlock/issues/3698
