### ISSUE TITLE
Testcase for “Blocking simple websocket” is broken

### ISSUE THREAD

**Issue by SoLenny** [AdguardTeam/AdguardBrowserExtension#1500]
Add "http://testcases.adguard.com/Filters/websockets/test-websockets.txt" as custom filter.
Go to http://testcases.adguard.com/Filters/websockets/test-websockets.html

Expected behaviour: all tests passed.

Actual behaviour: 2nd test failed.

**Comment by ameshkov** [comment]
This is not our bug. WebSocket blocking appears to be broken in Chrome 77. It is likely that it will be fixed in Chrome 78.

Bug in Chromium:
https://bugs.chromium.org/p/chromium/issues/detail?id=1011108
