### ISSUE TITLE
NotepAd++ userDefinedLang.xml for AdBlock, AdGuard and uBlock syntax.

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardBrowserExtension#1501]
Есть-ли userDefinedLang.xml для подсветки синтаксиса составления правил в NotepAd++ ?
Если нет, то может стоит сделать? Мне бы очень подсобило...

**Comment by Alex-302** [comment]
Есть для Visual Studio Code
https://marketplace.visualstudio.com/items?itemName=adguard.adblock

**Comment by XX-J** [comment]
> Есть для Visual Studio Code

 Хочется именно для NotepAd++. Зачем устанавливать отдельное приложение только для написания правил блокировки? А NotepAd++  -  универсален, т.е. может использоваться для всего.

 Я, может, и сам бы сделал userDefinedLang.xml для синтаксиса правил, но мне нужно где-то взять ключевые слова, знаки, выражения и их сопоставления по цветам. Пока нашёл только сопоставления цветов с классами в стиле, спрятанном в [ace.js](https://github.com/AdguardTeam/AdguardBrowserExtension/blob/master/Extension/lib/libs/ace/ace.js)...

**Comment by Alex-302** [comment]
подсветка описана здесь https://github.com/ameshkov/VscodeAdblockSyntax/blob/master/syntaxes/adblock.tmLanguage.json

**Comment by XX-J** [comment]
> подсветка описана здесь

 Я смотрел этот файл. Обозначений цветов там не нашёл. Да и синтаксис типа этого: `"match": "^(.*?)(#@?\\??#\\^?)(.+)$"` - я не понимаю (это регулярное выражение?).

**Comment by Alex-302** [comment]
да, это регулярные выражения, в соответствии с которыми подвечиваются части правила

**Comment by Alex-302** [comment]
Там зависит от цветовой темы VSC.

**Comment by XX-J** [comment]
Значит [adblock.tmLanguage.json](https://github.com/ameshkov/VscodeAdblockSyntax/blob/master/syntaxes/adblock.tmLanguage.json) не подходит как образец для переделки...

**Comment by ameshkov** [comment]
Ну другого нет. Хороший повод переехать на visual studio code:)
