### ISSUE TITLE
Add advanced settings

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1502]
Create an option to show advanced settings in miscellaneous settings.
It will be useful to add features, whish are not necessary or redundant in UI.
At the moment there is nothing to add there, but maybe this https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1441 can be added, or maybe 
 some UI tweaks.

**Comment by oleedd** [comment]
Maybe to add this:
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1257
Autosaving rules every 3 seconds is very annoying. It is not so quick to type a rule.
