### ISSUE TITLE
New scam in adfly and another sites

### ISSUE THREAD

**Issue by abnergou** [AdguardTeam/AdguardBrowserExtension#1503]
Hello devs, i like so much this plugin, really help and use full thanks by that.
I just report a new scam in adfly and another sites in web, is really suspicius and can exposed the users.
I really hate  this scam and this just a poor formule to get money.
This is a image of scam: https://imgur.com/X9Wv1ip
I really say thank if adguard can block or bypass this.

**Comment by abnergou** [comment]
> @abnergou can you provide an example link?

Any links shortened by adfly
Like this: http://eunsetee.com/5yw
This is one link what the adfly redirect: https://maranhesduve.club/?tag_id=759228&sub_id1=-1&sub_id2=5664589250004559617&cookie_id=72c95fec-0f6a-44fb-b892-ac00f8b59bfd&lp=adfly_allow&convert=Your%20Video%20Is%20Ready%20To%20Stream&allb=redirect&ob=redirect&href=http%3A%2F%2Fgoogle.com&hop=3&info=&geo=PT

**Comment by zzebrum** [comment]
@abnergou well, that's how adfly works and monetize its service. The best way is to avoid using it then. You can report specific scam domains though.
