### ISSUE TITLE
The language of blocking page doesn't follow system language UI via v3.3.2.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardBrowserExtension#1510]
1. In v3.3.2, you forsake the old blocking page and then use the blocking page which is used by AG for PC/Home.
On my Windows 10, the language UI of AG browser extension is Chinese Traditional.
But the language of blocking page is English via v3.3.2.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/VLaXEOQ.png)
</details><br/>

2. You updated AG browser extension to v3.3.2 on Chrome web store.
But it's strange that I couldn't update to v3.3.2 by clicking "update" button in Chrome's extension setting.
I need to remove the old version and then install a new one.
Why?

3. Does AG for Safari have the Browsing Security?
May you check the language of blocking page via AG for Safari v1.6?
Well, I just know AG for Safari doesn't have Browsing Security.

B/R

**Comment by maximtop** [comment]
1. We will fix it, thank you.
2. We have published it only for a small part of users
3. You would better to ask about safari extension in the safari repository https://github.com/AdguardTeam/AdGuardForSafari
