### ISSUE TITLE
AdGuard French filter is blocking WatchESPN service provider selection images

### ISSUE THREAD

**Issue by mmortal03** [AdguardTeam/AdguardBrowserExtension#1512]
### Platform

AdGuard Version 3.2.1
Chrome Version 77.0.3865.120 (Official Build) (64-bit)
Windows 10
Language Specific AdGuard French filter

### Expected Behavior

When you click on a WatchESPN program, you'll be able to see the service provider images so that you can select the appropriate one.

### Actual Behavior

The service provider images get blocked, so all you see are blank rectangles.

### How to reproduce

1.) Clear browser cache, just to be sure. 
2.) Enable Language Specific AdGuard French filter. 
3.) Browse to https://www.espn.com/watch/schedule
4.) Click on a program
5.) See screenshot below for the result

### Other information

An example of one of the blocked provider images' host URL: https://secure.espncdn.com/espn360/images/affiliates/pickerImage/logo-spectrum.png

### Screenshots

![AdGuard_French_filter_bug](https://user-images.githubusercontent.com/8298277/67158357-babade80-f2fc-11e9-974d-8000f4e4718f.jpg)

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdguardFilters #42681](https://github.com/AdguardTeam/AdguardFilters/issues/42681) via [**ZenHub**](https://www.zenhub.com/)
