### ISSUE TITLE
Block WebRTC won't enable.

### ISSUE THREAD

**Issue by Novaaaaaaaa** [AdguardTeam/AdguardBrowserExtension#1515]
When I toggle Block WebRTC on, it immediately toggles itself back off again. I am using 3.3.2 on chrome. If you need more information, I'd be happy to help.

**Comment by maximtop** [comment]
Which version of Chrome are you using?
Have you allowed permission?
![image](https://user-images.githubusercontent.com/17272769/67557090-0fa38e00-f71d-11e9-83c0-55ad2e83766f.png)

**Comment by SoLenny** [comment]
@Novaaaaaaaa Hello, can you specify which version of Chrome are you using?
Have you allowed permission?

**Comment by SoLenny** [comment]
At this moment we did not receive the necessary information from the user, therefore we are forced to close this task :( 
But if you still have this problem, be free to open it again.
