### ISSUE TITLE
New empty lines added between the rules in filter editor

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1517]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:** 3.3.2
  - 
- **Browser and version:** Chrome 76
  - 
- **Operating system and version:** Windows 10
  - 
- **Filters you use in AdGuard:** Base, Social, Spyware, Russian, Annoyances
  - 
- **Stealth Mode settings:** no
  - 

### Actual Behavior

When few rules pasted to filter editor, new empty lines added between the rules.

### Screenshots

![111](https://user-images.githubusercontent.com/8361299/67754623-74bdf300-fa3f-11e9-8a76-3b3066cfa52f.gif)

**Comment by maximtop** [comment]
From which place do you copy rules?

**Comment by Alex-302** [comment]
From Visual Studio Code. The same with text copied from browser.
