### ISSUE TITLE
Some sites do not open in Firefox Nightly 72.0a1 with Adguard enabled

### ISSUE THREAD

**Issue by pohunohi** [AdguardTeam/AdguardBrowserExtension#1518]
https://www.neowin.net/news/cat/software
http://www.fast-torrent.ru/
> Corrupted Content Error
    The page you are trying to view cannot be shown because an error in the data transmission was detected. Please contact the website owners to inform them of this problem.

**Comment by SoLenny** [comment]
@pohunohi Hello, can you please specify which version of AdGuard you use?

**Comment by pohunohi** [comment]
> 
> 
> @pohunohi Hello, can you please specify which version of AdGuard you use?

3.3.2

**Comment by SoLenny** [comment]
@pohunohi And please, specify which filters enabled.

**Comment by maximtop** [comment]
seems that this rule brokes fast-torrent
`fast-torrent.ru$$script[wildcard="*a['push'](a['shift']());}};var c=*return'newState';*while(!![])*"][max-length="110000"]`

**Comment by pohunohi** [comment]
> 
> 
> @pohunohi And please, specify which filters are enabled.

Базовый фильтр AdGuard
Фильтр счетчиков и систем аналитики
Фильтр виджетов социальных сетей
Фильтр раздражителей
Русский фильтр

**Comment by ameshkov** [comment]
Can you reproduce it on example.org?

Try adding `example.org$$div` to the user filter and see how it goes.

**Comment by Alex-302** [comment]
The same issue with `example.org$$div`

**Comment by ameshkov** [comment]
99% probability this is a bug in Firefox and we should report it to them @maximtop

**Comment by Vladsg** [comment]
I had the same problem, but everything is already solved. As said above, most likely the problem was in Firefox, but these are nightly builds
AdGuard 3.3.2
Firefox: 72.0a1 (2019-11-10)

**Comment by maximtop** [comment]
@SoLenny I confirm that in the last nightly build there are no errors
