### ISSUE TITLE
(Pale Moon) Misconfigurations or overlaping windows

### ISSUE THREAD

**Issue by LimboSlam** [AdguardTeam/AdguardBrowserExtension#152]
Hi there, I'm just installed the recent RC of Adguard Adblocker and gotta say it's improving greatly! :+1: Though theres two small issues:   

![adguard adblocker with pale moon v26 0 0](https://cloud.githubusercontent.com/assets/10698432/12693990/8384ed84-c6d2-11e5-83e2-ddd029697313.jpg)

![adguard](https://cloud.githubusercontent.com/assets/10698432/12694056/f1705df4-c6d4-11e5-9a8e-d6fe91650de8.jpg)

1.) Go to: http://www.zdnet.com/article/how-to-switch-from-pc-windows-to-a-mac-as-painlessly-as-possible/
2.) Click the Adguard add-on and hit the search/filter log icon (you'll see the overlap, hopefully)
3.) Exit out the filter logger/pop-up window and re-click the Adguard add-on 

This issue also occurs only in Pale Moon and not Firefox eithier v38.6 or v44.0. I tested against v25.7.3 and v25.8.1 of Pale Moon and the issue does occur before v26.0.0, which is what I'm currently using.. I'm also on Windows Vista SP2 x86 

Hope this helps and if need anymore info, just ask me.

**Comment by ameshkov** [comment]
We'll check it, thank you!

**Comment by Mizzick** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=942511

**Comment by Mizzick** [comment]
Fixed

**Comment by atropnikov** [comment]
I think we need to fix win.getActiveTab in https://github.com/AdguardTeam/AdguardBrowserExtension/blob/master/Extension/browser/firefox_legacy/data/content/content-script/popup-script.js. Use UI.getActiveTab instead of tabs.activeTab.

**Comment by Mizzick** [comment]
Ok

**Comment by LimboSlam** [comment]
Thanks you guys! So this will be fixed in milestone 2.2 or 2.3?

**Comment by ameshkov** [comment]
I think it will be in v2.2 as commit fixing it was pushed to master already.

**Comment by LimboSlam** [comment]
Sweet. This is good news. Thanks again! :+1:
