### ISSUE TITLE
google analytics are broken by $document exclusion

### ISSUE THREAD

**Issue by leninalbertolp** [AdguardTeam/AdguardBrowserExtension#1520]
Hello, everybody.

Sorry my English is not my native language, Deepl is my best friend in these cases.

Last week I reported on reddit something strange that was happening to me with Google Analytics, I leave the [link to reddit](https://www.reddit.com/r/Adguard/comments/dnzib2/problem_with_google_analytics/) but I'm still going to reproduce it here. I think I found the cause of what I'm going to expose.

I have problems accessing the initial screen of Google Analytics I skipped the following message.

>Missing permits
>You do not have access to the account, property or view. Contact an Analytics administrator who has user management permission.

Other functions if they are accessible on a regular basis.

Screenshot with adguard enabled.

![Adguard Enable](https://i.imgur.com/3kxgHm2.jpg)

Screenshot with adguard disabled.

![Adguard Disable](https://i.imgur.com/A15TmAV.jpg)

Does it happen to anyone else?

Adguard for Windows 7.2.2936 Beta License

Beta Browser Extension 3.3.2

Filters activated:

English filter, mobile advertising filter, spyware filter, useful ads filter, Spanish/Portuguese filter, extra adguard, adguard popup blocker

Discreet mode activated:

Hide your search queries, send Do-Not-Track request, remove X-Client-Data header from HTTP requests, auto-destruct third party cookies = 0, block WebRTC

Red:

Using the WFP Network Controller

Filter HTTPS protocol = Enabled

Adguard for chrome, firefox and microsoft edge chromium in integration mode

**I think I found the cause of the problem**.

The error occurs between the Adguard for Windows application and the browser extension in integration mode.

What led me to that conclusion?

When using the windows application without the browser extension, the error does not appear.

When the windows application protection is paused and the extension exits the integration mode, the error does not appear.

The error is only reproduced when you have the Windows application and the browser extension in integration mode.

**Update**

It is neither the windows application nor the browser extension. It is a rule in the English filter.

![filter for english](https://i.imgur.com/EgpQhGg.jpg)

When deactivating the **@@|google.com/analytics/web/$document** rule of the English filter the error is no longer reproduced.

**Comment by ameshkov** [comment]
@Alex-302 please take a look, this sounds like an AG issue

**Comment by Alex-302** [comment]
@leninalbertolp I have no issues when click on 
Home icon. Could you, please, open filtering log, reproduce an issue and make screenshot of blocked requests?
![image](https://user-images.githubusercontent.com/8361299/68941289-1e2a1600-07ae-11ea-8296-0068b0ae9230.png)

**Comment by leninalbertolp** [comment]
@Alex-302 I'm sorry for my late response. I was away from home for a few days.

Here's the image you asked for.

![adguard001](https://user-images.githubusercontent.com/8427648/69621544-b24d7600-1015-11ea-93f1-fcc1de5c4699.png)

In addition, I recorded a video reproducing the error.

[Watch video](https://www.youtube.com/watch?v=ZVx9YoZV2g8)

**Comment by Alex-302** [comment]
@leninalbertolp please check with disabled(one by one, with checking after each):
- filters;
- Stealth Mode;
- AdGuard extension module.

**Comment by leninalbertolp** [comment]
If you deactivate the English filter, the error disappears.

**Comment by Alex-302** [comment]
Ok. Please check these exclusions one by one:
- `@@||analytics.google.com^$jsinject`;
- `@@||analytics.google.com^$jsinject,elemhide,extension`;
- `@@||analytics.google.com^$urlblock`;
- `@@||analytics.google.com^$content`.

**Comment by leninalbertolp** [comment]
@Alex-302  Add one by one to the user rules and in each the continuous error.

**Comment by Alex-302** [comment]
Which domain you visiting?

**Comment by leninalbertolp** [comment]
analytics.google.com/analytics/

**Comment by Alex-302** [comment]
Strange. Could you, please, provide remote access?

**Comment by leninalbertolp** [comment]
Yeah right, tell me how we do

**Comment by Alex-302** [comment]
ok. Do you have Telegram or Skype?

**Comment by leninalbertolp** [comment]
skype leninp6

**Comment by Alex-302** [comment]
Cannot find. Please write to me: `Alex302 .` (with a dot at the end)

**Comment by leninalbertolp** [comment]
the dot is glued or separated because I get several

**Comment by Alex-302** [comment]
![image](https://user-images.githubusercontent.com/8361299/69671915-9e4e5680-109f-11ea-86d4-56b031733896.png)
please make screenshot of results

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/CoreLibs #1207](https://github.com/AdguardTeam/CoreLibs/issues/1207) via [**ZenHub**](https://www.zenhub.com/)
