### ISSUE TITLE
AdGuard is not available in the Chromium based Microsoft Edge extensions gallery.

### ISSUE THREAD

**Issue by sergerosenthaler** [AdguardTeam/AdguardBrowserExtension#1521]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

AdGuard is not available in the Chromium based Microsoft Edge extensions gallery.
https://microsoftedge.microsoft.com/insider-addons/category/EdgeExtensions

### Proposed Solution

AdGuard should be published to the Chromium based Microsoft Edge extensions gallery under 
https://microsoftedge.microsoft.com/insider-addons/category/EdgeExtensions

### Alternatives Considered

Alternatively a download from the Chrome Gallery is possible, but not perfect.

**Comment by zzebrum** [comment]
@sergerosenthaler Currently, it seems that they have chosen by themselves the extensions list is present in Store. We will keep an eye on this.

**Comment by beerisgood** [comment]
@zzebrum 
Is this a official build?:
https://microsoftedge.microsoft.com/addons/detail/pdffkfellgipmhklpdmokmckkkfcopbh

Version info say 3.4.15 but here on GitHub and chrome store latest version is 3.4.11

**Comment by maximtop** [comment]
@beerisgood yes, it is official.

**Comment by TPS** [comment]
I think someplace w/in Adguard Windows when detecting Edge Chromium ("Chredge") as the main browser, it's redirecting to Chrome extensions, instead of Edge's.  Could y'all coordinate w/ that team to fix?

**Comment by ameshkov** [comment]
@TPS well, we just haven't published Assistant to the Edge Store. But since there's a risk of someone uploading a fake there, we'll do this: https://github.com/AdguardTeam/BrowserAssistant/issues/22

**Comment by TPS** [comment]
@ameshkov: @maximtop said _(above)_ that it _is_ officially published there?
