### ISSUE TITLE
regex no support block load domains with $document or $all

### ISSUE THREAD

**Issue by krystian3w** [AdguardTeam/AdguardBrowserExtension#1522]
### Prerequisites

- [X] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

New method block load domain with `$document` or `$all` no support regex. [](https://github.com/PolishFiltersTeam/KAD/issues/905)

- **AdGuard version:**
  - 3.3.2
- **Browser and version:**
  -  Chrome 78 and Firefox 70.0.1
- **Operating system and version:**
  - Windows 10 Pro 19H1 (1903)
- **Filters you use in AdGuard:**
  - `KAD - Przekręty`  ([filter_232_KADPrzekrety](https://github.com/AdguardTeam/FiltersRegistry/tree/master/filters/ThirdParty/filter_232_KADPrzekrety))
- **Stealth Mode settings:**
  - Disabled
- **Other browser extensions:**
  - None

### Expected Behavior

Allow use regex to "blacklist" (block load) scam domain with `$document` / `$all`

### Actual Behavior

Regex no block load page (with warning).

### Screenshots

N/A

### Additional Information

Regex used in KAD:

```
/^https?:\/\/(.*\.|)(apps?|best|competition|game|mobile|play|prize|reward|sweeps)[0-9]{2,8}\.[a-z-]{5,22}[0-9]{1,8}\.(agency|icu|life|live)\//$document,domain=agency|icu|life|live
```

Also tested simplified many versions - also does not work.

Remove `domain=agency|icu|life|live` also does not help.

---

uBO support regex and block these domains with scam:

`http://prize64576.nonametds34.live/?u=kwwbb7n&o=fhccwn7`

![obraz](https://user-images.githubusercontent.com/35370833/68532551-c78c8a00-031e-11ea-9699-6d0a49955856.png) |
--- |

IMO faster than blacklist any on DNS level manually.

**Comment by ameshkov** [comment]
You don't need this part here: `domain=agency|icu|life|live` 
```
/^https?:\/\/(.*\.|)(apps?|best|competition|game|mobile|play|prize|reward|sweeps)[0-9]{2,8}\.[a-z-]{5,22}[0-9]{1,8}\.(agency|icu|life|live)\//$document,domain=agency|icu|life|live
```

I don't really understand why this works in uBO, but personally, I find this approach to $domain modifier broken.

**Comment by krystian3w** [comment]
I suppose regex without domains can slowdown more than 4 tld.

**Comment by krystian3w** [comment]
I suppose regex without domains can slowdown more than 4 tld.

**Comment by ameshkov** [comment]
> I suppose regex without domains can slowdown more than 4 tld when use $all instead of $document.

Hm, so that's why it is used? Well, this might make sense.

I guess we can make an exception for `$domain` modifier semantics in one case -- when we match requests with the "DOCUMENT" type: https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1534

**Comment by Yuki2718** [comment]
I tend to agree, this "noname" series is changing rapidly and both AdGuard Browsing security and Google Safe browsing haven't been able to catch up while a single regex filter can block all of them.
Just an another recent example:
https://github.com/AdguardTeam/AdguardFilters/issues/46124

**Comment by krystian3w** [comment]
Theoretically, it is enough to update the holes on your pages/server and the infection is unlikely to sneak in.

---

As for the idea of regex, I decided that the domain names are unfortunately unstable / vulgar (rare eg. `prizeXXXX.f**kingmodayXXXX.XXXX), so it is based on subdomains.

Old solution with wildcards can found here:

https://github.com/PolishFiltersTeam/KAD/issues/919#issue-461224300 (Rather outdated.)

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/74785136-dbdf0c00-52a9-11ea-912d-aba33c055cfd.png)

so no support TLD only now.

**Comment by ameshkov** [comment]
> so no support TLD only now.

What do you mean?

**Comment by krystian3w** [comment]
I cannot use only:

`domain=agency|icu|life|live`

To exlude test other 1-st/highest level domains, e.g.:

```
.pl
.ru
.ua
```

Regex generate popup if only delete domain 'Basic modifier' or when I give the full domain name (which makes no sense in this case).

Consider removing the modifier to and AdGuard effectively block scam with fake tinder / free phones and tablets.
As long as the filter does not interfere with the smooth and stable operation of the browser.
