### ISSUE TITLE
Add Support For The Way uBlock Origin Can Block Disqus Comments Until You Click A Button

### ISSUE THREAD

**Issue by Cybo1927** [AdguardTeam/AdguardBrowserExtension#1523]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Problem Description

In uBlock origin adding 
`||disqus.com/forums/*/embed.js$script,redirect=disqus.com/forums/*/embed.js
||disqus.com/embed.js$script,redirect=disqus.com/embed.js
||disqus.com/count.js$script
@@||disqus.com/embed.js?_=1457540*$script`
would make it block Disqus on page load but there is a button you can click to unblock it. Currently, in AdGuard it doesn't do anything (the comment section loads with the page)

### Proposed Solution

Look here for information:
https://gist.github.com/gorhill/ef1b62d606473c68d524#file-gistfile1-txt

### Additional Information

Tested on:
https://ubuntu-mate.org/blog/ubuntu-mate-yakkety-beta1/

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/Scriptlets #53](https://github.com/AdguardTeam/Scriptlets/issues/53) via [**ZenHub**](https://www.zenhub.com/)
