### ISSUE TITLE
Reqiest: set exact rules for website ?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [AdguardTeam/AdguardBrowserExtension#1524]
Meaning:
Disable all normal filters, and let me manually choose what to block?
All this, while remembering the rules for this website.

The reason is that some websites try to detect the blocking (example [here](https://www.dailymail.co.uk/sciencetech/article-7653269/Google-expands-crowdsourced-public-transit-app-Pigeon-five-new-cities-US.html), which I've noticed that sadly I can't use Adguard, as others reported [here](https://forum.adguard.com/index.php?threads/dailymail-co-uk-is-blocking-adblockers-and-then-adguard.35492/)), so maybe they will not detect a partial set of the blocking.

**Comment by SoLenny** [comment]
@AndroidDeveloperLB Hello. You can use your own filters and rules and configure them the way you like on a particular site :)

**Comment by AndroidDeveloperLB** [comment]
@SoLenny No. I can't.
See attached video.
It won't let me till I re-enable ad-blocking.
There is no option in the middle. It's either all or nothing.
Why did you close this without letting me reply?

[2019-11-14_19-55-23.zip](https://github.com/AdguardTeam/AdguardBrowserExtension/files/3847904/2019-11-14_19-55-23.zip)

If you know of such an option, please show me how it's done, because currently the UI doesn't show such a thing. 
And if it does exist, please make the UI a bit better to make it clear how it's done.

**Comment by ameshkov** [comment]
@AndroidDeveloperLB what you need is `$genericblock` and `$generichide` modifiers:
https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#generic-rules

So you add a rule like this to the user filter:
`@@||example.org^$generichide,genericblock`

And then start adding your own rules specifically for this website, smth like this:
```
||doubleclick.net^$domain=example.org
example.org###banner
```

**Comment by AndroidDeveloperLB** [comment]
@ameshkov I'm talking about having it on the UI when you choose the item to block. You don't have these options there.
Also, there is no option to do it per website for all the current filters (not just the rules that I make).
This makes it very hard to go un-detected by the websites. Usually I either choose to enable or disable the ad-blocker.
And sadly as opposed to what was told me I don't see any way to set my own rules alone on specific websites, and my request about this was closed:
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1524#event-2798321476
