### ISSUE TITLE
CSS rules with after/before are not visible in the filtering log

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/AdguardBrowserExtension#1526]
### Issue Details

- **AdGuard version:**
  - AdGuard v3.3.2
- **Browser and version:**
  - Chrome 78.0.3904.97

### Steps to reproduce
1. Add these rules to user filter:
`example.com#$#p::after { content: "Test"!important; color: red!important; }`
`example.com#$#p::before { content: "Test"!important; color: red!important; }`
2. Go here - http://example.com/

### Expected Behavior
CSS rules should be visible in the filtering log.

### Actual Behavior
CSS rules are not visible in the filtering log.

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29142494/68756852-357cce00-060b-11ea-96e2-15253632b63c.png)

</details>

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1148

**Comment by AdamWr** [comment]
Ok, it's duplicate.
