### ISSUE TITLE
Why don't attribute selectors trigger sometimes while class selectors do?

### ISSUE THREAD

**Issue by levonder** [AdguardTeam/AdguardBrowserExtension#1527]
Usecase: [udemy.com](udemy.com) (homepage logged out)

If I look at the page source, there's e.g. a div tagged with 'ud-app-loader' class at the top level under 'body' (usually at the bottom there).

The following selector works: 
```
udemy.com##.ud-app-loader
```
while this one doesn't:
```
udemy.com##[class="ud-app-loader"]
```

Why?
(I also tried `#?#` version, no changes.)

Thank you.

**Comment by maximtop** [comment]
because there is no such elements on the page which can be found by selector 
document.querySelector('[class="ud-app-loader"]')

this one should work
`document.querySelector('[class*="ud-app-loader"]')`
