### ISSUE TITLE
Content Blocker css-display-none rules aren't applied when you open a website first time

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#153]
Safari Version 10.0 (12602.1.50.0.10)
#### Steps to reproduce
1. Disable all ad filters in AG
2. Add rule `##body` (which should hide all webpages)
   
   This rule is transformed to the following content blocker rule:
   
```
[
    {
        "trigger": {
            "url-filter": ".*",
            "resource-type": ["document"]
        },
        "action": {
            "type": "css-display-none",
            "selector": "body"
        }
    }
]
```

3. Open a new tab
4. Enter "google.com" into the address bar and press Enter
#### Expected result

Page is empty
#### Actual result

Page is not empty. The rule will be applied after you refresh the page.

The old bug report (that was about Google search only):
https://bugs.webkit.org/show_bug.cgi?id=153743

The new bug report (as issue now exists for any website):
https://bugs.webkit.org/show_bug.cgi?id=162057

**Comment by srjallan** [comment]
I'm also seeing this on both Mac and iOS, but it only started a few days ago... On Mac in particular, I've been using the 2.1 betas since the first one and issues only started recently. Are you sure this is a WebKit bug?

**Comment by ameshkov** [comment]
@srjallan seems so as the bug is not present when you first navigate to google.com and then do the search.

**Comment by ameshkov** [comment]
I've just tried one more test.

1. Added ```google.com##.content``` to user filter. This rule hides all google search results.
2. The rule works when I go to google.com first and enter any search query there.
3. But it does not work when I use the address bar

**Comment by ameshkov** [comment]
@srjallan seems that you are right in the end:)

The page layout is really different when you use the address bar.

Here is an address of that page:
https://www.google.com/search?client=safari&rls=en&q=iphone+6s+buy&ie=UTF-8&oe=UTF-8&gws_rd=cr,ssl&ei=gkyxVqTqIoGmsAHM_bLoBA

**Comment by ameshkov** [comment]
Huh, after getting some sleep:) and further testing I am now sure that the issue exists. The page layout is not so different and ads must be blocked by "css-display-none" rules.

New steps for reproducing the issue:
1. Disable all ad filters
2. Add one rule to the user filter: ```##body```
This rule hides the whole page.
3. Enter "https://www.google.com/" and press enter
4. The page is hidden (that's expected)
5. Now open new tab and enter "buy iphone 6s" in the address bar and press "Enter"

**Expected result:**
Whole page is hidden

**In fact:**
Page is not hidden.
It is not hidden even when you refresh the page.

**Comment by ameshkov** [comment]
Ok, here's more about it.

The bug is reproducible only if content blocker's trigger has `resource-type` field.
Removing this field fixes the issue.

That's weird, but I guess we can now close this issue on our side.

**Comment by ameshkov** [comment]
Reported update information to Safari devs:
https://bugs.webkit.org/show_bug.cgi?id=162057
