### ISSUE TITLE
vev.io now requires Adblocker disabled to run

### ISSUE THREAD

**Issue by ngdaniel1** [AdguardTeam/AdguardBrowserExtension#1530]
[https://vev.io/78r8pm165734](url)  This link is the 50th episode of Sesame Street and I'm trying to watch it before allowing kids at home to watch it.

I'm trying to view this video episode but it only runs when Adguard is disabled. 

With Adguard enabled, the message says, " Something is wrong! please try disabling any adblocking software you are using and refreshing the page."

Please assist.

**Comment by Alex-302** [comment]
Please send report using AdGuard
<details><summary>Screenshot:</summary> 

![image](https://user-images.githubusercontent.com/8361299/69133703-03fa7b80-0abf-11ea-9913-4b9d86ce4032.png)

 </details>
