### ISSUE TITLE
Adguard vs Pinterest.

### ISSUE THREAD

**Issue by Light-on** [AdguardTeam/AdguardBrowserExtension#1532]
Здравствуйте. Проблема наблюдается около месяца или дольше и, по всей видимости, берёт начало с момента обновления расширения, когда я увидела в браузере соответствующее уведомление от Adguard. Есть сайт: www.pinterest.com. Там немало рекламы среди "пинов" в новостной ленте, поэтому блокировщик необходим, но он действует на сайт страшным образом. Новостная лента представляет собой сплошной набор изображений, статичных и анимированных, а также автовоспроизводимых беззвучных видео. Листая страницу вниз, в какой-то момент одно из изображений множится, замещая собой все последующие, при этом оно отображается в сломанном виде, вертикально растянутое и размытое. Далее фон страницы меняется с белого на чёрный и внутри рамки окна браузера происходит хаос из фрагментов изображений, панели закладок и прочего, кнопки Свернуть-Развернуть-Закрыть окно оказываются внутри этого хаоса, ни одно действие в браузере не доступно, браузер закрывается аварийно из панели задач на рабочем столе. Отключаю Adguard - полно рекламы и проблема не повторяется. Изучите, пожалуйста, происходящее.

Браузер Google Chrome актуальной версии, Windows 7.

**Comment by SoLenny** [comment]
@Light-on Здравствуйте, не могли бы вы попробовать воспроизвести это снова и записать на видео?
Так же, уточните, пожалуйста, какие фильтры у вас включены и какие еще расширения вы используете?
К сожалению, на последней версии AdGuard из chrome-webstore данный баг у меня не воспроизводится.

**Comment by Light-on** [comment]
@SoLenny Я бы записала, но вся система очень тормозит, я еле-еле контролирую курсор, чтобы попасть на панель задач и закрыть браузер. Каждый раз боюсь какого-нибудь критического зависания.
Мои фильтры: базовый, фильтр счётчиков и системы аналитики, фильтр полезной рекламы, немецкий, русский, французский, EasyList Italy, Dandelion Sprout's Nordic Filters.
Ого. В прошлой версии Adguard у меня было добавлено несколько фильтров, но в работе было всего два или три, помимо основных, отмеченных галочкой. Этот набор сам появился, а я не смотрела, просто не вносила никаких изменений в настройки. Нужно, наверное, оставить базовый и фильтр счётчиков и системы аналитики? Не помню, работал ли раньше фильтр полезной рекламы. Остальные наверняка лишние. 
Ещё есть несколько правил в пользовательском фильтре для соцсети, нежелательные блоки.
Режим интеграции включён, я не знаю, о чём это.
Надо ещё сказать, что ситуация с Pinterest случается нерегулярно, не каждый раз. Также замечено, что показ рекламы на сайте нерегулярен, иной раз частая, а потом обновляю страницу и почти не попадается. И ещё один момент, экран изредка мигает при загрузке страницы и при дозагрузке, когда листаю вниз. Мигает один раз, притормаживая всё на пару секунд.

**Comment by Light-on** [comment]
Получилось сделать скриншоты. Вот так выглядит сущий кошмар.
![adg-smth3 info](https://user-images.githubusercontent.com/35206151/69290933-9b241800-0c12-11ea-86c1-f7c8140a4f08.png)
![adg-smth2 info](https://user-images.githubusercontent.com/35206151/69290934-9b241800-0c12-11ea-89cf-8404f0f19d8e.png)
![adg-smth1 info](https://user-images.githubusercontent.com/35206151/69290935-9b241800-0c12-11ea-909c-e48edd451418.png)

**Comment by Light-on** [comment]
Снято после того, как я отключила все языковые фильтры.

**Comment by SoLenny** [comment]
@Light-on Подскажите, пожалуйста, а вы пробовали выключить фильтры или полностью выключить AdGuard? 
Такое случается именно когда он включен?
Или может проблема не совсем в AdGuard?

**Comment by Light-on** [comment]
@SoLenny Достаточно было отключить фильтрацию на Pinterest, чтобы проблема перестала повторяться. Я пишу сюда в последнюю очередь, когда передумала обо всём и убедилась, что без Adguard сайт не ломается вместе с Хромом.

**Comment by Light-on** [comment]
Не исключено, что в проблеме участвует ещё какой-то недофикс со стороны того же Хрома или кто его знает, что ещё. Но на данный момент я нахожу причину в Adguard. Очень бы хотелось самой понять, как вообще возможен такой ужас в окне браузера и какие процессы, файлы могут так воздействовать на Хром в момент просмотра сайта.

**Comment by Alex-302** [comment]
@Light-on можете проверить с включенной фильтрацией, но выключенными фильтрами? Если не поможет - отключите Антитрекинг. Это всё находится в настройках.
Если отключение фильтров поможет, включайте обратно по одному с проверкой. Если найдёте фильтр, после которого сайт ломается, сообщите нам.

**Comment by Light-on** [comment]
@Alex-302 Антитрекинг всегда отключён. При попытке отключить фильтры обнаружилось, что никак не остановить работу русского фильтра, автоматически возобновляет фильтрацию на сайте, несмотря на снятую галочку. Убрала автоматическое подключение подходящих фильтров, помогло. Сразу заметила, что без русского фильтра сайт быстрее загружается. Прослежу дальше. Насчёт русского фильтра мне вспомнились обсуждения на форуме Adguard, если я правильно помню, с русским фильтром и раньше были какие-то неприятности и его приходилось держать выключенным.

**Comment by Light-on** [comment]
Без русского фильтра пропускает рекламу в соцсети.

**Comment by Alex-302** [comment]
Для этого сайта в русском фильтре нет правил.
Если выключить русский, проблема повторяется?

**Comment by Light-on** [comment]
Сегодня новый фокус. При включённом Adguard и работающем русском фильтре опять размножилось сломанное изображение и стала чёрной полоса прокрутки, вслед за этим экран замер на пару секунд, мигнул, и сайт вернулся в нормальное состояние. Обновляю ленту, открываю пины - пока без происшествий. Слежу.

**Comment by SoLenny** [comment]
@Light-on На данный момент я закрываю задачу, так как у нас не получилось воспроизвести этот баг, а у Вас, я надеюсь он тоже перестал воспроизводиться, если вдруг у вас снова возникнут проблемы с Pinterest, обязательно откройте эту задачу снова и мы постараемся решить ее :)
