### ISSUE TITLE
Multiple Technical Issues : YT + "Google" account ban if avoiding advertising ...

### ISSUE THREAD

**Issue by aspadistra** [AdguardTeam/AdguardBrowserExtension#1533]
### I don't myself for certain "know absolutely" what this means, but probably it means a complex set of countermeasures before JAN 2020. 

-- Google AKA Alphabet really ceased years ago being a provider of purely technical services, as its AD AGENCY ASPECT has beyond totally overpowered nearly all aspects of its operations that are technical (ALBEIT SLOWLY).  

-- Alphabet aka Google is not as BEYOND TOTALLY CORRUPT as say Twitter or Pinterest or Reddit or Facebook ... yet it is all too probable it has escaped EU + AUS + NZL + CAN + MEX + India access ban is due to the bribing of government officials by hiring their relatives ... that in the USA is somehow not considered corruption (or as in ZA "State Capture") at all ...

**Multiple Technical Issues : YouTube ban your account if you avoid advertising ...**

-- [https://www.funzen.net/2019/11/13/youtube-ban-your-account-if-you-avoid-advertising/](url)

Recently you may have received a notification on your YouTube account when watching videos, or an email, which indicates that the world's most popular online video platform has changed its terms and conditions of service. 

This notice has been received by all users who use this platform.

YouTube has substantively changed its policies. 
These policies will be effective as of December 2019. 

There are some points within these changes that have not left the community happy at all.

[...]

One of the most controversial changes, when the new terms and conditions were announced, is that YouTube may ban the accounts of users who use some type of advertising blocker. 

In other words, if you use Adblock or some type of app or extension to not see the advertising that appears on YouTube, well Your account may be banned forever.

The specific point that mentions this says the following: YouTube may cancel your access or access your Google account to the Service in part or in whole if it reasonably determines that providing the Service is no longer commercially viable.

This makes it very clear that not only can they ban you from YouTube, they can also unsubscribe your Gmail account, Adsense, Adwords and all services related to the Google world.

When is it no longer commercially viable for Google?

Unfortunately, we have not found any information related to this topic within the new Terms and Conditions. 

Some content creators, YouTubers, have said that they will ask Google to explain specifically what it means when they mention the phrase commercially viable. 

So far no Alphabet aka Google company manager has clarified this issue.

From here, we recommend you disable any extension or application that blocks advertising on YouTube, because you could run the risk of permanent banning. 

Remember that you can add exceptions so that the app or extension does not work on certain websites. For what it is not necessary uninstall said tool to not be banned by Google.

**Comment by SoLenny** [comment]
@ameshkov Have a look, please.

**Comment by ameshkov** [comment]
Google has already confirmed that this is not about ad blocking, don't worry
