### ISSUE TITLE
Support for const in Global scope

### ISSUE THREAD

**Issue by oleedd** [AdguardTeam/AdguardBrowserExtension#1538]
It is the shortest way to break an ad script by creating a const variable in Global scope.
But AdGuard creates them in Local scope.
So it would be very cool to execute the only string in Global scope. Maybe with some modifier like `#%?#`.
`example.com#%#const AD=null`

**Comment by ameshkov** [comment]
Well, I'd suggest using the `set-constant` scriptlet instead as we're anyway going to deprecate the JS rules (outside of the user filter): https://github.com/AdguardTeam/Scriptlets#set-constant

Alternatively, you can do this:
```
#%#Object.defineProperty(window, 'AD', { get: function() { return null; } });
```

**Comment by oleedd** [comment]
But it is **much shorter way**. The size of filters is important.
Changing constants will cause an error. But Object.defineProperty — not.
>we're anyway going to deprecate the JS rules

Why?

**Comment by ameshkov** [comment]
> Why?

They can be dangerous in the wrong hands.

We already limit them to the user filter and AdGuard official filter lists only (or to custom filter lists where the user has explicitly op in).

**Comment by oleedd** [comment]
>we're anyway going to deprecate the JS rules (outside of the user filter)

Why wrong hands? Your filters devs are very conscious and careful.

**Comment by ameshkov** [comment]
@oleedd yeah, well, I have nothing against our filters devs:) I am talking about third-party filter lists -- they can go rogue for instance. That's why we restrict JS rules to user/custom rules only.

**Comment by oleedd** [comment]
But why JS rules will stop to work in own AdGuard filters? Or they will not stop?

**Comment by oleedd** [comment]
But why JS rules will stop to work in own AdGuard filters? Or they will not stop?

**Comment by oleedd** [comment]
But why JS rules will stop to work in own AdGuard filters? Or they will not stop?

**Comment by oleedd** [comment]
@ameshkov
Please answer. I don't wont to open a new issue with this question.

**Comment by oleedd** [comment]
@ameshkov
Please answer. I don't want to open a new issue with this question.

**Comment by ameshkov** [comment]
@oleedd we're going to replace them all with scriptlets.

This cannot be done quickly, but we're slowly getting rid of them.

**Comment by oleedd** [comment]
I don't think that scriptlets can satisfy all needs of js rules. There may be rare cases where something special is needed.
