### ISSUE TITLE
[Chromium] Detect SW Iron & Vivaldi browsers (Chromium cores but execution environments <> Chrome)

### ISSUE THREAD

**Issue by aspadistra** [AdguardTeam/AdguardBrowserExtension#154]
Detect SW Iron & Vivaldi browsers (Chromium cores but execution environments <> Chrome).

Both browsers get AdGuard via the Chrome Store area. 

However, there are differences in the execution environments of these Chromium branches that may arise (or do exist now) that may interfere with program operation. 

By detecting (and possibly invoking safe mode operations) with these browsers some alternate platform problems may be prevented.

**Comment by ameshkov** [comment]
Hm, is there any serious difference there? As I know, SW Iron provides exactly the same extensions API.

Not sure about Vivaldi though, the browser seems to be modified "deeper".

**Comment by aspadistra** [comment]
VIVALDI does not have the same LEFT MOUSE BUTTON behaviour.

One does not get the "Left Mouse Button Menu" at all ! 

If Vivaldi is detected, the "UPDATE FILTERS" could be dynamically added to the RIGHT BUTTON MOUSE MENU.

**Comment by ameshkov** [comment]
@Mizzick please take a look

**Comment by ameshkov** [comment]
@Mizzick the problem is described better in this issue:
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/154

**Comment by Mizzick** [comment]
The issue with Vivaldi is described here:
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/155
