### ISSUE TITLE
Ensure that AdGuard works properly on chromeOS

### ISSUE THREAD

**Issue by F3000** [AdguardTeam/AdguardBrowserExtension#1541]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

**Comment by SoLenny** [comment]
@F3000 Hello, could you describe your problem in more detail?

**Comment by SoLenny** [comment]
Due to the fact that we did not receive more detailed information from the user, at the moment I am closing the task. Please open it again if you have additional information.
