### ISSUE TITLE
fishki.net - high memory usage

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1545]
@adguard-bot commented on [Sat Nov 30 2019](https://github.com/AdguardTeam/AdguardFilters/issues/45172)

### Issue URL (Incorrect Blocking)
[https://fishki.net/1686322-blokirovanie-reklamy--jeto-zakonno-vykladyvaju-povtorno.html](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Ffishki.net%2F1686322-blokirovanie-reklamy--jeto-zakonno-vykladyvaju-povtorno.html)
### Comment
Username: @kotenok2000
> Memory usage is too big.

@kotenok2000 commented on Tue Dec 03 2019

Uploaded to google drive
https://drive.google.com/file/d/1j97czv-VLiY4PTlBhJZQyoKuupTR_bE8/view?usp=sharing

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/f1gwdVO.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/VN5EDrN.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | Ext
AdGuard version: | 3.3.4
Browser: | Chrome
Stealth mode options: | Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Strip URLs from tracking parameters, Block WebRTC, Hide your Referrer from third-parties
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances, <br/>Adblock Warning Removal List, <br/>I don't care about cookies<br/><br/><b>Security:</b><br/> Malware Domains Blocklist, <br/>Spam404<br/><br/><b>Language-specific:</b><br/> AdGuard Turkish, <br/>AdGuard French, <br/>AdGuard Russian, <br/>AdGuard German, <br/>AdGuard Japanese, <br/>AdGuard Dutch, <br/>AdGuard Spanish/Portuguese, <br/>ABPindo, <br/>EasyList China, <br/>EasyList Italy, <br/>Latvian List, <br/>Official Polish filters for AdBlock, uBlock Origin & AdGuard, <br/>Dandelion Sprout's Nordic Filters

---

@BlazDT commented on [Sun Dec 01 2019](https://github.com/AdguardTeam/AdguardFilters/issues/45172#issuecomment-560026566)

Not higher than usual on the site for me. What do you define as high?

@zloyden please check at your device

---

@zloyden commented on [Sun Dec 01 2019](https://github.com/AdguardTeam/AdguardFilters/issues/45172#issuecomment-560071032)

Not reproduced on my end. I have less memory usage on this site.
@Alex-302 please take a look.

---

@kotenok2000 commented on [Mon Dec 02 2019](https://github.com/AdguardTeam/AdguardFilters/issues/45172#issuecomment-560393870)

Memory usage gradually gets bigger with adguard.

---

@kotenok2000 commented on [Mon Dec 02 2019](https://github.com/AdguardTeam/AdguardFilters/issues/45172#issuecomment-560393923)

list of loaded extensions:
ahfgeienlihckogmohjhadlkjgocpleb : Интернет-магазин Chrome : version 0_2
ajhmfdgkijocedmfjonnpjfojldioehi : Privacy Pass : version 2_0_3
apdfllckaahabafndbhieahigkjlhalf : Диск Google : version 14_2
bdeifmcaonlafkglbdpbbhkeecjnkipo : Quick Tab : version 4_2
bgnkhhnnamicmpeenaelnjfhikgbkllg : AdGuard Антибаннер : version 3_3_4
bikbmgikikoblfpoledibfbicaoofkkm : Fit To Screen by TheY2T : version 2_0_0_0
blpcfgokakmgnkcojhhkbfbldkacnbeo : YouTube : version 4_2_8
dhdgffkkebhmkfjojejmpbldmpobfkfo : Tampermonkey : version 4_9
dnopbpmlkabcondfpckfnhgabfcncjmg : VirusTotal : version 2019_8_10_42620
eckljalfcmlblcidfmbjbcgdofcjekjm : Drawception : version 2019_8_22_47322
edacconmaakjimmfgnblocblbcdcpbko : Session Buddy : version 3_6_3
gdbofhhdmcladcmmfjolgndfkpobecpg : Don't track me Google : version 4_22
gfdkimpbcpahaombhbimeihdjnejgicl : Feedback : version 1_0
hcpidejphgpcgfnpiehkcckkkemgneif : Awesome Cookie Manager : version 1_0_0_2
hgmnkflcjcohihpdcniifjbafcdelhlm : Tabman Tabs Manager : version 0_12_4
hjoieblefckbooibpepigmacodalfndh : IPFS Companion (Beta @ f5f7660) : version 2_9_0_860
iaiomicjabeggjcfkbimgmglanimpnae : Tab Session Manager : version 5_1_1
jbdahlimgohfikaoinpdclkpciabakhf : Pinterest : version 2019_8_26_40927
jddpjgadbhnefiopiagpjbocgbhbjngc : Aperture Science Network Interface (Blue) : version 1
jgeocpdicgmkeemopbanhokmhcgcflmi : Twitter : version 2019_8_10_34474
jlipbpadkjcklpeiajndiijbeieicbdh : The Great Discarder : version 0_1_2
kmendfapggjehodndflmmgagdbamhnfd : CryptoTokenExtension : version 0_9_74
mfehgcgbbipciphmccgaenjidiccnmng : Cloud Print : version 0_1
mhjfbmdgcfjbbpaeojofohoefgiehjai : Chrome PDF Viewer : version 1
ncndcebmkibkhopclfdjfacgfholcghi : Google Images Restored : version 0_1_6
neajdppkdcdipfabeoofebfddakdcjhd : Google Network Speech : version 1_0
nkeimhogjdpnpccoofpliimaahmaaome : Google Hangouts : version 1_3_14
nmmhkkegccagdldgiimedpiccmgmieda : Платежная система Интернет-магазина Chrome : version 1_0_0_5
npgcnondjocldhldegnakemclmfkngch : Обход блокировок Рунета : version 0_0_1_38
phbbckhobdikmioopccocgpohmgegnki : Книга Фанфиков : version 2019_8_12_726
phmkjpaalnpngdifcgejpakhfleamlag : Reverse Playlist for YouTube™ (BETA) : version 0_2_0
pjkljhegncpnkpknbcohdijeoejaedia : Gmail : version 8_2
pkedcjkdefgpdelpbcmbmeomcjbeemfm : Chrome Media Router : version 7819_902_0_1

---

@Alex-302 commented on [Mon Dec 02 2019](https://github.com/AdguardTeam/AdguardFilters/issues/45172#issuecomment-560681775)

Also not reproduced. Could you, please, save `Heap snapshot` using dev toouls and upload archive to file hosting?(open the site in private tab and do not login)

---

@kotenok2000 commented on [Tue Dec 03 2019](https://github.com/AdguardTeam/AdguardFilters/issues/45172#issuecomment-561214883)

Uploaded to google drive 
https://drive.google.com/file/d/1j97czv-VLiY4PTlBhJZQyoKuupTR_bE8/view?usp=sharing

**Comment by kotenok2000** [comment]
I tried to copy filtering log
[Журнал.html.txt](https://github.com/AdguardTeam/AdguardBrowserExtension/files/3940932/html.txt)

**Comment by Alex-302** [comment]
@kotenok2000 а не проверяли, влияет ли отключение других расширений и фильтров?
