### ISSUE TITLE
Suggestions for filtering log

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1546]
- [ ] Add pause button - do not add new records and do not clear while navigation;
- [x] add content type filter like in ~Windows or MacOS app~ Chrome dev tools;
- [x] add time column (HH:MM:SS);
- [x] allow to adjust columns width and remember it;
- [ ] allow to move and minimize/hide columns;
- [ ] add separator when a tab was refreshed, if log saving is enabled;
- [ ] ~add a button to increase the height of the lines to display long URLs (for very long strings scrolling can be added). For example, 3-4 lines of text~;
- [x] make the log header fixed(visible when scrolling);
- [ ] make grid complete(vertical and horizontal);
- [ ] filtering by the content of certain/all columns (options can be showed by clicking on the icon of the enlarged glass);
- [x] clear search request button https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1564
- [ ] devide HTML type by sup-types(element hiding/CSS, Scriptlets/JS, cookies/header modifications, Replace/$$, stealth)

**Comment by XX-J** [comment]
Freeze Filtering Log Header While Scrolling Down #862
 Add color on blocked items to the Filtering Log #868
 [Filtering log] Translate some items. #1126
 [Filtering log] Sort columns, move separator. #1127
 Persist filtering log checkboxes state #1128
 Filtering log is empty if "Blocked" and "Whitelisted" checkboxes are checked #1314
 Filtering Log: add "filter" settings #1358
 Change display of a rule in `Filtering rule` column in filtering log #1496

 Open filtering log in the same mode as the tab from where it is opened #1495
 Persist filtering log size #1125
 Remember filtering log window position and size #1655

**Comment by Nzzyme** [comment]
Will these issues not be fixed??

**Comment by Alex-302** [comment]
@Nzzyme some will be implemented(updatet the first message).

**Comment by Alex-302** [comment]
@maximtop Any news?

**Comment by maximtop** [comment]
> @maximtop Any news?

The task is not a priority, since the MV3 filtering log might be reworked or operate in a limited mode.
