### ISSUE TITLE
[Chromium branch Vivaldi] Add "Update Filters" to Address Bar Menu after "Website Security Report"

### ISSUE THREAD

**Issue by aspadistra** [AdguardTeam/AdguardBrowserExtension#155]
[Chromium branches] 

Add "Update Filters" to Address Bar Menu after "Website Security Report" ... because having to go in and update the filters manually is a real pain because you cannot update them from this menu.

**Comment by ameshkov** [comment]
Right click on the AG icon and you'll see "check filter updates" there.

**Comment by aspadistra** [comment]
On one of the browsers (or more than one?) the version of AdGuard that run
![adguard_insert_update_filters](https://cloud.githubusercontent.com/assets/285496/12865040/cbdeda26-cc55-11e5-869f-30c2d54b3ba8.gif)

**Comment by aspadistra** [comment]
Oops! The wonky user interface and bad connection led to this being closed by accident.

**Comment by ameshkov** [comment]
That's how it looks like when you do the right click:
<img width="473" alt="2016-02-08_1313" src="https://cloud.githubusercontent.com/assets/5947035/12882925/d605782c-ce65-11e5-9fd0-91e22b24989a.png">

**Comment by aspadistra** [comment]
VIVALDI does not have the same LEFT MOUSE BUTTON behaviour.

One does not get the "Left Mouse Button Menu" at all !

If Vivaldi is detected, the "UPDATE FILTERS" could be dynamically added to the RIGHT BUTTON MOUSE MENU.

**Comment by Mizzick** [comment]
There is also "Check for filters updates" button on the settings page.

**Comment by ameshkov** [comment]
> There is also "Check for filters updates" button on the settings page.

It's just everybody want to have a shortcut for checking filter updates in two clicks.

Here is a key point:
> If Vivaldi is detected, the "UPDATE FILTERS" could be dynamically added to the RIGHT BUTTON MOUSE MENU.

**Comment by Mizzick** [comment]
I think we should wait for Vivaldi to release out of the beta.

**Comment by atropnikov** [comment]
There is "Check for filters updates" button in the context menu. I think it is enough.
