### ISSUE TITLE
Update localizations

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#1550]

**Comment by lancelot-moon** [comment]
@maximtop 

1. May you update the translations of AG Browser Extension **after the updates of filters' lists and descriptions are done**?
https://github.com/AdguardTeam/AdguardForAndroid/issues/3271

I guess that AG Browser Extension can't sync the latest filters' lists and descriptions/translations with AG server.

2. Please also update the translations of overview on Chrome web store, Firefox add-ons store, Edge store and Opera store.
https://chrome.google.com/webstore/detail/adguard-adblocker/bgnkhhnnamicmpeenaelnjfhikgbkllg?hl=zh-TW

https://addons.mozilla.org/zh-TW/firefox/addon/adguard-adblocker/

https://www.microsoft.com/zh-tw/p/adguard-adblocker/9mz607gwkbs7?activetab=pivot:overviewtab

https://addons.opera.com/zh-tw/extensions/details/adguard/

**Comment by lancelot-moon** [comment]
A missed phrase, "default", in General isn't translated.
It seems that you don't upload it to Crowdin.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/FBtIPe2.png)
</details><br/>
