### ISSUE TITLE
Default блокировка виджетов coinmarketcap.com, счетчиков метрики YA и Google

### ISSUE THREAD

**Issue by slavserver** [AdguardTeam/AdguardBrowserExtension#1551]
DEL...

**Comment by Alex-302** [comment]
@slavserver мало информации. Отправьте отчёт с помощью расширения
![image](https://user-images.githubusercontent.com/8361299/70704591-f8bff780-1cda-11ea-8676-21bd44f04680.png)
В этом случае все нужные параметры будут введены автоматически. Нужен только адрес страницы и скриншот.

**Comment by slavserver** [comment]
я администратор сайта  clona.ru . Думаю вам самим будет проще его посетить и посмотреть, 14 поддоменов + основной,  как не очень удобно по каждому кидать отчет. Спасибо

**Comment by slavserver** [comment]
![Снимок экрана от 2019-12-09 10-41-14](https://user-images.githubusercontent.com/20759703/70705748-aa642600-1ce5-11ea-878e-d27f13d77f9e.png)

**Comment by slavserver** [comment]
![Снимок экрана от 2019-12-12 13-44-59](https://user-images.githubusercontent.com/20759703/70705775-bd76f600-1ce5-11ea-8959-1b03d63955be.png)

**Comment by Alex-302** [comment]
> 14 поддоменов + основной

зачем все 14? Достаточно одного. Они же аналогичны.

**Comment by slavserver** [comment]
это вам решать, я просто добавил все для информирования... )))
еще раз спасибо
