### ISSUE TITLE
Increase max width of rules editor

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1553]
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/70735450-fbd8d900-1d16-11ea-807f-31e08fbd7108.png)

</details>

**Comment by XX-J** [comment]
Я - За! Но уже было: #1037 . Андрей тогда сказал:
> Очень сложно с текущей версткой.
