### ISSUE TITLE
Social media filter issue

### ISSUE THREAD

**Issue by PentagramTr** [AdguardTeam/AdguardBrowserExtension#1555]
- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:** 3.3.4
  
- **Browser and version:** Firefox 71.0 (64 bit)
  
- **Operating system and version:** Windows 10
  
- **Filters you use in AdGuard:** Base filter, Social filter,Tracking Protection,NoCoin,Turkish,Annoyances
 
- **Stealth Mode settings:** Enabled
 
 

### Actual Behavior

Social media filter is up to date but does not work on this page.
It works in Chrome.

http://gemlikbasinhaber.com/defne-yapragi/3213/

### Screenshots

Firefox

<details><summary>Screenshot:</summary>

![screenshot-gemlikbasinhaber com-2019 12 13-21_50_51](https://user-images.githubusercontent.com/34379403/70825738-349baf80-1df6-11ea-9ed1-b211bdda2068.png)

</details>

Chrome

<details><summary>Screenshot:</summary>

![gemlikbasinhaber (1)](https://user-images.githubusercontent.com/34379403/70825780-47ae7f80-1df6-11ea-965b-a83bd8ef382c.png)

</details>

---

**Filters**

Chrome
<details><summary>Screenshot:</summary>

![chrome sosyal](https://user-images.githubusercontent.com/34379403/70825987-d1f6e380-1df6-11ea-98ca-25199379fe60.png)

</details>

Firefox

<details><summary>Screenshot:</summary>

![firefox sosyal](https://user-images.githubusercontent.com/34379403/70825996-dd4a0f00-1df6-11ea-8f61-f5b494af92ca.png)

</details>

**Comment by Alex-302** [comment]
Please check for filters update. These buttons was hidden today.
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/70828015-2e580400-1df3-11ea-821d-c1b4fefa24ee.png)

</details>

**Comment by PentagramTr** [comment]
Still same.
Extension says "No updates found."
This looks like a bug.

<details><summary>Screenshot:</summary>

![ft](https://user-images.githubusercontent.com/34379403/70858415-e6c89980-1f12-11ea-9d6d-34b028222de0.png)


</details>

**Comment by ameshkov** [comment]
Yeah, looks like Firefox-specific bug

**Comment by PentagramTr** [comment]
There is another similar bug.

Filters updated at the same time. Filters are not in the latest version in Firefox.

<details><summary>Chrome:</summary>

![Chrome](https://user-images.githubusercontent.com/34379403/70879916-4341bc80-1fd8-11ea-8361-056252407b31.png)


</details>

<details><summary>Firefox:</summary>

![firefox](https://user-images.githubusercontent.com/34379403/70879937-4d63bb00-1fd8-11ea-8281-efa0649bb151.png)


</details>

**Comment by tvinzz** [comment]
@PentagramTr, do you still can detect this problem with latest AdGuard version (3.3.8)?

**Comment by PentagramTr** [comment]
@tvinzz 
No. I have not encountered this issue these days.

**Comment by zzebrum** [comment]
reopen if needed
