### ISSUE TITLE
Change conversion rules for `##^` rules -- add max-length="262144"

### ISSUE THREAD

**Issue by krystian3w** [AdguardTeam/AdguardBrowserExtension#1556]
### Prerequisites

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:** 
  -  3.3.4
- **Browser and version:** 
  -  Firefox 71.0
- **Operating system and version:**
  -  Windows 10 Pro 1909
- **Filters you use in AdGuard:** 
  -  N/A
- **Stealth Mode settings:** 
  -  Disabled
- **Other browser extensions:** 
  -  none

### Expected Behavior

Remove pop-up with GDPR/Cookies/Privacy Policy on:

`https://www.eobuwie.com.pl/`

### Actual Behavior

Filter no disable pop-up with GDPR/Cookies/Privacy Policy, so need use ExtendCSS syntax on:

`https://www.eobuwie.com.pl/`

### Screenshots

<details><summary>Screenshot:</summary>

![obraz](https://user-images.githubusercontent.com/35370833/71310949-92458280-241a-11ea-84fd-463270030955.png) |
--- |

</details>

### Additional Information

tested filter:

```
eobuwie.com.pl$$script[tag-content="technologii cookies"]
```

similar works in uBO 1.24.2 + Firefox 71:

`eobuwie.com.pl##^script:has-text(technologii cookies)`

<details><summary>Screenshot from uBO logger:</summary>

![obraz](https://user-images.githubusercontent.com/35370833/71311055-fa489880-241b-11ea-81a5-2548cf1bc7d6.png) |
--- |

</details>

**Comment by Alex-302** [comment]
It works 
![image](https://user-images.githubusercontent.com/8361299/71349997-f8481c00-2578-11ea-8a77-a253ad62cf51.png)

**Comment by AdamWr** [comment]
On my end it doesn't work with Firefox extension (works fine with app, but I think it shouldn't).

I guess that this rule doesn't work, because [by default ](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#default-setting) `max-length` is set to 8192 characters, but in this case this script has about 17000 characters.

This rule works:
`eobuwie.com.pl$$script[tag-content="technologii cookies"][max-length="20000"]`

**Comment by ameshkov** [comment]
`max-length` was set to 8KB looong time ago so that's okay

The question is what should we do with the automatic rules conversion? uBO, for instance, does not care about script sizes.

When doing the automatic conversion, we could set it to something big, like 64KB for instance.

**Comment by krystian3w** [comment]
> does not care about script sizes

only added `[min-length="..."]`:

https://github.com/gorhill/uBlock/wiki/Procedural-cosmetic-filters#subjectmin-text-lengthn

**Comment by krystian3w** [comment]
`homedesign.pl$$.popmake-overlay[data-popmake*="rodo"]`

why this no works on first visit? Also glitch with lenght in `<div>`?

**Comment by ameshkov** [comment]
sould be changed to:
```
homedesign.pl$$div[class="popmake-overlay"][data-popmake="rodo"]
```

**Comment by krystian3w** [comment]
no match:

```
data-popmake="{&quot;id&quot;:1567,&quot;slug&quot;:&quot;rodo&quot;,&quot;theme_id&quot;:1561,&quot;cookies&quot;:[{&quot;event&quot;:&quot;on_popup_close&quot;,&quot;settings&quot;:{&quot;name&quot;:&quot;pum-1567&quot;,&quot;key&quot;:&quot;&quot;,&quot;session&quot;:false,&quot;time&quot;:&quot;1 month&quot;,&quot;path&quot;:true}},{&quot;event&quot;:&quot;on_popup_open&quot;,&quot;settings&quot;:{&quot;name&quot;:&quot;pum-1567&quot;,&quot;key&quot;:&quot;&quot;,&quot;session&quot;:true,&quot;time&quot;:&quot;1 month&quot;,&quot;path&quot;:true}}],&quot;triggers&quot;:[{&quot;type&quot;:&quot;click_open&quot;,&quot;settings&quot;:{&quot;cookie_name&quot;:[&quot;pum-1567&quot;],&quot;extra_selectors&quot;:&quot;&quot;}},{&quot;type&quot;:&quot;auto_open&quot;,&quot;settings&quot;:{&quot;cookie_name&quot;:[&quot;pum-1567&quot;],&quot;delay&quot;:&quot;500&quot;}}],&quot;mobile_disabled&quot;:null,&quot;tablet_disabled&quot;:null,&quot;meta&quot;:{&quot;display&quot;:{&quot;stackable&quot;:false,&quot;overlay_disabled&quot;:false,&quot;scrollable_content&quot;:false,&quot;disable_reposition&quot;:false,&quot;size&quot;:&quot;medium&quot;,&quot;responsive_min_width&quot;:&quot;0%&quot;,&quot;responsive_min_width_unit&quot;:false,&quot;responsive_max_width&quot;:&quot;80%&quot;,&quot;responsive_max_width_unit&quot;:false,&quot;custom_width&quot;:&quot;640px&quot;,&quot;custom_width_unit&quot;:false,&quot;custom_height&quot;:&quot;380px&quot;,&quot;custom_height_unit&quot;:false,&quot;custom_height_auto&quot;:false,&quot;location&quot;:&quot;center top&quot;,&quot;position_from_trigger&quot;:false,&quot;position_top&quot;:&quot;100&quot;,&quot;position_left&quot;:&quot;0&quot;,&quot;position_bottom&quot;:&quot;0&quot;,&quot;position_right&quot;:&quot;0&quot;,&quot;position_fixed&quot;:false,&quot;animation_type&quot;:&quot;fade&quot;,&quot;animation_speed&quot;:&quot;350&quot;,&quot;animation_origin&quot;:&quot;center top&quot;,&quot;overlay_zindex&quot;:false,&quot;zindex&quot;:&quot;1999999999&quot;},&quot;close&quot;:{&quot;text&quot;:&quot;Zgadzam si\u0119 z polityk\u0105 prywatno\u015bci | RODO&quot;,&quot;button_delay&quot;:&quot;0&quot;,&quot;overlay_click&quot;:&quot;1&quot;,&quot;esc_press&quot;:&quot;1&quot;,&quot;f4_press&quot;:&quot;1&quot;},&quot;click_open&quot;:[]}}" 
```
