### ISSUE TITLE
AdGuard browser extension breaks WebSockets

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardBrowserExtension#1557]
### Issue Details

- **AdGuard version:**
  - Ext 3.3.4
- **Browser and version:**
  - Yandex 19.12.0.358
- **Operating system and version:**
  - Presumably Windows 10
- **Filters you use in AdGuard:**
  - Base, RU
- **Stealth Mode settings:**
  - None
- **Other browser extensions:**
  - Unspecified

### Actual Behavior

When extension is enabled, WebSockets connection constantly times out. Creating a `@@||domain^$websocket` rule does not help.

HAR file available as a ticket attachment. Both client and server use ASP.NET Core SignalR.

Known remediation methods: Completely disable the extension and reload browser.

### Screenshots & HAR

Taken in production environment and might not be available for general public. Available in helpdesk ticket 2445735.

**Comment by ameshkov** [comment]
Is this problem specific to Yandex browser or it can be reproduced somewhere else?

**Comment by vladikKBR85** [comment]
Not sure, but this [https://chrome.google.com/webstore/detail/adguard-adblocker/bgnkhhnnamicmpeenaelnjfhikgbkllg](https://chrome.google.com/webstore/detail/adguard-adblocker/bgnkhhnnamicmpeenaelnjfhikgbkllg) extension seem not to cause any troubles

**Comment by zzebrum** [comment]
reopen if needed
