### ISSUE TITLE
Holiday Update Brakes Edge/Edgeium Browser!!!

### ISSUE THREAD

**Issue by thejester77** [AdguardTeam/AdguardBrowserExtension#1558]
### Prerequisites

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

Latest update Version 3.3.6 broke Edge/Edgeium ablity to load any/all websites. Browser can't reach website and just hangs until page times out.

- **AdGuard version:**

Version 3.3.6

### Expected Behavior

Before Version 3.3.6, everything worked perfectly. Pages loaded properly, didn't hang waiting for a response from websites.

### Actual Behavior

Latest update Version 3.3.6 breaks Edge/Edgeium Browser... Pages will not load at all, and just hang waiting for a response from website.

No matter how many settings/switches a user turns off/on, the only way to get functionality back to Edge/Edgeium browser is to PAUSE/STOP AdGuard Extension from running.

By doing this, all functionality comes back to Edge/Edgeium browser.

After looking at the updates for Version 3.3.6, I have a suspicion that LOCALAZATION code update might be the problem.

Everything worked fine until you pushed the update at 12:30am (12-24-19).

**Comment by SoLenny** [comment]
@thejester77 Hello, please specify the localization that you use and with which version of the extension you updated? First of all, try removing the AdGuard extension and installing it cleanly.

**Comment by v3nc3s** [comment]
I have the same with ver. 3.3.6 installed from Microsoft Store. Filters are up to date with default settings.
Microsoft Edge Dev version 80.0.361.9 x64.
Both are in Polish Language.
Reinstalling the extension does not fix the problem.

**Comment by ameshkov** [comment]
Have you installed it from the Chrome WebSstore?

**Comment by ameshkov** [comment]
Could you please tell me what filter lists are enabled?

**Comment by ameshkov** [comment]
> After looking at the updates for Version 3.3.6, I have a suspicion that LOCALAZATION code update might be the problem.

Yeah, I see, most likely you are right

**Comment by ameshkov** [comment]
What's weird is that I cannot reproduce this issue with the version of AdGuard from Chrome WebStore. What's even weirder -- we uploaded **the very same build** to Microsoft Store.

**Comment by ameshkov** [comment]
Okay, I think I found the issue.

Make sure that "Send statistics of ad filters usage" is disabled in AdGuard Miscellaneous settings.
It seems to be incompatible with Edgium.

**Comment by ameshkov** [comment]
I've published the hotfix to Microsoft Store. It may take a couple of days to be reviewed and published.

Meanwhile, the quick solution would be to disable "Send ad filters usage stats" option in AdGuard Miscellaneous settings.
