### ISSUE TITLE
Правило не работает в Firefox, но работает в Chrome

### ISSUE THREAD

**Issue by a-ladanov** [AdguardTeam/AdguardBrowserExtension#1562]
В пользовательском фильтре есть правило
`e.mail.ru#%#//scriptlet("ubo-set-constant.js", "Object.prototype.mimic", "undefined"))`
В Chrome оно появляется в журнале фильтрации и работает.
В Firefox отсутствует в журнале.
Пока наблюдал за поведением, заметил, что Firefox, кажется, вообще не принимает скриплеты.
Adguard 3.3.6
Firefox 71
Chrome 79.0.3945.88
Windows 7 x64

**Comment by ameshkov** [comment]
Посмотрим, спасибо

**Comment by ameshkov** [comment]
Странно, вроде бы все работает

![image](https://user-images.githubusercontent.com/5947035/71473364-bcff5480-27e7-11ea-8e8d-4063e5c050b0.png)

**Comment by a-ladanov** [comment]
Хм... попробовал переустановить, но все равно Firefox не хочет использовать правило.
Вот скрины. Там у Firefox есть какие-то "измененные правила". Это что? В Chrome такого нет.
![firefox](https://user-images.githubusercontent.com/18179397/71477136-285a1e00-280a-11ea-8a0a-a6ea474d8fc8.png)
![firefox2](https://user-images.githubusercontent.com/18179397/71477139-2c863b80-280a-11ea-8424-7f6c1aa3de8c.png)
![chrome](https://user-images.githubusercontent.com/18179397/71477140-2e4fff00-280a-11ea-89a3-690155efb979.png)

**Comment by maximtop** [comment]
Попробуйте все правила отключить и оставить только скриплетное, чтобы глянуть отрабатывает оно или нет.

**Comment by a-ladanov** [comment]
Ух ты, когда только один пользовательский фильтр включен, правило работает. А что это значит?

**Comment by ameshkov** [comment]
Ну видимо какой-то из фильтров мешает, понять бы какой

**Comment by a-ladanov** [comment]
Мешает Русский фильтр. Страница еще только начинает загружаться, а уже в журнале появляется "измененное правило"

**Comment by ameshkov** [comment]
@maximtop может HTTPS filtering как-то мешает скриптлетам? Оч странно

**Comment by maximtop** [comment]
@a-ladanov мы удалили контентное правило, которое мешает работе скриплетов. Оно оказалось старым. 

```
e.mail.ru$replace=/(if\(init\)\s*{\n\t*init\(\\$\,\s*\[\n\t*")[A-Za-z0-9#\,-_\s*"]+(".split)/\$1#not_today\$2/,~script,~other,~xmlhttprequest,important
```

А почему контентные правила мешают фильтрам я буду разбираться после нового года.

Измененные правила - это ошибка в тексте, на самом деле эти правила изменяют контент страницы и лучше наверное подойдет Изменяющие правила - Modifying rules.

**Comment by a-ladanov** [comment]
Обновил фильтры, и все равно adguard для firefox не применяет скриптлеты из пользовательского, пока не отключу русский фильтр. Что-то еще ломает функционал.
В русском есть еще один скриптлет для e.mail.ru, но он не мешает - проверил, добавив его в пользовательский.

**Comment by maximtop** [comment]
да, похоже, что еще вот это правило мешает `@@||e.mail.ru^$generichide,jsinject`, но не должно

**Comment by a-ladanov** [comment]
А как его отключить? Что добавить в пользовательский, чтобы отменить его действие? Хочется проверить.

**Comment by maximtop** [comment]
можно в user filter добавить 
`@@||e.mail.ru^$generichide,jsinject,badfilter`

**Comment by Alex-302** [comment]
Удалил устаревшие правила
<details>

```
!+ NOT_PLATFORM(windows,mac,android)
@@||ad.mail.ru/adp/$domain=e.mail.ru
!+ PLATFORM(ext_opera, ext_ff)
@@||e.mail.ru^$generichide,jsinject
!+ NOT_PLATFORM(windows, mac, android)
@@||e.mail.ru^$generichide
```

</details>

**Comment by a-ladanov** [comment]
Да, вы правы. Именно это правило влияет.
Кстати также попробовал добавить правило
`@@||e.mail.ru^$generichide,jsinject`
в Chrome - посмотреть, влияет ли оно (в фильтре я так понял ограничение по браузерам из-за метки ext_opera, ext_ff), но в Chrome все скриплеты работали для e.mail.ru, несмотря на правило.

**Comment by ameshkov** [comment]
> да, похоже, что еще вот это правило мешает @@||e.mail.ru^$generichide,jsinject, но не должно

@maximtop почему не должно-то, `jsinject` должен скриптлеты отключать.

**Comment by maximtop** [comment]
@ameshkov https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#jsinject из описания тут не очень понятно
может добавить инфу, что и скриплеты, которые инжектятся расширением или приложением, тоже должны отключаться?
