### ISSUE TITLE
Кнопка для удаления поискового запроса в журнале фильтрации

### ISSUE THREAD

**Issue by a-ladanov** [AdguardTeam/AdguardBrowserExtension#1564]
Пожалуйста, рассмотрите вариант добавления кнопки для быстрого удаления поискового запроса в журнале фильтрации (что-то вроде крестика)

![remove](https://user-images.githubusercontent.com/18179397/71518305-04fba580-28d4-11ea-93ef-8543e94ac8e3.png)

**Comment by a-ladanov** [comment]
Частично пересекается с https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1546
Так что возможно дубль.

**Comment by ameshkov** [comment]
Да, дубль все-таки. Я упомяну ее там отдельно
