### ISSUE TITLE
Adguard Integration-ONLY version?

### ISSUE THREAD

**Issue by ImportTaste** [AdguardTeam/AdguardBrowserExtension#1565]
There have been times where the extension has been doing things outside of integrating with Adguard for Windows. Sometimes it has been the extension's fault, other times it was my fault because I turned off Adguard to test something and forgot about the extension.

I would really like a stripped down version of the extension that featured the integration and nothing else, even if it were only available from a source outside of the Chrome Store.

**Comment by ImportTaste** [comment]
Eh, nevermind.

**Comment by ameshkov** [comment]
Well, I know it's too late, but there will be a separate "assistant" extension soon.
