### ISSUE TITLE
Browser Extension for Maxthon

### ISSUE THREAD

**Issue by DrRazon** [AdguardTeam/AdguardBrowserExtension#1566]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

**Comment by ameshkov** [comment]
We actually researched that some time ago -- Maxthon simply does not provide enough capabilities for an ad blocking browser extension.
