### ISSUE TITLE
Content restrictor $script is Malfunctioning

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardBrowserExtension#1568]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:** 3.3.6

- **Browser and version:** FireFox v53.0.3 | Google Chrome v75

- **Operating system and version:** Windows 7 SP1 x64

- **Filters you use in AdGuard:**

 Базовый фильтр AdGuard | Русский фильтр | Фильтр раздражителей | Фильтр виджетов социальных сетей | Фильтр счетчиков и систем аналитики

- **Stealth Mode settings:**

 Всё, кроме "Самоуничтожение основных файлов cookies (не рекомендуется)"

- **Other browser extensions:**

 В Google Chrome v75 никаких расширений, кроме AdGuard v3.3.6 и единственного пользовательского правила `complaneta.com$script` - нет. FireFox не настолько чист, но, я думаю, это не влияет на результат.

### Expected Behavior

 Ограничитель `$script` должен блокировать все файлы скриптов, подгружаемые на указанном домене, и свои и внешние. С указателем `~third-party` - только свои, с `third-party` - только внешние.

### Actual Behavior

 Ограничитель `$script` в FireFox v53.0.3 и Google Chrome v75 блокирует только свои скрипты - не правильно, нужно все.

<details><summary>Screenshot:</summary>

![2020 01 02-3](https://user-images.githubusercontent.com/17948007/71700159-12cd9100-2dd4-11ea-8c47-418b49d184cc.png)
----------
![2020 01 02-6](https://user-images.githubusercontent.com/17948007/71700164-1eb95300-2dd4-11ea-8613-5c79276d32a1.png)
</details><br/>

 Ограничитель `$script,~third-party` в FireFox v53.0.3 и Google Chrome v75 блокирует только свои скрипты - правильно.

<details><summary>Screenshot:</summary>

![2020 01 02-2](https://user-images.githubusercontent.com/17948007/71700247-6a6bfc80-2dd4-11ea-8155-6da4e99360f8.png)
----------
![2020 01 02-5](https://user-images.githubusercontent.com/17948007/71700257-75bf2800-2dd4-11ea-8fb7-a9f6091f70b1.png)
</details><br/>

 Ограничитель `$script,third-party` в FireFox v53.0.3 не блокирует ничего - не правильно.

<details><summary>Screenshot:</summary>

![2020 01 02-1](https://user-images.githubusercontent.com/17948007/71700309-af902e80-2dd4-11ea-8a24-d1d2cb970c3d.png)
</details>

 А в Google Chrome v75 `$script,third-party` блокирует только свои скрипты, игнорируя указатель `third-party` - не правильно.

<details><summary>Screenshot:</summary>

![2020 01 02-4](https://user-images.githubusercontent.com/17948007/71700317-b9199680-2dd4-11ea-85bc-6ecd82bbbc27.png)
</details>

### Additional Information

 Пример привёл со страницы: [https://complaneta.com/chistyashchee-sredstvo-1l-cs-isoclene1-cactus-cs-isoclene1.html](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://complaneta.com/chistyashchee-sredstvo-1l-cs-isoclene1-cactus-cs-isoclene1.html)

**Comment by ameshkov** [comment]
А можете точные правила привести которые тестировались, а то я не до конца понимаю проблемы.

И еще обратите внимание, что правила вида `$script,third-party` игнорируются -- во избежание ложноположительных мы не даем блокировать "ВООБЩЕ ВСЕ" если нет ограничителя на конкретный домен (типа `$script,third-party,domain=example.org`).

**Comment by XX-J** [comment]
Я хотел, ради проверки, заблокировать ВСЕ ВНЕШНИЕ скрипты на сайте [https://complaneta.com](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://complaneta.com/chistyashchee-sredstvo-1l-cs-isoclene1-cactus-cs-isoclene1.html) правилом `complaneta.com$script,third-party`, но, как написал выше, - не получилось.

**Comment by ameshkov** [comment]
А надо вот так было:
`$script,third-party,domain=complaneta.com`

**Comment by XX-J** [comment]
По моему так `complaneta.com$script,third-party` выглядит более наглядно и правильно. Тем более, что так `complaneta.com$script,~third-party` - работает, а так  `complaneta.com$script` - наполовину...
 Может пересмотреть логику работы `$script` или дописать её?

**Comment by Alex-302** [comment]
> `complaneta.com$script,third-party` выглядит более наглядно и правильно

нет же. `адрес_запросов$тип,~где`

`complaneta.com$script,~third-party` - оно блокирует скрипты complaneta.com, но не загруженные со стороны, т.е. только на самом complaneta.com

**Comment by XX-J** [comment]
`complaneta.com$script,~third-party` - я и говорю, что работает так, как написано, т.е. ПОНЯТНО - действие соответствует визуальному восприятию, а `complaneta.com$script,third-party` и `complaneta.com$script` - действие не соответствуют визуальному восприятию, тем более относительно первого.

**Comment by Alex-302** [comment]
Соответствует)
`complaneta.com$script,~third-party` - `адрес_запросов$тип,кроме_сторонних` ; `~` - инвертирование(сторонние/не_сторонние)
`complaneta.com$script,third-party` - `адрес_запросов$тип,только_сторонние` ; 
т.е `что$где` ~когда~

**Comment by XX-J** [comment]
`адрес_запросов$тип,только_сторонние` - ну так я и думал, что при запросе с `этого адреса` будут блокироваться `только сторонние` ресурсы `этого типа`.

**Comment by ameshkov** [comment]
С этого всмысле что с этого адреса скрипт грузится, а не скрипт грузится со страницы с таким адресом.

**Comment by XX-J** [comment]
Я понял, но всё равно, это не выглядит настолько прозрачно - понятно, насколько могло быть.

 Т.е., резюмируя всё вышесказанное, правильное написание выглядело бы следующим образом:

`$script,domain=complaneta.com` - блокируются Все скрипты, подгружающиеся из сторонних файлов (т.е. не написанные в коде HTML страницы), на страницах домена complaneta.com

`$script,third-party,domain=complaneta.com` - блокируются Все скрипты, подгружающиеся из сторонних файлов, кроме скриптов подгружающихся с домена complaneta.com

`$script,~third-party,domain=complaneta.com` - блокируются только собственные скрипты с домена complaneta.com, подгружающиеся из сторонних файлов, что соответствует правилу `complaneta.com$script` и `complaneta.com$script,~third-party`.

    ?

**Comment by ameshkov** [comment]
Ага, все верно
