### ISSUE TITLE
AdGuard browser extension affects normal playback of bilibili.com videos

### ISSUE THREAD

**Issue by ShawCCC** [AdguardTeam/AdguardBrowserExtension#1569]
**### Steps to reproduce**
1.Turn on AdGuard browser extension
2.Go to this website - https://www.bilibili.com/video/av35992956
**### Expected behavior**
Video player should works.
**### Actual behavior**
Video player not work.

When I enable the adguard browser extension, I cannot play any of the videos on bilibili.com. I have asked the staff of bilibili.com related questions, and they said that it was caused by the Anti-theft chain.

ScreenShot:
![3](https://user-images.githubusercontent.com/37112629/71806880-f1ef8f00-30a4-11ea-923a-8d9b85ad32f8.JPG)

**### Your environment**

- AdGuard AdBlocker extension version:3.0.8

- Environment name and version:Google Chrome 79.0.3945.88

- Filters you use in AdGuard:English filter, Spyware filter, AdGuard annoying ad filter, Useful ad filter, Japanese filter

**Comment by krystian3w** [comment]
AG `v3.3.8`? 

3.0.8 is very old: https://github.com/AdguardTeam/AdguardBrowserExtension/releases/tag/v3.0.8

**Comment by ShawCCC** [comment]
> AG `v3.3.8`?
> 
> 3.0.8 is very old: https://github.com/AdguardTeam/AdguardBrowserExtension/releases/tag/v3.0.8

I updated to 3.3.8, but the problem persists.

**Comment by AdamWr** [comment]
Does it work if you disable all filters and/or stealth mode?
https://github.com/AdguardTeam/AdguardFilters/issues/46832

**Comment by ShawCCC** [comment]
> Does it work if you disable all filters and/or stealth mode?

Yes, it works when disable all filters and / or stealth mode.

**Comment by AdamWr** [comment]
Does it work if you disable only stealth mode?

**Comment by ShawCCC** [comment]
> Does it work if you disable only stealth mode?

It can work when disable only stealth mode.

**Comment by AdamWr** [comment]
Could you please check this rule (please enable stealth mode again and add this rule to user filter):
`@@||bilivideo.com^$stealth,domain=bilibili.com`

**Comment by ShawCCC** [comment]
> Could you please check this rule (please enable stealth mode again and add this rule to user filter):
> `@@||bilivideo.com^$stealth,domain=bilibili.com`

Yeah, you solved the problem perfectly!
Thanks.

**Comment by AdamWr** [comment]
Ok, thank you for checking it.
I will add this rule to AdGuard Base filter.
Update should be available in 1-2 hours.
