### ISSUE TITLE
Make Filters Removable (Options ==> 1: Terenary Button, 2: "X" delete next to button)

### ISSUE THREAD

**Issue by aspadistra** [AdguardTeam/AdguardBrowserExtension#157]
Make Filters Removable.

Removing filters is possible with other filtering extensions
-- uBlock 
-- Ad Block (and most of its branch variations) 
-- The method for the above with these extensions may be sometimes hidden or obscure, but it is there. 
-- It is best have the method out in the open.

User Interface Options

1: Terenary Button (aka 3 state switch)

The numbers are used to indicate Space Units aka "_" 
[ON] 1 2 3 [OFF] 1 2 3 4 [Delete]
-- The button colours may have to be changed somewhat to do this and not confuse people. 

2: "X" delete next to button

% means the Space Units area outside the "On" | "Off" individual filter switches 
[ON] 1 2 3 [OFF] % % % % [X] 
# 
# Delete Filters only after Restart

I recommend deleting filters only after restart, and all filter operations are nominal.

**Comment by ameshkov** [comment]
In fact you can delete filters now, but the operation is really irrational.

To do this:
1. Disable filters you want to be deleted
2. Click "All Filters"
3. Click "Save" there. All disabled filters will be deleted.

**Comment by ameshkov** [comment]
Planned on v3.0, along with a feature allowing to add "custom filters" by URL.

**Comment by ameshkov** [comment]
Covered by #789
