### ISSUE TITLE
Please block the below mentioned ads url and also add option to send message of such url

### ISSUE THREAD

**Issue by aravindSRM-India** [AdguardTeam/AdguardBrowserExtension#1570]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X ] I am running the latest version
- [X ] I checked the documentation and found no answer
- [ X] I checked to make sure that this issue has not already been filed

### Problem Description
1) There are some ads url which is not blocked by dns and extention
2) Please add a send message for such urls

Many ads url swam with malious intention. There is no option to easly report them
### Proposed Solution
1) please add the below mentioned urls to your block list
2) Please add option to send malious url via message

### Additional Information

URL list is below:

www.click.affifix.com click.affifix.com www.go.oclasrv.com go.oclasrv.com www.a33bb68b84b.com a33bb68b84b.com www.cdn.affifix.com cdn.affifix.com www.b9a861044f1.com b9a861044f1.com serve.popads.net www.serve.popads.net fapmeth.com www.fapmeth.com popads.net www.popads.net frcznmfu.com www.frcznmfu.com adslala.com www.adslala.com pejqoq4cafo3bg9yqqqtk5e6s6.com www.pejqoq4cafo3bg9yqqqtk5e6s6.com tqeobp89axcn.com www.tqeobp89axcn.com winprizefree.com www.winprizefree.com codeonclick.com www.codeonclick.com www.jeyuhcbagxbp.com jeyuhcbagxbp.com www.lqrrkjodhq.com lqrrkjodhq.com www.ouiinryhlvbgq.com ouiinryhlvbgq.com b.codeonclick.com www.b.codeonclick.com c1.popads.net www.c1.popads.net c2.popads.net www.c2.popads.net c3.popads.net www.c3.popads.net track.cmdelivery.pw www.track.cmdelivery.pw prize-v.com www.prize-v.com jeyuhcbagxbp.com www.jeyuhcbagxbp.com dcw.1592878.com www.dcw.1592878.com apc.clck-01.online www.apc.clck-01.online afftrk.online www.afftrk.online redonetype.com www.redonetype.com baiduccdn.com www.baiduccdn.com baiduccdn.com/popadsout.php www.baiduccdn.com/popadsout.php bunkirling.co www.bunkirling.co pipeschannels.com www.pipeschannels.com track.scared2convert.com www.track.scared2convert.com delivery.ayuemami.com www.delivery.ayuemami.com ayuemami.com www.ayuemami.com www.zlfpmrmkr.com zlfpmrmkr.com www.anqnimezkdjm.com anqnimezkdjm.com defpush.com www.defpush.com vcxqcjov.com www.vcxqcjov.com dpbviawkrumynm.com www.dpbviawkrumynm.com st-n.ads3-adnow.com www.st-n.ads3-adnow.com www.digitaldsp.com digitaldsp.com pushmobilenews.com www.pushmobilenews.com smashseek.com www.smashseek.com bdv.bidvertiser.com www.bdv.bidvertiser.com rcappkszvgwxx.com www.rcappkszvgwxx.com aqocbcnfxkuw.com www.aqocbcnfxkuw.com a.o333o.com www.a.o333o.com pagead2.googlesyndication.com www.pagead2.googlesyndication.com mycadads.info www.mycadads.info newclubads.info www.newclubads.info downloadgot.com www.downloadgot.com www.pehjaplsxbsfhs.bid pehjaplsxbsfhs.bid www.brrxmhuhyokw.bid brrxmhuhyokw.bid baiduccdn.com www.baiduccdn.com www.baidu.com baidu.com b42rracj.com www.b42rracj.com baiduccdn.com www.baiduccdn.com googleads.g www.googleads.g www.googleads.g.doubleclick.net googleads.g.doubleclick.net cdn.1120057983.world www.cdn.1120057983.world cdn.afftrk.online www.cdn.afftrk.online phoenixads.co.in www.phoenixads.co.in profitguruonline.com www.profitguruonline.com vukhhjzd.com www.vukhhjzd.com waudeesestew.com www.waudeesestew.com rzekbhnk.top www.rzekbhnk.top ade.clmbtech.com www.ade.clmbtech.com mylifeads.info www.mylifeads.info jsc.mgid.com www.jsc.mgid.com gsxewjrbrbtldy.com www.gsxewjrbrbtldy.com shein.in www.shein.in kdkzvfzmgvm.com www.kdkzvfzmgvm.com imasdk.googleapis.com www.imasdk.googleapis.com b.scorecardresearch.com www.b.scorecardresearch.com static.clmbtech.com www.static.clmbtech.com googletagservices.com www.googletagservices.com tpc.googlesyndication.com www.tpc.googlesyndication.com adage.com www.adage.com adageindia.in www.adageindia.in z-na.amazon-adsystem.com www.z-na.amazon-adsystem.com clients5.google.com adservice.google.co.in secure.calcch.com googl.co.in afgmyvid.com www.afgmyvid.com newfmads.info www.newfmads.info z-na.amazon-adsystems.com www.z-na.amazon-adsystems.com adsclk.com www.adsclk.com findbetterresults.com www.findbetterresults.com dolohen.com www.dolohen.com media.trafficjunky.net www.media.trafficjunky.net cdn1.ads.contentabc.com www.cdn1.ads.contentabc.com ads2.contentabc.com www.ads2.contentabc.com ads.trafficjunky.net www.ads.trafficjunky.net cdn.engine.phn.doublepimp.com www.cdn.engine.phn.doublepimp.com ssl2anyone3.com www.ssl2anyone3.com zme8o3l1c4.com www.zme8o3l1c4.com eventlive-lh.akamaihd.net www.eventlive-lh.akamaihd.net p319134.vacroz.xyz www.p319134.vacroz.xyz www.p319134.clksite.com p319134.clksite.com pushno.com www.pushno.com adserver.socialmint.news www.adserver.socialmint.news gld35wndkn.com www.gld35wndkn.com oupushee.com www.oupushee.com hantinlethemsed.info www.hantinlethemsed.info ilo134ulih.com www.ilo134ulih.com pewgnvqixnhvij.com www.pewgnvqixnhvij.com keapeiros.xyz www.keapeiros.xyz joralei.pw www.joralei.pw native.propellerclick.com www.native.propellerclick.com umekian.pw www.umekian.pw elwraek.xyz www.elwraek.xyz daezorwyn.xyz www.daezorwyn.xyz erberos.xyz www.erberos.xyz stoshoos.com www.stoshoos.com remtoaku.net www.remtoaku.net eloplen.com www.eloplen.com naustoch.net www.naustoch.net zoonoapt.net www.zoonoapt.net rinsouxy.com www.rinsouxy.com phengung.net www.phengung.net gloorajo.com www.gloorajo.com lessonis.com www.lessonis.com vd.7vid.net www.vd.7vid.net hcg82f2b.com www.hcg82f2b.com c.adsco.re tyjyrkcrv.com 41upk.bemobtrk.com www.tyjyrkcrv.com www.c.adsco.re www.41upk.bemobtrk.com ehu96t2p.com www.ehu96t2p.com

**Comment by ameshkov** [comment]
Please report ads to https://github.com/AdguardTeam/AdguardFilters.

But simply listing domains is not enough, we need examples of actual ads.
AAlso please note that most of the domains you've listed are already blocked.
