### ISSUE TITLE
Whitelist for individual YouTube channels

### ISSUE THREAD

**Issue by MaxVonMustermann** [AdguardTeam/AdguardBrowserExtension#1571]
Please add the ability to whitelist certain YouTube channels (or add the ability to whitelist channels a user subscribed to). Would be really appreciated, since other adblockers already have this useful feature. Thanks for the work on Adguard! :)

**Comment by ameshkov** [comment]
Dup of https://github.com/AdguardTeam/AdguardBrowserExtension/issues/147
