### ISSUE TITLE
Tests are not working in Firefox

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1575]
Please look here: https://github.com/AdguardTeam/TestCases/issues/35

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp

**Comment by ameshkov** [comment]
Additionally, check why this does not work:
`||testcases.adguard.com/Filters/qunit/qunit.js$script,redirect=noop.js,domain=testcases.adguard.com` (`noop.js` is a valid alias for `noopjs` which works okay)
