### ISSUE TITLE
whitelisting doesnt work

### ISSUE THREAD

**Issue by jackferno** [AdguardTeam/AdguardBrowserExtension#1577]
![image](https://user-images.githubusercontent.com/44953676/72585612-f3426800-38ab-11ea-8e20-8a61af66f2eb.png)
![image](https://user-images.githubusercontent.com/44953676/72585625-005f5700-38ac-11ea-8e94-1ef4cbfe8c8d.png)
these are the same website!

**Comment by ameshkov** [comment]
You should enter the domain name there, not the full URL: `tab.gladly.io`
