### ISSUE TITLE
YouTube player crashes at ~90% on any video

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardBrowserExtension#1578]
### Issue Details

- **AdGuard version:**
  - 3.3.8
- **Browser and version:**
  - Chrome Release
- **Operating system and version:**
  - Unspecified Windows 10
- **Filters you use in AdGuard:**
  - Base, Spanish
- **Stealth Mode settings:**
  - None
- **Other browser extensions:**
  - Unspecified spellchecker

### Screenshots

<details><summary>Screenshot:</summary>

![error adguard console](https://user-images.githubusercontent.com/33634917/72698374-9e714c80-3b4c-11ea-866c-5edb0a576f98.png)

</details>

### Additional Information

User ID: 2099266

**Comment by SoLenny** [comment]
@akmLaVx Can't reproduce it on my side. User can try to unlock blocked requests using the filtering log.
