### ISSUE TITLE
In Yandex browser icon for disabled Adguard is indistinguishable from the panel

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardBrowserExtension#158]
Looks like this: http://screencast.com/t/WWYogiteNtS

Yandex Browser version is 16.2.0.2568 beta

**Comment by ameshkov** [comment]
@vbagirov please provide the full window screenshot

**Comment by vbagirov** [comment]
Screenshot of the full window

**Comment by ameshkov** [comment]
Resolved by the new icon in v2.5
