### ISSUE TITLE
General and adult links injected in to HTML DOM when ADGUARD is enabled

### ISSUE THREAD

**Issue by tallman5** [AdguardTeam/AdguardBrowserExtension#1582]
Viewing the HTML, in a style element there is:

        FBS-AD, LEADERBOARD-AD, [ad-id^="googlead"], [href*="//xml.revrtb.com/"], [href^="https://maskip.co/"], [id^="bunyad_ads_"], [lazy-ad="leftbottom_banner"], [lazy-ad="leftthin_banner"], [lazy-ad="lefttop_banner"], [lazy-ad="top_banner"], [onclick^="window.open('http://adultfriendfinder.com/search/"], [onclick^="window.open('https://www.brazzersnetwork.com/landing/"], [onclick^="window.open('window.open('//delivery.trafficfabrik.com/"], [src^="/Redirect.a2b?"], a[href$="/vghd.shtml"], a[href*=".adk2x.com/"], a[href*=".adsrv.eacdn.com/"] > img, a[href*=".allsports4you.club"], a[href*=".approvallamp.club/"], a[href*=".bang.com/"][href*="&aff="], a[href*=".clkcln.com/"], a[href*=".clksite.com/"], a[href*=".fwd28.com/"], a[href*=".ichlnk.com/"], a[href*=".inclk.com/"], a[href*=".intab.fun/"], a[href*=".irtyc.com/"], a[href*=".opskln.com/"], a[href*=".orange2258.com/"], a[href*=".qertewrt.com/"], a[href*=".red90121.com/"], a[href*=".smartadserver.com"], a[href*=".udncoeln.com/"], a[href*="//3wr110.xyz/"], a[href*="//ridingintractable.com/"], a[href*="/adServe/banners?"], a[href*="/cmd.php?ad="], a[href*="/servlet/click/zone?"], a[href*="5iclx7wa4q.com"], a[href*="=Adtracker"], a[href*="=adscript"], a[href*="=exoclick"], a[href*="?adlivk="][href*="&refer="], a[href*="a2g-secure.com"], a[href*="ad2upapp.com/"], a[href*="deliver.trafficfabrik.com"], a[href*="delivery.trafficfabrik.com"], a[href*="emprestimo.eu"], a[href*="googleme.eu"], a[href*="mfroute.com/"] {
            display: none !important;
        }

**Steps**

1. Launch Edge with AG enabled
1. Navigate to https://www.gatsbyjs.org/
1. Copy the entire HTML element from a dev console, HTML will contain above
1. Close browser, launch again, disable AG
1. Navigate to https://www.gatsbyjs.org/, CSS will be gone
1. Repeat first three steps, CSS will be back

**Comment by Alex-302** [comment]
Hi. Please look at applied style - ` display: none !important;`
These CSS selectors are used for hiding ads.
