### ISSUE TITLE
Feature request in adguard block rules

### ISSUE THREAD

**Issue by Kees1958** [AdguardTeam/AdguardBrowserExtension#1583]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [Y ] I am running the latest version
- [Y] I checked the documentation and found no answer
- [Y] I checked to make sure that this issue has not already been filed

Two feature requests for writing your own AAdguard rules:

1. Please add a **PING** or navigator.sendBeacon() like AdBlockPlus has.  Since Hyperlink auditing can't be disabled using about://flags. 

2. Please add an **ALL** like uBlockOrigin has. With $all all Adguard block options are included (like domain, stealth, etc) to completely block (all) access to a domain

**Comment by zzebrum** [comment]
@Kees1958
1. We've created separate feature requests for all AG products, this one for AG browser extension: #1584
2. AdGuard has `$all` modifier support - #1506
