### ISSUE TITLE
Add $ping content type

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#1584]
@ameshkov commented on [Tue Feb 04 2020](https://github.com/AdguardTeam/CoreLibs/issues/1258)

* [x] Check how we can distinguish requests sent by `navigator.sendBeacon`
* [x] Add this content type support
* [x] Add it to the knowledge base

**Comment by vbagirov** [comment]
https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/476

**Comment by bogachenko** [comment]
Когда добавите это в программу?

**Comment by ameshkov** [comment]
@bogachenko `navigator.sendBeacon` на сетевом уровне вообще не отличается от любого другого запроса так что он только по собственному типу отличим

**Comment by bogachenko** [comment]
проблема заключается в том, что у меня есть список правил. в нем есть правила типа `/дерьмовый[-_]запрос/$ping,other,script` и в программе он не работает, тогда когда в расширении все заебумба

**Comment by ameshkov** [comment]
@bogachenko хм, понял, подумаем как бы так схэндлить.

Пока что только на два правила делить
