### ISSUE TITLE
Add Firefox Preview Nightly for Developers support

### ISSUE THREAD

**Issue by superlex** [AdguardTeam/AdguardBrowserExtension#1587]
Firefox Preview Nightly gains extension support:
https://www.androidpolice.com/2020/02/05/firefox-preview-nightly-extension/
For now it supports only uBlockOrigin, it would be nice if it would support AdGuard Browser Extension too :)

**Comment by ameshkov** [comment]
Unfortunately, this is not up to us. Eventually, Mozilla will add support of AdGuard as well

**Comment by superlex** [comment]
Ok, thanks anyway :)
