### ISSUE TITLE
Why can't the "baidu.com" domain name be blocked after the update?

### ISSUE THREAD

**Issue by thb007** [AdguardTeam/AdguardBrowserExtension#1596]
![R%_1NO_KAXGB4(4~8R@R2KU](https://user-images.githubusercontent.com/17548936/75113307-aa8a8580-5687-11ea-92fe-021ffde1b438.png)
The adguard used by my computer is the latest nightly version. Recently, I found that the adguard software has enforced a whitelisting measure on "baidu.com". At least the pc program has begun to cancel the blocking of the baidu domain name. Why is this? ?The screenshot below shows evidence that adguard did not intercept any Baidu domain name

![d](https://user-images.githubusercontent.com/17548936/75113215-d48f7800-5686-11ea-8791-deb81bfb823c.png)
![f](https://user-images.githubusercontent.com/17548936/75113218-d9542c00-5686-11ea-9de1-37b299b742d4.png)
![g](https://user-images.githubusercontent.com/17548936/75113222-dbb68600-5686-11ea-8d3f-523dd67d064b.png)

**Comment by ameshkov** [comment]
What filter lists are you using?

Could you please look for any rule for `baidu.com` there?

**Comment by thb007** [comment]
> What filter lists are you using?
> 
> Could you please look for any rule for `baidu.com` there?

I lifted the restrictions through @@ || www.baidu.com ^ $ document, badfilter, I don't understand. I ruled out normally.

**Comment by thb007** [comment]
> What filter lists are you using?
> 
> Could you please look for any rule for `baidu.com` there?

The problem has been found not to be a problem with your software.
