### ISSUE TITLE
Can not use on yandex android browser

### ISSUE THREAD

**Issue by hepin1989** [AdguardTeam/AdguardBrowserExtension#1597]
Can not use on yandex android browser

**Comment by SoLenny** [comment]
@hepin1989 Hello, do you mean that AdGuard for Android doesn't work fine?

**Comment by hepin1989** [comment]
@SoLenny Noop, I want to install this plugin on Yandex Android browser; I already has the Adguard content blocker and Adguard app installed, but I want to easily add some website to whiteList or block some elements.

**Comment by zzebrum** [comment]
@hepin1989 

> I want to easily add some website to whiteList or block some elements.

There is no integration mode between browser extension and the application on mobile devices. It would be better to report to us about missed ads so we can fix it in filters for all our users. 

Also note that  AdGuard browser extension is not adapted for mobile devices either.
