### ISSUE TITLE
Errors in console when domain with filters is inaccessible

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1601]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**3.3.8
- **Browser and version:** 80
 - **Operating system and version:** Win10
- **Filters you use in AdGuard:** Base, Soc, Track, Rus, Annoyances
- **Stealth Mode settings:** disabled

### Actual Behavior

Few errors in console, when filters.adtidy.org is inaccessible.

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/75928520-403bc700-5e77-11ea-8833-656e8b333d52.png)

</details>

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/75928538-48940200-5e77-11ea-805d-84018716614f.png)

</details>

**Comment by ameshkov** [comment]
I don't think it's directly connected to the outage, though. The outage might have triggered it somehow, but there's definitely a different bug.
