### ISSUE TITLE
Start automatik with chrome on android

### ISSUE THREAD

**Issue by hohleweg** [AdguardTeam/AdguardBrowserExtension#1602]
Hi
Man i starter adguard Automatik wehen i start chrome in android handy?
Thanks       

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

**Comment by SoLenny** [comment]
@hohleweg Hello. Could you describe more specifically your question? I do not fully understand it.

**Comment by hohleweg** [comment]
Hi there
sorry! So every time I restart my phone I have to turn on Adgard I want the Adguard ALWAYS activated when I start chrome

**Comment by SoLenny** [comment]
@hohleweg do you mean the phone app?

**Comment by hohleweg** [comment]
Yes Thema Telefone App Switch Android

**Comment by zzebrum** [comment]
@hohleweg please, specify the AdGuard version you have.

**Comment by hohleweg** [comment]
Hi
3.3.2    230-1.5.163.cl

zzebrum <notifications@github.com> schrieb am Mi., 18. März 2020, 14:27:

**Comment by hohleweg** [comment]
. The Newest version

**Comment by SoLenny** [comment]
Issue moved to [AdguardTeam/AdguardForAndroid #3382](https://github.com/AdguardTeam/AdguardForAndroid/issues/3382) via [**ZenHub**](https://www.zenhub.com/)

**Comment by SoLenny** [comment]
@hohleweg Hello, I transferred your task to the corresponding repository.
