### ISSUE TITLE
Chrome 80.0.3987.132 adguard prevent pages from loading after idle

### ISSUE THREAD

**Issue by jkldgoefgkljefogeg** [AdguardTeam/AdguardBrowserExtension#1603]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
AdGuard AdBlocker 3.3.8
- [x] I checked the documentation and found no answer
Yeah
- [x] I checked to make sure that this issue has not already been filed
Yeah

### Issue Details

- **AdGuard version:**
AdGuard AdBlocker 3.3.8
- **Browser and version:**
Google Chrome | 80.0.3987.132 (Official Build) (64-bit)
- **Operating system and version:**
Ubuntu 18.04.4 LTS
- **Filters you use in AdGuard:**
Base, Tracking Protection, Social Media, Annoyances, Warning Removal, Malware domains Blocklist, Spam404, NoCoin, French, Russian, German, Dutch, Japanese, Spanish/Portuguese, EasyList China, EasyList Italy
- **Stealth Mode settings:**
Off
- **Other browser extensions:**
Cashback Watch 0.0.1.4, Google Voice (by Google) 2.5.8, HTTPS Everywhere 2019.11.7, LastPass: Free Password Manager 4.43.0, Mute Tab 1.4, Proxy SwitchyOmega 2.5.20, Tampermonkey 4.9

### Expected Behavior

AdGuard does not interfere with Chrome page loading after unlock.

### Actual Behavior

After unlocking computer, chrome tabs are not rendering website until I disable AdGuard extension. Adguard extension seems to have become unresponsive and Adguard menu not loading. I confirmed Chrome is actually loading webpage via packet capture, but rendering is blocked until AdGuard is disabled.

### Additional Information

New issue since upgraded to Chrome 80.0.3987.132

**Comment by ameshkov** [comment]
Quick question - have you tried reinstalling AdGuard? It's hard to say what exactly happened, but at least this may help solve the issue right now

**Comment by zzebrum** [comment]
@jkldgoefgkljefogeg hi there! any update on this?
