### ISSUE TITLE
No longer working for YouTube

### ISSUE THREAD

**Issue by stephen147** [AdguardTeam/AdguardBrowserExtension#1605]
### Prerequisites
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details
- **AdGuard version:**
AdGuard - Latest
- **Browser and version:**
Chrome - Latest
- **Operating system and version:**
Windows 10
- **Filters you use in AdGuard:**
NA
- **Stealth Mode settings:**
NA
- **Other browser extensions:**
NA

### Expected and Actual Behavior

As the subject. I've tried other ad blockers but the same issue is there. YT comes back with "An error has occurred..." When playing a video out of my Watch Later playlist, if the video goes to the next one. It normally goes onto the next video. Instead, it throws the error explained above.

Disabling ADg will no longer have this issue but the ads will be there.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdguardFilters #51393](https://github.com/AdguardTeam/AdguardFilters/issues/51393) via [**ZenHub**](https://www.zenhub.com/)
