### ISSUE TITLE
adguard.configure callback does not apply rules

### ISSUE THREAD

**Issue by NoobSkywalker** [AdguardTeam/AdguardBrowserExtension#1607]
- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard API version:**
  - v3.3.8

### Expected Behavior

When a new rule is added and adguard.configure runs and callback is called (in my case i create a promise and resolve  it) and a new tab is opened (chrome.tabs.create ...) the rules are applied on the newly created tab. 

### Actual Behavior

the newly created tab does not use the rules added. Instead when i add a timeout within adguard.configure callback of ~3 seconds, then rules are added.

**Comment by NoobSkywalker** [comment]
Is there a hint where this has been fixed ? Or how it has been resolved ?

**Comment by maximtop** [comment]
https://github.com/AdguardTeam/AdguardBrowserExtension/commit/c8566dae0d018e59b8ff603e4fe030ed5f35e3eb
