### ISSUE TITLE
Add a [Browse] button to the "Add a custom filter list" window

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardBrowserExtension#1608]
Currently you can only type/paste path to a local file.

**Comment by XX-J** [comment]
Я сколько не пытался - у меня, при добавке локального фильтра, всегда пишется ошибка. Пробовал писать путь `F:\fgh.txt` и его же с кавычками, файл с правилами на месте, а по итогу - Ошибка.

 Почему так, может нужен определённый синтаксис фильтра, а не просто правила построчно?

**Comment by maximtop** [comment]
@vbagirov 
> Add a [Browse] button to the "Add a custom filter list" window
Browsers do not allow to get the path to the local file due to security reasons.

https://html.spec.whatwg.org/multipage/input.html#fakepath-srsly

@XX-J 
> Почему так, может нужен определённый синтаксис фильтра, а не просто правила построчно?
определенный синтаксис фильтра не нужен

проверьте что:
1. путь к файлу указан правильно. чтобы получить правильный путь можно открыть файл во вкладке вашего браузера и скопировать путь из адресной строки
2. у расширения включена настройка "Allow access to file URLs" (https://uploads.adguard.com/Image_2021-02-15_12-08-52.png)

**Comment by XX-J** [comment]
> проверьте что:
> 
>     1. путь к файлу указан правильно. чтобы получить правильный путь можно открыть файл во вкладке вашего браузера и скопировать путь из адресной строки
> 
>     2. у расширения включена настройка "Allow access to file URLs" (https://uploads.adguard.com/Image_2021-02-15_12-08-52.png)

 1. Сделал как сказали.
 2. Не нашёл такого пункта в настройках расширения.

 Всё равно пишет "Ошибка". [Вот](https://radikal.ru/video/1AiA6CCdm17), сделал видео процесса. [Вот](https://www13.zippyshare.com/v/tswEXCkM/file.html) сам файл.
 Этот же файл, [выложенный на GitHub'e](https://raw.githubusercontent.com/XX-J/XX-J-s-annoyance-filter/master/XX-J's%20annoyance%20filter.txt), по HTTPS ссылке принимается AdGuard'ом.

 ПО: Win7 SP1 x64 rus; FireFox v53.0.3 x32 rus; FireFox v78.6.1 ESR x32 rus;

**Comment by maximtop** [comment]
> ПО: Win7 SP1 x64 rus; FireFox v53.0.3 x32 rus; FireFox v78.6.1 ESR x32 rus;

В Firefox нет такой опции и нет возможности загружать указывая ссылки для локальных файлов
За обновлениями можете подписаться на этот баг - https://bugzilla.mozilla.org/show_bug.cgi?id=1266960

**Comment by XX-J** [comment]
> В Firefox нет такой опции и нет возможности загружать указывая ссылки для локальных файлов

 А я себе весь мозг вы... И так извращался и эдак, и в одном форке и в другом... А тут оказывается "заботливые" мозиловцы произвели анальное огораживание "пугливого" пользователя от "злобного" хакера. Пи......!

 @maximtop Можно ли сделать пометку в окне "Новая подписка на фильтр" об неподдерживаемости локального источника фильтра, если AdGuard определил браузер как Firefox? Просто я чувствую что я не последний кто наступит на эти грабли.

**Comment by maximtop** [comment]
> @maximtop Можно ли сделать пометку в окне "Новая подписка на фильтр" об неподдерживаемости локального источника фильтра, если AdGuard определил браузер как Firefox? Просто я чувствую что я не последний кто наступит на эти грабли.

Можно в Firefox не писать про возможность добавить локальный файл.

**Comment by XX-J** [comment]
> Можно в Firefox не писать про возможность добавить локальный файл.

 Ну или так. Сделайте, пожалуйста.

**Comment by maximtop** [comment]
Создал задачу https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1758
