### ISSUE TITLE
HTTPS Everywhere support.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardBrowserExtension#1609]
Request HTTPS Everywhere support like this:
https://chrome.google.com/webstore/detail/https-everywhere/gcbommkclmclpchllfjekcdonpmejbdp?hl=zh-TW

**Comment by lancelot-moon** [comment]
@SoLenny 
Why was this closed?

**Comment by SoLenny** [comment]
@lancelot-moon Hello. It was close due to it already exists in the CoreLibs repository.

**Comment by lancelot-moon** [comment]
@SoLenny
Does AG Browser Extension have CoreLibs?
Well, thanks for answering.

**Comment by SoLenny** [comment]
@lancelot-moon I apologize for misleading you. You are right, Corlibs are used only for Win, Android and Mac. We closed this task because the CWS policy requires extensions to do only one thing, for example, our extension should only block ads and trackers

**Comment by lancelot-moon** [comment]
Is CWS policy made by Google?
It shouldn't affect browser extensions/content blockers on macOC or iOS, right?
I see that 1Blocker blocks ads/trackers and provides HTTPS Everywhere.
https://1blocker.com/
