### ISSUE TITLE
Yahoo mail issue

### ISSUE THREAD

**Issue by Pepperjet** [AdguardTeam/AdguardBrowserExtension#161]
Newest version does not allow the yahoo mail compose button to correctly deploy in chrome or firefox.  Please fix.  Thanks!

**Comment by ameshkov** [comment]
Hi! Could you please provide a screenshot?

**Comment by ameshkov** [comment]
Ah, no need in it, I see the issue.

**Comment by ameshkov** [comment]
The issue is now resolved. Filter updates will be available in 20 minutes.

**Comment by Pepperjet** [comment]
Good job Andrey!  The filter update worked on Chrome and Firefox.  Also a bit less drag on the browsers - excellent.
Question:  Is the latest Adguard version for Firefox 2.0.20 and for Chrome 2.1.5?
Thanks much,
Eric

hQ    k Pepper  k Coons  k  Possum

**Comment by ameshkov** [comment]
> Question:  Is the latest Adguard version for Firefox 2.0.20 and for Chrome 2.1.5?

We have just released new version (v2.1.5). Now we need some time for review in all add-on stores.

It has already passed in Chrome Store, but not yet in AMO.

If you don't want to wait for review, you can get v2.1.5 right now:
https://addons.mozilla.org/en-US/firefox/addon/adguard-adblocker/versions/

**Comment by Pepperjet** [comment]
Thanks Andrey!
One last question:  Is there a way to revert back to an older version, ...just in case?
Kind regards,
Eric

hQ    k Pepper  k Coons  k  Possum

**Comment by ameshkov** [comment]
> One last question:  Is there a way to revert back to an older version, ...just in case?

Of course, the previous version stays on AMO also. But you'll need to uninstall the newer version first.
