### ISSUE TITLE
Chinese Traditional (zh-TW) issues on extensions store.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardBrowserExtension#1611]
1. The short description's translations are wrong on Firefox add-ons store.
You wrongly pasted the translations of "AdGuard ad blocker effectively blocks all types of ads on all web pages, even on Facebook, YouTube and others!" as the short description.

The correct short description is `Unmatched adblock extension against advertising and pop-ups. Blocks ads on Facebook, YouTube and all other websites.`.
Here are the correct short description's translations:
https://crowdin.com/translate/adguard-applications/17594/en-zhtw#3905524

https://addons.mozilla.org/zh-TW/firefox/addon/adguard-adblocker/
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/rIsdf91.png)

![image](https://i.imgur.com/mbqLMbX.png)
</details><br/>

2. If using italic fonts somewhere in the overview on Firefox add-ons store, bad looking.
I have cancelled italic fonts. (Removed `<i>...</i>` from my translations.)
**Please again update the overview's translations on Firefox add-ons store.**
Here are the translations:
https://crowdin.com/translate/adguard-applications/17618/en-zhtw#3865672
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/LAo4VNa.png)
</details><br/>

3. They're still old v3.3.8 with outmoded overview on Edge add-ons store and Opera extensions store.
I'll check after they're updated to v3.4.11.
https://microsoftedge.microsoft.com/addons/detail/pdffkfellgipmhklpdmokmckkkfcopbh?hl=zh-TW&gl=TW
https://addons.opera.com/zh-tw/extensions/details/adguard/

(Afterwards, overview's translations on Edge add-ons store are solved.
But it's still an old version on Opera extensions store.)

I'm not sure you used `Unmatched adblock extension against advertising and pop-ups. Blocks ads on Facebook, YouTube and all other websites.` or `AdGuard ad blocker effectively blocks all types of ads on all web pages, even on Facebook, YouTube and others!` as the short description on Edge add-ons store and Opera extensions store.
It's better to use `Unmatched adblock extension against advertising and pop-ups. Blocks ads on Facebook, YouTube and all other websites.` as the short description.

**Comment by lancelot-moon** [comment]
The point 3 was solved, but it's better if modifying the name "Adguard" to "AdGuard 廣告封鎖器" on Opera extensions store.
And the points 1 and 2 aren't fixed on Firefox add-ons store.

**Comment by maximtop** [comment]
I've updated descriptions in the Firefox addons store
Check please if everything is right.

**Comment by lancelot-moon** [comment]
Yes, they’re fixed on Firefox addons store.
Thanks.

**Comment by vozersky** [comment]
The name is going to be changed to "AdGuard 廣告封鎖器" on Opera extensions store after v3.5 release.

**Comment by lancelot-moon** [comment]
@vozersky Thank that you noticed this thing.))

**Comment by vozersky** [comment]
@lancelot-moon update: there is a slight chance it's actually not possible to change the name in Opera store :(
I'll double check it before the release.
