### ISSUE TITLE
BigBlueButton not connecting when trying to use mic and speaker

### ISSUE THREAD

**Issue by JaschaHD** [AdguardTeam/AdguardBrowserExtension#1612]
Since we're in an interesting time currently we're using BigBlueButton for communication quite a lot. 

But when joining a call and trying to connect via headset (with mic and speaker) there's always a bug: "incompatible sdp" and the sound doesn't connect.

This bug wasn't resolved after adding bbb to the blacklist in AdGuard. From what I've read you have to manually deactivate the extension which is quite anoying and I coulnd't find a different way to fix the problem.

**Comment by zzebrum** [comment]
@JaschaHD hi! Can you disable all filters and Stealth mode and check if it helps?

**Comment by JaschaHD** [comment]
Oh... I jsut realised that stealth mode isnt affected by whitelisting sites and also the WebRTC block option was enabled for my system.
It works as intended now.


So sorry to bother you and thx for the help!

Have a good day
