### ISSUE TITLE
Integration mode not working with Adguard for Windows

### ISSUE THREAD

**Issue by Lolen10** [AdguardTeam/AdguardBrowserExtension#1613]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - Adguard 7.4 nightly 11 (Windows 10)
  - Adguard 3.3.8 (extension: chrome)

- **Browser and version:**
  - Opera GX: LVL1 (core: 67.0.3575.105)

- **Operating system and version:**
  - Windows 10

- **Filters you use in AdGuard:**
  - Adguard Base Filter, EasyList, Adguard Tracking filter, Adguard Annoyances filter, Fanboy's Annoyances, Web Annoyances Ultralist, Adblock Warning Removal List, I do'nt care about cookies, NoCoin filter list, Adguard experimental filter, Adguard german filter

- **Stealth Mode settings:**
  - not enabled

### Expected Behavior

The Extension should go into integration mode with adguard for windows

### Actual Behavior

It stays in normal mode

**Comment by zzebrum** [comment]
@Lolen10 we've released a new native browser assistant which is a combination of the old browser extension and legacy assistant. You can read a little bit more about it here: https://github.com/AdguardTeam/AdguardForWindows/releases/tag/v7.4-beta-1

Please, go to AdGuard settings - Browser Assistant tab and click on Get the extension button:
https://uploads.adguard.com/Windows_10_32_bit_rus_2020-03-31_12-23-54.png
