### ISSUE TITLE
[User rules] Blocking full domain doesn't work with IP adresses

### ISSUE THREAD

**Issue by beerisgood** [AdguardTeam/AdguardBrowserExtension#1617]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  -  3.4.15 from Chromium-Edge Store
- **Browser and version:**
  -  Chromium-Edge 80.0.361.109 (Offizielles Build) (64-Bit)
- **Operating system and version:**
  -  Windows 10
- **Filters you use in AdGuard:**
  -  Base, Tracking protection, AdGuard Germany
- **Stealth Mode settings:**
  -  -
- **Other browser extensions:**
  -  -

### Expected Behavior

Using user rule can block all site types with defined filter

### Actual Behavior

Only domain's can be blocked with filter, not IP's like local IP for router login site

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

Both
`||192.168.178.1^$all`
and
 `HTTP://*^$all`

can't block the sites like 192.168.178.1
but filter work for sites like example.com

**Comment by zzebrum** [comment]
@beerisgood try this `@@||192.168.$~third-party,badfilter`

**Comment by beerisgood** [comment]
> @beerisgood try this `@@||192.168.$~third-party,badfilter`

Doesn't work, also i try with "@@" as this is for whitelisting isn't it?
But both doesn't block the IP URL.

in uBlock Origin this wasn't a problem btw

**Comment by beerisgood** [comment]
Any further idea or help?

@Alex-302 
@altokarev
@ameshkov
@atropnikov
@Dariamag
@Eugene-Savenko
@IldarKamalov
@northis
@Revertron
@sfionov
@SoLenny
@Stillness-2
@vbagirov
@vozersky
@zebrum

**Comment by tvinzz** [comment]
please, check https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#network-modifier

**Comment by beerisgood** [comment]
> please, check https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#network-modifier

Sadly this doesn't work with AdGuard browser extension.

This is even written in your link:
"_Only AdGuard for Windows, Mac, Android are technically capable of using this type of rules_."
