### ISSUE TITLE
Filter rules count is higher in Firefox.

### ISSUE THREAD

**Issue by PentagramTr** [AdguardTeam/AdguardBrowserExtension#1619]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:** 3.4.11
  
- **Browser and version:** Firefox 75.0 (64 bit)
  
- **Operating system and version:** Windows 10

- **Filters you use in AdGuard:** Base-Social-Annoyances-Tracking Protection-Turkish-NoCoin

- **Stealth Mode settings:** Enabled
  
- **Other browser extensions:**
 

### Actual Behavior

Filter rules count appears higher in the Firefox Adguard extension. (About 1,351 rules.) This count is lower in Chrome.
I reinstalled both extensions, but nothing has changed. And I use the same filters on both extensions.

### Screenshots

<details><summary>Chrome rule count:</summary>

![a1](https://user-images.githubusercontent.com/34379403/79063687-bbc93900-7cab-11ea-8d5e-edbb5060218f.png)

</details>

<details><summary>Firefox rule count:</summary>

![Ekran Görüntüsü 2020-04-10 02 58 21-fullpage](https://user-images.githubusercontent.com/34379403/78950529-b3200980-7ad7-11ea-9c21-5bca2cc05162.png)

</details>

**Comment by SoLenny** [comment]
@PentagramTr Hello, we do different sets of rules for Chrome and Firefox. That's why the count of rules is different.
