### ISSUE TITLE
Browser Assistant Beta DevTool panel

### ISSUE THREAD

**Issue by moraks** [AdguardTeam/AdguardBrowserExtension#1621]
Will be added  the ADG panel to DevTools in new AdGuard Browser Assistant Beta? 
I often use it, this is a convenient thing (for my opinion)... 

<details><summary>Screenshot+</summary>

![DevTools](https://user-images.githubusercontent.com/20518047/79007751-03ee3b80-7b86-11ea-84fa-7e6495f4b828.jpg)

</details>

**Comment by zzebrum** [comment]
Issue moved to [AdguardTeam/BrowserAssistant #5](https://github.com/AdguardTeam/BrowserAssistant/issues/5) via [**ZenHub**](https://www.zenhub.com/)
