### ISSUE TITLE
Cosmetic rules can be used as CSS rules

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/AdguardBrowserExtension#1624]
### Issue Details

- **AdGuard version:**
  - AdGuard v3.4.19
- **Browser and version:**
  - Chrome

I mean that at the moment we can also use `##` instead of `#$#` and CSS rule will be applied.

Steps to reproduce:
1. Add this rule:
`example.org##body { background: red!important; }`
2. Go to - http://example.org/

It also allows to use `url(...)` and if I understand correctly it shouldn't be allowed - https://github.com/AdguardTeam/CoreLibs/issues/1026, https://github.com/AdguardTeam/CoreLibs/issues/659#issuecomment-472826518

Example:
```
example.org##body { background: lightblue url("https://www.w3schools.com/cssref/img_tree.gif") no-repeat fixed center!important; }
```

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/79443306-f4358380-7fd9-11ea-9bfd-5220f5e7f154.png)

</details>

https://github.com/AdguardTeam/CoreLibs/issues/1293

**Comment by ameshkov** [comment]
When implementing this issue, please take a look at CoreLibs unit-tests -- there are many tricky edge cases.
