### ISSUE TITLE
theverge.com delay

### ISSUE THREAD

**Issue by SeriousHoax** [AdguardTeam/AdguardBrowserExtension#1626]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  -  3.4.19
- **Browser and version:**
  -  Chromium Edge 81
- **Operating system and version:**
  -  Windows 10
- **Filters you use in AdGuard:**
  -  Adguard Base, AdGuard Mobile Ads, Adguard Tracking Protection, Adguard Annoyances, Adguard Social Media
- **Stealth Mode settings:**
  - 
- **Other browser extensions:**
  - 

### Expected Behavior

 Website loading with unnecessary delay

### Actual Behavior

 Delay in page loading for https://www.theverge.com/ 
When the page is visited there's always a certain unnecessary delay for the page to come into view. Now if I click on an article then there's a delay again, if I go back then there's a delay as well. This is Adguard extension related because there's no such issue with uBlock Origin with same filters.

### Screenshots

 Check the gif for details on how to reproduce

<details><summary>Screenshot:</summary>

![adg](https://user-images.githubusercontent.com/29574622/79636026-ac0f9000-8196-11ea-9402-73a7808c78d5.gif)
</details>

**Comment by zecanard** [comment]
Not experiencing this with the browser extension in Safari on macOS Catalina and iOS 13.4.1, if that helps narrow it down.

**Comment by SeriousHoax** [comment]
> 
> 
> Not experiencing this with the browser extension in Safari on macOS Catalina and iOS 13.4.1, if that helps narrow it down.

I've asked this to some other users on Windows and they are experiencing this delay too more or less. One of them is even using Adguard desktop. He has this delay too on The Verge website. So maybe this needs to be tested on Windows. Same behavior with Firefox on Windows 10.

**Comment by Yuki2718** [comment]
> 
> One of them is even using Adguard desktop. 

In fact it's not an extension issue but a filter issue, so should be moved to AdGuardFilters.
Please add this to User Rules and test:
`||googletagmanager.com/gtm.js$script,redirect=googletagmanager-gtm`

If the issue persists, also
```
||googletagservices.com/tag/js/gpt.js$script,redirect=googletagservices_gpt
theverge.com#%#//scriptlet('abort-current-inline-script', 'CONCERT_ADS_CONFIG.dfpVariables')
```

**Comment by Alex-302** [comment]
Hmm. I cannot reproduce this issue - page content loaded fast.

**Comment by SeriousHoax** [comment]
> 
> 
> > One of them is even using Adguard desktop.
> 
> In fact it's not an extension issue but a filter issue, so should be moved to AdGuardFilters.
> Please add this to User Rules and test:
> `||googletagmanager.com/gtm.js$script,redirect=googletagmanager-gtm,domain=theverge.com`
> 
> If the issue persists, also:
> 
> ```
> ||googletagservices.com/tag/js/gpt.js$script,redirect=googletagservices-gpt,domain=theverge.com
> theverge.com#%#//scriptlet('abort-current-inline-script', 'CONCERT_ADS_CONFIG.dfpVariables')
> ```

Hi, the first rule fixed the issue. The second one was not required. Now the page is loading fast as it should.

**Comment by Yuki2718** [comment]
> 
> 
> Hmm. I cannot reproduce this issue - page content loaded fast.

It may not be obvious delay, but when visited the top page I got page-blink or a temporal black screen, and after clicking any article again blink or a temporal white screen - how long it take depends, sometimes 0.5 sec or so other times more.

**Comment by SoLenny** [comment]
Issue moved to [AdguardTeam/AdguardFilters #54102](https://github.com/AdguardTeam/AdguardFilters/issues/54102) via [**ZenHub**](https://www.zenhub.com/)

**Comment by SeriousHoax** [comment]
@Yuki2718 The issue has been fixed for the extension but it's still present in the desktop app for Windows. Have a look please!
