### ISSUE TITLE
Custom filter cannot be updated

### ISSUE THREAD

**Issue by thb007** [AdguardTeam/AdguardBrowserExtension#1627]
The custom filter cannot be updated, the default rules are updated normally

**Comment by SoLenny** [comment]
@thb007 Hello, please specify which browser and extension version you are using.

**Comment by thb007** [comment]
> @thb007 Hello, please specify which browser and extension version you are using.

Version 3.4.19, version 80.0.3987.163 (official version) (64-bit)

**Comment by SoLenny** [comment]
@thb007 Can you let me the link to custom filter that you are trying to update?

**Comment by thb007** [comment]
![image](https://user-images.githubusercontent.com/17548936/79946255-2a737700-84a2-11ea-91ee-4fe3e1d3efc0.png)
![image](https://user-images.githubusercontent.com/17548936/79946284-3bbc8380-84a2-11ea-93d5-794039099cfe.png)
```
https://www.kbsml.com/adblock/adguard/adg-kall.txt
```

**Comment by thb007** [comment]
> @thb007 Can you let me the link to custom filter that you are trying to update?

```
https://www.kbsml.com/adblock/adguard/adg-kall.txt
```

**Comment by SoLenny** [comment]
@thb007 Is it your own filter? Can you update it so I can test it?

**Comment by thb007** [comment]
> @thb007 Is it your own filter? Can you update it so I can test it?

It ’s mine, the latest version: 20200422-21: 31

**Comment by SoLenny** [comment]
Try using a different version format. Most likely the updates do not pass precisely because of this. Use the same format as we use for our filters like `! Version: 2.1.15.96`

**Comment by thb007** [comment]
> Try using a different version format. Most likely the updates do not pass precisely because of this. Use the same format as we use for our filters like `! Version: 2.1.15.96`

I test it

**Comment by thb007** [comment]
> Try using a different version format. Most likely the updates do not pass precisely because of this. Use the same format as we use for our filters like `! Version: 2.1.15.96`

Changed similar Version: 2.1.15.96, but it does not work

**Comment by thb007** [comment]
> Try using a different version format. Most likely the updates do not pass precisely because of this. Use the same format as we use for our filters like `! Version: 2.1.15.96`

When I look at the test later, I will delete the shared rule address

**Comment by maximtop** [comment]
I've checked right now, and it updated.

**Comment by thb007** [comment]
> I've checked right now, and it updated.

Thanks, it worked, it has been updated normally.

**Comment by maximtop** [comment]
Feel free to open the issue again if you'd encounter this problem again.
