### ISSUE TITLE
Error in console after browser start

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1628]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:** 3.4.19
  - 
- **Browser and version:** Chrome 80
  - 
- **Operating system and version:** Win10
  - 
- **Filters you use in AdGuard:** Base, Tracking, Social, Annoyances, Russian
  - 
- **Stealth Mode settings:**
  - 
- **Other browser extensions:**
  - 

### Actual Behavior

Error in console after browser start(not every time).

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/79805643-3a3e6e80-836f-11ea-849d-d173988ebfa6.png)

</details>

**Comment by ameshkov** [comment]
Isn't it already fixed?

**Comment by maximtop** [comment]
Already fixed
