### ISSUE TITLE
Improve the usage

### ISSUE THREAD

**Issue by fisforfaheem** [AdguardTeam/AdguardBrowserExtension#1629]
Chrome already takes a ton of resources...but with this, it takes even more, please do somethig  like dns or anything else that does cloud filtering for faster and no processing.

**Comment by zzebrum** [comment]
@fisforfaheem hi there! you already can use [AdGuard DNS](https://adguard.com/en/adguard-dns/overview.html) or [AdGuard Home](https://adguard.com/en/adguard-home/overview.html) solutions.
