### ISSUE TITLE
"I don't care about cookies" filter slows down GMAIL

### ISSUE THREAD

**Issue by Tiamatti** [AdguardTeam/AdguardBrowserExtension#1630]
When using Adguard extension with Edge and Chrome, i realized that gmail was having some "hiccups" when scrolling down and up. I was disabling all my extensions till fine the guilt: adguard extension. Then i disabled filters one by one till find if it was related with any of them. After that i realized that "I don't care about cookies" filter was causing the problem. When enabled, gmail took longer to load 100%, and even after loading, i was experimenting some tiny freezes when changing tabs inside gmail and scrolling down or up right after that. I disabled that filter and i'm not having any problem anymore.

**Comment by zzebrum** [comment]
@Tiamatti It is a third-party filter, so we can suggest you either contact filter maintainer or use other filters for your purposes.
