### ISSUE TITLE
Hyperlink auditing option

### ISSUE THREAD

**Issue by Tiamatti** [AdguardTeam/AdguardBrowserExtension#1631]
As adressed [HERE](https://blog.malwarebytes.com/privacy-2/2019/06/hyperlink-auditing-where-has-my-option-to-disable-it-gone/) and many other sites and foruns, Hyperlink auditing is a big concern when privacy is considered. 

Till now, the only options to avoid Hyperlink auditing are firefox and brave browsers, and ublock origin extension. 

It should be a huge update to adguard if you could add the option to disable it in your extension. I guess it shouldn't be too difficult as ublock already have it and it is a open source extension. 

Ty for your kind attention

**Comment by zzebrum** [comment]
@Tiamatti it was done recently - #1584

**Comment by Tiamatti** [comment]
@zzebrum sorry for my ignorance. But can you help me to understand pls? 

I got that that already implemented the option to disable Hyperlink auditing

But is it in the filters? which one? or do i have to add it by myself to my rules? ty!

**Comment by zzebrum** [comment]
@Tiamatti sorry, I've missed your comment. As I can see you've created the feature request already - #1636 

and yes, ping modifier support was added so you can use it in your own rules.
