### ISSUE TITLE
to-do.live.com is broken

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1634]
@adguard-bot commented on [Mon Apr 27 2020](https://github.com/AdguardTeam/AdguardFilters/issues/54460)

### Issue URL (Incorrect Blocking)
https://to-do.live.com/tasks/ 
### Comment
> Сайт https://to-do.live.com/tasks/ не работает только с включенным дополнением AdGuard.
> Даже если просто выключить дополнение для этого сайт - все равно не работает.
> Если совсем в браузере выключить дополнение AdGuard тогда сайт открывается нормально.
> Писал в поддержку Яндекс Браузера. Они подтверждают, что не работает сайт https://to-do.live.com/tasks/ только с включенным вашим дополнением и рекомендовали написать вам.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/LKZCg8u.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/LJCjMRr.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Ext
AdGuard version: | 3.4.19
Browser: | Yandex
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Other:</b><br/> Filter unblocking search ads and self-promotion<br/><br/><b>Language-specific:</b><br/> AdGuard Russian
Other extensions used: | нет таких

---

@Alex-302 commented on [Mon Apr 27 2020](https://github.com/AdguardTeam/AdguardFilters/issues/54460#issuecomment-620134515)

![image](https://user-images.githubusercontent.com/8361299/80403418-37400280-88c8-11ea-8948-75bb18e65c27.png)

**Comment by Alex-302** [comment]
Reproduced with disabled filters and Stealth Mode.

**Comment by ameshkov** [comment]
It makes sense to push a hotfix if so.

We could include updated scriptlets and extcss as well.

**Comment by Redbox24** [comment]
the error hasn't been fixed yet?

**Comment by maximtop** [comment]
Seems like this is the chrome bug.
I've created a chrome extension, which reproduces the problem and submitted issue to the chromium bug tracker. 
https://bugs.chromium.org/p/chromium/issues/detail?id=1075905
