### ISSUE TITLE
[Question] Is it possible for AdGuard to modify HTTP headers?

### ISSUE THREAD

**Issue by Cybo1927** [AdguardTeam/AdguardBrowserExtension#1635]
Is there currently any way to modify sent HTTP headers? I want to spoof things like my referrer or user agent, I can trick sites that use JavaScript APIs to get these but it doesn't work if they check headers.

**Comment by zzebrum** [comment]
@Cybo1927 currently we have these options in AdGuard browser extension: https://uploads.adguard.com/AdGuard_Settings_2020-04-29_12-39-28.png
