### ISSUE TITLE
Triggered scriptlet rules without domain restriction are not printed to filtering log

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1637]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:** 3.4.19
- **Browser and version:** 80
- **Operating system and version:** Win10
- **Filters you use in AdGuard:** Base
- **Stealth Mode settings:** no
- **Other browser extensions:**

### Expected Behavior

The rule is shown in the filtering log.

<details><summary>Screenshot - the rule with domain restriction:</summary>

![image](https://user-images.githubusercontent.com/8361299/80596742-85234a80-8a2f-11ea-959b-a09bfc1d7074.png)

</details>

### Actual Behavior

The rule is not shown in the filtering log.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/80596658-6329c800-8a2f-11ea-92fc-3c75e6ba76f5.png)

</details>

Sample site:
`http://www.fontyukle.net/en/`
The rule:
`#%#//scriptlet("abort-current-inline-script", "$", "reklam")`
`fontyukle.net#%#//scriptlet("abort-current-inline-script", "$", "reklam")`

**Comment by Alex-302** [comment]
The same issue with JS rules.

Go to http://example.org/ and check these rules one by one:
```
example.org#%#AG_onLoad(function() { if(window.location.href.indexOf("/consent-a-?targetUrl=") != -1){document.getElementsByClassName('button[data-consent-el="acceptAllButton"]')[0].click();} });
```

**Comment by Alex-302** [comment]
@Mizzick ping

**Comment by Mizzick** [comment]
this is an intended behaviour
