### ISSUE TITLE
Adguard block image download even when turned off

### ISSUE THREAD

**Issue by Tsunamijhoe** [AdguardTeam/AdguardBrowserExtension#1638]
I have had to completely remove the adguard extension from Opera 67/68 (Windows 7 Ultimate) as it kept blocking download of images from thetvdb.com. It kept blocking even when turned off or if i whitelisted site.

**Comment by SoLenny** [comment]
@Tsunamijhoe Hello, could you describe in more detail how exactly you download pictures from this site? Or maybe you could give an example with a link?

**Comment by zzebrum** [comment]
reopen if needed

**Comment by Tsunamijhoe** [comment]
I just tried once again,and unless you fixed this in the last 2 days, problem still persist.. I replied to the email you sent me, asking me to provide details to the problem,i did. 
Problem persists for this one site.. I still get blocked image downloads from thetvdb.com. Only deleting extension will let me save images from the site. Other ad blockers does NOT block said site.
