### ISSUE TITLE
Converted uBO scriptlets issue

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1643]
@adguard-bot commented on [Sat May 30 2020](https://github.com/AdguardTeam/AdguardFilters/issues/56461)

### Issue URL (Ads)
 [https://www.doofree88.com/movie/the-kings-avatarfor-the-glory-2020%e0%b9%80%e0%b8%97%e0%b8%9e%e0%b8%a2%e0%b8%b8%e0%b8%97%e0%b8%98%e0%b9%8c%e0%b9%80%e0%b8%8b%e0%b8%b5%e0%b8%a2%e0%b8%99%e0%b8%81%e0%b8%a5%e0%b8%ad%e0%b8%a3%e0%b8%b5](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.doofree88.com%2Fmovie%2Fthe-kings-avatarfor-the-glory-2020%25e0%25b9%2580%25e0%25b8%2597%25e0%25b8%259e%25e0%25b8%25a2%25e0%25b8%25b8%25e0%25b8%2597%25e0%25b8%2598%25e0%25b9%258c%25e0%25b9%2580%25e0%25b8%258b%25e0%25b8%25b5%25e0%25b8%25a2%25e0%25b8%2599%25e0%25b8%2581%25e0%25b8%25a5%25e0%25b8%25ad%25e0%25b8%25a3%25e0%25b8%25b5)
### Comment
> Hi. Alex-302 after i enable Thai Ads Filter and upate filter, all ads video still playing but can skip ad faster than disable Thai Ads Filter.In my opinion Thai Ads filter created for support uBlock Origin or Nano Adblocker.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/kDU2ANi.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Ext
AdGuard version: | 3.4.31
Browser: | Chrome
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>EasyList<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection, <br/>EasyPrivacy<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances, <br/>(Obsolete) Anti-Adblock Killer \| Reek<br/><br/><b>Security:</b><br/> Malware Domains Blocklist, <br/>Spam404, <br/>NoCoin Filter List<br/><br/><b>Language-specific:</b><br/> Thai Ads Filters

---

@Alex-302 commented on [Tue Jun 02 2020](https://github.com/AdguardTeam/AdguardFilters/issues/56461#issuecomment-637575786)

I can confirm than, but it seems this is not filters issue(uBO's rules are converted), that rule works in user filter and works with AdGuard for Windows(without user filter)

**Comment by Alex-302** [comment]
Issues
1. Timer(red counter after pressing Pray button) is not accelerated
![image](https://user-images.githubusercontent.com/8361299/83534992-2eab9f00-a4fa-11ea-9154-b19569b38d9c.png)

2. window.open is not blocked when you click on player

**Comment by ameshkov** [comment]
We should check what's wrong there indeed
