### ISSUE TITLE
streamtape.com - infinite Pending status of video request

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1644]
@adguard-bot commented on [Wed Jun 03 2020](https://github.com/AdguardTeam/AdguardFilters/issues/56724)

### Issue URL (Incorrect Blocking)
 [https://streamtape.com/e/YyP3XmrJ8kTvy7d/?autostart=true](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fstreamtape.com%2Fe%2FYyP3XmrJ8kTvy7d%2F%3Fautostart%3Dtrue)
### Comment
Username: @Sorrow-San
> Extensive testing shows that even if you "turn off" adguard, every single filter, and clear your user-filters list the videos on Streamtape will still refuse to fully load. But if you disable the extension entirely then the videos will load without any issues. (Although, you do get swarmed with Ads taking this approach) 
> 
> This problem is also unique to Adguard's desktop extension it appears as uBlock Origin and AdBlock Plus do not elicit this response. And the IOS mobile app for Adguard also doesn't appear to cause this problem.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/DRxwfGA.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/gd1AZC7.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Ext
AdGuard version: | 3.4.31
Browser: | Chrome
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>AdGuard Mobile Ads, <br/>EasyList, <br/>Peter Lowe's Blocklist<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances
Custom filter subscriptions: | https://gitlab.com/Sorrow-San/9anime-adblock-filters/-/raw/master_EasyListFormat/9Anime%20filter%20list.txt
Other extensions used: | None

---

@AdamWr commented on [Wed Jun 03 2020](https://github.com/AdguardTeam/AdguardFilters/issues/56724#issuecomment-638383961)

I'm not sure, but it looks like a website issue.
On my end this video works very rarely and it doesn't matter if AdGuard is enabled or not.
<details><summary>Screenshot with AdGuard disabled and video doesn't work</summary>

![image](https://user-images.githubusercontent.com/29142494/83669262-8e28ae00-a5d1-11ea-91e6-d52a56c6ff33.png)

</details>

<details><summary>Screenshot with AdGuard enabled and video works fine</summary>

![image](https://user-images.githubusercontent.com/29142494/83674891-7143a900-a5d8-11ea-9dd7-dd3ac5dc6bf3.png)

</details>

@AdguardTeam/filters-maintainers Could you please check it?

---

@zloyden commented on [Thu Jun 04 2020](https://github.com/AdguardTeam/AdguardFilters/issues/56724#issuecomment-638698113)

On my end it doesn't depend on AdGuard with our filters. Only if you manually block `.plyr-overlay`.

---

@Sorrow-San commented on [Thu Jun 04 2020](https://github.com/AdguardTeam/AdguardFilters/issues/56724#issuecomment-639063475)

Strange that two people aren't having the issue, I'll run some more tests in a bit and report back to see if somehow it's got something to do with cached information that's only present while AdGuard is active.

---

@Alex-302 commented on [Mon Jun 08 2020](https://github.com/AdguardTeam/AdguardFilters/issues/56724#issuecomment-640736989)

Reproduced. Infinite `Pending` status of video request
![image](https://user-images.githubusercontent.com/8361299/84056130-76c93680-a9be-11ea-962e-339613c10712.png)

**Comment by Alex-302** [comment]
Video works when extension is disabled in Chrome settings.

**Comment by ameshkov** [comment]
Yeah, this is the same issue as #1634, i.e. https://bugs.chromium.org/p/chromium/issues/detail?id=1075905 https://bugs.chromium.org/p/chromium/issues/detail?id=938560

@maximtop can we maybe come up with a temporary solution?

**Comment by maximtop** [comment]
> @maximtop can we maybe come up with a temporary solution?

In order to solve this issue, we have to remove the 'extraHeaders' option. I think it is not possible because without it extension won't have access to the following headers:
- Origin
- Referer
- Cookie

**Comment by ameshkov** [comment]
Temporary solution for Chrome would be to not add extraHeaders option to requests of the following types: 

* stylesheet
* script
* media

So you will need to add two listeners: one, without extraHeaders - for these three types, and the second one for other resource types.
