### ISSUE TITLE
Web pages are scrolled automatically while clicking "Check for filters updates" by the context menu of Firefox

### ISSUE THREAD

**Issue by byyxx128** [AdguardTeam/AdguardBrowserExtension#1645]
### Issue Details

- **AdGuard version:**
  - 3.4.31
- **Browser and version:**
  - Firefox 77.0.1/78.0b6 (Actually it can be reproduced with any version of Firefox)
  - The problem does not happen in Chrome or any Chromium-based browsers.
- **Operating system and version:**
  - Windows 10 20H1 version 2004 build 19041 (I don't think it's a problem of OS either)
- **Filters you use in AdGuard:**
  - Base filter (It could not be the issue of filters as well)
- **Stealth Mode settings:**
  - disabled
- **Other browser extensions:**
  - N/A (I have disabled all the rest)

### Steps to Reproduce
1. Open any web page in Firefox.
e.g. https://blogs.windows.com
2. Click "Check for filters updates" by the context menu. You may see nothing abnormal.
3. Page down a little. Click "Check for filters updates" again. You will find the page is scrolled automatically.

### Expected Behavior
The web page should not be scrolled.

### Screenshots
![screenshot](https://user-images.githubusercontent.com/20079289/84593753-5139a280-ae80-11ea-9c79-fc2e7f342c55.gif)

**Comment by byyxx128** [comment]
Just a reminder that the issue still exists as of AdGuard Extension 4.0.204 with Firefox 103+.

**Comment by kaprielov** [comment]
it looks like an ff bug, we sent them the [issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1782712)

**Comment by kaprielov** [comment]
Fixed. Will work correctly in the next version

**Comment by byyxx128** [comment]
Yep, fixed. Works perfect now.
