### ISSUE TITLE
Adguard settings reset in Firefox after closing

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1646]
@jbionic2016 commented on [Fri Jun 12 2020](https://github.com/AdguardTeam/AdguardFilters/issues/57268)

Hi there,

I have Adguard addon in Firefox browser. It used to be working just fine until recently, but since Firefox update to version 77 or so something strange is happening. Every time I close Firefox all Adguard settings are gone, so at next startup of Firefox Adguard shows that it is loading something (see 1st picture below), it never showed something like this before. But once I go Adguard Options, all the settings are reset by their default values, all filters are gone, so I have to set it up all over again, which is a bit of pain.. So I wonder if this can be fixed any time soon..

Operating system: Windows 10 Home
Browser: Firefox 77.0.1 (64-bit)
AdGuard version for Firefox: Version 3.4.31
Filters enabled: AdGuard Base filter, AdGuard Tracking Protection filter, EasyPrivacy, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter
Stealth mode options (Windows only) Enabled
![111](https://user-images.githubusercontent.com/23212486/84536843-55868400-acf7-11ea-9c19-ededddd4cd2f.jpg)
![222](https://user-images.githubusercontent.com/23212486/84536845-56b7b100-acf7-11ea-8d94-894948c50979.jpg)
![333](https://user-images.githubusercontent.com/23212486/84536847-56b7b100-acf7-11ea-863f-cf7f057dc148.jpg)
![444](https://user-images.githubusercontent.com/23212486/84536848-57e8de00-acf7-11ea-8bdb-062106ce752c.jpg)

---

@BlazDT commented on [Fri Jun 12 2020](https://github.com/AdguardTeam/AdguardFilters/issues/57268#issuecomment-643440984)

@TheHasagi @Chinaski1

**Comment by jbionic2016** [comment]
Hi there. I just wanted to demonstrate what the problem looks like in practice
https://youtu.be/VYnwmUkEx3g

**Comment by zzebrum** [comment]
@jbionic2016 do you use any kind of cleaning app, such as CCleaner?

**Comment by jbionic2016** [comment]
> @jbionic2016 do you use any kind of cleaning app, such as CCleaner?

Yes, I do. But previously this did not cause any problems, Adguard used to be loading just fine

**Comment by ameshkov** [comment]
@jbionic2016 this is very unusual.

Please next time you restart Firefox, open "Tools" -> "Web Developer" -> "Browser Console", copy/paste all the stuff from there.

One more thing to check - open about:profiles and try creating a new browser profile. Check how it works with a new profile.

**Comment by jbionic2016** [comment]
> @jbionic2016 this is very unusual.
> 
> Please next time you restart Firefox, open "Tools" -> "Web Developer" -> "Browser Console", copy/paste all the stuff from there.
> 
> One more thing to check - open about:profiles and try creating a new browser profile. Check how it works with a new profile.

Here is the log I copied from Browser Console
https://drive.google.com/file/d/1KIhfiB3tLE-yGa2PNOVCMEdSUQ8Yztq_/view?usp=sharing

As advised, I've created a new profile and installed Adguard addon for it. At next Firefox startup all Adguard pre-settings for the new profile have been loaded without a hitch. So apparently the problem has something to do with the profile then. What would be your recommendations then?

**Comment by ameshkov** [comment]
It seems that the profile's "IndexedDB" is corrupted, I see a lot of unspecified errors in the log.

I am not sure if it's possible to recover or recreate it. Not sure, maybe you need to somehow export your current profile data, create a new one and import that data there?

Anyways, this does not look like a bug of AdGuard.

**Comment by qumberrizvi** [comment]
This seems to be happening for me too. Could you please look into it again. Let me know what additional details I can provide?

**Comment by mozartinio** [comment]
@qumberrizvi 
Hi
Does the problem repeat if you try a new profile?

**Comment by qumberrizvi** [comment]
> @qumberrizvi Hi Does the problem repeat if you try a new profile?

Thank you for the hint. I did not try creating a new profile but re-installing the extension seems to have fixed it.
