### ISSUE TITLE
in Youtube Ad Aguard was blocked

### ISSUE THREAD

**Issue by Legarad** [AdguardTeam/AdguardBrowserExtension#1649]
Normally it worked well for me last week, but now the Youtube programs are not blocked by the extension and the worst case is that the Skip Advertising Button is blocked if the extension is active.

Adguard Extension Version  3.4.31 
Chrome 83.0.4103.97

**Comment by chz816** [comment]
Same problem here: start to see the ad page on YouTube: it is a blank white page with "Skip Ad" tap. Start to have this problem since this Monday.

**Comment by Walkerby** [comment]
Similar problem: when it is ad time youtube shows a playback error

**Comment by zzebrum** [comment]
@Legarad @chz816 @Walkerby guys, it is a new ad experiment on youtube, it is not available for all Youtube users and so far not reproducible on our side. Please enable Experimental filter in Other filters group.

**Comment by gitguys** [comment]
> @Legarad @chz816 @Walkerby guys, it is a new ad experiment on youtube, it is not available for all Youtube users and so far not reproducible on our side. Please enable Experimental filter in Other filters group.

I'm seeing plenty of other people complaining about this issue on Reddit as well saying it's happening with Adguard and other blockers.

For myself In recent weeks despite running Adguard, Youtube was showing a stationary washed out image of an ad that was mostly white or very light grey and I had to click a skip ad button to watch videos.  After enabling the Experimental filter as you advised the videos are now playing right away without any skip button at least for now.

**Comment by chz816** [comment]
> > @Legarad @chz816 @Walkerby guys, it is a new ad experiment on youtube, it is not available for all Youtube users and so far not reproducible on our side. Please enable Experimental filter in Other filters group.
> 
> I'm seeing plenty of other people complaining about this issue on Reddit as well saying it's happening with Adguard and other blockers.
> 
> For myself In recent weeks despite running Adguard, Youtube was showing a stationary washed out image of an ad that was mostly white or very light grey and I had to click a skip ad button to watch videos. After enabling the Experimental filter as you advised the videos are now playing right away without any skip button at least for now.

I've enabled the experimental filter but it doesn't work for me. I have the same issue as yours. But my problem is on Safari.

**Comment by gitguys** [comment]
> > > @Legarad @chz816 @Walkerby guys, it is a new ad experiment on youtube, it is not available for all Youtube users and so far not reproducible on our side. Please enable Experimental filter in Other filters group.
> > 
> > 
> > I'm seeing plenty of other people complaining about this issue on Reddit as well saying it's happening with Adguard and other blockers.
> > For myself In recent weeks despite running Adguard, Youtube was showing a stationary washed out image of an ad that was mostly white or very light grey and I had to click a skip ad button to watch videos. After enabling the Experimental filter as you advised the videos are now playing right away without any skip button at least for now.
> 
> I've enabled the experimental filter but it doesn't work for me. I have the same issue as yours. But my problem is on Safari.

Working in Safari for me.  Try restarting Safari.  Also, I'm using a nightly build of Adguard so YMMV.

**Comment by zzebrum** [comment]
sorry, that rule was moved to Annoyances filter. Also logging out from the account - is a temporary solution.

**Comment by chz816** [comment]
> sorry, that rule was moved to Annoyances filter. Also logging out from the account - is a temporary solution.

Should we enable all the filters in the Annoyance filter?

**Comment by gitguys** [comment]
> > > @Legarad @chz816 @Walkerby guys, it is a new ad experiment on youtube, it is not available for all Youtube users and so far not reproducible on our side. Please enable Experimental filter in Other filters group.
> > 
> > 
> > I'm seeing plenty of other people complaining about this issue on Reddit as well saying it's happening with Adguard and other blockers.
> > For myself In recent weeks despite running Adguard, Youtube was showing a stationary washed out image of an ad that was mostly white or very light grey and I had to click a skip ad button to watch videos. After enabling the Experimental filter as you advised the videos are now playing right away without any skip button at least for now.
> 
> I've enabled the experimental filter but it doesn't work for me. I have the same issue as yours. But my problem is on Safari.

Enabling the experimental filter worked, but now I've found it was only temporary.  The problem is back today.  So I suppose there's still no good fix for it.  Getting "skip ad" with white background again.

![Screen Shot 2020-06-23 at 6 14 24 PM](https://user-images.githubusercontent.com/11050768/85480780-cc384280-b57d-11ea-978d-507240444c48.png)

**Comment by ruchern** [comment]
> > > > @Legarad @chz816 @Walkerby guys, it is a new ad experiment on youtube, it is not available for all Youtube users and so far not reproducible on our side. Please enable Experimental filter in Other filters group.
> > > 
> > > 
> > > I'm seeing plenty of other people complaining about this issue on Reddit as well saying it's happening with Adguard and other blockers.
> > > For myself In recent weeks despite running Adguard, Youtube was showing a stationary washed out image of an ad that was mostly white or very light grey and I had to click a skip ad button to watch videos. After enabling the Experimental filter as you advised the videos are now playing right away without any skip button at least for now.
> > 
> > 
> > I've enabled the experimental filter but it doesn't work for me. I have the same issue as yours. But my problem is on Safari.
> 
> Working in Safari for me. Try restarting Safari. Also, I'm using a nightly build of Adguard so YMMV.

Safari works fine. The ads seem to appear on Chromium-based browsers so far.

**Comment by chz816** [comment]
> > > > > @Legarad @chz816 @Walkerby guys, it is a new ad experiment on youtube, it is not available for all Youtube users and so far not reproducible on our side. Please enable Experimental filter in Other filters group.
> > > > 
> > > > 
> > > > I'm seeing plenty of other people complaining about this issue on Reddit as well saying it's happening with Adguard and other blockers.
> > > > For myself In recent weeks despite running Adguard, Youtube was showing a stationary washed out image of an ad that was mostly white or very light grey and I had to click a skip ad button to watch videos. After enabling the Experimental filter as you advised the videos are now playing right away without any skip button at least for now.
> > > 
> > > 
> > > I've enabled the experimental filter but it doesn't work for me. I have the same issue as yours. But my problem is on Safari.
> > 
> > 
> > Working in Safari for me. Try restarting Safari. Also, I'm using a nightly build of Adguard so YMMV.
> 
> Safari works fine. The ads seem to appear on Chromium-based browsers so far.

I use Safari and it bothers me on both Safari and Chrome.

**Comment by erkinalp** [comment]
Also reproducible by me.

**Comment by swanknight** [comment]
I'm having the same issue on Firefox 80. Turning on the experimental filter seems to have solved this issue...for now.
PS: I tested this with uBlock Origin and I didn't run into this issue.

**Comment by KosiMazakii** [comment]
Same here, experimental filter enabled, but on Microsoft Edge 85.0.564.51 (official x64) got this annoying skip add on YT.

**Comment by swanknight** [comment]
I'm still getting this issue even with the experimental filter enabled.
