### ISSUE TITLE
make this thing stop blocking Pornhub

### ISSUE THREAD

**Issue by DialexG91** [AdguardTeam/AdguardBrowserExtension#1650]
because when I try to open I get ERR_CONNECTION_RESET, it's a great idea, is it not?

**Comment by zzebrum** [comment]
@DialexG91 hmm, AdGuard browser extension could not cause such error. 
What AdGuard version do you have?

**Comment by DialexG91** [comment]
the last one

**Comment by zzebrum** [comment]
@DialexG91 I mean build number? Also, please, export your AdGuard settings and send it to devteam[at]adguard[dot]com

**Comment by DialexG91** [comment]
it's version 3.4.31, but I think I finally fixed disabling some filters like Malware Domain Blocklist and others
