### ISSUE TITLE
Redirect to blocked site - no filtering!

### ISSUE THREAD

**Issue by WrongBit** [AdguardTeam/AdguardBrowserExtension#1651]
I have filter `/yandex/` and it works well when some page refers to anything on domain yandex.ru;
But when I visit `fishki.net`, its pages temporarily redirect browser on yandex.ru and then back! And it works! Why redirects do not filtered by ADG? It's total fail if any hack can simply "redirect" me to dangerous page!

**Comment by slavaleleka** [comment]
@WrongBit 
could you please describe how we can reproduce the issue? 

what do you mean "I have filter /yandex/ and it works well"? what have you done?

**Comment by WrongBit** [comment]
I thought my message contains enough info. At least for people who understand what "advert blocker" is.
Thru Settings->User rules I added rule `/yandex/` - it's simple regular expression. And **it works** - meaning ADG blocks any content coming from site "yandex.ru".
But when I visit `http://old.fishki.net/recent/`, this site has "trick": from main page they redirect browser to yandex.ru WHAT MUST NOT HAPPEN if you have rule `/yandex/` - isn't it obvious? But ADG just pass browser to yandex.ru site. WHY? This site is BLOCKED BY MY RULE.

I made investigation and found that fishki.net has JS which executes `location = 'yandex.ru/....' ` - this redirection BYPASS any rules and drop me on yandex.ru site. This is mistake of ADG - it do NOT prevent redirection, despite it has rule `/yandex/`.

**Comment by slavaleleka** [comment]
your regexp user rule is a simple blocking rule and it works for blocking requests, but it should not prevent inline script execution (no matter what's in that scripts). for such purposes we have [Scriptlets](https://github.com/AdguardTeam/Scriptlets#scriptlets), I suggest you to try them

**Comment by WrongBit** [comment]
Wrong answer. A whole meaning of "blocking" is to prevent ANY loading of "wrong" resources! Doesn't matter from where loading was initiated - by click, by script, by page content... all of 'em should go thru "central dispatcher" and blocked accordingly.
