### ISSUE TITLE
Devtools does not work on some webpages

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/AdguardBrowserExtension#1653]
**where:**
https://thegrammarexchange.infopop.cc/topic/evidence-in-plural-form#:~:text=Evidence%20in%20plural%20form,about%20a%20piece%20if%20evidence

**what:**
it should be AdGuard tab there but it isn't
https://uploads.adguard.com/slbdzdrkds4u.png

- AdGuard browser extension 3.4.31 
- Chrome 83.0.4103.116
- macOS 10.15.5

**Comment by maximtop** [comment]
I've checked on the last version and it seems to be working.

**Comment by Alex-302** [comment]
I can confirm that. Random bug.
