### ISSUE TITLE
Integration with Adguard for Windows

### ISSUE THREAD

**Issue by Bushido1** [AdguardTeam/AdguardBrowserExtension#1654]
When the Adguard for Windows is working in the background (the icon not visible in the system tray) and I click on the settings icon of Adguard Browser Assistant in the Opera, nothing happens.
When the icon of Adguard for Windows is visible in the system tray and I click on the settings icon of Adguard Browser Assistant in the Opera, settings screen of Adguard for Windows appears.
When the Adguard for Windows is working in the background (the icon not visible in the system tray) and I click on the settings icon of AdGuard ad blocker extension in the Chrome, settings screen of AdGuard ad blocker extension appears in a new tab.
Why I cannot see a settings screen of Adguard for Windows if I click on the settings buttons of extensions and when the Adguard for Windows is working in the background.

**Comment by TheHasagi** [comment]
@Bushido1 

Hello, cannot reproduce the state you are talking about when AdGuard is closed (service is running), all works as usual. Can you try to re-install the extension and check again? Unfortunately, for now, the option that can open AdGuard main window from the extension is disabled.

**Comment by Bushido1** [comment]
@TheHasagi 

Hello, if this option is disabled, then all works as usual. I was surprised that a settings button of extensions did not work.
Also, why the user created rules list is not synchronised with the one in the Adguard for Windows with Chrome? Extension for Opera uses the list from Adguard for Windows? Blocked elements in Chrome appear only in the list of Chrome extension.
Perhaps it is wise to synchronise the rules list in all your products like you do with the activation key?

**Comment by TheHasagi** [comment]
It will be implemented soon. If you mean the integration between the browser extension and  AdGuard for Windows, then the rules apply only to those found in AdGuard for Windows.
