### ISSUE TITLE
Google/Gmail/Youtube (Log-in) problems

### ISSUE THREAD

**Issue by odessing** [AdguardTeam/AdguardBrowserExtension#1658]
### Prerequisites

- [v] I am running the latest version
- [v] I checked the documentation and found no answer
- [v] I checked to make sure that this issue has not already been filed
  - Did find some stuff about adds on youtube

### Issue Details

- **AdGuard version:**
  - Version 3.4.31
- **Browser and version:**
  - Firefox 77.0.1
- **Operating system and version:**
  - Manjaro Linux XFCE
- **Filters you use in AdGuard:**
  - Ad blocking
  - Other
  - Language-specific
- **Stealth Mode settings:**
  - None
- **Other browser extensions:**
  - None

### Expected Behavior

Able to log-in to any google service like Youtube and Gmail. Google uses 2 separate log-in screens: first for the username, second for the Password. The password one is not working. Youtube videos playing without adds. With the applicable google websites whitelisted in adguard settings everything is working again. 

### Actual Behavior

- Not able to log-in on Youtube and Gmail
  - I can enter a username but instead of a password screen I get an "Oops something went wrong, try again"
- Youtube videos are not loading with AdGuard enabled
  - Black background with spinning circle
- Youtube videos sometimes have a skip add video before the video
- Everything works with the Google websites whitelisted or AdGuard disabled
  - Also tried deleting all Firefox cache and cookies, but that did not work

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

I do enjoy AdGuard more than other Ad blockers :)

**Comment by jsjain** [comment]
I am having the same problem in chrome and my youtube videos are also not loading they are getting blocked by adguard.
`https://r5---sn-ci5gup-cag6.googlevideo.com/videoplayback?....`

**Comment by zzebrum** [comment]
I was able to reproduce the issue described in the comment just once so far. @jsjain try to disable filter in the AdGuard one by one and check if it helps.

@odessing youtube issue you've described most probably will be fixed here: https://github.com/AdguardTeam/AdguardFilters/issues/58065 just needed to wait until filters devs add a rule for youtube.  And about problem with logging in google account - can you try to reproduce the problem in another browser? also, try to disable filters one by one to check if it helps.

**Comment by odessing** [comment]
@zzebrum The issue was resolved by reinstalling the AdGuard extension on this specific PC. I did not encounter similar problems on my other 2 PC's.

**Comment by jsjain** [comment]
Sorry to post on closed issue but, @zebrum Yes it works fine after disabling the adguard base filter, but should those valid google links be whitelisted by default ??
Right now Igot it working by manually whitelisting those links.

**Comment by zzebrum** [comment]
@jsjain do you have an easy way to reproduce the issue? Youtube is working ok on my side now (

**Comment by jsjain** [comment]
@zebrum Not sure why is it occurring it in my system, but as I said its working fine by whitelisting `||.*googlevideo.com` links for youtube to work fine.
Moreover I started working fine again after reinstalling chrome on my mac.
