### ISSUE TITLE
Filter List Updates Not Working

### ISSUE THREAD

**Issue by hl2guide** [AdguardTeam/AdguardBrowserExtension#1659]
### Issue Details

- **AdGuard version:**
  - AdGuard v3.4.31
- **Browser and version:**
  - Vivaldi 3.1.1929.45 (Stable channel) (64-bit)
- **Operating system and version:**
  - Windows 10
- **Filters you use in AdGuard:**
  - Ad Blocking, Privacy, Social Widgets, Annoyances, Security
- **Stealth Mode settings:**
  - none
- **Other browser extensions:**
  - none

### Expected Behavior

I've set the "Filters update interval" to 1 hour and expect an update check to be done every hour.

### Actual Behavior

No auto-updates for filters occur ever (I have to manually do it in the settings area).

**Comment by adgkart** [comment]
Hi! Could you please make the following?

- In AdGuard AdBlocker settings set “Filters update interval” as 1 hour
- Then right-click on AdGuard AdBlocker icon
- Tap on “Manage Extensions”
- Turn on “Developers mode” in the top right corner
- Tap on “Details” in AdGuard AdBlocker area
- Tap on “background.html”
- Choose “Console” view
- Wait for a couple of hours
- Make screenshots and link them to this conversation

Thank you!
