### ISSUE TITLE
Adguard extension prevents Waterfox browser from showing websites content

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardBrowserExtension#166]
Problem was reproduced in Waterfox v.43.0.4 with Adguard extension v.2.1.5. The extension needs to be disabled in order to see any pictures, text etc on any website.

http://forum.adguard.com/showthread.php?9114

**Comment by Bohdan-SUP** [comment]
Have a ticket as well - QDO-224-39053

**Comment by ameshkov** [comment]
Temporary solution until it is fixed.

Install Adguard v2.0.20:
https://addons.mozilla.org/ru/firefo...version-2.0.20

Disable Autoupdate for it.
