### ISSUE TITLE
 "Block ads on this website" is not working

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardBrowserExtension#1660]
Здравствуйте,
Не работает ручная блокировка элемента на всех доменах Яндекса.
Прошу пофиксить.

**Comment by zzebrum** [comment]
Опишите проблему подробнее, пожалуйста.

**Comment by gitter10101** [comment]
Здравствуйте, 
1. Захожу на страницу Яндекс.
2. Открываю адгуард
3. Нажимаю на кнопку "заблокировать рекламу на сайте"
4. Ничего не происходит. Мень блокирования элемента не появляется.

**Comment by adgkart** [comment]
Добрый день!

Пришлите, пожалуйста, дополнительную информацию:

- AdGuard version
- Browser and version
- Operating system and version
- Filters you use in AdGuard
- Stealth Mode settings
- Other browser extensions

**Comment by pipka1234** [comment]
> Добрый день!
> 
> Пришлите, пожалуйста, дополнительную информацию:
> 
> * AdGuard version
> * Browser and version
> * Operating system and version
> * Filters you use in AdGuard
> * Stealth Mode settings
> * Other browser extensions
**_Версия адгуард:_** 3.4.31
**_Браузер:_** Yandex browser 20.6.0
**_ОС:_** Android 7
**_Фильтры:_** 
_Ad Blocking:_
AdGuard Base, 
AdGuard Mobile Ads, 
EasyList, 
Peter Lowe's Blocklist
_Privacy:_
AdGuard Tracking Protection, 
EasyPrivacy, 
Fanboy's Enhanced Tracking List, 
Fanboy Anti-Facebook List, 
Fanboy's Anti-thirdparty Fonts
_Social Widgets:_
AdGuard Social Media, 
Fanboy's Social Blocking List
_Annoyances:_
AdGuard Annoyances, 
Fanboy's Annoyances, 
Web Annoyances Ultralist, 
Adblock Warning Removal List, 
I don't care about cookies, 
EasyList Cookie List
_Security:_
Malware Domains Blocklist, 
Spam404, 
NoCoin Filter List
_Language-specific:_
AdGuard Russian, 
RU AdList, 
RU AdList: Counters, 
RU AdList: BitBlock
**_Антитрекинг:_**
Hide your search queries, 
Send Do-Not-Track header, 
Strip URLs from tracking parameters, 
Self-destructing first-party cookies (4320), 
Self-destructing third-party cookies (0), 
Block WebRTC, 
Hide your Referrer from third-parties
_**Другие расширения:**_
Их нет

**Comment by maximtop** [comment]
сайты яндекса динамически генерируют новые классы и тэги, которые использует селектор элементов ассистента
поэтому при следующей загрузке страницы, если яндекс сгенерирует новые элементы и классы, то правила не применяются 

если у вас еще возникнут какие-то вопросы, то пишите
