### ISSUE TITLE
Removing obsolete filters REQUEST

### ISSUE THREAD

**Issue by a-privacy-conscious-user** [AdguardTeam/AdguardBrowserExtension#1662]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ x ] I am running the latest version
- [ x ] I checked the documentation and found no answer
- [ x ] I checked to make sure that this issue has not already been filed

### Problem Description

AdGuard offers obsolete filters (for example Safari filter list, prebake and antiadblock killer)

### Proposed Solution

AdGuard should only offer up to date filters

**Comment by zzebrum** [comment]
Obsolete filters will be removed soon.
