### ISSUE TITLE
Integration to AdguardHome

### ISSUE THREAD

**Issue by superm1** [AdguardTeam/AdguardBrowserExtension#1667]
# Problem Description
Currently the extension has no idea that Adguard Home is installed on the network.  Generally this is OK, but the problems arise when AdguardHome is blocking a domain and I momentarily need it in the browser.  In this circumstance I would like to remotely turn on/off Adguard home when I hit the pause button on the extension.

### Proposed Solution

As Home Assistant has support to login to your Adguard Home instance and then offer switches to remotely turn on/off for the network I feel the same thing should be possible for the extension.  Let it log into that same instance and then let pause sync up.
https://www.home-assistant.io/integrations/adguard/

**Comment by adgkart** [comment]
Hi! Here we are limited with browser extension possibilities. Actually, the extension could mostly act only inside the browser.  You can add AdGuard Home to your favorites bar to have fast access to needed options.

**Comment by superm1** [comment]
@adgkart thanks for response.  Right, I realized the extension is limited in acting inside the browser, but I was thinking specifically that extension might be able to have a section to put AdguardHome login credentials for your local network, and stay logged in and communication with AdguardHome.  So if you turned off in the browser for the page it could also just change it for the network at the same time.

For now, yes I will just keep a quick link to it in my favorites bar.
