### ISSUE TITLE
Предложение по улучшению сервиса

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardBrowserExtension#1669]
Здравствуйте,
Предлагаю добавить функцию которая будет блокировать Flash, Java и JavaScript в настройки антитрекинга.
Заранее спасибо!

**Comment by maximtop** [comment]
Здравствуйте. 

Так как эти функции уже встроены в браузер и политика хрома не поощряет использование множества различных функций в одном расширении ([документация](https://developer.chrome.com/extensions/single_purpose)), мы не будем их добавлять в адблокер.

В любом случае, большое спасибо за предложение. Пишите нам еще, если найдете какие-то баги или у вас появятся другие предложения.
