### ISSUE TITLE
Malwarebytes blocked Adguard Trojan

### ISSUE THREAD

**Issue by ngdaniel1** [AdguardTeam/AdguardBrowserExtension#1672]
I have attached the text from Malwarebytes about the Adguard Trojan pop up that was blocked.

Not sure if this is a bug.  It probably isn't but I thought I'd report it anyway.  It was blocked as soon as chrome browser was started with the Adguard extension.

[Adguard Trojan.txt](https://github.com/AdguardTeam/AdguardBrowserExtension/files/4996923/Adguard.Trojan.txt)

Thank you.

**Comment by zzebrum** [comment]
@ngdaniel1 thank you very much! We've reported the issue to the Malwarebytes. You may do the same to speed things up a little.
