### ISSUE TITLE
you are missing a key feature "apply these filters on this selected domain too"

### ISSUE THREAD

**Issue by minanagehsalalma** [AdguardTeam/AdguardBrowserExtension#1676]
here is the problem that led me to thinking of this 

there is a site that is regularly changing it's domain so the fix would be just adding this *.staticword.* to it's rules .. as this the only static thing in the domain name( but that didn't seem to work so i used subname.staticword.* even tough the sub name changes too ) 

i have tried to copy the rules from the already working domain(using the filtering log option and selecting the blocked filter then copy the rule) and change it to subname.staticword.* and pasted it to user rules but couldn't get it to work(nothing changed at all like i haven't added anything) even though that are showed as blocked like the other domain  in the filtering log.

so i think that i missed a filter or two and maybe messed some text so i though wouldn't it be hell easier for the dev to have an apply filters to a specified site option when vising a site that's there is a similar one from it that the adblock doesn't work on or even a second domain to the site.

as you can't just go to whatever list that's being used to block ads on a specific site and edit it directly to make it include your selected ...  but unfortunately you have to open the filtering log and copy each rule one a time  and edit it then paste it in the user rules which isn't a job for everyone and would surely be done incorrect in some way.

so you can go to the site that the adblock is working just fine on and choose the "apply these filters to a selected site" option to type the domain name or wild card to apply them on another domain of the site or even a one that not very different from it in the terms of anti ad blocking Mechanism.

which would free you of a lot of reported issues cased of the same problems ( similar site - the site have more than one domain or regularly changes it  )

and you can get the extension to catch these actions and update the db with them( i am not sure how will that work)

[the site that lead me to this idea ](https://github.com/AdguardTeam/AdguardFilters/issues/61283)

sorry for making it long but i wanted to be understood as much as possible.
thanks

**Comment by krystian3w** [comment]
`Subdomain` is not a problem if you omit this.

Loading a solution under a narrow group of domains with exclude narrowing it to domains is unlikely to pass.

Such a generic solution will pass in Nano Defender (e.g abort `anOption` / `app_vars.force_disable_adblock`), but not on the uBO/Nano Adblocker/AdGuard filter lists.

> https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#wildcard-for-tld

As long as the `egy`​`best` / `vid`​`stream` does not start entering strange numbers in the domain name e.g.:
- `evil-egybest34.live`
- `evil-vidstream34.live`

 the symbol simplifying public suffix should be enough.

---

I also don't understand where you'd like such a button put "<kbd>add this domain to the filters in the custom filters section</kbd>".

**Comment by minanagehsalalma** [comment]
> the symbol simplifying public suffix should be enough.

huh ? 



> where you'd like such a button put "add this domain to the filters and save my modification in the custom filters section".

in the actions menu when you click on the extension on the site that you want to apply the filters from.

and it's apply not add  "apply these filters on a selected domain"

> > https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#wildcard-for-tld

i know about that but i didn't know that's meant for Top-level domain part only.

**Comment by adgkart** [comment]
Hi! It is not actually functionality of the application and in most cases such requests can be easily handled by cosmetic rules inside filters

**Comment by krystian3w** [comment]
He rather wants to easily export logger filters and easily change domains in it to work on another domain.

Partly, an error with no action may be due to a different anti-blocking script structure - hence copying or making a global filter makes no sense.

**Comment by minanagehsalalma** [comment]
> He rather wants to easily export logger filters and easily change domains in it to work on another domain.
> 
> Partly, an error with no action may be due to a different anti-blocking script structure - hence copying or making a global filter makes no sense.

so it's a no ?
