### ISSUE TITLE
Prevent blocking Databases

### ISSUE THREAD

**Issue by colorgold** [AdguardTeam/AdguardBrowserExtension#1688]
### Issue Details

- **AdGuard version:** Version 3.5.12
  - 
- **Browser and version:**Chrome Version 84.0.4147.135 (Official Build) (64-bit)
  - 
- **Operating system and version:** Windows 10 Home version 1903
  - 
- **Filters you use in AdGuard:**Ad Blocking, Privacy, Other, Language-specific
  - 
- **Stealth Mode settings:**Not enabled
  - 
- **Other browser extensions:**
  - 

### Expected Behavior
I imported Firebase products from the CDN on my website. The page is expected to load the scripts to allow users to login and access their account.

### Actual Behavior
AdGuard AdBlocker blocks the script from loading thus resulting in this error: `Failed to load resource: net::ERR_BLOCKED_BY_CLIENT firebase-app.js:1/ Uncaught ReferenceError: firebase is not defined`. Users are not able to click anywhere on the page because of this. I found that AdGuard was responsible when I turned it off and reload it the page. I did not have this problem until the day of this report.

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/45986859/90841055-4c321d00-e321-11ea-8a3d-fc8d8d94a4d1.png)

</details>

**Comment by maximtop** [comment]
Hi, thank you for your report.
Can you provide a URL to the website where the firebase script is blocked?
