### ISSUE TITLE
Google Chrome Helper (Renderer) 100% CPU with Adguard on The Verge

### ISSUE THREAD

**Issue by lapcat** [AdguardTeam/AdguardBrowserExtension#1689]
AdGuard AdBlocker 3.5.12 with Google Chrome 84.0.4147.135 on macOS 10.14.6

On this page, when Adguard is enabled, I'm seeing 100% CPU usage in Google Chrome Helper. (My MacBook Pro fans spin up.) When I disable Adguard, it goes back to normal.

https://www.theverge.com/2020/8/21/21396313/apple-fortnite-lawsuit-emails-app-store-ban-epic

Ad Blocking, Privacy, Social Widgets, and Annoyances filters are enabled. Stealth mode is not enabled.

**Comment by zzebrum** [comment]
@lapcat please update filters, it should be ok now.

**Comment by lapcat** [comment]
Thanks! Confirmed, it seems to be fine now with updated filters.

**Comment by AdamWr** [comment]
@lapcat Could you please add the rule below to user filter and then check if you can still reproduce this issue?
Rule:
```
theverge.com#%#(function(){if(-1==document.cookie.indexOf("_chorus_privacy_consent")&&document.location.hostname.includes("theverge.com")){var c=new Date, d=c.getTime(), date = new Date(d + 365 * 60 * 60 * 1000); document.cookie="_chorus_privacy_consent="+d+"; path=/; expires=" + date.toUTCString(), location.reload()}})();
```

**Comment by lapcat** [comment]
> @lapcat Could you please add the rule below to user filter and then check if you can still reproduce this issue?
> Rule:
> 
> ```
> theverge.com#%#(function(){if(-1==document.cookie.indexOf("_chorus_privacy_consent")&&document.location.hostname.includes("theverge.com")){var c=new Date, d=c.getTime(), date = new Date(d + 365 * 60 * 60 * 1000); document.cookie="_chorus_privacy_consent="+d+"; path=/; expires=" + date.toUTCString(), location.reload()}})();
> ```

This new rule seems fine in my testing.

**Comment by AdamWr** [comment]
I will add this rule, thank you for checking it.
