### ISSUE TITLE
Spyware 4 false positive 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardBrowserExtension#169]
http://www.spyware-fighters.com/

![image](https://cloud.githubusercontent.com/assets/15856304/13143642/fdc8ca72-d64d-11e5-962f-2e738f3ec22d.png)

ZID-205-31127

**Comment by ameshkov** [comment]
@vbagirov please report a false positive

**Comment by evgeniy-ADG** [comment]
https://github.com/AdguardTeam/AdguardForWindows/issues/961

**Comment by vbagirov** [comment]
Also sent them a message by the way.
