### ISSUE TITLE
macOS Big Sur Beta 5 Youtube

### ISSUE THREAD

**Issue by mclgoerg** [AdguardTeam/AdguardBrowserExtension#1692]
It seems like that Adguard is causing an issue on macOS Big Sur Beta 5 and YouTube videos.
Issue: Videos are loading forever
Fix-> Disable adguard while on YouTube

**Comment by zzebrum** [comment]
@mclgoerg sorry for the delay! What AdGuard version do you have installed? What filters are enabled? 

Also, can you provide us with the screenshot?

**Comment by mclgoerg** [comment]
Seems like it got fixed. I am using V2.5.0.844 nightly.
