### ISSUE TITLE
||example.org^ doesn't block the main page

### ISSUE THREAD

**Issue by curbengh** [AdguardTeam/AdguardBrowserExtension#1693]
### Issue Details

- **AdGuard version:**
  - 3.5.12
- **Browser and version:**
  - Chrome 84
  - Firefox 80
- **Operating system and version:**
  - Windows 10
- **Filters you use in AdGuard:**
  - Base filter
- **Stealth Mode settings:**
  - 
- **Other browser extensions:**
  - 

### Expected Behavior

`||example.org^` should block the whole website.

### Actual Behavior

`||example.org^` only blocks site assets (e.g. example.org/main.css)
`||example.org$all` is required to block the whole website.

**Comment by zzebrum** [comment]
@curbengh that is how simple rules work: https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#sub-requests
