### ISSUE TITLE
Forvo.com play audio button doesn't work

### ISSUE THREAD

**Issue by JonDous** [AdguardTeam/AdguardBrowserExtension#1695]
https://forvo.com/word/%E4%BD%9C%E6%88%A6/#ja

Firefox + AG. Without filtration everything's okay. With is nothing works.

**Comment by TheHasagi** [comment]
@JonDous 

Looks like some of the filters are breaking up the website. Try to use disable them one by one to check if it helps. With default filters and settings this issue is not reproducible.

**Comment by JonDous** [comment]
> @JonDous
> 
> Looks like some of the filters are breaking up the website. Try to use disable them one by one to check if it helps. With default filters and settings this issue is not reproducible.

Today it works🤷‍♂️. Sometimes it stops. It seems the site's updates break the page with filters, after filter gets update and everything become okay. During the few weeks it repeats again. Please tell me how to disable the filter which breaks the site. Only this filter not other which remove ads. I mean when I determine which one is a problem, how to disable only it.

**Comment by Chinaski1** [comment]
@JonDous 
You can find out this information through the filter log. Open it and try to go to the site. Blocked requests should appear there, you can unlock them directly from the extension. 
It is also not a good idea to use a large number of third-party filters. Filtering rules can be overlapping and prevent the site from working properly.
