### ISSUE TITLE
BUG - Adguard Extension Custom Filter freezes Chrome and doesnt load websites

### ISSUE THREAD

**Issue by Soulweave** [AdguardTeam/AdguardBrowserExtension#1697]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [YES] I am running the latest version
- [YES] I checked the documentation and found no answer
- [YES ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  -Browser extension version 3.5.12
- **Browser and version:**
  - Version 85.0.4183.83 (Official Build) (64-bit)
- **Operating system and version:**
  - Windows 10 Home Edition
- **Filters you use in AdGuard:**
  - Default Filters + Custom Filter - Custom Filter is from Steven Black Hosts - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews/hosts
- **Stealth Mode settings:**
  - Disabled
- **Other browser extensions:**
  - None

### Expected Behavior

Adding the Custom Filter and enable, browser should work like normal if no Custom Filter was added

### Actual Behavior

Shortly after adding, chrome just freezes when loading any website and becomes unresponsive

</details>

### Additional Information

The same happens on Firefox latest version when adding and enabling a custom filter

**Comment by ameshkov** [comment]
The current version of AdGuard browser extension does not accept hosts files as filter lists.

We may support them in the future updates, but anyways -- extension is not the ideal tool to apply blocklists that are supposed to be used by a network-level ad blocker like AdGuard Home.

**Comment by Soulweave** [comment]
Hi if this is the case, why is the option to add custom filters in adguard extension? If is not supported then you should rename and put an alert. see attached
![2020-09-09 15_45_19-Window](https://user-images.githubusercontent.com/68402270/92606782-9f114b80-f2b3-11ea-8e2e-85f53b81794d.png)
![2020-09-09 15_45_57-Window](https://user-images.githubusercontent.com/68402270/92606787-9fa9e200-f2b3-11ea-9e11-56e61710cf6b.png)

**Comment by ameshkov** [comment]
> Hi if this is the case, why is the option to add custom filters in adguard extension? If is not supported then you should rename and put an alert. see attached

Please don't confuse "FILTER LISTS" and "HOSTS LISTS", these are two different types of lists.

**Filter lists** -- like AdGuard Base filter or EasyList are supposed to be used in browser extensions like AdGuard.
**Hosts lists** -- are supposed to be used by network-level blocking software (DNS servers for instance).

Filter lists are supported by AdGuard extensions and you can add them as custom filters.

**Comment by Soulweave** [comment]
Thanks. this clarifies partially. However it is misleading the text within the extension. In comparison, uBlock Origin supports steven blacks host lists.

**Comment by beerisgood** [comment]
AdGuard doesn't update the following filter list:
https://raw.githubusercontent.com/Kees1958/W3C_annual_most_used_survey_blocklist/master/EU_US_most_common_trackers

Even a manual update check doesn't help.
See the date from yesterday:
![image](https://user-images.githubusercontent.com/9625159/99839177-961ddf80-2b6a-11eb-8f55-f50b340f044f.png)

**Comment by ameshkov** [comment]
> See the date from yesterday:

Most likely the filter content hasn't changed since yesterday

**Comment by beerisgood** [comment]
> Most likely the filter content hasn't changed since yesterday

It does. The problem exists for longer now

**Comment by maximtop** [comment]
This problem occurs because the filter does not follow the version format.
Version should be defined via integer number like `Version: 123` or in [semver](https://semver.org/) format `Version: 1.2.3`

I'm going to open an issue with the feature request to update filters when the filter checksum is changed if the version does not match the format.

**Comment by beerisgood** [comment]
@maximtop thanks! That solve it.
