### ISSUE TITLE
Facing error when visiting https://marketplace.visualstudio.com/publishers/Microsoft%20DevLabs

### ISSUE THREAD

**Issue by Jisu-Woniu** [AdguardTeam/AdguardBrowserExtension#1698]
### Issue Details

- **AdGuard version:**
  - 3.5.12
- **Browser and version:**
  - Firefox 81
- **Operating system and version:**
  - Windows 10
- **Filters you use in AdGuard:**
  -    Ad Blocking:
  -    AdGuard Base filter
  -    Privacy:
  -    AdGuard Tracking Protection filter
  -    Social Widgets:
  -    AdGuard Social Media filter
  -    Annoyances:
  -    AdGuard Annoyances filter
  -    Fanboy's Annoyances
  -    Adblock Warning Removal List
  -    Language-specific:
  -    AdGuard Chinese filter
  -    AdGuard Japanese filter
  -    EasyList China
  -    CJX's Annoyance List
  -    ChinaList+EasyList
  -    [Xinggsf Ad Blocking(https://gitee.com/xinggsf/Adblock-Rule/raw/master/rule.txt)](https://gitee.com/xinggsf/Adblock-Rule/raw/master/rule.txt)

- **Stealth Mode settings:**
  - 
![2020-09-09 (2)](https://user-images.githubusercontent.com/31986081/92589703-87df5780-f2cd-11ea-9c69-8e607fbf9e6f.png)

- **Other browser extensions:**
  - AdGuard Extra

### Expected Behavior
When visiting [https://marketplace.visualstudio.com/publishers/Microsoft%20DevLabs](https://marketplace.visualstudio.com/publishers/Microsoft%20DevLabs) 

![2020-09-09 (1)](https://user-images.githubusercontent.com/31986081/92589510-3767fa00-f2cd-11ea-9e82-93626896ebb6.png)

### Actual Behavior

![2020-09-09](https://user-images.githubusercontent.com/31986081/92589571-5070ab00-f2cd-11ea-82c2-e7814038b68e.png)

**Comment by Chinaski1** [comment]
Hello there!
 
If you disable that filters:
- Fanboy's Annoyances
- Adblock Warning Removal List
- Language-specific:
- AdGuard Chinese filter
- AdGuard Japanese filter
- EasyList China
- CJX's Annoyance List
- ChinaList+EasyList
- Xinggsf Ad Blocking (https://gitee.com/xinggsf/Adblock-Rule/raw/master/rule.txt)

Is the issue will be solved?

**Comment by zzebrum** [comment]
@Jisu-Woniu any updates? Also is there any errors in the browser console?

**Comment by Jisu-Woniu** [comment]
Solved, thank you anyway.

**Comment by Jisu-Woniu** [comment]
Still not solved.
![2020-09-15](https://user-images.githubusercontent.com/31986081/93209734-1bfb6400-f791-11ea-8d29-4b91dc5623dd.png)

**Comment by Jisu-Woniu** [comment]
If I add `@@||marketplace.visualstudio.com/_static/tfs/*` in my user-defined filter, it will work.
![result](https://user-images.githubusercontent.com/31986081/93212056-a85b5600-f794-11ea-9a4c-b91b022e2938.png)

**Comment by Jisu-Woniu** [comment]
Maybe I will send another issue to xinggsf.

**Comment by Chinaski1** [comment]
@Jisu-Woniu 
You need to allow the use in incognito mode for the extension AdGuard, open a private window, and check is the issue still persists?

**Comment by zzebrum** [comment]
@Jisu-Woniu you have quite a lot of browser extensions enabled and a lot of filters in AdGuard too. Most likely it is a compatibility problem or some rule breaks the page. The only way to find out is to disable extensions in the browser and leave only AdGuard filters enabled in the extension (Base, Tracking protection, Social media, Annoyances, and language-specific) and check if the problem persists.
