### ISSUE TITLE
[Feature request] Add blocked ads counter and other features to the extension in the 'Assistant mode'

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardBrowserExtension#170]
Прошу сделать работу расширения по умолчанию такой, чтобы пользовательский опыт после установки приложения не менялся: значок выглядел точно также, расширение указывало количество заблокированной рекламы; при блокировании рекламы или другого элемента, правило фильтрации записывалось в редактор фильтров (для последующего сохранения настроек) приложения Adguard.

ZRH-654-27878

**Comment by ameshkov** [comment]
> при блокировании рекламы или другого элемента, правило фильтрации записывалось в редактор фильтров (для последующего сохранения настроек) приложения Adguard.

Не понял, но ведь сейчас уже так работает?

**Comment by evgeniy-ADG** [comment]
Там дальше был вопрос о синхронизации, это, видимо, я его часть захватил. Да, сейчас всё именно так :) Хотят, чтобы расширение не синело, а показывала много полезной инфы.

**Comment by ameshkov** [comment]
Просто расширение не все видит, что делает программа, из-за этого счетчик просто будет меньше показывать, чем есть на самом деле.

Счетчик возможно будет вернуть когда мы реализуем механизм, с помощью которого помощник будет узнавать о количестве заблокированного. Тогда и в режим интеграции его можно будет добавить.

Пусть пока тогда этот фича реквест открытым повисит.
