### ISSUE TITLE
Convert combined ubo :style() and ExtendedCss

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/AdguardBrowserExtension#1702]
@krystian3w commented on [Tue Sep 08 2020](https://github.com/AdguardTeam/ExtendedCss/issues/114)

I try hide newsletter leftover on site `telewizja-cyfrowa.com` in right column (sidebar):

<details> <summary> screenshot </summary><br>

![obraz](https://user-images.githubusercontent.com/35370833/92507180-dd046600-f206-11ea-9d4c-b9f135b3a03a.png) |
--- |
`https://telewizja-cyfrowa.com/` |

</details>

by:

```
telewizja-cyfrowa.com###text-2 > .textwidget > p:nth-of-type(1):has-text(/[\w\W]{337}/):has-text(/Dołącz/):style(font-size: 0 !important;)
```

And filter does not work in AdGuard Addon and I suppose is no translated correct in FiltersRegistry:

> https://github.com/AdguardTeam/FiltersRegistry/commit/9dafde297a9a9dd6fadbc89cf854057e36d540e2#diff-aadf84ddda58c6ad55b8ceb5f0e975b3

For works is needed mark as ExtendedCSS manually:

```
telewizja-cyfrowa.com#?##text-2 > .textwidget > p:nth-of-type(1):has-text(/[\w\W]{337}/):has-text(/Dołącz/):style(font-size: 0 !important;)
```

But uBO no need this in own syntax.

---

related: https://github.com/AdguardTeam/FiltersRegistry/issues/381

---

@krystian3w commented on [Fri Sep 11 2020](https://github.com/AdguardTeam/ExtendedCss/issues/114#issuecomment-690894524)

OK, I suppose glitch by `:has-text(/[\w\W]{337}/)` or `:has-text(/wiadomosci\./)` = "`\`".

---

@slavaleleka commented on [Mon Sep 14 2020](https://github.com/AdguardTeam/ExtendedCss/issues/114#issuecomment-692106232)

@krystian3w 
is it possible to use `:style(...)` in ubo-whitelist rules?

---

@krystian3w commented on [Mon Sep 14 2020](https://github.com/AdguardTeam/ExtendedCss/issues/114#issuecomment-692159653)

@slavaleleka 

Yes by `#@#` (unless I misunderstood):

```
telewizja-cyfrowa.com#@##text-2 > .textwidget > p:nth-of-type(1):has-text(/[\w\W]{337}/):has-text(/Dołącz/):style(font-size: 0 !important;)
```

Also cover whitelist by:

* `#@$#`  with `:has(foo)` and `{ foo }` 
* `#@$?#` with `:has(foo)` and `{ foo }` 

`telewizja-cyfrowa.com#@$##text-2 > .textwidget > p:nth-of-type(1):has-text(.):has-text(/Dołącz/) { font-size: 0 !important; }`
`telewizja-cyfrowa.com#@$?##text-2 > .textwidget > p:nth-of-type(1):has-text(.):has-text(/Dołącz/) { font-size: 0 !important; }`

---

but my whitelist filter with regex is marked as no supported / invalid **by uBO**:

![obraz](https://user-images.githubusercontent.com/35370833/93104957-c64e8b00-f6ae-11ea-80da-1606ab1776c6.png)  |
--- |

```
telewizja-cyfrowa.com#@$##text-2 > .textwidget > p:nth-of-type(1):has-text(/[\w\W]{337}/):has-text(/Dołącz/) { font-size: 0 !important; }
telewizja-cyfrowa.com#@$?##text-2 > .textwidget > p:nth-of-type(1):has-text(/[\w\W]{337}/):has-text(/Dołącz/) { font-size: 0 !important; }
```

due by "`{337}`" in regex.

**Comment by krystian3w** [comment]
bump
