### ISSUE TITLE
Please make the browser extension's UI & UX mobile friendly on Firefox for Android

### ISSUE THREAD

**Issue by Neon329** [AdguardTeam/AdguardBrowserExtension#1703]
Firefox for Android (`Nightly 200925 18:01`) now supports AdGuard browser extension. But the user interface is not mobile friendly (see the screenshots). So the users who want to use AdGuard browser extension instead of some other content blockers this would help them a lot while navigating through the user interface. 

![Screenshot_20200926-055134~2](https://user-images.githubusercontent.com/70356738/94325712-61076d80-ffbd-11ea-8577-4c0d8732c1f5.png)
![Screenshot_20200926-055116~2](https://user-images.githubusercontent.com/70356738/94325729-72e91080-ffbd-11ea-8b15-9e3544bece4f.png)

**Comment by ameshkov** [comment]
It's indeed not mobile-friendly yet, but we're planning to fix this as a part of a huge refactoring that we're doing right now.
