### ISSUE TITLE
Add the ability turning on/off each user rule manually 

### ISSUE THREAD

**Issue by wernser412** [AdguardTeam/AdguardBrowserExtension#1707]
Agregar un boton de opción para habilitar o deshabilitar reglas de usuario y un boton para limpiar o borrar las reglas de usuario.

![2020_10_04_17 42 16](https://user-images.githubusercontent.com/53667212/95028891-7c334680-0669-11eb-8eae-28e2f9340f5e.jpg)

**Comment by XX-J** [comment]
Feature: Give us a checkbox option #278.

**Comment by Alex-302** [comment]
You can use `Ctrl-/` hotkey(like in Vscode).

**Comment by maximtop** [comment]
It looks like the topic starter needs checkboxes on mobile. I think it is not so easy to use shortcuts there.
