### ISSUE TITLE
for ca.investing.com, the market data cannot auto update. if whitelist this website, cannot show the web page

### ISSUE THREAD

**Issue by Sherman-Chata** [AdguardTeam/AdguardBrowserExtension#1708]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ *] I am running the latest version
- [ *] I checked the documentation and found no answer
- [ *] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 
- **Browser and version:**
  - 
- **Operating system and version:**
  - 
- **Filters you use in AdGuard:**
  - 
- **Stealth Mode settings:**
  - 
- **Other browser extensions:**
  - 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

I'm using Chrome extension, when visit https://ca.investing.com/etfs/proshares-trust-ultrapro-qqq , the data cannot auto update.

**Comment by zzebrum** [comment]
@Sherman-Chata what filters enabled in AdGuard settings?

**Comment by Sherman-Chata** [comment]
Sorry, please delete that issue report. I tried a lot of settings, finally, when I clean the Chrome data, everything works.

Thank you for response.

Best regards

Sherman
