### ISSUE TITLE
How to set custom/secure DNS of Adguard in Edge, Chrome, Firefox and in Windows 10

### ISSUE THREAD

**Issue by GauravSahare27** [AdguardTeam/AdguardBrowserExtension#1709]
Hello sir,

Recently Chromium based browsers came with secure DNS[available with 3 options Google DNS, Cloudflare and CleanBrowsing(Family Filter)] in settings>privacy, but I don't know how to set up AdGuard DNS? Firefox already provided this setting but with Cloudflare only, and when I set custom DNS in Windows 10 and click "verify", then troubleshooter window run but showing "troubleshooter could not verify network setting"
Actually I am sharing my Android smartphone internet connection to my Windows 10 laptop via Hotspot.
Please help me how to properly set up AdGuard DNS to terminate ads when we use one of them?

**Comment by zzebrum** [comment]
@GauravSahare27 
you need to use DoH URL: https://uploads.adguard.com/Settings_-_Security_2020-10-13_12-28-03.png

All URL for DoH servers can be found here: https://kb.adguard.com/en/general/dns-providers#adguard-dns
For your purpose, you need to use either Default or Family protection server.
