### ISSUE TITLE
Sometimes in youtube Nasty ads come please help adguard

### ISSUE THREAD

**Issue by ESTORI23** [AdguardTeam/AdguardBrowserExtension#1710]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 
- **Browser and version:**
  - 
- **Operating system and version:**
  - 
- **Filters you use in AdGuard:**
  - 
- **Stealth Mode settings:**
  - 
- **Other browser extensions:**
  - 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by ESTORI23** [comment]
BAD NASTY ADS COME

**Comment by zzebrum** [comment]
@ESTORI23 please, fill the form above 👆 
we need to know the information about your browser, AdGuard settings and steps to reproduce the problem.

**Comment by zzebrum** [comment]
reopen if needed
