### ISSUE TITLE
Adding exclusions for HTML rules from filtering log doesn't work in the extension for Firefox.

### ISSUE THREAD

**Issue by Sergey-Lyapin** [AdguardTeam/AdguardBrowserExtension#1712]
After clicking unblock button `$@$` exclusion doesn't appear in user rules.
<details>
<summary>Screenshot</summary>
<img src="https://user-images.githubusercontent.com/18536328/96701994-ed793600-1399-11eb-9436-4eb4865af1cb.png" />
</details>

Firefox Version 82.0 
Adguard Version 3.5.12

**Comment by maximtop** [comment]
Is this filter from user rules?
Can you write it here?

**Comment by Sergey-Lyapin** [comment]
No, it is from russian filter, check here [vsetv.com](http://www.vsetv.com)
`dengi.ua,vsetv.com,dt.ua,liga.net$$script[wildcard="*Xr=""zmc""+""track""*"][max-length="16000"]`

**Comment by AdamWr** [comment]
I can still reproduce it, so I guess it should be re-opened.

**Comment by Mohammadsaead69** [comment]
This is Microsoft edge and not Firefox,hey,what are you talking about’?

**Comment by Birbber** [comment]
@Mohammadsaead69 This issue is related to Firefox.
