### ISSUE TITLE
Allow managing the notification about filters update 

### ISSUE THREAD

**Issue by screenoman** [AdguardTeam/AdguardBrowserExtension#1717]

**Comment by screenoman** [comment]
Maybe I should have contacted AdGuard support?

**Comment by zzebrum** [comment]
@screenoman why did you close the issue? :) 
It is a valid feature request and we will think about how we could implement it.

**Comment by screenoman** [comment]
> @screenoman why did you close the issue? :)
> It is a valid feature request and we will think about how we could implement it.

Good to hear.  Thank you.

**Comment by screenoman** [comment]
I take it you guys are still thinking about how you could implement what I requested.  This is why I deleted the request.  I figured that "implementation" would look like this.  Nearly two months later and nothing but crickets.
