### ISSUE TITLE
[Chromium] detect BitTorrent INC Maelstrom

### ISSUE THREAD

**Issue by aspadistra** [AdguardTeam/AdguardBrowserExtension#172]
==================================
Maelstrom seems to be based on tweaked version of Chrome, but a few versions back. 
AG runs fine, as far as I can tell -- but the BT tweaks may or may not have affected its efficiency. 
==================================

Maelstrom	44.0.1.3 (Developer Build) (32-bit)

Revision	2363fffeece6a40ec011ac91a9d755552ea398a2

OS	Windows 

Blink	537.36 (@de6285633d870582ea87d3ae9484417f0848bf64)

JavaScript	V8 4.4.63.31

Flash	20,0,0,306

User Agent
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) 
Chrome/44.0.2403.157 Torrent/44.0.1.3 Safari/537.36

Command Line	"C:\Users\admin\AppData\Local\Maelstrom\Application\maelstrom.exe" --flag-switches-begin --disable-direct-write --enable-centered-app-list --enable-credential-manager-api --enable-download-resumption --enable-link-disambiguation-popup --enable-scroll-prediction --reduced-referrer-granularity --enable-spelling-auto-correct --flag-switches-end

Executable Path	C:\Users\admin\AppData\Local\Maelstrom\Application\maelstrom.exe

Profile Path	C:\Users\admin\AppData\Local\Maelstrom\User Data\Default

**Comment by ameshkov** [comment]
I suppose this is that browser:
http://project-maelstrom.bittorrent.com/

Isn't it just a Chromium with a bunch of extensions over it?

**Comment by Mizzick** [comment]
I see nothing to fix here.

**Comment by ameshkov** [comment]
I guess it is about testing, not fixing.

**Comment by gshumihin** [comment]
I've got an error:
<img src="http://content.screencast.com/users/shumegor/folders/Jing/media/bb5ffb11-7533-40d1-8538-abfb4e0edd2f/2016-04-13_1937.png" width="300">
This happens when new tab opens.

**Comment by gshumihin** [comment]
Looks like Adguard forks fine. And Maelstorm's feature works good for me too. So mentioned error is the only one suspicious thing i've seen.

**Comment by Mizzick** [comment]
Fixed
