### ISSUE TITLE
Whitelist rule per every single ad elements for filtered websites

### ISSUE THREAD

**Issue by MinkiDev** [AdguardTeam/AdguardBrowserExtension#1722]
Whitelist rule is currently available for domains.
It will be better if can be unblocked by element-by-element rules.

**Comment by zzebrum** [comment]
@MinkiDev not quite understand what do you mean. Can you explain with more details, please?

**Comment by MinkiDev** [comment]
apologize for making you confused.

I mean, whitelist works domain-global now.
![figure_a](https://user-images.githubusercontent.com/29994623/100236186-abcb4480-2f70-11eb-84a0-f69d29757032.png)

and this is what I expected,
![figure_b](https://user-images.githubusercontent.com/29994623/100236578-33b14e80-2f71-11eb-8a94-916f60ca7819.png)
(Whitelist with element-specific: block all ads except user-whitelisted elements)

So, I wonder is it possible technically, anyway.

**Comment by zzebrum** [comment]
@MinkiDev for this purpose, you need to use exceptions for cosmetic rules: https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#exceptions
