### ISSUE TITLE
Banners in adguard extension

### ISSUE THREAD

**Issue by SilentWarrior1** [AdguardTeam/AdguardBrowserExtension#1724]
### Issue Details

- **AdGuard version:**
  - < 3.5.23 >
- **Browser and version:**
  - Opera GX (core: 62.0.3331.52) x64 and Chromium Версия 74.0.3860.0 x32
- **Operating system and version:**
  - Windows 10 x64 1809 ltsc
- **Filters you use in AdGuard:**
  - Fanboy's Enhanced Tracking List, EasyPrivacy, Фильтр счетчиков и систем аналитики, Фильтр раздражителей, Fanboy's Annoyances, Web Annoyances Ultralist, Adblock Warning Removal List, NoCoin Filter List, DNS фильтр, BarbBlock, RU AdList, RU AdList: Counters.
- **Other browser extensions:**
  - Good Old Youtube, Enchancer for Youtube.

### Actual Behavior

spam banner in the adguard extension as in screenshot below

### Screenshots

< https://i.imgur.com/BnXpFvK.png >

Adguard, who's need to block ads, generating ads itself? are you kidding me?!

**Comment by zzebrum** [comment]
@SilentWarrior1 It's not exactly an ad, more like self-promotion (which has a slightly different status according to our Filter Policy). It's only visible if you click on the extension icon, and it never appears again once you've closed it. Also, it is only shown in our free products (browser extensions).
By the way, AdGuard blocks our own ads on websites and in search results equally well as with all other ads, we make no preference here.
