### ISSUE TITLE
Add new blocking/unblocking rule pattern without subdomain

### ISSUE THREAD

**Issue by Sergey-Lyapin** [AdguardTeam/AdguardBrowserExtension#1727]
Add new blocking/unblocking rule pattern without subdomain in filtering log

![Screenshot 2020-12-08 at 19 54 23](https://user-images.githubusercontent.com/18536328/101515760-c3062b00-398f-11eb-8d94-eadae83ebe32.png)

**Comment by Alex-302** [comment]
Already implemented
![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/8361299/e1e22926-312a-4ce5-92fd-8a426cd3af56)
