### ISSUE TITLE
[Enhancement] Offload all that filter work to some GPUs that have 100+ CPU units (non-specific shaders)

### ISSUE THREAD

**Issue by aspadistra** [AdguardTeam/AdguardBrowserExtension#173]
[Enhancement] 

Offload all that filter work to some GPUs that have 100+ CPU units (non-specific shaders). 

It may take the help of some of the GPU makers like AMD to provide a driver for this, and only GPU units made after 2012 should even be considered for this. 

There is a good demo of GPUs with respect to suitability for this on the YouTube with this

"T4D #84 - Pt 2 Bitcoin Mining, BFL ASIC vs FPGA vs GPU vs CPU"

found at 

[https://youtu.be/ae97jo4wtis](url)

Even if AG does not go this way, other filter software may go this way on MOBILES.

**Comment by aspadistra** [comment]
Addendum : 

Technically all ones needs is a GPU with Integer capability. 

GPU floating point capability is not a requirement for text filtering at all. 

This could make GPUs as old as 2008 useful for this kind of filtering, but as this would open up the field to hundreds of GPU model variations - and thus driver bloat - I am in principal not endorsing this idea.

**Comment by ameshkov** [comment]
There's no way we can do such thing from a browser extension.

You see, we are operating with a browser API inside a sandbox, created by the browser.
We just can't go out of that sandbox and use such low-level things like GPU.
