### ISSUE TITLE
YouTube search bar not clickable

### ISSUE THREAD

**Issue by F3000** [AdguardTeam/AdguardBrowserExtension#1730]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ x] I am running the latest version
- [ x] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 3.5.23
- **Browser and version:**
  - 
- **Operating system and version:**
  - 
- **Filters you use in AdGuard:**
  - Base Filter 
  - Lowe's blacklist 
  - Fanboy Tracking Filter 
- **Stealth Mode settings:**
  - no 
- **Other browser extensions:**
  - 

### Expected Behavior

Visit YouTube.Com and try to search after a text 

### Actual Behavior

I can't click in the search bar 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by Chinaski1** [comment]
@F3000 
Hello there!
I checked your situation in Google Chrome and Youtube search works as expected.
Please specify which browser you use (and its version) and also specify third-party extensions (if any).

**Comment by F3000** [comment]
ups yes i have forgotten this Info . 

I use Microsoft edge chromium v87 . 

Plugins only AdGuard and SendURL by link

**Comment by Chinaski1** [comment]
Do you have Custom Filter enabled?
It is advisable to turn it off before testing.

**Comment by F3000** [comment]
I have no custom filter enabled.

I found this today : 


https://techcommunity.microsoft.com/t5/articles/known-issue-adblock-causing-errors-on-youtube/td-p/1486882

**Comment by Chinaski1** [comment]
The issues do not seem to be related.
To clarify the situation, do you mean that [your search](https://uploads.adguard.com/Chinaskiug504.png) does not work with this combination of filters?
You can try to [find out](https://kb.adguard.com/en/technical-support/reporting-tool#solo) which of the configurations is broking the Youtube search

**Comment by Chinaski1** [comment]
Since the user has stopped responding, I am closing the task.
Reopen it if the problem recurs.
