### ISSUE TITLE
AdGuard is blocking JSitor.com domain for no reason

### ISSUE THREAD

**Issue by ashvin777** [AdguardTeam/AdguardBrowserExtension#1734]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 
- **Browser and version:**
  - 
- **Operating system and version:**
  - 
- **Filters you use in AdGuard:**
  - 
- **Stealth Mode settings:**
  - 
- **Other browser extensions:**
  - 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by Chinaski1** [comment]
Hello there!

Please provide more details:
- What version of the extension are you using?
- What browser and operating system are you using?
- What filters are enabled?
- Do you use third-party extensions?

With the default settings, the site will work as expected (extension version 3.5.25)

**Comment by Chinaski1** [comment]
Since the user has stopped responding, I am closing the task.  
Reopen it if the problem recurs.

**Comment by ashvin777** [comment]
This has been resolved. Thanks team
