### ISSUE TITLE
Error when adding this custom filter: https://gitee.com/halflife/list/raw/master/ad.txt

### ISSUE THREAD

**Issue by Leojc** [AdguardTeam/AdguardBrowserExtension#1735]
### Issue Details

- **AdGuard version:**
  -  3.5.23 
- **Browser and version:**
  - Firefox 84.0
- **Operating system and version:**
  - Windows 10
- **Filters you use in AdGuard:**
  - Custom Filter: https://gitee.com/halflife/list/raw/master/ad.txt
- **Stealth Mode settings:**
  - enabled

### Behavior
Error when adding this custom filter. https://gitee.com/halflife/list/raw/master/ad.txt

### Screenshots

<details><summary>Screenshot:</summary>

![图片](https://user-images.githubusercontent.com/33376945/102007088-f3b7dd00-3d60-11eb-944f-c9da386faa6f.png)

</details>

**Comment by maximtop** [comment]
The filter could not be loaded because it includes another filter `cjx-ublock.txt`, which returns 404 error.
The developer of the filter should remove the included filter or change the path to an existing filter.

**Comment by ameshkov** [comment]
Talking about this line:
`!#include cjx-ublock.txt`

**Comment by Leojc** [comment]
Thanks! I'll contect the developer.
