### ISSUE TITLE
Duolingo

### ISSUE THREAD

**Issue by Light-on** [AdguardTeam/AdguardBrowserExtension#1736]
Здравствуйте. Прошу вас о помощи. На сайте https://www.duolingo.com/practice нововведение: анимированные картинки. Они сопровождают текст при каждом обновлении страницы. Блокировать нежелательный элемент получается, Но. Сначала нежелательный элемент появляется, его видно секунду-две, потом исчезает, а после отправки текста (перед очередным обновлением страницы) он снова появляется. Невозможно. Пожалуйста, попробуйте придумать правило, надёжно блокирующее эти картинки.

Мой браузер: Хром, версия актуальная.

**Comment by Light-on** [comment]
Кажется, проблема решилась! Или разработчики сайта внесли изменения, или помог Adguard? Нужно понаблюдать ещё, как пойдут дела.

**Comment by zzebrum** [comment]
@Light-on при проблемах с блокировкой рекламы, используйте инструмент "Сообщить о проблеме".

**Comment by Chinaski1** [comment]
Здравствуйте.
В таком случае я закрываю задачу.
Вы можете открыть её повторно, если проблема повторится.
Также желательно дать более подробное описание возникшей ситуации (Браузер и его версия, версия расширения, шаги воспроизведения).
