### ISSUE TITLE
HTML DOM addEventListener doesn't work in Javascript rules. jQuery doesn't support? How to remove the BlockAdBlock script?

### ISSUE THREAD

**Issue by tumatanquang** [AdguardTeam/AdguardBrowserExtension#1737]
> I try to remove Adblock detected on the website [fake-it.ws](https://fake-it.ws/).

**HTML DOM addEventListener doesn't work in Javascript rules**

When I view-source this web page, I see that when the web page detected adblock, it will add a `hasAdblocker` class to `<body>` and div id `adblocker` will be displayed block. So I wrote a rule to remove the `hasAdblocker` class and the div id `adblocker`. The rule is as follows:
`fake-it.ws#%#document.getElementsByTagName('body')[0].removeAttribute('class');document.getElementById('adblocker').remove();`
After refreshing the page, I found that the above code had a problem. Because the rules are executed before the site's `<body>` is loaded while the site adding `hasAdblocker` class is done after the entire web page is loaded and the div id `adblocker` is in `<body>` again because it cannot be removed either. The error I get at console log:
`Error executing AG js: TypeError: Cannot read property 'removeAttribute' of undefined`
The above code works normally, the syntax is correct (I tried running the code in the console log after the web page finished loading, the class and id were removed).
So I used addEventListener in the hopes of fixing the problem. New rules:
`document.addEventListener("DOMContentLoaded", function(){document.getElementsByTagName('body')[0].removeAttribute('class');document.getElementById('adblocker').remove();});`
However, it still doesn't work. At the console log nothing is displayed, including errors!

**jQuery doesn't support?**

Does this extension still not support jQuery? I tried using jQuery syntax for the filter rule and of course it doesn't work.

**Expand: How to remove the BlockAdBlock script?**

BlockAdBlock has updated to version 4. I have not found a solution to remove it as it is added directly in the page, just before `</body>` rather than using a separate javascript file. Is there any solution to remove it?

**Comment by Chinaski1** [comment]
Hello there!
 
Yes, jQuery not supported.
As for ad blockers and filters, I think @Alex-302 @zloyden @Sergey-Lyapin can help you.
For the rest of the questions I will be able to answer you a little later.

**Comment by Chinaski1** [comment]
I close this task.

Regarding the question about BlockAdBlock, you will soon get an answer from @slavaleleka

**Comment by slavaleleka** [comment]
@tumatanquang 
1. For element class removing there is [remove-class scriptlet](https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-scriptlets.md#remove-class); for element removing you can use [extended-css remove pseudos](https://github.com/AdguardTeam/ExtendedCss#remove-pseudos)
2. jQuery is not supported in rules
3. For dealing with BlockAdBlock scripts we have [prevent-bab scriptlet](https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-scriptlets.md#prevent-bab). But if you want to **remove the script** you'll need [HTML filtering rules](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#html-filtering-rules) which are supported by AdGuard for Windows, Mac, Android and by the AdGuard's Firefox browser extension

**Comment by tumatanquang** [comment]
@slavaleleka Please answer this: https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1743
