### ISSUE TITLE
Безопасность браузера и вредоносные расширения

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardBrowserExtension#1738]
Здравствуйте!
Я думаю вы все видели [ЭТУ](https://m.habr.com/ru/company/yandex/blog/534586/) статью в официальном блоге Яндекса. Хотелось бы узнать, безопасно ли расширение для браузера от адгарда и насколько?

И еще один вопрос:
Защищает ли адгард от чего-то подобного? Если да, то почему домены savefrom.net, frigate и т.д не блокируются адгардом?

**Comment by Chinaski1** [comment]
Добрый день, @ghost

Да, ситуация, которая описана в статье конечно довольно любопытная.
Но как вы уже догадались, мы не применяем какие-либо "запрещенные" методы, которые потенциально могут навредить нашим пользователям. Так что с уверенностью могу сказать - использовать AdGuard безопасно :)

Что касается блокировки сторонних расширений и доменов, которые они используют - 
у нас нет доступа к запросам этих самых расширений, поэтому мы собственно их и не блокируем.
