### ISSUE TITLE
Яндекс браузер блокирует установку вашего разгирения

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardBrowserExtension#1739]
Здравствуйте!
Имеется проблема, что **_МОБИЛЬНЫЙ_** Яндекс браузер блокирует установку релизной версии расширения, но при этом бета версия ставится нормально.

Скрины прилагаю.

Бета версия успешно установилась:
![Screenshot_20201228-235500](https://user-images.githubusercontent.com/76709035/103245338-857e3780-4968-11eb-9ba3-86c78e14556d.jpg)
![Screenshot_20201228-235650](https://user-images.githubusercontent.com/76709035/103245339-86af6480-4968-11eb-9aad-7cc6ea405717.jpg)

А вот с релизной версией вот такая бяка:
![Screenshot_20201228-235403](https://user-images.githubusercontent.com/76709035/103245356-96c74400-4968-11eb-97f9-487b9e5470d3.jpg)

Версия браузера:
20.11.3
ОС:
Андроид. Проверял на разных версиях, результат неизменный.

Да, у меня стоит полноценная версия адгард в виде приложения. И да, я ей активно пользуюсь, но я предпочитаю двойную защиту. К тому же на 4пда есть [ПОХОЖАЯ ТЕМА](https://4pda.ru/forum/index.php?showtopic=808466&view=findpost&p=60220036) , правда она касается Ublock. Но судя по всему Яндекс блокирует установку всех известных дополнений для блокировки рекламы.

Прошу провести расследование 🤗

**Comment by Chinaski1** [comment]
На самом деле использовать AdGuard вместе с расширением, также бессмысленно как носить две куртки в теплую погоду. Методы, которые используются расширением являются лишь частью функционала основного приложения. Используя данную комбинацию, вы едва ли добьетесь улучшения качества блокировки рекламы.
При желании конечно можно установить AdGuard Content Blocker, который встроен в Яндекс браузер по умолчанию.

По поводу установки расширения, да - действительно есть такая проблема. Постараемся разобраться в ближайшее время, спасибо за информацию.
