### ISSUE TITLE
Compatibility issue with Random Agent Spoofer add-on

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#174]
![fc0xyq1](https://cloud.githubusercontent.com/assets/5947035/13269235/c6f9d07e-da97-11e5-9ce6-13ea9f2312fd.png)

**Comment by ameshkov** [comment]
Please check it, the issue is major.

**Comment by Mizzick** [comment]
Cannot reproduce with latest FF 44.0.2 and adguard 2.1.5.

**Comment by ameshkov** [comment]
> Cannot reproduce with latest FF 44.0.2 and adguard 2.1.5.

So what? You must not close issues if you cannot reproduce anything.

Search for what can possibly cause this.

**Comment by ameshkov** [comment]
Here is an update: translation is broken by RAS addon.

Please check it with a new version (based on frame scripts) which is in pull request now.

**Comment by Mizzick** [comment]
Fixed with frame-scripts version #138
