### ISSUE TITLE
Add support for Apple Silicon (M1 processor)

### ISSUE THREAD

**Issue by hoaxlayer** [AdguardTeam/AdguardBrowserExtension#1740]
- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Problem Description

While the current Intel build is working great in the M1 version of Safari, an Apple Silicon version would be preferred.

### Proposed Solution

Build an Apple Silicon or universal package version of the Safari extension.

### Alternatives Considered

Keep running the Intel version

**Comment by Chinaski1** [comment]
Duplicate of: https://github.com/AdguardTeam/AdGuardForSafari/issues/493
