### ISSUE TITLE
Reverse syntax of CSS rules for Javascript rules

### ISSUE THREAD

**Issue by tumatanquang** [AdguardTeam/AdguardBrowserExtension#1743]
I am writing a simple filter that both Adblock Plus and Adguard Adblock can use. However, Adblock Plus uses `#$#` for **Javascript rules** (they are less developed than Adguard Adblock without **CSS rules** yet) but in Adguard Adblock use that notation for **CSS rules**.
So please reverse the notation of **CSS rules** and **Javascript rules**. Edit **CSS rules** to `#%#` and **Javascript rules** to `#$#` so the filter is compatible on both extensions.

**Comment by Chinaski1** [comment]
Hello there!

Automatic conversion of ABP snippets, as like a trusted filter will be supported starting from version 4.0
Here is a link to the [compatibility table](https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/compatibility-table.md#scriptlets)

**Comment by slavaleleka** [comment]
@tumatanquang 

so you want to use that filter list in AdGuard as custom, right? could you please provide examples of rules you mentioned? what kind of issues you've faced for now?

**Comment by tumatanquang** [comment]
@Chinaski1 @slavaleleka 
I will explain my problem:

> The following syntax is from [Non-basic rules](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#javascript-rules) on Adguard Adblock website and [Adblock Plus filters explained](https://adblockplus.org/filter-cheatsheet).

**First, CSS rules syntax:**

> _Adguard Adblock_:  `[domains] "#$#" css`
> _Adblock Plus_: `Still not have!`

**Second, Javascript rules syntax:**

> _Adguard Adblock_: `[domains]  "#%#" script`
> _Adblock Plus_: `[domains] "#$#" script`

As you can see, the Javascript rules syntax of Adblock Plus is currently the CSS rules syntax of Adguard Adblock. While the Javascript rules syntax of Adguard Adblock is not currently used on Adblock Plus. For example, I write the following filter:
> `example.com#%#window.AdsVariable = undefined;`

Like the above example, if a filter is used on Adguard Adblock, the variable `AdsVariable` will have the value `undefined` but on Adblock Plus, it won't work!
Or for example:
> `example.com#$#body { background-color: #333!important; }`

If used on Adguard Adblock, this rule will apply a style `background-color: #333!important` to the `body` element at **example.com** and all subdomains.
But if that filter is used on Adblock Plus, it will execute the Javascript script: `body { background-color: #333!important; }`
And of course the syntax is wrong!
That's why I want you to reverse the syntax of CSS rules and Javascript rules on Adguard Adblock. Since the current syntax of Adguard Adblock and Adblock Plus is not the same, my filter is not able to work on both extensions.

P/s: Hope my example is easy to understand.
