### ISSUE TITLE
Remove 'Enable case-sensitivity` in 'Adding a rule'

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1747]
I see no rules with this modifier in the filters.

For URL blocking/unblocking rules it can be replaced by `badfilter`'ing rule(patterns must be locked in this case, because `badfilter` works with original rule only).
@AdguardTeam/filters-maintainers you can suggest other options.

**Comment by Mizzick** [comment]
After consideration we decided that this is not necessary.
