### ISSUE TITLE
Blocking rules conflict

### ISSUE THREAD

**Issue by Bushido1** [AdguardTeam/AdguardBrowserExtension#1749]
### Issue Details

- **AdGuard version:**
  - AdGuard for Windows 7.5.3
- **Browser and version:**
  - Chrome 87.0.4280.141 64-bit
- **Operating system and version:**
  - Windws 10 Pro 20H2 19042.746
- **Stealth Mode settings:**
  - Enabled

### Expected Behavior

A rule added to the filter list of https://chrome.google.com/webstore/detail/adguard-adblocker/bgnkhhnnamicmpeenaelnjfhikgbkllg is added to the filters list of AdGuard for Windows.

### Actual Behavior

A rule added to the filter list of https://chrome.google.com/webstore/detail/adguard-adblocker/bgnkhhnnamicmpeenaelnjfhikgbkllg is not added to the filters list of AdGuard for Windows.

### Additional Information

What is the purpose of filters list of https://chrome.google.com/webstore/detail/adguard-adblocker/bgnkhhnnamicmpeenaelnjfhikgbkllg for AdGuard for Windows users if the rules added to https://chrome.google.com/webstore/detail/adguard-adblocker/bgnkhhnnamicmpeenaelnjfhikgbkllg are not added to the AdGuard for Windows?
I have to add the rule twice in order to block something within the operating system, not just in browser.

**Comment by Chinaski1** [comment]
Issue moved to [AdguardTeam/AdguardForWindows #3665](https://github.com/AdguardTeam/AdguardForWindows/issues/3665) via [**ZenHub**](https://www.zenhub.com/)
