### ISSUE TITLE
The back button in Safari (or gesture, or keyboard shortcut) doesn't actually go back in browsing history

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#175]
I can confirm this issue on "newsru.com"

**Comment by Mizzick** [comment]
I just tried and everything is fine.
How did it look like for you?

**Comment by Mizzick** [comment]
Safari 9.0.3

**Comment by ameshkov** [comment]
1. Open newsru.com
2. Go to any article there
3. Press "back" button
4. Page reloads and it does not go back

**Comment by Mizzick** [comment]
Can you show the logs please?
What build do you use?

**Comment by ameshkov** [comment]
This issue happens on Euronews website as well, go here and click some links to reproduce.
http://ru.euronews.com

**Comment by Mizzick** [comment]
Blocking script from http://pagead2.googlesyndication.com/pagead/show_ads.js causes an exception that forces Safari to reload the tab.

To prevent this - add @@pagead2.googlesyndication.com/pagead/show_ads.js to User filter.
