### ISSUE TITLE
Hide My AdBlocker

### ISSUE THREAD

**Issue by m1999ves** [AdguardTeam/AdguardBrowserExtension#1750]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [+] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Problem Description

Websites are able to detect AdBlock and therefore propose deactivation shit.

### Proposed Solution

I would like to suggest a function called Hide my AdBlocker. It can hide the code from the website, so that I can browse the website without ads and their supporters.

### Additional Information

Nothing.

**Comment by Chinaski1** [comment]
Hello there!

- Open the AdGuard Extension settings -> Filter -> Annoyancess -> Enable AdGuard Annoyances Filter.

This filter will hide the information that you are using AdBlocker from sites.
