### ISSUE TITLE
Блокировка Suggested posts в ленте Facebook

### ISSUE THREAD

**Issue by jbionic2016** [AdguardTeam/AdguardBrowserExtension#1751]
Приветствую.

Проблема касается отображения ленты Facebook в Chrome-браузере с установленными расширениями Adguard AdBlocker 3.5.31 и Adguard Extra 1.0.204.

В ленте Facebook  достали уже Suggested posts от всяких фриков, спасающих собачек и снимающих себя на видео. Возможно ли сделать что-нибудь, чтоб заблокировать появление подобных постов в ленте?

Если есть иные проверенные решения на базе скриптов для Tampermonkey, то готов рассмотреть, только дайте ссылки.

Заранее благодарю.

Operating system: Windows 10 Home
Browser: Chrome Version  87.0.4280.141 (Official Build) (64-bit)
AdGuard version for Chrome: Version 3.5.31
Filters enabled: AdGuard Base filter, AdGuard Tracking Protection filter, EasyPrivacy, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter
Stealth mode options (Windows only) Enabled
 AdGuard Extra 1.0.204

**Comment by jbionic2016** [comment]
Кстати, вопрос актуален и для Android-версии приложения Facebook Lite. Я правда не уверен, что непремиальный Adguard сможет в этом случае что-то предложить, учитывая, что Suggested posts показываются в родном приложении Фейсбука, а не в стороннем браузере независимого производителя.

**Comment by Chinaski1** [comment]
Добрый день, @jbionic2016.

Вы не могли бы, пожалуйста, уточнить о каких именно Suggested posts идет речь (желательно со скриншотами)?
Также вам следует попробовать открыть браузер в режиме инкогнито и проверить, проложат ли данные посты появляться в вашей ленте.

**Comment by jbionic2016** [comment]
Да, пожалуйста, сколько угодно. 
https://i114.fastpic.ru/big/2021/0120/c8/7532ab48a12711b236a759eb96b35ac8.jpg
https://i114.fastpic.ru/big/2021/0120/49/ed694acc1e0f2d007a5c70adfef27d49.jpg
https://i114.fastpic.ru/big/2021/0120/f6/46a76f409664f6fe72069afbd76c9df6.jpg
https://i114.fastpic.ru/big/2021/0120/92/0604c40cac64cc2b662165af4b0f4892.jpg

Проверил в режиме инкогнито - проблема остаётся, последний из скриншотов выше как раз в режиме инкогнито был сделан.

**Comment by jbionic2016** [comment]
Кстати, аналогичная проблема есть и в ленте Quora 
https://thumbsnap.com/urfKMRed

Тоже какой-то идиот решил что мне может быть интересно..

**Comment by Chinaski1** [comment]
Issue moved to [AdguardTeam/AdguardFilters #73287](https://github.com/AdguardTeam/AdguardFilters/issues/73287) via [**ZenHub**](https://www.zenhub.com/)
