### ISSUE TITLE
Vivaldi 3.6 stuck

### ISSUE THREAD

**Issue by erowerlord** [AdguardTeam/AdguardBrowserExtension#1752]
The new update to Vivaldi browser causes problems in AdGuard. Pages stuck, browser window no respond (cannot click)

if I disable the extension everything works as expected.

My OS: Windows 7 Ultimate 64-bit (6.1, Build 7601) Service Pack 1 (7601.win7sp1_ldr_escrow.180422-1430) (Turkish, Japanese dual lang. settings)

Vivaldi v3.6.2165.34 (Stable channel) (64 bit)

AdGuard v3.5.31

BIOS: InsydeH2O Version 40CN20WW(V1.07)
Processor: Intel(R) Core(TM) i3-2310M CPU @ 2.10GHz (4 CPUs), ~2.1GHz
Memory: 3072MB RAM
Available OS Memory: 3054MB RAM
Card name: AMD Radeon HD 6300M Series 1GB

Actual behavior:
The browser stuck if it tries to load a page, if i stop the page before it loads browser is running but unusable (with extension)

Expected behavior:
It works as smoothly as before.

Note : I have tried other alternative apps and no ad blocker. No matter how bad it works, even I used the internal blocker. Some sites still freeze. This problem is more likely to be from the browser. I guess I rushed

**Comment by ameshkov** [comment]
@AdguardTeam/qa-team please take a look asap

**Comment by Chinaski1** [comment]
Tested, the extension works without any issues.
