### ISSUE TITLE
Feature Req.: Red Flagging Malware Extensions

### ISSUE THREAD

**Issue by crogonint** [AdguardTeam/AdguardBrowserExtension#1754]
I actually installed your extension hoping that there was a way to weed through and find out if any of the ones I have are on your list of 250 some malware infested Chrome Extensions. I don't even care IF the developers fix them. If they were dishonest once, I don't want any product they ever make.

Anyway, I didn't see it. I'm on a Linux machine, so I can't install the program. :'(

Soo... here I am asking if you could turn that list in to a quick search function. That's all I need, I'll do the rest. :) I suppose other people might like an uninstaller function, but I'm not overly concerned with that part. :)

**Comment by Chinaski1** [comment]
Hello there!

AdGuard AdBlocker is an extension aimed mainly at blocking ads and protecting your privacy.
It is not up to us to decide which extension is potentially dangerous and block it. Chrome/Firefox/etc store directly handles these issues.

**Comment by crogonint** [comment]
Are you kidding me?? There are news articles all over the place about you
guys giving lists of malware infested extensions to Google et al, and they
ignored them.

HONESTLY. I've got a full suite of Ad-blockers. I have no use for yours..
per say.

However, I'll PROUDLY support you IF you stand up to Google and the rest
and build out this SORELY needed feature!

I've seen your list. All I'm asking is that you KEEP tabs on bad
extensions, and put the list to good use.
 - James T. Long

------------
There are 10 kinds of people in the world - those who understand binary,
and those who don't.
