### ISSUE TITLE
12 hour Time Format Feature

### ISSUE THREAD

**Issue by hl2guide** [AdguardTeam/AdguardBrowserExtension#1755]
### Problem Description

The filter update time is only shown in 24 hour format.

![image](https://user-images.githubusercontent.com/17044982/107107845-c468ac80-6887-11eb-9efc-792a2c76d6aa.png)

### Proposed Solution

Please add a setting for showing timestamp in 12 hour AM/PM time format (locale based?).

Better feature support for regional date and time formats would be wonderful. 💜

**Comment by maximtop** [comment]
We use https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString for format
