### ISSUE TITLE
Adguard causing blank page in Edge (Chromium)

### ISSUE THREAD

**Issue by yurividal** [AdguardTeam/AdguardBrowserExtension#1757]
### Issue Details

- **AdGuard version:**
3.5.31
- **Browser and version:**
Edge Chromium Version 89.0.774.27
- **Operating system and version:**
Windows 10
- **Filters you use in AdGuard:**
all except security

Sometimes the page doesnt load at all, we only get a blank grey page, even on simple google searches. The solution is to disable adguard, and open the page in a new tab.

**Comment by Chinaski1** [comment]
Hello @yurividal 

Please specify if you have activated all filters in the enabled sections?
This seems to be what is causing the issue.
Try leaving only AdGuard filters and see if the issue still reproduce?

**Comment by Chinaski1** [comment]
Since there has been no response, I will close this task.

Reopen it if the issue is still reproduced.
