### ISSUE TITLE
Issue: CMP is being blocked by AdGuard AdBlocker

### ISSUE THREAD

**Issue by nmpina28** [AdguardTeam/AdguardBrowserExtension#1759]
Greetings,

My apologies for deleting the content of this issue but it contains some private information and for this reason, it should be addressed to the product support using private means of communication (mail,...).

Cheers,

Nelson

**Comment by nmpina28** [comment]
I had to close this ticket for the reasons pointed in the issue description. This issue should be handled in a more private way. Besides, it's of my knowledge that the CMP should not be blocked in any case.
Cheers.

**Comment by ameshkov** [comment]
Nelson, you need to report your concerns to https://github.com/easylist/easylist since this is the list that is used by most of the ad blockers.

**Comment by nmpina28** [comment]
> Nelson, you need to report your concerns to https://github.com/easylist/easylist since this is the list that is used by most of the ad blockers.

Thank you. I'll do so. Nonetheless, I find it odd the Ad Blockers not having a list of themselves. 
Cheers

**Comment by ameshkov** [comment]
Every ad blocker adds something on its own, but a big chunk of ad servers is handled by EasyList.

**Comment by ameshkov** [comment]
> the content of this issue but it contains some private information and for this reason

I've cleared the issue edits history just in case.

**Comment by nmpina28** [comment]
> > the content of this issue but it contains some private information and for this reason
> 
> I've cleared the issue edits history just in case.

Thank you once again for your help and for clearing the issue edit history (y)

**Comment by nmpina28** [comment]
> > the content of this issue but it contains some private information and for this reason
> 
> I've cleared the issue edits history just in case.

If it is not asking too much, do you know how I can delete an issue opened by me? And how I can clear the issue history?

Thank you once again ameshkov

**Comment by ameshkov** [comment]
I don't think this is possible, only the repo admin can edit issue history.
