### ISSUE TITLE
Блокировка рекламы YouTube

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardBrowserExtension#1761]
Здравствуйте!
В видеороликах на YouTube имеется релма, рассказываемая непосредственно блогером. Предлагаю заблокировать ее используя данное решение (open source): https://sponsor.ajay.app/

**Comment by Chinaski1** [comment]
Дубликат: https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1762
