### ISSUE TITLE
Chrome extension base filter prevents Twitter timeline from loading

### ISSUE THREAD

**Issue by lapcat** [AdguardTeam/AdguardBrowserExtension#1763]
- **AdGuard version:**
AdGuard v3.5.31
- **Browser and version:**
Chrome 88.0.4324.182
- **Operating system and version:**
macOS 10.14.6
- **Filters you use in AdGuard:**
Base filter

Starting yesterday, my Twitter timeline on https://twitter.com/home stopped loading with the AdGuard base filter enabled. The timeline is just blank with no tweets. If I start to scroll down the page, then the timeline finally loads. I've seen a number of other reports on Twitter of users experiencing the same thing, a blank timeline.

I checked the AdGuard filtering log for blocks, and when I made the following exception in my user rules, the timeline started loading again:

`twitter.com#@%#!function(){(new MutationObserver(function(){document.querySelectorAll('div[style^="padding-bottom: 0px;"] > div[style^="padding-top:"] > div:not([class]):not([style]), div[class] > div[style^="position: relative"] > div[style*="position: absolute;"]:not([class]):not([style*="display: none"])').forEach(function(b){Object.keys(b).some(function(a){if(a.includes("reactEventHandlers")){a=b[a];try{var c=a.children._owner.alternate.key;c.includes("promotedTweet")&&(b.style="display:none!important;")}catch(d){}}})})})).observe(document,{childList:!0,subtree:!0})}();`

This behavior only started yesterday. Prior to that, there were no problems, so it seems that Twitter made some kind of a change. My filters were a few days out of date, but updating them to the latest didn't fix the problem. Only making an exception for the base filter rule fixed the problem.

**Comment by Chinaski1** [comment]
Hello there!

Could you please specify in more detail in which section the issue is reproduced?
The site appears to work as expected with Base Filter enabled.

**Comment by lapcat** [comment]
Here's a screenshot.
<img width="689" alt="Screen Shot 2021-02-20 at 9 22 18 AM" src="https://user-images.githubusercontent.com/56086/108600640-c50c4300-735d-11eb-8cbf-af60bb0f0f78.png">

**Comment by Chinaski1** [comment]
@lapcat 
Maybe you are using third-party extensions in your browser, or have other filters or stealth-mode settings enabled?

**Comment by AdamWr** [comment]
I guess it's the same issue as here - https://github.com/AdguardTeam/AdguardFilters/issues/75585
I think it should be fixed already.

**Comment by lapcat** [comment]
> I guess it's the same issue as here - [AdguardTeam/AdguardFilters#75585](https://github.com/AdguardTeam/AdguardFilters/issues/75585)
> I think it should be fixed already.

Yes, this appears to be fixed in the latest filter update. Thank you.
