### ISSUE TITLE
Pseudo element selectors :nth-ancestor() and :upward() not working in filter rules

### ISSUE THREAD

**Issue by kriegaex** [AdguardTeam/AdguardBrowserExtension#1767]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:** 3.5.31
- **Browser and version:** Chrome 88.0.4324.182 (64-Bit)
- **Operating system and version:** Windows 10
- **Filters you use in AdGuard:** many, but irrelevant here
- **Stealth Mode settings:** inactive
- **Other browser extensions:** several

### Expected vs. Actual Behavior

A user-defined filter like `faz.net##.lst-Services` works nicely. But trying to use `faz.net##.lst-Services:upward(1)` or `faz.net##.lst-Services:nth-ancestor(1)` fails to block anything, no matter if I use it in the interactive "block element" pop-up box or directly edit the filter list. AFAIU the [documentation](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters?utm_source=browser_extension&utm_medium=options&utm_campaign=userfilter_description#extended-css-upward), I thought this should work.

I am looking for a way to select parent/ancestor elements of elements identified by a CSS selector.

**Comment by slavaleleka** [comment]
`faz.net##.lst-Services:upward(1)` from User rules [works for me](https://uploads.adguard.com/slbdzdr5lxf8.png)

**Comment by kriegaex** [comment]
What the heck? Yesterday it did not work, now it suddenly does, at least if I directly add the rule to the user rules list. What I actually want is `faz.net##.lst-Services:upward(4)` in order to hide the whole info box.

It definitely does **not** work in the interactive preview:

![image](https://user-images.githubusercontent.com/1537384/108651915-5e219200-74f5-11eb-8e8b-39a14d6d255c.png)

When I click "Vorschau" (preview) here, nothing happens. Only after I save it as a rule and reload, it works.

**Comment by slavaleleka** [comment]
unfortunately preview doesn't work for ExtendedCSS rules, that's a [knows issue](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/756)

**Comment by kriegaex** [comment]
Ugh, that's quite inconvenient. The preview is one of the killer features of the browser extension, because it permits to interatively find the right element and then seamlessly save the new rule.
