### ISSUE TITLE
Adguard doesn't remember language and open english version of website when in extension I open link to adguard website.

### ISSUE THREAD

**Issue by Mlocik97** [AdguardTeam/AdguardBrowserExtension#1768]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 
  - AdGuard 3.5.31
- **Browser and version:**
  - 
  - Chrome 88.0.4324.182
- **Operating system and version:**
  - 
  - Linux Ubuntu 20.04
- **Filters you use in AdGuard:**
  - 
  - All, except anti 3rd font and "others".
- **Stealth Mode settings:**
  - 
  - Enabled
- **Other browser extensions:**
  - 
  - YouTube NonStop

### Expected Behavior

When I visit adguard.com and set language to Czech, website remember it, and everytime I visit adguard.com it will always be in Czech language (I set), but when I click on "adguard.com" link from Extension in Browser, it set back to English.

### Actual Behavior

Don't switch language back to English.

### Screenshots

<details><summary>Screenshot:</summary>

![Snímka obrazovky z 2021-02-22 16-05-07](https://user-images.githubusercontent.com/34808350/108726520-d012cf00-7527-11eb-9ecc-4918e661b31b.png)

from my visit

![Snímka obrazovky z 2021-02-22 16-05-21](https://user-images.githubusercontent.com/34808350/108726546-d5701980-7527-11eb-9f3f-45371a3b589f.png)
after clicking on button in extension, that open adguard website.
</details>

**Comment by Chinaski1** [comment]
Hello @Mlocik97 

I can't reproduce your issue, when I go to adguard.com via the "Check website security" button it takes me to a page with a correctly displayed language.
Please check in the page and account settings that you have the [same language set](https://uploads.adguard.com/Chinaskil4dxp.png).

**Comment by Mlocik97** [comment]
I don't have adguard account.

**Comment by Chinaski1** [comment]
@Mlocik97 

It seems that the information about the selected language has been cached by the browser.
Try clearing the cache, select the desired language and try again.
Will the issue still reproduced?

**Comment by Mlocik97** [comment]
Ok, it seems like clearing cashe fixed problem.
