### ISSUE TITLE
Unresponsive Script errors with Firefox add-on

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#177]
Source bug report:
http://forum.adguard.com/showthread.php?9265-Unresponsive-Script-errors-with-Firefox-add-on

@Mizzick please try FF with AMO add-on and these prefs:
http://forum.adguard.com/showthread.php?9265-Unresponsive-Script-errors-with-Firefox-add-on&p=77133&viewfull=1#post77133

**Comment by ameshkov** [comment]
Cannot reproduce

**Comment by erkinalp** [comment]
started to appear again in FF55b

**Comment by ameshkov** [comment]
> started to appear again in FF55b

Are you on stable or beta channel of AG extension? We're planning to push the WebExtension version of extension really soon (it's in the beta channel at the moment).

**Comment by erkinalp** [comment]
Stable channel(legacy add-on).

**Comment by ameshkov** [comment]
> Stable channel(legacy add-on).

Could you please check the beta version just in case if the issue is already resolved.

**Comment by erkinalp** [comment]
Beta channel is also legacy now.

**Comment by ameshkov** [comment]
There're three channels:

AMO stable (WebExtensions add-on)
AMO beta (WebExtensions add-on)
Legacy (the old bootstrapped add-on)

**Comment by erkinalp** [comment]
I opened addons.mozilla.org today and all channels are legacy still. Can you point me to webextension directly?

**Comment by vozersky** [comment]
@erkinalp  https://addons.mozilla.org/en-US/firefox/addon/adguard-adblocker/versions/beta?page=1#version-2.6.7beta
