### ISSUE TITLE
[Request] Play In External Player

### ISSUE THREAD

**Issue by zero77** [AdguardTeam/AdguardBrowserExtension#1770]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description
For some websites where blocking video adverts is difficult and becomes a cat and mouse game, like twitch and others.

### Proposed Solution

Could you please provide the ability to play a video in an external player vlc or something else, thanks.
This has already been implemented in adguard for android.

### Alternatives Considered
Continue to invest time trying to block ads head on.

**Comment by anastenko** [comment]
Hello there.
Could you please provide some examples of websites where this issue can be reproduced? 
Usually, these types of ads are successfully blocked by a standard set of filters. Therefore it's not necessary to implement this feature.

**Comment by zero77** [comment]
Using twitch as an example, which i know is still an open issue with adguard, using an external player like vlc was suggested as a workaround. https://github.com/uBlockOrigin/uAssets/issues/5184#issuecomment-719692920
https://github.com/AdguardTeam/AdguardFilters/issues/69100

**Comment by Chinaski1** [comment]
I don't think adding this functionality is feasible and unlikely to be implemented at the extension level.
On the Android platform we use our own player, so users can share videos from YouTube to filter advertising content.
You can use VLC players as a temporary solution. We will try to find ways to block this type of advertising in the near future.

**Comment by zero77** [comment]
> I don't think adding this functionality is feasible and unlikely to be implemented at the extension level.
On the Android platform we use our own player, so users can share videos from YouTube to filter advertising content.
You can use VLC players as a temporary solution.

VLC was and example and was mentioned as a workaround by someone else there are other options. A custom player like in android may be a better option but would lightly be more work to support so i suggested a third party.

> We will try to find ways to block this type of advertising in the near future.

Do you know if there is an issue or a discussion somewhere for this.

**Comment by Chinaski1** [comment]
However, we are not planning to develop our own video player in the near future as there is no urgent need for this.
And as you understand, we can't make redirects to third-party players either.
But we will revisit this feature if necessary.

I think it makes sense to keep an eye on [this issue](https://github.com/AdguardTeam/AdguardFilters/issues/69100) in the filter repository, the filter developers should find a solution.
