### ISSUE TITLE
Question about Do Not Track

### ISSUE THREAD

**Issue by Erengit** [AdguardTeam/AdguardBrowserExtension#1771]
Is the `Do Not Track` feature in Stealth Mode the same thing as the `Do Not Track` feature in the Chrome browser?

<details>
 <summary>Screenshot</summary>
 
![UPvpH8](https://user-images.githubusercontent.com/79805068/109428347-d57c8780-7a07-11eb-99f7-164baad7fe3a.jpg)

</details>

<details>
 <summary>Screenshot</summary>
 
![0Ck6I4](https://user-images.githubusercontent.com/79805068/109428354-e200e000-7a07-11eb-9342-4b7233e74c1d.jpg)

</details>

I'm using Chrome and `Do Not Track` is already active. In that case, I don't need to turn on `Do Not Track` feature in AdGuard. Right?

**Comment by anastenko** [comment]
Hello there.
You're right, in this case there's no need to use "Do not track" option in AdGuard extension, since they work pretty much the same.
