### ISSUE TITLE
Feature request on Edge Extension: give an option to block ads only on this page 

### ISSUE THREAD

**Issue by Ben-md5** [AdguardTeam/AdguardBrowserExtension#1773]
I expected the adguard edge extension to add an option to provide whether or not to remove ads from a page on a web site Only interceptions in this page, such as those in ABP Plus and ublock

**Comment by Chinaski1** [comment]
Hello there!

This feature is already implemented in the [Whitelist section](https://uploads.adguard.com/Chinaskifw927.png)
Turn on the invert whitelist and add sites you want to block ads on.
