### ISSUE TITLE
adguard causing uncontrolled scrolling

### ISSUE THREAD

**Issue by wolf5614** [AdguardTeam/AdguardBrowserExtension#1776]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details
Adguard is causing uncontrolled scrolling. When using the down arrow pages will scroll uncontrollable to the bottom of page. Once started unable to stop. Turned off adguard the problem goes away, turn it back on and the problem resumes.

- **AdGuard version:**
  - 
- **Browser and version:**
  - 
- **Operating system and version:**
  - 
- **Filters you use in AdGuard:**
  - 
- **Stealth Mode settings:**
  - 
- **Other browser extensions:**
  - 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by anastenko** [comment]
Hello.
Could you specify the AdGuard version you use, and also all filters enabled?
What sites this issue occurs on? 
Do you use default settings or have you already customized it somehow?

**Comment by wolf5614** [comment]
Version 3.5.31 all filters on except security

    On Friday, March 19, 2021, 09:26:29 AM EDT, anastenko ***@***.***> wrote:  
 
 


Hello.
Could you specify the AdGuard version you use, and also all filters enabled?
What sites this issue occurs on?
Do you use default settings or have you already customized it somehow?

**Comment by anastenko** [comment]
Could you give an example of the site the issue happened on?

**Comment by wolf5614** [comment]
yahoo.com, the Hill.com, Nytimes.com, military times.com and just about all sites. When I turn off adguard the problem goes away, turn it back on the problem comes back. I've already ruled out windows 10, and my settings.
    On Friday, March 19, 2021, 09:42:33 AM EDT, anastenko ***@***.***> wrote:  
 
 


Could you give an example of the site the issue happened on?

**Comment by anastenko** [comment]
Unfortunately, I can't reproduce the issue from my side. Probably you use some custom filters that might effect it.

It's recommended to disable all user rules and the entire "anti-tracking" module first. Leave only base filter and "tracking protection" filters enabled. 
Also make sure that other extensions in the browser are disabled (if installed).

After all above was followed check the work of mentioned sites in incognito mode and let us know the result.

**Comment by anastenko** [comment]
@wolf5614, any news? Have your issue been resolved?

**Comment by wolf5614** [comment]
no news still having the issue
    On Wednesday, March 24, 2021, 09:33:48 AM EDT, anastenko ***@***.***> wrote:  
 
 


@wolf5614, any news? Have your issue been resolved?

**Comment by anastenko** [comment]
Have you tried to follow the instructions given previously?
If yes, then please try to switch off all your active filters and enable it one by one while checking if the issue occurs again. It will help to understand which particular filter might cause this issue.

**Comment by anastenko** [comment]
I'm closing this issue due to no response from the user for a long time. The issue can't be reproduced on our end.
Reopen it if necessary.
