### ISSUE TITLE
Неправильное отображение времени обновления фильтров

### ISSUE THREAD

**Issue by Vitalik93** [AdguardTeam/AdguardBrowserExtension#1777]
Использую последнюю версию расширения для Firefox (3.5.34). Интервал обновления фильтров выставлен на раз в час, тем не менее обновления фильтров раз в час не происходит. Например открываю настройки, проверяю, когда фильтры были обновлены, написано, что пару часов назад. Запускаю после этого ручное обновление фильтров, пишет что такой то фильтр обновлен. Почему тогда обновление фильтров не происходит по заданному интервалу автоматически?

**Comment by anastenko** [comment]
Здравствуйте!
Обновление фильтров происходит, в первую очередь, у нас на сервере, где нет установленного интервала обновлений, поэтому время на некоторых фильтрах может не меняться несколько часов.

**Comment by Vitalik93** [comment]
> 
> 
> Здравствуйте!
> Обновление фильтров происходит, в первую очередь, у нас на сервере, где нет установленного интервала обновлений, поэтому время на некоторых фильтрах может не меняться несколько часов.

Зачем тогда в настройках раздел, где можно выставлять свой интервал обновлений? За что он отвечает?

**Comment by Vitalik93** [comment]
В общем проверил в дебагере Adguard, как проходят обновления фильтров. Примерно через час после ручной проверки запустилась автоматическая. Только вот в настройках расширения почему то последнее время обновления показано совсем другое. Получается проблема только в отображении времени последнего обновления фильтров в самом расширении.

![Снимок экрана 2021-03-29 152611](https://user-images.githubusercontent.com/34383288/112889332-c7d52300-90d5-11eb-879b-34fafc78ceff.png)

![Снимок экрана 2021-03-29 152729](https://user-images.githubusercontent.com/34383288/112889346-cb68aa00-90d5-11eb-81e8-3a05f97117f1.png)

![Снимок экрана 2021-03-29 152814](https://user-images.githubusercontent.com/34383288/112889361-cdcb0400-90d5-11eb-9214-d0f02d2e6145.png)

**Comment by Vitalik93** [comment]
Более того, даже время ручной проверки обновлений сбивается. Сначала совпадает с дебагером, но если закрыть настройки и еще раз открыть, то время уже другое.

![Снимок экрана 2021-03-29 215306](https://user-images.githubusercontent.com/34383288/112892536-b8f06f80-90d9-11eb-8969-cdd0b6edd340.png)

![Снимок экрана 2021-03-29 215323](https://user-images.githubusercontent.com/34383288/112892547-bbeb6000-90d9-11eb-94da-a9b780d53562.png)

![Снимок экрана 2021-03-29 215352](https://user-images.githubusercontent.com/34383288/112892559-be4dba00-90d9-11eb-9efb-8322d792a6a9.png)

**Comment by Vitalik93** [comment]
Хотя даже по дебагеру автоматическое обновление запустилось почему то через пол часа, хотя интервал выставлен час.

**Comment by anastenko** [comment]
> @anastenko У меня оно на всех не меняется. Зачем тогда в настройках раздел, где можно выставлять свой интервал обновлений? За что он отвечает?

Выбранный интервал указывает время, когда расширение загрузит обновления с сервера.

**Comment by anastenko** [comment]
Расширение раз в полчаса проходит по фильтрам и выбирает те фильтры, для которых прошел указанный для проверки в настройках интервал. 
Если же нажать на кнопку обновления, расширение сначала показывает время нажатия, а после перезагрузки уже указывает время ближайшего обновленного фильтра.

**Comment by Vitalik93** [comment]
@anastenko Зачем так усложнять элементарное? Можно было сделать как в приложении для Windows - просто показывать время, когда фильтры последний раз обновлялись. Вне зависимости от того, было ли ручное обновление или автоматическое.

**Comment by anastenko** [comment]
Пока обновление фильтров работает именно таким образом, но будет исправлено в следующих версиях
