### ISSUE TITLE
The extension window menu is not static (Firefox)

### ISSUE THREAD

**Issue by Vitalik93** [AdguardTeam/AdguardBrowserExtension#1778]
В данный момент окно расширения становится шире при переключении с раздела "действия" на раздел "статистика". Может стоит убрать это поведение, чтобы окно расширения всегда было одного размера? По моему окно статистики не пострадает от уменьшения его размера на пару миллиметров.

![Снимок экрана 2021-03-26 000357](https://user-images.githubusercontent.com/34383288/112550285-cea72180-8dc7-11eb-8f80-238875ee5a6e.png)

![Снимок экрана 2021-03-26 000427](https://user-images.githubusercontent.com/34383288/112550289-d1a21200-8dc7-11eb-8482-8131ee248054.png)

**Comment by Chinaski1** [comment]
Приветствую!

Вы не могли бы, пожалуйста, уточнить версию браузера, расширения и ОС?

**Comment by Vitalik93** [comment]
Firefox 87.0, Adguard 3.5.34, Windows 10 20H2.

**Comment by Vitalik93** [comment]
Проверил эту проблему в Edge с расширением из его магазина, там такого нет. Видимо проблема только в расширении для Firefox.
