### ISSUE TITLE
Помощь в разработке фильтров Антифишинга.

### ISSUE THREAD

**Issue by Vitalik93** [AdguardTeam/AdguardBrowserExtension#1779]
В обзоре расширения на сайте Блога [тут](https://adguard.com/ru/blog/in-depth-review-adguard-browser-extension.html) увидел, что в настройках Антифишинга был подраздел "Помогите нам в разработке фильтров Антифишинга". В последней версии расширения (3.5.34) эту настройку на нашёл. Считаю, что стоит вернуть её, чтобы у пользователя был выбор, отправлять эту информацию или нет.
![general_ru](https://user-images.githubusercontent.com/34383288/112631129-2af95800-8e3f-11eb-8157-afcec85799ac.png)

**Comment by Chinaski1** [comment]
Данная функция была перемещена в раздел [**Разное**](https://uploads.adguard.com/Chinaski4kiyg.png).

**Comment by Vitalik93** [comment]
@Chinaski1 Судя по названию и [описанию](https://kb.adguard.com/ru/general/filter-rules-statistics?utm_source=browser_extension&utm_medium=options_screen&utm_campaign=filter_rules) та функция, что находится сейчас в разделе "Разное" относится к фильтрам, а не к Антифишингу.
