### ISSUE TITLE
Повышение безопасности (merged)

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardBrowserExtension#1782]
Здравствуйте,
Прошу рассмотреть возможность добавления возможности, указанной в issue в другом вашем продукте.

https://github.com/AdguardTeam/AdguardForAndroid/issues/3793

**Comment by Chinaski1** [comment]
Дубликат: https://github.com/AdguardTeam/CoreLibs/issues/1284

**Comment by Chinaski1** [comment]
Реализовать данную возможность на уровне расширения не представляется возможным. Дело в том, что в Chrome Store существует ограничение на создание многоцелевых приложений, данная политика обязывает разработчиков действовать в рамках выбранного профиля.
Более подробно с этой информацией вы можете ознакомится [тут](https://developer.chrome.com/docs/extensions/mv3/single_purpose/).
