### ISSUE TITLE
Adguard forum doesn't work

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardBrowserExtension#1783]
Dear developers!
Your forum does not work correctly even when Adguard is turned off. The problem is the inability to register. Instead of confirmation, a strange message "This site can't be reached" appears. I checked the DNS settings. I checked on different devices (the first screenshot is a smartphone, and the second screenshot is a computer) the problem remains unchanged. Enabling or disabling Adguard does not help. Installing and configuring a VPN does not help. I also checked on other devices, the problem still persists.

Additional information:
1. The problem manifests itself on many sites (not only on your site), disabling Adguard does not help.
2. The problem appeared a few months ago.
3. There are no programs or third-party extensions other than adguard.
4. There are no viruses on the devices.

**Screenshots:**
![68747470733a2f2f7265706f7274732d696d672e616467756172642e636f6d2f6d3155505348762e6a7067](https://user-images.githubusercontent.com/81529375/112763997-6ba7cb80-900f-11eb-87e0-ce21f98608de.jpeg)
![68747470733a2f2f7265706f7274732d696d672e616467756172642e636f6d2f376a4c72717a372e6a7067](https://user-images.githubusercontent.com/81529375/112763998-6cd8f880-900f-11eb-8e76-db75903cca9c.jpeg)

**Comment by ameshkov** [comment]
Could you please check the browser console? Are there any errors printed there when this happens?

**Comment by grihhih** [comment]
> Are there any errors

Yes.
'Failed to load resource: ERR_CONNECTION_TIMED_OUT'

Sometimes this:
'Failed to load recourse: ERR_CONNECTION_REFUSED'

**Comment by Chinaski1** [comment]
Also, you should try to check `hosts` file. Are there any entries that could potentially block the captcha?
In addition to this, I think you can turn on [Google DNS](https://kb.adguard.com/en/general/dns-providers#google-dns) and try again.

**Comment by pipka00** [comment]
Hello again!

> Also, you should try to check `hosts` file. Are there any entries that could potentially block the captcha?

`Hosts` files are empty. More precisely, they contain only one record (`127.0.0.1 localhost`). 

> In addition to this, I think you can turn on [Google DNS](https://kb.adguard.com/en/general/dns-providers#google-dns) and try again.

When I set the DNS you specified, the Internet disappears at all. Absolutely everything stops working. The error `DNS_PROBE_FINISHED_NO_INTERNET` appears.

For the sake of experiment, I checked different DNS services (Adguard, Cloudflare, Quad9). The problem persists.

If this plays a role, the Google web page (YouTube inclusive) displays the error `ERR_CONNECTION_REFUSED` or `ERR_CONNECTION_TIMED_OUT`.

What can you tell me to do? Is there a way to register?

**Comment by Chinaski1** [comment]
You have Google services blocked, and captcha is sent from their addresses. ([This is where it should be](https://uploads.adguard.com/Chinaskiltxtm.png))
Try to use [this](https://kinsta.com/blog/err_connection_timed_out/) or similar instruction to solve the issue.

**Comment by gogib** [comment]
> Try to use [this](https://kinsta.com/blog/err_connection_timed_out/) or similar instruction to solve the issue.

Hello again!
I hope I'm not giving you any trouble with this issue ;)

I carefully read the instructions and followed the steps indicated in it. Nothing has changed. The `ERR_CONNECTION_REFUSED` and `ERR_CONNECTION_TIMED_OUT` errors persisted.

Checked on the VM the problem persists. Are there any other recommendations? Could it be a regional ban? How can I check it? For example  VPN doesn't help in this case.

**Comment by jikoph** [comment]
I'm sorry to bother you. It's been two weeks since my last response. Is there any solution to this situation?

**Comment by Chinaski1** [comment]
Unfortunately, there is nothing we can do on our side to solve this issue :(
Maybe it's geoblocking or something similar.
