### ISSUE TITLE
Removed language code from homepage URLs

### ISSUE THREAD

**Issue by Vitalik93** [AdguardTeam/AdguardBrowserExtension#1784]
Ссылки на описание многих фильтров ведут на [английскую версию](https://kb.adguard.com/en/general/adguard-ad-filters#english) сайта с описанием, а некоторые [на русскую](https://kb.adguard.com/ru/general/adguard-ad-filters#russian). Может стоит для русской версии расширения сделать все ссылки на русскоязычную версию сайта?

![Снимок экрана 2021-03-29 144416](https://user-images.githubusercontent.com/34383288/112838380-4bbee900-909d-11eb-8701-57c7f2d7e75f.png)

**Comment by Chinaski1** [comment]
Добрый день, [исправили](https://github.com/AdguardTeam/FiltersRegistry/pull/451). Будет добавлено в грядущем обновлении v3.6
