### ISSUE TITLE
Ckumy

### ISSUE THREAD

**Issue by ckumy** [AdguardTeam/AdguardBrowserExtension#1787]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 
- **Browser and version:**
  - 
- **Operating system and version:**
  - 
- **Filters you use in AdGuard:**
  - 
- **Stealth Mode settings:**
  - 
- **Other browser extensions:**
  - 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by anastenko** [comment]
Hello.

Could you specify the issue?
