### ISSUE TITLE
Testing v2.2

### ISSUE THREAD

**Issue by Mizzick** [AdguardTeam/AdguardBrowserExtension#179]
Please test latest dev build https://github.com/AdguardTeam/AdguardBrowserExtension/releases/tag/v2.2-dev

**Comment by Mizzick** [comment]
@gshumihin please take a look at new dev build https://github.com/AdguardTeam/AdguardBrowserExtension/releases/tag/v2.2.1
with some extra attention to Palemoon

**Comment by ameshkov** [comment]
@gshumihin is it good?

**Comment by gshumihin** [comment]
yep, its ok
