### ISSUE TITLE
Block Floc checks in Chrome?

### ISSUE THREAD

**Issue by YBS-PC** [AdguardTeam/AdguardBrowserExtension#1791]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

**Comment by anastenko** [comment]
Hello.

AdGuard already blocks Google FloC via Tracking Protection filter. You can read more info about it on our [telegram channel ](https://t.me/adguarden/353)
