### ISSUE TITLE
Improving UI

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdguardBrowserExtension#1793]
**_I will add new content to the Issue as improvements are found._**
- **In statistics:** 
Remove useless scrolling in 2mm. By shrinking the list vertically to fit everything.
Even if there is scrolling, the last line is cut from the bottom.

![ScreenFlow](https://user-images.githubusercontent.com/62497891/115230779-185c0100-a115-11eb-90d8-789255fca314.gif)

**Comment by Oleg-Chashko** [comment]
- **In statistics:**
It is difficult to understand that these two icons are related.
<img width="442" alt="1" src="https://user-images.githubusercontent.com/62497891/115235300-54459500-a11a-11eb-8036-81d260862a2f.png">

1. Example:
Align left and move the icon to the left.
<img width="442" alt="1 Kopie 2" src="https://user-images.githubusercontent.com/62497891/115235679-bdc5a380-a11a-11eb-9946-7b6fefe16139.png">

2. Example:
Create a field.
<img width="442" alt="1 Kopie" src="https://user-images.githubusercontent.com/62497891/115235823-e8aff780-a11a-11eb-8842-c839ab0f9eb5.png">

**Comment by Oleg-Chashko** [comment]
- **Extension icon**
The number of blocked "AD" in the extension icon, please align horizontally and vertically.
<img width="184" alt="1" src="https://user-images.githubusercontent.com/62497891/115238392-ed29df80-a11d-11eb-9d4c-47a2394034ac.png">

1. Example:
<img width="184" alt="1 Kopie" src="https://user-images.githubusercontent.com/62497891/115238421-f3b85700-a11d-11eb-9869-bdd0da985c1b.png">

**Comment by Oleg-Chashko** [comment]
- **The funnel & labels in buttons:**
Move the funnel icon to the right. In all buttons, raise the labels slightly to the top so that the labels are in the center of the buttons.
<img width="398" alt="2" src="https://user-images.githubusercontent.com/62497891/115240315-e8662b00-a11f-11eb-9e85-106b1e73de3c.png">
<img width="418" alt="3" src="https://user-images.githubusercontent.com/62497891/115240499-16e40600-a120-11eb-8853-c7fce719c6bf.png">


_I give you your example where everything is OK._
<img width="214" alt="4" src="https://user-images.githubusercontent.com/62497891/115240582-2e22f380-a120-11eb-9abe-c1b7b23385cd.png">

**Comment by Oleg-Chashko** [comment]
- **New filter subscription:**

1. Move text to the left.
2. Add contrast "X".
3. Center the text box vertically.
<img width="931" alt="1" src="https://user-images.githubusercontent.com/62497891/115242105-d9807800-a121-11eb-96b7-a77a31cbbedd.png">

**Comment by maximtop** [comment]
Hi, @Oleg-Chashko. Thank you for your review and testing. Currently we are in the end of UI refactoring. And there would be some small changes. So, please do not waste your time and please come back when beta 3.6 would be released.

**Comment by Oleg-Chashko** [comment]
> Hi, @Oleg-Chashko. Thank you for your review and testing. Currently we are in the end of UI refactoring. And there would be some small changes. So, please do not waste your time and please come back when beta 3.6 would be released.

Hi, @maximtop. Thank you for the warning.
1. When to expect beta 3.6? 
2. Should I delete the topic or not? 
Thank you Maxim!

**Comment by maximtop** [comment]
1. I hope that it will be released in a week or two.
2. Yeah, it would be better to remove this topic and create a new one when it's time.
