### ISSUE TITLE
TOGGLE JAVA ON/OFF MISSING PLUS MORE

### ISSUE THREAD

**Issue by YesTrustMe** [AdguardTeam/AdguardBrowserExtension#1798]
I have seen it before a few months ago, but now I can't find it.

As a suggestion, please have a detailed directory using a sidebar with hyperlinks with all the features instead of us having to go the very long route to access features that are buried within each category.

Also, adding a stop autoplay feature would be extremely useful against media (videos) that jump at you and slow you down.

**Comment by anastenko** [comment]
Hello.

Could you give us more details on your request? It's not quite understandable.

**Comment by zzebrum** [comment]
@YesTrustMe in the nearest future we don't have big plans for redesigning the extension.

> TOGGLE JAVA ON/OFF

browser extension doesn't have this feature, while desktop apps for MacOS and Windows does have Block Java option.
