### ISSUE TITLE
Page loading bug

### ISSUE THREAD

**Issue by anandssm** [AdguardTeam/AdguardBrowserExtension#1799]
Sometimes it slows down the connection for infinite period ...
![Screenshot_2021-05-01-05-45-32-92_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/83481224/116764999-c2eef080-aa40-11eb-9828-619220894032.jpg)

**Comment by zzebrum** [comment]
@anandssm does it happens only on Github?

**Comment by Chinaski1** [comment]
Closed due to no response.
