### ISSUE TITLE
Adguard extension for Firefox 44.0 causes console error

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardBrowserExtension#180]
Happens in Firefox v.44.0+ if you go to https://myspiritedart.rezclick.com and open Developer tools -> Console. It contains following line, marked as 'Error':

Content Security Policy: Параметры страницы заблокировали загрузку ресурса в self ("script-src https://myspiritedart.rezclick.com https://*.rezclick.com").

The screenshot is here:
http://screencast.com/t/YLc2xhiMu0k3

Error does not come up if you disable Adguard extension.

EZA-540-12610

**Comment by ameshkov** [comment]
That happens because of JS rules which are being blocked by website's CSP.
That is expected behavior, I am not sure if we should do anything with that.

**Comment by ameshkov** [comment]
Of course it is possible to edit CSP and allow inline scripts, but I am not sure if it is a right thing to do from the "security" point of view..

**Comment by Mizzick** [comment]
One more issue with CSP
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/140
