### ISSUE TITLE
Generic CSS exclusions

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#1801]
We should make `#@#.adsbygoogle` and `*#@#.adsbygoogle` work the same way - completely disable matching CSS/elemhide rules on ALL domains.

Here's what needs to be done:

* Update the code to match this behavior
* Add a note to KB about this
* Add a test case to testcases.adguard.com

**Comment by XX-J** [comment]
Не знаю к этому относится или нет, но:
 Пару дней назад стал пользоваться таким правилом: `#$#html { scrollbar-width: unset !important; scrollbar-color: #55698a #edeae4; }` (тёмно-синие скролы). Правило работает везде, кроме почты [https://e.mail.ru/inbox/](https://href.li/?https://e.mail.ru/inbox/).
 Проверял и так `*#$#...`, и эдак `#$?#...`, - не работает. Заработало только с припиской, в начале, домена - `e.mail.ru#$#...`

**Comment by ameshkov** [comment]
Наверняка для почты `$generichide` исключение есть

**Comment by XX-J** [comment]
> Наверняка для почты $generichide исключение есть

 В Журнале такого исключения нет, как и моего правила. Зато есть правило, подтверждающее отсутствие исключения `$generichide`  -  `#%#//scriptlet('set-constant', 'Document.prototype.interestCohort', 'undefined')` из "Фильтра счетчиков и систем аналитики".

**Comment by XX-J** [comment]
В исключениях "Русского фильтра" правила `@@||e.mail.ru^$generichide` не нашёл. Но всё-равно решил попробовать правило `@@||e.mail.ru^$generichide,badfilter`, и, о чудо!  -  Сработало!  Большое Спасибо, Андрей, за помощь!
