### ISSUE TITLE
$removeparam is not applied to some redirects

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1805]
### Issue Details

- **AdGuard version:** 3.6
- **Browser and version:** Chrome 90
- **Operating system and version:** Windows 10
- **Filters you use in AdGuard:** Base filter, Social filter
- **Stealth Mode settings:** all

### Actual Behavior

Original link:
https://www.pepper.ru/visit/thread/176974
When you open is, there are will be few redirects:
1. `https://visit.digidip.net/visit?pid=793&generated=shortener&url=https%3A%2F%2Fwww.mvideo.ru%2Fproducts%2Fkabel-opticheskii-hi-fi-belkin-av10009qp1m-50036181%3Fnull%26_requestid%3D76813&ppref=https%3A%2F%2Fwww.pepper.ru&ref=128927846`
2. `http://ad.admitad.com/g/c9f1ad68bcde02b6793e3a3184f61a/?ulp=https://www.mvideo.ru/products/kabel-opticheskii-hi-fi-belkin-av10009qp1m-50036181?null&_requestid=76813`
3. `http://www.mvideo.ru/products/kabel-opticheskii-hi-fi-belkin-av10009qp1m-50036181?reff=admitad_cpa_campaign_content&null=`

The rules:
`||visit.digidip.net^$removeparam=/^(ppref|ref|pid)=/`
`||ad.admitad.com/g/$removeparam=subid`
`||mvideo.ru^$removeparam=/^(_requestid|reff)=/`

1 and 2 works as expected, but 3 - not applied. But when I refresh destination page - parameters removed.

**Comment by wout-codes** [comment]
Also reproducible in `https://new.edmodo.com/`, then clicking the login button. Same results with the extension + the apps.

**Comment by maximtop** [comment]
In the Chrome browser, the `onBeforeRequest` event doesn't fire twice when search parameters are removed from the redirect url, thus we have decided to rework the "Remove tracking parameters" setting. Now it will toggle "AdGuard URL Tracking filter"
