### ISSUE TITLE
Youtube ad not blocked! (creator pls expain)

### ISSUE THREAD

**Issue by arandomdev015** [AdguardTeam/AdguardBrowserExtension#1808]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version, yes
- [ ] I checked the documentation and found no answer, no
- [x] I checked to make sure that this issue has not already been filed, yes

### Issue Details

- **AdGuard version:**
  -  Version 3.5.34
- **Browser and version:**
  -  chrome
- **Operating system and version:**
  -  MacBook 2015, mac OS big slur
- **Filters you use in AdGuard:**
  -  none
- **Stealth Mode settings:**
  -  Yes
- **Other browser extensions:**
  -  The others do not interfere

### Expected Behavior

 blocked ad

### Actual Behavior, it's not blocking this thing,check screenshot

 looking up a video

### Screenshots 
![Screen Shot 2021-05-17 at 4 59 12 PM](https://user-images.githubusercontent.com/82900978/118574966-5eb77680-b73a-11eb-86a9-34ccd326fe83.png)

 up there

<details><summary>Screenshot:</summary>

 up there

</details>

### Additional Information

 none

**Comment by anastenko** [comment]
@arandomdev015
We couldn't reproduce this issue on our side. Could you specify what filters do you use?

**Comment by anastenko** [comment]
Also try clearing cache and browser history, that might help.

**Comment by anastenko** [comment]
@arandomdev015 Any news?

**Comment by Chinaski1** [comment]
@arandomdev015 
Any news?

**Comment by arandomdev015** [comment]
No, it is still there, i can't remove it, the filter is always on

**Comment by anastenko** [comment]
@arandomdev015 What filters do you use?

**Comment by anastenko** [comment]
I'm closing this task due to no response.
If this issue occurs again, please reopen it and provide us more information.

**Comment by arandomdev015** [comment]
Hello, this situation has bottom worse. I have cleared cookies and cache nothing works, there more ads that are not blocked please help and sorry for the late reply

**Comment by anastenko** [comment]
@arandomdev015 In order to investigate this issue we'll need you to send us exported settings of your extension.

Here's what we need you to do:

- Go to AdGuard settings page - General
- Click "Export settings"
- Send exported settings to "devteam@adguard.com"
