### ISSUE TITLE
[AdGuard extension, Windows] No filter rules loaded (Number of filter rules: 0)

### ISSUE THREAD

**Issue by szemley** [AdguardTeam/AdguardBrowserExtension#1810]
Hello.

I think, that it's not a bug - per se - but information about "Number of filter rules" shows 0. Yesterday, after AdGuard install and configuration (enable various lists, so-called "Stealth Mode" etc.), there was about 200.000 rules and everything worked okay.

However, today I noticed, that nothing is blocked - I mean e.g. various elements on websites, removed yesterday via AdGuard (vide context menu - "check and block" method). It turned out, that "Number of filter rules" is 0 - so no rule is loaded. Also, adding some filter list via URL link, when AdGuard is checking that list - it takes very long time and probably does not end (yesterday,  it worked very quickly). All choosed lists - in various sections, such as Social widgets, Privacy and so on - are enabled. Additionaly, rules added/created by the User are visible, but don't block anything.

I tried to disable/enable AdGuard, restart web browser and so on. Is there something, that could help? (Probably reinstall could help, but reinstalling AdGuard every day is not a solution).  Additional info:

o Version: 3.5.34,
o Web browser: Firefox 52.9.0 (fortunately, for a few more days),
o OS: Windows Vista (SP 2) (see above),
o Stealth mode: enabled.
 
I apologize for the lack of more accurate information, but this is basically everything.

Thanks, best regards.

**Comment by Chinaski1** [comment]
Hello there!

To find out the cause of the issue you need to open your browser -> Extensions -> Debug add-ons -> Turn on the "Debug add-ons" checkbox -> Click on "Debug" AdGuard -> Send a screenshot of the error screen

**Comment by Chinaski1** [comment]
@szemley 

Any news?

**Comment by Chinaski1** [comment]
Closed due not response.

**Comment by szemley** [comment]
Hi.

I'm so sorry for such a long time without answer. I wanted to debug AdGuard extension, but Firefox asked for incoming connection and so on. But - according to system and browser version - I didn't decided to perform debug etc.

Once again - apologize.

Best regards.
