### ISSUE TITLE
AdGuard Turkish filter is not enabled automatically

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1811]
### Issue Details

- **AdGuard version:** 3.6
  - 
- **Browser and version:** last Chrome / Opera
  - 
- **Operating system and version:** Windows 10
  - 
- **Filters you use in AdGuard:** Base
  - 
- **Stealth Mode settings:** no
  - 
- **Other browser extensions:** no
  - 
 
`Activate the most appropriate filters automatically` option is enabled.

### Expected Behavior

AdGuard Turkish filter turns on.

### Actual Behavior

AdGuard Turkish filter not turns on. Visited a dozen of Turkish sites(`.com.tr` and with another TLDs)

**Comment by gork7777** [comment]
I tested this on Chrome but Turkish filter is automatically enabled for me
