### ISSUE TITLE
Notification keep spamming me

### ISSUE THREAD

**Issue by Dr-Snuggles** [AdguardTeam/AdguardBrowserExtension#1813]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

Th notification for version update pops up every other page visit (with the same version). It should be possible to turn it off and ,if it is on, it should only be seen once.

- **AdGuard version:**
AdGuard v3.6.6
- **Browser and version:**
Chrome 90
- **Operating system and version:**
Windows 10
- **Filters you use in AdGuard:**
Base filter
- **Stealth Mode settings:**
Off
- **Other browser extensions:**
- None

### Expected Behavior

The notice should only pop up once (or never if turned off)

### Actual Behavior

The notification pops up every other page visit.

### Screenshots
![2021-05-29_10-59-11](https://user-images.githubusercontent.com/6368737/120239088-d4086880-c25d-11eb-84b8-85623b58638c.png)

<details><summary>Screenshot:</summary>

</details>

**Comment by ameshkov** [comment]
In theory, this is only possible if Chrome for some reason does not persist configuration changes.

Do you have any registry cleaner or anything like that? Something, that may mess with Chrome extensions' persistent storage?

**Comment by ameshkov** [comment]
@maximtop maybe let's start using `chrome.storage` instead of the `localStorage` there? I suspect that all these cleaners won't mess with `chrome.storage`

**Comment by Dr-Snuggles** [comment]
Well, I did turn off notifications. Those settings and all the other settings are saved (whitelist, notification on/on buttons etc..), so it does manage to save the settings, and they do persist. However the setting for notification seem to be ignored.

![chrome_2021-06-01_10-03-17](https://user-images.githubusercontent.com/6368737/120288584-ab658a80-c2c0-11eb-92df-5ff50ac816e1.png)

I haven't noticed any other localStorage data getting wiped. Other apps can save persistently to localstorage.

**Comment by ameshkov** [comment]
@Dr-Snuggles please do the following:

1. Go to `chrome://extensions`
2. Switch to "developer mode"
3. Find AdGuard, click on "background.html"
4. You'll see a "developer tools" window. Switch to the "Console" tab there
5. Copy/paste the following script there:

```
chrome.storage.local.get(['adguard-settings'], (result) => {
    console.log(result['adguard-settings']['app-version']);
});
```

What will it print to the console?

**Comment by zzebrum** [comment]
@Dr-Snuggles any update?

**Comment by Dr-Snuggles** [comment]
It says 3.6.6 :)
However the problem seem to have gone away now. I seem to have been using beta-version and as soon as i switched to the stable things work again.

**Comment by anastenko** [comment]
@Dr-Snuggles In this case I'm closing this issue. Let us know if there are any issues in the future.
