### ISSUE TITLE
Shortcut: Toggle Javascript

### ISSUE THREAD

**Issue by ChiIllHOLA** [AdguardTeam/AdguardBrowserExtension#1814]
![image](https://user-images.githubusercontent.com/84558486/120294549-e2f02900-c2f8-11eb-88d2-73e41b58a8a6.png)

Similar to Ublock Origin's feature of enabling and disabling javascript on a certain website, why not for Adguard as well? 

This is merely a shortcut of having to create your own filter rules and it's integration will be in the user rules section.

It should be one of the options available once you click on the extension or in the browser context menu to make it more accessible when deciding to use it.

Cheers, Pete

P.S.
Maybe a `disable javascript on all sites` feature is needed too :)

**Comment by anastenko** [comment]
@ChiIllHOLA Hi. 
We already have [similar issue](https://github.com/AdguardTeam/AdGuardForSafari/issues/488), so I'm closing this one.
