### ISSUE TITLE
AdGuard hides valid page contents

### ISSUE THREAD

**Issue by Molkree** [AdguardTeam/AdguardBrowserExtension#1815]
### Issue Details

- **AdGuard version:**
  - Version 3.6.5
- **Browser and version:**
  - Chrome 91
- **Operating system and version:**
  - Windows 10
- **Filters you use in AdGuard:**
  - Base filter
  - Other: Filter unblocking search ads and self-promotion
  - Language-specific: AdGuard Chinese filter, AdGuard French filter, AdGuard German filter, AdGuard Japanese filter, AdGuard Russian filter, EasyList Italy, List-KR, Dandelion Sprout's Nordic Filters
- **Stealth Mode settings:**
  - Disabled
- **Other browser extensions:**
  - Doesn't matter as I can see this issue in incognito mode with AdGuard being the only extension enabled. Unless not enabled extensions can somehow interfere then I will provide the list.

### Expected Behavior

Text and images visible at this [link](https://tardis-sn.github.io/tardis/sponsors.html).

### Actual Behavior

Text and images are hidden.

### Screenshots

<details><summary>How it should be:</summary>

![image](https://user-images.githubusercontent.com/12860284/120350111-5a2cb980-c307-11eb-8814-418403d203bc.png)

</details>

<details><summary>How it is now:</summary>

![image](https://user-images.githubusercontent.com/12860284/120350198-70d31080-c307-11eb-9870-f4a25e307550.png)

</details>

### Additional Information

AdGuard says that it blocked 0 ads yet somehow contents of the page disappear.

**Comment by anastenko** [comment]
@Molkree Hi.
The counter shows only blocked urls, not hidden or modified elements, that's why you need to check the filtering log.

**Comment by anastenko** [comment]
@Molkree We've already deleted this rule from Russian filter, so try updating filters after a couple of hours. Or use `tardis-sn.github.io#@##sponsors` as a temporary solution.

**Comment by Molkree** [comment]
Thanks, it was quick!
