### ISSUE TITLE
Not ordinary behavior pseudo-class :remove() with :upward()

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardBrowserExtension#1817]
**1**. Если применить правило `example.com##a:upward(div):remove()`, то элемент скроется, а не удалится.

<details><summary>Screenshot:</summary>

![2021 06 01-2](https://user-images.githubusercontent.com/17948007/120580379-c4da1400-c431-11eb-867c-3f179423ce4b.png)
</details>
<br>

 А если такое: `example.com#$#a:upward(div) { remove: true; }`, то удалится.

<details><summary>Screenshot:</summary>

![2021 06 02-1](https://user-images.githubusercontent.com/17948007/120580722-547fc280-c432-11eb-81c5-da18f0994296.png)
</details>
<br>

 Удаляться должен в обоих случаях.

[https://example.com](https://example.com)

___________________________________________________

 **2**. Если применить правило, например `example.com##.ab, .bc, .cd:remove()`, то удаляются все перечисленные классы, но по написанию кажется что только последний, а остальные скрываются.
 Так и задумано или это неправильное поведение и подразумевалось, что для каждого удаляемого элемента надо писать свой `:remove()`?
 А если задумано, то может стоит изменить? Ведь написание `example.com##.ab:remove(), .bc, .cd:remove()` более точно отображает что правило скрывает, а что удаляет.

___________________________________________________
 Adguard v3.6.6 | FireFox v78.10 ESR | Win7SP1
Базовый фильтр AdGuard | Фильтр отслеживания по URL | Фильтр счетчиков и систем аналитики
Фильтр виджетов социальных сетей | Фильтр раздражителей | Русский фильтр
 Антитрекинг: Стандарт + Блокировка WebRTC

**Comment by anastenko** [comment]
@XX-J Приветствую!
1. Да, действительно `example.com##a:upward(div):remove()` должно удалять, а не скрывать элемент.
2. Лучше не составлять правила таким образом, а следовать принципу "одно правило - один селектор"

**Comment by XX-J** [comment]
> 2. Лучше не составлять правила таким образом, а следовать принципу "одно правило - один селектор"

 Мне не нужны рекомендации, мне нужно чёткое следование логики - Вашей или моей.

**Comment by anastenko** [comment]
@XX-J Для того, чтобы некоторые элементы были скрыты, а другие удалены, необходимо использовать разные правила.
Например, `example.org #? # h1, a: remove ()` удаляет все элементы, которые совпадают с обоими селекторами, а для того, чтобы скрыть какие-то элементы, уже отдельно прописывается соответсвующее правило.

**Comment by XX-J** [comment]
> Для того, чтобы некоторые элементы были скрыты, а другие удалены, необходимо использовать отдельные правила.

 Это официальная позиция команды AdGuard, касаемо моего второго вопроса?
 И она не может быть изменена?

**Comment by slavaleleka** [comment]
синтаксис псевдокласса [:remove()](https://github.com/AdguardTeam/ExtendedCss/#remove-pseudos) такой:
```
selector:remove()
```

и подразумевается, что может быть указан не один, а несколько селекторов через запятую, и только в конце `:remove()`. в таком случае все элементы удалятся. менять это не планировали

**Comment by anastenko** [comment]
Issue moved to [AdguardTeam/AdguardFilters #85135](https://github.com/AdguardTeam/AdguardFilters/issues/85135) via [**ZenHub**](https://www.zenhub.com/)
