### ISSUE TITLE
Clicking on acceptable ad leads to about:blank

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardBrowserExtension#182]
Safari 9.0.3, El Capitan.

Screen recording here:
https://www.dropbox.com/s/sxr58qgukjuzlpa/adguard%20bug.mp4?dl=0

**Comment by ameshkov** [comment]
Which filters are enabled?

**Comment by Alex-302** [comment]
Added to Safari filter:
```
@@||googleadservices.com/pagead/aclk?
```

**Comment by Bileence** [comment]
<img width="1052" alt="screen shot 2016-03-04 at 12 32 19" src="https://cloud.githubusercontent.com/assets/17642148/13525986/315073f0-e205-11e5-8948-b178f3e11022.png">
<img width="1076" alt="screen shot 2016-03-04 at 12 33 00" src="https://cloud.githubusercontent.com/assets/17642148/13525999/4b34d7ac-e205-11e5-8064-0b5b57203a2b.png">

**Comment by Alex-302** [comment]
@Bileence 
please check the rule above

**Comment by ameshkov** [comment]
Some tech details.

"if-domain" option of the Content Blocker API does not work when the link is opened in a new tab, that's why even google.com whitelisting did not help.
