### ISSUE TITLE
$removeparam modifier entries not showing which filterlist is used

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardBrowserExtension#1820]
### Issue Details
$removeparam modifier entries are not shown individually in the filtering logs and do not show which filter list include the $removeparam modifier entries making it difficult for me to debug anything as i don't know which filter have a specific $removeparam modifier . The solution for now for this is that i open all of my custom filter files and then search if a particular  $removeparam modifier rule .

***Issue URL ( example )**: https://www.google.com/search?q=adguard

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
+ https://raw.githubusercontent.com/chirag127/adblock/main/PRM.txt

</details><br/>

### Expected Behavior

A clear and concise description of what you expected to happen is $removeparam modifier entries shown individually in the filtering logs and filtering log should show which filter list includes a particular $removeparam modifier entry.

### Actual Behavior

A clear and concise description of what actually happened is  $removeparam modifier entries are not shown individually in the filtering logs and filtering log not show which filter list includes a particular $removeparam modifier entry.

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/76880977/121664788-7e398900-cac5-11eb-860a-7a9cab73bfa5.png)
![image](https://user-images.githubusercontent.com/76880977/121664798-80034c80-cac5-11eb-9eb6-611132163774.png)

</details>

**Comment by anastenko** [comment]
@chirag127 Hello. 
We'll fix it in v4.0.

**Comment by chirag127** [comment]
how is it going on?

**Comment by anastenko** [comment]
@chirag127 These changes should be included in v4.0.

**Comment by chirag127** [comment]
> @chirag127 These changes should be included in v4.0.

I'm on the beta version.

**Comment by maximtop** [comment]
@chirag127 rules with removeparam modifier are shown in the separate filtering log events in the AdGuard Extension 4.0,
Isn't what this issue was about?
![image](https://user-images.githubusercontent.com/17272769/144816174-0b454238-d173-483c-a62f-f9d68b2a085c.png)
