### ISSUE TITLE
can't block $removeparam modifier  from filtering logs.

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardBrowserExtension#1821]
### Issue Details
 
Can't block parameters from the filtering logs.

An option to $removeparam modifier is not present in the blocking tool via filtering logs .

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/120335071-cced6300-c30e-11eb-82ff-4117fe1291dd.png)
+ https://raw.githubusercontent.com/chirag127/adblock/main/EDU.txt

</details><br/>

### Expected Behavior

An option to $removeparam modifier is present in the blocking tool via filtering logs .

### Actual Behavior

An option to $removeparam modifier is not present in the blocking tool via filtering logs .

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/76880977/121807383-82a2a500-cc71-11eb-851d-12b116819d56.png)
![image](https://user-images.githubusercontent.com/76880977/121807384-82a2a500-cc71-11eb-85da-c9e3e468cf8d.png)

</details>

**Comment by anastenko** [comment]
@chirag127 Hi. 
For now there's no possibility to block `$removeparam` via filtering log, but it sound like a good suggestion. We'll consider it for the future updates.

**Comment by chirag127** [comment]
how is it going on ?

**Comment by slavaleleka** [comment]
it will be fixed in upcoming v4.0

**Comment by chirag127** [comment]
> it will be fixed in upcoming v4.0

I'm using beta but seems not fixed.

**Comment by maximtop** [comment]
In the released version is working as expected, feel free to open this issue again if it is not true.
