### ISSUE TITLE
ADGUARD Desktop completely blocks all internet connectivity EVEN when not active at startup.

### ISSUE THREAD

**Issue by U-Go-7** [AdguardTeam/AdguardBrowserExtension#1825]
- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

### Issue Details

I tried to use the desktop version because of the supposedly more powerful features and the system wide filtering.
I have a question and a issue.

Question: why do I need a browser app to allow the desktop app to work within that browser? What kind of "system wide" app needs that? And what do I do if I use several browsers for different purposes, some of which have no specific companion app and need me to choose the generic adguard companion app, but some of them have a specific companion app, and yet in the settings of Adguard I must choose EITHER the specific OR the generic companion app?

Issue: I can't use internet anymore. Any website I try to open, in any browser, says that there is a security risk, which is related to Adguard.
So, considering that in this moment I do not have the time to test which one of the thousand settings is responsible for this, I just deactivated the desktop app and chosen it not to run at startup.
Things worked fine in that session but as soon as I restarted windows, internet was not working. Same security issue.
So I opened Adguard and turned it on (it turns on automatically when I open it. I did not look if there is an option to avoid that but I take the occasion to say that, if there is none, it would be nice to have it), and I closed it, choosing "no" so that it won't run in the background.
Once again, all good, until the next system start-up.
So  I did the same thing and then immediately uninstalled Adguard.

I admit, I am super busy and the search for previous issues here is not super intuitive so I might have missed if this was already answered, please feel free to point me to the previous answer in that case.

Thanks

- **AdGuard version:**
last as of today
- **Browser and version:**
many, last version as of today
- **Operating system and version:**
win 10 64 last update as of today
- **Filters you use in AdGuard:**
mostly all as far as I remember. All what I could turn on I turned it on.
- **Stealth Mode settings:**
on
- **Other browser extensions:**
clearURLsbut it did not make a difference without

### Expected Behavior

well, I did expect that maybe some functions of some websites would not work, but what's the point of giving people the choice to activate all options at once if that completely breaks all internet connection?

### Actual Behavior

completely broke all internet functionality

### Screenshots

sorry, got lazy in this occasion. If you can't reproduce I will reinstall and se what I can do.

**Comment by anastenko** [comment]
Issue moved to [AdguardTeam/AdguardForWindows #3831](https://github.com/AdguardTeam/AdguardForWindows/issues/3831) via [**ZenHub**](https://www.zenhub.com/)
