### ISSUE TITLE
BiliBili anti-theft chain mechanism and Adguard Browser Extension stealth mode conflict

### ISSUE THREAD

**Issue by CHIZI-0618** [AdguardTeam/AdguardBrowserExtension#1826]
### Prerequisites

- I am running the latest version
- I checked the documentation and found no answer

### Issue Details

- **AdGuard version:**
    v3.6.6
- **Browser and version:**
    Chrome 91.0.4472.114    
- **Operating system and version:**
    Windows 10 21H1 19043.1055
- **Filters you use in AdGuard:**
    Base filter
- **Stealth Mode settings:**
    Enabled
- **Other browser extensions:**
    Closed

### Expected Behavior

Enable stealth mode "hidden references, to prevent third-party visualization" mode
Video loading without error

### Actual Behavior

Enable stealth mode "hidden references, to prevent third-party visualization" mode
Video loading error and the video cover cannot be displayed. Please check the screenshot for details

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/51962278/123189163-eb8ae800-d4cf-11eb-9cef-cb5dd742f4fe.png)
![image](https://user-images.githubusercontent.com/51962278/123189182-f3e32300-d4cf-11eb-86a6-696fa2970bc1.png)
![image](https://user-images.githubusercontent.com/51962278/123189201-f9406d80-d4cf-11eb-9196-3916fff894eb.png)

</details>

### Additional Information

#1569 The solution mentioned is currently unreliable after testing

https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_English/filter.txt#:~:text=%40%40%7C%7Cbilivideo.com%5E%24stealth%2Cdomain%3Dbilibili.com

Please take care of my poor English, thank you for your work

**Comment by anastenko** [comment]
@CHIZI-0618 Hello.
We couldn't reproduce it on our end. Videos work just fine for me.
Could you give us the full list of filter that you use? Any custom filters?
Does it depend on the type of video you watch or it blocks all videos?

**Comment by CHIZI-0618** [comment]
@anastenko 
It can be triggered by playing a video from this [URL](https://www.bilibili.com/v/popular/all). It is guessed that only "popular" videos have been processed.
I made sure to turn off all filters (including custom filters) and turn off all other browser extensions during the test.
Although an error will be reported when the video loads, there is a certain probability that the video can be played normally. Of course, this requires a long loading time and the video cover will not be displayed.
If you still can’t reproduce it, I’ll try to record the video and send it to your mailbox, which requires research.
Thanks!

**Comment by anastenko** [comment]
@CHIZI-0618 
Sadly I can't reproduce it no matter what I try :(

Could you please reinstall the extension and monitor its behavior? As I can see you use some other extensions, so please turn them off as they might affect our extension work.
Also send us the exported settings, so we could set them exactly the way you set it.

**Comment by anastenko** [comment]
@CHIZI-0618 Any news?

**Comment by CHIZI-0618** [comment]
> @CHIZI-0618 Any news?
@anastenko 
I’m sorry to keep you waiting, I finally made up my mind to disable all browser extensions for testing,
And I also closed all ad blocking rules (including customization!)
However, the test result is still that the cover and video content cannot be loaded after entering the video from the [popular video page.](https://www.bilibili.com/v/popular/all)
[Here is the screen recording file
](https://daiyu.lanzoui.com/ihvCErjqg2f)

**Comment by anastenko** [comment]
@CHIZI-0618 Hi. You can simply send us the settings of yours. The button for exporting is situated in "General" section of AdGuard settings. 
"Keep log" button doesn't save the log as a file, it serves to keep all log requests even after you refresh the opened page. The log will be cleared once you refresh the opened page if "Keep log" is disabled.

**Comment by CHIZI-0618** [comment]
This is the setting item I exported
[20210720_214806_adg_ext_settings_3.6.6.json.txt](https://github.com/AdguardTeam/AdguardBrowserExtension/files/6848804/20210720_214806_adg_ext_settings_3.6.6.json.txt)
Please delete the .txt file suffix (because GitHub does not accept json files here).
Hope this file will help you.
Thanks! @anastenko

**Comment by anastenko** [comment]
@CHIZI-0618 Hello.
I've imported your settings in order to reproduce it, but no luck. 
Does it depend on whether you're singed in or not? Did you try watching with VPN?
Honestly, no idea what can cause it :(

**Comment by CHIZI-0618** [comment]
In fact, I am using the [Clash](https://github.com/Dreamacro/clash) proxy software, but I did not proxy the bilibili website, and it did not affect the results after testing.

**Comment by anastenko** [comment]
@CHIZI-0618 We're really happy the issue was solved on your side. 
Sadly this function doesn't change the situation for my pc, still can't reproduce it. I'm afraid we can't do anything about it.
