### ISSUE TITLE
Adguard Report Wizard should recognize AdguardExtra extension/userscript and URLS for external filters

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardBrowserExtension#1827]
### Problem Description
Adguard Browser Extension does not include information about custom user scripts and external URLs filters in Wizard Report.
Adguard Report Wizard should recognize `Adguard Extra` extension/userscript present and URLs for external filters if are used.

**Comment by anastenko** [comment]
@FadeMind Hello.
Are you talking about [this feature](https://reports.adguard.com/en/new_issue.html)?

**Comment by FadeMind** [comment]
@anastenko yes.

**Comment by anastenko** [comment]
Issue moved to [AdguardTeam/ReportsWebApp #279](https://github.com/AdguardTeam/ReportsWebApp/issues/279) via [**ZenHub**](https://www.zenhub.com/)

**Comment by anastenko** [comment]
@FadeMind I've moved this issue to the proper repository, so you can check it there.

**Comment by FadeMind** [comment]
@anastenko thank you
