### ISSUE TITLE
AdGuard Browser Extension keeps notifying it has been updated to v3.6.6

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdguardBrowserExtension#1828]
### Issue Details
- **Browser and version:**
  - Google Chrome Stable, AdGuard Browser Extension 3.6.6
- **Operating system and version:**
  - Windows 10 Enterprise 20H2
- **Filters you use in AdGuard:**
  - Default
- **Other browser extensions:**
  - Bitwarden 

### Expected Behavior

To be notified once, and never again.
Both when the X is clicked, and when disable notifications is clicked.

### Actual Behavior

Every time I open Chrome, it shows the notification.

### Screenshots
![Capture](https://user-images.githubusercontent.com/6005161/123506031-7113c100-d6a5-11eb-9cdc-3babae8555fc.PNG)

**Comment by anastenko** [comment]
@jslawler Hello.
Please do the following:

- Go to chrome://extensions
- Switch to "developer mode"
- Find AdGuard, click on "background.html"
- You'll see a "developer tools" window. Switch to the "Console" tab there
- Copy/paste the following script here:

```
chrome.storage.local.get(['adguard-settings'], (result) => {
    console.log(result['adguard-settings']['app-version']);
});
```
- and tell us the result.

**Comment by zzebrum** [comment]
dup of #1813 
@jslawler any news?

**Comment by jslawler** [comment]
> dup of #1813
> @jslawler any news?

I haven't had access to the affected machine since the issue was raised. I'll update this within the next couple of weeks.

**Comment by jslawler** [comment]
> @jslawler Hello.
> Please do the following:
> 
> * Go to chrome://extensions
> * Switch to "developer mode"
> * Find AdGuard, click on "background.html"
> * You'll see a "developer tools" window. Switch to the "Console" tab there
> * Copy/paste the following script here:
> 
> ```
> chrome.storage.local.get(['adguard-settings'], (result) => {
>     console.log(result['adguard-settings']['app-version']);
> });
> ```
> 
> * and tell us the result.

Code block response:
3.5.31

I'm also heavily getting the below on repeat whenever an action is performed in Chrome, such as a page loading.
> 2021-07-13T19:56:25.716: Corruption: block checksum mismatch
> print @ log.js:79
> error @ log.js:99
> checkError @ local-storage.js:30
> (anonymous) @ local-storage.js:45
> (anonymous) @ deferred.js:123
> execute @ deferred.js:67
> (anonymous) @ deferred.js:152
> reject @ common.js:751
> (anonymous) @ local-storage.js:88

**Comment by anastenko** [comment]
@jslawler Hello!
Seems like your storage is corrupted. The easiest way to fix this is by reinstalling your browser.
Please do so and let us know the result.

**Comment by jslawler** [comment]
> @jslawler Hello!
> Seems like your storage is corrupted. The easiest way to fix this is by reinstalling your browser.
> Please do so and let us know the result.

All appears to be well after uninstall/reinstall, thanks @anastenko.
Code block result now displays 3.6.6.

Issue marked as resolved.
