### ISSUE TITLE
Twitter promoted posts sneaking through, fixed with disable/enable

### ISSUE THREAD

**Issue by sporkman** [AdguardTeam/AdguardBrowserExtension#1829]
### Issue Details

- **AdGuard version:**
  - AdGuard for Safari Version 1.9.19
- **Browser and version:**
  - Safari 14.1.1
- **Operating system and version:**
  - OS-X 10.14.6
- **Filters you use in AdGuard:**
  - All of the stock filters and no others
- **Stealth Mode settings**
  - : N/A
- **Other browser extensions:**
  -  1Password
 
### Expected Behavior

Promoted Tweets on Twitter are blocked

### Actual Behavior

Promoted Tweets are not blocked UNLESS I visit twitter, deselect "enabled on this website" in the AdGuard browser bar menu, then reselect "enabled on this website". The page reloads on reselecting and at that point promoted tweets are blocked again. If I close the tab and visit again, promoted ads will show until I repeat this process of disable/enable.

### Screenshots

N/A

### Additional Information

I have restarted my mac, restarted safari, and adguard.

**Comment by anastenko** [comment]
Issue moved to [AdguardTeam/AdGuardForSafari #630](https://github.com/AdguardTeam/AdGuardForSafari/issues/630) via [**ZenHub**](https://www.zenhub.com/)
