### ISSUE TITLE
AdGuard URL tracking parameters removing - doesn't work?

### ISSUE THREAD

**Issue by szemley** [AdguardTeam/AdguardBrowserExtension#1830]
Hello.

We know, that AdGuard _„Stealth mode”_ offer an option to remove URL tracking parameters. Also, there is a special filter - "**URL Tracking**" used for removing tracking parameters from URLs, right? So, I would like to ask if situation described below is normall or it's - for example - a bug?

Note: both examples shows Google search and a moment of hovering mouse cursor over a link to the _linux.org_ website. Using such method, Google can tracks not only what User search for, but which links User actually click on, right?

➥ 1) Google search result with AdGuard's _„Stealth mode”_ and "**URL Tracking**" filter enabled:

https://www.google.com/url?q=https://www.linux.org/&sa=U&ved=2ahUKEwigvOqs1cHxAhWH_rsIHYZxBk8QFjARegQIBxAB&usg=AOvVaw0KTzbusmwtTraGcF6iH1JP

➥ 2) Above example - Google search result, but with Privacy Badger addon installed:

https://www.linux.org/

That's why I want to ask about AdGuard's _„Stealth mode”_ and "**URL Tracking**" filter (available here: [»click«](https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_17_TrackParam/filter.txt)). Shouldn't both settings prevent - in this example - Google link tracking via Google search? Or maybe I don't understand something and AdGuard provide protection for different form of URL tracking?

I have no idea if this is a bug - I just want to know, thanks. By the way: AdGuard v3.6.6 was installed from AMO website.

Best regards.

**Comment by anastenko** [comment]
@szemley Hello!
The filter removes tracking parameters from the link before the site or request is loaded, not when a link is on the page. You can read the information on how it works [here](https://adguard.com/en/blog/adguard-url-tracking-filter.html).
In the future we may also do the same removing as Privacy Badger does.
