### ISSUE TITLE
I would like to add a feature that allows undoing manually blocked items

### ISSUE THREAD

**Issue by AbdalrahmanAzab** [AdguardTeam/AdguardBrowserExtension#1833]
**- Browser and version:**
     Google Chrome Stable, AdGuard Browser Extension 3.6.6

**- Operating system and version:**
     Windows 10 Home 21H1

Hello
Sometimes I want to undo an item that I unintentionally blocked and it is difficult for me to do this, so I wish to add a feature to undo deleting items so that manually blocked items appear in a custom list to make it easier for us to undo the deletion of an item
sry for my bad English
Thanks

**Comment by anastenko** [comment]
@AbdalrahmanAzab Hello.
Could you specify the feature you're talking about? 
Do you mean a button which disables all custom rules for a page or a field to disable a rule that was just added?
We have a similar feature request here [#1806](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1806). Does it correlate to what you suggested?

**Comment by anastenko** [comment]
@AbdalrahmanAzab Seem like this issue is a duplicate of [#1806](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1806), so we've closed this one. 
Feel free to re-open it if your feature request is different from the mentioned one.
