### ISSUE TITLE
Auto cleaning of user rules

### ISSUE THREAD

**Issue by mdziczkowski** [AdguardTeam/AdguardBrowserExtension#1835]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:** 3.6.6
- **Type:** Browser extension (addon)
- **Browser:** Firefox 89
- **System:** Linux (64-bit)

- **Other browser extensions:**
  - opt-out plugin
  - webRTC blocker
  - facebook plugin

### Expected Behavior

Possibility to add custom (user) blocking and exception rules with aren't included in the existing filters

### Actual Behavior

When I type the user rules, the input box get cleared out while that after few seconds from entering it

### Screenshots

Unable to take it due to short time between typing and the text beeing cleared out

### Additional Information

None for now

**Comment by anastenko** [comment]
@mdziczkowski Hello.
That's an unusual case. Could you please record a video of the screen while trying to type anything? Also specify what rules you're trying to add?

**Comment by anastenko** [comment]
@mdziczkowski Any news?

**Comment by mdziczkowski** [comment]
[UPDATE]

There is a small clearing up I ned to do... I did some research and had discovered that the rule get cleared up from the field because while typing, the whole text get selected and "refreshed", removing all empty lines. That makes the rules maintanance more difficult.

Example rules I attempt to add :

`## Exception rule
@@*^$stylesheet,font
@@*.*css
@@*style*
@@*css*
@@*font*
@@*captcha*
@@*download*
@@||account*.*
@@||profile*.*
@@||konto*.*
@@||font*.*
@@|jquery*.*
@@||ajax.*
@@*.googleapis.com
## Block rule
||ad.*
||ads.*
||adv.*
||ad*.*
*^/ga.js
||ga.*
||zasobyuwp.pl
||v.wp*.pl
poczta.o2.pl##div.page:nth-child(2) > div.login-area:nth-child(2) > div.responsive-image.responsive-image--1`


Unfortunatelly. I'm unable to record a video because I have only two hands and it's very difficult to efficently type with one, while the second one would hold a phone to record it

**Comment by anastenko** [comment]
@mdziczkowski Now I understood how to reproduce the issue. As you previously said, the whole text is selected once you enter the settings. Try to click a random area of the text field with a mouse and enter any text. 
This "text selection" thing should be fixed with the next extension update.

**Comment by mdziczkowski** [comment]
> @anastenko Try to click a random area of the text field with a mouse and enter any text.

I had already tryed that. It seem that this issue is related to this field only

> This "text selection" thing should be fixed with the next extension update.

Good to know. It would be also good if the textarea (where are the rules typed) won't become "refreshed" while the user types anything into it and the text formating (like empty lines) won't become removed themself (it's annoying and makes more difficult to maintain the rules

**Comment by mdziczkowski** [comment]
UPDATE: I had finally got able to record the video of the issue (capturing the self replace of the rules while paused to type).

[Link to the video](https://streamable.com/k3upxx)

**Comment by XX-J** [comment]
> I'm unable to record a video because I have only two hands and it's very difficult to efficently type with one, while the second one would hold a phone to record it

 Use programs for screen video capturing next time.
________________________________________

 Проблему подтверждаю. При вводе правил действительно зачастую все правила исчезают.

 Давно сам мучаюсь от автосохранения списка правил AdGuard'ом, но всё не доходили руки завести отдельную issu'ю. Частично я комментировал это здесь: https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1410#issuecomment-653644746

 ##### В продолжение моему комментарию выше:

 Я пользуюсь в основном двумя браузерами: Serpent v52.2021.06.05 ( на базе FireFox v52.9) и FireFox v78.10 ESR. В Serpent'e опустошение пользовательского списка правил при загрузке браузера происходит редко, а в 78-ом FireFox'e ОЧЕНЬ часто, приблизительно в 50% случаев (пере)запуска браузера. Он как больной желудочным гриппом - ничего не может в себе удержать.

 Из-за этого приходится делать резервные копии папок кэша AdGuard'a (из папки профиля пользователя браузера). Т.к. если FireFox аварийно закрылся (а у меня это бывает из-за нехватки 4 ГБ ОП во время отключения AdGuard'a для составления своих правил), то скорее всего пользовательский список правил при следующем запуске браузера САМООПУСТОШИТСЯ, а там может быть кучка написанных мною свежих правил, которые ещё не успел перенести в основной список.

 ##### Момент появления бага:

 Вкладка с настройками Adguard'a на странице пользовательских правил у меня всегда закреплена.
 ###### При нормальном поведении AdGuard'a:
 После каждого (пере)запуска браузера, если переключиться на страницу настроек AdGuard'a, я вижу что все правила в списке выделены.
 ###### При возникновении бага с исчезновением всех правил:
  Если, во время запуска браузера, быстро переключиться на вкладку с пользовательскими правилами AdGuard'a, то можно заметить что, как обычно, весь список правил на месте и он весь выделен, но спустя 1-5 сек. он, прямо на глазах, ИСЧЕЗАЕТ, и остаётся 1-2 правила, которые я вводил последними (не важно как, вручную или копированием и вставкой).

 Хочу акцентировать момент на том, что остаются последние введённые 1-2 правила. Так происходит ВСЕГДА при возникновении бага. Именно 1-2 правила и именно последние введённые за предыдущую браузерную сессию - остаются ВСЕГДА. Если за предыдущую браузерную сессию небыло введено ни одного правила и произошёл баг, то список пользовательских правил будет АБСОЛЮТНО пуст.

 #### Моё резюме и желалка:

 Автосохранение текста пользовательских правил работает без учёта специфики полного спектра возможных взаимодействий с ним. Короче - неполноценно, и надо исправить. Как минимум перестать выделять весь список правил после загрузки браузера или сбрасывать это выделение, - может хоть так правила не будут стираться.

 В идеале - сделать опцию отключения автосохранения и производить сохранение принудительным нажатием на кнопку, с отключением возможности (затемнением) вносить изменения в список во время процесса сохранения, - так больше Контроля!

**Comment by anastenko** [comment]
@XX-J Здравствуйте!
Планируется внедрение кнопки "Сохранить", что поможет избавиться от данной проблемы.

**Comment by maximtop** [comment]
We have removed the autosave button, please check if not everything is ok.

**Comment by mdziczkowski** [comment]
> We have removed the autosave button, please check if not everything is ok.

I'll check it when I get my system fully working
