### ISSUE TITLE
Intercept cmd+f/ctrl+f on options page to focus search bar

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1839]
### Problem Description

After changing state of a filter, you need no click on search field for edit search phrase. Too many redundant actions if user want to find many filters, or do it frequently.

### Proposed Solution

Autofocus search input field when page loaded, and return focuse to input field after click on filter(on/off).

### Alternatives Considered

Intercept `Ctrl-F` / `Command-F` hotkey.

**Comment by Alex-302** [comment]
UPD: when user press Ctrl-F, please select whole search request. This will allow to start typing new request without removing previous(like in IDEs).

**Comment by contribucious** [comment]
@Alex-302 … and regarding the `Filtering log` part _(as also included in [the commit](https://github.com/AdguardTeam/AdguardBrowserExtension/commit/76ba98e311778d06a416140d19060ce429cc4a2d))_, like … the general behavior in `AdGuard for Windows` including the filtering log too, I would add. _#consistency_ :heavy_check_mark:

###### Naturally, insofar as this keyboard shortcut will be preserved there for the `AdGuard Browser extension` (even if modified towards `Ctrl+Shift+F` or another one for example). This point being discussed [here](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2155).

**Comment by maximtop** [comment]
@Alex-302 please open the new issue. this one was resolved.
