### ISSUE TITLE
New AdguardSelector interface

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#184]
Here is how it looks like:
layout.vpsvps.ru/adguard-assistant/

Layout attached:
[archive.zip](https://github.com/AdguardTeam/AdguardBrowserExtension/files/158984/archive.zip)

@Mizzick assign a milestone.

**Comment by ameshkov** [comment]
@Mizzick 

Oh, one more **very** important thing.

Currently all images are encoded as **data:** URLs.
This is restricted in AMO, so please extract it to separate files.

Ignore last two frames in layout page - this is for AG Assistant, not for browser extension.

**Comment by Mizzick** [comment]
@ameshkov It would be good to have a separated and not minimized styles and fonts for assistant only.

**Comment by ameshkov** [comment]
Can you extract them from that archive?

**Comment by Mizzick** [comment]
Ok, done. Need to correct some localizations now.

**Comment by ameshkov** [comment]
Here are some very important notes:

1. You should remove jquery and jquery UI usages from that code. As I understand, this is the only place where jquery UI is used, so we will be able to get rid of it in add-on.

2. Upload new strings to oneskyapp

**Comment by Mizzick** [comment]
New strings uploaded to oneskyapp

**Comment by Mizzick** [comment]
Waiting for translations now
