### ISSUE TITLE
Important Memory Usage

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdguardBrowserExtension#1840]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - AG 3.6.6
- **Browser and version:**
  - Firefox 90.0.2
- **Operating system and version:**
  - macOS 11.15
- **Filters you use in AdGuard:**
  - all filters are on. 
- **Stealth Mode settings:**
  - Enabled 
- **Other browser extensions:**
  - 1Password, Evernote, Traffic Light, BD Anti-tracker, Windscribe 

### Expected Behavior

A moderate memory usage. 

### Actual Behavior

 When I start up my MBP with no application opened, the extension already uses between 700MB to 1.2GB. 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

The memory usage remains the same with Firefox opened.

**Comment by anastenko** [comment]
@Quorum75 Hi. Could you try disabling some of the filters and check if the memory usage is reduced?

**Comment by Quorum75** [comment]
No improvement. 

FYI AG Pro 2.5.3.955 installed on my macOS uses less than 200MB with the same configuration and filters.

**Comment by anastenko** [comment]
@Quorum75 Please reinstall the extension and leave only those filters that are needed in usage or try using the default ones.

**Comment by Quorum75** [comment]
Did you receive my log? 
Are you saying it's the number of filters that is responsible?
If so, why is there no issue with macOS?

**Comment by anastenko** [comment]
@Quorum75 In addition to the extension, there are content blockers in macOS. Also mac limits the number of rules used in one content blocker to 50,000.
Didn't receive the logs.

**Comment by Quorum75** [comment]
The 50K rules you are referring to are for Safari so why mentioning macOS?

Also, here the problem is on Firefox.

**Comment by anastenko** [comment]
@Quorum75 Sorry, I was referring to Safari extension.
If I understood you correctly you turned on all the filters, so obviously it eats lots of memory. So we recommend using specifically those you need. 
As for the other AdGuard products (you mentioned AG for macOS), they all are different, you can't expect the same behavior from them.

**Comment by Quorum75** [comment]
I think there is a misunderstanding here. 

If you read again my initial message I am referring to a problem with AG Extension in Firefox not Safari - there is no filter to setup in Safari extension. 

Also, I unchecked all filters (Firefox extension) and I am still at 600MB consumption. 
Is this memory usage normal?

**Comment by anastenko** [comment]
@Quorum75 Could you please give us more details on how to reproduce it step by step?

**Comment by Quorum75** [comment]
My bad, I went too fast and I forgot to uncheck the Custom Filters.
<img width="718" alt="AG Custom Filter" src="https://user-images.githubusercontent.com/49731083/128217149-15f30506-41ce-43bc-a616-4196f0d11e0b.png">
For this reason I have a huge memory usage, even more than macOS AG although both have the same configuration and filters.
![AG Memory](https://user-images.githubusercontent.com/49731083/128217362-ac7c6e7f-46d4-4ba4-b1b1-c3c6b6466d23.jpg)

**Comment by anastenko** [comment]
@Quorum75 Makes sense. 
As I previously mentioned, memory usage can be different for different AdGuard products, even though you might use the same filters and configuration.

**Comment by Quorum75** [comment]
Yes. Sonow  I am doubtful about the need to use AG FF extension with macOS AG apart of killing my 16Gb RAM.

**Comment by anastenko** [comment]
@Quorum75 Using only the desktop version seems right, since it has more coverage.

**Comment by Quorum75** [comment]
I reported the bug to Mozilla and I am in conversation with he dev about this problem. 

https://bugzilla.mozilla.org/show_bug.cgi?id=1722041

**Comment by Quorum75** [comment]
Follow up: https://bugzilla.mozilla.org/show_bug.cgi?id=1722041

"Looking at the memory report, the web extension "AdGuard AdBlocker" is using around 2.2GB of memory. We can move it to the web extensions component, though I'd guess that it is more likely that there is an issue with the extension itself that should be reported to the extension developer.

As a workaround, the original reporter could try a different ad blocker, like uBlock Origin."

**Comment by Birbber** [comment]
We no longer support integration of AG desktop application and AG browser extension, so there's no need in using both of them. You can leave just the desktop application.
