### ISSUE TITLE
FF AG is always disabled when opening new tab.

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdguardBrowserExtension#1842]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  -  FF AG Extension Version 3.6.6
- **Browser and version:**
  -  FF 92.0a1 (2021-08-06)
- **Operating system and version:**
  -  macOS 11.5.1 (20G80)
- **Filters you use in AdGuard:**
  -  All default filters
- **Stealth Mode settings:**
  -  Enabled
- **Other browser extensions:**
  -  1Password, Evernote, Trraffic Light, Windscribe, Auto Tab discard.

### Expected Behavior

 At each opening of a new tab AG should be enabled

### Actual Behavior

 Every time you open a new tab, AG is disabled and must be manually enable.

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

 This issue did not happen before and I don't know if any update (AG or FF) is responsible for it. Also, the same problem occurs with FF 90.0.2. 
However no problem with Safari.

**Comment by anastenko** [comment]
@Quorum75 Hello!
Maybe your whitelist is inverted, please check it. Also some custom filters might affect it.

**Comment by Quorum75** [comment]
Nope I didn't. I tried everything and I couldn't find the origin of the problem. 
Then, I just uninstall d FF and now everything works fine, oh well!

I read somewhere that it was better to get both AG.
However Andrey told me it's was not necessary to get the extension because I already have AG desktop. So guess what? I just get rid of it. No more risk to face the problem again and better for FF memory.
