### ISSUE TITLE
Remove referrer from the `document.referrer`

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1844]
### Issue Details

- **AdGuard version:** 4.0
- **Browser and version:** Chrome 92.0.4515.131
- **Operating system and version:** Windows 10
- **Filters you use in AdGuard:** Base, Spyware, URL tracking
- **Stealth Mode settings:** All

### Expected Behavior

Source must be hidden from the site. For example, search for `sbjs.rocks` in Google and go to this result.

### Actual Behavior

Source is detected by the site.
![image](https://user-images.githubusercontent.com/8361299/129216152-4cf7d785-875e-47a1-af9e-f8fabb05b87b.png)
Same in MS Edge and Firefox. This issue is not reproduced with AdGuard for Windows.

It seems this issue is related to `document.referrer`.
When added `sbjs.rocks#%#//scriptlet("set-constant", "document.referrer", "undefined")` source is not detected.
![image](https://user-images.githubusercontent.com/8361299/129216389-a4f04a1c-19ac-496b-9207-ca4835d42bd3.png)

**Comment by Aydinv13** [comment]
I can't confirm the issue because I have the source hidden from the site on different browsers (Chrome, Edge, FF)

**Comment by Aydinv13** [comment]
If it's opened from the search system like Google, source is detected by the site

**Comment by mahdiameri** [comment]
Thanks. So right

**Comment by maximtop** [comment]
It's a standard browser feature that doesn't depend on the headers. We can prevent the sharing of the referrer by setting a constant value for `document.referrer` via a rule, or via a content script. According to the reactions collected here, it doesn't seem that this issue is very popular.
