### ISSUE TITLE
Assistant iframe styles are affected by cosmetic rules specific for websites

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1848]
@adguard-bot commented on [Mon Aug 30 2021](https://github.com/AdguardTeam/AdguardFilters/issues/92978)

### Issue URL (Incorrect Blocking)
 [https://www.tv2.no/a/6805835/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.tv2.no%2Fa%2F6805835%2F)
### Comment
> When trying to block an element with Nordic Filters turned on, the buttons at the bottom of the AdGuard popup are missing ("Select a different element", "Preview", "Block"). When Nordic Filters (under "Language-specific") are turned off, the buttons appear. Possible conflict between Nordic Filters and element blocking?

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/pBtGJ9O.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/8FRqmEj.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.6.6
Browser: | Chrome
Stealth mode: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Language-specific:</b><br/>Dandelion Sprout's Nordic Filters
Other extensions used: | nothing relevant

---

@DandelionSprout commented on [Mon Aug 30 2021](https://github.com/AdguardTeam/AdguardFilters/issues/92978#issuecomment-907945872)

I seem to have found the problem: AdGuard's element picker is using `html` and `body` elements for seemingly no valid reason, which causes `www.tv2.no#$#body:not(.broom, .lab) { padding-top: 70px !important }` to take effect for it.

This seems like a pretty severe bug in AdGuard Browser Extension, and it's a 50:50 chance if I can even make a good temporary fix for it.

---

@DandelionSprout commented on [Mon Aug 30 2021](https://github.com/AdguardTeam/AdguardFilters/issues/92978#issuecomment-907949066)

I've now added a tempfix for this in https://github.com/DandelionSprout/adfilt/commit/996d2e36ed0c0d1871f37545771c7fa4d0b30e37, but it is by no means a good idea in the long run.

**Comment by matso167** [comment]
I don't have Nordic Filters enabled, but the element picker popup doesn't show at all on website https://ylilauta.org/
