### ISSUE TITLE
Remove EULA link from AdGuard Browser extension

### ISSUE THREAD

**Issue by anedroid** [AdguardTeam/AdguardBrowserExtension#1849]
Nie jestem pewien co do licencji tego rozszerzenia. W repozytorium GitHub, oraz na stronie [addons.mozilla.org](https://addons.mozilla.org/en-US/firefox/addon/adguard-adblocker) jest napisane, że jest licencjonowane pod LGPLv3. Z kolei sekcja "o rozszerzeniu" zawiera link do [umowy licencyjnej](https://adguard.com/pl/eula.html), która jest wyraźnie sprzeczna z licencją LGPLv3. Dokument nie mówi wyraźnie, którego oprogramowania dokładnie dotyczy: czy tylko natywnych aplikacji na Windows, MacOS i Android, czy także rozszerzenia do przeglądarki.

Pisałem w tej sprawie do FSF. Powiedzieli, że może być tak, że jedno oprogramowanie jest wydawane na wielu licencjach jednocześnie. Sądzę, że w rozszerzeniu znajduje się błąd - link do EULA wstawiony przez pomyłkę, ale napis "wszelkie prawa zastrzeżone" sugeruje, że jest to niewolne oprogramowanie. Błąd może także znajdować się w opisie rozszerzenia na stronie addons.mozilla.org. Proszę doprecyzujcie to.

**English version below, translated by myself**. Sorry for any mistakes.

I am not sure about license of this extension. In the GitHub repository, and on [addons.mozilla.org](https://addons.mozilla.org/en-US/firefox/addon/adguard-adblocker) it's written, that it's licensed under LGPLv3. But "about this extension" section contains link to [EULA](https://adguard.com/pl/eula.html), which is clearly opposite to LGPLv3 license. The document doesn't tell clearly, which software is it about: just to native applications on Windows, MacOS and Android, or to the browser extension too.

I've written in this issue to FSF. They told me it might be that software is released under multiple licenses. I suppose there's a mistake in extension itself - link to EULA inserted by mistake, but text above "all right reserved" suggest, that's proprietary software. Mistake can be instead in the extension's description at addons.mozilla.org. Please, deprecise this.

**Comment by anedroid** [comment]
Sorry, but I still don't know is Adguard browser extension free or proprietary.

**Comment by anastenko** [comment]
@anedroid AdGuard Browser Extension is free to use.

**Comment by anedroid** [comment]
You mean only using, like having it's installed in my browser, or too studying the source code, modifying the extension, and sharing it with, or without changes? I am the GNU/Linux user, so I need to know it.

**Comment by anastenko** [comment]
Yes, you can. It's an open source product.
Sorry if that wasn't clear from my previous messages.

**Comment by maximtop** [comment]
We will remove the link to EULA from the browser extension
