### ISSUE TITLE
AdguardSelectorLib not working properly in Safari iPad/iOS

### ISSUE THREAD

**Issue by Stillness-2** [AdguardTeam/AdguardBrowserExtension#185]
When we try to adapt AdguardSelectorLib to work in Action Extension, occur a  problems. On some sites the selector does not select anything or leads to freeze Safari.

It is necessary to achieve stable work on iPhone, iPad (or on appropriate simulators), at the following sites: yandex.ru, nnm-club.me, lenta.ru, meduza.io, yahoo.com. 

To build the project, use the branch `feature/issues/35`:
https://github.com/AdguardTeam/AdguardForiOS/tree/feature/issues/35

**Comment by Mizzick** [comment]
https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/HandlingEvents/HandlingEvents.html

**Comment by Stillness-2** [comment]
The function for element selection must be called on first tap on a screen.

**Comment by Stillness-2** [comment]
Can't implement custom renderer of selection, because no api for removing of the custom drawing.
