### ISSUE TITLE
mcpedl still has video count down after ad being blocked

### ISSUE THREAD

**Issue by Wendys-corp** [AdguardTeam/AdguardBrowserExtension#1850]
im using windows 10 everything up to date on chrome
![image](https://user-images.githubusercontent.com/73713314/132078241-24ad0682-9934-42e7-82d9-67a0ddf2406f.png)
link is here
https://mcpedl.com/realms-safe-plus/
can be triggered by clicking on one of the downloads
video ad is blocked
website without ANY adblockers enabled
![image](https://user-images.githubusercontent.com/73713314/132078289-7be2af68-c817-48d0-9f4c-c4251c082ca2.png)

**Comment by Wendys-corp** [comment]
pls add this website to the bypass api

**Comment by slavaleleka** [comment]
enable AdGuard Annoyances filter please
