### ISSUE TITLE
Support `$removeheader`

### ISSUE THREAD

**Issue by piquark6046** [AdguardTeam/AdguardBrowserExtension#1851]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Problem Description
According to  [AdGuard's knowledgeBase](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#removeheader), `$removeheader` modifier can remove a header in HTTP request/response header. 
According to [this Issue](https://github.com/AdguardTeam/CoreLibs/issues/1427), `$removeheader` modifier can be used on AdGuard for Windows, AdGuard for Android, etc.

### Proposed Solution

Please support `$removeheader` modifier on AdGuard Browser Extension using `webRequest` method, etc.

### Alternatives Considered

Nothing.

### Additional Information

https://github.com/AdguardTeam/CoreLibs/issues/1427
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest

**Comment by anastenko** [comment]
@piquark6046 Hello.
`$removeheader` support will we added in v4.0.
