### ISSUE TITLE
Filter doesn't work when writing rules on the same line and separated by comma

### ISSUE THREAD

**Issue by tumatanquang** [AdguardTeam/AdguardBrowserExtension#1852]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [✔️] I am running the latest version
- [✔️] I checked the documentation and found no answer
- [✔️] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:** v3.6.12
- **Browser and version:** Chrome 93
- **Operating system and version:** Windows 7
- **Filters you use in AdGuard:** Own filter
- **Other browser extensions:** IDM Integration Module

### Expected Behavior
Rules written on the same line, separated by commas will work.
### Actual Behavior
When writing all filter rules on the same line, separated by commas, the filter rule will not work. But after separating the rules they should work.
### Additional Information
I wrote an ad blocking filter on [9gag.com](https://9gag.com), here is the original filter rule I wrote:
```
9gag.com##.inline-ad-container,section.block-ad,section.salt-container,#sidebar-stream-0 > h4:first-child,#stream-0 > article:last-child
```
Then refresh the page, no rules apply!
Then I split into:
```
9gag.com##.inline-ad-container,section.block-ad,section.salt-container
9gag.com###sidebar-stream-0 > h4:first-child
9gag.com###stream-0 > article:last-child
```
The filter works again, the elements that match the filter's rules are hidden.

**Comment by Birbber** [comment]
@tumatanquang Hello.
This will be fixed in version 4.0.
