### ISSUE TITLE
Blocks quora.com answers

### ISSUE THREAD

**Issue by kiyokodyele** [AdguardTeam/AdguardBrowserExtension#1853]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [YES] I am running the latest version
- [YES] I checked the documentation and found no answer
- [YES] I checked to make sure that this issue has not already been filed

### Issue Details

When you go to Quora Q&A page, answers are not showing, doing so in other browser without the ad-block seems to work. Also disabling the extension fixes the problem.

- **AdGuard version:**
3.6.12
- **Browser and version:**
Microsoft Edge Version 92.0.902.84 (Official build) (64-bit)
- **Operating system and version:**
Microsoft Windows 10 Version 20H2, Build 19042.1165
- **Filters you use in AdGuard:**
Nothing, all set to default as installed
- **Stealth Mode settings:**
Nope
- **Other browser extensions:**
Cookie Editor and Postman Extension

### Expected Behavior

Get answers pane / results from Quora Q & A page

### Actual Behavior

No answers shown

### Screenshots

![image](https://user-images.githubusercontent.com/45057955/132596908-f3905cfb-d540-48a8-865f-514568dc1083.png)

### Additional Information

This might probably because ad-block thinks that the answer pane are ads or quora is putting ads on the answer panes.

**Comment by anastenko** [comment]
@kiyokodyele Hi.
Doesn't look like AdGuard issue. Maybe [Quora's answer collapse policy](https://help.quora.com/hc/en-us/articles/360000470346)?
Also "Cookie Editor" extension sounds suspicious. Could you turn it off and check again?

**Comment by kiyokodyele** [comment]
> @kiyokodyele Hi.
> Doesn't look like AdGuard issue. Maybe [Quora's answer collapse policy](https://help.quora.com/hc/en-us/articles/360000470346)?
> Also "Cookie Editor" extension sounds suspicious. Could you turn it off and check again?

I read the Quora's answer collapse policy, nothing appears to be related about ads
I also disabled Cookie Editor, same result

It appears that adguard is blocking 2 ads in Quoara's Q&A page.

**Comment by kiyokodyele** [comment]
I'm gonna close this issue now. Somehow, just now, I revisited the site now it works properly. Weird.

**Comment by Birbber** [comment]
@kiyokodyele Sure. Reopen it if the issue occurs again.
