### ISSUE TITLE
Dark interface for the extension

### ISSUE THREAD

**Issue by NguyenASang** [AdguardTeam/AdguardBrowserExtension#1856]
### Problem Description

Sometime when I open the extension page to choose filter or change some setting, but the page is too bright, it burns my eyes (especially at night) :(

### Proposed Solution

Can you add dark mode for this extension ? If you can, it will be very good XD

### System Information

Operating System: Window 11 64 bit
Browser: Edge version 93.0.961.47 (64 bit)
Extension version: 3.6.12

**Comment by ameshkov** [comment]
Yep, it will be added in v4.0 (expect it to be available in beta really soon).
