### ISSUE TITLE
Add two options to disable javascript and font

### ISSUE THREAD

**Issue by HamidRezaAshkiyan** [AdguardTeam/AdguardBrowserExtension#1858]
If you look at ublock origin there is to feature that needed to be in AdGuard. First Option to disable JavaScript and disable font.

And if you can customize witch JS script to block just like ublock it would be great.

There should be two options to disable JS and font globally or just for current site.

**Comment by Birbber** [comment]
@HamidRezaAshkiyan Hi!
We will think about implementing this feature for future updates.
As a temporary solution try:
```
||example.com^$csp=script-src
$font,third-party,domain=example.com
```
The first rules should disable all scripts for a particular webpage, and the second one - disables third-party fonts

**Comment by HamidRezaAshkiyan** [comment]
Thank you, 
is there any specific release date and features for v4?

**Comment by Birbber** [comment]
There's no ETA unfortunately, but we hope the next version will come out soon enough.

**Comment by Birbber** [comment]
I'm closing this issue, since it will be merged with [a bigger one](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1859).
