### ISSUE TITLE
 This extension is slowing down Google Chrome. 

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardBrowserExtension#1863]
**Issue URL** : chrome://extensions/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/133782714-331b65bf-1acb-420b-8441-3fc4e6c14914.png)
![image](https://user-images.githubusercontent.com/76880977/133782713-3d59bef3-12ae-48b3-8ece-a5b88e00a3ca.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Birbber** [comment]
@chirag127 Hi!
This message can be seen after a long usage of the extension while filtering log or settings being open (because it consumes more memory). 
There's nothing wrong about this message.
