### ISSUE TITLE
“run-at” option for Javascript user rules

### ISSUE THREAD

**Issue by vsl7** [AdguardTeam/AdguardBrowserExtension#1864]
I suggest to introduce a “run-at” modifier for Javascript user rules so as to execute them at _document-start_ or at _document-end_.

https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#javascript-rules

**Comment by maximtop** [comment]
If you are talking about AdGuard AdBlocker Extension, then we already try to inject all necessary scripts as soon as possible.

https://github.com/AdguardTeam/AdguardBrowserExtension/blob/5f875daf02e762ce20661b59468291bc523864bc/Extension/browser/chrome/manifest.json#L29

If you have some use case, which is not working as expected, describe it bellow.

**Comment by maximtop** [comment]
Script rules from user rules are injected as soon as possible too. But sometimes inline script are injected faster. 
Here I've create an sample page with different scripts, so you can see when we inject script rules https://maximtop.github.io/misc-tests/test-inject-order/.

As you can see script rules are executed before inline scripts

![image](https://user-images.githubusercontent.com/17272769/134305109-9960035a-c712-4971-afc8-6e33ae760063.png)

**Comment by vsl7** [comment]
That’s right, and I am closing the issue.
