### ISSUE TITLE
Mobile view for Kiwi Browser (Android)

### ISSUE THREAD

**Issue by depler** [AdguardTeam/AdguardBrowserExtension#1866]
This browser support chrome extensions: https://play.google.com/store/apps/details?id=com.kiwibrowser.browser

AdGuard works fine, but there is web page scaling problem (since extension supposed to run on desktop only):

![IMG_20210921_205851](https://user-images.githubusercontent.com/13541699/134223175-9aa8f12f-d37a-47c1-baf1-88874c6c36ff.jpg)

Can you please add mobile view support?

**Comment by krystian3w** [comment]
Similar is sometime in Firefox Fenix, maybe addon 4.0.0 should have layout with RWD in 2021.

**Comment by Birbber** [comment]
@depler Hi!
We're planning to release v4.0 soon enough. Looks like this issue has already been fixed in that version.
Please wait until its release and let us know the result.
