### ISSUE TITLE
User-Agent String Reduction 

### ISSUE THREAD

**Issue by isKhalil** [AdguardTeam/AdguardBrowserExtension#1867]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
AdGuard Version 3.6.12
- **Browser and version:**
 Chrome Version 93.0.4577.82 (Build officiel) (64 bits)
- **Operating system and version:**
   Windows 7 (64 bits)
- **Filters you use in AdGuard:**
Not Filtering
- **Stealth Mode settings:**
Disabled
- **Other browser extensions:**
IDM Integration Module

### Screenshots
![AdG-Iss](https://user-images.githubusercontent.com/91100106/134761611-e88a2a73-5488-401f-b161-e1ded780c041.png)

**Comment by stanislav-atr** [comment]
@isKhalil, hi! This will be implemented in next release update as a part of [this](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1871) issue.
