### ISSUE TITLE
Replace the usage of navigator.(userAgent|appVersion|platform) with navigator.userAgentData

### ISSUE THREAD

**Issue by Z-byte-prog** [AdguardTeam/AdguardBrowserExtension#1868]
### Problem Description

A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. In a future version of Chrome, the amount of information available in the User Agent string will be reduced.

### Proposed Solution

To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.

### Alternatives Considered

Note that for performance reasons, only the first access to one of the properties is shown.

### Additional Information

chrome-extension://pegbcdkgejkhafedjabljgfjkmknghab/adguard/adguard-content.js
https://blog.chromium.org/2021/05/update-on-user-agent-string-reduction.html

i am not quiet sure how to fix this. Help anyone?

**Comment by maximtop** [comment]
Thank you for reporting this issue. We are going to fix it in the near future.
