### ISSUE TITLE
Selector border position is wrong: below the actually selected element

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#187]
Steps to reproduce:
1. Open this page:
http://www.msn.com/en-us/news/politics/cnn-donald-trump-broke-the-rules-of-fox-news-gop-debate/ar-BBqnNHL#image=1
2. Try to block something on that page
3. You'll see that green border is below selected element

**Comment by Mizzick** [comment]
https://www.dropbox.com/s/ndhe4fj2atprppx/Screenshot%202016-04-06%2020.50.33.png?dl=0

**Comment by Mizzick** [comment]
Fixed
