### ISSUE TITLE
Adguard Firefox Extension may cause Gesturefy  not working properly

### ISSUE THREAD

**Issue by scriptxyz** [AdguardTeam/AdguardBrowserExtension#1873]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [yes ] I am running the latest version 
- [ yes] I checked the documentation and found no answer
- [yes ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:** 
 Adguard windows 7.6.1/browser assistant 1.1.16/AdGuard AdBlocker 3.6.13
- **Browser and version:**
Firefox 93
- **Operating system and version:**
Windows 11
- **Filters you use in AdGuard:**
-  base filter, easylist, tracking proection filter, social media filter, chinese filter
- **Stealth Mode settings:**
NA
- **Other browser extensions:**
NA

### Expected Behavior

Gesturefy  can work well. (use mouse to close tabs)

### Actual Behavior

On some websites, Gesturefy is working. But on some websites, Gesturefy  is not working (can't use mouse to close tabs).

After disable adblock browser extension, Gesturefy   is working again.

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by Birbber** [comment]
@scriptxyz Any news?
