### ISSUE TITLE
Disable Adblocker issue

### ISSUE THREAD

**Issue by Mile-Hi-Dave** [AdguardTeam/AdguardBrowserExtension#1882]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 
- **Browser and version:**
  - 
- **Operating system and version:**
  - 
- **Filters you use in AdGuard:**
  - 
- **Stealth Mode settings:**
  - 
- **Other browser extensions:**
  - 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

When going to a page on thehill.com a big ole box ad/popup appears asking you to turn off the adblocker.  it's worse than just going ahead and disabling Adguard on the site and dealing with the ads.  Don't know how to do a screenshot on this Surface, but the attached "print screen" shows the issue.
[The Hill.pdf](https://github.com/AdguardTeam/AdguardBrowserExtension/files/7413780/The.Hill.pdf)
.

**Comment by Birbber** [comment]
@Mile-Hi-Dave Any news?

**Comment by Birbber** [comment]
I'm closing this issue due to no response. Please reopen it if needed.
