### ISSUE TITLE
Videos embedded from janjua.tv

### ISSUE THREAD

**Issue by syco** [AdguardTeam/AdguardBrowserExtension#1883]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 3.6.13 on Firefox 78.15.0esr (64-bit)
- **AdGuard version:**
  - 3.6.14 on Chrome 95.0.4638.69
- **Operating system and version:**
  - Debian 11
- **Filters you use in AdGuard:**
  - All available filters
- **Stealth Mode settings:**
  - Enabled
- **Other browser extensions:**
  - bitwarden

### Expected Behavior

Video play

### Actual Behavior

Video on this website (https://www.livehere.one/italia-1-diretta/), embedded from janjua.tv, doesn't play in firefox, the player never starts, but plays fine in chrome.

Please let me know if I can provide anything else.
Thanks

**Comment by Birbber** [comment]
@syco Hi! 
The video won't load even without AdGuard. I tried to reproduce the issue on firefox version 94.0.1 (64-bit) and firefox version 79.0(64-bit) playing the video via the link and opening different videos on the website. Will try on Debian vm. Maybe you can share other examples or send us the video of reproducing the issue?

You mentioned you use all available filters in AdGuard. We don't recommend turning them all on. Choose only those filters that meet your needs.

Also send us your settings and let us know what Stealth Mode settings you use.

**Comment by syco** [comment]
Hi,

you prompted me to download the 2 json configurations and compare them.

I noticed that the top level general/filters/stealth mode were all the same, but in the sub menus there were some differences,
For example, on firefox I had several language filters selected, and on chrome only easylist italy.
Once I disabled the extra filters enabled on firefox and not on chrome it started working.
Strange, since I don't configure the plugin manually, I always import the same settings I exported months ago.

Anyway, I reconfigured them so they are the same to the last entry, and now it works.

Here's attached the configuration I'm using for reference.
```json
{
  "protocol-version": "1.0",
  "general-settings": {
    "app-language": "en-US",
    "allow-acceptable-ads": true,
    "show-blocked-ads-count": true,
    "autodetect-filters": true,
    "safebrowsing-enabled": true,
    "filters-update-period": -1
  },
  "extension-specific-settings": {
    "use-optimized-filters": false,
    "collect-hits-count": false,
    "show-context-menu": true,
    "show-info-about-adguard": false,
    "show-app-updated-info": true
  },
  "filters": {
    "enabled-groups": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      0
    ],
    "enabled-filters": [
      208,
      10,
      14,
      17,
      2,
      3,
      4,
      109,
      118,
      122,
      123,
      201,
      210,
      11,
      101,
      207,
      215,
      242,
      204,
      225,
      239
    ],
    "custom-filters": [],
    "user-filter": {
      "rules": "",
      "disabled-rules": ""
    },
    "whitelist": {
      "inverted": false,
      "domains": [],
      "inverted-domains": []
    }
  }
}
```
A question on these settings.
The groups and filters are all numeric, is it possible that uploading an old configuration created with a previous version of adguard, enables different things?

Thanks

**Comment by Birbber** [comment]
@syco Importing settings of the previous version shouldn't make such problem.
As I can see you have "autodetect-filters" option enabled. It means when you enter a webpage with a different language it will automatically enable a relevant language-specific filter. So maybe that's how it happened.

**Comment by syco** [comment]
That was most likely it.
But thanks for looking into it, it's frustrating when things work in a browser and not in the other, but it was my fault..
