### ISSUE TITLE
Having issues on the following website..

### ISSUE THREAD

**Issue by fisforfaheem** [AdguardTeam/AdguardBrowserExtension#1885]
torrentgalaxy and watchcartoononline.io  Please fix issues.... torrent galaxy is redirecting upon click anywhere...and the later had weird video playback issues please se

**Comment by Birbber** [comment]
Issue moved to [AdguardTeam/AdguardFilters #100175](https://github.com/AdguardTeam/AdguardFilters/issues/100175) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Yuki2718** [comment]
> torrentgalaxy and watchcartoononline.io

torrentgalaxy should have fixed in https://github.com/AdguardTeam/AdguardFilters/issues/99901 `watchcartoononline.io` redirecte me to `www.wcostream.com` and I see no playback issue.
@Alex-302 @BlazDT @zloyden @Sergey-Lyapin @stanislav-atr Pls take a look.

**Comment by fisforfaheem** [comment]
https://bleaborahm.one/N3NmWHFWEQss i am being redirected to this
