### ISSUE TITLE
new link bypass needed or social filter

### ISSUE THREAD

**Issue by Wendys-corp** [AdguardTeam/AdguardBrowserExtension#1886]
im using chrome 
everything auto updates
it does not link bypass

https://social-unlock.com/5ZHmn

**Comment by Birbber** [comment]
@Wendys-corp Hi! Sorry for the late reply. Could you add more details on your request? Is something not working on this webpage or should it be blocked?

**Comment by krystian3w** [comment]
It ask to add auto-click (or other workaround like use `set-constant`) in 4 social buttons used as social wall.

So you can move this by "zenhub" into "AdGuardFilters". Maybe filter  writer found safest solution.

**Comment by Birbber** [comment]
Issue moved to [AdguardTeam/AdguardFilters #101264](https://github.com/AdguardTeam/AdguardFilters/issues/101264) via [**ZenHub**](https://www.zenhub.com/)
