### ISSUE TITLE
Causss video lay seconds in changing full screen

### ISSUE THREAD

**Issue by V0idk** [AdguardTeam/AdguardBrowserExtension#1889]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 
- **Browser and version:**
  - 
- **Operating system and version:**
  - 
- **Filters you use in AdGuard:**
  - 
- **Stealth Mode settings:**
  - 
- **Other browser extensions:**
  - 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by Birbber** [comment]
@V0idk Hello! Could you specify which webpage you see it on? Does it depend on the player you use?
What AdGuard version do you use?

**Comment by Birbber** [comment]
@V0idk Any news?

**Comment by Birbber** [comment]
I'm closing the issue due to no response. Please re-open if needed.
