### ISSUE TITLE
Change the "Phishing and malware protection" description

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#1891]
Currently, the text there is:
![image](https://user-images.githubusercontent.com/5947035/142840295-a7523171-61bd-4660-8e31-fc0b720bbf19.png)

We need to emphasize, that the check is done using a web service so that the user understood the privacy implications:
![image](https://user-images.githubusercontent.com/5947035/142840625-59bce840-791e-4204-ad42-35e703451bea.png)

Text:
`Check if the domain is dangerous using a special web service`

cc @nataMai

**Comment by nataMai** [comment]
@ameshkov  Будь добр, направь меня в нужный файл, чтобы я там поправила.

**Comment by nataMai** [comment]
I updated this text in Crowdin.
