### ISSUE TITLE
Dots in the end of settings descriptions

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#1892]
Currently, half of descriptions does not have dots in the end, and the other half does:
https://uploads.adguard.com/up04_AdGuard_Settings__9qn6l.png

We need to make it consistent.

@nataMai should we use dots or not?

**Comment by nataMai** [comment]
@ameshkov I suggest using dots in such cases.

**Comment by nataMai** [comment]
In label descriptions, we should not use a dot at the very end.

**Comment by nataMai** [comment]
I updated the strings in Crowdin.

**Comment by gork7777** [comment]
Does this issue persist? I found some issues too. Here:
https://imgur.com/a/B8gWal0
https://imgur.com/a/wv719MT
https://imgur.com/a/ybS1fGd
https://imgur.com/a/S9ETKEt
