### ISSUE TITLE
Injects the box-sizing CSS rule with the wildcard selector on MS Edge

### ISSUE THREAD

**Issue by YNWA** [AdguardTeam/AdguardBrowserExtension#1893]
### Issue Details

- **AdGuard version:**
  - AdGuard v3.2.1
- **Browser and version:**
  - Microsoft Edge Version 95.0.1020.53 (Official build) (64-bit)
- **Operating system and version:**
  - Ubuntu 18.04.4 LTS
- **Filters you use in AdGuard:**
  - Base filter, Russian filter, Filter unblocking search ads and self-promotion 
- **Stealth Mode settings:**
  - Stealth Mode is disabled
- **Other browser extensions:**
  - no other extensions

### Expected Behavior

Expect the user agent to not have injected styles

```
* {
    box-sizing: border-box;
}
```

### Actual Behavior

After adding the AdGuard extension on a fresh MS Edge installation we found injected stylesheet that breaks website layouts.

### Screenshots

<details><summary>Screenshot:</summary>

![Screenshot from 2021-11-22 16-48-24](https://user-images.githubusercontent.com/2243240/142873909-8991cc27-50f4-4387-b142-4ef0627c6446.png)

</details>

**Comment by igordanilovski** [comment]
Exactly same issue happens to me with injecting the box-sizing. When disabling the extension everything backs to normal.

**Microsoft Edge Version**: 96.0.1054.29
**Windows Version**: 11
**Extension Version**: 3.6.15

![image](https://user-images.githubusercontent.com/39922564/142875858-19169a22-d03c-42de-abf6-be24f8fcc895.png)

**Comment by ameshkov** [comment]
Tbh, this looks like an Edge bug, we're trying to figure out what exactly is triggering it.

**Comment by ameshkov** [comment]
Okay, nvm, this is our bug.

**Comment by ameshkov** [comment]
The updated version is on review in Edge Addons store.

**Comment by ameshkov** [comment]
The updated version finally passed the review and is available on the Edge add-ons store.
