### ISSUE TITLE
Increasing the contrast the "X" button on the dark theme

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdguardBrowserExtension#1897]
<img width="668" alt="Screen Shot 2021-11-22 at 18 47 53" src="https://user-images.githubusercontent.com/62497891/142920093-288b118a-5c12-486a-b9d8-c58f655f8af9.png">

**Comment by maximtop** [comment]
Issue moved to [AdguardTeam/AdguardAssistant #363](https://github.com/AdguardTeam/AdguardAssistant/issues/363) via [**ZenHub**](https://www.zenhub.com/)
