### ISSUE TITLE
Improvement of the statistics graph

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdguardBrowserExtension#1898]
AdGuard v.4.0.64
Browser Firefox v.96.0a1 (2021-11-22) (64-bit)
Operating system: macOS v.12.0.1 (21A559)

The graph of statistics should not be the same vertically at different values.

Screenshots:

https://user-images.githubusercontent.com/62497891/142921167-b58495d9-4f60-4600-8344-426ce8e4307f.mov

**Comment by Oleg-Chashko** [comment]
Move the graph line to the foreground.

<img width="315" alt="143033116-85446096-50ef-474c-80b7-7f0573dea68a copy 2" src="https://user-images.githubusercontent.com/62497891/143052390-c7ead8e7-eefb-4ba2-8275-bb0b92eb3b8d.png">

**Comment by Oleg-Chashko** [comment]
It's hard to see how these two icons are connected.
<img width="442" alt="115235300-54459500-a11a-11eb-8036-81d260862a2f" src="https://user-images.githubusercontent.com/62497891/143055974-5ed98bfd-4ad6-404a-9301-7a1411934120.png">

Example:
Align left and move the icon to the left.
<img width="442" alt="115235679-bdc5a380-a11a-11eb-9946-7b6fefe16139" src="https://user-images.githubusercontent.com/62497891/143056259-ac22440a-0c22-4003-b12a-200ee7f4e686.png">

Example:
<img width="442" alt="115235823-e8aff780-a11a-11eb-8842-c839ab0f9eb5" src="https://user-images.githubusercontent.com/62497891/143056439-defb24ff-2105-48dc-b4a5-94a89d3257e3.png">

Example:

<img width="315" alt="143033116-85446096-50ef-474c-80b7-7f0573dea68a copy" src="https://user-images.githubusercontent.com/62497891/143056532-8e9b4b82-7d18-4a6e-804d-7cc81bc685c4.png">

**Comment by maximtop** [comment]
> AdGuard v.4.0.64 Browser Firefox v.96.0a1 (2021-11-22) (64-bit) Operating system: macOS v.12.0.1 (21A559)
> 
> The graph of statistics should not be the same vertically at different values.
> 
> Screenshots:
> 
>  Screen.Recording.2021-11-22.at.19.52.39.mov

The graph displays values relative to the highest value of the selected ad type. If we take the highest number of all blocked ads, then some groups could have so low a value that their graph would be on the y axis.

**Comment by Oleg-Chashko** [comment]
It might be better to make one chart with 5 graphs of different colors.

Example:

<img width="610" alt="Screen Shot 2021-12-08 at 15 16 51" src="https://user-images.githubusercontent.com/62497891/145224012-0e57cf86-ccb6-41f0-8023-121981ca019a.png">

**Comment by maximtop** [comment]
> It might be better to make one chart with 5 graphs of different colors.
> 
> Example:
> 
> <img alt="Screen Shot 2021-12-08 at 15 16 51" width="610" src="https://user-images.githubusercontent.com/62497891/145224012-0e57cf86-ccb6-41f0-8023-121981ca019a.png">

We plan to implement somethink like this in the future

**Comment by Oleg-Chashko** [comment]
- The curve of the graph does not correspond to the numerical readings.

![Screen](https://user-images.githubusercontent.com/62497891/145258818-6e8848c2-e73d-4171-a8e5-a1e6547db4fb.gif)

**Comment by maximtop** [comment]
> * The curve of the graph does not correspond to the numerical readings.

This was made intentionally for the graph line to be smooth.

**Comment by Oleg-Chashko** [comment]
> > * The curve of the graph does not correspond to the numerical readings.
> 
> This was made intentionally for the graph line to be smooth.

I understood everything, it's strange that in this graph you managed to do it as expected.

<img width="274" alt="Screen Shot 2021-12-09 at 12 35 16" src="https://user-images.githubusercontent.com/62497891/145389592-1e809387-9376-4cc9-a84f-3e2856183bdc.png">

**Comment by Oleg-Chashko** [comment]
- If the cursor is on the line, there is a dead zone of readings.

https://user-images.githubusercontent.com/62497891/145390752-71dcac79-117e-460a-aa90-98ddadd831e2.mp4
