### ISSUE TITLE
Implement "integration mode" for Safari browser extension

### ISSUE THREAD

**Issue by sergeykuzmich** [AdguardTeam/AdguardBrowserExtension#190]
Safari extension does not switch to assistant mode when using system installed AdGuard.

Safari extension 2.1.5
AdGuard 1.2.0
Safari 9.0.3
OS X 10.11.3

**Comment by ameshkov** [comment]
We cannot **yet** implement the integration mode in Safari extension (like it's done in [Chrome and FF](https://adguard.com/en/adguard-adblock-browser-extension/integration-mode.html#integrationMode))

Safari has pretty many restrictions which does not allow us use the same way of detecting desktop AG presence.

**Comment by ameshkov** [comment]
Hm, i've just got an idea. The only problem is the desktop AG detection. It is really not that hard to use a different way instead the one we use in other extensions.

**Comment by ameshkov** [comment]
@Mizzick please assign a milestone to this issue.

In other extensions we are looking for AG response header. For Safari we could use some IPC method to detect if desktop AG is present.

**Comment by SergeyKuzmich** [comment]
Maybe there is a way to build separate extension for Safari which works only as a helper. 

As I understand 'assistant extension' code is already in Safari extension, but there is a problem to detect installed AG and switch it?! I think I can check it out and try to force run Safari extension in integration mode.

**Comment by ameshkov** [comment]
It's not that simple, integration code is not included into a Safari extension now.

You're right, the problem is with desktop AG detection. Chrome/FF add-ons do it on per-tab basis checking response headers. Instead we should switch to some unified detection, for instance connecting to some reserved local port.

**Comment by williamli** [comment]
Is "integration mode" ready on Safari yet?
If I have the AG desktop running, should I install the safari plugin?

**Comment by ameshkov** [comment]
Safari 12 deprecates old browser extensions so it's not relevant anymore
