### ISSUE TITLE
Images are broken by HTML filtering rules

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/AdguardBrowserExtension#1906]
@adguard-bot commented on [Mon Nov 22 2021](https://github.com/AdguardTeam/AdguardFilters/issues/100876)

### Issue URL (Incorrect Blocking)
 [https://www.apkmirror.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.apkmirror.com%2F)
### Comment
> This website not working with the beta browser extension, but working fine with last stable build.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/ZZBoLpT.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/JgIm8Sd.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v4.0.64
Browser: | Firefox
Stealth mode: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/>AdGuard URL Tracking, <br/>AdGuard Tracking Protection<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/>Liste AR
Other extensions used: | ESET Security

---

@githubuser013 commented on [Thu Nov 25 2021](https://github.com/AdguardTeam/AdguardFilters/issues/100876#issuecomment-979499860)

Dears,
Any update? the images still don't appear.

Thanks

**Comment by AdamWr** [comment]
It looks like a bug.
It seems that HTML filtering rules causes that images are not loaded correctly.
For example, add this rule to "User rules":
```
com,net,org,pl,ru$$script[tag-content="test_test_test"]
```
then try to open any image, example -  [https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png)

Image is broken.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/143549163-5217442f-bd63-417b-adca-7401b2b1d513.png)

</details>

**Comment by Mizzick** [comment]
It happens like there is something wrong with `webRequest.filterResponseData()` in FF.
Processed images are broken, this could be tested with:
```
function listener(details) {
  // if (details.type === 'image') {
  //   return;
  // }

  let filter = browser.webRequest.filterResponseData(details.requestId);
  let decoder = new TextDecoder("windows-1252");
  let encoder = new TextEncoder("windows-1252", { NONSTANDARD_allowLegacyEncoding: true });

  filter.ondata = event => {
    let str = decoder.decode(event.data, {stream: true});
    str = str.replace(/Example/g, 'Replaced');
    filter.write(encoder.encode(str));
    // Doing filter.disconnect(); here would make us process only
    // the first chunk, and let the rest through unchanged. Note
    // that this would break multi-byte characters that occur on
    // the chunk boundary!
  }

  filter.onstop = event => {
    filter.close();
  }

  //return {}; // not needed
}

browser.webRequest.onBeforeRequest.addListener(
  listener,
  {urls: ["<all_urls>"]},
  ["blocking"]
);
```
So for now we will just bypass all images.

**Comment by bkrucarci** [comment]
I can confirm it is fixed with the latest beta release. (v.4.0.105 beta)
The issue https://github.com/AdguardTeam/AdguardFilters/issues/105205 solved on my end. FYI
