### ISSUE TITLE
addons.mozilla.org beta release

### ISSUE THREAD

**Issue by Eiqnepm** [AdguardTeam/AdguardBrowserExtension#1907]
Is there a beta release on addons.mozilla.org? I'm aware there's a beta release on the Chrome add-on store however I'm unable to find the same for Firefox so I'm able to install the new beta release on my Android phone.

**Comment by maximtop** [comment]
There is no beta release on addons.mozilla.org, but you can try to install the standalone build. It can be downloaded here: https://adguard.com/beta.html
