### ISSUE TITLE
New possible filters?

### ISSUE THREAD

**Issue by alhambra11** [AdguardTeam/AdguardBrowserExtension#1909]
Since Spam404 project was discontinued, could we have an optional anti-phishing list? Ideally I'd suggest https://gitlab.com/curben/phishing-filter it's from the same author of the already in-built malware URL blocklist. Additionally, there's another small list to use to stave off PUPs https://gitlab.com/curben/pup-filter

Both of these already come fully compatible for both adguard home and adguard browser extension. Adding them to the android version would be a great addition imo.

**Comment by slavaleleka** [comment]
Issue moved to [AdguardTeam/FiltersRegistry #547](https://github.com/AdguardTeam/FiltersRegistry/issues/547) via [**ZenHub**](https://www.zenhub.com/)
