### ISSUE TITLE
Wrong area selection shown at yandex.ru

### ISSUE THREAD

**Issue by gshumihin** [AdguardTeam/AdguardBrowserExtension#191]
Happens when i'm trying to block elements with "Block element" tool:
<img src="http://content.screencast.com/users/shumegor/folders/Jing/media/2aab0d33-6836-4c46-a4ac-c4768a54358e/00001001.png" width="400">
<img src="http://content.screencast.com/users/shumegor/folders/Jing/media/47ae8844-0a2d-42a9-b22b-4d764e4c9858/00001002.png" width="400">

**Comment by gshumihin** [comment]
Same happened with lenta.ru: http://screencast.com/t/4H8CnBWNj

**Comment by Mizzick** [comment]
this happens when the selected element is not scrollable

**Comment by ameshkov** [comment]
Can you fix it?

**Comment by Mizzick** [comment]
Fixed
