### ISSUE TITLE
Barblock

### ISSUE THREAD

**Issue by alhambra11** [AdguardTeam/AdguardBrowserExtension#1910]
I'm running the beta version of adguard for chrome, and I see Barblock list is still here. Since it's not maintained anymore, wouldn't be better to get rid of it?

**Comment by slavaleleka** [comment]
Issue moved to [AdguardTeam/FiltersRegistry #546](https://github.com/AdguardTeam/FiltersRegistry/issues/546) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Mohammadsaead69** [comment]
> نه بهتر نیست ..

**Comment by Mohammadsaead69** [comment]
به جای این حرف ها شما هم بهتر نیست کمی اطلاعات از تغییرات انجام شده برای من ارسال کنید!؟؟

**Comment by Mohammadsaead69** [comment]
MohammadSaead69(John Doe)

**Comment by Birbber** [comment]
@Mohammadsaead69 This filter was removed from the preset list of available filters: https://github.com/AdguardTeam/FiltersRegistry/pull/548.
We don't send yearly reports with change logs, since you can read them in every release description.
