### ISSUE TITLE
UI Improvement: Sliders and etc.

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdguardBrowserExtension#1912]
- macOS v.12.0.1 (21A559)
- Microsoft Edge v.97.0.1072.13
- AdGuard Browser extension v.4.0.64

![UI Filters](https://user-images.githubusercontent.com/62497891/144471239-a7a3aa91-8b86-4eb6-95ac-d3c87cacb024.gif)

---

- For example: Not OK
<img width="575" alt="Screen Shot 2021-12-02 at 18 01 30" src="https://user-images.githubusercontent.com/62497891/144471449-b03b7f11-d81b-4ef1-a4a9-51cc3f59c6ee.png">

- For example: Not OK
<img width="656" alt="Screen Shot 2021-12-02 at 18 03 47" src="https://user-images.githubusercontent.com/62497891/144471497-ec8ce755-8913-4ab7-9208-3fb22cdb8c20.png">

- For example: OK
<img width="575" alt="Additional settings" src="https://user-images.githubusercontent.com/62497891/144471647-83cb00e5-569f-4418-be74-b64b57e1a531.png">

**Comment by gork7777** [comment]
Looks like not fixed in V4.0.105 beta

**Comment by Oleg-Chashko** [comment]
> Looks like not fixed in V4.0.105 beta

I confirm checked, not fixed.

**Comment by maximtop** [comment]
In the extension, we have decided to align the icon, title, and toggle in one line.

**Comment by Oleg-Chashko** [comment]
Forgot to align.

https://user-images.githubusercontent.com/62497891/150393423-a02428b7-b0d0-4d36-b83f-7edf97607b51.mp4

**Comment by maximtop** [comment]
> Forgot to align.

Sorry, we have missed it, but it wasn't clear from the initial issue.
Could you please create a new issue?

**Comment by Oleg-Chashko** [comment]
> > Forgot to align.
> 
> Sorry, we have missed it, but it wasn't clear from the initial issue. Could you please create a new issue?

Ok.
