### ISSUE TITLE
UI Improvement: scrolling in the statistics

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdguardBrowserExtension#1913]
![Screen](https://user-images.githubusercontent.com/62497891/144477837-90c8795f-9527-43dd-93f6-bd3dc5e1c74f.gif)

If possible, remove the scrolling in the statistics. Since the 5mm scrolling is not quite clear what it is for.
Perhaps you need it to demonstrate promotions and discounts. 

If scrolling in the statistics is not possible to remove:
- If it's to show promotions and discounts, make the scrolling activate when there are promotions and discounts.
- If this is difficult or impossible, make it so that when you switch to a statistic you do not have to use the scroll.
<img width="317" alt="Screen Shot 2021-12-02 at 18 59 31" src="https://user-images.githubusercontent.com/62497891/144477728-0a0ce70c-da68-4738-b6e3-9a6d98ceadff.png">

**Comment by maximtop** [comment]
We can't remove scroll, because it could happen that there will be more than 5 items in the statistics tab.
