### ISSUE TITLE
The new tab is defined as either (ntp.msn.com) or (edge://newtab/)

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdguardBrowserExtension#1914]
### Prerequisites

[ ✔︎ ] I am running the latest version
[ ✔︎ ] I checked the documentation and found no answer
[ ✔︎ ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - AdGuard Browser extension v.4.0.64
- **Browser and version:**
  - Microsoft Edge v.97.0.1072.13
- **Operating system and version:**
  - macOS v.12.0.1 (21A559)
- **Filters you use in AdGuard:**
  - Base filter, Social filter, Tracking Protection filter, Annoyances filter, AdGuard Russian filter and AdGuard German filter
- **Stealth Mode settings:**
  - Disabled
- **Other browser extensions:**
  - Not installed

### Expected Behavior

The new tab is defined as either (ntp.msn.com) or (edge://newtab/).

### Actual Behavior

I would like accuracy in detecting a new tab.

### Screenshots

https://user-images.githubusercontent.com/62497891/144483193-bc2a8a7b-1103-465b-b0af-1dc511dc742c.mp4

**Comment by maximtop** [comment]
I've opened few new tabs and all of them returned `edge://newtab`.
Could you please describe in which cases browser action returns ntp.msn.com or provide steps to reproduce?

**Comment by Oleg-Chashko** [comment]
> I've opened few new tabs and all of them returned `edge://newtab`.
> Could you please describe in which cases browser action returns ntp.msn.com or provide steps to reproduce?

Press (+) to open new tabs, nothing else needs to be done.

**Comment by Oleg-Chashko** [comment]
Press (+) to open new tabs, nothing else needs to be done.

Screenshots:

https://user-images.githubusercontent.com/62497891/144605203-306f74da-e8a0-40a9-98fa-ff1ca76b2dec.mp4

**Comment by maximtop** [comment]
Can not reproduce

https://user-images.githubusercontent.com/17272769/144611305-b3f4581c-f9f7-453e-b0a6-a1d58f9fc1a9.mp4

**Comment by Oleg-Chashko** [comment]
For the sake of purity of the experiment:
I uninstalled the browser and the extension and put it back on again, the problem remains.

<img width="1418" alt="Screen Shot 2021-12-03 at 14 46 35" src="https://user-images.githubusercontent.com/62497891/144613363-b80508e7-f962-487b-b9be-85193a5778ad.png">

**Comment by maximtop** [comment]
Requests from filtering log do not reflect tab url.
![image](https://user-images.githubusercontent.com/17272769/144613896-af3cc7dd-c7a6-49b2-9442-d04471436039.png)

Tab url is provided by browser API.
![image](https://user-images.githubusercontent.com/17272769/144614456-f499eee1-1b5a-44d9-9cfb-3d5f66beb553.png)

**Comment by Oleg-Chashko** [comment]
AdGuard Browser extension v.3.6.16, the problem remains.

<img width="1314" alt="Screen Shot 2021-12-03 at 15 01 57" src="https://user-images.githubusercontent.com/62497891/144615343-563bf2db-321f-4c8c-93fc-c8a505059f58.png">

Can I help you?

**Comment by Oleg-Chashko** [comment]
Installed a third party extension, there is a problem too. The problem is in the browser. Closed the topic.
<img width="1249" alt="Screen Shot 2021-12-03 at 15 19 32" src="https://user-images.githubusercontent.com/62497891/144618319-71efb75d-8784-4aca-9e43-f7a5f54197a3.png">
