### ISSUE TITLE
When a filter rule is selected, artifacts appear around the brackets

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdguardBrowserExtension#1916]
- AdGuard Browser extension v.4.0.64
- Firefox: v.96.0a1 (2021-12-03) (64-bit) 
- macOS v.12.0.1 (21A559)

When a filter rule is selected, artifacts appear around the brackets.

<img width="632" alt="Screen Shot 2021-12-03 at 19 54 14" src="https://user-images.githubusercontent.com/62497891/144658478-3fbc0a42-815a-45e5-8c2b-8a63fe6d5fad.png">

https://user-images.githubusercontent.com/62497891/144659843-4460dde7-49f6-47cd-a05d-fc5955b9c1f1.mp4

**Comment by maximtop** [comment]
Those are not artifacts but highlighted paired brackets.
