### ISSUE TITLE
Filters update notification didn't pop up

### ISSUE THREAD

**Issue by gshumihin** [AdguardTeam/AdguardBrowserExtension#192]
**Steps to reproduce:**
1. Open Firefox browser.
2. Install adguard extension (ver. dev 2.2)
3. Open Adguard settings
4. Go to "Ad blocker" section
5. Click "Check for filter updates" button

**Expected result:**
If there is no updates, you should see that type of notification: <img src="http://content.screencast.com/users/shumegor/folders/Jing/media/e8334e7d-a58e-4da8-bd07-6f6eec316a90/00001003.png" width="350">

**Real result:**
There is no any type of notification.

**Comment by gshumihin** [comment]
Nothing happened after i ckicked "check filters update" button in settings

**Comment by Mizzick** [comment]
Fixed
