### ISSUE TITLE
Firefox AG Beta Extension Not Recognized

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdguardBrowserExtension#1924]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  -  AG Beta Application version 2.6.1.1051 release (CL-1.8.221, DNS-1.6.58) / FF AG Beta Extension 1.2.2
- **Browser and version:**
  -  Firefox 95.0 (64-bit)
- **Operating system and version:**
  -  macOS 12.0.1 (21A559)
- **Filters you use in AdGuard:**
  -  See below.
![AG Filters 1:2](https://user-images.githubusercontent.com/49731083/145399437-504b790d-4d90-4868-bd55-71841b12b2f9.jpg)
![AG Filters 2:2](https://user-images.githubusercontent.com/49731083/145399456-8a4e126a-466b-46f8-8200-6d088e43bdd2.jpg)
- **Stealth Mode settings:**
  -  Yes
- **Other browser extensions:**
  -  See below.
![FF Extensions ½](https://user-images.githubusercontent.com/49731083/145399619-80aa08a2-fd04-446b-a6d6-a4b66606af1d.jpg)
![FF Extensions 2:2](https://user-images.githubusercontent.com/49731083/145399632-1cb9c8e8-4624-4cd3-8c3a-d4f9d3f7b8b0.jpg)

### Expected Behavior

 AG Beta application should recognized that FF AG Beta extension is installed.

### Actual Behavior

 AG Beta application does not recognized FF AG Beta extension installation. 

### Screenshots

FF AG Beta installed and working.

![AG Beta](https://user-images.githubusercontent.com/49731083/145399922-1f97cfe3-5aa6-4c19-acc1-1c460a8206f0.jpg)

However AG Beta application still recommend to install FF AG extension.

![AG FF](https://user-images.githubusercontent.com/49731083/145399946-6bb6c76e-5512-4d6a-9f3e-973433aae635.jpg)

<details><summary>Screenshot:</summary>

</details>

**Comment by Birbber** [comment]
Issue moved to [AdguardTeam/AdguardForMac #1010](https://github.com/AdguardTeam/AdguardForMac/issues/1010) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Quorum75** [comment]
In fact it doesn't work because when you click on FF extension within AG Beta you end up on a webpage requesting you to install Firefox 🤦🏻‍♂️

![image](https://user-images.githubusercontent.com/49731083/145415603-37491edd-fd2e-4c85-b80a-e655f7f0fef7.jpeg)

However I found a workaround by downloading manually the file and installing it. 

Then, the issue is either from AG or FF. 🤔
