### ISSUE TITLE
UI Firefox - Filtering log

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdguardBrowserExtension#1926]
Firefox - Filtering log:

- Increase the horizontal size of the window so that the arrow does not appear.
- Increase contrast.

<img width="1000" alt="Firefox - Filtering log" src="https://user-images.githubusercontent.com/62497891/145709578-7ab3feee-f7b5-49c1-9ece-b023f1addf90.png">

---

For example: Microsoft Edge & Google Chrome - Filtering log

- Microsoft Edge and Google Chrome do not have these problems.

<img width="1000" alt="Microsoft Edge   Google Chrome - Filtering log" src="https://user-images.githubusercontent.com/62497891/145709600-b9143c1b-f42e-498d-8dbb-cfce27d78b7c.png">

**Comment by Birbber** [comment]
@Oleg-Chashko We'll see if we can use a screen size to calculate the size of the filtering log, thanks for the suggestion. Additionally, will think about bringing placeholders to the unified design.
