### ISSUE TITLE
Rules break the webiste, but they should not be applied there

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/AdguardBrowserExtension#1927]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - AdGuard v4.0.64
- **Browser and version:**
  - Chrome 96
- **Operating system and version:**
  - Windows 10
- **Filters you use in AdGuard:**
  - Russian
- **Stealth Mode settings:**
  - disabled
- **Other browser extensions:**
  - only AdGuard for Chrome

### Expected Behavior

Rules should not be applied here https://yandex.ru/metro/moscow?scheme_id=sc34974011.

### Actual Behavior

Rules break the website, but they should be applied there, because those selectors don't exist in the code.
**To reproduce this:**
1. Add the rules below to the User rules.
2. Open  https://yandex.ru/metro/moscow?scheme_id=sc34974011.
3. You'll see that the webiste is broken.
```
yandex.by,yandex.com,yandex.fr,yandex.kz,yandex.ru,yandex.ua##div[style="min-height:220px"] > div > div  > div > *:not(div)
yandex.ru##.q-page div[style^="will-change: position, transform; width: 320px;"] > div[class*=" "] > div[style="min-height:300px"] :not(div)
```

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33488229/147480380-c28b79ac-51ba-40c9-928b-cbdf9fd6c337.png)

</details>

**Comment by maximtop** [comment]
Can not reproduce on the Chrome Version 97.0.4692.71 (Official Build) (x86_64) anymore
