### ISSUE TITLE
User filter export works incorrect

### ISSUE THREAD

**Issue by gshumihin** [AdguardTeam/AdguardBrowserExtension#193]
**Steps to reproduce:**
1. Go to Adguard settings
2. Go to User filter section
3. Add few rules to User filter list
4. Press "Export" button

**Expected result:**
All rules exported into export.html file. This file also should be opened in new tab.
<img src="http://content.screencast.com/users/shumegor/folders/Jing/media/106cb444-5233-4d9a-88b0-803d66340086/00001005.png" width="300">

**Result:**
export.html file is empty:
 <img src="http://content.screencast.com/users/shumegor/folders/Jing/media/959ba42f-2e5d-4702-a264-f0b68652f513/00001007.png" width="350">
but User filter list looks like that:
<img src="http://content.screencast.com/users/shumegor/folders/Jing/media/33d741a1-8e88-4814-afd7-61a28771dbfb/00001006.png" width="350">

**Comment by Mizzick** [comment]
Fixed
