### ISSUE TITLE
The rule `_ad300.` is blocking access to `lapuelle-juridique.com`

### ISSUE THREAD

**Issue by MlecerfAxe** [AdguardTeam/AdguardBrowserExtension#1931]
### Issue Details

- **AdGuard version:**
  - Version 3.6.16
- **Browser and version:**
  - Chrome Version 96.0.4664.45 
- **Operating system and version:**
  - Windows 10 & Linux Mint & Ubuntu
- **Filters you use in AdGuard:**
  - Base filter
- **Stealth Mode settings:**
  - it's disabled
- **Other browser extensions:**
  - 

### Expected Behavior

My site page should display

### Actual Behavior

The page does not appear and it tells me that I am not connected to the internet however all the other pages of my site are working, I only have one problematic page and it ends with "_ad300.html "

### Screenshots

<details><summary>Screenshot:</summary>

![Screenshot](https://user-images.githubusercontent.com/96476274/146926221-356a9796-91fd-4a06-92d2-49b059176219.png)

</details>

**Comment by Birbber** [comment]
@MlecerfAxe Could you send us the link, so we could check it on our end?

**Comment by MlecerfAxe** [comment]
@Birbber [https://www.lapuelle-juridique.com/l-administration-saisie-d-une-demande-de-rupture-conventionelle-est-ellle-en-obligation-de-mener-la-procedure-a-son-terme---_ad300.html](https://www.lapuelle-juridique.com/l-administration-saisie-d-une-demande-de-rupture-conventionelle-est-ellle-en-obligation-de-mener-la-procedure-a-son-terme---_ad300.html)

**Comment by Birbber** [comment]
@MlecerfAxe This website won't load even without AdGuard extension, giving a message in console: https://uploads.adguard.com/annrgy_k9b9d.png

**Comment by MlecerfAxe** [comment]
@Birbber We use certain country ip blocking, can you tell me which country you are doing your tests from and can you provide me with a fixed ip that i can see to allow it

**Comment by Aydinv13** [comment]
@Birbber I can confirm the issue, the rule `_ad300.` is blocking access to the website (base filter)

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdguardFilters #105109](https://github.com/AdguardTeam/AdguardFilters/issues/105109) via [**ZenHub**](https://www.zenhub.com/)
