### ISSUE TITLE
Change 'pause' button style

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdguardBrowserExtension#1932]
I edited pause button like version 3.6. Also we have to press save button to save user rules, can you add an option to autosave?
Normal:
![AG](https://user-images.githubusercontent.com/35523759/147388725-2ec5b645-bb27-40de-bf6c-d67295a94b33.JPG)
Edited:
![AG_button](https://user-images.githubusercontent.com/35523759/147388728-e1e79b94-a86c-4631-97c9-b03e07e02a4d.png)

**Comment by Birbber** [comment]
@gork7777 Autosave feature was deliberately replaced by implementation of "save" button in order to avoid some inconveniences. Will think about changing the button though!

**Comment by bkrucarci** [comment]
@gork7777 it seems fixed on latest beta 4.0.108
