### ISSUE TITLE
Legacy AdGuard Extension

### ISSUE THREAD

**Issue by bkrucarci** [AdguardTeam/AdguardBrowserExtension#1933]
Hi,

Current AdGuard is not compatible with Pale Moon and Seamonkey.
Is there any plan to fork AdGuard to release a legacy add-on for these kind of browsers? 
uBlock is releasing the legacy version still. ([see](https://github.com/gorhill/uBlock-for-firefox-legacy/releases))

I want to use AdGuard on Pale Moon. uBlock cannot run CSS rules of AdGuard's.

Any possibilities for legacy add-on?

Thanks

**Comment by Birbber** [comment]
@bkrucarci We're not planning on supporting legacy add-on. You can download older AdGuard builds in order to use it in Pale Moon browser.
