### ISSUE TITLE
Misinformation on AdGuard's Reputation Check [Suggestion]

### ISSUE THREAD

**Issue by bkrucarci** [AdguardTeam/AdguardBrowserExtension#1935]
I am using latest AdGuard browser extension BETA. If it is not the right place for this, please move where acceptable place.

I just checkhed the [reputation page of AdGuard](https://reports.adguard.com/en/welcome.html) with a fresh phishing link !

**The cloudflare blocks the phishing.** ![See Screenshot](https://user-images.githubusercontent.com/15933805/147514618-e83f5f72-1604-4e60-a3a1-a46ba0e5c4f0.png)

**Comodo Valkyrie blocks the phishing** 
![Comodo Verdict](https://user-images.githubusercontent.com/15933805/147514644-011fa6a5-4201-4004-8861-146579ca0b51.png)

**On AdGuard's Reputation Page... AdGuard says it is SAFE !**
![Screenshot_2](https://user-images.githubusercontent.com/15933805/147514717-e35c9103-e8d1-41f4-8409-62b6ad7e6963.png)

What is AdGuard doing?
With the current method of AdGuard's reports page misinform the people. Because the extension claims that it has *Phishing and malware protection* . AdGuard seems only blocks the "known" phishing and malicious websites. It is a blacklisting method. If a website is not in blacklist then AdGuard says website secure! As shown above screenshots.
The phishing is so fresh! First scan of the page on VirusTotal. [The Virustotal Result of First Scan](https://www.virustotal.com/gui/url/71c721233451972e48c0c2c052dc2865b390232fec3d392bede46aafa7303a79/detection)
There is no WOT or Google Safebrowsing knows it! How did adguard determine that this site is safe without these guys?

What should AdGuard do?
Blacklisting is good. I am not bad at with blacklisting. AdGuard needs Default Deny approach on reputation check. On the same senario, if website is not blacklist then it is un-known ! Unknown website can be good or bad.
AdGuard's reputation checker should mark the website as "Unknown" website with a good explanation of it can be good or bad.

I hope I can explain the issue well. Please comment below for further improvements on this problem. @Birbber

**Comment by Birbber** [comment]
@bkrucarci You have a good point, thanks for the report. This issue concerns not only the extension, but the other AdGuard products as well. 
We can't implement it just now, since it's quite risky, therefore I'll close this issue for now. But our colleagues will internally discuss this issue and decide whether we can do anything about it.

**Comment by bkrucarci** [comment]
@Birbber
Is there any place to follow this issue? I want to be informed.
You said 
> We can't implement it just now, since it's quite risky

But the current situation is risky as well. You may open another issue in right place but please leave it open. We should be able to follow about it.
Thanks

**Comment by Birbber** [comment]
@bkrucarci Global issues that affect many products are conducted in a private project. Unfortunately, there is no public place for that. But don't worry, it won't be lost or forgotten!

**Comment by bkrucarci** [comment]
@Birbber When it is solved, can you please mention the changelog here?
Thank you.

**Comment by Birbber** [comment]
@bkrucarci Sure.
