### ISSUE TITLE
Ad blocking is not working on Edge's start page

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1936]
### Issue Details

- **AdGuard version:** 4.0
  - 
- **Browser and version:** Edge
  - 
- **Operating system and version:** Win10
  - 
- **Filters you use in AdGuard:** Base
  - 
- **Stealth Mode settings:** all
  - 
- **Other browser extensions:** no
  - 

### Expected Behavior

The rules applied.

### Actual Behavior

In the filtering log I see URL of the page
`https://ntp.msn.com/edge/ntp?locale=en&title=New%20tab&dsp=1&sp=Bing&startpage=1&PC=U531&OCID=MNHP_U531`
also I see the rules, which looks like injected, but not applied.
Not sure If this page is protected.

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/147557614-077e8bfa-8116-4c6f-a08d-46b0a8baba00.png)

</details>

**Comment by Oleg-Chashko** [comment]
The new tab is defined as either (ntp.msn.com) or (edge://newtab/) #1914

**Comment by Alex-302** [comment]
Protected page can't be filtered.
