### ISSUE TITLE
AdGuard 4.0.64 Beta Doesn't Check Option on Reports AdGuard Page

### ISSUE THREAD

**Issue by bkrucarci** [AdguardTeam/AdguardBrowserExtension#1937]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [+] I am running the latest version
- [+] I checked the documentation and found no answer
- [+] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - AdGuard Extension v4.0.64 Beta
- **Browser and version:**
  - Latest Opera
- **Operating system and version:**
  - Windows 10
- **Filters you use in AdGuard:**
  - Base + Turkish + Tracking + Social + URL Param + Annoyances
- **Stealth Mode settings:**
  - Enabled. All options checked (but Self-destruction of first-party cookies )
- **Other browser extensions:**
  - None

### Steps to Reproduce Bug

1 - I enabled the option "Remove URL Tracking Parameters" under Stealth mode. It enables the related filter.
2 - Go to a website use "Report an Issue" option under extension menu
3 - Go to the step 4/8
4 - You will see that "Remove URL Tracking Parameters" option is unchecked but it is enabled.
5 - "Disable WebRTC" option is enabled. At same step, it is checked with no problem. There is a problem with "Remove URL Tracking Parameters" option and it does not check on the report issue page.

### Screenshots

<details><summary>Screenshot:</summary>

![Screenshot_1](https://user-images.githubusercontent.com/15933805/147654860-4cbe2774-f9aa-4468-8d7f-0d130b5e0ee3.png)
![Screenshot_2](https://user-images.githubusercontent.com/15933805/147654874-4b373dbd-9f5e-4c14-8dd0-f718e83ac14c.png)
![a3](https://user-images.githubusercontent.com/15933805/147656366-97524c3e-3253-4b27-b31f-2b45fe22c3cb.png)
![Screenshot_4](https://user-images.githubusercontent.com/15933805/147654883-ba697b34-435d-4c58-b76a-10296486b724.png)

**Comment by Birbber** [comment]
Issue moved to [AdguardTeam/ReportsWebApp #290](https://github.com/AdguardTeam/ReportsWebApp/issues/290) via [**ZenHub**](https://www.zenhub.com/)
