### ISSUE TITLE
Please don't make false claims

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardBrowserExtension#1942]
Hey
@Birbber  You are not an engineer. There is no such thing as "QA Engineer". Engineering is not about sitting behind a screen, and pressing keys on a keyboard to write code. No, engineering is far more serious. Engineering is about designing and building real entities, like turbines or buildings. Software developers have a tend to make huge and false claims these days. They are not engineers, and will never be engineers, not even close. 
Bye

**Comment by gork7777** [comment]
Hi. There is such a thing as QA, there is exactly the same in engineering. Engineer is not just about design and building. I saw some software too, but I know more or less what software is and the engineer. Engineer exists to create something new and different. If you don't have knowledge I don't think you should say such things to people
