### ISSUE TITLE
Phishing protection issue

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1944]
- **AdGuard version:** 4.0.92

### Expected Behavior

URL is blocked

### Actual Behavior

Following URL is not blocked(whole dynserv.org blacklisted) when you click it
`http://birthday4.dynserv.org/parpar.html/b2Q9MXN5bTYxZDg3NGJlYjZjYmNfdmxfQWN0aXZlMTF2bF8wdDZjLnN3dm80Zi5DMDAwMHJmbmVmOTFleHYxMHlfdnExMDUwLmZuZWY5MGFxYjBmLTBuYmZuNms=1a1MfO`
But this is blocked
`http://birthday4.dynserv.org/parpar.html/xxx=xxx`

probably due to `302 redirect`

**Comment by maximtop** [comment]
Redirects are not blocked by phishing protection intentionally due to this issue
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/995
