### ISSUE TITLE
What or where to find your lists sources and would AdGuard like to collaborate with mypdns.org.

### ISSUE THREAD

**Issue by Rexadev** [AdguardTeam/AdguardBrowserExtension#1945]
https://mypdns.org/mypdns/

Topic: What or where to find your lists sources

Content: As I am contributing to an external projects sources, for which you previously included from https://github.com/clefspeare13/pornhosts now https://mypdns.org/clefspeare13/pornhosts.
I would then like to ask you if there is a way to locate your sources for MixedContent blocking content's or if you would like to share the origin of any of these sources?.
I will also ask if you in any way would like to considering co-operating with mypdns.org in the future on this topic.

Disscusion on mypdns.org - https://mypdns.org/mypdns/support/-/issues/260

**Comment by Birbber** [comment]
Hello, @Rexadev. Please look for this info in [FiltersRegistry](https://github.com/AdguardTeam/FiltersRegistry). You need to find the `filters/` folder. For each filter there is a `metadata.json` where the `subscriptionUrl` is specified.
As for the collaboration suggestion, I'll transfer it to the colleagues and will let you know once I got any information.

**Comment by Birbber** [comment]
@Rexadev Could you give us more information on what kind of collaboration do you suggest? It's not quite clear whether you suggested to include AdGuard as a source of rules or something else.

**Comment by Rexadev** [comment]
Ping @spirillen https://github.com/spirillen

**Comment by spirillen** [comment]
Hey @Birbber 

I think what rexadev is up to, is to share validated data on adult related DB's and that, I, as such just should be pulling the data from your external sources.

But the fact is, here comes a few challenges as:
1. We do not blindly import external data
2. All our accepted records have been verified by a human
    1. Exceptions for this is 1 external source.

For the other way around I believe you could benefit from using one or more parts of our projects and not just the anti adult list as which I think rexadev is referring to.

Do to the resent actions of GH's on adult related subjects (https://mypdns.org/my-privacy-dns/porn-records/-/issues/1986) && 
![image](https://user-images.githubusercontent.com/44526987/151186925-1c6d2c25-84fb-41b5-b69f-f7a8700c9a86.png)

(These are two years old issues. and they suspended my account for two weeks)

I will offer you to use our issue board for adult like issues and commits; as we, our self, no longer have any _trust_ nor feeling _safe_ on GH any longer and therefor in full have moved all activities to own domain.
It is this part I see the biggest mutual benefit for both projects.

---------

A new feature on mypdns is Dante's Adult contents reporting tools: https://mypdns.org/infrastructure/porn-report (Requires API-Key to use)
