### ISSUE TITLE
Unable to update filter rules using China Mobile Broadband network 

### ISSUE THREAD

**Issue by DustinWin** [AdguardTeam/AdguardBrowserExtension#1949]
### Prerequisites
- [ √ ] I am running the latest version
- [ √ ] I checked the documentation and found no answer
- [ √ ] I checked to make sure that this issue has not already been filed

### Issue Details
When I use China Mobile Broadband's network, I cannot update AdGuard's ad blocker (filter rules), but it works fine after switching to another operator's network, or after overturning the wall (with VPN). 
![QQ截图20220114230320](https://user-images.githubusercontent.com/45238096/149537211-a9979298-681f-4313-9757-14104d706729.png)

- **AdGuard version:**
 AdGuard v3.6.17
- **Browser and version:**
Edge Dev 99.0.1131.3
- **Operating system and version:**
Windows 11

**Comment by DustinWin** [comment]
I think I found the reason: China Mobile Broadband can't access the "filters.adtidy.org" domain.

**Comment by Birbber** [comment]
@DustinWin Thanks for the report. Some users faced the same issue. Could you send us a screenshot of `Network` tab on [Background.html](https://uploads.adguard.com/background.html.png)? Any errors there?

**Comment by DustinWin** [comment]
> @DustinWin Thanks for the report. Some users faced the same issue. Could you send us a screenshot of `Network` tab on [Background.html](https://uploads.adguard.com/background.html.png)? Any errors there?

Thanks for your reply, I found out that the ad blocker can be updated using China Mobile Broadband. 
![QQ截图20220120214037](https://user-images.githubusercontent.com/45238096/150349729-97e6c64d-e311-4592-9500-97164b9fe4ea.png)
