### ISSUE TITLE
JS to turn on/off the protection switch

### ISSUE THREAD

**Issue by dappcreative** [AdguardTeam/AdguardBrowserExtension#1953]
Hello, is it possible to turn on/off the protection switch using javascript?

I tried 

document.querySelector('.switch-btn').checked = 0 but it does not work.

KR

**Comment by Birbber** [comment]
@dappcreative Could you give more information on how you're gonna use it?

**Comment by dappcreative** [comment]
with tampermonkey, i want to load additional popup.js in the background script, i need some js function i can call to disable the protection automatically on sites of my choosing.

**Comment by Birbber** [comment]
@dappcreative In this case you better create your own custom filter or add a list of domains in allowlist.

**Comment by dappcreative** [comment]
Thank you, can you atleast tell me if there is a funtion where i can disable the proection switch through javascript? KR
