### ISSUE TITLE
在Kiwi浏览器上设置界面无法缩放，调整到桌面版网页才可以缩放，而且打不开拦截WebRTC选项

### ISSUE THREAD

**Issue by MonicaWQY** [AdguardTeam/AdguardBrowserExtension#1967]
在Kiwi浏览器上设置界面无法缩放，调整到桌面版网页才可以缩放，而且打不开拦截WebRTC选项

**Comment by Birbber** [comment]
@MonicaWQY Hi, what version of AdGuard browser extension do you use?
It shouldn't be an issue on version 4.0, since the settings page adjusts to mobile screen.

**Comment by MonicaWQY** [comment]
3.6.17



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月31日(周一) 下午5:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [AdguardTeam/AdguardBrowserExtension] 在Kiwi浏览器上设置界面无法缩放，调整到桌面版网页才可以缩放，而且打不开拦截WebRTC选项 (Issue #1967)




 
@MonicaWQY Hi, what version of AdGuard browser extension do you use?
 It shouldn't be an issue on version 4.0, since the settings page adjusts to mobile screen.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Birbber** [comment]
@MonicaWQY Try testing on [4.0.105 beta](https://github.com/AdguardTeam/AdguardBrowserExtension/releases/tag/v4.0.105-beta).

**Comment by MonicaWQY** [comment]
> @MonicaWQY尝试在[4.0.105 beta](https://github.com/AdguardTeam/AdguardBrowserExtension/releases/tag/v4.0.105-beta)上进行测试。

我的，我试试

**Comment by Birbber** [comment]
@MonicaWQY Any update on this?

**Comment by MonicaWQY** [comment]
4.0版本可以打开选项，但是我开VPN插件的时候还是会有个提示



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月2日(周三) 下午4:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [AdguardTeam/AdguardBrowserExtension] 在Kiwi浏览器上设置界面无法缩放，调整到桌面版网页才可以缩放，而且打不开拦截WebRTC选项 (Issue #1967)




 
@MonicaWQY Any update on this?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Birbber** [comment]
@MonicaWQY There's a similar issue [#1934](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1934). You can monitor the progress or leave comments there.
I'm closing this one as a duplicate.
