### ISSUE TITLE
List problem

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardBrowserExtension#1968]
https://gitlab.com/curben/urlhaus-filter#url-based-adguard

It seems Adguard products all use the standard link (updates once) to update the list, while the third mirror link or even the second one update twice, hence both give better malware protection to users. Basically, even if Adguard checks updates twice a day, it still downloads the outdated list. See https://imgur.com/a/LmxjbMV

**Comment by slavaleleka** [comment]
AdGuard uses `curben.gitlab.io/malware-filter/urlhaus-filter-ag-online.txt` url for the filter list update, 
and checks it every 4 hours which means **6 times per day**. so there might be no problem with it, isn't it?
