### ISSUE TITLE
Add a build for legacy Firefox ESR (31.x)

### ISSUE THREAD

**Issue by xdel** [AdguardTeam/AdguardBrowserExtension#197]
Due to visible slowdown for current ESR 38.x and the release 45.x (page rendering times are increased approximately twice) over earlier versions I would prefer to stay on old ESR. Unfortunately due to changes in the build procedure new extension bundle is not working for me anymore. As building the extension from scratch is very tricky and does require a couple of legacy SDKs to be installed, providing separate binary for old Firefox versions would be a very nice step.

**Comment by xdel** [comment]
https://github.com/AdguardTeam/AdguardBrowserExtension/tree/v2.2.1 fixes the problem in general over 2.1.x.

**Comment by TPS** [comment]
@AdguardTeam There isn't any legacy/Pale Moon version from https://github.com/AdguardTeam/AdguardBrowserExtension/releases/tag/v2.2.4 onwards....  Please release 1! :bow:

**Comment by ameshkov** [comment]
That's because v2.2.4 is for chromium only:)

**Comment by TPS** [comment]
Well, _that_ explains it.… 😊
