### ISSUE TITLE
AdGuard 4.0.108 Does Not Check Updates for Custom Filter

### ISSUE THREAD

**Issue by bkrucarci** [AdguardTeam/AdguardBrowserExtension#1972]
I am using Anti-Prayer List from Dandelion's AdList.
He updated the filter a few minutes ago. I have uBlock Origin on Chromium with same filters installed and uBlock gets the update after Dandelion adding the new rules. uBlock Origin blocked the contents after checking updates but AdGuard didn't ! 

I used the "Check for Updates" option AdGuard Settings > Filters . It said "No updates found".

Does AdGuard browser extension check updates for custom filters which added through a raw link?

Thanks

**Comment by maximtop** [comment]
Hi, @bkrucarci 
> Does AdGuard browser extension check updates for custom filters which added through a raw link?
Yes, the extension should check updates for custom filters added by the url.

Could you please attach the url to the filter? And maybe commit where this filter was updated?

**Comment by bkrucarci** [comment]
Hi @maximtop ,

Here is the commit : https://github.com/DandelionSprout/adfilt/commit/dc7db3c6b5244c9c191d5319c62f04d6f9a0c200
The filter is Dandelion's AntiPrayerTimesList . This commit was rather new when I opened this issue.
Here is my custom filters : https://i.imgur.com/XERt1Qz.png

**Comment by maximtop** [comment]
This filter doesn't follow a semantic versioning scheme (https://semver.org/) in its descriptions, that's why it wasn't updated. 
We are going to check if the filter version follows the scheme, otherwise, we will check filter content.

**Comment by maximtop** [comment]
Fixed
