### ISSUE TITLE
sezonlukdizi1.com###uyari for block fembed notification

### ISSUE THREAD

**Issue by retta1** [AdguardTeam/AdguardBrowserExtension#1975]
sezonlukdizi1.com###uyari for block fembed notification

_Originally posted by @retta1 in https://github.com/AdguardTeam/AdguardFilters/issues/108919#issuecomment-1035035356_

**Comment by maximtop** [comment]
I do not understand what you want us to do with this information. 
If you want this rule to be added to some of the filters it is not the right place for this issue.
Now I'm closing this issue. Feel free to open it again if my assumption is wrong.

**Comment by retta1** [comment]
@maximtop I already described here https://github.com/AdguardTeam/AdguardFilters/issues/108919#issuecomment-1035035356
