### ISSUE TITLE
[feature] [new] new twitter popup blocking viewing posts to block

### ISSUE THREAD

**Issue by hacknorris-aka-penguin** [AdguardTeam/AdguardBrowserExtension#1981]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

twitter recently updated their webapp blocking viewing profiles without account (like this ↓ )
![image](https://user-images.githubusercontent.com/97974194/154137644-398db8e4-c5c4-4a96-91c7-288b4f4be86a.png)

it happens after 2 minutes or scrolling fast thru 10 posts.

### Proposed Solution

adding new default rules to adguard default list of annoyances and hiding this popup while allowing wieving full profile without account

### Alternatives Considered
alternatively? probably visually hiding this popup but blocking scrolling if not possible to stop this

**Comment by hacknorris-aka-penguin** [comment]
if something - this screenshot is not an ad here but my old account which got suspended because i sweared at someone (and no im not gonna delete posts). and yes it also blocks me from visiting my profile :'D did this in incognito

anyways - who would advertise muted account? lol

**Comment by Birbber** [comment]
Issue moved to [AdguardTeam/AdguardFilters #111044](https://github.com/AdguardTeam/AdguardFilters/issues/111044) via [**ZenHub**](https://www.zenhub.com/)
