### ISSUE TITLE
Scriptlet rule does not work correctly in iframe on Firefox

### ISSUE THREAD

**Issue by hoang-rio** [AdguardTeam/AdguardBrowserExtension#1984]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - Adguard v3.6.17
- **Browser and version:**
  - Firefox 97.0.1
- **Operating system and version:**
  - MacOS 11.5.2
- **Filters you use in AdGuard:**
  - Base filter, [ABPVN List from custom url](https://abpvn.com/filter/abpvn-aDplLh.txt?adguard)
- **Stealth Mode settings:**
  - 
- **Other browser extensions:**
  - Violent Monkey

### Expected Behavior

Scriptlet rule work both on iframe or normal brower tab.

### Actual Behavior

Scriptlet rule is show in log window but it not work correctly when target website is loaded via iframe. 
When open iframe url in new browser tab scriptlet rule work correctly.
May be not only scriptlet rule does not work correctly please check another rule.

### Screenshots

<details><summary>When loaded in iframe</summary>

![Screenshot 2022-02-23 at 18 57 25](https://user-images.githubusercontent.com/11514638/155315022-8b3204e4-825d-4c1e-84ff-1b58c9d179cc.png)
</details>
<details>
<summary>When open in new brower tab</summary>

![Screenshot 2022-02-23 at 18 58 56](https://user-images.githubusercontent.com/11514638/155315220-7466c4cf-40e5-4f8c-8542-6e9756c3579e.png)
</details>

### Additional Information

URL with iframe: https://mitom1.tv/truc-tiep/juventus-u19-vs-roma-u19-1800-23-02/
URL in iframe: https://playmt.fastlycdn.xyz/ajax/chanel/type/3/link/as9xexm?autoplay=1

This issue only happend in Firefox. In Chrome with same setting everything working fine

**Comment by maximtop** [comment]
Could you specify which scriptlet rule is not working? 
Also, could you check if the issue can be reproduced in the beta version v4.0.x?
