### ISSUE TITLE
AdGuard 4.0.125 Beta Phishing Malware Protection Bug

### ISSUE THREAD

**Issue by bkrucarci** [AdguardTeam/AdguardBrowserExtension#1986]
### Issue Details

- **AdGuard version:**
  -  AdGuard Extension 4.0.125 Beta
- **Browser and version:**
  -  Firefox 97.0.1
- **Filters you use in AdGuard:**
  -   Custom Filter (Only) 
- **Stealth Mode settings:**
  -  Disabled
- **Other browser extensions:**
  -  None, just AdGuard.

### Expected Behavior

Fresh install of AdGuard on Fresh Firefox.  I never enabled the phishing & malware protection. 
When I go to the website : quellaplentyresolute[dot]com
AdGuard blocked the page "based on my security preferences."

2nd senario, Disable the AdGuard, restart browser, website still blocked by AdGuard !

Please check this.

### Screenshots

![Screenshot_172440_2022-02-23](https://user-images.githubusercontent.com/15933805/155338997-78fa7490-a3c5-4127-99f3-fca365e5763d.png)
-
![Screenshot_172504_2022-02-23](https://user-images.githubusercontent.com/15933805/155339057-0e8f8e78-0962-4414-aca7-e1484a9ca5da.png)

**Comment by Chinaski1** [comment]
Hello!

Judging from the text of the notice the secret is that your system using AdGuard DNS.
Please make a test on [adguard.com](https://adguard.com/en/test.html) to be sure
Then change DNS (network) settings clear your browser cache and try again :)

**Comment by bkrucarci** [comment]
> Hello!
> 
> Judging from the text of the notice the secret is that your system using AdGuard DNS. Please make a test on [adguard.com](https://adguard.com/en/test.html) to be sure Then change DNS (network) settings clear your browser cache and try again :)

True! Thanks for this
