### ISSUE TITLE
kaotic.com porn ads

### ISSUE THREAD

**Issue by Punallion** [AdguardTeam/AdguardBrowserExtension#1990]
Ill leave this here since there is no support option in my adguard firefox extension.

Can you fix the porn images on kaotic.com, i tried to create my own filter but it does not work, thanks.

**Comment by gork7777** [comment]
It looks already blocked. Which filters are you using?

**Comment by maximtop** [comment]
> Ill leave this here since there is no support option in my adguard firefox extension.
> 
> Can you fix the porn images on kaotic.com, i tried to create my own filter but it does not work, thanks.

Feel free to report issues via https://kb.adguard.com/en/technical-support/reporting-tool#extension
or directly here https://reports.adguard.com/en/new_issue.html
