### ISSUE TITLE
Pause button not fully aligned to center

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdguardBrowserExtension#1994]
You can see the difference if you look at the right and bottom parts of the pause button.

![adg](https://user-images.githubusercontent.com/35523759/156684829-4f829961-a7a6-4a23-95c5-7e8c1c18c446.jpg)

**Comment by gork7777** [comment]
You can also increase the size of the 'settings' icon to match the pause size.

**Comment by realodix** [comment]
https://github.com/AdguardTeam/AdguardBrowserExtension/commit/862af2d194ac2a6f2dee04a9bda04871b52b518e
