### ISSUE TITLE
Filter Importation Error

### ISSUE THREAD

**Issue by piquark6046** [AdguardTeam/AdguardBrowserExtension#1999]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 4.0.133 and 3.6.17
- **Browser and version:**
  - Firefox Dev 99.0b2
- **Operating system and version:**
  - Ubuntu 21.10
- **Filters you use in AdGuard:**
  - AG Tracking, AG URL, Fanboy Anti-FB, Fanboy Anti-3rd Font, AG Social, AG Annoyances
- **Stealth Mode settings:**
  -  OFF
- **Other browser extensions:**
  - Tampermonkey

### Expected Behavior
List-KR is successfully imported like AdGuard for Windows 7.9.1.

### Actual Behavior
List-KR cannot be downloaded.

### Screenshots

<details><summary>Screenshot:</summary>

![Screensho](https://user-images.githubusercontent.com/98787049/158051192-c03052ab-8f04-42c3-94e3-69098326f320.png)
![Screenshot](https://user-images.githubusercontent.com/98787049/158051014-da5151f2-2635-4f6f-9849-0c46e0840c1a.png)
![Screenshot1](https://user-images.githubusercontent.com/98787049/158051016-6960c8c5-8504-4063-b9f1-623720ea11fc.png)

</details>

### Additional Information

```
https://github.com/List-KR/List-KR/raw/master/filter.txt
```
```
https://github.com/DandelionSprout/adfilt/raw/master/AnnoyancesList
```

**Comment by maximtop** [comment]
Fails to download filters because one of included filters is empty (https://raw.githubusercontent.com/List-KR/List-KR/master/filters/desktop/macos_app.txt)

I think that we should not fail if included filter is empty.
