### ISSUE TITLE
Chromium Incognito Mode Problem

### ISSUE THREAD

**Issue by yigido** [AdguardTeam/AdguardBrowserExtension#2]
Hello,

I am using latest 2.0.7 version on my latest Chromium 44 build.
I use my browser always in incognito mode. When I visited a phishing page, Adguard opens another browser window to show its alert about phishing.
Why I can't see the alert in incognito mode? Adguard closes the phishing tab in incognito windows and then Adguard opens a new browser window to show alert.

Can you please look into it?
Why adguard did not show alert in incognito mode?

If you have question please ask I want to help.

Thanks,

**Comment by adguard** [comment]
Hi! We have an open bug about this. It was not possible to open "access denied" page in incognito mode but it is possible now so we will fix it eventually.

**Comment by yigido** [comment]
Thank you.

**Comment by ameshkov** [comment]
Fixed:
https://github.com/AdguardTeam/AdguardBrowserExtension/commit/9e24a5adddf37ee0c1162dbd798f9d991d157171

Sorry for delay:(
