### ISSUE TITLE
Firefox add-on UI is broken

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#20]
We should test it.

http://forum.adguard.com/showthread.php?5916-%D0%A0%D0%B5%D1%88%D0%B5%D0%BD%D0%BE-%D0%AF%D0%BD%D0%B4%D0%B5%D0%BA%D1%81-%D0%94%D0%B8%D1%80%D0%B5%D0%BA%D1%82-%D0%B2-%D0%9D%D0%BE%D0%B2%D0%BE%D1%81%D1%82%D0%B8-%D0%AF%D0%BD%D0%B4%D0%B5%D0%BA%D1%81&p=59772&viewfull=1#post59772

http://forum.adguard.com/showthread.php?5916-%D0%A0%D0%B5%D1%88%D0%B5%D0%BD%D0%BE-%D0%AF%D0%BD%D0%B4%D0%B5%D0%BA%D1%81-%D0%94%D0%B8%D1%80%D0%B5%D0%BA%D1%82-%D0%B2-%D0%9D%D0%BE%D0%B2%D0%BE%D1%81%D1%82%D0%B8-%D0%AF%D0%BD%D0%B4%D0%B5%D0%BA%D1%81&p=59950&viewfull=1#post59950

**Comment by ameshkov** [comment]
So what? Have you tested it?

**Comment by gshumihin** [comment]
Wont reproduce, but this tabkiller (https://github.com/piroor/tabkiller) cannot be installed in firefox ver. 40.0.3
