### ISSUE TITLE
Wrong preview showed when blocking elements on yandex.ru

### ISSUE THREAD

**Issue by gshumihin** [AdguardTeam/AdguardBrowserExtension#200]
**Steps to reproduce:**
1. Go to ytandex.ru
2. Select area like this: <img src="http://content.screencast.com/users/shumegor/folders/Jing/media/0a4bddc7-e3e8-434a-afe7-0cff2d270bfe/00001021.png" width="600">
3. Mark "Block similar elements"
4. Final rule should be: yandex.ru##.row, .second, .text_black_yes
5. Click preview 

**Expected result:**
On preview should be shown empty page

**Result:**
<img src="http://content.screencast.com/users/shumegor/folders/Jing/media/4e15f05c-4caa-432d-9b0b-3ba2a2f83bf0/00001022.png" width="600">

**Comment by Mizzick** [comment]
Fixed
