### ISSUE TITLE
What is the function of `Self-destructing third-party cookies` ?

### ISSUE THREAD

**Issue by takanon1china** [AdguardTeam/AdguardBrowserExtension#2000]
I'm using Chrome and my "Block third-party cookies" setting is on.
<details>
 <summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/101582952/158213633-39afa11d-2de4-4008-b862-a6c8364c5a3f.png)

</details>

Question is, does AdGuard's "Self-destruct third-party cookies" feature work the same as "Block third-party cookies" in Chrome?

So do I need to turn off the "Self-destructing third-party cookies" option in Stealth Mode?
<details>
 <summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/101582952/158213773-4bb0cc2a-8d9d-4340-aa67-590495cbaa9a.png)

 </details>

If both settings are the same thing, I'm thinking of close the cookie option in AdGuard.

**Comment by Spok1** [comment]
>Question is, does AdGuard's "Self-destruct third-party cookies" feature work the same as "Block third-party cookies" in Chrome?

No. It only blocks delivery.

>So do I need to turn off the "Self-destructing third-party cookies" option in Stealth Mode?

This means that cookies are destroyed after a certain period. 

>If both settings are the same thing, I'm thinking of close the cookie option in AdGuard.

This is not the same. If there are no third-party cookies, then nothing will be destroyed! Logical, isn't it!😏

**Comment by takanon1china** [comment]
Thanks for your help
I decided to keep Chrome's Block third party cookies setting on. It seems that there is no need for the cookie blocking setting in AdGuard.
