### ISSUE TITLE
Увеличение потребления памяти расширением!

### ISSUE THREAD

**Issue by Spok1** [AdguardTeam/AdguardBrowserExtension#2003]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**  
  3.6.17
- **Browser and version:**
 Chrome/99.0.4844.51
- **Operating system and version:**
 Выпуск	Windows 10 Pro
Версия	21H1
Сборка ОС	19043.1586

- **Filters you use in AdGuard:**
AdGuard Russian,</br>AdGuard Mobile Ads,</br>AdGuard Annoyances,</br>AdGuard Base,</br>AdGuard Tracking Protection,</br>AdGuard Social Media

- **Stealth Mode settings:**
  Hide your search queries, Remove X-Client-Data header from HTTP requests, Strip URLs from tracking parameters, Hide your Referrer from third-parties
- **Other browser extensions:**
adguard vpn

### Expected Behavior

Чтобы не увеличивался набор памяти!
### Actual Behavior

Увеличение памяти бесконтрольное!

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/34476664/158626417-bc3c0007-7236-45ef-bc68-cd9ae615d4e7.png)

</details>

**Comment by Vitalik93** [comment]
В последней версии (4.0.141) для Edge тоже заметил, что памяти стало больше потребляться. Раньше в простое было чуть выше 70 000 КБ, максимум 80, сейчас стабильно выше 80, а при открытии сайтов уходит за 90 - 100.

**Comment by maximtop** [comment]
Я потестировал у себя.
В эдж cперва установил 4.0.141, с настройками по умолчанию и следующими фильтрами: AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Russian filter. 
Затем установил 3.6.17 с тем же набором фильтров и настроек.

Открыл страницу яндекса (которая памяти занимает в 2 раза больше чем расширение) перезагрузил ее пару раз.

4.0.141 
все вкладки закрыты - 60MB
открытый таб c yandex.ru 70MB - 80MB

3.6.17
все вкладки закрыты - 58MB
открытый таб с yandex.ru 74MB - 79MB

Рост в памяти незначительный, если сравнивать версии. 

Больше памяти начинает потребляться, если открыть попап, настройки или фильтеринг лог (это происходит потому что мы начали рендерить страницы с помощью React, а не нейтив JS, React мы взяли, чтобы код стал понятнее и можно было быстрее внедрять новые фичи).

Также память может расти до тех пор пока кэш заполняется, но это тоже не бесконтрольное потребление памяти.

**Comment by Spok1** [comment]
@maximtop
> мы начали рендерить страницы с помощью React, а не нейтив JS,

Это же библиотека Js,по сути тот же джава крипт,только с удобным интерфейсом для ввода данных в приложениях мобильных!

> Также память может расти до тех пор пока кэш заполняется, но это тоже не бесконтрольное потребление памяти.

Некорректно как-то сравнивать разовое открытие вкладки в разных версиях расширения! Потребление будет различаться,однако,если в моем случае так вот пооткрывать/закрывать в течение дня сотню другую вкладок,да к тому же ещё по 500 блокированных запросов в них будет–выходит такая картина,что кэш приложения не сбрасывается,а только лишь увеличивается,что и приводит к утечке памяти,которая приведена у меня в снимке!

**Comment by maximtop** [comment]
120MB это результат, которого вы достигли открывая/закрывая сотни вкладок с 500 заблокированных запросов?
растет ли потребление дальше, если продолжать это делать?

**Comment by Spok1** [comment]
Думаю,что вырастит и дальше,если продолжать использовать браузер в подобном режиме! Это проблема, которую нужно решать! Сам браузер не сбрасывает кэш текстур графического ускорителя, и за условных 10 часов процесс отрисовщика занимает порядка 1 ГБ. Утечки памяти непозволительны ещё и в расширениях,коих  может быть не так и мало! Думаю,вы понимаете о чем я!

**Comment by maximtop** [comment]
Когда вырастет пришлите новый скриншот, пожалуйста. А еще переходите на v4.0, вносить правки в v3.6 мы уже не будем.

**Comment by Spok1** [comment]
> А ещё переходите на v4.0, вносить правки в v3.6 мы уже не будем.

Обновится расширение должно вскоре,там и погляжу что да как, и если нужно–пришлю отчёт снова.

**Comment by Spok1** [comment]
> А ещё переходите на v4.0, вносить правки в v3.6 мы уже не будем.

Обновится расширение должно вскоре,там и погляжу что да как, и если нужно–пришлю отчёт снова. А вам, я полагаю,есть над чем поразмыслить и внести соответствующие правки в последующие обновления расширения,чтобы кеш не разростался.

**Comment by Vitalik93** [comment]
Открыто 9 вкладок (скрин). Дальше при открытии вкладок увеличивается до 95 и выше 100.

![Снимок экрана 2022-03-25 120732](https://user-images.githubusercontent.com/34383288/160100680-9c7e8ece-c8d3-4667-8ddc-29276478a8e2.png)

**Comment by Spok1** [comment]
> Дальше при открытии вкладок увеличивается до 95 и выше 100.

Тут,видимо,недаработка в коде едж играет роль,ибо на хром такого нет,а выше 100 уже увеличивается,если смотреть на странице ютуб бесконечно ролики не обновляясь,когда заблокированных запросов перевалит за 200. А может быть и новая версия расширения не стабильна. В общем,покамест у меня расширение не обновилось,не могу подтвердить ваше утверждение. Как только,так сразу создам новый коммит.

**Comment by Spok1** [comment]
@maximtop 
> Когда вырастет пришлите новый скриншот, пожалуйста. А еще переходите на v4.0, вносить правки в v3.6 мы уже не будем.

 Потребление на этот разу у microsoft edge chromium

<details><summary>Screenshot 1</summary>

![image](https://user-images.githubusercontent.com/34476664/183312090-a16e5917-f67c-408e-9bb4-486b19b0cc70.png)

</details>

**Comment by maximtop** [comment]
Спасибо, посмотрим.

**Comment by Spok1** [comment]
>tswebextension.

Что это?

**Comment by Vitalik93** [comment]
У меня нормально. 

![Снимок экрана 2022-08-08 090452](https://user-images.githubusercontent.com/34383288/183359283-396689f4-3240-46aa-8bdc-012eac45719e.png)

**Comment by maximtop** [comment]
> Что это?

https://www.npmjs.com/package/@adguard/tswebextension

**Comment by Spok1** [comment]
@Vitalik93
> У меня нормально.
> 
> ![Снимок экрана 2022-08-08 090452](https://user-images.githubusercontent.com/34383288/183359283-396689f4-3240-46aa-8bdc-012eac45719e.png)

Открой 70 страниц во вкладках,посиди на каждой из них и посмотри на результат, после уже делай можешь выводы делать!

**Comment by Spok1** [comment]
@Vitalik93
> У меня нормально.
> 
> ![Снимок экрана 2022-08-08 090452](https://user-images.githubusercontent.com/34383288/183359283-396689f4-3240-46aa-8bdc-012eac45719e.png)

Открой 70 страниц во вкладках,посиди на каждой из них по 10ьсинут и посмотри на результат, после уже можешь выводы делать!

**Comment by Spok1** [comment]
@Vitalik93
> У меня нормально.
> 
> ![Снимок экрана 2022-08-08 090452](https://user-images.githubusercontent.com/34383288/183359283-396689f4-3240-46aa-8bdc-012eac45719e.png)

Открой 70 страниц во вкладках,посиди на каждой из них по 10 минут и посмотри на результат, после уже можешь выводы делать!

**Comment by Spok1** [comment]
@maximtop, я не силён в программировании! Могу лишь сделать выводы,что это связано с переездом на manifest v3?

**Comment by maximtop** [comment]
@Spok1 мы в этой версии еще не переезжали на mv3

**Comment by Spok1** [comment]
А что тогда даст эта библиотека в двух словах, я не понимаю просто!

**Comment by Spok1** [comment]
Улучшения привнесёт? А по поводу потребления,это после многочисленного открытия вкладок и работы с ними. Обычно неиспользованная память должна выгружаться ,а тут разрастается.

**Comment by maximtop** [comment]
это процесс подготовки к переезду на mv3

**Comment by Spok1** [comment]
Ну Гут. Поскорее бы внесли ясность, сломается ли блокировка типичная или нет в хромобраузерах или нет!
