### ISSUE TITLE
Много пустого места в настройках.

### ISSUE THREAD

**Issue by Vitalik93** [AdguardTeam/AdguardBrowserExtension#2008]
В последней версии расширения (4.0.141) для Edge в настройках много не использованного пространства. Свободного места много а текст и кнопки сбиты в центре. В версии 3.6 по моему выглядело удачнее.

![Снимок экрана 2022-03-18 180339](https://user-images.githubusercontent.com/34383288/159040330-267b6c5f-30dc-438f-8ec8-e7d635eec71f.png)

**Comment by Birbber** [comment]
@Vitalik93 Для этой версии специально сделали таким образом. Но спасибо за ваше мнение!
