### ISSUE TITLE
FirefoxNightly browser console error

### ISSUE THREAD

**Issue by gshumihin** [AdguardTeam/AdguardBrowserExtension#201]
**Steps to reproduce:**
1. Turn on "Send statistics for ad filters usage"
2. Open Browser console
3. Open any website 

**Result:**
$elemhide rules don't work, console error:
<img src="http://content.screencast.com/users/shumegor/folders/Jing/media/b93be141-88de-4128-9e6f-d33dd484fe71/00001023.png" width="400">
Link to [Learn More]: https://developer.mozilla.org/en-US/docs/Security/Mixed_content

**Comment by Mizzick** [comment]
Fixed
