### ISSUE TITLE
Circle around the protection switch blinks

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdguardBrowserExtension#2015]
I'm using AdGuard V4.0.141 and Chrome V99.0.4844.82. The circle around the protection switch blinks two times when you hover the cursor over it. No problem on the windows app. I think there's a problem with the animation when the circle is growing. Also this problem exists in other browsers.

Windows AdGuard;

https://user-images.githubusercontent.com/35523759/159369154-2c64c95c-2bc3-45b1-b0a8-d82a8e2dd3ab.mp4

AdGuard Extension;

https://user-images.githubusercontent.com/35523759/159369195-35d3141b-f567-4613-8e8d-f8d9fafffd6b.mp4

**Comment by Vitalik93** [comment]
Не наблюдаю такого. Версия 4.0.141, Edge.

**Comment by gork7777** [comment]
Looks like not resolved on v4.0.159. I tested but the issue persists.

https://user-images.githubusercontent.com/35523759/161539893-a2b419a5-6769-4e62-a227-f89a5e0db229.mp4

**Comment by kaprielov** [comment]
@gork7777 Hello, we cannot reproduce this problem
