### ISSUE TITLE
Allow list stopped working since AG extension 4.0.141

### ISSUE THREAD

**Issue by worldsdream** [AdguardTeam/AdguardBrowserExtension#2016]
I got the Adguard extension update in Firefox. The design looks great. I like it.

The only issue I have seen for now is that the allow list doesn't work.

For example, I have:

*mywebsite.com

It always did not run AG when I opened that website, even if there were subdomains.

For example:

test1.mywebsite.com
test2.mywebsite.com

Can you reproduce this bug? I didn't have any issues prior to AG version 4.0.141

**Comment by gork7777** [comment]
Did you try like `mywebsite.com` without `*` ?

**Comment by maximtop** [comment]
It was working by accident in the v3.6.
Allowlist is intended for domains without wildcards.

**Comment by worldsdream** [comment]
That explains...
I added the domains and subdomains without wilcards.
