### ISSUE TITLE
yandex.ru - issues with AdGuard for Firefox

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/AdguardBrowserExtension#2019]
https://github.com/AdguardTeam/AdguardFilters/issues/113066#issuecomment-1076212343
https://github.com/AdguardTeam/AdguardFilters/issues/113066#issuecomment-1076265530
It looks like that only AdGuard for Firefox has these issues.

**Comment by maximtop** [comment]
Page crashes if AdGuard Tracking Protection filter and AdGuard Russian filter are enabled
Marking this rules as bad `||yandex.*/clck/` solves problem `||yandex.*/clck/$badfilter`
We need to investigate further in order to find reasons of the crashes

**Comment by zloyden** [comment]
@maximtop I can't reproduce it on my end for now. Reverted that rule.

**Comment by maximtop** [comment]
Me too, closing this issue. Feel free to open again if issue occurs again
