### ISSUE TITLE
Port Adguard extension to MS Edge

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#202]
They've just announced this feature:
https://blogs.windows.com/msedgedev/2016/03/17/preview-extensions/
https://dev.windows.com/en-us/microsoft-edge/extensions/

Not much information available about extensions yet, they plan to reveal more on Build conference.
Anyway, we should port AG as soon as possible.

**Comment by Bohdan-SUP** [comment]
Any updates on this?

**Comment by ameshkov** [comment]
Not that fast.

**Comment by BooBerry** [comment]
Okay, any update on this now since it's mentioned in the 2.3.5 beta release notes that it's been ported to Edge?

**Comment by ameshkov** [comment]
Not ported, we've just done some preparations for that.

**Comment by ameshkov** [comment]
@BooBerry and now it's done:)

**Comment by ameshkov** [comment]
**Known issues:**

1. Integration mode is not working as it is not possible to override Referer header for requests sent by us webrequest listeners won't work for any request sent from a privileged context even privileged context is our own extension.
2. Filters stats won't be collected even if user turns "send ad stats usage" on. The problem again is with webrequest, it can't listen to "ms-browser-extension" urls.
3. "Export" function crashes Edge
