### ISSUE TITLE
Журнал фильтрации не запоминает позицию.

### ISSUE THREAD

**Issue by Vitalik93** [AdguardTeam/AdguardBrowserExtension#2023]
В последней версии расширения (4.0.141) журнал фильтрации при открытии сдвинут ближе к правому верхнему углу браузера. Сдвигаю его ближе к середине, но после повторного открытия он опять оказывается на первоначальной позиции. Было бы неплохо если журнал запоминал позицию и открывался каждый раз на том же месте.

![Снимок экрана 2022-03-24 145455](https://user-images.githubusercontent.com/34383288/159922980-821ed84c-1591-40d7-a7eb-a73e38123d11.png)

**Comment by Alex-302** [comment]
Уже есть задача про это https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1655

С позицией и размером может помочь прога PowerToys(FancyZones). С зажатой клавишей можно перетягивать в заранее созданную зону экрана, и прога сама растянет окно до нужного размера в определённой зоне экрана.

**Comment by Vitalik93** [comment]
> Уже есть задача про это #1655
> 
> С позицией и размером может помочь прога PowerToys(FancyZones). С зажатой клавишей можно перетягивать в заранее созданную зону экрана, и прога сама растянет окно до нужного размера в определённой зоне экрана.

Хорошо что задача уже есть. Вообще сразу бы сделали, чтоб по середине открывался, в 3.6 по крайней мере так было. Сторонними прогами не хочу пользоваться, спасибо.

**Comment by Alex-302** [comment]
Оригинальной задаче почти 4 года https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1125 Проще стороннюю утилиту от MS установить) Ну или лог не закрывать) Это не самая приоритетная функция.
