### ISSUE TITLE
Some filtering log tabs are cut in Russian

### ISSUE THREAD

**Issue by Birbber** [AdguardTeam/AdguardBrowserExtension#2025]
### Issue Details

- **AdGuard version:**
  4.0.141

### Expected Behavior

All filtering log tabs should be displayed: https://uploads.adguard.com/annrgy_x96jp.png

### Actual Behavior

Filtering log is cut and some tabs aren't displayed: https://uploads.adguard.com/annrgy_filtering_log.png

**Comment by maximtop** [comment]
For all languages we open filtering log in the same size. It is by design that some buttons do not fit in it. When we implement feature to remember filtering log size this problem disappear.

**Comment by Vitalik93** [comment]
> For all languages we open filtering log in the same size. It is by design that some buttons do not fit in it. When we implement feature to remember filtering log size this problem disappear.

Хотя бы ориентировочно, в какой версии планируется исправить? Подобный запрос [создавался](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1655) еще в 20 году и до сих пор не реализован.

**Comment by maximtop** [comment]
Вот уже скоро, код в мастере уже
https://github.com/AdguardTeam/AdguardBrowserExtension/commit/ff5e238fcf5032fdac035bb2f5609164db206636
