### ISSUE TITLE
Can't see the text in Namu.wiki

### ISSUE THREAD

**Issue by KorCJunseo** [AdguardTeam/AdguardBrowserExtension#2026]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [V] I am running the latest version
- [V] I checked the documentation and found no answer
- [V] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 
- **Browser and version:**
  - 
- **Operating system and version:**
  - 
- **Filters you use in AdGuard:**
  - 
- **Stealth Mode settings:**
  - 
- **Other browser extensions:**
  - 

### ![image](https://user-images.githubusercontent.com/102404795/160228491-fe318833-2929-460e-b699-189e4fa7bbf7.png)
It is in korean only but it supposed to look like that normally: 
![image](https://user-images.githubusercontent.com/102404795/160228548-1d88455a-ec69-4ca7-bcee-f0facb0dd1e1.png)

**Comment by gork7777** [comment]
It's probably related to filter issue, please report the site on the AdGuard extension from report an issue button.

**Comment by Birbber** [comment]
Issue moved to [AdguardTeam/AdguardFilters #113981](https://github.com/AdguardTeam/AdguardFilters/issues/113981) via [**ZenHub**](https://www.zenhub.com/)
