### ISSUE TITLE
Adblocker Requested Feature - Synchronisation

### ISSUE THREAD

**Issue by BrokenShoeLace** [AdguardTeam/AdguardBrowserExtension#2028]
Please add a synchronise option like Firefox has to share rules between connected devices.

**Comment by Birbber** [comment]
@BrokenShoeLace Hi! We already have issues connected to this one: [#1790](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1790) and [#1786](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1786). I will close this one as a duplicate.
