### ISSUE TITLE
v4 major problems

### ISSUE THREAD

**Issue by gt-nik** [AdguardTeam/AdguardBrowserExtension#2030]
Version: 4.0.141 extension
Windows: 10 Pro
Firefox: 98.0.2

When Firefox run for the 1st time after the new version has auto-intalled,
--- a configuration page open asking for settings
--- all settings lost (White list, user rules, enabled filters, settings)
 
i setup everything from the beginning, but when i restart Firefox everything lost again.
 
i uninstall the extension, restart Firefox and install it again and i setup everything from the beginning.
--- It now blocks pictures, videoplayers, pages like CNN and my bank web banking.
 
i go back to version 3.6.17 (from my local HDD backup) and disable extension auto-update
--- ALL WORKING GOOD AGAIN
  
Best Regards

**Comment by maximtop** [comment]
Thank you for opening the issue. Could you please export and share your settings from 3.6.17 with us? We will try to reproduce the issue.

Also, extension logs produced during the update can help us to fix the issue. Here is the instruction on how to view logs https://maximtop.notion.site/How-to-find-an-extension-logs-in-the-Firefox-682216c6dea54b6a9832edf924b07d3b.

This information you can send to the devteam@adguard.com

**Comment by ameshkov** [comment]
> i uninstall the extension, restart Firefox and install it again and i setup everything from the beginning.

Could you configure it as usual and export settings?

**Comment by ameshkov** [comment]
Hmm, cannot reproduce it with your settings.

> It now blocks pictures, videoplayers, pages like CNN and my bank web banking.

How does this look like?

**Comment by gt-nik** [comment]
Hi,

1.  in google search and CNN pages, there were no pictures/videos - only text and placeholders of pictures/videos were shown.
2. in 3 movie pages like https://fevgatotv.com/do-you-do-you-saint-tropez-2021/ a) only movie's placeholder shown, b) youtube trailer popup appeared but trailer not started c) "watch movie on Hdvid.tv server" button goes to an empty page (no text no placeholders).
3. trying to login to my bank's internet banking, when i submit username/password it redirects to an "error try later" page and an alert notification received by my mobile phone says that someone is trying to logging to my account and he blocked successfully.
- all of the above NOT happen using my mobile phone's Kiwi Browser (even if i choose to show me the desktop-pc pages and not the mobile ones) at the same time and using the same wifi connection.
- when i restore my saved/backup v3.6.17 to Firefox, all worked good again.
 
Thanks

**Comment by ameshkov** [comment]
Quick question - is it a desktop Firefox or a mobile Firefox?

**Comment by gt-nik** [comment]
i just sent you by email settings and logs of version 4.0.161 that seems to working OK now.

**Please not that now i am running Firefox 99.0**

Best Regards

**Comment by vozersky** [comment]
Great, thanks
