### ISSUE TITLE
Not show correct display and bad performance in Vivaldi browser

### ISSUE THREAD

**Issue by lagun** [AdguardTeam/AdguardBrowserExtension#2033]
Not show correct display for vivaldi and and bad performance.  sometime i got browser freeze cause form adguard extension. i use latest version.  improve performance adguard extension for vivaldi please.
![thumbnail](https://user-images.githubusercontent.com/11750056/161148659-574e83af-5b0d-48da-a98c-f605eed44ecd.jpeg)
i use adguard latest version.

**Comment by Birbber** [comment]
@lagun Hi! Could you give us more information on how to installed the extension, other extensions you use and the browser's version?
When I install it from Chrome extensions store there's nothing wrong with the extension.

**Comment by maximtop** [comment]
There is a bug in Vivaldi when the browser doesn't close instances of the popup.
<img width="698" alt="image" src="https://user-images.githubusercontent.com/17272769/161711430-7af859d3-beb7-4116-809d-f98563888e38.png">
Seems that performance issues can be related to it. We have reported to them this problem, but they do not have an open bug tracker. And they sent only the number of the issue via email (VB-86801). 

Try to turn off/turn on the extension. Can performance issues still be observed?

**Comment by lagun** [comment]
it's fixed now.  Thank adguard team.
