### ISSUE TITLE
Settings always open in new window tab

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdguardBrowserExtension#2034]
I'm using V4.0.159. Apart from the first window, I opened the second and third windows. When I open the settings in the first and second windows, settings opens in the third window. So it opens in the recent window. I resized the tab in the first window to the new window size. When I opened the settings in the first window, the settings opened in the window I resized. The settings need to be opened in the window we are in like on the VPN extension.

First window: YouTube
Second window: AG Adblocker
Third window: AG DNS

https://user-images.githubusercontent.com/35523759/161396673-081bb124-dc0d-47db-9a06-981b5f49de60.mp4

https://user-images.githubusercontent.com/35523759/161396658-70a94c80-4f16-4145-a0b0-335950785480.mp4

**Comment by maximtop** [comment]
It may be related to this chrome bug https://bugs.chromium.org/p/chromium/issues/detail?id=1305284
I wasn't able to reproduce on my side.
Which version of chrome browser do you have? 
Can the issue be reproduced after browser restart?

**Comment by gork7777** [comment]
@maximtop I'm using V100.0.4896.60 chrome. And issue can be reproduce after restart.

**Comment by maximtop** [comment]
I've tested on 100.0.4896.60 too.
Can we organize with you an anydesk session, for the possibility to debug on your computer? Write me in telegram maximtop, or email maximtop@gmail.com

**Comment by Birbber** [comment]
@maximtop @gork7777 Did you manage to organize the session?

**Comment by maximtop** [comment]
Yeah, we did. It seems like a chrome bug when chrome browser api doesn't return the correct window id for the last focused window.
We can close this issue for now.
