### ISSUE TITLE
In some case `$replace` rule breaks video player

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/AdguardBrowserExtension#2038]
### Issue Details

- **AdGuard version:**
  -  4.0.161
- **Browser and version:**
  -  Firefox 99

### Steps to reproduce
1. Add this rule:
```
/playback/v3/videoPlaybackInfo$replace=/("vendorAttributes" : {)[\s\S]*?}\,[\s\S]*?("streaming")/\$1}}\,\n\$2/,domain=go.discovery.com|discoveryplus.com|go.tlc.com|watch.hgtv.com|investigationdiscovery.com|sciencechannel.com
```
2. Go to -  [https://go.discovery.com/video/alaska-the-last-frontier-discovery/a-whole-new-frontier](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://go.discovery.com/video/alaska-the-last-frontier-discovery/a-whole-new-frontier)
US IP needed.

### Expected Behavior
Video player should works fine.

### Actual Behavior
Video player is broken.
It seems that it's due to `\n` in `$replace` rule.

### Screenshots
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29142494/162000889-6d44a35d-5944-4073-9f52-0058c709f93a.png)

</details>

**Comment by Birbber** [comment]
@AdamWr I wasn't able to reproduce it.

**Comment by AdamWr** [comment]
I still can reproduce it, if I add mentioned rule to user rules.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/164228506-229a374e-e19b-4f7e-805c-c7fa1755454b.png)

</details>

If rule is not added (or if `\n` is removed from the rule), then video works fine.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/164228766-6724aa02-e459-402f-a382-261db3f87bf6.png)

</details>
