### ISSUE TITLE
YouTube missing last video, only an empty space there

### ISSUE THREAD

**Issue by vmv** [AdguardTeam/AdguardBrowserExtension#2040]
![Screenshot_1](https://user-images.githubusercontent.com/17906882/162563470-a02a0208-64cc-4ec5-8b43-084f40a2a685.png)

**Comment by gork7777** [comment]
Working as intended I guess for blocked ad.

**Comment by vmv** [comment]
Yeah, but other ad blockers don't do that. the space is filled with another video from the next line. So, i guess, there is something there that doesn't allow a new element to take that place

**Comment by maximtop** [comment]
Youtube places a specified number of videos in a row. Without reworking markup, it is impossible to replace empty space with another video. I've checked ublock origin and it hides the ad on the upper row the same way and the empty space remains. 

<img width="1723" alt="image" src="https://user-images.githubusercontent.com/17272769/162715247-f327cdef-191f-487f-8ade-b6be7ead6afd.png">
