### ISSUE TITLE
High memory consumption

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#2041]
@adguard-bot commented on [Thu Apr 07 2022](https://github.com/AdguardTeam/AdguardFilters/issues/114871)

### Issue URL (Incorrect Blocking)
 [https://ac.qq.com/ComicView/index/id/649617/cid/875?fromPrev=1](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fac.qq.com%2FComicView%2Findex%2Fid%2F649617%2Fcid%2F875%3FfromPrev%3D1)
### Comment
Username: @ZouloveGhack
> if i open 43 manga website my ram will max to use my computer so lag if i do that pls fix it i try in google and edge 2021 year i have this problem and this again I love this adguard but sometime there give me a max ram use that so... 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/b5GXNN4.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/nGTCM4m.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v4.0.141
Browser: | Chrome
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters, <br>Self-destructing third-party cookies (2880), <br>Block WebRTC, <br>Hide your Referrer from third-parties
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>AdGuard Mobile Ads, <br/>EasyList, <br/>Peter Lowe's Blocklist<br/><br/><b>Privacy:</b><br/>AdGuard URL Tracking, <br/>AdGuard Tracking Protection, <br/>EasyPrivacy, <br/>Legitimate URL Shortener, <br/>Fanboy's Enhanced Tracking List, <br/>Fanboy's Anti-Facebook List, <br/>Fanboy's Anti-thirdparty Fonts<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media, <br/>Fanboy's Social Blocking List<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances, <br/>Fanboy's Annoyances, <br/>Web Annoyances Ultralist, <br/>Adblock Warning Removal List, <br/>I don't care about cookies, <br/>EasyList Cookie List, <br/>Dandelion Sprout's Annoyances List<br/><br/><b>Security:</b><br/>Online Malicious URL Blocklist, <br/>NoCoin Filter List<br/><br/><b>Other:</b><br/>AdGuard DNS<br/><br/><b>Language-specific:</b><br/>AdGuard Russian, <br/>AdGuard Chinese
Other extensions used: | IDM

---

@Alex-302 commented on [Fri Apr 08 2022](https://github.com/AdguardTeam/AdguardFilters/issues/114871#issuecomment-1092802189)

Try to check without third-party filters. Memory consumption is regular on my end.

---

@ZouloveGhack commented on [Sat Apr 09 2022](https://github.com/AdguardTeam/AdguardFilters/issues/114871#issuecomment-1093513301)

@Alex-302 this is my AdGuard save file `https://drive.google.com/file/d/1Ni0EAsOAajF_Iv0r8OoXxL7qRHMWJoxk/view?usp=sharing` i use is edge and google chrome same use ram full no third-party filters

---

@ZouloveGhack commented on [Sat Apr 09 2022](https://github.com/AdguardTeam/AdguardFilters/issues/114871#issuecomment-1093519745)

![无标题](https://user-images.githubusercontent.com/28489226/162549138-9cb83f54-1d64-474f-a19a-5b6fac973480.png)

---

@ZouloveGhack commented on [Sat Apr 09 2022](https://github.com/AdguardTeam/AdguardFilters/issues/114871#issuecomment-1093520503)

i can open 90 website if i no open adguad

**Comment by Alex-302** [comment]
@ZouloveGhack

**Comment by Vitalik93** [comment]
4 версия действительно стала тяжелее. У себя в Edge заметил повышение потребления памяти в среднем на 20 000 КБ.
