### ISSUE TITLE
Please Restore / Reimplement 3.6 Allow List functionality for subdomains via Wildcard in Text file

### ISSUE THREAD

**Issue by Doug-inMD** [AdguardTeam/AdguardBrowserExtension#2045]
### Problem Description

Since the 4.x release - my Allowlist.txt that had several internal company and Microsoft / 365 domains no longer work at all (only www).

I would rather have a few domains INCLUSIVE of all sub-domains and the wildcard (*) did exactly that.

A sample of sites below:  I have / had about 30 entries (That would grow to 100+ if this issue is not reverted).

192.168.123.*
*.autodesk.com
*.autodesk.eu
*.microsoft.com
*.office.com
*.netflix.com

The current allow list under 4.x no longer works - unless I want 15+ subdomains added for each single wildcard entry previously.  4.x way is tedious, inefficient and unnecessary.

The old 3.6 way also allowed for IP address wildcard so other devices (Copiers - Firewalls - LAN Switches - Routers) wouldn't have to be added individually.

The allow list text file was a great way to 'set and forget' for all the browsers I need to use.

### Proposed Solution

Please reconsider re-implementation of the 3.6 wildcard functionality.  This function worked in Chrome, Edge and Firefox perfectly.

### Alternatives Considered

I do NOT want to have to implement a 'rules' approach which is also more tedious than the previous allow list text file in 3.6 version.

### Additional Information

I have seen a few Developer responses that the wildcard functionality in the 3.6 release was unintended but it is much more functional than the 'corrected' 4.x approach.

**Comment by maximtop** [comment]
Thank you for creating the issue. But we already have one about wildcards https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2020
