### ISSUE TITLE
Generic cosmetic filter is not logged

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AdguardBrowserExtension#2047]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

On `www.automoto.it` a generic cosmetic rule `###iubenda-cs-banner` in Annoyances is applied but not logged at all (before https://github.com/AdguardTeam/AdguardFilters/commit/eea89d9f0a54b66b932574e6196bd42365a9872a).

- **AdGuard version:**
  - 4.0.163
- **Browser and version:**
  - Brave 1.37.116
- **Operating system and version:**
  - Windows 10
- **Filters you use in AdGuard:**
  - Base, Annoyances
- **Stealth Mode settings:**
  - Disabled
- **Other browser extensions:**
  - Nothing

### Expected Behavior

Generic cosmetic rule applied is logged.

### Actual Behavior

Not

### Screenshots

<details><summary>Screenshot:</summary>

![log](https://user-images.githubusercontent.com/58900598/163698639-211b091b-21a3-452a-ac9a-115455c0e768.png)

</details>

**Comment by maximtop** [comment]
Thank you, we'll take a look.

**Comment by stanislav-atr** [comment]
@Yuki2718, i wasn't be able to reproduce this behavior on automoto and some random websites, could you please provide another case?

**Comment by stanislav-atr** [comment]
@Yuki2718, i wasn't able to reproduce this behavior on automoto.it and some random websites, could you please provide another case?

**Comment by Yuki2718** [comment]
@stanislav-atr It's logged if added to User rules. How about `www.ilmessaggero.it`? (the same rule)

**Comment by stanislav-atr** [comment]
Reproduced it on `cioccolatonippon.it`

**Comment by Yuki2718** [comment]
@stanislav-atr That's not the point. Okay here's how to reproduce now:
1. Add `https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/AnnoyancesFilter/sections/cookies_general.txt` and `https://github.com/AdguardTeam/AdguardFilters/blob/master/AnnoyancesFilter/sections/cookies_specific.txt` to Custom.
2. Visit `www.automoto.it` with the logger opened.
3. Check that `#iubenda-cs-banner` 's css property is set to display: none by user style sheet yet the rule is not logged:
<details>
<summary>Screenshot</summary>

![logs](https://user-images.githubusercontent.com/58900598/164278414-9abf17fc-6e2e-47e7-a66d-f6b295429e96.png)

</details>

**Comment by stanislav-atr** [comment]
@Yuki2718 with iubenda script enabled
```
automoto.it#@%#AG_onLoad(function(){if(-1==document.cookie.indexOf("euconsent-v2")){var a=new MutationObserver(function(){var b=!1,c=document.querySelector("button.iubenda-cs-close-btn");c&&(c.click(),b=!0);null===document.querySelector("button.iubenda-cs-close-btn")&&b&&a.disconnect()});a.observe(document,{childList:!0,subtree:!0,attributes:!0});setTimeout(function(){a.disconnect()},1E4)}});`

@@||iubenda.com^$script,xmlhttprequest,domain=automoto.it
```
 and filters sections you specified used as custom
(working sections urls)
```
https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/AnnoyancesFilter/Cookies/sections/cookies_general.txt
https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/AnnoyancesFilter/Cookies/sections/cookies_specific.txt
```

i still see that element blocked and generic rule being logged in filtering log

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/68852737/182837677-0033912d-7821-4bad-ad9a-e04cc36d23fb.png)
</details><br/>

as i recall `display: flex !important` shouldn't be the reason for blocknig rule not to apply

**Comment by Yuki2718** [comment]
Yes, I now see the rule is logged. Don't know what was happenning at the time.
