### ISSUE TITLE
Error updating filters with AG Browser Extension v4.0.163

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardBrowserExtension#2048]
It always shows the error updating filters with AG Browser Extension v4.0.163 when trying updating filters in general webpages.
And then it'll show "No updates found" when clicking "check updates" in the settings of AG Browser Extension.

**Comment by maximtop** [comment]
Are there any errors during the update on the background page?

**Comment by lancelot-moon** [comment]
> Are there any errors during the update on the background page?

Error updating filters

**Comment by maximtop** [comment]
Open developer tools for the extension in chrome:
![image](https://user-images.githubusercontent.com/17272769/163751827-edd603ae-90f9-440f-996a-40555a786668.png)
Open network tab:
![image](https://user-images.githubusercontent.com/17272769/163751931-553f80ba-cbf0-4cd5-b053-9c0a50c1b751.png)
Press the button to update filters
Send us errors of requests, which happen during filters update.

**Comment by lancelot-moon** [comment]
Today, filters can be updated.
Weird.

**Comment by lancelot-moon** [comment]
@maximtop Can't update filters again.

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/HMGzBUk.png)
</details><br/>

**Comment by maximtop** [comment]
@lancelot-moon I do not see any errors in the network.
Maybe there are no updates for filters? What logs say in the console tab? 
How do you determine that filters are not updated?

**Comment by lancelot-moon** [comment]
@maximtop 

> How do you determine that filters are not updated?

Don't forget it'll show Error updating filters on the screen of a webpage.
Almost passed 6 days after 18th April, 2022.. No filters updates during the period?
Please answer me the latest update date of AG Base filter.
My AG Base filter version: v2.2.26.47, 18th April, 2022

**Comment by maximtop** [comment]
I've written you in telegram.
