### ISSUE TITLE
`$match-case` modifier doesn't work correctly

### ISSUE THREAD

**Issue by tumatanquang** [AdguardTeam/AdguardBrowserExtension#2049]
### Issue Details

- **AdGuard version:** v4.0.133
- **Browser and version:** Chrome 93

### Expected Behavior

The rule has a `$match-case` modifier will case-sensitive.

### Actual Behavior

It's still case-insensitive.

### Additional Information
I wrote a filter rule like this: `/config.js$match-case`
It blocked the entire link containing `/config.js` as I expected.
But it also blocks the link: **/Config.js**, **/ConfiG.js**, **/CONFIG.js**
That is, it blocks the entire link containing `/config.js` without case-sensitive.

**Comment by maximtop** [comment]
Thank you, we'll take a look.
