### ISSUE TITLE
CCLeaner breaks chrome extension

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#205]
We should reproduce this issue and then look what's wrong in the background page console (just in case)

**Comment by bkrcrc** [comment]
Priform Support Team replied my e-mail about the problem, they are on it.

_Hi,

Thanks for bringing this to our attention. We're currently investigating this issue and working towards getting it resolved but in the meantime, you should be able to avoid this problem by excluding the Adguard file - using these steps:

1 - Open CCleaner > click Options > Exclude
2 - Click Add > File > Browse
3 - Navigate to: C:\Users\%USER%\AppData\Local\Google\Chrome\User Data\Default\Local Storage\
4 - Click on the "https_adguard.com_0.localstorage-journal" file > click Open > OK.

However, if this doesn't fix the problem, please let me know and I will be happy to help.
Regards,
	
Megan Sparks (Piriform Support)_

**Comment by bkrcrc** [comment]
When will you release a new version? It is too annoying.

**Comment by gshumihin** [comment]
Adding C:\Users\%USERNAME%\AppData\Local\Google\Chrome\User Data\Default\Local Storage\chrome-extension_bgnkhhnnamicmpeenaelnjfhikgbkllg_0.localstorage-journal solved problem

**Comment by gshumihin** [comment]
All i see in console is rules count: 0

**Comment by ameshkov** [comment]
> When will you release a new version? It is too annoying.

I really hope they will fix it on CCLeaner side.

**Comment by bkrcrc** [comment]
@ameshkov then it will be annoying some time. Because CCleaner releases their fixes for monthly. I hope they won't postpone the fix of this.

So it is not in our hands. Anyway, thanks.

**Comment by BooBerry** [comment]
Does it break the Opera extension too?

**Comment by bkrcrc** [comment]
Hi @BooBerry , yes it also broke my Opera Adguard extension.
You can check the issue #206 , is closed and merged with this topic.
Firefox is OK. But chromium based browsers which has cleaning support of CCleaner are broken.

**Comment by Alex-302** [comment]
Wise Care also breaks extension
http://forum.adguard.com/showthread.php?10073-Yahoo-Mail&p=81252&viewfull=1#post81252

**Comment by ameshkov** [comment]
@Mizzick let's speed up work on this issue and prepare a patch, this seems to be critical.

**Comment by bkrcrc** [comment]
Forum will be full of missed ad reports because of this problem, lets see! It is so annoying

**Comment by vbagirov** [comment]
Issue was linked from this forum thread: http://forum.adguard.com/showthread.php?10079

**Comment by Mizzick** [comment]
Fixed with https://github.com/AdguardTeam/AdguardBrowserExtension/releases/tag/v2.2.4-dev

**Comment by bkrcrc** [comment]
Sounds good! Can someone give me the .crx file? I am not good at coding or compiling.

**Comment by ameshkov** [comment]
Should be already available in the Chrome WebStore.

**Comment by ameshkov** [comment]
Ah, forgot to publish release here:
https://github.com/AdguardTeam/AdguardBrowserExtension/releases/tag/v2.2.4

**Comment by bkrcrc** [comment]
Thanks @ameshkov I will test for the Opera.

**Comment by bkrcrc** [comment]
hi @ameshkov & @Mizzick , the problem is still here, I repeat, the problem is still here!
I am using Opera with version 2.2.4.
Please re-open this thread. Thanks

**Comment by ameshkov** [comment]
Argh, that's bad.

Could you please show what you see on the extension background page console?

To do it:
1. Open chrome://extensions page
2. Turn developer mode on
3. Find Adguard extension and click chrome_background.html there
4. Switch to "Console" tab
5. Copy/paste everything from there

**Comment by ameshkov** [comment]
Just checked Opera with CCLeaner and it seems to be fixed.

The only issue left is that CCLeaner still removes everything from the user filter.

**Comment by bkrcrc** [comment]
@ameshkov , yes indeed.
Please see the screenshot: http://i.hizliresim.com/pzkXRL.png
It seems problem solved on your side ;) If user used CCleaner, then he/she needs to update the filters before surfing. As you can see in the screenshot. After that everything work.

**Comment by ameshkov** [comment]
Hm, filters update should have started automatically.

It's just how it works:
1. If AG filters are empty we reset version to 0.0.0.0 and start autoupdate immediately.
2. After that AG works as it should.

This is of course a temporary solution. It should anyway be fixed on CCLeaner side too.
