### ISSUE TITLE
Bug in `Preserve Log` button

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardBrowserExtension#2052]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:** 4.0.163
  
- **Browser and version:** Chrome 100
- **Operating system and version:** Win10 21H2
- **Filters you use in AdGuard:** AG Base, AG Social, AG Annoyances, AG Tracking Protection, AG URL, AG Turkish
  
- **Stealth Mode settings:**  Send Do-Not-Track header, Strip URLs from tracking parameters

  

### Additional Information

Clicking the active 'Preserve Log' icon will not react, but clicking it again will deactivate the button. To turn off the 'Preserve Log' button, it is always necessary to click twice.

This is not a temporary problem. This happens all the time. I am able to reproduce this problem every time. So it looks like AdGuard bug.

Gif:
https://ibb.co/j4DnTyj

### Steps to reproduce:

- Go to any website and open the filtering log and click the `Preserve log` button.
- Close the filtering log window
- Open filtering log again and test it by clicking the `Preserve log` button.

**Comment by maximtop** [comment]
Thank you. We'll take a look.
