### ISSUE TITLE
Область наведения кнопок.

### ISSUE THREAD

**Issue by Vitalik93** [AdguardTeam/AdguardBrowserExtension#2054]
Область наведения кнопок "приостановить защиту" и "настройки" квадратная, хотя сами кнопки круглые. Может стоит ее тоже сделать круглой? Смотрелось бы по моему лучше, тем более что  круглая кнопка "переключение защиты" как раз имеет круглую область наведения. Версия расширения - 4.0.163.

![Снимок экрана 2022-04-21 202846](https://user-images.githubusercontent.com/34383288/164887494-396a2eda-7731-4607-9f14-2e742f0d0923.png)
![Снимок экрана 2022-04-21 202921](https://user-images.githubusercontent.com/34383288/164887498-41edf225-59e2-4176-98bf-a8d424eec553.png)

**Comment by maximtop** [comment]
Спасибо, за созданную задачу, но это сделано по дизайну, мы не будем это фиксить.
