### ISSUE TITLE
Interface shows English instead of local language

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardBrowserExtension#2055]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:** 4.0.163
- **Browser and version:** Chrome 100
- **Operating system and version:** Win10 21H2
- **Filters you use in AdGuard:** AG Base, AG Social, AG Annoyances, AG Tracking Protection, AG URL, AG Turkish
  
- **Stealth Mode settings:**  Send Do-Not-Track header, Strip URLs from tracking parameters

### Additional Information

The problem seems to be related to the user filter section. I can reproduce this issue if I delete a rule from the user filter and then update the filters.

This is not a temporary issue, I can often reproduce this issue.

### Gif:
https://ibb.co/Y87vdNC

### Steps to reproduce:

- Block any script using the filtering log.
- Close the window and go to your user filter.
- Delete the last rule you blocked and then update the filters.
- The interface language is shown in English, refreshing the page solves the problem.

**Comment by maximtop** [comment]
I wasn't able to reproduce it. Could you please send more info?
Go to the background page, switch to the network tab press the update filters button, and send a screenshot like the below one with the information I pointed with arrows.
![image](https://user-images.githubusercontent.com/17272769/165041008-b9a7bfb4-e472-4300-8cea-e72c8aa3c934.png)

**Comment by dcxstq2** [comment]
@maximtop 

Please check:

<details>
 <summary>1</summary>
 
![111](https://user-images.githubusercontent.com/104112959/165058119-e24901d1-02c4-41b9-aa5f-85879ddfd2b3.png)


</details>

<details>
 <summary>2</summary>
 
![222](https://user-images.githubusercontent.com/104112959/165058188-d34b68fa-cdf7-4488-bb07-f65fee91a395.png)



</details>

<details>
 <summary>3</summary>
 
![333](https://user-images.githubusercontent.com/104112959/165058252-d99a0620-d935-4cb9-9415-d7b8d4390f38.png)


</details>


<details>
 <summary>4</summary>
 
![4444](https://user-images.githubusercontent.com/104112959/165058311-b173dd47-afdf-4df8-bfba-489565fd5c13.png)


</details>

(Screenshots were copied after the problem was reproduced.)

**Comment by maximtop** [comment]
Thank you. Could you also run in the console of background page
`chrome.i18n.getAcceptLanguages(console.log)`

![Uploading image.png…]()

**Comment by dcxstq2** [comment]
@maximtop 

Please check

<details>
 <summary>Photo</summary>

![cs](https://user-images.githubusercontent.com/104112959/165064044-907fd06e-b22c-4559-a81c-2c97192a28be.png)


</details>

**Comment by maximtop** [comment]
sorry asked you wrong call
try this one please
chrome.i18n.getUILanguage()

**Comment by dcxstq2** [comment]
@maximtop 

Here:

<details>
 <summary>Photo</summary>
 
![zxx](https://user-images.githubusercontent.com/104112959/165069024-e91d9b52-8e44-47bd-a0dd-77332326be0a.png)


</details>

**Comment by maximtop** [comment]
I can't detect the issue on my side. Can you connect with me via telegram? My nic there is maximtop.

**Comment by dcxstq2** [comment]
> I can't detect the issue on my side. Can you connect with me via telegram? My nic there is maximtop.

I do not use a smartphone. If you want, you can write to me at `denizakkan@tutanota.com`

---

Maybe some extra information that can help you reproduce:

- Go to custom DNS setting and select Cloudflare DNS. (`chrome://settings/security`)
- Use incognito mode

**Comment by maximtop** [comment]
@Birbber yes, the issue rarely and randomly is reproduced on the user extension, I'll try to investigate this issue later again.
