### ISSUE TITLE
Wildcarded scriptlet rule does not appeared in Filtering log

### ISSUE THREAD

**Issue by piquark6046** [AdguardTeam/AdguardBrowserExtension#2057]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 4.0.161
- **Browser and version:**
  - Mozilla Firefox Dev 100.0b9
- **Operating system and version:**
  - Ubuntu 21.10
- **Filters you use in AdGuard:**
  - List-KR, AdGuard TPF, AdGuard URL, AdGuard Social and AdGuard Annoyances 
- **Stealth Mode settings:**
  - Disabled
- **Other browser extensions:**
  - KeePassXC

### Expected Behavior

`#%#//scriptlet("set-constant", "adScriptInitialized", "true")` is logged in filtering log of AdGuard Browser Extension.

### Actual Behavior

`#%#//scriptlet("set-constant", "adScriptInitialized", "true")` is **NOT** logged in filtering log of AdGuard Browser Extension.
However, `naver.com#%#//scriptlet("set-constant", "adScriptInitialized", "true")` is logged.

### Screenshots

<details><summary>Screenshots:</summary>

![Screenshot](https://user-images.githubusercontent.com/98787049/165279559-69dd72e4-c8de-49b4-8d89-8d5a00c9da9e.png)
![Screenshot2](https://user-images.githubusercontent.com/98787049/165279600-a193724e-9d21-4b01-89de-750648bb1c68.png)

</details>

### Additional Information

Before debugging it, please disable List-KR.
https://github.com/List-KR/List-KR/commit/2a7f2d93b7db42d713f9bc6c9d80a539817d0255

**Comment by maximtop** [comment]
It's made by design. We do not want to print in the filtering log all events, which could fire from multiple iframes from the page.
