### ISSUE TITLE
Adguard Can't Filter on Opera

### ISSUE THREAD

**Issue by bkrcrc** [AdguardTeam/AdguardBrowserExtension#206]
My system: Windows 7 SP1 64bit Fully updated - Opera stable browser - Adguard extension - Latspass - HTTPS Everywhere

Problem: 
1 - I installed Adguard extension and updated filters manually. 
2 - It worked at first install
3 - Restart Opera, (maybe I ran CCleaner)
4 - Start Opera and go to any site wih ads.. Adguard doesn't filter.

I have no problem with my other browsers but Opera. Can you please check, thanks.

**Comment by ameshkov** [comment]
The problem is in CCLeaner, it's latest version breaks AG: #205

**Comment by bkrcrc** [comment]
Hi ameshkov,

Also Wise Disk Cleaner or Wise Care 365 are braking the Adguard extension. Reproduce steps..

1 - Install Adguard extension to your browser
2 - Do your customization on Adguard extension (Add new whitelist rules, and add new subscriptions etc.)
3 - Close browser
4 - Go to Wise Disk Cleaner and do common cleaning and advanced cleaning with all areas checked.
5 - Restart your browser
6 - You will realize that Adguard thinks it is just installed and all your settings are gone.

Please check this, too.

**Comment by ameshkov** [comment]
@bkrcrc 
What do they all have against our settings?:)

I've filed a new issue on this, thank you!
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/207

**Comment by bkrcrc** [comment]
Who knows :) 
Adguard saves its settings where they want to clean or delete. You can maybe store Adguard settings on other places. What do you think?
By the way, did you reproduce the issue?

**Comment by ameshkov** [comment]
> Adguard saves its settings where they want to clean or delete. You can maybe store Adguard settings on other places. What do you think?

It is possible of course (yet it will be hard to update existing installations).

> By the way, did you reproduce the issue?

Yeah, it's pretty easy.

**Comment by Bushido1** [comment]
Is there a fix for it? In last Opera developer version, CCleaner still executes the same problem.

**Comment by ameshkov** [comment]
Meh, that's bad. Anyway, in the next update we'll move filters to the
storage so this issue should be resolved automatically.

--
wbr, Andrey Meshkov
skype: aymeshkov
cell: +7 903 534 9643

2016-05-24 18:47 GMT+03:00 Bushido1 <notifications@github.com>:
