### ISSUE TITLE
Ads leak through AdGuard after toggling options and reloading a tab

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardBrowserExtension#2061]
### Issue Details

<details><summary>System configuration</summary>

![ad](https://user-images.githubusercontent.com/104163780/166705006-bce258c2-7659-405e-9851-44a00821ddd7.png)

</details>

### Screenshots

<details><summary>Screencast:</summary>

https://user-images.githubusercontent.com/104163780/166709072-412ed6b8-ddea-48a1-8719-be966a97f54b.mp4

</details>

### Additional Information

When you toggle `Hide Referrer from third parties` (or maybe other options) and then reload a site in another tab, ads leak through the extension.

I've had this happen on different sites, but the example URL is  [https://futebolplayhd.com/assistir-sportv-ao-vivo-hd-24-horas-online-gratis/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Ffutebolplayhd.com%2Fassistir-sportv-ao-vivo-hd-24-horas-online-gratis%2F)

**Comment by lancelot-moon** [comment]
@maximtop @ameshkov @AdamWr 

When I reopened chrome, AG for browser extension v4.0.163 didn't block ad video on YouTube.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/NS3yV7k.jpg)
</details><br/>

**Comment by maximtop** [comment]
Seems like this issue is not reproducible anymore in the v4.2
