### ISSUE TITLE
AdGuard icon missing in browser tab for Firefox

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdguardBrowserExtension#2062]
There's icon for Chrome but there's no icon for Firefox.

Firefox: <details><summary>Screenshot:</summary>![icon](https://user-images.githubusercontent.com/35523759/166941789-99243891-2714-4803-b0b6-6d8157698b11.png)</details>

Chrome: <details><summary>Screenshot:</summary>![İcon](https://user-images.githubusercontent.com/35523759/166942251-57051937-d9cc-4d61-a068-c4bf73ed80e2.png)</details>

**Comment by XX-J** [comment]
Нет иконки на отдельной странице пользовательских правил.
<br>

 AdGuard v4.0.181 - FireFox v78.13 ESR - Win7SP1

**Comment by maximtop** [comment]
> Нет иконки на отдельной странице пользовательских правил.
> 
> AdGuard v4.0.181 - FireFox v78.13 ESR - Win7SP1

Спасибо, там тоже пофиксим
