### ISSUE TITLE
[Bug] AdGuard Cannot Apply Exported Setting File

### ISSUE THREAD

**Issue by bkrucarci** [AdguardTeam/AdguardBrowserExtension#2066]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 4.0.161
- **Browser and version:**
  - Firefox 100
- **Operating system and version:**
  - Windows 10 
- **Filters you use in AdGuard:**
 Exported settings file.
[20220503_234243_adg_ext_settings_4.0.161.zip](https://github.com/AdguardTeam/AdguardBrowserExtension/files/8645815/20220503_234243_adg_ext_settings_4.0.161.zip)

### Expected Behavior

AdGuard should apply all settings in exported settings file.

### Actual Behavior

I had previously exported my AdGuard settings with my Firefox browser. I then imported my settings into the AdGuard add-on, which I installed in another Firefox browser. I waited for the message which say "Settings succesfully imported"
Custom Filters seem added but not enabled generally.
Language Filters were enabled generally but the Turkish filter was not enabled under the hood...

### Screenshots

I always keep Turkish Filter enabled. Please see it in .json settings file.
![Screenshot_1](https://user-images.githubusercontent.com/15933805/167268640-b66d7c52-c0f2-48fd-b30d-2d374a6b7bdf.png)

But those are not enabled in imported settings.
![Screenshot_2](https://user-images.githubusercontent.com/15933805/167268615-b8e10092-8c3e-4c0e-abab-f6c43aea3a30.png)

**Comment by maximtop** [comment]
On my side, the Turkish filter enables as expected with the provided settings file. Maybe there are some errors on the background page?

Custom filters group should be enabled after migration, yes.

**Comment by bkrucarci** [comment]
@maximtop I tested on different browsers. Turkish filter enabled on tests.
But custom filters group did not enable after settings import. For your information

**Comment by maximtop** [comment]
Let's leave this issue closed until won't find out how to reproduce it reliably.
