### ISSUE TITLE
Unable to install a beta version on Chrome

### ISSUE THREAD

**Issue by raed667** [AdguardTeam/AdguardBrowserExtension#2069]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - AdGuard v4.0.163 beta
- **Browser and version:**
  -  Chrome 101
- **Operating system and version:**
  - MacOs 12.3.1
 
### Expected Behavior

Be able to install a beta release on Chrome.

### Actual Behavior

When I try to install a `beta` release on chrome using the provided [chrome-beta.crx](https://github.com/AdguardTeam/AdguardBrowserExtension/releases/download/v4.0.163-beta/chrome-beta.crx) file I get the following error:

  `This extension is not listed in the Chrome Web Store and may have been added without your knowledge.`

### Screenshots

<details><summary>Screenshot:</summary>

<img width="429" alt="image" src="https://user-images.githubusercontent.com/1442690/168044643-17715ee1-345a-4708-9013-e357c7e404e1.png">
</details>

**Comment by maximtop** [comment]
Chrome doesn't allow installing extensions outside of the Chrome Web Store, you can install the beta version from this link https://chrome.google.com/webstore/detail/adguard-adblocker-beta/gfggjaccafhcbfogfkogggoepomehbjl
we keep this file for Opera users.
