### ISSUE TITLE
Wise Disk Cleaner issue with Adguard extension

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#207]
Source report:
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/206#issuecomment-201251855

Seems to be the same issue as with CCLeaner: #205 
We should check what exactly do they delete and why AG cannot restore its settings.

**Comment by Mizzick** [comment]
Fixed with https://github.com/AdguardTeam/AdguardBrowserExtension/releases/tag/v2.2.4-dev
