### ISSUE TITLE
Show vertical scrollbar

### ISSUE THREAD

**Issue by martinezspn** [AdguardTeam/AdguardBrowserExtension#2072]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

Open the filtering log and click maximize button. The scroll bar on the right is not shown.
Swipe the horizontal scrollbar at the bottom to the right to see vertical scrollbar..

Show the vertical scrollbar by default like in the previous (3.6.17) version.

If you think this feature is not necessary, close this report directly.

<details>
 <summary>See here</summary>

![image](https://user-images.githubusercontent.com/105452968/168150079-310ee32c-bf91-42e8-a35f-aa31e18094c6.png)

</details>

System: Chrome (latest)
Windows 10 (latest)

**Comment by maximtop** [comment]
What browser are you using and which os? There is a scrollbar on macOS and chrome. It is not visible when content fits in the window.

**Comment by martinezspn** [comment]
@maximtop I'm using Chrome and yes if I use the filtering log fullscreen the scrollbar also shows up.

**Comment by martinezspn** [comment]
However, as far as I remember, in the previous version the scrollbar was visible by default even if the filtering log was not full screen.

**Comment by maximtop** [comment]
I think it was visible because all columns fit the window. Now they do not fit, scrollbar can be seen if you scroll the horizontal scrollbar to the right.

**Comment by maximtop** [comment]
Closing this as the vertical scrollbar works as expected
