### ISSUE TITLE
can't add user custom rulers in edge extension for Ver 4.0.163 at windows 10 

### ISSUE THREAD

**Issue by FY1043031060** [AdguardTeam/AdguardBrowserExtension#2073]
- **AdGuard version:**
     4.0.163
- **Browser and version:**
    edge 101.0.1210.47 (正式版本) (64 位)
- **Operating system and version:**
    Windows 10
![image](https://user-images.githubusercontent.com/13435836/168409006-7c6b7c54-127e-4b51-82d6-89e584baff0e.png)

**Comment by maximtop** [comment]
Can you record a video of how are you trying to add new rules? Currently, it is not clear what is going wrong.

**Comment by maxikuzmin** [comment]
@FY1043031060 ping

**Comment by maxikuzmin** [comment]
@FY1043031060 is the issue still relevant?
