### ISSUE TITLE
Privacy Permission Broken on Chromium Browser (Edge, Chrome, Opera, etc) when Turning on WebRTC Blocking.

### ISSUE THREAD

**Issue by Nekroz88** [AdguardTeam/AdguardBrowserExtension#2074]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [Yes] I am running the latest version
- [Yes] I checked the documentation and found no answer
- [Yes] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - Adguard Browser Extension (Chromium) version 4.0.163
- **Browser and version:**
  - Edge Chromium Stable 101.0.1210.39
  - Opera GX Lastest Stable Version
- **Operating system and version:**
  - Windows 10
- **Filters you use in AdGuard:**
  - Every filters except "Unblock search ads".
- **Stealth Mode settings:**
  - Enabled.
- **Other browser extensions:**
  - None.

### Expected Behavior

When turning on WebRTC Blocking Button, it is expected that the (chromium) browser will ask the user to grant Adguard "Read and Modify Privacy-related Settings" Permission. And the new permission will be added inside the browser extension settings if the user click "Allow".
This process works normal for Adguard Chromium Extension version 3.6 or below.

### Actual Behavior

Since Adguard Extension got new UI update (from version 4.0), the browser won't grant Adguard privacy-control permission when clicking "Allow" anymore, but "Deny" instead.
Furthermore, after clicking "Allow", the permission won't appear in the browser extension settings, but it will appears only when _turning off WebRTC Blocking_. This leads to the fact that when user needs to block WebRTC (on some sites), Adguard won't works at all, or not working properly as expected like older version (like 3.6.17 for example).

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

This problem only happens when the user add Adguard (version 4.0 or above) to their Chromium browser _for the first time_.
If the users upgrade their extension from lower version of Adguard (like from version 3.6.17) to newer version, the browser will keep the permission that already granted to Adguard before and everything is still fine if doing that.

**Comment by maximtop** [comment]
Thank you for posting this issue. I can confirm it.
