### ISSUE TITLE
Syntax highlighter misses some modifiers

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#2075]
For instance, it misses `$all`:
![image](https://user-images.githubusercontent.com/5947035/168540336-5ed0b10a-7740-4f26-8434-4e64ff08ae6c.png)

We should check other modifiers as well.

**Comment by slavaleleka** [comment]
`denyallow` is not highlighted yet too
https://uploads.adguard.com/slbdzdrvbgitc.png
