### ISSUE TITLE
Blocked CSP report is not displayed in the blocked requests of the filtering log

### ISSUE THREAD

**Issue by Birbber** [AdguardTeam/AdguardBrowserExtension#2081]
### Steps to reproduce
- Open any webpage like yandex.ru
- Scroll for some time
- Open 'Other' tab and wait until a blocked CSP request appears
- Select 'Blocked' in request types  

### Expected Behavior

Blocked CSP report should be displayed in 'Blocked' requests list

### Actual Behavior

Blocked CSP report is not displayed in the blocked requests: https://uploads.adguard.com/annrgy_555tb.mp4

**Comment by slavaleleka** [comment]
the issue cannot be reproduced on v4.2.209
look like it was fixed in [v4.2.168](https://github.com/AdguardTeam/AdguardBrowserExtension/blob/master/CHANGELOG.md#fixed-4) : https://github.com/AdguardTeam/AdguardBrowserExtension/commit/a1a68e10e8a5e1d794b3277df733e05204cd9c9c
