### ISSUE TITLE
instagram.com

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardBrowserExtension#2082]
https://www.instagram.com/p/Cd_cSNJls9g/

Using Edge Browser with AG extension for Edge. No ad/tracking filters applied. Only the "Stealth" mode is applied with the following settings: https://prnt.sc/YZh3D9na8Fym

Still when I reload the page, no videos play on Instagram (logged in). Disabling AG Extension and then reloading the page plays the video. Please fix.

**Comment by Nzzyme** [comment]
Sorry, I have posted under wrong section. Can you please move this to Filters Issues?

**Comment by Birbber** [comment]
Issue moved to [AdguardTeam/AdguardFilters #119930](https://github.com/AdguardTeam/AdguardFilters/issues/119930) via [**ZenHub**](https://www.zenhub.com/)
