### ISSUE TITLE
Check FF add-on compatibility

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#209]
Hello,

There are changes coming to Firefox in the next year that will make browsing more reliable for users, and creating add-ons easier for developers. Your add-on may require updating to maintain its compatibility, but once this is done and the transition is complete, your add-on will be more interoperable, secure, and future-proof than ever.

We've created resources, recommended migration paths, office hours, and more, to ensure you have the support you need to get through the transition.

To get started, head over to our compatibility checker at https://compatibility-lookup.services.mozilla.com to see if your add-on will be affected.

You can also go to https://wiki.mozilla.org/Add-ons/developer/communication to see all the resources available currently. We are continuously adding new information as it becomes available.

Thank you for your participation and support, and we look forward to working with you.

Sincerely,
The Add-ons Team

**Comment by Mizzick** [comment]
> SDK add-on using legacy APIs
We think this is an SDK add-on using legacy APIs. These APIs will be deprecated once WebExtensions become the standard for add-on development.

https://wiki.mozilla.org/Add-ons/developer/communication#2.29_Has_SDK_add-on_using_legacy_APIs

There is an issue already about add-on sdk #151

**Comment by ameshkov** [comment]
@Mizzick read carefully, stopping using add-on SDK will change nothing for us as they plan to remove XPCOM support by the end of 2017 and force all add-on developers to migrate to webextensions.
@atropnikov please read it too.

**Comment by ameshkov** [comment]
I just not sure if we really should get rid of sdk now.
