### ISSUE TITLE
Total blocked: Remove the extra space

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdguardBrowserExtension#2093]
Remove the extra space or put a dot instead of a space if you really want it.
It is best to avoid using the Thousands Separators.
Just please don't put a space or a comma.

<img width="417" alt="Screen Shot 2022-05-28 at 20 22 00" src="https://user-images.githubusercontent.com/62497891/170838341-8271352a-75ca-4c73-bf2c-54a7e92c47e6.png">

Good example:

![Install-Adguard-Adblocker-Extension](https://user-images.githubusercontent.com/62497891/170838508-acced3f0-8388-43a8-9a69-2fb46d58abab.jpg)

Bad example:

![Adguard-AdBlocker-chrome-extension copy](https://user-images.githubusercontent.com/62497891/170838633-333d9d7d-e361-4fe1-be4f-b05ed3de2575.jpg)

**Comment by maximtop** [comment]
We use https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString
It means that the number format depends on your OS setting.
