### ISSUE TITLE
Improve the counter background

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/AdguardBrowserExtension#2097]
### Issue Details

- **AdGuard version:**
4.0.171
- **Browser and version:**
Chrome 102.0.5005.62
- **Operating system and version:**
Windows 11 21H2

### Expected Behavior

The counter background should be more visible

### Actual Behavior

The counter background is barely visible, especially against the background of other extensions from the screenshot

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33488229/170982389-066f31d0-a873-45fe-95ce-edc577cfaf09.png)

</details>

### Additional Information

Noticed it in the dark theme, but it also happens in the light theme. Restarting the browser does not help.

**Comment by maximtop** [comment]
Should be fixed with a new chrome update
https://bugs.chromium.org/p/chromium/issues/detail?id=1329772
https://bugs.chromium.org/p/chromium/issues/detail?id=1321962
