### ISSUE TITLE
German localization: the inscription not in the center of the button in "AdGuard-Erweiterung konfigurieren"

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdguardBrowserExtension#2098]
<img width="847" alt="AdGuard-Erweiterung konfigurieren" src="https://user-images.githubusercontent.com/62497891/171047789-7332f4d3-77cd-433e-a923-b11ef791cbd7.png">

**Comment by Birbber** [comment]
@Oleg-Chashko Hi. It's a known issue. Already working on it, but thanks for noticing!
