### ISSUE TITLE
Midori support

### ISSUE THREAD

**Issue by sysfu** [AdguardTeam/AdguardBrowserExtension#210]
I've recently migrated several computers to Elementary OS which uses the Midori browser as the default.

I like the browser well enough, but it's particularly painful now to browse the web unprotected without the benefit of Adguard or the Adguard browser extension.

Would it be much work to create an extension for Midori? Is there anything I can do as a volunteer to help?

**Comment by ameshkov** [comment]
Isn't it on the default filtered apps list in AG for Windows?

**Comment by ameshkov** [comment]
What for browser extension, it seems Midori just does not provide an SDK for browser extensions.

**Comment by sysfu** [comment]
I believe it is filtered in Windows yes, however I'm running Midori on [Elementary OS,](https://www.elementary.io) an Ubuntu based distro.

https://launchpad.net/midori

**Comment by ameshkov** [comment]
It seems they are trying to integrate popular extensions features into the browser instead of providing a way to develop extensions.

**Comment by gue5t** [comment]
Midori has an extension system based on shared libraries (.dll/.so); Midori ships many of these with the browser and maintains them in the Midori repository to avoid bitrot. Midori extensions have access to a very rich API to manipulate virtually every part of the browser, and they are not sandboxed or considered untrusted; users are not expected to download and install Midori extensions from untrusted parties.

Midori doesn't support the sandboxed, Javascript extension APIs used by Chrome or Firefox, though something along these lines could happen in the future. There *are* plans to integrate libpeas to enable writing Midori extensions in languages like Javascript, Lua and Python, but this still will require trusting the extensions and is not the same as the Firefox or Chrome model. If you need help writing an extension (the documentation is a little sparse), please come to the IRC (#midori on freenode) or submit a bug on Launchpad and someone will help answer specific questions. There's an old but still quite accurate PDF that explains the basics of Midori extension development [here](https://github.com/AdguardTeam/AdguardBrowserExtension/files/211433/midori-extensions-tutorial-0.1.1.1.pdf).

That said, Midori does already have an adblock extension in its upstream repo. Does Adguard do more than simply apply AdblockPlus-style filter lists? Depending on what the difference in functionality is, it might make the most sense to add useful features into the upstream adblock extension in Midori.

**Comment by ameshkov** [comment]
@gue5t thanks for the clarifications! Basically all ad blockers are alike, the difference is in the details.

Could you please point me at adblock implementation in Midori repo?

**Comment by sysfu** [comment]
@ameshkov I think this might be it: https://code.launchpad.net/~midori/midori/adblock-main-frame

**Comment by ameshkov** [comment]
It seems that current implementation has a very limited support even for core ABP syntax.
