### ISSUE TITLE
Filtering log is not launching

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardBrowserExtension#2100]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:** 4.0.171
- **Browser and version:** Chrome 102
- **Operating system and version:** Windows 10 21H2
- **Filters you use in AdGuard:** Base, AG Annoyances, AG Social, AG Tracking protection, AG TrackParam, AG Turkish
- **Stealth Mode settings:** Send Do-Not-Track header, Strip URLs from tracking parameters
- **Other browser extensions:** SimpleTranslate

### Screenshots

<details><summary>Screenshot:</summary>

![resim](https://user-images.githubusercontent.com/104112959/171737458-092567ff-6b28-444d-9803-4c371e5bbf54.png)

</details>

---

Gif:

https://i.imgur.com/USBgDe2.gif

### Additional Information

Issue started after version `4.0.171` I faced the problem twice. Restarting the browser and computer does not help
Reinstalling the extension usually resolves this problem temporarily, but the problem starts again after a few days.

**Comment by maximtop** [comment]
Thank you for filling this issue.
Can you reproduce this issue after changing the filtering log size?

**Comment by dcxstq2** [comment]
> Can you reproduce this issue after changing the filtering log size?

Yes, this issue is reproducible if the filter log size is changed. I am not using the default filtering log size. 
I've customized the filtering log window by expanding it a bit.

<details>
 <summary>Screenshot</summary>

![resim](https://user-images.githubusercontent.com/104112959/171892483-f5676489-f1d9-4b93-8856-dfc4df7ea79a.png)


</details>

**Comment by maximtop** [comment]
Can you record a video of how you are changing the filtering log window size?

**Comment by maximtop** [comment]
Thank you. I was able to reproduce the bug.
