### ISSUE TITLE
Removeparam does not work at mozilla.org

### ISSUE THREAD

**Issue by bkrucarci** [AdguardTeam/AdguardBrowserExtension#2102]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**  
   - 4.0.181
- **Browser and version:** 
   - Mozilla Firefox 101.0
- **Operating system and version:** 
   - Windows 10 Latest
- **Filters you use in AdGuard:** 
   - Base, Tracking, Social, Annoyance, Turkish, Tracking Param. Filter.
- **Stealth Mode settings:** 
   - All Enabled (Only "Self-destruction of first-party cookies" disabled)
- **Other browser extensions:** 
   - Bitwarden, Simple Translate

### Actual Behavior

Parameters not removed when click extensions or links in the website. https://addons.mozilla.org/en-US/firefox/

Parameters should be removed with the existing filters.
`$removeparam=utm_medium`
 `$removeparam=utm_content`
 `$removeparam=utm_source`
 `$removeparam=utm_campaign`

### Vidoe

Please watch the video
https://recordit.co/Mz4N5iynGJ

(It seems a known issue since the version 4.0.53: https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1884 )

**Comment by gork7777** [comment]
Can confirm, it works fine in Chrome when you refresh the web page.
