### ISSUE TITLE
Implement AdGuard Extra into AdGuard browser

### ISSUE THREAD

**Issue by PolicyPuma4** [AdguardTeam/AdguardBrowserExtension#2110]
### Problem Description
The functionality of AdGuard Extra isn't included in the AdGuard browser, this means many ads and especially annoyances slip there way past AdGuard browser when AdGuard Extra isn't installed, this can be quite troublesome when it isn't possible to install AdGuard Extra, for example Firefox Android 😤.

### Proposed Solution
Implement AdGuard Extra into AdGuard browser. It seems to me AdGuard Extra is nothing more than a userscript that could easily be implemented into AdGuard browser 🤓.

### Alternatives Considered
The AdGuard client supports AdGuard Extra by default, this is great however if you're unable or not allowed to filter network traffic by using MITM this alternative wouldn't work 😢.

### Additional Information
I really like the work AdGuard does in making easy to use apps and most importantly having good open source filters and extensions to go along with them, having AdGuard Extra included in AdGuard browser would assure that AdGuard browser will block all ads and annoyances possible right out of the box 💪.

**Comment by Birbber** [comment]
@PolicyPuma4 Hi! Sorry for the late reply.
We can't do it for now because AdGuard Extra requires frequent updates, while AdGuard Extension is usually reviewed long enough in a browser store. 
Maybe it will be possible when we switch to manifest V3. Will consider your suggestion in the future.
