### ISSUE TITLE
modifiers removeparam invalid

### ISSUE THREAD

**Issue by 17699** [AdguardTeam/AdguardBrowserExtension#2111]
AdGuard version:  4.0.181
Browser and version:  edge102
Problem site www.bilibili.com url address bar query parameter (?vd_source=123abc..............)
 
$removeparam is not valid in the original site document / redirect address bar url

**Comment by maximtop** [comment]
@17699 
I'm sorry, but I didn't get from your description what went wrong and how to reproduce the issue.
Could you please ad more details?

**Comment by 17699** [comment]
![1](https://user-images.githubusercontent.com/73463775/174211244-21d8853a-9f67-436e-95cc-07a0e703b080.png)
![2](https://user-images.githubusercontent.com/73463775/174211283-84b41e17-7ea6-4b1f-ba6f-ae2f1bf9ffa2.png)
@maximtop

**Comment by maximtop** [comment]
Do you mean that there is some URL, and the query param `vd_source` shouldn't be removed from it?
Can you give use this URL in the comments? And tell us why it shouldn't be removed?

**Comment by 17699** [comment]
https://www.bilibili.com/video/BV13Y411T7wq
https://www.bilibili.com/video/BV1qY411K7vu
https://www.bilibili.com/video/BV1kF411F7Kh
This is the original page BV+10strings ,
Query String spm_id_from deleted successfully ，vd_source  delete failed.

**Comment by maximtop** [comment]
When I enter these pages there are no query params. Should I click somewhere to get them? Can you send us the URL with query params?

**Comment by maximtop** [comment]
I still do not get from which URL query parameter wasn't removed.
