### ISSUE TITLE
Why doesn't AdGuard block a "takeover" popup like this?

### ISSUE THREAD

**Issue by palewire** [AdguardTeam/AdguardBrowserExtension#2112]
![foxnews](https://user-images.githubusercontent.com/9993/174136706-0471001e-f590-44aa-8d2e-2109a8290145.jpg)

**Comment by palewire** [comment]
Thank you. I'm attempting to use AdGuard with Playwright and an automation script that captures hundreds of news sites from around the world. Is there a way to turn on the annoyances filter "automatically" with an environment variable, config file or startup flag?

**Comment by maximtop** [comment]
No, there is no such flag, but you can build your own extension on the top adguard API https://static.adguard.com/extensions/adguardadblocker/beta/adguard-api.zip
