### ISSUE TITLE
`$removeparam` does not work in novel.naver.com

### ISSUE THREAD

**Issue by piquark6046** [AdguardTeam/AdguardBrowserExtension#2114]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 4.0.181
- **Browser and version:**
  - Mozilla Firefox Dev 102.0b9
- **Operating system and version:**
  - Ubuntu 22.04
- **Filters you use in AdGuard:**
  - List-KR, **AdGuard URL Tracking filter**, AdGuard Tracking protection filter, AdGuard Social and AdGuard Announces
- **Stealth Mode settings:**
  - Disable WebRTC, Hide your search queries and Send websites signals not to track you
- **Other browser extensions:**
  - Tampermonkey ( No userscript )

### Expected Behavior

The request must be modified like https://github.com/AdguardTeam/AdguardFilters/pull/89838.

### Actual Behavior

The request is not modified well.

### Screenshots

<details><summary>Screenshots:</summary>

![Screenshot from 2022-06-17 17-55-32](https://user-images.githubusercontent.com/98787049/174355810-4df795e5-940b-41fe-9bf6-90cd63bb3bbe.png)
![Screenshot from 2022-06-17 17-55-44](https://user-images.githubusercontent.com/98787049/174355825-75196ed8-6031-497c-a32d-78be5a39e7fe.png)

</details>

### Additional Information

To reproduce this issue, please click one of the highlighted buttons in the following screenshot.

 
<details><summary>Screenshot:</summary>

![Screenshot from 2022-06-17 18-24-05](https://user-images.githubusercontent.com/98787049/174356205-a85ef8de-4c6e-457e-9c24-c55f907f2a1e.png)

</details>

**Comment by piquark6046** [comment]
Ping.

**Comment by maximtop** [comment]
This is not working because the `removeparam` rules require the type to be specified. In this case, it is the image type.

You can read more about it here: [removeparam modifier](https://adguard.com/kb/general/ad-filtering/create-own-filters/#removeparam-modifier).
> `$removeparam` rules that do not have any [content type modifiers](https://adguard.com/kb/general/ad-filtering/create-own-filters/#content-type-modifiers) will match only requests where the content type is 'document.'

**Comment by maximtop** [comment]
I've tested on v4.2.159, this rules
```
cc.naver.com$removeparam=a,image
cc.naver.com$removeparam=r,image
cc.naver.com$removeparam=px,image
cc.naver.com$removeparam=py,image
```
