### ISSUE TITLE
DION not works correctly

### ISSUE THREAD

**Issue by JokerVilli** [AdguardTeam/AdguardBrowserExtension#2118]
### Issue Details

- **AdGuard version:**
 v4.0.181
- **Browser and version:**
Chrome v102.0.5005.115
- **Operating system and version:**
Windows 10

### Expected Behavior

DION works correctly

### Actual Behavior

DION not works correctly

**Comment by maximtop** [comment]
Hi, could you clarify please what is DION?

**Comment by maximtop** [comment]
I've googled DION and there are mostly results about singers.
Feel free to open this issue again if there are any new details.
