### ISSUE TITLE
The extension does not work on Firefox

### ISSUE THREAD

**Issue by jellizaveta** [AdguardTeam/AdguardBrowserExtension#2121]
https://github.com/AdguardTeam/AdguardFilters/issues/122558

The extension seems to completely stop working on firefox only. It works fine on other browsers like Chrome and Brave. However, when I enable the extension on Firefox, any website I visit, unless they don't have ads, it will show. I have to manually keep blocking these ads and the number of ads blocked on any website always counts 0.

**System configuration**

Information | value
-- | --
AdGuard product: | AdGuard Browser extension v4.0.181
Browser: | Firefox
Stealth mode: | disabled
Filters: | Ad Blocking:AdGuard Base

**Comment by maximtop** [comment]
Need more info and logs.
