### ISSUE TITLE
Handle the addition of two or more identical rules

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdguardBrowserExtension#2124]
Can you improve this so that identical rules are not write in user rules? I think this will be useful for users.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/35523759/175356080-200123c6-6d72-4bf3-9373-7b97108eb05a.png)
</details>

**Comment by maximtop** [comment]
It's by design. We allow users to write in the filtering log whatever they want. On another side, this is a good feature request for the rules linter that we plan to implement.

**Comment by gork7777** [comment]
@maximtop But this will be added to AdGuard for Windows, so I suggested the extension as well.

**Comment by Birbber** [comment]
@gork7777 We don't plan to change it for now, but will consider your request while working on rules linter.
