### ISSUE TITLE
Some UI changes for editor

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardBrowserExtension#2125]
**1**.  Добавьте, пожалуйста, выключатель пользовательского фильтра на отдельную страницу редактирования этого самого пользовательского фильтра.

![2022 06 24-2](https://user-images.githubusercontent.com/17948007/175457752-769f0576-5d5f-4ae8-8709-8cadface6c87.png)

 А то неудобно - редактируешь на одной странице, а лезть за полным отключением надо в настройки - на другую страницу. Я всегда держу страницу редактирования пользовательских правил открытой, а держать открытой ещё и страницу настроек из-за одной из них - это перебор. (Отсюда: https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1352#issuecomment-1165162219)
___________________________________________________

 **2**. Избыточная высота футера - можно сделать в 2 раза меньше.

 **3**. Отступ перенесённой строки 4 пробела - достаточно 2-х.

![2022 06 24-3](https://user-images.githubusercontent.com/17948007/175505681-95aebeaf-3a46-435e-b32d-8702a19eb848.png)
<br>

----------
 AdGuard v4.0.181 &nbsp; | &nbsp; FireFox v78.13 ESR &nbsp; | &nbsp; Win7SP1

**Comment by XX-J** [comment]
При изменении высоты футера сообщение "Сохранено" можно перенести внутрь кнопки "Сохранить", временно меняя в ней текст.

![2022 07 12-1](https://user-images.githubusercontent.com/17948007/178401807-d91cec67-9a9e-454c-9f68-5293d1d7c774.png)

**Comment by XX-J** [comment]
**4.** Перенести кнопку "Сохранить" в центр или поставить её после кнопок "Импорт" "Экспорт". Кнопка "Сохранить" самая используемая (по крайней мере для меня) и по этому к ней можно было бы быстрее дотянуться мышью, если бы она была расположена ближе к центру.

![2022 07 20-1](https://user-images.githubusercontent.com/17948007/180055191-8af02624-c4ed-4d52-aa9c-5b7a69a58940.png)

**Comment by XX-J** [comment]
Спасибо Большое за **1**-е и **4**-е!

 Но что насчёт **2**-го и **3**-го пункта?

 Суммирую:

 **2**. Избыточная высота футера - можно сделать в 2 раза меньше.

 **3**. Отступ перенесённой строки 4 пробела - достаточно 2-х.

![2022 06 24-3](https://user-images.githubusercontent.com/17948007/175505681-95aebeaf-3a46-435e-b32d-8702a19eb848.png)

 При изменении высоты футера сообщение "Сохранено" можно перенести внутрь кнопки "Сохранить", временно меняя в ней текст.

![2022 07 12-1](https://user-images.githubusercontent.com/17948007/178401807-d91cec67-9a9e-454c-9f68-5293d1d7c774.png)

**Comment by maximtop** [comment]
Второй и третий пункты мы менять не будем.

**Comment by XX-J** [comment]
> Второй и третий пункты мы менять не будем.

 Почему?
