### ISSUE TITLE
xpath comparing positions with `count` and `preceding-sibling` doesn't work

### ISSUE THREAD

**Issue by DetachHead** [AdguardTeam/AdguardBrowserExtension#2131]
given the following html:
```html
<html>
<head></head>
<body>
<div class="header">header</div>
<div>post content</div>
<div>post content</div>
<div class="separator"></div>
<div class="header"><span>sponsored</span></div>
<div>post content</div> <!-- hide -->
<div>post content</div> <!-- hide -->
<div>post content</div> <!-- hide -->
<div class="separator"></div>
<div class="header">header</div>
<div>post content</div>
<div>post content</div>
<div>post content</div>
<div>post content</div>
<div>post content</div>
<div class="separator"></div>
<div class="header"><span>sponsored</span></div>
<div>post content</div> <!-- hide -->
<div>post content</div> <!-- hide -->
<div class="separator"></div>
<div class="header">header</div>
<div>post content</div>
<div>post content</div>
<div>post content</div>
<div>post content</div>
</body>
</html>
```

i created the following xpath to compare the positions of the previous "sponsored" `span` and the previous "separator" `div` in order to determine which "post content" `div`s to block:

```xpath
//div[count(./preceding-sibling::div[@class='header' and .//span[.='sponsored']][1]/preceding-sibling::*) > count(./preceding-sibling::div[@class='separator'][1]/preceding-sibling::*)]
```

this works in ublock origin, but not in adguard

### Issue Details

- **AdGuard version:** 4.0.181
- **Browser and version:** chrome 103.0.5060.66 and safari (ios 15.1.1)
- **Operating system and version:** windows 10 and ios 15.1.1
- **Filters you use in AdGuard:** `*##:xpath(//div[count(./preceding-sibling::div[@class='header' and .//span[.='sponsored']][1]/preceding-sibling::*) > count(./preceding-sibling::div[@class='separator'][1]/preceding-sibling::*)])`
- **Stealth Mode settings:** n/a
- **Other browser extensions:** ublock origin (to compare the behavior, disabled while testing adguard)

### Expected Behavior
elements blocked in both ublock and adguard

### Actual Behavior
elements only blocked in ublock

### Screenshots

<details>
<summary>ublock origin</summary>

![image](https://user-images.githubusercontent.com/57028336/177035439-20a1b014-49d2-4e39-9a6a-074ed31264f0.png)

</details>

<details>
<summary>adguard</summary>

![image](https://user-images.githubusercontent.com/57028336/177035585-66b58c79-488a-44cf-a482-e85ab25a1276.png)
</details>

**Comment by slavaleleka** [comment]
Issue moved to [AdguardTeam/ExtendedCss #146](https://github.com/AdguardTeam/ExtendedCss/issues/146) via [**ZenHub**](https://www.zenhub.com/)
