### ISSUE TITLE
Cannot apply $replace rules in Firefox to the loaded scripts 

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#2133]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:** 4.0.204
  - 
- **Browser and version:** 102.0.1 (64-bit)
  - 
- **Operating system and version:** Win10
  - 
- **Filters you use in AdGuard:** Base
  - 
- **Stealth Mode settings:** all
  - 
- **Other browser extensions:** no
  - 

### Expected Behavior

`$replace` rule is applied to external script.

### Actual Behavior

The rule is not applied.

* `||adguard.com/js/main.3600.min.js$replace=/^.*//` - does nothing on adguard.com

* `||example.com^$replace=/Example Domain/AG Test/` - this rule, applied to HTML, works.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/178970483-4fab42d3-4de7-4f60-8d8f-53ce6d049113.png)

</details>

**Comment by stanislav-atr** [comment]
||[adguard.com/js/main*$replace=/^.*/alert('test')/](http://adguard.com/js/main*$replace=/%5E.*/alert('test')/)
Отрабатывает



||[adguard.com/js/main.3600.min.js$replace=/^.*//](http://adguard.com/js/main.3600.min.js$replace=/%5E.*//)
Не работал кейс, потому что 3600 меняется
