### ISSUE TITLE
Clicking on a request in `Filtering log` multiple times should toggle `Request details`

### ISSUE THREAD

**Issue by contribucious** [AdguardTeam/AdguardBrowserExtension#2136]
**Hello,** :wave:

Just _another_ enhancement request here, on this Sunday (sunny here). :relaxed:

_Thank you in advance!_ :thumbsup:
___
&nbsp;

### Issue Details

* **AdGuard version:**
  * AdGuard 4.0.181
* **Browser and version:**
  * Firefox 102.0.1

### _Desired_ Behavior

In the `Filtering log`, clicking on a request multiple times should ideally toggle the display of the right side column (`Request details`), I would say.

This, also in order to be more consistent with the **AdGuard for Windows** behavior.

:bulb: Having a similar user experience is especially useful when you often use both regularly (my case, as a Windows and Linux user).

:arrow_right: See animated GIF below for a comparison in their current state.
:gear: _**AdGuard for Windows** 7.10.1 {light theme} — **AdGuard Browser extension** 4.0.181 {dark theme}._

### Animated GIF

<details>
<summary>Click me to see it …</summary>
&nbsp;

![AdGuard_comparison](https://user-images.githubusercontent.com/4764956/179404650-e00ce7b4-df74-48e9-a3a5-c8172ae0d7cf.gif)
</details>
&nbsp;

**Comment by maximtop** [comment]
Looks legit for me
