### ISSUE TITLE
`:hover` elements should be less bright (contrast) in dark mode

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdguardBrowserExtension#2137]
### Issue Details

- **AdGuard version:**
  - 4.0.181
- **Browser and version:**
  - Chrome 103
- **Operating system and version:**
  - macOS 12.4
- **Filters you use in AdGuard:**
  - .
- **Stealth Mode settings:**
  - .
- **Other browser extensions:**
  - .

### Expected Behavior

`:hover` elements are slightly brighter (contrasted) in dark mode

### Actual Behavior

`:hover` elements are much brighter (contrasted) in dark mode

### Screenshots

<details><summary>Screenshot:</summary>

![2022-03-29_17-33-46](https://user-images.githubusercontent.com/19418601/160636397-d359011f-c56a-4c51-bb57-a3136aecbeda.png)

</details>

### Additional Information

https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1408#issuecomment-1181753617

**Comment by rakleed** [comment]
@kaprielov why did you add the label Resolved if the items in [the dropdown list](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2137#issuecomment-1205490904) are still too bright?

**Comment by rakleed** [comment]
@kaprielov please take a look

**Comment by gork7777** [comment]
@rakleed Better open a new issue I guess.
