### ISSUE TITLE
` filtering-log_` disconnected

### ISSUE THREAD

**Issue by bowie0021** [AdguardTeam/AdguardBrowserExtension#2138]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:** 4.0.204
- **Browser and version:** Chrome 103
- **Operating system and version:** Windows 10 21H2
- **Filters you use in AdGuard:**
 
- **Stealth Mode settings:**
 
- **Other browser extensions:**
  

---

Console says connection to filtering log is disconnected. I don't know if this is a bug or expected behavior.

### Screenshots

<details><summary>Screenshot:</summary>

![12](https://user-images.githubusercontent.com/109369779/179833762-31044017-c38f-427b-befa-e56e66d3f019.png)

</details>

**Comment by maximtop** [comment]
Hi! It is expected. We print logs when filtering log starts messages exchange with background page and ends.
