### ISSUE TITLE
cant block an element

### ISSUE THREAD

**Issue by Karmylr** [AdguardTeam/AdguardBrowserExtension#2141]
link="https://www.hk01.com/%E5%8D%B3%E6%99%82%E4%B8%AD%E5%9C%8B/795222/%E7%8E%84%E5%A5%98%E5%AF%BA%E4%BE%9B%E5%A5%89%E9%87%8E%E7%94%B0%E6%AF%85%E7%AD%89%E5%8D%97%E4%BA%AC%E5%A4%A7%E5%B1%A0%E6%AE%BA%E6%88%B0%E7%8A%AF-%E7%B6%B2%E6%B0%91%E7%97%9B%E6%89%B9-%E9%9D%96%E5%9C%8B%E7%A5%9E%E7%A4%BE%E5%88%86%E7%A4%BE"
want to block"hk01.com##div[class="md:min-h-[90px] lg:min-h-[250px] hidden md:flex md:items-center"]"

**Comment by maximtop** [comment]
@Alex-302 can you take a look, please?

**Comment by gork7777** [comment]
@Karmylr Hey, can you please enable `AdGuard Chinese filter` from settings? And don't forget to update the filters. Can't reproduce while `Chinese filter` is enabled.

**Comment by Alex-302** [comment]
It is already blocked by `hk01.com##.md\:min-h-\[90px\].lg\:min-h-\[250px\].hidden.md\:flex.md\:items-center` from Chinese filter.
