### ISSUE TITLE
Some type of JS rule does not work in ppomppu.co.kr

### ISSUE THREAD

**Issue by piquark6046** [AdguardTeam/AdguardBrowserExtension#2142]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - AdGuad Standalone 4.0.204
- **Browser and version:**
  - Mozilla Firefox Dev 103.0b9
- **Operating system and version:**
  - Ubuntu 22.04
- **Filters you use in AdGuard:**
  - List-KR (manual), AdGuard TPF, AdGuard URL Tracking, AdGuard Social and AdGuard Annoyances
- **Stealth Mode settings:**
  - None
- **Other browser extensions:**
  - React Developer Tools and Tampermonkey (no userscript is enabled)

### Expected Behavior

Only a non-domain-specific works.

### Actual Behavior

All JS rules work.

### Screenshots

<details><summary>Screenshot:</summary>

![Screensh232323](https://user-images.githubusercontent.com/98787049/180446269-c0a438f4-fb57-4fe4-aa40-805e02e663c5.png)

</details>

### Additional Information

```
#%#(function() { console.log("#%# - works") })();
ppomppu.co.kr#%#(function() {  console.log("ppomppu.co.kr#%# - works") })();
www.ppomppu.co.kr#%#(function() {  console.log("www.ppomppu.co.kr#%# - works") })();
```

https://listauthorschat.slack.com/archives/C010N14G4TF/p1658494800537439?thread_ts=1658493173.532209&cid=C010N14G4TF

https://www.ppomppu.co.kr/

**Comment by maximtop** [comment]
I can't reproduce. Are you sure that the error was caused by these rules? They do not have the AG_onLoad function call.

**Comment by maximtop** [comment]
Can you attach a link to this filter?

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/raw/master/filter.txt
Here it is.

**Comment by maximtop** [comment]
There are errors in the rules. Brackets in the end are redundant.
