### ISSUE TITLE
Cosmetic rules do not work inside an iframe

### ISSUE THREAD

**Issue by jellizaveta** [AdguardTeam/AdguardBrowserExtension#2148]
When hiding an element inside an iframe, the cosmetic rule in the extension doesn't work.
`media.toidas.net##.toidas-sns-embed-inner`

Here's the site where to look:
https://toidas.net/entry/18910

<details><summary>Screenshot:</summary>

<img width="757" alt="Снимок экрана 2022-08-01 в 18 28 58" src="https://user-images.githubusercontent.com/91964807/182187023-e09eb96f-2435-4c38-a2bd-489b70a685d0.png">

</details><br/>

According to https://github.com/AdguardTeam/AdguardFilters/issues/125708

**Comment by maximtop** [comment]
There is no more such element on the page
