### ISSUE TITLE
Размер окна ручной блокировки.

### ISSUE THREAD

**Issue by Vitalik93** [AdguardTeam/AdguardBrowserExtension#2149]
Использую последнюю версию расширения - 4.0.204 и браузер Edge 103.0.1264.77. Заметил, что при уменьшении масштаба страницы, окна ручной блокировки (выбор и настройка блокировки) тоже уменьшаются. Может стоит сделать, чтобы данные окна были всегда одного размера? Масштаб сайта иногда имеет смысл уменьшить, когда слишком крупный, а здесь в любом случае получается слишком мелко, даже при 80% масштаба.

![Снимок экрана 2022-08-01 184519](https://user-images.githubusercontent.com/34383288/182202195-1b8b7368-beb1-4d39-b18a-31a3a68fd2af.png)

![Снимок экрана 2022-08-01 184605](https://user-images.githubusercontent.com/34383288/182202214-09f5ab2d-84a8-4aeb-87d4-68d6a0c25b03.png)

**Comment by Birbber** [comment]
@Vitalik93 Выглядит как ожидаемое поведение. Окно ручной блокировки - такая же часть странцы, как и всё остальное.
