### ISSUE TITLE
Не работает ручная блокировка.

### ISSUE THREAD

**Issue by Vitalik93** [AdguardTeam/AdguardBrowserExtension#2152]
Использую последнюю версию расширения (4.0.204) и браузер Edge (103.0.1264.77). Попробовал сейчас заблокировать элемент на странице, но заметил что блокировка не работает. Происходит вот что: после выбора элемента и блокировки он скрывается, но после обновления страницы опять висит, причем пользовательский фильтр пуст. Проверил на 3 сайтах -  повторилось.

**Comment by gork7777** [comment]
Можете ли вы предоставить веб-сайты?

**Comment by Vitalik93** [comment]
Проверил в Firefox - там всё нормально.  В Edge стоит расширение из Microsoft Store. Может быть именно с ним проблема.

**Comment by maximtop** [comment]
у меня не повторяется, посмотрите, есть ли какие-то ошибки в консоли самой страницы, и в консоли бэкграунд пейдж

**Comment by Vitalik93** [comment]
> у меня не повторяется, посмотрите, есть ли какие-то ошибки в консоли самой страницы, и в консоли бэкграунд пейдж

В консоли никаких ошибок при попытке добавить свое правило нет.

**Comment by Vitalik93** [comment]
Переустановка расширения решила проблему. Странный глюк тем не менее...

**Comment by maximtop** [comment]
если повторится, то дайте знать
