### ISSUE TITLE
Extension writes too much data on the HDD

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#2157]
### Issue Details

- **AdGuard version:** 4.1.1
- **Browser and version:** Chrome 103
- **Operating system and version:** Windows 10
- **Filters you use in AdGuard:** Base, 2x AdGuard tracking, Social, Annoyances, Russian
- **Stealth Mode settings:** All, except cookies
- **Other browser extensions:** no

### Actual Behavior

Extension writes thousands files every day and more than 70 GB per week. 30% of total writes to the hdd.

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/8361299/183050432-ce877dd1-f9d1-4209-9685-1f42cf54b856.png)

</details>

7 days

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/8361299/183509520-df9d6710-c045-4d88-8f04-2e777af4a72f.png)

</details>

**Comment by Vitalik93** [comment]
У себя в Edge такого не наблюдаю.

![Снимок экрана 2022-08-07 163539](https://user-images.githubusercontent.com/34383288/183296091-c81382a6-75d2-4463-8004-b16deec92b04.png)

**Comment by Alex-302** [comment]
Это просто объём файлов, а не объём записанного.

**Comment by tumatanquang** [comment]
The `gfggjaccafhcbfogfkogggoepomehbjl` folder is the data folder of the AdGuard AdBlocker (Beta) extension.
The `bgnkhhnnamicmpeenaelnjfhikgbkllg` folder is the data folder of the AdGuard AdBlocker extension.
Why do you use 2 versions simultaneously? It does not help you block ads better!

**Comment by Alex-302** [comment]
@tumatanquang only one enabled.

**Comment by ameshkov** [comment]
I think it's already resolved in the v4.2 version, but I'll assign it to the patch version just to double-check.

**Comment by Alex-302** [comment]
Will check using SSDReady.

**Comment by Alex-302** [comment]
It's much better now

<details>
<summary>2h period</summary>

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/8361299/61bdd081-4684-43c8-a700-0b48df140eef)

</details>

But still the extension records many times more than others.
