### ISSUE TITLE
Fonts are blurry after 4.1 update

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdguardBrowserExtension#2158]
After the v4.1 update, the fonts are looks blurry. I added screenshots for that and you can check these. I'm using Chrome v104.0.5112.81.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/35523759/183135739-cfe8999b-98e9-4036-ae0a-bc5f7dc4ee44.png)
</details>

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/35523759/183136282-40c5ac3e-a586-46cc-9a2d-4ddacee49c47.png)
</details>

<details><summary>Font settings</summary>

![image](https://user-images.githubusercontent.com/35523759/183145470-90784ce8-0b7e-4efa-bd80-59bd64741883.png)
</details>

**Comment by Vitalik93** [comment]
По моему наоборот шрифты стали лучше.

**Comment by kaprielov** [comment]
I don't see any blurring of fonts. Are you looking at windows/mac? And what is the screen resolution, is there scale?

**Comment by gork7777** [comment]
@kaprielov Yes I'm at Windows. My screen resolution is 1920x1080. There's no scale, I'm using 100% scale.

**Comment by kaprielov** [comment]
We cannot reproduce this problem. What version of windows do you have? Are Advanced scaling settings enabled?
<img width="996" alt="Снимок экрана 2022-08-10 в 11 34 41" src="https://user-images.githubusercontent.com/12276208/183855067-361fdd77-d8d1-4490-83e5-6532a63a291b.png">

**Comment by gork7777** [comment]
@kaprielov I'm using Windows 10 v21H2. Yes, fix scaling for apps setting is enabled. Also this problem same for the Firefox too after 4.1 update.

**Comment by gork7777** [comment]
@kaprielov Well, actually there's a comparison in the above issue, you can have a look at it.

**Comment by kaprielov** [comment]
@gork7777 From your screenshots it is not quite clear what the problem is. Can you install an earlier version and take comparative screenshots with 4.1?

**Comment by gork7777** [comment]
@kaprielov I don't know how to install an earlier version :/

**Comment by kaprielov** [comment]
@gork7777 You can find them [here](https://github.com/AdguardTeam/AdguardBrowserExtension/releases) in the Assets section. Download and unzip the zip. Then open the extension page in google chrome(chrome://extensions), and turn on developer mode (top right corner). Click Load unpacked in the upper left corner of the page. Then select the folder containing the manifest.json file.

**Comment by maximtop** [comment]
@gork7777 I've put screenshots from 4.1 and 4.0 next to each other and do not see if fonts are blurry. They've changed a little, but they are not blurry.

**Comment by gork7777** [comment]
@maximtop Well, but in 4.0 fonts are more readable and looks nice to me at least. And in this same issue there are 2 more issues too: https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2159, https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2180

**Comment by maximtop** [comment]
@gork7777 Are fonts on your computer blurry as well here https://fonts.google.com/specimen/Roboto+Flex?

**Comment by gork7777** [comment]
@maximtop It looks a little blurry when it's a 14px font. I guess it gets blurry as the pixels get smaller maybe? It's not blurry at 16px. You can also see the difference quite a bit if you look at these two comparisons:

<details><summary>v4.0</summary>

![image](https://user-images.githubusercontent.com/35523759/188898170-4e0e48fb-c499-41d5-9b80-e659f363511c.png)
</details>

<details><summary>v4.1</summary>

![image](https://user-images.githubusercontent.com/35523759/188898405-f6725967-721c-4676-b3f3-1d0072031c71.png)
</details>

**Comment by kaprielov** [comment]
@gork7777 It seems to be a problem in the font. Please create an issue here. https://github.com/googlefonts/roboto-flex/issues

**Comment by NPA6cjf1jtr-qfc6fbh** [comment]
Why change the font to Roboto Flex?

**Comment by maximtop** [comment]
> Why change the font to Roboto Flex?

We found it more flexible for our purposes
