### ISSUE TITLE
Fonts are now less readable on 4.1.1

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardBrowserExtension#2159]
### Problem Description

Fonts are now thinner and smaller making them less readable

Version 4.0.204
![Version 4 0 204](https://user-images.githubusercontent.com/110733278/183255512-d004a4ce-78e7-4994-8eb6-28eaa4399e6b.png)

Version 4.1.1
![Version 4 1 1](https://user-images.githubusercontent.com/110733278/183255517-c1f72e08-1dc7-4419-abc9-7e62a5417a96.png)

**Comment by gork7777** [comment]
Well, same issue was opened https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2158

**Comment by maximtop** [comment]
It would be nice of you to add information about your system and browser versions. 
Closing this as a duplicate.
