### ISSUE TITLE
adguard no blocking ads

### ISSUE THREAD

**Issue by remotosko** [AdguardTeam/AdguardBrowserExtension#216]
i'm using chromium "portable"(extracted of chromium mini installer) latest build dated on 1st april. The thing is that adguard always block ads but sometimes no, so i need update filters for fix, i paste some images(is there 4).

1º image: undefined blocks ads
2º image: no number in extension
3º image: adguard settings 
4º image: youtube video

![blocking ads](https://cloud.githubusercontent.com/assets/18273146/14266422/62588ccc-fac8-11e5-8f9e-d1f510555846.png)

![no number](https://cloud.githubusercontent.com/assets/18273146/14266421/62568a58-fac8-11e5-9564-6e63c3d0a2be.png)

![nonumber2](https://cloud.githubusercontent.com/assets/18273146/14266423/628068f0-fac8-11e5-8f6c-5580a7d5ffca.png)

![youtube](https://cloud.githubusercontent.com/assets/18273146/14266424/6280a428-fac8-11e5-8c00-b2dd794efa46.png)

**Comment by ameshkov** [comment]
Hi! Thank you for reporting it!

First one is a known issue, should be fixed in the next release (will be released this week).
What for other issues, just in case, do you use CCleaner or some app like that?

**Comment by remotosko** [comment]
yes, i do, why? i think the problem is adguard for other issues

**Comment by ameshkov** [comment]
The latest CCLeaner version deletes while cleaning Chrome data.
Some details on this issue are here: #205 

> 2º image: no number in extension
> 3º image: adguard settings 
Means filters are empty

> 4º image: youtube video
Definitely something is wrong with the filters.

When you check filter updates AG downloads the latest filters and everything works ok until next CCLeaner run.

**Comment by remotosko** [comment]
i report to pirifrom developers or you'll mark the bugs(or is marked)?

if you want close this issue i will clean manually until fix.

**Comment by ameshkov** [comment]
> i report to pirifrom developers or you'll mark the bugs(or is marked)?

We'll fix it on our side, but anyway, it would be great if they fix it on their side too.

**Comment by ameshkov** [comment]
> if you want close this issue i will clean manually until fix.

Closed as duplicate, we anyway have an issue about the same problem.
