### ISSUE TITLE
rules count bug

### ISSUE THREAD

**Issue by ahmedm25** [AdguardTeam/AdguardBrowserExtension#2160]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [y ] I am running the latest version
- [y ] I checked the documentation and found no answer
- [y ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - (4.1.1)
- **Browser and version:**
  - (Chrome 104)
- **Operating system and version:**
  - (e.g. Windows 7)
- **Filters you use in AdGuard:**
  - (Base filter)
- **Stealth Mode settings:**
  - (disabled)
- **Other browser extensions:**
  - (FDM ,google tanslate)

### Expected Behavior

rules count in filters page return a count of enabled filters

### Actual Behavior

rules count in filters page return a code instead of numbers

### Screenshots

[Untitled](https://user-images.githubusercontent.com/40965513/183273234-ea53387a-7eb5-4696-b559-18491fcb161b.jpg)

</details>

**Comment by gork7777** [comment]
This relates to Arabic translation. AdGuard team can you please check that string for all languages? [Filter rules count](https://crowdin.com/translate/adguard-applications/17594/en-ar#3936964). It appears as code because there's a space in the variable.

**Comment by maximtop** [comment]
Thank you for openning the issue. 
Looks like in the translation were used other % characters.
