### ISSUE TITLE
WebRTC Issue

### ISSUE THREAD

**Issue by johnconner122** [AdguardTeam/AdguardBrowserExtension#2166]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [yes] I am running the latest version
- [yes] I checked the documentation and found no answer
- [yes] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
          AdGuard v4.0.204
- **Browser and version:**
          Kiwi Browser v101
- **Operating system and version:**
          Android 8.1.0
- **Filters you use in AdGuard:**
  - 
- **Stealth Mode settings:**
          Enabled
- **Other browser extensions:**
         AdGuard Extra v1.0.408

# ## Expected Behavior

WebRTC should be blocked

### Actual Behavior

I can still see WebRTC leaking IP address!

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by slavaleleka** [comment]
there is an issue with Kiwi Browser
https://github.com/kiwibrowser/android/issues/228
