### ISSUE TITLE
Add a generic solution (new `Action` in the popup) to skip the video ad(s) currently played

### ISSUE THREAD

**Issue by contribucious** [AdguardTeam/AdguardBrowserExtension#2167]
### _(:wave:)_ Prerequisites

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Problem Description

Many websites (catch-up TV websites, …) use preroll/midroll video ads and … do not have AdGuard rules (yet).

### Proposed Solution

Add a _generic_ solution, in the form of a new entry in the `Actions` list of the extension popup + in the AG context menu, to let the user be able to skip the video ad currently played _(or possibly, all of them in a consecutive way — generic detection possible in this case for automation: any video with a duration of less than 50 or possibly 60 seconds)._

:arrow_right_hook: **How in summary?** By simply going to the end of the video ad directly (admittedly, _some_ websites prevent this).

### :gear: Technical Aspects / Possible Implementation

<details>
<summary>Read me …</summary>
&nbsp;

Basically, a new _action_ entry would appear in [the popup](https://user-images.githubusercontent.com/4764956/184285347-3a752830-2af2-4354-b22c-29996dd7a0f5.png) below `Block ads on this website` and be called:
- `Video ads? Try to skip them all!` (for full automation mode);
- `Video ad now? Try to skip it!` or `Video ad? Try to skip it!` (for basic mode — action to be repeated a few times naturally but not a problem at all if the popup stays open).

:heavy_plus_sign: Also in [the context menu](https://user-images.githubusercontent.com/4764956/184287358-d00f3bff-58d3-4520-801d-2748e8933f2f.png). But just _as a bonus_, because some websites hijack the right click on the _sometimes like-fullscreen_ player _(and the **Firefox** solution: `Shift + right click` or **Chromium-based** one: `double right click` at the same precise location, is not necessarily known to everyone)_.

This new _action_, added to the list of existing _Actions_, would trigger the following JavaScript code in the current web page:

```javascript
const video = ¦Detection of the video element currently playing here —
               for the test let's just say `document.querySelector('video')` or
               `document.getElementsByTagName('video')[0]`¦;

// Main solution
// ✔ Go directly to the end of the video ad.
video.currentTime = (video.duration) - 0.1; // 0.1 just to make sure that the end-of-play event(s) can be sent properly.

// Alternative solution (possibly as an alternative Action to the AdGuard menu therefore)
// ✔ Increases the playback speed of the video ad x6.
// For websites that want to receive all video ad-related events at various playback positions,
// but do not time the time spent between the start and end of playback,
// before allowing the main video desired by the user to start playing …
// Remark: Do not set a value too high for older PCs/devices though, I would say.
video.playbackRate = 6;
```
</details>
&nbsp;

#### :thumbsup: Thank you in advance!

**Comment by Birbber** [comment]
@contribucious Hi. To be honest, it's unlikely it's gonna work on every webpage and looks like AdBlocker is not the right place for something like this.

**Comment by contribucious** [comment]
@Birbber Hello Anna. Yes, indeed. No problem, I completely understand. :v: :relaxed:
