### ISSUE TITLE
not works in sites xxx

### ISSUE THREAD

**Issue by fff99** [AdguardTeam/AdguardBrowserExtension#217]

**Comment by ameshkov** [comment]
Huh?

**Comment by cabban** [comment]
@ameshkov he means xxx = adult naughty sites

**Comment by ameshkov** [comment]
:) @fff99 which sites exactly?

**Comment by cabban** [comment]
hahah, little shamefull to say that , but in theory all strange sites has many freaking annoying ads and pop up ads :P

**Comment by ameshkov** [comment]
@cabban it would be better to report such websites to https://github.com/AdguardTeam/AdguardFilters then

**Comment by cabban** [comment]
@ameshkov haha why I never go in there:-P
