### ISSUE TITLE
duplichecker.com

### ISSUE THREAD

**Issue by mohsinali1065** [AdguardTeam/AdguardBrowserExtension#2170]
Using Chrome Version 103.0.5060.134 (Official Build) (64-bit)
While browsing site **https://www.duplichecker.com/free-tools.php**
i see all images included logo disappear. It was working fine before some days.

### Issue Details

- **AdGuard version:**
Version 4.1.1
- **Browser and version:**
Chrome Version 103.0.5060.134 (Official Build) (64-bit)
- **Operating system and version:**
Window 10
### Expected Behavior

All images should be shown.

### Screenshots
![image](https://user-images.githubusercontent.com/17384487/185101041-51fc9075-5cef-490e-a470-d29b26ac0f02.png)

<details><summary>Screenshot:</summary>

In following grid, images are missing.

</details>

**Comment by Alex-302** [comment]
@mohsinali1065 Please use this tool for report filteing issues
https://kb.adguard.com/en/technical-support/reporting-tool#extension
