### ISSUE TITLE
adguard extension crashed frequently on chrome

### ISSUE THREAD

**Issue by shaman96** [AdguardTeam/AdguardBrowserExtension#2174]
![Screenshot 2022-08-23 074512](https://user-images.githubusercontent.com/4917070/186039214-e558ebc8-de8d-4977-be2e-033e47fbb6bf.jpg)

**Comment by maximtop** [comment]
Hi, thank you for opening the issue.
Could you please expand the first two errors?
Are there any steps to reproduce?

**Comment by scrutinizer11** [comment]
I reported an identical issue and have errors collected in a log that I attached. Please, have a look.
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2165#issuecomment-1229120700

**Comment by Birbber** [comment]
Will close this one as a duplicate of #2165. Feel free to leave a comment there.
