### ISSUE TITLE
Rule count is 0

### ISSUE THREAD

**Issue by ShintoPlasm** [AdguardTeam/AdguardBrowserExtension#2175]
There seems to be an issue with downloading/updating filter lists in the browser extensions. I've tried this in Microsoft Edge (Windows 10) and Firefox for Android - in both cases, the extension shows a rule count of 0 despite several filter lists being enabled. When I click 'Update', a message indicates that no updates are available.

_Edit: This is the case both for existing installations as well as newly installed extensions: i.e. an extension which used to function OK suddenly shows 0 rule count, same as a newly installed and configured extension._

Is there a problem with the server hosting the filter lists?

**Comment by maximtop** [comment]
@ShintoPlasm,
which version of extension are you using? 
are filters categories enabled?

**Comment by ShintoPlasm** [comment]
@maximtop,

Extension versions I'm using:
- Edge on Windows 10: v4.1.19 (installed from the Edge Store); strangely it is now showing the rule count again.
- Firefox Stable on Android: v4.1.19 (installed through the browser's add-on page). Still showing rule count 0, despite uninstalling and reinstalling the extension. See screenshot-

![photo_2022-08-26_13-28-32](https://user-images.githubusercontent.com/35544416/186903534-afff1514-eadd-4781-9749-2806a35f25d7.jpg)

**Comment by ShintoPlasm** [comment]
Update from a couple of hours later: all of my AdGuard extensions (Edge W10; Firefox W10; Firefox Android) have reverted to rule count 0. I'd removed and reinstalled all of them, and initially it seemed to have been fixed on the desktop (not on Android). Now, after restarting the computer/browser a few times as part of work, the rule count is back to 0 and no adblocking occurs on any page anymore.

**Comment by maximtop** [comment]
Can it be reproduced by restarting edge browser? Do you have any errors on background page?

**Comment by ShintoPlasm** [comment]
Settings from the Firefox add-on (v4.1.19), attached.

I can't get Edge to reproduce this in a consistent manner - it seems to come and go.

In Firefox, the issue seems more consistent - is there an equivalent to the background page in FF where I could capture any errors?

[20220828_142838_adg_ext_settings_4.1.19.zip](https://github.com/AdguardTeam/AdguardBrowserExtension/files/9439737/20220828_142838_adg_ext_settings_4.1.19.zip)

**Comment by maximtop** [comment]
Yes, here is the instruction. https://maximtop.notion.site/How-to-find-an-extension-logs-in-the-Firefox-682216c6dea54b6a9832edf924b07d3b

**Comment by maximtop** [comment]
I've found the error. It happens because of the rule `bing.com##^#b_results > .b_a`. We recently changed the interface of `TSUrlFilter.RuleConverter.convertRule` for another library and unfortunately didn't update the error handling in the extension. I'm going to update the extension as soon as possible. For now, you can just comment out this rule.

**Comment by ShintoPlasm** [comment]
Great, happy you've caught it so quickly! :)
