### ISSUE TITLE
White banner while checking filter updates

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdguardBrowserExtension#2176]
After v4.1.19 update, the update banner is broken when updating filters with right click context menu. While updating filters from AdGuard settings, going to another browser tab also breaks the update banner. You can check the video in the previously opened issue: https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1948
Chrome version: 104.0.5112.102
Same for the Firefox browser. Firefox version: v104.0

**Comment by maximtop** [comment]
Can't reproduce. Do you have some styles, which may influence GitHub styles? 
Also, please give more information about browser, os.

**Comment by gork7777** [comment]
@maximtop I'm just using GitHub Dark default theme, not using another else. Also I'm using Chrome v104.0.5112.102 - Windows 10 21H2. This issue only on the GitHub website.

**Comment by maximtop** [comment]
Can confirm, that with the dark theme, the notification adds white background.

**Comment by gork7777** [comment]
This is same for the all Dark themes.

**Comment by bkrucarci** [comment]
I can confirm that with the Dark Reader add-on enabled on my Firefox.

There is no problem with light theme of Firefox.
Screenshot added.

**On Dark Theme**
![Screenshot_1](https://user-images.githubusercontent.com/15933805/187764536-4506c8f9-f2e2-4701-bbe7-dd07eab579f1.png)


**Switch to Light Theme**
![Screenshot_3](https://user-images.githubusercontent.com/15933805/187764558-8d429330-8a22-4706-b806-d60aed227d29.png)

**No Problem on Light Theme**
![Screenshot_2](https://user-images.githubusercontent.com/15933805/187764578-81530e22-8b7e-4fb1-8598-7d754a579206.png)
