### ISSUE TITLE
Handle url changes that were caused by js

### ISSUE THREAD

**Issue by stanislav-atr** [AdguardTeam/AdguardBrowserExtension#2178]
@stanislav-atr, добрый. С параметром на конце или нет, но это всё равно - **главная**. А на любой **заглавной странице** пустой `path` должен работать, т.к. путь **отсутствует**.

_Originally posted by @XX-J in https://github.com/AdguardTeam/tsurlfilter/issues/54#issuecomment-1230080681_

**Comment by XX-J** [comment]
[stanislav-atr](https://github.com/stanislav-atr) commented [on 29 Aug](https://github.com/AdguardTeam/tsurlfilter/issues/54#issuecomment-1230071138)

> @XX-J, добрый день! Смена урла с [https://yandex.ru/?com=1](https://href.li/?https://yandex.ru/?com=1) на [https://yandex.ru/](https://href.li/?https://yandex.ru/) происходит без перезагруки и отправления нового запроса, поэтому yandex.ru/ не может быть сматчен в данном кейсе.

 Это происходит посредством команды `history.pushState('', '', 'new-url')`? И надо отслеживать изменения в истории посещённых страниц?
