### ISSUE TITLE
Sidebar buttons are too far apart

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardBrowserExtension#2179]
- [ Yes ] I am running the latest version
- [ Yes ] I checked the documentation and found no answer
- [ Yes ] I checked to make sure that this issue has not already been filed

![Screenshot 2022-08-30 004643](https://user-images.githubusercontent.com/112417589/187252607-08460772-c052-47a2-984e-ed1d137ac88c.png)

**Comment by Birbber** [comment]
We already have a [similar issue](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2150). Will close this one as a duplicate.
