### ISSUE TITLE
Downloading ressources throws a `Wrong checksum` error

### ISSUE THREAD

**Issue by raed667** [AdguardTeam/AdguardBrowserExtension#2181]
### Issue Details

When I run `yarn resources` I get the following error: 

```
Download https://filters.adtidy.org/extension/chromium/filters.json...
Done
Download https://filters.adtidy.org/extension/chromium/filters_i18n.js...
Done
Download https://filters.adtidy.org/extension/chromium/filters/1.txt...
Wrong checksum: found b/w/uOkTbdVY4URauoUTRQ, expected XM+Ok/4cehM54qr6NC9cDA
Error: Wrong checksum: found b/w/uOkTbdVY4URauoUTRQ, expected XM+Ok/4cehM54qr6NC9cDA
```

### Expected Behavior

Able to download filters by running `yarn resources`

### Actual Behavior

A checksum error prevents lists form being downloaded.

### Additional Information

Branch: master
Node: v16.13.1
Yarn: 1.22.18

**Comment by maximtop** [comment]
Thank you! We will take a look.

**Comment by maximtop** [comment]
Should be fixed on the side of the filters.
