### ISSUE TITLE
regex filter doesn't work on extension 4.1.22

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/AdguardBrowserExtension#2182]
This rule was hiding a lot of the episodes at https://www.zdf.de/kinder/loewenzahn with previous version, with this new version not anymore. If I only put a single word into "contains" and remove regexp / at start and end, it works.

`zdf.de#?#.teaser-block-grid > article.b-content-teaser-item:has(> .inner > .box > p:contains(/Das verlorene Boot|Der Teufel mit der roten Kapuze|Elvis verzweifelt gesucht|Der extra scharfe Wettstreit|Die große Rolle|Die superschlaue Mini-Sau|Das wichtigste Rennen|Im Rausch der Lüfte|Zeitreise in Bärstadt|Plötzlich Großfamilie|Das Weihnachtsabenteuer|Der geheimnisvolle Magier|Magische Spurensuche|Die verrückte Entführung|Der glänzende Traum|Das neue Zuhause|Eine Rampe für die Rollis|Im Labyrinth der Bäume|Die unglaubliche Geschichte|Eiskalte Tricks|Das alte Rätsel|Alarm im Stadtwald|Die starke Band|Gänsehaut garantiert!|Das Orakel von Bärstadt|Die große Flucht|Rätselhafte Spuren|Der bunte Haufen|Die beste Bande|Die sagenhafte Leckerei| Das große Los|Rettung am Wasserloch|Nachts in der Savanne|Die geniale Verbindung|Der falsche Wilderer|Entführung bei Nacht|Ab in die Wildnis|Auf furchtloser Fährte|Ein Schwein bricht ein|Die tollkühne Blitzjagd|Minoos Reise zum Mars|Nichts für schwache Nerven|Rivalen im Wind|Der Schatz des Piraten|Der rettende Damm|Die verwunschene Puppe|Der heftige Sturz|Das schlaue Wunder|Ausreißer im Wollpelz|Auf Fährtensuche im Wald|Der verrückte Diebstahl|Die verschwundene Diva|Blick in unendliche Weiten|Das große Fressen|Peter klettert in den Bergen|Geheimnisvolle Botschaften|Peter und das Biest vom Bärensee|Der vergessene Freund|Ein harter Schwindel|Peter jagt den Dieb|Brandstifter in Bärstadt|Rettet die Königin|Peter entdeckt den Jäger der Nacht|Verloren in weiten Lüften|Die schweißtreibende Suche|Peter sieht scharf|Vernebelte Sicht|Knochenbruch beim Pokalspiel|Der schlaue Tausch|Das knallharte Trainingscamp|Das Wunder von Bärstadt|Der Baum auf dem Büdchen|Die gefälschte Venus|Kampf der vollen Tonne|Ein Gas unter Druck|Schatzsuche im Gehölz|Das Rätsel der alten Mühle|Der grüne Fußabdruck|Wettlauf gegen die Zeit|Der Schatz im Schrott|Erste Hilfe für die Milch|Abenteuer in Südafrika|Urtiere in Gefahr|Über alle Hindernisse|Der unschlagbare Löwenzahn|Eine dolle Knolle|Der Raub der Honigmacher|Jagd auf den Lurch|Grüne Wildnis in Gefahr|Die Sphinx von Bärstadt|Schwarmalarm in Bärstadt|Die neue Schule|Kleckern, schleckern, einfach lecker|Einsatz für die Wildwiese|Die wundersame Verwandlung|Freundschaft in Not|Schatzjagd mit dem GPS|Peters kommt auf den Hund|Mit Liebe gemacht|Der falsche Hase|Das glitzernde Geheimnis|Besuch aus dem Kosmos|Wenn die Flut kommt|Die tückische Täuschung|Peter und der Tanz der Vampire|Peter und die Killerpilze|Der unsichtbare Diebstahl|Peter will ne Minikuh|Ein unmögliches Angebot|Peters Stimme wird gestimmt|Buddeln in Bärstadt|Die verzauberten Nüsse|Ein Plattfuß kommt selten allein|Der galaktische Wunderschuh|Heimlicher Besuch|Das Phantom im Wald|Die fremde Oma|Die Jagd im Netz|Das entführte Schlauto|Kleine Räuber, große Hilfe|Der Weg der roten Hose|Tumult am Teich|Wikinger in Bärstadt|Alles für die Füße|Wer sprayt, der fliegt!|Leben am seidenen Faden|Der letzte Saurier|Entflammendes Spiel|Das geraubte Blau|Der geheimnisvolle Dreh|Der Doppelgänger|Der listige Jäger|Verfolgung in der Unterwelt|Das Ungeheuer von Bärstadt|Ein Lied für Bärstadt|Der Schwindel im Labyrinth|Saubere Lösung fürs Finale|Das Gespenst von Greifenklau|Die Letzte ihrer Art|Rätselhafte Rufe|Die verflixte Landung|Bei Peter staubt's|Diebesgut im Elchwinkel|Nachbar Paschulke als Retter in der Not.|Spuk am Bauwagen|Der falsche Verdacht|Peter wird hereingelegt.|Das verflixte Treffen|Das wilde Jucken|Peter Lustig verlässt Bärstadt!|Erschütterung am Bauwagen|Wenn aus Nachbarn Freunde werden|Hühner sind musikalisch|Der unheimliche Biss|Spuk im Bärstadtwald|Peter beißt zu|Der knallrote Kuchen|Kleiner Happen, große Wirkung|Peter segelt gegen den Wind|Die wilde WG|Geheimaktion im Geisterhaus|Willkommen im Bauwagen|Peter und die Kupferkanne|In Fritz' Garten lebt ein Stacheltier|Der Schatz der Vergangenheit|Das große Gackern|Die Hagelkanone|Peters Müll-Tour|Der Geist aus dem Matsch|Diebstahl im tiefen Grün|Peter versinkt im Moor|Die weltbeste Kraftmaschine|Peters süßes Geheimnis|Streuner auf samtigen Pfoten|Biber in Bärstadt|Das geheime Rezept|Eisschock im Elchwinkel|Peter und der Geist der Marksburg|Der heimliche Helfer|Peter und die Perlmuschel|Der richtige Dreh|Die zündende Idee|Das galaktische Grundstück|Von Pillendrehern und Totengräbern|Das riskante Rennen|Warum hat der Hund vier Beine?|Verfolgung auf zwei Rädern|Der weltbeste Dünger|Pelziger Besuch|Peter und die Wölfe|Ein Fischfresser auf Landgang|Peter braucht Mist|Die giftgrüne Wunderalge|Eine folgenreiche Verwechslung|Peters Boot ist nicht von Pappe|Die Jagd nach dem Lichtschwert|Geheimnisvolles Heulen|Peter schickt ein Licht ins All|Fritz Fuchs rettet den Bauwagen!|Keks ist verschwunden|Der Unkrautgärtner|Das heiße Abenteuer|Der unsichtbare Untermieter|Rettung auf den letzten Seiten|Der Prinz vom matschigen Tümpel|Gefährliche Grabung|Das unglaubliche Himmelsblau|Durstig in Bärstadt|Peter sucht das Wattenmeer|Unheimliche Verbindung|Verräterische Spuren|Dicke Backen in Bärstadt|Der rettende Sprung|Geheimnisvolle Verstecke|Der doppelte Durchblick|Der traumhafte Helfer|Gold aus Mist gemacht|Das falsche Rot|Verirrt im Schnee|Meter und Maße|Die unglaubliche Maschine|Stacheltiere in Gefahr|Hochspannung am Bauwagen|Zeitreise in Bärstadt|Die Jagd im Netz|Der rätselhafte Gast|Das fliegende Auge|Die rätselhafte Zahlenjagd|Technik aus der Natur|Das Konzert im Dunkeln|Eine Mühle dreht durch|Spuk an Bord|Das Geheimnis der Flosse|Expedition Drachenzahn|Das Rätsel der Flosse|Der Beschützer der Brennnesseln|Die allerlustigste Geburtstagsparty|Peter steht im Wald|Technik aus Natur|Sensation am See|Strom für die Finsternis|Nestsuche für den Nachwuchs|Bucht der versunkenen Schätze|Der Karpfenräuber|Peters Höhenflug|Im Zauber der magischen Kraft|Karibische Klänge in Bärstadt|Dicke Luft im Kiosk|Heißes Pflaster in Bärstadt|Peter und das Geheimnis der Schlange|Peter und die Kraft im Draht|Peter staut das Wasser|Der weiße Wunderstoff/))`

**Comment by Alex-302** [comment]
Which browser and version?

**Comment by BlazDT** [comment]
Latest Chrome version

**Comment by AdamWr** [comment]
Maybe it's related to this - https://github.com/AdguardTeam/ExtendedCss/issues/149, though it's weird that it works if regex is not used.
Does it work if you change `:has` to `:-abp-has`?

**Comment by BlazDT** [comment]
With :`-abp-has` it works fine on Chrome 105.0.5195.54

**Comment by maximtop** [comment]
Can't reproduce in the v4.2.159
