### ISSUE TITLE
The app is more likely a virus or has a vulnerability to one.

### ISSUE THREAD

**Issue by FoxGamingYTCR** [AdguardTeam/AdguardBrowserExtension#2184]
AdGuard: latest version 7.10.2
Firefox: 104.0.1
windows 10
filters on: ad block, hide your search query, do not track, URL tracking remover, auto language filters, self destruction of 3rd party cookies, 1st party cookie self destruction, disable cache of 3rd party cookies, block webrc, block push API, block location API, block flash, hide referrer, remove x client data, protect from dpi, hide ip, hide user agent, all browsing security, dns protection (dns over https), adguard extra, popup blocker, web of trust (WOT), traffic filtering and all https filtering, 
filters off: do not block search ads and self promotion, 3rd party authorization header, everything but turn off advertising id, browser assistant and use adguard as proxy, 
extensions: adguard adblocker, advanced profanity filter, avast online security and privacy, avast safeprive, honey, unpaywall, noscript, YouTube auto like, no coin, fastforward, foxyproxy, disable webrtc, clearurls, localcdn, decentraleyes and privacy badger. (I have more  but still)

I was hoping it would work lovely, easy to use like the extension, perfectly safe.

avast one detected 3 files that were viruses and blocked access to websites (showed certification errors and unable to connect securely.

Screenshot:
![Capture](https://user-images.githubusercontent.com/105371123/188503954-6a6fe066-5a4c-4fb8-bf88-32a033a9d02f.PNG)
![Capture2](https://user-images.githubusercontent.com/105371123/188504154-b9bd1379-f7a2-4cd9-8d3e-aa55facdfdab.PNG)
![Capture3](https://user-images.githubusercontent.com/105371123/188504485-7b1f71f9-ff89-47db-9d8b-4f84471ec3b4.PNG)
![Capture4](https://user-images.githubusercontent.com/105371123/188504486-f8ce511d-2c3b-41fe-a178-80468fc012c4.PNG)
![Capture5](https://user-images.githubusercontent.com/105371123/188504490-15d29a0a-5b1f-427b-b563-27dccc15e45d.PNG)

**Comment by FoxGamingYTCR** [comment]
https://www.youtube.com/watch?v=ULQbv04dnZ4 I have posted a video of this  on YouTube.

**Comment by maximtop** [comment]
Issue moved to [AdguardTeam/AdguardForWindows #4408](https://github.com/AdguardTeam/AdguardForWindows/issues/4408) via [**Zenhub**](https://www.zenhub.com/)
