### ISSUE TITLE
[Question] Company VPN is blocking filter updates (adtidy.org)

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdguardBrowserExtension#2185]
The company I work for uses a VPN which block's AdGuard from doing filter updates. The domain adtidy.org which gets called during the update process is blocked (_Error updating filters Failed to get updates. Please try again later._) as the VPN company has labelled it as shareware.
I cannot request this to be unblocked, so am unable to do any filter updates for the AdGuard extension.

Last time the filters were updated was the 2nd AUG 2022, and the extension was re-installed today.

Is there any other way for me to update these filters?

**Comment by maximtop** [comment]
Hi, there are no other ways to update filters, except wait until the extension will be updated or you can host filters on your own server and add them via custom filters.
