### ISSUE TITLE
Paramount+

### ISSUE THREAD

**Issue by m2c2lure67** [AdguardTeam/AdguardBrowserExtension#2188]
It was working for ParamountPlus.com, but now it's not.:
error code: 111

**Comment by maximtop** [comment]
Is it working without extension, have you tried to disable filters, remove userrules or reset settings?

**Comment by Birbber** [comment]
@m2c2lure67 Any news on that?

**Comment by m2c2lure67** [comment]
Sorry.  It looks like it was the last Chrome update, and seems to have resolved with your last update(s).
