### ISSUE TITLE
Extension doesn't inject scripts into frame in the Firefox on welt.de

### ISSUE THREAD

**Issue by Morku** [AdguardTeam/AdguardBrowserExtension#2190]
### Issue Details

- **AdGuard version:**
  -  AdGuard 4.1.22
- **Browser and version:**
  -  Firefox 104.0.2
- **Operating system and version:**
  -  Windows 11 Build 22000.978
- **Filters you use in AdGuard:**
  -  Base, Mobile, URL-Tracking, Tracking, Social, Annoyance, German
- **Stealth Mode settings:**
  -  Tracker, Tracker-param, hide search, donottrack, hide referrer
- **Other browser extensions:**
  -  AdGuard Extra

For some reason, some filtering rules, noticable for Cookie Pop-ups are not performed in the Extension for Firefox.

Examples:

https://www.heise.de/

<details><summary>Screenshot:</summary>

![grafik](https://user-images.githubusercontent.com/6276915/190455904-fc67bd61-cb0c-4d71-901d-f5abaa7d5760.png)

</details><br/>

`cmp.heise.de#%#AG_onLoad(function(){if(window.location.href.includes("consentUUID")){var g=new MutationObserver(function(){var b=document.querySelector('button[title*="ustimmen"]');b&&(g.disconnect(),b.click())});g.observe(document,{childList:!0,subtree:!0});setTimeout(function(){g.disconnect()},1E4)}});`

https://www.computerbase.de/

<details><summary>Screenshot:</summary>

![grafik](https://user-images.githubusercontent.com/6276915/190456091-66a5155d-5885-4226-9260-1aa25534f286.png)

</details><br/>

`computerbase.de#%#AG_onLoad(function(){if(-1==document.cookie.indexOf("OptanonAlertBoxClosed") || -1==document.cookie.indexOf("consent") ){var a=new MutationObserver(function(){var b=document.querySelector("dialog.js-consent"),d=document.querySelector("body.consent-dialog-open");c=document.querySelector(".consent__options .js-consent-accept-button");b&&d&&c&&(a.disconnect(),c.click(),d.classList.remove("accept-cookies-button"),b.style="display: none !important;")});a.observe(document,{childList:!0,subtree:!0});setTimeout(function(){a.disconnect()},1E4)}});`

https://www.welt.de/

<details><summary>Screenshot:</summary>

![grafik](https://user-images.githubusercontent.com/6276915/190456152-6c5ce0cf-3a82-45d4-853e-8dcfbce39859.png)

</details><br/>

`cmp.wowtv.de,sourcepoint.tvnow.de,cmp2.freiepresse.de,cmp-sp.neuepresse.de,cdn.privacy-mgmt.com,cmp.techbook.de#%#AG_onLoad(function() {var b=new MutationObserver(function() {var c=document.querySelector('button[title="Alle akzeptieren"]'); c&&(b.disconnect(),c.click()) });b.observe(document, {childList: !0,subtree: !0});setTimeout(function() {b.disconnect()}, 1E4)});`

When I use Firefox with AdGuard for Windows, I don't have the issue. All 3 Pop-ups are autoclicked fine.
Also when I use a Chromium based browser with Extension, it works fine.
It's only Firefox+Extension.

I can reproduce the issue on a fresh browser profile, different systems, in a vm, so there is something not working in the extension.
There is also no limitation for Firefox, since the Extension [I don't care about cookies](https://addons.mozilla.org/de/firefox/addon/i-dont-care-about-cookies/) can bypass all 3 examples fine.

Attached my settings.

[20220915_170249_adg_ext_settings_4.1.22.zip](https://github.com/AdguardTeam/AdguardBrowserExtension/files/9577623/20220915_170249_adg_ext_settings_4.1.22.zip)

**Comment by maximtop** [comment]
Hi! What do you mean by works unreliable?

I've pasted this rule in user rules
```
cmp.heise.de#%#AG_onLoad(function(){if(window.location.href.includes("consentUUID")){var g=new MutationObserver(function(){var b=document.querySelector('button[title*="ustimmen"]');b&&(g.disconnect(),b.click())});g.observe(document,{childList:!0,subtree:!0});setTimeout(function(){g.disconnect()},1E4)}});
```
Navigated to https://www.heise.de, and cookie consent was clicked.

This rule won't work if added via custom filters, because Firefox policy doesn't allow remote scripts to be executed in the extension. Still, it would work if added to the embedded filters with a new version of the extension.

**Comment by Morku** [comment]
Hi,

you are right. If I paste the heise.de filter into custom filter as single rule, it's working for me as well.
Same for the computerbase rule.

When I paste the welt.de Cookie rule into custom filter, it's not working even then.

See the following video:


https://user-images.githubusercontent.com/6276915/190592159-41a6666b-73d1-4761-9d6c-fdbf67033c5c.mp4



However, all 3 rules are part of AdGuard Annoyance filterlist where I copied out.

Now, see another video where I past all 3 filter rules into the customer user rules:


https://user-images.githubusercontent.com/6276915/190592966-7e846ccd-e892-4e45-9cff-917ba729e842.mp4



For whatever reason, only the Computerbase clicking rule worked in this try. The heise Pop-up which was working before in user rules stopped working.
The welt.de Pop-up filter rule never works at any try and configuration.

Thats what I mean by **unreliable**. The Chromium extension doesn't have that issue at all.

**Comment by Morku** [comment]
I don't have the deep technical knowledge to understand, why it's not working in Firefox. It's my observation.
And if it is a limitation or bug by Firefox, I still don't understand, why heise.de and computerbase.de only works when I put the filter rule in custom rules when it's already in Annoyance filters.

It should always work, like when put in custom filters. And I probably will find other pages where it doesn't work as well. So for me, it's not just a welt.de issue.

Also "I don't care about cookies" also prove that autoclicking does work for 100% for all 3 pages in Firefox.

I have done your steps and thats the result. Hope I have done correctly:

<details><summary>Screenshots:</summary>

![welt0](https://user-images.githubusercontent.com/6276915/190641529-ba6dfcae-25c7-423c-8b4e-ac88c8e2ef4b.png)

![welt1](https://user-images.githubusercontent.com/6276915/190641549-6323b0be-ccb4-4c1f-a2a0-354ae5395ffd.png)

![welt2](https://user-images.githubusercontent.com/6276915/190641561-d836b7d4-a87f-457d-9076-5d375900db8d.png)


</details><br/>

**Comment by maximtop** [comment]
Looks like the same bug occurs for these websites sometimes too. I was able to reproduce it on other websites.
