### ISSUE TITLE
`:hover` buttons should be less bright (contrast) in dark mode

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdguardBrowserExtension#2191]
### Issue Details

- **AdGuard version:**
  - 4.1.22
- **Browser and version:**
  - Chrome 105
- **Operating system and version:**
  - macOS 12.6
- **Filters you use in AdGuard:**
  - .
- **Stealth Mode settings:**
  - .
- **Other browser extensions:**
  - .

### Expected Behavior

`:hover` buttons with `select__item` class are slightly brighter (contrasted) in dark mode

### Actual Behavior

`:hover` buttons with `select__item` class are much brighter (contrasted) in dark mode

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/19418601/182902892-977a3bd8-1e7f-4ef2-9867-d39f02f11ed0.png)

</details>

### Additional Information

https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2137#issuecomment-1205490904

**Comment by kaprielov** [comment]
We already have same issue 
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2137#issuecomment-1233282873

**Comment by rakleed** [comment]
@kaprielov but you closed that issue and marked it as fixed. And you don't respond to my comments.

**Comment by kaprielov** [comment]
@rakleed You can expect this fix in the next release version
