### ISSUE TITLE
Buttons "Total" and "Last week" in statistics tab doesnt match to the selected extensions theme 

### ISSUE THREAD

**Issue by mozartinio** [AdguardTeam/AdguardBrowserExtension#2193]
### Issue Details

Buttons "Total" and "Last week" in statistics tab doesnt match to the selected extensions theme 

### Expected Behavior

Buttons have to be the same color as chosen in the extension 

### Actual Behavior

Buttons "Total" and "Last week" in statistics tab doesnt match to the selected extensions theme 

### Screenshots
![tabs](https://user-images.githubusercontent.com/107266093/191083725-b0415e8b-ef78-4019-b900-bdce12c25365.png)

**Comment by maximtop** [comment]
Seems to be fixed in the v4.2.159
