### ISSUE TITLE
Rakuten Canada cashback links were being blocked

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/AdguardBrowserExtension#2196]
@m4848 commented on [Fri Sep 23 2022](https://github.com/AdguardTeam/AdguardFilters/issues/130494)

### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.22

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.rakuten.ca/static/cashback-shopping-whitelist?

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

1. <comment>

2. Screenshots
<details><summary>Screenshot 1:</summary>

![image](https://user-images.githubusercontent.com/68094988/191974239-7b62ef1e-997b-4d63-b2cf-a2f3da68fb1d.png)
![image](https://user-images.githubusercontent.com/68094988/191974566-b23b1efb-bd2a-4e94-8b74-fece02c953a5.png)

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by maximtop** [comment]
duplicate https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1723
