### ISSUE TITLE
Use the same design in external rules editor, like in embed

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#2199]
<details>
<summary>Current</summary>

![image](https://user-images.githubusercontent.com/8361299/192529453-43380a10-1f2e-4777-9afb-cd9b84cca9aa.png)

</details>

<details>
<summary>Suggested(like internal, just without sidebar)</summary>

![image](https://user-images.githubusercontent.com/8361299/192529815-7849f5f2-1dca-4aee-bb04-2b159e1c411b.png)

</details>

**Comment by XX-J** [comment]
Тогда уж наоборот - внешний дизайн внутри - у него больше полезной (рабочей) площади.

**Comment by Alex-302** [comment]
При чём тут площадь? Речь про однообразие дизайна.

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/8361299/198294680-d32a1180-af97-4af9-b742-3c0bc1aff86b.png)


</details>

**Comment by XX-J** [comment]
> Речь про однообразие дизайна.

 Я - за однообразие дизайна, но такого, где рабочая область больше, а во внешнем - больше (хоть можно и ещё увеличить).

**Comment by Alex-302** [comment]
"Размер - не главное". На широкоформатном мониторе, например, будет видно много, но неудобно - всё будет у левого края экрана.

**Comment by XX-J** [comment]
Как я понял ты предлагаешь добавить шапку с выключателем к внешнему редактору правил, чтобы он был похож на встроенный. От этого сократится вертикально видимое поле для редактирования. Я же - за максимально видимое поле редактирования - удобство превыше дизайна.

 Но если дизайн встроенного редактора будет таким же как и внешнего, т.е. без шапки - я не против.

> На широкоформатном мониторе, например, будет видно много, но неудобно - всё будет у левого края экрана.

 Если неудобно "у левого края", то можно пользоваться встроенным редактором - там же слева панель, своеобразный "отступ".
