### ISSUE TITLE
||github.com^$document and ^$document,redirect=noopframe doesn't work

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardBrowserExtension#2205]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - AdGuard v4.1.36
- **Browser and version:**
  - Chrome 106
- **Operating system and version:**
  - Windows 10
- **Filters you use in AdGuard:**
  - Adguard Base filter, URL Tracking filter, Tracking Protection filter, Social Media filter, Annoyances filter, Russian filter

**Comment by maximtop** [comment]
can't reproduce
