### ISSUE TITLE
bug opening links in firefox

### ISSUE THREAD

**Issue by fretere** [AdguardTeam/AdguardBrowserExtension#2211]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  -  4.1.37
- **Browser and version:**
  -  Firefox 105.0.3 and Chromium 106.0.5249.119 
- **Operating system and version:**
  -  Linux Manjaro
- **Filters you use in AdGuard:**
  -  all except customize
- **Stealth Mode settings:**
  - no
- **Other browser extensions:**
  -  tampermonkey, privacy badger

### Expected Behavior

 open link when i click

### Actual Behavior

 in some websites, clicking link doesn't work

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

I recently noticed a problem with some html links. I click on the link but nothing happens (I see a vain attempt to open the link in a new tab but adquard blocks it).

When I deactivate the application, it works again (deactivating the application for the site in question does not work; you have to deactivate the extension completely).
I have seen this with k2s or rapidgator links; on the other hand, filejoker or fileboom links work without any problem.

**Comment by maximtop** [comment]
@fretere Hi! Thank you for reaching us. Could you please specify websites and links which are blocked from clicking?
Can it be reproduced with all filters disabled?

**Comment by fretere** [comment]
Hi, thanks for answering ;)
An example: https://ed-protect.org/NxFcj (you have to click on "afficher les liens") then on the uptobox link.

I disabled all filters and it solved the problem; i eventually found which one who is "guilty", it's the language specific (the penultimate just above customize).
I deactivate this one from now on.

**Comment by 256shadesofgrey** [comment]
I observe the same behavior on chrome, so this bug is not firefox specific.

**Comment by fretere** [comment]
You're right, i've updated the first message. ;)

**Comment by maximtop** [comment]
> I disabled all filters and it solved the problem; i eventually found which one who is "guilty", it's the language specific (the penultimate just above customize).

It is a filter issue, there is nothing to do with the extension. Please fill free to fill filters issues via the reports tool https://reports.adguard.com/en/new_issue.html

I'm closing this issue. If you have any other issues or questions, please feel free to ask.
