### ISSUE TITLE
Adguard bug report language specific stop you from ctrl click 

### ISSUE THREAD

**Issue by asaf3023** [AdguardTeam/AdguardBrowserExtension#2212]
### Steps to reproduce

1.Turn on Adguard french filter in language specific Filters
2.you cant ctrl, middle left click and open a new tab with the menu on some websites (im trying to ctrl open https://9anime.to )
3. done

### Expected behavior
open a new tab for the link you clicked on

### Actual behavior
it open for maybe a second a tab and closes it really fast

<details><summary>Screenshot:</summary>

 https://youtu.be/YUh7TPDOjHU

</details>

### Customer ID 
 i didnt get a customer id from reporting it through the application but i did get a ticket number my ticket number is 665593

### Your environment

* Environment name and version: (e.g. Firefox 106.0.1 (64 bits))
* Operating system and version: (e.g. Windows 10 Pro, v. 21H1, build 19043.2006, Experience  Windows Feature Experience Pack 120.2212.4180.0)

 i hope you have a good day :)

**Comment by maximtop** [comment]
Issue moved to [AdguardTeam/AdguardFilters #132769](https://github.com/AdguardTeam/AdguardFilters/issues/132769) via [**Zenhub**](https://www.zenhub.com/)

**Comment by maximtop** [comment]
It looks like this issue is related to filters, also I suggest you update your bookmark link to https://9anime.to/home
