### ISSUE TITLE
Impossible to select text in the filtering log

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#2214]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:** 4.1.39
  - 
- **Browser and version:** Chrome 106.0.5249.119 
  - 
- **Operating system and version:** Windows 10
  - 
- **Filters you use in AdGuard:** Base filter, Social filter, etc
  - 
- **Stealth Mode settings:** all
  - 
- **Other browser extensions:** no
  - 

### Expected Behavior

Text can be selected.

### Actual Behavior

Inpossible to select text in the filtering log, except details tab.

**Comment by ameshkov** [comment]
Discussed this, duplicates https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1251
