### ISSUE TITLE
Hover is not removed from the update button

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#2215]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:** 4.1.36
  - 
- **Browser and version:** Firefox 
  - 
- **Operating system and version:** Android 13
  - 

### Actual Behavior

After checking for updates using a button on the main screen, hover is added and not removed.

**Comment by maximtop** [comment]
Do you mean that the hover effect should be removed from this button while the extension is checking for updates?
https://uploads.adguard.org/Image_2023-08-28_13-01-47.png

**Comment by Alex-302** [comment]
No. It just didn't disappear. It is ok now.

**Comment by maximtop** [comment]
Ok, I'm closing the issue now.
