### ISSUE TITLE
Не повторяется. Попробуйте обновить фильтры, а затем перезапустить контент блокеры в настройках Сафари - сперва нужно подождать примерно минуту на их применение, а затем открыть сайт.

### ISSUE THREAD

**Issue by innervisionteam** [AdguardTeam/AdguardBrowserExtension#2217]
Не повторяется. Попробуйте обновить фильтры, а затем перезапустить контент блокеры в настройках Сафари - сперва нужно подождать примерно минуту на их применение, а затем открыть сайт.

_Originally posted by @zloyden in https://github.com/AdguardTeam/AdguardFilters/issues/133295#issuecomment-1293099468_

**Comment by innervisionteam** [comment]
Не помогло. Фильтры обновлены и контент блокеры перезапущены. Ждал около 5 минут и затем перезапустил сайт. Проблема не пропала.

**Comment by maximtop** [comment]
сафари расширение в другом репозитории https://github.com/AdguardTeam/AdGuardForSafari
