### ISSUE TITLE
Issue with protection on Firefox [Android]

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/AdguardBrowserExtension#2228]
@adguard-bot commented on [Mon Nov 14 2022](https://github.com/AdguardTeam/AdguardFilters/issues/134879)

### Issue URL (Incorrect Blocking)
 [https://example.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fexample.com%2F)
### Comment
> adguard disable won't work,it will auto reopen without or with reload.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/cfwQnjE.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/X47GSZA.jpg)
</details>
<details>
  <summary>Screenshot 3</summary>

  ![Screenshot 3](https://reports-img.adguard.com/Cw2009f.jpg)
</details>
<details>
  <summary>Screenshot 4</summary>

  ![Screenshot 4](https://reports-img.adguard.com/kNAqZh1.jpg)
</details>
<details>
  <summary>Screenshot 5</summary>

  ![Screenshot 5](https://reports-img.adguard.com/5tbjhrM.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v4.1.39
Browser: | Firefox
Stealth mode: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/>AdGuard URL Tracking, <br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/>AdGuard Chinese

---

@DandelionSprout commented on [Tue Nov 15 2022](https://github.com/AdguardTeam/AdguardFilters/issues/134879#issuecomment-1315153357)

It was news to me that Firefox (re-?)added an extension popout menu in the Android version. Which Firefox version number do you use?

---

@zloyden commented on [Tue Nov 15 2022](https://github.com/AdguardTeam/AdguardFilters/issues/134879#issuecomment-1315157477)

> adguard disable won't work,it will auto reopen without or with reload.

Not related to the filters.
I'll move this task to another repo.

**Comment by maximtop** [comment]
From screenshots, it is not clear what is not working.
On my side disabling protection works correctly. Can be checked by adding some cosmetic rules.

**Comment by maximtop** [comment]
Feel free to add more information.
