### ISSUE TITLE
Adguard does not inject CSS into disqus iframe

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#223]
All the details are here:
http://forum.adguard.com/showthread.php?10411-Block-Disqus-related-articles-on-other-sites

**Comment by Mizzick** [comment]
works fine with
`||disqus.com^$third-party`

**Comment by ameshkov** [comment]
@Mizzick I am talking about Adguard's CSS, not about blocking the whole frame.

**Comment by ameshkov** [comment]
In that forum thread the problem was with the rule `disqus.com###placement-bottom`

**Comment by Mizzick** [comment]
So how should it work then?

**Comment by ameshkov** [comment]
In theory it should be added by content script. The problem is that AG styles aren't added for disqus iframe.

I think the problem is in the frame size (we don't process small frames), as at first disqus frame is too small.

**Comment by Mizzick** [comment]
Ah, ok, got it now.

**Comment by Mizzick** [comment]
Ok, I've tried now with 
`disqus.com###layout`

**Comment by ameshkov** [comment]
This change breaks the check purpose. window.outerWidth returns the size of the whole browser window (tab), so you'll inject the code into every frame, even the smallest.

**Comment by Mizzick** [comment]
Okay, for small frames from now we will load only small set of css excluding all generic css rules.
