### ISSUE TITLE
Adguard Extension leaks domain block

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardBrowserExtension#2231]
### AdGuard Extension version

4.1.39

### Browser version

Edge 107.0.1418.42

### OS version

Windows 11 22H2

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, Official Polish filters for AdBlock, uBlock Origin & AdGuard, Polish Social Filters, KAD - Anti-Scam, Polish Annoyances Filters, Polish Anti Adblock Filters, Others

### Issue Details

1Hosts Lite have rule `||info-eastflirts.com^`.
Adguard Extension leak this domain.

### Expected Behavior

Blocked domain.

### Additional Information

Even adding `||www.info-eastflirts.com^` to user rules does not fix this. Domain still open. 

See https://github.com/StevenBlack/hosts/commit/c270c20b3fdfacd75d63e92b57665c1390af6984

**Comment by maximtop** [comment]
If you want this domain to be blocked completely on opening it in new tab, then add rule `||info-eastflirts.com^$document`

**Comment by FadeMind** [comment]
Thank you @maximtop Closing.
