### ISSUE TITLE
NordVPN - Phising Browser Extension

### ISSUE THREAD

**Issue by MartinIIOT** [AdguardTeam/AdguardBrowserExtension#2235]
### AdGuard Extension version

4.1.46

### Browser version

Firefox 107.0

### OS version

Windows 11

### What filters do you have enabled?

AdGuard Base filter, EasyList, Others

### What Stealth Mode options do you have enabled?

Block trackers

### Issue Details

NordVPN block addon with "Phising" warning screen.

**Comment by mozartinio** [comment]
@MartinIIOT Hello! Please tell me more precisely what your problem is? Could you show your devtools console tab when you try to reproduce the issue

**Comment by MartinIIOT** [comment]
@mozartinio Hello! I will collect all the necessary data and deliver next week.

**Comment by MartinIIOT** [comment]
Hello,
after I reinstall Firefox (107.01) extension (4.1.46), problem not exist on my Win11... No warning on NordVPN 7.3.5.0 😄

**Comment by mozartinio** [comment]
@MartinIIOT Great!
So, I'm going to close this issue.
If the problem happens again you can reopen it

**Comment by krystian3w** [comment]
> you can reopen it

no possible without write access into repository (lack of label contributor, collaborator or public show github teams releated with AdGuard).

Or I missed magic words added to [adguard-bot](https://github.com/adguard-bot) like "I shall pass".

**Comment by maximtop** [comment]
as an option read `reopen it` as `open the new one`
