### ISSUE TITLE
Web resources are blocked

### ISSUE THREAD

**Issue by CurryChou777** [AdguardTeam/AdguardBrowserExtension#2236]
### AdGuard Extension version

4.1.46

### Browser version

Chrome 107

### OS version

macOS 10.15

### What filters do you have enabled?

No filters

### Issue Details

Recently, after I upgraded the version, I suddenly found that some websites could not be opened. After checking the reasons, I found that static resources were blocked.The request for the same domain name failed

### Screenshots

![image](https://user-images.githubusercontent.com/22877154/204210150-894320f9-011b-4efe-b69e-e4140fb2968c.png)

**Comment by maximtop** [comment]
Looks like the filter issue. Please report your issue here with more information https://reports.adguard.com/en/new_issue.html
