### ISSUE TITLE
Last version can't use *.domain.com ?

### ISSUE THREAD

**Issue by Witawat** [AdguardTeam/AdguardBrowserExtension#2239]
### AdGuard Extension version

4.1.46

### Browser version

Microsoft Edge 107.0.1418.62

### OS version

windows 10 64bit

### What filters do you have enabled?

No filters

### What Stealth Mode options do you have enabled?

Block trackers

### Issue Details

Last version can't use *.domain.com 
for allow subdomain shopping cart

**Comment by maximtop** [comment]
Are you talking about the allowlist?

**Comment by maximtop** [comment]
Closing this, in the favor of the previous task.
