### ISSUE TITLE
Specific element hiding exclusions doesn't work in Safari

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#224]
***Steps to reproduce:***
1. Add rule for hiding BODY  ```i.ua##body``` 
2. Add exclusion for unblocking ```i.ua#@#body```
3. Open i.ua
***Expected result:***
BODY is unblocked
***Actual result:*​**
BODY is not unblocked

The same issue is with Buffer extension - it is broken by rule from social filter ```~buffer.com###sharer```
exclusion doesn't help ```buffer.com#@##sharer```
only ```@@||buffer.com^$elemhide```(added to Safari filter now)
With Adguard:
<details> 
![](http://imagizer.imageshack.com/img922/1859/a0xTtQ.png)
</details>
without Adguard:
<details> 
![](http://imagizer.imageshack.com/img922/4869/ZUvyw5.png)
</details>

**Comment by Mizzick** [comment]
It works as expected.
But after you set a new rule - wait few moments for content blocker, it takes maybe few seconds to reset it with added rule.
Tested with i.ua and lenta.ru

**Comment by Alex-302** [comment]
Yes, my mistake. But exclusion still not works for Buffer extension. It opens on the page when you click on extension icon. Maybe it is a different case.
If you will test it, you should to disable social filter and add  ```buffer.com#@##sharer```
screenshots are in the first message.

**Comment by Mizzick** [comment]
I've tried buffer, but I saw a different site layout, maybe they changed it already?

**Comment by ameshkov** [comment]
@Alex-302 this may be caused by the Safari itself, who knows, maybe it just works differently for extensions?
