### ISSUE TITLE
Adguard suddenly breaks Chrome

### ISSUE THREAD

**Issue by JoeVertigo** [AdguardTeam/AdguardBrowserExtension#2242]
### AdGuard Extension version

4.1.46

### Browser version

Version 108.0.5359.99 (Official Build) (64-bit)

### OS version

Windows 10 Pro for Workstations 22H2 19045.2311

### What filters do you have enabled?

AdGuard Base filter

### Issue Details

Having the Adguard plugin enabled prevents any webpage from loading in chrome. Even whitelisted pages will not load. Disabling the plugin instantly returns functionality. No other plugins or combination of my plugins seem to effect the issue. Looking at recent reviews on the Chrome Web Store, other people have started having the same issue today (Friday, Dec 09, 2022).

### Expected Behavior

I expect webpages to load normally while the plugin is enabled.

**Comment by wysohn** [comment]
Experienced the same.

Pretty urgent since browser isn't responsive at all with this extension enabled.

Some kind of infinite loop or something as CPU load peaks with the extension enabled

**Comment by wysohn** [comment]
Nvm this is a duplicate

https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2240
