### ISSUE TITLE
Adguard use 100% CPU

### ISSUE THREAD

**Issue by fedor7** [AdguardTeam/AdguardBrowserExtension#2243]
### AdGuard Extension version

4.1.46

### Browser version

Firefox 107.0.1 (64 )

### OS version

Windows 10 22H2

### Issue Details

Adguard use 100% CPU. Firefox process manager show 100% CPU use in section Extentions.
Tabs are not loading content. Firefox is not working.
Disable Adguard is getting CPU free.

### Expected Behavior

normal use CPU

**Comment by maximtop** [comment]
Might it be related to this issue? 
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2240
