### ISSUE TITLE
Add direct links to AdGuard socials and AdGuard communities

### ISSUE THREAD

**Issue by kodiakhub** [AdguardTeam/AdguardBrowserExtension#2245]
### Issue Details

Hi, AdGuard should give importance to social media and communities in terms of the best efficiency for users & user to user shares.

<details><summary>Community information outdated:</summary>

- [AdGuard Browser Extension](https://chrome.google.com/webstore/detail/adguard-adblocker/bgnkhhnnamicmpeenaelnjfhikgbkllg?hl=en)

  - ![image](https://user-images.githubusercontent.com/56846906/206920165-9f6e95ce-b6e4-4188-8580-dc7d4e1cdadf.png)

Due to modern communities, forum usage is no longer as popular as it used to be.

</details><br/>
 
For AdGuard, there is a lack of community informations awareness for the latest developments and useful informations. Also, apart from the language support available, there are no community channels for different languages. Suppose that, only Google chrome extension has 10 million+ downloads. 50,000 users may need information about AdGuard in different languages for solidarity.

### Proposed solution

Firstly, AdGuard social media and AdGuard community links must be visibly added to all related to AdGuard apps.

<details><summary>For example screenshot:</summary>

![Example](https://user-images.githubusercontent.com/56846906/206920460-8b7dc32f-2545-4027-a1d6-b7227e92c305.png)

</details><br/>

Secondly, if there is a suitable place for all AdGuard related content to be easy accessibility and in solidarity with the modern community, it would be good to open a Discord server.

**Comment by mozartinio** [comment]
@kodiakhub Hello!
We would like to do but browsers have limitations that do not make it possible 
Maybe it can be done in other AdGuard products or at least we will try to realise it
