### ISSUE TITLE
cookie question not disappear

### ISSUE THREAD

**Issue by cedge2020** [AdguardTeam/AdguardBrowserExtension#2247]
### AdGuard Extension version

Versio 4.1.46

### Browser version

Microsoft Edge Versio 108.0.1462.46 (Virallinen koontiversio) (64-bittinen)

### OS version

windows 11

### What filters do you have enabled?

AdGuard Base filter, AdGuard Annoyances filter

### Issue Details

i see there at iltapulu. fi site,cookie question although ad guard on with enough settings?

![Verkkosieppaus_14-12-2022_161816_www iltapulu fi](https://user-images.githubusercontent.com/68057066/207621201-7f111cde-1869-4073-b6d6-593dbd78b41b.jpeg)

### Expected Behavior

i think ad guard then not notice all cookie questions?

### Screenshots

included before

**Comment by maximtop** [comment]
This is a filters issue, please fill report here 
https://reports.adguard.com/

Some fields can be filled automatically if you click this button
![image](https://user-images.githubusercontent.com/17272769/207622446-df3bc981-2d66-4e41-806a-df5916806803.png)
