### ISSUE TITLE
The rule cannot take effect

### ISSUE THREAD

**Issue by Emilia66666** [AdguardTeam/AdguardBrowserExtension#2248]
### Issue Details

![image](https://user-images.githubusercontent.com/86843239/208231634-a9ec4b06-fa2d-4573-b8a4-b6af50a0811c.png)
\w\w\w\w\w\w

and

[0-9][0-9][0-9][0-9][0-9][0-9]

Unable to match numbers properly    It can normally take effect on any other supported software

**Comment by maximtop** [comment]
These are not regular selectors and hiding rules do not support regexes. Look at [extended CSS selectors](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#extended-css-selectors), maybe there would be some suitable to you ways to hide elements.

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2254
https://github.com/AdguardTeam/AdguardFilters/issues/138626
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2248

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2254
https://github.com/AdguardTeam/AdguardFilters/issues/138626
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2248
