### ISSUE TITLE
$$ rules break encoding on some websites

### ISSUE THREAD

**Issue by Birbber** [AdguardTeam/AdguardBrowserExtension#2249]
### AdGuard Extension version

4.1.52

### Browser version

latest FireFox

### OS version

macos 12.4

### Issue Details

Add to user rules:
```
winfuture.de$$a[id="header_logo_link"]
eurointegration.com.ua$$div[class="main_logo"]
```

Result:
- [eurointegration.com.ua](http://eurointegration.com.ua/) logo is removed
- [winfuture.de](http://winfuture.de/) is broken by this rule

**Comment by krystian3w** [comment]
Both use problematic: charset=iso-8859-1 / charset=windows-1251.
