### ISSUE TITLE
Highlighting some elements with assistant makes them disappear

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardBrowserExtension#225]
http://rufilm.tv/films/kievskiy-tort-smotret-onlayn.html - for example, when you highlight the player with Element blocker tool, the player disappears.

Another issue on the same website (as an example): Adguard icon and 'cross' to close the previewer are not visible.

Screenshot to illustrate:
http://i7.5cm.ru/i/huLg.png

Originally from http://forum.adguard.com/showthread.php?10454

**Comment by Mizzick** [comment]
We have to test it with new assistant interface.
