### ISSUE TITLE
Report firefox mobile instead of firefox

### ISSUE THREAD

**Issue by User6751** [AdguardTeam/AdguardBrowserExtension#2250]
### AdGuard Extension version

4.1.52

### Browser version

Firefox Mobile 108.1.0

### OS version

Android 10

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Chinese filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Issue Details

the report issue function will auto fill the field as Firefox

### Expected Behavior

it should use Firefox Mobile instead

### Screenshots

![Screenshot_20221222-205838_Firefox](https://user-images.githubusercontent.com/120245025/209139512-6edebdde-b46e-4d24-8dfd-fbd1a3821d03.jpg)
![Screenshot_20221222-205848_Firefox](https://user-images.githubusercontent.com/120245025/209139522-d0996f4b-1f94-4cc5-a5c7-146938326a91.jpg)

**Comment by mozartinio** [comment]
@User6751 Hello!
Thank you!
