### ISSUE TITLE
Allowlist in adguard firefox plugins is not working

### ISSUE THREAD

**Issue by pekkle-hksar** [AdguardTeam/AdguardBrowserExtension#2253]
### AdGuard Extension version

Version 4.1.53

### Browser version

Firefox 108.0.1 (64-bit)

### OS version

Windows 10

### What filters do you have enabled?

AdGuard Base filter, AdGuard Chinese filter, AdGuard Japanese filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, Others

### Issue Details

there is a rule in AdRules AdBlock List (https://github.com/Cats-Team/AdRules/blob/main/adblock.txt)
||s.yimg.com^

there is an allowlist rule in AdRules Allow Domains List (https://github.com/Cats-Team/AdRules/blob/main/allow-domains-list.txt)
s.yimg.com

However, when browsing https://hk.yahoo.com, many pictures of news are still being blocked. Checked the filter log, the allowlist is not effective.

Please help to check.

### Expected Behavior

news pictures in https://hk.yahoo.com should not be blocked
e.g. https://s.yimg.com/uu/api/res/1.2/uzHg5GklFn6IL_ffmuMfoQ--~B/Zmk9ZmlsbDtoPTM4ODtweW9mZj0wO3c9NzIwO2FwcGlkPXl0YWNoeW9u/https://s.yimg.com/os/creatr-uploaded-images/2022-12/f1bbd080-8640-11ed-9ffd-67c706e60972.cf.webp

**Comment by maximtop** [comment]
Allowlist unblocks all requests on the website. If you want to unblock specific requests use exception rules with `@@`.
https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#exceptions-modifiers

**Comment by pekkle-hksar** [comment]
![image](https://user-images.githubusercontent.com/6582068/209786012-b9a04741-e4f1-463a-b43f-3d801296ba5e.png)
Tested to add @@ in Allow List, and it is not working.

What is the usage of the Allow List then?

**Comment by pekkle-hksar** [comment]
added @@||s.yimg.com^ to User Rules and could unblock the pictures.
However, the Allow List is not working as tall.

**Comment by pekkle-hksar** [comment]
@maximtop could kindly help to review and reopen the issue

**Comment by maximtop** [comment]
Allowlist should be used when you want to unblock the whole website.
For example, if you want ads not to be blocked on `https://hk.yahoo.com` you should add `hk.yahoo.com` to the allowlist.
All information can be found in the knowledge base https://kb.adguard.com/en/browser-extensions/overview#allowlist

**Comment by pekkle-hksar** [comment]
got it, thanks a lot
