### ISSUE TITLE
The website changes at any time. The interceptor doesn't work

### ISSUE THREAD

**Issue by Emilia66666** [AdguardTeam/AdguardBrowserExtension#2254]
### Issue Details

![image](https://user-images.githubusercontent.com/86843239/209788968-a098e2fd-868b-4812-8554-08abb8baf50c.png)

The website changes at any time. The interceptor doesn't work
How can I write rules to prevent

**Comment by mozartinio** [comment]
@Emilia66666 Hi!
Issue reported to the wrong repository
You need to report it here https://github.com/AdguardTeam/AdguardFilters

**Comment by krystian3w** [comment]
But what happend if user tries block something out of scope by AdguardFilters? You will redirect then to adguard support forum?

**Comment by krystian3w** [comment]
@Emilia66666 try change `post-id-ble-ble-ble` to:

`[id^="post-"]`

**Comment by krystian3w** [comment]
github.com/AdguardTeam/AdguardFilters/issues/138626

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2254
https://github.com/AdguardTeam/AdguardFilters/issues/138626
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2248
