### ISSUE TITLE
The filters cannot be updated

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/AdguardBrowserExtension#2257]
@zloyden I try but your extension cannot update. There are many customer who using your extension with any settings.
![Screen Shot 2022-12-29 at 21 43 29](https://user-images.githubusercontent.com/73129281/209969456-610b3028-3cf4-440a-a3fe-5a19709ffe8f.png)

_Originally posted by @devdiary2203 in https://github.com/AdguardTeam/AdguardFilters/issues/138654#issuecomment-1367380684_

**Comment by mstfcbngl** [comment]
I also having this issue with Opera GX and Chrome. I'm using extension with "On certain sites" setting not "On all sites" which I think it's cause this issue. I hoping it can be fixable thing and fix.

**Comment by maximtop** [comment]
@mstfcbngl are there any errors on the background page during the update?

**Comment by mstfcbngl** [comment]
@maximtop I'm getting the same error as in the image in the first post.

**Comment by maximtop** [comment]
This is the error on the options page. The background page can be found like it is described here: https://maximtop.notion.site/How-to-export-logs-from-the-background-page-in-the-extension-fb7e2fe23cb0451ea010672ce0570929

**Comment by maximtop** [comment]
> @maximtop I'm getting the same error as in the image in the first post.


This is the error on the options page. The background page can be found like it is described here: https://maximtop.notion.site/How-to-export-logs-from-the-background-page-in-the-extension-fb7e2fe23cb0451ea010672ce0570929

**Comment by maximtop** [comment]
@mstfcbngl Are you sure, that you don't have any extensions, which may interfere with request headers in the browser? Or browser settings?

Could you try to install the extension in another browser or a new profile to check it?

**Comment by mstfcbngl** [comment]
@maximtop I have other extensions for ad block or any for other stuff. I'm currently use Opera GX but I tried with chrome with just one another ad block extension, same result.

**Comment by maximtop** [comment]
@mstfcbngl Can this link be opened directly in the browser https://filters.adtidy.org/extension/chromium/filters.js?v=4.1.53&cid=aYZSCi6K3834741&lang=tr&id=bopfaehpakahokaelnomggbohfbimcia?

**Comment by mstfcbngl** [comment]
@maximtop Yes.

**Comment by mstfcbngl** [comment]
I've tried disabling other ad block extension and then try to update filter with AdGuard but it's the same result. I hope all take the screenshots properly. 

![Ekran görüntüsü 2023-01-09 193717](https://user-images.githubusercontent.com/97148287/211360533-12eee689-66be-40e4-a4f0-60024d6ee776.png)

![Ekran görüntüsü 2023-01-09 193845](https://user-images.githubusercontent.com/97148287/211360436-e395b971-bc37-41e8-996e-85170f6939d2.png)

![Ekran görüntüsü 2023-01-09 193903](https://user-images.githubusercontent.com/97148287/211360443-c9870730-6741-46b1-88d0-bff3dff7f6ac.png)

**Comment by D13410N3** [comment]
Hello.
Issue should be fixed now, please check

**Comment by maximtop** [comment]
@mstfcbngl can you check now?

**Comment by mstfcbngl** [comment]
@maximtop Still can't update.

**Comment by maximtop** [comment]
Are there the same errors?

**Comment by mstfcbngl** [comment]
In console and network pages or AdGuard interface?

**Comment by maximtop** [comment]
> In console and network pages or AdGuard interface?

yes

**Comment by mstfcbngl** [comment]
Looks like this

![Ekran görüntüsü 2023-01-11 143235](https://user-images.githubusercontent.com/97148287/211796518-bae4f765-712c-4786-86a2-bf5d0b49489e.png)

![Ekran görüntüsü 2023-01-11 143523](https://user-images.githubusercontent.com/97148287/211796541-396a85d4-8e16-498b-9b2e-12261ce8a11a.png)

![Ekran görüntüsü 2023-01-11 143422](https://user-images.githubusercontent.com/97148287/211796603-6939dbb0-3c00-48f8-bd32-f3d7f13ba4ca.png)

![Ekran görüntüsü 2023-01-11 143438](https://user-images.githubusercontent.com/97148287/211796620-3b1c51ab-10d8-4658-80a5-176ab331c3a7.png)

**Comment by maximtop** [comment]
May you try to open the URL causing the error in the browser address bar, and check if filters are loaded there? 
If no send the same screenshots from the dev tools.

**Comment by mstfcbngl** [comment]
> @mstfcbngl May you try to open the URL causing the error in the browser address bar, and check if filters are loaded there? If no send the same screenshots from the dev tools.

If you mean request URL, I'll give you example from it's each different type of blocks.

![Ekran görüntüsü 2023-01-11 145826](https://user-images.githubusercontent.com/97148287/211801375-a48a4fb4-3557-4845-b2dd-fc64461cac12.png)

![Ekran görüntüsü 2023-01-11 145836](https://user-images.githubusercontent.com/97148287/211801398-21c3760c-b48e-4f3a-a5f0-ed96f6925424.png)

![Ekran görüntüsü 2023-01-11 145853](https://user-images.githubusercontent.com/97148287/211801413-1c24ab28-7552-4059-b0dd-9b73d470e57a.png)

**Comment by maximtop** [comment]
> @maximtop I have other extensions for ad block or any for other stuff. I'm currently use Opera GX but I tried with chrome with just one another ad block extension, same result.

Is your browser version the latest?

**Comment by mstfcbngl** [comment]
> > @maximtop I have other extensions for ad block or any for other stuff. I'm currently use Opera GX but I tried with chrome with just one another ad block extension, same result.
> 
> Is your browser version the latest?

Yep, both are, Opera GX and Chrome.

**Comment by maximtop** [comment]
> > > @maximtop I have other extensions for ad block or any for other stuff. I'm currently use Opera GX but I tried with chrome with just one another ad block extension, same result.
> > 
> > 
> > Is your browser version the latest?
> 
> Yep, both are, Opera GX and Chrome.

109.0.5414.87?

**Comment by mstfcbngl** [comment]
> > > > @maximtop I have other extensions for ad block or any for other stuff. I'm currently use Opera GX but I tried with chrome with just one another ad block extension, same result.
> > > 
> > > 
> > > Is your browser version the latest?
> > 
> > 
> > Yep, both are, Opera GX and Chrome.
> 
> 109.0.5414.87?

For Chrome? Almost same, 109.0.5414.75. But I can't see any updates available, it's says Chrome is up to date. For Opera GX, it's LVL 4 (core: 93.0.4585.84)

**Comment by maximtop** [comment]
@mstfcbngl looks like this issue is specific to your computer. Can you write me by email `maximtop@gmail.com`, for faster communication?
