### ISSUE TITLE
Extended CSS rules do not work on first visit

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/AdguardBrowserExtension#2260]
### AdGuard Extension version

4.1.53

### Browser version

Chrome 108

### OS version

Windows 11

### What filters do you have enabled?

No filters

### Issue Details

It looks like that Extended CSS rules do not work on first visit (probably on whatever website and only once time) after disabling then enabling extension.

Steps to reproduce:
1. Add these rules:
```adblock
example.org##a
example.org#?#body:has(div)
```
2. Disable extension (in browser settings `chrome://extensions/`)
3. Enable extension
4. Go to - https://example.org/

### Expected Behavior

Website should be blank, but for some reason Extended CSS (`example.org#?#body:has(div)`) rule is not applied on the first visit only.
It works fine if I firstly go to whatever website and then to `https://example.org/`, but if I just open `https://example.org/` (after disabling then enabling extension) then it doesn't work.

`example.org##a` works correctly every time.

**Comment by mozartinio** [comment]
@AdamWr 
Hello!
It is reproduced on our side and we will add your rule 
Thank you so much for your suggestion!

**Comment by oleedd** [comment]
The same after opening Chrome.
