### ISSUE TITLE
Add auto disable feature between main filters and partial filters.

### ISSUE THREAD

**Issue by kodiakhub** [AdguardTeam/AdguardBrowserExtension#2261]
### Issue Details

Hi, firstly check this: https://github.com/AdguardTeam/AdguardFilters/issues/139200#issuecomment-1371041183 there are many cases of issues like this.

In short, activating all filters is not useful in terms of usage.

### Proposed solution

For example:

<details><summary>If main filter activated, should be like (partial filters are greyed out, cannot be enabled):</summary>

![1](https://user-images.githubusercontent.com/56846906/210774698-749f3f33-5150-4e93-b635-864601a830d5.png)

</details><br/>

<details><summary>If partial filters activated, should be like(main filters are greyed out, cannot be enabled):</summary>

![2](https://user-images.githubusercontent.com/56846906/210774706-8fea2c6f-07ee-4522-99d7-e3d89ba68ee4.png)

</details><br/>

**Comment by krystian3w** [comment]
Adblock Warning Removal is not form AdGuard hands if you changed contrast on images in post production.

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/FiltersRegistry/issues/632

**Comment by mozartinio** [comment]
@kodiakhub 
Hello! We were thinking about your suggestion and have decided that we will leave it as it is 
By the way thank you for your feature request
