### ISSUE TITLE
Remove gaps between items

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardBrowserExtension#2264]
### Issue Details

![Screenshot 2023-01-11 194003](https://user-images.githubusercontent.com/122447646/211797656-df49e10a-c637-4749-b973-933277620a87.png)

**Comment by mozartinio** [comment]
@98365 
Hello!
Thank you for mention it!

**Comment by ZCK22** [comment]
Any update on whether this will still be worked on?

**Comment by maximtop** [comment]
Not fixed yet, but is planned.

**Comment by maximtop** [comment]
Duplicate of https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2198
