### ISSUE TITLE
Add a custom shortcut key for blocking options

### ISSUE THREAD

**Issue by Emilia66666** [AdguardTeam/AdguardBrowserExtension#2266]
### Issue Details

Sometimes I need to block multiple times on a website, which may be used

### Proposed solution

![image](https://user-images.githubusercontent.com/86843239/212678703-d746c7ae-4047-46e6-8896-f2abcc5bf7cc.png)
Add a custom shortcut key for blocking options

**Comment by mozartinio** [comment]
@Emilia66666 Hi!
Closed this issue because it is duplicate #2013
