### ISSUE TITLE
ArGuard automatically modify frequency on Ubiquity devices setup as Acces Point

### ISSUE THREAD

**Issue by Xperiense** [AdguardTeam/AdguardBrowserExtension#2279]
### AdGuard Extension version

4.1.53

### Browser version

Chrome 109.0.5414.120

### OS version

Windows 7

### What filters do you have enabled?

AdGuard Base filter

### Issue Details

When I open the management page of a Ubiquity devices (both versions M and AC), so basically devices created by Ubiquity in last 10 years, if the device is setup in AP mode, the Frequency setup who is usually on 5600 MHz or something .. are Automatically changed by AdGuard on "auto" .. and because i work fast ... I press save .. and than i have surprise that the Client Devices is not connecting to AP anymore.
if I disable AdGuard on that page .. the real frequency remain the same. 

This problem I notice since last 3 years.
![2021 12 27 01 Frequency is auto when AdGuard is enabled](https://user-images.githubusercontent.com/123823521/215276035-feae2168-f5ec-4a28-82d4-8be82d0dd8ec.jpg)
![2021 12 27 02 Frequency is Corect when AdGuard is disabled](https://user-images.githubusercontent.com/123823521/215276039-0a3d3d13-cdae-4b5c-a653-26af682eafbf.jpg)
![2023 01 28 01 Frequency is auto when AdGuard is enabled](https://user-images.githubusercontent.com/123823521/215276041-4d879061-7c92-41d8-8d7f-acd5452fd194.jpg)
![2023 01 28 02 Frequency is Corect when AdGuard is disabled](https://user-images.githubusercontent.com/123823521/215276042-553a39a7-13fa-495f-a789-f44f633592b8.jpg)

### Expected Behavior

As you can see in photo .. if AdGuard is disabled .. the correct original Setup frequency is displayed. This is Correct behavior ... the AdGuard DO NOT CHANGE Frequency AT ALL ! Since changing this by mistake it create problems in Wireless links between CPE (customer premises equipment) and AP (access point)

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

no anything to add. When AdGuard extension is enabled the frequency on AP devices are changed automatically to auto. If device is setup as CPE .. AdGuard does not interfear with frequency field, so it is normal behavior on CPS.

**Comment by maximtop** [comment]
@Xperiense 
Thank you for reporting this issue. Can you please answer two questions?
1. Is the issue reproduced without filters enabled?
2. Is the issue reproduced if the domain is added to the allowlist?

**Comment by Xperiense** [comment]
@Xperiense<https://github.com/Xperiense>
Thank you for reporting this issue. Can you please answer two questions?

  1.  Is the issue reproduced without filters enabled?
Xper> while I’m on management page of the Ubiquity device, if I go in Google Extension bar and I right click on AdGuard and I choose “Disable Filtering on this website” the page will reload with Correct Frequency settings. If I enable again … the page will reload with Frequency switched back to AUTO

  1.  Is the issue reproduced if the domain is added to the allowlist?
Xper> hmmm ..
***@***.***

My Allow list is full with name of devices. Since I acces devices using their name, because are inside my network, I do not use domain name into their full FQDN name, so I assume it will not help to ADD domain name to the AllowList since DOMAIN it is not used while managing the devices.

**Comment by maximtop** [comment]
> Xper> while I’m on management page of the Ubiquity device, if I go in Google Extension bar and I right click on AdGuard and I choose “Disable Filtering on this website” the page will reload with Correct Frequency settings. If I enable again … the page will reload with Frequency switched back to AUTO

Filters disabling can be done from the extension's options page. And it shouldn't trigger a page reload.

I'm asking this in order to understand if this is a filter issue, or an extension itself. Until now seems like this is a filter issue, and it can be solved if you determine the rule causing the issue, and disable it.

**Comment by Xperiense** [comment]
Xper> while I’m on management page of the Ubiquity device, if I go in Google Extension bar and I right click on AdGuard and I choose “Disable Filtering on this website” the page will reload with Correct Frequency settings. If I enable again … the page will reload with Frequency switched back to AUTO

Filters disabling can be done from the extension's options page. And it shouldn't trigger a page reload.

Xper> I enable the AdGiard from the Chrome Taskbar by Right Click on AdGuard icon and choose Disable Filtering on this website .. from Dropdown

***@***.***



And after I Disable in the same way it shows correct frequency

***@***.***

I'm asking this in order to understand if this is a filter issue, or an extension itself. Until now seems like this is a filter issue, and it can be solved if you determine the rule causing the issue, and disable it.

Xper> I’m telling you what I done. It is up to you to conclude. And the Nasty part is that when I connect on AP devices I usually do to make small adjustments, and before I realize that AdGiard snitching frequency to Auto … I press Save and then surprise surprise 😊 the CPE devices wont connect anymore .. than it is impossible to GUESS OLD Frequency .. so it is huge mess and keeping customers without internet.

**Comment by maximtop** [comment]
If "Disable Filtering on this website" works for you, then use it. Or find the rule via the filtering log which interferes with work on your managing panels.
