### ISSUE TITLE
not working adguard extention!

### ISSUE THREAD

**Issue by kinghamid-iran** [AdguardTeam/AdguardBrowserExtension#2280]
### AdGuard Extension version

4.1.53

### Browser version

edge 109

### OS version

windows 10

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, Iranian filter

### What Stealth Mode options do you have enabled?

Block trackers

### Issue Details

Hi, I when closed the edge browser and opened the link from the Samsung flow app from the Microsoft store adguard extension not working !!!!! please fix this issue --- I'm using  Filter Persian blocker --- ublock origin working!
I share the link on my mobile Samsung internet in the Samsung internet tab share and select Samsung flow for share link on my pc

tanks.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by mozartinio** [comment]
@kinghamid-iran 
Hello!
Could you please record a video of how you doing this and exactly what happens?

**Comment by mozartinio** [comment]
@kinghamid-iran 
Any news?

**Comment by mozartinio** [comment]
@kinghamid-iran
 I will close the issue for now
 When you will ready to send more information you can reopen it
