### ISSUE TITLE
Unable to select an element on hao.360.com in the 360 Secure Browser

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardBrowserExtension#2283]
### AdGuard Extension version

4.1.53

### Browser version

13.1.6410.0, 360 Secure Browser, [link](https://mse.360.cn/m/index.html)

### OS version

Windows 10

### What filters do you have enabled?

AdGuard Base filter, AdGuard Chinese filter, AdGuard Russian filter, AdGuard Annoyances filter

### Issue Details

Extension is unable to select an element on the hao.360.com website

### Expected Behavior

Elements is selected, blocked

### Screenshots

Nothing is happening when you try launching the element selection tool

<details><summary>Screenshot 1:</summary>

![image](https://user-images.githubusercontent.com/15856304/217255892-e5138686-aa78-4c32-91a2-84a1f4f90f3b.png)

</details>

**Comment by mozartinio** [comment]
@Eugene-Savenko 
Hello!
Its reproduce on our side too
Thank you! We'll take this bug to work

**Comment by Eugene-Savenko** [comment]
Closing this one, as it's no longer reproducible.
