### ISSUE TITLE
Add a synchronization function of Google hard disk to the user filter

### ISSUE THREAD

**Issue by AnduinZZ** [AdguardTeam/AdguardBrowserExtension#2284]

**Comment by mozartinio** [comment]
@AnduinZZ 
Hello!
Can you explain what exactly you suggesting? 
If "synchronization" is an update of the custom filter then what makes you think that from google disk does not pull a fresh version of the filter? Like does it work from other similar disks?
Am i understood you correctly?

**Comment by mozartinio** [comment]
@AnduinZZ
I can suggest you create your own filter then save it in google drive and add it to custom filters

**Comment by mozartinio** [comment]
@AnduinZZ 
Did it satisfy your requirement?

**Comment by mozartinio** [comment]
@AnduinZZ 
Im about to close this issue. If you got any questions or suggestions about this feature request you can reopen it
Thank you!
