### ISSUE TITLE
Add :others() Operator

### ISSUE THREAD

**Issue by iSmokeMid69** [AdguardTeam/AdguardBrowserExtension#2285]
### Issue Details

Ublock Has :others() Operator..Which Keep Only A Selected Element Of A Page And Remove Everything Else..This Is Very Useful For Link Shortener Sites

Details -

subject:others()

Experimental.

    Description: Target all elements outside than the currently selected set of elements.
    Chainable: Yes.
    subject: Can be a plain CSS selector, or a procedural cosmetic filter.
    Examples:
        twitter.com##:matches-path(/^/home/) [data-testid="primaryColumn"]:others()
        nature.com##:matches-path(/^/articles//) :is(.c-breadcrumbs,.c-article-main-column):others()

Introduced in uBO 1.41.1b2

For any element feeding into others(), the resultset of the others() operator will include everything else except:

    the descendants of a subject element
    the ancestors of a subject element

The resultset will contains the siblings of a subject element except when those siblings are either a descendant or ancestor of another subject element.

Though this operator is unlikely to be used in default lists, it opens the door to create specialized filter lists which purpose is some sort of "reader mode", where everything else than a selected set of elements are hidden from view.

Related discussion:

    https://www.reddit.com/r/uBlockOrigin/comments/slyjzp/

**Comment by slavaleleka** [comment]
Issue moved to [AdguardTeam/ExtendedCss #164](https://github.com/AdguardTeam/ExtendedCss/issues/164) via [**Zenhub**](https://www.zenhub.com/)
