### ISSUE TITLE
Migrate Firefox add-on to event pages

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#2286]
### Issue Details

In about 3-6 months using event pages instead of background pages will become mandatory on Firefox.

### Proposed solution

Here's the information about migration:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Background_scripts#convert_to_non-persistent

**Comment by DAVIDMORGAN78** [comment]
I lost my pot card and I need to know how to get in your life

**Comment by DAVIDMORGAN78** [comment]
I lost my pot card I need to know how to get a new one

**Comment by krystian3w** [comment]
And all works fine?
