### ISSUE TITLE
URL handling

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardBrowserExtension#23]
1) When adding whitelist/blacklist entries, neglecting www. or other subdomain prefixes will not work. If I enter "domain.com", what it means is really "*.domain.com/*". The interpretation should be built-in.

2) If users copy and paste the URL from address bar, the URL will include protocol, i.e. http:// or https://. The whitelist doesn't work with protocols included. Users must enter the bare domain. Also inconvenient.

**Comment by ameshkov** [comment]
Do you mean parental control lists?
