### ISSUE TITLE
Wildcard or regex support for domain name (not domain zone)

### ISSUE THREAD

**Issue by tumatanquang** [AdguardTeam/AdguardBrowserExtension#2303]
> @tumatanquang Hi! Wildcard for domain name (not domain zone) - it is not safe because there can be wrong blocking with another useful sites

I'm not sure which of the "another useful sites" you're referring to, but domains that are nearly identical (or only partially different) will often be the same owner or will be alias of each other or even phishing domains.
If the wildcard for the domain is not safe, I hope there is another solution, like regex support for the domain name. In this case, perhaps the regex will be a little faster than the wildcard.

_Originally posted by @tumatanquang in https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2297#issuecomment-1474583040_

**Comment by mozartinio** [comment]
@tumatanquang 
I reopen #2297 and going to close this issue as dublicate
