### ISSUE TITLE
Website fail with "AdGuard — Filter gegen Belästigungen"

### ISSUE THREAD

**Issue by Dragodraki** [AdguardTeam/AdguardBrowserExtension#2306]
The Adguard addon filter for removing popups, banners and cookie consent (category "Annoyances") results in the website "https://www.jobware.de/ratgeber/muss-der-lebenslauf-unterschrieben-werden" doesn't load at all. Maybe jobware.de does it on purpose to force its deactivation, I don't know. Can someone fix it in this filter?

**Comment by mozartinio** [comment]
@Dragodraki Hello!
It is reproduced on our side and we will figure out how to fix it
Thank you!

**Comment by maximtop** [comment]
cant reproduce anymore
