### ISSUE TITLE
`Search in tabs` (Filtering log) down arrow not working properly

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdguardBrowserExtension#2307]
### AdGuard Extension version

4.1.53

### Browser version

Chrome v111.0.5563.65 - Firefox v111.0

### OS version

Windows 10

### Issue Details

As you can see in the video, when you click on `Search in tabs` the names of the tabs appear, menu will be open and work properly, but when you click the arrow down, the tab section is selected and the menu (names of the tabs) doesn't open. 

### Expected Behavior

Clicking on the arrow (in the `Search in tabs`) should open the menu (names of the tabs) and it should work properly. Just like when we click on `Search in tabs`.

### Screenshots

<details><summary>Video:</summary>

https://user-images.githubusercontent.com/35523759/226430348-99130763-7401-478f-9ba6-77216477aff3.mp4
</details>

### Additional Information

When the mouse cursor is over the arrow, it may look like I'm not doing anything, but in the video I'm clicking on the arrow. Same for Firefox Browser too.

**Comment by contribucious** [comment]
Reproducible on my end as well (on both **Firefox 111.0** and **Edge 111.0.1661.44**).

**Comment by mozartinio** [comment]
@gork7777 
Thank you! It is reproduced on our side as well

**Comment by maximtop** [comment]
seems to be working in v4.2.159-beta

**Comment by gork7777** [comment]
@maximtop you're right, thanks!
