### ISSUE TITLE
Отсутствие подписки!

### ISSUE THREAD

**Issue by Spok1** [AdguardTeam/AdguardBrowserExtension#2308]
### AdGuard Extension version

4.1.53

### Browser version

Edg/111.0.1661.43

### OS version

Windows 10

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Russian filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### What Stealth Mode options do you have enabled?

Remove tracking parameters, Hide your search queries, Send websites signals not to track you, Remove X-Client-Data header

### Issue Details

Не отображается в списке подписок подписка на Украинские фильтры

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://user-images.githubusercontent.com/34476664/226509349-f66e7f74-29f6-40cd-8199-f6f1e8037052.png)
</details>

### Additional Information

Что делает эта подписка? **Legitimate URL Shortener**

**Comment by mozartinio** [comment]
@Spok1 
Maybe you have an old metadata stored in memory
Try updating filters through the settings - the filter should show up
Or did you try to reinstall the extension?





[16:06](https://performix.slack.com/archives/D03N04F3ETV/p1679490398172479)
ну или расширение переустановить

**Comment by Spok1** [comment]
@mozartinio,

> Try updating filters through the settings - the filter should show up

How do I do this?

> Or did you try to reinstall the extension?

I recently installed on a new browser (18th), so we can say that it is recently installed.

> Maybe you have an old metadata stored in memory

Hardly!

**Comment by Spok1** [comment]
@mozartinio hey!

**Comment by mozartinio** [comment]
@Spok1 
1. "Filter" tab in settings
2. Click on "check for updates" button

Please let me know if it helps

**Comment by Spok1** [comment]
@mozartinio,worked! And why did the Ukrainian subscription not appear during automatic renewal?

**Comment by mozartinio** [comment]
@Spok1  
Auto update works only for enabled filters thats is why is happened
So if it works fine for now im closing the issue 
If the problem will repeat again feel free to reopen this issue
