### ISSUE TITLE
Font is inconsistent in the "filters updated" snack

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardBrowserExtension#2309]
![Screenshot 2023-03-23 010037](https://user-images.githubusercontent.com/128627239/226981551-56a95ed9-1191-4099-bcec-ed27a8e392c2.png)
![Screenshot 2023-03-23 010032](https://user-images.githubusercontent.com/128627239/226981568-cacfc168-88e9-4a45-8a7a-3e7e7e0ec4a3.png)

**Comment by mozartinio** [comment]
@8020percent 
Hello!
Can you please give more information in which browsers you catch the difference?

**Comment by 8020percent** [comment]
> @8020percent Hello! Can you please give more information in which browsers you catch the difference?

Chrome and Edge

**Comment by mozartinio** [comment]
@8020percent 
Thank you! We are working on it
