### ISSUE TITLE
Safari doesn't support content-blocking rule with regexp, which contains negative lookahead 

### ISSUE THREAD

**Issue by Stillness-2** [AdguardTeam/AdguardBrowserExtension#231]
We need exclude these rules from conversion.

Rules examples:
`/^https?://(?!static\.)([^.]+\.)+?fastpic\.ru[:/]/$script,domain=fastpic.ru`
`/^https?://(?!www\.)([^.]+\.)+?(kordonivkakino\.net|m(ac-torrent-download\.net|oviki\.ru))[:/]/$script`
`/https?://(?!(mc\.yandex\.ru|www\.google-analytics\.com)/)/$third-party,script,subdocument,domain=massivmebel.by`

**Comment by Mizzick** [comment]
Fixed

**Comment by ameshkov** [comment]
JFYI, one more example of such filter rule:
```
/http://cdn[0-9]\.spiegel\.de/images/image-([^-]+)-[^-]+-[^-]+-(?!\1)[^-]+\.jpg/$image,domain=spiegel.de
```
