### ISSUE TITLE
Extension support for Arc browser

### ISSUE THREAD

**Issue by netopolit** [AdguardTeam/AdguardBrowserExtension#2316]
### Issue Details

[Arc browser](https://arc.net/) is becoming quite popular. It's a Chromium based browse. The AddGuard extension can be installed from Chrome extension store but it doesn't work. I'd like to request Arc browser compatibility. 
Thank you.

### Alternative solution

Maybe there is a temporary solution? I tried using legacy assistant but it didn't work either.

**Comment by piquark6046** [comment]
As far as i know, its built-in adblocker is uBlock Origin.
https://www.reddit.com/r/browsers/comments/vdhge5/arc_browser_new_browser_based_on_chromium/?utm_source=share&utm_medium=web2x&context=3

**Comment by netopolit** [comment]
uBlock Origin comes as preinstalled browser extension which you can uninstall and theoretically use Adguard instead. Legacy extension doesn't work either though it's a subpar solution.

[https://www.reddit.com/r/Adguard/comments/116h4l2/adguard_arc_browser/](https://www.reddit.com/r/Adguard/comments/116h4l2/adguard_arc_browser/)

**Comment by krystian3w** [comment]
LibreWolf also have preinstalled uBo, I didn't look to see if they were washing dirt on the forum or in private emails writing for permission.

**Comment by netopolit** [comment]
This went way off-topic. Are you considering making AdGuard app work with Arc browser?

**Comment by maximtop** [comment]
Yes, we will see what we can do.

**Comment by netopolit** [comment]
Thank you

**Comment by vozersky** [comment]
@netopolit it should be working fine now :)

**Comment by netopolit** [comment]
@vozersky It does. Thank you!
