### ISSUE TITLE
Add URL trackers in problem type dropdown

### ISSUE THREAD

**Issue by xupdate** [AdguardTeam/AdguardBrowserExtension#2318]
![Screenshot 2023-04-06 030913](https://user-images.githubusercontent.com/129993539/230181328-a0bd2ef1-df72-4d5d-9af9-3317a7eff54d.jpg)

**Comment by slavaleleka** [comment]
Issue moved to [AdguardTeam/ReportsWebApp #324](https://github.com/AdguardTeam/ReportsWebApp/issues/324) via [**Zenhub**](https://www.zenhub.com/)
