### ISSUE TITLE
AdGuard not saving the filters I turn on (every filter)

### ISSUE THREAD

**Issue by Aydinv13** [AdguardTeam/AdguardBrowserExtension#2323]
@DannyJacoby commented on [Fri Apr 07 2023](https://github.com/AdguardTeam/AdguardForWindows/issues/4671)

### AdGuard version

4.1.53

### Browser version

Firefox version 111.0.1

### OS version

Windows 11, 22H2, build 22621.1413

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard DNS filter, Filter unblocking search ads and self-promotion

### What Stealth Mode options do you have enabled?

Send Do-Not-Track signals, Strip URLs of tracking parameters, Self-destruction of third-party cookies, Self-destruction of first-party cookies, Disable cache for third-party requests, Block the third-party Authorization header, Disable WebRTC, Block Push API, Block Location API, Block Flash, Disable Windows Telemetry, Turn off Advertising ID, Disable Microsoft Defender automatic samples submission, Disable WAP Push Message Routing Service, Hide your Referrer from third-parties

### Issue Details

Adguard keeps popping up every time I open firefox, and it keeps notifying me that I'm "unprotected". I go into my settings, turn on all protections, but they just aren't being saved. I've cycled just about everything, and I've done everything but a full reinstall of adguard. I'll be doing that after this ticket is submitted, but this is a super weird issue and I just wanted to log it in case others were experiencing something similar.

**Comment by Aydinv13** [comment]
@DannyJacoby I have moved your issue to the right repo.

**Comment by mozartinio** [comment]
@DannyJacoby
Hi!
Am i right that you cant even turn on  the adblocker?
Can you sent to us screenshot where it says "unprotected" or video of the process

**Comment by toadsworth-jr** [comment]
Just to be sure, the `Welcome to AdGuard` page also opens up along with it, yeah?

**Comment by mozartinio** [comment]
@toadsworth-jr 
Yes, after installation the welcome page is opening

**Comment by mozartinio** [comment]
@DannyJacoby
Any news?

**Comment by toadsworth-jr** [comment]
(Would this issue be bad enough to have it warranted a Priority 1 tag?)

**Comment by thstyl2000** [comment]
> (Would this issue be bad enough to have it warranted a Priority 1 tag?)

Well, it is quite annoying...
What kind of data are needed here?

**Comment by AlexandrPkhm** [comment]
Hi! Please let us know if the issue persists on the most recent version of Firefox and AdGuard Browser extension which is 4.1.55. If it does please send us a screenshot or video with the steps to reproduce.

**Comment by zzebrum** [comment]
@thstyl2000 @DannyJacoby any news?

**Comment by thstyl2000** [comment]
Can confirm it's fine now.

**Comment by toadsworth-jr** [comment]
It still works. I was able to easily reproduce this by simply reopening Firefox, on a Windows 10 machine.
(One key thing that I didn't do is to fully reinstall Firefox. I might do it as a last resort.)
![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/75596775/058f3576-5e9f-480f-9735-55a55eab5b31)
![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/75596775/2d092a58-df40-417e-88ed-9535d81609b0)
![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/75596775/b0dc6d55-8575-47e9-8e6d-0c3faa41b951)
