### ISSUE TITLE
Add advanced filter support for `Preview` feature in `AdGuard dev console`

### ISSUE THREAD

**Issue by kodiakhub** [AdguardTeam/AdguardBrowserExtension#2324]
### Issue Details

Hi, I'm learning filtering slowly and the `Preview` feature is very helpful to turn this knowledge to experience. If possible, could you add existing advanced filtering options to supported for the `Preview` feature? Thanks in advance.

For example, see:

<details><summary>Video</summary>
<p>

https://user-images.githubusercontent.com/56846906/230796014-7bef7077-a2f4-43d8-9623-6cfb4c01f0a1.mp4

</p>
</details>

### Proposed solution

In the title

**Comment by mozartinio** [comment]
@kodiakhub 
Hello!
Please tell us more about what you are proposing as a feature request
What type of existing advanced filtering options you want to see in the preview tab?

**Comment by alexx7311** [comment]
Hello! Extended CSS selectors are currently not supported in DevTools. We've created an issue #2345 
You can follow the progress there.
