### ISSUE TITLE
Hotmail reloading the page when click in the "others" on the mailbox

### ISSUE THREAD

**Issue by neofln** [AdguardTeam/AdguardBrowserExtension#2325]
### AdGuard Extension version

4.1.55

### Browser version

chrome 111.0.5563.147

### OS version

WIndows 10 22h2

### Issue Details

Hotmail is reloading the page when click in the "others" on the mailbox, so we can't access the others e-mails, when adguard is off the problem is solved and lots of announces appears in the page.

### Expected Behavior

I expect to see the page without the announces to access the other e-mails, as it happens in the last version of the extension. 

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by mozartinio** [comment]
@neofln 
Hello! Your issue doesn't reproduce on our side so can you please try to reload extension/update browser/clear cookie
Does it reproduce on previous extension version? 
Does it reproduce only in chrome browser or everywhere?

**Comment by neofln** [comment]
Hi.
Doesn't happens in the last version of the extension, never happens before.
For sure I will try to "reload extension/update browser/clear cookie".
I just use hotmail and Adguard on chrome so I don't know if it will reproduce in another browser, as I said before Adguard is off just in hotmail as partial solution.
Thank you for the suggestions, after test it I'll inform if solved the problem.


________________________________
De: Maxim ***@***.***>
Enviado: segunda-feira, 17 de abril de 2023 04:28
Para: AdguardTeam/AdguardBrowserExtension ***@***.***>
Cc: neofln ***@***.***>; Mention ***@***.***>
Assunto: Re: [AdguardTeam/AdguardBrowserExtension] Hotmail reloading the page when click in the "others" on the mailbox (Issue #2325)


@neofln<https://github.com/neofln>
Hello! Your issue doesn't reproduce on our side so can you please try to reload extension/update browser/clear cookie
Does it reproduce on previous extension version?
Does it reproduce only in chrome browser or everywhere?

**Comment by neofln** [comment]
Response 2.
Hi.
I have updated chrome and, after this and after reset the filters of the site on the extension the big announcement at the right of screen is eliminated by ADGUARD but the two announcements at the top of the e-mail list on "others" still appears.
I have used the announcement block option and have removed the divs that shows this announcements and similar ones and after that I blocked the div that contains both of it, now at the top of list "others" I have only my e-mails.

The filters is these ones, in case you have interest:

outlook.live.com##.kk1xx, ._Bfyd, .DVTER, .yedzL, .ypzld, .YmHO2, .MxMxG
outlook.live.com###MainModule > div.SW7A6 > div.LBktY > div.q9iRC.css-181:nth-child(3) > div.HOVUa > div.nbmyu.FkPdL.czwRD.LCprM:last-child > div.C1EJK.LyMTI.css-190:first-child > div.Cz7T5.customScrollBar:nth-child(2) > div.ONAp_ > div.Cz7T5 > div.Cz7T5 > div.customScrollBar.jEpCF > div.zXLz3 > div.full.evj9g:first-child


Thank you again.

________________________________
De: Maxim ***@***.***>
Enviado: segunda-feira, 17 de abril de 2023 04:28
Para: AdguardTeam/AdguardBrowserExtension ***@***.***>
Cc: neofln ***@***.***>; Mention ***@***.***>
Assunto: Re: [AdguardTeam/AdguardBrowserExtension] Hotmail reloading the page when click in the "others" on the mailbox (Issue #2325)


@neofln<https://github.com/neofln>
Hello! Your issue doesn't reproduce on our side so can you please try to reload extension/update browser/clear cookie
Does it reproduce on previous extension version?
Does it reproduce only in chrome browser or everywhere?

**Comment by alexx7311** [comment]
Have you tried clearing cookies? That might be the problem. If it doesn't help, you can try incognito mode (Ctrl+Shift+N in Chrome)

Please take a screenshot of the page with these elements. 

We must warn you that it is not possible to send screenshots to github by e-mail. Please go to the issue page https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2325 and leave a comment with screenshots.
