### ISSUE TITLE
Отсутствует фильтрация! 

### ISSUE THREAD

**Issue by Spok1** [AdguardTeam/AdguardBrowserExtension#2329]
### AdGuard Extension version

4.1.55

### Browser version

Microsoft Edge 112.0.1722.34

### OS version

Microsoft Windows 10  Версия 10 21H1 (сборка ОС 19043.2251)

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Russian filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters, Hide your search queries, Send websites signals not to track you, Hide Referrer from third parties, Remove X-Client-Data header, Disable WebRTC

### Issue Details

Не блокируются web-запросы на страницах, открытых через боковую панель браузера.

### Expected Behavior

Полная фильтрация ответов

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by zzebrum** [comment]
dup of #2223
