### ISSUE TITLE
Failed to block unnecessary content on CSDN

### ISSUE THREAD

**Issue by Ywandung-Lyou** [AdguardTeam/AdguardBrowserExtension#2336]

**Comment by AlexandrPkhm** [comment]
Hi @Ywandung-Lyou!

Unfortunately, your request lacks the information necessary for us to diagnose and troubleshoot the issue. If the issue persists please recreate a request with the necessary data. The best way to do so is to use our official [report tool](https://adguard.com/kb/guides/report-website/).
