### ISSUE TITLE
Adguard Browser Extension not working

### ISSUE THREAD

**Issue by Am4hisa** [AdguardTeam/AdguardBrowserExtension#2337]
### AdGuard Extension version

4.1.55

### Browser version

Chrome 114.0.5720.4

### OS version

Win11 Pro 22621.1555

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Chinese filter, AdGuard Japanese filter, AdGuard Russian filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, List-KR

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters

### Issue Details

Domain rule is work. (||test.com/ad , /ad/test  etc... )
CSS rule is not work. (test.com###Ad , #?##main > div:contains(Ad) etc...)

### Expected Behavior

Block Ads and so on

### Additional Information

Reset the statistics and the blocker will work fine.
I already reset statistics. so I can not reproduce this issue now...

**Comment by AlexandrPkhm** [comment]
Hi!
Unfortunately, we are unable to reproduce the issue. Please reach out to us if you'll encounter this issue again and we will continue investigating.
