### ISSUE TITLE
No injection of styles and JS into pages, opened with launching the browser

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#2343]
### AdGuard Extension version

4.2.110

### Browser version

114.0.5735.9

### OS version

Windows 10

### What filters do you have enabled?

AdGuard Base filter, AdGuard Russian filter

### Issue Details

Element hiding, CSS, JS and scriptlet rules are not applied to pages, opened with launching the browser when used saving a session.

1. Add to user rules

```
##._post_content img
#%#//scriptlet('set-constant', 'test', '1')
```

2.1 Open vk.com
2.2 Open dev tools, type `test` in Console tab and press Enter

Expected and current behavior in case, when a site opened **after** start if browser:

1. Images are hidden;
2. `1` returned in console

### Steps to reproduce

1. Restart the browser 
2. Check rules result.

### Actual behavior

1. Images are not hidden
2. Entering `test` in console returns `test is not defined`

**Comment by XX-J** [comment]
Скажу больше - при некоторых манипуляциях со страницей, например переключения аккаунта почты на Mail.ru, Adguard не переприменяет стилевые правила. Я предполагаю что это из-за того, что страница не обновляется полностью, а только частично, по современному, как происходит на многих сайтах, и на всех (или почти на всех) таких сайтах Adguard сбоит таким образом.

 Итог: версию 4.2.110 невозможно использовать!

 FireFox v78.13 ESR
