### ISSUE TITLE
Rule-generator creates an element-hiding rule for parent page despite it should be for iframe

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AdguardBrowserExtension#2346]
### AdGuard Extension version

4.1.55

### Browser version

Brave 1.51.110

### OS version

Windows 10

### What filters do you have enabled?

AdGuard Base filter

### Issue Details

On `https://www.girlsgogames.com/game/bubble-town` if you try to create a rule to disable `###sponsorText` from the logs, `girlsgogames.com#@##sponsorText` is created but it does not work as the rule is actually applied to an iframe `securegames.iwin.com`.

### Expected Behavior

`securegames.iwin.com#@##sponsorText` should be created.

### Screenshots

NA

**Comment by alexx7311** [comment]
Hello! We already have an open issue for this problem #1449 
We will fix this bug soon!

**Comment by Yuki2718** [comment]
Sorry, couldn't catch in search.
