### ISSUE TITLE
Transfer "Report a bug" and "Leave feedback" actions to the "Settings" tab

### ISSUE THREAD

**Issue by Vitalik93** [AdguardTeam/AdguardBrowserExtension#2350]
### Issue Details

Считаю, что кнопки "Сообщить об ошибке" и "Оставить отзыв" должны находиться в разделе "О программе", а не в основных настройках, т.к. отношения к настройкам они не имеют. 

![Снимок экрана 2023-05-09 151606](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/34383288/e3e57764-324c-4b49-ab7a-5dea2a4e1b53)

**Comment by alexx7311** [comment]
Здравствуйте! Спасибо за предложение, но на данный момент переносить эти экшены мы не планируем.
