### ISSUE TITLE
Instagram

### ISSUE THREAD

**Issue by Harumoon** [AdguardTeam/AdguardBrowserExtension#2355]
It doesn't block any ad or 'Sponsored' post on Instagram [on desktop]. However since a few days ago this is the same with Ublock Origin which I've been using successfully for years.
Any chance there is something you can do about this? Instagram is the only website where it's not working.
Thanks.

**Comment by slavaleleka** [comment]
could you please report a website via the extension popup?
https://adguard.com/kb/guides/report-website/

**Comment by Harumoon** [comment]
Hi,
Thanks for the reply. Actually, don't worry about it, the process is just
way too difficult and involved just to report a problem.
