### ISSUE TITLE
Subscribe button is not available because the filter description is too long

### ISSUE THREAD

**Issue by xiulou23** [AdguardTeam/AdguardBrowserExtension#2357]
### AdGuard Extension version

4.1.55

### Browser version

lemur 2.4.0.051

### OS version

HarmonyOS 3.0.0.208

### Issue Details

我打算添加一个过滤器，但是因为这个过滤器的描述过长，导致添加按钮被挤出界面，而且无法上下滑动，因此无法添加过滤器。我使用的浏览器叫做lemur，是一个能安装扩展程序的安卓浏览器。
我要添加的过滤器链接是https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockfilters.txt
![Screenshot_20230518_012401_com lemurbrowser exts beta](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/133690386/bc400c51-3b57-425f-b244-70d31a5f9cc5)

### Screenshots

<deta
![Uploading Screenshot_20230518_012401_com.lemurbrowser.exts.beta.jpg…]()
ils><summary>Screenshot 1:</summary>

</details>

**Comment by alexx7311** [comment]
Hello! We were able to install this filter without any problems on lemur 2.4.0.051. What's your screen resolution and display size?

**Comment by xiulou23** [comment]
> Hello! We were able to install this filter without any problems on lemur 2.4.0.051. What's your screen resolution and display size?你好！我们能够在狐猴 2.4.0.051 上安装此过滤器而不会出现任何问题。您的屏幕分辨率和显示尺寸是多少？

我的屏幕分辨率是1080X 2340，你说的显示尺寸是指我的屏幕大小吗？我的手机屏幕大小是6.62英寸

**Comment by xiulou23** [comment]
> Hello! We were able to install this filter without any problems on lemur 2.4.0.051. What's your screen resolution and display size?你好！我们能够在狐猴 2.4.0.051 上安装此过滤器而不会出现任何问题。您的屏幕分辨率和显示尺寸是多少？

屏幕分辨率与显示大小我已经说了，我就顺便再说一句，我的手机是HUAWEI mate30 5G，刚刚忘记说了

**Comment by alexx7311** [comment]
Hello! We're not supporting lemur browser yet, but you can try Firefox for android. We'll close the issue for now. If the problem repeats in Firefox, you can reopen it.
