### ISSUE TITLE
Add an option to disable page loading in Firefox before AdGuard extension is loaded

### ISSUE THREAD

**Issue by Spok1** [AdguardTeam/AdguardBrowserExtension#2363]
### Issue Details

Всё чаше наблюдаю,что при запуске браузера с открытой последней вкладкой с любым сайтом происходит загрузка всех рекламных скриптов и запросов в браузере до начала фильтрации приложением.

### Proposed solution

В  связи с вышеописанным предлагаю сделать отложенную загрузку страницы,пока расширение не загрузится для того,чтобы не пропускать рекламу и пр.

### Alternative solution

Посмотрите как это сделано в юблок ориджинс,если не представляете о чём речь.

**Comment by krystian3w** [comment]
> как юблок ориджинс

Only this [function](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fgithub.com%2Fgorhill%2FuBlock%2Fwiki%2FDashboard%253A-Filter-lists%23suspend-network-activity-until-all-filter-lists-are-loaded) is flawed at chromium level, hence it is better not to set some advertised page as homepagepage or recover session with advertised pages as soon as possible.

So it could even be the result of Chromium 110 code changes: https://github.com/uBlockOrigin/uAssets/discussions/16939

**Comment by Spok1** [comment]
And what do you want to say that this is unrealizable in adguard?

**Comment by alexx7311** [comment]
It could be implemented as an option for Firefox. Let's see how many votes will this feature get.

**Comment by Spok1** [comment]
@alexx7311,It sounds good! I think everyone will appreciate it! Let's bring this issue up for consideration.

**Comment by krystian3w** [comment]
While on Firefox the problem is reproducible, because Mozilla has made it so that the add-on has a chance to filter the traffic (In the sense that, in the code for Firefox, this option could only serve as a switch for Mozilla's "overzealousness.").
