### ISSUE TITLE
jd.com 网址会导致无限重复刷新

### ISSUE THREAD

**Issue by msccreater** [AdguardTeam/AdguardBrowserExtension#2365]
### AdGuard Extension version

版本 4.1.55

### Browser version

edge 版本 113.0.1774.50 (正式版本) (64 位)

### OS version

win11 22H2

### What filters do you have enabled?

AdGuard Chinese filter

### What Stealth Mode options do you have enabled?

Remove tracking parameters, Hide your search queries, Send websites signals not to track you, Self-destruction of third-party cookies, Hide Referrer from third parties, Remove X-Client-Data header, Disable WebRTC

### Issue Details

open link  https://item.jd.com/xxx.html 会导致无限重复刷新

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by alexx7311** [comment]
Hello! We haven't been able to reproduce the problem. 

What steps do you take to reproduce the problem? Please attach some screenshots to illustrate the problem.

Have you tried checking the problem in browser incognito mode?

**Comment by alexx7311** [comment]
We will close the issue for now. You can reopen it if the problem still persists.
