### ISSUE TITLE
The feature of automatic ad clicking

### ISSUE THREAD

**Issue by xiulou23** [AdguardTeam/AdguardBrowserExtension#2367]
### Issue Details

我有一个建议给你们，就是增加一个模拟用户点击广告的功能，用于保护隐私的。Adguard会过滤广告，但是我希望过滤广告时能模拟用户点击广告，而且还要是随机点击被过滤的广告，广告商会根据用户点击广告然后用大数据推测用户的兴趣爱好，我这一个功能就是专门对付这些广告商的，使广告商无法精准的推测用户兴趣爱好。模拟用户点击广告时一定要让用户感知不到。

**Comment by alexx7311** [comment]
Hello! Thanks for you feature request, but we won't implement this feature.
