### ISSUE TITLE
AdGuard blocks useful content

### ISSUE THREAD

**Issue by KarasMachine** [AdguardTeam/AdguardBrowserExtension#2369]
### AdGuard Extension version

4.1.55

### Browser version

Google Chrome 113.0.5672.126

### OS version

Mac OS Ventura 13.3 (22E252)

### What filters do you have enabled?

AdGuard Base filter

### Issue Details

When I work on the Supa website and go to the section with template thumbnails (https://dashboard.supa.ru/create/social-media/instagram-post), when AdGuard is enabled, they load very slowly (the first block with templates loads quickly , but when scrolling, new thumbnails do not want to be loaded.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>
<img width="1409" alt="Снимок экрана 2023-05-31 в 11 37 50" src="https://github.com/AdguardTeam/AdguardBrowserExtension/assets/135109562/002fc612-ac51-4027-be1a-51858cecf11d">

**Comment by alexx7311** [comment]
Hello! We couldn't reproduce the problem. 

Could you please perform the following steps and see if helps to deal with the problem:

- Please, in the Filters setting, set only 2 sets of filters to be active - language specific and AdGuard Base one.
- Disable Stealth Mode and all the additional security modules.
- Check if the problem recurs in browser incognito mode (⌘ + Shift + N in Chrome).

If it doesn't recur, you'll need to clear your browser cookies.

**Comment by alexx7311** [comment]
The issue will be closed for now. You can reopen it if the problem still persists.
