### ISSUE TITLE
open a window in browser at each browser restart

### ISSUE THREAD

**Issue by 1C0D** [AdguardTeam/AdguardBrowserExtension#2370]
### AdGuard Extension version

4.1.55

### Browser version

firefox

### OS version

win 10

### What filters do you have enabled?

No filters

### What Stealth Mode options do you have enabled?

Remove tracking parameters

### Issue Details

open window in browser (configure adguard) at each browser restart

### Expected Behavior

no reopen

### Screenshots

<details><summary>Screenshot 1:</summary>

![Merci d'avoir installé AdGuard ! — Mozilla Firefox](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/63018905/7078481e-861e-4be9-a29c-8218184ee092)

</details>

**Comment by alexx7311** [comment]
duplicate of #2189

**Comment by 1C0D** [comment]
it was not doing it again after reinstallation
