### ISSUE TITLE
AdGuard extension doesn't block Share button and Show other videos element

### ISSUE THREAD

**Issue by Spok1** [AdguardTeam/AdguardBrowserExtension#2374]
### AdGuard Extension version

4.1.56

### Browser version

Fierfox 113.0.1

### OS version

Windows 10 21H2

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Russian filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Mobile App Banners filter, AdGuard Experimental filter

### Issue Details

Косметические правила не срабатывают в Firefox при просмотре трейлера!

### Expected Behavior

Чтобы фильтрация работала!

### Screenshots

<details><summary>Screenshot 1:</summary>

![изображение](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/34476664/59bb869d-0ed9-4a47-8d25-a4fca1d1ad38)

</details>

### Additional Information

Ссылка на страницу: https://rezka.ag/series/action/32360-mandalorec-2019.html

**Comment by alexx7311** [comment]
Здравствуйте! Похоже на проблему фильтрации, а не проблему расширения. Сообщите, пожалуйста, о проблеме с помощью опции "Сообщить о проблеме" в расширении (так, как вы бы сообщали о пропущенной рекламе). Подробную инструкцию по заполнению можно найти по ссылке https://adguard.app/kb/ru/guides/report-website/
