### ISSUE TITLE
Popup 

### ISSUE THREAD

**Issue by tetoksn** [AdguardTeam/AdguardBrowserExtension#2375]
### AdGuard Extension version

4.1.56

### Browser version

Kiwi browser Android Chromium version 112.0.5615.133.

### OS version

Android 11

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Chinese filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, EasyList, ABPVN List

### What Stealth Mode options do you have enabled?

Remove tracking parameters, Hide your search queries, Send websites signals not to track you, Self-destruction of third-party cookies, Hide Referrer from third parties, Remove X-Client-Data header, Disable WebRTC

### Issue Details

Can not block popup on truyengihotne.com 
(popup is generated after scrolling for around 3-5 minutes, ) 
The popup link is: →https://rinsermouton.space/iruYAZavNohEAZDPhiNQSbE/37482/?sco...
If i dont use adguard, the link will direct me to shopee.vn

### Screenshots

<details><summary>Screenshot 1:</summary>

]

</details>

**Comment by alexx7311** [comment]
Hello! It looks like a filter problem, not extension problem. Please report a website via extension popup (as missing ads). You can find instructions at https://adguard.app/kb/guides/report-website/#form
