### ISSUE TITLE
"Easy Privacy" filter disturbs input fields and PayPal-button

### ISSUE THREAD

**Issue by Dragodraki** [AdguardTeam/AdguardBrowserExtension#2376]
### AdGuard Extension version

4.1.56

### Browser version

Firefox ESR 102.12.0

### OS version

Windows 7 64-Bit

### What filters do you have enabled?

EasyPrivacy

### What Stealth Mode options do you have enabled?

Block trackers, Hide your search queries, Send websites signals not to track you, Hide Referrer from third parties

### Issue Details

On shopping website https://www.digitalo.de/checkout/login.html (you must put an item in your cart before) when typing in the input fields (name, adress, etc.), the title overlaps with the entered characters. And on every article site the PayPal buttons get removed. This does happen only if "EasyPrivacy" filter is enabled. When disabled everything work normal again. I checked this with all other addons disabled to make sure there isn't any conflict with other addons.
Seems some "tracking" things have their reason... difficult to make rules that work 100% sure, I'm aware of that.

### Expected Behavior

PayPal-buttons for express shopping shouldn't be hidden (until this is to protect from heavy tracking method). And when checking out on register/login the adress input fields should move its title above the field once user filled it to avoid overlapping (also when having "EasyPrivacy" enabled).

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by alexx7311** [comment]
Hello! "Easy Privacy" is not our filter. You can report it to the creators at https://easylist.to/
