### ISSUE TITLE
Cannot move external rules editor to the main browser's window

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#2379]
### AdGuard Extension version

4.2.133

### Browser version

Version 114.0.5735.134

### OS version

Windows 10 x64

### Issue Details

In 4.1 external filter editor opened in a new window as a tab. Now it opens as separate window, and can't be moved to the main window.
To work with the rules it is convenient to keep the editor in a separate pinned tab.

### Screenshots

<details><summary>4.1 vs 4.2</summary>

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/8361299/0de6484d-b53c-4a5d-9ec4-1219d9c993e6)

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/8361299/1d7ae0f0-903a-4ec8-991a-42f909296143)

</details>

**Comment by XX-J** [comment]
Во всех версиях AdGuard 4.2.xxx на FireFox'e v78.13 ESR кнопка открытия внешнего редактора правил не работает!

<details><summary>Screenshot:</summary>

![2023-07-21-1](https://i.ibb.co/Y7f5jgT/2023-07-21-1.png)
</details>

**Comment by maximtop** [comment]
> Во всех версиях AdGuard 4.2.xxx на FireFox'e v78.13 ESR кнопка открытия внешнего редактора правил не работает!
> 
> Screenshot:
> Консоль страницы настроек выдаёт следующую ошибку:
> 
> ```
>     Uncaught (in promise) Error: Type error for parameter createData (Property "focused" is unsupported by Firefox) for windows.create.          background.js
>     openEditorFullscreen      moz-extension://ede33548-d89b-415c-aa4f-140c0ba03277/pages/options.js:11980
>     AsyncFunctionThrow      self-hosted:697
> ```
> 
> Screenshot:

заведите под эту проблему отдельную задачу, будем смотреть почему в прошлых версиях не работает
