### ISSUE TITLE
Sort out the pre-compiler hints and filter list sources for Edge and Opera

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/AdguardBrowserExtension#2380]
### AdGuard Extension version

4.2.133 beta

### Browser version

Edge 114.0.1823.55

### OS version

Windows 11

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Annoyances filter

### Issue Details

Related to this issue - https://github.com/AdguardTeam/AdguardFilters/issues/154327

Steps to reproduce:
1. In Edge browser install AdGuard AdBlocker (Beta) 4.2.133
2. Navigate to - [https://forum.dobreprogramy.pl/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fforum.dobreprogramy.pl%2F)
3. Disable protection
4. Enable protection
5. Add this rule:
```adblock
forum.dobreprogramy.pl##body
```
6. Refresh website

Rule doesn't work.

### Expected Behavior

Website should be blank.
Another problem is that disabling protection doesn't work correctly and ads are not displayed.

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/29142494/e6b884b2-3401-46f2-8c1f-c327557240d9)

</details>

<details><summary>Screenshot 2:</summary>

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/29142494/2b1b43a4-9284-48ed-913f-afeecfb1b7d3)

</details>

### Additional Information

It seems that it's related to service worker, after unregistering it element hiding rule (`forum.dobreprogramy.pl##body`) works correctly.

**Comment by ameshkov** [comment]
After some internal discussions, here's my (hopefully) final suggestion:

1. Keep using different lists for Chromium, Edge and Opera
2. Change the logic for pre-compiler hints in the following way:

    * Chrome: `adguard_ext_chromium`
    * Opera: use two flags: `adguard_ext_chromium` + `adguard_ext_opera`
    * Edge: use two flags: `adguard_ext_chromum` + `adguard_ext_edge`

3. Make the same change to the FiltersCompiler
4. Update the knowledge base with the updated information: https://adguard.com/kb/general/ad-filtering/create-own-filters/#conditions-directive

**Comment by krystian3w** [comment]
How will it work with uBo directives? Will it have to be encapsulated into two ifs independently? Example:

<table><tr><td>

```adb
!#if env_chromium
!#if adguard_ext_opera
foo.bar##.opera
!
!
!#endif
!#endif
```

</td><td>

```adb
!#if env_chromium
!#if adguard_ext_edge
foo.bar##.edge-chromium
!
! maybe edge legacy too
!#endif
!#endif
```

</td></tr></table>

**Comment by ameshkov** [comment]
Neither option will work.

Does uBO support conditions? 

Something like that should be good:
```
!#if env_chromium || adguard_ext_opera
foo.bar##.opera
!#endif
```

**Comment by krystian3w** [comment]
It does not support and is not planned to be implemented e.g. due nesting is fixed in uBo 1.20.0+.
Then the filter "rule" for AdGuard is executed in uBo (condition marked as invalid is not ignored).

So it comes out that in the end it should be like this after all:

```adb
!#if !ext_ublock
!#if !ext_ubol
!#if env_chromium || adguard_ext_opera
foo.bar##.opera
!#endif
!#endif
!#endif
```

**Comment by ameshkov** [comment]
I am not sure how to resolve this without conditions support.

Probably you'll need to use two different blocks for AG and uBO.

**Comment by ameshkov** [comment]
> It does not support and is not planned to be implemented e.g. due nesting is fixed in uBo 1.20.0+.

Nesting only solves `&&` condition, it does not replace `||` which is needed more often to be honest.

Why was the feature request for conditions support rejected?

**Comment by krystian3w** [comment]
I would fudge that because of the small number of real-world usages/cases (high chance of parser corruption when the code is written only by gorhill and no one catches all the implementation bugs in the beta).

**Comment by gorhill** [comment]
Support for AdGuard-compatible proprocessing expressions was added a bit over two weeks ago: <https://github.com/gorhill/uBlock/commit/194354cd5d77>. I was not aware of the issue here. just a coincidence that I decided to support this to increase compatibility.

**Comment by ameshkov** [comment]
@gorhill looks great, thank you!
