### ISSUE TITLE
Adguard does not detect the currently opened site

### ISSUE THREAD

**Issue by richie3011** [AdguardTeam/AdguardBrowserExtension#2382]
### AdGuard Extension version

4.1.56

### Browser version

Kiwi browser 112

### OS version

Android 13

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Annoyances filter, AdBlockID, Peter Lowe's Blocklist, Online Malicious URL Blocklist

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters, Hide your search queries, Send websites signals not to track you, Self-destruction of third-party cookies, Hide Referrer from third parties, Remove X-Client-Data header, Disable WebRTC

### Issue Details

Adguard doesn't detect currently opened site,only seen chrome://newtab/. I also can't use block ads on this wesite,report an issue and check website security from Adguard extension

### Expected Behavior

Adguard should be able to detect which sites are currently open & can use these features: block ads from the website,report an issue and check website security from Adguard extension directly 

### Screenshots

![Screenshot_2023-06-24-07-19-00-11_4d38fce200f96aeac5e860e739312e76](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/98148960/ba293d13-19c9-4cd5-b80d-886659dd4761)
![Screenshot_2023-06-24-07-18-54-48_4d38fce200f96aeac5e860e739312e76](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/98148960/6bb4d3d4-aa68-4f43-b196-5fac9962c2c2)

### Additional Information

All ads are well blocked. it's just that the problem is adguard doesn't detect websites like I explained above

**Comment by alexx7311** [comment]
Hello! We were able to reproduce the problem. Steps to reproduce:
1. Install Kiwi browser 112
2. Go to Kiwi browser settings > Extensions and install AdGuard Extension
3. Open any website (e.g. facebook.com)
4. Go to Kiwi browser settings > AdGuard AdBlocker
5. Check the currently opened site in extension
