### ISSUE TITLE
requests show blocked then unblocked then back to blocked in log

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardBrowserExtension#2383]
### AdGuard Extension version

4.1.56

### Browser version

Microsoft Edge

### OS version

Windows 11

### Issue Details

if i look in the log. things will be blocked then show unblocked then back to blocked. this has happened a couple times.

### Screenshots

<details><summary>Screenshot 1:</summary>

![Untitled](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/118186787/e0fd5785-cd59-4173-a638-04978ef40aab)

</details>

**Comment by maximtop** [comment]
Thank you, 
Could you please share the link where you observe this problem?

**Comment by jordanswrld94** [comment]
i think it maybe happening on multiple websites. youtube loaded ads today. dont know if it was pertaining to this issue or that they are using googlevideo.com to load ads now

**Comment by jordanswrld94** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/152988#issuecomment-1607698202

**Comment by maximtop** [comment]
I wasn't able to reproduce the issue. It might be related to a potential network instability on your end. Could you please share the details from the Network tab in Chrome DevTools, as well as the filtering log? This will help us troubleshoot the problem further.
