### ISSUE TITLE
Adguard: blocking web worker, service worker

### ISSUE THREAD

**Issue by Clemens-Ratte-Polle** [AdguardTeam/AdguardBrowserExtension#2385]
Moin.
How can i see all workers pages using?
With uMatrix i can block or allow workers by default.
Too many sites use workers in background but could also function without them.
So i want to forbid all cause of security reasons.
Is that recommended?
thx

**Comment by alexx7311** [comment]
We do not have such a function and do not plan to implement it yet. 

Service workers are part of the web and they do no harm in and of themselves. 
If we see cases where they are used for tracking in any way that would require separate rules for blocking, we will consider it.

**Comment by Clemens-Ratte-Polle** [comment]
ok, but the service worker or webworkers are really big for most people who do not know about this option:
chrome://settings/content/all
chrome://serviceworker-internals/
For sites you know that is unimportant you can delete them.
