### ISSUE TITLE
router.vuejs.org - link buttons do not work

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/AdguardBrowserExtension#2390]
https://github.com/AdguardTeam/AdguardFilters/issues/155459.
To reproduce it:
1. Disable filters and other modules in the extension
2. Open `router.vuejs.org` in Firefox private tab
3. Click on the button `Get Started`
4. Nothing happens. There you should be redirected to `https://router.vuejs.org/installation.html`
5. If you can't reproduce it, follow the steps again in new private tab in the same session until you get it.

<details><summary>Error in the console:</summary>

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/33488229/a90b9d37-3b8c-41dc-96c3-56735a4a2f94)

</details><br/>

**Comment by BANOnotIT** [comment]
https://github.com/vuejs/router/issues/1757#issuecomment-1642617962

**Comment by Birbber** [comment]
@BANOnotIT Hello, the issue's indeed on FireFox side, and it's not affected by our extension. Thank you for the update!
I'm closing this issue. Please re-open if needed.
