### ISSUE TITLE
IndexedDB is not working in the private browsing mode in firefox extension

### ISSUE THREAD

**Issue by emikaadeo-git** [AdguardTeam/AdguardBrowserExtension#2391]
### AdGuard Extension version

 4.1.56, 4.2.133

### Browser version

Firefox 115.0

### OS version

Windows 11, macOS 13.4.1

### What filters do you have enabled?

AdGuard Base filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Tracking Protection filter

### Issue Details

After installing new version of Firefox (115.0) and browser restart, the number of filter rules shows `"0"` which makes AdGuard extension not working on any website.
The number of filter rules is cleared on every browser restart.
Tested with `4.1.56` stable and `4.2.133` beta version of AdGuard Extension
Tested OS: Windows 11, macOS 13.4.1
New Firefox funcionality [https://support.mozilla.org/pl/kb/quarantined-domains](https://support.mozilla.org/pl/kb/quarantined-domains) already set to `false`

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by alexx7311** [comment]
Hello! Are you referring to the counter in the AdGuard popup or to the number of rules in the Filters tab of the extension settings? Please record a video of the problem so that we can reproduce it.

**Comment by emikaadeo-git** [comment]
Hi, I'm referring to the number of rules in the Filters tab of the extension settings.
Right now I can't record a video (maybe later)

Here are some screenshots:

- Number of Filters rules (click Check Updates) when Firefox is running
![FF_01](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/56483380/094b4619-3a47-47be-9630-c75f41449457)

- Number of Filters rules after Firefox restart
![FF_02](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/56483380/38b30e1e-648a-4336-9d79-447205979cfe)

**Comment by alexx7311** [comment]
We couldn't reproduce the problem. What exact steps do you take to reproduce the problem? Please send us the video later, if possible.

**Comment by emikaadeo-git** [comment]
Exact steps to reproduce the problem:

- Upgrade (or clean install) Firefox to version 115.0
- Launch Firefox
- Go to Filters tab of the extension settings
- Click "Check for updates" to update Filters rules (in my case number of Filters rules shows `221419`)
- Exit Firefox
- Launch Firefox again
- Go to Filters tab of the extension settings again
- Number of Filters rules shows `0`

**Comment by emikaadeo-git** [comment]
I don't know if it matters but my Firefox is configured to **Always use private browsing mode** in preferences UI (see about:preferences#privacy)

**Comment by alexx7311** [comment]
Hello! We were able to reproduce the problem with 'Always use private browsing mode' option enabled.

**Comment by maximtop** [comment]
It seems that the Firefox team has fixed a [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1639542) where IndexedDB wasn't functioning in private browsing mode. Our extension stores the rules in IndexedDB, and we have a fallback for when IndexedDB isn't available, as was the case in versions prior to 115. When Firefox fixed this, IndexedDB appeared to work, but in reality, it gets cleared or something similar with every browser reload.

I've filed a bug report here: https://bugzilla.mozilla.org/show_bug.cgi?id=1841806. We're now considering our next steps - either remove IndexedDB from our modules and use localStorage, or wait for a fix from Firefox.

**Comment by ameshkov** [comment]
Let's wait until monday and see how Mozilla reacts. If there's no reaction we may consider a hotfix.

**Comment by maximtop** [comment]
The extension is under review. Once it passes the review, it will be published.

**Comment by emikaadeo-git** [comment]
Firefox 116.0.3 with [fix](https://bugzilla.mozilla.org/show_bug.cgi?id=1841806#c31) from Mozilla is on the way.
There's still no 4.2.151 (which contains fix from AdGuard) on [AMO](https://addons.mozilla.org/pl/firefox/addon/adguard-adblocker/) so if you install FF 116.0.3 with 4.2.142 the bug will reapear :(
