### ISSUE TITLE
Greeting page whenever Firefox starts

### ISSUE THREAD

**Issue by BANOnotIT** [AdguardTeam/AdguardBrowserExtension#2394]
### AdGuard Extension version

Version 4.1.56

### Browser version

Firefox 115.0 (64-bit)

### OS version

Ubuntu 22.04.2

### Issue Details

Whenever I start Firefox the extension thinks I just have installed it and shows me the greeting page.

### Expected Behavior

Just start Firefox and the extension should be silent and just do its work.

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/11363215/3263bc4a-85e4-4b18-979d-7b019bd6865a)

</details>

**Comment by alexx7311** [comment]
Hello! We couldn't reproduce the problem. Please reinstall the extension and restart Firefox. Did the problem recur?
Does the problem recur in other browsers?

**Comment by BANOnotIT** [comment]
Yeah... Reinstalling the extension somehow helped. Next time will do that first.
