### ISSUE TITLE
Extensions detects link like an advertising

### ISSUE THREAD

**Issue by 0x800040005b** [AdguardTeam/AdguardBrowserExtension#2398]
### AdGuard Extension version

4.1.56

### Browser version

different browsers

### OS version

Windows

### What filters do you have enabled?

AdGuard Base filter

### Issue Details

Hi! I try to develop laravel application. And when i get into some pages on site there is button 

for example: create page, or add Post. But there is empty block with width: 0 and height: 0;

when i disabled an extension the links appeared. But it's a very important buttons for my site. How to fix it, in addition to adding to the white-list??? Thanks! 

                        <a href="{{ route('page.create') }}"
                            class="btn btn-outline-primary custom-btn-small mb-0 {{ languageDirection() == 'ltr' ? 'me-0' : 'ms-0' }} mt-2 mt-md-0">
                            <span class="fa fa-plus"> &nbsp;</span>{{ __('Add Page') }}
                            
                            

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/67833526/db8763ce-89aa-41ca-9047-5246025a9bb6)

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/67833526/48bbfcf0-db45-4352-9c79-75c3d9820619)

</details>

### Additional Information

asdaasdqwe

**Comment by alexx7311** [comment]
Hello! Please open AdGuard popup > AdGuard Settings > User rules (make sure it's on) and try adding this rule to User rules:

`@@||coolorca.cc^$document`

**Comment by alexx7311** [comment]
@0x800040005b Is the problem still relevant?
