### ISSUE TITLE
Add 'Protect from DPI' and 'Encrypted Client Hello (ECH)' to Adguard extension

### ISSUE THREAD

**Issue by xiulou23** [AdguardTeam/AdguardBrowserExtension#2400]
### Issue Details

“保护免受DPI影响”和“使用加密的Client Hello”这两个功能对保护隐私方面起到重要作用，但是为什么到现在为止没有加入到Adguard浏览器扩展中？是因为技术上做不到吗？如果技术上可行的话，我希望你们能尽快把这两个功能加进Adguard扩展中

**Comment by Birbber** [comment]
@xiulou23 Hello! Thank you for the suggestion, but unfortunately it's impossible to implement in browser extension. Try using our desktop application instead.
