### ISSUE TITLE
Some matches-attr rules with {n,} in regex are highlighted as error

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AdguardBrowserExtension#2401]
### AdGuard Extension version

4.1.56

### Browser version

Brave v1.52.130

### OS version

Windows 10

### What filters do you have enabled?

AdGuard Base filter, AdGuard Japanese filter

### Issue Details

This User rule `pussyspace.com,pussyspace.net#?#.itemsetbox [class]:matches-attr("class"="/[0-9A-Za-z]{18,}/") [id] img:not(a img)` is highlighted as error. This also caused false positive, but apparently it was due to https://github.com/AdguardTeam/ExtendedCss/issues/166 and not related to the problem here. Error disappers if I remove `{18,}`, but some rules in Japanese filters don't show error despite having {n,}, namely:
```
realtime-chart.info#?#.news_b table[border="0"][cellpadding="5"][style="background:#fff"] > tbody >  tr[bgcolor="#fff"] > td.newsarea[style] > a.wl[href^="https://a"][href*=".to/"]:upward(2)
realtime-chart.info#$?#div[id] > [id]:has(> [style^="top:1"]:matches-attr("style"="/top\s*:\s*1\d{3}\.?\d*px/")) + * > [style^="top:1"]:matches-attr("style"="/top\s*:\s*1\d{3}\.?\d*px/") > [onclick]:not(:has(td > a))  { pointer-events: none !important; }
realtime-chart.info#$?#div[id] > [id]:has(> [style^="top:1"]:matches-attr("style"="/top\s*:\s*1\d{3}\.?\d*px/")) + * > [style^="top:1"]:matches-attr("style"="/top\s*:\s*1\d{3}\.?\d*px/") > [style*="font-size:"]:is(b, span, a):not(:has(td > a)) { font-size: 0 !important; pointer-events: none !important; }
realtime-chart.info#$?#td[style^="vertical-align"] div[style*="top"]:matches-attr("style"="/^\s*top\s*:\s*3\d{2}\.?\d*px;?\s*/") > a[id][onmousedown] { pointer-events: none !important; }
realtime-chart.info#$?#td[style^="vertical-align: top"] [onclick*="()"][target="_blank"]:has([style*="background-image: url\(\"data:image/jpg;"]:matches-attr("style"="/height\s*:\s*[12]\d{2}\.?\d*px/")) { pointer-events: none !important; }
realtime-chart.info#$?#td[style^="vertical-align"] [style*="top"]:matches-attr("style"="/^\s*top\s*:\s*3\d{2}\.?\d*px;?\s*/") > a[id][onmousedown] { pointer-events: none !important; }
```
The only rule also shows error is `realtime-chart.info#?#td[style^="vertical-align"] div[id] [style*="top"]:matches-attr("style"="/^\s*top\s*:\s*3\d{2}\.?\d*px;?\s*/") ~ [class][onclick]:has(> [style^="top:1"]):matches-attr("style"="/top\s*:\s*1\d{3}\.?\d*px/"):not(:has(td > a))` which I removed by https://github.com/AdguardTeam/AdguardFilters/commit/7b7094cbad4a0d6925c9efd4977bddd0f03e7f47
The rules seem to work, so maybe they're incorrectly flagged as error.

### Expected Behavior

No error

### Screenshots

<details><summary>Screenshot 1:</summary>

![rules](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/58900598/b950290b-f943-49ae-9b12-299279f2476c)

</details>

**Comment by alexx7311** [comment]
@Yuki2718 The [beta](https://github.com/AdguardTeam/AdguardBrowserExtension/releases/tag/v4.2.151-beta) is out!
