### ISSUE TITLE
edgeで同期機能を使っていて、adguardダウンロード時にesetがウィルス反応出した。

### ISSUE THREAD

**Issue by takuyatahata** [AdguardTeam/AdguardBrowserExtension#2402]
### AdGuard Extension version

AdGuard 広告ブロッカー

### Browser version

edge

### OS version

 (Get-Item (Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\msedge.exe').'(Default)').VersionInfo.ProductVersion 114.0.1823.86

### Issue Details

エッジの同期機能でダウンロードして使っていたがesetでウィルス反応が出た。

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>
![スクリーンショット 2023-07-11 172707](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/41463834/53ddfe9e-ab47-4503-9da4-dbaffe7d5081)

### Additional Infor
![スクリーンショット 2023-07-11 172801](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/41463834/06b51791-7fc6-4108-9c28-b840e2329ba0)
mation

_No response_

**Comment by Birbber** [comment]
@takuyatahata Please give us more information on the issue.

**Comment by Birbber** [comment]
Closing this issue due to no reply. Please re-open if needed.

**Comment by takuyatahata** [comment]
@Birbber 
Hi,
風邪を引いて休んでいました、返事が遅れてすみません。
edgeのブラウザを使っていてアダルトサイトにアクセスしたときに、マルウェアの反応が出たのだと思います。
ネット喫茶のパソコンは一応セキュリティソフトが入っていてウイルスに反応します。
安全にブラウザを使うこつがあれば教えてください。
XDMの拡張機能は正規の物かわかりません。
