### ISSUE TITLE
Using qoura.com with AdGuard

### ISSUE THREAD

**Issue by amdredlambda** [AdguardTeam/AdguardBrowserExtension#2403]
### AdGuard Extension version

4.1.56

### Browser version

FireFox 115.2.0 (Build #2015961525), ff36f634f8+ GV: 115.0.2-20230710165010 AS: 115.0 2023-07-10T22:00:31.350313

### OS version

Google ChromeOS Version 103.0.5060.132 (Official Build) (64-bit)

### Issue Details

All Filters, but Language especific and Custom, are enabled.
All Stealth Modes settings, but Self-destruct First-party cookies and WebRTC, are enabled.

Hi,
qoura.com functions like login, ../answer/request, .../draft, and profile browse fail to operate unless quora.com is added to AdGuard Allowlist setting. Will be possible to point at which setting are appropiate to use in AdGuard to use quora.com whitout allowlisting the entire domain. Or if there is a fix to work around the use of AdGuard protection in quora.com

Thanks

### Expected Behavior

To be able to use AdGuard protection in quora.com

### Screenshots

<details><summary>Screenshot 1:</summary>

![Screenshot 2023-07-18 11 01 38 AM](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/139887822/010c608c-07a3-4777-ba89-3362f130689b)
![Screenshot 2023-07-18 11 00 08 AM](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/139887822/9e8ae6cd-321c-46fc-9af2-ba681e924e6a)

</details>

**Comment by Birbber** [comment]
@amdredlambda Hello! There's no need in enabling every filter available. You can read their description and decide which ones are not necessary for you. 
Try disabling some of the filters from 'Privacy' group. For example, 'Fanboy's Anti-Facebook List', 'Fanboy's Anti-thirdparty Fonts', 'Legitimate URL Shortener', etc.

**Comment by alexx7311** [comment]
@amdredlambda Hello! Is the problem still relevant? If you do not respond within a few days, the issue will be closed.
