### ISSUE TITLE
Filters can not enable but can disable

### ISSUE THREAD

**Issue by ZHLONG-CN** [AdguardTeam/AdguardBrowserExtension#2405]
### AdGuard Extension version

4.1.57

### Browser version

Microsoft Edge 114.0.1823.82

### OS version

Windows 10 x64 and Windows 11 x64, 22h2

### Issue Details

I am going to setting adguard for my new Windows 11 PC, with Microsoft Edge. When I enable any filters, and refresh the settings page, it show disabled again. And I disable the default filter which is enabled, refresh the page and it show disabled, and I can not enable it again.

It happened on my old PC and new PC.

**Comment by Birbber** [comment]
@ZHLONG-CN Hello! We couldn't reproduce the issue on our end. 
Have you tried re-installing the extension? 
Please check `background.html` console for any errors and share a screenshot.

<img width="852" alt="изображение" src="https://github.com/AdguardTeam/AdguardBrowserExtension/assets/78078725/5b4c7367-cece-4944-b8fd-73f9fe0779ee">
