### ISSUE TITLE
Unable to enable Chinese filter

### ISSUE THREAD

**Issue by ioqq** [AdguardTeam/AdguardBrowserExtension#2409]
### AdGuard Extension version

4.1.57

### Browser version

chrome115

### OS version

Windows10

### What filters do you have enabled?

AdGuard Base filter, AdGuard Social Media filter, AdGuard Annoyances filter, EasyList

### What Stealth Mode options do you have enabled?

Disable WebRTC

### Issue Details

I want to turn on the AdGuard Chinese filter, but every time I turn it on, I refresh the page and it will return to the off state

### Expected Behavior

Enable Chinese filter normally

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>
https://github.com/AdguardTeam/AdguardBrowserExtension/assets/60423609/5e522949-ce29-4c0d-acb6-d3457a36251c

**Comment by Birbber** [comment]
@ioqq Hello! We weren't able to reproduce the issue on our end. Does this issue occur with Chinese filter only or maybe other filters you enable get disabled, too?
Do you use any extensions that might affect AdGuard extension?

**Comment by ioqq** [comment]
![imgonline-com-ua-converthLnpBxRdNIpf](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/60423609/d49400f6-b781-40ff-8396-548174c3d042)
@Birbber

**Comment by maximtop** [comment]
If you open this link in the browser, is it opened as expected?

**Comment by ioqq** [comment]
@maximtop https://filters.adtidy.org/extExtension/chromium/filters/224.txt I can't access the domain name, maybe it is my network problem，Let me try if the network operator can solve it

**Comment by Birbber** [comment]
@ioqq Any news on this issue?

**Comment by Birbber** [comment]
@ioqq Is this issue still reproducible?
