### ISSUE TITLE
An Application Error occured when visiting a website for the first time

### ISSUE THREAD

**Issue by OreoProMax** [AdguardTeam/AdguardBrowserExtension#2416]
### AdGuard Extension version

4.1.57

### Browser version

Edge 115.0.1901.183 and Chrome 114.0.5735.199

### OS version

Windows 11

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter, Online Malicious URL Blocklist, NoCoin Filter List

### Issue Details

The first time trying to access [https://beta-accounts.paradoxinteractive.com/login?returnUrl=/redeem](url) will encounter an Application Error and persistent console error generating. Get recovered after turning off the ADguard. Reproduced both in my Edge 115.0.1901.183 and Chrome 114.0.5735.199. It seems to be cookie-related.

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/61046258/d26f658f-72e4-4860-8c58-787c865218fa)

</details>

**Comment by alexx7311** [comment]
Hello! Most likely it's a filter problem, not the extension problem. Please report this website via the extension popup. Most of the fields will be filled in automatically, you can find step-by-step instructions at https://adguard.app/kb/guides/report-website/#form
