### ISSUE TITLE
Add support for Xbox

### ISSUE THREAD

**Issue by MistakingManx** [AdguardTeam/AdguardBrowserExtension#2419]
### Issue Details

On the Microsoft Edge app for Xbox, there's a website (microsoftedge.microsoft.com/addons) that lists AdGuard by Performix.
But when trying to install it, it states "An error has occurred".

### Proposed solution

I'd like AdGuard to come up with a way to support Xbox consoles, since they're so restricted in the browser-space.

### Alternative solution

I've tried using AdGuard Home, but it doesn't work well enough, very intrusive ads still take over the web.

**Comment by slavaleleka** [comment]
are you sure other browser extensions are available for Edge on Xbox?

**Comment by Birbber** [comment]
@MistakingManx Hi. It's said on [Xbox support page](https://support.xbox.com/en-US/help/hardware-network/console/use-microsoft-edge-on-xbox) that some features that exist on other versions of Edge (like downloads or browser extensions) aren’t supported on the console version of the browser.

**Comment by MistakingManx** [comment]
Downloads have been on Xbox's Edge for years, but I can't confirm support for extensions has been added yet.

I recall that I read somewhere that it's the developer 's job to ensure compatibility, but I can chalk that up to misremembering. I have a habit of mixing things up somewhere.
