### ISSUE TITLE
Cannot apply CSS rules inside iframe

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#2420]
### AdGuard Extension version

4.2.142

### Browser version

114

### OS version

Windows 10

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard French filter

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters, Hide your search queries, Send websites signals not to track you, Self-destruction of third-party cookies, Self-destruction of first-party cookies, Hide Referrer from third parties, Remove X-Client-Data header, Disable WebRTC

### Issue Details

**URL**: `https://maxppp.com/`
**Rules:**

```
maxppp.com#$#.cdk-overlay-container { display: none !important; }
maxppp.com#$#body.gb-global-scrollblock { overflow: auto !important; }
```

<details>
<summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/8361299/0ccbedf6-34f6-4029-820d-886b7e9a170c)

</details>

<details>
<summary>Screenshot 2 - the rules above are not applied:</summary>

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/8361299/0cc030c3-9446-4e40-b541-86aae3cd8dea)

</details>

### Expected Behavior

Popup must be hidden.

### Additional Information

No issues with AdGuard apps.

**Comment by maximtop** [comment]
The same problem is on the v4.1 too.

**Comment by AdamWr** [comment]
It seems that the similar issue occurs with version 4.2.151, related to - https://github.com/AdguardTeam/AdguardFilters/issues/158843

Ad marked on the screenshot below should be hidden by `##.playerinads` rule, but it doesn't work.

<details><summary>Screenshot 1</summary>

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/29142494/05e3625c-e619-4c5f-8443-40d2ced4a23c)

</details>

The problem doesn't occur when website is loaded, but if you click on a different video player, for example "Vidmoly" (marked on the screenshot below) and again on "Roll+", then rules are not applied to iframe.

<details><summary>Screenshot 2</summary>

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/29142494/d5f6447b-27e4-44e3-9431-9b84cdc4f2c1)

</details>

Steps to reproduce
1. Add this rule:
```adblock
 contentx.me#%#alert(1);
 ```
2. Go to - [https://diziroll.co/dizi/what-we-do-in-the-shadows/sezon-5/bolum-6](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fdiziroll.co%2Fdizi%2Fwhat-we-do-in-the-shadows%2Fsezon-5%2Fbolum-6)
3. Alert will be displayed, it's okay
4. Click on `Vidmoly` button (marked on screenshot 2 above)
5. Click on `Roll+` button
6. There should be an alert again, but it doesn't work

It looks like that in this case it works correctly with version 4.1.57.

**Comment by maximtop** [comment]
> 4.2.159 beta doesn't fix it.

task is still open

**Comment by maximtop** [comment]
It's a bot; I suggest watching the results.
<img width="333" alt="image" src="https://github.com/AdguardTeam/AdguardBrowserExtension/assets/17272769/fd18b701-b385-4ff6-9fdd-98fedca3e40c">
