### ISSUE TITLE
Automatic filters update does not work in mobile browsers

### ISSUE THREAD

**Issue by ChowMein47** [AdguardTeam/AdguardBrowserExtension#2423]
### AdGuard Extension version

4.1.57

### Browser version

Kiwi Browser 116.0.5845.61 & Firefox mobile 116.3.0

### OS version

Android 13 

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters, Hide your search queries, Send websites signals not to track you, Self-destruction of third-party cookies, Hide Referrer from third parties, Remove X-Client-Data header, Disable WebRTC

### Issue Details

Automatic filter update doesn't work. I set it to standard but I have to update it manually everyday 

### Expected Behavior

Automatic filters update should be work 

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by emikaadeo-git** [comment]
Same here on desktop.
Firefox 116.0.1
macOS 13.5
AdGuard version 4.2.142

**Comment by Ricardojim133** [comment]
> ### AdGuard Extension version
> 4.1.57
> 
> ### Browser version
> Kiwi Browser 116.0.5845.61
> 
> ### OS version
> Android 13
> 
> ### What filters do you have enabled?
> _No response_
> 
> ### What Stealth Mode options do you have enabled?
> Block trackers, Remove tracking parameters, Hide your search queries, Send websites signals not to track you, Self-destruction of third-party cookies, Hide Referrer from third parties, Remove X-Client-Data header, Disable WebRTC
> 
> ### Issue Details
> Automatic filter update doesn't work. I set it to standard but I have to update it manually everyday
> 
> ### Expected Behavior
> Automatic filters update should be work
> 
> ### Screenshots
> Screenshot 1:
> ### Additional Information
> _No response_

**Comment by ameshkov** [comment]
v4.2 is already out so no, only in v4.3.
