### ISSUE TITLE
Userscript Support

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardBrowserExtension#2424]
### Issue Details

AG extension currently does not support userscripts. A separate extension could be added in the AG extension itself to install and use userscripts.

### Proposed solution

Just like AG for Android/PC, is it feasible to include userscript functionality even in AG extension without it getting heavy on resources and slowing down browsing? If so, then may you consider the possibility of adding this feature?

### Alternative solution

Currently, a separate extension is needed to install and user userscripts in a web browser.

**Comment by Birbber** [comment]
@Nzzyme Hello. We won't be able to do this, since adding userscripts will violate 'one purpose' policy of Chrome Store.

**Comment by Ricardojim133** [comment]
> ### Issue Details
> AG extension currently does not support userscripts. A separate extension could be added in the AG extension itself to install and use userscripts.
> 
> ### Proposed solution
> Just like AG for Android/PC, is it feasible to include userscript functionality even in AG extension without it getting heavy on resources and slowing down browsing? If so, then may you consider the possibility of adding this feature?
> 
> ### Alternative solution
> Currently, a separate extension is needed to install and user userscripts in a web browser.
