### ISSUE TITLE
When using element blocker tool, some elements are clicked on instead of becoming selected

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardBrowserExtension#243]
For example:
http://z26i.imgup.net/ADs98b9.png

on this page:
http://www.cast4u.tv/embedcr.php?live=hdch9&vw=620&vh=490

Originally from http://forum.adguard.com/showthread.php?10376

**Comment by vbagirov** [comment]
Another example is 
http://praxistipps.chip.de/iphone-sperrcode-vergessen-was-tun_1427

From forum thread:
https://forum.adguard.com/index.php?threads/manual-blocking-clicks-the-element.9857/#post-81864

**Comment by Mizzick** [comment]
Fixed
