### ISSUE TITLE
Russian translation detected in Edge when installing extension from MS add-ons

### ISSUE THREAD

**Issue by AleksandrKalininAdGuard** [AdguardTeam/AdguardBrowserExtension#2430]
### AdGuard Extension version

4.1.57

### Browser version

MS Edge, Version 115.0.1901.203 (Official build) (64-bit)

### OS version

Win 11

### Issue Details

When installing the AdGuard browser extension from MS add-ons, MS Edge detects Russian language and offers translation even if the page doesn't contain Russian language.

### Expected Behavior

The translation option from Russian to English shouldn't appear.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by AleksandrKalininAdGuard** [comment]
+ CRM 791437

**Comment by ameshkov** [comment]
We can also use this:
https://www.w3.org/International/questions/qa-translate-flag
