### ISSUE TITLE
Can't disable WebRTC on stealth mode

### ISSUE THREAD

**Issue by ChowMein47** [AdguardTeam/AdguardBrowserExtension#2434]
### AdGuard Extension version

4.2.151

### Browser version

Kiwi Browser 116.0.5845.70

### OS version

Android 13 

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdBlockID

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters, Hide your search queries, Send websites signals not to track you, Self-destruction of third-party cookies, Hide Referrer from third parties, Remove X-Client-Data header

### Issue Details

Can't disable WebRTC.The button cannot be activated 

### Expected Behavior

The enable webrtc button can be activated 

### Screenshots

<details><summary>Screenshot 1:</summary>

![GridArt_20230815_091609025](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/98148960/9b2e09a3-fa2a-4399-8562-295ea4052fa9)

</details>

**Comment by ameshkov** [comment]
Duplicates https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2436
