### ISSUE TITLE
Can't close adguard

### ISSUE THREAD

**Issue by Karmylr** [AdguardTeam/AdguardBrowserExtension#2439]
### AdGuard Extension version

4.1.57

### Browser version

Chrome 115.0.5790.171

### OS version

Windows 10

### What filters do you have enabled?

AdGuard Base filter, AdGuard Chinese filter

### Issue Details

Can't close adguard

### Expected Behavior

Don't block ads on this page when I turn off the switch bottom.

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/69903376/fbb6f929-d391-41cf-8841-2695a9ce061a)

</details>

**Comment by ameshkov** [comment]
Please update to version 4.2.

**Comment by Karmylr** [comment]
![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/69903376/34b684a9-6115-43c6-a4f2-ba745a7de14d)
![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/69903376/b8de259f-b7aa-4864-a32a-baf81f2d5175)
