### ISSUE TITLE
Adguard's benchmark scores

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardBrowserExtension#244]
Performance issue: according to this (https://www.raymond.cc/blog/10-ad-blocking-extensions-tested-for-best-performance/) benchmark test, adguard is performing better than ABP, but slightly lesser than ublock in CPU usage or page loading speed. Yet this benchmark is about Adguard as an extension, but I experienced that ublock is certainly faster in loading pages, compared to Adguard windows. What is a reason of this performance difference? Are developers of Adguard aware of it? ublock is an open source and it might be possible to get an idea of their performance from their code (I am sorry I am saying this too easily, developing a software would be a huge task that I can't imagine of, please ignore if these are too stupid words) (2 - 1) I've read this (chrisaljoudi/uBlock#161) where developers of ublock origin states that they inject certain filter about www.faceporn.net ads when there exists elements that only matches its first 8 characters "www.face" for performance reasons. I am wondering if Adguard does similar things when injecting filters. For example I am aware of English filter's general CSS injection rule to neutralize fuckadblock.js scripts. It seems that it is injected in every webpage, but maybe we can try to search for fuckadblock.js or blockadblock.js and inject the rule only for those with matching search results. This seems to be what ublock is doing.

**Comment by SlowMemory** [comment]
When tested on my machine with Chrome, ublock origin performs mostly better in terms of timings of domcontentloaded and load events.

**Comment by ameshkov** [comment]
@SlowMemory with the very same filters?

**Comment by SlowMemory** [comment]
Technically using the same filters is impossible, implementation details are different and there are incompatibility in filter rules. 

I did a quick test on loading time with Adblock plus, Adguard, ublock origin, with only EasyList and EasyPrivacy enabled, although I usually use English filter and Spyware filter with Adguard. Cache was enabled, which is different from the benchmark test in OP.

google.com - Adguard: 497ms, ABP: 417ms, Ublock origin: 350ms (both DOMContentLoaded and load)
cnn.com - Adguard: 1.39s/6.82s, ABP: 1.40s/7.15s, Ublock origin: 1.25s/5.99s (DOMContentLoaded/load)

What is doubtful about the benchmark test in OP is memory usage test, on my end Adguard consumes the lowest memory in most cases.

**Comment by ameshkov** [comment]
497ms for Google seems to be too much, are you sure "send ad filters stats" is turned off?

**Comment by SlowMemory** [comment]
Yes, I had disabled every settings but those in ad blocker module.

**Comment by ameshkov** [comment]
I see an overhead ~50-100ms depending on the page layout complexity. This overhead is caused by the difference in applying cosmetic rules. AG&ABP inject stylesheets into a page and delegate further work to a browser. uBlock is trying to do everything on its own. On one hand doing so allows it to apply cosmetic rules a bit faster. On the other hand this approach leads to code complexity and potential mistakes.

**Comment by ameshkov** [comment]
And here is one interesting thing I've just noticed. If I make Adguard to apply cosmetic rules **after** DOMContentLoaded is already fired, the overhead seems to be almost gone. Weeeeird

**Comment by ameshkov** [comment]
@SlowMemory could you please test a build from this branch?
https://github.com/AdguardTeam/AdguardBrowserExtension/tree/feature/issues/244

**Comment by SlowMemory** [comment]
It does improves the loading time of google.com, it is now 374ms on my end.

**Comment by ameshkov** [comment]
Yep, the same for me, 10-30ms slower than uBO. I guess the difference is not that serious and we can safely ignore it.

Question: does it have any influence on ad blocking quality? Do you see any difference with that build?

**Comment by SlowMemory** [comment]
Now elements are hidden after it is displayed.

**Comment by ameshkov** [comment]
> Now some elements are hidden after it is displayed.

Hm, so you see the difference after all? I was afraid of that, but could not find a good example where I can observe this issue.

**Comment by SlowMemory** [comment]
Sorry, I should have provided an example. If I add a rule google.com##body to a user filter and visit google.com, it shows the page for a short time then it is hidden.

**Comment by sandybeachit** [comment]
I saw that same article did you guys manage to close the performance gap then between ublock and adguard? Just curious thats all.

Thanks
