### ISSUE TITLE
'Proceed anyway' does not work, or applies redirect to destination in another tab

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#2450]
### AdGuard Extension version

4.2.158

### Browser version

Chrome 116

### OS version

Windows 10 x64

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

### Issue Details

1. Add `$popup,domain=example.com`
2. Go to `example.com` (it will be [incorrectly blocked](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2449))
3. Press `Proceed anyway`

Destination link will be opened in the one of opened (existing) tabs.

### Expected Behavior

Redirect must be in the same tab with a blocking page.

**Comment by slavaleleka** [comment]
the issues cannot be reproduced with v4.2.168 beta
https://github.com/AdguardTeam/AdguardBrowserExtension/releases

**Comment by Alex-302** [comment]
Same with 4.2.167, but it seems it works with a delay ~3 s.
