### ISSUE TITLE
Disabling and reenabling AdGuard results in increase of CPU usage

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardBrowserExtension#2451]
### AdGuard Extension version

4.2.159 Beta

### Browser version

Chrome 116

### OS version

Windows 10 22H2

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Additional Information

Steps to reproduce:

1. Have 1000+ open/background tabs
2. Disable and reenable AdGuard Browser Extension

**Comment by alexx7311** [comment]
@859680 After re-enabling the extension, does the CPU load increase temporarily or does it increase and stay at a high level? The increase is due to page refresh, so the load should drop after a few seconds.

Please attach some screenshots to illustrate the problem.
