### ISSUE TITLE
Popup context showing wrong number of blocked ads

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardBrowserExtension#2453]
### AdGuard Extension version

4.2.159 Beta

### Browser version

Chrome 116

### OS version

Windows 10 22H2

### What filters do you have enabled?

AdGuard Base filter, AdGuard Russian filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Issue Details

https://streamable.com/hc795s
https://streamable.com/vgsq96

**Comment by ameshkov** [comment]
Could you please upload the video to GH, they're already expired on streamable.

**Comment by slavaleleka** [comment]
the issues cannot be reproduced with v4.2.168 beta
https://github.com/AdguardTeam/AdguardBrowserExtension/releases

could you please try it?
