### ISSUE TITLE
Specific rules not applied in the new tab on the first opening

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/AdguardBrowserExtension#2459]
### AdGuard Extension version

4.2.159

### Browser version

Chrome 116

### OS version

Windows 11

### What filters do you have enabled?

AdGuard Base filter

### Issue Details

Related to - https://github.com/AdguardTeam/AdguardFilters/issues/160293

It looks like that CSS exceptions do not work after closing and then opening the same website.

Steps to reproduce:
1. Add these rules:
```adblock
##body
example.org#@#body
```
2. Go to - https://example.org/
3. Close current tab
4. Open new tab and again navigate to - https://example.org/

Website is blank, exception rule is not applied.

<details><summary>Video</summary>

https://github.com/AdguardTeam/AdguardBrowserExtension/assets/29142494/3ff83576-7633-455f-9962-8f09cdeaae35

</details>

### Expected Behavior

`example.org#@#body` should be applied and content should be visible.

**Comment by AdamWr** [comment]
It seems that it's not only about element hide exceptions rules.
The same happens with JavaScript rules, for example:
```adblock
example.org#%#alert(1);
```
though it seems that for some reasons it's a bit harder to reproduce and doesn't occur as often as issue with exceptions.

**Comment by AdamWr** [comment]
>Is it the same as the issue here?

This one is rather a new issue and it probably didn't occur in previous version, I suppose it's not related to mentioned issue.

I guess that in the case of https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1772 it could have been a race condition and scriptlet was executed too late, but I'm just guessing.

**Comment by Alex-302** [comment]
Maybe related to this issue - sometimes, when I open Youtube in a new tab and open some (popupar) video, I see only blocked URLs in the filtering log, and video ads are not blocked.

<details>
<summary>Details</summary>

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/8361299/65ff2af1-d762-4093-aa93-7b81ccb078b6)


</details>

**Comment by zloyden** [comment]
Actually, I don't know if it's related to this issue or not, but I've seen the similar behaviour on `pikabu.ru`. Looks like the scriptlet rule does not apply when you open a new tab, but after refreshing the scriptlet shows on the console and works as expected.
