### ISSUE TITLE
Safari extension with old API blocks the same image multiple times

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#246]
Steps to reproduce:
1. Turn on Fanboys Annoyance filter
2. Open filtering log
3. Go to http://forums.plex.tv

You'll feel that page load is freezed and you'll see a lot of same images blocked:
http://forums.plex.tv/applications/dashboard/design/images/rss.gif

It looks like AG checks the same image every time, that shouldn't be like that.

Do we go "initCollapseMany" way for every page when using old API?

**Comment by Mizzick** [comment]
Fixed
