### ISSUE TITLE
Domains from the allowlist were not properly escaped before being passed into the regular expression rules.

### ISSUE THREAD

**Issue by DerFreischutzTKH** [AdguardTeam/AdguardBrowserExtension#2461]
### AdGuard Extension version

Adguard Chrome Extension 4.2.162

### Browser version

Chrome Version 116.0.5845.141 (Official Build) (64-bit)

### OS version

Win10 22H2 19045.3324

### What filters do you have enabled?

AdGuard Base filter, AdGuard Chinese filter, AdGuard Social Media filter, Others

### What Stealth Mode options do you have enabled?

Disable WebRTC

### Issue Details

After updating the Adguard Extension last night, I noticed that on all websites, Adguard displayed [Protection is disabled]. I tried pressing the Protection switch, but it still remained in the disabled state.

And then I noticed that in the filtering log, all websites were listed under the Allowlist.
![adbug1](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/46635684/bbb2ac84-8d2a-4afe-ad2b-2b7fe7a2a990)

After disabling the Allowlist, some websites started blocking ads.
Some websites, even after disabling the Allowlist, showed "Protection is enabled," but Adguard was still not functioning properly.
like twitter.com
![adbug2](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/46635684/9c50bcbf-06f7-4fec-b7aa-72471828adff)

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

I discovered that one of the lines in the allowlist caused the above-mentioned bug.
@@||jpg.church^
I haven't made any change to my allowlist for about half year.
I'm not sure when this line was added to the allowlist
But Adguard was working fine until it updated itself yesterday.

**Comment by maximtop** [comment]
Maybe you have "invert allowlist" option enabled?

**Comment by DerFreischutzTKH** [comment]
> Maybe you have "invert allowlist" option enabled?

nope

**Comment by zhelvis** [comment]
@DerFreischutzTKH Which version you are upgrading from?

**Comment by DerFreischutzTKH** [comment]
> Which version you are upgrading from?

I don't know

I discovered that one of the lines in the allowlist caused the above-mentioned bug.
@@||jpg.church^
I haven't made any change to my allowlist for about half year.
I'm not sure when this line was added to the allowlist
But Adguard was working fine until it updated itself yesterday.
