### ISSUE TITLE
AdGuard leaks adboxes on wykop.pl randomly

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardBrowserExtension#2463]
### AdGuard Extension version

4.2.162

### Browser version

Chrome 116.0.5845.141

### OS version

Windows 11 22H2 22621.2215

### What filters do you have enabled?

AdGuard Base filter, AdGuard Russian filter, AdGuard Tracking Protection filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, Online Malicious URL Blocklist, Official Polish filters for AdBlock, uBlock Origin & AdGuard, Polish GDPR-Cookies Filters, KAD - Anti-Scam, Polish Anti Adblock Filters, NoCoin Filter List

### Issue Details

Website: https://wykop.pl randomly leaks adboxes after open site in new tab.
Clear site session cookies OR close and open new tab and open site "fix" the issue. 

### Expected Behavior

No adboxes

### Screenshots

<details><summary>Screenshot 1:</summary>

![20230831-1693505688](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/9846948/930ef06f-a44e-48df-a980-1e1e8dd2c402)

</details>

<details><summary>Screenshot 2:</summary>

![20230831-1693505679](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/9846948/127c8ab8-63b5-4be0-b52f-7616c5019457)

</details>

### Additional Information

Reported in the past here https://github.com/AdguardTeam/AdguardFilters/issues/160000 but "no reproduce" by @AdamWr

**Comment by AdamWr** [comment]
Maybe related to - https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2459

**Comment by maximtop** [comment]
@FadeMind #2433 this one was fixed in your version

**Comment by stanislav-atr** [comment]
This is not reproduced on the latest AG version.
