### ISSUE TITLE
Auto include AdGuard Extra in names of other extensions used

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardBrowserExtension#2467]
### Proposed solution

![reports adguard com_en_new_issue html_browser=Chrome browsing_security enabled=false filters=1 2 4 14 17 product_type=Ext product_version=4 2 162 stealth enabled=false url=https%3A%2F%2Fgithub com%2FAdguardTeam%2FAdguar](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/143959878/2c7f4bac-9557-46cf-a32d-9336688c0e04)

**Comment by Birbber** [comment]
Hi, we already have an open [feature request](https://github.com/AdguardTeam/ReportsWebApp/issues/280) on this matter. I'm closing this as a duplicate.
