### ISSUE TITLE
Youtube ads appeard after latest update

### ISSUE THREAD

**Issue by abdallah-mo7sin** [AdguardTeam/AdguardBrowserExtension#2470]
### AdGuard Extension version

 4.2.162

### Browser version

 116.0.5845.141

### OS version

win 11

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Chinese filter, AdGuard Dutch filter, AdGuard French filter, AdGuard German filter, AdGuard Japanese filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Annoyances filter, AdGuard Other Annoyances filter, EasyList, ABPindo, Bulgarian list, EasyList China, EasyList Czech and Slovak, EasyList Dutch, EasyList Germany, EasyList Hebrew, EasyList Italy, EasyList Lithuania, Latvian List

### Issue Details

After latest update youtube ads appeared again at the start of the videos but with black screen 

### Screenshots

<details><summary>Screenshot 1:</summary>

![Screenshot 2023-09-04 140051](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/141024975/5506b141-0e4c-458c-8254-00500bbbc5e9)

</details>

**Comment by alexx7311** [comment]
Dup. of #2480
