### ISSUE TITLE
Webpage does not reload when changing AG state

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardBrowserExtension#2471]
### AdGuard Extension version

4.2.162

### Browser version

Chrome 116.0.5845.141 (Official Build) (64-bit)

### OS version

Windows 11 (64-Bit)

### Issue Details

Until the last update, webpages used to reload when we changed the state of AG.

For example, if the current state of AG is enabled for a particular webpage, when we disabled AG for that webpage, the page used to reload. Now, after the new update, we no longer see that.

### Expected Behavior

The Webpage is supposed to reload when the state of AG is changed. That is,

AG on to AG off
or
AG off to AG on

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/6959116/e1b13072-7917-4dc9-8d9a-d3467fc5c62c)

</details>

### Additional Information

I didn't include the filter list and Stealth mode settings as I don't think it is related to those.

**Comment by Birbber** [comment]
@Nzzyme Hello and thank you for the report! I've managed to reproduce the issue, although it disappeared once I've restarted the browser. We'll look into this.

**Comment by Nzzyme** [comment]
Is there any fix for this yet? I am still observing this issue.

**Comment by Birbber** [comment]
The issue is not reproducible on the latest version, try updating the extension. If the issue still persists please re-open this issue.
