### ISSUE TITLE
[Chrome] Gmail.com tabs become irresponsive after cancelling selector menu

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardBrowserExtension#248]
Steps to reproduce:

- Run Adguard extension in Integration mode (reproduceable both on Mac and Windows);
- Go to gmail.com, log in;
- Use extension menu to choose element blocker;
- Without selecting any element, close the element blocker.

Result: gmail tabs (inbox, spam etc.) are unclickable until page refresh. Was tested in Chrome.

**Comment by Mizzick** [comment]
Fixed
