### ISSUE TITLE
YouTube ads at the beginning of a video

### ISSUE THREAD

**Issue by Nevidebla** [AdguardTeam/AdguardBrowserExtension#2480]
Can't block the ad at the begin of video.
![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/54260027/ab2851d7-9713-454c-9516-57b437ebe3e1)

### AdGuard Extension version

4.1.57

### Browser version

116.0.5845.180 (Official Build) (64-bit)

### OS version

Windows 10 Enterprise 22H2 19045.3324

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by FadeMind** [comment]
Embedded youtube player does not work. 
![20230906-1693981890](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/9846948/c57b551a-cad3-4523-8061-731f7a3514af)

![20230906-1693982069](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/9846948/7d3ab043-b8fc-4bb5-9056-2de0d515f9e1)

youtube.com site works.

![20230906-1693982111](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/9846948/c05ab373-a0ce-4b5b-a627-3c96ef32b2c3)

**Comment by alexx7311** [comment]
@Nevidebla @abdallah-mo7sin Please check if the problem reproduces on the latest beta https://agrd.io/extension_chrome_beta

**Comment by FadeMind** [comment]
@alexx7311 beta works well. No issue.

**Comment by alexx7311** [comment]
@Nevidebla @abdallah-mo7sin We'll close the issue for now. You can reopen it any time.
