### ISSUE TITLE
unblock a secure site on a new domain

### ISSUE THREAD

**Issue by Miklesp** [AdguardTeam/AdguardBrowserExtension#2483]
### AdGuard Extension version

AdGuard 4.2.162

### Browser version

yandex browser

### OS version

Windows 10

### What filters do you have enabled?

AdGuard Base filter

### Issue Details

I have launched a new website on the domain rostov-reklama.ru . The adguard blocks all styles, scripts and images on this site. This is the website of an outdoor advertising agency. Please add the domain rostov-reklama.ru to the whitelist

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/113426262/38a2917a-6e36-4bba-8475-825efcdb7789)

</details>

**Comment by alexx7311** [comment]
@Miklesp Hello! Please report this website via the extension popup. Most of the fields will be filled in automatically, and you can find step-by-step instructions at https://adguard.app/kb/ru/guides/report-website/#extension

**Comment by Miklesp** [comment]
@alexx7311  Hello! It's impossible. At the third step, the adguard does not recognize the site and redirects to Github

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/113426262/82a66f68-c174-4555-9eb4-812dba2c8469)

**Comment by Miklesp** [comment]
@adguard-bot #status #not complited
