### ISSUE TITLE
Stop Duplicate Scriplet In Filtering Log

### ISSUE THREAD

**Issue by BlazeFTL** [AdguardTeam/AdguardBrowserExtension#2490]
### AdGuard Extension version

*

### Browser version

*

### OS version

*

### What filters do you have enabled?

AdGuard Base filter, AdGuard Chinese filter

### Issue Details

Same Scriptlet Is Repeated More Than Once

### Expected Behavior

Same Scriptlet Shouldnt Be Repeated More Than Once

### Screenshots

<details><summary>Screenshot 1:</summary>

![Screenshot_20230917-185612_Firefox Nightly](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/139938337/f383569b-f266-46f9-9f7b-084eae54407f)

</details>

**Comment by maximtop** [comment]
Events about scriptlets injection fire for every iframe.
