### ISSUE TITLE
Result is not shown when Adguard extension is on.

### ISSUE THREAD

**Issue by jawad53** [AdguardTeam/AdguardBrowserExtension#2493]
### AdGuard Extension version

Version 4.2.168

### Browser version

Version 117.0.5938.89 (Official Build) (64-bit)

### OS version

windows

### What filters do you have enabled?

AdGuard Base filter

### Issue Details

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/49428387/0907cd23-0699-41a6-8a4b-ba8fcbd3902d)

https://www.duplichecker.com/backlink-checker.php

Result is not generated when Adguard Extension is on.

### Expected Behavior

Result should be generated 
https://www.duplichecker.com/backlink-checker.php

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/49428387/01d928c6-2455-4f1f-b463-ed3305fdfd2b)

</details>

### Additional Information

It should not block results section

**Comment by Alex-302** [comment]
@jawad53 Please send report from AdGuard menu
![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/8361299/4296a006-1b04-412f-a522-d2fc3e2c13e5)

**Comment by jawad53** [comment]
okay. Thanks
