### ISSUE TITLE
Some websites do not work with the AdGuard extension enabled

### ISSUE THREAD

**Issue by YongChingShieh** [AdguardTeam/AdguardBrowserExtension#2495]
### AdGuard Extension version

4.1.57

### Browser version

Google Chrome 116.0.5845.188 (Official Build) (64-bit)

### OS version

	Microsoft Windows 10 Enterprise	10.0.19045 Build 19045

### What filters do you have enabled?

AdGuard Base filter, AdGuard Chinese filter, AdGuard French filter, AdGuard German filter, AdGuard Japanese filter, AdGuard Russian filter, EasyList China

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters, Disable WebRTC

### Issue Details

enable adguard chinese filter ,some website not work

### Expected Behavior

some content not display
去广告插件屏蔽, 请等待10秒, 或将其关闭即刻恢复浏览   translate : Ad-blocking plugin activated. Please wait for 10 seconds or disable it to resume browsing.

This means that to view the content, you must turn off ad filtering or wait 10 seconds

### Screenshots

<details><summary>Screenshot 1:</summary>

 
![01](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/24885976/592620fe-bd66-46c8-9ba0-73e8c70b1bec)

![02](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/24885976/7051a339-d38c-48d8-a884-c523c6373b56)

</details>

**Comment by alexx7311** [comment]
@YongChingShieh If you disable all filters in the extension, including the Chinese filter, will the sites you mentioned start working?

**Comment by YongChingShieh** [comment]
> @YongChingShieh If you disable all filters in the extension, including the Chinese filter, will the sites you mentioned start working?

thanks , i will be  try

**Comment by alexx7311** [comment]
@YongChingShieh Were you able to reproduce the problem with the filters disabled?

**Comment by YongChingShieh** [comment]
> @YongChingShieh Were you able to reproduce the problem with the filters disabled?

update filter after, the website work 
https://github.com/AdguardTeam/AdguardFilters/issues/162347#event-10476929321

**Comment by alexx7311** [comment]
We're glad the problem has been resolved!
