### ISSUE TITLE
In `README`, logo is hard to see when using dark theme in GitHub

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdguardBrowserExtension#2496]
### Issue Details

In the [README](https://github.com/AdguardTeam/AdguardBrowserExtension#readme), the logo is hard to see when using the dark theme on GitHub. Also, the app's screenshots look too bright with a light background.

<details><summary>Screenshot:</summary>

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/19418601/dde37529-163f-4085-bb78-950c45d86fb3)

</details>

### Proposed solution

You need to add logo and screenshot options for the dark theme.

Useful link: https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/

**Comment by Birbber** [comment]
@rakleed Hi. Thanks for the request. The logo for dark theme has been fixed, closing this issue.

**Comment by rakleed** [comment]
@Birbber can you also take a dark screenshot for the dark theme on GitHub?

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/19418601/5523fe03-8a59-4df4-bcff-1d3ebadd504d)
