### ISSUE TITLE
Proceed anyway is not working for more than two level domains

### ISSUE THREAD

**Issue by Fyphen1223** [AdguardTeam/AdguardBrowserExtension#2497]
### AdGuard Extension version

Latest version

### Browser version

Chrome Latest

### OS version

Chromebook Latest

### What filters do you have enabled?

AdGuard Base filter

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters, Hide your search queries, Send websites signals not to track you, Hide Referrer from third parties, Remove X-Client-Data header

### Issue Details

When I access some sites, such as GitHub codespaces, it says that AdGuard has blocked because it's on the filtering list.
And I cannot access the site because the button to access is disabled (no action occurred after I clicked the button).
IN ADDITION TO THIS, when the block screen is shown in some site (github code spaces), even other tabs' sites have started to be blocked. URL is the blocked site (which in my case is codespaces). For example, Discord has been blocked by AdGuard with other site's URL.

### Expected Behavior

When I click the button, I should be redirected to the original site. But NO ACTIONS HAD TAKEN!!!
Also other sites should not be blocked with other sites' URLs.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by maximtop** [comment]
Do you have any custom rules, or anything in allowlist?

**Comment by Fyphen1223** [comment]
OF COURSE NOT!

**Comment by alexx7311** [comment]
@Fyphen1223 We'll need to look at your settings.

Please go to your AdGuard extension settings > General and click 'Export settings'.

Send this file to [devteam@adguard.com](mailto:devteam@adguard.com) and mention the `2497` number in the subject.

**Comment by Fyphen1223** [comment]
@alexx7311 
Thanks for reply, and I send an e-mail.

**Comment by maximtop** [comment]
I was able to reproduce an issue with the github codespace. Here are the steps to reproduce (STR):

1. Create an empty codespace at [GitHub Codespaces](https://github.com/codespaces).
2. Notice that the page is blocked by the rule `/(//|\.|^)github\.[a-z]{2,20}(/|$)/$document,match-case,domain=~com|~org|~net|~co|~blog|~community|~host|~io|~microsoft|~office|~uk|~us|~xn--fiqs8s` (this rule might be replaced, so you may need to add it to your user rules).
3. Click "Proceed Anyway."

Expected outcome: The codespace page should open.
Actual outcome: The ad-blocking page appears again.

**Comment by Fyphen1223** [comment]
In my case, the rule is truly same with @maximtop 's rule.
```
/(//|\.|^)github\.[a-z]{2,20}(/|$)/$document,match-case,domain=~com|~org|~net|~co|~blog|~community|~host|~io|~microsoft|~office|~uk|~us|~xn--fiqs8s
```

And if you want to try to reproduce other bugs (which involve other tabs), please reload other tab. 
Then you will see the notification that the page was blocked with the rule.
And note, I did not set any such rules on my User Rules.

**Comment by DandelionSprout** [comment]
Okay, I **think** I found the fault, and will adjust that entry accordingly. Give me 15min.

**Comment by Fyphen1223** [comment]
15mins had already passed, and that's it.

**Comment by Fyphen1223** [comment]
Should I close this issue or not?

**Comment by maximtop** [comment]
@Fyphen1223, we will close this issue ourselves once we release a version in which the 'Proceed Anyway' button is fixed.

**Comment by Fyphen1223** [comment]
Ok, thanks.
