### ISSUE TITLE
Filter Download Page Opens at Browser Restart

### ISSUE THREAD

**Issue by Stijnvi** [AdguardTeam/AdguardBrowserExtension#2498]
### AdGuard Extension version

4.1.57

### Browser version

Firefox 117.0.1

### OS version

Windows 11

### Issue Details

Every time I start Firefox, the AdGuard 'filter download' page pops up, which then redirects to https://welcome.adguard.com/v4/firefox/thankyou.html
I also noticed my AdGuard settings are being reset every time I close the browser.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Birbber** [comment]
@Stijnvi Hi! We've recently released v4.2.168. Please check if the issue still reproducible after the update.

**Comment by Stijnvi** [comment]
Hi @Birbber 
Thank you for your fast response. 
The issue hasn't occurred on my laptop since the update, but I haven't had the chance to check on my PC yet. 
I will let you know as soon as I do, but I have good hopes that the new version has solved the issue.
Thank you again!

**Comment by Birbber** [comment]
I'm closing this issue now. Please re-open if it occurs again.
