### ISSUE TITLE
AdGuard v4.2.168 is not working in the Firefox for Android after update

### ISSUE THREAD

**Issue by Light-on** [AdguardTeam/AdguardBrowserExtension#2501]
### AdGuard Extension version

4.2.168

### Browser version

115.2.1esr (64-разрядный)

### OS version

Windows7

### Issue Details

Здравствуйте. Новейшее обновление браузера Firefox сломало работу расширения на всех сайтах. Что происходит? Я вызываю меню Adguard нажатием на значок на панели инструментов и вижу окно без символа Agduard, там пусто. Кроме того, значок расширения не показывает ни одной блокировки, нет цифр на чёрном, просто зелёный щит. Там, где расширение блокирует рекламу, теперь пустые места, которых раньше не было. Виноват, по-видимому, браузер, но обращаться к Adguard, кажется, реальнее.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Light-on** [comment]
![fixissues](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/35206151/a36ee085-4c96-49e9-a468-80818c56f41e)

**Comment by takemybabies** [comment]
Can confirm. This same thing has been happening to me as well for the past few days. Presumably, it is an issue with the recent Firefox extension update. Simply put, it no longer works or does what it is supposed to - it does not block ads.

**Comment by maximtop** [comment]
@Light-on
А не могли бы поделиться вашими настройками на devteam@adguard.com и может есть какие-то шаги для повторения, сходу меня не получилось повторить

@takemybabies could you please send your settings to devtean@adguard.com, and maybe there are some STR (steps to reproduce), it looks to be working on my machine as expected

**Comment by Alexandersuz** [comment]
Был такой глюк, переустановка не помогла. Сейчас заново установил расширение, вроде всё заработало нормально

**Comment by u07** [comment]
У меня сломалось в Яндекс браузере сегодня, после "крупного обновления расширения"

**Comment by u07** [comment]
[20230926_123735_adg_ext_settings_4.2.168.zip](https://github.com/AdguardTeam/AdguardBrowserExtension/files/12724519/20230926_123735_adg_ext_settings_4.2.168.zip)

Это вот настройки, просили выше. Симптомы такие же как и у ТС - окошко расширения без логотипа Adguard.

**Comment by maximtop** [comment]
> Это вот настройки, просили выше. Симптомы такие же как и у ТС - окошко расширения без кнопки вкл-выкл и счётчика.

это настройки до или после переустановки?
я попробовал их экспортировать, зашел на пару сайтов, но ошибка не повторилась
еще в момент, когда сайт не работает, было бы удобно иметь возможность получить логи с background page
как тут написано https://maximtop.notion.site/How-to-find-an-extension-logs-in-the-Firefox-682216c6dea54b6a9832edf924b07d3b?pvs=4

**Comment by u07** [comment]
До переустановки. Ну, сейчас логи снимать уже поздно...

**Comment by maximtop** [comment]
> До переустановки. Ну, сейчас логи снимать уже поздно...

а на каком-то определенном сайте или на многих?

**Comment by u07** [comment]
На всех.

**Comment by takemybabies** [comment]
I managed to fix this on my end by reinstalling the add-on. (Had to close Firefox in between) Thanks for the help.

**Comment by Light-on** [comment]
Помогла переустановка расширения! Всем большое спасибо за комментарии.

**Comment by c8c8** [comment]
I confirm that 4.2.168 is not working on Firefox Mobile.  It does work on Firefox for Windows.  Uninstalling and reinstalling (multiple times) did not help.  I have an Android tablet that is still running the last 4.1 release which is working fine.  I cannot await a fix where adblocking is concerned, so switched to ublock.  I expect this kind of problem will result in significant loss of market share which is a pity, Adguard's interface is much nicer.

**Comment by u07** [comment]
Someone just have to debug this instead of reinstalling. Please, if you read this and still have the issue, get the logs as maximtop instructed.

What may be helpful also is packing the whole extension directory into a zip for the developers, so they can reproduce the issue... Although I'm not a dev and not sure if it works that way

**Comment by valerafcc** [comment]
I tried reinstalling the extension, but it doesn't fix the problem in the Firefox mobile browser.
![Screenshot_20231002_170526_io github forkmaintainers iceraven](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/47479172/2ed0a972-fd2c-44e7-aa5d-fd40e48f2944)

**Comment by maximtop** [comment]
Yes, indeed, the AdGuard AdBlocker is not working on Firefox for Android. We will address this issue in the next patch release.

**Comment by u07** [comment]
Hey, why android? The topic starter uses Windows 7. And as for me, it's not even Firefox :)) but same symptoms

**Comment by maximtop** [comment]
> Hey, why android? The topic starter uses Windows 7. And as for me, it's not even Firefox :)) but same symptoms

We were definitely able to reproduce the bug on Android.

**Comment by neon71** [comment]
The problem still exists, and as I can see it have tag Resolved... it is not resolved!

**Comment by valerafcc** [comment]
> The problem still exists, and as I can see it have tag Resolved... it is not resolved!

the problem has been solved, but the extension has not been released yet
https://github.com/AdguardTeam/AdguardBrowserExtension/releases/tag/v4.2.189-beta
