### ISSUE TITLE
Filtering does not work in the Firefox/Iceraven mobile browser

### ISSUE THREAD

**Issue by valerafcc** [AdguardTeam/AdguardBrowserExtension#2513]
### AdGuard Extension version

4.2.168

### Browser version

Firefox 118, Iceraven 2.9.2

### OS version

Android 10, 13

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Russian filter

### Issue Details

В мобильном браузере Iceraven https://github.com/fork-maintainers/iceraven-browser/releases/tag/iceraven-2.9.2 и firefox 118 перестала работать фильтрация. 
Счетчик на разных сайтах всегда показывает 0 и реклама на страницах присутсвует.
Расширение и сами браузеры пробовал переустанавливать, проверил на двух телефонах.

### Screenshots

<details><summary>Screenshot 1:</summary>

![Screenshot_20230927_154409_io github forkmaintainers iceraven](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/47479172/428735b7-a1ca-46c2-9a83-a9009fbc44c7)
![Screenshot_20230927_154502_io github forkmaintainers iceraven](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/47479172/5a25f42c-131c-4708-b642-cac9e9aa78d8)

</details>

**Comment by alexx7311** [comment]
Dup. of https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2501
