### ISSUE TITLE
AdGuard extension for Firefox Mobile can't block ads 

### ISSUE THREAD

**Issue by ChowMein47** [AdguardTeam/AdguardBrowserExtension#2515]
### AdGuard Extension version

 4.2.168

### Browser version

Firefox Mobile 117

### OS version

Android 13 

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdBlockID, Peter Lowe's Blocklist

### Issue Details

A new AdGuard extension for Firefox Mobile can't blocking ads eventhough the filters already enabled & downloaded. To reproduce this issue you have to re-install Adguard extension on Firefox Mobile 

### Expected Behavior

Ads should be blocked after enable filters such as Adguard base, tracking protection,others

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by alexx7311** [comment]
Dup. of https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2501
