### ISSUE TITLE
Adguard setting not saving after browser is closed

### ISSUE THREAD

**Issue by Aslanex** [AdguardTeam/AdguardBrowserExtension#2517]
### AdGuard Extension version

4.2.168

### Browser version

Firefox 118

### OS version

Ubuntu 22.04.3

### Issue Details

Filter settings do not save when browser is closed. After opening the browser, all filters are set back to default, all whitelisted sites are removed etc.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by alexx7311** [comment]
@Aslanex Please update the extension to the latest version and check if the problem persists.

**Comment by alexx7311** [comment]
@Aslanex @TheCheddarCheese We have not been able to reproduce the problem. Does the problem reproduce in other browsers, such as Google Chrome? If you reset the browser settings, does the problem persist?

**Comment by Aslanex** [comment]
The problem seemed to stop occurring a few days after this report. Now I am on Firefox 119 and everything works fine.
