### ISSUE TITLE
Ads not blocked even the filter is in the list

### ISSUE THREAD

**Issue by bkrcrc** [AdguardTeam/AdguardBrowserExtension#252]
#1
Wesbite: http://www.oyunindir.club/drift-zone-2-apk-indir-para-hileli.html
Scrshot: https://s32.postimg.org/5f2xuzog5/screenshot.png

The ad shown in the screenshot is not blocked. But, @Alex-302 said the filter for this ads already in the Turkish list. Please see his comment: https://forum.adguard.com/index.php?threads/3-missed-ads.10590/#post-83716

I am using Chrome 50 stable latest and Adguard extension 2.3.4 with English + Turkish + Spyware + Social + Fanboy enhanced tracking filters.

Can you please check the problem?
Thanks

**Comment by Alex-302** [comment]
Yes, I could:)
As I wrote on the forum, it is a possible bug.
Added
oyunindir.club##a[href^="http://kurulum.xyz/"]

**Comment by bkrcrc** [comment]
If there is a possible bug, please do not close the topic.
Thanks

**Comment by ameshkov** [comment]
@Alex-302 if there's a bug you'd better file a bug report to extension repo

**Comment by Alex-302** [comment]
@ameshkov 
done
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/257
