### ISSUE TITLE
Rule options are not clickable in the filtering log

### ISSUE THREAD

**Issue by contribucious** [AdguardTeam/AdguardBrowserExtension#2521]
### AdGuard Extension version

4.2.186 beta / 4.2.189 beta

### Browser version

Firefox 118.0.1

### OS version

Windows 10 Pro 22H2 (OS Build 19045.3448)

### Issue Details

Hi. Currently, rule options are not clickable in the filtering log. IMHO, this should be the case.

### Expected Behavior

Rule options are clickable (to be consistent with other places, such as the "Trusted" checkbox present in the dialog for adding a custom filter — see animated GIF below).

### Screenshots

<details>
<summary>Reveal (animated GIF) …</summary>
&nbsp;

![AGBE_Zn88CIW08q](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/4764956/5e4e3f26-2296-4412-b275-edb44d878b9f)
</details>

### Additional Information

This is in a way an extension of this issue: https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2204

###### _Thanks! :v:_

**Comment by stanislav-atr** [comment]
@contribucious, hi! This issue will be resolved as a part of the earlier https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2204.
