### ISSUE TITLE
Adguard extension for Firefox is not blocking Ads

### ISSUE THREAD

**Issue by koopa990** [AdguardTeam/AdguardBrowserExtension#2526]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.2.168

### Environment

```markdown
- OS: Android 13
- Device: Oneplus 9
- Firmware: ???
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Popups filter

### Issue Details

Steps to reproduce:
1. Reinstall Firefox browser and Adguard exntension
2. Customize filters as per usual
3. Go onto a site with reasonable ads.

### Actual Behavior

Ads still appear on screen.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by maximtop** [comment]
@koopa990 Hi, we have fixed this issue in the beta, and release soon will be deployed as well.
Here is the issue https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2501

**Comment by koopa990** [comment]
> @koopa990 Hi, we have fixed this issue in the beta, and release soon will be deployed as well. Here is the issue #2501

How can I install 4.2.189 for Firefox android?

**Comment by maximtop** [comment]
Beta can be installed from this link https://agrd.io/extension_firefox_beta
Release will be deployed soon.

**Comment by koopa990** [comment]
> Beta can be installed from this link https://agrd.io/extension_firefox_beta Release will be deployed soon.

THis only downloads .xpi. Intallation?

**Comment by maximtop** [comment]
> > Beta can be installed from this link https://agrd.io/extension_firefox_beta Release will be deployed soon.
> 
> THis only downloads .xpi. Intallation?

yes, I think there is no easy way to install beta version on the firefox for android
