### ISSUE TITLE
Chrome doesn't show Google search results

### ISSUE THREAD

**Issue by HomerNau** [AdguardTeam/AdguardBrowserExtension#2528]
### AdGuard Extension version

4.2.189

### Browser version

Version 117.0.5938.150 (Official Build) (64-bit)

### OS version

Windows 11 Pro (22H2

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard Social Media filter

### Issue Details

After a few seconds Google chrome search results disappears (blank white backgrond). Refreching the page, results are shown again for a few seconds before it disappears (blank white background).
I trased it to my adblocker by switching off all extentions and then switching on. Then refrech page and see if the page go blank. As soon as I switch on my Adblocker, search results disappears after a few seconds.
![Chrome blank screen](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/147542664/ed262c8a-77c8-4d03-a1fc-b922287aac5c)

### Expected Behavior

That my search results will stay on the screen as previous (before adblocker update) and only ads are gone as per adblocker.

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/147542664/28c53f6f-1fd9-43b6-927f-861fb070b920)

</details>

### Additional Information

It only happens on my Desktop PC. My Chrome on my Dell notebook seems un affected.

**Comment by dftf-stu** [comment]
Hi @HomerNau

Two things you can try:

**Make sure the AdGuard filters are up-to-date**
- Click the AdGuard icon, in the top-right area of your browser (it might be hidden inside the jigsaw-icon 🧩)
- In the AdGuard pop-up, click the cog ⚙ icon
- In the tab which opens, click "Filters"
- Click the "Check for updates" button

**Remove any custom-rules you might have made**
- Click the AdGuard icon, in the top-right area of your browser (it might be hidden inside the jigsaw-icon 🧩)
- In the AdGuard pop-up, click the cog ⚙ icon
- In the tab which opens, click "User rules"
- Delete any line there which has "google" mentioned in it
- Then click the "Save" button

After following those steps, fully-close all tabs and windows you have open for your browser
Wait about 10-15 seconds
Then bring a new window for your browser back-up on screen, and try the Google site again

Is the issue still happening?

**Comment by HomerNau** [comment]
Hi,

 

It did not work. Chrome search results still disappears.

Chrome - Version 118.0.5993.71 (Official Build) (64-bit)

AdGaurd - Version 4.2.189

 

Kind Regards

**Comment by HomerNau** [comment]
When I turn this off, Chrome search result does not disapear.



 

Kind Regards

**Comment by alexx7311** [comment]
@HomerNau Please do the following:
1. Reinstall the AdGuard extension and enable the permission to use this extension in incognito mode.
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/114913601/f43be5ca-5a6f-40fa-8edd-4127e99b4513)

</details>

2. Disable all other extensions, open a new incognito window in Chrome and see if the problem persists.

**Comment by HomerNau** [comment]
Hi,

Still disappearing even with incognito enabled.

Going in to incognito, the search results still disappear.

 

Kind Regards

**Comment by HomerNau** [comment]
Yes, all extension disabled. It is only happening on my desktop.Same chrome account on my dell notebook works fine.On 12 Oct 2023 11:10, alexx7311 ***@***.***> wrote:
@HomerNau Have you disabled all other extensions in Chrome? Does the problem reproduce with only AdGuard extension enabled?

**Comment by HomerNau** [comment]
I tried using the app, that did not work.
I uninstalled it in disabled the extention and now Chrome search keeps on disappearing.

Previously, only disabling the base filters  solved the problem.

 

AdGuard broke my Chrome. Had to install Firefox

 

Kind Regards

**Comment by alexx7311** [comment]
@HomerNau Please go the Google search results > open AdGuard popup > Filtering log and look for **Modified** and **Blocked** requests. Take a screenshot of these requests.
Then go back to the search results and press F12 to open DevTools > Elements and click on the body and take a screenshot of the Styles tab.
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/114913601/4d16c785-d9f8-4383-b51b-3f5cb9f8b40e)

</details>

**Comment by HomerNau** [comment]
Hi,

Problem solved.
Ran Malwarebytes and found a few Registry Key that was suspect.

I have quarantine them and now everything is back to normal. Adguard extension set back to what is was.

 

Kind Regards
