### ISSUE TITLE
Youtube no ads allowed popup blocking issue

### ISSUE THREAD

**Issue by Mezo0099** [AdguardTeam/AdguardBrowserExtension#2529]
### AdGuard Extension version

Version 4.2.189

### Browser version

Chrome

### OS version

Windows 11

### What filters do you have enabled?

AdGuard Base filter

### Issue Details

Hi on youtube, When blocking the new no ads allowed popup as an extra ad, the videos continue to pause when the popup is supposed to show, and scrolling stays disabled till i refresh the page.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by alexx7311** [comment]
@Mezo0099 Please report this website via the extension popup. Most of the fields will be filled in automatically, and you can find step-by-step instructions at https://adguard.app/kb/guides/report-website/
