### ISSUE TITLE
Move Adguard filters from file system to storage

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#253]
1) We currently use a "FilterStorage" class to manage filters storage.

**2) Don't forget about handling it on extension update.**

**Comment by Mizzick** [comment]
Fixed

**Comment by ameshkov** [comment]
@Mizzick don't forget to add unlimited storage permission!

**Comment by ameshkov** [comment]
Actually we made it wrong now.

You are currently using localStorage which has size restriction (5MB).
Instead we should use "browser.storage":
https://developer.chrome.com/extensions/storage
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage

**Comment by ameshkov** [comment]
Done
