### ISSUE TITLE
Log in issues when AdGuard extension is enabled

### ISSUE THREAD

**Issue by KristofferD** [AdguardTeam/AdguardBrowserExtension#2537]
### AdGuard Extension version

4.2.189

### Browser version

118.0.2 (64-bit)

### OS version

Ubuntu 20.x

### What filters do you have enabled?

AdGuard Base filter

### What Stealth Mode options do you have enabled?

Block trackers

### Issue Details

I've recently encountered a problem with the AdGuard Firefox Extension that has affected my ability to log into various educational institutions' Canvas websites.

Instead of being redirected to the Canvas dashboard or intranet, I am sent back to the school's Canvas homepage.

### Expected Behavior

After entering my login credentials, I should be redirected to the Canvas dashboard or intranet of the educational institution.

### Additional Information

    This issue started approximately a week ago.
    It's not limited to a single institution's Canvas website. I've tried logging into multiple institutions' Canvas websites and the issue persists on all of them.
    When I disable the AdGuard Firefox Extension, I am able to log in normally.

It's unclear if this issue is caused by a change in the Canvas platform, something on the school's end, or an update to the AdGuard Firefox Extension. I wanted to bring it to your attention in case others are experiencing similar issues. I hope a solution can be found soon as the extension has otherwise been very helpful.

**Comment by alexx7311** [comment]
@KristofferD Hello! It looks very much like a problem with the filters, not the extension. If you add the website to Allowlist, does the problem persist?

**Comment by alexx7311** [comment]
@KristofferD If we don't get a response in a few days, this issue will be closed.
