### ISSUE TITLE
AdGuard extention does not work on Firefox beta, nightly

### ISSUE THREAD

**Issue by ja1hss** [AdguardTeam/AdguardBrowserExtension#2538]
### AdGuard Extension version

4.2.168

### Browser version

firefox nightly 120.0a1

### OS version

Android 11

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Japanese filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, AdGuard DNS filter, AdGuard Experimental filter, Filter unblocking search ads and self-promotion

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters, Hide your search queries, Send websites signals not to track you, Self-destruction of third-party cookies, Hide Referrer from third parties, Disable WebRTC

### Issue Details

 all web pages are treatedas a "secured page", so Adblocking does not work at all.
It occuts beta, nightly version only.
original Firefox and  iceraven works fine.

### Expected Behavior

Does not treal all web page as "secured page".

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by alexx7311** [comment]
@ja1hss Please update the extension to the latest version and check if the problem persists.

**Comment by ja1hss** [comment]
I tried to update and checked. It works well and problem was fixed. Thanks, Alexx7311.
