### ISSUE TITLE
Every time youtube opens a video there is a popup about "disable adblocking".

### ISSUE THREAD

**Issue by LaoJiuYes** [AdguardTeam/AdguardBrowserExtension#2540]
### AdGuard Extension version

4.2.189

### Browser version

Edge 118

### OS version

Windows11 22H2

### What filters do you have enabled?

AdGuard Base filter

### What Stealth Mode options do you have enabled?

Block trackers

### Issue Details

Every time youtube opens a video there is a popup about "disable adblocking".

### Expected Behavior

Wish there was a way to remove the above

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Rairof** [comment]
![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/107706560/d72aef80-be9d-42eb-91b2-b5577a78b006)
Same issue here, tried updating filter, clearking site cashe and cookies, resetted broweer and restarting it. Nothing worked.

**Comment by amaanalihaider** [comment]
same issue

**Comment by Kugankr** [comment]
<img width="784" alt="Screenshot 2023-10-15 at 4 19 45 PM" src="https://github.com/AdguardTeam/AdguardBrowserExtension/assets/122229279/59babeb9-b321-4794-8d0c-cc266ce328a8">
same issue for me too

**Comment by WangMinan** [comment]
same issue

**Comment by Birbber** [comment]
Hello! We already have [a similar issue](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2532) on this problem, so I'll close this one as a duplicate. Stay tuned for updates there. 

We'd like to know which countries have been affected and would appreciate if you share the location chosen in your google account. You can share it by sending us an email at `devteam@adguard.com`, mentioning the issue. Thank you in advance!
> It's not mandatory and won't be used for anything other than investigating the issue
