### ISSUE TITLE
AdGuard extension interferes with video playback

### ISSUE THREAD

**Issue by marian353** [AdguardTeam/AdguardBrowserExtension#2546]
### AdGuard Extension version

 4.2.189

### Browser version

google chrome

### OS version

windows 11 

### What filters do you have enabled?

No filters, AdGuard Base filter

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters, Hide your search queries, Send websites signals not to track you, Self-destruction of third-party cookies, Self-destruction of first-party cookies, Hide Referrer from third parties, Remove X-Client-Data header

### Issue Details

some videos no longer work because of the active adguard application

### Expected Behavior

some videos no longer work because of the active adguard application

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

some videos no longer work because of the active adguard application

**Comment by zzebrum** [comment]
@marian353 yeah, that is probably a filtering problem. What website are we talking about, and what filters you have enabled?

**Comment by marian353** [comment]
I have the filters that come once you install the add-on
https://sitefilme.com/filme-online-hd/ online movie sites
https://www.google.ro/search?q=filme+online&rlz=1C2YTUH_enRO1059RO1059&iflsig
=AO6bgOgAAAAAZS6z74bQEmoLYiV30ODzKTLk_146x0Ex&uact=5

În mar., 17 oct. 2023 la 17:37, zzebrum ***@***.***> a scris:

**Comment by marian353** [comment]
there are several movie sites where the movies don't work because of the ad
guard extension[image: image.png]

În mar., 17 oct. 2023 la 18:20, marius mihai ***@***.***> a
scris:

**Comment by alexx7311** [comment]
@marian353 Hello! Please report these websites via the extension popup. Most of the fields will be filled in automatically, and you can find step-by-step instructions at https://adguard.app/kb/guides/report-website/#form
