### ISSUE TITLE
Recently Youtube started blocking the extension

### ISSUE THREAD

**Issue by erokichi101** [AdguardTeam/AdguardBrowserExtension#2548]
### AdGuard Extension version

4.2.189

### Browser version

Chrome  118.0.5993.71 

### OS version

windows 10

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, AdGuard DNS filter, EasyList, Fanboy's Annoyances, Fanboy's Social Blocking List, Web Annoyances Ultralist, Adblock Warning Removal List, Online Malicious URL Blocklist, I don't care about cookies, NoCoin Filter List, Dandelion Sprout's Nordic Filters, Dandelion Sprout's Annoyances List

### Issue Details

Recently YouTube started blocking the extension. It started from yesterday, October 17, 2023.  After watching 3 adless videos it blocked the adblocker completely.

![youtub](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/148357295/60e1a82f-da8a-42a6-8cca-e0db632a0f81)

### Expected Behavior

It usually loads YouTube videos without showing any ads. But from yesterday Youtube started blocking the extension. Videos won't load while adguard is on.

### Screenshots

![youtub](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/148357295/5cf6da78-22fd-4fbd-bf46-5840fb154f12)

### Additional Information

I think YouTube security measures have increased and adguard needs to be upgraded with an advanced bypass option.
![youtub](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/148357295/34e64c21-1fb3-4e55-b093-1f858d9ab43a)

**Comment by Birbber** [comment]
Hello! We already have [an issue on this problem](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2532) and are working on it. Please stay tuned for updates.
