### ISSUE TITLE
Youtube AdBlocker Detector

### ISSUE THREAD

**Issue by FronTiny** [AdguardTeam/AdguardBrowserExtension#2550]
### AdGuard Extension version

4.2.189

### Browser version

118.0.2088.46

### OS version

19045.3570

### What filters do you have enabled?

No filters, AdGuard Base filter

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters, Hide your search queries, Send websites signals not to track you, Self-destruction of third-party cookies, Hide Referrer from third parties

### Issue Details

Youtube have now a Adblocker detector which is now detects your extension every opening the video it appears on what in the image, before the message only warning then later on the Close button of the message have a cooldown and now have a cooldown with warning that after 4 more videos the later videos will not be played. I hope you'll upgrade your extension thank you for your services

### Expected Behavior

No message and warning should appear

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/129482032/9531ff2c-2ef7-4412-9f28-dd860599287e)

</details>

**Comment by XHesaX** [comment]
same problem here

**Comment by Birbber** [comment]
Hello! We already have [an open issue on this problem](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2532). Please check updates there.
I'm closing this one as a duplicate.
