### ISSUE TITLE
'$cookie' exclusion breaks sites in Firefox

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#2552]
### AdGuard Extension version

4.2.189

### Browser version

Firefox

### OS version

unknown

### What filters do you have enabled?

AdGuard Base filter, AdGuard Japanese filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Issue Details

Original issue: https://github.com/AdguardTeam/AdguardFilters/issues/164150

With enabled Tracking Protection filter https://store-jp.nintendo.com/ after login redirects to https://store-jp.nintendo.com/on/demandware.store/Sites-MNS-Site/ja_JP/CSRF-Fail because of the cookie rules exclusion
`@@||store-jp.nintendo.com^$cookie`

Once you fixed and refreshed (e.g. by removing the rule), it will no more happen until you clear everything and sing in again.

<details>
<summary>Screenshot</summary>

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/8361299/9ea0b1c1-18ad-48dd-b2f5-d929b2f71af6)

</details>

It happens only in Firefox with the browser extension.

To reproduce this problem you need an account, Japanese VPN and the rules in user filter:
```
@@||store-jp.nintendo.com^$cookie
$cookie=/dwac_/
$cookie=/^_ga_/
```

### Expected Behavior

Exclusion `@@||store-jp.nintendo.com^$cookie` should not break sites.

### Additional Information

Please mention `@AdguardTeam/filters-maintainers` when it will be fixed.

**Comment by zloyden** [comment]
Another issue https://github.com/AdguardTeam/AdguardFilters/issues/171997#issuecomment-1925455675.

**Comment by zloyden** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/172656.
