### ISSUE TITLE
The ads have stopped blocking on spotify

### ISSUE THREAD

**Issue by Pinkchicken888** [AdguardTeam/AdguardBrowserExtension#2554]
### AdGuard Extension version

4.2.189

### Browser version

Chrome

### OS version

Windows 10

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard Other Annoyances filter

### What Stealth Mode options do you have enabled?

Block trackers, Send websites signals not to track you

### Issue Details

When I listen to spotify on the web it has stopped blocking ads. The ads cover art disappears but the ad audio stays.

### Expected Behavior

Normal there is a brief few seconds of no audio then the music starts again.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by alexx7311** [comment]
@Pinkchicken888 Hello! Please report this website via the extension popup. Most of the fields will be filled in automatically, and you can find step-by-step instructions at https://adguard.app/kb/guides/report-website/#form
