### ISSUE TITLE
Youtube doesn't work

### ISSUE THREAD

**Issue by vadimbk** [AdguardTeam/AdguardBrowserExtension#2556]
### AdGuard Extension version

4.2.189

### Browser version

118.0.5993.88

### OS version

macOS 14.0

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Russian filter, AdGuard Turkish filter

### Issue Details

Youtube with ads stops its work 

### Expected Behavior

Youtube video must play

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Birbber** [comment]
Hello! Indeed a duplicate of #2532. Please check issue updates there. 
Closing this one.
