### ISSUE TITLE
Add hint while using YouTube

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdguardBrowserExtension#2557]
### Issue Details

YouTube updates its ad blocking detection codes daily and users are not aware of it. So they will rate your products poorly.

### Proposed solution

To solve this, add small hint popup for YouTube domain and notify users in that hint. Ex: "`YouTube's adblock detection system is updated daily. Update filters regularly or daily for better ad blocking`" hint popup can be added.

**Comment by alexx7311** [comment]
@gork7777 Hello! Answered in https://github.com/AdguardTeam/AdguardForWindows/issues/4873
