### ISSUE TITLE
Youtube not recommended adblock message window

### ISSUE THREAD

**Issue by prepmarcell** [AdguardTeam/AdguardBrowserExtension#2562]
### AdGuard Extension version

4.2.189

### Browser version

Firefox 119.0 (64 bites)

### OS version

Windows 11 22H2 22621.2428 (2022. ‎09. ‎28.)

### What filters do you have enabled?

AdGuard Base filter, Hungarian filter

### Issue Details

I wanted to start a youtube video and now for the first time I got a new message that did not recommend adblock from YouTube. And to turn it off adblock and it kept displaying the message.

### Expected Behavior

It's disturbing.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by prepmarcell** [comment]
I will send you the picture as soon as I get the warning message.

**Comment by Birbber** [comment]
We already have [an open issue on this problem](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2532). Please check updates there.
Closing this one as a duplicate.
