### ISSUE TITLE
The search bar overlaps search tabs on Google Chrome search results page

### ISSUE THREAD

**Issue by oridwanbello** [AdguardTeam/AdguardBrowserExtension#2565]
### AdGuard Extension version

Version 4.2.189

### Browser version

Chrome 118.0.5993.117 (Official Build) (arm64)

### OS version

Sonoma 14.1

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Chinese filter, AdGuard Dutch filter, AdGuard French filter, AdGuard German filter, AdGuard Japanese filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, AdGuard DNS filter, AdGuard Experimental filter, Filter unblocking search ads and self-promotion, ---Third-party filters---, EasyList, ABPindo, Bulgarian list, EasyList China, EasyList Czech and Slovak

### Issue Details

The search bar overlaps search tabs on Google Chrome search results page. Thereby, making it difficult to navigate between search tabs. When the extension is switched off, the problem is solved. So, this appears to be an Adguard issue. Thanks

### Expected Behavior

The Search bar should be above the search tabs

### Screenshots

<details><summary>Screenshot 1:</summary>

</details><img width="1953" alt="Screenshot 2023-10-29 at 12 46 07 PM" src="https://github.com/AdguardTeam/AdguardBrowserExtension/assets/98242888/6bd2c3b6-33d7-40d4-8ab9-f0ccfb11c6c3">

**Comment by degarni** [comment]
![chro](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/121092285/64828695-106c-4830-a041-86fa71fb9282)

Je confirme, même soucis chez moi depuis plusieurs jours. 
Si je désactive l'extension, tout fonctionne normalement.

**Comment by maximtop** [comment]
Hi @oridwanbello and @degarni,

Thank you for bringing this issue to our attention. Based on the symptoms you've described, this problem appears to be related to the filters you have enabled.

To help us resolve this issue more effectively, could you please submit a detailed report via https://reports.adguard.com? You can also access this reporting tool directly from the AdGuard extension by clicking on the Popup -> "Report an issue" button.
