### ISSUE TITLE
Blocking of stylesheets

### ISSUE THREAD

**Issue by mdziczkowski** [AdguardTeam/AdguardBrowserExtension#2566]
### AdGuard Extension version

4.1.57

### Browser version

Firefox for Android

### OS version

Android 13

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Chinese filter, AdGuard Dutch filter, AdGuard French filter, AdGuard German filter, AdGuard Japanese filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, AdGuard DNS filter, AdGuard Experimental filter, Filter unblocking search ads and self-promotion, EasyList, ABPindo, Bulgarian list, EasyList China, EasyList Czech and Slovak, EasyList Dutch, EasyList Germany, EasyList Hebrew, EasyList Italy, EasyList Lithuania, Latvian List, Liste AR, Liste FR, ROList, EasyPrivacy, Icelandic ABP List, AdBlockID, Greek AdBlock Filter, Fanboy's Annoyances, Fanboy's Social Blocking List, Web Annoyances Ultralist, Thai Ads Filters, Hungarian filter, Peter Lowe's Blocklist, Xfiles, Adblock Warning Removal List, Online Malicious URL Blocklist, RU AdList - Counters, ABPVN List, Fanboy's Enhanced Tracking List, Official Polish filters for AdBlock, uBlock Origin & AdGuard, Polish GDPR-Cookies Filters, Estonian List, CJX's Annoyances List, Polish Social Filters, Fanboy's Anti-Facebook List, List-KR, xinggsf, I don't care about cookies, EasyList Spanish, KAD - Anti-Scam, Adblock List for Finland, ROLIST2, Iranian filter, road-block, Polish Annoyances Filters, Polish Anti Adblock Filters, Fanboy's Anti-thirdparty Fonts, EasyList Cookie List, NoCoin Filter List, Frellwit's Swedish Filter, YousList, AlleBlock, EasyList Polish, Polish Anti-Annoying Special Supplement, Dandelion Sprout's Nordic Filters, Dandelion Sprout's Annoyances List, Legitimate URL Shortener, Dandelion Sprout's Serbo-Croatian List, IndianList, Others

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters, Hide your search queries, Send websites signals not to track you, Self-destruction of third-party cookies, Hide Referrer from third parties, Remove X-Client-Data header, Disable WebRTC

### Issue Details

The extension blocks as default the stylesheet, etc. destroying every site's layout

### Expected Behavior

Normal display of the website

### Screenshots

<details>
Not Applicable
</details>

**Comment by alexx7311** [comment]
@mdziczkowski The list of filters that covers the main part of ads is following: Base filter, Tracking Protection filter, Mobile Ads filter, Social Media filter, Annoyances filter. Did the recommendations given above help you?

**Comment by alexx7311** [comment]
@mdziczkowski We'll close the issue for now. You can open it again if the problem recurs.

**Comment by krystian3w** [comment]
Maybe enough will by no longer enable:

> Fanboy's Anti-thirdparty Fonts
