### ISSUE TITLE
Adguard cannot block rocketscript

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#257]
http://www.oyunindir.club/drift-zone-2-apk-indir-para-hileli.html
Example script, which load ad:
http://kurulum.xyz/dosyaindir.js
<details> 
![1](http://imagizer.imageshack.com/img923/3518/6if29m.png)
</details>

**Comment by Mizzick** [comment]
It works as expected.
Tested with latest chrome and v2.3.4 extension.

**Comment by ameshkov** [comment]
That's a good question.

Rocketscript is a very simple technology used by Cloudflare to improve pages loading times.
So, what's going on:
1. Cloudflare removes all "src" attributes with a custom "data-rocketsrc" attribute.
2. After the DOMContentLoaded event fires, Cloudflare scans all "script[data-rocketsrc]" elements and creates a new **single** "script" tag that loads concatenated and minified scripts.

So, we should hook into this process and check "data-rocketsrc" values before cloudflare starts working.

**Comment by ameshkov** [comment]
Hm, I could be wrong, cloudflare script will process these scripts before we receive an url check response form the background page
