### ISSUE TITLE
Filtering log is not working on Firefox mobile

### ISSUE THREAD

**Issue by lemonNsoda** [AdguardTeam/AdguardBrowserExtension#2573]
### AdGuard Extension version

4.2.209 firefox extension

### Browser version

firefox 119

### OS version

android 13

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Annoyances filter, List-KR

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters, Hide your search queries, Send websites signals not to track you, Self-destruction of third-party cookies, Hide Referrer from third parties, Disable WebRTC

### Issue Details

 i touched open filtering log. But log tab not open. 
Both on setting and extension page.

### Expected Behavior

Open filtering log page on new tab

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by alexx7311** [comment]
Dup. of https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2536
