### ISSUE TITLE
Cant block the ad from the antiblock

### ISSUE THREAD

**Issue by gaoda1347** [AdguardTeam/AdguardBrowserExtension#2576]
### AdGuard Extension version

4.2.208

### Browser version

Opera GX (LVL5 (core: 102.0.4880.117))

### OS version

WIN11 X64 22H2

### Issue Details

https://toramemoblog.com/ffxiv-textools I Cant block AD in this site

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by alexx7311** [comment]
@gaoda1347 Hello! Please try to enable **Adblock Warning Removal List** and **AdGuard Annoyances filter**. If it didn't help please report this website via the extension popup. You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/
