### ISSUE TITLE
Suggestions For Future

### ISSUE THREAD

**Issue by BlazeFTL** [AdguardTeam/AdguardBrowserExtension#2577]
### Issue Details

AG Team Really Goes Through A Lot Of Wasted Time When Things Could Be Much More Simplified
Great Work By Them Ofc

### Proposed solution

Implement A Default List As Default Tab & Move Other Extra Filters Which Can Cause Breakage Or Anti Adb To Separate Tabs...This Would Reduce A Lot Of False Detection Or Breakage Due To Users Turning On Many Filters Without Understanding The Results...Ex - UBO Git Gets Hardly 2-5 Issues A Day Where Adguard Gets 100-200+ Issues In 1-2 Days

Currently Filter Maintainers Have To Commit On Multiple Places Or Files As Every Folder Have Files Based On Categories 
Ex - https://github.com/AdguardTeam/AdguardFilters/tree/master/BaseFilter/sections 
This Folder Has 10 Files But Could Be Just 1-2 Filters.txt (Something Ublock Origin Does) This Definitely Is Helpful For Filter Maintainers
Ubo Has Divided Those Filter Files Just By Years
Filters 2020.txt
Filters 2021.txt
Etc...

Simplifying #%#//scriptlet To Shorter Things Would Be Great Too...Ex - //+js()|##+js
Or Using Using Short Names For Scriplets Would Also Be Helpful & Time Saving For Filter Maintainers...
Ex: set-constant > set
window-open-defuser > wod/nwo = no window open

IDK About This But ID,Class Could Be Simplified To ###, ##. (Really Simple)

All Of This Because I Wanted To Create A PR & Felt Demotivated Seeing Those Many Files🤣🌚

**Comment by zzebrum** [comment]
@BlazeFTL thank you! In the future, we will take your suggestions into account.
