### ISSUE TITLE
beta 2.3.5 completely breaks Adguard on Safari

### ISSUE THREAD

**Issue by tiberian83** [AdguardTeam/AdguardBrowserExtension#258]
I just installed 2.3.5 beta on my system and now Adguard doesn't work at all. No blocked ads at all neither with the old or the new API.

**Comment by locusathome** [comment]
Yup, I can acknowledge that, nothing blocked, gives a Ad blocker Filter rules count: 1
Icon indicator of blocked ads completely silent.
Adguard browser's context menu not there.

**Comment by ameshkov** [comment]
Uh, I am sorry, we should have tested it.

I've updated the build in release notes and on our server (yet it has the same version so you need to reinstall extension).
