### ISSUE TITLE
Youtube is picking up adguard

### ISSUE THREAD

**Issue by Sheriffjake3439** [AdguardTeam/AdguardBrowserExtension#2581]
### AdGuard Extension version

latest

### Browser version

chrome

### OS version

Windows 11

### What filters do you have enabled?

AdGuard Base filter

### What Stealth Mode options do you have enabled?

Block trackers

### Issue Details

Youtube is picking up that there is an ad blocker when using adguard

### Expected Behavior

Youtube updated there stuff 

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by XHesaX** [comment]
same here 
![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/76571933/39a3f60d-11c7-4a32-a82b-135f6c088eb5)

**Comment by HuanDoan** [comment]
Well, "Holy war" has been started 

<img width="1185" alt="image" src="https://github.com/AdguardTeam/AdguardBrowserExtension/assets/20861694/7ef7e9fc-b26b-475b-801e-1cd998e40b1d">

**Comment by HuanDoan** [comment]
In incognito mode (of course, allowing the extensions), the problem seems resolved.

**Comment by krystian3w** [comment]
This is rule issue, should be reported first into:

https://github.com/AdguardTeam/AdguardFilters/issues/162262

And at mobile in: https://github.com/AdguardTeam/AdguardFilters/issues/164533

**Comment by Birbber** [comment]
Hi. We already have [an open issue on this problem](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2532). Please check the updates and leave your comments there. 
Closing this one as a duplicate.
