### ISSUE TITLE
youtube can detect ads blocker 

### ISSUE THREAD

**Issue by Pravin1109999** [AdguardTeam/AdguardBrowserExtension#2582]
### AdGuard Extension version

4.2.208

### Browser version

119

### OS version

13.2.1

### What filters do you have enabled?

AdGuard Mobile Ads filter

### What Stealth Mode options do you have enabled?

Block trackers

### Issue Details

when i try to play video youtube show that adgaurd is enabled.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Birbber** [comment]
Hi. We already have [an open issue on this problem](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2532). Please check the updates and leave your comments there. 
Closing this one as a duplicate.
