### ISSUE TITLE
Setting the filter interface language from Traditional Chinese will change the display to Simplified Chinese

### ISSUE THREAD

**Issue by PoYu-Liao** [AdguardTeam/AdguardBrowserExtension#2583]
### AdGuard Extension version

4.2.209

### Browser version

chrome 119.0.6045.105

### OS version

windows 10

### What filters do you have enabled?

AdGuard Base filter, AdGuard Chinese filter, AdGuard Japanese filter, NoCoin Filter List

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters, Send websites signals not to track you, Remove X-Client-Data header, Disable WebRTC

### Issue Details

Several versions of it can display all Traditional Chinese characters normally, but I don’t know which version started to have this problem.As for other areas, Traditional Chinese can be displayed normally, only the filters have been changed to Simplified Chinese.

### Expected Behavior

The filter settings display Traditional Chinese.

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/29099489/363c9d07-3def-4183-bdb9-ee59566b22f6)

</details>

**Comment by slavaleleka** [comment]
it shall be fixed in the next after 4.2.209 version

**Comment by PoYu-Liao** [comment]
This Chinese problem still exists.
It still hasn't been fixed in 4.2.226  version.
![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/29099489/da1886b4-06e2-4379-8dd7-d87f99c875ef)

**Comment by slavaleleka** [comment]
even after you update filters manually?
https://uploads.adguard.org/slbdzdrvia4gw.png

**Comment by PoYu-Liao** [comment]
It'll be back to normal.
Thank you.
