### ISSUE TITLE
Disable browser console scriptlet logging if Filtering log is closed

### ISSUE THREAD

**Issue by Steven-DD** [AdguardTeam/AdguardBrowserExtension#2584]
### AdGuard Extension version

4.2.209

### Browser version

Microsoft Edge  119.0.2151.44 

### OS version

Windows 11

### What filters do you have enabled?

AdGuard Base filter, AdGuard Chinese filter, AdGuard Japanese filter, AdGuard Russian filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, EasyList, EasyList China, EasyList Italy, Liste AR

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters, Hide your search queries, Send websites signals not to track you, Self-destruction of third-party cookies, Hide Referrer from third parties, Remove X-Client-Data header, Disable WebRTC

### Issue Details

3 errors in the console when loading any page while AdGuard is enabled.

### Expected Behavior

No error in the console.

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/47879312/e768bc13-4817-4fed-92b9-057c902ee359)

</details>

### Additional Information

#2105 

I noticed a related issue mentioned within this issue as well, and now it's come up again

**Comment by maximtop** [comment]
Hi, @Steven-DD 
Are these logs visible if you close the filtering log window?

**Comment by Steven-DD** [comment]
> Hi, @Steven-DD Are these logs visible if you close the filtering log window?

Yes, whenever I open the developer tools and refresh the page, it appears in my log no matter what

**Comment by maximtop** [comment]
It seems that there is a bug. 
Just wanted to clarify, is this option enabled at you?
<img width="720" alt="image" src="https://github.com/AdguardTeam/AdguardBrowserExtension/assets/17272769/d10e2e91-b217-4ea7-a12f-6f2a8827fa09">

If yes, then disable it, and reload extension (or browser), it should help.
This option shouldn't be responsible for making work of scriptlets more verbose. It should be verbose only if filtering log is open.

**Comment by Steven-DD** [comment]
> It seems that there is a bug. Just wanted to clarify, is this option enabled at you? <img alt="image" width="720" src="https://user-images.githubusercontent.com/17272769/281424357-d10e2e91-b217-4ea7-a12f-6f2a8827fa09.png">
> 
> If yes, then disable it, and reload extension (or browser), it should help. This option shouldn't be responsible for making work of scriptlets more verbose. It should be verbose only if filtering log is open.


Yes, I've closed it now and will open it again when the bug is fixed.   thank you!
