### ISSUE TITLE
AdGuard extension settings page in kiwi browser is unavailable

### ISSUE THREAD

**Issue by babut85** [AdguardTeam/AdguardBrowserExtension#2585]
### AdGuard version

0.3.89 but this is inaccurate

### Browser version

kiwi 116.0.5845.240

### OS version

android 10 arm64

### Issue Details

the settings window is not displayed. only the window with the general switch off is displayed. this has not happened with previos versions(with old gui). the extension has become completely useless

**Comment by slavaleleka** [comment]
> AdGuard version: 
> 0.3.89 but this is inaccurate

what do you mean? what actual version of the extension is problematic?

**Comment by alexx7311** [comment]
@babut85 Hello! Please update the extension to a newer version https://agrd.io/extension_chrome and check if the problem persists.

**Comment by babut85** [comment]
> @babut85 Hello! Please update the extension to a newer version https://agrd.io/extension_chrome and check if the problem persists.

0.3.90 mv3 experimental- without changes, the settings page is not displayed. google store doesn't find any other versions if i search from a mobile phone, but if i search from a computer then it finds. wtf?! %\
4.2.209 works fine

**Comment by maximtop** [comment]
> 0.3.90 mv3 experimental- without changes, the settings page is not displayed. google store doesn't find any other versions if i search from a mobile phone, but if i search from a computer then it finds. wtf?! %

There is special repo for mv3 experimental extension issues https://github.com/AdguardTeam/AdGuardMV3
Feel free to fill them there.
