### ISSUE TITLE
Slickdeals.net  referral links don't work

### ISSUE THREAD

**Issue by KeithGP** [AdguardTeam/AdguardBrowserExtension#2588]
### AdGuard Extension version

4.2.209

### Browser version

119.0.6045.106 

### OS version

Windows 11

### What filters do you have enabled?

No filters

### Issue Details

I am unable to click on any of the links that are referral out of slickdeals.net. I narrowed it down to AdGuard Adblocker by disabling the extension altogether and everything worked normal. I tried just disabling the filter on the site, but that did not work. I had to go into Extensions and disable the whole filter. When I click a link, the new tab tries to popup and is immediately closed.

### Expected Behavior

Be able to disable the filter and allow the website to work as normal

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by alexx7311** [comment]
@KeithGP Hello! Please report this website via the extension popup. You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/
