### ISSUE TITLE
Lack of rules in version 2.3.5

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardBrowserExtension#259]
Hello. I want to know the reason why rules are fewer in version 2.3.5 than in 2.3.4? 

For example: I have downloaded both versions to the browser and also added 10 same filters for each version. But when i enter the settings of these extensions saw that the number of rules were different in both versions.

So, The number of rules are 112,269 in version 2.3.4, but in version 2.3.5 are 87520.

**Comment by ameshkov** [comment]
What's the value of "Use optimized filters" setting?

**Comment by thislife81** [comment]
In version 2.3.4 are 73,195, but in version 2.3.5 are 73,196

**Comment by ameshkov** [comment]
Whitelist, user filter?

**Comment by thislife81** [comment]
Yes. They are simiilar.

**Comment by thislife81** [comment]
Yes. They are similar.

**Comment by ameshkov** [comment]
Which exact filters are turned on?

**Comment by thislife81** [comment]
1)English filter
2)Spyware filter
3)Social media filter
4)Experimental filter
5)Russian filter
6)Turkish filter
7)Mobile ads filter
8)EasyList
9)EasyPrivacy
10)Malware Domains

**Comment by ameshkov** [comment]
Huh, no clue, cannot reproduce it on my side.
