### ISSUE TITLE
YouTube will now detect adguard blocking ads

### ISSUE THREAD

**Issue by PoYu-Liao** [AdguardTeam/AdguardBrowserExtension#2591]
### AdGuard Extension version

4.2.209

### Browser version

chrome 119.0.6045.105

### OS version

windows 10 22H2

### What filters do you have enabled?

AdGuard Base filter, AdGuard Chinese filter, EasyList, NoCoin Filter List

### What Stealth Mode options do you have enabled?

Hide Referrer from third parties, Remove X-Client-Data header, Disable WebRTC

### Issue Details

When I was watching YouTube today, YouTube detected an ad-blocking extension.

The contents of the pop-up window are as follows
YouTube bans ad blockers
It seems you are using an ad blocker.
Ads enable YouTube to serve billions of users around the world.
If you want to watch ad-free content, you can subscribe to YouTube Premium so creators can still earn subscription revenue.

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/29099489/3a07b366-af54-4b44-8ea0-d5be76754a83)

</details>

**Comment by jezewskiBNetrox** [comment]
Update your filters. I just did that and this thing disappeared.

**Comment by Birbber** [comment]
Hello! We already have [an open issue on this problem](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2532). Closing this one as a duplicate.
