### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by Vasja777** [AdguardTeam/AdguardBrowserExtension#2592]
### AdGuard Extension version

Версия 4.2.209

### Browser version

Google Chrome  Версия 109.0.5414.120 (Официальная сборка), (64 бит)

### OS version

Windows 7

### What filters do you have enabled?

AdGuard Base filter

### Issue Details

Ютюб  отключает просмотр.Ваша программа не работает.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>
![Clip2net_231110002639](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/150396509/abde1af6-2f39-4a20-876c-70a85288cce8)
![Clip2net_231110002639](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/150396509/983d9f1d-e371-48a2-bf16-98267f80736a)

**Comment by Vasja777** [comment]
Проблема с фильтрацией рекламы

**Comment by Birbber** [comment]
Приветствую! У нас уже открыта [задача по данной проблеме](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2532). Пожалуйста, следите за прогрессом выполнения и, при необходимости, оставляйте комментарии.
Закрываем это обращение как дубликат #2532.
