### ISSUE TITLE
Filter auto-update does not work

### ISSUE THREAD

**Issue by Vitalik93** [AdguardTeam/AdguardBrowserExtension#2595]
### AdGuard Extension version

4.2.209

### Browser version

Edge 119.0.2151.44

### OS version

Windows 10

### What filters do you have enabled?

AdGuard Base filter, AdGuard Russian filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Issue Details

Заметил, что не работает автообновление фильтров. Стоит в настройках интервал "раз в час", но со вчера фильтры не обновлялись.

### Expected Behavior

Должны обновляться с установленным интервалом.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by alexx7311** [comment]
@Vitalik93 Здравствуйте! Попробуйте, пожалуйста, переустановить расширение и проверить, повторяется ли проблема.

В других браузерах тоже не работает?
Если установлены какие-то программы, которые работают с сетью, например файрволлы, антивирусы, прокси и впн-приложения, попробуйте их временно отключить.

**Comment by Vitalik93** [comment]
В данный момент проблема не актуальна. Один раз после спящего режима фильтры несколько часов не обновлялись, запустил обновление вручную и с тех пор все хорошо.
