### ISSUE TITLE
YouTube detects AdGuard

### ISSUE THREAD

**Issue by banshek7** [AdguardTeam/AdguardBrowserExtension#2597]
### AdGuard Extension version

3

### Browser version

chrome

### OS version

windows 11

### Issue Details

If I have the UI toggle for your shit turned to off, go to a video i want to play on youtube, let it load and get the block message, THEN hit the toggle on your UI and let it reload the page, it perfectly bypasses, so obviously there is a function happening at the start that you could look at and figure out why it works like that, and just put it in the actual running operation for youtube protection. 

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by AkramiPro** [comment]
youtube detect adblocker again

**Comment by alexx7311** [comment]
@banshek7 @AkramiPro Please update the extension to the latest version https://github.com/AdguardTeam/AdguardBrowserExtension/releases/tag/v4.2.226 and check if the problem persists.

**Comment by alexx7311** [comment]
@banshek7 @AkramiPro Is the problem still relevant?

**Comment by alexx7311** [comment]
Closing as dup. of https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2532
