### ISSUE TITLE
blick.ch needs reload to block ads on Safari

### ISSUE THREAD

**Issue by tiberian83** [AdguardTeam/AdguardBrowserExtension#260]
With beta 2.3.6 blick.ch needs a reload to block ads on Safari. It always happens after starting up Safari and loading the page for the first time. A reload of the page fixes it temporarly.

**Comment by ameshkov** [comment]
Temporarily?

**Comment by ameshkov** [comment]
Can't confirm it on my side. 

So, here are some questions:
1. Where should I look for ads there?
2. Can you reproduce the same issue with another website?
3. Old or new API?

**Comment by tiberian83** [comment]
![image](https://cloud.githubusercontent.com/assets/10312300/15701327/de46c3b0-27d9-11e6-86ab-cdd6bc74412a.jpeg)

**Comment by tiberian83** [comment]
Yes, with temprarly I mean until the next Safari startup.

To your other questions:
1. See the picture above.
2. So far I can't reproduce it on other pages. But I haven't tried to newest beta for a long time yet.
3. New API.

**Comment by tiberian83** [comment]
The picture shows the front page.

**Comment by ameshkov** [comment]
> 3. New API.

This may be the cause of it. New API need more time on content blocker initialization so something may be missed on the homepage.

To partially fix this we are doing a post-processing, hiding ads after content blocker is initialized. The problem with blick.ch is that post-processing did not help as google ads were already loaded into the page.

**Comment by ameshkov** [comment]
The question is why post-processing did not help in case of blick.ch.

How fast is that website's main page loading in your case? From my place it may take up to 5-10 seconds , is it the same for you?

**Comment by tiberian83** [comment]
Yes, it also takes several seconds to load. It's one of the pages that load very slow (old and new API) and much slower than with uBlock or on Chrome.

**Comment by tiberian83** [comment]
The problem never appeared on iOS though.

**Comment by ameshkov** [comment]
> Yes, it also takes several seconds to load. It's one of the pages that load very slow (old and new API) and much slower than with uBlock or on Chrome.

Btw, have you tried the old API in the new beta? Is it better now?

**Comment by ameshkov** [comment]
> The problem never appeared on iOS though.

Unlike iOS on OS X content blocker is registered on browser startup and it takes some time.

**Comment by tiberian83** [comment]
Yes, I tried the old API. My first impression was that it is maybe a little bit better but still not as fast as uBlock or Adguard on Chrome. Also the new API is still faster. But I will do some more testing these days.

**Comment by ameshkov** [comment]
> My first impression was that it is maybe

Give it some time, 1-2 page refreshes at most, it should warm up the filtering engine.
Our tests shows that on blick.ch with the changes we've made it should be faster than ublock.

**Comment by ameshkov** [comment]
Oh, and it never won't be as fast as AG on Chrome, Safari SDK is not very good from the performance point of view:(

**Comment by tiberian83** [comment]
Ok, I will try it again as soon as I get home tonight. :)

**Comment by tiberian83** [comment]
Maybe I will switch back to Chrome in a near future then. I just like a lot the Safari synchronisation between OS X and iOS. And Chrome on iOS has mo adblocking so far.

Something off topic: How's the progress of the full version of Adguard for iOS? It would be nice to block ads in apps too. :) Opera VPN does that perfectly but I don't want to route my data through their servers.

**Comment by ameshkov** [comment]
> Something off topic: How's the progress of the full version of Adguard for iOS? It would be nice to block ads in apps too. :)

Beta test will start in a month or so.

> Opera VPN does that perfectly but I don't want to route my data through their servers.

A bit controversial product you know. Blocking ads and collecting data about you to show you "more relevant" ads somewhere else..

**Comment by ameshkov** [comment]
@tiberian83 regarding the original issue, could you please try this build?
[AdguardBeta-2.3.6.safariextz.zip](https://github.com/AdguardTeam/AdguardBrowserExtension/files/293183/AdguardBeta-2.3.6.safariextz.zip)

Made some changes to the code detecting if post-processing rules should be applied to the page.

**Comment by tiberian83** [comment]
> Beta test will start in a month or so.
Nice. Will it be public? If you need another beta tester, let me know. :)

> A bit controversial product you know. Blocking ads and collecting data about you to show you "more relevant" ads somewhere else..
That's exactely why I don't want to use their service.

> regarding the original issue, could you please try this build?
I will install this new build tonight when I get home.

**Comment by ameshkov** [comment]
> Nice. Will it be public? If you need another beta tester, let me know. :)

Yep, through the TestFlight, as always:
https://forum.adguard.com/index.php?threads/adguard-for-ios-beta-test.6344/

We'll make a public announcement as soon as it's ready.

**Comment by tiberian83** [comment]
Thanks, I just joined the forum and sent a message to Vasily.

**Comment by tiberian83** [comment]
I tried the new build with the new API and blick.ch. I would say 3 out of 4 times it works fine, the other times I see a white gap but no ads so far. I will continue observing it but first I will try the old API now.

**Comment by tiberian83** [comment]
First impression is that the old API indeed is faster than before. Weird thing still is that these few Swiss pages load much slower than all the other pages while they load equally fast on Chrome. Maybe it has something to do with Safari too.

**Comment by ameshkov** [comment]
> Maybe it has something to do with Safari too.

This is definitely has something to do with it:)

> I would say 3 out of 4 times it works fine, the other times I see a white gap but no ads so far.

When it does not work fine, is it taking more time for blick.ch to load?

**Comment by tiberian83** [comment]
No, not really. Sometimes blick.ch loads fast and sometimes very very slow. But it's not related to the white gap or ads. Also the white gap only happens with the new API while the very slow loading happens with the old API. With the new API it's also slow sometimes but not as slow as the old API.

Difficult story... :-) I'm just wondering what is different on that page than on others.

**Comment by tiberian83** [comment]
Which browser, API, full version etc. do you use and which would you recommand as the best working solution?

**Comment by ameshkov** [comment]
> No, not really. Sometimes blick.ch loads fast and sometimes very very slow. But it's not related to the white gap or ads.

It seems that to find out the cause we need to add more logging to extension. I'll make a new build soon.

> Which browser, API, full version etc. do you use and which would you recommand as the best working solution?

I use all our products, switching from one to another periodically:)

It depends. Talking about browser extensions, Chrome provides us with more options and it is pretty fast. Standalone app version can block more due to the way it works (blocking on a network level). What for best working, just choose what suits you better.

**Comment by tiberian83** [comment]
I do the same thing right now. I bought a lifetime version for Android and Mac. The standalone app so far is the fastest option for Safari.

**Comment by tiberian83** [comment]
If I disable "protect from harmful pages" within Safari, blick.ch loads much faster. Maybe the problem is somewhere within this check.

**Comment by ameshkov** [comment]
@tiberian83 with a standalone app?

**Comment by tiberian83** [comment]
No, new API runs faster if "protect from harmful pages" is disabled. There's an option for it within Safari settings.

**Comment by ameshkov** [comment]
@tiberian83 thank you for doing this research, this may be important indeed. Filed a new issue on this: #263

**Comment by tiberian83** [comment]
You are welcome. It's just an Observation I did yesterday. But to be sure you understood me right. I'm not talking about the malware/phishing protection within Adguard. I'm talking about the option whithin Safari which is called something like "protect from harmful pages" (my Safari is in German) and connects to Google servers I think.

**Comment by ameshkov** [comment]
@tiberian83 
Oh, yep, I though that's about our feature:)

"Protect from harmful pages" uses google safebrowsing indeed. Maybe something wrong with how it is implemented in Safari as there's no slowdown in Chrome (the check is done asynchronously so it should not slow it down).
