### ISSUE TITLE
Google Chrome crashes when downloading 8 files at the same time

### ISSUE THREAD

**Issue by rsgpwxfvc** [AdguardTeam/AdguardBrowserExtension#2601]
### AdGuard Extension version

v4.2.209

### Browser version

Chrome119.0.6045.124

### OS version

Windows 11  (10.02261)

### Issue Details

I downloaded 8 files from Google Drive in Chrome at the same time, and then dragged the tabs of the same window.
The browser crashes every time.

Downloading the same 8 files at the same time, and then dragging the tabs of the same window, the browser will also crash.

When I remove adguard, the above problem no longer occurs.

1gb.test
https://drive.google.com/file/d/0B1MVW1mFO2zmZHVRWEQ3Rkc3SVE/edit

Hope this helps you test the bug

I attach my test video.
https://mega.nz/folder/smEzjILQ#fOqPMlw3ScvC1imQ3wan_A

### Expected Behavior

Stop crashing

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by alexx7311** [comment]
@rsgpwxfvc We couldn't reproduce the problem. Please update the extension to the newest version and check if the problem persists.
