### ISSUE TITLE
Detect coexistence with Consent-O-Matic

### ISSUE THREAD

**Issue by erkinalp** [AdguardTeam/AdguardBrowserExtension#2602]
### Issue Details

[Consent-O-Matic](https://github.com/cavi-au/Consent-O-Matic) is a browser extension to automate consent popup handling. It handles those banners by clicking them in the background. Hence, for this extension to work correctly, consent banners must not be suppressed.

### Proposed solution

If Consent-O-Matic is detected, suppress cookie dialog filters but continue applying other filters.

### Alternative solution

Incorporate consent handling into Adguard. Keep in mind Consent-O-Matic lets users pick by purpose of use.

**Comment by vozersky** [comment]
@erkinalp I don't think there is an actual need for more detailed adjustment i.e. allowing some tracking categories.
