### ISSUE TITLE
Маска *.site.com не работает в списке исключений (Allowlist)

### ISSUE THREAD

**Issue by AiratHalitov** [AdguardTeam/AdguardBrowserExtension#2611]
### AdGuard Extension version

4.2.209

### Browser version

Chrome 119.0.6045.160 (Official Build) (64-bit)

### OS version

Windows 10

### Issue Details

Пример: 
Раньше можно было указать регулярное выражение *.youtube.com, и под это условие попадали домены www.youtube.com и studio.youtube.com, а сейчас это не работает и нужно добавлять каждый домен вручную. 
А если у сайта куча поддоменов, то это превращается в ужас и рутину. 

Регулярное выражение для поддомена *.site.com должно иметь больший приоритет, чем точное указание поддомена test.site.com
Например:
*.google.com
включает в себя и docs.google.com, и drive.google.com, и mail.google.com

Можете это исправить, пожалуйста?

P.S. Или у вас поменялся синтаксис, и я об этом не знаю? Просто ссылки на справку нету, поэтому это не так очевидно.

**Comment by maximtop** [comment]
в версии 4.2.226 вернули возможность указывать wildcard
проверить можно пока только на бете https://chromewebstore.google.com/detail/adguard-adblocker-beta/gfggjaccafhcbfogfkogggoepomehbjl

**Comment by AiratHalitov** [comment]
> в версии 4.2.226 вернули возможность указывать wildcard проверить можно пока только на бете https://chromewebstore.google.com/detail/adguard-adblocker-beta/gfggjaccafhcbfogfkogggoepomehbjl

Поставил бету -- работает. Спасибо!
