### ISSUE TITLE
Google and Yandex search sites are blocked. The culprit Adguard Persoanal CA according to Google.

### ISSUE THREAD

**Issue by DRCLEMENTAKATENG** [AdguardTeam/AdguardBrowserExtension#2616]
### AdGuard Extension version

4.2.22 beta

### Browser version

Firefox 120

### OS version

Windows 10

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

When I type in anything for Google search no search results come up except pointing the finger at Adguard Personal CA or I have been hacked.

**Comment by alexx7311** [comment]
@DRCLEMENTAKATENG Hello! Do you have AdGuard for Windows or Mac installed? Our extensions do not replace website's certificates with AdGuard Personal CA. To reinstall the certificate please go to AdGuard **Settings > Network > Reinstall Certificate** or you can use this link http://local.adguard.org/cert to reinstall it manually.

**Comment by DRCLEMENTAKATENG** [comment]
No I do not have Adguard/Adguard Personal CA installed on my Laptop.
