### ISSUE TITLE
The $all modifier does not work in current tab

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#2620]
### AdGuard Extension version

4.2.228 beta

### Browser version

Chrome 119.0.6045.200 

### OS version

Windows 10 x64

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters, Hide your search queries, Send websites signals not to track you, Hide Referrer from third parties, Remove X-Client-Data header, Disable WebRTC

### Issue Details

'$all' and '$popup' do nothing in current tab.
Related to https://github.com/AdguardTeam/AdguardFilters/issues/167012 [NSFW]

### Steps to reproduce

0. Unblock all `#%#` for this site
1. Add to user rules

```
||crmentjg.com^$all
||crmpt.livejasmin.com^$all
||twinrdsrv.com^$all
```

2. Open https://www.inxxx.com/v/big-dick-christy-mack-fucks-one-lucky-photographer-cowgirl-video.xxx-video  [NSFW] in a new private tab
3. Click on the player

### Actual behavior

Ad redirect happens in the current tab, but the visited site open in a new tab.

### Expected Behavior

Ad redirect must be blocked (stopped by the blocking page dummy) by the rules above like in 4.1

**Comment by 105th** [comment]
Related issue - https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2732
