### ISSUE TITLE
Loss of antiphishing and antimalre settings

### ISSUE THREAD

**Issue by RadoslawDeska** [AdguardTeam/AdguardBrowserExtension#2623]
### AdGuard Extension version

4.2.209

### Browser version

Firefox 120.0

### OS version

Windows 10 22H2

### What filters do you have enabled?

AdGuard Base filter, Filter unblocking search ads and self-promotion

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters, Hide your search queries, Send websites signals not to track you, Self-destruction of third-party cookies, Hide Referrer from third parties, Remove X-Client-Data header

### Issue Details

I put Windows into hibernation state while Firefox running with several tabs opened in only one window. When restoring Windows session after hibernation, Adguard loses its settings: Phishing & Malware security in Basic Settings tab, ALL filters in Filters tab are switched off, Invisibility setting is switched off, and previously populated list of allowed is cleared.

### Expected Behavior

I expect that nothing interferes with Adguard extension, especially that Windows session is supposed to restore exact state of a machine from before hibernation.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by RadoslawDeska** [comment]
As a comment, reinstallation of the extension seems to have worked. But why I had to do it? I expect this is wrong...

**Comment by Birbber** [comment]
@RadoslawDeska Hello! Thank you for the report.
Could you check if it's still reproducible for you in a new version when it's released? [v4.2.228](https://github.com/AdguardTeam/AdguardBrowserExtension/releases/tag/v4.2.228) is currently under the store review in Firefox, but we expect it to be published soon. You can also download beta version following the link at 'how to install beta' section.

**Comment by RadoslawDeska** [comment]
This is a little bit difficult to reproduce, because I reinstalled the extension in Firefox and the problem was gone. So I cannot and will probably not be able to reproduce it. Would have to wait for it to happen...

**Comment by erkinalp** [comment]
Possible solution: #2604
