### ISSUE TITLE
Regex rules are not working

### ISSUE THREAD

**Issue by tumatanquang** [AdguardTeam/AdguardBrowserExtension#2624]
### AdGuard Extension version

4.2.209

### Browser version

Chrome 109

### OS version

Windows 7

### What filters do you have enabled?

Filter unblocking search ads and self-promotion

### Issue Details

Here's the link to the banner image I want to block: https://i2.wp.com/hentaivnmoi.net/wp-content/uploads/2023/10/banner-five88-new-465x60-1.gif
These are the rules that I used to try to block that link:
```
/banner.*\.gif/
/banner.*\.gif/$image
/banner*\.gif/
/banner*\.gif/$image
/banner-.*\.gif/
/banner-.*\.gif/$image
```
However, all of the above rules are not applicable to the banned image link that I mentioned above. It is not blocked by the above rules!

### Expected Behavior

Although all the rules that I have given above match the banner image link. However, it seems that the extension ignored it even though it should have been blocked.

**Comment by alexx7311** [comment]
@tumatanquang Hello! Please try the following rule `/banner-*.gif$domain=hentaivnmoi.net`

**Comment by tumatanquang** [comment]
Hi @alexx7311, I tried the blocking rule you gave, but it didn't work. According to the link above, it seems that the banner is downloaded via CDN with the domain name `i2.wp.com` so I also tried more with the blocking rule: `/banner-*.gif$domain=i2.wp.com`. And it doesn't work!

**Comment by alexx7311** [comment]
@tumatanquang It should work. Please try to clear the browser's cache or open the link in incognito mode.

<details>
  <summary>Screenshot</summary>

  ![Screenshot](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/114913601/3d2cf7e5-771b-4c40-ac14-3d26f629dc20)

</details>

**Comment by alexx7311** [comment]
@tumatanquang Is the problem still relevant?

**Comment by GrennKren** [comment]
> /banner-*.gif$domain=hentaivnmoi.net

That is wildcard and not regex format
