### ISSUE TITLE
Filtering does not work in the sidebar

### ISSUE THREAD

**Issue by Spok1** [AdguardTeam/AdguardBrowserExtension#2633]
### AdGuard Extension version

4.2.228

### Browser version

Edge 119

### OS version

Windows 10

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Russian filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Experimental filter

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters, Hide your search queries, Hide Referrer from third parties

### Issue Details

The extension in the Ms Edge browser does not filter pages opened from the sidebar.

### Expected Behavior

I want the pages opened in the sidebar to be filtered, as in the main window!

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/34476664/f259ad43-1c70-49dc-b12f-76556cf27631)

</details>

**Comment by Birbber** [comment]
Hello! Thank you for the report.
We already have [an open issue on this matter](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2223). You can watch the progress and leave comments there. 
I'm closing this one as a duplicate.

**Comment by Spok1** [comment]
@Birbber, as far as I understood, this problem has not been solved, but there will be in the future?

**Comment by trmdi** [comment]
@Spok1 
Subscribe to this issue: https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2223
