### ISSUE TITLE
YouTube detection

### ISSUE THREAD

**Issue by LunarVZ** [AdguardTeam/AdguardBrowserExtension#2635]
### AdGuard Extension version

4.2.228

### Browser version

Chrome Version 119.0.6045.200

### OS version

Windows 10 Pro 22H2

### What filters do you have enabled?

AdGuard Base filter, AdGuard Japanese filter

### Issue Details

YouTube simply showed their usual warning about "Using an Adblocker".

### Expected Behavior

YouTube not doing anything

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by imamulikhlas** [comment]
happened to me

**Comment by alexx7311** [comment]
@LunarVZ @imamulikhlas Please open the popup and click on 'Check for filter updates' button, then restart the browser. Does that solve the problem?

**Comment by LunarVZ** [comment]
@alexx7311 Think that worked for me. I'll close the issue on my thread for now since I think YouTube hasn't interrupted me for awhile. @imamulikhlas You'll have to open a new bug thread through the extension if updating the filters didn't work for you.
