### ISSUE TITLE
'this [#api] is undefined' error

### ISSUE THREAD

**Issue by manorov** [AdguardTeam/AdguardBrowserExtension#2636]
### AdGuard Extension version

Versão 4.2.228

### Browser version

Firefox 110.0.1 (64-bits)

### OS version

Windows 10

### What filters do you have enabled?

AdGuard Base filter

### Issue Details

my adguard extension stopped working today, the page of loading filters is stuck the loading, the test site says i have no adguard enabled, and the ads arent being blocked

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>
![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/103893365/42fa91ab-ffe4-488d-aacc-956ee7835664)

**Comment by manorov** [comment]
![Screenshot_1](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/103893365/708ebc56-10c6-49cc-9f96-6b7cc7f10924)

yes a error in background.html

im stuck in this page
![Screenshot_2](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/103893365/f0086542-9a38-4be8-9a7e-727fcffabab0)

and the extension dont load completely
![Screenshot_7](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/103893365/4bb3741c-327b-4003-9187-41b416932142)

**Comment by Barmem** [comment]
seems like theres still an issue 
![изображение](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/70278808/25976520-43b9-4e85-842c-4a67e36f5678)

**Comment by maximtop** [comment]
> seems like theres still an issue

please specify your extension and browser versions

**Comment by Barmem** [comment]
> > seems like theres still an issue
> 
> please specify your extension and browser versions

extention: 4.3.13
broswer: Firefox 123.0.1 (64 bit)
