### ISSUE TITLE
Youtube blocked adblock

### ISSUE THREAD

**Issue by Giyu9500** [AdguardTeam/AdguardBrowserExtension#2638]
### AdGuard Extension version

4.2.228

### Browser version

119.0.6045.200

### OS version

Windows 10 Home 22H2

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

### Issue Details

The filter does not block YouTube ads

### Expected Behavior

Please update your filters so you can watch YouTube without ads again

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by a-milburn** [comment]
Try the latest release, it seems to be evading YoutTube now.

**Comment by Birbber** [comment]
Hi! Thank you for the report.
We already have [an open issue on that matter](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2532). I'm closing this one as a duplicate.
