### ISSUE TITLE
Помощь

### ISSUE THREAD

**Issue by them1212** [AdguardTeam/AdguardBrowserExtension#2639]
Здравствуйте скажите пожалуйста, а когда браузерное расширение, выйдет из бетэ версии и плохо блокируется реклама на сайтах.

**Comment by them1212** [comment]
Понятно, а как мне создать раздачу в репозитории, какой раздел надо выбрать например не блокируется реклама на сайтах.

**Comment by Alex-302** [comment]
А в журнале фильтрации есть что-то?

**Comment by them1212** [comment]
Здравствуйте, да есть журнал фильтрации, скриншот отправляю[
![Screenshot_20231212_111426_com yandex browser](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/38691051/6501d732-a3d6-4c63-879d-edb86499f472)
](url)
