### ISSUE TITLE
Automatically check if filter rules can be compiled correctly.

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardBrowserExtension#264]
Noticed in iOS version: 
When users try to add a filter with incorrect rules in it, they see a notification message about hitting 45k rules limit.

**Comment by ameshkov** [comment]
We should make some kind of a test extension which will download all our filters and then check if these downloaded filters are compiled into a valid content blocker.

If content blocker is not valid, this test extension should find out which filter rule is invalid.

Current Safari version has a callback parameter in "setContentBlocker", so you'll be able to find out if it is registered successfully or not.

**Comment by ameshkov** [comment]
Look at how guys from ABP handle errors:
```
function setContentBlocker(callback)
{
  // When given the same rules as last time setContentBlocker will always give
  // null (success) to the callback, even when there was actually an error. We
  // cache the last result therefore so that we can provide a consistent result
  // and also to avoid wastefully regenerating an identical blocklist.
  if (!contentBlockListDirty)
  {
    callback(lastSetContentBlockerError);
    return;
  }

  let contentBlockerList = new ContentBlockerList();
  for (let subscription of FilterStorage.subscriptions)
    if (!subscription.disabled)
      for (let filter of subscription.filters)
        contentBlockerList.addFilter(filter);

  contentBlockListDirty = false;
  safari.extension.setContentBlocker(
    // There is a strange bug in setContentBlocker for Safari 9 where if both
    // the callback parameter is provided and the rules aren't converted to a
    // JSON string it fails. Worse still it actually performs the callback twice
    // too, firstly with an empty string and then with an Error:
    //   "Extension compilation failed: Failed to parse the JSON String."
    // To mitigate this we convert the rules to JSON here and also ignore
    // callback values of "". (Usually the callback is performed with either
    // null for success or an Error on failure.)
    // Bug #26322821 filed on bugreport.apple.com
    JSON.stringify(contentBlockerList.generateRules()),
    function(error)
    {
      if (error == "")
        return;

      lastSetContentBlockerError = error;
      callback(error);
    }
  );
}
```

**Comment by Mizzick** [comment]
I added this ABP like error handling in our code. So now we can show proper error message for users.

**Comment by ameshkov** [comment]
I was talking not about error handling in our code. This error message does not mean anything even for us, what's good in it for user?

**Comment by ameshkov** [comment]
Read this comment thoroughly:
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/264#issuecomment-225127771

We need a test extension that will find out which exact rule is failing.
Currently we are doing it manually dividing the list etc.

**Comment by Mizzick** [comment]
>>When users try to add a filter with incorrect rules in it, they see a notification message about hitting 45k rules limit.

So now we can show correct message for users, what is bad in that?

**Comment by ameshkov** [comment]
> So now we can show correct message for users, what is bad in that?

Not bad, we should show it (however it is not yet finished, I don't see the code for showing error message yet).

It's just this issue is about different thing.

**Comment by Mizzick** [comment]
Ok, take a look
/trunk/Applications/Extensions/SafariContentBlockerTester

**Comment by ameshkov** [comment]
> Ok, take a look
> /trunk/Applications/Extensions/SafariContentBlockerTester

Push it to this repo to a separate folder

**Comment by Mizzick** [comment]
https://github.com/AdguardTeam/SafariContentBlockerTester
