### ISSUE TITLE
Can't disable filtering for each site

### ISSUE THREAD

**Issue by alije123** [AdguardTeam/AdguardBrowserExtension#2642]
### AdGuard Extension version

4.2.228

### Browser version

Firefox 122.0a1

### OS version

Windows 10 22H2

### What filters do you have enabled?

AdGuard Base filter, AdGuard Russian filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, EasyList, Fanboy's Annoyances, Fanboy's Social Blocking List, RU AdList - Counters, Fanboy's Anti-Facebook List, I don't care about cookies

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters, Hide your search queries, Hide Referrer from third parties

### Issue Details

I click on the "Protection Switch" to disable filtering for a specific site, there is a delay (which is already described in another question) and the site reloads again with filtering enabled, and when I open the extension modal window again and the switch is back on. There is nothing in the logs on background.html

### Expected Behavior

The page reloads and filtering is disabled

### Screenshots

![firefox_804hpedmxa](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/33022255/cafa4e98-00ac-470f-a78c-6fd2ab0bc2ca)  (if I hide the gif under the spoiler, it won't render)

**Comment by alexx7311** [comment]
@alije123 Thanks! We'll think about implementing the feature you mentioned.
