### ISSUE TITLE
Can't open the Emoji tab in Twitch.

### ISSUE THREAD

**Issue by DexfromAntarctica** [AdguardTeam/AdguardBrowserExtension#2643]
### AdGuard Extension version

4.2.228

### Browser version

Chrome 120.0.6099.71

### OS version

Windows 10 19045.3693

### What filters do you have enabled?

AdGuard Base filter

### Issue Details

In Twitch, I can't open Emoji tab located at typing. It's not problem of BetterTTV and other Extension, just Adguard browser Extension. 

Unusually, double-tapping the Twitch Chat setting to turn it on opens the Emoji tab. And when I close it again, it doesn't open.
I hope you can fix it soon.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by alexx7311** [comment]
@DexfromAntarctica Hello! We couldn't reproduce the problem. Please disable all other extensions, clean your browser cookies or open twitch.tv in incognito mode and see if the problem recurs.

**Comment by DexfromAntarctica** [comment]
now it's fixed 👍 Thx
