### ISSUE TITLE
The extension is not blocking a redirection to another website

### ISSUE THREAD

**Issue by enaelspeed** [AdguardTeam/AdguardBrowserExtension#2644]
### AdGuard Extension version

Version 4.2.228

### Browser version

chrome 120

### OS version

windows 11 23h2

### What filters do you have enabled?

AdGuard Base filter

### Issue Details

Lors d'un clic au lieu de bloquer une redirection vers un site inconnue.
affiche des nuisances et ad guard ne la pas bloquer.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by erkinalp** [comment]
Translated from original french:

> When clicked instead of blocking a redirection to an unknown site, displays nuisances and ad guard does not block it.

**Comment by alexx7311** [comment]
@enaelspeed Hello! What steps do you take to reproduce the problem? Please attach some screenshots to illustrate the problem.

**Comment by alexx7311** [comment]
@enaelspeed We'll need more details to investigate the issue. We're closing the issue for now.
