### ISSUE TITLE
The YouTube premium advertising comes through again when you open the YouTube page for the first time

### ISSUE THREAD

**Issue by Aura67** [AdguardTeam/AdguardBrowserExtension#2645]
### AdGuard Extension version

4.2.228

### Browser version

firefox 120.0.1

### OS version

Microsoft Windows 10 

### Issue Details

I have found a mistake, YouTube has if you now click on accept cookies in the browser in Firefox with the AdGuard adblocker, the advertising from YouTube Premium appears at the top and is no longer blocked. YouTube must have changed something for the advertising so that it can get through again. So when you open the YouTube page for the first time.

### Expected Behavior

I forgot to take a screen and I no longer get the message.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

If I still find problems, I'll create a new problem. I've only been able to find one problem!

**Comment by alexx7311** [comment]
@Aura67 Hello! 
Please check if the necessary filters are enabled and up to date.
The list of filters that covers the main part of ads is following: **Base filter, Tracking Protection filter, Mobile Ads filter, Social Media filter, Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter.**

Clean your browser cookies and see if the problem recurs. If it does, open the AdGuard extension popup and click "Report an issue", then follow the on-screen instructions.
