### ISSUE TITLE
Must fully disable AdGuard to get login prompt

### ISSUE THREAD

**Issue by muttmutt** [AdguardTeam/AdguardBrowserExtension#2647]
### AdGuard Extension version

4.2.228

### Browser version

120.0.6099.62 (Official Build) (x86_64)

### OS version

macOS 14.2 (23C64)

### What filters do you have enabled?

AdGuard Base filter, AdGuard Popups filter, AdGuard Other Annoyances filter

### Issue Details

When attempting to log into foreignpolicy.com, I end up having to disable alll elements of AdBlock to get the prompt.

### Expected Behavior

It should work without disabling ad blocking

### Screenshots

<details><summary>Screenshot 1:</summary>

https://github.com/AdguardTeam/AdguardBrowserExtension/assets/46875832/1da25519-0eaf-4c33-8134-6d35d7be6865

</details>

**Comment by Birbber** [comment]
@muttmutt Hi. Thank you for the report.
Is there a reason why you use both the extension and the desktop application? We'd recommend using the desktop only as it already covers all applications and browsers.

We haven't been able to reproduce it on our end. Please send us the exported settings file of AdGuard Browser Extension so we can see what causes the issue.

**Comment by muttmutt** [comment]
I wondered about that. So I guess I’m a belt-and-suspenders guy. 🤣

Ok, I’ll disable the browser extension and see if that makes things better. Thanks.

--
Phil Scarr
***@***.***

**Comment by Birbber** [comment]
Sure. Let us know if anything else happens.
I'm closing this issue for now, feel free to re-open it if needed.
