### ISSUE TITLE
Floating adguard logo in the way all the time

### ISSUE THREAD

**Issue by theeharlequin** [AdguardTeam/AdguardBrowserExtension#2649]
### Issue Details

This adguard logo appeared recently.  It is on any web page I visit.  It is in the way and pisses me off.  Is there any way to get rid of this pointless annoyance?  You can see it in the lower right of this screenshot.
![AD Block Screensot](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/73401087/3b6d38a3-1a26-496a-874e-3a778e02820f)

### Proposed solution

Please get rid of this damned thing. 

### Alternative solution

I will have to uninstall the extension altogether.

**Comment by Birbber** [comment]
@theeharlequin Hi. Thanks for the report.
This icon is the [legacy assistant](https://github.com/AdguardTeam/AdguardAssistant) which was most likely enabled in AdGuard desktop application. You can disable it in Settings --> Browser Assistant --> and uncheck `Legacy Assistant` option.

**Comment by theeharlequin** [comment]
Thank you that worked!

H Joseph "Chip" Wagner







On Friday, December 15, 2023 at 03:40:53 AM PST, Anna ***@***.***> wrote: 







@theeharlequin Hi. Thanks for the report.
This icon is the legacy assistant which was most likely enabled in AdGuard desktop application. You can disable it in Settings --> Browser Assistant --> and uncheck Legacy Assistant option.

**Comment by theeharlequin** [comment]
That annoying ad guard logo is floating in front of all my web pages.  How do I delete it?

H Joseph "Chip" Wagner







On Friday, December 15, 2023 at 03:41:36 AM PST, AdGuard GitHub Bot ***@***.***> wrote: 







Closed #2649 as completed.
