### ISSUE TITLE
Cosmetic rules with wildcard do not work on some domains

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/AdguardBrowserExtension#2650]
I'm not sure if it happens on other domains, but it occurs on `.com.ru`

AdGuard AdBlocker version 4.2.228/4.2.240

### Steps to reproduce:
1. Add these rules:
```adblock
flightradar24.*##body
flightradar24.*#%#alert(1);
```
2. Navigate to - [https://flightradar24.com.ru/faq/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://flightradar24.com.ru/faq/)

### Expected Behavior
Rules should be applied - website should be blank and there should be message `1`.

### Actual Behavior
Rules are not applied on websites with `.com.ru` domain.

**Comment by PaTTeeL** [comment]
Same problem here, uses example in https://adguard.com/kb/general/ad-filtering/create-own-filters/
`[$url=/\[a-z\]+\\.example\\.com^/]##.textad` like `[$url=/\[a-z\]+\\.smzb618\\.com^/]##.menu` which does not work with site https://smzb618.com/live/297468?sjsc_source_code=x8g8s.

And only `[$domain=smzb618.*]##.menu` or `[$domain=smzb618.com]##.menu` works, so is there anything wrong ?

I‘ve tried 
```
[$domain=/smzb618.+/]##.menu
[$domain=/smzb618\.+/]##.menu
[$domain=/smzb618.\+/]##.menu
[$domain=/smzb618\.\+/]##.menu
[$domain=\/smzb618.+/]##.menu
[$domain=\/smzb618\.+/]##.menu
[$domain=\/smzb618.\+/]##.menu
[$domain=\/smzb618\.\+/]##.menu
[$domain=/smzb618.+\/]##.menu
[$domain=/smzb618\.+\/]##.menu
[$domain=/smzb618.\+\/]##.menu
[$domain=/smzb618\.\+\/]##.menu
[$domain=\/smzb618.+\/]##.menu
[$domain=\/smzb618\.+\/]##.menu
[$domain=\/smzb618.\+\/]##.menu
[$domain=\/smzb618\.\+\/]##.menu
[$url=/smzb618.+/]##.menu
[$url=/smzb618\.+/]##.menu
[$url=/smzb618.\+/]##.menu
[$url=/smzb618\.\+/]##.menu
[$url=/smzb618.+\/]##.menu
[$url=/smzb618\.+\/]##.menu
[$url=/smzb618.\+\/]##.menu
[$url=/smzb618\.\+\/]##.menu
[$url=\/smzb618.+/]##.menu
[$url=\/smzb618\.+/]##.menu
[$url=\/smzb618.\+/]##.menu
[$url=\/smzb618\.\+/]##.menu
[$url=\/smzb618.+\/]##.menu
[$url=\/smzb618\.+\/]##.menu
[$url=\/smzb618.\+\/]##.menu
[$url=\/smzb618\.\+\/]##.menu
[$url=||smzb618.com*]##.menu
[$url=||smzb618.com^]##.menu
```
nothing happened either.

**Comment by maximtop** [comment]
There are compatibility notes in the end of description of the each modifier in the adguard rules. They state that these modifiers are not fully supported in the extension yet.

**Comment by PaTTeeL** [comment]
> There are compatibility notes in the end of description of the each modifier in the AdGuard rules. They state that these modifiers are not fully supported in the extension yet. They will be supported in v4.4 though.

Thank you for reply. Waiting for the update!
