### ISSUE TITLE
when creating a filter for myself, how to i get wildcard characters to work?

### ISSUE THREAD

**Issue by m2c2lure67** [AdguardTeam/AdguardBrowserExtension#2656]
### Issue Details

e.g...this works for one video using the child(26), but child(*) does not work.:
youtube.com###movie_player > div.ytp-player-content.ytp-iv-player-content:nth-child(26) > div.annotation.annotation-type-custom.iv-branding > button.branding-img-container.ytp-button:first-child > img.branding-img.iv-click-target

### Proposed solution

how to i format the syntax to get the wildcard character to work?

**Comment by alexx7311** [comment]
@m2c2lure67 The `*` character is not supported in `:nth-child(n)`
You can only use numbers and the `n` multiplier.

Example for reference: https://webdesign.tutsplus.com/the-30-css-selectors-you-must-memorize--net-16048t

The best solution is to check in devtools if the selector finds what you need, given that the element exists.
