### ISSUE TITLE
AdGuard extension filters reset in Firefox browser after sleep mode

### ISSUE THREAD

**Issue by Nfams** [AdguardTeam/AdguardBrowserExtension#2657]
### AdGuard Extension version

4.2.228

### Browser version

Firefox from like 120 maybe?

### OS version

win 10

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Popups filter, EasyList

### Issue Details

Each day i wake my pc from sleep (this desktop and my suface pro too. I have to re enable the filters individually or load from a profile i decided to save as this has been happening all the time. Could it be a firefox bug?

### Expected Behavior

The filters would stay saved on or off

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Birbber** [comment]
@Nfams Hello. Thank you for the report. 
This issue should have already been fixed in [version 4.2.240](https://github.com/AdguardTeam/AdguardBrowserExtension/releases/tag/v4.2.240). Please update and check if the problem still persists.

**Comment by Nfams** [comment]
It is updated. I will check if the problem persists. Thanks for your help

**Comment by alexx7311** [comment]
@Nfams Is the problem still relevant?

**Comment by Nfams** [comment]
Yes it still persists on desktop. I'm thinking it could be the Firefox
version as one other pc I have is on 120 not the latest patch and it is
keeping the filters enabled. Mobile seems fine too. Thanks for your help.

**Comment by Nfams** [comment]
any idea as to what would be happening as on my desktop which i use for may hours i seem to need to re enable my profile a few times a day. I'll check the interval tomorrow

**Comment by alexx7311** [comment]
@Nfams Do you have a stable way to reproduce the problem? We can, for example, try to remotely connect to your computer and try to figure it out.

**Comment by Nfams** [comment]
Not too sure but could it have something to do with multiple windows at the same time? My primary window is yt videos and has stayed enabled all day however the window for all else has been dissabling all day?

**Comment by alexx7311** [comment]
@Nfams We have not been able to reproduce this problem, so it's hard to say. If a developer connects to your computer, will you be able to reproduce the problem and show it to them?

**Comment by Nfams** [comment]
Only lead i have is when my surface pro hibernates or if I close firefox it
resets

**Comment by alexx7311** [comment]
@Nfams If the problem happens again, please leave a comment and we'll reopen the issue.
