### ISSUE TITLE
Can't install Adguard-2.3.8.safariextz

### ISSUE THREAD

**Issue by tiberian83** [AdguardTeam/AdguardBrowserExtension#266]
When I try to install Adguard-2.3.8.safariextz I just get an error message saying it's not possible to install it. Beta works fine though.

**Comment by ameshkov** [comment]
Have you tried 2.3.9? Published it tomorrow.

**Comment by tiberian83** [comment]
Yes, I did. 2.3.9 doesn't work neither. Again beta works fine. I tried it on two different Macs.

**Comment by ameshkov** [comment]
Weird, can't confirm it on my side. I wonder if it is some security limitation which I don't have as I am a developer?

**Comment by tiberian83** [comment]
Maybe. Weird thing is that 2.3.8 and 2.3.9 beta work fine. Also the update doesn't show up automatically in Safari while it does with the beta.

**Comment by tiberian83** [comment]
I just tried the Safari Technology Preview. It works fine there but still not with the normal Safari.

**Comment by ameshkov** [comment]
The only difference is the update channel (release should get updates from the extensions gallery)

**Comment by tiberian83** [comment]
Well the weird thing is I can't update the release version from 2.2.3 to 2.3.9 neither automatically nor manually. :(

**Comment by ameshkov** [comment]
> Well the weird thing is I can't update the release version from 2.2.3 to 2.3.9 neither automatically nor manually. :(

That's ok, 2.3.9 is still waiting for review, so it's not yet available in extensions gallery.

**Comment by worldsdream** [comment]
Remove it from safari extension first.
Then install the one from github 2.3.9

You can find it here:
https://github.com/AdguardTeam/AdguardBrowserExtension/releases

**Comment by tiberian83** [comment]
This worked. Thank you.

**Comment by worldsdream** [comment]
Great. @ameshkov you can mark this as resolved.
