### ISSUE TITLE
icloud.com/mail - does not open with Stealth mode

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/AdguardBrowserExtension#2660]
### AdGuard Extension version

4.2.240

### Browser version

Chrome 120

### OS version

Windows 11

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters, Hide your search queries, Send websites signals not to track you, Self-destruction of third-party cookies, Self-destruction of first-party cookies, Hide Referrer from third parties, Remove X-Client-Data header, Disable WebRTC

### Issue Details

https://github.com/AdguardTeam/AdguardFilters/issues/168928. icloud mail does not open with the Stealth mode enabled.
Looks like exceptions do not help at all. Don't see the same with the app, only with extension.
```adblock
@@||cdn.apple-cloudkit.com^$stealth
@@||appleid.cdn-apple.com^$stealth
@@||webcourier.push.apple.com^$stealth
@@||apple.com^$stealth
@@||icloud.com^$stealth
```

STR:
1. Disable filters
2. Enable stealth mode with all options
3. Add the exceptions above to user rules
4. Open the site
5. Log in.

### Expected Behavior

 icloud mail should be loaded.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by zloyden** [comment]
Similar issue https://github.com/AdguardTeam/AdguardFilters/issues/169044. It works fine with the app, but not with the extension.

**Comment by yagee** [comment]
I have same issue!

**Comment by pduchnovsky** [comment]
The issue is with "Hide Referrer from third parties", with this setting disabled, it works again.
