### ISSUE TITLE
The AdGuard AdBlocker extension is not supported for the 91 esr version of Firefox.

### ISSUE THREAD

**Issue by maximtop** [AdguardTeam/AdguardBrowserExtension#2661]
![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/17272769/103b24f6-19b4-43a4-bf9b-41667d3a9b84)

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/17272769/a17abf5f-5473-4f82-a8e6-0f2599b4f2a1)

**Comment by krystian3w** [comment]
Now we have Firefox 115 ESR, so no worth is use 91/102 ESR releases.
