### ISSUE TITLE
AdGuard extension settings in Firefox browser are often cleared off

### ISSUE THREAD

**Issue by nwave3** [AdguardTeam/AdguardBrowserExtension#2663]
### AdGuard Extension version

4.2.240

### Browser version

Firefox 120.0.1

### OS version

Windows 10

### What filters do you have enabled?

AdGuard Base filter, AdGuard Russian filter, AdGuard Tracking Protection filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter

### What Stealth Mode options do you have enabled?

Block trackers, Send websites signals not to track you

### Issue Details

Постоянно слетают настройки расширения и начинает показываться реклама. При выставлении своих настроек расширения, где то через час они уже могут слететь.

### Expected Behavior

Ожидаемый результат, что не приходится каждый час заходить в настройки и заново не устанавливать фильтры.

### Screenshots

<details><summary>Screenshot 1:</summary>

 

</details>

**Comment by alexx7311** [comment]
@nwave3 Здравствуйте! Опишите, пожалуйста, пошагово, как повторить проблему. 
Повторяется ли проблема, если сбросить настройки Firefox на стандартные?

**Comment by nwave3** [comment]
@alexx7311 Здравствуйте. Сначала заметил закономерность, что фильтры сбрасываются, когда автоматически включается русский фильтр и я отключил эту настройку. Сейчас вижу, что настройки могут сброситься если я сверну браузер на несколько минут или просто в процессе работы с браузером и я не понимаю, что вызывает ошибку. Использую стандартные настройки Firefox, отключил только сбор статистики.

**Comment by alexx7311** [comment]
@nwave3 Подскажите, пожалуйста, есть ли у вас стабильный способ повторить эту проблему? У нас повторить не получается, но мы можем, например, попробовать удаленно подключиться к вашему компьютеру и попытаться разобраться.

**Comment by alexx7311** [comment]
@Santademon @kpd328 Hello! Do you have a stable way to reproduce this problem? We can try connecting to your computer remotely and try to figure it out.

**Comment by kpd328** [comment]
The most consistent way I've found is to close the browser and reopen it, that'll trigger settings clearing every time. It does also happen occasionally when browsing, but that doesn't seem to carry any sort of consistency I can see.

**Comment by alexx7311** [comment]
@kpd328 If the settings are cleared after every time you reopen your browser, then that would be enough to identify the problem. Please email mtopciu@adguard.com and include the number of this problem (2663) in the subject line.

**Comment by maximtop** [comment]
I investigated the issue on a PC exhibiting similar behavior and suspect that it may be a bug related to Firefox. Occasionally, Firefox seems to lack the ability to set, get, or delete data in the storage by specific key "adguard-settings".

![anydesk00002](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/17272769/da4a8784-67c9-4253-8c02-79ee4d6bd488)

**Comment by maximtop** [comment]
I've created the issue in the firefox bug tracker.
https://bugzilla.mozilla.org/show_bug.cgi?id=1885297
