### ISSUE TITLE
Can't block Ad's in https://www.dogdrip.net/

### ISSUE THREAD

**Issue by DexfromAntarctica** [AdguardTeam/AdguardBrowserExtension#2664]
### AdGuard Extension version

 4.2.240

### Browser version

Chrome 120.0.6099.129

### OS version

Windows 10 19045.3693

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard URL Tracking filter, EasyList, List-KR

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters

### Issue Details

dogdrip.net is one of the biggest Korean community site, but Adguard's not blocking ad's in here. 
I use Both Browser and Windows version, but nothing works. 
Ad's usually pop out about Coupang, which site that has a reputation for bad advertising.
It appears that the site operator is using the Anti-guard service. I would appreciate it if you could take care of it.

### Expected Behavior

Adguard block Ad's

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>
![doddod](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/153389170/142bf622-bb85-4c07-94a7-93818c6862b2)

### Additional Information

Hope you fix this problem

**Comment by alexx7311** [comment]
@DexfromAntarctica Hello! Please report this website via the extension popup. You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/

**Comment by piquark6046** [comment]
@DexfromAntarctica Please install [microShield userscript](https://github.com/List-KR/microShield). If you can understand the Korean language, please visit [here](https://community.list-kr.com/docs/AdGuard/Userscripts/microShield).
