### ISSUE TITLE
Ads on ya.ru

### ISSUE THREAD

**Issue by mov32rus** [AdguardTeam/AdguardBrowserExtension#2666]
### AdGuard Extension version

Версия 4.2.241

### Browser version

Яндекс Браузер

### OS version

Windows 10 Версия 21H2 64 Bit

### Issue Details

Здравствуйте, Ваше браузерное расширение не до конца отключает рекламу в Яндексе. Вы выпустили новое обновление часть рекламы из картинок ушло потому что когда скролишь вниз была реклама сейчас ей нет и в видео тоже есть реклама( Увижу допишу свой отзыв)
![2023-12-24_061459](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/154716563/a0c862bc-c833-4d76-9252-5a47b616abb4)
![2023-12-24_061521](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/154716563/4ade21d1-6da9-497a-9e3f-225c481cb316)
![2023-12-24_062028](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/154716563/e6550336-db94-4883-84f0-704726d9159a)

### Expected Behavior

Раньше когда я установил ваше расширение рекламы не было вообще от слово совсем не мешала выходить в сеть. 

### Screenshots

![2023-12-24_061459](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/154716563/fc2ec3e3-533d-4600-8496-606aed4649ac)
![2023-12-24_061521](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/154716563/96b06d48-f2a7-44b4-8d98-822c9501e415)
![2023-12-24_062028](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/154716563/e64780fd-fdf5-459b-a261-b74a797286eb)

### Additional Information

Надеюсь вы сделаете качественно и на века чтобы команда Яндекса не смогла сделать рекламу по другому алгоритму. Просто заблокируйте что связано с Яндекс Директ от него идёт реклама.

**Comment by alexx7311** [comment]
@mov32rus Здравствуйте! Это похоже на проблему фильтров, а не расширения. Перейдите, пожалуйста, на сайт с рекламой, откройте попап расширения AdGuard и нажмите кнопку "Сообщить о проблеме", затем следуйте инструкциям на экране. Больше информации доступно в нашей базе знаний по ссылке: https://adguard.app/kb/guides/report-website/
