### ISSUE TITLE
Logon in Blocked with Hide Referrer from third parties on in Edge

### ISSUE THREAD

**Issue by StephenBHahn** [AdguardTeam/AdguardBrowserExtension#2667]
### AdGuard Extension version

4.2.240

### Browser version

Edge

### OS version

Windows 10

### What filters do you have enabled?

AdGuard Base filter, AdGuard Chinese filter, AdGuard Dutch filter, AdGuard French filter, AdGuard German filter, AdGuard Japanese filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter

### What Stealth Mode options do you have enabled?

Remove tracking parameters, Hide your search queries, Send websites signals not to track you, Self-destruction of third-party cookies, Self-destruction of first-party cookies, Hide Referrer from third parties

### Issue Details

When I attempt to log on the Schwab.com and I have Hide Referrer from third parties in Stealth Mode on the login box is empty.  If Hide Referrer from third parties is off the expected credential text boxes appear.

### Expected Behavior

I expect the login creditional textboxes to appear.

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/154730088/6885dd73-2d0e-44db-8fc4-bed46250f17c)

</details>

### Additional Information

This behavior does not happen in Firefox 121.0.  The login screen is as expected.

**Comment by alexx7311** [comment]
The issue is related to https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2648
