### ISSUE TITLE
Youtube related issues

### ISSUE THREAD

**Issue by STICKERS94** [AdguardTeam/AdguardBrowserExtension#2673]
### AdGuard Extension version

4.2.241

### Browser version

chrome

### OS version

windows 10 pro

### What filters do you have enabled?

AdGuard Base filter

### What Stealth Mode options do you have enabled?

Block trackers, Hide your search queries, Self-destruction of third-party cookies, Remove X-Client-Data header

### Issue Details

i've been using this ad blocker for quite some time and never had any problem except for youtube, while watching videos it just never makes me see any ad which was incredible but it started to cause other issues:

1. it's a minor issue but if it's fixed it would make it perfect, when i open youtube, on the home page you start to get ads adguard just remove it and leaves the space blank, if you could fill the blank space with other videos in my recommendation it would be great.
2. now this is a major issue, while watching youtube videos adguard just makes the subscribe button disappear, there is no way to unsubscribe a channel even in the subscription page it doesn't show the subscribe button it's absurd, please fix it immediately 

i am sure it is caused by adguard because when i disabled all my extensions and enabled them one by one, it was adguard that was causing the problem please fix it.

### Expected Behavior

this ad blocker should just block ads that's all i want and just fill that empty space with the next video in the home page of youtube 
and please don't make the subscribe button disappear.

**Comment by alexx7311** [comment]
@STICKERS94 Hello! 
1. We do not redesign the layout of websites, for this purpose you can use userscripts, for example with Tampermonkey.
2. This is a [known issue](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2575). You can disable 'Help with the development of AdGuard filters' option in the Additional settings of AdGuard extension or you can wait for us to fix it.
