### ISSUE TITLE
Adguard blocked important element on chhip.de (false positive)

### ISSUE THREAD

**Issue by Dragodraki** [AdguardTeam/AdguardBrowserExtension#2676]
### Issue Details

chip.de
Example: https://www.chip.de/downloads/StartIsBack-fuer-Windows-10_81578527.html
-> On the right side the table under "Download facts" provides information about the download. Currently it gets blocked by Adguard mobile ads filter and thats not satisfying since it shouldn't get blocked

### Proposed solution

Please whitelist the table element under "Download facts" for chip.de/* in your filter Adguard mobile ads

**Comment by alexx7311** [comment]
@Dragodraki Hello! Please report this website via the extension popup. You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/
