### ISSUE TITLE
Errors in the console when using 'Self-destruction of first-party cookies' option

### ISSUE THREAD

**Issue by alexx7311** [AdguardTeam/AdguardBrowserExtension#2683]
### AdGuard Extension version

4.2.241

### Browser version

Chrome 121

### OS version

Windows 11

### What filters do you have enabled?

AdGuard Base filter

### What Stealth Mode options do you have enabled?

Self-destruction of first-party cookies

### Issue Details

STR:
1. Enable 'Self-destruction of first-party cookies'
2. Open the extension's background page
3. Open the console
4. Go to dzen.ru and browse for 2-3 minutes

<details>
  <summary>Screenshot</summary>

  ![Screenshot](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/114913601/474d0fd4-8d0a-46b6-9475-fa2b58cca100)

</details>

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by slavaleleka** [comment]
fixed in v4.3.53
