### ISSUE TITLE
YouTube doesn't work when AdGuard is enabled

### ISSUE THREAD

**Issue by eddyflycatcher** [AdguardTeam/AdguardBrowserExtension#2688]
### AdGuard Extension version

AdGuard Browser uitbreiding Versie 4.2.241 TSWebExtension v1.0.5 TSUrlFilter v2.2.8 Scriptlets v1.9.101 ExtendedCss v2.0.56

### Browser version

Chrome 120

### OS version

windows 10

### What filters do you have enabled?

AdGuard Base filter

### What Stealth Mode options do you have enabled?

Block trackers

### Issue Details

Youtube will not work unless I disable Adguard

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>
![-2024-jan-14-001](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/156576364/f7166fd7-2734-4b65-9687-39411cc8bef0)

**Comment by alexx7311** [comment]
@eddyflycatcher Hello! Please describe the problem in as much detail as possible, reproduce the problem and take a screenshot.
In the screenshot you sent, we can see that YouTube is working with AdGuard enabled.

**Comment by krystian3w** [comment]
Page can be Frozen after pause or use right click menu.

Cat and mouse gaming with Google.

**Comment by flyingbug2** [comment]
MS Edge browser also has the same problem today. Seems Google has never been stopping trying to block AD plug-in since last year.

**Comment by alexx7311** [comment]
@eddyflycatcher @krystian3w @flyingbug2 Does updating filters and clearing cookies solve the problem?
We have recently released a beta version of the extension with differential filter updates, you can test if the problem persists on it.
Link: https://github.com/AdguardTeam/AdguardBrowserExtension/releases/tag/v4.3.4-beta

**Comment by flyingbug2** [comment]
Thanks a lot! beta version update works!
Henry
