### ISSUE TITLE
Adguard interface suddenly is blank. No method to activate or deactivate.

### ISSUE THREAD

**Issue by Templar01** [AdguardTeam/AdguardBrowserExtension#2689]
### AdGuard version

4.2.208

### Browser version

1.51.110 Chromium: 113.0.5672.77 (Official Build) (64-bit) 

### OS version

Windows 10 -- 10.0.19041.3570

### What filters do you have enabled?

AdGuard Base filter

### What Stealth Mode options do you have enabled?

Hide your search queries

### Issue Details

I already have a remedy and that is to simply rip and replace, however, I will lose almost a years worth of test and research data if I do. I was hoping more for a remedy which didn't involve me losing all my work. Thanks in Advance

We have a before and after scenario that cannot be explained. I'm hoping someone will be able to explain why this has happened and suggest a remedy. As stated, I already have the fix but that's akin to demolishing the house when all I want to do is fix the door. 😉

I have a test bed for which I do not want to change or update Adguard since it will change my test conditions. To ensure this, I have all DNS traffic going through a PiHole DNS Hole server specifically to ensure that no updates to the browser or Adguard are performed without expressed permission for this platform under stets. This scenario has been stable for 18 months and Adguard and Brave browser has been frozen for the last six. 

Here are the conditions:

1. Adguard has been frozen for six months.
2. Brave Browser has been frozen for six months.
3. Suddenly, the Adguard menu is blank. See image.![image](https://github.com/AdguardTeam/AdguardForWindows/assets/49827456/edc3a61e-a4c3-4fd3-a857-15d7966c3f42)
4. Right-click menus are also incapacitated.
5. Malware checks show nothing and other browsers such as Chrome are not affected.
6. Other profiles of the same browser are also unaffected.
7. Isolating the extension by disabling all other extensions does nothing.
8. Loading Adguard into a new browser profile brings back full function. In order to removed any variable, the second instance of adguard was using exported settings from the non-working instance. See attached 
![image](https://github.com/AdguardTeam/AdguardForWindows/assets/49827456/4e51c9dc-5ca0-490b-9824-1befb38aca89)

### Actual Behavior

Adguard interface is blank.

### Expected Behavior

Adguard interface should not be blank

### Screenshots

![image](https://github.com/AdguardTeam/AdguardForWindows/assets/49827456/d068ee20-5884-4abd-9ddb-b28386203992)

**Comment by alexx7311** [comment]
@Templar01 Hello! We haven't been able to reproduce the problem. The problem may be related to your browser settings. Have you tried restoring the settings to default?

**Comment by sam59** [comment]
Hello,
I had the same bug on Firefox vs 122 and Adguard 4.2.241, the extension was not filled nothing.
I reset the parameters and always the same bug.
I uninstalled and reinstalled Adguard and there, it was good, but there are always bugs.
The filters deactivate themselves in the parameters, I had to activate them several times, unfortunately some refuse to remain active like the filters "Online Malicious Url Blockist", "List Nocoin filters", "Filter adguard tracer of URL".
The "Check update" button does not work.

**Comment by JackTheBill** [comment]
The same problem in Opera (104-108) on Kubuntu, on some tabs the extension works, on others it doesn’t
![Screenshot_20240307_143245](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/94058259/05ef32b6-e9e3-4777-aa69-9917e727cb5b)

**Comment by alexx7311** [comment]
@JackTheBill What version of Kubuntu and extension version are you using? What websites are you experiencing the problem on?

**Comment by alexx7311** [comment]
@JackTheBill We'll close the issue for now. If the problem still reproduces, please leave a comment.
