### ISSUE TITLE
The option to change theme does not work in Opera GX

### ISSUE THREAD

**Issue by Babosvaciji** [AdguardTeam/AdguardBrowserExtension#2691]
### AdGuard Extension version

lastest version

### Browser version

Opera GX

### OS version

Windows 11

### Issue Details

i have put a theme on dark mode and does not change, the white theme remains

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by alexx7311** [comment]
@Babosvaciji Hello! We couldn't reproduce the problem. Please disable all other extensions, reinstall AdGuard and check if the problem persists.

**Comment by alexx7311** [comment]
@Babosvaciji We'll close the issue for now. Please leave a comment if you would like us to continue exploring this issue.
