### ISSUE TITLE
Adguard extension crashes

### ISSUE THREAD

**Issue by ole-frat** [AdguardTeam/AdguardBrowserExtension#2699]
### AdGuard Extension version

4.3.10

### Browser version

Vivaldi 6.5.3206.57 (Stable channel) stable (64-bit) 

### OS version

Manjaro 23.1.3 Vulcan

### What filters do you have enabled?

AdGuard Base filter, AdGuard Russian filter, Fanboy's Annoyances, Fanboy's Social Blocking List, Adblock Warning Removal List, Online Malicious URL Blocklist, RU AdList - Counters, Fanboy's Enhanced Tracking List, I don't care about cookies, NoCoin Filter List

### What Stealth Mode options do you have enabled?

Block trackers, Hide your search queries, Send websites signals not to track you

### Issue Details

Extension crushes every now and then after routine update. On previous version everything worked alright.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>
![2024-01-28-160314_1280x800_scrot](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/157974970/3d14cb1c-7a9e-4fb2-8870-7491f736bd14)
![2024-01-28-161024_1280x800_scrot](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/157974970/f3b407ff-11af-4f1d-9be9-647cf3dcd572)

**Comment by alexx7311** [comment]
@ole-frat Hello! The issue is most likely connected to the memory leak problem we have found. You can check if the problem persists on the 4.3.26 beta when it comes out.
