### ISSUE TITLE
Adguard  firefox extension crashes

### ISSUE THREAD

**Issue by sam59** [AdguardTeam/AdguardBrowserExtension#2700]
### AdGuard Extension version

4.2.241

### Browser version

firefox 122.0

### OS version

Windows 10 22H2

### What filters do you have enabled?

Others

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters, Hide your search queries, Self-destruction of third-party cookies, Hide Referrer from third parties, Disable WebRTC

### Issue Details

Hello,
The extension is empty and nothing is blocked by Adguard while in the parameters the apparently active filters and rules.
I reset the parameters and always the same bug.
Uninstallation and reinstallation temporarily solves the problem, but then returns.
The filters deactivate themselves in the parameters, I had to activate them several times, unfortunately some refuse to remain active like the filters "Online Malicious Url Blockist", "List Nocoin filters", "Filter adguard tracer of URL".
The "Check update" button does not work.

### Screenshots

<details><summary>Screenshot 1:</summary>

![adguardbug](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/26506372/321ffeed-6bb4-47a7-9f47-2da277f09f20)

![adguardbug2](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/26506372/b11033af-8b2b-4a0a-a9c0-c6a15c7a89d7)

</details>

**Comment by alexx7311** [comment]
@sam59 Hello! What steps do you take to reproduce the problem?

**Comment by zzebrum** [comment]
@sam59, and please update to the latest version: https://github.com/AdguardTeam/AdguardBrowserExtension/releases/tag/v4.3.13

**Comment by sam59** [comment]
@zzebrum, Updated, but still the same problem, I will reset Firefox, if no change, I will stop there and go to Ublock Origin.

**Comment by sam59** [comment]
I reset Firefox and the problem seems to be solved, a Maj of Firefox had to break something.
The filters are now active, and the button to check the updates is functional.
