### ISSUE TITLE
Extension completely broken

### ISSUE THREAD

**Issue by Jazun** [AdguardTeam/AdguardBrowserExtension#2703]
### AdGuard Extension version

AdGuard Browser extension Version 4.2.241

### Browser version

Microsoft Edge 121.0.2277.98 (Official build) (64-bit)

### OS version

Windows 11 Home Version 10.0.22621 Build 22621

### Issue Details

I don't know what happened. It just randomly stopped working. Clicking "Block ads on this website" doesn't visually do anything. The report an issue button also does nothing. When I try to reset the settings, it gives me an error. Updating the filters also gives me an error. I've tried restarting my browser, disabling and re-enabling the extension, restarting my computer.

### Expected Behavior

I expect it to work normally but the protection button just doesn't appear.

### Screenshots

<details><summary>Screenshot 1:</summary>
![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/59619806/4ed9f671-2d6e-430b-b259-a99d53d27dff)

</details>

**Comment by zzebrum** [comment]
@Jazun please, update to the latest version and check if the problem persists: https://github.com/AdguardTeam/AdguardBrowserExtension/releases/tag/v4.3.13
