### ISSUE TITLE
custom ad blocking is not work

### ISSUE THREAD

**Issue by qarthadsht** [AdguardTeam/AdguardBrowserExtension#2704]
### AdGuard Extension version

버전 4.3.13

### Browser version

opera 106.0.4998.70

### OS version

windows 11

### What filters do you have enabled?

AdGuard Base filter

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters, Hide your search queries, Send websites signals not to track you, Self-destruction of third-party cookies, Hide Referrer from third parties

### Issue Details

Custom ad blocking has been broken since this update. The default blocker still works to some extent.

**Comment by 105th** [comment]
@qarthadsht published hotfixed version 4.3.14, already available in Opera store.
Please update and let us know in new issues if problem is still there
