### ISSUE TITLE
Cosmetic rules do not work on all websites recently

### ISSUE THREAD

**Issue by RossWang** [AdguardTeam/AdguardBrowserExtension#2705]
### AdGuard Extension version

4.3.13

### Browser version

Opera

### OS version

106.0.4998.70

### Issue Details

Including all the custom rules.

Website blocking rule like `||example.com^$document` is also broken for a long time.

### Expected Behavior

Other Ad Blocker works fine on Opera.

**Comment by 105th** [comment]
@RossWang published hotfixed version 4.3.14, already available in Opera store.
Please update and let us know in new issues if problem is still there
