### ISSUE TITLE
Extension settings are reset after a few minutes

### ISSUE THREAD

**Issue by boganiLuca** [AdguardTeam/AdguardBrowserExtension#2706]
### AdGuard Extension version

Versione 4.2.241

### Browser version

Firefox 122.0

### OS version

Windows 10 22H2

### What filters do you have enabled?

No filters

### Issue Details

The extension settings are reset every few minutes. I noticed this after having a lots of pop-ups from the extension (see [here](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2702)) and entered settings in order to see if there was something I could do about the pop-ups: I tried changing something, saw no changes, then re-entered settings and found them all unchanged. I kept trying, and every time my changes were undone: I then exported my settings in a file (attached), and I tried also by importing them, but they keep getting reverted to the original settings (probably the default ones).

My two cents: the settings are somehow getting reset, this triggers the update of the filters, and this causes also the pop-up notification to appear.

[20240205_183702_adg_ext_settings_4.2.241.json](https://github.com/AdguardTeam/AdguardBrowserExtension/files/14178212/20240205_183702_adg_ext_settings_4.2.241.json)

### Expected Behavior

The settings should not be reverted every few minutes.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

The only other extension installed is DownThemAll

**Comment by zero77995** [comment]
very annoying, removed this ext.

**Comment by Ericli0708** [comment]
I have try disable that auto filter setting, but yea it will reset itself. Please fix this thx.

**Comment by maximtop** [comment]
Hi, guys,

Can someone help us understand why this issue is occurring? Everything appears to be working as expected on our end. Please contact me at m.topciu@adguard.com, and we'll try to figure out why this is happening. It might be necessary to connect to your computer to investigate further.

**Comment by halcyforn** [comment]
i found something. probably firefox update 121 broke something in extension but delete extension, close firefox, open firefox and reinstall extension repair this bug, thats why it cant be recreated simply reinstall repair it.

**Comment by maximtop** [comment]
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2663#issuecomment-1980982715
