### ISSUE TITLE
Rejecte website eu.puma.com

### ISSUE THREAD

**Issue by Dragodraki** [AdguardTeam/AdguardBrowserExtension#2709]
### AdGuard Extension version

4.3.13

### Browser version

Firefox 115.7.0esr (64-Bit)

### OS version

Windows 11 Pro 64-Bit

### What filters do you have enabled?

AdGuard Tracking Protection filter

### What Stealth Mode options do you have enabled?

Block trackers, Hide your search queries, Send websites signals not to track you, Hide Referrer from third parties

### Issue Details

When trying to access https://eu.puma.com or one of its sub-pages, it says: 

Fehler: Umleitungsfehler
Beim Verbinden mit eu.puma.com trat ein Fehler auf.
Dieses Problem kann manchmal auftreten, wenn Cookies deaktiviert oder abgelehnt werden.

The error only happends if Adguard Tracking Protection filter is enabled. As soon I turn it off and reload the website, it works as intended. But if I turn the filter on again, delete the site cache and reload, it fails like before. So it has to be a problem related to Adguard filter or how the website tracks user profile.

### Expected Behavior

The website should load its content with Adguard Tracking Protection filter enabled.

### Screenshots

<details><summary>Screenshot 1:</summary>

![grafik](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/76787321/da93cd62-29d1-4edc-af4a-5db776649814)

</details>

**Comment by maximtop** [comment]
seems like this issue is related to the filters
please report it via report an issue button in the extension
https://uploads.adguard.org/Image_2024-02-12_07-51-11.png

**Comment by Dragodraki** [comment]
I put much effort to described the problem here. Not very nice to tell me using another method after that, escpecially because your project on Github has an custom bug report form extra for this type of issues.

Additonally I posted it via "report an issue" button like you said, but if you wouldn't like to support Github issues anymore, you should disable the issue feature completely and redirect to https://reports.adguard.com/de/new_issue.html inside Githubs readme.txt

**Comment by maximtop** [comment]
I understand your concerns, and I acknowledge the effort you've put into describing the problem. However, this repository is intended for technical issues related to the extension itself. From your description, it appears that the issue is related to the filters. The team responsible for writing or troubleshooting filter-related issues may have specific questions, which is why I recommended using the designated reporting method. This approach helps streamline the process and ensures that your issue is addressed by the appropriate team.

**Comment by Dragodraki** [comment]
First of all: Thanks for helping people here and I can totally understand why you have to categorize.
Like I said, in this case you should disable the custom form on Github issues, as there it asks explicit which filters the user have enabled. Plus, and this is seems more efficient, you should leave a big note inside readme.txt on which URL users should report which kind of problem, if you not want to see all of them in Githubs issues. All bigger addon developers do so.

**Comment by maximtop** [comment]
All the information you're referencing is detailed in the README section of our GitHub repository:
https://github.com/AdguardTeam/AdguardBrowserExtension?tab=readme#reporting-issues

This section points to the filters repository and explains how to report issues as well.

**Comment by Dragodraki** [comment]
Ok, thats my fault then - I didn't read this section carefully enough. Though, issues on Github are a standard today. Maybe you can advise users in issues form on Github to better visit your website about filter problems (for such dummies like me).
