### ISSUE TITLE
Top part of some symbols gets 'cut' when you look at the rule-to-create in element blocker

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardBrowserExtension#271]
Screenshot: http://radikal.ru/fp/3ec5c4dc3cc44475b99381ba22ccb08b

Wasn't able to reproduce. User has Linux and Yandex.Browser 16.6.0.6383 beta, bug doesn't depend on the website.

Original thread: https://forum.adguard.com/index.php?threads/11187/

**Comment by ameshkov** [comment]
Will be solved after redesign.
