### ISSUE TITLE
Can't open images on copilot drawing website

### ISSUE THREAD

**Issue by rjzjs** [AdguardTeam/AdguardBrowserExtension#2710]
### AdGuard Extension version

4.3.13

### Browser version

edge

### OS version

windows11

### What filters do you have enabled?

AdGuard Base filter, AdGuard Chinese filter, AdGuard Tracking Protection filter, AdGuard Annoyances filter

### Issue Details

adguard intercepted copilot's drawing website,i can't open images unless i close adguard

### Expected Behavior

don' intercept Microsoft designer

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

https://github.com/AdguardTeam/AdguardBrowserExtension/assets/157266132/3e3df2af-af2f-4121-a972-2a7ae9910d27

https://github.com/AdguardTeam/AdguardBrowserExtension/assets/157266132/4e489a42-2900-4d92-8c99-3949010dd32b

### Additional Information

.

**Comment by alexx7311** [comment]
@rjzjs Hello! Hello! Please report this website via the extension popup. You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/
