### ISSUE TITLE
[Firefox for Android] Fix custom filter adding modal

### ISSUE THREAD

**Issue by VladisLoveZh** [AdguardTeam/AdguardBrowserExtension#2715]
### AdGuard Extension version

4.3.12

### Browser version

Firefox 121.0.1.

### OS version

Android 10\ EMUI 12.0.0

### What filters do you have enabled?

AdGuard Base filter

### What Stealth Mode options do you have enabled?

Block trackers

### Issue Details

Current layout in 'Filters'>'Custom'>‘add custom filter'  in AdGuard Browser extension for Android' does not fit a screen in vertical mode. 
’Trusted' check-box can't be seen unless in tablet mode

### Expected Behavior

A correct layout thus all elements fits a screen as it should be. 

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/103937301/b02532eb-cf75-4d05-a3a5-2e1ec181872a)
 
![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/103937301/b745d50d-1307-47e0-a8d5-021fc4b55e54)
![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/103937301/f86196af-aed3-4252-b9b8-c9ea00e5263a)

</details>

**Comment by slavaleleka** [comment]
duplicate: https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2697
