### ISSUE TITLE
Custom Rules Not Working

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardBrowserExtension#2719]
### AdGuard Extension version

4.3.13

### Browser version

Edge Version 121.0.2277.128 (64-bit)

### OS version

Windows 11 Pro (23H2)

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, AdGuard DNS filter, Web Annoyances Ultralist, Adblock Warning Removal List, Online Malicious URL Blocklist, NoCoin Filter List, Others

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters, Hide your search queries, Send websites signals not to track you, Self-destruction of third-party cookies, Hide Referrer from third parties

### Issue Details

Although, a custom Filtering Rule whose syntax is supported by AdGuard is added via a URL, the filter rules are not applied and the requests to the domains are not blocked.

I added the following Custom Filter via this URL:
[https://[raw.githubusercontent.com/craiu/mobiletrackers/master/list-ABP.txt](https://raw.githubusercontent.com/craiu/mobiletrackers/master/list-ABP.txt)](url)

As you can see the rules follow the AdGuard syntax:

||example.org^

Still after updating the filters, connection to the domains is not blocked.

Example:

There is a rule added in the list:
||playgoog1e.com^

When I try to open **playgoog1e.com**, it opens the page instead of blocking it.

This is not observed in uBlock Origin.

 

### Expected Behavior

Supported custom filters added via URL should be applied and connections to the domains should be blocked.

### Screenshots

![Custom Filter 1](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/6959116/b74e1cdd-d34a-45d9-9f06-96722c704618)
![Web page Opens](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/6959116/928b78d2-116e-49b0-a339-67d59799222e)

**Comment by Nzzyme** [comment]
Did you get a chance to check this?

**Comment by alexx7311** [comment]
@Nzzyme Hello! We have a different syntax than uBlock Origin. To block the example.org domain you can use the `||example.org^$document` rule. 

Without the `$document` modifier, the rule will not work. You can learn more from our Knowledge Base at https://github.com/AdguardTeam/AdguardKnowledgeBase/blob/master/01.general/02.how-to-create-your-own-ad-filters/docs.en.md

**Comment by Nzzyme** [comment]
> @Nzzyme Hello! We have a different syntax than uBlock Origin. To block the example.org domain you can use the `||example.org^$document` rule.
> 
> Without the `$document` modifier, the rule will not work. You can learn more from our Knowledge Base at https://github.com/AdguardTeam/AdguardKnowledgeBase/blob/master/01.general/02.how-to-create-your-own-ad-filters/docs.en.md

I checked the syntax on AG website and found this:

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/6959116/29141388-84cc-4c65-993e-f98ebbaea7d9)

**Comment by alexx7311** [comment]
@Nzzyme This rule blocks the request made to example.org, not the domain itself. Our rules by default do not work for the address that is typed into the search box, so the $document modifier is mandatory in such cases. But you are right, such text can be misleading, we'll try to improve it.

Please take a look at this https://github.com/AdguardTeam/AdguardKnowledgeBase/blob/master/01.general/02.how-to-create-your-own-ad-filters/docs.en.md#document

**Comment by Nzzyme** [comment]
![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/6959116/74282aef-32fe-4411-8484-d7b80a895c67)

https://github.com/hagezi/dns-blocklists?tab=readme-ov-file#tif

Why is AG listed then in the supported list?
