### ISSUE TITLE
http://onlinemoviewatchs.site/play/ stopping adblockers

### ISSUE THREAD

**Issue by jakop345** [AdguardTeam/AdguardBrowserExtension#272]
http://onlinemoviewatchs.site/play/ is stopping adblockers including adguard,this time i am sure.
Screenshot below:
![image](https://cloud.githubusercontent.com/assets/15250559/16175272/2d6934c2-3604-11e6-9670-9d254242b1a6.png)

**Comment by ameshkov** [comment]
Wrong repo, moved to AdguardFilters:
https://github.com/AdguardTeam/AdguardFilters/issues/2374
