### ISSUE TITLE
AdGuard suddenly stops to prevent YouTube add

### ISSUE THREAD

**Issue by EHMilon** [AdguardTeam/AdguardBrowserExtension#2722]
### AdGuard Extension version

4.3.13

### Browser version

Microsoft Edge Version 121.0.2277.128 (Official build) (64-bit)

### OS version

Windows 11

### What filters do you have enabled?

No filters

### Issue Details

AdGuard extension fail to block YouTube adds. Suddenly I found this issue. I reset settings not work, I uninstall and reinstall still it's not working.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by alexx7311** [comment]
@EHMilon Hello! Please report this website via the extension popup. You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/
