### ISSUE TITLE
Issue on blocking specific paths.

### ISSUE THREAD

**Issue by Anupparajuli01** [AdguardTeam/AdguardBrowserExtension#2724]
### AdGuard Extension version

Version 4.3.13

### Browser version

Firefox 123.0

### OS version

Mac Sonoma 14.2.1

### What filters do you have enabled?

AdGuard Base filter

### What Stealth Mode options do you have enabled?

Block trackers

### Issue Details

I am not able to block specific paths from a website. For example, I wanted to block (youtube.com/shorts/*). I want to block everything from YouTube that has path shorts and any other sub-path from  youtube.com/shorts. 

### Expected Behavior

The youtube.com/shorts/*   plays normally. 

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by alexx7311** [comment]
@Anupparajuli01 To learn how to create filters, you can refer to our knowledge base at https://adguard.info/kb/general/ad-filtering/create-own-filters/

For specifically blocking YouTube shorts, you may find it helpful to read about [Element hiding rules](https://adguard.info/kb/general/ad-filtering/create-own-filters/#cosmetic-elemhide-rules) and [Extended CSS selectors](https://adguard.info/kb/general/ad-filtering/create-own-filters/#extended-css-selectors)

You can also use YouTube Redux which is totally compatible with AdGuard extension.
