### ISSUE TITLE
strange behavior,no interception

### ISSUE THREAD

**Issue by tch1121** [AdguardTeam/AdguardBrowserExtension#2725]
https://sleazyfork.org/zh-CN/scripts?sort=updated

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/89089119/224c2a0b-4b43-4e2a-ab9f-143a14c381cd)

**Comment by alexx7311** [comment]
@tch1121 Hello! Could you export the extension settings for us? Please also specify the extension and browser version.

**Comment by tch1121** [comment]
{
  "protocol-version": "2.0",
  "general-settings": {
    "allow-acceptable-ads": false,
    "show-blocked-ads-count": false,
    "autodetect-filters": true,
    "safebrowsing-enabled": true,
    "filters-update-period": -1,
    "appearance-theme": "system"
  },
  "extension-specific-settings": {
    "use-optimized-filters": false,
    "collect-hits-count": false,
    "show-context-menu": true,
    "show-info-about-adguard": true,
    "show-app-updated-info": true,
    "hide-rate-adguard": false,
    "user-rules-editor-wrap": false
  },
  "filters": {
    "enabled-filters": [
      2,
      3,
      4,
      7,
      18,
      19,
      22,
      104,
      122,
      207,
      208,
      224,
      229,
      242
    ],
    "enabled-groups": [
      0,
      1,
      2,
      3,
      4,
      5,
      6,
      7
    ],
    "custom-filters": [],
    "user-filter": {
      "enabled": true,
      "rules": "",
      "disabled-rules": ""
    },
    "allowlist": {
      "enabled": true,
      "inverted": false,
      "domains": [],
      "inverted-domains": []
    }
  },
  "stealth": {
    "stealth-disable-stealth-mode": true,
    "stealth-hide-referrer": true,
    "stealth-hide-search-queries": true,
    "stealth-send-do-not-track": true,
    "stealth-block-webrtc": false,
    "stealth-remove-x-client": true,
    "stealth-block-third-party-cookies": true,
    "stealth-block-third-party-cookies-time": 2880,
    "stealth-block-first-party-cookies": false,
    "stealth-block-first-party-cookies-time": 4320,
    "block-known-trackers": true,
    "strip-tracking-parameters": false
  }
}

**Comment by tch1121** [comment]
Maybe it’s not Adguard’s problem
It’s the same thing when I use uBlock
![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/89089119/8e98113f-8106-42ea-9f4e-18b0b9f7c77f)

Can anyone tell me how to solve it?
