### ISSUE TITLE
websockets are broken on old versions of Chrome

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#273]
For example:
- http://www.privat24.ua/

https://forum.adguard.com/index.php?threads/adguard-%D0%B8-privat24.11219/
without extension
<details>
![image](http://imagizer.imageshack.com/img921/3608/QX3tLC.png)
</details>
with extension
<details>
![image](http://imagizer.imageshack.com/img923/776/wJtp92.png)
</details>
websocket
wss://www.privat24.ua/ws/sr
- slack.com
can't connect with enabled extension.
This issue can't be fixed by filters.

Tested on Slimjet 6.0.11.0 (based on Chromium 46.0.2490.71)
Browser:
https://mega.nz/#!AVdHXbaQ!UZDPIzpo_S17pxs2luTvXbOG39KgNHasfTEeNyiZNlU

**Comment by Alex-302** [comment]
Maybe the same issue.
Extension for Chrome 2.3.8, Chrome 51
Checked even without filters.
URL:
https://poloniex.com/exchange
Extension is enabled:
<details> 
![s](http://imagizer.imageshack.com/img921/7397/CQ8nVC.png)
![s](http://imagizer.imageshack.com/img923/6206/IpZ0l0.png)
</details>
Extension is disabled:
<details> 
![s](http://imagizer.imageshack.com/img923/4834/mcFe8o.png)
![s](http://imagizer.imageshack.com/img922/3086/yvgcpg.png)
</details>

**Comment by ameshkov** [comment]
@Mizzick please take a look at this issue, seems to be broken in new Chrome

**Comment by Mizzick** [comment]
So, any ideas how can we fix this?

**Comment by ameshkov** [comment]
Have you tested it?

**Comment by Mizzick** [comment]
`var c = window.WebSocket,
   d = document.createElement("iframe");

d.style.display = "none";
document.documentElement.appendChild(d);
if (d.contentWindow.WebSocket) {
   c = d.contentWindow.WebSocket
}
c
WebSocket() { [native code] }`

**Comment by ameshkov** [comment]
There is nothing we can do with this I guess.

This issue is about broken WebSocket, is it the same issue?

**Comment by Mizzick** [comment]
https://github.com/gorhill/uBO-WebSocket/pull/4

**Comment by ameshkov** [comment]
@Mizzick don't forget the MS Edge manifest

**Comment by Mizzick** [comment]
Yeap

**Comment by ameshkov** [comment]
So the problem with Slimjet is fixed now?

**Comment by Mizzick** [comment]
Yeap
