### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by catlikehana** [AdguardTeam/AdguardBrowserExtension#2731]
### AdGuard Extension version

4.3.13

### Browser version

Yandex Browser 24.1.3.809 (64-bit)

### OS version

Windows 11 23H2 22631.3235

### What filters do you have enabled?

AdGuard Base filter, AdGuard Chinese filter, AdGuard French filter, AdGuard German filter, AdGuard Japanese filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, EasyList Italy, Dandelion Sprout's Nordic Filters

### Issue Details

Memory leak - RAM increases exponentially in a short amount of time on a specific web page when the tab is active until it depletes and said page crashes - the page will auto reload and then do the same thing again, this will continue until the tab is closed. 

Issue also persists on Microsoft Edge & Google Chrome on the same page with fresh install of Adguard as the only extension.

The page in question:
https://www.businessinsider.com/bo-burnham-inside-all-eyes-on-me-analysis-ending-explained-2021-6?r=US&IR=T

So far it seems to be isolated to that web page, however I have not investigated beyond this so could possibly affect more than mentioned.

### Expected Behavior

To view the page normally without memory depletion and crashing.

Memory usage without the adguard extension enabled is normally around 450k, with the extension enabled the page reaches around 8 million.

### Screenshots

<details><summary>Screenshot 1:</summary>

![Untitled](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/143365829/5532bbe9-dea8-4497-bd15-b7f240eece6f)
![Untitled2](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/143365829/2d1b0476-b3f2-4a8b-9d15-db25abf895b2)
![Untitled3](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/143365829/5a59a466-0968-45e7-a8df-b5dddd0a8a09)
![Untitled5](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/143365829/87e1b278-ada9-4fc8-94ed-9b460df13d03)
![Untitled6](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/143365829/cb7fb8e8-a5a9-4187-af8c-e41e454dc526)

</details>

### Additional Information

System:
Intel Core i5 13600KF
Jginyue B760M Snow Dream
Asgard Valkyrie V5 Series 32GB DDR4 (4x8GB) 3200 
Asus Dual GTX 1070 O8G
Crucial P5 Plus 1TB

Windows 11 23H2 22631.3235
Yandex Browser 24.1.3.809 (64-bit)

Adguard Version 4.3.13
TSWebExtension v1.0.8
TSUrlFilter v2.2.9
Scriptlets v1.9.105
ExtendedCss v2.0.56

Video - https://streamable.com/wlrx86

**Comment by catlikehana** [comment]
I just switched over to the beta client as i noticed there was a memory leak fix in the release notes.
Unfortunately the issue persists but memory depletion is at a slightly slower rate than previous and the page lasts a little longer.

Version 4.3.26
TSWebExtension v1.0.15
TSUrlFilter v2.2.14
Scriptlets v1.10.1
ExtendedCss v2.0.56

![Untitled](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/143365829/40627508-ba9b-47e8-ad2a-c1b205732a5d)

**Comment by catlikehana** [comment]
I tried switching over to the adguard beta extension as i saw a note about memory leak fixes on the release notes. 
issue persists on both my main profile with multiple extensions and also any new profiles created with just adguard beta enabled.

Yandex Browser 24.1.3.809 (64-bit)
Adguard Extension Beta 4.3.26
TSWebExtension v1.0.15
TSUrlFilter v2.2.14
Scriptlets v1.10.1
ExtendedCss v2.0.56

![Untitled](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/143365829/eac05175-d01e-4e36-b2d9-1f0fa4cf34d1)

**Comment by catlikehana** [comment]
> Hi! Does the issue persist in other browsers, or is it exclusive to Yandex Browser?

It is the same in Google Chrome & Edge

![Untitled](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/143365829/f96cfc8a-9b8f-4601-a1c4-bab9b0de9352)

**Comment by catlikehana** [comment]
without adguard installed, the page displays within an expected range and without depletion - memory usage will normally increase when you scroll down as it loads more content but this will be expunged as needed whereas with adguard enabled it seems to not get cleared and instead expands until it crashes.

![Untitled2](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/143365829/de9b6d27-9113-449a-8051-cd5527b38db9)

**Comment by maximtop** [comment]
Seems like blocking certain requests on this website is causing the memory leak. Can you confirm that after adding this rule `@@||cmp.osano.com^$domain=businessinsider.com` to the user rules section, the memory leak issue does not occur?

**Comment by Alex-302** [comment]
Fixed in the AdGuard Cookies filter https://github.com/AdguardTeam/AdguardFilters/commit/d228ff4262604f673706c4da42d52d16e5a68ff7

**Comment by catlikehana** [comment]
> Seems like blocking certain requests on this website is causing the memory leak. Can you confirm that after adding this rule `@@||cmp.osano.com^$domain=businessinsider.com` to the user rules section, the memory leak issue does not occur?

This has done the trick, thank you very much
