### ISSUE TITLE
Editing Sharepoint calendars not working

### ISSUE THREAD

**Issue by zaqes** [AdguardTeam/AdguardBrowserExtension#2733]
### AdGuard Extension version

4.3.13

### Browser version

Chrome 122.0.6261.94

### OS version

macOS 14.3.1

### Issue Details

The buttons are greyed out when AdGuard extension is enabled, even if Blocking is turned off for that site.
If I disable the extension it works.

### Expected Behavior

Be able to use the Buttons.

### Screenshots

<details><summary>Screenshot 1:</summary>

<img width="301" alt="Screenshot 2024-03-05 at 15 39 13" src="https://github.com/AdguardTeam/AdguardBrowserExtension/assets/75309967/0fbfe3a1-2d17-44a7-8ac3-c4f9c6fc4825">

</details>

**Comment by alexx7311** [comment]
@zaqes Hello! Do you have the Stealth mode enabled in the extension?
Does the problem persists if you disable all modules in the extension?

**Comment by zaqes** [comment]
Looking deeper into the logs it looks like the Legitimate URL Shortener with the rule "$~ping,removeparam=lcid,domain=~rekono.si" breaks it when removing lcid from the URL even though protection is disabled for the site.

**Comment by alexx7311** [comment]
@zaqes This is not our filter. Please go to https://github.com/DandelionSprout/adfilt/issues/new?assignees=&labels=Problem+report&projects=&template=problem-report-form.yml and report this problem to the creator of Legitimate URL Shortener directly.

A rule can work with filtering turned off if it is cached by the browser. In this case you should clear cookies and check again, or open the page in browser incognito mode.

**Comment by zaqes** [comment]
I don't understand, why is it filtering a site that where protection is turned off?
