### ISSUE TITLE
The Subscribe button on YouTube is hidden

### ISSUE THREAD

**Issue by SergeyNUkolov** [AdguardTeam/AdguardBrowserExtension#2734]
### AdGuard Extension version

4.3.13

### Browser version

Yandex Browser

### OS version

Windows 10

### Issue Details

A few days ago I decided to unsubscribe from several dead channels on YouTube and noticed that the "Subscribe / Unsubscribe" button was missing. Disabling all browser extensions one by one, I discovered that this button was mistakenly hidden by Adguard.

### Screenshots

<details><summary>Adguard ON:</summary>

![2024-03-06 02-22-28 Настоящий Детектив  Russian Edition  - YouTube, группа Вкладки окна  — Яндекс Браузер](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/62967872/e8e278bb-3ff6-4ab4-a9f3-6d601b90094c)

</details>

<details><summary>Adguard OFF:</summary>

![2024-03-06 02-23-15 Настоящий Детектив  Russian Edition  - YouTube, группа Вкладки окна  — Яндекс Браузер](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/62967872/8d933448-3ec1-4115-9930-ddc63191d641)

</details>

### Additional Information

-

**Comment by alexx7311** [comment]
Dup. of https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2575

You can disable this option until we fix the problem
<details>
<summary>Details</summary>

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/8361299/06b9100f-1abf-4923-9150-8f73b4e00cc6)

</details>
