### ISSUE TITLE
The filters are rolled back to the pre-installed ones when importing settings

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#2735]
### AdGuard Extension version

4.3.29

### Browser version

Chrome 122

### OS version

Windows 10 x64

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Russian filter, AdGuard Turkish filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter

### Issue Details

1. Enable few filters
2. Check for filters update
3. Remember versions of filters
4. Export settings
5. Import settings
6. Check versions of filters

Actual behavior - versions are downgraded.

### Expected Behavior

Filters are actual (not rolled back)

**Comment by tumatanquang** [comment]
This also appears to be a bug related to the Import/Export Settings feature that I also reported at #2484.
