### ISSUE TITLE
The web page will not load after the filter update.

### ISSUE THREAD

**Issue by rnixs** [AdguardTeam/AdguardBrowserExtension#2737]
### AdGuard Extension version

Version 4.3.13

### Browser version

Chrome 122.0.6261.112 

### OS version

Mac OS Sonoma 14.2.1

### What filters do you have enabled?

AdGuard DNS filter

### Issue Details

After updating DNS Filter, the problem occurs.

### Screenshots

<details>
<summary>Issue screen</summary>
<img width="1512" alt="image" src="https://github.com/AdguardTeam/AdguardBrowserExtension/assets/81290656/1561e5a0-7299-44a3-837c-c4c35cb52de8">

<img width="1512" alt="image" src="https://github.com/AdguardTeam/AdguardBrowserExtension/assets/81290656/aefdd5e4-e74e-4084-8bd4-607c809c940c">

</details>

**Comment by piquark6046** [comment]
Please update the filters and install [microShield userscript](https://github.com/List-KR/microShield).
