### ISSUE TITLE
Delay before Adguard shows in menubar (firefox)

### ISSUE THREAD

**Issue by worldsdream** [AdguardTeam/AdguardBrowserExtension#274]
When opening firefox on Mac or Windows, and if you have Adguard in your menubar, there is a delay before it shows up there.

Does not look good, looks like it's not great integrated with Firefox (other extensions, everything is fine at load)

Can you confirm and is there a fix on the way?

Safari and Chrome are good!

**Comment by ameshkov** [comment]
I guess it's caused by the time AG need to init filters. We can't help it now. Maybe it will be better in future when we switch AG for FF to WebExtensions SDK.
