### ISSUE TITLE
Windows 11 is not properly identified when reporting an issue

### ISSUE THREAD

**Issue by alexx7311** [AdguardTeam/AdguardBrowserExtension#2740]
### AdGuard Extension version

4.3.31

### Browser version

Chrome 122

### OS version

Windows 11

### Issue Details

Windows 11 is identified as Windows 10 during an issue reporting

STR:
1) Open the popup
2) Click 'Report an issue'

<details>
  <summary>Screenshot</summary>

  ![Screenshot](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/114913601/d662f728-6b41-49bc-aa98-a922d50ab821)

</details>

### Expected Behavior

Windows 11 is reported as Windows 11

**Comment by slavaleleka** [comment]
Windows 11 should already be handled fine. the only reason it may be reported as Windows 10 is an error during the version calculation, i.e. [navigator.userAgentData.getHighEntropyValues()](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorUAData/getHighEntropyValues) execution may fail
