### ISSUE TITLE
YouTube causing memory leaks/complete system lockup.

### ISSUE THREAD

**Issue by R-StarDaCRhymeBoSS** [AdguardTeam/AdguardBrowserExtension#2742]
### AdGuard Extension version

Version 4.3.13

### Browser version

Chrome Version 122.0.6261.113 (Official Build) (64-bit)

### OS version

Windows 10

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters, Hide your search queries, Send websites signals not to track you, Self-destruction of third-party cookies, Hide Referrer from third parties, Remove X-Client-Data header

### Issue Details

While using YouTube  I get a very brief error screen before videos load, it's less than a millisecond and at random times my entire PC freezes and forces a reboot. 
This only happens while YouTube is open and feels like an intentional countermeasure against adblocking on the platform.

### Expected Behavior

I expect my computer to never freeze up from YouTube, I have a pretty powerful PC with a 1 TB NVME hard drive with 64 GB of 4000mhz ram plus a i7 8700k (no oc) and a RX 7900XTX so it's not a computing power problem.
I can play very demanding games or do anything else on Chrome besides YouTube (including watching Rumble videos) and never get any crashes or even hiccups.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

I appreciate any investigation into this issue you guys are able to do

**Comment by alexx7311** [comment]
@R-StarDaCRhymeBoSS Hello! We've fixed the memory leak problem in the latest [4.3.31 build](https://github.com/AdguardTeam/AdguardBrowserExtension/releases/tag/v4.3.31).
Please update the extension and check if the problem persists.

**Comment by alexx7311** [comment]
@R-StarDaCRhymeBoSS Does the problem still reproduce?

**Comment by mr-josh** [comment]
I'm currently running Firefox and version 4.3.14 (latest available on the mozilla add-ons store) and may be seeing the issue in YouTube music. Have taken a memory snapshot and you can see the extension using 229MiB of memory:

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/18021383/5fdf048b-e380-47d6-8e53-40b6f08219d1)

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/18021383/dbdb05aa-ac9a-4b90-a6bb-73b8992f52f5)

**Comment by alexx7311** [comment]
@mr-josh If you have Firefox, it's better to comment in https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2594
But first, please install https://github.com/AdguardTeam/AdguardBrowserExtension/releases/tag/v4.3.31-beta
where we fixed a bug causing the extension memory leak.
