### ISSUE TITLE
thingstogetme.com links close right after opening

### ISSUE THREAD

**Issue by myrrien** [AdguardTeam/AdguardBrowserExtension#2746]
### AdGuard Extension version

4.3.13

### Browser version

Chrome 122

### OS version

Windows 10

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, EasyList, EasyList Italy, EasyPrivacy, Fanboy's Annoyances, Peter Lowe's Blocklist, Adblock Warning Removal List, Online Malicious URL Blocklist, Fanboy's Anti-Facebook List, EasyList Cookie List, NoCoin Filter List, Legitimate URL Shortener, Others

### Issue Details

I have a wishlist on thingstogetme.com and when I click some wishlist links it opens and closes right after. It doesn't do this with all links. I tried to disable AdGuard for the site but the problem persists. I tried to add the following custom rule but the problem persists.
`@@||thingstogetme.com^$important,document,popup`
The problem goes away if I completely disable AdGuard from the extension list.

### Expected Behavior

When I click the first wishlist link it opens in a new tab.
I'll put here my personal wishlist link for testing, there's no personal information in there, just a list of objects. One of the affected is the Anycubic Photon Mono 2 (first item).
https://www.thingstogetme.com/1047103a97e70

**Comment by alexx7311** [comment]
@myrrien Hello! When you click on the link, the request goes to `https://www.thingstogetme.com/click/7578420ad79f6?_context=web`
then it gets redirected to `https://go.redirectingat.com/?xcust=13628495caff6a&url=https%3A%2F%2Fanycubic.it%2Fcollections%2Fstampante-3d-in-resina%2Fproducts%2Fanycubic-photon-mono-2&xs=1&sref=https%3A%2F%2Fwww.thingstogetme.com%2F1047103a97e70&id=114618X1573629`
and then redirected to `https://track.webgains.com/click.html?wgcampaignid=54264&wgprogramid=296120&clickref=114618X1573629X81b9babbdc218e16ec3c7537376ffed6&wgtarget=https%3A%2F%2Fanycubic.it%2Fcollections%2Fstampante-3d-in-resina%2Fproducts%2Fanycubic-photon-mono-2`

The last redirect is blocked by the rule `||webgains.com^$popup`
Please try to unblock webgains.com
