### ISSUE TITLE
Разделитель для фильтров

### ISSUE THREAD

**Issue by Cursone** [AdguardTeam/AdguardBrowserExtension#2748]
### Issue Details

Есть такой фильтр **RU, UA, UZ, KZ** - https://easylist-downloads.adblockplus.org/ruadlist.txt

![2024-03-17_12-21-01](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/155391717/4c56f4b5-137a-44e2-a7af-75116062367f)

![2](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/155391717/d9436ee3-f04d-4839-846d-cc1f9f5f8274)

### Proposed solution

Вот и получается, что не понятно **RU, UA, UZ, KZ** это один фильтр или несколько? Может стоит их разделять не запятой, а например в столбик для лучшего восприятия?

**Comment by Cursone** [comment]
Почти не деля прошла, но ответа так и нет. Отличное отношение у Вас к пользователям.

**Comment by zzebrum** [comment]
@Cursone 

> Может стоит их разделять не запятой, а например в столбик для лучшего восприятия?
Согласны с вами в том, что название фильтра не совсем корректное, но это сторонний фильтр, мы на него не влияем.
