### ISSUE TITLE
Filters' Stats Update Stucked at February 21, 2024 at 10:04 AM

### ISSUE THREAD

**Issue by User-8-2-2008** [AdguardTeam/AdguardBrowserExtension#2751]
### AdGuard Extension version

4.3.13

### Browser version

Firefox 123.0.1

### OS version

Windows 10

### What filters do you have enabled?

AdGuard Base filter, AdGuard German filter, AdGuard Japanese filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard DNS filter, ABPindo

### Issue Details

After trying multiple times clicking the "Check for New Updates" at the Filters page, its time status is stucked at February 21, 2024 at 10:04 AM.

### Expected Behavior

It should be updated to latest time.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by maximtop** [comment]
Hi,
could you please ask some questions?
what setting do you have here?
<img width="671" alt="image" src="https://github.com/AdguardTeam/AdguardBrowserExtension/assets/17272769/193c6947-62fe-4fd3-b935-9d5532620863">

what is visible on background page in the console, and network tab in developer tools?
https://maximtop.notion.site/How-to-export-logs-from-the-background-page-in-the-extension-fb7e2fe23cb0451ea010672ce0570929

**Comment by alexx7311** [comment]
@User-8-2-2008 Any updates?

**Comment by alexx7311** [comment]
@User-8-2-2008 Please update the extension to the newest version and leave a comment if the problem persists. We will close the issue for now.
