### ISSUE TITLE
Settings are cleared every 15 minutes

### ISSUE THREAD

**Issue by akirichua** [AdguardTeam/AdguardBrowserExtension#2755]
### AdGuard Extension version

4.3.13

### Browser version

Firefox 124.0

### OS version

Windows 10

### What filters do you have enabled?

AdGuard Base filter, AdGuard Russian filter, Bulgarian list

### Issue Details

Extension always show popups that some filter is enabled. All settings is clearing in 10-15 minutes after last save.

**Comment by alexx7311** [comment]
Dup. of #2663

**Comment by alexx7311** [comment]
@akirichua Hello! Please do the following:
1) Open the Browser console (press Ctrl + Shift + J (or Cmd + Shift + J on a Mac))
2) Choose Multiprocess mode and leave the Browser console opened
<details>
  <summary>Multiprocess mode</summary>

  ![Multiprocess mode](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/114913601/aa00993e-6eb2-4a8f-8e65-1bb1b1408ba2)

</details>

3) Follow steps 1-3 from this [instruction](https://maximtop.notion.site/How-to-export-logs-from-the-background-page-in-the-extension-fb7e2fe23cb0451ea010672ce0570929) for Firefox to open background page in the extension
4) Type each of these commands in the console of the background page:

`await browser.storage.local.get('adguard-settings');`

`await browser.storage.local.get('adguard-settings-2');`

`await browser.storage.local.set({'adguard-settings': 'test'});`

`await browser.storage.local.set({'adguard-settings-2': 'test'});`

`await browser.storage.local.remove('adguard-settings');`

`await browser.storage.local.remove('adguard-settings-2');`

5) Right click on any entry in console of the background page and click "Save All Messages to File" (as per step 4 in the [instruction above](https://maximtop.notion.site/How-to-export-logs-from-the-background-page-in-the-extension-fb7e2fe23cb0451ea010672ce0570929))
6) Go to the Events tab in Firefox at `about:telemetry#events-tab`
7) Type in "Find in Events" field "extensions.data" and take a screenshot, then "storageLocalError" and take a screenshot.

<details>
  <summary>Find in Events</summary>

  ![Find in Events](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/114913601/e488439d-4440-45db-bf8f-4f0156d763d9)

</details>

8) Navigate to the Browser console (from the step 1) and right click on any entry and click "Save All Messages to File".
9) Please attach all resulting files to the comment in this issue.

**Comment by alexx7311** [comment]
@akirichua Further discussion will be in https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2775
If you would like to help us solve the problem, please leave a comment in that issue.
