### ISSUE TITLE
Problems with rule processing (Adblock-style syntax)

### ISSUE THREAD

**Issue by yarynanowak** [AdguardTeam/AdguardBrowserExtension#2760]
### AdGuard Extension version

4.3.13

### Browser version

Firefox 123.0.1 (64-bit)

### OS version

Linux

### What filters do you have enabled?

Others

### Issue Details

When I add (`"Filters > Custom"` menu) the Ukrainian Security Filter (https://www.awwwwesome.org/data/filters/USF/adblock.txt), AdGuard does not process rules that fully comply with Adblock-style syntax.

For example, all rules from the "Domain-Based Blocklist" section of the above filter are not processed. 

Even if you manually enter the rule `||0ukr.net^` in the "User rules" menu section, it is also not processed by the extension. However, if you rewrite this rule to `||0ukr.net$document`, it is processed successfully. 

In my opinion, this is a bug, since the `||0ukr.net^` rule fully complies with the syntax and recommendations for creating rules available at: https://adguard.com/kb/general/ad-filtering/create-own-filters/

### Expected Behavior

AdGuard should process rules that fully match the Adblock syntax (for example, `||0ukr.net^`)

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by alexx7311** [comment]
@yarynanowak The rule `||0ukr.net^` blocks a request made to `0ukr.net`, but it won't block `0ukr.net` if you type that address into the search box. For the rule to work for document requests, you need the $document modifier.

We plan to improve the description in our knowledge base.

**Comment by yarynanowak** [comment]
> For the rule to work for document requests, you need the $document modifier.

Is this a feature of AdGuard rule processing? I ask because uBlock Origin and Brave process the rule in the ||0ukr.net^ format without any problems, blocking access to the document

**Comment by alexx7311** [comment]
> Is this a feature of AdGuard rule processing?

@yarynanowak Yes, that's right. Our approach is different, but it's more traditional than what uBlock Origin do.
