### ISSUE TITLE
Ads on the YouTube

### ISSUE THREAD

**Issue by Aryan0000000000** [AdguardTeam/AdguardBrowserExtension#2766]
### AdGuard Extension version

Version 4.3.31

### Browser version

Chrome 

### OS version

Windows 

### What filters do you have enabled?

AdGuard Base filter

### What Stealth Mode options do you have enabled?

Block trackers

### Issue Details

Ads are not blocking on YouTube...since today morning [ 27 March ]

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>
<img width="960" alt="image" src="https://github.com/AdguardTeam/AdguardBrowserExtension/assets/96041475/119e2d18-1120-4f48-b655-d65ae93f0b00">

**Comment by alexx7311** [comment]
@Aryan0000000000 Hello! Please report this website via the extension popup. You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/
