### ISSUE TITLE
In Firefox, AdGuard extension keeps turning off the filters so it doesn't work.

### ISSUE THREAD

**Issue by kentuckywoman2** [AdguardTeam/AdguardBrowserExtension#2767]
### AdGuard Extension version

4.3.31

### Browser version

Firefox 124.0.1 64-bit

### OS version

Windows 10

### What filters do you have enabled?

AdGuard Base filter

### What Stealth Mode options do you have enabled?
None

### Issue Details

The adquard extension shows it is enabled. But every day when I either wake up my computer from sleep or restart it, or boot it up, the extension shows it is enabled, but if I go to settings,  NOTHING is enabled. No filters, etc. So I enable the ones I want, but it keeps doing this all day long - turning off the filters. I've run my antivirus program. I downloaded both UBlock Origin and Adblocker Ultimate to see if they do the same thing, but they don't. I'd really like to keep using AdGuard Adblocker, but this is a complete puzzle to me. Someone told me it was a Firefox issue or something with AdGuard's security certificate that Firefox doesn't recognize. Please help. Or Fix it.

### Expected Behavior

I expected AdGuard to work the same way it always has done, but it's not working at all on Firefox browser. I expected the filters to stay enabled, and I can't figure out how they  get disabled, yet the extension still says it's enabled, even with every filter, etc., turned off.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by maximtop** [comment]
Hi! Thank you for reporting this issue.

We've recently identified a bug in Firefox that prevents changes to AdGuard settings. See the comment here https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2663#issuecomment-1980982715. Could you please verify if you're experiencing the same issue on your end? Here are the steps to do so:

1. Navigate to the background page. You can find instructions here: [How to export logs from the background page in the extension](https://www.notion.so/maximtop/How-to-export-logs-from-the-background-page-in-the-extension-fb7e2fe23cb0451ea010672ce0570929?pvs=4).
Please send us any errors you observe there.
2. Additionally, try to retrieve or set AdGuard settings from storage using the following command in the console:
await browser.storage.local.get('adguard-settings');
4. Check if any errors occur when executing the above command.
5. If errors do appear, could you please access the browser console and telemetry page as described in this Firefox bug report? [Firefox Bug 1885297 Comment 4](https://bugzilla.mozilla.org/show_bug.cgi?id=1885297#c4).

We're looking forward to your feedback to help us resolve this issue more effectively.

**Comment by alexx7311** [comment]
@kentuckywoman2 Hello! Further discussion will be in https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2775
If you would like to help us solve the problem, please leave a comment in that issue.

**Comment by SeDi343** [comment]
Have the same problem
![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/3628936/f6de720b-3030-404c-b9f6-46196af89e61)

**Comment by neferer** [comment]
![resim](https://github.com/user-attachments/assets/fbaa67c0-da9a-4bd9-b408-659207b65e48)
AdGuard filters in the Firefox disabling themselves.

**Comment by alexx7311** [comment]
@neferer This is a Firefox bug. Please follow instructions from https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2775#issuecomment-2036577871 and leave a comment with results in https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2775

It would help us solve this problem faster.
