### ISSUE TITLE
AdGuard extension doesn't install

### ISSUE THREAD

**Issue by xieruidong521** [AdguardTeam/AdguardBrowserExtension#2769]
### AdGuard Extension version

版本 4.3.35

### Browser version

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0

### OS version

win10 x64

### Issue Details

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/28883857/69570527-22c2-4838-9664-5003f3869e3d)

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by alexx7311** [comment]
@xieruidong521 Hello! Looks like bug https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2761, where the extension can't install when filters.js is unavailable.
Please use [the instructions](https://maximtop.notion.site/How-to-export-logs-from-the-background-page-in-the-extension-fb7e2fe23cb0451ea010672ce0570929) to collect logs from the console and attach the log file to the comment.

**Comment by xieruidong521** [comment]
I am using China Mobile's network. I checked the console logs and the requests were very slow. Then, I switched to China Telecom's network, uninstalled and reinstalled the plugin, and the result was successful. I estimate it is a network problem. In China, the network is complex

**Comment by alexx7311** [comment]
@xieruidong521 We have a new version of the extension coming out within a week, it will be possible to install it even with network problems. If the problem recurs, you can try installing the new version.
