### ISSUE TITLE
Ads on dailyvoice.com website

### ISSUE THREAD

**Issue by grapephil** [AdguardTeam/AdguardBrowserExtension#2772]
### AdGuard Extension version

4.1.22

### Browser version

chrome

### OS version

ubuntu

### What filters do you have enabled?

AdGuard Base filter

### Issue Details

https://dailyvoice.com/new-jersey/englewood/tenafly-bank-isnt-fooled-by-id-theft-police-say/

### Expected Behavior

no ads

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by alexx7311** [comment]
@grapephil Hello! Please report this website via the extension popup. You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/
