### ISSUE TITLE
$removeparam does not work with regular expressions

### ISSUE THREAD

**Issue by alexx7311** [AdguardTeam/AdguardBrowserExtension#2778]
### AdGuard Extension version

4.3.44

### Browser version

Chrome 122

### OS version

Windows 11

### Issue Details

STR:
1) Go to extensions settings
2) Go to User rules section
3) Add the following to the user rules:
```
||example.org^$removeparam=/^param\d*3\$/
||example.org$removeparam=/^ss\$/
```
4) Open https://example.org/?param123&param1234&param456&ss&sss in browser incognito mode

### Expected Behavior

These rules should remove the `param123` and `ss` parameters

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by gorhill** [comment]
When using a regex, the parameters are normalized to `name=value` and the regex is tested against the normalized form, so for your regex to work they need to be crafted as follow:

    ||example.org^$removeparam=/^param\d*3=/
    ||example.org$removeparam=/^ss=/

**Comment by alexx7311** [comment]
@gorhill Hello and thanks!
