### ISSUE TITLE
Style filter is applied, but scriptlet filter is not in Firefox

### ISSUE THREAD

**Issue by zenstorage** [AdguardTeam/AdguardBrowserExtension#2782]
### AdGuard Extension version

4.3.35

### Browser version

Chrome 123 / Firefox 124

### OS version

Windows 11

### What filters do you have enabled?

No filters

### Issue Details

In these filters:
```
twitter.com##+js(json-prune-xhr-response, data.user.result.timeline_v2.timeline.instructions.[].entries.[].content.items.[].item.itemContent.tweet_results.result.legacy.possibly_sensitive, , propsToMatch, url:/UserMedia)
twitter.com##+js(rmnt, #text, /./)
twitter.com##div:style(border: 1px solid red !important;)
```
The style filter is applied in Chrome and FIrefox, but the scriptlet filter is not applied in FIrefox, I have already tried using the Adguard and ABP syntax but it has the same result,I let something go?

### Expected Behavior

Scriptlet filter to be applied

### Screenshots

All filters working in Chrome:

<details><summary>chrome:</summary>

![chrome](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/82182314/34613730-8202-4a41-8534-9f76cf1d58c7)

</details>

Only style filter working in Firefox:

<details><summary>firefox:</summary>

![firefox](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/82182314/cc088406-c00d-41ec-84b8-86e96d954273)
</details>

**Comment by slavaleleka** [comment]
`rmnt` scriptlet should work fine

but `json-prune-xhr-response` is not available in the extension v4.3.35, it was added in [Scriptlets v1.10.25](https://github.com/AdguardTeam/Scriptlets/blob/master/CHANGELOG.md) and available in AdGuard Browser extension [v4.3.46](https://github.com/AdguardTeam/AdguardBrowserExtension/releases/tag/v4.3.46)

**Comment by maximtop** [comment]
Thanks, @AdamWr

Indeed, it seems like the problem is with the CSP, since scriptlet rules are working in Firefox—take example.org, for example.

> Any chance for prioritizing this task? - #1733

I've moved it to v4.4.

**Comment by zenstorage** [comment]
I tried removing the Content-Security-Policy headers from the site and it seems to resolve it, some adguard change to remove just to apply the scriptlets?
