### ISSUE TITLE
Malware alert page appears frequently during browsing

### ISSUE THREAD

**Issue by sil71sil** [AdguardTeam/AdguardBrowserExtension#2784]
### AdGuard Extension version

Extensión de navegador AdGuard Versión 4.3.46 

### Browser version

Chromium Versión 109.0.5414.120 (Build oficial) (32 bits)

### OS version

Windows 7

### What filters do you have enabled?

AdGuard Base filter, AdGuard Spanish/Portuguese filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, AdGuard DNS filter, Filter unblocking search ads and self-promotion, EasyList, EasyPrivacy, AdBlockID, Fanboy's Annoyances, Fanboy's Social Blocking List, Web Annoyances Ultralist, Peter Lowe's Blocklist, Xfiles, Adblock Warning Removal List, Online Malicious URL Blocklist, Fanboy's Enhanced Tracking List, Official Polish filters for AdBlock, uBlock Origin & AdGuard, CJX's Annoyances List, Fanboy's Anti-Facebook List, I don't care about cookies, EasyList Spanish, Fanboy's Anti-thirdparty Fonts, EasyList Cookie List, NoCoin Filter List, AlleBlock, Dandelion Sprout's Nordic Filters, Dandelion Sprout's Annoyances List, Others

### Issue Details

La extensión funciona muy bien. Bloquea todo lo seleccionado. Estoy muy agradecida por el excelente trabajo que hacen.
Pero cuando trabaja activamente el bloqueo de sitio o publicidades y elementos molestos, siempre abre una nueva pestaña que informa que  '' x ''  elemento o sitio ha sido bloqueado. 
¿Hay alguna forma de ocultar estas notificaciones de AdGuard?   Cuando visito sitios con mucha publicidad yo tengo que cerrar muchas pestañas, algunas veces incluso 20 veces, que informan del bloqueo.
No me malentienda, yo amo la extensión, pero es muy molesto cerrar todo el tiempo las tabs de notificación. No encuentro en la configuración la forma de desactivar estas notificaciones. 
¿Pueden brindar ayuda con este asunto, por favor? 
Desde Argentina, muchas gracias.
Silvia

### Expected Behavior

No más notificaciones. 

### Screenshots

![AdG 1](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/106161247/9740bafd-2d7d-4f10-8ffb-d9b909c254cd)

**Comment by alexx7311** [comment]
@sil71sil Hello! Unfortunately, if you disable the Malware alert page, you will have a website with ads displayed instead of this page. Some type of ads can only be blocked this way, which is why we use this page.

**Comment by sil71sil** [comment]
@alexx7311  thanks for the clear answer

**Comment by sil71sil** [comment]
@alexx7311  thanks for the clear answer
