### ISSUE TITLE
Consider to include Firefox signed .xpi in GitHub stable releases (just like uBlock Origin)

### ISSUE THREAD

**Issue by emikaadeo-git** [AdguardTeam/AdguardBrowserExtension#2786]
### Issue Details

As you may know at the beggining of 2023 Mozilla decides that:

> All extension submissions with a significantly large number of users are now subject to human review by the add-ons review team before approval. This may, occasionally, result in minor delays publishing new versions of your extension on AMO.

Well, this often leads to huge delays (sometimes even weeks) in publishing new versions of extensions on AMO.
Version 4.3.46 was released a WEEK ago (Apr 8, 2024) and (at the time of writing) it's still not available on AMO.
I know that I can install beta release from GitHub but I want to use stable releases.

### Proposed solution

Would it be possible for you to include signed stable Firefox xpi's in GitHub releases?
uBlock Origin already do this:

![Screenshot 2024-04-15 at 14-31-50 GitHub - gorhill_uBlock uBlock Origin - An efficient blocker for Chromium and Firefox  Fast and lean](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/56483380/f43b0510-a444-47c8-8555-b2ccfb6b2b1c)

**Comment by maximtop** [comment]
Signing standalone addons in Firefox requires a review, at least that's what we've noticed with our beta standalone builds. These used to be signed automatically, but now the process requires time for review.

**Comment by maximtop** [comment]
There is no standalone build for the release, only for the beta. 
It's possible that the beta release on GitHub was published when the standalone beta build for Firefox was signed.
