### ISSUE TITLE
WebSocket connections can't be blocked

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardBrowserExtension#279]
Chrome 51.0.2704.106 m
Adguard 2.3.8

Reproduced in Opera and Yandex browser as well. 
Can't reproduce in Firefox, looks like Chromium only.

str:
1. Open https://e.mail.ru/
2. Ads are in the right side of the screen: 

![551c9e18-00fe-11e6-86c7-1db30b9d2766](https://cloud.githubusercontent.com/assets/17472907/16422274/7cae4708-3d60-11e6-9401-a93f3617ecd6.png)

**Comment by Alex-302** [comment]
Temporary added to Russian filter:
```
e.mail.ru#%#window.WebSocket = undefined;
```

**Comment by Mizzick** [comment]
Should test with after #273

**Comment by ameshkov** [comment]
@gshumihin we need to test this

**Comment by Alex-302** [comment]
Removed:
```
e.mail.ru#%#(function() { var d = document.documentElement; var appendChild = d.appendChild; d.appendChild = function(n) { appendChild.apply(d, arguments); if (n.contentWindow) { n.contentWindow.WebSocket = undefined; } } })();
```
