### ISSUE TITLE
Integrate Consent-O-Matic

### ISSUE THREAD

**Issue by SpotlightForBugs** [AdguardTeam/AdguardBrowserExtension#2794]
[Consent-O-matic project page](https://github.com/cavi-au/Consent-O-Matic)

Consent-O-Matic is a wonderful solution that combats many cookie banners. Particularly useful if you don't want to block cookie banners, but you don't want to accept all cookies either. 

I know that Chrome and Edge are preparing to discard 3rd-party cookies, but I think that many sites are going to use first party cookies for tracking instead to circumvent those restrictions.

**Comment by alexx7311** [comment]
@SpotlightForBugs Hello! Thanks, but we're not going to integrate Consent-O-Matic.
Closing as a dup. of https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2602
