### ISSUE TITLE
cookie bug

### ISSUE THREAD

**Issue by JackeyLov5** [AdguardTeam/AdguardBrowserExtension#2798]
### AdGuard Extension version

4.3.46

### Browser version

Chrome 124.0.6367.62

### OS version

macos 14.5

### Issue Details

I've been having problems with cookies expiring on some of my sites, and it can take up to 30 minutes for me to log back in, but I've noticed that my cookies expire after 30 days, so apparently it's the plugin, even though I've disabled cookies on that site, and I've uploaded my configuration file. What setting is causing the problem [20240426_042253_adg_ext _settings_4.3.46.json](https://github.com/AdguardTeam/AdguardBrowserExtension/files/15120331/20240426_042253_adg_ext_settings_4.3.46.json)

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by alexx7311** [comment]
@JackeyLov5 Hello! Did we understand you correctly that on certain sites you are unlogged after 30 minutes? Do other site settings change, such as the selected theme or site language?

Please explain step by step how to reproduce the problem and provide examples of such sites.

**Comment by JackeyLov5** [comment]
Is that okay?
<img width="1049" alt="image" src="https://github.com/AdguardTeam/AdguardBrowserExtension/assets/130417202/a4d81c7c-6577-4d2a-950e-b16366f1c287">

**Comment by alexx7311** [comment]
@JackeyLov5 Those cookies you highlighted expire in 2025.

Please copy this rule into User rules section and click Save:
`@@||t00ls.com^$stealth,removeparam,cookie`

Did it solve the problem? Maybe one of the modules from Stealth Mode is causing the problem.

**Comment by JackeyLov5** [comment]
> @JackeyLov5 Those cookies you highlighted expire in 2025.
> 
> Please copy this rule into User rules section and click Save: `@@||t00ls.com^$stealth,removeparam,cookie`
> 
> Did it solve the problem? Maybe one of the modules from Stealth Mode is causing the problem.

It should be. So I turned off some functions and now it's normal. I don't want to toss around. Let's wait for the next update.

**Comment by alexx7311** [comment]
We'll close the issue for now. Please leave a comment if the problem recurs.
