### ISSUE TITLE
Firefox: cannot add filter subscription

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#28]
Steps to reproduce:
1. Go to Adguard settings
2. Click "All filters"
3. Enable one filter
4. Press "Save changes"

Expected result:
Filter is added to the list

Result:
Filter is not added to the list until page refresh

**Comment by Mizzick** [comment]
Cannot reproduce with
Adguard AdBlocker (Beta) 2.0.15
FireFox 40.0.3

**Comment by ameshkov** [comment]
Not that simple. This problem is reproducible if it takes too much time to download that filter list (try with EasyList for instance).

**Comment by Mizzick** [comment]
Fixed with showing loader during downloading.
