### ISSUE TITLE
[Feature request] Rework filters UI in our extensions

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardBrowserExtension#281]
Я использую плагин Adguard Антибаннер (Legacy) v2.3.8 вместе с Mozilla FireFox v35.0.1.

Очень часто добавляю / удаляю / исправляю свои собственные фильтры. Т.к. в большинстве своём я использую не быстрые компьютеры, то частенько приходится ждать неудобной (по моему мнению) динамической прогрузки списка фильтров. Сейчас она меня достала в конец: для того, чтобы пролистать список фильтров до конца и посмотреть / изменить / удалить последний (последние) добавленный фильтр приходится ждать от 30 до 40 сек на прогрузку каждого участка списка из 20 - 30 правил, и так раз 5 - 6, пока доберусь до конца списка. И это не считая того, что после прогрузки новой порции списка в ней сначала идут повторные правила (дубляж) из предыдущих частей списка и только потом - новые. Иногда новая подгруженная часть списка состоит полностью из дубляжей.

Из всего вышесказанного я прошу вас сделать следующее:
1. Переделать динамически подгружаемый список фильтров (правил) в статический, загружаемый полностью при открытии окна настроек Adguard'а. Либо сделать опцию, чтобы пользователь сам мог выбрать динамический ему использовать список фильтров или статический. Можно список сделать в виде отдельного окна, но тоже статический. Кстати, после переделки в статический, проблема дубляжей должна отпасть сама собой.
2. Сделать "галочки" отключения и включения отдельных фильтров. А то не удобно, для проверки, каждый раз удалять и создавать фильтр заново. Сделать опцию, дающую возможность задействовать включённый таким образом фильтр сразу-же, без перезагрузки страницы (как в Adblock Plus), когда это возможно - но только опционально.
3. Сделать нормальное удобное большое и/или расширяемое окно со списком пользовательских фильтров. Или отдельное окно для списка фильтров.

**Comment by ameshkov** [comment]
Пункты 1 и 3 могут быть закрыты проще: если мы добавим возможность установки фильтров просто по URL. Тогда можно будет редактировать их просто в текстовом редакторе и обновления подтягивать в программу.

Пункт 2: галки обязательно сделаем.

**Comment by XX-J** [comment]
> установки фильтров просто по URL
Это в смысле: по ссылке из окна настроек Adguard'а?
> редактировать их просто в текстовом редакторе
во вкладке или окне браузера или внешнем текстовом редакторе?

P.S.: Я автор запроса...

**Comment by ameshkov** [comment]
> Это в смысле: по ссылке из окна настроек Adguard'а?

Ну да, не ограничивать фильтры только нашим списком, а давать установить любой просто по ссылке. Условно, в дропбоксе можно держать файл и по ссылке его устанавливать.

> во вкладке или окне браузера или внешнем текстовом редакторе?

Подразумевался внешний редактор. Пользовательский фильтр, все же, не предназначен для тысяч правил.

**Comment by XX-J** [comment]
> установить любой просто по ссылке

А будет ли он автоматически обновляться при добавлении правила из Adguard'а? Т.е. не только читаться, но и писаться самим Adguard'ом?

Что будет с существующим методом редактирования правил фильтрации: уберёте или оставите как есть?

> Пользовательский фильтр, все же, не предназначен для тысяч правил.

У меня их пока около 120.

**Comment by ameshkov** [comment]
> А будет ли он автоматически обновляться при добавлении правила из Adguard'а? Т.е. не только читаться, но и писаться самим Adguard'ом?

Нет, из самого Adguard не будет редактирования, только установка и проверка обновлений.

> Что будет с существующим методом редактирования правил фильтрации: уберёте или оставите как есть?

Мы его поменяем, но только при редизайне всего расширения.

**Comment by XX-J** [comment]
> Нет, из самого Adguard не будет редактирования, только установка и проверка обновлений.

Добавление новой возможности, в виде автоподгрузки внешнего файла с правилами, - это хорошо, но я имел ввиду редактирование правил фильтрации добавленных самим Adguard'ом, поэтому:

> Пункты 1 и 3 могут быть закрыты проще...

- это не поможет отредактировать только-что созданное (ые) Adguard'ом правило (а) фильтрации.


> Мы его поменяем, но только при редизайне всего расширения.

Стоит ли надеяться, что Вы его поменяете с учётом моих пожеланий (п. 1-3)? Когда у Вас запланирован "редизайн"?

**Comment by ameshkov** [comment]
> Добавление новой возможности, в виде автоподгрузки внешнего файла с правилами, - это хорошо, но я имел ввиду редактирование правил фильтрации добавленных самим Adguard'ом, поэтому:

Редактировать подгруженный фильтр нет смысла, так как он при обновлении фильтра он перетрется. 

> Стоит ли надеяться, что Вы его поменяете с учётом моих пожеланий (п. 1-3)? Когда у Вас запланирован "редизайн"?

Да, с управлением фильтрами точно все станет лучше.

А вот точный срок сложно назвать, задач на дизайнере много сейчас. Очень хочется до конца года все необходимые редизайны провести: iOS, Android,  расширение.

**Comment by XX-J** [comment]
> Редактировать подгруженный фильтр нет смысла, так как он при обновлении фильтра он перетрется.

Я Вообще, изначально, НЕ имел ввиду редактирование автоподгружаемого файла правил. Я имел ввиду встроенный в плагин редактор создаваемых же в плагине и с помощью плагина правил. И все пункты относятся только к ЭТОМУ. Больше всего раздражает ДИНАМИЧЕСКАЯ прогрузка СПИСКА правил при их листании (колесом или ползунком).

> Да, с управлением фильтрами точно все станет лучше.
А вот точный срок сложно назвать, задач на дизайнере много сейчас.

Ну, если это не сложно, не могли бы Вы в ближайшем минорном обновлении просто ВЫКЛЮЧИТЬ ДИНАМИЧЕСКУЮ прогрузку списка правил редактора Adguard, о которой говорится чуть выше?

**Comment by ameshkov** [comment]
> Ну, если это не сложно, не могли бы Вы в ближайшем минорном обновлении просто ВЫКЛЮЧИТЬ ДИНАМИЧЕСКУЮ прогрузку списка правил редактора Adguard, о которой говорится чуть выше?

Мы ее специально добавляли, потому что без нее дичайше тормозит на больших списках:(

Но, думаю, имеет смысл увеличить размер подгружаемой страницы хотя бы до 100-200 элементов.

**Comment by XX-J** [comment]
> Но, думаю, имеет смысл увеличить размер подгружаемой страницы хотя бы до 100-200 элементов.

Да, этого, думаю, будет вполне достаточно. Только хочу уточнить: нужно либо пользователю дать возможность выбрать (в интерфейсе Adguard'а) на какое количество элементов будет осуществляться подгрузка страницы, либо сразу ставить 200. Просто варианты могут быть разные: медленный компьютер или быстрый, много правил в списке или мало и, наконец, согласен пользователь ждать прогрузку или он "торопится".

А по поводу интерфейса (галочки, большое окно списка правил) - я готов ждать. Понимаю сколько на Вас работы и благодарен Вам за хороший блокировщик рекламы и адекватную поддержку.

**Comment by ameshkov** [comment]
Вывел в отдельную задачу:
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/289
