### ISSUE TITLE
https://www.youtube.com/ и DarkTube

### ISSUE THREAD

**Issue by Cursone** [AdguardTeam/AdguardBrowserExtension#2815]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

4.3.46

### Browser version

Brave 1.47.186

### OS version

Windows 8.1 Enterprise х64

### Issue Details

Использую вот это расширение - **Tampermonkey** и вот этот скрипт- **DarkTube** - https://greasyfork.org/ru/scripts/399863-darktube

Если использовать - **AdGuard для Windows**, то результат такой

![1](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/155391717/f169eff0-391a-4d2c-9d24-fca7fb2d919a)

Если использовать - **AdGuard Extension**, то результат такой

![2](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/155391717/b528ed96-066d-41b6-b7ca-b386d57e346f)

### Actual Behavior

**AdGuard для Windows** и **AdGuard Extension** по разному отрабатывают.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by PavelParkhomenko** [comment]
Добрый день. Нам не удалось повторить проблему. На наших тестовых устройствах при использовании Tampermonkey с скриптом DarkTube в целом не удаётся добиться смены темы на youtube. Вне зависимости от того, включён ли AdGuard для Windows или расширение. 

Также просим обратить внимание на то, что у вас используется устаревшая версия браузера Brave.
