### ISSUE TITLE
AdGuard menu doesn't open in Firefox Nightly

### ISSUE THREAD

**Issue by YelenaKoroleva** [AdguardTeam/AdguardBrowserExtension#2817]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

4.3.46

### Browser version

Firefox Nightly 128.0a1

### OS version

macOS 12.7.1

### Issue Details

Steps to reproduce:
1. install Firefox Nightly
2. install AdGuard extension
3. click the extension to open the menu

<details>
  <summary>Screenshot</summary>

  ![Screenshot](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/114913601/6138225e-9714-4930-a10e-90ff490d5c26)

</details>

### Expected Behavior

seeing number of blocked requests, main toggle and other features

### Actual Behavior

the features don't appear

</details>

**Comment by alexx7311** [comment]
It seems to be a bug in the nightly version of Firefox. The problem doesn't occur in the stable version.

**Comment by ChaerilM** [comment]
![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/1352081/6ddf89a3-019e-4a9e-a145-0761fedfe7e7)

is this same with this that happen to me for couple of days?.

**Comment by xiulou23** [comment]
> ### Please answer the following questions for yourself before submitting an issue
> 
> - [X] Filters were updated before reproducing an issue
> - [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
> - [X] I checked to make sure that this issue has not already been filed
> 
> ### AdGuard Extension version
> 
> 4.3.46
> 
> ### Browser version
> 
> Firefox Nightly 128.0a1
> 
> ### OS version
> 
> macOS 12.7.1
> 
> ### Ad Blocking
> 
> _No response_
> 
> ### Privacy
> 
> _No response_
> 
> ### Social
> 
> _No response_
> 
> ### Annoyances
> 
> _No response_
> 
> ### Security
> 
> _No response_
> 
> ### Other
> 
> _No response_
> 
> ### Language-specific
> 
> _No response_
> 
> ### What Stealth Mode options do you have enabled?
> 
> _No response_
> 
> ### Issue Details
> 
> Steps to reproduce:
> 1. install Firefox Nightly
> 2. install AdGuard extension
> 3. click the extension to open the menu
> 
> <details>
>   <summary>Screenshot</summary>
> 
>   ![Screenshot](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/114913601/6138225e-9714-4930-a10e-90ff490d5c26)
> 
> </details>
> 
> 
> ### Expected Behavior
> 
> seeing number of blocked requests, main toggle and other features
> 
> ### Actual Behavior
> 
> the features don't appear
> 
> 
> </details>
> 
> 
> ### Additional Information
> 
> _No response_

我也遇到这个问题，希望能尽快解决

**Comment by emilio** [comment]
FWIW would be _great_ to get these regressions reported earlier to Firefox as well, even if there's a workaround available on the extension's side :)

https://bugzilla.mozilla.org/show_bug.cgi?id=1906132 tracks this, about to attach a fix.

**Comment by vozersky** [comment]
we are going to fix it from our side for now
hotfix is coming

**Comment by alexx7311** [comment]
The fix is available for our Firefox beta channel https://agrd.io/extension_firefox_beta
The release version is being reviewed right now, but will be available soon too.
