### ISSUE TITLE
Get rid of _proto_ property usage

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#282]
This is a deprecated property, eventually it should be removed from our code:
https://github.com/AdguardTeam/AdguardBrowserExtension/search?utf8=%E2%9C%93&q=__proto__

Reference:
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/proto

**Comment by Mizzick** [comment]
Fixed
