### ISSUE TITLE
Button to Disable JavaScript in Main Interface to Avoid Some Paywalls

### ISSUE THREAD

**Issue by rodrigosambadesaa** [AdguardTeam/AdguardBrowserExtension#2822]
### Issue Details

There isn't a button in Chrome extension's main interface to disable JavaScript to avoid some paywalls, like in uBlock Origin extension.

### Proposed solution

Implement a button in the main interface of the Chrome extension to disable JavaScript to avoid some paywalls.

**Comment by alexx7311** [comment]
@rodrigosambadesaa Hello! We haven't yet decided if it's something we should implement, but we'll give it some more thought.
Closing as a dup. of https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1859

**Comment by rodrigosambadesaa** [comment]
Dissapointing that you haven't made a decision despite allmost three years passed.
