### ISSUE TITLE
FACEBOOK ADS and page suggestion

### ISSUE THREAD

**Issue by jatinmanek** [AdguardTeam/AdguardBrowserExtension#2827]
Hi team, the adblock and page suggestion are now not being blocked by adguard please look into it.
![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/103603769/99ab789b-8ed8-44e7-aa62-bdfb11df7cd2)

**Comment by alexx7311** [comment]
@jatinmanek Hello! Please report this website via the extension popup. You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/
