### ISSUE TITLE
Merge StealthMode Extension code

### ISSUE THREAD

**Issue by Mizzick** [AdguardTeam/AdguardBrowserExtension#283]
The code we can reuse:
https://github.com/AdguardTeam/StealthMode

Add a new settings section: "Privacy": https://uploads.adguard.com/up04_84asd_AdGuard_Settings.png

## Privacy

Protect your identity and sensitive personal info from thousands of online trackers by blocking the most popular tracking methods.

### General

* [ ] `Hide Referrer from third-parties`
    `Prevents third-parties from knowing what website you are visiting.`
* [ ] `Hide your search queries`
    `From websites, you visit from a search engine`
* [ ] `Send Do-Not-Track header`
    `Signals to web servers that you don't want to be tracked.`
* [ ] `Remove X-Client-Data header`
    `Blocks Google Chrome from sending its version and modifications information to Google domains.`

### Cookies

* [ ] `Self-destructing third-party cookies`
    `Limits the lifetime of third-party cookies.`
* [ ] `Time-to-live for a third-party cookie`
    `Set to 0 to block them completely.`
* [ ] `Self-destructing first-party cookies (not recommended)`
    `Limits the lifetime of first-party cookies.`
* [ ] `Time-to-live for a first-party cookie`
    `Set to 0 to block them completely.`

**Comment by ameshkov** [comment]
Not just merge, it should also work in FF after that.

**Comment by ameshkov** [comment]
Add a "Stealth Mode" settings group for it (below "Ad Blocker" group)

**Comment by Anoop2609** [comment]
I have seen screenshot of the new layout of adgurad but there is no Stealth Mode option. Is this feature is coming in new adgurad or not? Just for curiosity....

**Comment by ameshkov** [comment]
Postponed it to v3.0 till new design is ready. It is coming tho

**Comment by AlikhanAliev** [comment]
![ext-privacy](https://user-images.githubusercontent.com/30260021/46201262-4477c280-c31c-11e8-97d2-90e6bf51236a.png)

[ext-privacy.zip](https://github.com/AdguardTeam/AdguardBrowserExtension/files/2427674/ext-privacy.zip)

**Comment by Nzzyme** [comment]
@ameshkov Just installed the latest release (3.0.7) for Chrome. I observed that the Stealth mode does not include few options that are available in Android namely:

Disable cache for third-party requests
Block third-party Authorization header
Block Push API
Block Location API
Mask your IP Address
Remove X-Client-Data header

Are we planning to include these? Thanks!

**Comment by ameshkov** [comment]
> Remove X-Client-Data header

This one is still present.

We've included the most important ones in this version.

We might add other options with time. Most likely the first to implement will be blocking push and location API.
