### ISSUE TITLE
Adguard filtering log in Opera does not show requests when visiting search engines (Google, Bing, Duckduckgo)

### ISSUE THREAD

**Issue by andris86** [AdguardTeam/AdguardBrowserExtension#2834]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

4.3.53

### Browser version

Opera

### OS version

Windows 11

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard Tracking Protection filter, AdGuard URL Tracking filter

### Annoyances

AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter

### Security

Online Malicious URL Blocklist, Phishing URL Blocklist, Scam Blocklist by DurableNapkin

### Language-specific

AdGuard Chinese filter, AdGuard Dutch filter, AdGuard French filter, AdGuard German filter, AdGuard Japanese filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter, AdGuard Ukrainian filter

### Issue Details

Steps to reproduce:
1. Open Adguard filtering log in Opera.
2. Open a search engine. I tried on Google, Bing and Duckduckgo in Opera.
3. Observe filtering log for network requests.

### Expected Behavior

Adguard shows requests in filtering log when visiting search engines.

### Actual Behavior

Nothing shows up in filtering log when visiting search engines in Opera.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

### Additional Information

Just installed the Opera browser. Nothing like this has happened in Edge and Firefox.

**Comment by alexx7311** [comment]
@andris86 Hello!
For the filtering to work, you need to enable the `Allow access to search page results` option. 

Relevant issue: https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2485
