### ISSUE TITLE
Issue: "Dandelion Sprout's Annoyances List" Blocks All Video Thumbnails on YouTube Channel Pages

### ISSUE THREAD

**Issue by Comsev** [AdguardTeam/AdguardBrowserExtension#2835]
Hello,

I am experiencing a significant issue with the filter "Dandelion Sprout's Annoyances List" in AdGuard, which has been affecting my browsing experience on YouTube.

**Problem Description**:

When the "Dandelion Sprout's Annoyances List" filter is enabled in AdGuard, it blocks all video thumbnails on the main pages of YouTube channels. This problem is not isolated to a specific channel but affects all YouTube channels that I visit. Instead of seeing the usual thumbnails for videos, I am met with blank spaces where the thumbnails should be. This issue severely disrupts the user experience as it prevents me from previewing the available videos on a channel's main page, which is essential for navigating and selecting content to watch.

**Expected Behavior**:

Video thumbnails should be displayed normally on the main page of YouTube channels, allowing users to see the preview images of the videos available on the channel.

**Actual Behavior**:

With the filter enabled, all video thumbnails are blocked, leading to a blank space where each thumbnail should be displayed. This makes it impossible to see which videos are available on the channel without clicking on each blank space individually, which is not practical or user-friendly.

**Impact**:

This issue is particularly problematic for users who rely on visual thumbnails to quickly identify and choose videos to watch. The absence of thumbnails forces users to guess the content of each video, significantly degrading the overall YouTube experience.

**System Information**:

Browser: _Microsoft Edge_
Operating System: _Windows 11 Pro_

**Additional Context**:

This issue started occurring after the recent update to the "Dandelion Sprout's Annoyances List." Prior to this update, the video thumbnails were displayed correctly.

I kindly request the developers to investigate and resolve this issue as it greatly affects the usability of YouTube with AdGuard enabled. Any assistance in fixing this problem would be highly appreciated.

Thank you for your attention to this matter.

**Comment by alexx7311** [comment]
@Comsev Hello! We haven't been able to reproduce the problem. If the problem is related to `Dandelion Sprout's Annoyances List`, you should report it to the filter developer https://github.com/DandelionSprout/adfilt
