### ISSUE TITLE
Auto pause AdGuard Chrome Plugin when connected to specific WiFi or LAN

### ISSUE THREAD

**Issue by chimcen** [AdguardTeam/AdguardBrowserExtension#2837]
### Issue Details

In AdGuard Pro for iOS is an option to pause (disable dns protection) in specified WiFi SSIDs. Is this also possible to implement into this browser extension?

### Proposed solution

It would be great if it's not only possible for WiFi SSIDs, but also for LAN networks (i.e. by LAN adapter name or IP range)?

**Comment by alexx7311** [comment]
@chimcen Hello! Unfortunately, it is impossible to implement such a feature within a browser extension.
