### ISSUE TITLE
Audio ads are not blocked

### ISSUE THREAD

**Issue by Proton-oss** [AdguardTeam/AdguardBrowserExtension#2838]
Чому блокувальник не блокує аудіоспам і  аудіорекламу?  Я обрав оновлення протирекламних фільтрів кожної години, але аудіоспам з'являється кожні 10 секунд !!! Допоможіть будь ласка.

**Comment by alexx7311** [comment]
@Proton-oss Будь ласка, подайте скаргу на сайт через Помічник AdGuard. За цим посиланням ви знайдете детальні покрокові інструкції: https://adguard.app/kb/guides/report-website/#extension
