### ISSUE TITLE
Youtube shows ads after all

### ISSUE THREAD

**Issue by SummerADDE** [AdguardTeam/AdguardBrowserExtension#2842]
Youtube has implemented a new feature that managed to show 1-2 short ads before any video I watch on their website nowadays. There is no button or "The video will start soon" seen anywhere or anything that says there are ads, just 2 ads being shown before the video actually starts, among other general bugs that the video player now has.

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/84330558/e49d1bea-3290-4d16-956b-fd08e252632c)

**Comment by Alby7** [comment]
@alexx7311 the ads do indeed show up, but I've discovered by accident a way to bypass them.
If you click on a timestamp in the comments or a chapter if they are enabled it will skip the add and go right to the video.

**Comment by alexx7311** [comment]
@Alby7 Hello! Please report this website via the extension popup. You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/
