### ISSUE TITLE
 Wrong log format: message is not printed.

### ISSUE THREAD

**Issue by suhan3z** [AdguardTeam/AdguardBrowserExtension#285]
![image](https://cloud.githubusercontent.com/assets/3650070/16811283/35970fd6-4930-11e6-8fe7-89201c6e9295.png)

**Comment by ameshkov** [comment]
@suhan3z the problem here is not that error, but wrong log format: message is not printed.

**Comment by Mizzick** [comment]
<img width="946" alt="screenshot 2016-07-14 15 50 26" src="https://cloud.githubusercontent.com/assets/13855288/16836339/b97ba168-49da-11e6-945c-c8517b05238c.png">
Nope, I think the problem is about Error object. It's ok with simple test error message

**Comment by Mizzick** [comment]
Fixed
