### ISSUE TITLE
AdGuard popup doesn't open in Firefox nightly

### ISSUE THREAD

**Issue by BaiBuCYBGT** [AdguardTeam/AdguardBrowserExtension#2852]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

4.3.53

### Browser version

firefox 128.0b7

### OS version

win10 22h2

### Issue Details

Steps to reproduce:
1.click 
2.
3.

### Expected Behavior

open it

### Actual Behavior

click and have nothing , just see picture

### Screenshots

<details><summary>Screenshot 1</summary>

![PixPin_2024-06-26_02-11-29](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/37788089/4db462ae-6141-4cf1-8b24-dbe9f2ac86f0)
![PixPin_2024-06-26_02-16-16](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/37788089/d8b941ec-30c7-4328-a8a1-e12d9fa205c4)
</details>

**Comment by BaiBuCYBGT** [comment]
![PixPin_2024-06-26_02-11-29](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/37788089/4357964a-7e10-4e80-926d-0c54060f4178)
![PixPin_2024-06-26_02-16-16](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/37788089/2df327fb-d787-4281-beb2-58f324d291c6)

**Comment by BaiBuCYBGT** [comment]
1. Click ADguard in browser
2. ADguard will pop up a small window
3. ADguard just pops up a little window that doesn't see anything.
![PixPin_2024-06-27_13-07-35](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/37788089/0a0f5b64-9578-480f-9c51-008d2d5af61f)
with the correct comparison.
![PixPin_2024-06-27_13-08-04](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/37788089/ce5e9aff-1af3-4f50-b18b-9446a29267ee)

**Comment by alexx7311** [comment]
@BaiBuCYBGT This is a bug with Firefox Nightly https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2817
Until we fix it you can use stable version of Firefox https://www.mozilla.org/en-US/firefox/127.0.2/releasenotes/
