### ISSUE TITLE
Settings are not saved in Firefox

### ISSUE THREAD

**Issue by xnoar747** [AdguardTeam/AdguardBrowserExtension#2853]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

4.3.53

### Browser version

Firefox 127.0.1

### OS version

Windows 11

### Issue Details

Steps to reproduce:
1. Open AdGuard settings
2. Change something
3. Close setting tab
4. Everything is like it should be
5. Wait some time with open browser or close browser
6. Settings have been reset again

### Expected Behavior

Settings remain as I changed them even after closing the browser.

### Actual Behavior

Settings are reset to the status at the time of installation.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

### Additional Information

Reinstalling the extension leads to the same error. So that does not help.

**Comment by alexx7311** [comment]
@xnoar747 Hello! This is a Firefox bug https://bugzilla.mozilla.org/show_bug.cgi?id=1885297.

You can help us fix it faster by following the steps listed in https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2775#issuecomment-2036577871 and posting your results in issue https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2775.

Thanks in advance!
