### ISSUE TITLE
"Hide Referer from third parties" and "Hide your search queries" features don't work in Opera

### ISSUE THREAD

**Issue by alexx7311** [AdguardTeam/AdguardBrowserExtension#2856]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

4.3.53

### Browser version

Opera 111.0.5168.43

### OS version

Windows 11

### Issue Details

Steps to reproduce:
1. Go to google.com and search for `what is my referer`
2. Go to whatismybrowser.com link from google.com search results
<details>
  <summary>Screenshot</summary>

  ![Screenshot](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/114913601/ffe928b2-73d1-43b4-83d2-c7a505291891)

</details>
4. It will show `google.com` as your referer
5. Enable `Stealth mode` in the extension's settings and turn on `Hide your search queries` switch
6. Follow the link from step 2 again and look at the results
7. Turn off `Hide your search queries` and enable `Hide Referrer from third parties`
8. Follow the link from step 2 again and look at the results

### Actual Behavior

It shows google.com as your referer with each of the options enabled.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by maximtop** [comment]
`Allow access to search page results`
should be enabled in the opera
