### ISSUE TITLE
The extension UI size is incorrect in Firefox 128.0 on Linux

### ISSUE THREAD

**Issue by hadrabap** [AdguardTeam/AdguardBrowserExtension#2864]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

4.3.53

### Browser version

Official Firefox 128.0 (not a distro one)

### OS version

Oracle Linux 8

### Issue Details

Steps to reproduce:
1. Click on a AdGuard toolbar icon

### Expected Behavior

An AdGuard control panel overlay window should be displayed with all controls visible.

### Actual Behavior

The window height of the AdGuard control panel is too short that nothing is visible nor accessible.

### Screenshots

<details><summary>Screenshot 1</summary>

![adguard-ui](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/25428188/c8fadad3-9c11-4468-9e8b-0dc033af7320)

</details>

### Additional Information

The issue started after upgrade to Firefox 128.0 from Firefox 127.0.2.

**Comment by alexx7311** [comment]
@hadrabap Hello! This is a [Firefox bug](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2817). Please update the extension to https://github.com/AdguardTeam/AdguardBrowserExtension/releases/tag/v4.3.64.

**Comment by maximtop** [comment]
Please update extension to the new version
Issue should be fixed already
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2817
