### ISSUE TITLE
Security issue and message issue

### ISSUE THREAD

**Issue by SuperUser771** [AdguardTeam/AdguardBrowserExtension#2866]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

4.3.64

### Browser version

Firefox 128

### OS version

macOS 10.13

### Language-specific

Frellwit's Swedish Filter

### Issue Details

Issue 1 - in the settings, the option "Phishing- och skadeprogramsskydd" automatically turns itself off
Issue 2 - when opening a website, suddenly now a message appears "Autoinkoppling av filter - Frellwit's Swedish Filter har aktiverats automatiskt". This has never happened before.

### Expected Behavior

Issue 1 - if the option for protection agains phishing etc is switched on, it has to remain switched on, it can't just automatically switch itself off
Issue 2 - why has this message suddenly now started to appear? It has never been so before.

### Actual Behavior

Issue 1 - in the settings, the option "Phishing- och skadeprogramsskydd" automatically turns itself off
Issue 2 - when opening a website, suddenly now a message appears "Autoinkoppling av filter - Frellwit's Swedish Filter har aktiverats automatiskt". This has never happened before.

### Screenshots

<details><summary>Screenshot 1</summary>

![bild](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/175257423/472f7033-2948-4cd6-b535-479393d3e407)

</details>

### Additional Information

Thank you for your time to read and analyse the problem. Would you be so kind to send me a reply, please? I hope to hear from you soon and get help how to solve these issues.

**Comment by alexx7311** [comment]
@SuperUser771 Hello! This is a Firefox bug https://bugzilla.mozilla.org/show_bug.cgi?id=1885297.

You can help us fix it faster by following the steps listed in https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2775#issuecomment-2036577871 and posting your results in issue https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2775.

Thanks in advance!
