### ISSUE TITLE
Return color of icon back to black

### ISSUE THREAD

**Issue by YesTrustMe** [AdguardTeam/AdguardBrowserExtension#2867]
### Issue Details

I have both the full version and the MV3 version. I can easily tell them apart but after today's update I can't. I preferred the MV3 version as it was light. 

Also is the MV3 version now the same as the regular version? If so, remove it please. 

### Proposed solution

See above

### Alternative solution

Use Ublock origin.

**Comment by alexx7311** [comment]
@YesTrustMe Hello! As explained here https://github.com/AdguardTeam/AdGuardMV3/issues/66#issuecomment-2225152746 we're not planning to change the icon.

> Also is the MV3 version now the same as the regular version? If so, remove it please.

MV3 version of the extension is associated with many limitations, but we tried to keep the functionality from MV2 extension as much as possible. You can read about the changes in our blog https://adguard.com/en/blog/adguard-mv3-beta.html
