### ISSUE TITLE
Regex Not Working on Adguard Browser Extension

### ISSUE THREAD

**Issue by GrennKren** [AdguardTeam/AdguardBrowserExtension#2876]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

I'm having trouble finding a filter that works universally on both Adguard and UBO.

For example, I want to remove a specific banner that appears on domains like example01.com, example03.com, etc.

`/example[0-9]*\.com/##a[target*="blank"]:has(> img)`
```
This works on:
- UBO
- Adguard for Windows
- Adguard for Android

but not on:
- Adguard Browser Extension
```

`[$domain=/example[0-9]*\.com/]##a[target*="blank"]:has(> img)`
```
This works on:
- Adguard Browser Extension Beta (v4.4)
- Adguard for Android
- Adguard for Windows

but not on:
- UBO
- Adguard Browser Extension (v4.3)
```

I've also looked at the compatibility details on
https://adguard.com/kb/general/ad-filtering/create-own-filters/#regexp-support.

It mentions that regex patterns don't work on AdGuard for Safari and AdGuard for iOS, but there's no mention of the Adguard Browser Extension.

I also tried `example*.com##a[target*="blank"]:has(> img)` but unfortunetly wildcard only works for TLD and not domain name. (Any Adguard Product and even UBO doesn't support it)

**Comment by alexx7311** [comment]
@GrennKren Hello!
We've added compatibility with the uBlock syntax in CoreLibs, so these rules will work in AdGuard for Windows, but for now the extension isn't compatible with it.
I've created an issue:  https://github.com/AdguardTeam/tsurlfilter/issues/135

**Comment by eric-gitta-moore** [comment]
for `Adguard Browser Extension`, I can work with `example0.com,example1.com,example2.com##a[target*="blank"]:has(> img)`

But if regular expression matching is supported, it would be a wonderful thing.
