### ISSUE TITLE
Can't enable any of the security filters

### ISSUE THREAD

**Issue by emeritaacuity0u** [AdguardTeam/AdguardBrowserExtension#2880]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

Version 4.4.1

### Browser version

Microsoft Edge for Business Version 126.0.2592.56

### OS version

Windows 11 Pro 22621.3737

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard Tracking Protection filter, AdGuard URL Tracking filter

### Annoyances

AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters, Hide your search queries, Ask websites not to track you

### Issue Details

Steps to reproduce:
1. Try enable any of the security filters

### Expected Behavior

Security filters are enabled

### Actual Behavior

Security filters enable for approximately 5 seconds, then disable

### Screenshots

<details><summary>Screenshot 1</summary>

https://github.com/user-attachments/assets/4427b73b-c303-46e6-82c8-42f4caed2a7d

</details>

### Additional Information

[adg_ext_settings_4.4.1_250724-022827.json](https://github.com/user-attachments/files/16365020/adg_ext_settings_4.4.1_250724-022827.json)

**Comment by alexx7311** [comment]
@emeritaacuity0u Hello! Do you have any problems enabling filters with `#recommended` tag?
Most likely the extension couldn't connect to filters.adtidy.org to download filters.

What do you see on the Network tab of the background page when you try to enable those filters?
<details>
  <summary>Screenshot</summary>

  ![Screenshot](https://github.com/user-attachments/assets/6ecfcebf-4c54-4d61-99e1-baf0fca5b311)

</details>

If there's a connection problem you can try to use VPN.

**Comment by emeritaacuity0u** [comment]
I'd say that's the issue then, Zscaler blocks adtidy, I was hoping that would be avoided with the merging of the MV3 extension.

**Comment by alexx7311** [comment]
@emeritaacuity0u The MV3 update indeed will solve this problem as the filters will be updated with the extension itself only.

If it's not too much trouble, please submit a false positive report to Zscaler team about our adtidy domain. We'll try to submit it too, but the more reports they get, the better chance they'll fix it faster.
