### ISSUE TITLE
Fast switching on several filters in a row causes some turned on filters to be disabled 

### ISSUE THREAD

**Issue by andris86** [AdguardTeam/AdguardBrowserExtension#2884]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

4.3.53

### Browser version

Brave browser v1.68.128

### OS version

windows 11 23H2

### Issue Details

1. Open Adguard extension options
2. Navigate to section where there a lot of filters like Language specific filter section
3. Turn them off/on manually one by one
4. Keep doing this and they will start glitching

### Actual Behavior

Filter switches are turning on/off on their own. Often there's several seconds delay before switch turns. Also one switch might turn when I click on second switch. It's happened all the time and it's like playing cat and mouse game. I recorded a video of the bug but can't upload here because file size is too big. Watch it here: https://www.youtube.com/watch?v=sDn_nObOsxE

**Comment by alexx7311** [comment]
Dup. of https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2804
