### ISSUE TITLE
missing filter refresh button.:

### ISSUE THREAD

**Issue by m2c2lure67** [AdguardTeam/AdguardBrowserExtension#2888]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

5.0.5

### Browser version

Chrome: 127.0.6533.89 

### OS version

n/a...both Windows and ChromeOS

### Issue Details

Steps to reproduce:
1. 
2.
3.

### Expected Behavior

Clicking the extension icon displays a small access panel with a "Refresh Filters" button that can be clicked to proceed with refreshing filters data.

### Actual Behavior

Clicking the extension icon displays a small access panel, but the "Refresh Filters" button is missing.

### Screenshots

<details><summary>Screenshot 1</summary>

![image](https://github.com/user-attachments/assets/67d089df-391b-4ef1-9891-b41c7114069a)

</details>

**Comment by alexx7311** [comment]
@m2c2lure67 Hello! This is not a bug. In the MV3 version of the extension, filters will be updated along with the extension. You can read about limitations of MV3 version at https://adguard.com/en/blog/adguard-mv3-beta.html

**Comment by m2c2lure67** [comment]
Alexx,   So pressing this button will be how the AdGuard filters are
updated going forward?...

[image: image.png]

**Comment by alexx7311** [comment]
@m2c2lure67 The extension will be updated automatically. There won't be any need to press any button to update it.
