### ISSUE TITLE
AdGuard Annoyances filter is missing in the Filters

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdguardBrowserExtension#2889]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

5.0.5 beta

### Browser version

Chrome 127.0.6533.89

### OS version

Windows 11

### Issue Details

Steps to reproduce:
1. Go to the `Filters` section

### Expected Behavior

This filter should be added on the `Filters` section.

### Actual Behavior

`AdGuard Annoyances filter`
_Blocks irritating elements on web pages including cookie notices, third-party widgets and in-page pop-ups. Contains the following AdGuard filters: Cookie Notices, Popups, Mobile App Banners, Other Annoyances and Widgets._

Not sure is this bug but this filter is missing in the `Filters` sections for MV3.

### Screenshots

<details><summary>MV3</summary>

![MV3](https://github.com/user-attachments/assets/508923e5-fd74-4c23-9da5-9fca7cc6fcee)
</details>

<details><summary>Normal extension</summary>

![Normal](https://github.com/user-attachments/assets/17375b16-df13-476c-8033-5eda35f1e47f)
</details>

**Comment by alexx7311** [comment]
@gork7777 Hello! This is not a bug. We've removed this filter, but we still have 5 of its components: Cookie Notices, Popups, Mobile App Banners, Other Annoyances, Widgets.
