### ISSUE TITLE
Block videos from bilibili.com and cannot play them

### ISSUE THREAD

**Issue by sy153** [AdguardTeam/AdguardBrowserExtension#2892]
I installed this latest beta plug-in and found that when I opened bilibili, it blocked my video and I couldn't play it. But when I changed to the old version, the video could be played.I want to know why

**Comment by alexx7311** [comment]
@sy153 Hello! We have templates for a reason.
Please export AdGuard extension settings and attach them to a comment here.

What browser are you using? What other extensions are you using? Have you tried disabling other extensions?
Please also provide a link to a video on bilibili.

**Comment by alexx7311** [comment]
@sy153 Please report this website via the extension popup. You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/
