### ISSUE TITLE
No on-off switch

### ISSUE THREAD

**Issue by empogithub** [AdguardTeam/AdguardBrowserExtension#2897]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

4.3.53

### Browser version

chrome 127.0.6533.100

### OS version

Windows 11 pro 22H2

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard Tracking Protection filter, AdGuard URL Tracking filter

### Annoyances

AdGuard Popups filter

### Security

Online Malicious URL Blocklist, Phishing URL Blocklist

### Language-specific

Frellwit's Swedish Filter

### What Tracking protection options do you have enabled?

Block trackers

### Issue Details

Steps to reproduce:
1. have low memory
2. reload the extension
3. done

### Actual Behavior

on off switch is not there

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

### Additional Information

on off switch is not there

**Comment by alexx7311** [comment]
@empogithub, hello! I'm not sure if it's a bug. The extension will need about 100-150 megabytes of RAM to run properly.
Please describe the problem in as much detail as possible, reproduce the problem and take a screenshot.

**Comment by alexx7311** [comment]
@empogithub, any updates?

**Comment by alexx7311** [comment]
@empogithub Please leave a comment if the issue is still relevant.

**Comment by empogithub** [comment]
now it's working again, thanks for the help.
