### ISSUE TITLE
Input for rule is too short (look at the screenshot)

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#29]
http://screencast.com/t/E7t6EzHQp

As I understand this style with 80% width is used in several places.
Check that fixing this won't break layout in other places.

**IMPORTANT:** Check layout in FF, it often looks different from Chromium

**Comment by Mizzick** [comment]
fixed

**Comment by ameshkov** [comment]
Close it, don't reassign

**Comment by Mizzick** [comment]
okay
