### ISSUE TITLE
Improve performance by replacing `lodash` npm package with `es-toolkit`

### ISSUE THREAD

**Issue by piquark6046** [AdguardTeam/AdguardBrowserExtension#2911]
### Issue Details

To improve performance of AdGuard Browser Extension, I suggest replacing `lodash` npm package with `es-toolkit` that provides 2-3 times faster and up to 97% smaller than `lodash`. 

https://github.com/toss/es-toolkit
https://es-toolkit.slash.page/
https://es-toolkit.slash.page/performance.html
https://es-toolkit.slash.page/compatibility.html

### Proposed solution

Replace `lodash` npm package with `es-toolkit`.

**Comment by maximtop** [comment]
While es-toolkit seems promising, I would hesitate to use it in the extension right now. The library is still pretty new and doesn’t have the maturity we might need. A lot of methods either aren’t implemented yet or are still in progress:

	•	Total Methods: 263
	•	Implemented: 66 (✅)
	•	Not Implemented: 187 (❌)
	•	In Progress/Planned: 87 (📝)
	•	No Support: 11

Given this, it seems too early to replace lodash—a well-established and widely-used library—with es-toolkit. The usage stats also show a big difference in maturity and adoption:

	•	Lodash: 50 million downloads
	•	es-toolkit: 25 thousand downloads

Switching to such a young library could introduce unnecessary risks, especially when compared to the stability and support that lodash offers.
