### ISSUE TITLE
Redirect rule causes a CSP error instead of redirecting

### ISSUE THREAD

**Issue by alexx7311** [AdguardTeam/AdguardBrowserExtension#2913]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

4.4.18

### Browser version

Chrome 127

### OS version

Windows 11

### Ad Blocking

AdGuard Base filter

### Issue Details

Steps to reproduce:
1. Turn on the Base filter
2. Go to any Spotify playlist on a free account (e.g. https://open.spotify.com/playlist/30ItA1hHyulAM5zsJnQuL4)
3. Press Play and skip a few song for an ad to appear

<details>
  <summary>Screenshot</summary>

  ![Screenshot](https://github.com/user-attachments/assets/724344fb-6e3b-468a-9a79-d1cb223fb56f)

</details>

Example of rules:
```
||media-us.amillionads.com/*.mp3$media,~xmlhttprequest,redirect=noopmp4-1s,domain=spotify.com
@@||media-us.amillionads.com/companion_images/$domain=open.spotify.com
```

### Actual Behavior

The ad is skipped but the player isn't working until you refresh the page.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by Alex-302** [comment]
*TODO*: after relase the version with fix of `$redirect` rules, remove `!+ NOT_PLATFORM(ext_chromium, ext_ff)` hints in Spotify rules group or revert PR.

**Comment by Yuki2718** [comment]
Another case https://github.com/AdguardTeam/AdguardFilters/issues/192915

**Comment by slavaleleka** [comment]
this issue was about MV2, and it was fixed
