### ISSUE TITLE
Is there a way to sync user filters across devices?

### ISSUE THREAD

**Issue by os9sur** [AdguardTeam/AdguardBrowserExtension#2915]
### Issue Details

As the number of user filtering rules increases with the use time, it is hoped that automatic backup can be achieved so that it can be synchronized across devices. Similar to tempermonkey, which can automatically back up to Google Drive, etc.

### Proposed solution

Hope to synchronize the user filter rule list across devices

**Comment by alexx7311** [comment]
@os9sur, hello! We're planning to implement [cloud sync](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2711) but we don't know when.
 Closing as a dup.
