### ISSUE TITLE
Hide Embeded HTML Window

### ISSUE THREAD

**Issue by Pete-w1rm** [AdguardTeam/AdguardBrowserExtension#2916]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

none

### Browser version

Chrome

### OS version

Windows 11 

### Ad Blocking

AdGuard Base filter

### Issue Details

Steps to reproduce:
1.
2.
3.

### Expected Behavior

go to http://www.kittyquarters.org
On the first page, scroll down to Events and Announcements.
Under that, an embedded HTML window should appear to permit the user to add their email address to our mailing list.

### Actual Behavior

It does not appear, and the window is blank when designing that page in WIX.
If I visit the site with any browser, the window is missing.
If I visit the site on a computer without AdGuard, the window appears.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by alexx7311** [comment]
@Pete-w1rm, hello! The window is blocked by `AdGuard Popups filter`, please report this website via the extension popup. You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/

**Comment by Pete-w1rm** [comment]
I reinstalled AdGuard and that fixed the issue.

 

Pete Chamalian, W1RM

***@***.***
