### ISSUE TITLE
AdGuard AdBlocker is not available in the Opera Addons store

### ISSUE THREAD

**Issue by maximtop** [AdguardTeam/AdguardBrowserExtension#2922]
The extension appears in the search results:
https://addons.opera.com/en-gb/search/?query=adguard
<img width="1460" alt="image" src="https://github.com/user-attachments/assets/f6640dbb-a0ff-4b50-a2fb-28c0541b66f5">

However, when clicking on the link, the page states that the extension cannot be found:
https://addons.opera.com/en-gb/extensions/details/adguard/
<img width="956" alt="image" src="https://github.com/user-attachments/assets/76cfb811-82e2-499b-a2ea-4938686f86b9">

Also, the extension can’t be accessed in the developer dashboard. In the Network tab of the developer tools, a 500 server error can be seen.

**Comment by maximtop** [comment]
@avl7771 @psliwka @r4fek, if any of you are reading this, could you please pass this message to the people responsible for the Add-ons store?

**Comment by maximtop** [comment]
Issue seems to be resolved.

**Comment by avl7771** [comment]
@maximtop we saw the message (all three of us as far as I can see ;)), this was an issue on the Opera addons store.

**Comment by maximtop** [comment]
@avl7771, thank you all for your quick response and actions.
