### ISSUE TITLE
How to change top left icon. When all icons are changed | How to fix icon not showing in menu

### ISSUE THREAD

**Issue by GeneralCodeStudios** [AdguardTeam/AdguardBrowserExtension#2930]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

Greetings! I have changed all icons and still on the UI or Settings page it displays the Adgaurd icon. In addition when the plugin is added to my chromium it shows the icon when pinned then the icon is invisible. Also, how could I remove the extension from going to page " chrome-extension://*****/undefined.html" upon installation as I've removed the page and its just saying it doesn't exist and I can't figure out how to make it not go there. So theses are my questions!

**Comment by GeneralCodeStudios** [comment]
So, what can I do @alexx7311

**Comment by GeneralCodeStudios** [comment]
@alexx7311 I'm so sorry. But I'm in need of assistance.

**Comment by alexx7311** [comment]
@GeneralCodeStudios, hello! Please describe in more detail what you are trying to do.
