### ISSUE TITLE
I already purchased Ad Block, but never installed it; how do i do so?

### ISSUE THREAD

**Issue by jigger833** [AdguardTeam/AdguardBrowserExtension#2935]

**Comment by jigger833** [comment]
I purchased Ad Block a few weeks ago, but never installed it; how do I do so now?

**Comment by jigger833** [comment]
This is the most non-user-friendly site I've ever dealt with!  It presumes both knowledge and familiarity. neither of which I have.

**Comment by alexx7311** [comment]
@jigger833, hello! If you purchased AdGuard Ad blocker licence you can go to AdGuard main page at https://adguard.com/en/welcome.html and choose the product that you need at the `Products` section
<details>
  <summary>Screenshot</summary>

  ![Screenshot](https://github.com/user-attachments/assets/cd8c405a-73f5-47c4-9247-4737999b67a7)

</details>

To activate the license you can use instructions from our knowledge base at https://adguard.com/kb/general/license/activation/

If you have any questions please don't hesitate to contact our support team at support@adguard.com
