### ISSUE TITLE
MV3 extension - custom proxy rule does not work in Microsoft Edge

### ISSUE THREAD

**Issue by SampeiNihira** [AdguardTeam/AdguardBrowserExtension#2938]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

5.0.65

### Browser version

Microsoft Edge latest version

### OS version

Win 10 x64

### Ad Blocking

AdGuard Base filter

### Annoyances

AdGuard Cookie Notices filter

### Language-specific

EasyList Italy

### What Tracking protection options do you have enabled?

Remove tracking parameters, Disable WebRTC

### Issue Details

Steps to reproduce:
1. Insert custom rule ||*^proxy.js
2. Open https://browserleaks.com/proxy

### Expected Behavior

See image with uBlock origin + custom rule:
![uBlock Origin](https://github.com/user-attachments/assets/2c433fed-6726-479e-93f4-b8fe21f33534)

### Actual Behavior

Image with AdGuard MV3
![AdGuard MV3](https://github.com/user-attachments/assets/5fbf1b16-d0b3-4f17-8452-c3e2f52626bd)

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

### Additional Information

I haven't tested whether the rule works in Chrome

**Comment by alexx7311** [comment]
@SampeiNihira, hello! I couldn't reproduce it on the lastest 5.0.78 beta.

<details>
  <summary>Screenshot</summary>

  ![Screenshot](https://github.com/user-attachments/assets/fbf8dafb-348c-4c7b-b2b0-8d8bfecdb8e6)

</details>

**Comment by SampeiNihira** [comment]
![1](https://github.com/user-attachments/assets/b8254e1c-1219-45f8-b320-93902f4bebd3)
Hi.
See if this aimmagine can help you.
I use the latest beta.
Could it be that the 3 proxy exceptions of the basic AG filter blocks the rule?

**Comment by alexx7311** [comment]
@SampeiNihira Not sure about Base filter but it may be the case that some rules are unblocking it. What if you try this one?
`||*^proxy.js^$important`

You can also try disablin all filters except for Base filter and use the user rule.

**Comment by SampeiNihira** [comment]
Yes,it works with the rule you wrote.
