### ISSUE TITLE
Open in anonymous window wont block the cookies popup at first load

### ISSUE THREAD

**Issue by x-rated** [AdguardTeam/AdguardBrowserExtension#2939]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

5.0.65

### Browser version

128

### OS version

Windows 11 24H2

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard Tracking Protection filter, AdGuard URL Tracking filter

### Social

AdGuard Social Media filter

### Annoyances

AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter

### Security

Online Malicious URL Blocklist, Phishing URL Blocklist, Scam Blocklist by DurableNapkin, uBlock Origin – Badware risks

### Other

AdGuard Experimental filter

### Language-specific

EasyList Czech and Slovak

### What Tracking protection options do you have enabled?

Block trackers, Remove tracking parameters, Hide your search queries, Ask websites not to track you, Hide Referrer from third parties, Remove X-Client-Data header

### Issue Details

Steps to reproduce:
1. visit https://www.techforum.cz/
2. right click on main logo in top left corner and click open in anonymous window
3. you can reload the website in anonymous window now to get rid of the cookies popup
4. dont close the anonymous window already opened and repeat step 2 again

### Expected Behavior

website should have cookies popup blocked at first load in anonymous window

### Actual Behavior

website doesnt have cookies popup blocked at first load in anonymous window

### Screenshots

<details><summary>screen recording</summary>

https://github.com/user-attachments/assets/072cf8a9-a23d-41aa-b008-f56723b4b866

</details>

### Additional Information

this behaviour can be fixed by adding this additional filter https://secure.fanboy.co.nz/fanboy-cookiemonster.txt

**Comment by alexx7311** [comment]
@x-rated, hello! Looks like it's the filtering issue, not the extension one. Let's have our Filters team look at this. 
I see the cookie warning with or without private mode.

Please report this website via the extension popup. You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/
