### ISSUE TITLE
Add support for the :style pseudo class syntax

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#294]
Based on:
https://github.com/AdguardTeam/AdguardForAndroid/issues/701

Review:
http://upsource.adguard.com/adguard-java-code/review/AJC-CR-8

We should also add pseudo classes validation.

**Two more things, specific to the browser extension:**
1. It is crucial to validate pseudo classes in Safari converter
2. Ignore `:style` pseudo class in Safari converter

**Comment by Mizzick** [comment]
Done
