### ISSUE TITLE
Scrollbar is gone after blocking ads on a website

### ISSUE THREAD

**Issue by martinysteen** [AdguardTeam/AdguardBrowserExtension#2946]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

4.4.22

### Browser version

Version 128.0.6613.138 (Official Build) (64-bit)

### OS version

Windows 11 Pro Version	23H2 OS build	22631.4169

### Ad Blocking

AdGuard Base filter

### Other

Filter unblocking search ads and self-promotion

### Language-specific

AdGuard French filter, AdGuard German filter, Dandelion Sprout's Nordic Filters

### Issue Details

Steps to reproduce:
1.Open https://seekingalpha.com/news/4149853-biggest-stock-movers-today-djt-intc-and-more?mailingid=36743321&messageid=2900&serial=36743321.16827&source=email_2900&utm_campaign=rta-stock-news&utm_content=link-1&utm_medium=email&utm_source=seeking_alpha&utm_term=36743321.16827
2.Apply user rules as in file attached
[adg_ext_settings_4.4.22_160924-121629.json](https://github.com/user-attachments/files/17011650/adg_ext_settings_4.4.22_160924-121629.json)
3.Annoying overlay (advertisement for upgrade) is gone, Top of content is visible (nice!) but scrollbar is gone
Using Ctrl_P (print pdf) creates all content, readable priview. 

### Expected Behavior

I wished Ctrl-Print was not necessary and instead a scrollbar could be used

### Actual Behavior

No scroll bar after removing advertisement

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by alexx7311** [comment]
@martinysteen, hello! This is filtering problem, not extension problem. Please report this website via the extension popup. You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/
