### ISSUE TITLE
Scriptlets exclusion matching is not working properly for rules with arguments

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#2947]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

4.4.22

### Browser version

Chrome 128.0.6613.138 (Official Build) (64-bit)

### OS version

Windows 10

### Ad Blocking

AdGuard Base filter

### Issue Details

Steps to reproduce:
1. Open the filtering log
2. Go to https://f2movies.life/movie/the-real-housewives-of-atlanta-season-7
3. Add exclusions for few `vidsrc.xyz` scripthet rules
4. Reload the page
5. Check if the rules applied

### Expected Behavior

`#@%#` rules must disable corresponding `#%#` rules.

### Actual Behavior

`#@%#` rules don't work.
It seems the same problem with `@@||f2movies.life^$jsinject`

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by SampeiNihira** [comment]
Hi,
I also did a same-test of the scriptlets but in AG MV3 5.0.78.
I unchecked the “disable WebRTC” feature.
I inserted this custom rule:

`#%#//scriptlet('nowebrtc')`

And then did a test here:

https://browserleaks.com/webrtc

If you close/open the browser or reload the tab it may happen that the rule does not work at a certain instant of time.

see images:

![1](https://github.com/user-attachments/assets/27585f1b-75ee-44a8-917b-a923f76650cc)

![2](https://github.com/user-attachments/assets/db965a4e-3688-4f80-81d7-c63dbd5006b5)


So I wonder but do the other scriptlets also have this problem?

Probably the issue deserves further investigation.

**Comment by maximtop** [comment]
Generally, scriptlet exclusions are working.  
Here is the rule:

```
example.org#%#//scriptlet('log', 'test')
```

It can be unblocked by one of these:

```
#@%#//scriptlet('log')
example.org#@%#//scriptlet('log')
example.org#@%#//scriptlet('log', 'test')
```

However, in some cases, they are not allowlisted. For example:

```
vidsrc.xyz#%#//scriptlet("abort-on-property-write", "glxopen")
#@%#//scriptlet("abort-on-property-write", "glxopen")
```

This needs to be investigated.
