### ISSUE TITLE
Many websites log you out when you enable Stealth Mode options (v2.4.2)

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardBrowserExtension#295]
Tested in Chrome. Used only Stealth Mode options enabled by default (http://screencast.com/t/hootjjkPuzsZ). 

Happened in vk.com, click.alfabank.ru (http://screencast.com/t/WRWK9UMhv), online.sberbank.ru, facebook.com etc.

**Comment by ameshkov** [comment]
Stealth mode postponed
