### ISSUE TITLE
The extension stopped working because of intersection of dynamic rules IDs

### ISSUE THREAD

**Issue by Timohasan** [AdguardTeam/AdguardBrowserExtension#2953]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

5.0.91

### Browser version

Chrome 129.0.6668.59

### OS version

Windows 10 Home

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard Tracking Protection filter, AdGuard URL Tracking filter

### Social

AdGuard Social Media filter

### Security

Online Malicious URL Blocklist

### Language-specific

AdGuard Russian filter, Estonian List

### What Tracking protection options do you have enabled?

Block trackers, Remove tracking parameters, Hide your search queries, Ask websites not to track you, Hide Referrer from third parties, Remove X-Client-Data header

### Issue Details

Steps to reproduce:
1.Updated to version 5.0.91 via browser.
2.
3.

### Actual Behavior

Does not block ads. The extension pop-up window is empty (no pause icon, no way to get to settings and statistics of blocked ads).

### Screenshots

<details><summary>Screenshot 1</summary>

<! [2024-09-19_193236](https://github.com/user-attachments/assets/b2633c99-26f3-4f2f-874b-f0671a9fbeb1)
 -->

</details>

**Comment by alexx7311** [comment]
@Timohasan, hello! Please go to chrome://extensions/ and enable Developer mode, then click on `service worker` on the extension tile.

<details>
  <summary>Screenshot</summary>

  ![Screenshot](https://github.com/user-attachments/assets/d1c8264a-0cd1-48b4-90e9-fe805e38e9b8)

</details>

Please copy entries from the console to a file and add it to a comment here.

**Comment by 105th** [comment]
@Timohasan can you please check update? we published new version with fix
