### ISSUE TITLE
Google Chrome “This extension may have been corrupted"

### ISSUE THREAD

**Issue by Kylgos** [AdguardTeam/AdguardBrowserExtension#2957]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

5.0.91

### Browser version

Google Chrome 129.0.6668.59

### OS version

Windows 10 22H2

### Ad Blocking

AdGuard Base filter

### Language-specific

AdGuard Spanish/Portuguese filter

### Issue Details

Steps to reproduce:
1. Install AdGuard extension for Chrome
2. Close Google Chrome
3. Open Google Chrome

### Expected Behavior

AdGuard is working properly without any warning.

### Actual Behavior

AdGuard extension for Chrome _sometimes_ (there is no concrete specification of when it happens) says when opening Google “**This extension may have been corrupted**” in red color.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

### Additional Information

This issue occurs in the latest versions of AdGuard.

**Comment by alexx7311** [comment]
@Kylgos, hello! Please go to chrome://extensions/ tab and enable Developer mode, then click on `service worker` on the extension tile.

<details>
  <summary>Screenshot</summary>

  ![Screenshot](https://github.com/user-attachments/assets/d1c8264a-0cd1-48b4-90e9-fe805e38e9b8)

</details>

Do you see any errors in the console of service worker? Please take a screenshot if you do.
Do you have any other adblocking extensions enabled in your browser? Please disable them if you do.

**Comment by alexx7311** [comment]
@Kylgos any updates?
