### ISSUE TITLE
Can't see bought films on YT

### ISSUE THREAD

**Issue by FictionFirst** [AdguardTeam/AdguardBrowserExtension#2959]
Hello

I have used ADguard Browser Extension for some time and have enjoyed it. Been using chrome browser on a chromebook as well as a winos 10. A week ago I suddenly couldn't watch films I had bought on Youtube, I got an error message saying can't play the film because of not having license for it. After turn with YT support with troubleshooting that didn't work. I turned off all the extensions and when I turned ADguard on the films couldn't be played. 
 Just want to mention this. I also noticed that chrome had an notification in the prefrence  > extension, that this extension was not going to be supported anymore.

**Comment by alexx7311** [comment]
@FictionFirst Hello! Please report this website via the extension popup. You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/

> Just want to mention this. I also noticed that chrome had an notification in the prefrence > extension, that this extension was not going to be supported anymore.

You can update the extension to the newest 5.0.97 version and you won't see this notification.
