### ISSUE TITLE
Edge mobile Unable to load rules

### ISSUE THREAD

**Issue by Jie-baobao** [AdguardTeam/AdguardBrowserExtension#2960]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

4.4.22

### Browser version

Edge Canary(mobile app)

### OS version

Android14

### Ad Blocking

AdGuard Base filter

### Issue Details

Steps to reproduce:
1.Developer mode installs Adguard
2.Keep loading rules
3.

### Actual Behavior

Keep loading rules，and It will never end.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by alexx7311** [comment]
@Jie-baobao, hello! Edge mobile doesn't support installation from Add-ons store yet, we'll add the support later.
Relevant issue: https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2773
