### ISSUE TITLE
Unable to add AdGuard Quick Fixes filter in MS Edge

### ISSUE THREAD

**Issue by SampeiNihira** [AdguardTeam/AdguardBrowserExtension#2963]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

5.0.97

### Browser version

Microsoft Edge latest version

### OS version

Windows 10 x64 Home

### Ad Blocking

AdGuard Base filter

### Annoyances

AdGuard Cookie Notices filter

### What Tracking protection options do you have enabled?

Remove tracking parameters, Hide your search queries

### Issue Details

Steps to reproduce:
1. It is possible to select the list of filters specified in the title
2. But the selection is not retained

### Expected Behavior

Obviously to be able to select and use AdGuard Quick Fixes filter

### Actual Behavior

See issue title

### Screenshots

![1](https://github.com/user-attachments/assets/796b7572-d82d-4ad9-93b5-bf3a5de6ed4f)

![2](https://github.com/user-attachments/assets/60eb38e3-4da2-4f80-acff-b3fa44c7a7c0)

<details><summary>Screenshot 1</summary>

</details>

**Comment by alexx7311** [comment]
@SampeiNihira, hello! You can use 4.4.22 extension from MS Edge store for now https://microsoftedge.microsoft.com/addons/detail/adguard-adblocker/pdffkfellgipmhklpdmokmckkkfcopbh

**Comment by SampeiNihira** [comment]
Thanks for the advice.

Certainly Microsoft Edge which has its own MS Store will have a longer time to disable MV2 extensions.

But considering that Edge is the preinstalled browser in Windows OSes,in my opinion,this and other problems that plague/afflict this browser should be fixed relatively quickly.

If of course there are no other Chromium-based browsers that have the usual Edge problem.

**Comment by SampeiNihira** [comment]
Fixed in AG. 5.0.138.

**Comment by slavaleleka** [comment]
duplicate:
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2985
