### ISSUE TITLE
Return option to check for updates for non-Chrome browsers

### ISSUE THREAD

**Issue by andris86** [AdguardTeam/AdguardBrowserExtension#2964]
### Issue Details

Recent update removed Check for Updates button in Filters menu. It was very useful, it was working fine all the time in Brave browser I'm using. 

I have read that due to some updates for Chrome it is no longer possible to maintain this function anymore in Chrome. But in Chrome only! This change is not affecting other Chromium browsers like Brave. Why do other Chromium browsers users have to suffer too?

I'm noticing that several days old issue is still affecting a specific website which was fixed in Filters repo several days ago. In other words, current filters my Adguard ext. is using are several days old and is not updating.

I really don't want to switch adblocking extensions but you leave me no choice if you don't return the Check for Updates button for non-Chrome users. 

### Proposed solution

Simply return Check for Updates button. The current design of this extension is more fit for MV3 version.

**Comment by maximtop** [comment]
Button was removed only for mv3 version extensions.

**Comment by maximtop** [comment]
Here are more details:
https://adguard.com/en/blog/adguard-browser-extension-mv3-release.html

The MV2 extension will remain available for some time, until Google decides to remove it. You can find it at this URL:
https://chromewebstore.google.com/detail/adguard-adblocker-beta/gfggjaccafhcbfogfkogggoepomehbjl

**Comment by alexx7311** [comment]
@andris86 You can do the following:
1. Download MV2 extension from https://uploads.adguard.org/chrome_4.4.22.zip
2.  Go to brave://extensions/ page and enable `Developer mode` in the top right of the page
3.  Drag and drop chrome_4.4.22.zip archive to brave://extensions/ page
