### ISSUE TITLE
Incorrect working of $third-party modifier in Safari

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#297]
Sample page:
https://www.tripadvisor.com/Hotel_Review-g60811-d93892-Reviews-Home2_Suites_by_Hilton_Baltimore_Downtown-Baltimore_Maryland.html
Images are blocked by the rule from Easylist China

```
||tripadvisor.com^$third-party
```

Image sample:
https://media-cdn.tripadvisor.com/media/photo-s/0b/b3/b1/a3/photo4jpg.jpg
This rule should not works on tripadvisor.com domain.
Screenshots:
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/16941178/8b07c3cc-4d5c-11e6-8410-828286a1fae9.png)

![image](https://cloud.githubusercontent.com/assets/15856304/16941188/95e21176-4d5c-11e6-9f70-3b590d5fb34f.png)
</details>

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardForSafari #104](https://github.com/AdguardTeam/AdGuardForSafari/issues/104) via [**ZenHub**](https://www.zenhub.com/)
