### ISSUE TITLE
Check for updates

### ISSUE THREAD

**Issue by milovir** [AdguardTeam/AdguardBrowserExtension#2970]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

5.0.97

### Browser version

Google chrome 129.0.6668.71

### OS version

Windows 11 version 24H2

### Ad Blocking

AdGuard Base filter, AdGuard Quick Fixes filter

### Privacy

AdGuard Tracking Protection filter

### Annoyances

AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Other Annoyances filter

### Security

Online Malicious URL Blocklist, Phishing URL Blocklist, Scam Blocklist by DurableNapkin, uBlock Origin – Badware risks

### Language-specific

AdGuard Russian filter, AdBlockID

### Issue Details

Steps to reproduce:
1. Check for updates
2.
3.

### Expected Behavior

In the all filters section there is no adguard update available on the google chrome browser extension.

### Actual Behavior

Revisited adguard extension in version 5.0.97 there is no update feature on all filters.

### Screenshots

<details><summary>Screenshot 1</summary>

https://prnt.sc/SB4BD9jMVw4G

</details>

**Comment by alexx7311** [comment]
Dup. of https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2964
