### ISSUE TITLE
The add-on is not updating

### ISSUE THREAD

**Issue by Apatityenergo** [AdguardTeam/AdguardBrowserExtension#2979]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

Версия 5.0.113

### Browser version

Версия 129.0.6668.71

### OS version

Windows 10

### Issue Details

The Adguard add-on cannot be updated. The refresh button is missing on the Filters page. There is also a missing button on the application form itself!
![1](https://github.com/user-attachments/assets/d067d1c9-16ca-47e8-a5ec-3fbe2d57b7ac)
![2](https://github.com/user-attachments/assets/d16c56f0-2f6a-41c4-a7bf-44e76736784f)

### Actual Behavior

Adguard add-on filters are not updated either manually or automatically.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by Apatityenergo** [comment]
Thank you!

**Comment by alexx7311** [comment]
Dup. of https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2964

**Comment by AlexandrPkhm** [comment]
Dup. of [#2964](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2964)
