### ISSUE TITLE
An invalid rule breaks the UI of the popup

### ISSUE THREAD

**Issue by prakharb5** [AdguardTeam/AdguardBrowserExtension#2989]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

4.4.22

### Browser version

Firefox 131

### OS version

Windows 11 22635.4225

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard Tracking Protection filter, AdGuard URL Tracking filter, Legitimate URL Shortener

### Social

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter, Fanboy's Annoyances

### Security

Online Malicious URL Blocklist

### What Tracking protection options do you have enabled?

Block trackers, Remove tracking parameters, Hide your search queries, Ask websites not to track you, Self-destruction of third-party cookies, Self-destruction of first-party cookies, Hide Referrer from third parties, Disable WebRTC

### Issue Details

Steps to reproduce:
1. Open any website
2. Check extension
3. Part of the extension UI is missing

### Expected Behavior

The extension should appear normally, with the site-specific toggle visible along with stats.

### Actual Behavior

 Site-specific toggle visible along with stats is missing in extension UI

### Screenshots

<details><summary>Screenshot 1</summary>

![image](https://github.com/user-attachments/assets/693371e4-a179-4829-8619-a7bbc640dd51)

</details>

### Additional Information

It works fine in Edge, but giving issues in Firefox.

**Comment by AlexandrPkhm** [comment]
@prakharb5, hello! Does the problem reproduce if you remove all custom filters and User rules or reset the settings?
We have a bug related to User rules where the popup looks the same if you enter a invalid rule, like #%#//scriptlet('foo' where the parenthesis at the end is missing.

**Comment by prakharb5** [comment]
Hello
I did not have any user rules added. Regardless, I reinstalled the extension to reset everything. And the extension started working properly.
After applying my prev settings and turning the filters on again, the UI again started breaking, but appeared after a few seconds. I played around with the filters to see which one was slowing it down, and I saw "Online Malicious URL Blocklist" had an impact.

**Comment by windwak3r** [comment]
@prakharb5 Please export your settings and attach them to a comment here.

**Comment by prakharb5** [comment]
The extension settings page freezes a lot, with everything taking a while to work.

PFA the file below:
[adg_ext_settings_4.4.22_141024-134421.json](https://github.com/user-attachments/files/17360946/adg_ext_settings_4.4.22_141024-134421.json)

**Comment by conuaunoc** [comment]
Also experiencing the same bug on Microsoft Edge on Windows 11

AdGuard Browser extension
Version 4.4.30
TSWebExtension v2.0.3
TSUrlFilter v3.0.5
Scriptlets v1.12.1
ExtendedCss v2.0.56

**Comment by conuaunoc** [comment]
![Screenshot 2024-10-15 at 10 27 07 PM](https://github.com/user-attachments/assets/6d742664-6bb0-4adc-b226-5fa7a2dd3712)

**Comment by prakharb5** [comment]
I was able to see that while filters are updating, the UI becomes very laggy and takes a while to load. Maybe some optimization can be done there?

There were a few errors in console:
![image](https://github.com/user-attachments/assets/f71ddd57-cf3c-4387-b683-454a5e4e3272)
