### ISSUE TITLE
Safari cannot block WebSocket connections with the Content Blocking API

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#299]
Example site:
https://nnmclub.to/
This WS is not blocked(only HTTP requests from this domain)
`wss://bgrndi.com:8041/`
Screenshot
<details>
![image](http://imagizer.imageshack.com/img922/363/qLqfZt.png)
</details>
The same issue is on mobile devices.

**Comment by ameshkov** [comment]
The easiest way to reproduce this is to use this DEMO and try to block echo.websocket.org: https://websocket.org/echo.html

**Comment by ameshkov** [comment]
Filed  a bug to webkit bugzilla:
https://bugs.webkit.org/show_bug.cgi?id=160159

Clearing milestone, let's wait for webkit guys now.

**Comment by tomasko126** [comment]
@Alex-302 @ameshkov WebSocket connections can finally be blocked in the newest version of the Safari Technology Preview browser.

**Comment by Alex-302** [comment]
Thanks, good news)

**Comment by ameshkov** [comment]
@tomasko126 thank you! Closing this issue.
