### ISSUE TITLE
HepsiBurada.com shopping site

### ISSUE THREAD

**Issue by ircserkan** [AdguardTeam/AdguardBrowserExtension#2996]
Even though I disabled it on HepsiBurada.com shopping site, some banners are blocked. I don't understand why it is blocked even though it is on the white list.

I looked into it a bit. *.com site banners come from *.net site, but some banners coming from here are not blocked, some are blocked.

(Written with translation, thank you for your understanding.)

**Comment by AlexandrPkhm** [comment]
Hello! Please report this website via the extension popup. You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/

**Comment by AlexandrPkhm** [comment]
@ircserkan Hello! Please report this website via the extension popup. You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/
