### ISSUE TITLE
ads starting to pop up again on youtube

### ISSUE THREAD

**Issue by shahipeg** [AdguardTeam/AdguardBrowserExtension#2997]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

Version 5.0.128

### Browser version

chrome 

### OS version

windows 10

### Ad Blocking

AdGuard Base filter

### Issue Details

Steps to reproduce:
i dont know what this means

### Actual Behavior

, when you start a video, it don't happen again but just only st the start of the video, it seem the ad blocker doesn't notice the ad 

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by senolfndk** [comment]
same problem

**Comment by AlexandrPkhm** [comment]
@shahipeg Hello! Please report this website via the extension popup. You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/
