### ISSUE TITLE
Extension is slow

### ISSUE THREAD

**Issue by GoldenBoot2** [AdguardTeam/AdguardBrowserExtension#2998]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

5.0.128

### Browser version

129.0.6668.100

### OS version

Windows 10

### Ad Blocking

AdGuard Base filter, AdGuard Quick Fixes filter, AdGuard Mobile Ads filter

### Privacy

AdGuard Tracking Protection filter, AdGuard URL Tracking filter

### Annoyances

AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter

### What Tracking protection options do you have enabled?

Block trackers, Remove tracking parameters, Hide your search queries, Ask websites not to track you, Hide Referrer from third parties, Remove X-Client-Data header, Disable WebRTC

### Issue Details

Steps to reproduce:
1.Open YouTube
2.Load any video

### Actual Behavior

Open YouTube, then play any video. The ads are loading, and the extension is a bit slow to remove them.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by windwak3r** [comment]
@GoldenBoot2, hello! What do you mean by 'a bit slow to remove them'? Are the ads not removed at all or are they visible for a while when you open youtube and then disappear?

**Comment by GoldenBoot2** [comment]
> @GoldenBoot2, hello! What do you mean by 'a bit slow to remove them'? Are the ads not removed at all or are they visible for a while when you open youtube and then disappear?

Ads visible for a while when open YouTube and then it disappear

**Comment by windwak3r** [comment]
@GoldenBoot2 Please go to AdGuard settings > Additional settings and make sure `Help with the development of AdGuard filters` is disabled.

Another reason for this problem could be the insufficient performance of your computer. Please try disabling all other extensions except AdGuard. Then disable Tracking protection module and all filters except AdGuard Base and Quick fixes filter in AdGuard settings. Did this help to solve the problem?

**Comment by GoldenBoot2** [comment]
> @GoldenBoot2 any updates?

I think it's an issue with my browser. I'm closing it. Thank you for the support.
