### ISSUE TITLE
Filters keep getting disabled at random time

### ISSUE THREAD

**Issue by Martini002** [AdguardTeam/AdguardBrowserExtension#2999]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

Version 4.4.22

### Browser version

Firefox 131.0.2 (64-bit)

### OS version

Windows 10

### Ad Blocking

AdGuard Base filter

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter

### Issue Details

Steps to reproduce:
1. enable filters

### Expected Behavior

Keep filters enabled

### Actual Behavior

Enabled the filters, after some time they gets disabled

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by windwak3r** [comment]
@Martini002, hello! This is a Firefox bug https://bugzilla.mozilla.org/show_bug.cgi?id=1885297.

You can help us fix it faster by following the steps listed in https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2775#issuecomment-2036577871 and posting your results in issue https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2775.

Thanks in advance!
