### ISSUE TITLE
Why latest adguard (v5.0) can't find in Edge extension store?

### ISSUE THREAD

**Issue by GuoBoy** [AdguardTeam/AdguardBrowserExtension#3000]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

Why latest adguard (v5.0) can't find in Edge extension store?

The latest adguard is v4.4.30 in edge store,that url is [link](https://microsoftedge.microsoft.com/addons/detail/adguard-%E5%B9%BF%E5%91%8A%E6%8B%A6%E6%88%AA%E5%99%A8/pdffkfellgipmhklpdmokmckkkfcopbh)

But I can get the latest v in Chrome Store.

**Comment by windwak3r** [comment]
@GuoBoy MV2 version of the extension with updated design is still being finalized. Chrome store now has MV3 version of the extension, but it's better to stay on MV2 version for now - to put it simply, it has better filtering.
Relevant blog article: https://adguard.com/en/blog/adguard-mv3-beta.html
