### ISSUE TITLE
youtube adv are blocked but unable see video, it  is getting black screen

### ISSUE THREAD

**Issue by Divanshu23438** [AdguardTeam/AdguardBrowserExtension#3005]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

5.0.138

### Browser version

130.0.6723.59

### OS version

-

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard Tracking Protection filter

### Social

AdGuard Social Media filter

### Issue Details

Steps to reproduce:
1.video is getting black screen when using AdGuard
2.
3.

### Actual Behavior

can't  see video video is getting black screen

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by windwak3r** [comment]
@Divanshu23438, hello! Please report this website via the extension popup. You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/
