### ISSUE TITLE
Unable to add custom filters

### ISSUE THREAD

**Issue by wyjtm** [AdguardTeam/AdguardBrowserExtension#3007]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

5.0.138

### Browser version

130.0.6723.59,64bit

### OS version

WINDOWS10

### Ad Blocking

AdGuard Base filter, AdGuard Quick Fixes filter

### Privacy

AdGuard Tracking Protection filter, AdGuard URL Tracking filter

### Annoyances

AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter

### Security

Online Malicious URL Blocklist

### Other

Filter unblocking search ads and self-promotion

### Language-specific

AdGuard Chinese filter, AdGuard German filter, AdGuard Japanese filter, AdGuard Russian filter, Polish Anti Adblock Filters

### What Tracking protection options do you have enabled?

Block trackers, Remove tracking parameters, Hide your search queries, Ask websites not to track you, Hide Referrer from third parties, Remove X-Client-Data header, Disable WebRTC

### Issue Details

Unable to add custom filters to AdGuard
After adding, it does not show that the addition was successful, and it says "You don't have any custom filters yet"

https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters.txt
https://raw.githubusercontent.com/uBlockOrigin/uAssets/refs/heads/master/filters/filters.txt

This filter can be added normally in version 4.4.30

### Actual Behavior

Unable to add custom filters

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by windwak3r** [comment]
Dup. of https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2962
