### ISSUE TITLE
Automatically activates the most suitable filter Automatically opens after closing

### ISSUE THREAD

**Issue by starlifezzz** [AdguardTeam/AdguardBrowserExtension#3013]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

4.4.30

### Browser version

Firefox 131.0.3

### OS version

Macos 13.7 (22H123)

### Ad Blocking

AdGuard Base filter

### Language-specific

AdGuard Chinese filter

### Issue Details

Steps to reproduce:
1.oepn brower
2. open web
3. Automatically activates the most suitable filter Automatically opens after closing，

### Expected Behavior

Automatically activates the most suitable filter Automatically opens after closing，
I Can sure  Closed this

### Actual Behavior

Automatically activates the most suitable filter Automatically opens

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by windwak3r** [comment]
@starlifezzz, hello! This is a Firefox bug. Can you help us out fixing it? Please do the following and post your results in https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2775
1) Open the Browser console (press Ctrl + Shift + J (or Cmd + Shift + J on a Mac))
2) Choose Multiprocess mode and leave the Browser console opened
<details>
  <summary>Multiprocess mode</summary>

  ![Multiprocess mode](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/114913601/aa00993e-6eb2-4a8f-8e65-1bb1b1408ba2)

</details>

3) Follow steps 1-3 from this [instruction](https://maximtop.notion.site/How-to-export-logs-from-the-background-page-in-the-extension-fb7e2fe23cb0451ea010672ce0570929) for Firefox to open background page in the extension (go to `about:addons` > `Debug Add-ons` > `Inspect`)
4) Type each of these commands one at a time in the console of the background page and press Enter after each one:

`await browser.storage.local.get('adguard-settings');`

`await browser.storage.local.get('adguard-settings-2');`

`await browser.storage.local.set({'adguard-settings': 'test'});`

`await browser.storage.local.set({'adguard-settings-2': 'test'});`

`await browser.storage.local.remove('adguard-settings');`

`await browser.storage.local.remove('adguard-settings-2');`

5) Right click on any entry in console of the background page and click "Save All Messages to File" (as per step 4 in the [instruction above](https://maximtop.notion.site/How-to-export-logs-from-the-background-page-in-the-extension-fb7e2fe23cb0451ea010672ce0570929))
6) Go to https://firefox-storage-test.glitch.me/ and **save the content of this page** to a txt file.
7) Go to the Events tab in Firefox at `about:telemetry#events-tab`
8) Type in "Find in Events" field "extensions.data" and take a screenshot, then "storageLocalError" and take a screenshot.

<details>
  <summary>Find in Events</summary>

  ![Find in Events](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/114913601/e488439d-4440-45db-bf8f-4f0156d763d9)

</details>

9) Navigate to the Browser console (from the step 1) and right click on any entry and click "Save All Messages to File".
10) Please attach all resulting files to the comment in this issue https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2775.

Thank you in advance for your help!
