### ISSUE TITLE
Ads on bihon.ro

### ISSUE THREAD

**Issue by LeventeCornea** [AdguardTeam/AdguardBrowserExtension#3024]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

4.4.41

### Browser version

Chrome 130

### OS version

Windows 10

### Issue Details

Steps to reproduce:
1.Go to www.bihon.ro
2.Have AdGuard enabled
3.Scroll down to the ad

### Expected Behavior

Ad is blocked

### Actual Behavior

Ad is still showed.

### Screenshots

<details><summary>Screenshot 1</summary>

![Screenshot 2024-11-03 173900](https://github.com/user-attachments/assets/0c5d854b-f727-4e0c-aa35-1bdb2f3c189c)

</details>

**Comment by alexx7311** [comment]
@LeventeCornea, hello! Please report this website via the extension popup. You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/
