### ISSUE TITLE
AdGuard Language Filter breaks MonsterInsights Java Loading

### ISSUE THREAD

**Issue by VinceS2** [AdguardTeam/AdguardBrowserExtension#3032]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

5.0.165

### Browser version

Chrome 130.0.6723.117

### OS version

Win 10 Pro

### Ad Blocking

AdGuard Quick Fixes filter

### Privacy

AdGuard Tracking Protection filter

### Social

AdGuard Social Media filter

### Security

Online Malicious URL Blocklist

### Issue Details

Steps to reproduce:
1.Look at Wordpress admin dashboard panel, see Monster Insights having java loading issue
2.Check both monsterinsights.com and the wordpress website are whitelisted in AdGuard
3.Go to filters and toggle language filters off
4. Hit F5 in admin panel and review MonsterInsights data! (took me a while to find this out!!!)
5. Study language filter list, see they are all on down to Dandelions Nordic, off from Ukraine and below
6. Wonder about this weird state of affairs, not even sure what the language filters are doing for me as only ever interested in English.
7. Resign to leaving Language filters off and making this report, so whatever the irksome bug somewhere in that mess can be weeded out :)

### Expected Behavior

default filters don't break really basic stuff, like Monster Insights

### Actual Behavior

It breaks access. Given this is a clear and repeatable issue, not bothering with screen shots etc, let me know if you want some more diagnostics. 

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by windwak3r** [comment]
@VinceS2, hello! Let's have our Filters team look at this first. Please report this website via the extension popup. You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/
