### ISSUE TITLE
The extension loads CPU every 30 seconds in Yandex browser

### ISSUE THREAD

**Issue by u07** [AdguardTeam/AdguardBrowserExtension#3036]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

v5.0.167 MV3

### Browser version

Yandex

### OS version

Windows 7 64

### Ad Blocking

AdGuard Base filter, AdGuard Quick Fixes filter

### Social

AdGuard Social Media filter

### Annoyances

AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter

### Other

Filter unblocking search ads and self-promotion

### Language-specific

AdGuard Russian filter

### Issue Details

AdGuard (background.js) запускается в фоне каждые 30 секунд и почти сразу закрывается. Процессор из-за этого постоянно нагружен на 50%, мешает работать. Браузер при этом может быть вообще свёрнут. Проверено с новым чистым профилем пользователя.

### Actual Behavior

-

### Screenshots

<details><summary>click here</summary>

![Безымянный 2](https://github.com/user-attachments/assets/3b71b831-a7f4-4ab1-ac29-5d33e2a023ca)
![Безымянный 3](https://github.com/user-attachments/assets/c6300976-74c2-4bf8-97bb-eb8f7325e09b)
![Безымянный 4](https://github.com/user-attachments/assets/84e269ee-868c-426b-892c-f73a5154bba6)
![Безымянный 5](https://github.com/user-attachments/assets/a257b751-2742-435a-b6b3-c464b64ac8aa)
![Безымянный 6](https://github.com/user-attachments/assets/b3b0f8d4-e32b-4758-a0a3-61d245fc41cd)
![Безымянный 7](https://github.com/user-attachments/assets/370ced85-8e97-4c02-87fc-ab61de491c95)

</details>

**Comment by Spok1** [comment]
Да, это определённо ненормально поведение!  У меня вопрос возникает только по поводу потребления памяти, вот это ненормально для плагина жрать как программа телеграма под виндоус! У тебя он даже больше потребляет, чем у меня! 400 против 426. Вот с этим также нужно бороться. Плагин с манифестом 2-й версии потреблял около 80-100 Мб, а этот как трактор!

**Comment by u07** [comment]
Ну если у него 150 тыщ правил, то это по 2 килобайта на правило. Многовато, конечно.. Но там может быть 150 тыщ скомпилированных regexp-ов, например

**Comment by u07** [comment]
Возможно, ключевое условие - оставить браузер в покое, а лучше свернуть. Тогда сработает какой-нибудь оптимизатор и прикончит adguard (ну а фигли, полгига памяти - не шутка). Он, соответственно, тут же возродится и начнёт ворошить 150К своих правил... Так это выглядит. Виноваты, считаю, оба. Кешировать надо такие вещи, холодный старт background.js не должен быть тяжёлым. Тогда и старт браузера облегчится, а это очень важная штука...

**Comment by u07** [comment]
Вот ещё скрин с совершенно другого компьютера. Тут, на минуточку, Core i7

![image](https://github.com/user-attachments/assets/f7fbb935-edf9-40d0-b79e-23f8b83c232f)

**Comment by windwak3r** [comment]
@u07, здравствуйте! Попробуйте, пожалуйста, обновить расширение до 5.0.170. Там мы выпустили фикс для утечки памяти, но с нагрузкой на ЦП тоже должно помочь.

**Comment by u07** [comment]
Кажется, починили! Пыхтит, не падает пока. Но потребление памяти выросло на 5%, хехе. Может, от версии фильтров зависит, конечно... Спасибо. Прям настроение улучшилось - хоть что-то на компьютере работает нормально)
