### ISSUE TITLE
Microsoft Edge prompt “This extension is broken”

### ISSUE THREAD

**Issue by zihao-0227** [AdguardTeam/AdguardBrowserExtension#3038]
Recently,I find Microsoft Edge prompt AdGuard “This extension is broken”. So I try Reload AdGuard. However, It don't work. Here are some information about my version.

**Microsoft Edge version:**版本 130.0.2849.80 (正式版本) (64 位)

**AdGuard version:**4.4.41

**operating system version：**
版本	Windows 11 IoT 企业版 LTSC
版本号	24H2
安装日期	‎2024/‎10/‎12
操作系统版本	26100.2314
体验	Windows Feature Experience Pack 1000.26100.32.0

I hope your can solve problem quickly!

**Comment by windwak3r** [comment]
@zihao-0227, hello! Do you have any other extensions installed? Please disable them and check if the problem persists.
Please go to edge://extensions/ and enable Developer mode, then open background.html of AdGuard extension.
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://github.com/user-attachments/assets/d7617f0f-0158-46d1-9b06-fbe5abd338a3)

</details>
Do you see any errors in the Console tab of background.html? Does reinstalling the extension solves the problem?

**Comment by zihao-0227** [comment]
Thank you to answer my question!

Well, The Microsoft Edge prompt “This extension is broken” again,here are the screen capture.

![{F23AAD1B-F217-4F97-BAA0-9F68FA7F44E3}](https://github.com/user-attachments/assets/5b41afca-e3b3-4848-a970-9c7a5a886ec1)

As you can see,I try to disable the other extensions. BUT at "Inspect views"(as "检查视图" in Chinese) ,It isn't have "background.html".

However, at my other PC and the other Microsoft Edge,It works fine. What should I do next？

![{DEFD5232-F505-4F70-A62E-2297AC29DB6F}](https://github.com/user-attachments/assets/699047d6-d6a8-4923-8e23-40626d63ad81)

**Comment by windwak3r** [comment]
@zihao-0227 Is there any order of actions you can take after which the extension will break? Or maybe you have noticed that the extension breaks for example when opening a browser or visiting a certain page? Does the problem reproduce if you disable all other extensions?

**Comment by windwak3r** [comment]
@zihao-0227 Please do the following:
1. Press `Win + R`.
2. Type `cmd` and press `Enter` to open the terminal.
3. Copy and paste one of the following commands into the terminal, depending on your installation.
32 bit Edge:
```
"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" --user-data-dir=C:\edge-debug --enable-logging --v=1
```
64 bit Edge:
```
"C:\Program Files\Microsoft\Edge\Application\msedge.exe" --user-data-dir=C:\edge-debug --enable-logging --v=1
```
4. Press `Enter` to run Edge browser and reproduce the problem.
5. **Remember the time** it was reproduced.
5. Go to `C:\edge-debug\` folder and copy `chrome_debug.log` to any location (note that each time you restart the browser, the logs will be rewritten).
6. Send us the file and **specify the time** the problem was reproduced at.

**Comment by zihao-0227** [comment]
Thank you to answer my question again!

OK,when AdGuard update to v.4.4.48,this problem is solved.Now I well

**Comment by zihao-0227** [comment]
OK,when the AdGuard update to v.4.4.48,this problem is solved.And I now I will close this problem.Thank you to answer my question again!
