### ISSUE TITLE
Removeparam rule doesn't work if it's in a custom filter, but works if it's in the User rules

### ISSUE THREAD

**Issue by SampeiNihira** [AdguardTeam/AdguardBrowserExtension#3041]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

5.0.168

### Browser version

Edge latest version

### OS version

Windows 10 Home x64

### Ad Blocking

AdGuard Base filter, AdGuard Quick Fixes filter

### Annoyances

AdGuard Cookie Notices filter

### Language-specific

EasyList Italy

### What Tracking protection options do you have enabled?

Remove tracking parameters, Hide your search queries

### Issue Details

Steps to reproduce:
1. Add from FilterLists custom filters "Actually Legitimate URL Shortener Tool” +
“ClearURLs for uBo (unofficial)”.

2. Open this link:
https://www.ebay.de/itm/186679189985?_trksid=p4247815.c101875.m1851&itmprp=cksum%3A1866791899851d87f28e6f894355904105bfee689f19%7Cenc%3AAQAJAAABgEnLatTXWXNAKPRnYtxVTXN2rJD11TMrqd%252Bc4NcqE%252BNGk6ejyqiKoKTZm%252BWiG7rLUKnmQT96yLmgza78VpCainYj%252Fcd7BbF%252F3JO7HSXt2n3iFYDbns8rSMT0idXbcmlMHWKniLK2o5tYYPmM8KWpVo95tWt2nTiQXMqmKRIMl5gAplMB1Ggx6kVqfXRetLAgGAr8tj3qIQFVusM3w2%252FTbqJcbms5AWlMLjBh33IT1VukCGrNibKsT%252F0qkwEeKrJ%252BqRhZKo%252F7BwNoK%252FJG9Di5oc8nbRdyqLnSmvEepcz27hw1plzGYkK3M%252FLS204Xl8d%252B%252BtIjQvpPKMqk7tOaYfRxOxqTc3Phjio2VBw5s0TdzIIxxR%252BteWen1ewuCZGgHTJtZr6usyBSJzML5fV2jMBQPa7DWTgyDixtoE50pm%252FEDlHegBefzvpwr4gPu1TxWSReqif%252BmyZ7w1jSjGESSDRCREZYTF84m9YVByxPQYOWWIrye4jSHSDhla3R%252B%252FoekGKQpA%253D%253D%7Campid%3APL_CLK%7Cclp%3A4247815&itmmeta=01J7YM3GS0ANMV3XSRX87J8ZNZ

3. There is no link shortening.

### Expected Behavior

The link needs to be shortened to this:

https://www.ebay.de/itm/186679189985

### Actual Behavior

Nothing happens.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by alexx7311** [comment]
There're 2 rules that remove parameters from this link:
```
||ebay.*^$removeparam=_trksid
://www.ebay.$document,removeparam=/^itm[a-zA-Z0-9].*$/
```
RegExp rule won't work in MV3, but the first rule should work.
For some reason it works in the User rules, but if it's in the Custom filters it doesn't work and should be investigated.

**Comment by windwak3r** [comment]
DNR implementation problem is causing this issue too https://github.com/w3c/webextensions/issues/468

Further discussions will be at https://github.com/AdguardTeam/AdguardBrowserExtension/issues/3034
