### ISSUE TITLE
Memory leak issue

### ISSUE THREAD

**Issue by fanmafeng571** [AdguardTeam/AdguardBrowserExtension#3043]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

5.0.168

### Browser version

chrome

### OS version

win10

### Issue Details

Steps to reproduce:
1.When the open label is not moved, the memory usage will increase with time. This problem has recently appeared. I hope to fix it as soon as possible
2.
3.

### Expected Behavior

1

### Actual Behavior

Memory leak

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by alexx7311** [comment]
@fanmafeng571 We'll fix it soon, thanks!

**Comment by alexx7311** [comment]
Closing as a dup. of https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2594
