### ISSUE TITLE
Failed Youtube Ad block on MS Edge MacOS Intel 

### ISSUE THREAD

**Issue by flyingbug2** [AdguardTeam/AdguardBrowserExtension#3044]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

4.4.41

### Browser version

Edge, 131.0.2903.51

### OS version

macOS 15.1

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard Tracking Protection filter, AdGuard URL Tracking filter

### Social

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter

### Security

uBlock Origin – Badware risks

### Language-specific

AdGuard Chinese filter, AdGuard German filter, AdGuard Japanese filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter, CJX's Annoyances List, Persian Blocker

### What Tracking protection options do you have enabled?

Block trackers, Remove tracking parameters, Hide your search queries, Ask websites not to track you, Self-destruction of third-party cookies, Hide Referrer from third parties, Remove X-Client-Data header, Disable WebRTC

### Issue Details

Steps to reproduce:
1. open any Youtube video on www.youtube.com
2.
3.

### Expected Behavior

no Ad

### Actual Behavior

YT detected Ad blocker, not showing videos.

### Screenshots

![screenshot-1732088589281](https://github.com/user-attachments/assets/313ad4c1-d82a-4c04-8ed0-0dc5d7728a63)

**Comment by flyingbug2** [comment]
I don't know the difference between MV2 vs. MV3, I just chose the MV2 when submitting this issue.

**Comment by windwak3r** [comment]
@flyingbug2, hello! Please report this website via the extension popup. You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/
