### ISSUE TITLE
Cannot remove "Rule limit Exceeded" warning

### ISSUE THREAD

**Issue by TotallyInformation** [AdguardTeam/AdguardBrowserExtension#3047]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

5.0.170

### Browser version

Vivaldi	7.0.3495.18 (Stable channel) (64-bit)

### OS version

Windows 11 26100.2454 (24H2)

### Ad Blocking

AdGuard Base filter, AdGuard Quick Fixes filter

### Privacy

AdGuard Tracking Protection filter, AdGuard URL Tracking filter

### Social

AdGuard Social Media filter

### Annoyances

AdGuard Mobile App Banners filter

### Security

Online Malicious URL Blocklist, Phishing URL Blocklist, Scam Blocklist by DurableNapkin, uBlock Origin – Badware risks

### What Tracking protection options do you have enabled?

Block trackers, Remove tracking parameters, Hide your search queries, Ask websites not to track you, Hide Referrer from third parties, Remove X-Client-Data header, Disable WebRTC

### Issue Details

Steps to reproduce:
1. Restart the browser - issue is present
2. Adjust the filters to be within the limits - issue still present
3. Restart the browser again - issue still present

### Expected Behavior

The rule limit warning should clear.

### Actual Behavior

The rule limit waring does not clear

### Screenshots

<details><summary>Screenshot 1</summary>
![image](https://github.com/user-attachments/assets/b90fa14f-f052-4fd7-8e09-04a6ea0da508)
</details>

<details><summary>Screenshot 2</summary>
![image](https://github.com/user-attachments/assets/e6adcfb7-795a-4a76-a6a7-139e5289b06c)
</details>

### Additional Information

Current rule stats:

```
Dynamic rules
User-added rules, such as [user rules](chrome-extension://bgnkhhnnamicmpeenaelnjfhikgbkllg/pages/options.html#/user-filter), [allowlisted websites](chrome-extension://bgnkhhnnamicmpeenaelnjfhikgbkllg/pages/options.html#/allowlist), [custom filters](chrome-extension://bgnkhhnnamicmpeenaelnjfhikgbkllg/pages/options.html#/filters?group=0), and [Quick Fixes filter](chrome-extension://bgnkhhnnamicmpeenaelnjfhikgbkllg/pages/options.html#/filters?group=1)
102 of 5000
Regex rules — included in the above
2 of 1000
Static rulesets
[Built-in filters](chrome-extension://bgnkhhnnamicmpeenaelnjfhikgbkllg/pages/options.html#/filters), such as Block annoyances or Language-specific filters
10 of 50
Static rules
Rules from [built-in filters](chrome-extension://bgnkhhnnamicmpeenaelnjfhikgbkllg/pages/options.html#/filters)
169309 of 329998
Regex rules — included in the above
228 of 1000
```

**Comment by windwak3r** [comment]
@TotallyInformation, hello! Please go to 'Rule limits' section and follow the steps from the warning.

If it didn't help, please reinstall the extension. Chrome has a bug that sometimes causes this issue even if you don't have any other ad-blocking extensions installed.
