### ISSUE TITLE
JS rules are not injected to small iframes

### ISSUE THREAD

**Issue by SlowMemory** [AdguardTeam/AdguardBrowserExtension#305]
This behavior is different from that of Adguard Windows. This happened to me when I was trying to apply a js rule to automatically click on a close button in an iframe. There are workarounds in my case so it is not critical, but it would be convenient if js rules are applied to small iframes too.

**Comment by ameshkov** [comment]
Have you tried the latest build? We know inject small part of CSS (domain-specific rules only)

**Comment by SlowMemory** [comment]
Hi, I was using this version : https://github.com/AdguardTeam/AdguardBrowserExtension/releases/tag/v2.4.1-beta
If it is already changed in the lastest version, this issue should be closed.

**Comment by ameshkov** [comment]
I thought you have built a new version on your own:)

No, this is an old version, we'll soon publish the next beta.

**Comment by SlowMemory** [comment]
It looks good in the lastest version, also flickering iframes are gone now!

**Comment by ameshkov** [comment]
Yep, that's true:)
