### ISSUE TITLE
Question about creating a blocking rule

### ISSUE THREAD

**Issue by Hipidan** [AdguardTeam/AdguardBrowserExtension#3062]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

示例URL  https://x.erplorer.cn/index.html?userId=123asdsd#/aaa/bbb

我的规则内容 :     ||*.erplorer.cn^$urlpather=/\?userId=[a-zA-Z0-9]+\/aaa\/bbb###规则元素

这个规则在页面https://x.erplorer.cn/index.html?userId=123asdsd#/aaa/ccc的时候也有效,如果让这个规则只在#/aaa/bbb有效

**Comment by alexx7311** [comment]
@Hipidan 

We currently have no $urlpather modifier in our filtering rules, so we're not entirely sure how to adjust your rule. It might be helpful to explore the documentation on advanced path modifiers, such as the one described here:
[AdGuard: Creating your own ad filters](https://adguard.com/kb/general/ad-filtering/create-own-filters/#non-basic-path-modifier).

Could you please provide more details about what you’re trying to achieve? For example, explain the exact conditions under which the rule should activate and what you want it to block or modify. With more information, we may be able to offer a more precise solution.

我们目前没有 $urlpather 修饰符，因此无法完全确定如何修改你的规则。你可以考虑查看高级路径修饰符方面的文档，例如以下链接中描述的内容：
[AdGuard: 创建自己的过滤器](https://adguard.com/kb/general/ad-filtering/create-own-filters/#non-basic-path-modifier)。

能否请你提供更多细节？例如，解释一下规则应在什么条件下生效，以及你期望它在这些情况下阻挡或修改什么内容。更多的详细信息将有助于我们为你提供更精确的解决方案。

**Comment by alexx7311** [comment]
@Hipidan any updates?

**Comment by alexx7311** [comment]
We'll close the issue for now. Please leave a comment if your question is still relevant.
