### ISSUE TITLE
Аддон не всегда корректно запускается при старте браузера!

### ISSUE THREAD

**Issue by Spok1** [AdguardTeam/AdguardBrowserExtension#3063]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

5.0.176

### Browser version

 Cent browser  основан на версии движка Chrome 118

### OS version

Windows 10

### Ad Blocking

AdGuard Base filter, AdGuard Quick Fixes filter

### Privacy

AdGuard Tracking Protection filter, AdGuard URL Tracking filter

### Annoyances

AdGuard Other Annoyances filter, AdGuard Widgets filter

### Language-specific

AdGuard Russian filter, AdGuard Ukrainian filter

### What Tracking protection options do you have enabled?

Block trackers, Remove tracking parameters, Hide your search queries, Ask websites not to track you, Hide Referrer from third parties, Remove X-Client-Data header, Disable WebRTC

### Issue Details

Steps to reproduce:

> Бывает не часто, поэтому это не воспроизвести так просто может быть.

1.Открыть браузер;
2.Увидеть надпись ошибка, где находятся выход в настройки.
3.

### Expected Behavior

Чтобы этого не происходило!

### Actual Behavior

Произошла ошибка в аддоне при старте браузера, при которой аддон не работал. Включение\выключение не помогало, только отключение и включение с последующей перезагрузкой браузера восстанавливало его работоспособность.

### Screenshots

<details><summary>Screenshot 1</summary>

![image](https://github.com/user-attachments/assets/6cb24a4b-f63a-40f1-a83d-2b2cebe4f986)

</details>

### Additional Information

На версии под манифестом 2 такого не происходило!

**Comment by windwak3r** [comment]
@Spok1, здравствуйте! А кроме этого сообщения проблема как-то проявляется? Фильтрация работает, попап расширения открывается?

**Comment by Spok1** [comment]
@windwak3r, как я указал в **Actual Behavior** ,  без перезагрузки в ним нельзя взаимодействовать.

**Comment by Spok1** [comment]
@windwak3r, как я указал в **Actual Behavior** ,  без перезагрузки в ним нельзя взаимодействовать.

**Comment by windwak3r** [comment]
@Spok1 Когда проблема повторится, сделайте, пожалуйста, следующее:
1. Перейдите на chrome://extensions/ и включите режим разработчика;
2. Нажмите на service worker на плитке расширения AdGuard;
3. Выберите там вкладку Console;
4. Нажмите правой кнопкой мыши на любой записи > Save as...;
5. Сохраните логи в любой папке и прикрепите их к сообщению в этой задаче.

**Comment by windwak3r** [comment]
Пока закроем эту задачу, как дубликат https://github.com/AdguardTeam/AdguardBrowserExtension/issues/3059
@Spok1 Если проблема повторится, оставьте, пожалуйста, комментарий в открытой задаче.
