### ISSUE TITLE
Yandex ads with dynamic ID are not blocked

### ISSUE THREAD

**Issue by Astalisa** [AdguardTeam/AdguardBrowserExtension#3070]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

 4.4.48

### Browser version

Fox

### OS version

12

### Ad Blocking

AdGuard Base filter

### Issue Details

1 яндекс 
2 результаты выдачи

### Expected Behavior

реклама яндекс не блокируется по скольку имеет динамический характер ID 

### Actual Behavior

реклама яндекс не блокируется по скольку имеет динамический характер ID 

### Screenshots

<details><summary>Screenshot 1</summary>

![Скриншот 22-12-2024 164729](https://github.com/user-attachments/assets/2c2aea4a-4ae6-4c61-b248-46af5dc4dee5)

</details>

**Comment by windwak3r** [comment]
@Astalisa, здравствуйте! Это похоже на проблему фильтров, а не расширения. Перейдите, пожалуйста, на сайт с рекламой, откройте попап расширения AdGuard и нажмите кнопку "Сообщить о проблеме", затем следуйте инструкциям на экране. Больше информации доступно в нашей базе знаний по ссылке: https://adguard.app/kb/guides/report-website/
