### ISSUE TITLE
Adguard is not resuming protection after visiting website with paused one

### ISSUE THREAD

**Issue by ZonD80** [AdguardTeam/AdguardBrowserExtension#3071]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

Latest

### Browser version

Chrome latest

### OS version

macos 15.2

### Issue Details

Steps to reproduce:
1. Place 2 websites to bookmarks tab.
2. Visit first website. Add it to exclusions list for adguard (pause proection)
3. Click on second website - protection will remain paused, it needs to be enabled by clicking on extension icon and then "enable"

### Expected Behavior

Protection should be enabled when visiting non-excluded website in the same tab

### Actual Behavior

Protection stays disabled, even if website is different

**Comment by windwak3r** [comment]
Dup. of https://github.com/AdguardTeam/AdguardBrowserExtension/issues/3020
