### ISSUE TITLE
Scriplet canvas seems not to work

### ISSUE THREAD

**Issue by SampeiNihira** [AdguardTeam/AdguardBrowserExtension#3074]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

5.0.178

### Browser version

Edge latest build

### OS version

Windows 10 Home x64

### Ad Blocking

AdGuard Base filter

### Annoyances

AdGuard Cookie Notices filter, AdGuard Other Annoyances filter

### Language-specific

EasyList Italy

### What Tracking protection options do you have enabled?

Remove tracking parameters, Hide your search queries, Disable WebRTC

### Issue Details

Steps to reproduce:
1.Insert scriptlet into user rules:
2.#%#//scriptlet('prevent-canvas')
3.Open [https://browserleaks.com/canvas](url)

### Expected Behavior

Any change in the test page that identifies a Canvas block

### Actual Behavior

No change to the test even with the scriptlet removed.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by maximtop** [comment]
The version of the scriptlets with ‘prevent-canvas’ has not been included in v5.0.178 yet.

**Comment by AdamWr** [comment]
If I'm not wrong, there is another issue.
Website uses iframe (`iframe#canvas-iframe`) with `sandbox="allow-same-origin"` attribute (and there is something like - `_el("#canvas-iframe").contentDocument.createElement("canvas")).getContext`) and it looks like that extension cannot inject scriptlets/JS rules to iframes with `sandbox` attribute.
So if I'm not mistaken, even if scriptlet will be available in extension, it will still not work.
>Blocked script execution in 'about:blank' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.
