### ISSUE TITLE
Firefox: Extension Does not save or delete settings or preferences, including filters, every time the browser is restarted

### ISSUE THREAD

**Issue by nasher87** [AdguardTeam/AdguardBrowserExtension#3078]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

4.4.48

### Browser version

Firefox 133.0.3

### OS version

Linux Manjaro KDE Plasma 24.2.1

### Ad Blocking

AdGuard Base filter, EasyList

### Privacy

AdGuard Tracking Protection filter, AdGuard URL Tracking filter, EasyPrivacy, Legitimate URL Shortener, Peter Lowe's Blocklist, Fanboy's Anti-Facebook List, Fanboy's Anti-thirdparty Fonts

### Social

AdGuard Social Media filter, Fanboy's Social Blocking List

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List, Fanboy's Annoyances, EasyList Cookie List

### Security

Online Malicious URL Blocklist, Phishing URL Blocklist, Scam Blocklist by DurableNapkin, uBlock Origin – Badware risks, NoCoin Filter List

### Other

Filter unblocking search ads and self-promotion, Fanboy's Anti-thirdparty Fonts, AdGuard DNS filter

### Language-specific

AdGuard Spanish/Portuguese filter

### What Tracking protection options do you have enabled?

Block trackers, Remove tracking parameters, Hide your search queries, Ask websites not to track you, Self-destruction of third-party cookies, Self-destruction of first-party cookies, Hide Referrer from third parties

### Issue Details

Steps to reproduce:

1. Start Firefox
2. Don`t block any publicity
3. Open the preferences
4. I Check the all de ad blocking and filters, it's deactivated
5. Import my old back-up to the pc, now is all active
6. The next day again, all the preferences, filters, white list and ad-block configuration is vanished

### Expected Behavior

All works

### Actual Behavior

Continue same

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by windwak3r** [comment]
@nasher87, hello! This is known Firefox bug https://bugzilla.mozilla.org/show_bug.cgi?id=1885297

You can help us fix it faster by following the steps listed in https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2775#issuecomment-2036577871 and posting your results in issue https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2775.

Then you can just reinstall the extension!
Thanks in advance!
