### ISSUE TITLE
Adguard does not show block items count when using *##+js(noeval) on website https://webbrowsertools.com/test-eval/

### ISSUE THREAD

**Issue by Kees1958** [AdguardTeam/AdguardBrowserExtension#3080]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

5.0.178

### Browser version

Brave

### OS version

Linux Mint 

### Issue Details

Steps to reproduce:
1. Add a custom rule
2. *##+js(noeval)
3. Surf to https://webbrowsertools.com/test-eval/
4. Push the test eval button

### Expected Behavior

Adguard icon showing count 1 (all filters are disabled)

### Actual Behavior

Adguard shows no block count on icon (with all filters disabled and jut 1 user rule)

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

### Additional Information

All filters are disabled, Adguard running with just 1 user rule

**Comment by windwak3r** [comment]
@Kees1958, hello! The extension doesn't count cosmetic rules.
