### ISSUE TITLE
Youtube doesnt work when adblocker is on! Theyr'e doing it again!

### ISSUE THREAD

**Issue by Aiiriiiiiiin** [AdguardTeam/AdguardBrowserExtension#3082]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

5.0.176

### Browser version

Chrome 131.0.6778.140

### OS version

Windows 10

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard Tracking Protection filter

### Issue Details

Steps to reproduce:
1. Just have it on, and youtube videos won't start as if your internet is bad.
2. ...
3. ...

### Expected Behavior

Youtube videos won't load, or get stuck a lot.

### Actual Behavior

Exactly what I wrote

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by windwak3r** [comment]
@Aiiriiiiiiin, hello! I couldn't reproduce the problem. Lets have our Filters team look at it first. 
Please report this website via the extension popup. You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/
