### ISSUE TITLE
Cleaning Chrome's cache with CCleaner breaks Stealth mode extension

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardBrowserExtension#309]
Stealth Mode extension works great, but when CCleaner or other cleaner cleans Chrome cache (only this element), the extension stops working until it'll being reinstalled.
I wonder if is possible to fix this "bug". Thanks a lot!

**1366198**

**Comment by ameshkov** [comment]
I suppose this issue should be created in Stealth Mode extension repo.
