### ISSUE TITLE
Add $generichide modifier support

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#31]
https://github.com/AdguardTeam/AdguardForWindows/issues/322

**Comment by Mizzick** [comment]
fixed

**Comment by atropnikov** [comment]
$generichide modifier not handled in Firefox extension, when css rules are registered via styleService.loadUserSheetByUri

**Comment by ameshkov** [comment]
Rules should be considered as generic ONLY if there is no "permittedDomains" restrictions.

Examples below.

**Generic**
```
###banner
~google.com,~yahoo.com###banner
```

**Not Generic**
```
google.com###banner
```

**Comment by Mizzick** [comment]
fixed

**Comment by gshumihin** [comment]
if "send statisticks" is on, in firefox works incorrect

**Comment by atropnikov** [comment]
fixed
