### ISSUE TITLE
Cloud sync protocol

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#315]
I could add this task to any repo as it concerns all our products. Anyway, let's do it here. First of all we should start with developing sync protocol.

Basically, sync is an import/export of AG settings from a file stored somewhere. We will allow user to sync through a number of "sync providers":
1. Chrome/FF storage sync
2. Dropbox/OneDrive/iCloud/Yandex.Drive/etc
3. Adguard personal account

The second challenge is the number of products we have. We should allow syncing between AG for Windows, Mac, Android, iOS and browser extensions. All are slightly different.

Also we should take into account, that different versions of the same product may be incompatible.

I suppose this documentation may be useful:
https://www.objc.io/issues/10-syncing-data/sync-case-study/
#### What I'd like to be synced

**User filter**
This is the easiest thing, we can simply sync it for all AG products.

**Whitelist**
AG for Windows, Mac and iOS do not have a whitelist (all exceptions are stored inside of the user filter). On the contrary, AG for Android and browser extensions have it. It is pretty easy to convert a whitelist entry into a filter rule. But here is a thing making everything complicated: "inverted whitelist" mode.

**Ad blocking filters**
The list of enabled filters.

However, there are some issues with it.
1. iOS and Safari has "Safari filter" enabled by default which we do not need in other AG versions. So we should allow user to choose filters which are not synced.
2. iOS, Safari and Android have "use mobile filters" option checked. It is not required in other products. I suppose we simply should not sync it.
3. iOS and Safari may hit the rules limit easily.
4. Custom filter subscriptions. Currently only AG for Windows allows adding custom filters by URL. So these filter subscriptions must be ignored by other products. However these subscriptions should be synced between Windows apps.

**Browsing security**
Browsing security options.

This is a paid feature in Android, so it should not be synced. Although, I suppose we could make sync a paid feature as well:).

**General settings**
It depends on AG version which settings are available for sync. For the browser extension it could be:
- Activate the most appropriate filters automatically
- Indicate the number of blocked ads on the Adguard extension icon
- Allow useful ads
- Invert whitelist

**Stealth mode**
Currently it is present in AG for Windows only. Please note that it depends on AG version which features are available.

**Extensions**
Currently it is present in AG for Windows only. Please note that it depends on AG version which features are available.

**Parental Control**
Currently it is present in AG for Windows only. **In fact I don't think we should sync this.**

**Comment by ameshkov** [comment]
@Mizzick I need a detailed protocol description along with the following answers:

1. How to resolve collisions?
2. How to solve the issues listed in the modules description?

**Comment by Mizzick** [comment]
I suggest we can store setting in json files, something like this:

> {
>   "version":"0.1",
>   "filters": {
>     "use-mobile-filters":false,
>     "enabled-filters": "1,2,3,5"
>   },
>   "user-filter": {
>     "rules": [
>       "||test1.org/$script",
>       "||test2.org/$script"
>     ]
>   },
>   "whitelist": {
>     "inverted": false,
>     "rules": [
>       "whitelist-rule"
>     ]
>   },
>   "general-settings": {
>     "allow-acceptable-ads": true,
>     "show-blocked-ads-count": true,
>     "autodetect-filters": true,
>     "safebrowsing-help": false
>   }
> }

**Comment by Mizzick** [comment]
Collisions should be solved server-side.
The issues listed in the modules description could be solved client-side, as well as issues with different products versions.
So I guess we can simply store everything possible in our sync-able file, and then the client apps could load and check what this particular application can use.

**Comment by Mizzick** [comment]
The issue I can see is how to authorise the access to this file, any proposals?

**Comment by ameshkov** [comment]
> Collisions should be solved server-side.

There is no server side when you sync through dropbox

**Comment by ameshkov** [comment]
> The issue I can see is how to authorise the access to this file, any proposals?

Every cloud file storage supports oauth. So our server-side implementation should do it as well.

**Comment by ameshkov** [comment]
**Question 1: Whitelist**
I don't see any solution or comment about the difference between AG products.

**Comment by ameshkov** [comment]
More than this, I simply see nothing about the differences between AG products. Suggested JSON-format simply cannot be used for sync between Windows and Android.

**Comment by Revertron** [comment]
For collision resolving we can include timestamp in the file, not some abstract version.

The options from Android version to include in the file:
1. Autostart with OS
2. Autoupdate filters
3. Update only over Wi-Fi
4. Block ads in all apps (premium feature)
5. App language
6. Notification icon (type)
7. Apps firewall settings:
    Enable filtering at all
    Block ads in this app
    Filter HTTPS in this app
    Allow mobile data
    Allow wi-fi data
    Allow mobile data with screen off
    Allow wi-fi data with screen off
    Notify user when we block this app (do not allow it's connections)
8. Enable firewall at all
9. Default firewall settings:
    Allow mobile data
    Allow wi-fi data
    Allow mobile with screen off
    Allow wi-fi with screen off
    Show firewall notifications
10. Enable HTTPS filtering (true/false)
11. HTTPS filtering mode (by whitelist or by blacklist)
12. Https blacklist (a list of domains)
13. Https whitelist (a list of domains)
14. Filtering method (hight quality, high speed, simplified)
15. Filtering mode (vpn/proxy)
16. Manual or automatic (with root) proxy
17. Local proxy port
18. Outbound proxy settings (http, socks4, socks5 like in Android itself, with ip, port, login/password)
19. Logging level: Default, Http requests, Everything, Errors only
20. Update channel: Release/Beta
21. Advanced settings:
    pref.proxy.block.ipv6
    pref.splash.enabled
    pref.vpn.disable.pause
    pref.vpn.dns (list of dns servers)
    pref.vpn.ipv4.force.complex
    pref.vpn.ipv4.force.default
    pref.vpn.ipv4.routes.excluded
    pref.vpn.ipv6.bypass
    pref.vpn.ipv6.disable
    pref.vpn.ipv6.force
    pref.vpn.tun.mtu

Seems that it is all...

**Comment by ameshkov** [comment]
Oh, I suppose that some of these settings simply cannot be synced.
For instance HTTPS filtering and such.

**Comment by Revertron** [comment]
But they need to be written to that file.

**Comment by Mizzick** [comment]
Yeap, I think we should collect all the settings, cause it could be synced between different user's devices on one platform.

**Comment by Mizzick** [comment]
Updated list with android settings:

> {
>   "timestamp":"1472817032841",
>   "filters": {
>     "use-mobile-filters":false,
>     "enabled-filters": [
>       {
>         "id": 1
>       }, {
>         "id": 2
>       },
>       {
>         "url":"http://filter-url"
>       }
>     ]
>   },
>   "user-filter": {
>     "rules": [
>       "||test1.org/$script",
>       "||test2.org/$script"
>     ]
>   },
>   "whitelist": {
>     "inverted": false,
>     "rules": [
>       "whitelist-rule"
>     ]
>   },
>   "general-settings": {
>     "allow-acceptable-ads": true,
>     "show-blocked-ads-count": true,
>     "autodetect-filters": true,
>     "safebrowsing-help": false,
>     "app-language": "en-Gb",
>     "os-autostart": true,
>     "autoupdate-filters": true,
>     "update-only-over-wi-fi": true,
>     "block-ads-all-apps": true,
>     "log-level": "default",
>     "update-channel": "release"
>   },
>   "firewall-setting": {
>     "enable-firewall": true,
>     "default-app-settings": {
>       "enable-filtering": true,
>       "enable-https-filtering": true,
>       "allow-mobile-data":true,
>       "allow-wi-fi-data":true,
>       "allow-mobile-with-screen-off":true,
>       "allow-wi-fi-with-screen-off":true,
>       "show-firewall-notifications":true
>     },
>     "apps-settings":[
>       {
>         "app-id": "test-app-identifier",
>         "settings": {
>           "enable-filtering": true,
>           "enable-https-filtering": true,
>           "allow-mobile-data":true,
>           "allow-wi-fi-data":true,
>           "allow-mobile-with-screen-off":true,
>           "allow-wi-fi-with-screen-off":true,
>           "show-firewall-notifications":true
>         }
>       }
>     ]
>   },
>   "android-specific-settings": {
>     "notification-icon-type": "default",
>     "https-settings": {
>       "enable-https-filtering": true,
>       "https-filtering-mode": "blacklist",
>       "https-blacklist": [
>         "blacklist-domain-one"
>       ],
>       "https-whitelist": [
>         "whitelist-domain-one"
>       ]
>     },
>     "filtering-method": "quality",
>     "filtering-mode": "vpn",
>     "proxy-mode": "manual",
>     "proxy-port": "8080",
>     "outbound-proxy-settings": "settings-text",
>     "advanced-settings": {
>       "pref.proxy.block.ipv6": "",
>       "pref.splash.enabled": "",
>       "pref.vpn.disable.pause": "",
>       "pref.vpn.dns": [],
>       "pref.vpn.ipv4.force.complex": "",
>       "pref.vpn.ipv4.force.default": "",
>       "pref.vpn.ipv4.routes.excluded": "",
>       "pref.vpn.ipv6.bypass": "",
>       "pref.vpn.ipv6.disable": "",
>       "pref.vpn.ipv6.force": "",
>       "pref.vpn.tun.mtu": ""
>     }
>   }
> }

**Comment by Stillness-2** [comment]
Settings from MacOS:

- "Activate filters automatically" (autodetect-filters)
- List of the active filters
- "Use Adguard Assistant"
- "Use Adguard Popup Blocker"
- "Use Web of Trust extension"
- SSL Exceptions
- User filter rules
- List of filtered Applications

Settings from iOS:

- List of the active filters
- "Use Simplified Filters"
- "Use Adguard Assistant"
- "Use Adguard Popup Blocker"
- "Use Web of Trust extension"
- SSL Exceptions
- User filter rules
- List of filtered Applications

**Comment by Stillness-2** [comment]
Settings from MacOS:

- "Activate filters automatically" (autodetect-filters)
- List of the active filters
- Whitelist
- "Use Adguard Assistant"
- "Use Adguard Popup Blocker"
- "Use Web of Trust extension"
- "Filter https protocol"
- SSL Exceptions
- User filter rules
- "Automatically filter applications"
- List of filtered Applications
- "Use Adguard as an http proxy"
- Proxy port

Settings from iOS:

- List of the active filters
- "Use Simplified Filters"
- "Auto Update over WI-FI only"
- Whitelist
- User filter rules
- Adguard DNS server type (standart, family, etc)

**Comment by Mizzick** [comment]
list with android, osx, ios and browser extension settings:

> {
>   "timestamp":"1472817032841",
>   "filters": {
>     "use-mobile-filters":false,
>     "enabled-filters": [
>       {
>         "id": 1
>       }, {
>         "id": 2
>       },
>       {
>         "url":"http://filter-url"
>       }
>     ]
>   },
>   "user-filter": {
>     "rules": [
>       "||test1.org/$script",
>       "||test2.org/$script"
>     ]
>   },
>   "whitelist": {
>     "inverted": false,
>     "rules": [
>       "whitelist-rule"
>     ]
>   },
>   "general-settings": {
>     "allow-acceptable-ads": true,
>     "show-blocked-ads-count": true,
>     "autodetect-filters": true,
>     "safebrowsing-help": false,
>     "app-language": "en-Gb",
>     "os-autostart": true,
>     "autoupdate-filters": true,
>     "update-only-over-wi-fi": true,
>     "block-ads-all-apps": true,
>     "log-level": "default",
>     "update-channel": "release",
>     "use-adguard-assistant": true,
>     "use-adguard-popup-blocker": true,
>     "use-wot-extension": true,
>     "ssl-exceptions": []
>   },
>   "firewall-setting": {
>     "enable-firewall": true,
>     "default-app-settings": {
>       "enable-filtering": true,
>       "enable-https-filtering": true,
>       "allow-mobile-data":true,
>       "allow-wi-fi-data":true,
>       "allow-mobile-with-screen-off":true,
>       "allow-wi-fi-with-screen-off":true,
>       "show-firewall-notifications":true
>     },
>     "apps-settings":[
>       {
>         "app-id": "test-app-identifier",
>         "settings": {
>           "enable-filtering": true,
>           "enable-https-filtering": true,
>           "allow-mobile-data":true,
>           "allow-wi-fi-data":true,
>           "allow-mobile-with-screen-off":true,
>           "allow-wi-fi-with-screen-off":true,
>           "show-firewall-notifications":true
>         }
>       }
>     ]
>   },
>   "android-specific-settings": {
>     "notification-icon-type": "default",
>     "https-settings": {
>       "enable-https-filtering": true,
>       "https-filtering-mode": "blacklist",
>       "https-blacklist": [
>         "blacklist-domain-one"
>       ],
>       "https-whitelist": [
>         "whitelist-domain-one"
>       ]
>     },
>     "filtering-method": "quality",
>     "filtering-mode": "vpn",
>     "proxy-mode": "manual",
>     "proxy-port": "8080",
>     "outbound-proxy-settings": "settings-text",
>     "advanced-settings": {
>       "pref.proxy.block.ipv6": "",
>       "pref.splash.enabled": "",
>       "pref.vpn.disable.pause": "",
>       "pref.vpn.dns": [],
>       "pref.vpn.ipv4.force.complex": "",
>       "pref.vpn.ipv4.force.default": "",
>       "pref.vpn.ipv4.routes.excluded": "",
>       "pref.vpn.ipv6.bypass": "",
>       "pref.vpn.ipv6.disable": "",
>       "pref.vpn.ipv6.force": "",
>       "pref.vpn.tun.mtu": ""
>     }
>   },
>   "ios-specific-settings": {
>     "use-simplified-filters": true,
>     "filtering-apps": []
>   }
> }

**Comment by ameshkov** [comment]
@Mizzick I don't like it. It just not an answer to the questions I've listed above.

Let me quote some of them.

> Also we should take into account, that **different versions of the same product may be incompatible**.

I see nothing about versions compatibility here.

> How to resolve collisions?

I need a clear answer.

**Comment by ameshkov** [comment]
I suppose we need to discuss it in person before moving on, alert me when you are ready.

**Comment by Mizzick** [comment]
https://gist.github.com/Mizzick/e954d1be3e2d51d84db314c00a6a7530

**Comment by ameshkov** [comment]
Let's continue work on cloud sync feature

**Comment by ameshkov** [comment]
Interface **examples:**
```
var SyncService = {
    syncSettings: function() {....},
    setSyncProvider: function(syncProvider) {....}
}

var SyncProvider = {
   get: function(fileName, callback) {},
   save: function(fileName, data, callback) {}
}
```

You can start with the simple **file**-based implementation.

**Comment by ganja24** [comment]
When is iCloud sync version of Adguard Pro going to be released?

**Comment by vbagirov** [comment]
Can we also give users an option to store several settings profiles in the personal account and switch between them?

**Comment by ameshkov** [comment]
@vbagirov I guess this could be implemented on the server side when we finally get to it.

**Comment by snhv** [comment]
> Browsing security
Browsing security options.

This is a paid feature in Android, so it should not be synced. Although, I suppose we could make sync a paid feature as well:).
> 
Please make sync a paid feature! I, as a subscribed user, am not happy when you keep releasing feature to free users. 

Please also consider make browsing security a paid feature, like in Android, as well.

Thanks.

**Comment by snhv** [comment]
> Basically, sync is an import/export of AG settings from a file stored somewhere. We will allow user to sync through a number of "sync providers":
> Chrome/FF storage sync
> Dropbox/OneDrive/iCloud/Yandex.Drive/etc
> Adguard personal account

Webdav would be nice. I personally use [pCloud cloud storage](https://stacksocial.com/sales/pcloud-premium-lifetime-subscription?rid=3685011&utm_campaign=CopyLink&utm_medium=ProductPage&utm_source=ReferralProgram) (note: referral link) which is excellent.

**Comment by AnthonyBe** [comment]
> We should cover:
Sync through Chrome/Safari(iCloud)/Firefox Sync.
Sync through Dropbox/Google Drive.

Please include OneDrive in cloud sync providers.

Also, something to consider, Edge browser is now available on most platforms; Android (phone and tablet), iOS (iPhone and iPad), and Windows.

**Comment by mrzool** [comment]
Hello, has this been implemented? I don't see the feature mentioned anywhere (Adguard nor Adguard pro).

User rules are a labor of love usually spanning years — they should get saved and synchronized by default.

**Comment by snhv** [comment]
No. What I resort to do is to create a repository for your list right here on Github. Then have AdGuard subscribe to that list. I'm able to do that with AdGuard Android and browser extension, but weirdly enough, can't figure out how with Windows desktop version.

**Comment by mrzool** [comment]
That's a cool workaround @snhv, thanks for sharing. Still, this should be a native feature...  Could be as simple as giving the opportunity to load the rules from a plain text file. Dropbox/iCloud/Gdrive would take care of the rest.

**Comment by ameshkov** [comment]
> but weirdly enough, can't figure out how with Windows desktop version

Hm, but why so? You can add custom lists there as wel

**Comment by snhv** [comment]
> Hm, but why so? You can add custom lists there as well

Oh just tried again and now I can. I swear when I tried 2 weeks ago (v7.3), the "Install" button just greyed out... Sorry for the confusion.

**Comment by AJolly** [comment]
But this wont sync userscripts, just the main rules
