### ISSUE TITLE
Wrong rule is constructed by the dev tools

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#324]
![bournemouth echo news sport leisure bournemouth air festival jobs homes dorset snow schools 2016-08-11 12-32-42](https://cloud.githubusercontent.com/assets/5947035/17584554/c21ea82e-5fbf-11e6-82a4-c80b53c53893.png)

**Comment by Mizzick** [comment]
So what is wrong? Unnecessary [id=".."]?

**Comment by ameshkov** [comment]
Of course, why id two times

**Comment by Mizzick** [comment]
Fixed
