### ISSUE TITLE
Palemoon requires "style" object properties to be camelCase 

### ISSUE THREAD

**Issue by gshumihin** [AdguardTeam/AdguardBrowserExtension#328]
Issue example:

* Rule `lenta.ru#$#.first-item h2:has(time) { font-size: 128px; }` doesn't work in palemoon
* Rule `lenta.ru#$#.first-item h2:has(time) { fontSize: 128px; }` works fine

**Comment by ameshkov** [comment]
Moved to ExtendedCss repo:
https://github.com/AdguardTeam/ExtendedCss/issues/5
