### ISSUE TITLE
Опечатка в версии FireFox на странице релизов.

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardBrowserExtension#329]
На странице [релизов](https://github.com/AdguardTeam/AdguardBrowserExtension/releases), в разделе FireFox пишется: **Firefox (version 30 or newer)**. Но уже с версии Adguard 2.3.6b на странице [дополнений](https://addons.mozilla.org/en-US/firefox/addon/adguard-adblocker/versions/?page=1#version-2.3.6-beta) FireFox требуется версия **38.0 and later**. Исправьте, пожалуйста.

**Comment by Mizzick** [comment]
Спасибо, исправили.
