### ISSUE TITLE
Make filter rule text box editable

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardBrowserExtension#331]
При вызове опции "Заблокировать рекламу на сайте" появляется окно "Блокировка элемента". Нажимаем "Расширенные настройки" и, чуть ниже, появляется текстовая строка с составленным фильтром.
 Если в этой строке начать редактировать мышью: например выделить что-нибудь и удалить, то **второй щелчок в этой строке** (например для удаления другого куска текста) **возвращает строку к первоначальному виду**, т.е. всё что было отредактировано пропадает и возвращается к тому виду как после нажатия "Расширенные настройки".
 Если редактировать фильтр **клавиатурой** и **не нажимать после этого мышкой** в текстовое поле, то текст фильтра сохраняется отредактированным.
 Пожалуйста, разрешите бедным мышечникам полноценный мазохизм :) .

**UPD**
![issue 331 adguardteam adguardbrowserextension 2016-08-29 13-49-53](https://cloud.githubusercontent.com/assets/5947035/18049228/98589f48-6def-11e6-976b-f7c023d87b30.png)

**Comment by ameshkov** [comment]
Полностью согласен, обновил title и добавил скриншот.

**Comment by XX-J** [comment]
Снова такая же проблема
 +
 не срабатывает контекстное меню по правой кнопке мыши на выделенном тексте
 +
 сбрасывается редактирование (с помощью клавиатуры) после предварительного просмотра.
___________________________________________________
Mozilla Firefox v50.0.2 (Win7SP1) - Adguard v2.9.2 (legacy)

**Comment by vozersky** [comment]
Повторил в Chrome 67

**Comment by Mizzick** [comment]
@4-life  pls take a look

**Comment by 4-life** [comment]
По ТЗ данная строка не редактируема и не парсится

**Comment by 4-life** [comment]
fixed by https://github.com/AdguardTeam/AdguardAssistant/commit/57e1b7bebe1425217b2adbf7ae3a85a1414170ce
