### ISSUE TITLE
WebSocket connections can't be blocked in FF Nightly

### ISSUE THREAD

**Issue by gshumihin** [AdguardTeam/AdguardBrowserExtension#334]
http://free-torrents.org/ looks like that:
<img src="http://content.screencast.com/users/shumegor/folders/Jing/media/a3fb3e5e-b933-4b22-a205-4f0117591c9d/00001351.png" width="300">

**Comment by Mizzick** [comment]
Isn't this a rules problem?

**Comment by ameshkov** [comment]
Relevant bug report:
https://bugzilla.mozilla.org/show_bug.cgi?id=1299766

**Comment by ameshkov** [comment]
Done
