### ISSUE TITLE
https://thoaimedia.com/save/ they have a adblock detector service called https://blockadblock.com

### ISSUE THREAD

**Issue by dyingjedi** [AdguardTeam/AdguardBrowserExtension#335]
Message pops up on many sites now. with this message.

Welcome!
It looks like you're using an ad blocker. That's okay. Who doesn't?
But without advertising-income, we can't keep making this site awesome.
I understand, I have disabled my ad blocker. Let me in!

http://prntscr.com/cawya0

https://thoaimedia.com/save/ they have a adblock detector service called https://blockadblock.com

http://prnt.sc/cax77a 

http://image.prntscr.com/image/6162af27bed341c5b99326034e830c6a.png

**Comment by ameshkov** [comment]
@Alex-302 could you please take a look?

@dyingjedi it would be easier if you report such issues directly to https://github.com/AdguardTeam/AdguardFilters

**Comment by Alex-302** [comment]
@dyingjedi 
please check this rule:
```
@@||thoaimedia.com^$generichide
```
Added to English filter.

**Comment by worldsdream** [comment]
I just checked the website, all good now.

issue can be closed
