### ISSUE TITLE
Memory leaks when using Adguard extension on Spotify web player

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardBrowserExtension#339]
> I got a memory leak and stuck screen when using Adgurd with Spotify web play.
> When I disable Adgurd on Spotify web player it works perfectly.

![image](https://cloud.githubusercontent.com/assets/15856304/18120837/b7ba866c-6f2f-11e6-9321-1b838d15ecd6.png)

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/18120849/c65dd14c-6f2f-11e6-943b-58644558b244.png)

**Comment by evgeniy-ADG** [comment]
The same issue at my end. Both extension in Chrome and the standalone version for Mac installed. Spotify web player crashes wneh you listen for 5-6 songs. I was not sure if it's related to Adguard, but it seems to be related.

**Comment by ameshkov** [comment]
@evgeniy-ADG is it related to Mac version or just to the extension?

**Comment by evgeniy-ADG** [comment]
I can't reproduce it now on another Mac, will try again later on the machine I was using at that time.

**Comment by evgeniy-ADG** [comment]
OSX 10.11.3
Chrome 52.0.2743.116 (64-bit)
Extension  2.4.10

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/18362226/ec7d5808-75d2-11e6-9f48-97a93fdfa175.png)

**Comment by evgeniy-ADG** [comment]
I believe the Social media filter causing this. Seems to work fine once you disable it.

**Comment by ameshkov** [comment]
@evgeniy-ADG это легко повторить?

**Comment by evgeniy-ADG** [comment]
Не очень.

**Comment by ameshkov** [comment]
Cannot reproduce
