### ISSUE TITLE
Statistics on the extended CSS element hiding filters 

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#343]
Even if user turns on "send filters usage stats" we do not collect it for extended CSS filters.

The question is why, in theory it is possible.

**Comment by Mizzick** [comment]
```
var applyStyle = function (element, style) { 
     for (var prop in style) {

            // Apply this style only to existing properties
            // We can't use hasOwnProperty here (does not work in FF)
            if (typeof element.style.getPropertyValue(prop) !== "undefined") {
                var value = style[prop];

                // First we should remove !important attribute (or it won't be applied')
                value = value.split("!")[0].trim();
                element.style.setProperty(prop, value, "important");
            }
        }
    };
```

Because we cut out everything after '!important'.
But if the subject option is enabled styles look like this:
`::content #Ad2 { display: none!important; background-image: url('chrome-extension://jpidmbdnmbbkpmiimchnleiibmogfepo/elemhidehit.png#1%3B%23%23%23Ad2') !important;}
`

**Comment by Mizzick** [comment]
`display: none !important; background-image: url("chrome-extension://jpidmbdnmbbkpmiimchnleiibmogfepo/elemhidehit.png#2%3Bfacebook.com%23%23div%5Bid%5E%3D%22hyperfeed_story_id%22%5D%5B-ext-has%3D%22a.uiStreamSponsoredLink%22%5D") !important;`

this hidden element style from facebook.

**Comment by Mizzick** [comment]
And then as I can see it's properly handled in filters-hit.js.
All tested in Chromium 54.0.2792.0 (64-bit).

**Comment by ameshkov** [comment]
What about unit tests?

**Comment by Mizzick** [comment]
I think it's too complex for unit tests.

**Comment by ameshkov** [comment]
> I think it's too complex for unit tests.

Why? What I am talking about is not **applying styles**, but generating CSS with bg image.

**Comment by Mizzick** [comment]
What's the point of this test? It's just an other style property, we already have two cases like this in https://github.com/AdguardTeam/ExtendedCss/blob/master/test/extended-css/test-extended-css.js
Check 3 and 9.

**Comment by ameshkov** [comment]
This is not about testing `ExtendedCss` module.

I am talking about testing "buildCss" and "buildCssHits" methods.

**Comment by Mizzick** [comment]
ahhh, ok, got it

**Comment by Mizzick** [comment]
Addded
