### ISSUE TITLE
2.4.10 + forum.ixbt.com = NO log in windows!

### ISSUE THREAD

**Issue by led9** [AdguardTeam/AdguardBrowserExtension#347]
Without your extension: (or extension disabled)
http://forum.ixbt.com
Right upper angle of page, click button "Войти" = all page turn dark, new iframe "Log in windows" appears.

With your extension: (ALL filters TURN OFF, forum.ixbt.com ADD to white list)
http://forum.ixbt.com
Right upper angle of page, click button "Войти" = all page turn dark, and NO "Log in windows" appears.

Fix it, please, or - where i can download previosly version of your extension?

**Comment by ameshkov** [comment]
@Alex-302 разберись пожалуйста побыстрее.

**Comment by Alex-302** [comment]
```
$("#ixbtcommon_iframe").load(function() {
        $("#ixbtcommon_overlay").css({
            'cursor': 'auto'
        });
            $("#ixbtcommon_iframe").fadeIn('fast').focus(); <-------- doesn't works with enabled extension
      });
```
