### ISSUE TITLE
[Feature request] When selected checkboxes Blocked and Whitelist the log should display Blocked+Whitelisted requests

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#35]

**Comment by Mizzick** [comment]
Ok, and what it displays now for Blocked+Whitelisted?

What do you mean under Blocked+Whitelisted?
I see two possible options: "Blocked OR Whitelisted" or "Blocked AND Whitelisted". The "AND" option seems to be more correct in this case.

**Comment by Alex-302** [comment]
Now if selected Blocked and Whitelisted, the list is empty.

I mean "Blocked AND Whitelisted". Sometimes it is useful to see only blocked and whitelisted simultaneously.

**Comment by ameshkov** [comment]
@Mizzick why so?

You would be right if we had radio buttons there.
But checkboxes group usually means OR, not AND.

**Comment by Mizzick** [comment]
Actually I think checkboxes list in filters means AND. But in our case it seems to be more possible an UI mistake.
I will show you something:
`show &= !this.searchWhitelisted || (filterData.requestRule && filterData.requestRule.whiteListRule);`
`show &= !this.searchBlocked || (filterData.requestRule && !filterData.requestRule.whiteListRule);`

So Blocked OR Whitelisted will just show all items.

**Comment by ameshkov** [comment]
> Actually I think checkboxes list in filters means AND.

That's what we are talking about. Currently checkboxes means AND, but by UX guidelines checkboxes should mean OR.

> So Blocked OR Whitelisted will just show all items.
It is really not that hard to make it work properly instead.

**Comment by Mizzick** [comment]
Fixed
