### ISSUE TITLE
Chromium: reproducible crash with SVG in iframe

### ISSUE THREAD

**Issue by steffenweber** [AdguardTeam/AdguardBrowserExtension#355]
Using Opera 39.0.2256.48 with AdGuard 2.4.10, opening the following URL reproducably crashes the tab: https://www.computerbase.de/thema/grafikkarte/rangliste/

> Page crashed
>
> Unfortunately, something caused this page to quit. It might have been an extensions conflict or some other reason.
>
> **Try reloading the page, or navigate to another page to continue.**
>
> [Reload this page]

Reloading the page does not help. Disabling AdGuard on this particular website does not help either.

The following line of HTML triggers the bug:

```
<iframe src="https://pics.computerbase.de/5/7/5/1/9/diagramme/130-630.1472712755.svg" width="630" height="414" class="svg-chart js-svg-iframe"></iframe>
```

Could you please have a look?

**Comment by Mizzick** [comment]
@gshumihin pls have a look?

**Comment by gshumihin** [comment]
I have same issue. 
_Opera version_: <img src="http://content.screencast.com/users/shumegor/folders/Jing/media/d267452a-336e-418c-a9ac-4fb6faf1532f/00001376.png" width="200">

**Comment by ameshkov** [comment]
@Mizzick in fact the issue is with all Chromium-based browsers.

Here is a test page:
https://ameshkov.github.io/web/svg-iframe-crash.html

**Comment by ameshkov** [comment]
Fixed
