### ISSUE TITLE
Websocket issue

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardBrowserExtension#356]
User gets jquery-1.9.1.min.js:3 Uncaught TypeError: Illegal invocation

"It seems to be triggered by some JS code in the extension, in a function called wrapCallback, where it tries to execute the callback. In my case I am using jQuery 1.9.1 and it looks like the ‘add’ function of jQuery is what is wrapped by wrapCallback. It’s trying to dispatch an event on the WebSocket object from the looks of it."

More details in **1215913**

![image](https://cloud.githubusercontent.com/assets/14153331/18392930/48948528-76bc-11e6-98bd-921f9731a1f7.png)

**Comment by RyanEwen** [comment]
I am the user who reported this issue and will be happy to provide more information as needed.

To clarify the jQuery usage - I believe it's being used to bind to events (onmessage) of the WebSocket object.

**Comment by Mizzick** [comment]
Thanks for reporting!
This should should be fixed with #349

**Comment by ameshkov** [comment]
Marked as duplicate then.

**Comment by Mizzick** [comment]
It's not a duplicate actually, but should be fixed with the new code in #349
