### ISSUE TITLE
Content blocker does not contain some domain-specific rules when it is first time compiler during browser startup

### ISSUE THREAD

**Issue by GigabitEthernet** [AdguardTeam/AdguardBrowserExtension#360]
When using Adguard and Anti-Adblock Killer | Reek, on Safari 9.1.3, on OS X 10.11.6, whitespace is left at the top of macrumors.com.

**Edit (ameshkov):** original issue name: MacRumors whitespace left when using Adguard and Anti-Adblock Killer | Reek

**Comment by ameshkov** [comment]
@GigabitEthernet could you please take a screenshot?

**Comment by ameshkov** [comment]
Also I need to know which exact filters you use.

**Comment by GigabitEthernet** [comment]
I think I may have been mistaken, I don't think it is related to Anti-Adblock Killer | Reek as I have it disabled and it is still happening.

It is happening with these filters enabled:

<img width="1068" alt="screen shot 2016-09-12 at 14 35 39" src="https://cloud.githubusercontent.com/assets/4457688/18437741/307cb8f2-78f6-11e6-96b2-f87634d1f936.png">

I also have _Use optimized filters_ enabled.

Screenshot of the whitespace:

<img width="1079" alt="screen shot 2016-09-12 at 14 35 16" src="https://cloud.githubusercontent.com/assets/4457688/18437761/437bce0c-78f6-11e6-9af7-a1d14941a577.png">

**Comment by ameshkov** [comment]
Is there any change if you add this rule to your user filter?
`macrumors.com##.ad`

**Comment by GigabitEthernet** [comment]
Upon restarting Safari, the page is correctly displayed the first time but upon refreshing, the whitespace is then shown again.

**Comment by ameshkov** [comment]
Sounds like a Safari bug.

@gshumihin could you please check it on your side? I have Safari 9.1.2, it is too old:)

**Comment by gshumihin** [comment]
That's how MacRumors looks for me with Adguard and Anti-adblock killer | Reek:
<img src="http://content.screencast.com/users/shumegor/folders/Jing/media/366387e7-fcac-4d26-b67b-71add9bdece3/00001387.png" width="250">
_Apps versions:_
- Safari: **9.1.3**
- Adguard (extension): **2.4.11**
- Anti-adblock killer: **9.7**

**Comment by ameshkov** [comment]
@gshumihin according to the screenshot you have old API turned ON. What with the new API?

**Comment by gshumihin** [comment]
Here's without old API:
<img src="http://content.screencast.com/users/shumegor/folders/Jing/media/7e87ff84-3041-48f1-9e9f-cd418bea76d3/00001393.png" width="300">

**Comment by ameshkov** [comment]
@gshumihin @Mizzick  I was able to reproduce this issue. It is pretty weird though.

After browser startup and first content blocker registration this whitespace is visible. It disappears after the next CB registration.

Steps to reproduce:
1. Close all browser tabs
2. Close the browser
3. Wait a bit
4. Start the browser
5. Wait 5 sec
6. Go to macrumors.com
7. Wait 5 sec
8. Refresh it

**Comment by gshumihin** [comment]
Really weird.

**Comment by ameshkov** [comment]
After all it appears to be a serious issue, @GigabitEthernet thank you for reporting it!

The problem is that during the browser startup content blocker may not contain domain-specific filters. There is a race condition of some sort.

**Comment by ameshkov** [comment]
Fixed

**Comment by GigabitEthernet** [comment]
This issue has now re-ocurred for me.

**Comment by ameshkov** [comment]
@GigabitEthernet with version 2.4.14 right?
Have you updated to sierra and Safari 10?

**Comment by GigabitEthernet** [comment]
Still on macOS El Capitan, Adguard 2.4.14.

**Comment by ameshkov** [comment]
> Still on macOS El Capitan, Adguard 2.4.14.

Is it easy to reproduce or it happened just once?

**Comment by GigabitEthernet** [comment]
Steps to reproduce:

1.

**Comment by ameshkov** [comment]
The problem is that I have this issue with any website in Safari 10 (due to Safari bug #153 )

> Open macrumors.com in a new tab (page will be incorrectly displayed)

Does it help to refresh the page? What exact version of Safari do you use?

**Comment by GigabitEthernet** [comment]
You're right, refreshing the page resolves the issue.

**Comment by ameshkov** [comment]
So that's it, they've published buggy Safari version to all OS X versions:(

**Comment by GigabitEthernet** [comment]
Using the Wipr extension (which also uses Content Blocking), the issue is not present and the page is displayed correctly the first time Safari is opened.

I assumed you meant this was a Content Blocking bug but it would appear that this is not the case?

**Comment by ameshkov** [comment]
@GigabitEthernet thank you very much!

After your comment I took a closer look into that issue and found out that the webkit bug I was blaming before is not really that serious and we can live with it:
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/153#issuecomment-263067779

Could you please try the new build and see if it's ok now?
[AdguardBeta-2.5.1.safariextz.zip](https://github.com/AdguardTeam/AdguardBrowserExtension/files/614288/AdguardBeta-2.5.1.safariextz.zip)

**Comment by GigabitEthernet** [comment]
The issue would appear to be resolved with the newer build. Thanks!

**Comment by ameshkov** [comment]
@GigabitEthernet thanks to you for being persistent and trying Wipr:)

Every time I was checking this issue, I was adding that problematic "resource-type" field and blaming apple again and again:)
