### ISSUE TITLE
Submit Adguard for Safari to Mac AppStore

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#361]
Learn more here:
https://developer.apple.com/safari/extensions/
https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/SafariAppExtension_PG/
More info:
https://developer.apple.com/app-store/review/guidelines/#extensions

**Comment by RobFog** [comment]
It would seem an older version is available already (https://safari-extensions.apple.com) and the listing needs to be updated?

**Comment by ameshkov** [comment]
> It would seem an older version is available already (https://safari-extensions.apple.com) and the listing needs to be updated?

We've submitted the newer version just after the release. It's just review takes pretty much time (last time it took about 40 days).

**Comment by ameshkov** [comment]
This task is not about extensions gallery, it seems Apple now allows extensions authors to submit them to the Mac AppStore.

**Comment by RobFog** [comment]
Thanks for the clarifications. 40 days is very long indeed.

I switched to the releases here because the Extensions Gallery version didn't seem to be working that well.

**Comment by ameshkov** [comment]
> Thanks for the clarifications. 40 days is very long indeed.

Yeah, I hope the situation will be better in Mac AppStore.

**Comment by Stillness-2** [comment]
https://developer.apple.com/library/prerelease/content/documentation/NetworkingInternetWeb/Conceptual/SafariAppExtension_PG/HandlingCommonScenarios.html#//apple_ref/doc/uid/TP40017319-CH12-SW1

**Comment by ameshkov** [comment]
https://developer.apple.com/safari/whats-new/

> Deprecated .safariextz-style Safari Extensions
> Support for .safariextz-style Safari Extensions installed from the Safari Extensions Gallery is deprecated with Safari 12 on macOS. Submissions to the Safari Extensions Gallery will no longer be accepted after December 2018. Developers are encouraged to transition to Safari App Extensions

Guys, it's time to completely rework the Safari extension :)

**Comment by ameshkov** [comment]
https://github.com/AdguardTeam/AdguardForSafari
