### ISSUE TITLE
Palemoon does not support CSSStyleSheet.addRule function

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#369]
We should use `insertRule` instead:
https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/insertRule

**Comment by LimboSlam** [comment]
@ameshkov: I want to first say thank you for all your hard work. 

Also, when saying the browser's name, it's spelled "Pale Moon." It's how Moonchild (@wolfbeast) does it.


**-PS:** There's an [upcoming milestone](https://www.palemoon.org/WIP/) for Pale Moon ([Tycho, v27.0.0a2](https://github.com/MoonchildProductions/Tycho)) which is re-based off a newer version of Firefox, that may need some testing to be done; "there is no support for Jetpack/SDK extensions (and likely never will be). Your extensions may or may not work depending on their nature." 

Now I'll be happy to test AG when I have the free time (being an aid/teacher in training and going school is hard, and very tiring!), and when I feel up to it. So..... Lets hope we can get support from the community.

**Comment by ameshkov** [comment]
> Also, when saying the browser's name, it's spelled "Pale Moon." It's how Moonchild (@wolfbeast) does it.

Renamed:)

> "there is no support for Jetpack/SDK extensions (and likely never will be). Your extensions may or may not work depending on their nature."

AG for FF is built with Jetpack/SDK, however we use only a small part of it. Let's hope new release won't break it.
