### ISSUE TITLE
Add a link to Adguard iOS app to extension popup footer

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#37]
Use spritepad to compose all icons to one sprite:
http://wearekiss.com/spritepad

Don't forget about retina.

Replace "Apple" icon for AG for Mac links to this:
https://www.dropbox.com/s/99u8q9pukceh0k2/24.png?dl=0
https://www.dropbox.com/s/ppma3gdvpuyraiz/48.png?dl=0

Use old apple icon for links to Adguard iOS app.

**Comment by Mizzick** [comment]
need translations

**Comment by ameshkov** [comment]
Have you exported new strings to oneskyapp?

**Comment by Mizzick** [comment]
Nope. Only one string actually was added to messages.json.

**Comment by ameshkov** [comment]
Let me reopen this till we have the translations.

**Comment by Mizzick** [comment]
Related: https://github.com/AdguardTeam/AdguardBrowserExtension/issues/59
