### ISSUE TITLE
[BUG] igrul-ka.ru - iframe with a chat is hidden (FF, Chrome)

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#373]
http://www.igrul-ka.ru/
Reproduced with 2.4.13 in Chrome and 2.4.11 in FF
Extension is enabled:
<details> 
![1](http://savepic.ru/11434439.jpg)
</details>
Extension is disabled:
<details> 
![1](http://savepic.ru/11406790.jpg)
</details>

**Comment by ameshkov** [comment]
Here is what's causing it:
```
Uncaught DOMException: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to parse the rule 'body > table > tbody > tr > td > table:nth-of-type(2) > tbody > tr:nth-of-type(1) > td:nth-of-type(1) > div:nth-of-type(4) > http: > div > strong > strong > strong > strong > div > iframe{visibility: hidden!important; height: 0px!important;}'.
```

**Comment by ameshkov** [comment]
@Mizzick not yet:
https://github.com/AdguardTeam/AdguardBrowserExtension/commit/1243b520c0b55c02e3b4b0e942f69f9ed5cd0f98#commitcomment-19775256

**Comment by Alex-302** [comment]
The chat is still hidden in Chrome.
http://ipic.su/img/img7/fs/kiss_626kb.1479922679.png
 In FF it is visible.

**Comment by StVol33** [comment]
Adguard Browser Extension 2.5.8 FF
The chat is still hidden in FF.

**Comment by ameshkov** [comment]
@Mizzick
