### ISSUE TITLE
Refactoring: tabs API

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#374]
Let's start with the API interface:

@atropnikov 
1. Describe "Tab" and "Window" classes.
2. Describe the tab API.
3. We also need tab events: (focus, open, close).

@Mizzick 
Learn how to use tabs and windows without SDK in Firefox.
We currently use `sdk/tabs` and `sdk/tabs/utils`

**Comment by Mizzick** [comment]
https://github.com/gorhill/uBlock/blob/master/platform/firefox/vapi-background.js

**Comment by ameshkov** [comment]
https://github.com/AdguardTeam/AdguardBrowserExtension/pull/433
