### ISSUE TITLE
Filtering log "Source" column is null for newly opened website

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#38]
Here is how it looks like:
http://screencast.com/t/0JYeEpmxoSHj

**Comment by Mizzick** [comment]
fixed

**Comment by atropnikov** [comment]
This bug is reproduced only in Firefox. Likely referrer isn't set correctly for the main frame. Check contentPolicy.js code to fix this bug.

**Comment by Mizzick** [comment]
okay

**Comment by ameshkov** [comment]
Not that simple.

There is a problem in Firefox 38 ESR, referrer is null for EACH request there.

**Comment by Mizzick** [comment]
Okay, but I fixed the presentation for null referrer requests.

**Comment by ameshkov** [comment]
Ok, let's create an additional issue then:
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/47
