### ISSUE TITLE
Issues on FF add-on update

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#380]
Reproduced in FF Dev Edition. We should re-test it later.

![adguard settings 2016-09-22 00-48-31](https://cloud.githubusercontent.com/assets/5947035/18730312/5aea7dee-805e-11e6-945f-17fd63bd6669.png)

**Comment by Mizzick** [comment]
Cannot reproduce in FF DevEdition 51.0a2 (2016-11-06) (64-bit)
with AG 2.4.14 dev

**Comment by ameshkov** [comment]
Easy to reproduce in FF beta

**Comment by ameshkov** [comment]
https://monosnap.com/file/v5TIxGCcsWuizC0ZoQ93EU0j2oBoYb

**Comment by ameshkov** [comment]
Ok, the issue is in FF add-on update. Old framescripts are continue working for some reason.
