### ISSUE TITLE
Firefox Dev Edition: whitelist stops working when global stylesheet is in use

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#381]
Reproduced in FF Dev Edition. We should re-test it later.

**Steps to reproduce:**
1. Add rule `##body`
2. Go to any website
3. `body` is hidden (which is expected)
4. Turn ad blocking off for this website (through AG menu or in AG settings, it does not matter).
5. Refresh the website

**Expected result:**
Body is not hidden anymore.

**Actual result:**
Nothing changed, body is hidden.

**Comment by Mizzick** [comment]
As I see css rules don't work at all in this FF version.

**Comment by ameshkov** [comment]
Ok then, thank you!
