### ISSUE TITLE
When opening the installed adguard addon preferences page, it's empty

### ISSUE THREAD

**Issue by worldsdream** [AdguardTeam/AdguardBrowserExtension#382]
When going to the addon list and clicking on "preferences". 
You see this: http://i.imgur.com/11xCHh6.png

I don't know if it's because the beta? or only on the mac? But this should not be doing it. 

Adguard for Mac 1.3.0
Firefox Stable 49.0
Adguard Addon Beta 2.4.14

**Comment by ameshkov** [comment]
I can confirm it, FF add-on behaves weirdly when you reinstall the add-on without browser restart.

**Comment by worldsdream** [comment]
What should we see if we go into the preference section and we have adguard for mac or adguard for windows installed?

**Comment by ameshkov** [comment]
You'll see add-on preferences, they are independent from the desktop apps (yet they won't be used if desktop app is detected)

**Comment by worldsdream** [comment]
We should see a message in top if we have adguard for mac/ windows installed and activated on the pc and opening the extensions preference page in one of the browsers saying something like:

This won't be used if desktop app is detected

**Comment by ameshkov** [comment]
Agreed, it's just we should change the way the integration works. Instead of making it a property of a "tab", it should be some global property.

Relevant task: #190

**Comment by ameshkov** [comment]
Should be resolved after migrating to #523
