### ISSUE TITLE
Let us see the rules of each filter with a selection box and search option

### ISSUE THREAD

**Issue by worldsdream** [AdguardTeam/AdguardBrowserExtension#384]
Adguard windows and mac, we can see the rules of each filter with a selection box to each rule and a search option in the top. Can we have this for extension?

For example I want to see which rules are in the English filter and I want to search for a domain called hi.com and I want to disable some of the rules for testing.

**Comment by ameshkov** [comment]
Yep, this is planned for extension redesign.
