### ISSUE TITLE
CSP blocks too much

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#385]
Browser: Chrome 52, extension 2.4.14
Rule:

```
|ws*://*$domain=news.mail.ru|lady.mail.ru|e.mail.ru
```

Error message in console:

```
Refused to connect .....
```

1)https://e.mail.ru/messages/inbox/
<details>
![image](http://imagizer.imageshack.com/img923/7731/0anBPS.png)
</details>
2) https://news.mail.ru/currency.html
<details>
![image](http://imagizer.imageshack.com/img922/4069/k3101T.png)
</details>
3) https://lady.mail.ru/article/492029-poloski-dlja-otbelivanija-shhetka-s-displeem-i-eshhe-tri-novinki-dlja-uhoda-za-zubami/
broken slide-show
<details>
![image](http://imagizer.imageshack.com/img922/773/d9vBXY.png)
</details>

**Comment by Mizzick** [comment]
This rule template **|ws*://*$domain=news.mail.ru|lady.mail.ru|e.mail.ru** was supposed to be used only in dead situations like in #344, it blocks all websocket requests on described domains.

**Comment by Alex-302** [comment]
Ok. How we can block WS on mail.ru domains? uBO blocks them without without incorrect blocking.

**Comment by ameshkov** [comment]
@Mizzick look at points 2 and 3:
"Refused to connect".

This is clearly a false positive.

**Comment by ameshkov** [comment]
We should have not used `connect-src` CSP as it prohibits `XMLHttpRequest` as well.

**Comment by Mizzick** [comment]
Ok, please test #344 after merge.

**Comment by Mizzick** [comment]
Seems to work well on Chrome 52, Chromium 54 on Mac

**Comment by Alex-302** [comment]
@Mizzick 
2,3 are working now. They are now using another way to unhide elements.
e.mail.ru is still broken with that rule
<details>
![image](http://imagizer.imageshack.com/img924/7404/s4Vfqh.png)
</details>

**Comment by Alex-302** [comment]
You can ignore the message above.

**Comment by ameshkov** [comment]
@Mizzick after all we've learned that `connect-src` does not work properly in older Chrome versions (46 for instance).

We should not add it for these older versions. Let's add starting from Chrome 52.

**Comment by ameshkov** [comment]
@Mizzick 
Instead of editing existing header, we could simply add one more header instead:
https://www.w3.org/TR/CSP2/#enforcing-multiple-policies

**Comment by ameshkov** [comment]
Also I suppose we don't really need to add `connect-src` restriction. It will be handled by the WS wrapper.

**Comment by Mizzick** [comment]
So finally, what do we need here?

**Comment by ameshkov** [comment]
Do not add `connect-src` restriction, that's enough.

**Comment by Mizzick** [comment]
Fixed
