### ISSUE TITLE
Some symbols (čšćđž) are displayed in a different font

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardBrowserExtension#387]
http://screencast.com/t/3z0K2cf3Swe

Happens with symbols like čšćđž from Croatian and, probably, other languages. Was tested and reproduced in Opera and Chrome.

**Comment by Mizzick** [comment]
https://www.dropbox.com/s/wfm5kt6r1c1o8np/Screenshot%202016-09-24%2020.58.14.png?dl=0
Somehow it depends on font-weight now.

**Comment by ameshkov** [comment]
@Mizzick ok I got it, `gotham pro` does not contain these symbols indeed.

It's just arial with font-weight 700 looks similar. 

Please get the same font files we use in AG for Windows from @confessor-adguard.

**Comment by Mizzick** [comment]
@confessor-adguard ?

**Comment by Mizzick** [comment]
Changed backup font to opensans semibold
