### ISSUE TITLE
Extension FF with JS, just like chrome

### ISSUE THREAD

**Issue by worldsdream** [AdguardTeam/AdguardBrowserExtension#388]
Is there an adguard extension XPI file that I can install myself so javascript is enabled just like with the adguard chrome extension? If yes, pls attach it here. If there is not, can this be made for the users? 

Why? Because there are a lot of rules in filters that I want to have working. With chrome it's all perfect. With FF it's not, because of the strict addon rules.

**Comment by ameshkov** [comment]
I suppose we could make an unlisted XPI which won't be limited.

@Mizzick let's change the build process for `legacy.xpi` and `firefox-standalone.xpi`.

**Comment by worldsdream** [comment]
https://github.com/AdguardTeam/AdguardBrowserExtension/releases/tag/v2.5.1-beta

Which one should I install. So it loads the JS rules from the filterlist? 

I tried those 3, all of them are not loading the JS rules from the filterlist:
1) legacy-2.5.1.xpi
2) firefox-standalone-2.5.1.xpi
3) https://addons.mozilla.org/en-US/firefox/addon/adguard-adblocker/versions/beta

**Comment by Mizzick** [comment]
It supposed to work in legacy-2.5.1.xpi and firefox-standalone-2.5.1.xpi.

So now in these builds script rules are updated the same way as all other rules.
May be we didn't get you?

**Comment by worldsdream** [comment]
Before 2.5.1, when a JS rule gets added to the filterlist and we update the filterlist on our pc with firefox. We did not get it. Chrome did get it. Thats because firefox strict addon rules. They dont accept such software in their addons page. 

Thats why I requested an .xpi for firefox, so we can install it and can have full benefits, just like chrome. 

This change is about this, correct?

**Comment by Mizzick** [comment]
Exactly yes!

**Comment by worldsdream** [comment]
Yesterday I tested and it was not working, I will test today again on my windows machine with latest stable FF.

**Comment by worldsdream** [comment]
It's working beautifully, it was my bad. I was testing it on: 

https://www.multiup.org/en/download/026e4f676d6c967e5e77f660a590f007/DDLValley.cool_HH_LLC.2016.HDRip.XviD.AC3-EVO.avi

It was showing: "Please disable adblock to download your file". But it's a rule issue itself, will report it to adguardfilters

Great! Now we can enjoy the same as chrome users!

**Comment by ameshkov** [comment]
We'd better check it again when rule is fixed
