### ISSUE TITLE
Underscore character is not displayed on Linux machine

### ISSUE THREAD

**Issue by N3m0s** [AdguardTeam/AdguardBrowserExtension#393]
Шрифт или размер шрифта не очень подобран, где подчеркнуто красным должна быть земля _ но ее не видно, поправьте отображение.

http://prnt.sc/cnsxvw

**Comment by N3m0s** [comment]
Забыл написать OS Linux

**Comment by ameshkov** [comment]
А зума нет случаем?

**Comment by N3m0s** [comment]
Нет, вон Алекс может подрубиться и сам посмотрит. Может из-за шрифта нового, может из-за размера, шрифт точно изменился я сразу заметил по сравнению со старой версией.

**Comment by ameshkov** [comment]
Шрифт изменился, просто я у себя не могу чот повторить

**Comment by N3m0s** [comment]
Я уже переустанавливал, создавал новый профиль в браузере, ничего не помогает. Бегунок в самом низу правил тоже проверил.
Есть земля
http://i075.radikal.ru/1610/8a/0a6505cf159e.png
Нет земли
http://s019.radikal.ru/i600/1610/ed/adf69108b988.png

**Comment by Alex-302** [comment]
Глянул, похоже у N3m0s текст пустой областью скрывается. Но у себя когда меняю размер дев тулзами, такое явление не повторяется.

**Comment by ameshkov** [comment]
@N3m0s а если там `14px/16px` поставишь, будет видно?

**Comment by N3m0s** [comment]
@ameshkov нет, вторую цифру сколько не меняй не видно, если только так. 
font: 400 13px monospace, 'courier new';
Убрать совсем.

**Comment by ameshkov** [comment]
Последний вопрос: а в хроме также все?

**Comment by N3m0s** [comment]
@ameshkov Да тоже самое, а вот firefox норм отображается.

**Comment by ameshkov** [comment]
Все, я добрался до никсов и нашел, надо line-height на 1px увеличить.

**Comment by XX-J** [comment]
Такая-же проблема, только в режиме редактирования правила.

<details><summary>Screenshot:</summary>

![video_2018-08-20_154108](https://user-images.githubusercontent.com/17948007/44347314-23f85500-a4a0-11e8-8157-6aa2b51347db.gif)
</details>

___________________________________________________
Mozilla Firefox v50.0.2 (Win7SP1) - Adguard v2.10.6 (legacy)
Английский фильтр | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и системы аналитики

**Comment by maximtop** [comment]
@XX-J Спасибо, попробую у себя повторить.

**Comment by maximtop** [comment]
Поправил, можно будет проверить, когда выйдет 2.10
