### ISSUE TITLE
Make "Users Filters" a have high priority then others.

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardBrowserExtension#396]
Браузер: Mozilla FireFox v35.0.1     Расширение: Adguard v2.4.14

 В "Русском фильтре" есть следующее исключающее правило: `@@||forums.overclockers.ru/*ad*.js`
Я же хочу заблокировать: `||overclockers.ru/ads/advert.js`
Поэтому пишу соответствующее правило, но оно не срабатывает. Исключение как было в журнале, так там и осталось.

 Я считаю что надо сделать ЛЮБЫЕ "Пользовательские фильтры" БОЛЕЕ ПРИОРИТЕТНЫМИ, чем все остальные.

**Comment by ameshkov** [comment]
Не, так делать нехорошо.

Зато мы хотим ввести модификатор $important, который позволит делать любое правило приоритетнее чем исключения. В перспективе - добавим.
