### ISSUE TITLE
Sierra/Safari 10 extension issue

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardBrowserExtension#398]
Use your Adguard Safari browser extension on macOS Sierra/Safari 10. When using the Content Blocking API, blank spaces appear where the ad normally would be placed. This behavior did not exist in Safari 9. When I refresh the page, the blank ad spaces are removed. When using the old API, this blank ad space issue does not occur (prefer to use the Content Blocking API because scrolling using the Magic Mouse is smoother). Is this something that you are aware of and if so, is there a fix in the works? Thanks!

TICKET ID
BTS-562-60526

**Comment by ameshkov** [comment]
Known webkit issue:
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/153

It would be great if user comments on this issue here:
https://bugs.webkit.org/show_bug.cgi?id=162057

More user complaints -> bigger chance they will fix it soon.
