### ISSUE TITLE
The icon in tray

### ISSUE THREAD

**Issue by Crash0w3r** [AdguardTeam/AdguardBrowserExtension#40]
http://forum.adguard.com/showthread.php?1020-%D0%A0%D0%B0%D1%81%D1%88%D0%B8%D1%80%D0%B5%D0%BD%D0%B8%D0%B5-Adguard-%D0%B2-%D0%AF%D0%BD%D0%B4%D0%B5%D0%BA%D1%81-%D0%91%D1%80%D0%B0%D1%83%D0%B7%D0%B5%D1%80%D0%B5&p=64469&viewfull=1#post64469

Incorrect display of the tray icon.

**Comment by ameshkov** [comment]
@Mizzick please check the favicon we use in extension. Does it contain hires icons?

**Comment by Mizzick** [comment]
Changed FF favicon to 32x32
