### ISSUE TITLE
Amazon page blinking issue

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardBrowserExtension#400]
Amazon.com flickers when you use Adguard extension. Can be noticed [here](https://www.amazon.com/gp/product/B01EXOXE06/ref=s9_acsd_aas_bw_c_x_3?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-2&pf_rd_r=EHPTEP6BCKPRA5F5VCP6&pf_rd_t=101&pf_rd_p=ef6ae536-040e-41a1-99f6-9e75cf4cc604&pf_rd_i=15246303011) for example.

Was tested in Chrome.

Original thread:
https://forum.adguard.com/index.php?threads/amazon-blinking-issue-when-using-adguard.14462/

**Comment by Bohdan-SUP** [comment]
Also reported by customer ID **1113751**
More information may be found here:
https://productforums.google.com/forum/?utm_medium=email&utm_source=footer#!msg/chrome/TWKsjxzpTY0/mHDxOn46AgAJ

**Comment by ameshkov** [comment]
https://forum.adguard.com/index.php?threads/amazon-blinking-issue-when-using-adguard.14462/

People say the issue still happens.

**Comment by evgeniy-ADG** [comment]
>Just tested the 2.5.1 Beta. No change regarding the flicker issue...

**Comment by bauerp** [comment]
Same. Quite annoying.

**Comment by claytoncarney** [comment]
Here's another screencast with more details:

https://mega.nz/#!wgp2HTAL!7qrzaTwfNfOqXFRR0S81aHir9gCTiKHEeW4R5oTiTzk

Does not appear that filters are a source of the problem. Only some change(s) made between 2.4.10 and 2.4.14.

**Comment by claytoncarney** [comment]
Demonstrating 2.5.1 Beta:

https://mega.nz/#!dw4mXBqD!gb1QwNe84U-D0eO7_rXdQlybaDx1wjC_7Up7p2IPAso

**Comment by bauerp** [comment]
Just to be clear, this issue isn't only in Chrome, it's happening in Safari as well.

**Comment by Mizzick** [comment]
Please try the latests beta:
https://github.com/AdguardTeam/AdguardBrowserExtension/releases/tag/v2.5.3-beta

**Comment by claytoncarney** [comment]
Win10 64-bit, Chrome 55: No flicker observed with 2.5.3 Beta.

**Comment by kntndrsn** [comment]
Working correctly for me as well
