### ISSUE TITLE
Edge tries to download .htm file when Adguard changes response CSP

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardBrowserExtension#401]
Screenshot: http://content.screencast.com/users/shumegor/folders/Jing/media/0304f482-df63-40cc-97a0-49b02cbf89ec/00001432.png

Reproduced in Adguard for Edge v2.4.13

Original thread: https://forum.adguard.com/index.php?threads/10884/page-2#post-104985

**Comment by Alex-302** [comment]
the same issue
https://forum.adguard.com/index.php?threads/ovgorskiy-ru.6822/

**Comment by ameshkov** [comment]
This issue happens when we try to change CSP for the website.
I'll investigate it further.

**Comment by ameshkov** [comment]
Appears to be a bug in Edge:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/10224614/

**Comment by vbagirov** [comment]
Microsoft claims that the latest Edge version (15063 for Creators Update) has the fix. 

@vozersky can you please test this?

**Comment by vozersky** [comment]
@vbagirov 
Checked http://www.ovgorskiy.ru/
Yes, it doesn't try to download a .htm file on:

![image](https://cloud.githubusercontent.com/assets/17472907/26553928/76634aa4-4496-11e7-9e96-4f9d700c955a.png)

Microsoft Edge 40.15063.0.0

there are few missed ads though

**Comment by atropnikov** [comment]
Everything is OK.
