### ISSUE TITLE
Feature request - another filtering log performance.

### ISSUE THREAD

**Issue by Fridrix** [AdguardTeam/AdguardBrowserExtension#403]
Adguard users use such steps to watch filtering log:
- launch a browser
- go to a website
- launch a filtering log
- refresh the page
- see the requests

We were proposed another guideline to perform it:
- launch a browser
- launch a filtering log
- go to the page
- see the requests

The main thing is that user could open filtering log  through Adguard extension or Assistant icon even on blank new tab page and could watch work of Adguard filters in real-time mode.

**Comment by ameshkov** [comment]
@Fridrix the second way is also possible, what's the problem with it?

**Comment by Fridrix** [comment]
@ameshkov its a request of one of the users. He would like to have this feature

**Comment by ameshkov** [comment]
@Fridrix I mean this is already possible to use filtering just as user has described.

**Comment by Fridrix** [comment]
@ameshkov i mean that user could open it even on a blank page
![image](https://cloud.githubusercontent.com/assets/20476168/19244354/b0880558-8f24-11e6-9d1b-dc6ce8af4545.png)
Here's no such button

**Comment by ameshkov** [comment]
@Fridrix right click on Adguard icon

**Comment by Bohdan-SUP** [comment]
Adguard 2.4.14 on Chrome.
That's what I have:
1) On a blank page:
![image](https://cloud.githubusercontent.com/assets/14153331/19266667/483aca3c-8fb3-11e6-813d-f2f31a405948.png)

2) On some opened page:
![image](https://cloud.githubusercontent.com/assets/14153331/19266655/3b19592c-8fb3-11e6-9822-3b84999d83a1.png)

**Comment by ameshkov** [comment]
Ah, got it, we'll add it to the context menu

**Comment by Bohdan-SUP** [comment]
User **1023133** in ticket HGE-951-65974 wonders "Why just add it to the context menu?.....Why not make the filtering log available just like it is on other pages with just simple left click and clicking on search icon"
![screen shot 2016-10-12 at 3 20 25 pm](https://cloud.githubusercontent.com/assets/14153331/19309763/8b4e305c-908f-11e6-949d-6ad7bee43ed0.png)

What do you think?

**Comment by ameshkov** [comment]
Matter of design I guess. It'd be weird if we show it for a page which we don't filter.

**Comment by The-Commissioner** [comment]
Looks like you guys never tested it on Firefox, would be lovely to see how you integrate it in the firefox adguard icon context menu. This will be fun.

**Comment by atropnikov** [comment]
Added to the context menu.
