### ISSUE TITLE
Twitter won't show external links preview with Adguard enabled

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardBrowserExtension#409]
https://twitter.com/VRSoloviev/status/788356755176689664

Happens like this:
![image](https://cloud.githubusercontent.com/assets/14153331/19514539/7cff9bf4-95fc-11e6-9a8a-a690eb96909d.png)

You need to actually disable extension in Preferences. Simply disabling protection for the exact website or pausing the protection does not help.

Happens only in Safari 10 on macOS Sierra, Adguard extension 2.4.10

Reported by 2 users - 1426667 and 1432936

**Comment by ameshkov** [comment]
@Bohdan-SUP please recommend them updating to the latest beta version (2.4.15).
