### ISSUE TITLE
GNU/Linux not mentioned in module section

### ISSUE THREAD

**Issue by davidhedlund** [AdguardTeam/AdguardBrowserExtension#411]
chrome://adguard/content/thankyou.html says

> Protection against phishing and malicious websites
> The Browsing Security module protects you from malicious and phishing websites. The module uses [a special web service](https://adguard.com/en/how-malware-blocked.html#other) to check the websites you visit.

Windows and Mac are supported, but not GNU/Linux.

**Comment by davidhedlund** [comment]
[mylabel:porting](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aporting%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by ameshkov** [comment]
@davidhedlund hi!

Why, it does support browser extensions, therefore it does not depend on OS.

> **Browser extensions** (as well as Adguard for Android and Adguard for Mac) work differently, using the so called [Lookup API](https://github.com/AdguardTeam/AdguardForAndroid/issues/162#issue-115487668) to do the check of pages that you visit

**Comment by davidhedlund** [comment]
> Browser extensions (as well as Adguard for Android and Adguard for Mac) work differently, using the so called Lookup API to do the check of pages that you visit

I missunderstood, you are right.

Can you please mention **GNU/Linux** (please do no use the term Linux) there too?

**Comment by davidhedlund** [comment]
[mylabel:open](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aopen%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by ameshkov** [comment]
@davidhedlund yep, sure. let's keep this issue open until it's done then.

**Comment by davidhedlund** [comment]
@ameshkov Thanks.

**Comment by vbagirov** [comment]
@ameshkov @davidhedlund 
I do not understand what exactly is required of me. Do I need to explicitly mention [here](https://adguard.com/en/how-malware-blocked.html#other) that Adguard browser extensions are supported in GNU/Linux?

**Comment by davidhedlund** [comment]
@vbagirov Yes.

Also, I see these links at the bottom on the page:

* Adguard for Windows
* Adguard for Android
* Adguard for Mac

but not
* Adguard for GNU/Linux


Can you please add that?

**Comment by vbagirov** [comment]
@davidhedlund 
The thing is, we have separate products for Win, Mac and Android, but not for GNU/Linux. Browser extensions (which, of course, also work in GNU/Linux) are platform-independent, and can work on any platform, as long as browsers there support browser extensions. So, as I see it, there is no justification to add a separate https://adguard.com/en/adguard-gnu+linux/overview.html page - there is simply nothing to tell about. 

Maybe we can add a line somewhere that states explicitly that Adguard browser extensions are supported in GNU/Linux, but that's it. And even then, it is not clear to me where to do so.

Also possible that I miss the point completely here, in which case @ameshkov please correct me.

**Comment by davidhedlund** [comment]
@vbagirov Yes, "GNU/Linux" should be mentioned somewhere.

**Comment by ameshkov** [comment]
@vbagirov i guess we should mention supported OS/platforms here:
https://adguard.com/en/adguard-adblock-browser-extension/overview.html

**Comment by vbagirov** [comment]
@davidhedlund @ameshkov I agree that mentioning it in https://adguard.com/en/adguard-adblock-browser-extension/overview.html would be a good measure. I will do it.
