### ISSUE TITLE
Give us an option to add 3rd party filters with their URLs

### ISSUE THREAD

**Issue by bkrucarci** [AdguardTeam/AdguardBrowserExtension#412]
Can we please get a feature like this in Adguard extension?
Please see: https://github.com/gorhill/uBlock/wiki/Filter-lists-from-around-the-web#import-external-filter-lists

Thanks

**Comment by ameshkov** [comment]
We'll do it along with planned add-on redesign.

**Comment by bkrcrc** [comment]
Thanks @ameshkov

**Comment by ameshkov** [comment]
Duplicate of #808 , done in the v3.0 branch
