### ISSUE TITLE
Should we use "Spyware Filter" enabled by default after install?

### ISSUE THREAD

**Issue by bkrucarci** [AdguardTeam/AdguardBrowserExtension#413]
Hi,

I think people should use "Spyware Filter" by default.
Social elements and annoyances elements depend on user preferences. But I am sure none want to be tracked by other companies or advertisers.

Current default filters of extension are;
English filter and local filter (if exists)

I suggest;
English + Spyware + local filter  (if exists)

After install, Adguard shows introduction to select filters.
I think Adguard should improve this way..
You put all settings in one place, it is wrong. You should show pages to users..
Seperate introduction pages for each filters and features.

What do you think?
Maybe you should create a poll for this to ask users?

Thanks :)

**Comment by ameshkov** [comment]
The problem of "spyware filter" is that it can cause more false positives and incorrect blocking. Same problem with social and annoyances filters. 

So we'd better provide a short "default" filters list and let user to decide if he needs to block things other from ads.

**Comment by bkrcrc** [comment]
@ameshkov I think there is no escape from False positives (blockings)..
This is possible but we cannot reject its usefullness of blocking tracking. I think Adguard should enable it byt default to protect users privacy.
I did not recommend Social Filter or annoyances by default..because they depend on preference.
Because people want to share contents with share buttons, or people want to be informed by annoyed non-ad popups for subscriptions of the websites.
But Spyware filter is different, I always enable it on my friends PC after installing Adguard.
I heard nothing bad from them.
And sometimes Alex302 adds some generic rules to Spyware filter which block ads too.. So the bare English filter doesn't enough.

**Comment by ameshkov** [comment]
It's just I suppose spyware filter is also depends on the users' preferences.

Let's take an example. There are some content serving networks like taboola and outbrain that show you list of articles basing on your profile. We don't block it in the english filter (unless they advertise a third party website) as it could be useful to user. However, these are blocked in spyware filter as they are tracking people.

**Comment by bkrcrc** [comment]
@ameshkov No you are wrong. Spyware filter is very safe for novice users and Avarage Joe's..
Please see my report here : https://forum.adguard.com/index.php?threads/resolved-iha-com-tr.15027/#post-108135
and the filter developer's reply.
They are very careful to block things completely. They do not block taboola and outbrain 'completely'.
So whats the next example :)

**Comment by ameshkov** [comment]
@bkrcrc you got me, I admit my example was not very good:)

@Alex-302 @seanl-adg 
Guys, what do you think about turning spyware filter ON by default? How problematic could it be?

**Comment by bkrcrc** [comment]
On the adblocker market, uBlock Origin is your rival..and it comes with EasyPrivacy enabled by default.
I think people are happy with it and using uBlock Origin w/o problems.
I hope our filter developers will agree with me :) Thanks @ameshkov

**Comment by worldsdream** [comment]
+1 for enabling spyware by default

**Comment by ameshkov** [comment]
Let me assign it on v3.0 for now, may be reassign to v2.6

**Comment by superlex** [comment]
I agree with bkrucarci suggestion :)

**Comment by ameshkov** [comment]
It will be done as a part of the onboarding experience rework, marking as dup

**Comment by bkrucarci** [comment]
@ameshkov @Birbber Any update on this? Tracking Protection filter is not enabled by default, still?
uBlock Origin enables the EasyPrivacy by default.

Any update before stable v4.0 release?

**Comment by ameshkov** [comment]
We should first make it less "problematic", i.e. work on the "stub" resources (those that replace analytics scripts). Currently, the tracking protection list still causes too many issues on different ecommerce websites, we would like it to be completely safe before enabling by default.
