### ISSUE TITLE
Extended CSS is not working on fs.to in Opera 40

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#414]
Extension version: 2.4.14
Example of ads
<details>
![image](http://imagizer.imageshack.com/img921/4986/BTIvkZ.png)
</details>
This site is clean in Chrome with extension.
Tried even this rule for check:

```
##div[-ext-has="div"]
```

**Comment by Mizzick** [comment]
##div[-ext-has="div"]
works fine in Opera 41

**Comment by Alex-302** [comment]
strange. Works now.
