### ISSUE TITLE
Can not block web-sockets on some sites in Firefox and Edge

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#416]
Extension version: 2.4.14 (Edge - 2.4.13)
Example sites:
- kinogo.club
- kinokrad.co

Related thread
https://forum.adguard.com/index.php?threads/et-code-ru.15323/

**Comment by Mizzick** [comment]
@Alex-302 have you tried it?
It seems to be fine on
http://kinogo.club/
http://kinokrad.co/

I can see ads on 
http://zserials.tv/zarubezhnye/chance.php
but may be there is no rule for this?

**Comment by Mizzick** [comment]
I've found it.
I think we gonna need the same hack as it was done with webkit in #344 
cause I can't see the url ws://et-code.ru:8040/904, that was blocked by CSP in chrome, in FF log.

**Comment by Mizzick** [comment]
Fixed

**Comment by ameshkov** [comment]
No way, WS connections must be reported to nsIContentPolicy (`shouldLoad`).

**Comment by ameshkov** [comment]
Relevant bug report:
https://bugzilla.mozilla.org/show_bug.cgi?id=1299766

**Comment by Mizzick** [comment]
These requests are not represented on shouldLoad. 
But I can see some data:image/png;base64 requests there, I think that's it.
Tried in the latest FF Nightly version.

**Comment by ameshkov** [comment]
Prepare a test page where you can reproduce the issue and let's file a new bug report then.

**Comment by Mizzick** [comment]
The following rule 'ws://et-code.ru:8040' should be added

**Comment by Mizzick** [comment]
no need on this rule actually
Fixed.
