### ISSUE TITLE
Adguard Legacy Add-on Won't Work on Pale Moon 27 (Jetpack/SDK extension no longer allowed)

### ISSUE THREAD

**Issue by bkrcrc** [AdguardTeam/AdguardBrowserExtension#419]
Pale Moon started to change somthing for the add-ons.
They released a forum post "[Pale Moon is changing!](https://forum.palemoon.org/viewtopic.php?f=1&t=13499#p95700)"
and their message is 

> If you are an extension developer, we strongly encourage you to download and test the Pale Moon pre-release versions with your extensions, and consider targeting Pale Moon v27 and above natively.

Please download the pre-releases here and check for Adguard.
https://www.palemoon.org/WIP/

The current legacy.xpi add-on doesn't work with Pale Moon 27,
Please see screenshot: http://s11.postimg.org/4zzlmt8er/screenshot.png

Thanks

**Comment by LimboSlam** [comment]
Thanks @bkrcrc for opening up this specific issue. I was planing to do so earlier, but I got caught up in my school work.

**Comment by bkrcrc** [comment]
@LimboSlam why did you give a "thumb down" emoji to my post?

**Comment by ameshkov** [comment]
We are in process of getting rid of jetpack/SDK, so I guess the issue will be resolved eventually.

**Comment by LimboSlam** [comment]
@bkrcrc: Oh sorry, I liked what you had to say, but I don't like our current situation right now with Pale Moon dropping jetpack/SDK. 

@ameshkov: is it possible for you to target Pale Moon specifically (XPCOM/XUL) even though you'll going the route of WebExtensions?

**Comment by bkrcrc** [comment]
@LimboSlam Pale Moon is not user friendly browser..not usable for many users.
Of course we do not have to use Pale Moon but it was a great browser before.

**Comment by ameshkov** [comment]
> though you'll going the route of WebExtensions

We are not going that route **yet**. In fact we want first to get rid of the SDK and use old FF APIs.

However, switching to WebExtensions is inevitable (when we feel it is stable enough).

**Comment by BooBerry** [comment]
Well, it looks like Mozilla will drop legacy extension support and go WebExtensions-only at the end of 2017.

http://www.ghacks.net/2016/11/24/firefox-will-only-support-web-extensions-by-the-end-of-2017/

**Comment by ameshkov** [comment]
Finally:) I hope WebExtensions support will be good enough by that time.

**Comment by bkrcrc** [comment]
I do not know what Pale Moon developer tries..he has very small user base and he waits support for his browser. Many Firefox add-on not working with Pale Moon, as well. I already uninstalled it.

**Comment by TPS** [comment]
@bkrcrc @AdguardTeam Minor nit: Could issue title be fixed to read <kbd>Adguard Legacy Add-on Won't Work on Pale Moon 27 (Jetpack/SDK extension ___no longer___ allowed)</kbd> (i.e., ___no___ supposed to be ___not___ or ___no longer___)?  It's rather confusing the way it reads now.

TIA.

**Comment by BooBerry** [comment]
https://forum.adguard.com/index.php?threads/pale-moon-legacy-xpi-support.19819/

So what's going to happen when Firefox goes WebExtensions-only? Are you guys going to drop the legacy .xpi (and Pale Moon support) or maintain it alongside the WebExtension?

Personally, I'd go for depreciating legacy or forking it off into another extension.

**Comment by TPS** [comment]
@ameshkov From [Pale Moon v.27.1](https://forum.palemoon.org/viewtopic.php?t=14724) onwards, there's now [PMkit, which "provides basic compatibility layer with Mozilla Add-on SDK."](http://developer.palemoon.org/Add-ons:Extensions/Jetpack)  This should help immensely with adapting AG in the interim, while doing the other conversions.

**Comment by ameshkov** [comment]
Actually, the legacy build from the master branch should work in Pale Moon just ok.

@atropnikov could we try it? It might be untested yet, but nevertheless, let's attach the new build to this issue.

**Comment by BooBerry** [comment]
Hmmm, I just tried legacy-2.5.16.xpi and no-go. It gives off a warning about it being a JetPack/SDK extension not being supported.

**Comment by ameshkov** [comment]
@BooBerry v2.5 is build from the old branch.

We were working on a huge refactoring in the master branch, got rid of the FF SDK and such.

**Comment by BooBerry** [comment]
Ah, I see that now. Got a compiled version handy I can try real quick? ;)

**Comment by ameshkov** [comment]
@BooBerry will be ready tomorrow, build script requires some changes:)

**Comment by atropnikov** [comment]
[palemoon-2.6.0.xpi.zip](https://github.com/AdguardTeam/AdguardBrowserExtension/files/804448/palemoon-2.6.0.xpi.zip)

**Comment by BooBerry** [comment]
This build works great!

**Comment by TPS** [comment]
D'y'all mind pushing this @ least as a legacy ß version?  I've been missing this since PM V27.0! 🙏

**Comment by ameshkov** [comment]
I expect us to publish official beta either tomorrow or on Friday:)

**Comment by lagun** [comment]
pale moon add-on have auto-update?

**Comment by ameshkov** [comment]
It will have it. Sorry for the delay with the 2.6 beta, going through inner test for a while.

**Comment by TPS** [comment]
@atropniatr Solved w/ https://github.com/AdguardTeam/AdguardBrowserExtension/releases/download/v2.6.1-beta/firefox-legacy-beta-2.6.1.xpi , then?

**Comment by atropnikov** [comment]
@TPS, yes.
