### ISSUE TITLE
is it possible to remove videoads 

### ISSUE THREAD

**Issue by cabban** [AdguardTeam/AdguardBrowserExtension#422]
hello has some sites 
www.dplay.se
www.expressen.se
www.aftonbladet.se

hope so :) cheers :) 

@ameshkov 
@Alex-302

**Comment by ameshkov** [comment]
Hi! @Alex-302 will look into it, thank you!

Next time you'd better create an issue in https://github.com/AdguardTeam/AdguardFilters repo, though:)

**Comment by cabban** [comment]
Aha i put it in extension😀

Skickat med AquaMail för Android
http://www.aqua-mail.com


På 3 november 2016 13:30:43 Andrey Meshkov <notifications@github.com> skrev:

**Comment by Alex-302** [comment]
@cabban please provide your filters list and direct links to pages with video ads.

**Comment by cabban** [comment]
@Alex-302 
English filterHomepage
EasyList + Adguard English filter. Filter list that specifically removes adverts on English language websites.
Spyware filterHomepage
The most comprehensive list of various online counters and web analytics tools. If you do not want your actions on the Internet to be tracked, use this filter.
Social media filterHomepage
Filter for social media widgets (Like buttons and such).
Annoyances filterHomepage
Blocks irritating elements on webpages including cookie notices third-party widgets and in-page popups.

http://tv.aftonbladet.se/abtv/
http://www.dplay.se/
http://www.expressen.se/tv/
http://www.viafree.se/ ( a message cant se if i had activated adblocker) 
hope this is possible :) thank u in advanced

**Comment by Alex-302** [comment]
> http://tv.aftonbladet.se/abtv/
> http://tv.aftonbladet.se/abtv/articles/201601
> http://www.expressen.se/tv/
works without ads

> http://www.dplay.se/tunnelbanan/season-4-tva-aggressiva-killar/

try
```
@@||dplay.se$generichide
```



> http://www.viafree.se/

try
```
@@||viafree.se$generichide
```

**Comment by cabban** [comment]
Viafree no close your adblocker to continue watching
Dplay no . The video is not even clickable unfortunately

Aftonbladet  works thank u
Expressen not working i have ads
Can u check 😀

Skickat med AquaMail för Android
http://www.aqua-mail.com


På 4 november 2016 13:22:53 Alex <notifications@github.com> skrev:

**Comment by Alex-302** [comment]
Can't reproduce. Need remote access.

**Comment by cabban** [comment]
Remote access? What's that?
Does it works for you?

Skickat med AquaMail för Android
http://www.aqua-mail.com


På 4 november 2016 16:03:47 Alex <notifications@github.com> skrev:

**Comment by Alex-302** [comment]
> Remote access? What's that?

TeamViewer

> Does it works for you?

yes, all these sites are works on my end(with the rules above)

**Comment by cabban** [comment]
really really wierd
cause , aftonbladet is the only one works of them four sites, strange that
it works for u :/

2016-11-04 16:16 GMT+01:00 Alex <notifications@github.com>:

**Comment by cabban** [comment]
![image](https://cloud.githubusercontent.com/assets/19514493/20025084/6f99f8f0-a2eb-11e6-8767-39ffa5bd1172.png)

**Comment by cabban** [comment]
![image](https://cloud.githubusercontent.com/assets/19514493/20025093/83cdf66e-a2eb-11e6-8461-84c440b7d727.png)

expressen.tv ads

**Comment by Bluscream** [comment]
@cabban 
> TeamViewer is a popular piece of  software used for Internet-based remote access and support. TeamViewer software can connect to any PC or server, so you can remote control your partner's PC as if you were sitting right in front of it. For the remote session to work the partner has to start a small application, which does not require installation or administrative rights

> https://www.teamviewer.com/

**Comment by cabban** [comment]
@Bluscream 
i know but letting someone control my computer is not so great i think :/
@Alex-302 but here in the printscreen u see ads

**Comment by Bluscream** [comment]
@cabban Of course noone can force you but it would really help to get your issue solved.
Also its a trustworthy company :)

**Comment by cabban** [comment]
@Alex-302 yes u can control på computer to fix the issue _=)

**Comment by ameshkov** [comment]
@cabban @Alex-302 you'd better sort the remote access details by email. It's just Github comments is not the best place for passing TV ID and password:)

**Comment by Bluscream** [comment]
@ameshkov If you suggest people to e-mail your company, it's always good to provide the email address in the same message. (I've seen the missing email while asking for it twice now :)

**Comment by Alex-302** [comment]
@cabban 
are you registered on our forum? You can send me PM.

**Comment by ameshkov** [comment]
> If you suggest people to e-mail your company

He knows Alex's email.
