### ISSUE TITLE
Adguard Safari extension block truste.com dialog, even if paused

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardBrowserExtension#424]
I'd like to report an error on the AdGuard Safari Extension.
First of all, it blocks the websites that use the cookie or other dialogs from truste.com, such as oracle.com or sourceforge.net. It is already an error, the dialog should not be blocked: one must agree terms to use the website. But instead of the dialog an empty gray box is displayed (see attachment), and as I cannot click OK, the entire site remains unavailable.

But it gets worse: even if I pause AdGuard and refresh, it keeps blocking the dialog! I have to enter Safari preferences and disable the plug-in to have the site and the dialog displayed correctly.

Please have AdGuard recognize dialogs from truste.com, such as the cookie info on oracle.com, and make sure that it doesn't keep blocking when on pause.

System info: MacOS Sierra 10.12.1 with Safari 10.0.1, AdGuard Safari plug-in 2.4.10 (using new content blocking API)

<details>
A short explanation:
- AdGuard activated.png: shows www.oracle.com <http://www.oracle.com/> when AdGuard extension is active and running. As you can see, there is a transparent grey box on the top of the screen blocking the site. 

![adguard activated](https://cloud.githubusercontent.com/assets/15856304/19924893/85ea4d72-a0f6-11e6-935c-14195e1c9b77.png)

- AdGuard paused.png: shows www.oracle.com <http://www.oracle.com/> when AdGuard extension is active but paused. The grey box on the top of the screen is still blocking the site. Although paused, AdGuard is still blocking!!!

![adguard paused](https://cloud.githubusercontent.com/assets/15856304/19924904/917b07d0-a0f6-11e6-8f6f-dd92917c7ca6.png)

- AdGuard deactivated.png: shows www.oracle.com <http://www.oracle.com/> when AdGuard extension is deactivated in the Safari settings. Now the grey box is filled with content, it is actually a cookie warning linked from truste.com. It should be recognised by AdGuard as “normal content”.

![adguard deactivated](https://cloud.githubusercontent.com/assets/15856304/19924905/948ba15a-a0f6-11e6-8b3e-a61a3085129a.png)

</details>
I only have the filters “English filter”, “German filter” and “Safari filter” activated. The default settings for Germany, nothing more.

**Comment by ameshkov** [comment]
Just tested it with extension version 2.4.15 and it is all good there.

Could you please ask user to try extension beta version?
