### ISSUE TITLE
Fake phishing extension "Ad Guarded Adblocker"

### ISSUE THREAD

**Issue by Bluscream** [AdguardTeam/AdguardBrowserExtension#426]
https://chrome.google.com/webstore/detail/ad-guarded-plus-premium/oejkdelkckgahmbgljmidaklagcoddep

![image](https://cloud.githubusercontent.com/assets/3318223/20037781/56dac870-a427-11e6-8c40-9f58dbdc02be.png)

In their manifest:
```json
                "lib/content-script/assistant/js/adguard-selector.js",
                "lib/content-script/assistant/js/adguard-rules-constructor.js",
```

![image](https://cloud.githubusercontent.com/assets/3318223/20037797/fc483d1a-a427-11e6-9695-16023685250f.png)
```js
* This file is part of Adguard Browser Extension (https://github.com/AdguardTeam/AdguardBrowserExtension).
```

**Comment by Bluscream** [comment]
He couldn't be more of an asshole when stealing your shit

![image](https://cloud.githubusercontent.com/assets/3318223/20037863/20c7e4f0-a429-11e6-96bd-28d5e7f46af1.png)

**Comment by ameshkov** [comment]
Heh, we've even filed a trademark abuse a while ago.

Google didn't not react on this as there's no direct trademark violation ("Ad Guarded" != "Adguard"). And we just don't have enough time to nag them about this.

**Comment by ameshkov** [comment]
> The last one seems to be the one you would need to send.

That's exactly what we did

**Comment by ameshkov** [comment]
Ah, no, it can't be a copyright infringement, extension source is LGPL.
So it was trademark violation abuse.
