### ISSUE TITLE
YouTube playlists don't automatically continue to the next song

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardBrowserExtension#431]
I've found a bug using the AdGuard Safari extension (v2.4.10) on macOS Sierra v10.12.1 with Safari v10.0.1. The extension is using the newer "content blocking API".

The issue is that YouTube playlists don't automatically continue to the next song if the tab isn't in focus.

Steps to Reproduce:
1. Open a YouTube playlist, and let it play: https://www.youtube.com/watch?v=bq773UNbZpw&index=6&list=PLF7B92F492FDAE703
2. Open another page in a separate tab: https://www.google.com
3. At the end of the song, it'll just stop playing, rather than proceeding to the next song.

If you bring the tab into focus, it'll then continue to the next song. However, if you disable AdGuard protection for YouTube, it'll automatically continue to the next song, even when the tab isn't in focus.

1449160

**Comment by ameshkov** [comment]
Duplicate for https://github.com/AdguardTeam/AdguardBrowserExtension/issues/142
