### ISSUE TITLE
Popup

### ISSUE THREAD

**Issue by Anoop2609** [AdguardTeam/AdguardBrowserExtension#435]
Add feature of popup blocking because some torrent site and other has to much popup

**Comment by Alex-302** [comment]
Please write here with the site examples
https://github.com/AdguardTeam/AdguardFilters/issues

**Comment by worldsdream** [comment]
I think he means a feature, where you can add websites to it manually and those websites wont open any popups anymore.

**Comment by ameshkov** [comment]
> I think he means a feature, where you can add websites to it manually and those websites wont open any popups anymore.

Ah, I got the idea.

@Anoop2609 I need as more examples of such websites as possible.

**Comment by Anoop2609** [comment]
https://thehiddenbay.xyz/ ,https://extratorrent.stream/ ,https://eztv.unblocked.rocks/ , https://limetorrents.unblocked.video/ ,https://torrentbutler.bypassed.live/ and other torrent. I am using firefox 50 so i only see popup in firefox , not any other browser.

**Comment by ameshkov** [comment]
@seanl-adg could you please take a look at these sites? I see they all use the same approach - clicking torrent link for the first time causes a popup.

I am interested in the script they use. Also I'd like to know if you have any ideas on what can be done to suppress this script?

**Comment by worldsdream** [comment]
@ameshkov is it possible to have a feature in adguard products.

1) If we add a website in userfilter with something behind it for example: website.com^nopopup and it will block all the popups of that website? 
2) A setting where we add those websites and it kill the popups?

Or not possible? I heard ublock is doing this correct?

**Comment by ameshkov** [comment]
> If we add a website in userfilter with something behind it for example: website.com^nopopup and it will block all the popups of that website?

That's exactly what I am thinking about.

**Comment by Anoop2609** [comment]
@ameshkov it is not good way to block popup by adding every single website in userfilter because all torrent site have there proxy site and they all have same behavior, so we need to dig into the script. visit https://proxyportal.org/ there are all torrent site which have same problem. I am thinking it may be helpful for use to see the problem.

You can develop any filter for popup in which  add all the website which is present in https://proxyportal.org/
for now and keep updating until better solution come.

**Comment by seanl-adg** [comment]
[Here](https://gist.githubusercontent.com/seanl-adg/466fc22780ef800499708d6dd4fe2f85/raw/083d5bbf1c99566df0afe4a5106ae01f6ff3ea63/onclasrv.js) is a deobfuscated popup script used in `https://thehiddenbay.xyz/`.

Note:
 - Some property names - "iOSSafariSwapPopunder", "disableChromePDFPopunderEventPropagation", 
 - The script contains a data:application/pdf url.
 - A part of a script
 ```
function() {
    var a = J.createElement('a'),
        U = J.createEvent('MouseEvents');
    a.href = e.url;
    a.target = '_blank';
    U.initMouseEvent('click', true, true, P, 1, 0, 0, 0, 0, true, false, false, false, 1, null);
    a.dispatchEvent(U);
}
```
I'll archive popunder scripts [here](https://gist.github.com/seanl-adg/466fc22780ef800499708d6dd4fe2f85).

**Comment by Anoop2609** [comment]
Man, you are awesome. Will you fix this issue in next beta release or in filter.

**Comment by ameshkov** [comment]
@seanl-adg so they emulate link click. Pretty popular approach, we should take care of it as well.

So, here are all the approaches we'd better take care of:

1. `window.open` - we can simply override it
2. Dynamic link creation and clicking using `MouseEvent.initMouseEvent` - override MouseEvent.prototype.initMouseEvent and that's it.

**Comment by ameshkov** [comment]
https://github.com/AdguardTeam/PopupBlocker
