### ISSUE TITLE
Can someone point me to instructions on how to block ads on a domain but not block ads on that site's subdomain?

### ISSUE THREAD

**Issue by edgr-sanchez** [AdguardTeam/AdguardBrowserExtension#436]
I would like to have Adguard block ads on facebook.com but I need Adguard to **NOT** block ads on business.facebook.com

Are there help documents that show how to do this? I've done Google searches but they tend to point me to other forums for AdBlock and ABP.

**Comment by edgr-sanchez** [comment]
Disregard, I found the proper Adguard Forum to ask this in.

**Comment by ameshkov** [comment]
Btw, i guess it's a good idea not to block ads on business.facebook.com for all users.
We'll add an exception rule to the english filter:
`@@https://business.facebook.com^$document,~third-party`
