### ISSUE TITLE
Adguard can't be installed on Firefox Nightly 53.0a1

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardBrowserExtension#443]
id 1453836

Firefox Nightly 53.0a1 (64) и Adguard AdBlocker 2.4.14

Расширение не устанавливается и соответственно не работает. 
Не появляется значок в браузере на панели.

**Comment by ameshkov** [comment]
А перезапуск браузера?

**Comment by vozersky** [comment]
https://dl.dropboxusercontent.com/u/57517781/screenshots/Screen%20Shot%202016-11-25%20at%2014.09.01.png
https://dl.dropboxusercontent.com/u/57517781/screenshots/Screen%20Shot%202016-11-25%20at%2014.08.33.png
https://dl.dropboxusercontent.com/u/57517781/screenshots/Screen%20Shot%202016-11-25%20at%2014.05.57.png

**Comment by zebrum** [comment]
не помогает.

**Comment by ameshkov** [comment]
А если бета-версию установить?

**Comment by XX-J** [comment]
C бетой 2.5.1 - тоже самое. Может проблема в Мозилле, которая альфа?

**Comment by ameshkov** [comment]
Может быть с этой новостью связано?
http://www.ghacks.net/2016/11/24/firefox-will-only-support-web-extensions-by-the-end-of-2017/

Но они должны были начать этот процесс только с 57 версии.

**Comment by XX-J** [comment]
Тогда, в теории, не должно работать ни одно из дополнений, которыми я обычно пользуюсь. Поэтому провёл небольшой тест:
Add to Search Bar v2.9   -   работает
Adguard legacy v2.5.1   -   НЕ работает
Adguard v2.5.1   -   НЕ работает
Duplicate in Tab Context Menu v1.0.11   -   работает
ePN CashBack v0.3.9   -   работает
FlagFox v5.1.17   -   работает
friGate v2.2.1.1   -   работает
Google Translator v2.1.0.5.1   -   НЕ работает
GreaseMonkey v3.9   -   работает
IE Tab 2 v6.2.18.1   -   НЕ работает
InlineDisposition Reloaded v1.0.0.0.1   -   работает
Keyword Search v1.1.8.3   -   работает
Mozilla Archive Format (MHT) v4.0.1   -   НЕ работает
Quick Context Search v1.5.4   -   работает
