### ISSUE TITLE
Feature request google anti tracker

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardBrowserExtension#447]
Right-clicking on google search result, we can copy the link. However
Google wants to analyze traffics and adds extra stuff to the original
link. Please make a filter that gets rid of the extra stuff on copying
link. There is a chrome extension that does this: source code on
https://github.com/Rob--W/dont-track-me-google/ and extension on
https://chrome.google.com/webstore/detail/dont-track-me-google/gdbofhhdmcladcmmfjolgndfkpobecpg?utm_source=chrome-app-launcher-info-dialog.

Customer ID: 1455593

Moved from: 
https://github.com/AdguardTeam/AdguardFilters/issues/3568#issuecomment-263143798

**Comment by XX-J** [comment]
А также можно добавить Яндекс, взяв за основу скрипт [Direct links out](https://github.com/nokeya/direct-links-out), и др.

**Comment by Bluscream** [comment]
There are some userscripts that already do this. But you're right, it should be part of the stealth-mode

**Comment by bkrcrc** [comment]
Can we remove the tracker tokens?
utm_source, utm_medium, utm_term, utm_content, utm_campaign, utm_reader and etc.
I am using [Pure URL](https://addons.mozilla.org/en-US/firefox/addon/pure-url/versions/) add-on to prevent these.

**Comment by ameshkov** [comment]
Both are planned as "stealth mode" features in Adguard's desktop version.

However, it is a bit out of scope for the browser extension (at least for now, until we're ready to implement part of the stealth mode features in it)

**Comment by ameshkov** [comment]
Dup of https://github.com/AdguardTeam/AdguardBrowserExtension/issues/39
