### ISSUE TITLE
Firefox with Adguard eats lots of Memory

### ISSUE THREAD

**Issue by yeezy69** [AdguardTeam/AdguardBrowserExtension#449]
Firefox 50 (64bit Arch Linux) with Adguard Add-On (2.4.14 and 2.5.1 Beta) needs lots of memory for me. After round about 24 hours about:memory says 2.000 - 4.000 MB. I deleted my whole Firefox profile. Only installed Adguard Add-On. But it didn't help. I have only 3-5 (always the same) tabs open. 

Without Adguard and with AdblockPlus memory Usage of Firefox is between 400 and 600 MB.

What can i do for help debugging?

![screenshot_001](https://cloud.githubusercontent.com/assets/22444686/20691057/9b5ab420-b5ce-11e6-9fbe-05212939465d.png)

**Comment by ameshkov** [comment]
Could you export memory report?

**Comment by yeezy69** [comment]
Yes, i will do it in next 24h. Is it okay, when i "Save memory reports" as "anonymized"?

**Comment by ameshkov** [comment]
Yeah totally ok

**Comment by yeezy69** [comment]
Here the memory report after 8 hours of use. At the moment Firefox uses 1.500MB. I don't close my tabs. I had continuous 6 tabs open with things like ebay, nagios, cacti... Tomorrow i will send another report after using firefox 24h. Thank you :)

[memory-report-8h.json.gz](https://github.com/AdguardTeam/AdguardBrowserExtension/files/619953/memory-report-8h.json.gz)

**Comment by yeezy69** [comment]
Here the memory report after 24 hours of use. 

[memory-report-24h.json.gz](https://github.com/AdguardTeam/AdguardBrowserExtension/files/621645/memory-report-24h.json.gz)

**Comment by yeezy69** [comment]
Last one: memory report after 48 hours, same instance, same tabs. (3.7 GB)

[memory-report-48h.json.gz](https://github.com/AdguardTeam/AdguardBrowserExtension/files/624392/memory-report-48h.json.gz)

**Comment by ameshkov** [comment]
Please check the latest beta, the issue should be resolved in it.

**Comment by yeezy69** [comment]
After one hour of use it seems to be fixed. I will test it one more day, report back and close this issue.

**Comment by yeezy69** [comment]
Memory usage now is round about 500MB after one day. Thank you :)
