### ISSUE TITLE
Error in FF console: Unable to run script because scripts are blocked internally

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#45]
A note from AMO reviewer:

> For your next release, please look into the following error, which shows up in the console multiple times:
> chrome://adguard/content/log.html?tabId=4 : Unable to run script because scripts are blocked internally.

**Comment by Mizzick** [comment]
Cannot reproduce

**Comment by ameshkov** [comment]
Yep, this issue is vanished for some reason after we've removed "Components"
