### ISSUE TITLE
Adguard Beta 2.5.1 UI and Icon Didn't Appear In Nightly 53

### ISSUE THREAD

**Issue by bkrcrc** [AdguardTeam/AdguardBrowserExtension#453]
OS: Windows 7 SP1 64bit
Browser: Mozilla Nightly 53.0a1 (64bit)

Please watch: http://recordit.co/ra2cFiSiCz

Stable version has the same problem on my end.

Thanks,

**Comment by Mizzick** [comment]
Thanks for reporting!
We fixed this already in #443.
