### ISSUE TITLE
Change build process so that all Adguard's code will be encapsulated into some kind of a reusable API

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#454]
API:

```
var adguardApi = {
    start: function(callback) {},
    stop: function(callback) {},
    configure: function(configuration, callback)
};

configuration = {
    filters: [],
    whitelist: [],
    blacklist: [] -- // if blacklist is not undefined, block only those domains
};
```

**Comment by atropnikov** [comment]
@ameshkov I think we should remove ```configuration``` parameter from the ```start``` method. We have ```configure``` method for this purpose.

**Comment by ameshkov** [comment]
@atropnikov as you wish:)

**Comment by atropnikov** [comment]
@ameshkov When you have time, please check documentation.
https://gist.github.com/atropnikov/b38ae64bac5f9b5e33232ea840884e21

**Comment by ameshkov** [comment]
@atropnikov you should also explain what is a "filter id". Add a link to the filters.json file for instance.

**Comment by ameshkov** [comment]
Do we indicate start/stop/configure errors somehow?

**Comment by atropnikov** [comment]
I think we can add validation for configuration, this is enough.
