### ISSUE TITLE
Add more filters

### ISSUE THREAD

**Issue by Anoop2609** [AdguardTeam/AdguardBrowserExtension#460]
Can you give more filter like  Dan Pollock’s hosts file, hpHosts’ Ad and tracking servers and MVPS HOSTS.

**Comment by Bluscream** [comment]
Filterlists != Hosts files

**Comment by ameshkov** [comment]
You know what, in theory we can simply convert these hosts files into Adguard filters and let people use them right away. I mean it is the easiest solution, not requiring supporting hosts files syntax.
