### ISSUE TITLE
Blank Space 

### ISSUE THREAD

**Issue by Anoop2609** [AdguardTeam/AdguardBrowserExtension#461]
Adgurad remove ads but not reslove the problem of blank spaces which comes after blocking ads. http://freefeast.info/difference-between/difference-between-bfs-and-dfs-bfs-vs-dfs/ . I found that problem in this webpage and some other but i notice today,

**Comment by Alex-302** [comment]
Please write here
https://github.com/AdguardTeam/AdguardFilters
And fill provided template, when you will open issue.
