### ISSUE TITLE
Extension doesn't work in the integration mode in Waterfox

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardBrowserExtension#473]
![image](https://cloud.githubusercontent.com/assets/15856304/21072180/452610f2-bec2-11e6-80bd-24113024357f.png)

Adguard 1.3.0
Extension 2.4.14
Mac OS X 10.12.1
Waterfox 50.0.21

**Comment by Bluscream** [comment]
Whats waterfox ? xD

**Comment by ameshkov** [comment]
Yet another FF-based browser I guess.

**Comment by vozersky** [comment]
@evgeniy-ADG are you sure that customer has added waterfox to the list of filtered apps in Adguard for Mac app menu?

**Comment by vozersky** [comment]
@evgeniy-ADG   nevermind

confirmed

**Comment by atropnikov** [comment]
Desktop Adguard doesn't filter any requests in Waterfox, so Extension can't detect it. @Stillness-2 Could you check this issue?

**Comment by ameshkov** [comment]
@atropnikov 
Do we have Waterfox in the default browsers list?

**Comment by vozersky** [comment]
@ameshkov  
we do

Also, it seems to work if we delete it from the filtered apps list and then readd
