### ISSUE TITLE
Element collapser causes huge load on certain websites

### ISSUE THREAD

**Issue by SlowMemory** [AdguardTeam/AdguardBrowserExtension#474]
This was reported here https://github.com/SlowMemory/List-KR/issues/71
If I visit http://coolenjoy.net/bbs/TOWTOW/87 with Adguard browser extension 2.5.8 and List-KR filter enabled, the site hangs up and I can't scroll the page for 5~7 seconds.
I believe that this is related to the recent update of element collapser, because profiling session indicates a big overhead on checkShouldCollapseElement function as shown below:
![scrs](https://cloud.githubusercontent.com/assets/19346646/21136398/e009fd4c-c168-11e6-8acc-46653404d828.png)

**Comment by Mizzick** [comment]
Fixed. @ameshkov @vozersky please test #467 after

**Comment by SlowMemory** [comment]
Thank you for a quick fix, but when I tested the latest build as of now (https://github.com/AdguardTeam/AdguardBrowserExtension/tree/45ee8221e1378bdfd147d88374f759bbeefc3bdc), the website in the original post was still a bit sluggish. Can you reproduce this? I hope this can be improved a bit.

**Comment by Mizzick** [comment]
I worked with this site http://www.cooln.kr/bbs/TOWTOW/87
Yeap I have seen in profiler a huge load on shouldCollapse method.
It's now better, isn't it?

**Comment by vozersky** [comment]
http://www.cooln.kr/bbs/TOWTOW/87 is 404 atm, got a new test page?

**Comment by Mizzick** [comment]
Maybe this one http://coolenjoy.net/bbs/TOWTOW/87

**Comment by vozersky** [comment]
to me it's still quite laggy for the first few seconds
