### ISSUE TITLE
Rule constructor works incorrectly with TD tag

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#483]
When TD tag is selected, rule constructor uses class name of the nested element instead his own
Adguard 2.5.9 for chrome
Example link
http://www.depo.ua/rus/politics/nabu-oprilyudnila-video-yak-ohendovskomu-povidomlyali-pro-14122016170300
![image](http://imagizer.imageshack.com/img924/1986/zadIti.png)
![image](http://imagizer.imageshack.com/img921/9072/avmMcF.png)

**Comment by atropnikov** [comment]
```deserializeElement``` function doesn't work correct. 

```serializeElement(<td><span>...</span></td>) => '<td><span>...</span></td>'```
but
```deserializeElement('<td><span>...</span></td>') => <span>...</span>```

**Comment by atropnikov** [comment]
We don't need the entire element in devtools.js, just retrieve element's info (classes, attributes etc).
```
var getSelectedElementInfo = function (callback) {
        browser.devtools.inspectedWindow.eval("DevToolsHelper.getElementInfo($0)", {
            useContentScriptContext: true
        }, function (elementInfo) {
            callback(elementInfo);
        });
    };
```
