### ISSUE TITLE
Some CSS issues with latest beta version

### ISSUE THREAD

**Issue by skipik** [AdguardTeam/AdguardBrowserExtension#486]
https://rutracker.cr/forum/tracker.php

http://jpegshare.net/9e/32/9e32b6abc40a330cfb3eaece0497ee8f.png.html

Opera Dev 44 / Adguard Browser Extension 2.5.9 Hotfix.
Everything is fine on 2.5.8 though.

**Comment by ameshkov** [comment]
Steps to reproduce:
1. Log in or sign up for a new account
2. Go to https://rutracker.cr/forum/tracker.php
3. Keep an eye on the iframe

Three issues
1. `style#adguard-collapse-styles` is empty, but it is still in the `head` element. It **must have been** removed as it is empty.
2. Blocked iframe is not hidden

**Comment by ameshkov** [comment]
@Mizzick bad solution, you'll leave legitimate elements hidden.

**Comment by ameshkov** [comment]
Ok, point 1 is not really an issue. The element is not really empty, it's just dev tools shows it as if it was empty.
