### ISSUE TITLE
avito.ru messages bug

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardBrowserExtension#488]
Message tab on avito.ru shows an error, even when all filters are disabled.

Tested and reproduced in Opera.

Screenshot:
http://radikal.ru/lfp/i013.radikal.ru/1612/a2/e8f44f28f9ca.jpg/htm

**Comment by Mizzick** [comment]
I see the same error even without our extension.

**Comment by vbagirov** [comment]
@Mizzick it works for me once I disable the extension altogether, not just make an exception for avito.ru.

**Comment by atropnikov** [comment]
Error is ```ws instanceof WebSocket => false```
