### ISSUE TITLE
Improve Safari content blocker compile time

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#49]
Read this article:
https://www.webkit.org/blog/4062/targeting-domains-with-content-blockers/

We can try something like that:
```
UrlFilterRule.REGEXP_SEPARATOR = «([:/]|$)»
UrlFilterRule.REGEXP_START_URL = "^https?://([^:/]+\\.)?";
```

I am not yet sure if it's ok, we should also check unit tests.

**Comment by Mizzick** [comment]
This does not make any sense. After testing with updated regexps I can say the compile time is the same.
