### ISSUE TITLE
Get rid of global stylesheet in case of FF add-on

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#493]
We currently use it for collecting ad filters usage stats when user enables "Send ad filters usage stats" option.

The problem is that global stylesheets are very problematic in FF, so let's simply get rid of it and make this option do nothing in FF (at least for now, until we finish with refactoring).

**Comment by The-Commissioner** [comment]
Hmmm.... I gues it's still not time to trust this company. Still sufferring from the same old problem, [duplication](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/405), lack of [response](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/405#issuecomment-254197091) etc. 

Guess I made the right choice.

**Comment by ameshkov** [comment]
@The-Commissioner thanks for reminding about those issues.

Both will be resolved by this change.

However, we should keep them open as they should be re-tested after a huge code reword which will be done in v2.6.

**Comment by The-Commissioner** [comment]
No Sir, I was not reminding about the issues. I was commenting on  the progress of the Support System, which when we last talked was to be revamped within a month but by the looks of it, it ain't happening.

And no I'm no longer helping/using/testing your product, as also stated earlier.

**Comment by ameshkov** [comment]
Done
