### ISSUE TITLE
Adguard forum - problem with avatar

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardBrowserExtension#497]
Логинимся на форуме [Adguard forum](https://forum.adguard.com/index.php). Переходим в Настройки -> [Персональная информация](https://forum.adguard.com/index.php?account/personal-details) -> Аватар `(Нажмите на изображение, чтобы изменить Ваш аватар.)`.

 Нажимаем на картинку дабы изменить аватар -> появляется рамка "Редактировать аватар" -> нажимаем "Обзор" -> выбираем JPEG от 200x200 пикселей `(как рекомендуется)`.
 Итог: справа вверху мелькает прогрузка изображения, верхний баннер "Загрузка успешно завершена" НЕ появляется, место под картинки остаётся НЕ заполненным, вместо имени файла - "Файл не выбран", кнопка "Ok" НЕ нажимается.
![default](https://cloud.githubusercontent.com/assets/17948007/21518541/4736be2a-ccf8-11e6-970e-6b6d1c26c262.jpg)
 Причём после нажатия кнопки "Закрыть" и перезагрузки страницы, оказывается что аватар всё-таки добавился (изменился) и отображается на странице Настроек.

 Для того, чтобы всё правильно заработало, нужно либо Отключить в Настройках ВСЕ Фильтры (Подписки), либо ВЫКЛючить галочку "Фильтрация на этом сайте" и, даже без перезагрузки страницы, ВСЁ заработает.
![default](https://cloud.githubusercontent.com/assets/17948007/21519026/4e371fdc-ccfb-11e6-8121-a24cb556623a.jpg)
 НО, если оставить ХОТЬ ОДИН **ЛЮБОЙ** ФИЛЬТР (Подписку) ВКЛючённым, то загрузка аватара вновь ломается.
 Всё вышеперечисленное пробовал на ОБОИХ браузерах.

___________________________________________________
Pale Moon v26.5 (WinXP) - Adguard legacy v2.5.11
Mozilla FireFox v53.0a1 - Adguard v2.5.11
Английский фильтр | Русский фильтр | Фильтр счетчиков и системы аналитики | Фильтр виджетов социальных сетей | Фильтр раздражителей | Anti-Adblock Killer (Reek)

**Comment by Alex-302** [comment]
добавил в английский фильтр
```
@@||forum.adguard.com/index.php?account$jsinject
```

**Comment by atropnikov** [comment]
Проблема в следующем. Во время загрузки аватара создается ```<iframe src="about:blank" style="display:none;" name="AutoInlineUploader"></iframe>```. Сабмит формы грузит в него json данные (размер, путь и тд). Расширение вставляет в этот iframe стили и скрипты. После загрузки iframe, скрипт пытается распарсить содержимое iframe и не может этого сделать.

**Comment by XX-J** [comment]
Обновил фильтры - Английский фильтр v1.1.4 от 29.12.16 00:00. Ситуация НЕ изменилась.

**Comment by atropnikov** [comment]
@XX-J, странно. Добавленное правило должно исправить проблему. Проверьте, пожалуйста, ошибки из веб-консоли при загрузке аватара.

**Comment by XX-J** [comment]
1. Выяснил: Проблема заключается в "Фильтре виджетов социальных сетей", а точнее как-то связана с классом ".sharePage" см. ниже.
![scrn-20161229154515](https://cloud.githubusercontent.com/assets/17948007/21565916/6596632c-ceae-11e6-8433-c860190bf7f6.jpg)

2. Если я хочу воспользоваться одним или несколькими фильтрами БЕЗ "Английского фильтра", то проблема опять всплывает. Как быть в данном случае? Т.е. я считаю НЕПРАВИЛЬНО привязываться к "Английскому фильтру", если проблема некорректного отображения загрузки аватара через IFRAME заключается в самом Adguard'e или каждом его фильтре в отдельности. В таком случае нужно либо исправлять что-то в самом Adguard'e, либо добавлять исключающее правило ВО ВСЕ ФИЛЬТРЫ.

**Comment by atropnikov** [comment]
@XX-J Проблема в том, что этот iframe нужен только для того, чтобы загрузить туда метаданные аватара, но расширение вставляет туда стили и скрипты (как и в любой другой фрейм). В качестве временного решения можно добавить правило ```@@||forum.adguard.com/index.php?account$jsinject,elemhide``` в пользовательский фильтр. В дальнейшем мы придумаем способ, как избежать таких ошибок. Задачу пока оставляем открытой.

**Comment by Alex-302** [comment]
Правило добавил в английский фильтр.

**Comment by XX-J** [comment]
Теперь, с "Английским фильтром", загрузка происходит правильно.

> В дальнейшем мы придумаем способ, как избежать таких ошибок.

Пришло на ум пару вариантов:
   1. Сделать жёсткую привязку в Adguard'e НЕ ОБРАБАТЫВАТЬ элементы, в которых присутствует style="display:none;" , ведь они, как я понимаю, всё равно НЕ ВИДНЫ.
   2. Вшить в Adguard, если ещё не вшит, не изменяемый извне скрытый фильтр, в который и заносить подобные исключения.
