### ISSUE TITLE
Adguard extension breaks some sites

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardBrowserExtension#499]
4pda.ru, avito ru

1. Windows 8.1
2. Версия Adguard: 2.5.8
3. Опера 42
4. Всякие "защитники" и "брандмаузер" отключены.
5. Отключение других расишрений не помогает
6. Внесение в белый список не помогает

> Вкладки с открытым форумом 4пда.ру зависают. Помогает только полное отключение расширения. Браузер Опера 42. Настройки проверял, в белыйсписок тоже добавлял, не помогло.

> Отключал фильтры поочередно, не помогло. К тому же, полностью отключена  фильтрация для этого сайта, но проблема остается. Помогает только полное 
отключение самого расширения в настройках браузера. Другие расширения отключал и тем самым выявил, что проблема возникает именно при включенном расширении adguard

> Обнаружил еще проблему, теперь уже с avito.ru, а имеено с сообщениями на сайте. То есть, если adguard включен в  расширениях, то на авито, сообщения просто не загружаются, стоит отключить Adguard в расширениях, сразу начинает все работать. При этом, ползунок "фильтрация на этом сайте" никак не решает проблему, только полное отключене расишрения

1474259

**Comment by Alex-302** [comment]
4pda уже не должен зависать. Исключил правила с расширенным CSS.
Открыл баг
https://github.com/AdguardTeam/ExtendedCss/issues/24

**Comment by Mizzick** [comment]
Please check the latest release
https://github.com/AdguardTeam/AdguardBrowserExtension/releases/tag/v2.5.11

**Comment by ameshkov** [comment]
Duplicate for #488
