### ISSUE TITLE
Integrate with Chrome DevTools

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#5]
We should add custom sidebar Panel to chrome developer tools Elements panel.

Will be really handy for filters developers.

Chrome documentation:
https://developer.chrome.com/devtools

**Comment by ameshkov** [comment]
Here is how it should look like:
<img width="1301" alt="00001080" src="https://cloud.githubusercontent.com/assets/5947035/15669104/3f99ec18-2727-11e6-9d77-2abd8758869d.png">

#### Panel content
Content is almost similar to Assistant dialog, but with some important improvements.

Take a look at this screenshot for details:
<img width="903" alt="dev_tools" src="https://cloud.githubusercontent.com/assets/5947035/15669516/5e7579d4-2729-11e6-98d9-b73a1992f95e.png">

**Comment by gshumihin** [comment]
Here's some feedback:
http://screencast.com/t/bWIbb6Axn
http://screencast.com/t/2Of6rKGuGWhT

Also, make <head> tag unselectable.

**Comment by Mizzick** [comment]
Ok fixed

**Comment by gshumihin** [comment]
Here's one more issue:
Too much elements blocked after i selected element to block and clicked "preview" button. Same situation with adding rule. But when i reload the page, issue is gone. Here's video: http://screencast.com/t/WAGqcY8GbC

**Comment by Mizzick** [comment]
Fixed

**Comment by ameshkov** [comment]
Take a closer look at this mockup:
https://cloud.githubusercontent.com/assets/5947035/15669516/5e7579d4-2729-11e6-98d9-b73a1992f95e.png

**Comment by ameshkov** [comment]
#### Rule builder fields

**Rule properties:**
[x] domain name (checked by default)
[] include CSS path (unchecked by default)
[] block by URL (visible for elements with src attribute only)

**Attributes**
[x] element name (checked by default)
[x] attribute1        (checked in case of "id" or "class" attributes, unchecked for all other types)
[x] attribute2
[x] attribute3

#### Logic

**block by URL:**
If this box is checked all other checkboxes should become "disabled".

**class attribute**
If element has multiple classes there should be multiple checkboxes one for each class name.

**Comment by Mizzick** [comment]
Fixed

**Comment by ameshkov** [comment]
1. Page reload is needed in Chromium
2. Tag name is not applied
3. For some elements I see just a domain name instead of the rule text
4. When dev tools is just opened - I see empty checkboxes. Why so? By default body element is selected.

**Comment by Mizzick** [comment]
1. Just tried with latest Chromium Version 54.0.2792.0 (64-bit), page reload is not needed.
2. Fixed
3. Fixed
4. Fixed

**Comment by ameshkov** [comment]
A pack of new bugs:
https://monosnap.com/file/nsr1HCdg1DXXUkLFxuoDJdjrkZVVG5
https://monosnap.com/file/aAH8YuFqPZZTp59psyyzD6M5AkXC5T

**Comment by Mizzick** [comment]
Fixed

**Comment by gshumihin** [comment]
Button "cancel preview" stays even after page reload.

**Comment by Mizzick** [comment]
Ok
