### ISSUE TITLE
hdfullfilmizlesene.net - embed[src] with blocked src is not collapsed

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#500]
http://www.hdfullfilmizlesene.net/anaokulu-polisi-2-kindergarten-cop-2-turkce-dublaj-izle/
<details>
![image](http://i88.fastpic.ru/big/2016/1230/47/173fb9b1b421c2b934dcd257b8b1f747.jpg)
</details>

**Comment by atropnikov** [comment]
1. Blocked embed fires ```load``` event, instead of ```error```.
2. ```embed``` tag is absent in ```requestTypeMap``` in preload.js
