### ISSUE TITLE
User filters with HTML filters are not saved

### ISSUE THREAD

**Issue by Ashus** [AdguardTeam/AdguardBrowserExtension#502]
I tried to write some user filters with HTML filtering according to documentation. Unfortunately everytime I try to import a rules file with a line containing `$$script`, it gets dropped.
If I add it manually and hit F5, it is also deleted right away.
When I add the lines manually and keep the configuration open, filtering works fine.

Using Opera 43 x64, Windows 10, AdGuard 2.5.11

**Comment by atropnikov** [comment]
@Ashus HTML filtering rules are not supported by browser extension.
