### ISSUE TITLE
nstarikov.ru - video players are invisible

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#503]
URL:
https://nstarikov.ru/blog/72008
Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/15856304/20061823/1d172dac-a50a-11e6-858e-71381a26c70f.png)
</details>
Browser: Chrome

Not reproduced on my side, only on @vgavrish pc.
`@@||nstarikov.ru^$elemhide` does not help.

Issue in AdguardFilters:
https://github.com/AdguardTeam/AdguardFilters/issues/3358

**Comment by Alex-302** [comment]
Added temporary rule
```
nstarikov.ru#$#.video-wrapper iframe[src] { height: 470px!important; }
```

**Comment by Alex-302** [comment]
Скрывалось из-за проблемы в расширении.
> а у вас нет ?

этого не знаю)

**Comment by ameshkov** [comment]
Seems to be "by design", let's leave that temporary rule forever:)

**Comment by Alex-302** [comment]
аналогичная проблема - тоже плеер ютуба скукожило (iframe.embedly-embed)
https://github.com/AdguardTeam/AdguardFilters/issues/4921
при этом все фильтры выключены, для повторения достаточно добавить любое правило сокрытия, например, `therebel.media##body > br`
пока добавил
```
therebel.media#$#iframe.embedly-embed { max-height: 400px!important; }
```

**Comment by ameshkov** [comment]
Ну давай еще одно временное правило добавим, чего уж
