### ISSUE TITLE
[Feature request] Add the ability to use DNS protection in extensions

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardBrowserExtension#504]
Есть предложение расширить и усилить возможности защиты, по аналогии с плагином Fox Web Security, в котором можно подключать любой DNS - пользователь сам делает настройки (Яндекс, Norton, Comodo и любые другие).

https://addons.mozilla.org/ru/firefox/addon/fox-web-security/

Блокирует не только запросы, но и опасные подзапросы. Причем нагрузки на браузер вообще не ощущается.

**Comment by ameshkov** [comment]
Проблемы:

1. Будет работать только в FF
2. Когда в конце года FF перейдет на новое SDK для расширений, перестанет работать и в нем.
