### ISSUE TITLE
Safari tab / Ergonomics issue

### ISSUE THREAD

**Issue by Shade69** [AdguardTeam/AdguardBrowserExtension#505]
Hi team :)
In the safari extension, could you update and align theses graphics? :

- MacOS Sierra logo : https://support.apple.com/content/dam/edam/applecare/images/en_US/mac-os/featured-content-sierra-roundel_2x.png
- iOS 10 logo : https://commons.wikimedia.org/wiki/File:IOS_10_Logo.png

<img width="458" alt="adguard" src="https://cloud.githubusercontent.com/assets/672816/21764972/2d49ff82-d666-11e6-868a-5a54bed84489.png">

Thank you ! 👍 
Best regards.

Jean-Philippe.

**Comment by danidoedel** [comment]
Better use the official graphics and follow Apples guidelines in that case...

https://developer.apple.com/app-store/marketing/guidelines/
https://developer.apple.com/softwarelicensing/agreements/maclogo.php

**Comment by Shade69** [comment]
You are totally right, i almost forgot the marketing things 😕

**Comment by ameshkov** [comment]
Makes sense, thank you for the links guys!

**Comment by Shade69** [comment]
Thanks Ameshkov. Also in the last version of Safari extension, when you open the tab there is a "double border" bug at the bottom 😉

<img width="341" alt="double border" src="https://cloud.githubusercontent.com/assets/672816/25182048/baa7e0b4-2513-11e7-8c86-194996a1ed3a.png">

**Comment by ameshkov** [comment]
Yup, thanks for reporting it!

**Comment by vozersky** [comment]
And what about the icon placement, guys?

**Comment by Shade69** [comment]
This depends on whether you are using new or old icons. As seen at the top of the topic, the old ones are not. Thanks ! 😃
