### ISSUE TITLE
@@*$generichide issue

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardBrowserExtension#507]
Generichide exceptions don't work correctly in Safari.

STR:
1. Install 2.5.11 extension to Safari
2. Import [rules.txt](https://github.com/AdguardTeam/AdguardBrowserExtension/files/694100/rules.txt)
3. Open:
www.championat.com
www.khabar.ndtv.com
www.bild.de

**Comment by vozersky** [comment]
duplicates #437

**Comment by ameshkov** [comment]
@vozersky it is not duplicate I guess, something new.

@Mizzick it appears something is wrong with third-level domains.

Here is a relevant forum discussion:
https://forum.adguard.com/index.php?threads/ndtv-com-anti-adb-ios.18066/

**Comment by gotitbro** [comment]
@ameshkov `$generichide` filters don't work even on second level domains. For example:
Add `##img` to **User Filters** and visit _**github.com**_ all avatars should be hidden even after you add 
`@@||github.com^$generichide` the avatars are still hidden.

**Comment by Alex-302** [comment]
@gotitbro Can you confirm the same issue with $genericblock exclusions?

**Comment by gotitbro** [comment]
@Alex-302 **_$genericblock_** are working, I checked this by adding `@@||timesofindia.com^$genericblock` to the **User Filter** and the visited: http://m.timesofindia.com/world/us/obama-ends-open-door-policy-for-cuban-migrants-white-house/articleshow/56509375.cms

The ads were visible which would have been blocked by generic blocking rules such as `||doubleclick.net^` ads and `||clmbtech.com^` ads were visible.

**Comment by Mizzick** [comment]
```
[
	{
		"trigger": {
			"url-filter": ".*"
		},
		"action": {
			"type": "css-display-none",
			"selector": "img"
		}
	},
	{
		"trigger": {
			"url-filter": "^https?://([^/]*\\.)?championat\\.com[/:&?]?",
			"resource-type": [
				"document"
			]
		},
		"action": {
			"type": "ignore-previous-rules"
		}
	}
]
```

ok, this is a simple content blocker file, produced by only 2 rules:

> ##img
> @@||championat.com^$generichide

but it doesn't work as expected.

**Comment by ameshkov** [comment]
@Mizzick could it be that `resource-type` is the culprit?

**Comment by Mizzick** [comment]
I've tried without, I guess something is wrong with this url-filter

**Comment by ameshkov** [comment]
@Mizzick shouldn't it be `^https?:**\/\/**`

**Comment by ameshkov** [comment]
@Mizzick just experiment with the `url-filter` then

**Comment by Mizzick** [comment]
ok, fixed

**Comment by ameshkov** [comment]
@Mizzick wait a bit, I didn't mean you should get rid of `url-filter`:)

**Comment by Mizzick** [comment]
Temporary fixed with "if-domain" triggers

**Comment by Mizzick** [comment]
After some investigations, we've found that "url-filter" doesn't work properly for css exceptions("ignore-previous-rules" for "css-display-none").
As an example:

Testing on https://lenta.ru
with simple content blocker:
```
[{trigger: {url-filter: ".*"}, action: {type: "css-display-none", selector: "img"}},
 {trigger: {url-filter: "^https?://([^/]*\\.)?le.*"}, action: {type: "ignore-previous-rules"}}]
```
These url-filter trigger an exception and first rule is ingored:
```//"url-filter": ".*"
                    //"url-filter": "https:*"
                    //"url-filter": "^https?:*"
                    //"url-filter": "^https?://*"
                    //"url-filter": "^https?://([^/]*\\.)?*"
                    //"url-filter": "^https?://([^/]*\\.)?l*"
```
But these do not:
```
//"url-filter": "https:\\/\\/lenta\\.ru"
                    //"url-filter": "https://lenta.ru/*"
                    //"url-filter": "https://lenta\\.ru"
                    //"url-filter": "https:\/\/lenta\.ru"
                    //"url-filter": "^https://lenta*"
                    //"url-filter": "^https?://lenta*"
                    //"url-filter": "^https?://icdn.lenta*"
                    //"url-filter": "^https?://lenta.*"
                    //"url-filter": "^https?://([^/]*\\.)?lent*"
                    //"url-filter": "^https?://([^/]*\\.)?le*"
```

**Comment by gotitbro** [comment]
@ameshkov @Mizzick Can this be considered fixed then?

**Comment by ameshkov** [comment]
@gotitbro yep, we've rolled it back to what we had in v2.4

Additionally, I'll file a bug report to WebKit shortly.

**Comment by gotitbro** [comment]
@ameshkov Can you push the fix to iOS as a minor update as well? Been waiting for a long time, can't access a lot of sites due to this bug.

**Comment by ameshkov** [comment]
@gotitbro sure!
