### ISSUE TITLE
Safari Content Blocker Problem

### ISSUE THREAD

**Issue by atropnikov** [AdguardTeam/AdguardBrowserExtension#510]
This part of code doesn't work correct
```
_createUrlFilterString: function (filter) {
    if (filter.urlRegExp) {
        return filter.urlRegExp.source;
    }

    if (filter.getUrlRuleText() == '||*') {
        return URL_FILTER_ANY_URL;
    }
    
    var urlRegExpSource = filter.getUrlRegExpSource();
    if (urlRegExpSource) {
        return urlRegExpSource;
    }

    // Rule with empty regexp
    return URL_FILTER_ANY_URL;
}
```
If ```urlRegExp``` has been initialized, it will not be replaced with ```SimpleRegex.regexConfiguration.regexStartUrl``` and ```SimpleRegex.regexConfiguration.regexSeparator``` and rule will not be created.

Maybe it will fix #508 and #507

**Comment by Mizzick** [comment]
Why it won't be replaced?

These strings are applied on urlRegExp creation:
```
regex = replaceAll(regex, regexConfiguration.maskAnySymbol,regexConfiguration.regexAnySymbol);
regex = replaceAll(regex, regexConfiguration.maskSeparator, regexConfiguration.regexSeparator);
```

https://github.com/AdguardTeam/AdguardBrowserExtension/blob/719726975d0858acd7e0b8e27c251ecc9c031083/Extension/lib/filter/rules/simple-regex.js#L108-L108

and then replaced with safari-friendly templates:
https://github.com/AdguardTeam/AdguardBrowserExtension/blob/171028406e76b0f77893c6669f8cbddc3d7224e3/Extension/browser/safari/lib/converter.js#L390-L390

**Comment by atropnikov** [comment]
@Mizzick  This test will fail
```
QUnit.test("Content Blocker RegExp Problem", function (assert) {

    var rule = new adguard.rules.UrlFilterRule('@@||4players.de^$genericblock', 0);

    var result = SafariContentBlockerConverter.convertArray([rule]);
    assert.ok(result.errorsCount, 0);

    // Initialize regexp (while processing request from content script for example)
    assert.ok(!!rule.getUrlRegExp());

    // Convert again
    result = SafariContentBlockerConverter.convertArray([rule]);
    assert.ok(result.errorsCount, 0);
});
```
Error message:
```
Error converting rule from: @@||4players.de^$genericblock cause:
Error: Safari doesn't support '|' in regular expressions
```

**Comment by ameshkov** [comment]
Do not allocate array every time:
`if (['||*', '', '*'].indexOf(filter.getUrlRuleText()) >= 0) {`
