### ISSUE TITLE
new sitename of dreamfilmhd.sh

### ISSUE THREAD

**Issue by cabban** [AdguardTeam/AdguardBrowserExtension#511]
hello this new site is full of ads and pop up ads hope u could fix this :) 
thank iu in advanced
![image](https://cloud.githubusercontent.com/assets/19514493/21953405/06060dd4-da36-11e6-80bf-3c3762567965.png)

**Comment by Alex-302** [comment]
Fixed. Please write to AdguardFilters repository next time.
