### ISSUE TITLE
Separate loading of the cosmetic filters and JS filters

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#512]
Currently, we load both types of filters via one request to a background page.

The problem is that loading of the cosmetic filters takes some time (~5-10ms), which also delays JS rules execution. We often need to execute JS rules as soon as possible and even that slight delay might be too much and may allow page own scripts to be executed first.

I suppose, that the only solution to this issue is to separate loading of cosmetic and js filters into two requests.

**Comment by atropnikov** [comment]
Actually, time between request to and response from background page takes from 50 to 300 ms (It was measured without fetching css rules);
