### ISSUE TITLE
Regular expressions with $ aren't processed properly

### ISSUE THREAD

**Issue by adbuker** [AdguardTeam/AdguardBrowserExtension#517]
related to https://github.com/AdguardTeam/AdguardForWindows/issues/1475

**Comment by atropnikov** [comment]
Also, I discovered following things. `findShortcut` and `extractRegexpShortcut` can return empty string. For instance: `@@||*$domain=lenta.ru` and `/(.jpg)$/`. In this case, our check for shortcut doesn't work, because we assume that shortcut can't be empty, only null.
