### ISSUE TITLE
Edge extension issues

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#521]
We should test it on both Anniversary update and Insider Preview fast ring.

#### Adding filter subscription

**Steps:**
1. Try to add a new filter subscription.
2. Turn all other filters off.
3. Check if the new filter works correctly.

**Expected result:**
1. New filter has been added successfully and works correctly.

**Actual result:**
Fail

#### Removing filter subscription

**Steps:**
1. Remove one subscription.
2. Turn off all filters.
3. Enable recommended filters list.

**Expected result:**
1. Ads are not filtered when all filters are disabled.
2. Ads are filtered correctly when recommended filters are enabled.

**Actual result:**
Fail

#### Test User filter

**Steps:**
1. Open User filter.
2. Add ||vk.com$elemhide
3. Add ||lostfilm.tv##.left
4. Open vk.com and lostfilm.tv

**Expected result:**
Pages are broken.

**Actual result:**
Fail

#### Test popup rules

**Steps:**
1. Add ||mywot.com^$popup to User filter
2. Go to: http://www.sitejabber.com/reviews/www.mywot.com
3. Try to click on the link.

**Expected result:**
mywot.com should not be opened.

**Actual result:**
Fail

#### Test $elemhide rules

**Steps:**
1. Open lenta.ru
2. Block any image by URL
3. Block any element with elemhide rule
4. Add @@||lenta.ru^$elemhide

**Expected result:**
1. Image (point 2) remains blocked 
2. Element (point 3) becomes unblocked

**Actual result:**
Fail

#### Test User filter clear/import/export

**Steps:**
1. Import rules to User filter.
2. Export rules from User filter.
3. Clear User filter.

**Expected result:**
1. Rules are correctly imported
2. Rules are correctly exported
3. User filter is empty.

**Actual result:**
Fail. Export rule is not working
Note – There were no rules files to import. 

#### Ad filtering on websites that were excluded by rules in filters.

**Steps:**
1. Add some websites to whitelist.
ulmart.ru
mchs.gov.ru
2. Test if the websites are filtered.
3. Add @@||lenta.ru$document to User filter
4. Lenta.ru should not be filtered.

**Expected result:**
"Invert whitelist" doesn't override exceptions.

**Actual result:**
Fail

**Comment by ameshkov** [comment]
@vozersky I suppose some test cases are just too vague and MS guy could not have understood what should be done. Please take a look at the failed cases.

Also one more issue: Test popup rules. We use some third party website to do the test. This is wrong, instead we should create our own test page and use it.

**Comment by atropnikov** [comment]
Problem **Ad filtering on websites that were excluded by rules in filters** is common for all browsers. I'll fix it.

**Comment by atropnikov** [comment]
Extension test page http://static.adguard.com/test_extension.html

**Comment by vozersky** [comment]
Passed on the latest build (14393.693):

* Adding filter subscription 
* Removing filter subscription
* Test User filter
* Test $elemhide rules 
* Ad filtering on websites that were excluded by rules in filters 

I will fix those cases to make them clear enough. 

Did not pass on the latest build (14393.693):

* Test popup rules
Popup rule doesn't work

* Test User filter clear/import/export 
export doesn't work, same as @atropnikov has stated in the previous message. 
import and clear do work fine

**Comment by vozersky** [comment]
***Regarding 2.5.12:***

1. Fields glitch: If you add a rule (to User filter for example) and press enter, the cursor will stay in the same line, and you can type more symbols and if you press enter again they will appear.

**Comment by atropnikov** [comment]
Seems, there is a bug in Edge with `Save as`. The code works in jsfiddle for example, but doesn't work on extension page.
```
var blob = new Blob(['rule']);
window.navigator.msSaveOrOpenBlob(blob, 'rules.txt');
```

**Comment by ameshkov** [comment]
It appears `msSaveOrOpenBlob` works OK in new build.
