### ISSUE TITLE
Chrome incognito mode

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardBrowserExtension#522]
Hello. In Icognito mode phishing websites opened in normal mode, not in incognito. 
Adguard version: Latest beta

![screenshot_95](https://cloud.githubusercontent.com/assets/19608513/22150631/7e45f01e-df33-11e6-881e-64d29fe86afb.png)

**Comment by atropnikov** [comment]
@thislife81 Chrome doesn't allow to open the chrome-extension:// page in incognito mode.

**Comment by ameshkov** [comment]
@atropnikov is it still an issue?

**Comment by atropnikov** [comment]
@ameshkov No, it isn't.

**Comment by thislife81** [comment]
Okay I got you
