### ISSUE TITLE
Migrate FF add-on to WebExtensions

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#523]
Here we'll collect everything regarding add-on migration including all the incompatibilities found.

Migrating stored data:
https://blog.mozilla.org/addons/2017/01/20/migrating-to-webextensions-port-your-stored-data/

**Comment by BooBerry** [comment]
It might be easier than you think.

As an experiment I installed the Firefox extension Chrome Store Foxified which can take Chrome extensions from the Web Store and upload them to AMO and actually sign them if you have an account (which I do). I didn't think it'd work, but damn, it took 2.5.11 from the Web Store and made it into a working WebExtension for Firefox.

And it actually _works_. Settings open up and respond well rather well (except a lag/delay when importing a user filter, which is the same with the normal Firefox version), and it's actually blocking ads on webpages (plus the Adguard button on the toolbar works along with the blocked ads count).

Of course on AMO's validation results it gives 16 warnings, but no errors and the WebExtension for Firefox actually _works_ from what I can tell.

**Comment by ameshkov** [comment]
It is easy indeed, I've tried it with v2.5 build earlier as well. I am not sure about some known Chromium issues like WebSocket blocking, though.

**Comment by BooBerry** [comment]
ws://adguardwebsocket.check/ad.adriver.ru
WebSocket
.adriver.$~object-subrequest
ad.adriver.ru

Yep, it's doing WebSocket too, it looks like.

**Comment by ameshkov** [comment]
In that build it uses special Chromium hack to handle WS, we should make FF-specific build to check it.

**Comment by ameshkov** [comment]
The second thing to handle is settings migation

**Comment by BooBerry** [comment]
I added a screenshot above, it seems to be working rather well.

I'm surprised, I thought WebExtensions support in Firefox wasn't good enough yet. I guess I is? =P

**Comment by ameshkov** [comment]
Yeah, they did a good job indeed:)

**Comment by ameshkov** [comment]
We've decided to migrate FF add-on to WebExtensions starting from version 2.6

**Comment by BooBerry** [comment]
That's great news. But the issue where there's a momentary browser lockup of a few seconds when first opening the settings, clearing/importing the user filter, etc. is still there, even with a converted WebExtension.

**Comment by ameshkov** [comment]
I wonder why can't I reproduce it.

Please try the newer build:
[firefox-amo-beta-2.6.0.xpi.zip](https://github.com/AdguardTeam/AdguardBrowserExtension/files/909811/firefox-amo-beta-2.6.0.xpi.zip)

**Comment by BooBerry** [comment]
Can't install it because it isn't signed (lawl!).

It happens in multiple OSes in Firefox-only. These are the following settings I have enabled (since there's no export yet) which reproduces it 100% of the time. I only have the **Indicate the number of blocked ads on the Adguard extension icon** setting enabled, along with **Phishing and malware protection** and **Add Adguard item to browser's context menu** enabled. All other settings are disabled. For filters I have the **English filter**, **Spyware filter**, **Annoyances filter** and **Malware Domains** enabled. User filter doesn't matter, BUT if you import a user filter (with 300+ rules) it will freeze/lockup Firefox for a few seconds while importing.

**Comment by ameshkov** [comment]
> Can't install it because it isn't signed (lawl!).

Add-ons -> click on "settings" icon there -> Debug add-ons -> Load temporary add-on

**Comment by BooBerry** [comment]
That's handy.

Still reproducible though. It seems to lockup/freeze while loading the filter lists and/or user filter, along with importing a large user filter.

**Comment by ameshkov** [comment]
@BooBerry let's sort the first issue (with settings).

Does it freeze every time when you open the settings page?

**Comment by BooBerry** [comment]
In 2.5.11 it does. But in this newer build it only does if I add the 4 filters above without updating them.

If I add the filters above, enable the settings I have enabled above and import a large user filter then close the settings then reopen it, there's indeed a lockup while it's loading the 4 filter lists. If I update the 4 filters then repeat, it seems to open instantly.

Here's the clincher, I remove the user filter without updating the 4 filter lists, guess what? It opens instantly without any type of freeze or lag.

It's related to the user filter loading, more than likely.

**Comment by ameshkov** [comment]
@BooBerry yep, you're right, user filters takes quite some time to load

**Comment by ameshkov** [comment]
@Bohdan-SUP filed a separate issue:
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/641

Moreover, the very same issue is here with the Chrome extension.

**Comment by BooBerry** [comment]
It's funny, I've never experienced it with Chrome at all. I'll retest it here in a bit.

Might want to test Edge too, just because. :)
