### ISSUE TITLE
rutor.info - page loading hangs for a few second

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardBrowserExtension#526]
http://rutor.info/ (http://multi-tor.org/)
firefox 50.1.0
extension 2.5.11
on going from Main to Top  and vice versa
![screenshot 2017-01-25 13 46 02](https://cloud.githubusercontent.com/assets/23637588/22293615/60155ef8-e321-11e6-8cd4-a82396853418.png)

**Comment by ameshkov** [comment]
We have already fixed it once, @Mizzick

**Comment by Mizzick** [comment]
will need to check this after
https://forum.adguard.com/index.php?threads/2-0-4-%D0%94%D0%B5%D1%84%D0%B5%D0%BA%D1%82-%D1%81-%D1%81%D0%BE%D0%B4%D0%B5%D1%80%D0%B6%D0%B8%D0%BC%D1%8B%D0%BC-%D0%B2%D0%BA%D0%BB%D0%B0%D0%B4%D0%BA%D0%B8-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B5%D0%BA-%D0%B2-ff.4260/#post47275
