### ISSUE TITLE
Basic URL rule, which contains domain name, blocks WS

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#528]
For example - player, which uses WS, is blocked by `/flirt4free.`
WS address: `ws://chat004.vs3.com:42121/chat?token=QldcTF5JZw==`
Maybe that's because some wide rules like that blocks:
ws://adguardwebsocket.check ***/domain.*** com

**Comment by ameshkov** [comment]
I guess if we want it to work similarly to other ad blockers, we should remove domain name from the `adguardwebsocket.check` url.

**Comment by Mizzick** [comment]
But I think it's very useful now, why do we have to remove this?

**Comment by ameshkov** [comment]
It'd be better if AG rules syntax is compatible with all other ad blockers, just to let us all use the same filters.

**Comment by atropnikov** [comment]
We could find matching rule only with `$websocket` modifier. But for this, we have to while rule parsing try to detect `websocket` rules, like `|ws://$domain=4shared.com`

**Comment by Mizzick** [comment]
I do not understand you. 
So we have the rule `/flirt4free`, which blocks websocket request from the player. It's correct, isn't it?

**Comment by atropnikov** [comment]
No, this rule shouldn't block websocket request.

**Comment by Mizzick** [comment]
Please provide a clear example?

**Comment by atropnikov** [comment]
Open `http://www.flirt4free.com/`, disable English filter. Add `/flirt4free.` rule.
Expected: URL `ws://adguardwebsocket.check/flirt4free.com` is NOT blocked
Actual: URL `ws://adguardwebsocket.check/flirt4free.com` is blocked
