### ISSUE TITLE
Extension interface feature request 

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardBrowserExtension#529]
В расширении для браузера при клике по иконке расширения открывается
превью, там и находятся(внизу) ссылки для перехода на загрузку версий для
андроид, виндовс и др. 

<details>

![fcdgtxv](https://cloud.githubusercontent.com/assets/17504743/22329284/7ca37504-e3b8-11e6-90d6-e37fa76cc88c.png)

</details>

Можно эти ссылки перенести в настройки расширения
для браузера?

Ticket: https://qcrm.supportyourapp.com/#/customer/1494083

**Comment by ameshkov** [comment]
Ну это вопрос дизайна все же. Мы это примем к сведению.
