### ISSUE TITLE
[Wish] Confirmation popup after sending a report via extension

### ISSUE THREAD

**Issue by bkrucarci** [AdguardTeam/AdguardBrowserExtension#53]
as the title said. I send "missed ads" and "phishing suspected" websites via extension menu.
I send reports but UI disappears after I click on "Submit" but the extension does not tell me about Did it send or it did not send.
So we need a small popup for "confirmation"
I hope I could explan my wish. Please consider this.
Thank you.

**Comment by ameshkov** [comment]
This is a good idea, but we want to do more than this.
We'd like to allow users create a detailed reports: #54
