### ISSUE TITLE
[Firefox] Worse works than on Google Chrome.

### ISSUE THREAD

**Issue by pro100Hub** [AdguardTeam/AdguardBrowserExtension#530]
Firefox 51.0
AdGuard 2.5.11

Worse works than on Google Chrome. In Mozilla Firefox works with minor delays. Pages load slowly and the reason in AdGuard. Without AdGuard works well.
Needs optimization. Please fixed.

Regards,

**Comment by ameshkov** [comment]
Hi! Any website or some particular websites?

**Comment by pro100Hub** [comment]
Hi, ameshkov!
Any website :(
You can check(test) yourself. Firefox with an extension AdGuard page opens slowly(delayed) than Google Chrome. Without AdGuard, Firefox works better.
There is also a problem with some sites, such as 'rutor.info'. I see a theme already exists on this error here: #526 
In general extension works worse, than in Google Chrome and it depends not on the browser, a from AdGuard extension.
I like your extension "AdGuard" and i do not want to delete it or move to another extension. Please carry out the analysis and make the optimization and increase the speed of his work on the Mozilla Firefox browser.

Regards,

**Comment by ameshkov** [comment]
Got it, thank you for the explanation!

I guess this slowdown cause is the same as in case of `rutor` issues, so I mark this issue duplicate. We'll try to fix it asap.
