### ISSUE TITLE
Can't Export Extension Filters 

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardBrowserExtension#532]
id 1291087
Current version 2.5.11
Chrome\FF

**Steps to reproduce:**
1. Go to Adguard settings
2. Go to User filter section
3. Add few rules to User filter list
4. Press "Export" button

**Result:** export file wasn't downloaded

<details>

![image](https://cloud.githubusercontent.com/assets/18548949/22369981/aa9843e2-e497-11e6-9bc9-4b9f4e95c3ca.png)

![image](https://cloud.githubusercontent.com/assets/18548949/22369983/b446bd9c-e497-11e6-8a25-b5b2ac6d9bae.png)

**Comment by atropnikov** [comment]
@vgavrish rules with `$replace` modifier are not supported by the browser extension. That's why you don't see it on export page.

**Comment by dallas7** [comment]
In the email reply to my initial 01/26 submission as Ticket ID: GPC-127-17309, it said "We were able to reproduce the issue at our end and filed the task for developers...Once resolved, it will be closed and marked with ‘Fixed’ label."
I see here only "closed."  So, no resolution?
In my submission I reported the download failure occurs with both the Whitelist _and_ User filter exports, the former having been left out of "steps to reproduce" above.
Also left out was my mention that the exports work A-OK in v49 and v50.  The failure appeared with v51.  
I set up Google Chrome imported my User filters, added another filter and exported OK.
Finally, the text "$replace" in my User filters does not exist and it's not that $replace is not seen on the export page - nothing is seen.
As well, in my Whitelist are five domain names, www.something.com - nothing fancy.
What now?
Thank you.

**Comment by evgeniy-ADG** [comment]
Replied through support.

**Comment by atropnikov** [comment]
Hello, @dallas7. Sorry for the misunderstanding and thank you for your cooperation. I investigated your problem, the corresponding issue is #541. Unfortunately, we cannot solve this problem completely. We are going to release a new version that fixes this problem (with some restrictions) and some performance issues soon.

**Comment by dallas7** [comment]
No problem.  Thanks for re-evaluating this discussion.  I understand the extension is free and your Web site indicates no support vs your licensed product.

But as a user, a minority in your customer base no doubt, who uses the "Block ads in this website" function (I have 42 rules) I wanted to report the problem.  Some one else will surely run into it, too.

There's no problem importing, so I can work around it by pasting the new rule from the settings page into the last-good exported file.

I read in the forum that v2.6 is in the works and I look forward to it.

Cheers.

**Comment by Bohdan-SUP** [comment]
@atropnikov 

The same thing happens in Chrome with Adguard 2.5.11 with a rule like ```$$script[tag-content="banner"]``` - it won't get exported.

Is this by design?

**Comment by Alex-302** [comment]
@Bohdan-SUP `$$` rules are not supported by browser extensions

**Comment by ameshkov** [comment]
Should we allow adding them?
