### ISSUE TITLE
Popups NOT BLOCKING by generic rule

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardBrowserExtension#533]
http://unutulmazfilmler.co/ ---> http://s24.postimg.org/hxt9wd0l1/screenshot_170.png
http://dizipub.com/ ---> http://s24.postimg.org/v38s2gugl/screenshot_171.png

**Comment by ameshkov** [comment]
It'd be better to report those issues to AdguardFilters next time.

@seanl-adg please take a look.

**Comment by seanl-adg** [comment]
It will be fixed when browser extensions support `$empty`.
