### ISSUE TITLE
How to add filter to filters.json

### ISSUE THREAD

**Issue by heubergen** [AdguardTeam/AdguardBrowserExtension#534]
Hi

I wanna add a new filter I saw on github to this extension but I didn't find a contribution.md so I ask here.

I'm not sure how you handle new filters in the filters.json file, should I just provide you the URL and hompage and you do the rest or can I do that on my own?

- heubergen

**Comment by Alex-302** [comment]
Hi. What do you want to add?

**Comment by heubergen** [comment]
Sorry for being unspecific, I try my luck with #543 :)

**Comment by Alex-302** [comment]
Ok, I understand you now:)
Please write to https://github.com/AdguardTeam/AdguardFilters/issues
and we will add it(we do it in other way).
