### ISSUE TITLE
Adguard affects scrolling speed on facebook

### ISSUE THREAD

**Issue by pedrogarcia** [AdguardTeam/AdguardBrowserExtension#535]
I've noticed that the Adguard browser extension for Chrome (64 bit stable, Windows 10 Build 14393.726) significantly affects the scrolling speed on facebook.com, making it jankier. 
I can swear it happens on other websites as well, but on facebook it is most noticeable. 
I was not able to isolate the cause of this, but I tested ublock origin with the default filters as well, and the issue is not present, so it is not my computer being slow!

I have the following filters enabled:

> English filter Version 1.1.7.75. Updated 29 january 2017 at 18:00.
> Spyware filter Version 1.0.10.50. Updated 29 january 2017 at 12:00.
> Social media filter Version 1.0.16.93. Updated 29 january 2017 at 17:00.
> Annoyances filter Version 1.0.9.46. Updated 29 january 2017 at 17:02.
> Spanish/Portuguese filter Version 1.0.86.52. Updated 29 january 2017 at 13:01.
> Adblock Warning Removal List Version 1.0.73.77. Updated 29 january 2017 at 19:34.
> Anti-Adblock Killer | Reek Version 1.0.1.68. Updated 2 december 2016 at 14:09.

All the filters in "browsing security" are disabled.

**Comment by Alex-302** [comment]
@pedrogarcia 
try to add these rules
```
facebook.com#@#div[id^="hyperfeed_story_id"][-ext-has="a.uiStreamSponsoredLink"]
facebook.com#@#div[id^="substream_"] div[id^="hyperfeed_story_id_"][-ext-has=".userContentWrapper span>a._m8c"]
```

**Comment by pedrogarcia** [comment]
Adding that filter improves, but doesn't fix the issue.

**Comment by ameshkov** [comment]
@Alex-302 both rules are too slow.

You should narrow the selector results down with a parent selector. Something like:
```
div#somecontainer > div[id^="hyperfeed_story_id"][-ext-has="a.uiStreamSponsoredLink"]
```

**Comment by Alex-302** [comment]
what about this?
№2
```
facebook.com##div[id^="substream_"] > div:not([id]):not([class]) > div[id] div[id^="hyperfeed_story_id_"][-ext-has=".userContentWrapper span>a._m8c"]
```
An ad for first rule is not shown on my side.

**Comment by ameshkov** [comment]
@Alex-302 yeah, the second one is much better.

**Comment by zebrum** [comment]
there were at least 3 more complains including extension for ms edge
will check this rule

**Comment by ameshkov** [comment]
@Alex-302 ?

**Comment by Alex-302** [comment]
I will check it

**Comment by Alex-302** [comment]
Removed unnecessary rule:
```
facebook.com##div[id^="hyperfeed_story_id"][-ext-has="a.uiStreamSponsoredLink"]
```
