### ISSUE TITLE
Mail.Ru is broken

### ISSUE THREAD

**Issue by monolithed** [AdguardTeam/AdguardBrowserExtension#537]
e.mail.ru — project is broken after the last update

**Comment by ameshkov** [comment]
@Alex-302 check this please

**Comment by Alex-302** [comment]
@monolithed Whats wrong?

**Comment by monolithed** [comment]
There are many complaint from out users. Try youself

**Comment by ameshkov** [comment]
Парни, давайте на русский перейдем.

@monolithed на что юзеры жалуются?

**Comment by ameshkov** [comment]
@monolithed все браузеры или какие-то специфические?

**Comment by Alex-302** [comment]
У меня ящик работает, письма отправляюься
http://imagizer.imageshack.com/img922/7057/63OqMY.jpg

**Comment by ameshkov** [comment]
Ну ты не показатель, у @monolithed выборка то поболе будет:)

**Comment by monolithed** [comment]
@ameshkov проблема в хроме воспроизводится точно, по остальным браузерам выясняем. Страница грузится около минуты и каждое действие требует не меньше 3-х секунд, даже на ховер.

**Comment by monolithed** [comment]
Total Time 3.34 s
Function handleDomChange @ extended-css-1.0.6.js:3242 

Это на ховер.

**Comment by monolithed** [comment]
```
Mozilla/5.0 (Windows NT 6.1; rv:51.0) Gecko/20100101 Firefox/51.0

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.100 YaBrowser/16.11.1.673 Yowser/2.5 Safari/537.36

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 YaBrowser/17.1.0.2034 Yowser/2.5 Safari/537.36

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36 OPR/42.0.2393.517

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36 OPR/42.0.2393.517
```

Это по агентам

**Comment by ameshkov** [comment]
@Alex-302 90% времени в excss проводит, селектор слишком медленный, снеси его пока extcss не оптимизировали: https://github.com/AdguardTeam/ExtendedCss/issues/25

**Comment by ameshkov** [comment]
@monolithed спасибо за уточнения!

**Comment by Alex-302** [comment]
@ameshkov ок, закомментил пока
