### ISSUE TITLE
A phrase is clipped in Russian localization

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardBrowserExtension#538]
Screenshot:
https://files.slack.com/files-tmb/T0B41S97U-F3Y9W2MMK-8d41945298/edge-menu-ru_480.jpg

**Comment by ameshkov** [comment]
I guess we can simply make browser action window a bit wider.

**Comment by atropnikov** [comment]
Or remove `max-width` CSS property from `.os-popup-other-os-block` class.
