### ISSUE TITLE
Improve the way we send "Complaint" on the website

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#54]
##### Report should contain the following information:
- **Product name** (Adguard Browser Extension, Adguard for Windows, Adguard for Mac, Adguard for Android, Adguard for iOS, etc)
- **Product version**
- **List of enabled filters**
- **User Filter rules**
- **Stealth Mode settings** (for Windows version only)
- **Subject** (missed ads, incorrectly removed content, other)
- **User comment**

When user clicks on "Send Complaint" button we should open a page with all information pre-filled.
After this user should be able to attach any number of screenshots to the report and post it.

**Comment by bkrcrc** [comment]
Eagerly waiting for this :)

**Comment by ameshkov** [comment]
Duplicate, done in v2.9
