### ISSUE TITLE
Adguard Extension continues to filter sites which have been added to the HTTPS exclusions

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardBrowserExtension#542]
If you use the standalone app and the extension (integration mode), adding a site to regular exceptions via the Assistant creates the same exception in the extension's whitelist. Is it possible to do the same trick while adding a site to HTTPS exclusions? At the moment, Adguard filters excluded sites. Reproduced on Windows 10, Adguard 6.1.298.1564, Chrome 55.0.2883.87, Adguard extension 2.5.11

**Comment by vozersky** [comment]
This is an expected behaviour atm, details in this discussion: #717
