### ISSUE TITLE
Firefox

### ISSUE THREAD

**Issue by Pepperjet** [AdguardTeam/AdguardBrowserExtension#546]
Blank header at top of yahoo mail page will not close.  Closes ok on Chrome.  Thanks!

**Comment by vozersky** [comment]
What header? Also, what FF and extension versions do you use? 

Looks like this to me (both stable):

Without blocking:
![image](https://cloud.githubusercontent.com/assets/17472907/22657716/8181bb5a-eca8-11e6-8b04-0c13bcfaa59a.png)

Adguard extension on:
![image](https://cloud.githubusercontent.com/assets/17472907/22657800/d95b0840-eca8-11e6-819b-b0656382bb9a.png)

**Comment by vozersky** [comment]
If it's about Ad leftover, we have a more suitable repo: https://github.com/AdguardTeam/AdguardFilters

**Comment by Pepperjet** [comment]
The header, or space between the very top of yahoo mail and the bottom of the Firefox search bar.  There "was" a blank space about 3" or so thick running across the entire page.  It was an IRS ad or something yahoo put on.  Seems to have now gone away for the moment.  Also was happening on Chrome but went away a couple days ago.

I've been updating the filters every day for nearly a week, sometimes that would clear it up, and sometimes not.
Using FF 51.0.1 and AA 2.5.11 on an old 32bit Windows XP Pro desktop machine.  Yes, I know..., soon to upgrade.
Thanks for the quick reply.

**Comment by Pepperjet** [comment]
Yes, it may have been an ad leftover.
Thanks for the filter info link!
