### ISSUE TITLE
Refactor "selector" code and make it an independent module which we can use for both AG Assistant, browser extension and our mobile apps

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#55]
@Mizzick please first provide an interface of that new module and let's discuss it.

**Comment by Mizzick** [comment]
https://github.com/AdguardTeam/AdguardBrowserExtension/pull/139

**Comment by ameshkov** [comment]
Do not close it, let's finish with rules constructor in the same issue.
