### ISSUE TITLE
[Feature request] When opening filtering log, make the current browser tab active instead of the first one

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardBrowserExtension#553]
It really makes sense.

Screenshot:
![image](https://cloud.githubusercontent.com/assets/8577533/22780082/6dfb71d4-eece-11e6-942f-f4df7fc358af.png)

Original thread:
https://forum.adguard.com/index.php?threads/17064/page-3#post-125889

**Comment by atropnikov** [comment]
I'll check it, but It should be fixed in 2.6 release.
