### ISSUE TITLE
Error while parsing wide filtering rule

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#556]
Source:
https://github.com/AdguardTeam/AdguardForAndroid/issues/1009

Review:
adguard-java-code/review/AJC-CR-158

**Comment by atropnikov** [comment]
We still have a problem. @Mizzick Please, check the following rule `|$domain=test.com,script`

**Comment by ameshkov** [comment]
@Mizzick add a test case for it.

**Comment by Mizzick** [comment]
It's ok, isn't it?

**Comment by atropnikov** [comment]
Rule `|$domain=test.com,script` regexp isn't correct.

**Comment by atropnikov** [comment]
```
var rule = new adguard.rules.UrlFilterRule('||$domain=test.com,script');
assert.ok(rule.isFiltered("http://example.com", true, adguard.RequestTypes.SCRIPT));
```
This test should not fail, but it does.

**Comment by Mizzick** [comment]
Ok, check this pull request
