### ISSUE TITLE
English filter names on 2.5.15 Beta

### ISSUE THREAD

**Issue by skipik** [AdguardTeam/AdguardBrowserExtension#558]
I compiled this version from the source files and installed it on my Opera Developer 44.
This is what I see: http://jpegshare.net/9e/34/9e34b69e44a54f5006d723752e218401.png.html

**Comment by ameshkov** [comment]
Have you built it from the master branch or from 2.5.15 tag?

There is a huge difference between them

**Comment by skipik** [comment]
I built it from 2.5.15 tag.

**Comment by ameshkov** [comment]
@Mizzick will look into it, thank you!

It's worth noticing, that v2.5.15 is just a hotfix for FF, it won't go to the Chrome/Opera stores.

Meanwhile, if you want to try the latest version, you'd better try the master branch. This is a HUGE rework of Adguard's core code.
