### ISSUE TITLE
BrowsingSecurity doesnt work in 2.0.20 dev build

### ISSUE THREAD

**Issue by gshumihin** [AdguardTeam/AdguardBrowserExtension#56]
Doesn't work in GoogleChrome (chrome ver. 47.0.2526.49 beta (64-bit))
Error from chrome_background:
![](http://content.screencast.com/users/shumegor/folders/Jing/media/b385090c-ff64-4404-b875-1a1afc2c0358/00000666.png)

**Comment by Mizzick** [comment]
@gshumihin please provide more details, how can I check this?

**Comment by ameshkov** [comment]
Just try vv.cc

**Comment by Mizzick** [comment]
Fixed
