### ISSUE TITLE
YouTube search not working

### ISSUE THREAD

**Issue by MarDarkXT** [AdguardTeam/AdguardBrowserExtension#560]
Version: 2.5.14
Browser: Microsoft Edge

YouTube search (suggestions) not working when accessing YouTube. Only after clicking the site logo and the page reloads, search starts working again.

**Comment by Alex-302** [comment]
which filters are enabled? It is works without filters?

**Comment by MarDarkXT** [comment]
English filterVersion 1.1.9.93. Updated 21 februarie 2017 at 11:00.
Spyware filterVersion 1.0.10.74. Updated 21 februarie 2017 at 13:01.
ROListVersion 1.0.1.8. Updated 19 februarie 2017 at 19:32.

Adguard auto enables the English filter after I disable them and still doesn't work.
Only when Adguard is disabled for YouTube the search works.

**Comment by MarDarkXT** [comment]
![whenitdoesntworks](https://cloud.githubusercontent.com/assets/25929539/23168413/bdbcf2fc-f850-11e6-8ec6-ca2aa8612f8f.PNG)
This is what it blocks when it doesn't work.
![whenitworks](https://cloud.githubusercontent.com/assets/25929539/23168432/cdf46aba-f850-11e6-8b12-f10e4a6b354e.PNG)
This is what it blocks when it works.

**Comment by Alex-302** [comment]
Try without ROListVersion filter.

**Comment by MarDarkXT** [comment]
Still doesn't work.

**Comment by Alex-302** [comment]
Ok. Theck now only with English filter and separately with Spyware  filter.

**Comment by MarDarkXT** [comment]
1) Only English filter on. It doesn't work.
2) Only Spyware filter on. It works, but after that it auto enables the English filter and for the next visit it won't work again.

**Comment by Alex-302** [comment]
Ok, show me, please, blocked requests with English filter.
Or try to exclude 

![image](http://imagizer.imageshack.com/img924/5237/SWP72w.png)
```
@@||google.ro/pagead/
```

**Comment by MarDarkXT** [comment]
![whenitdoesntworks](https://cloud.githubusercontent.com/assets/25929539/23170294/4f32803e-f857-11e6-9fd7-c22ba91967e9.PNG)
This is all that it blocks when only English filter is on.
![images](https://cloud.githubusercontent.com/assets/25929539/23170320/6f08b1c6-f857-11e6-81de-d061684ec3fb.PNG)
Also the images do not load when this happens.

I am not sure how to use that exclusion.

**Comment by Alex-302** [comment]
We can't reproduce it. Could you provide me remote access?

**Comment by MarDarkXT** [comment]
That was my work computer so I can't give you access, but I'll check at home and reply as soon as possible.

**Comment by MarDarkXT** [comment]
I didn't get the chance to try it a home, but I believe I previously encountered this at home. I could give access but only after 7 PM Romania time.

**Comment by Alex-302** [comment]
Ok. Write me when you will be ready. My Skype: alxbrv

**Comment by ameshkov** [comment]
@Alex-302 please update the issue once you've sorted things out.

**Comment by Alex-302** [comment]
Ok.

@MarDarkXT is the issue still exists?

**Comment by vozersky** [comment]
I was able to reproduce it on VM.
Disabling **English filter** fixes this problem for me.

**Comment by Alex-302** [comment]
@vozersky give me please remote access to VM

**Comment by MarDarkXT** [comment]
Sorry I was out of town this weekend. We could try today. I check and it also happens on my personal computer at home.

**Comment by MarDarkXT** [comment]
@vozersky But disabling the English filter causes YouTube to show ads in videos.

**Comment by vozersky** [comment]
@MarDarkXT sure, disabling English filter is not a solution, I'm just telling @Alex-302 that some rule in English filter is the culprit

**Comment by MarDarkXT** [comment]
@vozersky Oh ok. And when this happens, if you click on the YouTube logo and the page reloads then everything works. This only happens when you directly access www.youtube.com

**Comment by vozersky** [comment]
@MarDarkXT could you please try adding this exception to your userfilter:

`@@||pubads.g.doubleclick.net/gampad/ads?*&gdfp_req=1$domain=youtube.com`

Should be fine with it, but I am afraid some ads can possibly go through.
We are going to look for a better solution. 

Could this be an Edge bug? 
Assist please, @atropnikov

**Comment by MarDarkXT** [comment]
@vozersky This seems to work. Watched 3 videos and didn't see any ads till now. Hope you find a permanent solution.

**Comment by ameshkov** [comment]
@Alex-302 it seems this rule might be necessary:
https://forum.adguard.com/index.php?threads/edge-extension-and-youtube-bug.19855/

**Comment by Alex-302** [comment]
@ameshkov The necessary exclusion was added a day ago.
[CODE]
@@||pubads.g.doubleclick.net/gampad/ads?ad_rule=0&d_imp=1&gdfp_req=1&iu=*mkt.ythome_1x1*&sz=1x1&correlator=$domain=youtube.com
[/CODE]
