### ISSUE TITLE
Ads are not blocked on bing.com web searches

### ISSUE THREAD

**Issue by pedrogarcia** [AdguardTeam/AdguardBrowserExtension#562]
Bing ads do not get blocked, even when creating a filter for them.

**Comment by ameshkov** [comment]
Again, I suppose this is due to the "settings" issue.

By default AG has "Allow search ads and self-promotion" option enabled, which is the culprit.

**Comment by pedrogarcia** [comment]
Nope, the ads persists even with that option disabled.
Ublock had a similar issue (here.)[https://github.com/nikrolls/uBlock-Edge/issues/30]

**Comment by ameshkov** [comment]
Let us re-test it then, thank you!

**Comment by vozersky** [comment]
Bing search ads are blocked with 2.6.0 Beta

**Comment by Mizzick** [comment]
So everything is ok?

**Comment by atropnikov** [comment]
@Alex-302 Please, recheck this issue again.

**Comment by Alex-302** [comment]
@atropnikov I don't ads even without Adguard

**Comment by Mizzick** [comment]
Tried on my side, the ads are blocked.
