### ISSUE TITLE
e.mail.ru - ad block detection with Opera extension

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#565]
It is not reproduced in Chrome.
Filters: Russian, English
How it looks in Opera:
<details>

![image](http://imagizer.imageshack.com/img924/5986/9cWAR1.png)
</details>
element names are randomized, when ad block detected. It checks visibility of elements.

**Comment by ameshkov** [comment]
@Alex-302 JS rules?

**Comment by Alex-302** [comment]
we have no JS rules for this site.
