### ISSUE TITLE
Add wildcard character support in domains lists

### ISSUE THREAD

**Issue by pedrogarcia** [AdguardTeam/AdguardBrowserExtension#571]
The following rule:
`
$xmlhttprequest,domain=btdb.in|epubr.*|lelivros.*|torrentz2.eu`

Does not block ajax requests for all TLDs which start with epubr.* and lelivros.* and etc.

**Comment by ameshkov** [comment]
Yeah, currently `domain` modifier accepts exact domain names, it just does not support a wildcard syntax.

Understanding it might be useful indeed.

**Comment by Alex-302** [comment]
Another type of rule
```
[dozens of Google domains],google.vu,google.ws##.pdp-psy.og-pdp ==> google.*##.pdp-psy.og-pdp
```

**Comment by ameshkov** [comment]
@Alex-302 sure, that's TLD approach will work for all kinds of domain restrictions.

**Comment by grenzor** [comment]
I'm curious, for examples of website elements with names such as:

`.random_NUi242j_block
.random_HUH82n_block
.random_xN29J0m_block`

Is it possible to block/hide these with something like `random_*_block`? Seems no blocker has the ability to use wildcards for elements in this way. I'm wondering whether it's just not been implemented or if it's actually not possible at all.

**Comment by ameshkov** [comment]
You can do it already:
```
div[class^="random_"][class$="_block"]
```

**Comment by grenzor** [comment]
Oh didn't realize it was possible. Does this mean wildcards can be used for all elements (or are there instances any where wildcards wouldn't work on them)?

**Comment by ameshkov** [comment]
> Oh didn't realize it was possible. Does this mean wildcards can be used for all elements (or are there instances any where wildcards wouldn't work on them)?

Yep:
https://www.w3schools.com/cssref/sel_attr_contain.asp
https://www.w3schools.com/cssref/sel_attr_begin.asp
https://www.w3schools.com/cssref/sel_attr_end.asp

**Comment by The-Commissioner** [comment]
> Seems no blocker has the ability to use wildcards for elements in this way.

Adblock Plus together with Element Hiding Helper had this ability for years.

**Comment by AndroidDeveloperLB** [comment]
> You can do it already:
> 
> ```
> div[class^="random_"][class$="_block"]
> ```

How would I use it to block URLs that end with the random string?
For example:

www.something.com###wm1ktoq36o8220085787

Also, can you please consider setting it easier? Meaning that we could mark which parts of the URL seem to be random?

**Comment by ameshkov** [comment]
If you need to block a URL, you need to use basic rules and not cosmetic: https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters

> Also, can you please consider setting it easier? Meaning that we could mark which parts of the URL seem to be random?

If you create a rule from AdGuard's filtering log, it offers something like this:
https://uploads.adguard.com/up04_ftp25_Filtering_log.png

**Comment by AndroidDeveloperLB** [comment]
@akmLaVx It doesn't offer to show where the wildcard will be, and it doesn't show items that I just blocked. Instead it shows items that can be blocked.
However, I got it this time to work as I wanted, somehow.
Please do consider choosing which part of the given URL will be a wild-card.
Also, please advice what to do on the case I wrote.
