### ISSUE TITLE
Не блокируется реклама в фоне(звук)

### ISSUE THREAD

**Issue by vitalek87** [AdguardTeam/AdguardBrowserExtension#573]
http://24tv.ua/nasirov_maye_shansi_viyti_pid_zastavu_cherez_yevropeysku_normu_poyasnennya_yurista_n790035
Opera beta 44.0.2510.401, Opera 43.0.2442.1144 
Не блокируются ссылки вида blob:http://24tv.ua/3f20f6dd-9009-441b-99d0-82a481c35d3f с которых грузится реклама

**Comment by vozersky** [comment]
Can't rep. Can anyone assist? 
@Alex-302 was able to reproduce it

**Comment by Alex-302** [comment]
Can we add support of `blob` modifier, which will redefine `Blob` function?
As I see, this script becomes popular
Another site with this script
http://gagadget.com/cellphones/5444-sdelka-mesyatsa-google-kupit-s-potrohami-kompaniyu-motorola-mobility/

**Comment by ameshkov** [comment]
@Alex-302 the issue has nothing to do with `Blob`, we need to find a way of blocking WebRTC connections in browser extensions.

**Comment by ameshkov** [comment]
Closed as dup:
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/588

**Comment by Alex-302** [comment]
Ok, but I don't see anything on `chrome://webrtc-internals/` page

**Comment by ameshkov** [comment]
These `blob` scripts cannot get from nowhere.

Three options:

1. Loaded with a regular script
2. Web socket
3. WebRTC

**Comment by ameshkov** [comment]
So, regular scripts then.

**Comment by ameshkov** [comment]
Again, my "scriptlets" suggestion solves this issue like completely, and it is one more example why we should do it.

**Comment by Alex-302** [comment]
But this method is not implemented yet.

I have deobfuscated script, but can't do anything with it
https://gist.githubusercontent.com/Alex-302/f32b9f79190eb3a5494bc7564772ab7a/raw/7e33d04544e893d540f74e4ff3aea5573697cf52/1.js

**Comment by ameshkov** [comment]
@seanl-adg does you deobfuscate app support this kind of obfuscation?

**Comment by seanl-adg** [comment]
@ameshkov Hi, it's of a form `var a = ["ABC", "DEF"...]`
