### ISSUE TITLE
Possible error with generichide implementation

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardBrowserExtension#574]
Example:

Search ads are not blocked in Yahoo.

1. Open https://search.yahoo.com
2. Type in a search request like "buy sneakers".

Result: Search ads at the right side of the page are not blocked.

**Comment by atropnikov** [comment]
English filter contains `@@||search.yahoo.com^$generichide` rule, that's why search ads at the right side are not blocked. @Alex-302 Please, check it.

**Comment by ameshkov** [comment]
I wonder why do the EasyList guys even need this rule?

```
search.yahoo.com##.searchRightMiddleAds
search.yahoo.com##.searchCenterTopAds
search.yahoo.com##.searchRightBottomAds
```

**Comment by Alex-302** [comment]
> search.yahoo.com##.searchRightMiddleAds
> search.yahoo.com##.searchCenterTopAds
> search.yahoo.com##.searchRightBottomAds

added
