### ISSUE TITLE
Console error after popup rule has been aplied 

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardBrowserExtension#579]
```
Unchecked runtime.lastError while running browserAction.setBadgeText: No tab with id: 403.
    at Object.onIconReady [as callback] (chrome-extension://bikgdlonheagbmdpkpdfbofacdcmageg/lib/api/background-page.js:295:39)
```

Can be reproduced at http://static.adguard.com/test_extension.html

**Comment by atropnikov** [comment]
We check `lastError` correctly, but because of async nature of the extension calls and because function `setBadgeText` doesn't have `callback` parameter, this error may appear sometimes.
Corresponding bug https://bugs.chromium.org/p/chromium/issues/detail?id=451320
