### ISSUE TITLE
[Safari] Tons of ads missed

### ISSUE THREAD

**Issue by gshumihin** [AdguardTeam/AdguardBrowserExtension#58]
Here's the short list:
- video ads on lenta.ru
- missed banner on rutracker
- missed ads onvk.com and facebook.com
- missed banner on youtube: http://screencast.com/t/HxHOXEUw4iF

**Comment by Mizzick** [comment]
Partially fixed in https://github.com/AdguardTeam/AdguardBrowserExtension/issues/63
And finally only content blocker branch will be supported in Safari 9+.
