### ISSUE TITLE
$popup rules do not work in Safari 

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardBrowserExtension#585]
1. Add ||static.adguard.com/popup.html$popup to User filter
2. Open http://static.adguard.com/test_extension.html and click on the link http://static.adguard.com/popup.html

**Comment by atropnikov** [comment]
Safari version doesn't support popup blocking. I'll check can it be implemented.

**Comment by atropnikov** [comment]
Safari content blocker API blocks popup windows that are opened via window.open. I will update the test case.
