### ISSUE TITLE
Possible websockets blocking issue

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardBrowserExtension#586]
[Test](https://adguardteam.github.io/TestCases/Filters/websockets/test-websockets.html) fails in Safari

**Comment by atropnikov** [comment]
@vozersky Which test did fail? I cannot reproduce it.

**Comment by vozersky** [comment]
@atropnikov the one I mentioned in the first post (2. Test blocking simple websocket connection)

**Comment by ameshkov** [comment]
What's exact Safari version?

It was fixed a long time ago:
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/299

**Comment by vozersky** [comment]
@ameshkov Version 10.1 (12603.1.30.0.34)

**Comment by ameshkov** [comment]
We might need to fix the test code. @atropnikov please assist.

**Comment by atropnikov** [comment]
@ameshkov What do you mean? Check the version of Safari in tests, or something else?

**Comment by ameshkov** [comment]
First of all we should figure out why test fails. Could it be that WebSocket does not throw error or something like that?

**Comment by atropnikov** [comment]
I found a reason of the problem. Test filter contains `||echo.websocket.org/?blocked` rule.
We replace `||` with `var URL_FILTER_REGEXP_START_URL = "^https?://([^/]*\\.)?";`
That's why WS connection isn't blocked.

**Comment by ameshkov** [comment]
@atropnikov we should've resolved it long ago, `||` should cover `WebSocket` as well. However, it'd be better to leave regexp pattern relatively simple.

**Comment by ameshkov** [comment]
I wonder, what will be the difference in performance?
`^(http|ws)s?`

**Comment by atropnikov** [comment]
Safari doesn't support `|`
