### ISSUE TITLE
Integration mode is inconsistent when HTTPS filtering is disabled in the desktop AG

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#587]
Full description:
https://github.com/AdguardTeam/AdguardForWindows/issues/1593

It seems, that you "save" integration mode flag in the tab and not update it when a user opts to go back.

**Comment by atropnikov** [comment]
Yes, I "save" integration mode flag for each tab, but it's updated each time when main frame is loading. This bug appears only in v2.5.19 after #561 fix.

**Comment by atropnikov** [comment]
So, this bug doesn't appear in 2.6.0 beta.
