### ISSUE TITLE
Ukrainian translation

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardBrowserExtension#589]
The Assistant uses English when the main app is set to use Ukrainian.

Reported here: 1035928

Adguard Assistant Beta Version: 3.0.116
AppVersion: 6.1.314.1628

**Comment by ameshkov** [comment]
We'll take this into account in the Assistant 4.0. @Alex-302, please keep an eye on it once @suhan3z upload it to oneskyapp.

**Comment by Alex-302** [comment]
Strange. All strings in oneskyapp are translated.
