### ISSUE TITLE
[Question]Disable Filter Auto-Update

### ISSUE THREAD

**Issue by The-Commissioner** [AdguardTeam/AdguardBrowserExtension#594]
Sometimes, I would like it to update upon request and not automatically.
Is there a hidden option or an about:config entry which can be tweaked so that auto check/auto update of filters can be stopped?
Both ABP and ublock have this option.

I am a firefox user :-)

**Comment by ameshkov** [comment]
Nope, no hidden option to prevent it.

Filed a feature request that should cover this:
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/596
