### ISSUE TITLE
$websocket modifier works incorrectly in Safari

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#597]
The rule `$websocket,domain=123movies.is` blocks too much.
How to reproduce:
- disable all filters and add `$websocket,domain=123movies.is`
- go to https://123movies.is/film/30-rock-season-3-16902/watching.html
- Player will be broken. Look at console for blocked requests

**Comment by Mizzick** [comment]
@Alex-302 any other example?
Can't open 123movies.is.
On yandex.ru it seems to be ok.

**Comment by Alex-302** [comment]
@Mizzick sure.
```
$websocket,domain=$websocket,domain=news.yandex.ru
```

<details>

![image](http://imagizer.imageshack.com/img923/948/A0eHMA.png)
</details>
Filters was disabled.

**Comment by Mizzick** [comment]
Well it blocks any "raw" resource-type now on Safari. We don't have any option to pick websocket requests.

**Comment by Alex-302** [comment]
Is not it better to ignore $websocket in Safari? Existing  break the sites.

**Comment by Alex-302** [comment]
The problem is not in unblocked websockets.

**Comment by ameshkov** [comment]
Guys, that's EASY.

We should convert $websocket rules to `|ws*://`

**Comment by ameshkov** [comment]
Being more precise:

1. If rule matches ANY URL
AND
2. If rule's content type EQUALS to websocket

THEN
`|ws*://*`

**Comment by Mizzick** [comment]
Ok, fixed
