### ISSUE TITLE
Outdated Yandex icon in the Adguard Extension section on the site

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardBrowserExtension#598]
https://adguard.com/en/adguard-adblock-browser-extension/overview.html

![image](https://cloud.githubusercontent.com/assets/15856304/24137974/e981ac0a-0e1e-11e7-9c7d-9eb8de749659.png)

Should be using this one: 
![image](https://cloud.githubusercontent.com/assets/15856304/24137981/fb1ad5f4-0e1e-11e7-80ff-eab1f4be925d.png)

**Comment by ameshkov** [comment]
It will be fixed after website redesign.
