### ISSUE TITLE
Let "integration mode" work for newer Edge versions 

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#601]
Request issues problem is fixed there.

**Comment by atropnikov** [comment]
Edge doesn't intercept requests from background page.
https://docs.microsoft.com/en-us/microsoft-edge/extensions/api-support/supported-apis#webrequest

**Comment by atropnikov** [comment]
So, we have to wait until this bug in Edge will be fixed.

**Comment by ameshkov** [comment]
Will be fixed once we start using WS API
