### ISSUE TITLE
@@*$genericblock do not work in safari

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardBrowserExtension#606]
Safari 9.1.3
$genericblock exceptions do not work in safari

1.Open lenta.ru
2.Block any image with generic basic rule.
3.Block any image with domain-specific basic rule. ($domain=lenta.ru)
4.Add @@||lenta.ru^$genericblock

domain-specific basic rule becomes unblock.

**Comment by ameshkov** [comment]
Yeah, $genericblock rules aren't supported in Safari, $generichide only:(
