### ISSUE TITLE
Integration mode is broken in Firefox

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardBrowserExtension#607]
firefox dev 54.0a2
adguard 1.4.1
extension 2.6.0

Steps
1. Enable protection in desktop version of Adguard.
2. Open few websites in browser.
3. Add some rules using "Block ads on this website" in extension.
3. Add filtering exception using browser extension.

Results:

Extension icon color is **green**.
Rules are **not** added to User filter of desktop version.
Exception rules are **not** added to User filter of desktop version.

**Comment by atropnikov** [comment]
FF WebExtension sends headers in lower case.
