### ISSUE TITLE
URL-less user filter rules handling

### ISSUE THREAD

**Issue by LaaUnique** [AdguardTeam/AdguardBrowserExtension#609]
I recently encountered issues when using rules such as just `###id` or `##.class` (without prepending URL) is the user filter, such rules don't seem to be applied.

(Chrome 56, macOS Sierra)

Using the extension about a year, this issue arose a month or 2 ago, then for some reason (extension / browser / OS update?) it disappeared, but now it appeared again.

Is it even legal to use such rules? Or do you have a roadmap on leaving/excluding them?
It would be really great if I could still use rules this way (e.g. to block all the useless stuff on all wiki-like sites). I understand it's rather dangerous because it handles all the URLs, but still it looks really useful.

Thank you.

**Comment by ameshkov** [comment]
Yeah, it's completely legal and it should work, not sure why it does not in your case, though.

Is it happening on all the websites or on some particular ones?
Which filters do you have enabled?

**Comment by LaaUnique** [comment]
Well, to keep it simple, I usually block all the "p-..." sections on wiki-like sites, so say `###p-interaction` doesn't work, while e.g. `en.wikipedia.org###p-interaction` does (it works without the "en" part as well).

![image](https://cloud.githubusercontent.com/assets/1406034/24297452/e562c068-10b3-11e7-8236-2c8dbe7c35dc.png)

**Comment by ameshkov** [comment]
In my case, it works okay. I suppose the issue might be caused by one of the filters you have enabled.

**Comment by LaaUnique** [comment]
Ehh okay, disabled all the filters, it worked, enabled the English one, it stopped working (enabling/disabling any other didn't affect the issue). I though filters are just sets of what should be filtered *out*, can they prevent something from being blocked as well?

**Comment by ameshkov** [comment]
> can they prevent something from being blocked as well?

Yeah, they can:
https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#elemhide-modifier
https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#generichide-modifier
https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#elemhide-exceptions

I still don't understand how the English filter alone could mess with wikipedia rules, it works as it should in my case.

**Comment by ameshkov** [comment]
What about other AG settings? What's different from the default?

**Comment by LaaUnique** [comment]
I'm sorry, not able to reproduce this once again :D: Pretty sure I did not change anything during last 2 days...
Well I guess this one should be closed as of now..

**Comment by ameshkov** [comment]
Heh:) No worries, thanks for checking it again:)
