### ISSUE TITLE
Add Adguard French filter

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#612]
https://github.com/AdguardTeam/AdguardFilters/issues/4588

**Comment by ameshkov** [comment]
Should be automatically added with the rebuild, right?

**Comment by atropnikov** [comment]
@Mizzick Is this issue resolved with 66cb8dab59d4c80d0c0d1742f52c81ed624455ff?

**Comment by Mizzick** [comment]
Yeap
