### ISSUE TITLE
Throttle setContentBlocker calls

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#62]
1. You should pass a callback to "setContentBlocker" to check when registration is finished
2. You should check registration result there (what if something gone wrong)
3. Throttle multiple "setContentBlocker" calls, delay until previous registration is finished.
```
    _setContentBlocker: function (json) {
        try {
            Log.info('Setting content blocker. Length=' + json.length);
            var result = safari.extension.setContentBlocker(json);
            Log.info('Content blocker has been set.');
        } catch (ex) {
            Log.error('Error while setting content blocker: ' + ex);
        }
    }
```

**Comment by Mizzick** [comment]
the result is undefined!

**Comment by Mizzick** [comment]
Fixed

**Comment by ameshkov** [comment]
That seems pretty bad to me.

If we can't use callback method, then simply delay "setContentBlocker" execution for 100-500ms and throttle multiple calls.

**Comment by Mizzick** [comment]
Fixed
