### ISSUE TITLE
*

### ISSUE THREAD

**Issue by The-Commissioner** [AdguardTeam/AdguardBrowserExtension#623]

**Comment by ameshkov** [comment]
Point 2 covers point 1 as you can move the tab in a new window.

What for "attaching to a page", AG already provides dev tools integration in Chrome. I suppose it's a good idea to improve that module and eventually replace current filtering log with it.

Dev tools is a great place for it as you can use existing "network" and "elements" tabs and integrate additional functionality inside of them.

**Comment by The-Commissioner** [comment]
w.r.t point 1 & 2
But if its provided as an option, I would like it to by default open in tab rather than in window and then moving it again and again.

**Comment by ameshkov** [comment]
> But if its provided as an option, I would like it to by default open in tab rather than in window and then moving it again and again.

Easy solution: bring back the toolbar in a newly opened filtering log window.
Hard solution: make a new "dock/undock" button somewhere inside of the filtering log window. Not sure about the second one, though. WebExtensions do not provide such a functionality, so we'll have to close window and then open a new tab with the same state.
