### ISSUE TITLE
Add $important modifier to the rule constructor

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#626]
... like in the app:
![image](http://imagizer.imageshack.com/img924/8350/0dyW8X.png)

**Comment by XX-J** [comment]
Почему не срабатывает следующее правило блокировки:
`cdn.mozilla.net/*/jsi18n.js$important`   ?
Ведь оно должно превалировать перед исключающем правилом из "Английского фильтра":
`@@||cdn.mozilla.net$document`

После отключения "Английского фильтра" моё правило начинает работать.
___________________________________________________
Pale Moon v26.5 (WinXP) - Adguard legacy v2.6.7
Английский фильтр | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и системы аналитики

**Comment by ameshkov** [comment]
Не, только не с `$document`. Другое дело, что это правило (сдн.мозилла) вообще не очень нужно.

@Alex-302 может удалим его?

**Comment by XX-J** [comment]
> Не, только не с `$document`.

Оказывается Ваш `$important` Не настолько и Important... Почему??

> может удалим его?

Я - за. По моему - это лишнее предостережение.

**Comment by ameshkov** [comment]
Тут скорее вопрос другой - почему `$document` применяется к запросам с типом, отличным от `DOCUMENT`, это не его задача

**Comment by Alex-302** [comment]
@ameshkov ок, удаляю. Правило очень староею

**Comment by XX-J** [comment]
> `DOCUMENT` - это не его задача

Согласно Справке [`document`](https://kb.adguard.com/ru/general/how-to-create-your-own-ad-filters#document) включает в себя [`jsinject`](https://kb.adguard.com/ru/general/how-to-create-your-own-ad-filters#jsinject), а уж тот, в свою очередь, блокирует *.js . Поэтому, можно сказать, что - Его.

**Comment by ameshkov** [comment]
`jsinject` - отключает JS-правила на странице. Так что цель все же именно страница.

**Comment by XX-J** [comment]
`jsinject` - Запрещает добавление javascript-кода на страницу.
Я так понял что из Всех мест, и со страницы, и с внешних файлов.
Но если задумка была ТОЛЬКО со страницы, то на лицо явно не правильная работа.

**Comment by Alex-302** [comment]
> Я так понял что из Всех мест, и со страницы, и с внешних файлов.

не `из Всех мест`. При добавлении правила с этим модификатором Адгард не встраивает свой JS код в страницы. Чужой JS(в коде страницы и прочие скрипты) не затрагивается.

**Comment by ameshkov** [comment]
Вот эти правила отключает:
https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#javascript-rules

**Comment by XX-J** [comment]
Ааа, я понял - попутал свой-чужой js.

Прикинул что похоже на `urlblock`. Проверил - и вправду Он. Загадка с `document` - решена.
