### ISSUE TITLE
Error on start/adding/removing filter subscription

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardBrowserExtension#627]
Edge browser
Insider Preview build 15063.11

![pasted image at 2017_04_03 18_10](https://cloud.githubusercontent.com/assets/17472907/24616595/461503ba-189a-11e7-8142-f55501ce09c1.png)

![pasted image at 2017_04_03 18_11](https://cloud.githubusercontent.com/assets/17472907/24616604/4b12d5d6-189a-11e7-821a-fbfa09e35f2a.png)

**Comment by atropnikov** [comment]
4c8ea49c5511bbee83df667489b54ba4c4250e97
