### ISSUE TITLE
"Show information on Adguard full version" is disabled by default

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardBrowserExtension#633]
"Show information on Adguard full version" is disabled when you open Adguard settings for the first time 
Should be enabled.

<details>

![image](https://cloud.githubusercontent.com/assets/17472907/24665386/ec60cea4-1965-11e7-8b4f-5b0026e84ec6.png)

</details>

**Comment by ameshkov** [comment]
This is okay, we shouldn't show it unless integration mode works
