### ISSUE TITLE
Huge user filter slows down the "options" page loading

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#641]
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/523#issuecomment-292925945

**Comment by BooBerry** [comment]
Groovy, anyone have a test Firefox build handy so I can retest this and verify?

**Comment by atropnikov** [comment]
@BooBerry  [firefox-amo-beta-2.6.0.xpi.zip](https://github.com/AdguardTeam/AdguardBrowserExtension/files/913319/firefox-amo-beta-2.6.0.xpi.zip)

**Comment by BooBerry** [comment]
Thank you very much! Confirmed, fixed!
