### ISSUE TITLE
$elemhide exceptions also affect basic rules

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardBrowserExtension#642]
Safari Version 10.1 (12603.1.30.0.34)

STR:
1. Add some 1 cosmetic and 1 basic rule (in our example - blocking image by url) for a page (i.e. lenta.ru)

```
lenta.ru###root > section.b-header.b-header-main.js-header:nth-child(4) > div.g-layout > div.row

https://icdn.lenta.ru/images/2017/04/10/16/20170410160659586/top7_f07b6db166774abba29e0de2e335f50a.jpg
```

Now add elemhide exception:

```
@||lenta.ru^$elemhide
```

Expected result: elemhide rules disabled, image remains blocked, 
Actual result: elemhide rules disabled, image also becomes unblocked

**Comment by Mizzick** [comment]
Will need to update converter in other projects.
