### ISSUE TITLE
Prepare AG sync sign up page layout

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#644]
Mockup:
![online mockup wireframe ui prototyping tool moqups 2017-04-10 17-23-34](https://cloud.githubusercontent.com/assets/5947035/24866363/8a39988a-1e12-11e7-908f-f3e213bccfa7.png)

In the rectangle let's use the signup dialog content:
![report 2017-04-10 17-24-36](https://cloud.githubusercontent.com/assets/5947035/24866400/aa6d90a2-1e12-11e7-8330-49ea14518aec.png)

Page layout should be as simple as possible. I'd prefer if there were no external resources at all, every image should be embedded (`data:`).

**Comment by ameshkov** [comment]
@sc0rp10

**Comment by ameshkov** [comment]
@sc0rp10 ping

**Comment by sc0rp10** [comment]
https://gist.github.com/IldarKamalov/85b33fb3846351513856d6c648c8c39e

**Comment by sc0rp10** [comment]
@IldarKamalov
