### ISSUE TITLE
tvguide.com - can't block ad manually with extension

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardBrowserExtension#647]
http://www.tvguide.com/ 
no window with preview\block buttons appears after selecting elements you want to block

also Adguard Assistant disappears when you click on it

* **Current behaviour**: 
<details>

![screenshot 2017-04-11 19 16 04](https://cloud.githubusercontent.com/assets/23637588/24952564/898519d6-1f80-11e7-83ed-304eb65e225a.png)

</details>

* **Expected behaviour**: 

<details>

![screenshot 2017-04-12 13 09 49](https://cloud.githubusercontent.com/assets/23637588/24952740/531f8326-1f81-11e7-802a-d96ebef1b702.png)

</details>

**Comment by atropnikov** [comment]
Site's CSS overrides assistant style. We should add the `!important` option.
