### ISSUE TITLE
Disappearance of the main section in "convert-video-online.com" when adblocker is on

### ISSUE THREAD

**Issue by jhnsmith08** [AdguardTeam/AdguardBrowserExtension#649]
It starts to happen after one or two days after installing adguard extension(not immediately after installing). The main section of "convert-video-online.com" disappears when adguard adblocker is on. I have tried other major adblocker and only adguard produces this issue.

Actually the problem is very weird! I reported this issue in the chrome extension page's review section a while back, but no response or fix yet! Thats why I'm reporting here!

**Comment by vozersky** [comment]
@jhnsmith08  hi! this is more like a filtering rules issue, so i will go ahead and move it: 

https://github.com/AdguardTeam/AdguardFilters/issues/4806

Could you please let us know what filters do you use in Adguard (you can see it in settings) and make screenshot of this issue, if possible.
