### ISSUE TITLE
$third-party works incorrectly in Safari browser

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardBrowserExtension#651]
STR:

1. Turn all filters in browser extension off.
2. Open www.trafmag.com
3. Add `||trafmag.com^$third-party` to User filter.
4. Refresh the page

Result: 

![pasted_image_at_2017_04_19_18_02_720](https://cloud.githubusercontent.com/assets/17472907/25188097/92a66ce2-252d-11e7-8f7b-8ef4b86d42ca.png)

**Comment by Mizzick** [comment]
Isn't it supposed to be `||www.trafmag.com^$third-party`?

**Comment by atropnikov** [comment]
No, `||` includes `www.`

**Comment by Mizzick** [comment]
Well, it looks like Safari cannot recognise first-party requests properly.

If I add `*$third-party` which blocks all third-party requests, I will see the all the requests blocked even to trafmag.com and all urls with it's subdomains. 

An other example: 
- add `||*$third-party`
- open https://adguard.com/en/welcome.html

result:

> [Info] Content blocker prevented frame displaying https://adguard.com/en/welcome.html from loading a resource from https://counter.adguard.com/counter?event=visit&aid=18672&promoid=1&ref=&rand=0.3894290477643466

From Safari docs:
> third-party
The rule is triggered if the resource is not from the same domain as the main page resource.

https://developer.apple.com/library/content/documentation/Extensions/Conceptual/ContentBlockingRules/CreatingRules/CreatingRules.html#//apple_ref/doc/uid/TP40016265-CH2-SW5

**Comment by ameshkov** [comment]
Yeah, seems so. We'd better file a bug report to them

**Comment by ameshkov** [comment]
https://bugs.webkit.org/show_bug.cgi?id=171202

**Comment by Alex-302** [comment]
:(
