### ISSUE TITLE
Change the name back to Adguard instead of Adguard AdBlocker

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardBrowserExtension#654]
We've got a request about the inconvenience and imperfect rendering of 2.6.1 version.

Screenshot:

<details>

![image](https://cloud.githubusercontent.com/assets/17320558/25300798/6323cf1a-2720-11e7-8d5e-12bd6bc03ef4.png)

</details>

Ticket ID: 1493043

**Comment by ameshkov** [comment]
Huh, what exact browser version is it?

**Comment by pro100Hub** [comment]
> Huh, what exact browser version is it?

FF 53.0 (32 bit)

**Comment by Mizzick** [comment]
Possibly depends on os, all fine for me on FF DevEdition 53.0

**Comment by pro100Hub** [comment]
This problem occurred when upgrading from the version of Adguard 2.5.19 to 2.6.1 Beta.
Please note the screenshot shows the "Settings Menu". The "Adguard" icon is moved there.

**Comment by ameshkov** [comment]
@pro100Hub I wonder why did the icon move, didn't happen in my case.

@Mizzick try moving it there manually, should be easy to reproduce.

**Comment by pro100Hub** [comment]
@ameshkov The transfer of the icon in the "settings menu" was done manually.
I made live screenshot: [http://s6.postimg.org/ktetwf25t/2017_04_24_13_25_18.gif](url)

**Comment by Mizzick** [comment]
hmm ok, got it

**Comment by ameshkov** [comment]
Can't be fixed in WebExtensions
