### ISSUE TITLE
Filtering log is cleaned while page is loading

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#655]
Browser: Chrome

Steps to reproduce:
1. Go to slickdeals.net
2. Open filtering log and clear it right away
3. Refresh the page and keep an eye on the filtering log.

You'll see that it is cleared one more time in the middle of page loading.

**Comment by Mizzick** [comment]
This is not the middle of pageloading, the page loads two times, and this is done by design at this site.
