### ISSUE TITLE
Cleaning Chrome cache with PCSuite 9 breaks Adguard Extension settings 

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardBrowserExtension#657]
After cleaning the computer with PCSuite 9, that clears the cache as well, our customer gets the message mentioned below, every time after the cleaning extension is installed once more. 

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/17320558/25385911/2b8d0fac-29ce-11e7-8364-31a1917f5e7c.png)

</details>

Ticket ID: 1536871

**Comment by ameshkov** [comment]
@atropnikov do we store this kind of settings in the local storage?

**Comment by atropnikov** [comment]
Yes, we do. `version` (and other settings) is stored in the local storage.

**Comment by atropnikov** [comment]
I wonder, does that cleaning tool affect `browser.storage` too?

**Comment by Anoop2609** [comment]
Not in just chrome, In Firefox 53 (64bit) also same thing happening but i am using Auslogics BoostSpeed 9.

**Comment by atropnikov** [comment]
@Anoop2609 what version of extension do you use?

**Comment by Anoop2609** [comment]
Adguard AdBlocker (beta) 2.6.1

**Comment by Anoop2609** [comment]
i don't think cleaning affect adguard because i just full clean my system with BoostSpeed 9 twice
and adguard is "OK" without any problem there is something else

**Comment by Anoop2609** [comment]
Cleaning the complete browsing data break adguard. 
![screenshot 10](https://cloud.githubusercontent.com/assets/23557479/25560634/2cc7e9ee-2d77-11e7-8217-21636bd6f4c4.png)

Please fix this ASAP

**Comment by ameshkov** [comment]
@Anoop2609 are you on Adguard 2.6?

**Comment by Anoop2609** [comment]
I am using  Adguard 2.6 beta WebExtensions and installed from official firefox addon site from Development Channel and also using firefox 53.0.2

**Comment by ameshkov** [comment]
@Anoop2609 filed a new issue about it:
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/681
