### ISSUE TITLE
Adguard settings window is not shown in private mode

### ISSUE THREAD

**Issue by Anoop2609** [AdguardTeam/AdguardBrowserExtension#658]
Firstly it happen i think it just a malfunction but now it is happening like "n" number of time, just look at the image . I am using Firefox 53.0(64 bit) and adguard 2.6.1 beta. New firefox extension is little slow also, size of the extension is 3.78MB it is too much because the your competitor ublock origin size is just 1.67MB and it also work very smooth but i love adguard so i just want to make it best adblocker
![screenshot 1](https://cloud.githubusercontent.com/assets/23557479/25441158/0eae697a-2abf-11e7-8234-e145df6df526.png)

**Comment by vozersky** [comment]
Reproduced.
@Anoop2609 thanks a lot for reporting it!

**Comment by vozersky** [comment]
@Anoop2609 about the extension size: we do actually include English filter in extension file itself (And it's about 2mb). I don't see a problem here though.
