### ISSUE TITLE
Anti Ad blocker

### ISSUE THREAD

**Issue by Anoop2609** [AdguardTeam/AdguardBrowserExtension#662]
Can you guys develop Anti Adblocker like your English Filter and Simplified domain names filter because adding all available anti adblocker increase the rule numbers even after using all these rules website detects adblocker.
 there is a site temp mail who detect adblocker over all the anti adblocker
https://temp-mail.org/en/view/5d5b2b42be3212df87e9347da0255c10/
![screenshot 11](https://cloud.githubusercontent.com/assets/23557479/25564354/554677f2-2dcf-11e7-8cf0-4c4065396982.png)
![screenshot 12](https://cloud.githubusercontent.com/assets/23557479/25564355/559b083a-2dcf-11e7-8f1e-9ab0b45a51e2.png)

**Comment by seanl-adg** [comment]
>Can you guys develop Anti Adblocker like your English Filter 

We are already doing it. It is English filter.
Our anti-adblock rules are already in English filter and Annoyance filter, depending on how much it affects the websites' main functionality.

So if you find a website that disables the site functionality when adblock is detected, report it to https://github.com/AdguardTeam/AdguardFilters/issues or report it by sending a feedback right from the extension.

**Comment by BooBerry** [comment]
IMO, you don't need to run the **Anti-Adblock Killer | Reek** and the **Adblock Protector** filter lists at the same time. The latter is a fork of the former, so all you're adding is a bunch of duplicated filter rules by having both.

Also, this is being discussed in https://github.com/AdguardTeam/AdguardForWindows/issues/1609 which would apply to everything (I guess it would of made more sense posting to AdguardFilters and not AdguardForWindows).
