### ISSUE TITLE
A bug with element hiding rule with domains containing `www`

### ISSUE THREAD

**Issue by seanl-adg** [AdguardTeam/AdguardBrowserExtension#665]
STR:
 1. Add a rule`~www.google.com,google.com##body > div:nth-of-type(1)`
 2. Go to https://www.google.com

Expected result: the rule is not injected, and the page is displayed as normal.
Actual result: the page is blank.
This broke a website in https://forum.adguard.com/index.php?threads/cba-pl.21252/

**Comment by ameshkov** [comment]
I wonder, do we have the same issue in Windows version?

**Comment by seanl-adg** [comment]
Not on my end.

**Comment by Alex-302** [comment]
The bug is still exists.
For example:
`www.i.ua##body`
this rule is applied to i.ua and to `some` sub-domains:
http://shop.i.ua http://mbox2.i.ua/ - applied
http://perevod.i.ua http://weather.i.ua - not applied

**Comment by atropnikov** [comment]
The problem isn't in domains or subdomains. Seems some script on the website, that somehow disables rules in the shadow DOM. I could not find how do they do it. I tried to apply CSS rules with some delay, and everything is OK in this case.

**Comment by Alex-302** [comment]
@ameshkov strange, but the rule is applied now to that domains. But my question is about domain with `www`. `www.i.ua##body` must be applied to `www.i.ua` only.

**Comment by Alex-302** [comment]
@atropnikov  strange, but the rule is applied now to that domains. But my question is about domain with `www`. `www.i.ua##body` must be applied to `www.i.ua` only.

**Comment by atropnikov** [comment]
Fixed 3da5a9bfbea0776bea6842b487428fa80e7e74b1
