### ISSUE TITLE
$webrtc does not work on rapidvideo.com

### ISSUE THREAD

**Issue by seanl-adg** [AdguardTeam/AdguardBrowserExtension#669]
I was using chrome browser extension 2.6.3 version.
STR:
 1. Open the filtering log.
 1. Go to `https://www.rapidvideo.com/embed/FEXYFN0CJO`

Expected result: WebRTC connection is established, so it is shown in the filtering log.
Actual result: no `stun:` urls appear in the filtering log.

Also, `$webrtc,domain=rapidvideo.com` does not block it, and when you click somewhere in the page, a popup window to `http://104.198.....` will open.

**Comment by Alex-302** [comment]
@atropnikov it does not block WebRTC in my Chrome 58
