### ISSUE TITLE
"Block ads on this website" tool is misbehaving in Firefox

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardBrowserExtension#671]
2.6.3 Beta
FF 54.0a2 (2017-04-18) (64-bit)

STR:
1. Choose "Block ads on this website"
2. Select an element.
3. Try to move the min\max slider few times.

![image](https://cloud.githubusercontent.com/assets/17472907/25715454/2ce022d0-3104-11e7-8804-62f5c3e552ac.png)

**Comment by Mizzick** [comment]
https://www.dropbox.com/s/32b3z1nydmwe0nh/Screenshot%202017-05-07%2021.48.53.png?dl=0

Somehow the frame source is changed.

**Comment by ameshkov** [comment]
That's page own scripts messing with it. Can we somehow protect our frames from this kind of changes?

**Comment by Mizzick** [comment]
I still can find how it messed up, and why it's only in Firefox. Actually, I don't think it has been done intended.

**Comment by atropnikov** [comment]
Although this bug is weird we have to fix it, it still appears not only on the `lenta.ru` website. @Mizzick Please get in touch with @zebrum for more details.

**Comment by seba2282** [comment]
About Firefox... I have a question about Firefox Android. Why Adguard, Ublock Origin or etc not block blocking video ads by redcdn.pl domain on example miniminiplus.pl ? I see all time big popup with this video ads. Is it bug in Firefox or in blockers ? Sorry my question.

**Comment by vozersky** [comment]
@altokarev

**Comment by altokarev** [comment]
Hi, it's a filtering problem, let's stick to your original issue AdguardTeam/AdguardForAndroid/issues/1199. This repo is for Adguard Browser Extension. Thanks!

**Comment by Mizzick** [comment]
Seems to be a browser bug or smth..
But is still reproducable with the newest FF
