### ISSUE TITLE
Adguard dropdown menu glitch - Edge browser

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardBrowserExtension#675]
1. Open Adguard settings.
2. Separate the settings tab from the browser window (make it a new window itself)
3. Close it.
4. Try to open Adguard dropdown menu in the first window again.
Result: It doesn't open until you restart the browser
Video: https://www.screencast.com/t/DdsyJnlr

**Comment by vozersky** [comment]
also, if the Adguard Settings tab has been already opened and you select Settings in dropdown menu again, there is an error in console:

![image](https://cloud.githubusercontent.com/assets/17472907/25755706/b493dcb2-31cc-11e7-8bd0-a2ee6d4180a4.png)

**Comment by Mizzick** [comment]
ok, it seems to be a messaging problem.
