### ISSUE TITLE
Incorrect behaviour of extension in the newest Firefox version.

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardBrowserExtension#677]
Adguard options can't be shown in the newest version of Firefox and no icon in the menu bar as well. All other extensions are disabled and still nothing. Check details below:

<details>

![image](https://cloud.githubusercontent.com/assets/17320558/25791588/2514f35a-33ca-11e7-9b6d-93142a33370f.png)

![image](https://cloud.githubusercontent.com/assets/17320558/25791597/342c2994-33ca-11e7-943a-6a435557b2d3.png)

</details>

Ticket ID: 1554404

**Comment by ameshkov** [comment]
FF Nightly?

**Comment by ameshkov** [comment]
Have you asked user to try v2.6 beta?

**Comment by vozersky** [comment]
obsolete
