### ISSUE TITLE
Enabling "Fanboy's annoyances" breaks "All filters" dialog

### ISSUE THREAD

**Issue by jlandersen** [AdguardTeam/AdguardBrowserExtension#678]
Hi 

I have a recurring issue, which is now consistent on my three different Macs (all running latest macOS Sierra with Safari 10.1, but the problem was there with previous versions as well).

When I install Adguard in Safari I can correctly go to settings, click "All filters" and toggle new ones to add. After having run with my newly added filters, I now only get a gray overload when choosing All filters:
 
![screen shot 2017-05-08 at 08 42 06](https://cloud.githubusercontent.com/assets/2197398/25793077/aebb031a-33ca-11e7-848f-1a3b70144e2f.png)
 
Let me know if I can provide any additional details.

**Comment by ameshkov** [comment]
@jlandersen hi! could you please try installing the latest beta version and see if the issue is gone there?

https://github.com/AdguardTeam/AdguardBrowserExtension/releases/download/v2.6.1-beta/safari-beta-2.6.1.safariextz

**Comment by jlandersen** [comment]
@ameshkov 

Hi, I tried the beta and the result was the same. It works initially but the next time I open Safari it doesen't work. 

It made me wonder whether the reason was one of the filters I usually enable, so I tried to enable them one by one. In between each, I quit Safari completely and loaded it again. Sure enough, the filter "Fanboy's Annoyances" seem to be the problem here.

If I enable "Fanboy's Annoyances", quit Safari, and reopen it, only the gray overlay shows. Disabling the filter again, and restarting Safari makes the "all filters" window show correctly again.

**Comment by ameshkov** [comment]
Ah! I got it!

**Comment by Mizzick** [comment]
This is not true about the quote char, it's only about enabled Fanboy's Annoyances filter.

**Comment by ameshkov** [comment]
I wonder why:)

**Comment by Mizzick** [comment]
Suddenly it is blocked by rule in this filter:
**###subscriptionModal**
https://easylist.to/easylist/fanboy-annoyance.txt

**Comment by Mizzick** [comment]
Ok, it seems like there is no way to an exclusion for content-blocker itself, so we should add som exclusions in Safari Filter.

**Comment by ameshkov** [comment]
@Mizzick any idea what domain is it?

**Comment by Mizzick** [comment]
href: `safari-extension://com.adguard.safaridev-N33TQXN8C7/4ddf3c72/pages/options.html"`
hostname: `com.adguard.safaridev-N33TQXN8C7`

If I add `com.adguard.safaridev-N33TQXN8C7` to whitelist - it works well.

**Comment by Mizzick** [comment]
@Alex-302 pls have a look.

**Comment by Alex-302** [comment]
@Mizzick is `com.adguard.safaridev-N33TQXN8C7` a constant in every browser?

**Comment by Mizzick** [comment]
we need this for Safari only. But I think it would be better to make it like `com.adguard.safaridev-*` or whitelist it by `safari-extension://` protocol if it's possible.

**Comment by Alex-302** [comment]
tried
```
@@safari-extension://com.adguard.safaridev-$document
```
and 
```
@@com.adguard.safaridev-$document
```
but they are not working in user filter

**Comment by Alex-302** [comment]
my mistake, it works. com.adguard.safari- in my case

**Comment by Alex-302** [comment]
Added to Safari filter
```
@@safari-extension://com.adguard.safari-$document
@@safari-extension://com.adguard.safaridev-$document
```

**Comment by Mizzick** [comment]
thanks!
