### ISSUE TITLE
The new Assistant settings window is located quite away from the icon

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardBrowserExtension#679]
![image](https://cloud.githubusercontent.com/assets/15856304/25843099/e66cfacc-34ae-11e7-80fb-4f858196e7f2.png)
![image](https://cloud.githubusercontent.com/assets/15856304/25843108/ed896200-34ae-11e7-9310-9b71c272d8eb.png)

The settings popover is too large

Reported here: 1479416

**Comment by ameshkov** [comment]
@evgeniy-ADG wrong repo

https://github.com/AdguardTeam/AdguardAssistant
