### ISSUE TITLE
German translation not updated in latest beta 2.6.1

### ISSUE THREAD

**Issue by sergerosenthaler** [AdguardTeam/AdguardBrowserExtension#680]
Hello,

https://adguard.oneskyapp.com/ has been updated with a lot of German translation improvements, if possible check them on OneSky and implement them into the beta.

**Comment by ameshkov** [comment]
@sergerosenthaler are the new strings approved in oneskyapp or should we review & approve them?

**Comment by sergerosenthaler** [comment]
@ameshkov as I don't have the reviewer role, I'm unable to change or approve any translations. In this case you have to go trough the translations and approve them.

**Comment by ameshkov** [comment]
@sergerosenthaler got it! @vbagirov please assist

**Comment by vbagirov** [comment]
I've updated the German translations.

**Comment by sergerosenthaler** [comment]
@vbagirov found a litte mistranslation, sorry for that.  #2378062 "Participate in&nbsp;the development of&nbsp;Adguard filters". Correct translation is "Beteiligen Sie sich&nbsp;an der Entwicklung von&nbsp;Adguard Filtern". Please update this on OneSky.

**Comment by sergerosenthaler** [comment]
@vbagirov and #2378006 "Check for filter updates". Correct German translation is "Auf Filter-Updates prüfen". Thank you.
