### ISSUE TITLE
Cleaning Firefox data breaks Adguard extension

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#681]
Source:
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/657#issuecomment-298206040

**Comment by ameshkov** [comment]
@Anoop2609
Could you please be more specific about what actually is broken by clearing the browser cache & data?

**Comment by ameshkov** [comment]
I've just tried reproducing it FF 53, but everything seems to be okay.

**Comment by Anoop2609** [comment]
Not okay in my pc, i simply clean cache of my firefox nothing else.
![screenshot 14](https://cloud.githubusercontent.com/assets/23557479/25885956/f4f6e1d2-3578-11e7-83ff-6e083831ec48.png)
![screenshot 15](https://cloud.githubusercontent.com/assets/23557479/25885959/f5e3733a-3578-11e7-94cf-4ebe50a913dc.png)
![screenshot 16](https://cloud.githubusercontent.com/assets/23557479/25885958/f5e2fca2-3578-11e7-8827-d18af4138080.png)

**Comment by Anoop2609** [comment]
I am sorry, i did not mentions that you have to select everything while clearing cache, if you select any other option then adgurad works totally fine
![screenshot 17](https://cloud.githubusercontent.com/assets/23557479/25886552/b767f2a4-357b-11e7-9ec2-91bd51b2c9d5.png)

**Comment by ameshkov** [comment]
FF 52?

**Comment by ameshkov** [comment]
It looks like a FF bug, which I cannot reproduce in FF 53, so I guess it might've been fixed in FF 53 already.

**Comment by Anoop2609** [comment]
No, i am using latest FF 53.0.2(64 bit) and it is only happening with adguard. i have also tons of other extension only adgurad gets affected.

**Comment by The-Commissioner** [comment]
@Anoop2609 it's not the cache that's the culprit, it's the cookies. If you clean cookies Adguard settings reset, if you don't clean them(cookies), Adguard retains it's settings. Try solving things on your own here. ;-)

**Comment by ameshkov** [comment]
Actually AG uses extensions `localStorage`, which is also cleared when you choose to clear cookies.

Anyways, switching to another storage type should solve the issue:
https://github.com/AdguardTeam/AdguardBrowserExtension/pull/684/files
