### ISSUE TITLE
SVG chart is broken by element hiding rules [Edge]

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#683]
http://quotes.wsj.com/MSFT
![unnamed 2](https://cloud.githubusercontent.com/assets/5947035/25782328/53d85156-3351-11e7-99f1-c47df3ee7b3f.jpg)
Strange, but when I change and revert some attribute of `.highcharts-series`, the chart becomes visible
Video:
https://mega.nz/#!YNth3SQa!PNFug22BB2dGW_rfXToISE0QVj6iewc7-uAN5ppszIE

**Comment by ameshkov** [comment]
`SCRIPT438: Object doesn't support property or method 'escape'`

**Comment by ameshkov** [comment]
It seems that `CSS` object is not defined in some cases

**Comment by atropnikov** [comment]
@ameshkov I don't see the error above in the browser console.
The problem appears only with some generic cosmetic rule in English filter. If I add `generichide` exception or enable another filter (with disabled English filter), everything is ok with the chart.

**Comment by Alex-302** [comment]
@atropnikov I can reproruce it with Spyware filter only.
Did you watch the video?

**Comment by atropnikov** [comment]
I don't know how, but a rule like `img[width="88"][height="31"]` breaks SVG rendering.

**Comment by seanl-adg** [comment]
`wsj.com##img[width="1"][height="2"]` breaks SVG, 
`wsj.com##img[WIDTH="1"][HEIGHT="2"]` does not break SVG.

**Comment by vozersky** [comment]
looks like `##img[Width=“1”][Height=“2"]` doesn't break svg as well

**Comment by ameshkov** [comment]
@atropnikov @Mizzick I suggest transforming Edge filters and replacing all the `[width]` and `[height]` selectors.
