### ISSUE TITLE
custom filters not saved 

### ISSUE THREAD

**Issue by ghajini** [AdguardTeam/AdguardBrowserExtension#686]
Custom filters not saved in adguard in Firefox for android.....
Iam adding 3 to 4 custom filters one by one.....after browser restart custom filters are empty

**Comment by vozersky** [comment]
@ghajini which filters are you trying to add?

**Comment by ghajini** [comment]
zap.in#$##verifyAd { height: 51px!important; }
zap.in#$##flexContentAdFrame { height: 51px!important; }
@@||zap.in^$content
zap.in#@##verifyAd
zap.in#@##flexContentAdFrame

These one ....one by one

**Comment by ghajini** [comment]
zap.in#$##verifyAd { height: 51px!important; }
zap.in#$##flexContentAdFrame { height: 51px!important; }
@@||zap.in^$content
zap.in#@##verifyAd
zap.in#@##flexContentAdFrame

These one ....one by one

**Comment by vozersky** [comment]
@ghajini make sure you actually press "enter" after adding a rule and the text field become gray (doesn't stay white)

let me know if that helps, please
