### ISSUE TITLE
"Block ads on this webside" tool misbehaves

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardBrowserExtension#691]
![image](https://cloud.githubusercontent.com/assets/17472907/26071271/2c0c3ef2-39b0-11e7-985f-4fce626b04a2.png)

* Edge 40
* can be reproduced on any websites, just try to use the blocking tool

**Comment by vozersky** [comment]
Everytime you click on blocking tool:

![image](https://cloud.githubusercontent.com/assets/17472907/26071871/49752948-39b2-11e7-8777-693aea5f41dd.png)

**Comment by Mizzick** [comment]
Nope it's fine with Edge 38 and 2.5.14, but broken with Edge 38 and 2.6.3
