### ISSUE TITLE
Allow user to disable specific filtering rules in Adguard filters

### ISSUE THREAD

**Issue by jlandersen** [AdguardTeam/AdguardBrowserExtension#695]
Hi - a small feature request

Some sites, e.g. Atlassian JIRA seem to be put in an exception list maintained internally/behind the scenes. It would be nice if it was possible to disable this exception when on a specific site, or manage this list in general. (JIRA is a tracking hog).

**Comment by vozersky** [comment]
Hi. Not sure if we'll be doing this for a browser extension, but let's keep a feature request for now.

**Comment by vozersky** [comment]
Similar request https://github.com/AdguardTeam/AdguardBrowserExtension/issues/629

**Comment by ameshkov** [comment]
The thing is that browser extension does not allow enabling/disabling rules of the filter subscriptions.

The easiest way to solve this would be to let people disable any rule. For instance, to provide an editable list with "disabled" rules (internally or somewhere in advanced settings). Thus, we'll be able to finally get rid of that ugly "site is in exceptions" message and let people enable ad blocking even if a website in excluded by some filter subscriptions.

**Comment by erkinalp** [comment]
It would worsen performance.

**Comment by ameshkov** [comment]
Forgot to update this issue. It is possible with `$badfilter` modifier.

Something like `@@||example.org^$badfilter` that disables: `@@||example.org^`
