### ISSUE TITLE
Add `Select all/none` buttons to rules constructor

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#703]
Sometimes too many check-boxes are selected by default

![image](http://imagizer.imageshack.com/img923/2779/iEUhV6.png)

**Comment by ameshkov** [comment]
It just selects all classes and IDs available. What would you suggest?

**Comment by ameshkov** [comment]
Ah, got it, just a button. I guess it's doable.
