### ISSUE TITLE
Access to settings in Safari

### ISSUE THREAD

**Issue by andrews05** [AdguardTeam/AdguardBrowserExtension#705]
Safari extensions commonly show a checkbox in the standard Extensions interface which will open a settings page when checked. This may be a weird way of doing it but for me it'd be nice if Adguard did the same. I don't keep Adguard in the toolbar which means there's currently no way for me to access the settings.

**Comment by vozersky** [comment]
@andrews05 hi!

Do you mean like this?

![screen shot 2017-05-24 at 15 14 22](https://cloud.githubusercontent.com/assets/17472907/26402705/0d7223b8-4094-11e7-9901-a02c25996a8a.png)

I don't think it's a common way, actually, it's kinda outdated to me. Checkbox instead of a button looks weird too.

**Comment by andrews05** [comment]
Hi @vozersky.
If you can do a button instead that'd be great. The point is, there's currently no way to access the settings if you don't have the toolbar button, so some form of alternative would be much appreciated.
