### ISSUE TITLE
Advanced settings menu does not expand

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardBrowserExtension#708]
Microsoft Edge 38.14393.0.0

![screenshot 2017-05-24 16 00 41](https://cloud.githubusercontent.com/assets/23637588/26404363/4df4e640-409a-11e7-9586-ee37219afe04.png)

**Comment by Mizzick** [comment]
@zebrum, can you please try this build?

[edge-beta-2.6.3.zip](https://github.com/AdguardTeam/AdguardBrowserExtension/files/1026063/edge-beta-2.6.3.zip)

**Comment by zebrum** [comment]
@Mizzick 
it works in Edge 38 now

**Comment by Mizzick** [comment]
Good, I think it's fixed with #704
