### ISSUE TITLE
Safari: Can't save HTML filtering rules

### ISSUE THREAD

**Issue by andrews05** [AdguardTeam/AdguardBrowserExtension#712]
I'm trying to add an HTML filtering rule but it won't save it. I've even tried pasting in the example from the docs, `example.org$$script[data-src="banner"]`, but when I save and refresh the settings page the rule disappears.

**Comment by vozersky** [comment]
Hi! Unfortunately, HTML filtering rules can't be supported by the browser extension, it's actually mentioned in the [KB article.](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#compatibility-with-different-versions-of-adguard-6)

**Comment by andrews05** [comment]
Whoops, missed that part. I managed to do with a javascript rule instead.
