### ISSUE TITLE
My 2 cents on the drama between Adguard and Adblock Protector Script

### ISSUE THREAD

**Issue by BetaLeaf** [AdguardTeam/AdguardBrowserExtension#713]
Look I know this isn't the place to be putting this, but as I am not a contributor, I cannot comment on the issue. All this drama over the last 3 days has me stressed out for no reason so I'm gonna do it anyways.  Here's my 2 cents on the whole Adguard - Adblock protector script drama.

@jspenguin2017 

So much headache in the last 3 days because you decided to take your rage out on a few people who opened issues and didn't take the time to read the line that basically says we only support uBlock, please don't open issues if you aren't using uBlock, we won't fix them. 

I had no problem with Adblock Protector Script, despite the lack of support, until you made changes to preventing Adguard users from using it. When I undo the change you made to the filter, I got it working again, for like 3 days, before it stopped working again today. This time, instead of force redirecting me to your website to let me know Adguard was not supported, the update completely disabled my internet on applications Adguard was hooked into with it. I turned on my computer and couldn't even access Google. Pages will sit there trying to load, chrome will realize it has stalled and asks if you want to wait or kill the tab. Waiting here does nothing so the only option I have is to kill the tab. If I had not gotten notice that this maintainer was not supporting Adguard and was taking active steps to prevent Adguard users from using the script, then good chance I would have ended up reinstalling windows before I figured it out what was causing the issue. 

After doing some independent research, I discovered that I need to replace Adblock Protector Script with AAK-Killer Cont. It would have been nice if you would have mentioned that on your website you were forcing Adguard users to be redirected to.

Ok, so, what could you have done to have a more positive impact?

Lets start by not force redirecting users to your own website, unless it is absolutely necessary to do so to deliver the message you wish to relay. A simple js alert saying Adguard is not supported and the filter should be uninstalled from Adguard is more than good enough. If you are going to go and redirect users to your website anyways, at the very least, let them know why it doesn't work, not just that it is not supported. Also, If you are going to maintain a similar project that does support Adguard, why not add that repository as a link to your site as "The alternative for Adguard users". You should also give users more time to move to a different solution before forcing changes on their system that would cripple the internet. 7 days is too short imho. Most corporations are given a least a couple of weeks, usually up to a month to fix the bugs that are reported to them before the discoverer of the bug goes public in an attempt to get the corporation in question to move their feet. I understand why you did what you did, but when the potential is the completely inability to access the internet, you really need to give users more time.

Also, I saw this: https://github.com/AdguardTeam/AdguardBrowserExtension/issues/701#issuecomment-304052064
![applicationframehost_2017-05-26_07-21-57](https://cloud.githubusercontent.com/assets/7028351/26492812/1a19a176-41e4-11e7-92cc-d24c3c2b5a86.png)
You do know that this is the very nature of how userscripts work correct? If you are looking for a solution that has more restricted access to what it can do, don't use userscript then. This is exactly why chrome and firefox have supported add-ons/extensions.

#701 

I would love to be a part of this community discussion. If you wouldn't mind opening up commenting, that would be great. Thanks.

**Comment by ameshkov** [comment]
> This time, instead of force redirecting me to your website to let me know Adguard was not supported, the update completely disabled my internet on applications

That's actually not his doing, really. I'll file a bug about it.

**Comment by BetaLeaf** [comment]
Alright, thanks for letting me know. 

I would love to be a part of this community discussion. If you wouldn't mind opening up commenting or adding me into the discussion, that would be great. Thanks.

**Comment by ameshkov** [comment]
@BetaLeaf huh, I thought anybody could comment on that issue.

**Comment by BetaLeaf** [comment]
I thought so to, but when I tried commenting, it said "You can't comment at this time."
On my end it shows #701 is closed and restricted to collaborators. https://github.com/AdguardTeam/AdguardBrowserExtension/issues/701#event-1093160946

**Comment by BetaLeaf** [comment]
That's why I did what I did and posted my 2 cents as a separate closed issue and just referenced the issue. If I had the ability to comment, I would have done so there.

**Comment by ameshkov** [comment]
Oh, that's unexpected, might be a Github bug:) I have accidentally locked it in the very beginning and unlocked immediately after this, it seems to be in a semi-locked state now. Ok, i'll mention you there, we'll see if it helps.

**Comment by BetaLeaf** [comment]
It's been about 10 minutes. I'm going to assume that, since we are replying 2-3 from each other, that you have taken steps to fix the semi-locked state. Unfortunately, I still cannot comment. No rush, just wanted to keep you updated.

**Comment by ameshkov** [comment]
Could you please try now?

**Comment by BetaLeaf** [comment]
Trying...

**Comment by BetaLeaf** [comment]
Nope. Still says "You can't comment at this time."

**Comment by ameshkov** [comment]
And now that's weird, I wonder how do others manage..

**Comment by BetaLeaf** [comment]
Indeed, I put in a support request to github. If I hear back, I will let you know.

What I said: 
```
Reference: https://github.com/AdguardTeam/AdguardBrowserExtension/issues/713#issuecomment-304263196

Trying to add a comment to https://github.com/AdguardTeam/AdguardBrowserExtension/issues/701 but it appears the thread is locked, despite it saying it was unlocked. The owner of the repository tried to mention me but that doesn't fix my inability to post a comment. What does the owner or I need to do to be able to comment?
```

**Comment by BetaLeaf** [comment]
@seanl-adg May I ask why you reopened this?

**Comment by ameshkov** [comment]
@seanl-adg seems to be unavailable at the moment. I guess he did it accidentally.

**Comment by BetaLeaf** [comment]
No worries. I was just curious as to why @seanl-adg re-opened it.

**Comment by BetaLeaf** [comment]
I got a reply from Github. Wasn't able to help me. @ameshkov I would contact them and see whats up.

```
Hi there!

Thanks for writing in!

The issue you are having does not appear to be the result of any technical issue that GitHub is experiencing. It may be a result of configurations or settings performed by another account.

We do consider these types of actions confidential and I'm afraid we will not be able to share any details beyond this.

Cheers,
Petros

```

**Comment by ameshkov** [comment]
@BetaLeaf sent you a collaboration invite with read permission, hope it's enough.

**Comment by BetaLeaf** [comment]
@ameshkov I have received and accepted it. Unfortunately, I am still unable to comment. Same error. It's not really a big deal. I just wanted to post my 2 cents about this drama. As long as the people in the issue are able to read my 2 cents, then I'm good. Thanks for the effort!

**Comment by ameshkov** [comment]
No problem:)

**Comment by BetaLeaf** [comment]
Oh and if I want to contribute in the future, I will make a pull request. Please set me back to just a regular user. It looks like you already did as I am writing this, but I just want to make sure there are no potential loose ends. Have a good day.

**Comment by ameshkov** [comment]
Sure, done!

**Comment by BetaLeaf** [comment]
Thanks.

**Comment by seanl-adg** [comment]
@BetaLeaf
Hi, @ameshkov is right, I must be accidentally tabbed on a "Reopen Issue" button while browsing the thread with a smartphone. I had no intention to reopen the issue.

**Comment by BetaLeaf** [comment]
No worries, @seanl-adg. Have a good day.
