### ISSUE TITLE
$content modifier works as URL exclusion

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#719]
This modifier must be ignored by extension.
![image](http://imagizer.imageshack.com/img922/2026/SjBqIL.png)

**Comment by Mizzick** [comment]
The list of ignored options:
```
UrlFilterRule.ignoreOptions = {
        // Deprecated modifiers
        'BACKGROUND': true,
        '~BACKGROUND': true,
        // Unused modifiers
        'COLLAPSE': true,
        '~COLLAPSE': true,
        '~DOCUMENT': true,
        // http://adguard.com/en/filterrules.html#advanced
        'CONTENT': true
    };
```

So this option $content is ignored, but the rule remains working.

**Comment by ameshkov** [comment]
A rule with a single `$content` modifier should be ignored.
A rule with multiple modifiers which includes `$content` should continue to work.
