### ISSUE TITLE
Google docs are broken in Adguard Edge extension

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#720]
Here how it looks with Adguard:
![unnamed](https://cloud.githubusercontent.com/assets/5947035/26697998/c2e0015a-471c-11e7-9cea-2ee4556a5b56.jpg)

To resolve the issue it's enough to add docs.google.com to exceptions.

@Alex-302 let's do it right now in AG filters unless the new version of extension lands.

**Comment by Alex-302** [comment]
Temporary rule:
```
@@||docs.google.com^$document
```
Remove this rule for reproducing

**Comment by atropnikov** [comment]
It seems the problem is that we pre-hide iframe `ElementCollapser.hideBySelector(iframeHidingSelector, null, shadowRoot);`
It's not a first time we have a problem with it.

**Comment by atropnikov** [comment]
Issues with the same problem:
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/503#issuecomment-299173475
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/503
