### ISSUE TITLE
Context menu is broken after you change focus from filtering log window back to the page

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardBrowserExtension#727]
Microsoft Edge 40.15063.0.0

STR:

1. Open any page in the browser.
2. Open filtering log.
3. Switch back to the first opened tab.
4. Right-click on the page and go to Adguard context menu.

Expected result:
![image](https://user-images.githubusercontent.com/17472907/26892656-acee0cee-4bc1-11e7-9261-0d0b59b9fab2.png)

Actual result: 

![image](https://user-images.githubusercontent.com/17472907/26892630-96fcd974-4bc1-11e7-9fd5-7ce049e56a6d.png)

**Comment by vozersky** [comment]
Console log is clear.

Possible Edge browser issue?

**Comment by ameshkov** [comment]
@Mizzick we need a better description of this issue in order to file a bug report to MS Edge devs

**Comment by vozersky** [comment]
still reproducable

**Comment by atropnikov** [comment]
[browser.windows.onFocusChanged](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/windows/onFocusChanged) works incorrectly in the Edge browser.

I've created a simple add-on:
```javascript
var lastWindowId = browser.windows.WINDOW_ID_NONE;

    browser.windows.onFocusChanged.addListener(function (windowId) {
        if (windowId === browser.windows.WINDOW_ID_NONE) {
            console.info('All Edge windows lost focus');
        } else if (windowId !== browser.windows.WINDOW_ID_NONE && lastWindowId === browser.windows.WINDOW_ID_NONE) {
            console.info('Focused to Edge window ' + windowId + ' from outside');
            return;
        } else if (browser.windows.WINDOW_ID_NONE && windowId !== browser.windows.WINDOW_ID_NONE) {
            console.info('Focused to Edge window ' + windowId + ' from Edge window ' + lastWindowId + '. You will never see this message.');
        }
        lastWindowId = windowId;
    });
```

The last `else if` statement won't ever be executed. Corresponding issue in the Edge bug tracker https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/13012346/

@ameshkov Could you fill a bug report?

**Comment by atropnikov** [comment]
[EdgeWindowFocus.zip](https://github.com/AdguardTeam/AdguardBrowserExtension/files/1225247/EdgeWindowFocus.zip)

**Comment by atropnikov** [comment]
[EdgeWindowFocus.zip](https://github.com/AdguardTeam/AdguardBrowserExtension/files/1225262/EdgeWindowFocus.zip)

**Comment by ameshkov** [comment]
Reported to MS
