### ISSUE TITLE
Make checkboxes in the filtering log apply "and" logic to the URL list (instead of "or")

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardBrowserExtension#728]
So if you, for example, check "third party" and "blocked", then only blocked third party requests will be shown. 

Now it shows all third party requests together with all requests that were blocked:

![image](https://user-images.githubusercontent.com/17472907/26895689-0978506a-4bcb-11e7-9aca-29505aabda58.png)

**Comment by Mizzick** [comment]
We had the discussion already on it, check #293

**Comment by ameshkov** [comment]
Yep, discussed it already, we find the current way more convenient.

**Comment by vozersky** [comment]
@ameshkov but why does it work different in win app then?

**Comment by ameshkov** [comment]
@vozersky okay, you've got a point, we should provide similar behavior:)

**Comment by Alex-302** [comment]
what about inverse `third party` filter? Sometimes I want to see only first-party requests
