### ISSUE TITLE
Search ads are not shown when "Allow search ads" option is enabled

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardBrowserExtension#731]
1. Google search ads not showing in Chrome, Firefox, Safari and Edge.

2. Bing search ads - in Safari

3. Yahoo search ads - in Safari

**Comment by vozersky** [comment]
It all works fine with the Mac app, except Yahoo, so I am not sure if it's a filtering problem

**Comment by vozersky** [comment]
@Mizzick please assist

**Comment by Mizzick** [comment]
Guys, this is just an other filter in the extension, it works exactly the same as others.
So in most cases it's about the rules in this filter.
Except of Safari, cause the rules are converted to content-blocker format, but it's again all about the rules.

**Comment by ameshkov** [comment]
> Except of Safari, cause the rules are converted to content-blocker format, but it's again all about the rules.

This might be a converter error and that's why I ask you to look into it.

**Comment by Mizzick** [comment]
[errors.txt](https://github.com/AdguardTeam/AdguardBrowserExtension/files/1077549/errors.txt)

**Comment by Mizzick** [comment]
@Alex-302 please check the file above

**Comment by Alex-302** [comment]
@Mizzick 
unsupported `[-ext-` - Extended CSS
`#@$#` - exclusion for CSS rules
`#%#` - JS

Search ads are visible on my side:
http://imagizer.imageshack.com/img922/1627/M5e79F.png
and on iOS

**Comment by Mizzick** [comment]
These errors are from Safari logs.

**Comment by Alex-302** [comment]
That rules are valid. Maybe something is wrong with converter.
Useful ads in Safari with 2.6.4
http://imagizer.imageshack.com/img924/4259/L1OscF.png

**Comment by Mizzick** [comment]
So the ads are shown? What else is wrong then?

**Comment by Alex-302** [comment]
@vozersky @zebrum What else is wrong?

**Comment by vozersky** [comment]
* Chrome is fine atm  I'm pretty sure it's connected to the latest changes in English filter
* Latest Firefox dev - **yahoo** and **google** have the issue 
* Safari - **bing** and **yahoo** have the issue

**Comment by ameshkov** [comment]
Here are the rules used for this:
https://github.com/AdguardTeam/AdguardFilters/blob/master/UsefulAdsFilter/sections/usefulads.txt#L21
```
! Bing
@@||bing.com/search$document
! Yahoo
@@||search.yahoo.com/search$document
```

These rules are ignored by Safari converter as document-level modifiers like `document` and `elemhide` can be used on the domain-level only (and not on a page-level).

So, to fix this issue in Safari we should change these two rules, make them more "specific" and use `#@#` instead of document-level exceptions.

**Comment by Alex-302** [comment]
Got it.

**Comment by ameshkov** [comment]
Closed and marked as invalid as it has nothing to do with the browser extensions functionality.
