### ISSUE TITLE
Invert whitelist issue, excluded domains are still added 

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardBrowserExtension#736]
**STR:** 

- Enable Invert whitelist mode
- Go to www.adguard.com
- Click on extension icon and click "enable protection" 

**Result:** adguard.com has been added to the whitelist

Though you are getting the message "This website is in the exceptions.." and the extension doesn't start filtering the site it is still a wrong behaviour, I think.

**Comment by ameshkov** [comment]
> Though you are getting the message "This website is in the exceptions.." and the extension doesn't start filtering the site it is still a wrong behaviour, I think.

What's the expected result then

**Comment by vozersky** [comment]
as to me, the domain name should not be added to the whitelist

**Comment by vozersky** [comment]
or the better way: 

can't we just show the message "This website is in the exceptions.." from the start? without trying to filter the excluded website first

**Comment by ameshkov** [comment]
I suppose this issue will be resolved automatically once we provide an opportunity to disable existing filter rules.
