### ISSUE TITLE
Anti-AB script on free-torrents.org - "Block ads..." tool doesn't work

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardBrowserExtension#737]
STR

- go to www.free-torrents.org
- try to use "Block ads on this website" tool

Safari browser even crashes if you try doing it several times

**Comment by vozersky** [comment]
> function antiadblock() {
    var a = $('iframe[style="visibility: visible; position: fixed !important; display: block !important; border: 0px !important; -webkit-box-shadow: rgba(0, 0, 0, 0.498039) 5px 5px 20px; z-index: 2147483647; left: 50px; top: 50px; width: 416px; height: 195px; opacity: 0.7;"]')
      , var2 = $('iframe[style="visibility: visible; position: fixed !important; display: block !important; border: 0px !important; -webkit-box-shadow: rgba(0, 0, 0, 0.498039) 5px 5px 20px; z-index: 2147483647; left: 50px; top: 50px; width: 416px; height: 195px;"]')
      , var3 = $('iframe[id="adguard-assistant-dialog"]')
      , var4 = $('iframe[class="sg_ignore adg-view-important"]')
      , div = $('div[class="__adblockplus__overlay"]')
      , div2 = $('div[class="sg_border"]')
      , div3 = $('div[class="sg_border sg_bottom_border"]');
    a.remove();
    var2.remove();
    var3.remove();
    var4.remove();
    div.remove();
    div2.remove();
    div3.remove();
    setTimeout(function() {
        antiadblock()
    }, 250)
}
console.info('Скрипт Anti-AdBlock сейчас будет запущен...');
antiadblock();
console.info('Скрипт Anti-AdBlock работает.');

**Comment by Alex-302** [comment]
try
```
#%#Object.defineProperty(window, 'antiadblock', { get: function() { return; } });
```

**Comment by ameshkov** [comment]
@vozersky guys, I guess it'd be better to discuss it in the filters repo

**Comment by vozersky** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/5330
