### ISSUE TITLE
Rules constructor works only after restarting the browser

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#738]
<details>

![image](http://imagizer.imageshack.com/img922/3189/ppGm8B.png)
</details>
extension version 2.6.4

**Comment by Alex-302** [comment]
It is working after restarting the browser.

**Comment by Mizzick** [comment]
Isn't it enough to just reopen devtools?

**Comment by Alex-302** [comment]
No.

**Comment by Alex-302** [comment]
@vozersky Please check it.

**Comment by vozersky** [comment]
Works for me, @Alex-302 can you still reproduce it?

**Comment by Alex-302** [comment]
Strange. I can't reproduce it now.
