### ISSUE TITLE
The "you just installed adguard" tab keeps popping up after cache/cookie/etc cleanup

### ISSUE THREAD

**Issue by Rabbit1991** [AdguardTeam/AdguardBrowserExtension#740]
As the title says, every time i cleanup the cache/cookie/etc using ccleaner or different program the "you just installed adguard" tab keeps popping up.
Although not urgent, it is still a pain in the ass to see everytime i do a cleanup then run firefox
My info if necessary:
I use firefox 53.0.3 64bit
Adguard adblocker 2.6.1 beta: addon 
Windows 10 home
Adguard for windows 6.2.369.1938 beta

**Comment by The-Commissioner** [comment]
@Rabbit1991 

>  Adguard adblocker 2.6.1 beta: addon

This is the problem area. There was an update release which should fix your problem. So, update your addon(2.6.3 beta).

https://addons.mozilla.org/en-US/firefox/addon/adguard-adblocker/versions/beta

**Comment by vozersky** [comment]
@Rabbit1991 Hi, yeah, please go ahead and update to the latest version :)
