### ISSUE TITLE
Frustrated bug in Adquard or MS Edge.

### ISSUE THREAD

**Issue by seba2282** [AdguardTeam/AdguardBrowserExtension#742]
I have a not typical problem. First I turn on some filters in Adquard Extension Edge and after turn off and turn on MS Edge again, I must turn on all the same filters in settings, what I turned on earlier. This is frustrating. Sorry for my style, but I can't write about this problem easier. 
Best Regards

**Comment by vozersky** [comment]
@seba2282 Hi! What version of MS Edge do you use? And Adguard extension is a stable version from extension store or the beta?

**Comment by seba2282** [comment]
First : Adquard Extension stable from MS Store
Second : MS Edge from Windows 10 1703 after last updates (W10 Stable Final Compilations Channels , not Insider). I forgot what is Edge version actually now. But all final official stable.

**Comment by vozersky** [comment]
can't reproduce with Microsoft Edge 40.15063.0.0

**Comment by seba2282** [comment]
Is it last version Edge after yesterday updates W10 CU 1703 ? Why ? Will be fix on this bug ?

**Comment by vozersky** [comment]
@seba2282 
![image](https://user-images.githubusercontent.com/17472907/27137230-09e4e954-5126-11e7-913c-0e8192c0da2a.png)

so, basically, when you restart the browser all the filters  you have previously added are missing from "Adblocker" section?

**Comment by vozersky** [comment]
@seba2282  Could you please check if there are any errors in the console when you add those filters etc.?

<details><summary>how to find the console:</summary>

**1.**  

![screen shot 2017-06-14 at 17 23 57](https://user-images.githubusercontent.com/17472907/27137404-8ddd2b4a-5126-11e7-853d-23619c8d0df2.png)

**2.**
![screen shot 2017-06-14 at 17 24 07](https://user-images.githubusercontent.com/17472907/27137422-969fc29c-5126-11e7-8fb3-0b693f3a9acd.png)

**3.**

![image](https://user-images.githubusercontent.com/17472907/27137521-ddd8760e-5126-11e7-9a56-0ad39917e785.png)

**Comment by seba2282** [comment]
@vozersky I will check, if I will be on PC but it is not typical. I turn on all filters without reek and after close and open again Edge I haven't turn on this filter, but only default. And I don't know why. Please give me time, because I am mobile actually and without home.

**Comment by seba2282** [comment]
Ok. I haven't background page. And I see, after clean history example by windows cleaner or privazer or ccleaner, AG back to previous options and monits about thank you for installing.

**Comment by vozersky** [comment]
@seba2282 try beta version and let me know if helps please: https://www.microsoft.com/ru-ru/store/p/adguard-adblocker-beta/9ndmfr4cv25m?rtc=1

**Comment by vozersky** [comment]
@seba2282   Here's the extension: https://github.com/AdguardTeam/AdguardBrowserExtension/releases/download/untagged-a5d7e475ab6bd27625e3/edge-release-2.6.4.zip

to install it:

1. in Edge browser type `about:flags ` in the adress bar and press enter 
2. Put a checkbox next to "Enable extension developer"
3. Restart the browser

Now you can load beta extension to the browser in extension side menu (unpack the archieve first)

**Comment by seba2282** [comment]
Ok. I will try, if I will be on PC. :)

**Comment by seba2282** [comment]
When premiere Final new version AG extension for browsers (Edge, Chrome, etc) ?

**Comment by seba2282** [comment]
My problem fixed with AG 2.6.4 Thanks 😊

**Comment by vozersky** [comment]
@seba2282  great 👍
