### ISSUE TITLE
[Question] Stop HTML5 and Flash Autorun video's Ads

### ISSUE THREAD

**Issue by sandybeachit** [AdguardTeam/AdguardBrowserExtension#743]
We have:

https://github.com/AdguardTeam/AdguardForWindows/issues/337

for adding this feature to the Adguard desktop app, my question is will this feature be added to the chrome extension as well as the desktop app or just the desktop app ?

**Comment by vozersky** [comment]
ideally, yes
please stick to the original thread for the discussion
