### ISSUE TITLE
Unblocked pop-up 

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardBrowserExtension#746]
https://mailtrack.io/trace/link/68af05769f497fcc9bca2782db2aa05897e4120d?url=http%3A%2F%2Fwww.nolo.com%2Flegal-encyclopedia%2Fwhat-independent-medical-examination-how-will-it-affect-my-workers-compensation-case.html&userId=1269685&signature=c12057303b877874

Chrome extension 

<details><summary>Screenshot:</summary>

![screen shot 2017-06-15 at 12 17 34 am](https://user-images.githubusercontent.com/27292111/27155198-b01e19be-5160-11e7-8997-ab306690c45c.png)

</details>

Ticket id: 1575195

**Comment by vozersky** [comment]
@veronikasav Filtering relates issues has to be reported to https://github.com/AdguardTeam/AdguardFilters/issues
