### ISSUE TITLE
Latest Firefox (54) enables Multiprocess support but Adguard extension currently doesn't support it

### ISSUE THREAD

**Issue by ensiform** [AdguardTeam/AdguardBrowserExtension#747]
Firefox 54 was just recently released and they have finally enabled Electrolysis/ Multiprocess however, because the Adguard extension does not yet support this, it is disabled globally.

Can be checked in about:support (though it won't tell you which ones are causing it)

Mozilla has an extension for checking which are not compatible: https://addons.mozilla.org/en-US/firefox/addon/add-on-compatibility-reporter/?src=api

This gives more details about incompatibility with multiprocess support.

**Comment by ameshkov** [comment]
Hi! v2.6 branch is transformed into an Embedded WebExtensions type already (it's in the beta channel), so we're on the way to fully convert it to WebExtensions by the time FF 57 is there.

**Comment by ensiform** [comment]
Okay, great.
