### ISSUE TITLE
Difference of blocked ads before AG turn off and after turn on

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardBrowserExtension#748]
1) Enter this site: http://qafqazinfo.az/news/detail/neft-46-dollara-dusub-188507

![screenshot_27](https://user-images.githubusercontent.com/19608513/27216959-fe2f6684-5288-11e7-9005-41c0404a5fda.png)

In the picture you can see that the site is clean and the number of blocked ads is 27.

2) Now turn off ADGUARD and refresh the page.

3) And then turn on ADGUARD and refresh the page. 

![screenshot_29](https://user-images.githubusercontent.com/19608513/27217103-8a650dd4-5289-11e7-87ef-67b82219ca31.png)

So, in this picture you can see some banners in the top and in the center and the number of blocked ads is 21.

What is the reason of this?

**Comment by ameshkov** [comment]
Just in case, what filters do you have enabled?

**Comment by ameshkov** [comment]
Got it, turkish filter blocks ads on this website.

Weird, I was able to reproduce the issue one time, and can't do it anymore.

**Comment by ameshkov** [comment]
Ah, okay, I figured how to reproduce it.

@atropnikov @Mizzick guys, please take a look.

Here's what happens:

1. Top banner is blocked by the `||qafqazinfo.az/banners/` rule
2. When you disable AG and refresh the page, the banner is loaded **and cached** by the browser.
3. So, when you enable AG again and reload the page, the banner is not blocked and loaded from cache every time.

Does it really ignore `webRequest.onBeforeRequest` listener? If so, we'd better file a bug report to Chrome.

**Comment by thislife81** [comment]
Here are my filters:

![screenshot_32](https://user-images.githubusercontent.com/19608513/27219399-a299740e-5292-11e7-994e-70ca0e64147a.png)

**Comment by ameshkov** [comment]
@Mizzick let's try calling this on every request filter change.

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest/handlerBehaviorChanged

**Comment by atropnikov** [comment]
I suppose, in this case, we should invoke this method when integration state changes.

**Comment by ameshkov** [comment]
> I suppose, in this case, we should invoke this method when integration state changes.

Did you mean "also when"?

**Comment by atropnikov** [comment]
Yes, I did. We already invoke `handlerBehaviorChanged` on every request filter change.

**Comment by ameshkov** [comment]
> Yes, I did. We already invoke handlerBehaviorChanged on every request filter change.

Huh, then I guess it does not help as I reproduced this issue with v2.6.

**Comment by atropnikov** [comment]
You just turn on / turn off integration mode, without request filter changes, don't you?

**Comment by ameshkov** [comment]
> You just turn on / turn off integration mode, without request filter changes, don't you?

I turn on/off AG protection for the website.

**Comment by atropnikov** [comment]
Sorry, I thought about AG integration mode. Maybe adding or removing rule to whitelist doesn't invoke `handlerBehaviorChanged`. @Mizzick we should check this.
