### ISSUE TITLE
Scrollbar glitch

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardBrowserExtension#750]
Double scrollbar in the filtering log (Chrome browser)

![screen shot 2017-06-20 at 15 46 42](https://user-images.githubusercontent.com/17472907/27333915-33f95744-55d0-11e7-92a8-e363f76eb092.png)

**Comment by maximtop** [comment]
I couldn't reproduce this issue on Mac OS and on Virtual Windows OS
