### ISSUE TITLE
Add support for extended css rules in the devtools

### ISSUE THREAD

**Issue by theseanl** [AdguardTeam/AdguardBrowserExtension#756]
To debug extended css rules, currently one have to repeat adding several rules to user filter and refresh the page.

It would be helpful, if devtools provide ability to highlight elements matching a user-inputted selectors in ExtCss syntax, and provide ability to preview the page that the rule in action.

**Comment by ameshkov** [comment]
Wouldn't it be better to add ExtCss support to the existing DevTools module?
At the moment, preview does not work for ExtCss rules.

![add support for extended css rules in the devtools issue 756 adguardteam adguardbrowserextension 2017-06-28 17-45-58](https://user-images.githubusercontent.com/5947035/27643423-b75120ea-5c29-11e7-8be5-5a7439683e7f.png)

**Comment by alexx7311** [comment]
upd in #2345
