### ISSUE TITLE
Windows Store error

### ISSUE THREAD

**Issue by MarDarkXT** [AdguardTeam/AdguardBrowserExtension#758]
Every time I try to access Adguard extension on Windows Store I get an error. This happens on all devices. All other extensions work.
![error](https://user-images.githubusercontent.com/25929539/27518596-3ce00ab8-59ec-11e7-9c21-12952d707896.PNG)

**Comment by seba2282** [comment]
I have the same and some number error. I forgot what number...

**Comment by vozersky** [comment]
Code: 0x8000FFFF
CV: mE8+U2PEgEaHZA1y

**Comment by ameshkov** [comment]
Does this link work?
https://www.microsoft.com/en-US/store/p/adguard-adblocker/9mz607gwkbs7?rtc=1

**Comment by ameshkov** [comment]
Also what about AG beta?
https://www.microsoft.com/store/apps/9NDMFR4CV25M

**Comment by vozersky** [comment]
@ameshkov no, it doesn't

**Comment by ameshkov** [comment]
Both beta and stable?

**Comment by vozersky** [comment]
@ameshkov 

both of them
the link works for a browser, but after you hit "Get the app button" the Store app opens with an error
 

![image](https://user-images.githubusercontent.com/17472907/27533940-015af368-5a6e-11e7-9bff-9e3857b9f0e7.png)

**Comment by ameshkov** [comment]
Reported to MS, I hope they'll answer soon.

**Comment by seba2282** [comment]
In Polish region any changes.
![adguard in windows store](https://user-images.githubusercontent.com/16944478/27590571-6d100cec-5b4f-11e7-87e1-073ce8592fe8.PNG)

**Comment by ameshkov** [comment]
@seba2282 MS guys are checking with the Windows Store team, waiting for them to figure what's causing it.

**Comment by seba2282** [comment]
@ameshkov Thanks for information.

**Comment by ameshkov** [comment]
It appears that we're not alone suffering from this issue. Windows Store team is working to resolve it as soon as possible.

**Comment by seba2282** [comment]
@ameshkov thanks. How can I report problem with filtering in new Adguard extension for Edge. I added rule ||redcdn.pl and I can still write this adress and AG doesn't block it. Version 2.6.4 for Edge. More sites still detects blocker. Really reek and inconpatible protector don't work. AG should have his dedicated scripts and list in one filter protector Adguard Adblocker. Sorry if here. But it is really big bug. The same Android and Windows should have. :)

**Comment by ameshkov** [comment]
Off-topic, but anyway.

> I added rule ||redcdn.pl and I can still write this adress and AG doesn't block it

By default AG does not block requests which are opened in the main browser window (tab). It blocks sub-requests only.

If you want a domain to prevent domain from loading in a tab, add `$empty` modifier.

**Comment by seba2282** [comment]
@ameshkov Sorry one more. Can you write all rule name block ? Can you deal my suggest "remove reek and protector inconpatible and adding dedicated Adguard Protector (list and scripts) in one filter" ? I think it time on this changes. :)

**Comment by ameshkov** [comment]
@seba2282 oh, I've already confirmed once that we will do it, don't worry:)

**Comment by seba2282** [comment]
@ameshkov Generally, I don't believe in third party protectors. And waiting for all products and please more filters for Android (example KAD, etc). One more thank you. :)

**Comment by MarDarkXT** [comment]
Store is working again.

**Comment by ameshkov** [comment]
@MarDarkXT all good, confirmed!
