### ISSUE TITLE
Adguard severely degrades performance on google chrome

### ISSUE THREAD

**Issue by pedrogarcia** [AdguardTeam/AdguardBrowserExtension#759]
Filters enabled:
English filterVersion 1.1.23. Updated 25 june 2017 at 14:00.
Social media filterVersion 1.0.20.74. Updated 23 june 2017 at 12:00.
Annoyances filterVersion 1.0.14.57. Updated 23 june 2017 at 18:02.
Spanish/Portuguese filterVersion 1.0.86.68. Updated 31 may 2017 at 02:09.
Adblock Warning Removal ListVersion 1.0.82.64. Updated 25 june 2017 at 14:34.

Send statistics for ad filters usage is turned off.

Google chrome is frequently stuttering and freezing while browsing and becoming unresponsive or locked, and especially while scrolling during a page load. With ublock origin or with no adblock, performance is significantly better. My computer is a little old, but it still has reasonable performance.

**Comment by ameshkov** [comment]
What exact version of Adguard and browser do you use?

**Comment by pedrogarcia** [comment]
​​
Google Chrome 59.0.3071.115 (Official Build) (64-bit)

Adguard AdBlocker version 2.5.11

I tried
​ ​
Adguard AdBlocker (Beta)
​ ​
2.6.5
​ as well, and it improves very little. ​


- Pedro H Garcia

**Comment by ameshkov** [comment]
There is one more thing I advise you to try. AG settings -> Options -> scroll to bottom -> enable "Use optimized filters"

Does it help?

**Comment by pedrogarcia** [comment]
Nope, I still see a lot of stuttering that I don't see with uBlock, especially when scrolling pages. 
Interestingly, I use adguard for microsoft edge on the same computer and it doesn't have the same issues.

Adguard always seemed to hang compared to uBlock, but with the last chrome versions (I'd say since 56, I think.) it started becoming way more noticeable.

**Comment by ameshkov** [comment]
@pedrogarcia what computer configuration do you have? Does it happen on every website or on some particular one?

**Comment by pedrogarcia** [comment]
It is a Dell notebook.
Intel Core i7-3632QM
AMD Radeon HD 7730M

**Comment by ameshkov** [comment]
Configuration is okay so performance issues surprise me.

What about second question (every website or some particular)?

**Comment by pedrogarcia** [comment]
I pressed shift+enter and it submitted the comment early. 

It happens on every website, but the more static web site it is, the less noticeable it is. If the website is very dynamic, like twitter, facebook is the worse, some blogs with a lot of comments, or play music, spotify, youtube, when I'm searching for images, stuff like that.

**Comment by pedrogarcia** [comment]
I forgot to mention newsblur, which i use a lot, and it is a feed reader. The issue is only really a problem because it makes scrolling stutter, and on these websites, when you reach the bottom, they load more content.

**Comment by ameshkov** [comment]
@pedrogarcia just in case, do you see a difference with this rule added to the user filter: `@@||newsblur.com^$elemhide`

**Comment by pedrogarcia** [comment]
Nope. I don't think it is anything website specific. I think that maybe some changes chrome's been making are affecting more adguard. But I tried a lot of things and I could not make the issue go away when using adguard. 

I found out just now that setting the #disable-v8-ignition-turbo flag to 'Enabled' in chrome:flags improves the situation.

**Comment by ameshkov** [comment]
> Nope. I don't think it is anything website specific. I think that maybe some changes chrome's been making are affecting more adguard. But I tried a lot of things and I could not make the issue go away when using adguard.

That rule disables part of the AG functionality on newsblur, that's why I asked. So now we now the problem is not due to cosmetic rules. And now I wonder what's the culprit.

**Comment by vozersky** [comment]
@pedrogarcia try to disable all other exceptions and userscripts and test with only Adguard enabled, there could be some kind of specific conflict in your environment (and we can fix it if understand what goes wrong). Adguard never had just "general" performance issues.

**Comment by pedrogarcia** [comment]
I have tested with the #disable-v8-ignition-turbo set to 'enabled' and with adguard 2.6.5, and the problems seem to have disappeared.

**Comment by ameshkov** [comment]
> I have tested with the #disable-v8-ignition-turbo set to 'enabled' and with adguard 2.6.5, and the problems seem to have disappeared.

That's interesting! I've been reading about this V8 performance optimizations, and in theory it should've made things faster, I wonder why it didn't.

Documentation:
http://benediktmeurer.de/2017/04/03/v8-behind-the-scenes-march-edition/

@vozersky could you please try setting it to `disabled` and check if there's any difference?
