### ISSUE TITLE
Adguard messing with Javascript Stylesheets Chrome

### ISSUE THREAD

**Issue by AeroyrHwrdd** [AdguardTeam/AdguardBrowserExtension#763]
I am unaware if it does the same on certain sites in other browsers as I mainly use Chrome. But on YT, Ebay and Just Eat so far I experienced an interference with stylesheets so I cannot play videos, see any images, its just white background and wording. 

I'm wondering if these websites are trying to discourage the use of adguard.

**Comment by vozersky** [comment]
@AeroyrHwrdd 
Sounds like a particular filtering rule problem 
What filters do you use and do you have anything in the user filter?
Also, what browser do you use?

**Comment by ameshkov** [comment]
> its just white background and wording.

@vozersky there was an issue with one filter resolved recently by @mmigi. I don't remember what filter was that, though, but the problem sounds just like what was happening.

**Comment by ameshkov** [comment]
I remembered! That was Hufilter. @AeroyrHwrdd do you use it?

**Comment by AeroyrHwrdd** [comment]
English filter
Spyware filter
Russian filter
German filter
Japanese filter
Dutch filter
Spanish/Portuguese filter
EasyList China
EasyList Italy
Liste FR
Norsk adblockliste
void.gr
Adblock-Persian list
Adblock polskie reguły
List-KR

I don't think I see a HU filter. 

I have 'Allow search ads and websites' self-promotion' disabled.

**Comment by vozersky** [comment]
@AeroyrHwrdd 

I am pretty sure this is Adblock-Persian list 1.0.0.25 [issue](https://github.com/AdguardTeam/AdguardFilters/issues/5485), try updating your filters and see if it helps ( "Check for filter updates" under the filters list).

Please give me the direct link to the page where the issue occurs, if it still does. Closed for now.
