### ISSUE TITLE
[Feature Request] Element Blocker Like uBlock

### ISSUE THREAD

**Issue by zero77** [AdguardTeam/AdguardBrowserExtension#765]
Can you please add an element blocker like uBlock has.

That allows the user to select an element on the page to add to a custom block list.

github.com/gorhill/uBlock/wiki/Element-picker

Thanks

**Comment by ameshkov** [comment]
What's the problem with existing element blocker?

**Comment by ameshkov** [comment]
**Simple blocker for casual users**
AG icon -> Block ads on this website.

**Complicated blocker for power users**
Open browser dev tools, select element, open Adguard tab - https://monosnap.com/file/Ilm16t5eaj7Oo83BQ9xcgYZN1YYKk9

**Filtering log**
AG menu -> click on small magnifier icon near the "Blocked" counter

**Comment by zero77** [comment]
yes, you are right sorry I missed it.

**Comment by The-Commissioner** [comment]
Umm...the choice of words there.

> Complicated blocker for **power users**

Only chrome users are power users?

**Comment by ameshkov** [comment]
> Only chrome users are power users?

FF plans to add `browser.devtools` support to WebExtensions, so eventually they will also get that module.

**Comment by The-Commissioner** [comment]
You didn't understand what I was saying, let it be.
