### ISSUE TITLE
Change the link to 'Search ads and websites' self-promotion'

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardBrowserExtension#767]
Here: https://www.screencast.com/t/MsC1Y2lu (after the first install) and here: https://www.screencast.com/t/QeF4gXAZUceK (in the settings)

The correct link is https://kb.adguard.com/general/search-ads-and-self-promotion

**Comment by Mizzick** [comment]
I think then this is the right one?
> https://kb.adguard.com/general/search-ads-and-self-promotion?utm_source=extension&aid=16593
