### ISSUE TITLE
Safari Extension still on 2.5.12 (Safari Extension Gallery)

### ISSUE THREAD

**Issue by sergerosenthaler** [AdguardTeam/AdguardBrowserExtension#768]
The Safari Extension is still on 2.5.12 even when new installed over the Safari Extension Gallery.

**Comment by ameshkov** [comment]
It might be necessary to uninstall the prev version. Won't be necessary when v2.6.5 make to the extension gallery.

v2.6.5 is currently waiting for the Apple review.

**Comment by Alain1978** [comment]
Hello it's the same thing in AMO always the old version of Adguard only available in devlopment channel.

**Comment by vozersky** [comment]
@Alain1978 Hi! It's still not approved for AMO

**Comment by ameshkov** [comment]
It usually takes quite some time to pass the AMO review
