### ISSUE TITLE
Popup rules doesn't work in chrome beta 

### ISSUE THREAD

**Issue by gshumihin** [AdguardTeam/AdguardBrowserExtension#77]
Tested with 2.0.21 build.
Added ||lenta.ru^$popup,third-party to user filter. 
Went to lenta.ru from google.com without any problems.
Chrome version: 47.0.2526.58 beta (64-bit)

**Comment by ameshkov** [comment]
I suppose the problem is in the redirect.

Do we really need to fix this? I am not sure yet.
