### ISSUE TITLE
AdGuard causes browser crash on some pages

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#770]
Here is an example of such a page:
https://aliorbank.pl/hades/do/Login

We may need to publish a hotfix.

**Comment by atropnikov** [comment]
After applying style to `embed` element in the `tempHideElement` function, site script tries to load it again, so we get in an infinite loop.
It is interesting that issue appears only in the Chromium, but not in the Firefox.
