### ISSUE TITLE
Upgrade "ExtendedCss" module to v1.0.8

### ISSUE THREAD

**Issue by seanl-adg** [AdguardTeam/AdguardBrowserExtension#771]
https://github.com/AdguardTeam/ExtendedCss/releases/tag/1.0.7

Starting from this version, it supports `:has-text` pseudo class and its backward-compatible syntax `[-ext-has-text='...']`.

**Comment by seanl-adg** [comment]
https://github.com/AdguardTeam/ExtendedCss/releases/tag/1.0.8
In 1.0.8, it supports `:-abp-has` and `:-abp-contains` pseudo class. It does not support respective backward-compatible syntaxes.

**Comment by ameshkov** [comment]
@Mizzick forgot the validation
