### ISSUE TITLE
Incorrect work on Pale Moon v26.5 (WinXP)

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardBrowserExtension#773]
Плагины версий 2.5.х legacy - работают без нижеописанных ошибок. Версии 2.6.x legacy (до 2.6.5 включительно) НЕ работают полноценно сами и мешают нормальной работе браузера.

 После загрузки браузера значок Adguard'a имеет серый вид, как будто он выключен. При нажатии на него всплывает небольшое ПУСТОЕ меню:
![adguard fail](https://user-images.githubusercontent.com/17948007/27971631-1e4d2ff8-635c-11e7-90a9-a72ae89c6948.jpg)
При этом, если попытаться авторизоваться на AliExpress, то мы получим следующую картину:
![aliexpress fail](https://user-images.githubusercontent.com/17948007/27971824-c7d168aa-635c-11e7-821f-c4375956e495.jpg)
Т.е. области ввода логина и пароля НЕТ, он её блокирует.

 В консоли браузера следующие ошибки:
![scrn-20170707203630](https://user-images.githubusercontent.com/17948007/27972146-f0c3fdf8-635d-11e7-8c58-d3e6bb491953.jpg)

 Плагин версии 2.6.5 нормально работает в двух случаях:
1. При обновлении плагина с версии 2.5.19 на 2.6.5 (до перезапуска браузера).
2. При остановке "нерабочего" плагина на странице Дополнений браузера и дальнейшем перезапуске (причём долгом) этого плагина (до перезапуска браузера).

**Comment by ameshkov** [comment]
@XX-J мы ведь 2.6.5 делали чтобы он был совместим с Palemoon 27, на 26 уже и не смотрели.

**Comment by ameshkov** [comment]
Посмотрим теперь, проверим

**Comment by XX-J** [comment]
> мы ведь 2.6.5 делали чтобы он был совместим с Palemoon 27, на 26 уже и не смотрели.

Просто 26.5 - это последняя совместимая с Windows XP.

**Comment by XX-J** [comment]
Adguard v2.6.7 legacy - такая-же проблема. Повторяется через раз. Причём с версиями 2.5.x - никогда таких проблем небыло. Вот консоль ошибок:

![default](https://user-images.githubusercontent.com/17948007/28432227-d6bea9f8-6d8f-11e7-932b-627b3c9d9a08.jpg)
