### ISSUE TITLE
 Ad Guard 2.6.5 ‒ vk.com hanging

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardBrowserExtension#774]
AdGuard causes problems with hanging on the website vk.com after scrolling a certain number of posts on the page. The list of the filters is below. After turning off and turning on each filter one by one it was established that Russian filter causes that hanging.

<details><summary>Screenshot:</summary>

![screen shot 2017-07-10 at 6 48 56 am](https://user-images.githubusercontent.com/27292111/28002235-e25f9882-653b-11e7-9e6c-be9d96125cb7.png)

</details

Ticket ID: 1493043

**Comment by ameshkov** [comment]
@vozersky please check it

**Comment by vozersky** [comment]
@veronikasav 
what happens, exactly? seems to be working fine
and again,  all problems related to filters or specific rules are to be reported to Adguard Filters repo first.
