### ISSUE TITLE
wunderground.com - Incorrect blocking

### ISSUE THREAD

**Issue by vishchakl** [AdguardTeam/AdguardBrowserExtension#775]
Incorrect blocking on 
https://www.wunderground.com/cgi-bin/findweather/getForecast?query=zmw:30189.1.99999&MR=1
reproduced on Mac with Adguard Browser Extension for Chrome.
Ticket ID: 1154975
<details><summary>Screenshot:</summary>
 
![screen shot 2017-07-10 at 4 42 11 pm](https://user-images.githubusercontent.com/29872276/28021068-4ed26938-658f-11e7-81ed-860cef292ed4.png)

**Comment by Bohdan-SUP** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/5622
