### ISSUE TITLE
Adguard blocks buttons on some sites

### ISSUE THREAD

**Issue by vitalkanev** [AdguardTeam/AdguardBrowserExtension#781]
### Steps to reproduce
1. Go to the, example, [here](https://www.mvideo.ru/login) (It's MVideo login page) or to Billing page on GitHub account settings with *Extension enabled*
2. Clearly look at the page

### Expected behavior
It should show the buttons (e. g. Login or Register)

### Actual behaviour
It blocks :thinking: 
On mvideo.ru it even blocks `подписаться на рассылку` button

<details><summary>Screenshots:</summary>

Sorry, but I uploaded only links.  Click on it to see

[mvideo.ru enabled](https://i.imgur.com/mFZK1IP.png)
[mvideo.ru disabled](https://i.imgur.com/BUXWC0D.png)
[Billing page enabled](https://i.imgur.com/wm4XGwc.png)
[Billing page disabled](https://i.imgur.com/K1YbWf2.png)

</details>

<details><summary>Screenshots of the browser console:</summary>

mvideo.ru:
![devconsole_20:55](https://i.imgur.com/XIXtlEc.png)

Billing page (github.com): 
![devconsole_21:00](https://i.imgur.com/1FDWAGJ.png)
</details>

### Your environment

* Adguard AdBlocker extension version: 2.6.6 (from Yandex's `browser:tune` page)
  I didn't use `2.6.7` :smirk:
* Environment name and version: (e.g. Chrome 59.0.3071.115) Yandex.Browser 17.6.0.1633
* Filters you use in Adguard: [See the Private Gist](https://gist.github.com/vitalkanev/32e7704db2a81ed2e96b25b464bbd8ab)
* Any other browser extensions you have installed: AdBlock Plus, Avast Online Security, 
Альтернативный поиск, MEGA

**Comment by Mizzick** [comment]
Looks like a filter issue. @Alex-302 ?

**Comment by Alex-302** [comment]
I can't reproduce.
@vitalkanev try to disable another ad blockers.

**Comment by vitalkanev** [comment]
@Alex-302 I tried to disable another ad blocker and... results are still same...

#

Sorry, but it was caused with *this* rule: 
```
##.btn, .download-head, .btn-download, .lang-ru, .installed
```

This was happened in the `mywot.com` website, when I removed `Invite friends` button
