### ISSUE TITLE
Adguard blocks Google voice search in Yandex Browser

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardBrowserExtension#782]
### Steps to reproduce
1. Open google.com, click on the mic icon. 
2. Pronounce any request you would like to search for.

### Expected behavior
Request is recognised, search is completed.

### Actual behaviour
After a few seconds an "No internet connection" error appears.

### Your environment
* Adguard AdBlocker extension version: 2.6.6
* Yandex Browser for Windows 17.6.1.749

### Please note
**Also reproduced with 2.6.7 Beta**
**Was not reproduced with the latest YB 17.6.1.745 on macOS**

**Comment by ameshkov** [comment]
I suppose that's why:
![43d8a785-aac0-4394-be19-83c91ce15f34](https://user-images.githubusercontent.com/5947035/28377429-6197da12-6cb5-11e7-9aa4-c106e276630e.png)

**Comment by Mizzick** [comment]
Doesn't work without extension installed.

<img width="1198" alt="screenshot 2017-08-16 17 22 05" src="https://user-images.githubusercontent.com/13855288/29368101-73395acc-82a7-11e7-9f6d-e4962dc9ae5a.png">

**Comment by ameshkov** [comment]
It works without extension

**Comment by vitalkanev** [comment]
But then it works with extension on Yandex 17.4.1 (Windows XP) :wink:

**Comment by ameshkov** [comment]
It still happens in Yandex 17.7 beta on MacOS.

The problem itself has nothing to do with that WebSocket, though. It is more likely that it is caused by AG wrapper.

**Comment by ameshkov** [comment]
Confirmed to be a browser bug.

To break it, it's enough to add an empty `onHeadersReceived` listener: 
```
            browser.webRequest.onHeadersReceived.addListener(function (details) {
            }, urls ? {urls: urls} : {}, ["responseHeaders", "blocking"]);
```

**Comment by vitalkanev** [comment]
Also this was reproduced as bug on Yandex 17.6.1 Beta on Lubuntu Zesty
