### ISSUE TITLE
Adguard doesn't work in Firefox nightly

### ISSUE THREAD

**Issue by Anoop2609** [AdguardTeam/AdguardBrowserExtension#783]
### Steps to reproduce

1.While installing adguard filters database is not loading properly.
2.Clicking on adguard icon on toolbar did not show setting box.
3.Other way by clicking right click we can open Adguard setting but nothing is working there also

### Actual behavior

Doing Nothing, Import Legacy extension on web-extension ASAP

<details><summary>Screenshot:</summary>

![screenshot 40](https://user-images.githubusercontent.com/23557479/28278450-c9ceef84-6b3a-11e7-9015-80cf03ba0d75.png)
![screenshot 41](https://user-images.githubusercontent.com/23557479/28278449-c9cdff20-6b3a-11e7-9161-e26918b70114.png)
![screenshot 42](https://user-images.githubusercontent.com/23557479/28278451-c9d390fc-6b3a-11e7-856d-8b10d4426f52.png)
![screenshot 43](https://user-images.githubusercontent.com/23557479/28278452-ca219f18-6b3a-11e7-9652-1874da4cd45e.png)

</details>

<details><summary>Screenshot of the browser console:</summary>

![screenshot 44](https://user-images.githubusercontent.com/23557479/28278559-24bfe11e-6b3b-11e7-86f7-388e70d54a94.png)
![screenshot 45](https://user-images.githubusercontent.com/23557479/28278564-29ba98c6-6b3b-11e7-9aee-9a956394e605.png)

</details>

### Your environment

* Adguard AdBlocker extension version: Adguard AdBlocker beta 2.6.7
* Environment name and version: Firefox Nightly 56.0a1 (17-07-2017)
* Filters you use in Adguard:None 
* Any other browser extensions you have installed: HTTPS Everywhere, Privacy Badger, IDM Integration Module.

**Comment by atropnikov** [comment]
@Anoop2609 
I cannot reproduce this issue. Could you try to remove the extension and retry installation? Which file did you install? `firefox-standalone-beta-2.6.7.xpi`?

**Comment by Anoop2609** [comment]
Same problem again, after reinstalling Firefox Nightly and then adguard firefox-standalone-beta-2.6.7.xpi. I don't know why this issue is not reproduce in your system and this time there is no other extension installed. 
![screenshot 46](https://user-images.githubusercontent.com/23557479/28316148-3eb882b6-6bdf-11e7-900a-e3e0226bca72.png)

**Comment by vozersky** [comment]
Reproduced with Firefox Nightly for Win, macOS version is fine though
Browser bug, i guess

**Comment by ameshkov** [comment]
Most likely it is

**Comment by veronikasav** [comment]
Unable to adjust any settings.

Adguard AdBlocker beta 2.6.7

<details><summary>Screenshot:</summary>

![screen shot 2017-07-30 at 9 28 19 pm](https://user-images.githubusercontent.com/27292111/28755955-28924aec-756e-11e7-9003-89f46a4015e9.png)

![screen shot 2017-07-30 at 9 28 30 pm](https://user-images.githubusercontent.com/27292111/28755956-2dd98290-756e-11e7-84df-00869faaf727.png)


</details>

**Comment by veronikasav** [comment]
Context menu line and all options into options page disappeared.
(adblocker 2.6.7 for firefox (54.0.1 x64))

<details><summary>Screenshot:</summary>

![screen shot 2017-07-30 at 9 36 04 pm](https://user-images.githubusercontent.com/27292111/28756001-34019f26-756f-11e7-922d-999e1df2d23f.png)

![screen shot 2017-07-30 at 9 36 17 pm](https://user-images.githubusercontent.com/27292111/28756004-3798c3ee-756f-11e7-8cda-e0db58572972.png)

</details>

Ticket ID: 1604018

**Comment by Anoop2609** [comment]
You guys need to fix this problem because many people are start using alternatives including me but i like adgurad so i really want to come back

**Comment by vozersky** [comment]
@Anoop2609 yep, we're on it

**Comment by ameshkov** [comment]
@Anoop2609 this is a bug of FF Nightly, we should simply wait till they fix it

**Comment by The-Commissioner** [comment]
Nightly 57 arriving tomorrow, purely webextensions now.

**Comment by Anoop2609** [comment]
@ameshkov if this is a FF Nightly bug, did you report this on Bugzilla?

**Comment by ameshkov** [comment]
> @ameshkov if this is a FF Nightly bug, did you report this on Bugzilla?

It was reported long time ago, fix should be available soon

**Comment by Anoop2609** [comment]
Fixed

**Comment by The-Commissioner** [comment]
@Anoop2609 Maybe you celebrated too early?

**Comment by ameshkov** [comment]
https://addons.mozilla.org/en-US/firefox/addon/adguard-adblocker/versions/beta

**Comment by The-Commissioner** [comment]
^^Doesn't work, needs workaround.

**Comment by vozersky** [comment]
works fine in 57.0a1

**Comment by The-Commissioner** [comment]
![1.png](http://i.imgur.com/Pjec0v7.png)

**Comment by ameshkov** [comment]
@The-Commissioner 

Cannot confirm with 2.7.1 beta, what are the changes in your Firefox profile configuration comparing to default values?

Was it a clean install or an update?

Tested in Nightly 57.0a1 (2017-09-05) (64-bit)

**Comment by ameshkov** [comment]
Oh, wait, could it be some compatibility issue? What are the other add-ons?

**Comment by The-Commissioner** [comment]
I tested it out on a complete new profile with no changes to any of the firefox settings and like I said since it was a completely new profile, no other addons were installed.
I'm on the nightly update channel rather than the nightly-date update channel, if that makes a difference.
Unless this workaround is applied : https://github.com/AdguardTeam/AdguardBrowserExtension/issues/783#issuecomment-319343177
The options doesn't show and the drop-menu from the address bar is also inaccessible.

Don't bother if it's just me. I already uninstalled because it's unusable,had  just installed it again to counter vozersky's claim.
BTW apart from this issue, the browser extension also needs some quality assessment.

**Comment by zebrum** [comment]
firefox just updated to 55.0.3 and I installed 2.6.7 from store. The same problem on my side

**Comment by vbagirov** [comment]
Is there any link to the Mozilla bug report that should (presumably) get this issue fixed?

**Comment by ameshkov** [comment]
Guys, everything seems okay now.
