### ISSUE TITLE
Implement the sync page

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#790]
Page layout is ready for quite some time already:
https://monosnap.com/file/lwxLJrn5kzgr8MWkBDAOrc8uF0Rpk5

@kaprielov can provide you with the HTML/CSS for these pages.

**Comment by Anoop2609** [comment]
Can you add the local backup feature in the sync page for all setting and filters.

**Comment by ameshkov** [comment]
It'd be better to file a new feature request for this:
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/804
