### ISSUE TITLE
Change the filters updated alert layout

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#791]
Instead of using the old v2.x layout, please switch to a new one:
https://monosnap.com/file/TCL0jBxXVim6vqRkX6MLJoPSxpy5Qf
https://monosnap.com/file/YZnmbFhsIpPtXNMSknvUtNoKsVHQTX

**Comment by Mizzick** [comment]
@kaprielov Do we have the layout html for this?
