### ISSUE TITLE
Statistics tab in the browser action popup

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#794]
In order for this to work extension should record the number of blocked requests per day/hour. 

Reports available:

**Blocked ads**
https://monosnap.com/file/Etl2DFOzz9Pa3fdr60XLHyL0KCB0On

**Request types**
https://monosnap.com/file/vLevZA1evZQG7rDiiYEioRJgw8TsHz

@kaprielov first of all, I need you to prepare the reports layout.

**Comment by danidoedel** [comment]
Using the Apple logo for iOS and an outdated OS X logo for macOS doesn‘t seem like a good decision for me.

**Comment by ameshkov** [comment]
> Using the Apple logo for iOS and an outdated OS X logo for macOS doesn‘t seem like a good decision for me.

Yeah, you're right, we should update them both

**Comment by kaprielov** [comment]
Please add a js lib for the graphs, and I can stylize it.

**Comment by ameshkov** [comment]
@Mizzick http://c3js.org/
http://jsfiddle.net/ha3L5z3b/

**Comment by Mizzick** [comment]
@kaprielov please take a look at the branch 5ab87cd

**Comment by sc0rp10** [comment]
@IldarKamalov can you please take a look to popup's markup?
