### ISSUE TITLE
Firefox: Use jpm instead of cfx

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#8]
https://www.npmjs.com/package/jpm

**Comment by ameshkov** [comment]
It is now a Critical issue. AMO no more allows cfx packed add-ons in.

**Comment by LimboSlam** [comment]
@ameshkov: I believe once this enhancement is implemented, Adguard for Pale Moon will stop functioning. I'm saying this because I recent incident of this happened with another add-on. 

But I'm sure @wolfbeast (our lead developer and founder of Pale Moon) can give a definite answer.

**Comment by atropnikov** [comment]
We can move all files in one directory on extension build. In this case path to script file will be identical for cfx and jpm tools.

**Comment by ameshkov** [comment]
@Mizzick I don't see any changes to the utility.
@LimboSlam we'll check the new build in Pale Moon.

**Comment by ameshkov** [comment]
@atropnikov 
> We can move all files in one directory on extension build. In this case path to script file will be identical for cfx and jpm tools.

Do you mean all JS files? Some files names are ambiguous.

**Comment by ameshkov** [comment]
@Mizzick to fix the issue with resource paths, just change the chrome.manifest to:
```
content   adguard ./data/content/
```

**Comment by ameshkov** [comment]
l18n still does not work though
