### ISSUE TITLE
safari yandex.news.ru hangup

### ISSUE THREAD

**Issue by blahdy** [AdguardTeam/AdguardBrowserExtension#800]
the list of enabled filters is attached. yandex.news hangs when opened - the links are unclickable, but the page is scrollable and refreshable. upon trying to hit a link - the rolling rainbow mouse pointer appears. =0)

safari is 11.0 (12604.1.32) on 10.12.6

**Comment by Alex-302** [comment]
I can't reproduce. Which filters are enabled?

**Comment by ameshkov** [comment]
@blahdy не стесняйтесь писать по-русски, всем будет проще

**Comment by ameshkov** [comment]
Обновленная версия для Сафари ревью прошла вчера или позавчера, наверняка с этим как-то связано

**Comment by blahdy** [comment]
чет скриншот не приклеился. вот список фильтров:
Фильтр раздражителейВерсия 1.0.16.21. Обновлено 28 июля 2017 в 21:02.
Русский фильтрВерсия 1.0.54.68. Обновлено 29 июля 2017 в 14:12.
Экспериментальный фильтрВерсия 1.0.26.65. Обновлено 13 июня 2017 в 16:00.
Упрощенный фильтр доменовВерсия 1.0.1.95. Обновлено 12 июля 2017 в 20:02.
Фильтр для SafariВерсия 1.0.3.53. Обновлено 15 июля 2017 в 19:02.
Fanboy's Social Blocking ListВерсия 1.0.74.28. Обновлено 30 июля 2017 в 00:33.
Fanboy's AnnoyancesВерсия 1.0.74.48. Обновлено 30 июля 2017 в 00:32.
Adblock Warning Removal ListВерсия 1.0.84.70. Обновлено 30 июля 2017 в 00:34.
RU AdListВерсия 1.0.84.69. Обновлено 30 июля 2017 в 00:32.
Anti-Adblock Killer | ReekВерсия 1.0.1.68. Обновлено 2 декабря 2016 в 19:09.
CJX's Annoyance ListВерсия 1.0.1.42. Обновлено 29 июля 2017 в 04:35.
Fanboy Anti-Facebook ListВерсия 1.0.0.13. Обновлено 19 июля 2017 в 16:36.
Fanboy's Enhanced Tracking ListВерсия 1.0.4.76. Обновлено 29 июля 2017 в 16:34.
Peter Lowe's listВерсия 1.0.3.17. Обновлено 28 июля 2017 в 16:33.
PrebakeВерсия 1.0.1.14. Обновлено 5 мая 2016 в 00:04.
RU AdList: BitBlockВерсия 1.0.81.45. Обновлено 30 июля 2017 в 00:34.
RU AdList: CountersВерсия 1.0.81.21. Обновлено 30 июля 2017 в 00:34.
Spam404Версия 1.0.1.97. Обновлено 30 июля 2017 в 00:34.

**Comment by Alex-302** [comment]
@blahdy если выключить все фильтры, тормозит? Попробуйте так же выключить все, кроме нашего русского фильтра, и наоборот - оставить все, кроме русского фильтра.

**Comment by ameshkov** [comment]
Хм, очень много фильтров, а вы в лимит 50000 правил везаете со всеми включенными?

**Comment by blahdy** [comment]
да, в лимит влезаю. дело в вашем русском фильтре. оставив его единственного включенного - начинает залипать и подгружать камень

**Comment by blahdy** [comment]
есть кто живой?

**Comment by ameshkov** [comment]
Хмхм, ну мысли то есть, там видимо правило, которое директ блокирует, конфликтует со скриптами самого яндекса. 

@Alex-302 у тебя не получается повторить?

**Comment by Alex-302** [comment]
Не повторяется.
Кстати старые правила уже убраны, т.к.  дизайн сменился.
Вот такое сейчас:
```
news.yandex.by,news.yandex.com,news.yandex.kz,news.yandex.ru,news.yandex.ua##.page-content__table > div.page-content__col > [class*="stor"][-ext-has='> div[class] > div[class^="title "]:contains(Яндекс.Директ)']
```

**Comment by ameshkov** [comment]
@blahdy до сих пор повторяется?

**Comment by blahdy** [comment]
до сих пор повторяется. 2-3 секунду работает нормально, потом залипает

**Comment by ameshkov** [comment]
@blahdy ну я уж и так и сяк пробую, не получается повторить:(

Нам по ходу очень не хватает экспорта/импорта настроек в расширении, гораздо легче было бы сейчас повторять.

**Comment by blahdy** [comment]
достаточно одного вашего русского списка, все остальные настройки и фильтры отключены кроме оптимизированных. может, на стабильном сафари пробуете? или, может, дело в наличии действующего логина на яндекс? фильтры используются оптимизированные, сафари бетка, адгард тоже бетка. тут, собственно мало чего воспроизводить. может, правда конфликтует с расширением translate, единственное установленное на обоих машинах

**Comment by ameshkov** [comment]
> сафари бетка

Technology preview? 

Я попробую обновиться, а то у меня до сих пор Safari 10.1

**Comment by blahdy** [comment]
не технолоджи превью, а Версия 11.0 Seed 2 ака Версия 11.0 (12604.1.32)

**Comment by ameshkov** [comment]
Да просто мне нужно OS X до беты обновлять, иначе Safari до 11 не обновится

**Comment by blahdy** [comment]
отбой, почистил сафари ониксом и все нормально. простите за беспокойство. keep up the good work

**Comment by blahdy** [comment]
почистил сафари ониксом, сначала нормально отобразилось, но теперь зависает опять

**Comment by ameshkov** [comment]
Давненько ж я мак не обновлял.

> сначала нормально отобразилось, но теперь зависает опять

Как долго пришлось ждать? В инкогнито все ок при этом?

@vozersky можешь посмотреть? У тебя новее сафари.

**Comment by vozersky** [comment]
В Version 11.0 (12604.1.28.2) с указанным набором фильтров не повторяется.

**Comment by blahdy** [comment]
я могу сделать какой-нибудь  дамп для расследования?

**Comment by blahdy** [comment]
комрады?

**Comment by ameshkov** [comment]
Сорян, завалило срочными делами.

У меня такие вопросы:
1. Что происходит в режиме инкогнито? Подвисает ли?
2. Что видно в консоли браузера? Можете ее вытащить?

**Comment by alexxxst** [comment]
Safari - Версия 11.0 (13604.1.38.1.6)
Русский фильтр - Версия 1.0.57.71. Обновлено 3 октября 2017 в 14:00

Фриз повторяется. Повторяется _иногда_ ещё и в результатах поиска. Бесит.
В консоли всё то же самое, как и при отключенном русском фильтре.
В режиме Инкогнито повторить фриз не получается.

<img width="1356" alt="2017-10-03 16 27 13" src="https://user-images.githubusercontent.com/9831551/31127493-c3607398-a857-11e7-9ff7-9dfdbd0fa4a4.png">

**Comment by Alex-302** [comment]
странно. У меня макось в виртуалке, что с Адгардом что без - работает одинаково.
Попробуйте в пользовательский фильтр добавить
```
news.yandex.by,news.yandex.com,news.yandex.kz,news.yandex.ru,news.yandex.ua#@#div.page-content__col > div.widget[-ext-has=" > div[class] > div[id]:contains(Яндекс.Директ)"]
news.yandex.by,news.yandex.com,news.yandex.kz,news.yandex.ru,news.yandex.ua#@#.page-content__table > div.page-content__col > div[class*=" "][data-bem][-ext-has=" > div > div:contains(Яндекс.Директ)"]
news.yandex.by,news.yandex.com,news.yandex.kz,news.yandex.ru,news.yandex.ua#@#.rubric-stories > div.story.story_view_normal.story_noimage[-ext-has=" > div > div:contains(Яндекс.Директ)"]
news.yandex.by,news.yandex.com,news.yandex.kz,news.yandex.ru,news.yandex.ua#@#.page-content__fixed div[class*=" "] > div.story[-ext-has=" > div > div:contains(Яндекс.Директ)"]
news.yandex.by,news.yandex.com,news.yandex.kz,news.yandex.ru,news.yandex.ua#@#.page-content__layout div[class^="page-content__"] > [class][-ext-has='> div[class] > h3 > a[href^="http://news-clck.yandex."]']
news.yandex.by,news.yandex.com,news.yandex.kz,news.yandex.ru,news.yandex.ua#@#.page-content__right > div.page-content__col_pos_top > form.filters_at_search[-ext-has="> div[class] > div[id]:contains(Яндекс.Директ)"]
news.yandex.by,news.yandex.com,news.yandex.kz,news.yandex.ru,news.yandex.ua#@#.page-content__left > div.pager[-ext-has="> div[class] > div[id]:contains(Яндекс.Директ)"]
```

**Comment by alexxxst** [comment]
Ну, вроде как перестала вкладка зависать в новостях.
Но и реклама появилась) А вот в результатах поиска всё по-старому: виснет.

**Comment by Alex-302** [comment]
добавьте ещё эти исключения
```
yandex.by,yandex.ru,yandex.ua#@#.traffic-home-panel-view > div[style*="!important"][-ext-has='div[style*="!important"] > a[href="https://direct.yandex.ru/?partner"]']
yandex.by,yandex.ru,yandex.ua#@#div[data-block="route-panel-content-view"] div[class^="route-panel-content-view__"][-ext-has='div[style$="!important"]>a[href="https://direct.yandex.ru/?partner"]']
yandex.ru,yandex.com,yandex.ua,yandex.kz,yandex.by,yandex.com.tr#@#body[data-bem*="search"] .serp-list .serp-item[-ext-has='.organic__subtitle > [class*="organic_"]:matches-css(background-color: rgb(254, *))']
```
Не понятно, почему у вас тормозит.

**Comment by alexxxst** [comment]
Виснуть перестало. Реклама на месте.

**Comment by Alex-302** [comment]
Значит Apple наоптимизировали) Пока не пробовал 11.
Но объктивно, даже macos 10 от версии к версии медленнее становилась. На виртуалке это ощутимо. Система двухгодичной давности просто летала...

**Comment by vozersky** [comment]
obsolete

**Comment by alexxxst** [comment]
> obsolete

Резво. А починить не судьба?
Опять всё стало зависать, наверное на самом яндексе что-то поменяли.

**Comment by ameshkov** [comment]
> Резво. А починить не судьба?
> Опять всё стало зависать, наверное на самом яндексе что-то поменяли.

Дело в том, что чинить надо не в самом расширении, а в фильтрах.

@Alex-302 посмотришь в сафари?

**Comment by alexxxst** [comment]
> Дело в том, что чинить надо не в самом расширении, а в фильтрах.

Тогда надо линкануть в нужный репо проблему?
Фильтрами же тоже занимаются на гитхабе.

**Comment by ameshkov** [comment]
> Тогда надо линкануть в нужный репо проблему?
> Фильтрами же тоже занимаются на гитхабе.

Я главного по фильтрам меншнул, все под контролем:)

**Comment by alexxxst** [comment]
> Я главного по фильтрам меншнул, все под контролем:)

Спасибо!

**Comment by Alex-302** [comment]
Я не знаю как повторить. У меня макось в виртуалке, работает как и в основной системе.
Тормозить может из-за расширенного CSS.
Исключения для пробы:
```
yandex.ru,yandex.com,yandex.ua,yandex.kz,yandex.by,yandex.com.tr#@#.b-page .main > .container__line > div:has(iframe[src^="data:"])
yandex.ru,yandex.com,yandex.ua,yandex.kz,yandex.by,yandex.com.tr#@#.b-page .main > .container__line > div:has(a[href*="morda"] > img[src*="morda"])
yandex.ru#@#body[data-bem*="search"] div.content__left > ul.serp-list.serp-list_left_yes > li.serp-item[-ext-has=">div[class] > div.organic__subtitle > div.label_color_yellow:contains(реклама)"]
news.yandex.by,news.yandex.com,news.yandex.kz,news.yandex.ru,news.yandex.ua#@#div.page-content__col > div.widget[-ext-has=" > div[class] > div[id]:contains(Яндекс.Директ)"]
news.yandex.by,news.yandex.com,news.yandex.kz,news.yandex.ru,news.yandex.ua#@#.page-content__table > div.page-content__col > div[class*=" "][data-bem][-ext-has=" > div > div:contains(Яндекс.Директ)"]
news.yandex.by,news.yandex.com,news.yandex.kz,news.yandex.ru,news.yandex.ua#@#.rubric-stories > div.story.story_view_normal.story_noimage[-ext-has=" > div > div:contains(Яндекс.Директ)"]
news.yandex.by,news.yandex.com,news.yandex.kz,news.yandex.ru,news.yandex.ua#@#.page-content__fixed div[class*=" "] > div.story[-ext-has=" > div > div:contains(Яндекс.Директ)"]
news.yandex.by,news.yandex.com,news.yandex.kz,news.yandex.ru,news.yandex.ua#@#.page-content__layout div[class^="page-content__"] > [class][-ext-has='> div[class] > h3 > a[href^="http://news-clck.yandex."]']
news.yandex.by,news.yandex.com,news.yandex.kz,news.yandex.ru,news.yandex.ua#@#.page-content__right > div.page-content__col_pos_top > form.filters_at_search[-ext-has="> div[class] > div[id]:contains(Яндекс.Директ)"]
news.yandex.by,news.yandex.com,news.yandex.kz,news.yandex.ru,news.yandex.ua#@#.page-content__left > div.pager[-ext-has="> div[class] > div[id]:contains(Яндекс.Директ)"]
mail.yandex.ru,mail.yandex.by,mail.yandex.ua,mail.yandex.kz#@#div[class*="mail-Layout-Aside-Inner"] div.b-teaser+div.ns-view-left-box > div.ns-view-folders[-ext-has='> a[href="#inbox"]']:matches-css(min-height: *246px)
yandex.ru,yandex.com,yandex.ua,yandex.kz,yandex.by#@$#.main__content .serp-list > .serp-adv-item:contains(реклама) { position: absolute!important; left: -3000px!important; }
yandex.by,yandex.ru,yandex.ua#@#body._map_ready div.sidebar-panel-view  div.home-panel-content-view__body div.search-catalog-item-view:has(> ._type_branding)
yandex.ru,yandex.ua#@#.route-panel-content-view__body > div.route-panel-content-view__bla-bla-car-banner-layout+div[class]:last-child
yandex.by,yandex.ru,yandex.ua#@#.traffic-home-panel-view > div[style*="!important"][-ext-has='div[style*="!important"] > a[href="https://direct.yandex.ru/?partner"]']
yandex.by,yandex.ru,yandex.ua#@#div[data-block="route-panel-content-view"] div[class^="route-panel-content-view__"][-ext-has='div[style$="!important"]>a[href="https://direct.yandex.ru/?partner"]']
```

**Comment by Alex-302** [comment]
Добавил к правилам для главного домена `~news.yandex.by,~news.yandex.com,~news.yandex.kz,~news.yandex.ru,~news.yandex.ua`, возможно станет получше.
