### ISSUE TITLE
Extension blocks Avira search engine

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardBrowserExtension#801]
Adguard Extension (2.6.7) blocks the website:
https://search.avira.com/#/web/result?q=iphone+7&engine=1&source=homepage
when disabling extension everything works fine

<details><summary>Screenshot(Extension enabled):</summary>

![screen shot 2017-07-28 at 10 25 22 pm](https://user-images.githubusercontent.com/28784344/28733232-c366a0fe-73e3-11e7-83f6-68eb093c77f1.png)

</details>

<details><summary>Screenshot(Extension disabled) :</summary>

![screen shot 2017-07-28 at 10 25 43 pm](https://user-images.githubusercontent.com/28784344/28733242-d2e5959e-73e3-11e7-9746-f3719dec956b.png)

</details>

### Your environment

* Adguard Extension (2.6.7)
* Chrome 
* English filterVersion 1.1.25.96. Updated 26 july 2017 at 23:00.
Spyware filterVersion 1.0.13.48. Updated 26 july 2017 at 19:00.
Social media filterVersion 1.0.21.58. Updated 26 july 2017 at 22:00.
Annoyances filterVersion 1.0.16.5. Updated 26 july 2017 at 23:02.
Russian filterVersion 1.0.54.54. Updated 25 july 2017 at 18:48.
German filterVersion 1.0.35.81. Updated 26 july 2017 at 14:01.
Experimental filterVersion 1.0.26.65. Updated 13 june 2017 at 16:00.
Mobile Ads filterVersion 1.0.9.10. Updated 26 july 2017 at 13:01.

**Comment by ameshkov** [comment]
This is a filters issue, caused by blocking `inspsearchapi.com` domain.

@AdguardTeam/filters-maintainers guys please take care of it.

**Comment by ypetruk** [comment]
The comment from the customer:
Your support is very much appreciated. Unfortunately, the behavior is not entirely as expected. The useful ads are not being displayed on search.avira.com when the feature "Protection on this website" activated.

Please find attached the print screen for the following 3 scenarios:

1. On google.de the ads are being displayed with the feature "Protection on this website" activated.
<details><summary>Screenshot:</summary>

<img width="1437" alt="google - adguard on" src="https://user-images.githubusercontent.com/28784344/29236992-72516be6-7f1d-11e7-82e1-f5cba245bd42.png">


</details>

2. On search.avira.com the ads are not being displayed when the feature "Protection on this website" is activated.

<details><summary>Screenshot:</summary>

<img width="1437" alt="safesearch - adguard on 1" src="https://user-images.githubusercontent.com/28784344/29237007-c016c308-7f1d-11e7-8e9a-5e1be60c081e.png">

</details>

3. However, on search.avira.com the ads are being displayed when the feature "Protection on this website" is deactivated.

<details><summary>Screenshot:</summary>

<img width="1437" alt="safesearch - adguard off 1" src="https://user-images.githubusercontent.com/28784344/29237009-d0cc463c-7f1d-11e7-97fd-43dffa029637.png">

</details>

Google URL:
https://goo.gl/QsdDJa

SafeSearch URL:
https://search.avira.com/#/web/result?q=samsung+galaxy+tablet&source=homepage&engine=1

**Comment by ameshkov** [comment]
@Alex-302 could you please take care of it?

**Comment by ameshkov** [comment]
Ah, nevermind, done:
https://github.com/AdguardTeam/AdguardFilters/commit/4cc1a19759e9d903cf444bd069de301c28bc7596
