### ISSUE TITLE
Block Script Manually

### ISSUE THREAD

**Issue by Anoop2609** [AdguardTeam/AdguardBrowserExtension#803]
Can you give us the ability to block script on any web page like ublock origin is doing, Currently i am using ublock because adguard is not working on Firefox nightly 56 and they offer too many customization and features. Some feature are really good like popup blocking , remote font block, script blocking and adding filters from url as i am using adgurad filters in ublock simply visiting https://filterlists.com/ and clicking add
![screenshot 47](https://user-images.githubusercontent.com/23557479/28783680-b48444e0-762e-11e7-92c4-0e2fde61fb4c.png)

**Comment by ameshkov** [comment]
Let's have separate feature requests for each of them.

* popup blocking -- what exactly do you mean?
* remote font block -- possible, quite easy to do.
* script blocking -- how does it look like?
* filterlists -- https://github.com/AdguardTeam/AdguardBrowserExtension/issues/805

**Comment by Anoop2609** [comment]
popup blocking 
![screenshot 49](https://user-images.githubusercontent.com/23557479/28791445-2259f9ae-764a-11e7-9407-58945f3e0281.png)
script blocking 
![screenshot 51 _li](https://user-images.githubusercontent.com/23557479/28791556-7e4ed248-764a-11e7-8a43-26824d5d9c15.jpg)

**Comment by ameshkov** [comment]
Filed a separate issue about it:
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/806
