### ISSUE TITLE
Adguard 2.6.7 in AMO

### ISSUE THREAD

**Issue by Alain1978** [AdguardTeam/AdguardBrowserExtension#807]
Hello, Adguard has been updated in AMO to version 2.6.7 but this version is not compatible with Firefox 57 that's mean it's not a webextention. I'm surprise because you anounced that the version of adguard would be an webextension to version 2.6.5. So what's happened ? Thanks for your answer.
![adguard](https://user-images.githubusercontent.com/18900339/28847557-f4908634-770f-11e7-8549-bf77ead51e04.jpg)

**Comment by ameshkov** [comment]
It is an "embedded webextension", which is a necessary intermediate stage before the full transfer. 

Basically, it is a webextension wrapped into a legacy bootstrapped extension. The only purpose of that wrapper is to migrate existing settings into the wrapped webextension. Once all the users are upgraded to v2.6, we'll be able to ditch the wrapper part.
