### ISSUE TITLE
Extension fails to detect the desktop program

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#812]
Source:
https://github.com/AdguardTeam/AdguardForWindows/issues/1876

### Steps to reproduce

1. Install AG extension to Chrome and AG desktop program
2. Restart the Chrome browser
3. Navigate to facebook.com (or wp.pl)

You may need to repeat 2-3 a couple of times.

### Expected behavior
Extension icon becomes blue and it starts working in the integration mode.

### Actual behavior
The extension does not detect the desktop AG.

### Your environment

* Adguard AdBlocker extension version: 2.6.7
* Environment name and version: Chrome Dev 62 (should be reproducible in older Chrome as well)

**Comment by atropnikov** [comment]
`wp.pl` site uses `ServiceWorker` cache to cache its content, that's why the extension isn't able to intercept HTTP response headers.

**Comment by ameshkov** [comment]
Will be solved automatically once we start using WS api
