### ISSUE TITLE
http://tudotv.tv/ - Ad leftover

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardBrowserExtension#814]
***Description***:
* **Current behaviour**: 

Ad leftover on http://tudotv.tv/assist-londrina-x-vil-nova-ao-vivo-gratis-em-hd-07-08-2017/
Reproduced on our side (Mac OS)

<details><summary>Screenshot:</summary>

![screen shot 2017-08-09 at 12 33 34 am](https://user-images.githubusercontent.com/28784344/29095675-690308f4-7c9a-11e7-975e-14d2e1c408ac.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | Chrome
Adguard version: | 1.4.1.
Adguard DNS: | None 
Adguard filters: | 0,1,2,3,4,11,14
Ticket ID (if exists): | 1476762
Active filters: English, spyware, annoyances, Spanish / Portuguese, adblock alert installed, anti-adblock, malware and spam.
Other functions ACTIVATES: protection against phishing and malware And activate the most appropriate filters automatically

**Comment by vozersky** [comment]
Issue moved to [AdguardTeam/AdguardFilters #6081](https://github.com/AdguardTeam/AdguardFilters/issues/6081) via [**ZenHub**](https://www.zenhub.com/)
