### ISSUE TITLE
exclusions schema mark

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardBrowserExtension#815]
Why Adguard Chrome Extensions using this `//` instead of `||` :
```
@@//example.com$script
```

Adguard For Windows Create Exclusions in this VALID schema:
```
@@||example.com$script
```

**Comment by ameshkov** [comment]
Talking about filtering log?

**Comment by FadeMind** [comment]
See Adding exlusion for gmail via Adguard Chrome Extension (from Google Chrome Store)
![image-20170813-009](https://user-images.githubusercontent.com/9846948/29252771-b6e988be-806d-11e7-96dc-9b16555737e5.png)

**Comment by ameshkov** [comment]
Ah, got it. That's intentional -- so that when you disable AG for a website, you didn't disable it for the website's subdomains

**Comment by ameshkov** [comment]
Extension does the same when you disable filtering of a website
