### ISSUE TITLE
https://ok.ru - the extension interrupts videos on the site

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardBrowserExtension#817]
При просмотре видео в одноклассниках, сайт зависает на последней секунде видео, методом тыка вычислил что при выключенном адгуарде видео показывает нормально, зависание не наблюдается, такое ощущение что блокируется адобе флеш плеер.

Фильтры поочередно включал и выключал, причина не выявилась, других расширений блокируюших рекламу и прочее не установленно, хотя видно что влияет на просмотр видео ваш Adguard, в режиме инкогнито тоже не помогло, на данной ссылке видно что на другом компьютере расширение так же тормозит видео в одноклассниках тоже в Chrome.

### Steps to reproduce

1. Зайти на https://ok.ru
2. Найти видео и попытаться проиграть
3. Видео "томозит" и прерывыается на последних  секундах

### Your environment

* Adguard AdBlocker extension version: 2.6.7
* Environment name and version: Windows, Chrome 60
* Filters you use in Adguard: Russian
* Any other browser extensions you have installed: no extensions,  the customer managed to reproduce on another laptop with Chrome and the extension
* ID 1608902

**Comment by ameshkov** [comment]
@evgeniy-ADG а у тебя повторяется?

**Comment by kudrik34** [comment]
пришлось установить полную версию адгуард, данную проблему он решает , но вот рекламу на ок.ру не блокирует ( странно) , на ютубе нашел выход решения проблемы с браузерным расширением адгуард, сделал как здесь https://www.youtube.com/watch?v=UkIAU2MAAck&index=1&list=LLMH8LWJIKqv8-xBzRT-EM8Q и теперь расширение не не тормозит видео в оках, полную версии удалил.

**Comment by Mizzick** [comment]
Cannot reproduce
