### ISSUE TITLE
Fonts in adguard-extension settings menu are broken in PaleMoon

### ISSUE THREAD

**Issue by gshumihin** [AdguardTeam/AdguardBrowserExtension#82]
![](http://content.screencast.com/users/shumegor/folders/Jing/media/150df5e3-0acc-439f-85aa-cc364e682919/00000700.png)
Normal view only on 120% scale
![](http://content.screencast.com/users/shumegor/folders/Jing/media/b42b8cd0-cf77-4fbf-bab6-fb399c9b5b0c/00000701.png)

**Comment by ameshkov** [comment]
In fact I think it's just how it scales fonts, nothing to fix there
