### ISSUE TITLE
avtoto.ru - Blocking issues - Bug

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardBrowserExtension#822]
Adguard blocks the search engine on the website avtoto.ru
https://eve-tools.ru/file/clip2ftp/5b84a58f-ff3e-41f9-ab82-ae744bd6684f.jpg
by using the rule http://eve-tools.ru/file/clip2ftp/45439d65-d5fb-4a8f-92bc-00fb8a9e4621.jpg 

Can`t reproduce it on my side

**Comment by vozersky** [comment]
invalid repo
filters? browser? ext. version?
