### ISSUE TITLE
Enhance styles protection

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#829]
### Steps to reproduce

Visit
http://chatovod.ru/chats/ 
http://chatovod.ru/

The rules:
```
1)
chatovod.ru##.chatlist > tbody > tr[class="bold"]:not([class^="chatitem"])
2)
chatovod.ru##object#\32 40x400
```

### Expected behavior
Selected elements are hidden

### Actual behavior
1. 

Screenshot:

<details>

![image](http://imagizer.imageshack.com/img923/8881/yhSksw.png)
</details>

2.

Screenshot:

<details>

![image](http://imagizer.imageshack.com/img924/1803/FzPXTl.png)
</details>

Caused by:

<details>

```

<script type="text/javascript">
    (function() {
            try {
                    var shadowRoot = $("html").get(0).shadowRoot;
                    if (shadowRoot) {
                            for(var i=0;i<shadowRoot.styleSheets.length;i++) {
                                    var sheet = shadowRoot.styleSheets[i];
                                    var cnt = sheet.cssRules.length;
                                    while(cnt-- > 0) sheet.deleteRule(0);
                                    }
                            }
                    } catch(e) {
                    if (window.console && window.console.log) console.log(e);
                    }
            })();
</script>

```

</details>

### Your environment
* Extension: 2.6.7
* Chrome 59

**Comment by atropnikov** [comment]
Did you read the issue description? This couldn't work because they remove CSS rules from the shadow DOM. We should protect CSS rules from removal.

```javascript
<script type="text/javascript">
    (function() {
            try {
                    var shadowRoot = $("html").get(0).shadowRoot;
                    if (shadowRoot) {
                            for(var i=0;i<shadowRoot.styleSheets.length;i++) {
                                    var sheet = shadowRoot.styleSheets[i];
                                    var cnt = sheet.cssRules.length;
                                    while(cnt-- > 0) sheet.deleteRule(0);
                                    }
                            }
                    } catch(e) {
                    if (window.console && window.console.log) console.log(e);
                    }
            })();
</script>
```

**Comment by Mizzick** [comment]
How can I understand this from this description?

**Comment by atropnikov** [comment]
It contains an example of script that removes CSS rules.

**Comment by Mizzick** [comment]
It should be described properly then

**Comment by Mizzick** [comment]
Actually we do have a protection, but it doesn't work in this case.

**Comment by ameshkov** [comment]
Frankly, I guess we shouldn't care about it, there's no way we protect from everything. @Alex-302 just use ExtCss.

**Comment by Mizzick** [comment]
The problem is that MutationObeserver doesn't intercept those changes. I think it will soon.
Otherwise it's a working solution to dismiss our styles.

**Comment by ameshkov** [comment]
> The problem is that MutationObeserver doesn't intercept those changes. I think it will soon.
> Otherwise it's a working solution to dismiss our styles.

You can easily overcome it by overriding `prototype.deleteRule` function. You can also override `disabled` property and such.

**Comment by ameshkov** [comment]
Actually let's reopen it, it might be useful

**Comment by Alex-302** [comment]
@Mizzick could you please check protection on this site?
http://fastpic.ru/view/77/2016/0814/_2ead2ca72789ae01434f529a8fa57eaa.png.html
In Chrome - with `@@||fastpic.ru^$jsinject` exclusion.
In FF with
```
fastpic.ru#@##brndfooter[-ext-has="> div"]
fastpic.ru#@##left-bottom[-ext-has="> div"]
fastpic.ru#@##left2[-ext-has="> div"]
fastpic.ru#@#div#content[-ext-has="> div"] > iframe:not([src])
fastpic.ru#@$##content[-ext-has="> div"] { top:0px!important; }
fastpic.ru#@$#body[-ext-has="> div"] { background: none!important; cursor: default!important; background: #ffffff!important; }
fastpic.ru#@$#html[-ext-has="> body"] { background: none!important; cursor: default!important; background: #ffffff!important; }
```

**Comment by Alex-302** [comment]
https://dni.ru/
element hiding is not working after visiting few articles. AdGuard  2.7.2 last beta.
```
dni.ru##div[id^="adfox_"]
dni.ru##.container__partners
dni.ru##div[id^="yandex_rtb_"]
dni.ru##.banner-240x400
dni.ru##.article__anons+div.sotial
```
http://imagizer.imageshack.com/img922/748/WIFqSe.png
