### ISSUE TITLE
Increment "blocked items" counter every time

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#83]
Now we have a workaround: 
1. Do not increase it over 99 (in FF) or 999 (in Chrome).
2. Do not increase it after 30 secs since page has been loaded

Instead do the following:
1. Increase it every time until it hits 100 for FF or 1000 for Chrome
2. When it's done, change counter text to "infinity symbol":
∞
U+221E

**Comment by Mizzick** [comment]
Fixed
