### ISSUE TITLE
Print applied element hiding and CSS rules to filtering log

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#830]
It is extremely useful when creating anti-adblock rules and fixing incorrect blocking.
At the moment I use another ad blocker for these purposes.

* [x] The way `buildCssHits` is called -- it reacts on `collectHitsCount` setting. We should introduce a new property instead, the one that will be aware of the filtering log status and of the setting state.
* [x] Start using the `filteringLog.addCosmeticEvent` when it is appropriate.
* [x] Make sure that user filter rules make to the filtering log.
* [x] Extend `CssHitsCounter` callback with the element data.
* [x] Add `Element` column to the filtering log (and modify `filteringLog.addCosmeticEvent` function as well).
* [x] Fix the cosmetic event details dialog: open in new tab, "unblock".
* [x] Extend cssHits to the injection rules (`example.org#$#div { background: #000; }`).
* [x] Make `CssHitsCounter` handle mutations.

**Comment by The-Commissioner** [comment]
This is a very old but important feature request, which I have been asking for since first testing of v5.9. But everytime it has fallen to deaf ears. Let's hope you making a request makes a difference this time.
BTW if it is successfully resolved, it needs to be ported to the Windows repository as well.

**Comment by maximtop** [comment]
How to be with a bunch of rules like "~sinoptik.ua###SinoptikInformer" or "~blogs.mediapart.fr##.cookie-warn"?

**Comment by ameshkov** [comment]
M?

**Comment by maximtop** [comment]
To test this issue you should have cosmetic or hiding hiding css rule. 
For example:
```example.com#$#body { background-color: #333!important; }```
or
```example.com###elementId```
Open filtering log
Press Refresh page button
After a while you should see which element was blocked by this rule if there was such element on the page
