### ISSUE TITLE
Cannot install extention. Help appreciated.

### ISSUE THREAD

**Issue by erichilton1987** [AdguardTeam/AdguardBrowserExtension#831]
I have used the Adguard extension on Microsoft Edge in the past with no issues.  However, now when I attempt to install the extension I get "The app encountered an error. Please reinstall to repair it." When I click "reinstall" it gives the same error. 
I do not have any other extensions installed.  I have cleared out all cookies/cache and nothing seems to help. I have also re installed Windows recently (due to a separate issue) and attempted to install the extension and I get the same error.
Any help to get this extension installed and working will be very much appreciated.  

Windows 10 x64 Pro edition
Dell XPS 8700 
![untitled](https://user-images.githubusercontent.com/31174696/29492171-068dff62-8541-11e7-8ad5-a604492d6c3f.png)

**Comment by vozersky** [comment]
Can't reproduce.
@erichilton1987  do you still experience the issue? Could be some temporary MS Store problems
