### ISSUE TITLE
FF add-on fails to properly detect the request type

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#832]
### Steps to reproduce

1. Add this rule to the user filter: `||r29static.com^$~image,~stylesheet,~script`
2. Open http://www.refinery29.com/2017/03/146730/trolling-definition-internet-troll-mean-comments
3. The first time the page loads okay, no images are blocked
4. Refresh the page

### Expected behavior
The [main image](http://s1.r29static.com//bin/entry/b06/680x816/1768153/image.png) is loaded okay:
https://monosnap.com/file/sU29RxzIVE7mpR2zptN1xRmJHPLWv6

### Actual behavior
The main image is blocked:
https://monosnap.com/file/MfRBR6IhI26fgRpUl3zycLA1kj77C8

In the filtering log request type is detected as "Other" instead of "Image"

### Your environment

* Adguard AdBlocker extension version: 2.7.0 beta
* Environment name and version: FF 56b3
* Filters you use in Adguard: default set of filters
* Any other browser extensions you have installed: none

**Comment by The-Commissioner** [comment]
This is the result after I specifically asked for the contents not to be copied in **any way**.

> No part of this post can be used anywhere(or be linked to), in any form, without prior permission.

It can't be such a coincidence that you added the same user filter and browsed the same site and the same article as was originally posted by me.

**Comment by ameshkov** [comment]
Sure, updated the issue text

**Comment by Mizzick** [comment]
Reproduced with FF 56.0b6

**Comment by Mizzick** [comment]
<img width="947" alt="screenshot 2017-08-28 14 21 11" src="https://user-images.githubusercontent.com/13855288/29771387-2b23a9fa-8bfc-11e7-8d2a-80fbd00c530f.png">
Appears to be a browser bug, any "image" request is followed by the "other" request

**Comment by ameshkov** [comment]
`onBeforeRequest`?

**Comment by Mizzick** [comment]
Yeap

**Comment by ameshkov** [comment]
Report it to https://bugzilla.mozilla.org/

**Comment by Mizzick** [comment]
Fixed
