### ISSUE TITLE
Saavn.com is not working

### ISSUE THREAD

**Issue by Anoop2609** [AdguardTeam/AdguardBrowserExtension#833]
### Steps to reproduce

1.Goto https://www.saavn.com/
2.Try to play any song 
3.Unable to play any song or list of songs

### Expected behavior
Play song and list of songs smoothly
### Actual behavior

<details><summary>Screenshot:</summary>

</details>

<details><summary>Screenshot of the browser console:</summary>

</details>

### Your environment

* Adguard AdBlocker extension version: 2.7.0 beta
* Environment name and version: FF Nightly 57
* Filters you use in Adguard: English filter, Spyware filter, Social media filter, Annoyances filter, EasyPrivacy,  Fanboy's Annoyances, Fanboy's Enhanced Tracking List
* Any other browser extensions you have installed: Disconnect

**Comment by vozersky** [comment]
Issue moved to [AdguardTeam/AdguardFilters #6458](https://github.com/AdguardTeam/AdguardFilters/issues/6458) via [**ZenHub**](https://www.zenhub.com/)

**Comment by vozersky** [comment]
Moved to AdguardFilters
