### ISSUE TITLE
doesn't work on ebay

### ISSUE THREAD

**Issue by GianniGi** [AdguardTeam/AdguardBrowserExtension#834]
### Steps to reproduce

1. visit ebay.com
2. click product urls, or place bid buttons, or watch buttons
3. clicking does nothing
4.

### Expected behavior

most urls aren't clickable, most actions are disabled (placing bids etc)

### Your environment

* Adguard AdBlocker extension version: 
adblocker 2.6.7

* Environment name and version: (e.g. Chrome 59.0.3071.115)
firefox 54.0.1

* Filters you use in Adguard:
* Any other browser extensions you have installed:

**Comment by vitalkanev** [comment]
Please completly fill the template, including filters, screenshots and *actual* things

**Comment by GianniGi** [comment]
where do I find the filters?

what actual things do you want me to write, more than what I've written?

**Comment by vozersky** [comment]
Can't reproduce, please check you filters in Adguard's settings and try deleting everything from the user filter. If you still experience the issue, please report here https://github.com/AdguardTeam/AdguardFilters/issues
