### ISSUE TITLE
self-promotion ads are skip 

### ISSUE THREAD

**Issue by Anoop2609** [AdguardTeam/AdguardBrowserExtension#835]
In YouTube videos adguard start skipping ads like "subscribe to channel" and recommendation to other videos. 
https://www.youtube.com/watch?v=jj_vTGH3Ujk   In this video 5:38 there are ads which are blocked when I was using an old version of adguard with same filters and Allow search ads and websites' self-promotion is OFF. 
Is this filter error or extension? 
There are the same type of ads skip in other videos. I will submit more link in future.

### Expected behavior

Complete block of all type of ads.
### Actual behavior

It looks like self-promotion ads are showing

<details><summary>Screenshot:
![screenshot 3](https://user-images.githubusercontent.com/23557479/29743673-2db43502-8ab4-11e7-9231-ffe7adaa9676.png)
</summary>

</details>

<details><summary>Screenshot of the browser console:
![screenshot 4](https://user-images.githubusercontent.com/23557479/29743678-473fccca-8ab4-11e7-87ae-6e4674b2f8a1.png)
</summary>

</details>

### Your environment

* Adguard AdBlocker extension version: 2.7.0 beta
* Environment name and version: Nightly FF 57 
* Filters you use in Adguard : English filter, Spyware filter, Social media filter, Annoyances filter, EasyPrivacy, Fanboy's Annoyances
* Any other browser extensions you have installed: NO

**Comment by XX-J** [comment]
Try add this rule:
`/annotations`

**Comment by Anoop2609** [comment]
But this is temporary fix and i am more interested in why this happen and how to fix this without adding /annotations.

**Comment by XX-J** [comment]
Annotations is NOT Advertising. Therefore Adguard NOT blocking Annotations on default.

**Comment by ameshkov** [comment]
@altokarev 
There is an "Annoyances filter" which blocks YT annotations as well.

**Comment by Anoop2609** [comment]
No, Annoyances filter did not fix this thing

**Comment by ameshkov** [comment]
@Alex-302 
Why there's no YT annotations rule in the annoyances filter?
`||youtube.com/annotations_`
