### ISSUE TITLE
Add the ability to block a whole page

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#837]
Browser extension can't stop redirections. For example:

<details>

![image](https://user-images.githubusercontent.com/8361299/29818452-1012c492-8cc5-11e7-994d-9c308655bc4b.png)

</details>

`$empty` modifier can't block it.

uBO has an option for blocking a whole page:
https://github.com/gorhill/uBlock/wiki/Strict-blocking

**Comment by krystian3w** [comment]
https://github.com/PolishFiltersTeam/KAD/issues/905

**Comment by ameshkov** [comment]
Additional details:
https://github.com/AdguardTeam/CoreLibs/issues/152

1. [ ] Allow using `$document` modifier for blacklist rules (applied to `DOCUMENT` resources only);
2. [ ] When a rule has `$document` modifier, redirect the request to a "blocking page";
3. [ ] Take blocking pages layout from the `projects/EXTENSIONS/repos/blocking-pages/browse` project
4. [ ] Update the safebrowsing blocking page layout as well
