### ISSUE TITLE
Test Windscribe compatibility

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardBrowserExtension#841]
Reported by user in FB:
>I am using both the adguard browser extension and windscribe extension for chrome and I sometimes notice a conflict issue between the two extensions.

### Steps to reproduce

1. Install Windscribe: https://chrome.google.com/webstore/detail/windscribe-free-vpn-and-a/hnmpcagpplmpfojmgmnngilcnanddlhb?hl=en
2. Run it with Adguard extension at the same time.

### Expected behavior

Both extensions work at the same time.

### Actual behavior

Can't reproduce it on a steady basis. User's screenshot:
![image](https://user-images.githubusercontent.com/14153331/29964865-2ea59b2c-8f14-11e7-8944-3a3986b80e16.png)

</details>

### Your environment

* Adguard AdBlocker extension version: 2.6.7

**Comment by ameshkov** [comment]
That's okay, everything should work okay
