### ISSUE TITLE
Compatibility to ghostery

### ISSUE THREAD

**Issue by Sparki2002** [AdguardTeam/AdguardBrowserExtension#842]
Hi, i'm using chrome 60.0.3112.113 with adguard 2.6.7 and ghostery 7.3.3.7.

Sometimes I'm getting this error:
`This extension failed to redirect a network request to data:, because another extension (Ghostery) redirected it to data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACklEQVR4nGMAAQAABQABDQottAAAAABJRU5ErkJggg==.`

**Comment by vozersky** [comment]
hi! 
both extensions execute similar functions, so, basically, the one who gets the request first - wins
