### ISSUE TITLE
Adguard Browser and uBlock Origin

### ISSUE THREAD

**Issue by Borglup69** [AdguardTeam/AdguardBrowserExtension#843]
Please, you can make the interface look like to that of uBlock Origin?

https://raw.githubusercontent.com/gorhill/uBlock/master/doc/img/df-qg-10.png

Thanks!

**Comment by Anoop2609** [comment]
Adguard team is already working on a new interface which will release in version 3 and you will find that new interface is much better than current ublock interface.

The new ideas are always welcome!

**Comment by vozersky** [comment]
@Borglup69 hi! I would really appreciate if you could elaborate a little bit more and tell me what exactly do you want to change in Adguard's interface :)

**Comment by ameshkov** [comment]
Guys, I am all for the feature requests, but they should be much more specific:)
