### ISSUE TITLE
Links doesn't react

### ISSUE THREAD

**Issue by Ronln** [AdguardTeam/AdguardBrowserExtension#844]
### Steps to reproduce

1. click on link "open in new not active tab"
2. links are not react any more
3.
4.

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

<details><summary>Screenshot of the browser console:</summary>

</details>

### Your environment

* Adguard AdBlocker extension version: 2.7.1
* Environment name and version: FireFox 55.0.3 (64-bit)
* Filters you use in Adguard: default
* Any other browser extensions you have installed: Frigate 2.2.1.1 , Adblock Plus 2.9.1 , Element Hiding Helper для Adblock Plus 1.4

**Comment by vozersky** [comment]
@Ronln hi! didn't really get those steps, are you talking about some specific website?

**Comment by Ronln** [comment]
Try at hd-bit.org

**Comment by zebrum** [comment]
can not reproduce. I'am on the latest firefox beta and AdGuard 2.7.1
What is Frigate? Can't find it in firefox store

**Comment by zebrum** [comment]
still can't reproduce neither on mac nor windows.

**Comment by zebrum** [comment]
@Ronln try to turn off all other addons in firefox and check if the issue persists.

**Comment by Ronln** [comment]
Yes it's persists
perhaps it's cuz of .ru localization
It's not only my issue some ppl complain about it on official forums https://forum.adguard.com/index.php?threads/После-захода-на-korrespondent-net-первое-открытие-другого-сайта-не-срабатывает.24110/

**Comment by zebrum** [comment]
@Ronln can you please reinstall AdGuard browser extension?
let's check with fresh install and defaults settings.

**Comment by Ronln** [comment]
i installed FF and Adguard in fresh new win10 with addons i mention before and seems everything works fine...

**Comment by Ronln** [comment]
I've found problem it's Kaspersky Protection extension it's impossible shut off or delete so i've deleted path of dword light_plugin_*** at HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Mozilla\Firefox\Extensions

**Comment by Ronln** [comment]
anyway if i use ABP Plus i don't have that issue

**Comment by zebrum** [comment]
remind me please what is your windows version?

**Comment by Ronln** [comment]
Win10 1607  14393.1715

**Comment by zebrum** [comment]
@Ronln can you please check the issue with [this](https://github.com/AdguardTeam/AdguardBrowserExtension/releases/download/v2.7.2/firefox-legacy-beta-2.7.2.xpi) extension's version?

**Comment by zebrum** [comment]
user from forum thread confirmed that there is no issue with legacy version

**Comment by Ronln** [comment]
Yes everything works fine.
Thank you.
