### ISSUE TITLE
Ability to disable WebRTC in Firefox

### ISSUE THREAD

**Issue by Anoop2609** [AdguardTeam/AdguardBrowserExtension#846]
Firefox's WebExtensions API support the complete disabling of WebRTC. Make this option available to user. 
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/privacy/network#Properties

**Comment by The-Commissioner** [comment]
about:config

> media.peerconnection.enabled;false
> media.peerconnection.turn.disable;true

**Comment by Anoop2609** [comment]
@The-Commissioner I know but i want in adguard as feature for those who don't use about:config.

**Comment by The-Commissioner** [comment]
@Anoop2609 are you using uBlock or Adguard in your nightly now? or both in different profiles?

**Comment by The-Commissioner** [comment]
Hmmm, is adguard working for you? In mine, the checkboxes are blanked in the options screen.
Are you using the workaround of disabling remote webextensions to make adguard work?

**Comment by Anoop2609** [comment]
yes, there is some issues with adguard and extensions.webextensions.remote=false in my config but this issue is taking care in #783. Can we talk about this in #783? Taking about this in issue make confusions

**Comment by BooBerry** [comment]
What does uBlock Origin do to disable WebRTC? I'm guessing it sets media.peerconnection.enabled and media.peerconnection.turn.disable like AFAIK it sets Chrome flags in Chrome to disable WebRTC?

IMO, it's worth adding as an option. But you *should* be able to disable WebRTC by adding this filter rule to the user filter;

`#%#window.webkitRTCPeerConnection = undefined; window.mozRTCPeerConnection = undefined; navigator.mozGetUserMedia = undefined; navigator.webkitGetUserMedia = undefined; window.MediaStreamTrack = undefined; window.AudioContext = undefined; window.webkitAudioContext = undefined; window.RTCPeerConnection = function() {};`

**Comment by The-Commissioner** [comment]
@BooBerry I think they should do something extra. I mean ofcourse something like disable WebRTC option but what about other people who use webrtc feature. AFAIK, either vivaldi or opera has a feature known as "hide IP while using webrtc", that would be interesting as a subcategory. That would actually be a good feature provided above what can already be done in the browser.

**Comment by BooBerry** [comment]
Edge also has the "hide IP while using WebRTC" option in about:flags

**Comment by yfdyh000** [comment]
> What does uBlock Origin do to disable WebRTC?

`media.peerconnection.ice.no_host` in Firefox.
https://github.com/gorhill/uBlock/blob/b429e1c7bad8d891f83f9f282a8406952caedbcd/platform/firefox/vapi-background.js#L274

**Comment by The-Commissioner** [comment]
@yfdyh000 So firefox also has a Hide IP while using WebRTC feature, just hidden, nice.
See we even provided the entries required to incorporate the features. :lol:
Shouldn't be hard now, I assume.

**Comment by BooBerry** [comment]
Hmmm, now if only Chrome had a similar option available, then it could be universal.

**Comment by The-Commissioner** [comment]
How's vivaldi or opera providing that feature? SInce they both are chromium based also, so shouldn't be hard to find.

**Comment by BooBerry** [comment]
Probably added as a feature to their forks, IMO.

**Comment by ameshkov** [comment]
I've assigned this feature request to v3.0, should think about it a bit, though.

Offtop:
I must admit FF caught up with Chrome in no time, I hope more people will soon realize that WebExtensions transition was not a bad idea after all.

**Comment by ameshkov** [comment]
Available as an option in stealth mode
