### ISSUE TITLE
Consider using insertCSS instead of the content scripts

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#847]
In light of [this change](https://bugs.chromium.org/p/chromium/issues/detail?id=632009) coming in future versions of Chromium, we should reconsider the way we inject CSS into the pages.

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/insertCSS
https://developer.chrome.com/extensions/tabs#method-insertCSS

**Comment by The-Commissioner** [comment]
What impact will it have on Firefox and related browsers bcuz from what I gathered it's a chromium bug and the issues referenced here, in them you are saying will be automatically fixed by solving this issue.

So, this chromium issue affects firefox also?

**Comment by ameshkov** [comment]
> What impact will it have on Firefox and related browsers bcuz from what I gathered it's a chromium bug and the issues referenced here, in them you are saying will be automatically fixed by solving this issue.

1. "user agent" stylesheets are already implemented in FF.
2. Aside from the styles priority, the problem with applying CSS from the content script is timing -- it is applied when part of the DOM is already loaded and causes layout recalculation. `insertCSS` will eliminate this recalculation.

> So, this chromium issue affects firefox also?

This is a common thing for all extensions which use WebExtensions save for Edge as `insertCSS` is kinda limited there.

**Comment by The-Commissioner** [comment]
I had realised it just after typing, thats why I deleted the comment.

**Comment by The-Commissioner** [comment]
@ameshkov As a goodwill gesture, this is what I was talking about at [wilders](https://www.wilderssecurity.com/threads/adguard-ad-blocker.342850/page-97#post-2700843) : 

https://github.com/AdguardTeam/AdguardForWindows/issues/1245#issuecomment-241444461

Was fixed in AGW but not in extension.

**Comment by ameshkov** [comment]
@The-Commissioner that was a good question anyway, and thanks for the bug report!
