### ISSUE TITLE
Improve memory allocations on filters update check

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#848]
The issue is caused by the number of closures we use. This is unoptimal.

Ideally, we should completely get rid of using closures in the code.

### Steps to reproduce

1. Open `about:memory`
2. Click "measure", remember AG memory usage
3. Open AG settings and click "Check filter updates"
4. Click "measure" again and compare with the previous result

### Expected behavior
AG should use maybe a couple of MB more (unless GC/CC is executed)

### Actual behavior
AG consumes 100MB more.

The situation becomes normal after a couple of GC cycles. However, the count of memory allocations is astonishing.

**Comment by Anoop2609** [comment]
![screenshot 29](https://user-images.githubusercontent.com/23557479/31071170-abeffcd8-a780-11e7-9de3-588b8b642536.png)
still consuming too much of memory(324 MB) after filters update

**Comment by ameshkov** [comment]
> still consuming too much of memory(324 MB) after filters update

Right after the filters update it is okay, the point is that now GC kicks and collects unused memory much earlier (less than in a minute everything is collected)
