### ISSUE TITLE
Video player does not work on seodiv.com

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/AdguardBrowserExtension#849]
### Steps to reproduce

1. Disable all filters in AdGuard
2. Add any cosmetic rule, for example `seodiv.com##.Testtttt`
3. Go here - http://seodiv.com/star-vs-the-forces-of-evil/7549-star-vs-las-fuerzas-del-mal-temporada-03-capitulo-01-04.html
4. Click on `INGLES` button (look screenshot)

### Expected behavior

Video player should load.
### Actual behavior

Video player does not load.

<details><summary>With AdGuard</summary>

![image](https://user-images.githubusercontent.com/29142494/30188151-41eabe06-942d-11e7-9c6d-d062d8400fc0.png)

</details>

<details><summary>Without AdGuard</summary>

![image](https://user-images.githubusercontent.com/29142494/30188193-8020b7de-942d-11e7-8678-11999f64e6d6.png)

</details>

### Your environment

* Adguard AdBlocker extension version:  2.6.7
* Environment name and version: Chrome 61.0.3163.79

**Comment by ameshkov** [comment]
Fixed in `browser-extension/pull-requests/21`
