### ISSUE TITLE
Update Filters option in AG Browser Extension

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardBrowserExtension#850]
@clementine123 commented on [Fri Sep 08 2017](https://github.com/AdguardTeam/AdguardForAndroid/issues/1432)

Can you add an option to update the filters in the menu option of the browser extension? Currently, one has to open the AG settings and only then can update them. Thanks!

**Comment by vozersky** [comment]
@clementine123

you can do in in the context menu

![image](https://user-images.githubusercontent.com/17472907/30276071-40b0123e-970c-11e7-9505-5ecb1f03e4bf.png)

**Comment by clementine123** [comment]
Oh yes, thank you!
