### ISSUE TITLE
Can't apply element hiding rule to the element inside IFRAME

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#852]
Original issue
https://github.com/AdguardTeam/AdguardFilters/issues/6595#issuecomment-328218629

<details>

![image](http://imagizer.imageshack.com/img922/485/1lY9Wi.png)
</details>

Does not work: `t3n-de.cdn.ampproject.org##amp-iframe`
works: `google.de##amp-iframe`

**Comment by ameshkov** [comment]
The thing is that this is how it is supposed to work in Safari.

`if-domain`/`unless-domain` are checked against the window domain, frame domain is ignored.

We can fix this if we use `url-filter` instead of the `if-domain`, but it's not good from the performance point of view.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardForSafari #105](https://github.com/AdguardTeam/AdGuardForSafari/issues/105) via [**ZenHub**](https://www.zenhub.com/)
