### ISSUE TITLE
Firefox for Android

### ISSUE THREAD

**Issue by ensiform** [AdguardTeam/AdguardBrowserExtension#853]
In a previous version of Firefox for Android, I had a working version of the Adguard extension but recently Firefox on Android updated and neither versions I tried show up in my drop down menu or function anymore. Is there a specific way to install and which build should be used to have it working in the current release.

**Comment by ameshkov** [comment]
Hi! Have you tried the version from the beta channel?

**Comment by ameshkov** [comment]
This one:
https://addons.mozilla.org/en-US/firefox/addon/adguard-adblocker/versions/beta

**Comment by ensiform** [comment]
@ameshkov Was able to get that one installed, but tapping the menu entry in the Firefox drop-down doesn't actually do anything. Isn't it supposed to give me a per site menu or global settings like on the Desktop.

**Comment by ameshkov** [comment]
Got it. It seems that WebExtensions build is not fully compatible with the FF. Legacy build is compatible, though.

Anyway, we need to make WebExtensions build compatible, assigned to v2.8

**Comment by ensiform** [comment]
So, I'm no sure if this is related to your end or if all of this is a common Firefox for Android bug. But I cannot actually access the options for the extension on Android. There's only uninstall and disable buttons in the add-ons page, and selecting the Adguard option in the drop-down menu in the browser does nothing at all. This is with the newest release (and what was happening before too) on the 28th from the Mozilla extension page 2.7.2 final. it claims to be webextension in the notes. Note: Firefox 56 has not yet propagated to my device on the store yet.

**Comment by The-Commissioner** [comment]
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/783#issuecomment-324975083

One month before I told this same thing and they said it's all OK.
