### ISSUE TITLE
Adguard hides iframe with Vimeo player even if asked not to

### ISSUE THREAD

**Issue by k-solnushkin** [AdguardTeam/AdguardBrowserExtension#854]
There is a deeply hidden bug somewhere in Adguard code that in certain cases causes Adguard to hide Vimeo player's iframe, thereby rendering the video unviewable. Attempts to disable Adguard protection mechanisms on multiple levels all fail.

### Steps to verify that the page displays normally without Adguard

1. Launch Mozilla Firefox without the Adguard extension installed
2. Navigate to https://amlab.me/
3. Click "Войти" in the upper right corner
4. Use login "test@example.com" and the same password to log in into the site
5. Navigate to https://amlab.me/santiago#lessons
6. Verify that the Vimeo player is displayed
7. Click the video to play it

### Steps to reproduce the problem
1. Launch Mozilla Firefox
2. Install Adguard AdBlocker extension
3. Navigate to https://amlab.me/
4. Click "Войти" in the upper right corner
5. Use login "test@example.com" and the same password to log in into the site
6. Navigate to https://amlab.me/santiago#lessons

### Expected behavior
The Vimeo video player is still displayed and video can be played:

![image](https://user-images.githubusercontent.com/23080507/30346839-c1e652ee-9812-11e7-9cef-149ba11347ba.png)

### Actual behavior
No video player appears on the screen; video therefore cannot be viewed:

![image](https://user-images.githubusercontent.com/23080507/30345846-706dc224-980f-11e7-9ab7-0b975e795af1.png)

To add insult to injury, all attempts to ask Adguard to turn off its filtering fail:

1. Deactivate "English filter" and "Russian filter", and also deactivate the setting to "Activate the most appropriate filters automatically". The result: it still hides the Vimeo player.

![image](https://user-images.githubusercontent.com/23080507/30346127-6b1e5184-9810-11e7-81d6-6d373847c76d.png)

2. Add the site "amlab.me" to Adguard's whitelist. The result: it still hides the Vimeo player.

![image](https://user-images.githubusercontent.com/23080507/30346220-c7b675c0-9810-11e7-9945-79b1b1b967bf.png)

3. Pause Adguard protection. The result: still the same.

![image](https://user-images.githubusercontent.com/23080507/30346267-ec3d8da2-9810-11e7-8d91-82e1021074ce.png)

The only option that helps is to go to "about:addons", find Adguard, and click "Disable" or "Remove". After that, reloading the page will display the Vimeo player.

The bug is apparently hidden very well in Adguard code; so deeply that even turning off filtering mechanisms one by one doesn't help to resolve the situation.

This can be related to other obscure iframe hiding issues such as https://github.com/AdguardTeam/AdguardBrowserExtension/issues/720, albeit I cannot verify this.

The bottom line is that users of "amlab.me" who have Adguard installed currently have to disable or remove the Adguard extension to be able to watch videos at "amlab.me", or alternatively they are switching to other ad-blocking solutions.

<details><summary>Screenshot:</summary>

After installing Adguard in its default configuration.

![image](https://user-images.githubusercontent.com/23080507/30345846-706dc224-980f-11e7-9ab7-0b975e795af1.png)

</details>

<details><summary>Screenshot of the browser console:</summary>

Screenshot of the browser console is not provided since it indeed contains a lot of warnings and errors but they are most likely irrelevant to the bug being reported in this issue.
</details>

### Your environment

* Adguard AdBlocker extension version: 2.6.7
* Environment name and version: Mozilla Firefox 55.0.3 (64 bit)
* Filters you use in Adguard: None, all were switched off but the problem still persists
* Any other browser extensions you have installed: Irrelevant, since reproducible even with clean, freshly installed Firefox

On behalf of users of the "amlab.me" website, thanks for looking into this and fixing the issue.

**Comment by ameshkov** [comment]
@k-solnushkin thank you very much for such a detailed explanation!

I was able to reproduce and fix the issue: https://github.com/AdguardTeam/AdguardBrowserExtension/commit/760dfe2bc3e7196a1182929164ebf39c8284c619

Version 2.7 is close to the final release, we're planning to push it next week. However, it usually takes quite some time to pass FF review.

There's a temporary solution you can use on your side until it's published: apply this patch to `jquery.vids.js`: https://gist.github.com/ameshkov/2144b0a42e99e24fa7be193e6f4fe195

The only thing changed is that I added a slight delay (wrapped $allVideos.each in a `setTimeout` call).

Sorry for the inconvenience!

**Comment by k-solnushkin** [comment]
@ameshkov 
Dear Andrey,

I was very impressed with the speed of fixing this issue! Thanks a lot, and also for the quick workaround which I will advise to "amlab.me".

All the best in your endeavors!
