### ISSUE TITLE
contrast philosophy

### ISSUE THREAD

**Issue by ghrt676** [AdguardTeam/AdguardBrowserExtension#855]
(1)  Do your operating principles allow for antithetical [paid] whitelisting?

(2) how does AdGuard blocking philosophy differ from _uBlock Origin_ or _Ad"block" Plus & EyeO_?

(3) What information is harvested from [Mozilla|chromium] extension users?

(4) Does each human person have a Right to Privacy?

**Comment by BooBerry** [comment]
Number 3's answer can hopefully be found in the privacy policy: https://adguard.com/en/privacy.html

**Comment by ameshkov** [comment]
> (1) Do your operating principles allow for antithetical [paid] whitelisting?

No. The only way we earn is by selling premium versions of AdGuard.

> (2) how does AdGuard blocking philosophy differ from uBlock Origin or Ad"block" Plus & EyeO?

This is quite simple: our job is to let people have their data under control. What's important, they should be able to control all their devices and apps.

@BooBerry 
> Number 3's answer can hopefully be found in the privacy policy: 

Btw, starting from v2.7 the whole "extension installation" part will be gone. Chrome store numbers are still unreliable, but it does not matter. To estimate the number of extensions users it's enough to count the number of filters update for an hour.

> (4) Does each human person have a Right to Privacy?

Obviously.
