### ISSUE TITLE
onet.pl show anti adblock notice

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/AdguardBrowserExtension#860]
This website https://www.onet.pl/ show anti adblock notice when Adguard Extension Beta 2.7.1 is installed, it also happen when Adguard Extension works in integration mode.
Without Adguard Extension (2.7.1), but with only Adguard for Windows or with 2.6.7 version and with appropriate filter lists it doesn't happen.

### Steps to reproduce

1. Install Adguard Beta 2.7.1
2. In AdGuard settings active `Adblock polskie reguły` filter list
3. Go here - https://www.onet.pl/
4. You will see anti adblock notice

### Expected behavior

Website shouldn't show anti adblock notice.
### Actual behavior

Website show anti adblock notice and hidde content.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29142494/30590109-876e8886-9d3d-11e7-8c6c-5aea98f6daf6.png)

</details>

### Your environment

* Adguard AdBlocker extension version: 2.7.1 Beta
* Environment name and version: Chrome 61.0.3163.91
* Filters you use in Adguard: English, Spyware, Russian, German, Social Media, Annoyances, Experimental, Adblock polskie reguły

**Comment by FadeMind** [comment]
This issue still exist in 2.7.2 stable.

**Comment by Mizzick** [comment]
@Alex-302 please take a look,
for it's seems to be ok, with appropriate filters enabled (Adblock & uBlock polish filter, Adblock & uBlock polish filter - Adguard supplement) and extension v2.7.2

**Comment by Mizzick** [comment]
Fixed with #829 
The issue was that they detect our presence in shadowRoot wrappers
