### ISSUE TITLE
Freeze Filtering Log Header While Scrolling Down

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardBrowserExtension#862]
Hello,

The "Filtering Log" window shows the list of domains. However, scrolling down on this page even scrolls down the log heading. Can you refer the attached screenshot and freeze the highlighted section so that when the user scrolls down, the highlighted section should stay and not scroll down? Thank you!  

### Your environment
![capture](https://user-images.githubusercontent.com/6959116/30753784-fe9329e2-9fdd-11e7-9dc9-dfccbaadb93b.jpg)

* Adguard AdBlocker extension version: 2.67
* Environment name and version: 61.0.3163.100 (Official Build) (32-bit)
* Filters you use in Adguard: N/A
* Any other browser extensions you have installed: N/A

**Comment by XX-J** [comment]
Plus add the column "Filter" (i.e. English Filter, Russian Filter etc.), please. Really necessary. To see clearly which "rule" to which "filter" belongs.

**Comment by clementine123** [comment]
Clicking on the filter rule in the log shows the filter name but yes, a valid point; a column with the filter name is helpful and serves as a quick reference. Thanks!

**Comment by ameshkov** [comment]
Huh, so many upvotes, we'll definitely do it.

**Comment by ameshkov** [comment]
> Plus add the column "Filter" (i.e. English Filter, Russian Filter etc.), please. Really necessary. To see clearly which "rule" to which "filter" belongs.

Moved to a new issue:
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/863

**Comment by Alex-302** [comment]
Pause button also will be useful. And separator after refreshing tab(look at uBO's log)

**Comment by oswaltalvaradolopez** [comment]
> Plus add the column "Filter" (i.e. English Filter, Russian Filter etc.), please. Really necessary. To see clearly which "rule" to which "filter" belongs.

**Comment by Nzzyme** [comment]
What is the priority of this enhancement? By when can we expect this to be implemented?

**Comment by ameshkov** [comment]
No change there, planned on v3.0

**Comment by Nzzyme** [comment]
Ok, so will this be implemented as I see this was removed from the 3.0 milestone?

**Comment by Nzzyme** [comment]
@ameshkov : Is this issue still being considered? Version 3.0.11 is out. It's strange that I don't see this issue in 3.0 or 3.1 milestone

**Comment by Nzzyme** [comment]
Guys, seriously? This is still not implemented?

**Comment by Alex-302** [comment]
I am voting for Pause button

**Comment by Alex-302** [comment]
Freeze filtering log

**Comment by XX-J** [comment]
I'm voting for **all** belong to Filtering log.

**Comment by Nzzyme** [comment]
> I am voting for
> **Pause button**

A pause button would be great.
