### ISSUE TITLE
Add $replace and `$$` rules partial support

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#864]
Firefox now supports `filterResponseData` which gives us the ability to filter HTML responses body:
https://blog.mozilla.org/addons/2017/09/28/webextensions-in-firefox-57/

Also, this question implies that the very same feature is available in Chrome:
https://support.mozilla.org/en-US/questions/1176377

```
function listener(details) {
 let filter = browser.webRequest.filterResponseData(details.requestId);
 let decoder = new TextDecoder("utf-8");
 let encoder = new TextEncoder();

 filter.ondata = event => {
    let str = decoder.decode(event.data, {stream: true});
    str = str.replace(/Example/g, 'WebExtension Example');
    filter.write(encoder.encode(str));
    filter.disconnect();
 }

 return {};
}

browser.webRequest.onBeforeRequest.addListener(
 listener,
 {urls: ["https://example.com/*"], types: ["main_frame"]},
 ["blocking"]
);
```

So, we can use it to implement partial support of `$$` and $replace rules.

Applying `$$` rules may be slow as we need to use [DOMParser](https://developer.mozilla.org/en-US/docs/Web/API/DOMParser). To mitigate it we need to limit `$$` rules to domain-specific rules only.

**Comment by ameshkov** [comment]
I can't find it in Chromium's sources, though, so the use of it may be limited to Firefox only

**Comment by ghajini** [comment]
@ameshkov, 
$$ rule -useful for browser extension users(there is limit I think $$) this is useful for longstanding instart logic crap...

**Comment by ameshkov** [comment]
Both $$ and $replace are really useful and can help us. Unfortunately, in FF only

**Comment by ghajini** [comment]
Basically I was restricted from using adguard chrome browser extension becoz ***instart logic bypasses chrome extension*** due to large inline scripts....this work as per AdamWr in adguard for windows but not work in browser extension due to limited $$rule support.......

https://github.com/AdguardTeam/AdguardFilters/issues/3844

**Comment by ameshkov** [comment]
We've figured a way for FF, eventually we'll find a way for Chrome as well

**Comment by BooBerry** [comment]
I guess Edge and Safari are out in the cold then? =P

Great news, hopefully you guys will find a way for Chrome too. 👍

**Comment by zebrum** [comment]
doesn't work

I've checked with this rules:

`forum.ru-board.com$$table[width="95%"]`
`lenta.ru$$div[class="logo-wrap js-logo"]`
