### ISSUE TITLE
Improve style protection

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#867]
auto.ru - AdGuard's styles are disabled by ad script
Chrome, AdGuard 2.7.2

Original issue with screenshots of ads:
https://forum.adguard.com/index.php?threads/%D0%A0%D0%B5%D1%88%D0%B5%D0%BD%D0%BE-https-cloud-mail-ru.9468/page-2#post-153621

**Comment by ameshkov** [comment]
Done: #650
