### ISSUE TITLE
Add color on blocked items to the Filtering Log

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardBrowserExtension#868]
Сейчас Исключения помечаются - Светло-зелёным.
Думаю будет более наглядно, если Заблокированные элементы будут помечаться - Светло-розовым, или Светло-красным.

<details><summary>Как-то так:</summary>

![255_223_223](https://user-images.githubusercontent.com/17948007/31050419-621585da-a652-11e7-970a-40efe4b1a84f.jpg)
</details><br/>

___________________________________________________
Pale Moon v26.5 (WinXP) - Adguard v2.7.2 (legacy)
Английский фильтр | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и системы аналитики

**Comment by vozersky** [comment]
@XX-J я не совсем понял что не так,  заблокированные элементы же сейчас красным и отмечаются

**Comment by Alex-302** [comment]
Навеное речь о контрастности. На некоторых мониторах подстветка настолько бледная, что её почти не видно(на старом ноуте так было).

**Comment by XX-J** [comment]
Да, почти не видно. У меня сливается с белым, в отличии от правил-исключений. Думаю надо повысить контрастность, чтобы была наравне с зелёным, которым помечаются правила-исключения.
