### ISSUE TITLE
Website those are sharing my info and block them

### ISSUE THREAD

**Issue by Anoop2609** [AdguardTeam/AdguardBrowserExtension#869]
Show visually that when we visit any website then how many other websites are connected with that website and sharing you information. Ability to block them automatically also manually.

**Comment by ameshkov** [comment]
Like this?
https://uploads.adguard.com/up04_e46th_ad_blocker.sketch.png

**Comment by Anoop2609** [comment]
yes

**Comment by ameshkov** [comment]
Then good news is that we're already doing it for v3.0:)
