### ISSUE TITLE
Search option misbehave on news.yandex.ru

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardBrowserExtension#872]
### Steps to reproduce

1. FF fresh install
2. AdGuard extension from store

### Actual behavior

when AG extension is enabled, search option totally messed up on news.yandex.ru
https://uploads.adguard.com/up03_vkls4.mp4

<details><summary>Screenshot of the browser console:</summary>

![screenshot 2017-10-05 18 27 04](https://user-images.githubusercontent.com/23637588/31235707-d8701442-a9fa-11e7-9789-9275ac1412b2.png)

</details>

### Your environment

* Adguard AdBlocker extension version: 2.7.2
* Environment name and version: FF57b5, windows 10
* Any other browser extensions you have installed: none

**Comment by ameshkov** [comment]
To fix this we should add our own `nonce` to the CSP

**Comment by zebrum** [comment]
now it works ok on FF57.0 with AG 2.7.3
