### ISSUE TITLE
Consider adding a confirmation message when sending reports

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardBrowserExtension#874]
> I notice that after using the "Submit a complaint about this website" option in Adguard AdBlocker for Firefox (desktop), no confirmation message is displayed.  Would it be possible to add a confirmation message so the user knows that the issue request has actually been sent and not silently failed?

1624296

**Comment by ameshkov** [comment]
We'll soon change the way reports are sent. The button will lead to a special "reporting" tool.
