### ISSUE TITLE
AdGuard extension blocks voice search in Google

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardBrowserExtension#876]
AdGuard extension 2.7 available in Yandex browser by default blocks voice search on google.com

### Steps to reproduce

1. Enable the extension with default settings
2. Go to https://www.google.com
3. Hit the microphone time
4. Try to search and see it fails

### Actual behavior

<details><summary>Screenshot:</summary>

Blinking like that, nothing happens

![image](https://user-images.githubusercontent.com/15856304/31441478-f116a3e4-ae9b-11e7-8c83-54c75985717f.png)

</details>

### Your environment

* Adguard version: Extension for Yandex, v. 2.7.2
* Yandex 17.7.1.804
* Subscriptions: English, Russian
* DNS: Off

**Comment by ameshkov** [comment]
Это баг яндекс браузера, мы им его отрепортили
