### ISSUE TITLE
$empty modifier and access-control-allow-origin header

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#879]
Details:
https://github.com/AdguardTeam/AdguardForWindows/issues/1360#issuecomment-333133473
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/280#issuecomment-333372352

**Comment by Mizzick** [comment]
Cannot reproduce anymore, 
checked with 
Google Chrome Version 64.0.3265.0 (Official Build) canary (64-bit)
Google Chrome Version 62.0.3202.62 (Official Build) (64-bit)

https://github.com/AdguardTeam/AdguardForWindows/issues/1360#issuecomment-333133473
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/280#issuecomment-299142090
