### ISSUE TITLE
vk.com -- recaptcha is hidden by the FF add-on

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#880]
Recaptcha is hidden:
https://uploads.adguard.com/up04_5s5a9_Welcome__VK.png

For some reason we don't receive `onProcessShouldCollapseResponse` after `tempHide` call

**Comment by Mizzick** [comment]
For some reason 
```ReferenceError: contentPage is not defined ```
Reproduced in FF 56

**Comment by Mizzick** [comment]
Appears to be a FF bug.
Isn't reproducible with FF 54.

**Comment by ameshkov** [comment]
What about FF 58

**Comment by Mizzick** [comment]
Reproduced in FF 58

**Comment by Mizzick** [comment]
missing some content scripts on amazon.com also, needs further investigation

**Comment by Mizzick** [comment]
Assistant is broken with the following error

```
[Exception... "Component returned failure code: 0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [nsIMessageSender.sendAsyncMessage]"  nsresult: "0xc1f30001 (NS_ERROR_NOT_INITIALIZED)"  location: "JS frame :: resource://gre/modules/ExtensionUtils.jsm :: sendAsyncMessage :: line 512"  data: no]
```
