### ISSUE TITLE
Add filtering in "New tab" windows

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardBrowserExtension#881]
Currently we don't do that, one of the side effects being there's no notification after checking for filter updates.

**Comment by a-ladanov** [comment]
А Adguard для Windows может фильтровать "новую вкладку"?

**Comment by ameshkov** [comment]
Да для него нет различия новая она или нет:)

**Comment by a-ladanov** [comment]
Может меня не правильно поняли, я о вкладке, например, chrome://newtab
В 62 версии Chrome переделали новую вкладку и теперь навязывают свои сервисы прямо в ней.
До 62 версии была возможность обойти это, видоизменив поисковую систему, но теперь нет.
А Adguard кажется полностью игнорирует служебные страницы.

**Comment by ameshkov** [comment]
Дефолтная newtab хрома в исключениях в англ фильтре чтоб туда помощник не втыкать:
`@@||google.*/_/chrome/newtab$document`

Если это правило отключить, все можно прекрасно переделать.

**Comment by a-ladanov** [comment]
Хм, отключил правило. Помощника нет, как и инжекта в принципе.
Следов Adguard на view-source не вижу. Может еще какое-то условие есть?

**Comment by ameshkov** [comment]
Да не, должно хватить, в журнале фильтрации надо посмотреть

**Comment by a-ladanov** [comment]
Установил 6.2 (кстати шикарный журнал теперь сделали)
Несмотря на отключенное правило в фильтре, newtab так и не фильтруется. Ну вот честно не знаю почему.
Но зато с помощью журнала сделал правило, чтобы сторонние сервисы не загружались.
В итоге получилось правило
`||google.ru/async/newtab_ogb^`
И правило срабатывает всегда, независимо от правила-исключения, которое  в английском фильтре.
![default](https://user-images.githubusercontent.com/18179397/31721734-a56fff74-b433-11e7-9219-fe6013c69160.png)

**Comment by ameshkov** [comment]
Мне кажется что newtab закэширован по-черному браузером и он его не перезапрашивает просто. Может в профиль перезайти надо?

**Comment by a-ladanov** [comment]
Профиль у меня по умолчанию, то есть регистрации в гугле я не имею, профиль всего один.
А у вас инжектится Adguard что ли в новую вкладку?
Если сделать поиском по умолчанию строку
`https://www.google.ru/search?q=%s`
изменится ли что-нибудь?

**Comment by ameshkov** [comment]
Да не, не изменится. Я о чем - думаю хром закэшировал код "новой вкладки" и больше не будет его перезапрашивать какое-то время. Чтобы AG отфильтровал ее и применил правила, надо заставить хром снова попытаться загрузить ее.

**Comment by a-ladanov** [comment]
Установил второго пользователя, там естественно поисковая строка какую дает нам гугл.
Новая вкладка инжектится.
Вот с такими параметрами поиска новая вкладка не инжектится
![default](https://user-images.githubusercontent.com/18179397/31723424-3b11b17c-b438-11e7-81bb-a41ad25196ba.png)

**Comment by a-ladanov** [comment]
Попробуйте сделать такой поиск и установить по умолчанию

**Comment by Mizzick** [comment]
https://stackoverflow.com/a/45659562
According to this answer it's not fully possible to add filtering for the new tabs.

**Comment by atropnikov** [comment]
1. Chrome (Firefox) doesn't inject content scripts into the "New tab"
2. All requests from the "New tab" are filtering
