### ISSUE TITLE
"Add New Rule" Field Box Border

### ISSUE THREAD

**Issue by clementine123** [AdguardTeam/AdguardBrowserExtension#882]
I was wondering if you are are able to make the border for the new user filter field little more darker. The current one has a faint border line and it's hardly noticeable. I have attached a screenshot for your reference. The image above shows the current scenario and the one below shows how it can be. A small change but a good one. Thank you.
![screenshot](https://user-images.githubusercontent.com/6959116/31777301-5e7273ee-b50b-11e7-8163-13cc3e7517ea.jpg)

### Your environment

* Adguard AdBlocker extension version: 2.7.2
* Environment name and version: (e.g. Chrome 59.0.3071.115): NA
* Filters you use in Adguard: NA
* Any other browser extensions you have installed: NA

**Comment by ameshkov** [comment]
In the light of the full redesign coming rather soon, I'd prefer not to spend time on tweaking the old one:)
