### ISSUE TITLE
Unable to Block Ad Using Context Menu

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardBrowserExtension#883]
I am unable to block a banner ad on a website using the AG context menu option in Chrome.

### Steps to reproduce

1. Visit the page: http://www.mensfitness.com. You will see a banner ad as seen in the screenshot:
https://gyazo.com/bed8c3d8138b2e16dfeb18fcfb0881d4
https://gyazo.com/dc32b353a5481a35d20e8485eaa5c42d

2. Right click on the page > Adguard AdBlocker > Block ads on this website...
3. Move mouse pointer at the banner ad location until it is highlighted
4. Clicking now will click on the ad link and open the page without the rule being added.

### Expected behavior
Ideally, after performing the above steps, an entry should be added in the user list and the link should not be clickable while selecting an ad on the page.

### Actual behavior
After performing the above steps, the ad banner is clickable and the page directs to the sponsor page instead of the rule being added to the user list.

### Your environment
* Adguard AdBlocker extension version: 2.7.2
* Environment name and version: Chrome 61.0.3163.100 (Official Build) (32-bit)
* Filters you use in Adguard: English, Spyware, Social Media & Annoyances, Mobile Ads & Malware Domains
* Any other browser extensions you have installed: N/A

**Comment by ameshkov** [comment]
@4-life could you please check if we have this very same issue with AdGuard Assistant?

We'll have to fix it in both Assistant and the browser extension anyway.

**Comment by clementine123** [comment]
Hi @4-life : Could you please confirm this?

**Comment by 4-life** [comment]
@clementine123 nope. AdGuard Assistant works as expected. @ameshkov it was different issue.

**Comment by 4-life** [comment]
I noticed that in AdGuard Assistant after the selection, In this block another banner is loaded

**Comment by clementine123** [comment]
@ameshkov So is this being considered for a fix?

**Comment by ameshkov** [comment]
> @ameshkov So is this being considered for a fix?

Nope, now we should come up with a fix

**Comment by ameshkov** [comment]
I am unable reproduce that issue anymore.

I see that there' s adonis anti-adblocker code on the page, it might've been the root cause for the misbehavior.
