### ISSUE TITLE
Some "media" request can't be blocked in Edge

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/AdguardBrowserExtension#885]
### Steps to reproduce

1. Try to block `media` request, for example use this rule -  `.mp4$media`
2. Go here - http://www.miniminiplus.pl/filmy/pokaz/okto-wiem-to-3-odc-15
3. Video/ads should be blocked

### Expected behavior

Media request should be blocked and video shouldn't start.

<details><summary>Screenshot from Chrome where it works correctly:</summary>

![image](https://user-images.githubusercontent.com/29142494/32032180-1325df66-ba06-11e7-89fb-6c2b9d03329a.png)

</details>

### Actual behavior

Video/ads is not blocked.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29142494/32032263-7b8a46c8-ba06-11e7-8015-1065ec34e2de.png)
![image](https://user-images.githubusercontent.com/29142494/32032278-928b0d8a-ba06-11e7-8aea-283e567f45e4.png)

</details>

<details><summary>Screenshot of the browser console:</summary>

![image](https://user-images.githubusercontent.com/29142494/32032301-aeb193f8-ba06-11e7-80ec-758426daf129.png)
`BHX19001: Żądanie do elementu http://www.miniminiplus.pl/wideo/46464-okto-wiem-to3/okto-wiem-to-3-15.mp4 zostało anulowane przez rozszerzenie EdgeExtension_AdguardAdguardAdBlocker_m055xr0c82818.`

</details>
<br>

Ads can be blocked by rule with `$empty` modifier, but normal video is still not blocked.

### Your environment

* Adguard AdBlocker extension version: 2.7.2
* Environment name and version: Microsoft Edge 41.16299.15.0 | Windows 10 1709
* Filters you use in Adguard: For test purpose I disabled all filters and used only "user" filter.
* Any other browser extensions you have installed: -

**Comment by ameshkov** [comment]
@AdamWr could you please re-check it with the latest extension build:
[edge-beta-2.9.0.zip](https://github.com/AdguardTeam/AdguardBrowserExtension/files/1855313/edge-beta-2.9.0.zip)

It seems to be working okay there.

**Comment by AdamWr** [comment]
I can't reproduce this issue anymore.
It seems that now it works fine and I can block "media" requests with AdGuard 2.8.4 and with AdGuard 2.9.0.
