### ISSUE TITLE
css-display-none rules do not work on Reddit.com

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#886]
Here are the details:
https://www.reddit.com/r/Adguard/comments/79ezbm/no_content_blockers_are_working_on_ios_safari/

These two rules should've hidden the "view in app" message on mobile reddit.com, but they failed.
```
reddit.com##.TransparentOverlay__overlay
reddit.com##.DualPartInterstitialFooter
```

I've even tried registering a simple content blocker:
```
[
    {
        "trigger": {
            "url-filter": ".*"
        },
        "action": {
            "type": "css-display-none",
            "selector": ".TransparentOverlay__overlay"
        }
    },
    {
        "trigger": {
            "url-filter": ".*"
        },
        "action": {
            "type": "css-display-none",
            "selector": ".DualPartInterstitialFooter"
        }
    }
]
```

**Comment by ameshkov** [comment]
@Mizzick any idea why is it happening?

What's interesting, hiding `#container` works as it should...

**Comment by Mizzick** [comment]
Lowercase rules work correct
```reddit.com##.transparentoverlay__overlay
reddit.com##.dualpartinterstitialfooter```

**Comment by Mizzick** [comment]
Check other sites

**Comment by Mizzick** [comment]
Seems to be a bug on reddit, now all fine.
Checked UpperCase class rules on rambler.ru aswell, works as expected.
Interesting fact that loweredCase rules are also suitable.

**Comment by ameshkov** [comment]
@Mizzick mark as "Cannot reproduce" or "Invalid"
