### ISSUE TITLE
Can't get extended CSS selectors to work

### ISSUE THREAD

**Issue by levonder** [AdguardTeam/AdguardBrowserExtension#888]
E.g. on a typical GitHub issue:

> ameshkov opened this issue on 10 Aug 2016

```
<div class="TableObject-item TableObject-item--primary">
        <a href="/ameshkov" class="author">ameshkov</a>  opened this <span class="noun">Issue</span>
        <relative-time datetime="2016-08-10T12:55:28Z" title="10 Aug 2016, 15:55 GMT+3">on 10 Aug 2016</relative-time>
        · 0 comments
</div>

```

As I understand

```
github.com##.noun[-ext-contains="Issue"]
github.com##.noun:contains(Issue)
```

such filters should block the word 'issue', don't seem to do that for me..
(Tried lowercase 'issue' as well.)

Chrome 62, Adguard 2.7.2

**Comment by ameshkov** [comment]
First of all, try using this userscript (via Violentmonkey for instance) to debug selectors:
https://github.com/AdguardTeam/Userscripts/blob/master/extendedCssDebugger/extended-css.debugger.user.js

Once it's installed, you can use it from the browser console:
https://uploads.adguard.com/up04_69gy5_Cant_get_extended_CSS_selectors_to_work__Issue_888__AdguardTeamAdguardBrowserExtension.png

Your selectors seem to be okay and it works for me -- hides the "issue" link (don't forget to refresh the page).

**Comment by levonder** [comment]
You can easily make other people feel stupid -_-
Never had to refresh the page for other selectors (usually adding them via 'block smth on this page' button, not from the prefs), didn't expect it to work in this case
Thank you, closing

**Comment by ameshkov** [comment]
No problem, I am glad to help, feel free to ask anything :)
