### ISSUE TITLE
Page cannot be filtered when "Adaptive Design" mode is enabled in Firefox DevTools

### ISSUE THREAD

**Issue by vitalkanev** [AdguardTeam/AdguardBrowserExtension#891]
Example here: [link](https://www.thecollectionbook.info/gallery/?f=/windows/nt%20kernel/windows%2010%20for%20iot/10.0.10240.16384/english/core)

### Steps to reproduce

1. Open the link above
2. Open DevTools - <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>I</kbd>
3. Click the `Adaptive Design` button (Looks like a phone)
4. Focus to the page - Select the device (I choosed `Google Nexus 5`)

### Expected behavior

It should filter the page

### Actual behavior

Ads and cookie note are visible

<details><summary>Screenshot:</summary>

![2017-11-12 15-43-30](https://user-images.githubusercontent.com/18398761/32699039-66c47ca0-c7c0-11e7-87a1-87a73575b21d.png)

Note that the color that I selected is not by default
</details>

<details><summary>Screenshot of the browser console:</summary>

![2017-11-12 15-46-18](https://user-images.githubusercontent.com/18398761/32699061-ab427b98-c7c0-11e7-97b7-1b29ba609776.png)

</details>

### Your environment

* Adguard AdBlocker extension version: 2.7.3
* Environment name and version: (e.g. Chrome 59.0.3071.115) Firefox 56 on Ubuntu Artful
* Filters you use in Adguard: Does not matter
* Any other browser extensions you have installed: Ubuntu modifications for Firefox; Safe Browsing Version 4 (temporary add-on) *by Mozilla*

**Comment by vozersky** [comment]
reproduced with FF stable, nightly is fine
seems to be the browser bug

**Comment by vitalkanev** [comment]
Upgraded to Firefox Quantum - Fine
