### ISSUE TITLE
Using AdBlocker but still problems...

### ISSUE THREAD

**Issue by Cattaleyae** [AdguardTeam/AdguardBrowserExtension#893]
I have an antivirus called F secure (from my internet provider).
Have the AdGuard full download and the Adblocker for Safari, however i've done this all i still get ads that just opens while i'm using Safari like so many times it drives me crazy.
This is the link that always opens during my session on Safari:
http://ssp.fwrdy.com/impression?bid_id=a2f4a77e-c7dc-11e7-801c-a42bb922f9e7

It's from a software i downloaded and eversince i did that i have that issue...

I hope you'll can help me out on this one, i don't know wich download it was that caused me problems on Safari. I use Mac Pro (2017) latest version of all software on it.
I've tried to search online to solve the problem but nothing worked out.

Cheers from Belgium!

**Comment by vozersky** [comment]
@Cattaleyae looks like malware/adware to me, you should try cleaning your device with malwarebytes.com
