### ISSUE TITLE
Integrate with reports.adguard.com

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#894]
"Submit a complaint" should now open a new tab leading to the reports webapp:
https://reports.adguard.com/new_issue.html

We should pre-fill necessary information right away.

Parameters description:
https://github.com/AdguardTeam/ReportsWebApp/

For instance, here is how it looks like when report is sent from AG for Windows:
https://reports.adguard.com/new_issue.html?product_type=Win&product_version=6.2.436.2170&url=http%3A%2F%2Fexample.org%2F&user_agent=Mozilla%2F5.0%20(Windows%20NT%206.1%3B%20Win64%3B%20x64)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F62.0.3202.89%20Safari%2F537.36&filters=2.3.4.10.1&userscripts=https%3A%2F%2Fcdn.adguard.com%2Fpublic%2FUserscripts%2FBeta%2FAdguardAssistant%2F4.0%2Fassistant.user.js%2Chttps%3A%2F%2Fcdn.adguard.com%2Fpublic%2FUserscripts%2FBeta%2FAdguardPopupBlocker%2F2.1%2Fpopupblocker.user.js&win.wfp=false&stealth.enabled=false&stealth.hide_search_queries=true&stealth.DNT=true&stealth.x_client=true&stealth.third_party_cookies=30&stealth.disable_third_party_cache=false&stealth.webrtc=false&stealth.push=false&stealth.location=true&stealth.flash=false&stealth.java=false&stealth.strip_url=false&block_third_party_auth=false

**Comment by vbagirov** [comment]
@ameshkov are you sure this is for 2.8? We plan to release v2.8 very soon, it will be troublesome to fit this task in there.
