### ISSUE TITLE
Filter is updated even though it is not enabled

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardBrowserExtension#895]
### Steps to reproduce
1. On "AdGuard Settings" page, disabled a filter (For ex: Russian Filter)
2. After sometime, checked for filter updates (either by context menu/icon/settings)
3. The summary of what filters were updated (small black box with the list that appears for a brief period) also shows Russian filter updated.

### Expected behavior
Only the filters that are enabled in settings should get the updates

### Actual behavior
All filters listed on the Settings page (even though if some are disabled) get the updates.

### Your environment
* Adguard AdBlocker extension version: 2.7.2
* Environment name and version: Version 60.0.3112.101 (Official Build) (32-bit)
* Filters you use in Adguard: English, Spyware, Social Media, Annoyances, Mobile Ads, Malware
* Any other browser extensions you have installed: N/A

**Comment by vitalkanev** [comment]
I can confirm this - Firefox Quantum 57 with Adguard 2.7.3 on Ubuntu Artful

<details>

![2017-11-17 17-56-54](https://user-images.githubusercontent.com/18398761/32953362-04c6ac08-cbc1-11e7-9467-f20359b1c7d6.png)

</details>

**Comment by ameshkov** [comment]
Guys, but that's intended

**Comment by clementine123** [comment]
@ameshkov : But would that not result in:

-excess user bandwidth
-excess time
-excess number of requests to the filter servers
-excess space & memory to "hold" the filters on the user's PC

Considering these, would it be good to say that it can be tweaked? May I ask the intention behind this? Thanks.

**Comment by ameshkov** [comment]
@clementine123 sorry for the late reply.

The filter has three different states in AG:
1. Enabled
2. Installed and Disabled
3. Not installed

Filters in the second state should be ready to be enabled and operate properly at any given moment and that's why we have this behavior.

If you don't want to have them updated, you can remove them (via "all filters" -> "save") dialog.
