### ISSUE TITLE
The Stealth Mode extension

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardBrowserExtension#896]
Can you please fix any bugs in the Stealth Mode extension.

So that when a user restarts there computer or when someone cleans there
internet browser. So that the data on the extension is not wiped and then
becomes unusable.

As when I have cleaned my internet browser it wipes the data from the
extension and then the extension becomes unusable until I reinstall it, please. Thank you.

Browser: Chrome
https://chrome.google.com/webstore/detail/stealth-mode/hfkpddhkjcbfmnclailpehabmekgphfh

Ticket ID: 1610986

**Comment by snhv** [comment]
If I recall correctly, in near future, functions of the Stealth extension will be implemented in the mainstream Adguard extension and the Stealth extension will be deprecated. So bugfix for Stealth extension won't likely happen.

**Comment by vozersky** [comment]
Issue moved to [AdguardTeam/StealthMode #19](https://github.com/AdguardTeam/StealthMode/issues/19) via [**ZenHub**](https://www.zenhub.com/)
