### ISSUE TITLE
AdGuard extension for Yandex prevents downloading of .pdf files on vk.com

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardBrowserExtension#897]
> При открытии .pdf файла из диалога ВКонтакте он не отображается на всю страницу. Иногда бывает, что отображается корректно. С выключенным расширением таких проблем не возникает. Список фильтров во вложении. Проблема сохраняется до тех пор, пока не будут отключены абсолютно все фильтры. Даже если включён единственный фильтр счётчиков и систем аналитики, проблема через раз возникает.

### Steps to reproduce

1. Enable AdGuard extension in Yandex
2. Go to vk.com dialogs and try to open a .pdf
3. See it partially loaded, happens from time to time

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/32979724-7d73dffc-cc63-11e7-80c5-dc195c9feb5a.png)

![image](https://user-images.githubusercontent.com/15856304/32979726-81be96b0-cc63-11e7-97f7-47afc21fa8ae.png)

</details>

### Your environment

* Adguard AdBlocker extension version: 2.7 I guess
* Environment name and version: Yandex 
* Filters you use in Adguard: see on the screenshot
* Any other browser extensions you have installed: on the screenshot

**Comment by atropnikov** [comment]
The pdf document is loaded fully, but YaBrowser extension for pdf documents doesn't correctly calculate the actual height of the iframe, which contains the document. Problem is in our "pre-hide" logic for iframes.
