### ISSUE TITLE
Большое потребление памяти

### ISSUE THREAD

**Issue by logan344** [AdguardTeam/AdguardBrowserExtension#898]
Иногда adguard с 4 фильтрами(русский, английский, фильтр раздражителей, фильтр счетчиков и систем аналитики) даже при двух-трех открытых вкладках(например rustorka.com и rutracker.org) может потреблять до 100 мб.В чем может быть проблема.Используется браузер chrome  62.0.3202.94

**Comment by a-ladanov** [comment]
Включи "Использовать оптимизированные фильтры"
Реально крутая опция. Мои фильтры "облегчились" в два раза, а рекламы больше не стало.
Пробуй.

**Comment by Alex-302** [comment]
Не првавильный совет.

**Comment by ameshkov** [comment]
Да не, совет неплохой, но лучше и на стороне расширения посмотреть в чем может быть дело.

**Comment by logan344** [comment]
Мне предоставить еще какие-либо данные?

**Comment by vozersky** [comment]
@logan344 какие еще расширения у вас активны в браузере?

**Comment by Alex-302** [comment]
И без сторонних расширений иногда потребляется больше желаемого.

**Comment by ameshkov** [comment]
Давайте не держать это открытым, а открывать задачи когда есть четкое понимание что не так, и главное, как это повторить.

Больше 100мб сожрать может при проверке обновлений фильтров, а потом браузер отпустит эту память, когда она ему понадобится.
