### ISSUE TITLE
AdGuard extension for Yandex - scaling issue

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardBrowserExtension#899]
> При использование плагина для яндекс браузера у меня возникают проблемы в приложении для вк. При делении окна на половину экрана в приложении в вк кривая масштабность. Визуально всё нормально, а вот курсор нажимает видимо не туда. Проблема возникает лишь у краёв окна.

For more information check the screen recording here: 1670830
The game on the screenrec is https://vk.com/metro2033?mid=304436820

### Your environment

* Adguard AdBlocker extension version: v. 2.7
* Environment name and version: Yandex browser

**Comment by ameshkov** [comment]
Duplicate of https://github.com/AdguardTeam/AdguardBrowserExtension/issues/897
