### ISSUE TITLE
Add a feature for blocking certain links/results from showing up on search engines

### ISSUE THREAD

**Issue by pedrogarcia** [AdguardTeam/AdguardBrowserExtension#900]
Add a feature list for blocking certains links or domains from showing up on search results.
There are a lot of spammy or unwanted (paywall or signup-only) results showing up in google search, and on my timeline on social networks. 
Having a filter for cosmetically blocking links in search results or in more general places would be a really useful feature.

**Comment by ameshkov** [comment]
You know what, it's yet to be announced, but we'll soon provide an additional browser extension for that.
