### ISSUE TITLE
Почти все ссылки из расширения ведут на 404

### ISSUE THREAD

**Issue by a-ladanov** [AdguardTeam/AdguardBrowserExtension#901]
Видимо из-за обновления официального сайта, почти все ссылки из расширения ведут на несуществующие страницы на официальном сайте. Например, подробности антифишинга или правила составления фильтров. Редирект не прикрутили. А-та-та.
Может уже известно, но на всякий случай повешу задачу.
Chrome-версия.

**Comment by ameshkov** [comment]
Блин, были редиректы, видимо сломались когда выкатывали акцию под черную пятницу

**Comment by ameshkov** [comment]
Передал разработчикам сайта
