### ISSUE TITLE
AdGuard sometimes hangs when Ghostery is also enabled

### ISSUE THREAD

**Issue by luav** [AdguardTeam/AdguardBrowserExtension#903]
### Steps to reproduce
- (I don't remember the URL where this issues occurred.)

### Expected behavior

Absence of hangs

### Actual behavior

Sometimes AdGuard hangs consuming 100% CPU and causes unresponsive tab.

Chrome Extensions tab shows the following warning:
```
Warning:
This extension failed to redirect a network request to data:, because another extension (Ghostery) redirected it to data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACklEQVR4nGMAAQAABQABDQottAAAAABJRU5ErkJggg==.
```

### Your environment

* Adguard AdBlocker extension version: 2.7.2
* Environment name and version: Chrome Version 62.0.3202.94 (Official Build) (64-bit), Linux Ubuntu 16.04 x64
* Any other browser extensions you have installed: Ghostery for Chrome version 7.4.1.4, ...

**Comment by karina-archazh** [comment]
Hi, everything works fine with new updated version of Ghostery and AdGuard.
