### ISSUE TITLE
Notify users when they disable Base filter

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardBrowserExtension#904]
Some users don't realize how important is English filter for proper filtering. We should immediately show a warning-like red text when a user disables English filter in "Filters" settings tab. It should say "English filter is necessary for quality filtering!" to the right of the "English filter" heading.

It should look somewhat like this:

<details>
<summary>Screenshot:</summary>

![image](https://uploads.adguard.com/vbagirov48298.png)

</details>

**Comment by ameshkov** [comment]
Can be solved by renaming to Base filter

**Comment by vbagirov** [comment]
I still believe that it is better to explicitly tell users that disabling this filter is undesirable, but changing its name to `Base` will certainly help to some degree.

**Comment by TPS** [comment]
Now that the name is changed to "AdGuard Base filter," could this issue title be updated?  TIA! 🙇🏾‍♂️

**Comment by TPS** [comment]
This was just closed, but there's still no warning, @ least on Android.…
