### ISSUE TITLE
Browsing security fails in chrome incognito mode

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardBrowserExtension#905]
### Steps to reproduce

1. browsing security enabled
2. open test page http://wmconvirus.narod.ru/ in private window

### Expected behavior

<details>

![2017-11-30 18 42 42](https://user-images.githubusercontent.com/23637588/33439346-474685b6-d5fe-11e7-9d2d-209a2686cfb1.png)

</details>

### Actual behavior

<details>

![2017-11-30 18 35 07](https://user-images.githubusercontent.com/23637588/33439357-4c351c2c-d5fe-11e7-893c-f41009ad42b0.png)

</details>

</details>

### Your environment

* Adguard AdBlocker extension version: 2.8.1
* Environment name and version: Chrome 62.0.3202.94

**Comment by atropnikov** [comment]
Fixed
