### ISSUE TITLE
[Request] Add Title to Your Filters

### ISSUE THREAD

**Issue by bkrcrc** [AdguardTeam/AdguardBrowserExtension#91]
Hello,
Can you please add titles to your filter lists?
I added Adguard Turkish list ito my uBO and there is no title for this filter and other filters.
Please see : http://img.prntscr.com/img?url=http://i.imgur.com/WyrB8w4.png
I wrote the red letters.

So can you please add this string
! Title: Adguard Turkish Filter
word top of the filter to give this filter a name? Easylist has such a string, you can check.

You can also do the same thing on your other filters. For example;
! Title: Adguard Spyware Filter
! Title: Adguard Social Media Filter
etc.

What do you think?
Thanks

**Comment by ameshkov** [comment]
Hi!

Done, thank you for suggestion!
