### ISSUE TITLE
Не работае журнал и блокировка в facebook

### ISSUE THREAD

**Issue by ForumLiker** [AdguardTeam/AdguardBrowserExtension#911]
Здравствуйте. Не работает журнал отображающий заблокированные запросы. Открывается пустое белое окно. Так же находясь на сайте facebook, нажимая в выпадающем меню дополнения "Заблокировать рекламу на сайте", ничего не происходит.
ОС Linux,
Firefox v 58,
Adguard Антибаннер 2.7.3

**Comment by zebrum** [comment]
@ForumLiker вчера вышла [бета 2.8.1](https://github.com/AdguardTeam/AdguardBrowserExtension/releases/tag/v2.8.1-beta), попробуйте с ней.

**Comment by vozersky** [comment]
С выделялкой повторилось:

`[Exception... "Component returned failure code: 0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [nsIMessageSender.sendAsyncMessage]"  nsresult: "0xc1f30001 (NS_ERROR_NOT_INITIALIZED)"  location: "JS frame :: resource://gre/modules/ExtensionUtils.jsm :: sendAsyncMessage :: line 514"  data: no]  (unknown)
	sendAsyncMessage resource://gre/modules/ExtensionUtils.jsm:514:51
	_handleMessage/deferred.promise< resource://gre/modules/MessageChannel.jsm:984:9`


@ForumLiker в бете 2.8.1 все ок, ставьте ее, пожалуйста :)

**Comment by ForumLiker** [comment]
И снова проблемы с фейсбуком на бета версии. Не показывает кол-во заблокированного + блокирует всплывающее окно в группах при нажатии на имя человека. И журнал все так же не работает ни на одном из сайтов.

**Comment by Alex-302** [comment]
@ForumLiker 
> блокирует всплывающее окно в группах при нажатии на имя человека

можно подробнее? Какие фильтры включены?

**Comment by ForumLiker** [comment]
@Alex-302 . Английский и Русский. Как я понял это единичный случай был, скорее всего глюк фб.

**Comment by vozersky** [comment]
@ForumLiker если вдруг повторится, посмотрите пожалуйста, что в консоли браузера пишет

**Comment by ForumLiker** [comment]
@vozersky Хорошо.
А что с журналом делать?? У кого-то он работает?

**Comment by vozersky** [comment]
Да. 
Проверяйте без других расширений в браузере.

**Comment by ameshkov** [comment]
Лучше просто на чистом профиле FF проверять такие штуки

**Comment by ForumLiker** [comment]
Запустил на чистом профиле, тоже белое окно, но случилось чудо! Я изменил размер этого окна и всем появилось содержимое! В моем профиле так же.

**Comment by ameshkov** [comment]
Похоже какая-то лажа с применением стилей в самом FF. Не понимаю почему только у вас так легко повторяется, а у нас чисто.

FF nightly или stable нет под рукой проверить?
