### ISSUE TITLE
$$-правила в бете 2.8.1

### ISSUE THREAD

**Issue by a-ladanov** [AdguardTeam/AdguardBrowserExtension#912]
В текущей бете, исходя из этой задачи https://github.com/AdguardTeam/AdguardBrowserExtension/issues/864, возможно добавлять $$-правила.
Пользовательский их не принимает, удаляет после обновления страницы настроек.

**Comment by ameshkov** [comment]
Эшибка в релиз нотс -- эти правила поддерживает только расширение для FF
