### ISSUE TITLE
Adblock support

### ISSUE THREAD

**Issue by hawkeye116477** [AdguardTeam/AdguardBrowserExtension#913]
Actually, I need 2 lists, one for Adblock and another for AdGuard/uBlock, because some filters cause problems on Adblock (for example: no scrollbar).
So the idea is to add maybe three exclamations before filters, which will work on AdGuard, but won't work on Adblock.
Example:
before
```

spidersweb.pl##.mfp-ready
spidersweb.pl##html:style(overflow: visible!important; margin-right: 0px!important)
```

after
```

!!!spidersweb.pl##.mfp-ready
!!!spidersweb.pl##html:style(overflow: visible!important; margin-right: 0px!important)
```

Thanks to this I will not have to make two filter lists and someone who have Adblock won't have problems.

**Comment by ameshkov** [comment]
Thank you! We're discussing it in the uBO repo right now:
https://github.com/gorhill/uBlock/issues/3331

I'll file a detailed issue when we come up with a common approach.
