### ISSUE TITLE
Allow search ads and websites' self-promotion doesn't work

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardBrowserExtension#916]
Have selected that option and it does not work, even for your
toaster example in the documentation.

<details><summary>Screenshot:</summary>

![screen shot 2017-12-14 at 4 46 45 pm](https://user-images.githubusercontent.com/27292111/33997850-6ca4bb52-e0ee-11e7-80d9-8032486d3291.png)

![screen shot 2017-12-14 at 4 44 45 pm](https://user-images.githubusercontent.com/27292111/33997851-6cc566b8-e0ee-11e7-8c28-2268bf64775f.png)

</details>

AdGuard for Chrome extension (2.7.2)
Google Chrome Version 63.0.3239.84

**Comment by ameshkov** [comment]
@Alex-302 ?

**Comment by Alex-302** [comment]
It works as expected on my end
![image](https://user-images.githubusercontent.com/8361299/34001219-17526834-e0f8-11e7-8d5e-f20aae43694d.png)

**Comment by vozersky** [comment]
can't rep

@veronikasav  it works, but well, it might need a couple of page reloads, best thing is: 
![image](https://user-images.githubusercontent.com/17472907/34004863-28a6fd04-e10a-11e7-8344-d09a3d6acb82.png)
