### ISSUE TITLE
What’s causing this problem?

### ISSUE THREAD

**Issue by PentagramTr** [AdguardTeam/AdguardBrowserExtension#918]
I reported a problem on the AdGuard forum. But the problem still going on now.
My report
https://forum.adguard.com/index.php?threads/resolved-chip-com-tr.27463/
https://www.chip.com.tr/galeri/yeni-36-duvar-kagidi_3545.html

I still can't see the buttons I mentioned in this issue. **But when I put the code that Alex wrote into my user filter, I can see the buttons. I installed the uBlock for testing and the buttons appear.**

Browser extension and Windows program users can't see these buttons. I uninstalled the extension and I reinstall again, but it did not work.
Whats causing this?
(The problem is not caused by the "Fanboy's Social Blocking List" filter and other extensions.)

-At the moment.
https://s18.postimg.org/atfee4y0p/chip.png

-When I put the codes into my user filter.
https://s18.postimg.org/6kaobzhwp/chip2.png
https://s18.postimg.org/oaccx137d/image.png

`chip.com.tr#@#.share_bar`
`chip.com.tr#@#.social-button-small`
`chip.com.tr#@#.social-button`
`chip.com.tr##.share_bar > li:not(.fr)`

* Adguard AdBlocker extension version: 2.7.2
* Browser: Chrome 63.0.3239.108 64-bit 
* Filters : English - Spyware - Social Media - Annoyance - Turkish - Fanboys Social Blocking List
* Other browser extensions : Disconnect - HTTPS Everywhere

**Comment by ameshkov** [comment]
Replied to the forum thread.

It seems that the mistake is made in the social filter.
