### ISSUE TITLE
[MS Edge + Extension] YouTube input lag

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardBrowserExtension#919]
### Steps to reproduce
1. Open YouTube with ADG browser extension. One of the following filters must be turned on: English filter, Social media filter, Russian, French and Romanian one.
2. Try to enter anything into YouTube's search bar.
3. Enjoy the ~5s input lag.

### Expected behavior
Text should get in without any problems.

### Actual behavior
User reports a 3-5s input lag.
Id: 1695567

### Your environment
* Adguard AdBlocker extension version: 2.7.2
* Environment name and version: Microsoft Edge 41.16299.15.0 / Microsoft EdgeHTML 16.16299
* Filters you use in Adguard: English, spyware, social media, Russian, French, dutch, ROList and Estonian List.
* Any other browser extensions you have installed: Bitwarden, F1000, Mate translate and Translator for Microsoft Edge

**Comment by Alex-302** [comment]
I can't reproduce it. Could you check?
- with disabled filters;
- with disabled AdGuard.

**Comment by zebrum** [comment]
me neither.
@akmAa can you test it one more time with those settings above?

**Comment by akmAa** [comment]
@zebrum Works fine with all filter disabled. As soon as any of these filters (English filter, Social media filter, Russian, French and Romanian) is enabled, YouTube starts lagging as hell.

The client uses ADG standalone extension - as long as it is stopped, everything works just fine.

**Comment by zebrum** [comment]
Did you try to disable other browser extensions?
