### ISSUE TITLE
PaleMoon menu is blacked out in integration mode

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#92]
This bug is about "legacy" version of the firefox add-on (capable of working in palemoon).

http://forum.adguard.com/showthread.php?7833-Pale-MoonIssues-Persist

**Comment by bkrcrc** [comment]
I am using stable Palemoon 25.8.1 64bit. There is no problem with Adguard (legacy)

**Comment by ameshkov** [comment]
I bet the problem is in themes or other add-ons, waiting for user to answer on the forum thread.

**Comment by bkrcrc** [comment]
For me I am using Windows 10 Home 64bit with Palemoon latest. I have no problem with Adguard (legacy) addon popup menu. See the screenshot : http://i.imgur.com/8vVWbkl.png
Just inform to you.

**Comment by gshumihin** [comment]
One more screenshot for Palemoon 26:
http://content.screencast.com/users/shumegor/folders/Jing/media/03e90e74-9024-49b2-b344-a0def67c10a3/2015-12-09_1822.png

**Comment by ameshkov** [comment]
@gshumihin I am 100% sure that should be a separate bug.

**Comment by ameshkov** [comment]
User has posted add-ons list:
http://forum.adguard.com/showthread.php?7833-Pale-MoonIssues-Persist&p=68863#post68863

**Comment by ameshkov** [comment]
@gshumihin please check it with these add-ons

**Comment by ameshkov** [comment]
@gshumihin so?

**Comment by gshumihin** [comment]
Febe, quick translator, second search, session manager, tab mix plus are not avaliable for palemoon.
As far as Quick Translator.

**Comment by gshumihin** [comment]
Tested adguard legacy 2.1.1 with Palemoon 25.8.1 and suggested extensions. Adguard menu (and Palemoon menu too) seems pretty normal. Except this little bug:
<img src="http://content.screencast.com/users/shumegor/folders/Jing/media/95eaefcf-be03-4ca0-bb8f-74ee8b8cf4c7/00000910.png" width="400">

**Comment by gshumihin** [comment]
@ameshkov 
Should i test same situation for Palemoon 26+Adguard legacy beta?

**Comment by bkrcrc** [comment]
Please test it. Because the next releases of Pale Moon browser will be based on Goanna ( mean PM 26). Thanks.

**Comment by gshumihin** [comment]
No issues for Goanna+stable Adguard extension

**Comment by bkrcrc** [comment]
Thanks @gshumihin , you did good jobs on that before the stable release. You will see that Adguard and Pale Moon users will not feel the difference, thanks to you effort.

**Comment by ameshkov** [comment]
I'll leave this issue open for now, but clear the milestone as we don't know what to fix

**Comment by Mizzick** [comment]
This can happen then Adguard can't find the correct browser tab cause of this bug in FF https://bugzilla.mozilla.org/show_bug.cgi?id=942511. It appears to be fixed in
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/152.
