### ISSUE TITLE
Adguard AdBlocker bug 12/21/2017

### ISSUE THREAD

**Issue by yun2673436976** [AdguardTeam/AdguardBrowserExtension#921]
Adguard AdBlocker bug: Google translation is not accurate, please copy Chinese to other translation software.
Adguard AdBlocker can not block the vip.xinxin62.net pop-up. I search for "rio" at vip.xinxin62.net, click on the bottom of the page 1,2,3 screening movie, vip.xinxin62.net "kept open a new window in the background, I am very angry, please fix this bug.
Adguard AdBlocker bug:谷歌翻译不准确，请把中文复制到其他翻译软件。
Adguard AdBlocker不能屏蔽“vip.xinxin62.net”弹出窗口。我在vip.xinxin62.net”搜索“rio”，点击网页底部1、2、3筛选电影，vip.xinxin62.net”不停的在后台打开新的窗口，我很生气，请修复这个bug。

**Comment by vozersky** [comment]
report to https://github.com/AdguardTeam/AdguardFilters/issues please
