### ISSUE TITLE
group.aliexpress.com

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardBrowserExtension#924]
@adguard-bot commented on [Thu Dec 14 2017](https://github.com/AdguardTeam/AdguardFilters/issues/8426)

### Issue URL (Incorrect Blocking)
[https://group.aliexpress.com](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fgroup.aliexpress.com)
### Comment
Username: @pro100Hub
> Здравствуйте.
> 
> AdGuard блокирует форму комментариев к любому заказу и отображение отзывов в разделе горящих товаров https://group.aliexpress.com/ru.htm?spm=a2g0v.11010108.300.5.3058a302oAtt0k&tracelog=rugroupbuyyt01
> Отключаю AdGuard и все формы на месте. Исправьте, пожалуйста. Спасибо.
> 
> AdGuards 2.8.1beta
> Firefox 56.0.2 x64
> 
> P.S: Просьба добавить возможность прикреплять скриншоты(reports.adguard.com) от встроенной функции в Firefox браузер. В данный момент ваша форма не принимает их скриншоты. Пришлось загружать на файлообменник.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://s6.postimg.org/jl9rehsf5/Screenshot-2017-12-14_Ali_Express.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | Ext
AdGuard version: | 2.8.1
Browser: | Firefox
Filters: | Russian,<br>English,<br>EasyList,<br>EasyPrivacy,<br>Adblock Warning Removal List

---

@Alex-302 commented on [Mon Dec 18 2017](https://github.com/AdguardTeam/AdguardFilters/issues/8426#issuecomment-352429670)

Не повторяется. Какой фильтр ломает?

---

@pro100Hub commented on [Thu Dec 21 2017](https://github.com/AdguardTeam/AdguardFilters/issues/8426#issuecomment-353435522)

@Alex-302 баг почему то не зависит от фильтров, отключал все. Баг пропадает только при отключении дополнения.
[Смотреть баг](https://i.imgur.com/1CMTCmr.gifv) 

---

@Alex-302 commented on [Fri Dec 22 2017](https://github.com/AdguardTeam/AdguardFilters/issues/8426#issuecomment-353591739)

Странности. У меня не повторяется никак.
@zebrum @altokarev проверьте у себя в Фоксе и Хроме

**Comment by Mizzick** [comment]
@zebrum have tried with 2.8.2 beta?
As for me, I cannot reproduce in FF 58.0b6 (64-bit) Dev

**Comment by Mizzick** [comment]
Appears to be the same as #880

**Comment by pro100Hub** [comment]
Можно узнать. Вопрос будет решаться или просто закрыли тему и баг останется?

**Comment by ameshkov** [comment]
Уже решен, бета еще новая не вышла

**Comment by pro100Hub** [comment]
@ameshkov большое спасибо! А то просто закрыли тему и ничего не написали)) 
С наступающим ;)
