### ISSUE TITLE
[Safari MacOS] Not allowing search ads to click through [New API]

### ISSUE THREAD

**Issue by IceDarius** [AdguardTeam/AdguardBrowserExtension#926]
On Safari High Sierra with the latest Safari (Version 11.0.2 (13604.4.7.1.3)) using the new API in the setting google Adwords will show (Allow search ads and websites self-promotion is enabled) but will not allow to click through and display "The URL was blocked by a content blocker". If I go into the settings and enable OLD API everything will work as it should. **Issue is for the new API of Safari 11 and is also impacting my peers.**

Please try many keywords and fix issue.

This happens for both googleadservices.com and doubleclick.net

### Steps to reproduce

1. On Safari High Sierra with the latest Safari (Version 11.0.2 (13604.4.7.1.3)) using the new API in the setting google Adwords will show (Allow search ads and websites self-promotion is enabled) but will not allow to click through and display "The URL was blocked by a content blocker". If I go into the settings and enable OLD API everything will work as it should.
2. Sample keyword "cheap flights" and click on flighthub ad copy.

### Expected behavior

Click through to link
### Actual behavior

Adwords get blocked when it shouldn't. 

<details><summary>Screenshot:</summary>

<img width="1156" alt="screen shot 2017-12-25 at 12 18 06 pm" src="https://user-images.githubusercontent.com/24467815/34341864-78007378-e96e-11e7-9fff-1b10382d87a0.png">

</details>

<details><summary>Screenshot of the browser console:</summary>

</details>

### Your environment

* Adguard AdBlocker extension version: 2.8.1 Beta **(I have also tried the stable version)**
* Environment name and version: Safari Version 11.0.2 (13604.4.7.1.3)
* Filters you use in Adguard: Allow Search Ads, Safari, Adguard
* Any other browser extensions you have installed: Chrome, cannot replicate issue on Chrome.

**Comment by ameshkov** [comment]
@Alex-302 I guess we should simply handle it in the filter for search ads, could you plz assist?

**Comment by ameshkov** [comment]
Or in Safari filter as the issue is specific to content blockers.

Smth like `@@||googleadservices.com/pagead/aclk`

**Comment by Alex-302** [comment]
moved to English filter
```
!+ NOT_OPTIMIZED PLATFORM(ios, ext_android_cb, ext_safari)
@@||googleadservices.com/pagead/aclk?
```
@IceDarius please check this rule(second string) in user filter.

**Comment by IceDarius** [comment]
What is it you'd like to do exactly? Whitelist "_@@||googleadservices.com/pagead/aclk_"?

That rule doesn't currently exist in my user filter, it's empty. Like I mentioned above, I want Adwords to work, and its fine with old API but not new API.

**Comment by Alex-302** [comment]
Please copy the rule to user filter, not to whitelist.

**Comment by IceDarius** [comment]
Thanks for the quick response, same result

**Comment by ameshkov** [comment]
That's odd.

Plz check if it looks the same as here:
https://uploads.adguard.com/up04_b4qky_Adguard_Settings.png

**Comment by IceDarius** [comment]
Correct, see attached. Again only happens on new API not old API. See screenshots below.

<img width="921" alt="screen shot 2017-12-26 at 11 37 56 am" src="https://user-images.githubusercontent.com/24467815/34360705-424ed170-ea31-11e7-94bb-1a01cee9c777.png">

<img width="764" alt="screen shot 2017-12-26 at 11 38 44 am" src="https://user-images.githubusercontent.com/24467815/34360719-5e1009e2-ea31-11e7-8396-d196645c85b4.png">

**Comment by IceDarius** [comment]
Any update?

**Comment by ameshkov** [comment]
@IceDarius sorry for the late reply, we have long new year holidays.

Could you please show a screenshot of AG settings, I want to see the exact list of filters you have enabled. Could it be that you've exceeded the 50k rules limit?

**Comment by IceDarius** [comment]
I'm using the defaults and enabling google ads, nothing extra.

<img width="917" alt="screen shot 2018-01-06 at 10 36 00 pm" src="https://user-images.githubusercontent.com/24467815/34646296-0c9105da-f332-11e7-8981-ee7d0b2181f3.png">

**Comment by ameshkov** [comment]
This is so weird.

Okay then, let's try a wider exception rule:
`@@||googleadservices.com`

Also, could you plz take a screenshot of the issue one more time?
What's the blocked page domain, is it googleadservices as on the first screenshot?

**Comment by IceDarius** [comment]
I've added both Googleadservices.com and Doubleclick.net with syntax you outlined. I don't think this is user related, this has been happening for a while I finally decided to report it since it wasn't being fixed. Everything works fine with the old API, new API cannot unblock google ads for some reason.

[Google ad link](https://www.googleadservices.com/pagead/aclk?sa=L&ai=DChcSEwiXyJOs6sbYAhUYtsAKHe1GAKUYABAAGgJpbQ&ohost=www.google.ca&cid=CAESQOD2S4khOFu2wj9WjsAcZvpdSJSMKGxkx2bxtLdWEb1v7lxrtdnjpo0-UTumrJsPi2us9fv5nrfIIod2FGsfXik&sig=AOD64_0bY-wzluY0xPIMacugW8TGpZ37PQ&q=&ved=0ahUKEwij0Ias6sbYAhVpwYMKHT-AAqgQ0QwIJw&adurl=)


Here is a screenshot
<img width="962" alt="screen shot 2018-01-07 at 4 45 20 pm" src="https://user-images.githubusercontent.com/24467815/34654518-cbb03858-f3ca-11e7-9edd-30192471835a.png">

Please try it for yourselves on MacOS with Safari, try various different key words google, use "cheap flights" as an example if you wish.

**Comment by ameshkov** [comment]
Oh, so it's doubleclick also.

One more rule for the user filter:
```
@@||ad.doubleclick.net/ddm/clk/
```

@Alex-302 we may need it for Safari.

**Comment by IceDarius** [comment]
Same result...

**Comment by ameshkov** [comment]
Argh:( doubleclick is blocked again or is it something else?

**Comment by IceDarius** [comment]
Not sure if you’re speaking to me, but doubleclick and googleadservices are not working, the filters have no effect.

**Comment by ameshkov** [comment]
@IceDarius I don't understand how is that possible, but anyway, could you please try these two wider rules  for both googleadservices and doubleclick. If the click is still blocked, check what exact domain is it.

Please copy/paste them carefully, no extra spaces in the beginning/end of the rules.

```
@@||googleadservices.com
@@||doubleclick.net
```

**Comment by IceDarius** [comment]
Hi Andre, I think we're going in circles here. I already did this, still have it enabled, and I already posted the [screenshot](https://user-images.githubusercontent.com/24467815/34654518-cbb03858-f3ca-11e7-9edd-30192471835a.png) <-- click link.

 I'm not a novice, this seems like a bug to me.

This is also happening to multiple peers of mine, I tried it on their computers myself.  Please try this yourself on a Mac with the English Filter, Safari Filter and enable Google ads. Then search for simple keywords such as "cheap flights" click on all the Adwords and see for yourself.

**Comment by ameshkov** [comment]
Lol, we were looking at the wrong place all the time:)

I've finally managed to reproduce the issue (thx to cheap flights keyword), and the URL that is blocked is not googleadservices or doubleclick, this was the end URL of the ad campaign:
https://uploads.adguard.com/up04_ar4hq_Failed_to_open_page.png

In my particular case (with Kayak) the rule to unblock it should be:
`@@||kayak.com/semi/adwords/`

@Alex-302 there are two more Google intermediate domains missed in our filters ([screenshot](https://uploads.adguard.com/up04_7ncyj_Failed_to_open_page.png)):
```
@@||adservice.google.*/ddm/clk
@@||ad.doubleclick.net/ddm/clk
```

@IceDarius thx for your patience. If the issue continues to happen with any of the search ads, we'd need to see the screenshot of the browser console (like on my first screenshot) so that we could see what exact URL was prevented from loading. It appears, that it's often not the same URL as the one in the address bar.

**Comment by IceDarius** [comment]
This did the trick... @@||adservice.google.*/ddm/clk

All sites are working, except Kayak.com and Flighthub.com. Those are safe sites, so I hope they are not added in your filters. Thanks for helping.

<img width="894" alt="screen shot 2018-01-11 at 11 04 04 pm" src="https://user-images.githubusercontent.com/24467815/34859368-c67998c8-f723-11e7-8290-fe06d454a9c1.png">

**Comment by ameshkov** [comment]
The false positive is caused by their landing pages URL, it falls under some common ad pattern.

**Comment by Alex-302** [comment]
> @@||ad.doubleclick.net/ddm/clk/
> @Alex-302 we may need it for Safari.

added

> @@||adservice.google.*/ddm/clk
> @@||ad.doubleclick.net/ddm/clk

added the first. The second is already added.
