### ISSUE TITLE
Malware Warning Page Improvement

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardBrowserExtension#927]
Hello,

When using the AG browser extension and visiting a phishing site (not necessarily that has malware), AG blocks access to the page and shows the standard block page as seen here:

http://prntscr.com/htnweh

However, the text on this blocked page mentions and is more related just to malware. It would be better that the text is modified to include a more broader aspect of security/privacy issues including "Phishing, Malware, Fraudulence"

Ex: mymovieplays.com is a phishing site that asks users to pay to stream content but the site is not dangerous in terms of any kind of malware (virus, trojan, etc.).

One other thing that I noticed was that once I arrived on this blocked page and wanted to go back, it never really allowed me to go back. Can this be fixed? Thanks

**Comment by ameshkov** [comment]
The text on that page depends on the domain category, it can be either "malware" or "phishing".

In this particular case, the website was reported as a malware.

**Comment by Nzzyme** [comment]
Exactly, which is incorrect and hence my post. The example link I provided and many others display as malware when they are phishing sites. Does this mean that when reporting sites, it needs to be specified whether it is a malware/phishing page. If so, then I am afraid that the issue is still observed.

Ex: "http://pelicanpanels.com" was reported on AG forums as being a phishing page but when I try to open it, I see the malware message.

**Comment by ameshkov** [comment]
> Does this mean that when reporting sites, it needs to be specified whether it is a malware/phishing page

Yes.

> Ex: "http://pelicanpanels.com" was reported on AG forums as being a phishing page but when I try to open it, I see the malware message.

This is wrong indeed, it was added to a wrong db then.

@zebrum plz, take a look.

**Comment by zebrum** [comment]
I've tried with different options - It's always the same malware warning page.

**Comment by Nzzyme** [comment]
Exactly, even for phishing sites, we see the warning page that says Malware. So instead can we have one standard warning page with text that covers everything - Malware, Phishing, etc. ?

**Comment by ameshkov** [comment]
Hmm, you've got a point. We'll need to change the text accordingly.

**Comment by ameshkov** [comment]
I'll keep that in mind -- we should handle it when new "access denied" pages markup is ready.

**Comment by Nzzyme** [comment]
ok, thank you

**Comment by Nzzyme** [comment]
@ameshkov : So is this planned to be fixed? It's been a year now and I still see the same message on blocked pages
