### ISSUE TITLE
High CPU usage on Edge

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardBrowserExtension#928]
### Steps to reproduce
1. Open a long (10+) list of tabs for a long time (24+ hours)
2. Enjoy a 30-50% CPU usage for Edge alone
3. Disable AdGuard extension
4. Voila, 0% CPU usage

### Expected behavior
Shouldn't cause high CPU usage

### Actual behavior
30-50% CPU usage

<details><summary>Screenshot:</summary>

![image001](https://user-images.githubusercontent.com/33634917/34432979-a868e414-ec84-11e7-8e9c-ee32566ba3d4.png)
with adg enabled

![image002](https://user-images.githubusercontent.com/33634917/34432992-b5098ffc-ec84-11e7-8216-2bc2487ffa46.png)
with adg disabled

</details>

### Your environment
* Adguard AdBlocker extension version: 2.7.2
* Environment name and version: (e.g. Chrome 59.0.3071.115): Microsoft Edge 42.17063.1000.0 / Microsoft EdgeHTML 17.17063
* Filters you use in Adguard: English, Spyware, Social media, Annoyances
* Any other browser extensions you have installed: none

**Comment by akmAa** [comment]
[AppSysLog.zip](https://github.com/AdguardTeam/AdguardBrowserExtension/files/1592813/AppSysLog.zip)
logs

**Comment by ameshkov** [comment]
Does it depend on what websites are opened?
