### ISSUE TITLE
"Thank you" page switches don't change the extension settings. [Legacy]

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardBrowserExtension#929]
2.8.2 legacy ext. 
Palemoon Version: 27.6.2 (64-bit

<details>

![image](https://user-images.githubusercontent.com/17472907/34439318-1834a3c6-ecbe-11e7-976e-7df40ac7a0b0.png)

![image](https://user-images.githubusercontent.com/17472907/34439326-20e72c64-ecbe-11e7-9e10-5c19df244f68.png)

</details>

**Comment by Mizzick** [comment]
Fixed
