### ISSUE TITLE
[Request] Palemoon 26 (Goanna) Support

### ISSUE THREAD

**Issue by bkrcrc** [AdguardTeam/AdguardBrowserExtension#93]
Hello,

Adguard will support this new codbase browser? Goanna is the new base of future Palemoon.
I need Adguard extension on it. Can you please look into it? Thanks
see : https://www.palemoon.org/WIP/

**Comment by LimboSlam** [comment]
More info about it can be found here: https://moonchildproductions.info/goanna.shtml and for webmasters/extension developers, please read this: https://forum.palemoon.org/viewtopic.php?f=24&t=9077.

**Comment by bkrcrc** [comment]
Thank you LimboSlam for more information that you gave to Adguard team :) I hope, we will recieve a reply from from them?

**Comment by ameshkov** [comment]
@bkrcrc have you tried current Palemoon add-on in Goanna?

@LimboSlam, thank you for the information!

**Comment by ameshkov** [comment]
@gshumihin please check how legacy.xpi works in Goanna

**Comment by bkrcrc** [comment]
@ameshkov, I upgraded my Palemoon stable to Palemoon 26 (based on Goanna)
Adguard works nice till now. If you want to try third beta of Palemoon 26 : ftp://ftp.palemoon.org/beta3/

**Comment by ameshkov** [comment]
@bkrcrc thank you!

**Comment by gshumihin** [comment]
I'll do full testrun today.

**Comment by gshumihin** [comment]
Everything is ok, except acceptable ads. Opened new issue #100
