### ISSUE TITLE
When is the new UI update?

### ISSUE THREAD

**Issue by Mancerrss** [AdguardTeam/AdguardBrowserExtension#930]
I see this [new interesting UI design concept](https://i.imgur.com/cGsUkkh.png) of the browser extension on the Adguard website. I tweeted on the Adguard Twitter about this and they said this looks like not to supposed to be only a concept but an upcoming design extension design update.

When that's really gonna ship. That looks modern, pretty and useful. That new Stats tab looks like useful and insightful

**Comment by ameshkov** [comment]
Hi!

In a couple of months.

The work is in progress in the `feature/redesign` branch, but we had to take a pause to implement a couple of important changes in the v2.x branch.
