### ISSUE TITLE
User filter rules are executed only upon page refresh

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardBrowserExtension#931]
> I am a user of your Adguard extension for Chrome Browser on Windows 10. I've recently come across a bug where, if I add a User-Filter of Javascript, e.g. "#%#AG_onLoad(function() " - It only executes upon page refresh (F5). Why is it not executing everytime I visit the page automatically? At the moment I'm targetting the root page only, and removing certain div. Then when I goto the pages with parameters, and return back to the root page its not executing the same onload.

ID: 1715896

**Comment by ameshkov** [comment]
It's hard to answer without knowing the exact rule and website.

Plz, ask him or her to supply the details.

**Comment by veronikasav** [comment]
Sorry, here is an update:
this is a test user filter which demonstrates the issue:

youtube.com#%#AG_onLoad(function() { if (location.pathname.length <= 1) { alert("home"); } else { alert("not in home"); } });

Actual Outcome / Problem: It's not executing this or any onLoad every page load, instead only does it if I do a page refresh like F5 on the keyboard.

Expected Outcome: Upon every page load it should execute the above javascript

**Comment by ameshkov** [comment]
Oh, this is simple. Youtube actually does not load a new page when you click any video link. It loads necessary data with an Ajax request and changes the page address using the History API.
