### ISSUE TITLE
Unable to turn the filtering off on specific websites

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardBrowserExtension#932]
1688649:

> when i turn off adguard on google or facebook it will still show that is on, it won't shut off, i turn it off close the slider and when i check back it does get green again and i can see the number of blocked ads on the icon (doesn't get gray), is there anything i should do?

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/34814813-b2976d06-f6b7-11e7-8c61-57990d58444c.png)

</details>

### Your environment

* Adguard AdBlocker extension version: 2.7.2
* Environment name and version: Opera
* Filters you use in Adguard: n/a
* Any other browser extensions you have installed: n/a

**Comment by ameshkov** [comment]
Cannot reproduce.

Suggested: reinstall the add-n
