### ISSUE TITLE
Beta 2.8.2 Doesn't save whitelist settings after reboot (Beta 2.8.1 works)

### ISSUE THREAD

**Issue by AjvarXX** [AdguardTeam/AdguardBrowserExtension#933]
### Steps to reproduce

1. Either import previously exported whitelist...
2. ... or simply switch slider off for specific site
3. Restart browser.
4.

### Expected behavior

Whitelist should have been stayed
### Actual behavior

Whitelist erazed and it filters on every site.

<details><summary>Screenshot:</summary>

</details>

<details><summary>Screenshot of the browser console:</summary>

</details>

### Your environment

* Adguard AdBlocker extension version: Beta 2.8.2
* Environment name and version: Waterfox 56.02
* Filters you use in Adguard: English 1.1.42.49. Russian 1.0.62.39. Adblock & uBlock polish filter 1.0.11.15. Adblock & uBlock polish filter - Adguard supplement 1.0.0.21.
* Any other browser extensions you have installed:
<details><summary>Addons:</summary>

<![addon list](https://user-images.githubusercontent.com/9568793/34886424-a2a29f46-f7cb-11e7-9de6-83b9a7769038.JPG)>

**Comment by ameshkov** [comment]
Reboot or just browser restart? Sounds rly weird, can you reproduce it with an empty profile?

**Comment by AjvarXX** [comment]
Browser restart. Problem reproduced again after I updated to *.2 again.
New profile doesn't seem to have this bug.
Affected profile was copypasted to FF52 ESR x86 and does not have this bug.
Will try FF56 x64 now.

**Comment by ameshkov** [comment]
Fixed
