### ISSUE TITLE
Element hiding exclusion can't be applied to iframe

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#934]
Extension 2.8.2 for Chrome
Iframe is not excluded by `@@||to.5swzc36gm3k.ru^$generichide`

Example URL (HDGO player)
http://itop-gear.ru/441-the-grand-tour-2-sezon-6-seriya-yaguary.html

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/34994634-d57ef018-fadc-11e7-8971-1a5f6261063a.png)

</details>

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/34994669-f7c79ed6-fadc-11e7-86f8-f9fbc8b5db2c.png)

</details>

**Comment by ameshkov** [comment]
Should be re-tested after #650 is finished

**Comment by Mizzick** [comment]
waiting for #847
