### ISSUE TITLE
Once in a while Adguard addon acts as if I just installed it opening welcome page + clearing whitelist

### ISSUE THREAD

**Issue by AjvarXX** [AdguardTeam/AdguardBrowserExtension#936]
This one might be a result of improper browser shutdowns due to BSODs so figure if report is valuable or not.
But it happened after updating to the latest WHQL.
Profile is basically fresh (over a week as I created it, synced tabs and history, installed addons).

### Steps to reproduce

1. Launch browser once in a while (happens once per day or per 2 days)
2. Perhaps a BSOD when browser was opened (happened few times)

### Expected behavior

nothing
### Actual behavior

New welcome tab opens with option to set settings
https://welcome.adguard.com/v2/thankyou.html?v=2.8.5&cid=Sf05ibBb37485573&lang=uk&id=adguardadblocker%40adguard.com&_locale=uk
Also whitelist is wiped
<details><summary>Screenshot:</summary>

</details>

<details><summary>Screenshot of the browser console:</summary>

![ctrlshiftj](https://user-images.githubusercontent.com/9568793/35231218-e041f946-ffa0-11e7-8d5c-3d781669da76.JPG)
</details>

### Your environment

* AdGuard AdBlocker extension version: 2.8.5
* Environment name and version: Waterfox 56.0.3
* Filters you use in AdGuard: 
* Any other browser extensions you have installed:
AdGuard Антибанер	2.8.5	true	adguardadblocker@adguard.com
Beyond Australis	1.4.8	true	thefoxonlybetter@quicksaver
Block site	1.1.9.0	true	{dd3d7613-0246-469d-bc65-2a3cc1668adc}
Disable WebRTC	1.0.18	true	jid1-5Fs7iTLscUaZBgwr@jetpack
FlashGot	1.5.6.14	true	{19503e42-ca3c-4c27-b1e2-9cdb2170ee34}
Form History Control (II)	2.0.3.2	true	formhistory@yahoo.com
Google Keep Notes	64.0.0	true	{a94d60a0-8408-4c53-8eec-cb349eb958b8}
Hide Caption Titlebar Plus ⁴	4.0.5	true	hidecaptionplus-dp@dummy.addons.mozilla.org
Hide Unwanted Results of Google Search	1.6	true	jid0-TpZJ4wPImlT1zIqfw58bD9vOeWQ@jetpack
HideScrollbars	1.1	true	Hidescrollbars@ArisT2Noia4dev
Hoxx VPN Proxy	2.2.2	true	@hoxx-vpn
MuteLinks	0.1.4	true	@mutelinks
New Tab Tools	86.2	true	newtabtools@darktrojan.net
OmniSidebar	1.6.15	true	osb@quicksaver
Stylus	1.1.7.8	true	{7a7a4a92-a2a0-41d1-9fd7-1e92480d612d}
YouTube High Definition	63.1.5	true	{7b1bf0b6-a1b9-42b0-b75d-252036438bdc}
Auto Unload Tab	0.9.1.5	false	{d3c46ca0-999d-11da-a72b-0800200c9a66}
Download Master	3.10.0	false	dm@westbyte.com
MEGA	3.16.1	false	firefox@mega.co.nz
ReminderFox	2.1.5.6	false	{ada4b710-8346-4b82-8199-5de2b400a6ae}
User Agent Overrider	0.5.2	false	useragentoverrider@qixinglu.com
User-Agent Switcher	0.2.0	false	{75afe46a-7a50-4c6b-b866-c43a1075b071}

**Comment by ameshkov** [comment]
WHQL?

**Comment by ameshkov** [comment]
> clearing whitelist

Are you sure it's just the whitelist and not the whole storage?

**Comment by ameshkov** [comment]
There should be some kind of a race condition causing that.

Got a couple more complains from ppl on other browsers.

**Comment by ameshkov** [comment]
@Mizzick @atropnikov 

Everything on the background page gets initialized before the storage is finished initializing.

Seems like a clear race condition to me.

**Comment by atropnikov** [comment]
@AjvarXX 
Could you please, when it will occur again, do the following: disable and enable AdGuard addon and see what happens. Will be settings loaded or stay default? 
Also please attach a content of the storage file. You can find it in your Firefox (Waterfox) Profiles folder. Something like this: `PATH TO BROWSER PROFILES FOLDER/Profiles/6w0somry.default/browser-extension-data/adguardadblockerbeta\@adguard.com/storage.js`
Thank you!

**Comment by AjvarXX** [comment]
Yes, looking at storage folder at least in my case it were BSODs that had influence on that. I see few .corrupt files. Strangly I didn't have problems with earlier addon versions, did it have a restore backed up storage.js feature? I will install *.3 Beta addon to test.
[adguardadblocker@adguard.com.zip](https://github.com/AdguardTeam/AdguardBrowserExtension/files/1655467/adguardadblocker.adguard.com.zip)

**Comment by ameshkov** [comment]
> did it have a restore backed up storage.js feature

Not really, there are no major changes between .3 and .4

**Comment by Mizzick** [comment]
Do we still have these problems?

**Comment by AjvarXX** [comment]
@Mizzick as long, as I went to stable PC (no BSODs) I had no more such problems.
I still suspect that previous version was more bsod-proof but doubtfully workload on unstable hardware should be a matter of concern for developers.

**Comment by Mizzick** [comment]
@AjvarXX thanks for your feedback anyway.
There were some problems on stable hardware aswell, but we didn't receive more complaints about, so I think the issue could be closed now.
