### ISSUE TITLE
Amazon search results pages break w/ adguard enabled

### ISSUE THREAD

**Issue by chuckreynolds** [AdguardTeam/AdguardBrowserExtension#937]
### Steps to reproduce

1. w/ AdGuard ON go to `amazon.com` and perform a search.
2. page initially loads to the fold, results after the fold are blank and scrolling causes pinwheel
3. Add `www.amazon.com` to whitelist, refresh, site loads fine.

### Expected behavior
Whatever is now being blocked on Amazon SERPS needs to be looked at so all results load 

### Actual behavior
page initially loads to the fold, results after the fold are blank and scrolling causes pinwheel

<details><summary>Screenshot:</summary>

<img width="1267" alt="screen shot 2018-01-22 at 13 51 20" src="https://user-images.githubusercontent.com/46185/35246400-6b427cf8-ff7b-11e7-86e1-8813d4ebddf4.png">

</details>

<details><summary>Screenshot of the browser console:</summary>

No errors show... but the timeline just continues to count... loads forever. race condition.

</details>

### Your environment
* AdGuard AdBlocker extension version: `2.6.5`
* Environment name and version: `Safari 11.0.2`
* Filters you use in AdGuard: `Safari filterVersion 1.0.4.10. Updated 18 january 2018 at 03:01.`
* Any other browser extensions you have installed: Ghostery but I completely disabled it for this debug sesh.

**Comment by ameshkov** [comment]
Could you please check it with the latest Safari beta (2.8.4)?

You can get it on the releases tab of the repo

**Comment by ameshkov** [comment]
Nvm, reproduced

**Comment by chuckreynolds** [comment]
glad you reproduced. just tried in `Safari Technology Preview`, `Release 47 (Safari 11.1, WebKit 12605.1.19.1)` and seems to load okay w/ Adguard on.

**Comment by ameshkov** [comment]
Confirmed, found the culprit.

Moved to the ExtCss repo:
https://github.com/AdguardTeam/ExtendedCss/issues/61

We'll disable these two problematic rules for Safari while figuring out what's wrong with them.

Marking this issue as duplicate as it was moved.

**Comment by ameshkov** [comment]
Thank you for reporting it!
