### ISSUE TITLE
AdGuard showing 'unsafe' alerts from private windows in public windows

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardBrowserExtension#939]
It doesn’t seem particularly safe when AdGuard opens ‘unsafe page alert’ windows from private windows in public windows, allowing users to continue to the URL via public mode.

Repro steps:
1. Install/Enable AdGuard browser extension 2.8.4
2. Open a private tab in Chrome/Opera (untested elsewhere)
3. In the private window, navigate to http://peppercash.ru 
4. Note AdGuard alert shows up in public window and allows you to "proceed" from the public window

**Comment by ameshkov** [comment]
As I recall, it should be pretty easy to fix

**Comment by Mizzick** [comment]
Cannot be fixed
Chrome doesn't allow open extension urls in incognito mode

**Comment by ameshkov** [comment]
Got it, this requires to use split-mode
