### ISSUE TITLE
Firefox extension stops working if user disables cookies

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#940]
It seems that disabling cookies prevents access to the extension's own localStorage and that breaks settings.

We should alert user if we detected a situation like that and provide an instruction:
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/940#issuecomment-365959933

**Comment by corvo7** [comment]
Hi:) We are waiting for the solution of the problem ...

**Comment by Mizzick** [comment]
It is possible to add our extension to cookies whitelist with `moz-extension://07ee6891-328a-e24f-a3b8-d1f4397d28b2` address.

**Comment by The-Commissioner** [comment]
I would still say it's a bug because other adblockers don't require cookies to work.

**Comment by ameshkov** [comment]
@The-Commissioner it's not about cookies, it is about `localStorage` and `indexedDB`, and this is a common practice to use both to store add-on settings.

**Comment by The-Commissioner** [comment]
Yes, I know. But what I'm saying is when I used the other adblocker, it didn't require cookies to work. They just work on indexedDB or localstorage.
If cookies is blocked for your extension, it fails to function.

**Comment by ameshkov** [comment]
Blocking cookies also blocks indexedDB and localStorage, that's the whole point -- user has disabled cookies and we ended up with localStorage and indexedDB that do not persist their state.

**Comment by The-Commissioner** [comment]
That's strange because i checked uBo and it uses indexedDB and it works without cookies all too well.
Regarding localstorage, wasn't it mentioned in one of the issue that it isn't a preferred mode of storage by a firefox dev?
So, that brings out the question why you need cookies when you're not providing any extra features(rather less) than the alternatives?
I guess a little rework is needed here.

**Comment by The-Commissioner** [comment]
> Regarding localstorage, wasn't it mentioned in one of the issue that it isn't a preferred mode of storage by a firefox dev?

Pardon me the localstorage discussion was in a ublock thread and not mentioned here in AG repo: https://github.com/gorhill/uBlock/issues/2925

**Comment by ameshkov** [comment]
That's not about localStore, this is about another entity -- "browser.storage"

**Comment by The-Commissioner** [comment]
Ok but still doesn't answer what do you do extra that it requires extra permissions?

**Comment by ameshkov** [comment]
As I can see, uBO also uses indexedDB. It may not look like it's broken, but it actually is -- filters content and caches aren't persisted and loaded from defaults every time. Actually, I think that both ways are not okay.

We'd better let users know that one of the components is not working as it should, and provide an instruction.

**Comment by The-Commissioner** [comment]
> filters content and caches aren't persisted and loaded from defaults every time.

Strange that doesn't happen here.

**Comment by ameshkov** [comment]
You can't see it, but if you debug it and find indexedDB usages, you'll see what I am talking about.

**Comment by Mizzick** [comment]
So, do we need to show some warning to user in case cookies are disabled?

**Comment by Mizzick** [comment]
No longer reproducable with FF 59
