### ISSUE TITLE
Group Policy - Force Chrome Extension Installation 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardBrowserExtension#942]
I’m attempting to test deploy your AdGuard extension for Chrome (Windows), using Group Policy. According to Google, “Each list item of the policy is a string that contains an extension ID and an "update" URL separated by a semicolon (;). The extension ID is the 32-letter string found e.g. on chrome://extensions when in developer mode. The "update" URL should point to an Update Manifest XML document as described at https://developer.chrome.com/extensions/autoupdate. Note that the "update" URL set in this policy is only used for the initial installation; subsequent updates of the extension employ the update URL indicated in the extension's manifest.”

For example: `gbchcmhmhahfdphkhkmpfmihenigjmpp;https://clients2.google.com/service/update2/crx` installs the Chrome Remote Desktop app from the standard Chrome Web Store "update" URL.

I was able to obtain the extension ID, but am unsure how to obtain the “update” URL to deploy the Chrome extension. Are you able to assist with this issue?

More Information can be found at under “ExtensionInstallForcelist”
http://dev.chromium.org/administrators/policy-list-3#ExtensionInstallForcelist

 ID: 1732987

**Comment by ameshkov** [comment]
Sorry for the late reply.

The update URL is the same for all extensions from Chrome Web Store: `https://clients2.google.com/service/update2/crx`
