### ISSUE TITLE
CSP rule doesn't work properly in Edge

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardBrowserExtension#943]
http://ex-fs.net/show/69752-discovery-bitvy-robotov.html

video is blocked by ws rule in edge browser

more details here: https://github.com/AdguardTeam/AdguardFilters/issues/10630

**Comment by Alex-302** [comment]
Revert this change after fixing
https://github.com/AdguardTeam/AdguardFilters/commit/69e3d1fe96db11907ea8f6b85d3e87a3fd25f7c1

**Comment by 4-life** [comment]
This rule is incompatible with the Edge browser because edge is used blobs for websockets in ther hls player
