### ISSUE TITLE
Unable to stop protection in Vivaldi 1.14, AdGuard 2.8 for Chrome

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardBrowserExtension#944]
Vivaldi 1.14.1077.45, AdGuard 2.8 from the Chrome store

### Steps to reproduce

1. Toggle AdGuard extension so that it stops filtering on a website
2. Refresh the page
3. Go to the extension's settings, see it running

### Expected behavior

AdGuard stops filtering on a particular site when configured accordingly

### Actual behavior

It continues filtering the website despite your previous actions. The fact that the number of blocked ads shows up only when you disable protection is also weird

<details><summary>Screenshot:</summary>

 
![giphy](https://user-images.githubusercontent.com/15856304/35862308-e8452bc2-0b53-11e8-8313-ff6eed905327.gif)

https://uploads.adguard.com/Screencast_2018-02-06.mp4

</details>

### Your environment

* AdGuard AdBlocker extension version: 2.8
* Environment name and version: Vivaldi 1.14.1077.45
* Filters you use in AdGuard: English, Russian, Social media, Spyware, Mobile ads, Annoyances
* Any other browser extensions you have installed: none

**Comment by ameshkov** [comment]
This is a known bug of Vivaldi
