### ISSUE TITLE
HTML filtering rules disappear from the user filter if page is refreshed too early

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#947]
Steps to reproduce:
1. Add content filtering `$$` rule. For example
`$$script[wildcard="*(function*String.fromCharCode(parseInt*.substr*"][max-length="7200"]`
2. Refresh the tab of extension.
Actual behavior:
the rule is absent

After restarting the browser the rule is visible.

Firefox 58.0.2 x64

**Comment by Mizzick** [comment]
Reproduced in Chrome aswell

**Comment by Mizzick** [comment]
```
2018-02-12T13:04:22.265Z: Cannot create rule from filter 0: $$script[wildcard="*(function*String.fromCharCode(parseInt*.substr*"], cause Content rule must have at least one permitted domain
```

**Comment by Mizzick** [comment]
`example.org$$script[wildcard="*(function*String.fromCharCode(parseInt*.substr*"][max-length="7200"]`
works fine
