### ISSUE TITLE
Network blocked requests are not collapsed

### ISSUE THREAD

**Issue by The-Commissioner** [AdguardTeam/AdguardBrowserExtension#949]
AG 2.8.5 Beta
Firefox
w10 x64

Block youtube for ghacks.net
GO to this page: https://www.ghacks.net/2018/02/09/apply-custom-colors-to-your-windows-explorer-folders-with-folder-colorizer-2/
The iframe is not collapsed.

**Comment by ameshkov** [comment]
The cause of that: AG does not collapse frames that are likely to be used as embedded players. We should do it in the case when the request to that frame is blocked.

**Comment by The-Commissioner** [comment]
ameshkov in 2016 said:-

> Hm, for some reason "iframe" elements are not removed from the page code.
As I recall we do this because of the possible issues with the "frameset" elements.
The question is: why do we do this for all "iframe" elements while we could easily check if there is a frameset or not.

Was solved in windows repo but not in extension repo.

**Comment by ameshkov** [comment]
Oh, this one is different. Browser extension is able to collapse frames, but there's an explicit exception for frames that are likely to be used for video players.

**Comment by ameshkov** [comment]
Resolved as part of #847
