### ISSUE TITLE
Not all images are picked by extension

### ISSUE THREAD

**Issue by The-Commissioner** [AdguardTeam/AdguardBrowserExtension#950]
AG 2.8.5
Firefox
W10 x64

The extension is not able to pick up all the images.
One of the e.g is the sign in prompt that you get when you visit https://github.com/AdguardTeam/AdguardBrowserExtension

It's not able to pick the image, Block element option in right context menu is not present.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdguardAssistant #214](https://github.com/AdguardTeam/AdguardAssistant/issues/214) via [**ZenHub**](https://www.zenhub.com/)
