### ISSUE TITLE
Make extension friendly for visually impaired users

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardBrowserExtension#953]
> Улучшете, пожалуйста, доступность дополнения AdGuard для браузеров.
> Надо всего лишь сделать кнопки в настройках флажками, там, где выбор опций, где предпологается, что надо выбрать опцию и активировать её или нет, там не озвучивается

### Your environment

* AdGuard AdBlocker extension version: 2.8
* Environment name and version: Firefox, Chrome
* Filters you use in AdGuard: n/a
* Any other browser extensions you have installed: n/a

**Comment by ameshkov** [comment]
We should re-test it in v3.0 as it's fully re-designed.

**Comment by yastrebilya2018** [comment]
Hello!
It's nice that the developments make the add-on and the app better for all categories of users.
Tell please,and when will v3.0 browser extension?
Thanks for the reply in advance.

**Comment by ameshkov** [comment]
It'll be finished in coming months. Rather close I'd say

**Comment by karina-archazh** [comment]
@maximtop @kaprielov please check how voice over playback setting page in Chrome and FF

**Comment by zzebrum** [comment]
@yastrebilya2018 здравствуйте! Скажите, какой скринридер вы используете и какая у вас операционная система на компьютере?

**Comment by yastrebilya2018** [comment]
Здравствуйте!

windows 7 x 64

nvda 2018.4.1

проблемы проявляются в браузерах google hrom и Firefox.

14.01.2019 17:00, zzebrum пишет:
