### ISSUE TITLE
Unify the publisher name

### ISSUE THREAD

**Issue by sergerosenthaler** [AdguardTeam/AdguardBrowserExtension#954]
As I mentioned earlier. You're using different publisher names on different plattforms. There you're promoting and selling a security software, you should unify the publisher name to "AdGuard Software Limited" on every platform (Google Chrome Web Store, Firefox Add-Ons, Safari Gallery Extension, Microsoft Store, AppStore, Google Play Store). Hypothetically speaking, would you trust a company that promotes a security-software under the developer name "Andrey Meshkov"?

**Comment by ameshkov** [comment]
Hm-hm, that's a good question. AMO does not provide a "corporate" account or whatnot, and that's why the extension is submitted from my personal account.

Although, we can rename it to AdGuard. I'll check the AMO rules and what should be done for that.

**Comment by sergerosenthaler** [comment]
Check out other security product developers, they use the same name in every store. Makes a more streamlined and professional impression.

On the Apple AppStore you're still distribute the product under Performix. Sorry but where is the link to AdGuard Software Limited? A name change can be done by contacting Apple https://developer.apple.com/support/account/

**Comment by ameshkov** [comment]
@sergerosenthaler I've paused renaming until v2.0 release. The renaming process will take at least a couple of weeks and during this period we won't be able to publish anything.

**Comment by sergerosenthaler** [comment]
Cool, I'm sure it makes the overall experience more professional. And don't take it personal:-) This was only to illustrate what I have meant. I take care what I'm downloading and from what source. Especially on the Google side there is a lot of garbage in the stores.

**Comment by ameshkov** [comment]
It makes perfect sense indeed, thank you:)

**Comment by ameshkov** [comment]
1. Updated the account name on AMO to `Adguard Software Ltd`;
2. Chrome WebStore: updated dev name to `Adguard Software Ltd` in the account settings;
3. Safari -- we need to wait for the new update to see if they pick up the company name;
4. MS Edge -- tbh, I am afraid of touching anything there, the dev dashboard is very unstable. I'll try to contact their support.
5. Addons.opera.com -- will do
