### ISSUE TITLE
Add manual filter update button in pop-out menu

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardBrowserExtension#958]
As requested by user #1765396,

> "Хотел бы предлоить вынести "Проверить обновление фильтров" в браузере во 
> всплывающее меню рядом с адресной строкой, например, под "Фильтрация на 
> этом сайте". По крайней мере, я несколько раз столкнулся с ситуацией, 
> когда это было бы очень удобно."

en:

> "It'd be great if you could add the "Check filter updates" button in the extension's pop-out menu. I've encountered several situations where it would be very convenient to do so."

**Comment by vozersky** [comment]
@akmLaVx 
можно нажать правой кнопкой мыши на иконку расширения, в меню есть обновление фильтров
![image](https://user-images.githubusercontent.com/17472907/36434069-2e79e06c-166f-11e8-91ca-747ac22755f7.png)

**Comment by vushe** [comment]
Для этого надо Мак покупать?

![image](https://user-images.githubusercontent.com/15868217/36541067-65db280a-17e5-11e8-944e-44335bae9c5a.png)

**Comment by vushe** [comment]
Спасибо за информацию!
Долго ломал голову, почему у меня не так. 

Оказывается, это работает только при включенной опции
"Add AdGuard item to browser's context menu".

По-моему, не очень удобно. Но, в любом случае, хорошо что есть.
