### ISSUE TITLE
The issues with content filtering rules in Firefox

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#959]
* Original issue
https://github.com/AdguardTeam/AdguardFilters/issues/10834#issuecomment-366604062

This rule breaks some styles
`e.mail.ru$$script[tag-content="patron.radar("adblock_detect-by""][max-length="1000"]`
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/36432993-2efe989e-1664-11e8-8666-629f9ab63009.png)

</details>

**Comment by AdamWr** [comment]
Another examples:
https://github.com/AdguardTeam/AdguardFilters/issues/11892
`speedtest.net$$div[class="dfp-ab-leaderboard"]`
and
https://github.com/AdguardTeam/AdguardFilters/issues/11394#issuecomment-365273250
`dcinside.com$$script[tag-content="function adBlockDetected()"]`

**Comment by Mizzick** [comment]
I guess we cannot control it. If you are removing some elements from layout, there is no guarantees that the rest will stay on its place. I mean, it's the same situation as with element hiding rules, if you remove something, all the rest could be messed.

**Comment by ameshkov** [comment]
The point is that for some reason it works differently in the Win/Mac versions and in the FF extension.

I suppose we may be damaging HTML in FF, and we need to find out how exactly.

Here's what you need to do:
1. Use this rule in AG for Win/Mac and in FF extension
2. Compare the resulting output (I guess you'll need to log what you've got)

**Comment by Mizzick** [comment]
Okay, I got it finally!
Content edited page lost `<DOCTYPE ..>`

**Comment by ameshkov** [comment]
++
