### ISSUE TITLE
Cannot disable ad blocking in Tor Browser

### ISSUE THREAD

**Issue by suhan3z** [AdguardTeam/AdguardBrowserExtension#96]
Disable filtration on page by checkbox, checkbox change state, but after refresh filtration continued.
Expected: filtration stops

**Comment by ameshkov** [comment]
The problem is that getChannelContextData returns null in case of Tor Browser

**Comment by atropnikov** [comment]
Fixed in https://github.com/AdguardTeam/AdguardBrowserExtension/issues/47
