### ISSUE TITLE
Switch to integration mode without desctop software

### ISSUE THREAD

**Issue by Rostov114** [AdguardTeam/AdguardBrowserExtension#964]
Hello.

AdGuard goes into the integration mode without installed Adguard for Windows, when sending the header:

`x-adguard-filtered: Adguard for Windows; version=6.2.437.2171`

Demo: http://dev.rostov114.ru/adguard/gotointegration.php

This specialty is already used by sites:

https://www.drive2.ru
http://www.mk.ru

In advance detect installed Adguard extension.

Demo detect ad blocking, up to detect extension type: http://dev.rostov114.ru/adguard/checkblocker.html

OS: Windows 7 x64
AdGuard AdBlocker extension version: 2.8.4
Environment name and version: Chrome 64.0.3282.186

**Comment by ameshkov** [comment]
Yep, we're aware of it, will be resolved soon: #963

**Comment by ameshkov** [comment]
Resolved, updated version is published to both AMO and Chrome WebStore
