### ISSUE TITLE
App title not translated to German and German description in the Microsoft Store not reflecting the new name AdGuard 

### ISSUE THREAD

**Issue by sergerosenthaler** [AdguardTeam/AdguardBrowserExtension#969]
![2018-03-08_13-13-32](https://user-images.githubusercontent.com/25068100/37150755-3156cbd6-22d3-11e8-9723-c5ad6e1a229d.png)

**Comment by sergerosenthaler** [comment]
@ameshkov maybe it would be better to use "AdGuard - Werbeblocker" in all stores this reflects the wording used for iOS and other platforms. What do you think?

**Comment by ameshkov** [comment]
With this naming `AdGuard AdBlocker` we were trying to somehow differentiate it from the desktop versions which are simply `AdGuard for [OS name]`.

**Comment by sergerosenthaler** [comment]
@ameshkov Okay, got it. So for the browser extensions „AdGuard Werbeblocker“:-)

**Comment by ameshkov** [comment]
Yup:)
