### ISSUE TITLE
AdGuard settings are not fully visible when accessing them from the overflow menu

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardBrowserExtension#970]
### Steps to reproduce

1. Install Firefox Quantum with the new overflow menu feature (58.0.2 for Mac in my case)
2. Install AdGuard 2.8
3. Right-click on the AdGuard icon in the bar and put it to the overflow menu
4. Click on the menu, click on AdGuard - the right side is cut

### Expected behavior

The settings screen is not cut

### Actual behavior

<details><summary>Screenshot:</summary>

<img width="429" alt="screen shot 2018-03-11 at 11 51 58" src="https://user-images.githubusercontent.com/15856304/37281143-b6efb492-25f8-11e8-84bb-58e14e33043f.png">

</details>

### Your environment

* AdGuard AdBlocker extension version: 
* Environment name and version: 58.0.2
* Filters you use in AdGuard: 2.8, 2.8 beta
* Any other browser extensions you have installed: none

**Comment by karina-archazh** [comment]
After adding the AG extension in the overflow menu, a white bar appears.
https://monosnap.com/file/sWu8dZSuvoYx9dWgu6TiHAZzWB9CRH
