### ISSUE TITLE
Blokeador para crome

### ISSUE THREAD

**Issue by oswaltalvaradolopez** [AdguardTeam/AdguardBrowserExtension#971]
### Steps to reproduce

1.
2.
3.
4.

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

<details><summary>Screenshot of the browser console:</summary>

</details>

### Your environment

* AdGuard AdBlocker extension version: 
* Environment name and version: (e.g. Chrome 59.0.3071.115)
* Filters you use in AdGuard:
* Any other browser extensions you have installed:
#970 #969 #968

**Comment by zebrum** [comment]
If you have a problem, please submit the detailed description using the template.
