### ISSUE TITLE
Assistant menu should save its position on page

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardBrowserExtension#973]
@zebrum commented on [Tue Mar 13 2018](https://github.com/AdguardTeam/AdguardAssistant/issues/197)

STR:
1. Load any page, run Assistant 
2. Choose element to block
3. Move Assistant menu to other place on the page
4. Press 'Preview' button

Actual behavior: Assistant menu returns to left top corner.

Expected behavior: Assistant menu stays were user place it.

**Comment by 4-life** [comment]
Assistant menu position based on assistant button position.
