### ISSUE TITLE
Assistant's "select another element" is too slow

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#977]
https://uploads.adguard.com/up04_k0gn4_BitTorrent_treker_RuTracker.org.png

As if you're re-injecting the code on "select another element" click. Please check what's wrong with it.

**Comment by ameshkov** [comment]
Hm, seems to be a false alarm, but plz check it just in case.

**Comment by 4-life** [comment]
Don't see anything like this
