### ISSUE TITLE
Some regex rules don't work

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/AdguardBrowserExtension#978]
### Steps to reproduce

1. Add this rule to user filter - `/^https?/`
2. Go here - http://oke.io/e9x4Fk0b

### Expected behavior

HTTP and HTTPS requests should be blocked
### Actual behavior

HTTP requests are not blocked

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29142494/37490319-9a946f14-289a-11e8-96bf-35d01ed6bb72.png)

</details>

### Your environment

* AdGuard AdBlocker extension version: 2.8.6
* Environment name and version: Chrome 65.0.3325.162
* Filters you use in AdGuard: English
* Any other browser extensions you have installed: -

**Comment by ameshkov** [comment]
Resolved in `pull-requests/100`
