### ISSUE TITLE
Link all phrases with a screenshot in oneskyapp

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#98]
1. Go to adguard.oneskyapp.com
2. Open the full list of phrases:
https://adguard.oneskyapp.com/collaboration/translate/project/project/13698/language/1#/

3. Look for phrases not linked with a screenshot

4. Open the list of screenshots:
https://adguard.oneskyapp.com/admin/screen/list/project/13698

Find corresponding screenshot (or upload if there's no such) and tag the phrases there.

**You can have one phrase tagged on multiple screenshots. Actually, you should do it if that phrase is used on more than one place.**

**Comment by Mizzick** [comment]
Fixed
