### ISSUE TITLE
Oswaltalvarado33@gmail.com 

### ISSUE THREAD

**Issue by oswaltalvaradolopez** [AdguardTeam/AdguardBrowserExtension#982]
### Steps to reproduce

1.
2.
3.
4.

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

<details><summary>Screenshot of the browser console:</summary>

</details>

### Your environment

* AdGuard AdBlocker extension version: 
* Environment name and version: (e.g. Chrome 59.0.3071.115)
* Filters you use in AdGuard:
* Any other browser extensions you have installed:

**Comment by oswaltalvaradolopez** [comment]
Crome

**Comment by ameshkov** [comment]
Please file a bug report properly, I don't understand what's that about.

Also, don't leave your email, it is publicly visible here.
