### ISSUE TITLE
nyafilmer.bz many ads and badges

### ISSUE THREAD

**Issue by cabban** [AdguardTeam/AdguardBrowserExtension#985]
### Steps to reproduce

1.
2.
3.
4.

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

<details><summary>Screenshot of the browser console:</summary>

</details>

### Your environment

* AdGuard AdBlocker extension version: 
* Environment name and version: (e.g. Chrome 59.0.3071.115)
* Filters you use in AdGuard:
* Any other browser extensions you have installed:
newest chrome
newest version of chrome
![image](https://user-images.githubusercontent.com/19514493/38028324-e75602e8-3292-11e8-9a13-aaa2d01a7586.png)

ads and pop up . ladda ner and titta nu  is take os to spam hope u could fix :)

**Comment by ameshkov** [comment]
Report it to https://agrd.io/report please
