### ISSUE TITLE
some sites is blocking me to view cause of the adblock 

### ISSUE THREAD

**Issue by cabban** [AdguardTeam/AdguardBrowserExtension#986]
### Steps to reproduce

1.
2.
3.
4.

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

<details><summary>Screenshot of the browser console:</summary>

</details>

### Your environment

* AdGuard AdBlocker extension version: 
* Environment name and version: (e.g. Chrome 59.0.3071.115)
* Filters you use in AdGuard:
* Any other browser extensions you have installed:

![image](https://user-images.githubusercontent.com/19514493/38028383-11137a2a-3293-11e8-960e-39b1219b5ec2.png)

**Comment by ameshkov** [comment]
Report it to https://agrd.io/report please
