### ISSUE TITLE
[Feature Request] Build Reporting Tool Into Add On

### ISSUE THREAD

**Issue by zero77** [AdguardTeam/AdguardBrowserExtension#993]
Can you please build the reporting tool into the add on, where it can automatically grab as much info as possible, and asks users for info if any moor is still needed.
Thanks

**Comment by evgeniy-ADG** [comment]
The tool is available in the extension since v. 2.8

![image](https://user-images.githubusercontent.com/15856304/38142432-f02d7f50-3444-11e8-93be-1a19b8b1d223.png)

**Comment by zero77** [comment]
Thanks, but I was meaning something a bit more comprehensive, something that automatically fills in a bit more info.

Mabey something as part of the element blocker.

**Comment by ameshkov** [comment]
> Thanks, but I was meaning something a bit more comprehensive, something that automatically fills in a bit more info.

But it is filling most of the info (save for the screenshot). Isn't it in your case?

**Comment by zero77** [comment]
Yes, a lot is filled out for me but, I think it would improve things if it was built into the add on, and doesn’t even have to leave the page. 

Also, would it be possible for Adguard browser extension to automatically fill in these as well.


>Please check AdGuard for filter updates. Does the issue persist?

By checking the date of the last update, and if needed running an update and then refreshing the page.

>Please disable User filter. Does the issue persist?

>What filters do you have enabled? Select any default filters from the list or enter URLs for any custom filters.

Could this info automatically be found by the add on as well.

**Comment by ameshkov** [comment]
> By checking the date of the last update, and if needed running an update and then refreshing the page.
> Could this info automatically be found by the add on as well.

The point is that the user is the only one who can tell if the problem is fixed or not.

**Comment by karina-archazh** [comment]
Hi, 

do you have any update for this issue?
