### ISSUE TITLE
Warning Page Appears Twice

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardBrowserExtension#995]
### Steps to reproduce
1. Open the link "dicountforu.com"
2. AG shows the warning page twice in two different tabs.

### Expected behavior
Warning page should be shown in the same tab only once.

### Actual behavior
Warning page opens in two different tabs.

Screenshot: http://prntscr.com/iyu14k

### Your environment

* AdGuard AdBlocker extension version: 
* Environment name and version: Chrome 65.0.3325.181 (Official Build) (32-bit)
* Filters you use in AdGuard: English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled]
* Any other browser extensions you have installed: N/A

**Comment by Nzzyme** [comment]
I suppose this is resolved? Can you confirm?

**Comment by zebrum** [comment]
@Nzzyme yeap.
