### ISSUE TITLE
nyafilmer.bz is having problem with pop up 

### ISSUE THREAD

**Issue by cabban** [AdguardTeam/AdguardBrowserExtension#996]
### Steps to reproduce

1.
2.
3.
4.
tap video player play button
### Expected behavior

paly video
### Actual behavior

pop up every longer pause or first time tap
<details><summary>Screenshot:</summary>

</details>

<details><summary>Screenshot of the browser console:</summary>

</details>

### Your environment

* AdGuard AdBlocker extension version: 
* Environment name and version: (e.g. Chrome 59.0.3071.115)
* Filters you use in AdGuard:
* Any other browser extensions you have installed:
it is like jawacloud.co, is having same ads in every player on streamingsites, happy to see a fix to block, then all togheter :) 

@Alex-302

**Comment by Alex-302** [comment]
@cabban wrong repository.
Please move to https://github.com/AdguardTeam/AdguardFilters/issues
