### ISSUE TITLE
GPU / video glitches with Safari AdGuard

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardBrowserExtension#998]
### Description

> I have a really strange problem with AdGuard AdBlocker Safari extension. Under certain conditions with certain videos on Twitch TV, the video starts flashing, showing GPU artifacts and sometimes cause the system to freeze. The problem is immediately fixed upon removing the AdGuard extension and rebooting and is introduced once AdGuard is installed and the page reloaded. This is what I mean:

- https://www.youtube.com/watch?v=gEiCgtrasNs
- https://www.youtube.com/watch?v=E_0p5iKnZAc

### Conditions

> 1. Only saw this happen with certain Twitch TV videos, for example:  https://www.twitch.tv/videos/243932818
> 3. Video quality set to “source”, full-screen mode and no web UI elements must be visible (e.g., video player’s UI at the bottom), just the video.
> 4. Probably related to certain Apple laptop model(s) and OS.
> 
> I don’t have any video or GPU issues anywhere else, which makes me think this is software related (but I guess it still could be hardware), especially since it starts the moment AdGuard is installed and the page refreshed / Safari restarted) and then fixed once the extension is removed. I tried this about 4 times.

### ID
1818530

### Your environment

- MacBook Pro 13 early 2015, 2.7 GHz, 16 GB 
- macOS 10.13.04, fresh installation 
- Safari 11.1
- AdGuard extenson 2.8..4

**Comment by EnergiaBuran** [comment]
I have the same problem also with "adblock ultimate". So, unless this is a hardware issue, whatever it is, it's probably not related to AdGuard code, but perhaps to Safari and macOS.
