### ISSUE TITLE
"Block ads" tool's buttons are displaced

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardBrowserExtension#999]
### Steps to reproduce
1. Open gmail.com
2. Try to block hangouts div
3. Click on "Advanced settings"

### Actual behavior
"Select another element" "preview" and "block" Buttons are displaced

### Screenshot

https://uploads.adguard.com/up05_wzaxg.png

### Your environment

* AdGuard AdBlocker extension version: 2.9.2
* Chrome  65.0.3325.181

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdguardAssistant #207](https://github.com/AdguardTeam/AdguardAssistant/issues/207) via [**ZenHub**](https://www.zenhub.com/)
